### PR TITLE
refactor(execution): get_tx_weights for the bouncer

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1671)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1671)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-NsxHXviEiDE1LDlijNu:-NsxHXvjB-6SL4gyJfWB:bv5u5em) ([raw file](https://github.com/starkware-libs/blockifier/blob/7aad9f2a35ed0e03d21e7cf598f0189319ffddaa/crates/blockifier/src/bouncer.rs#L72)):*
> ```XML
>         state_diff_size
>     );
> }
> ```

According to @giladchase, the simple `impl` block should be the highest



_Code quote:_
```XML
impl From<ExecutionResources> for BouncerWeights {
    fn from(data: ExecutionResources) -> Self {
        BouncerWeights {
            n_steps: data.n_steps + data.n_memory_holes,
            builtin_count: data.builtin_instance_counter.into(),
            ..Default::default()
        }
    }
}

impl BouncerWeights {
    impl_checked_sub!(
        builtin_count,
        gas,
        message_segment_length,
        n_events,
        n_steps,
        state_diff_size
    );
}
```
___
*[`crates/blockifier/src/bouncer.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-NsxHtiADji686susN7G:-NsxHtiADji686susN7H:bb73xfv) ([raw file](https://github.com/starkware-libs/blockifier/blob/7aad9f2a35ed0e03d21e7cf598f0189319ffddaa/crates/blockifier/src/bouncer.rs#L87)):*
> ```XML
> }
> 
> impl From<HashMapWrapper> for BuiltinCount {
> ```

Same
___
*[`crates/blockifier/src/blockifier/bouncer.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-NsxI4QBDuzPLKPidIOA:-NsxI4QBDuzPLKPidIOB:b-su5rse) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5c4339b6bccde43e46746aee86fcb789faf79b7/crates/blockifier/src/blockifier/bouncer.rs#L28)):*
> ```XML
>         n_events: usize,
>     ) -> TransactionExecutionResult<Self> {
>         // TODO(Avi, 30/03/2024): Consider removing "l1_gas_usage" from actual resources.
> ```

Keep this TODO



_Code quote:_
```XML
/ TODO(Avi, 30/03/2024): Consider removing "l1_gas_usage" from actual resources.
```

**Review by Yael-Starkware — COMMENTED** [review]
Context:
In high level , the bouncer update function (previously known as add() in python) will proceed in the following steps:
1. update_auxiliary_info
2. update_capacity (BouncerWeights)
    a. get_tx_weights  - This PR
    b. check if keccak was used and update the capacity accordingly
    c. try to update the bouncer by subtracting the tx_weights
        if succeeds -> commit the new values, OK
        else  -> keep the old bouncer values, Error

Code:
1. The main function here is get_tx_info. This function gets information from the execution info and state and computes the weights that this transaction will add to the bouncer weights (represented by BouncerWeights struct).
2. I had to reformat the ExecutionResources struct into BouncerWeights struct so a from trait was added.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-:-NtFGpRQ48dS4gS8XTE8:b-g25oek)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @Yoni-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
The logic should be exactly the same as computed in transaction_executor execute function for the bouncer_info that is sent to the python code. So if you have any doubts about something you cam compare with that. (and also talk to me)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-:-NtFLUMYDydsBRH-XW3H:bvv30kh)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @Yoni-Starkware)

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1671)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @giladchase, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-NtKTEZ_A7XJZ1Q30fPs:-NtKTEZ_A7XJZ1Q30fPt:bmkfzk6) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ecbe735a3813be9614d00a84dce776a77ce80f/crates/blockifier/src/bouncer.rs#L95)):*
> ```XML
>     fn from(mut data: HashMapWrapper) -> Self {
>         let builtin_count = Self {
>             bitwise: data.remove(BuiltinName::bitwise.name()).expect("bitwise must be present"),
> ```

We can allow `data` to be more flexible.



_Suggestion:_
```XML
data.remove(BuiltinName::bitwise.name()).unwrap_or(0)
```
___
*[`crates/blockifier/src/bouncer.rs` line 255 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-NtKSY7nEMVK7Vyc_5wn:-NtKSY7nEMVK7Vyc_5wo:b-u3ufkc) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ecbe735a3813be9614d00a84dce776a77ce80f/crates/blockifier/src/bouncer.rs#L255)):*
> ```XML
> 
> /// Calculates the L1 resources used by L1<>L2 messages.
> /// Returns the total message segment length and the L1 gas usage.
> ```

Please update.



_Code quote:_
```XML
/// Calculates the L1 resources used by L1<>L2 messages.
/// Returns the total message segment length and the L1 gas usage.
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1671)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-NtKTEZ_A7XJZ1Q30fPs:-NtKgh0y62LAaXEHRn1U:b-m4naz4) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ecbe735a3813be9614d00a84dce776a77ce80f/crates/blockifier/src/bouncer.rs#L95)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We can allow `data` to be more flexible.
</blockquote></details>

This was in discussion previously, the improvement was to make data less flexible and panic in case it is not what we expected. Since we actually don't expect this vector to deviate from what we think should be in it.
FYI there is an incoming refactor that is transforming this vector to a well defined struct as well ( @Yoni-Starkware correct me if I'm wrong).
___
*[`crates/blockifier/src/bouncer.rs` line 255 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-NtKSY7nEMVK7Vyc_5wn:-NtKhOPHA0PqOoj_3v-a:b-bgr02v) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ecbe735a3813be9614d00a84dce776a77ce80f/crates/blockifier/src/bouncer.rs#L255)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please update.
</blockquote></details>

not sure I understand , what is missing?

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/bouncer.rs` line 255 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-NtKSY7nEMVK7Vyc_5wn:-NtKi6rO8Ihl2Cchymql:bk3t2m7) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ecbe735a3813be9614d00a84dce776a77ce80f/crates/blockifier/src/bouncer.rs#L255)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure I understand , what is missing?
</blockquote></details>

/// Returns the total message segment length and the gas weight.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1671)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 255 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-NtKSY7nEMVK7Vyc_5wn:-NtKja-sBdUKKHrHC0Oz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ecbe735a3813be9614d00a84dce776a77ce80f/crates/blockifier/src/bouncer.rs#L255)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

/// Returns the total message segment length and the gas weight.
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-:-NtKkM9WB07-kWGJtLzZ:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1671)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1671#-:-NtMBLSlExCI2AQlnUKY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
