### PR TITLE
test(concurrency): add ERC20 cairo 1 contract for testing

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-NxHDdXEDfmYhzaTYvBT:-NxHDdXEDfmYhzaTYvBU:b9ci1h1) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6757cf4b0fec64687092f0b79946e051c2e5f95/crates/blockifier/src/concurrency/fee_utils_test.rs#L25)):*
> ```XML
>         version: TransactionVersion::THREE
>     });
>     let chain_info = &block_context.chain_info;
> ```

It might be a good idea to create a function out of this code, which would make it easier if another test wants to use cairo1 erc20 later.

**Review by Yoni-Starkware — COMMENTED** [review]
Where did you find this contract?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-:-NxMBpBA75r5uGwej5Ru:b-wvth2m)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
I used the casm you sent in our chat this https://alpha-mainnet.starknet.io/feeder_gateway/get_compiled_class_by_class_hash?classHash=0x7f3777c99f3700505ea966676aac4a0d692c2a9f5e667f4c606b51ca1dd3420 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-:-NxMyIli3u2cTgyVtbX_:b-xgu3bx)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
Oh :) 
so please rename the file to erc20.casm.json

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-:-NxMz79aAyHdbbJfpyWk:bdygskf)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-NxN-cQ88-Pyd_7yHAOs:-NxN-cQ88-Pyd_7yHAOt:bd78j6e) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6757cf4b0fec64687092f0b79946e051c2e5f95/crates/blockifier/src/concurrency/fee_utils_test.rs#L36)):*
> ```XML
> 
>     let mut concurrency_call_info = create_fee_transfer_call_data(state, &account_tx, true);
>     let call_info = create_fee_transfer_call_data(state, &account_tx, false);
> ```

You can remove `test_state_cairo1`



_Suggestion:_
```XML
    let state_reader = test_state_reader(chain_info, BALANCE, &[(account, 1)], erc20_version)

    let sequencer_balance = 100;
    let sequencer_address = block_context.block_info.sequencer_address;
    fund_account(chain_info, sequencer_address, sequencer_balance, &mut state_reader);

    let state = CachedState::from(state_reader);
    let mut concurrency_call_info = create_fee_transfer_call_data(state, &account_tx, true);
    let call_info = create_fee_transfer_call_data(state, &account_tx, false);
```
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-NxN-sHn75dSBLdyi5uj:-NxN-sHo7UQYb_daWMAM:bwxrzgp) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6757cf4b0fec64687092f0b79946e051c2e5f95/crates/blockifier/src/test_utils/initial_test_state.rs#L45)):*
> ```XML
>     initial_balances: u128,
>     contract_instances: &[(FeatureContract, u16)],
>     erc20_contract_version: CairoVersion,
> ```

`erc20_version`/`erc20_cairo_version`



_Suggestion:_
```XML
erc20_version
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
Can you please add the cairo code itself?

> Reviewed 3 of 6 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-:-NxSO7hA9KRXmfwlasuT:b-7859ph)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls.casm.json` line 0 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-NxSNtWO69RHhPaff4yT:-NxSNtWO69RHhPaff4yU:btcc0ao) ([raw file](https://github.com/starkware-libs/blockifier/blob/af0285cbe343ff74c020dd18e7d24d73146c5ea8/crates/blockifier/ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls.casm.json#L0)):*
What is this file?
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-NxSPCY55BLe2YrDK8Fp:-NxSPCY55BLe2YrDK8Fq:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/af0285cbe343ff74c020dd18e7d24d73146c5ea8/crates/blockifier/src/test_utils/contracts.rs#L53)):*
> ```XML
> // ERC20 contract is in a unique location.
> const ERC20_CONTRACT_PATH: &str =
>     "./ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls_compiled.json";
> ```





_Suggestion:_
```XML
const ERC20_CAIRO0_CONTRACT_PATH: &str =
    "./ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls_compiled.json";
```
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-NxSPNa63-sRJqhqru82:-NxSPNa63-sRJqhqru83:b9pahql) ([raw file](https://github.com/starkware-libs/blockifier/blob/af0285cbe343ff74c020dd18e7d24d73146c5ea8/crates/blockifier/src/test_utils/initial_test_state.rs#L8)):*
> ```XML
> use strum::IntoEnumIterator;
> 
> use super::CairoVersion;
> ```

Please avoid using `super`



_Code quote:_
```XML
use super::CairoVersion;
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls.casm.json` line  at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-NxSNtWO69RHhPaff4yT:-NxSymWNAgfuiOVCcq9I:bedeel9) ([raw file](https://github.com/starkware-libs/blockifier/blob/af0285cbe343ff74c020dd18e7d24d73146c5ea8/crates/blockifier/ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls.casm.json#L)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is this file?
</blockquote></details>

it's the same as the erc20. I forgot to delete it.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-NxSPCY55BLe2YrDK8Fp:-Ny-_t0q-pxcRgMN-vEv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/af0285cbe343ff74c020dd18e7d24d73146c5ea8/crates/blockifier/src/test_utils/contracts.rs#L53)):*
> ```XML
> // ERC20 contract is in a unique location.
> const ERC20_CONTRACT_PATH: &str =
>     "./ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls_compiled.json";
> ```

Done.
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-NxSPNa63-sRJqhqru82:-Ny-_sTz7t8CGBIii04O:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/af0285cbe343ff74c020dd18e7d24d73146c5ea8/crates/blockifier/src/test_utils/initial_test_state.rs#L8)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please avoid using `super`
</blockquote></details>

Done.
___
*[`crates/blockifier/ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls.casm.json` line  at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-NxSNtWO69RHhPaff4yT:-Ny-a4vG444Qfu7aMn9L:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/af0285cbe343ff74c020dd18e7d24d73146c5ea8/crates/blockifier/ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls.casm.json#L)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

it's the same as the erc20. I forgot to delete it.
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-O-ZsBzwDWPZ2yO28hka:-O-ZsBzwDWPZ2yO28hkb:bfhnhwo) ([raw file](https://github.com/starkware-libs/blockifier/blob/dac225010d7176ade831a144a3319d1c736ff4bd/crates/blockifier/src/concurrency/fee_utils_test.rs#L18)):*
> ```XML
> 
> #[rstest]
> pub fn test_fix_call_info(
> ```

Seems irrelevant for this PR. Did you rebase?



_Code quote:_
```XML
ub fn test_fix_call_info(
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-O-Zt5vBE5w9Mly8WF3k:-O-Zt5vCDpniugE2Bgs7:bqxw62c) ([raw file](https://github.com/starkware-libs/blockifier/blob/dac225010d7176ade831a144a3319d1c736ff4bd/crates/blockifier/src/test_utils/contracts.rs#L54)):*
> ```XML
> const ERC20_CAIRO0_CONTRACT_PATH: &str =
>     "./ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls_compiled.json";
> const ERC20_CAIRO1_CONTRACT_PATH: &str = "./ERC20_without_some_syscalls/ERC20/erc20.casm.json";
> ```

Please fix the file locations accordingly



_Suggestion:_
```XML
const ERC20_CAIRO0_CONTRACT_PATH: &str =
    "./ERC20/ERC20_cairo0/erc20_contract_without_some_syscalls_compiled.json";
const ERC20_CAIRO1_CONTRACT_PATH: &str = "./ERC20/ERC20_cairo1/erc20.casm.json";
```

**Comment by meship-starkware** [comment]
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-O-ZsBzwDWPZ2yO28hka:-O-_9-wH8uwrqo9RB-pw:b4gqps9) ([raw file](https://github.com/starkware-libs/blockifier/blob/dac225010d7176ade831a144a3319d1c736ff4bd/crates/blockifier/src/concurrency/fee_utils_test.rs#L18)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Seems irrelevant for this PR. Did you rebase?
</blockquote></details>

I rebased now, but these changes are for this test to use the cairo1 erc20. LMK if you still think there are still irrelevant changes.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r4, 14 of 15 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-:-O-_DuSK6GTlic0L1Qtw:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1875#-O-_9nbX4zkW0q9PVU1I:-O-_DROG2XdGqzRmGPn3:bfnpjva) ([raw file](https://github.com/starkware-libs/blockifier/blob/34bc4b11573765af4f85ce705e33136ee3f21bcd/crates/blockifier/src/test_utils/initial_test_state.rs#L87)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure this is the solution we want here, but it was the easiest way to compensate for the fact that Rust does not have default parameters. I can add to all the places that use test_state Cairo version 0 instead.
</blockquote></details>

That's okay. Maybe choose a better name in a different PR (test_state_with_erc20_v0 to the old func)
Can you please change @avi-starkware transfers test to use the new erc20? (also in a different PR)

**Review by noaov1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1875)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
