### PR TITLE
Make sure state doesn't change on failing account deploy tx

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/577)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/577)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NXJF2DWBqksDT-V8WEq:-NXJF2DX67U1_wGHVAWI:bplue0t) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b9875f6f0227bf9a79752d90d2775ef43964cd/crates/blockifier/src/transaction/account_transactions_test.rs#L226)):*
> ```XML
> 
> #[test]
> /// Failing account deployment should not change state (no fee charge or nonce bump)
> ```

End with period.



_Suggestion:_
```XML
Tests that failing
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NXJFHRpDPHOf2_nCWqr:-NXJFHRpDPHOf2_nCWqs:b-13f1u4) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b9875f6f0227bf9a79752d90d2775ef43964cd/crates/blockifier/src/transaction/account_transactions_test.rs#L227)):*
> ```XML
> #[test]
> /// Failing account deployment should not change state (no fee charge or nonce bump)
> fn test_fail_deploy_account() {
> ```

Why does this require a special test?



_Code quote:_
```XML
test_fail_deploy_account
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NXJFBa54bAZPDyHaPVJ:-NXJFBa54bAZPDyHaPVK:b-cicb1s) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b9875f6f0227bf9a79752d90d2775ef43964cd/crates/blockifier/src/transaction/account_transactions_test.rs#L234)):*
> ```XML
>         PatriciaKey::try_from(StarkFelt::try_from(TEST_FAULTY_ACCOUNT_CONTRACT_ADDRESS).unwrap())
>             .unwrap(),
>     );
> ```

I think there's a shorter way throughout the code to initialize this struct.



_Code quote:_
```XML
    let deployed_account_address = ContractAddress(
        PatriciaKey::try_from(StarkFelt::try_from(TEST_FAULTY_ACCOUNT_CONTRACT_ADDRESS).unwrap())
            .unwrap(),
    );
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NXJFNyh3oD__ps5-fi5:-NXJFNyh3oD__ps5-fi6:b-4m4kzb) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b9875f6f0227bf9a79752d90d2775ef43964cd/crates/blockifier/src/transaction/account_transactions_test.rs#L240)):*
> ```XML
>     // Create and execute (failing) deploy account transaction.
>     let deploy_account_tx =
>         create_account_tx_for_validate_test(TransactionType::DeployAccount, INVALID, None);
> ```

What do those mean?



_Code quote:_
```XML
INVALID, None
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/577)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NXJFHRpDPHOf2_nCWqr:-NXJbrBQBitnlrdr7UtN:b-odkerc) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b9875f6f0227bf9a79752d90d2775ef43964cd/crates/blockifier/src/transaction/account_transactions_test.rs#L227)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why does this require a special test?
</blockquote></details>

Oh, because execution happens before validation?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/577)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NXJFHRpDPHOf2_nCWqr:-NXKb3Fm8jzKesNAfJcQ:b2nign6) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b9875f6f0227bf9a79752d90d2775ef43964cd/crates/blockifier/src/transaction/account_transactions_test.rs#L227)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Oh, because execution happens before validation?
</blockquote></details>

yes
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NXJFNyh3oD__ps5-fi5:-NXPBMaS3gs9vCSyVzLy:b-bklkjl) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b9875f6f0227bf9a79752d90d2775ef43964cd/crates/blockifier/src/transaction/account_transactions_test.rs#L240)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What do those mean?
</blockquote></details>

`INVALID` indicates to `account_faulty.cairo` that the `__validate__` should fail (`assert 0 = 1`).
the `None` is here because there is another scenario (`CALL_CONTRACT` instead of `INVALID`) where you can add data; we don't need data in this case.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/577)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NXJFNyh3oD__ps5-fi5:-NXPiSaU3TsnHGOK_AXY:b88eki7) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b9875f6f0227bf9a79752d90d2775ef43964cd/crates/blockifier/src/transaction/account_transactions_test.rs#L240)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`INVALID` indicates to `account_faulty.cairo` that the `__validate__` should fail (`assert 0 = 1`).
the `None` is here because there is another scenario (`CALL_CONTRACT` instead of `INVALID`) where you can add data; we don't need data in this case.
</blockquote></details>

Give them names in the code (variables).

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/577)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NXJFNyh3oD__ps5-fi5:-NXPkaZLAXQMXhpUihbv:b31rpuq) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b9875f6f0227bf9a79752d90d2775ef43964cd/crates/blockifier/src/transaction/account_transactions_test.rs#L240)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give them names in the code (variables).
</blockquote></details>

1. none of the other usages use names, want me to fix them?
2. why give `INVALID` a name? it has one
3. Setting `additional_data = None` is strange IMO, should I go for it?

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/577#-:-NXPwdbvBkyf5uQZVGQz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NXJFNyh3oD__ps5-fi5:-NXPwQ8N887ZozqQPGPY:b-hp7q6m) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b9875f6f0227bf9a79752d90d2775ef43964cd/crates/blockifier/src/transaction/account_transactions_test.rs#L240)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. none of the other usages use names, want me to fix them?
2. why give `INVALID` a name? it has one
3. Setting `additional_data = None` is strange IMO, should I go for it?
</blockquote></details>

If none of them have it, your choice.

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 241 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NYwKwPwEADq69-r1-XL:-NYwKwPwEADq69-r1-XM:b-2tsyv6) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b3e6c89eb595814466772c7b9c508540ca6ff68/crates/blockifier/src/transaction/account_transactions_test.rs#L241)):*
> ```XML
>     deploy_account_tx.execute(&mut state, block_context).unwrap_err();
> 
>     // Assert nonce and balance are unchanged.
> ```

This only checks the nonce and balance. Consider testing the actual contract at this address hadn't changed (e.g. by sampling `address_to_class_hash` or the state trees via some other method)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/577)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 182 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/577#-NYwVwyr1KUgCDdP1PF4:-NYwVwyr1KUgCDdP1PF5:bcwjgby) ([raw file](https://github.com/starkware-libs/blockifier/blob/92400c88af24709de018e51e7d34c136f9f1f079/crates/blockifier/src/transaction/account_transactions_test.rs#L182)):*
> ```XML
> 
> #[test]
> fn test_infinite_recursion() {
> ```

dunno what reveiwable is showing here... `git diff HEAD^` doesn't show this test



_Code quote:_
```XML
test_infinite_recursion
```

**Review by zuphitf — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/577#-:-NYwfQQ-4m-c7NDpXuMD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Pull request merged**
