### PR TITLE
chore(fee, concurrency): move all fee logic to fee_utils

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2004)

### CODE REVIEW

**Review by avi-starkware — APPROVED** [review]
One small non-blocking comment.

:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2004#-:-O0DHq_v2qfC_u4WEbbQ:b-ov1lp4)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2004#-O0DGqxn04LmilyinVga:-O0DGqxo3Qdzif5aNHNn:b-krds26) ([raw file](https://github.com/starkware-libs/blockifier/blob/67ba5ba7f76d538aa40194fdbf504ef7d4e3e371/crates/blockifier/src/concurrency/fee_utils.rs#L76)):*
> ```XML
> // Fixes the fee transfer call info to have the correct sequencer
> // balance. In concurrency mode, the fee transfer is executed with a false (constant) sequencer
> // balance. This affects the call info.
> ```

Fix the line breaks.
Non-blocking



_Code quote:_
```XML
// Fixes the fee transfer call info to have the correct sequencer
// balance. In concurrency mode, the fee transfer is executed with a false (constant) sequencer
// balance. This affects the call info.
```

**Review by avi-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2004)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2004)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2004)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @avi-starkware and @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2004)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @avi-starkware and @noaov1)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2004)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
