### PR TITLE
test(execution): support disjoint recipients in transfers flow test

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921)

### CODE REVIEW

**Comment by avi-starkware** [comment]
+reviewer:@barak-b-starkware

**Review by OriStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz1e_s63wHymj659Cww:-Nz1e_s63wHymj659Cwx:b-gjhn46) ([raw file](https://github.com/starkware-libs/blockifier/blob/edcd9af339bf12532d8b0db30d3911f0825a426c/crates/blockifier/src/test_utils/transfers_simulator.rs#L65)):*
> ```XML
> 
>     fn next(&mut self) -> Option<Self::Item> {
>         self.index = (self.index + 1) % self.accounts.len();
> ```

You should advance index here, right?
___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz-It739WLB8DOHyXee:-Nz-It74CpxUnA4TKr18:b-q50yzn) ([raw file](https://github.com/starkware-libs/blockifier/blob/edcd9af339bf12532d8b0db30d3911f0825a426c/crates/blockifier/src/test_utils/transfers_simulator.rs#L82)):*
> ```XML
>     pub fn new(recipient_iterator_kind: RecipientIteratorKind) -> Self {
>         let account_contract = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo0);
>         let concurrency_mode = true;
> ```

Shouldn't this be a parameter of the function?



_Code quote:_
```XML
let concurrency_mode = true;
```
___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz1gD3eCn0S-sXx0Bbs:-Nz1gD3eCn0S-sXx0Bbt:b4bgow5) ([raw file](https://github.com/starkware-libs/blockifier/blob/edcd9af339bf12532d8b0db30d3911f0825a426c/crates/blockifier/src/test_utils/transfers_simulator.rs#L119)):*
> ```XML
>     pub fn execute_chunk_of_transfers(&mut self) {
>         let mut chunk: Vec<Transaction> = Vec::with_capacity(CHUNK_SIZE);
>         for _ in 0..CHUNK_SIZE {
> ```

Consider asserting that the CHUNK_SIZE is smaller than N_ACCOUNTS to get independent transactions.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz1gD3eCn0S-sXx0Bbs:-Nz2NFmUCIQUS-xNxJws:b-a7qis) ([raw file](https://github.com/starkware-libs/blockifier/blob/edcd9af339bf12532d8b0db30d3911f0825a426c/crates/blockifier/src/test_utils/transfers_simulator.rs#L119)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

It is only relevant for the Disjoint iterator, and I don't think it will be a big deal if all the dependency we have is between transactions from the same sender. Moreover, CHUNK_SIZE might be a bit misleading because the set of transactions sent to the executor is further divided into chunks in the executor before it actually starts the parallel execution.

@noaov1 what do you think?
</blockquote></details>

The actual size of the chunk comes from `concurrency_config.chunk_size`.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 28 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz3uFrhDqsAsbKMEz6O:-Nz3uFrhDqsAsbKMEz6P:bt7t0z7) ([raw file](https://github.com/starkware-libs/blockifier/blob/0396168d4d297618b37aa8d9abaf0cb27e7d033d/crates/blockifier/src/test_utils/transfers_generator.rs#L28)):*
> ```XML
> const CHARGE_FEE: bool = true;
> const TRANSACTION_VERSION: TransactionVersion = TransactionVersion(StarkFelt::THREE);
> const CONCURRENCY_MODE: bool = false;
> ```

This can't be changed to `true` yet, since `execute_chunk()` is not yet implemented.



_Code quote:_
```XML
const CONCURRENCY_MODE: bool = false;
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz-It739WLB8DOHyXee:-Nz3ui0Q2Lf2BizYFiWd:be4qja) ([raw file](https://github.com/starkware-libs/blockifier/blob/edcd9af339bf12532d8b0db30d3911f0825a426c/crates/blockifier/src/test_utils/transfers_simulator.rs#L82)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

In another PR, I'll add a `TransfersSimulatorConfig` struct that will include `concurrency_mode`.
This PR is just about the recipient iterator.

If I add it as a parameter of the function, I will just need to put `let concurrency_mode = true` before I call this function, which isn't better.
</blockquote></details>

I added it as a constant.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz1gD3eCn0S-sXx0Bbs:-Nz3umvO-qu8lpYZh3CO:b-4htyyj) ([raw file](https://github.com/starkware-libs/blockifier/blob/edcd9af339bf12532d8b0db30d3911f0825a426c/crates/blockifier/src/test_utils/transfers_simulator.rs#L119)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

The actual size of the chunk comes from `concurrency_config.chunk_size`.
</blockquote></details>

I added a constant called `STREAM_SIZE`. `CHUNK_SIZE` is used in the concurrency config.

**Review by OriStarkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 28 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz3uFrhDqsAsbKMEz6O:-Nz7LeA011DOEhhOc--a:b-updlha) ([raw file](https://github.com/starkware-libs/blockifier/blob/0396168d4d297618b37aa8d9abaf0cb27e7d033d/crates/blockifier/src/test_utils/transfers_generator.rs#L28)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This can't be changed to `true` yet, since `execute_chunk()` is not yet implemented.
</blockquote></details>

Consider adding this line in a comment.
___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz1gD3eCn0S-sXx0Bbs:-Nz7P_KA5b2LtE11QTVn:b-yj93sq) ([raw file](https://github.com/starkware-libs/blockifier/blob/edcd9af339bf12532d8b0db30d3911f0825a426c/crates/blockifier/src/test_utils/transfers_simulator.rs#L119)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I added a constant called `STREAM_SIZE`. `CHUNK_SIZE` is used in the concurrency config.
</blockquote></details>

If you don't want to add an assertion, consider adding a comment explaining that in case this will cause a bug in the future.

**Review by OriStarkware — APPROVED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 28 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz3uFrhDqsAsbKMEz6O:-Nz7bF4d78kT9XEKEHQi:b-7yd1q4) ([raw file](https://github.com/starkware-libs/blockifier/blob/0396168d4d297618b37aa8d9abaf0cb27e7d033d/crates/blockifier/src/test_utils/transfers_generator.rs#L28)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Consider adding this line in a comment.
</blockquote></details>

Added a TODO.
___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nz1gD3eCn0S-sXx0Bbs:-Nz7bEB40RK9kqsI5haT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/edcd9af339bf12532d8b0db30d3911f0825a426c/crates/blockifier/src/test_utils/transfers_simulator.rs#L119)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

If you don't want to add an assertion, consider adding a comment explaining that in case this will cause a bug in the future.
</blockquote></details>

Done.

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-:-NzNTuC7DTxAHjNdN9O4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by OriStarkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by OriStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transfers_flow_test.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-NzvmVAB7khAu8W3dab6:-NzvmVAB7khAu8W3dab7:brnfqs8) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/blockifier/transfers_flow_test.rs#L9)):*
> ```XML
>     // Note: to make transactions in each chunk fully independent, make sure the number of accounts
>     // is larger than the chunk size. Otherwise, the same account may be used in multiple
>     // transactions in the same chunk.
> ```

Why would you like to make transactions in each chunk fully independent?
In this case, can we force it in the code somewhere?



_Code quote:_
```XML
    // Note: to make transactions in each chunk fully independent, make sure the number of accounts
    // is larger than the chunk size. Otherwise, the same account may be used in multiple
    // transactions in the same chunk.
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 23 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nzvmy7eE6MAPrzukc6a:-Nzvmy7eE6MAPrzukc6b:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L23)):*
> ```XML
> 
> const N_ACCOUNTS: u16 = 10000;
> const STREAM_SIZE: usize = 1000;
> ```





_Suggestion:_
```XML
const NUM_TXS: usize = 1000;
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-NzvnDdH03A0LrqWhOB1:-NzvnDdH03A0LrqWhOB2:b-c7fgc) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L30)):*
> ```XML
> const CONCURRENCY_MODE: bool = false;
> const N_WORKERS: usize = 4;
> const CHUNK_SIZE: usize = 10;
> ```

See comment [here](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzvgvxfEbVWCJHyVKqc)



_Code quote:_
```XML
// TODO(Avi, 10/06/2024): Change to true once concurrency is supported.
const CONCURRENCY_MODE: bool = false;
const N_WORKERS: usize = 4;
const CHUNK_SIZE: usize = 10;
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 36 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-NzvlqZX6YEFHG_J_GYH:-NzvlqZX6YEFHG_J_GYI:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L36)):*
> ```XML
>     RoundRobin,
>     DisjointFromSenders,
> }
> ```





_Suggestion:_
```XML
pub enum RecipientIteratorType {
    Random,
    RoundRobin,
    DisjointFromSenders,
}
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 136 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-NzvmltOBBPMilCO0iyL:-NzvmltOBBPMilCO0iyM:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L136)):*
> ```XML
> 
>     pub fn execute_transfers_stream(&mut self) {
>         let mut tx_stream: Vec<Transaction> = Vec::with_capacity(STREAM_SIZE);
> ```





_Suggestion:_
```XML
    pub fn execute_transfer_txs(&mut self) {
        let mut txs: Vec<Transaction> = Vec::with_capacity(NUM_TXS);
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transfers_flow_test.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-NzvmVAB7khAu8W3dab6:-NzwCAIs77kjUGTL3tae:b-ckd9nu) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/blockifier/transfers_flow_test.rs#L9)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Why would you like to make transactions in each chunk fully independent?
In this case, can we force it in the code somewhere?
</blockquote></details>

This is what @Yoni-Starkware said the test should do, but it's not super critical, so I don't want to put an assert here. It might fail the CI for a silly reason.
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 23 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nzvmy7eE6MAPrzukc6a:-NzwBbAkBO-GdR-0hWnu:bubc9wt) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L23)):*
> ```XML
> 
> const N_ACCOUNTS: u16 = 10000;
> const STREAM_SIZE: usize = 1000;
> ```

Done.

I am making all the changes in #1945 to avoid rebases for name changes.
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-NzvnDdH03A0LrqWhOB1:-NzwBX-S05-cjGB2NqOk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L30)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

See comment [here](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzvgvxfEbVWCJHyVKqc)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 36 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-NzvlqZX6YEFHG_J_GYH:-NzwBXN27XWTMm8EWSAd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L36)):*
> ```XML
>     RoundRobin,
>     DisjointFromSenders,
> }
> ```

Done.
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 136 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-NzvmltOBBPMilCO0iyL:-NzwDwcSBR6nYfKHBupQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L136)):*
> ```XML
> 
>     pub fn execute_transfers_stream(&mut self) {
>         let mut tx_stream: Vec<Transaction> = Vec::with_capacity(STREAM_SIZE);
> ```

Done.

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 72 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nzwe6RO7xBS-Fe7nH0q:-Nzwe6RO7xBS-Fe7nH0r:bkxcbqd) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L72)):*
> ```XML
>         Some(self.account_addresses[current_index])
>     }
> }
> ```

Something like:
WDYT?



_Suggestion:_
```XML
pub enum RecipientIteratorType {
    Random,
    RoundRobin,
    DisjointFromSenders,
}

pub struct RecipientIterator {
    recipient_addresses: Vec<ContractAddress>,
    rng: Option<StdRng>,
}

impl RecipientIterator {
    pub fn new(account_contract: FeatureContract, ty: RecipientIteratorType) -> Self {
        let account_addresses: Vec<ContractAddress> = (0..N_ACCOUNTS)
            .map(|instance_id| account_contract.get_instance_address(instance_id))
            .collect::<Vec<_>>();
        let (recipient_addresses, rng): (Vec<ContractAddress>, Option<StdRng>) = match ty {
            RecipientIteratorType::Random => {
                (account_addresses, Some(StdRng::seed_from_u64(0_u64)))
            },
            RecipientIteratorType::RoundRobin => {
                let mut account_addresses_iter = account_addresses.iter();
                if let Some(first) = account_addresses_iter.next() {
                    let r = account_addresses_iter.chain(std::iter::once(first));
                    (r.map(|l| *l).collect(), None)
                } else {
                    panic!("Empty account_addresses");
                }
            },
            RecipientIteratorType::DisjointFromSenders => {
                ((N_ACCOUNTS..2 * N_ACCOUNTS).map(|instance_id| account_contract.get_instance_address(instance_id)).collect::<Vec<_>>(), None)
            },
        };
        Self { recipient_addresses, rng }
    }
}

impl Iterator for RecipientIterator {
    type Item = ContractAddress;

    fn next(&mut self) -> Option<Self::Item> {
        if let Some(mut rng) = self.rng {
            Some(*self.recipient_addresses.iter().choose(&mut rng).unwrap())            
        } else {
            Some(*self.recipient_addresses.iter().next().unwrap())
        }
    }
}
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 72 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nzwe6RO7xBS-Fe7nH0q:-NzwiXosC_To7sDU0AWY:bivn74g) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L72)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Something like:
WDYT?
</blockquote></details>

I think this change will make it harder to understand what a given type of iterator does because it interweaves the flow of different types of iterators. Additionally, it will make it harder to add a new type of iterator.

If you find the logic behind each type of iterator acceptable and just want to refactor the code, how about we merge it as it is and do the refactor it in another PR if needed?

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @barak-b-starkware, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 72 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-Nzwe6RO7xBS-Fe7nH0q:-O1GUn4W5N3B3n5zvAje:bxbrnu9) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ddc182ab8aca1ba7d6bcd60b87d89445c02e89c/crates/blockifier/src/test_utils/transfers_generator.rs#L72)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I did a refactor that should address your concerns in PR #1977.
</blockquote></details>

@barak-b-starkware @OriStarkware 
I ended up accepting this suggestion. My usage of iterators was overkill.

The refactor mentioned above is no longer relevant.

Please take a look.

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921#-:-O1Gr1d35G2g-jpanm8-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by OriStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1921)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Pull request merged**
