### PR TITLE
Test the txIfo syscall with both deprecated and non-deprecated transa…

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…ctions

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Ngwjs2C0WjMbgCCY0Mt:-Ngwjs2C0WjMbgCCY0Mu:b-1gd79o) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfbd75e24e377719a86ec7ed4542ec616233f5ce/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L233)):*
> ```XML
>         });
>     entry_point_call
>         .clone()
> ```

why is this final clone needed?



_Code quote:_
```XML
.clone()
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NgwjpRzBrxNe2IDhuFu:-NgwjpS-Cxwa6xg-mKW4:b-o4vn93) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfbd75e24e377719a86ec7ed4542ec616233f5ce/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L235)):*
> ```XML
>         .clone()
>         .execute_directly_given_account_context(&mut state, default_current_context)
>         .unwrap_err();
> ```

what exactly are you testing here...?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Ngwjs2C0WjMbgCCY0Mt:-NgyQbnxEnDk8C_G9bav:bss4a2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfbd75e24e377719a86ec7ed4542ec616233f5ce/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L233)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this final clone needed?
</blockquote></details>

Removed.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NgwjpRzBrxNe2IDhuFu:-NgyQcvyDmVaOlHmegsd:b-pumqcs) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfbd75e24e377719a86ec7ed4542ec616233f5ce/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L235)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what exactly are you testing here...?
</blockquote></details>

This PR is currently on hold until the compiler release. 
I opened it based on Elin's request. My plan is to test both deprecated and non-deprecated transactions and verify the functionality of the new fields.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Ngy_sbB3TyBdb-0uSx8:-Ngy_sbB3TyBdb-0uSx9:bu2t9ga) (no related file):*
I think there is a rebase issue here now

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 300 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Ni_t0S90OFkyJCUuP9V:-Ni_t0S90OFkyJCUuP9W:b-ebwrgl) ([raw file](https://github.com/starkware-libs/blockifier/blob/e789d3c067a1d99548a161e018e801be47ea3ff7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L300)):*
> ```XML
> 
>     // Test V3 transactions.
>     let mut version = Felt252::from(3_u8);
> ```

is there a way to parametrize the `version` in this test?
to reduce code?
I see you are directly creating an account tx context object, so you can't use `invoke_tx_args`, but maybe TAL again and see if you can combine things?

(I would add more testing infra just to support this now, only check for low hanging fruit)



_Code quote:_
```XML
let mut version = Felt252::from(3_u8);
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 307 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Ni_tLH78esSAKgP8BUt:-Ni_tLH78esSAKgP8BUu:baunnuu) ([raw file](https://github.com/starkware-libs/blockifier/blob/e789d3c067a1d99548a161e018e801be47ea3ff7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L307)):*
> ```XML
>     let nonce = Nonce(stark_felt!(3_u16));
>     let l1_gas = StarkFelt::try_from(L1_GAS).map_err(SyscallExecutionError::from).unwrap();
>     let l2_gas = StarkFelt::try_from(L2_GAS).map_err(SyscallExecutionError::from).unwrap();
> ```

if you are unwrapping, anyway, why `map_err` at all?



_Code quote:_
```XML
    let l1_gas = StarkFelt::try_from(L1_GAS).map_err(SyscallExecutionError::from).unwrap();
    let l2_gas = StarkFelt::try_from(L2_GAS).map_err(SyscallExecutionError::from).unwrap();
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 322 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Ni_skc4AEugKB8TtjEC:-Ni_skc4AEugKB8TtjED:b-e3rnqa) ([raw file](https://github.com/starkware-libs/blockifier/blob/e789d3c067a1d99548a161e018e801be47ea3ff7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L322)):*
> ```XML
>         l2_gas,                       // Resource.
>         StarkFelt::ZERO,              // Max amount.
>         StarkFelt::ZERO,              // Max price per unit.
> ```

the problem with zero values is - if they are not correctly populated, but are allocated, this test won't catch it.
please change to arbitrary non-zero values below (first define variables for the nonzero values)



_Code quote:_
```XML
        StarkFelt::ZERO,              // Max amount.
        StarkFelt::ONE,               // Max price per unit.
        l2_gas,                       // Resource.
        StarkFelt::ZERO,              // Max amount.
        StarkFelt::ZERO,              // Max price per unit.
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 300 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Ni_t0S90OFkyJCUuP9V:-NidvR_C-bRVBRbsIkZl:ba8gdxt) ([raw file](https://github.com/starkware-libs/blockifier/blob/e789d3c067a1d99548a161e018e801be47ea3ff7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L300)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is there a way to parametrize the `version` in this test?
to reduce code?
I see you are directly creating an account tx context object, so you can't use `invoke_tx_args`, but maybe TAL again and see if you can combine things?

(I would add more testing infra just to support this now, only check for low hanging fruit)
</blockquote></details>

I've parametrized the version.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 307 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Ni_tLH78esSAKgP8BUt:-NidvGz27d4z1RzoRy_-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e789d3c067a1d99548a161e018e801be47ea3ff7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L307)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you are unwrapping, anyway, why `map_err` at all?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 263 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NieMuQ_1Iw4su3d-L3b:-NieMuQ_1Iw4su3d-L3c:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/960e12ffbed41bd33dbbf0702de2382d901e0388/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L263)):*
> ```XML
>     only_query: bool,
> ) {
>     let mut state = create_test_state();
> ```





_Suggestion:_
```XML
#[test_case(
    ExecutionMode::Validate,
    stark_felt!(TEST_SEQUENCER_ADDRESS),
    Felt252::from(1_u8),
    false;
    "Validate execution mode: block info fields should be zeroed. Tx version 1.")]
#[test_case(
    ExecutionMode::Execute,
    stark_felt!(TEST_SEQUENCER_ADDRESS),
    Felt252::from(1_u8),
    false;
    "Execute execution mode: block info should be as usual. Tx version 1.")]
#[test_case(
    ExecutionMode::Validate,
    stark_felt!(0_u16),
    Felt252::from(3_u8),
    false;
    "Validate execution mode: block info fields should be zeroed. Tx version 3.")]
#[test_case(
    ExecutionMode::Execute,
    stark_felt!(TEST_SEQUENCER_ADDRESS),
    Felt252::from(3_u8),
    false;
    "Execute execution mode: block info should be as usual. Tx version 3.")]
#[test_case(
    ExecutionMode::Execute,
    stark_felt!(TEST_SEQUENCER_ADDRESS),
    Felt252::from(3_u8),
    true;
    "Execute execution mode: block info should be as usual. Tx version 3. Query.")]
fn test_get_execution_info(
    execution_mode: ExecutionMode,
    sequencer_address: StarkFelt,
    version: Felt252,
    only_query: bool,
) {
    let mut state = create_test_state();
    let expected_block_info = [
        stark_felt!(CURRENT_BLOCK_NUMBER), // Block number.
        stark_felt!(CURRENT_BLOCK_TIMESTAMP), // Block timestamp.
        sequencer_address
    ];
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 265 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NieNVxc1WXxl3msRRiv:-NieNVxc1WXxl3msRRiw:b3wb22o) ([raw file](https://github.com/starkware-libs/blockifier/blob/960e12ffbed41bd33dbbf0702de2382d901e0388/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L265)):*
> ```XML
>     let mut state = create_test_state();
> 
>     let mut tx_version = version;
> ```

try making `version` as `mut` in the test parameters, so you don't need this other variable



_Code quote:_
```XML
let mut tx_version = version;
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 286 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NieNlKN9puIn8h0qHti:-NieNlKN9puIn8h0qHtj:b-p8ttt3) ([raw file](https://github.com/starkware-libs/blockifier/blob/960e12ffbed41bd33dbbf0702de2382d901e0388/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L286)):*
> ```XML
>             stark_felt!(&*ChainId(CHAIN_ID_NAME.to_string()).as_hex()), // Chain ID.
>             nonce.0,                         // Nonce.
>             stark_felt!(0_u16),              // Length of resource bounds array.
> ```

what's this doing on v1 tx info?



_Code quote:_
```XML
stark_felt!(0_u16),              // Length of resource bounds array.
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 322 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Ni_skc4AEugKB8TtjEC:-NifTPsY8ebN73XpDM_2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e789d3c067a1d99548a161e018e801be47ea3ff7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L322)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the problem with zero values is - if they are not correctly populated, but are allocated, this test won't catch it.
please change to arbitrary non-zero values below (first define variables for the nonzero values)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 263 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NieMuQ_1Iw4su3d-L3b:-Nif0y7zCTTYtViJvkSz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/960e12ffbed41bd33dbbf0702de2382d901e0388/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L263)):*
> ```XML
>     only_query: bool,
> ) {
>     let mut state = create_test_state();
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 265 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NieNVxc1WXxl3msRRiv:-Nif-uzRBYXhjdYIZuuX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/960e12ffbed41bd33dbbf0702de2382d901e0388/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L265)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

try making `version` as `mut` in the test parameters, so you don't need this other variable
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 286 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NieNlKN9puIn8h0qHti:-Nif1-f122bSNr7zwe9Z:bcrtb0h) ([raw file](https://github.com/starkware-libs/blockifier/blob/960e12ffbed41bd33dbbf0702de2382d901e0388/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L286)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this doing on v1 tx info?
</blockquote></details>

The syscall was updated, and now `resource_bound` is an argument of the entry point.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 356 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Nihz2qr2Ondth6UFuRL:-Nihz2qr2Ondth6UFuRM:bmgcb25) ([raw file](https://github.com/starkware-libs/blockifier/blob/f328943bea54e90e52151c29238634639a2240d0/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L356)):*
> ```XML
>             account_tx_context,
>             false,
>         ),
> ```

why `false`? to not limit steps based on resource bounds?



_Code quote:_
```XML
    let result = match execution_mode {
        ExecutionMode::Validate => entry_point_call
            .execute_directly_given_account_context_in_validate_mode(
                &mut state,
                account_tx_context,
                false,
            ),
        ExecutionMode::Execute => entry_point_call.execute_directly_given_account_context(
            &mut state,
            account_tx_context,
            false,
        ),
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils.rs` line 396 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NiiWCbrEb-EEAldMD5b:-NiiWCbs3MvXe-e0dZuL:b-fvbfcs) ([raw file](https://github.com/starkware-libs/blockifier/blob/f328943bea54e90e52151c29238634639a2240d0/crates/blockifier/src/test_utils.rs#L396)):*
> ```XML
>         state: &mut dyn State,
>         account_tx_context: AccountTransactionContext,
>         limit_steps_by_resources: bool,
> ```

Why do we need a new flag?



_Code quote:_
```XML
limit_steps_by_resources: bool,
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 396 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NiiWCbrEb-EEAldMD5b:-NiivT6ZD5HQ8mOSkuqE:b-sn1mjn) ([raw file](https://github.com/starkware-libs/blockifier/blob/f328943bea54e90e52151c29238634639a2240d0/crates/blockifier/src/test_utils.rs#L396)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why do we need a new flag?
</blockquote></details>

This flag enables us not to limit steps.
To send non-trivial values for `max_fee` and `resource_bound`.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 356 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Nihz2qr2Ondth6UFuRL:-NiivKefAFwyR1WdjEfJ:b-gvhpdk) ([raw file](https://github.com/starkware-libs/blockifier/blob/f328943bea54e90e52151c29238634639a2240d0/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L356)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why `false`? to not limit steps based on resource bounds?
</blockquote></details>

Exactly.
I have changed the `resource_bound` and `max_fee`to non-trivial values.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r7, 3 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils.rs` line 396 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NiiWCbrEb-EEAldMD5b:-Nj5xH6993P7VsBZ9iY9:b77j661) ([raw file](https://github.com/starkware-libs/blockifier/blob/f328943bea54e90e52151c29238634639a2240d0/crates/blockifier/src/test_utils.rs#L396)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This flag enables us not to limit steps.
To send non-trivial values for `max_fee` and `resource_bound`.
</blockquote></details>

Are you passing both `true` and `false`? Maybe for the `execute_directly*` utils we can pass a constant `true`?
Oh, I see you use `false` in the test; why?
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 210 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Nj5xWZq-iq80yUN6oz2:-Nj5xWZq-iq80yUN6oz3:brea95q) ([raw file](https://github.com/starkware-libs/blockifier/blob/e464ad3dfb4c49c9db5d4ae1ec02ba9fcde7bab7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L210)):*
> ```XML
>     ExecutionMode::Validate,
>     stark_felt!(0_u16),
>     Felt252::from(1_u8),
> ```

Maybe using `TransactionVersion` here (and also `ContractAddress`) will be clearer to the test reader.



_Code quote:_
```XML
Felt252::from(1_u8),
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 212 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Nj5xhbR-QRKnESnNK5d:-Nj5xhbR-QRKnESnNK5e:b-j7dji3) ([raw file](https://github.com/starkware-libs/blockifier/blob/e464ad3dfb4c49c9db5d4ae1ec02ba9fcde7bab7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L212)):*
> ```XML
>     Felt252::from(1_u8),
>     false;
>     "Validate execution mode: block info fields should be zeroed. Tx version 1.")]
> ```

For all



_Suggestion:_
```XML
Transaction V1.
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 396 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/987#-NiiWCbrEb-EEAldMD5b:-Nj6vNxW08QUe6EXNHM7:bpcwz8d) ([raw file](https://github.com/starkware-libs/blockifier/blob/f328943bea54e90e52151c29238634639a2240d0/crates/blockifier/src/test_utils.rs#L396)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are you passing both `true` and `false`? Maybe for the `execute_directly*` utils we can pass a constant `true`?
Oh, I see you use `false` in the test; why?
</blockquote></details>

To disable the `n_step_resource` check.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 210 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Nj5xWZq-iq80yUN6oz2:-Nj70OYJEBLxRwFbZqr0:bey172n) ([raw file](https://github.com/starkware-libs/blockifier/blob/e464ad3dfb4c49c9db5d4ae1ec02ba9fcde7bab7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L210)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe using `TransactionVersion` here (and also `ContractAddress`) will be clearer to the test reader.
</blockquote></details>

Change for the sequencer address as well?
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 272 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Nj70YI0CVT05DDmONoH:-Nj70YI0CVT05DDmONoI:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3892d7416ce4462755a7aa8778f1a8c3dc6dccd9/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L272)):*
> ```XML
>             nonce.0,                                                    // Nonce.
>             stark_felt!(0_u16),                                         /* Length of resource
>                                                                          * bounds array. */
> ```





_Suggestion:_
```XML
            stark_felt!(0_u16),                                         // Length of resource
                                                                        // bounds array. 
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 210 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Nj5xWZq-iq80yUN6oz2:-Nj7QIZWD6xzOK6GSpoU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e464ad3dfb4c49c9db5d4ae1ec02ba9fcde7bab7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L210)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Change for the sequencer address as well?
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 209 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Nj7c9ga6cemI7cBpsLs:-NjBgRSW1MviAi8pX9eL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/667993dff96fbb8880f325aab5429ee1b2e6c45d/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use shorthand macro (here and in the rest of the parametrizations)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 272 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Nj70YI0CVT05DDmONoH:-NjC6E67A4KMkvYRVrZf:bk5k9yg) ([raw file](https://github.com/starkware-libs/blockifier/blob/3892d7416ce4462755a7aa8778f1a8c3dc6dccd9/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L272)):*
> ```XML
>             nonce.0,                                                    // Nonce.
>             stark_felt!(0_u16),                                         /* Length of resource
>                                                                          * bounds array. */
> ```

`ResourceBounds` -> `resource bounds`

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 272 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/987#-Nj70YI0CVT05DDmONoH:-NjCFkwN9eKreDmyPQxG:bn37rde) ([raw file](https://github.com/starkware-libs/blockifier/blob/3892d7416ce4462755a7aa8778f1a8c3dc6dccd9/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L272)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`ResourceBounds` -> `resource bounds`
</blockquote></details>

            stark_felt!(0_u16),                                         // Length of resource
                                                                        // bounds array.
Failed on format check. 
So, I reverted the comment format change.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/987#-:-NjCaYIJEGvLs73LgigK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
