### PR TITLE
Zero block_info fields in validate execution mode.

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1010)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1010#-NhKxH3y3ApMDSw21CT6:-NhKxH3y3ApMDSw21CT7:ba4m9ig) ([raw file](https://github.com/starkware-libs/blockifier/blob/10aca980d8221768da4ab121bb0dd494242d79d7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L207)):*
> ```XML
>             stark_felt!(TEST_SEQUENCER_ADDRESS) // Sequencer address.
>         ];
>         "Execute execution mode: block info should be as usual.")]
> ```

What happened to the align here?



_Suggestion:_
```XML
#[test_case(
    ExecutionMode::Validate,
    [stark_felt!(0_u16); 3];
    "Validate execution mode: block info fields should be zeroed.")]
#[test_case(
    ExecutionMode::Execute,
    [
        stark_felt!(CURRENT_BLOCK_NUMBER), // Block number.
        stark_felt!(CURRENT_BLOCK_TIMESTAMP), // Block timestamp.
        stark_felt!(TEST_SEQUENCER_ADDRESS) // Sequencer address.
    ];
    "Execute execution mode: block info should be as usual.")]
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 89 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1010#-NhKxwZ0-2GpvI_RF78G:-NhKxwZ0-2GpvI_RF78H:b-5qds3f) ([raw file](https://github.com/starkware-libs/blockifier/blob/10aca980d8221768da4ab121bb0dd494242d79d7/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L89)):*
> ```Cairo
>         assert(tx_info.account_contract_address.into() == account_address, 'ACCOUNT_MISMATCH');
>         assert(tx_info.max_fee.into() == max_fee, 'MAX_FEE_MISMATCH');
>         assert(tx_info.signature.len() == 0_u32, 'SIGNATURE_MISMATCH');
> ```

Where was the length of the signature affected?
Where was it once created and now no longer?



_Code quote:_
```Cairo
        assert(tx_info.signature.len() == 0_u32, 'SIGNATURE_MISMATCH');
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1010#-NhKz0xV4lyy23UWEwB2:-NhKz0xV4lyy23UWEwB3:b-s7z87d) ([raw file](https://github.com/starkware-libs/blockifier/blob/10aca980d8221768da4ab121bb0dd494242d79d7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L238)):*
> ```XML
>     };
> 
>     assert!(!result.unwrap().execution.failed)
> ```

Why did the execution fail? Is it something deterministic and expected - but unrelated?



_Code quote:_
```XML
assert!(!result.unwrap().execution.failed)
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1010)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1010)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 89 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1010#-NhKxwZ0-2GpvI_RF78G:-NhL-oMt06suLZxxR0Aa:b-848oyw) ([raw file](https://github.com/starkware-libs/blockifier/blob/10aca980d8221768da4ab121bb0dd494242d79d7/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L89)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Where was the length of the signature affected?
Where was it once created and now no longer?
</blockquote></details>

This code was never tested in the blockifier (see Shahar's TODO that I removed)
They copied this code from the OS test on dev - the signature is tested there.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1010#-NhKxH3y3ApMDSw21CT6:-NhL1fdpCtNxVH0_M5tr:b-bc7dkd) ([raw file](https://github.com/starkware-libs/blockifier/blob/10aca980d8221768da4ab121bb0dd494242d79d7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L207)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

What happened to the align here?
</blockquote></details>

Oops, the formatter does not work on test_case I guess. Thanks
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1010#-NhL2T7k-7bHRGWEYGU7:-NhL2T7k-7bHRGWEYGU8:bhka959) ([raw file](https://github.com/starkware-libs/blockifier/blob/917fccafe993b6acd2a3dfec6aa7e5c281efd072/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L219)):*
> ```XML
> 
>     // TODO(spapini): Fix the "UNEXPECTED ERROR".
>     entry_point_call.execute_directly(&mut state).unwrap_err();
> ```

@ArniStarkware here.



_Code quote:_
```XML
    // TODO(spapini): Fix the "UNEXPECTED ERROR".
    entry_point_call.execute_directly(&mut state).unwrap_err();
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1010#-NhKz0xV4lyy23UWEwB2:-NhL1mUu1cYm0Eaw-d7a:bdegmf) ([raw file](https://github.com/starkware-libs/blockifier/blob/10aca980d8221768da4ab121bb0dd494242d79d7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L238)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why did the execution fail? Is it something deterministic and expected - but unrelated?
</blockquote></details>

I'm asserting success; note the `!` at the beginning.

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1010)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
