### PR TITLE
chore: patch range_check name bug

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2043)

### CODE REVIEW

**Review by ilyalesokhin-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2043#-:-O1AhkpE0PibauiETqv7:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

**Comment by ilyalesokhin-starkware** [comment]
Note that cairo-vm-v1.0.0-rc4 was released

**Review by dorimedini-starkware — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2043)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_objects.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2043#-O1B-TtO3tnS0Y8pILJq:-O1B-TtO3tnS0Y8pILJr:baf6zlm) ([raw file](https://github.com/starkware-libs/blockifier/blob/1229081042ad050a5b6cec1c71fccfaa6b2664e0/crates/native_blockifier/src/py_objects.rs#L123)):*
> ```XML
>                 .ok_or(NativeBlockifierInputError::UnknownBuiltin(builtin_name.clone()))?;
>             wrapper.insert(builtin, *count);
>         }
> ```

non-blocking



_Suggestion:_
```XML
        let builtin = if builtin_name == "range_check96_builtin" {
            BuiltinName::range_check96
        } else {
            BuiltinName::from_str_with_suffix(builtin_name)
                .ok_or(NativeBlockifierInputError::UnknownBuiltin(builtin_name.clone()))?
        }
        wrapper.insert(builtin, *count);
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2043)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_objects.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2043#-O1B-TtO3tnS0Y8pILJq:-O1B1x1J-9KZ3f8ACg9F:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/1229081042ad050a5b6cec1c71fccfaa6b2664e0/crates/native_blockifier/src/py_objects.rs#L123)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

non-blocking
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2043#-:-O1B3xEaDhVK8-kkDdyK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
