### PR TITLE
Update blockifier dependencies for 0.12.1 release.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/756)

### CODE REVIEW

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/756#-:-N_d0Wls6AbfEfs8PyRl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/756#-N_d01xwDLTv5KOyaOxX:-N_d01xwDLTv5KOyaOxY:b-99cowb) ([raw file](https://github.com/starkware-libs/blockifier/blob/3baa85eba889c3edddbcf180d16e26aafde9fc00/crates/blockifier/src/execution/cairo1_execution.rs#L244)):*
> ```XML
>     program_segment_size: usize,
> ) -> Result<(), VirtualMachineExecutionError> {
>     let verify_secure = true;
> ```

Consider restoring the return variable for readability.

**Review by dorimedini-starkware — DISMISSED** [review]
> Reviewed 6 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/756)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/756#-N_d0A1U6zpBLrqbFbNx:-N_d0A1VBAp33_r4RPh8:b-cex8rd) ([raw file](https://github.com/starkware-libs/blockifier/blob/3baa85eba889c3edddbcf180d16e26aafde9fc00/crates/blockifier/src/execution/cairo1_execution.rs#L253)):*
> ```XML
>         vm,
>         hint_processor,
>     )?)
> ```

isn't this equivalent?



_Suggestion:_
```XML
    runner.run_from_entrypoint(
        entry_point.pc(),
        &args,
        verify_secure,
        Some(program_segment_size),
        vm,
        hint_processor,
    )
```
___
*[`crates/blockifier/src/execution/deprecated_execution.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/756#-N_d0P_Y0XUYmRC6W8Gk:-N_d0P_Z2nsXzE54eBso:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/3baa85eba889c3edddbcf180d16e26aafde9fc00/crates/blockifier/src/execution/deprecated_execution.rs#L209)):*
> ```XML
>         vm,
>         hint_processor,
>     )?)
> ```

?



_Suggestion:_
```XML
    runner.run_from_entrypoint(
        entry_point_pc,
        &args,
        verify_secure,
        program_segment_size,
        vm,
        hint_processor,
    )
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 488 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/756#-N_d0f6F6I3rA1xm-UjY:-N_d0f6F6I3rA1xm-UjZ:b-wupl8i) ([raw file](https://github.com/starkware-libs/blockifier/blob/3baa85eba889c3edddbcf180d16e26aafde9fc00/crates/blockifier/src/execution/syscalls/hint_processor.rs#L488)):*
> ```XML
>         self.context.vm_run_resources.run_resources()
>     }
> }
> ```

duplicated... consider implementing a macro and use
```
impl_resource_tracker_for!(SyscallHintProcessor);
impl_resource_tracker_for!(DeprecatedSyscallHintProcessor);
```



_Code quote:_
```XML
impl ResourceTracker for SyscallHintProcessor<'_> {
    fn consumed(&self) -> bool {
        self.context.vm_run_resources.consumed()
    }

    fn consume_step(&mut self) {
        self.context.vm_run_resources.consume_step()
    }

    fn get_n_steps(&self) -> Option<usize> {
        self.context.vm_run_resources.get_n_steps()
    }

    fn run_resources(&self) -> &RunResources {
        self.context.vm_run_resources.run_resources()
    }
}
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 10 files at r1, 5 of 9 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/756#-:-N_dwDPQB4I6W7pk3Zx5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/756#-N_d0A1U6zpBLrqbFbNx:-N_dwG5n9dbRT5xggrQg:b-p094un) ([raw file](https://github.com/starkware-libs/blockifier/blob/3baa85eba889c3edddbcf180d16e26aafde9fc00/crates/blockifier/src/execution/cairo1_execution.rs#L253)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In this case, the `?` converts the error type. Without it, it doesn't work.
</blockquote></details>

Let's continue later
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 488 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/756#-N_d0f6F6I3rA1xm-UjY:-N_dvuyo-PgvycD3Tr-r:b-p094un) ([raw file](https://github.com/starkware-libs/blockifier/blob/3baa85eba889c3edddbcf180d16e26aafde9fc00/crates/blockifier/src/execution/syscalls/hint_processor.rs#L488)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Are you sure you prefer this? Macros can create less readable code and are sometimes harder to maintain. In this case (and in similar ones), we use duplication often because of the nature of `deprecated` code, which will eventually be deleted. I think it's easier to maintain here with the duplication (which is usually the reason to avoid it). WDYT?
</blockquote></details>

Let's continue later

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/756)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by barak-b-starkware — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 5 of 9 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/756)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
