### PR TITLE
Add class to Declare AccountTransaction variant.

### PR DESCRIPTION
**Pull request by noaov1**
In a subsequent PR I will pass the `contract_class` from `PyExecutor.execute`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/276)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/276)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/276#-NOF3F7RElZ8t6k5e--T:-NOF3F7RElZ8t6k5e--U:brom36h) ([raw file](https://github.com/starkware-libs/blockifier/blob/4958ca55f9f26ccc64327e33135bef911277d621/crates/blockifier/src/transaction/transactions.rs#L24)):*
> ```XML
> 
> pub trait Executable {
>     fn execute(
> ```

I'm not sure this trait is needed anymore, especially now that `Declare.execute`'s signature is divergent from the rest. Can we delete it and make the class non-optional?



_Code quote:_
```XML
pub trait Executable {
    fn execute(
        &self,
        state: &mut dyn State,
        block_context: &BlockContext,
        account_tx_context: &AccountTransactionContext,
        contract_class: Option<ContractClass>,
    ) -> TransactionExecutionResult<Option<CallInfo>>;
}
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/276)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/276)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/276#-NOF3F7RElZ8t6k5e--T:-NOF4ROQC9QlIECIDBUG:b-g5ph8t) ([raw file](https://github.com/starkware-libs/blockifier/blob/4958ca55f9f26ccc64327e33135bef911277d621/crates/blockifier/src/transaction/transactions.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm not sure this trait is needed anymore, especially now that `Declare.execute`'s signature is divergent from the rest. Can we delete it and make the class non-optional?
</blockquote></details>

I am not sure I follow. All the transactions structs are defined in SN API and therefore we cannot define inherent `impl` for them and must use a trait.

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/276)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/276#-NOF3F7RElZ8t6k5e--T:-NOF82gG2n0UUWoHI_Xi:b-ihoris) ([raw file](https://github.com/starkware-libs/blockifier/blob/4958ca55f9f26ccc64327e33135bef911277d621/crates/blockifier/src/transaction/transactions.rs#L24)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I am not sure I follow. All the transactions structs are defined in SN API and therefore we cannot define inherent `impl` for them and must use a trait.
</blockquote></details>

I keep forgetting this fact... :(
Add a short comment then (above the class argument) that it is only used for declare.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/276)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/276#-NOF3F7RElZ8t6k5e--T:-NOFBnO42A4WTEkqByFW:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/4958ca55f9f26ccc64327e33135bef911277d621/crates/blockifier/src/transaction/transactions.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I keep forgetting this fact... :(
Add a short comment then (above the class argument) that it is only used for declare.
</blockquote></details>

Done

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/276#-:-NOFD7cZ22T3_qwVthf6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
