### PR TITLE
Merge main-v0.12.3 into main.

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1021)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 9 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1021)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1021#-:-NhRejcP7ZAEy48WtqYb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1021)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1021#-NhRektv94HMySS_Zgu6:-NhRektv94HMySS_Zgu7:b8qdezt) (no related file):*
Python side?

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1021)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1021#-NhRektv94HMySS_Zgu6:-NhRicFyBAC6o66Y20MX:b-fb7c7j) (no related file):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

After this is merged?
</blockquote></details>

Usually we don't merge before making sure the Python CI passed (for merge PRs and those that involve `native-blockifier`).

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1021)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1021#-NhRektv94HMySS_Zgu6:-NhRimlqDj8H4Jo-r1C6:bucsdcw) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Usually we don't merge before making sure the Python CI passed (for merge PRs and those that involve `native-blockifier`).
</blockquote></details>

There's a risk that it will break Bazel build in the `main` repo., and then Blockifier is stuck (can't advance commit).

___

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1021)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1021#-NhRektv94HMySS_Zgu6:-NhRjRpLAcYiCLBwhM4M:b47hmex) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

There's a risk that it will break Bazel build in the `main` repo., and then Blockifier is stuck (can't advance commit).
</blockquote></details>

What commit should I take for python? (before the merge commit is created)

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1021)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1021#-NhRektv94HMySS_Zgu6:-NhRja0v3CZ0A3Ye-Bj6:b-nhicy9) (no related file):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What commit should I take for python? (before the merge commit is created)
</blockquote></details>

The tip of this branch (merge commit of `0.12.3` and `main`), and after this is merged - you take the final commit (the merge of this branch with `main`).

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1021)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
