### PR TITLE
Fix signature pointer in Cairo 1 allocate_tx_info_segment().

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/656)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/656)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/656#-NYmXqbU1FUiA_RWWpuS:-NYmXqbVBv395K6A4GfL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/225668c45fb15e6b30600c936edbfe779d1dbb8d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L348)):*
> ```XML
>         let tx_signature_length = account_tx_context.signature.0.len();
>         let mut tx_signature_end_ptr = tx_signature_start_ptr;
>         tx_signature_end_ptr += tx_signature_length;
> ```





_Suggestion:_
```XML
        let tx_signature_start_ptr = self.allocate_tx_signature_segment(vm)?;
        let tx_signature_length = account_tx_context.signature.0.len();
        le tx_signature_end_ptr = tx_signature_start_ptr + tx_signature_length;
        let account_tx_context = &self.context.account_tx_context;
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/656)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/656#-NYmXqbU1FUiA_RWWpuS:-NYmflGX15a654pGm3aJ:b-r5ijsv) ([raw file](https://github.com/starkware-libs/blockifier/blob/225668c45fb15e6b30600c936edbfe779d1dbb8d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L348)):*
> ```XML
>         let tx_signature_length = account_tx_context.signature.0.len();
>         let mut tx_signature_end_ptr = tx_signature_start_ptr;
>         tx_signature_end_ptr += tx_signature_length;
> ```

`account_tx_context` must be above `tx_signature_length`. Also `+=` operator for `Relocatable` can panic if it overflows `usize`, and `+` returns an error so that is indeed better. We do use `ptr += 1` in some places in our code, maybe we should change those. A panic is an attack on our sequencer.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/656)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/656#-NYmXqbU1FUiA_RWWpuS:-NYmgYU43N7j5L6Woh4Q:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/225668c45fb15e6b30600c936edbfe779d1dbb8d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L348)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

`account_tx_context` must be above `tx_signature_length`. Also `+=` operator for `Relocatable` can panic if it overflows `usize`, and `+` returns an error so that is indeed better. We do use `ptr += 1` in some places in our code, maybe we should change those. A panic is an attack on our sequencer.
</blockquote></details>

WDYT?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/656#-:-NYmhrBb60noNP_v8yoT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/656#-NYmXqbU1FUiA_RWWpuS:-NYmhkYCDDXceuJ10cJE:bcxvkai) ([raw file](https://github.com/starkware-libs/blockifier/blob/225668c45fb15e6b30600c936edbfe779d1dbb8d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L348)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Yes, I agree. Can you take this?
Can you show me the location of the panic?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/656)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/656#-NYmXqbU1FUiA_RWWpuS:-NYmi5Z98Vhl-h5013yZ:bek8bit) ([raw file](https://github.com/starkware-libs/blockifier/blob/225668c45fb15e6b30600c936edbfe779d1dbb8d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L348)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yes, I agree. Can you take this?
Can you show me the location of the panic?
</blockquote></details>

Yes, I'll take it and show you in the PR.

**Pull request merged**
