### PR TITLE
Implement `call_contract` syscall.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/483)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/483)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/483)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/483#-NViG2dz4vGpz_KTNHsk:-NViG2dz4vGpz_KTNHsl:b-dfdm3a) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8018ffc3715c200a8f50e57e6f3bc5dd7cf4a31/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L175)):*
> ```XML
>         builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 10)]),
>     };
>     main_call_vm_resources += &library_call_vm_resources;
> ```

Now, u can use `2*`, since you removed some of the overhead of test_library_call

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/483#-:-NViG8r61t57yR1k0N7a:bnfp4nl)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/483)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/483#-NViG2dz4vGpz_KTNHsk:-NViGb043_AiapESqWYo:b-pi5smd) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8018ffc3715c200a8f50e57e6f3bc5dd7cf4a31/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L175)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Now, u can use `2*`, since you removed some of the overhead of test_library_call
</blockquote></details>

How come it passes as it is?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/483)* status: 3 of 4 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/483#-NViG2dz4vGpz_KTNHsk:-NViKyd59PtoZyXMnho6:banha33) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8018ffc3715c200a8f50e57e6f3bc5dd7cf4a31/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L175)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come it passes as it is?
</blockquote></details>

Play with the numbers. That's what I did.

**Pull request merged**
