### PR TITLE
refactor(concurrency): use apply_writes in the commit of VersionedState

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)

### CODE REVIEW

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-:-NzYAV-q4bBFIfHNrJJU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by avi-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-Nzb1YZW0eVBW67kXrDt:-Nzb1YZXAz3NStJMRtow:b-ou240z) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8948ffe4cc41f10720f6db1985ac0a4148f9bf7/crates/blockifier/src/concurrency/versioned_state.rs#L83)):*
> ```XML
>         // TODO(barak, 01/08/2024): Add visited_pcs argument to `apply_writes`.
>         self.initial_state.apply_writes(&writes, &class_hash_to_class, &HashMap::default());
>     }
> ```

Is this possible?



_Suggestion:_
```XML
impl<S: StateReader> VersionedState<S> {
    pub fn new(initial_state: S) -> Self {
        VersionedState {
            initial_state,
            storage: VersionedStorage::default(),
            nonces: VersionedStorage::default(),
            class_hashes: VersionedStorage::default(),
            compiled_class_hashes: VersionedStorage::default(),
            compiled_contract_classes: VersionedStorage::default(),
            declared_contracts: VersionedStorage::default(),
        }
    }

    pub fn into_initial_state(self) -> U {
        self.initial_state
    }

    fn get_writes_up_to_index(&mut self, tx_index: TxIndex) -> StateMaps {
        StateMaps {
            storage: self.storage.get_writes_up_to_index(tx_index),
            nonces: self.nonces.get_writes_up_to_index(tx_index),
            class_hashes: self.class_hashes.get_writes_up_to_index(tx_index),
            compiled_class_hashes: self.compiled_class_hashes.get_writes_up_to_index(tx_index),
            declared_contracts: self.declared_contracts.get_writes_up_to_index(tx_index),
        }
    }

    #[cfg(any(feature = "testing", test))]
    pub fn get_writes_of_index(&self, tx_index: TxIndex) -> StateMaps {
        StateMaps {
            storage: self.storage.get_writes_of_index(tx_index),
            nonces: self.nonces.get_writes_of_index(tx_index),
            class_hashes: self.class_hashes.get_writes_of_index(tx_index),
            compiled_class_hashes: self.compiled_class_hashes.get_writes_of_index(tx_index),
            declared_contracts: self.declared_contracts.get_writes_of_index(tx_index),
        }
    }
}

impl<U: UpdatableState> VersionedState<U> {
    pub fn commit(&mut self, index: TxIndex) {
        let writes = self.get_writes_up_to_index(index);
        let class_hash_to_class = self.compiled_contract_classes.get_writes_up_to_index(index);
        // TODO(barak, 01/08/2024): Add visited_pcs argument to `apply_writes`.
        self.initial_state.apply_writes(&writes, &class_hash_to_class, &HashMap::default());
    }
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-Nzb1YZW0eVBW67kXrDt:-NzcGU823HWiZhY0j547:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8948ffe4cc41f10720f6db1985ac0a4148f9bf7/crates/blockifier/src/concurrency/versioned_state.rs#L83)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this possible?
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 233 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-NzcewaE1k46N6k1f2rJ:-NzcewaF33zP2jX54Ja1:b-1y9lvp) ([raw file](https://github.com/starkware-libs/blockifier/blob/81163fa5097a0b81cc95093909101d356483a0e8/crates/blockifier/src/concurrency/versioned_state.rs#L233)):*
> ```XML
>     pub fn commit_chunk_and_recover_block_state(self, commit_index: TxIndex) -> U {
>         let mut versioned_state = self.into_inner_state();
>         if commit_index > 0 {
> ```

What is the value of the commit index? The last committed transaction?



_Suggestion:_
```XML
 if commit_index >= 0 {
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 231 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-Nzch9Ip7oVVOI8P1_Y3:-Nzch9IqCE6exZhNMu5X:bw8ynbe) ([raw file](https://github.com/starkware-libs/blockifier/blob/81163fa5097a0b81cc95093909101d356483a0e8/crates/blockifier/src/concurrency/versioned_state.rs#L231)):*
> ```XML
> 
> impl<U: UpdatableState> ThreadSafeVersionedState<U> {
>     pub fn commit_chunk_and_recover_block_state(self, commit_index: TxIndex) -> U {
> ```

I think it should be implemented for VersionedState.
One should call it from the main thread, so no need to pass through the thread-safe.
(do `threadsafe_state.into_inner_state().commit()`)



_Code quote:_
```XML
impl<U: UpdatableState> ThreadSafeVersionedState<U> {
    pub fn commit_chunk_and_recover_block_state(self, commit_index: TxIndex) -> U {
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 244 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-NzcjS2T1MO7GSU2xxDr:-NzcjS2T1MO7GSU2xxDs:blzo60e) ([raw file](https://github.com/starkware-libs/blockifier/blob/81163fa5097a0b81cc95093909101d356483a0e8/crates/blockifier/src/concurrency/versioned_state.rs#L244)):*
> ```XML
>             );
>         }
>         versioned_state.into_initial_state()
> ```

A bit clearer IMO



_Suggestion:_
```XML
            let class_hash_to_class =
                versioned_state.compiled_contract_classes.get_writes_up_to_index(commit_index);
            
            let state = versioned_state.into_initial_state()
            // TODO(barak, 01/08/2024): Add visited_pcs argument to `apply_writes`.
            initial_state.apply_writes(
                &writes,
                &class_hash_to_class,
                &HashMap::default(),
            );
            
            state
        }
        
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 233 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-NzcewaE1k46N6k1f2rJ:-Nzco_E399sS_K6AVpSx:b-2yr70w) ([raw file](https://github.com/starkware-libs/blockifier/blob/81163fa5097a0b81cc95093909101d356483a0e8/crates/blockifier/src/concurrency/versioned_state.rs#L233)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is the value of the commit index? The last committed transaction?
</blockquote></details>

If the commit index equals 0 then we will want to get the writes of transaction 0, no?
Asked a related [question](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzcp8919ip_2exd4Ymv) in another PR.

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 231 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-Nzch9Ip7oVVOI8P1_Y3:-NzcrAmP1Ic6C1tWhKYA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/81163fa5097a0b81cc95093909101d356483a0e8/crates/blockifier/src/concurrency/versioned_state.rs#L231)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think it should be implemented for VersionedState.
One should call it from the main thread, so no need to pass through the thread-safe.
(do `threadsafe_state.into_inner_state().commit()`)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 233 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-NzcewaE1k46N6k1f2rJ:-NzclRgu1bTTW6ii7ERc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/81163fa5097a0b81cc95093909101d356483a0e8/crates/blockifier/src/concurrency/versioned_state.rs#L233)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is the value of the commit index? The last committed transaction?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 244 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-NzcjS2T1MO7GSU2xxDr:-NzclsW05zP_gvgOZfbJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/81163fa5097a0b81cc95093909101d356483a0e8/crates/blockifier/src/concurrency/versioned_state.rs#L244)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

A bit clearer IMO
</blockquote></details>

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-:-Nzfrfot6sWx-KaSLvhM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @OriStarkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1948#-:-NzhQzwg-H90gJ_Fbs-r:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @OriStarkware)

**Pull request merged**
