### PR TITLE
Add Cairo1 test contract

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a> 
    * **PR #449** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/449" target="_blank">Graphite</a> 
      * **PR #451** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/451" target="_blank">Graphite</a> 
        * **PR #450** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/450" target="_blank">Graphite</a> 
          * **PR #452** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/452" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/452?utm_source=stack-comment).

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452#-:-NUpcSZIDkGIEUg00I6u:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NUpcD3m6Hkrxdzu4JkE:-NUpcD3m6Hkrxdzu4JkF:bov9vir) (no related file):*
We have a compatibility test for contracts (the one you suggested when we started, remember?).
Can you try to make it work with the new compiler? If it's move than 5-10 mins., we'll take it (ignore post-merge failures in the meantime).

___

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 221 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV2lVYVBU4mcDkOhBuk:-NV2lVYVBU4mcDkOhBul:b-p96w87) ([raw file](https://github.com/starkware-libs/blockifier/blob/937d4c183ab146340eaef65a9d33007b4a8f4dde/crates/blockifier/src/test_utils.rs#L221)):*
> ```XML
>     let class_hash_to_class = HashMap::from([(
>         ClassHash(stark_felt!(TEST_CLASS_HASH)),
>         get_contract_class(TEST_CONTRACT_CAIRO1_PATH),
> ```

No change needed to `get_contract_class` in order to read a Cairo 1 contract?



_Code quote:_
```XML
get_contract_class(TEST_CONTRACT_CAIRO1_PATH)
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NUpcD3m6Hkrxdzu4JkE:-NV2leYDCQeSYeOub0s-:bw2jjv9) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We have a compatibility test for contracts (the one you suggested when we started, remember?).
Can you try to make it work with the new compiler? If it's move than 5-10 mins., we'll take it (ignore post-merge failures in the meantime).
</blockquote></details>

@giladchase, for visibility.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 221 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV2lVYVBU4mcDkOhBuk:-NV3Dop22WKTDdOsgvAZ:bmf8p8c) ([raw file](https://github.com/starkware-libs/blockifier/blob/937d4c183ab146340eaef65a9d33007b4a8f4dde/crates/blockifier/src/test_utils.rs#L221)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No change needed to `get_contract_class` in order to read a Cairo 1 contract?
</blockquote></details>

There are definitely changes. This PR is in progress:)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 221 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV2lVYVBU4mcDkOhBuk:-NV3POxmBlTuOLWRgV0t:bgc7vqv) ([raw file](https://github.com/starkware-libs/blockifier/blob/937d4c183ab146340eaef65a9d33007b4a8f4dde/crates/blockifier/src/test_utils.rs#L221)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

There are definitely changes. This PR is in progress:)
</blockquote></details>

:heart:

**Review by elintul — COMMENTED** [review]
> Reviewed 18 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: 18 of 21 files reviewed, all discussions resolved

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 17 of 26 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: 17 of 36 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV59bpS8CYVkI0VVLkI:-NV59bpTCwTIoBJFXfjT:bohecil) (no related file):*
LMK when to resume reviewing.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: 16 of 36 files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV59bpS8CYVkI0VVLkI:-NV8QjWE6Jg-xMx49tml:b2nhl01) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

LMK when to resume reviewing.
</blockquote></details>

Now

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 26 files at r6, 13 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: 30 of 36 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 24 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV8bLvHEksIkkTQlznS:-NV8bLvHEksIkkTQlznT:b-51k21s) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/execution/contract_class.rs#L24)):*
> ```XML
> use crate::execution::execution_utils::sn_api_to_cairo_vm_program;
> 
> #[derive(Debug, Clone, Eq, PartialEq)]
> ```

Please alphabetize, for all `#[derive(...]]` in this file.



_Code quote:_
```XML
Debug, Clone, Eq, PartialEq
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 44 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV8bh6PEZS5zhZCpUZs:-NV8bh6PEZS5zhZCpUZt:b50eaxm) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/execution/contract_class.rs#L44)):*
> ```XML
> /// We wrap the actual class in an Arc to avoid cloning the program when cloning the class.
> // Note: when deserializing from a SN API class JSON string, the ABI field is ignored
> // by serde, since it is not required for execution.
> ```

Move above `ContractClass` enum.



_Code quote:_
```XML
/// Represents a runnable StarkNet contract class (meaning, the program is runnable by the VM).
/// We wrap the actual class in an Arc to avoid cloning the program when cloning the class.
// Note: when deserializing from a SN API class JSON string, the ABI field is ignored
// by serde, since it is not required for execution.
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 73 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV8bsWS7LcZIEHOGqZh:-NV8bsWS7LcZIEHOGqZi:b6f7tom) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/execution/contract_class.rs#L73)):*
> ```XML
> }
> #[derive(Debug, Default, Clone, Eq, PartialEq, Hash)]
> pub struct EntryPointV1 {
> ```

Can't we use `cairo-lang`'s struct?



_Code quote:_
```XML
pub struct EntryPointV1
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 79 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV9-dZ6BSpFpIRg42oU:-NV9-dZ6BSpFpIRg42oV:b-pbhc0k) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/execution/contract_class.rs#L79)):*
> ```XML
> }
> 
> // TODO(spapini): Share with cairo-lang-runner.
> ```

Why not now? Does it require a refactor in `cairo-lang`?
What part of this new code will be shared?



_Code quote:_
```XML
// TODO(spapini): Share with cairo-lang-runner.
```

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 26 files at r6, 3 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: all files reviewed, 8 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 114 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV91O7Z1LHO-CC8TAhS:-NV91O7_3YVoPc0xmWbp:b-fx7my6) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/execution/contract_class.rs#L114)):*
> ```XML
>             HashMap::new(),
>             vec![],
>             None,
> ```

Can you please give the empty arguments names?



_Code quote:_
```XML
            vec![], // The builtins will be set on each call.
            data,
            Some(0),
            hints,
            ReferenceManager { references: Vec::new() },
            HashMap::new(),
            vec![],
            None,
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 134 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV91eVK3ESZgs05FCfR:-NV91eVL-8Gc5P6IB1jD:b-enrlo0) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/execution/contract_class.rs#L134)):*
> ```XML
>     }
> }
> ```

Please move utilities (outside of `impl`s) to the bottom of the file, and add headers for `V0`/`V1`.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV91vNm3FdIcFyECIl8:-NV91vNm3FdIcFyECIl9:b-83kda3) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/transaction/account_transactions_test.rs#L30)):*
> ```XML
>     let test_erc20_class_hash = ClassHash(stark_felt!(TEST_ERC20_CONTRACT_CLASS_HASH));
>     let class_hash_to_class = HashMap::from([
>         (test_account_class_hash, get_contract_class_v0(ACCOUNT_CONTRACT_PATH).into()),
> ```

Wrote in another PR too: can this function return `ContractClass`? I think that's most of its usages.



_Code quote:_
```XML
get_contract_class_v0
```

**Review by elintul — COMMENTED** [review]
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: all files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 73 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV8bsWS7LcZIEHOGqZh:-NV94x3W79mcY-qm2CKG:be1n120) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/execution/contract_class.rs#L73)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can't we use `cairo-lang`'s struct?
</blockquote></details>

It uses BigInt instead of EntryPointSelector with Starhash, and adds a lot of ocnversions inside the code.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 79 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV9-dZ6BSpFpIRg42oU:-NV9567W7yFlTRDT5VCI:b-ix6sh0) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/execution/contract_class.rs#L79)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not now? Does it require a refactor in `cairo-lang`?
What part of this new code will be shared?
</blockquote></details>

It's already there, but it's not pub.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV91vNm3FdIcFyECIl8:-NV96Gn24oK1yjIXU-OT:b4u29xr) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/transaction/account_transactions_test.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Wrote in another PR too: can this function return `ContractClass`? I think that's most of its usages.
</blockquote></details>

Yes, but it loses information which is a bit unfortunate. What if a consumer needs exactly a class v0?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/452#-:-NV96urp5BdHpUxKlt1X:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/452#-NV91vNm3FdIcFyECIl8:-NV96nNL5cYLR05t_DiA:b-71wd6p) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed3a5fd74e96e25632feb66daa667e76f4e7a92/crates/blockifier/src/transaction/account_transactions_test.rs#L30)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Yes, but it loses information which is a bit unfortunate. What if a consumer needs exactly a class v0?
</blockquote></details>

I think it happens much less then those `.into()`-s.

**Pull request merged**
