### PR TITLE
Add Declare and DeployAccount tx to AccountTransaction enum.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/206)

### CODE REVIEW

**Review by Adi-Yakovian — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/206)* status: 1 of 7 files reviewed, 25 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMT7k7YBmC2ia_yhsTA:-NMT7k7YBmC2ia_yhsTB:bagp2sy) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L81)):*
> ```XML
> }
> 
> fn build_expected_validate_call_info(
> ```

Consider removing the `build` prefix in these functions (not sure if it's better, your call :)).



_Code quote:_
```XML
build_
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTS-7o7IiEfSqC3IVx:-NMTS-7o7IiEfSqC3IVy:b-xdtb5a) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L90)):*
> ```XML
>             class_hash: None,
>             entry_point_type: EntryPointType::External,
>             entry_point_selector: get_selector(entry_point_selector_name),
> ```

I wonder how it works, as I renamed it to `selector_from_name` on Thursday... Checking.



_Code quote:_
```XML
get_selector
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTO79R60MlhKbBPdiE:-NMTO79R60MlhKbBPdiF:bxnypll) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L103)):*
> ```XML
> fn build_expected_fee_transfer_call_info(
>     block_context: &BlockContext,
>     expected_account_address: ContractAddress,
> ```

Consider losing the `expected` prefix to be consistent with the parameter naming of `build_expected_validate_call_info`. I'm still not sure what's better.



_Suggestion:_
```XML
    account_address: ContractAddress,
    actual_fee: Fee,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMT8KnR91n5jYrgY_fO:-NMT8KnR91n5jYrgY_fP:b-h7k21s) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L106)):*
> ```XML
>     expected_actual_fee: Fee,
> ) -> CallInfo {
>     // Build expected fee transfer call info.
> ```

(as it is embedded in the function name now)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTQLEP0TEfvqeUjK07:-NMTQLEP0TEfvqeUjK08:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L146)):*
> ```XML
>     block_context: &BlockContext,
>     expected_sequencer_balance: StarkFelt,
>     test_erc20_account_balance_key: &str,
> ```





_Suggestion:_
```XML
erc20_account_balance_key
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTXMkr3kshMxHEY86b:-NMTXMkr3kshMxHEY86c:bww3327) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L148)):*
> ```XML
>     test_erc20_account_balance_key: &str,
> ) {
>     let expected_account_balance = stark_felt!(0);
> ```

I'm not sure it belongs inside this function, as it theoretically may change.
However, I think this function will be modified to `validate_balances` later (so we can also validate the previous balance), so maybe we can wait with it. Whatever you decide.



_Code quote:_
```XML
let expected_account_balance = stark_felt!(0);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTUCh02Bd9pOV2kBTY:-NMTUCh02Bd9pOV2kBTZ:bv3raph) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L191)):*
> ```XML
> fn test_invoke_tx() {
>     let mut state = create_account_tx_test_state();
>     let block_context = BlockContext::create_for_testing();
> ```

Maybe a reference always suffices? (and then we can lose the reference addition elsewhere)



_Suggestion:_
```XML
let block_context = &BlockContext::create_for_testing()
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTSexPAvFxLMGW8CpP:-NMTSexPAvFxLMGW8CpQ:bka33xb) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L194)):*
> ```XML
>     let invoke_tx = invoke_tx();
>     // Extract invoke transaction fields for testing, as it is consumed when creating
>     // `AccountTransaction`.
> ```

(following Elin's comments)



_Suggestion:_
```XML
an account transaction.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTVjJm3v14Tx_aes_a:-NMTVjJm3v14Tx_aes_b:blm0rva) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L245)):*
> ```XML
>     let expected_execution_info = TransactionExecutionInfo {
>         validate_call_info: expected_validate_call_info,
>         execute_call_info: Some(expected_execute_call_info),
> ```

*Consider* moving the `Some` to `expected_execute_call_info`, following one of Elin's comment.
Not sure that it's better in this case.



_Code quote:_
```XML
Some
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTWL9qCNDTGN3LQVNa:-NMTWL9qCNDTGN3LQVNb:bpes68k) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L259)):*
> ```XML
>     // Test final balances.
>     validate_final_balances(
>         &mut state,
> ```

Similar to the `block_context` - maybe we can have the initial state be a mutable reference to the returned state and then lose the `&mut` addition elsewhere?



_Code quote:_
```XML
&mut state
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTWran4qiB026-ZAcN:-NMTWran4qiB026-ZAcO:b-jbyt21) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L261)):*
> ```XML
>         &mut state,
>         &block_context,
>         stark_felt!(expected_actual_fee.0 as u64),
> ```

I think we should still define a variable holding this value (named `expected_sequencer_balance`) solely for readability.



_Code quote:_
```XML
stark_felt!(expected_actual_fee.0 as u64)
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTYCuGCNcdpuLyY3HU:-NMTYCuGCNcdpuLyY3HV:b-ohetdg) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L336)):*
> ```XML
> #[test]
> fn test_declare_tx() {
>     let mut state = create_account_tx_test_state();
> ```

Same as my comments in invoke.



_Code quote:_
```XML
    let mut state = create_account_tx_test_state();
    let block_context = BlockContext::create_for_testing();
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTYUNZ1EDCQ2LU81hn:-NMTYUNZ1EDCQ2LU81ho:b-dvwr8s) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L340)):*
> ```XML
>     let declare_tx = declare_tx();
>     // Extract declare transaction fields for testing, as it is consumed when creating
>     // `AccountTransaction`.
> ```

Same as in invoke.



_Suggestion:_
```XML
an account transaction
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTZus35Id9Z8y8Xcws:-NMTZus4DJ7mhvaiz3uQ:b-dvwr8s) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L381)):*
> ```XML
>         &mut state,
>         &block_context,
>         stark_felt!(expected_actual_fee.0 as u64),
> ```

Same as in invoke.



_Code quote:_
```XML
stark_felt!(expected_actual_fee.0 as u64)
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 413 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTZzrE6576KYJiItAA:-NMTZzrE6576KYJiItAB:b-dvwr8s) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L413)):*
> ```XML
> fn test_deploy_account_tx() {
>     let mut state = create_account_tx_test_state();
>     let block_context = BlockContext::create_for_testing();
> ```

Same as in invoke.



_Code quote:_
```XML
    let mut state = create_account_tx_test_state();
    let block_context = BlockContext::create_for_testing();
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMT_AEz1DuggoZupUsG:-NMT_AF-1htam_5tJg6S:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L416)):*
> ```XML
>     let deploy_account_tx = deploy_account_tx();
>     // Extract deploy account transaction fields for testing, as it is consumed when creating
>     // `AccountTransaction`.
> ```





_Suggestion:_
```XML
an account transaction
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 422 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMT_Ysi7G7Lw76KQN_4:-NMT_Ysi7G7Lw76KQN_5:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L422)):*
> ```XML
>     let salt = deploy_account_tx.contract_address_salt;
> 
>     // Update the balance of the about to be deployed account contract in the erc20 contract.
> ```





_Suggestion:_
```XML
// Update the balance of the about to be deployed account contract in the erc20 contract, so it can pay for the transaction execution.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 434 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTajxe2ZsbiO7Ofnmj:-NMTajxf20eroM9V4aoA:bwiasni) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L434)):*
> ```XML
> 
>     // Build expected validate call info.
>     let mut validate_calldata_vec = vec![class_hash.0, salt.0];
> ```

Maybe you can use `concat` here as well?

Anyway, avoid using implementation-specific names (i.e., `vec`), unless it is necessary :)
(I totally understand why it bothered you, though. I simply think that it is okay the lose the `vec` suffix in this case)



_Code quote:_
```XML
    let mut validate_calldata_vec = vec![class_hash.0, salt.0];
    validate_calldata_vec.extend(&(*constructor_calldata.0));
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 439 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTbN2oBQ1v_uKTZKjf:-NMTbN2oBQ1v_uKTZKjg:b-58wbtw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L439)):*
> ```XML
>     let expected_validate_call_info = build_expected_validate_call_info(
>         VALIDATE_DEPLOY_ENTRY_POINT_NAME,
>         Calldata(Arc::new(validate_calldata_vec)),
> ```

In another PR we decided to avoid specifying the `Arc`, and use `into`. I'll make sure with Gilad, and if it is so, I'll ask him to write it in our channel. 



_Code quote:_
```XML
Arc::new(validate_calldata_vec)
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 463 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTcKAQ1DJ21C5BA05r:-NMTcKAQ1DJ21C5BA05s:b-dvwr8s) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L463)):*
> ```XML
>     let expected_execution_info = TransactionExecutionInfo {
>         validate_call_info: expected_validate_call_info,
>         execute_call_info: Some(expected_execute_call_info),
> ```

Same as in invoke.



_Code quote:_
```XML
Some(expected_execute_call_info)
```

**Review by Adi-Yakovian — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/206)* status: 3 of 7 files reviewed, 26 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTvvXe3AuKxEKcEels:-NMTvvXe3AuKxEKcEelt:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1bc53459fb1b050c53723704ddaedb2b18f78869/crates/blockifier/src/transaction/transactions.rs#L34)):*
> ```XML
>     }
>     // Calldata for validation contains only the hash of the declared class (a parameter of the
>     // transaction that cannot be obtain using `get_tx_info()`).
> ```





_Suggestion:_
```XML
obtained
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTw0MC1NIYBJnMISwZ:-NMTw0MC1NIYBJnMISw_:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1bc53459fb1b050c53723704ddaedb2b18f78869/crates/blockifier/src/transaction/transactions.rs#L64)):*
> ```XML
> 
>     /// Calldata for validation contains class_hash, salt and constructor_calldata (parameters of
>     /// the transaction that cannot be obtain using `get_tx_info()`).
> ```





_Suggestion:_
```XML
obtained
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/206)* status: 3 of 7 files reviewed, 11 unresolved discussions (waiting on @Adi-Yakovian and @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTvvXe3AuKxEKcEels:-NMTzIvD95nxcFKmQTJL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1bc53459fb1b050c53723704ddaedb2b18f78869/crates/blockifier/src/transaction/transactions.rs#L34)):*
> ```XML
>     }
>     // Calldata for validation contains only the hash of the declared class (a parameter of the
>     // transaction that cannot be obtain using `get_tx_info()`).
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTw0MC1NIYBJnMISwZ:-NMTzJAf7a2MF4U7966b:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1bc53459fb1b050c53723704ddaedb2b18f78869/crates/blockifier/src/transaction/transactions.rs#L64)):*
> ```XML
> 
>     /// Calldata for validation contains class_hash, salt and constructor_calldata (parameters of
>     /// the transaction that cannot be obtain using `get_tx_info()`).
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMT8KnR91n5jYrgY_fO:-NMTm-E61Vf3dPwtmuN7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L106)):*
<details><summary><i>Previously, Adi-Yakovian wrote…</i></summary><blockquote>

(as it is embedded in the function name now)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTSexPAvFxLMGW8CpP:-NMToslY4j4fUPx-YAyR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L194)):*
<details><summary><i>Previously, Adi-Yakovian wrote…</i></summary><blockquote>

(following Elin's comments)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 422 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMT_Ysi7G7Lw76KQN_4:-NMTrpMN7MMqxzpf99Ic:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L422)):*
> ```XML
>     let salt = deploy_account_tx.contract_address_salt;
> 
>     // Update the balance of the about to be deployed account contract in the erc20 contract.
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 434 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMTajxe2ZsbiO7Ofnmj:-NMTsbttDBShOnhj2JS4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b16d3ba21b12e9301605a265eee528c7e1f7dfe/crates/blockifier/src/transaction/transactions_test.rs#L434)):*
<details><summary><i>Previously, Adi-Yakovian wrote…</i></summary><blockquote>

Maybe you can use `concat` here as well?

Anyway, avoid using implementation-specific names (i.e., `vec`), unless it is necessary :)
(I totally understand why it bothered you, though. I simply think that it is okay the lose the `vec` suffix in this case)
</blockquote></details>

Done.

**Review by Adi-Yakovian — COMMENTED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/206)* status: 4 of 7 files reviewed, 9 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 149 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMUB0NCEkRwsPMolRhR:-NMUB0NCEkRwsPMolRhS:batpfvr) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d59a2ff7cdce3156dc9a758753e00c84a3076ad/crates/blockifier/src/transaction/transactions_test.rs#L149)):*
> ```XML
>     erc20_account_balance_key: &str,
> ) {
>     // We currently assume the total fee charged for the transaction is equal to the initial balance
> ```

If you can, write somewhere a TODO to remove this comment later :)



_Code quote:_
```XML
    // We currently assume the total fee charged for the transaction is equal to the initial balance
    // of the account.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMUFdls2iU6dEt0W2TW:-NMUFdls2iU6dEt0W2TX:b-jahhod) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d59a2ff7cdce3156dc9a758753e00c84a3076ad/crates/blockifier/src/transaction/transactions_test.rs#L193)):*
> ```XML
> #[test]
> fn test_invoke_tx() {
>     let state = &mut create_account_tx_test_state();
> ```

I might be missing something, as it doesn't look like there is an extra line break, but then when I tried to mark these lines it seemed like there is.

Anyway, now that I went over the code without my comments, it seemed to me that we should separate these code sections (I added a suggestion in the other tests as well).
It's not a must, and a matter of taste, so feel free to disregard it :)



_Suggestion:_
```XML
    let state = &mut create_account_tx_test_state();
    let block_context = &BlockContext::create_for_testing();
    let invoke_tx = invoke_tx();

    // Extract invoke transaction fields for testing, as it is consumed when creating an account
    // transaction.
    let calldata = Calldata(Arc::clone(&invoke_tx.calldata.0));
    let sender_address = invoke_tx.sender_address;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 337 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMUFPCk9pK3OhfNMaAQ:-NMUFPCk9pK3OhfNMaAR:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d59a2ff7cdce3156dc9a758753e00c84a3076ad/crates/blockifier/src/transaction/transactions_test.rs#L337)):*
> ```XML
> #[test]
> fn test_declare_tx() {
>     let state = &mut create_account_tx_test_state();
> ```





_Suggestion:_
```XML
    let state = &mut create_account_tx_test_state();
    let block_context = &BlockContext::create_for_testing();
    let declare_tx = declare_tx();
    
    // Extract declare transaction fields for testing, as it is consumed when creating an account
    // transaction.
    let sender_address = declare_tx.sender_address;
    let class_hash = declare_tx.class_hash.0;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 417 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/206#-NMUDr1P7eNXWnjv7FQQ:-NMUDr1P7eNXWnjv7FQR:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d59a2ff7cdce3156dc9a758753e00c84a3076ad/crates/blockifier/src/transaction/transactions_test.rs#L417)):*
> ```XML
>     let deploy_account_tx = deploy_account_tx();
>     // Extract deploy account transaction fields for testing, as it is consumed when creating an
>     // account transaction.
> ```





_Suggestion:_
```XML
    
    // Extract deploy account transaction fields for testing, as it is consumed when creating an
    // account transaction.
    let class_hash = deploy_account_tx.class_hash;
    let deployed_account_address = deploy_account_tx.contract_address;
    let constructor_calldata = deploy_account_tx.constructor_calldata.clone();
    let salt = deploy_account_tx.contract_address_salt;
```

**Pull request merged**
