### PR TITLE
feat: add merge_branches script

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @dorimedini-starkware, @liorgold2, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOM_p3M7ANr6LwdUd:-NqfOM_p3M7ANr6LwdUe:b-wugcpa) (no related file):*
Please rebase over `main-v0.13.1`.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOU5kDErP7sqIvMNa:-NqfOU5kDErP7sqIvMNb:bcwlk24) (no related file):*
I think you need to add `paernt_branch.txt` to each master branch.

___
___
*[`scripts/merge_branches.py` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOfaV12nvnU6JrZ7J:-NqfOfaV12nvnU6JrZ7K:b-ciom25) ([raw file](https://github.com/starkware-libs/blockifier/blob/428ea93489d2e157a7a6611d8c21aa9ace15c857/scripts/merge_branches.py#L16)):*
> ```Python
> from typing import Dict, List, Optional
> 
> FINAL_BRANCH = "dev"
> ```

Unused.



_Code quote:_
```Python
FINAL_BRANCH = "dev"
```
___
*[`scripts/merge_paths.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOhtXAjJBkjPa6jrY:-NqfOhtXAjJBkjPa6jrZ:bxadxu8) ([raw file](https://github.com/starkware-libs/blockifier/blob/428ea93489d2e157a7a6611d8c21aa9ace15c857/scripts/merge_paths.json#L1)):*
> ```JSON
> {
> ```

Consider also porting the test of this file.

**Comment by barak-b-starkware** [comment]
*[`scripts/merge_branches.py` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOfaV12nvnU6JrZ7J:-NqfiPsh3ktEfnX-7kzS:bj6mld8) ([raw file](https://github.com/starkware-libs/blockifier/blob/428ea93489d2e157a7a6611d8c21aa9ace15c857/scripts/merge_branches.py#L16)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Changed to `main`.
Used here:



_Code quote:_
```Python
def get_dst_branch(src_branch: str, dst_branch_override: Optional[str]) -> str:
    if dst_branch_override is not None:
        return dst_branch_override
    assert (
        src_branch.replace("origin/", "") != FINAL_BRANCH
    ), f"{FINAL_BRANCH} has no default destination branch."

    dst_branch = load_merge_paths()[src_branch]
    assert dst_branch != NULL, f"Default merge path is disabled for {src_branch}."
    return dst_branch
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: all files reviewed, 10 unresolved discussions (waiting on @barak-b-starkware, @elintul, @liorgold2, and @Yoni-Starkware)

___
*[`scripts/merge_branches.py` line 6 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfsmiZ9kP22WORBTtN:-NqfsmiZ9kP22WORBTtO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L6)):*
> ```Python
> Merge a branch into another branch. Example usage:
> ```
> scripts/merge_branches.py --src cairo-v0.12.2
> ```





_Suggestion:_
```Python
scripts/merge_branches.py --src main-v0.13.0
```
___
*[`scripts/merge_branches.py` line 17 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfsqPHCXpCE8tzR4Cp:-NqfsqPHCXpCE8tzR4Cq:brapb21) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L17)):*
> ```Python
> 
> FINAL_BRANCH = "main"
> MERGE_PATHS_FILE = "scripts/merge/merge_paths.json"
> ```

no `merge` directory AFAIK



_Suggestion:_
```Python
"scripts/merge_paths.json"
```
___
*[`scripts/merge_branches.py` line 18 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfsHCi37056ePNmDfZ:-NqfsHCi37056ePNmDf_:bbulica) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L18)):*
> ```Python
> FINAL_BRANCH = "main"
> MERGE_PATHS_FILE = "scripts/merge/merge_paths.json"
> NULL = "null"
> ```

do we need a `null` target in the blockifier repo? I think we have linear merges only (merge graph is a line graph) in this repo, right? I think this (and usages) can be deleted



_Code quote:_
```Python
NULL = "null"
```
___
*[`scripts/merge_branches.py` line 54 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqftCcT22D2LEGch8WK:-NqftCcT22D2LEGch8WL:b6vkjgj) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L54)):*
> ```Python
>     dst_branch = load_merge_paths()[src_branch]
>     assert dst_branch != NULL, f"Default merge path is disabled for {src_branch}."
>     return dst_branch
> ```

see above (no point in NULL)



_Suggestion:_
```Python
    return load_merge_paths()[src_branch]
```
___
*[`scripts/merge_branches.py` line 76 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqftOXx5Uy3uuydawQJ:-NqftOXx5Uy3uuydawQK:b-m0kqg3) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L76)):*
> ```Python
>         f"git diff $(git merge-base origin/{source_branch} origin/{destination_branch}) "
>         f"origin/{destination_branch} {files_line}"
>     )
> ```

code dup, but it's copied from python side (my fault) so I'll allow it (me? mistakes? never)



_Code quote:_
```Python
def srcdiff(source_branch: str, destination_branch: Optional[str], files: List[str]):
    destination_branch = get_dst_branch(
        src_branch=source_branch, dst_branch_override=destination_branch
    )
    files_line = " ".join(files)
    run_command(
        f"git diff $(git merge-base origin/{source_branch} origin/{destination_branch}) "
        f"origin/{source_branch} {files_line}"
    )


def dstdiff(source_branch: str, destination_branch: Optional[str], files: List[str]):
    destination_branch = get_dst_branch(
        src_branch=source_branch, dst_branch_override=destination_branch
    )
    files_line = " ".join(files)
    run_command(
        f"git diff $(git merge-base origin/{source_branch} origin/{destination_branch}) "
        f"origin/{destination_branch} {files_line}"
    )
```
___
*[`scripts/merge_branches.py` line 127 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-Nqftpm97Ns9ztvofjJe:-Nqftpm97Ns9ztvofjJf:bjlaxey) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L127)):*
> ```Python
> 
>     if len(conflicts) != 0:
>         compare = "https://github.com/starkware-industries/starkware/compare"
> ```

incorrect URL I think



_Code quote:_
```Python
"https://github.com/starkware-industries/starkware/compare"
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: all files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @liorgold2, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOM_p3M7ANr6LwdUd:-Nqg2H1v-tPZN0OIxv-r:b-205269) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please rebase over `main-v0.13.1`.
</blockquote></details>

As discussed in Slack, in order to merge `main-v0.13.1` to `main` we need the script in `main`. and since we will branch out to `main-v0.13.2` from `main` it's better to merge the script to `main`.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOU5kDErP7sqIvMNa:-Nqg3ofDB4IR5lLFT4nN:b3y38kt) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think you need to add `paernt_branch.txt` to each master branch.
</blockquote></details>

AFAIU, the "parent branch" mechanism, is not used in the `blockifier` repo, do you still want to add it?

___
___
*[`scripts/merge_branches.py` line 6 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfsmiZ9kP22WORBTtN:-Nqg-j6g3oj8KUQGn5nv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L6)):*
> ```Python
> Merge a branch into another branch. Example usage:
> ```
> scripts/merge_branches.py --src cairo-v0.12.2
> ```

Done.
___
*[`scripts/merge_branches.py` line 17 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfsqPHCXpCE8tzR4Cp:-Nqg-nJU2UKjt3tSMZrd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no `merge` directory AFAIK
</blockquote></details>

Done.
___
*[`scripts/merge_branches.py` line 18 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfsHCi37056ePNmDfZ:-Nqg01Qa8cnTL57_KF7o:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do we need a `null` target in the blockifier repo? I think we have linear merges only (merge graph is a line graph) in this repo, right? I think this (and usages) can be deleted
</blockquote></details>

Done.
___
*[`scripts/merge_branches.py` line 54 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqftCcT22D2LEGch8WK:-Nqg08Lz7U70cGhpzt4H:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above (no point in NULL)
</blockquote></details>

Done.
___
*[`scripts/merge_branches.py` line 127 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-Nqftpm97Ns9ztvofjJe:-Nqg2DiVCHpandnpxOOm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/462178582fb6b1b4e87d0f94f7ddf9d60bf43162/scripts/merge_branches.py#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

incorrect URL I think
</blockquote></details>

Done.
___
*[`scripts/merge_paths.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOhtXAjJBkjPa6jrY:-Nqg45YYCkjSEnri-DmH:b-g8obhb) ([raw file](https://github.com/starkware-libs/blockifier/blob/428ea93489d2e157a7a6611d8c21aa9ace15c857/scripts/merge_paths.json#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider also porting the test of this file.
</blockquote></details>

What is the behavior we want? Should it run somehow with `cargo test`? or do you just want it to be there so people can test it from time to time?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @elintul, @liorgold2, and @Yoni-Starkware)

___
*[`scripts/merge_paths.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOhtXAjJBkjPa6jrY:-NqgFP6R0qN56fBxNUCC:b-88a3bt) ([raw file](https://github.com/starkware-libs/blockifier/blob/428ea93489d2e157a7a6611d8c21aa9ace15c857/scripts/merge_paths.json#L1)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

What is the behavior we want? Should it run somehow with `cargo test`? or do you just want it to be there so people can test it from time to time?
</blockquote></details>

IMO you only need to load the JSON, and in the blockifier case, assert that the graph is a linear graph that ends at branch `main`

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @elintul, @liorgold2, and @Yoni-Starkware)

___
*[`scripts/merge_paths.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOhtXAjJBkjPa6jrY:-NqgT8ji9B85uWxstzLI:bad8hyb) ([raw file](https://github.com/starkware-libs/blockifier/blob/428ea93489d2e157a7a6611d8c21aa9ace15c857/scripts/merge_paths.json#L1)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Do you think the CI should run the test? (is this what happens in the Python repo?)
</blockquote></details>

yes. IF someone edits the JSON in a bad way, CI should catch it. It's a very fast test, I don't see it as an issue

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @elintul, @liorgold2, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqfOU5kDErP7sqIvMNa:-NqgTNNYDG6Gz8MHngds:bclh28z) (no related file):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

AFAIU, the "parent branch" mechanism, is not used in the `blockifier` repo, do you still want to add it?
</blockquote></details>

I don't see why we need the parent_branch.txt file, @elintul do you?

___

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-:-Nqh6xSXCKF0zSOUU1tT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2 and @Yoni-Starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @liorgold2, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 69 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-Nqh44JGCQpXz-QtnXmZ:-Nqh44JGCQpXz-QtnXm_:b-2hp1a) ([raw file](https://github.com/starkware-libs/blockifier/blob/282574a72f2dffcb6d453f94be6092b72be7efbe/.github/workflows/ci.yml#L69)):*
> ```YAML
>         with:
>           python-version: '3.9'
>       - run: scripts/merge_paths_test.py
> ```

maybe this should be a separate phase? You don't need python for anything else



_Code quote:_
```YAML
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: scripts/merge_paths_test.py
```
___
*[`scripts/merge_paths_test.py` line 12 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-Nqh6U1-AnWlhJTb39Vy:-Nqh6U1-AnWlhJTb39Vz:b-cr3vw4) ([raw file](https://github.com/starkware-libs/blockifier/blob/282574a72f2dffcb6d453f94be6092b72be7efbe/scripts/merge_paths_test.py#L12)):*
> ```Python
> 
>     src_dst_iter = iter(merge_paths.items())
>     (_, prev_dst_branch) = next(src_dst_iter)
> ```

or `if ... sys.exit(1)` if needed (if it is needed, consider adding an `if_then_exit(condition, text)` utility function)



_Suggestion:_
```Python
(oldest_branch, prev_dst_branch) = next(src_dst_iter)
assert oldest_branch not in merge_paths.values(), f"Oldest branch ({oldest_branch}) cannot be a target."
```
___
*[`scripts/merge_paths_test.py` line 20 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-Nqh6izp7Ad15C13mN8s:-Nqh6izp7Ad15C13mN8t:byut10g) ([raw file](https://github.com/starkware-libs/blockifier/blob/282574a72f2dffcb6d453f94be6092b72be7efbe/scripts/merge_paths_test.py#L20)):*
> ```Python
>                 f"out {MERGE_PATHS_FILE}."
>             )
>             sys.exit(1)
> ```

why `if ... sys.exit(1)` and not `assert`?



_Code quote:_
```Python
        if prev_dst_branch != src_branch:
            print(
                f"Since the merge graph is linear, the source branch '{src_branch}' must be the "
                f"same as the previous destination branch, which is '{prev_dst_branch}'. Check "
                f"out {MERGE_PATHS_FILE}."
            )
            sys.exit(1)
```
___
*[`scripts/merge_paths_test.py` line 25 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-Nqh7-1G4YmI2NAGjFBn:-Nqh7-1G4YmI2NAGjFBo:bmsmkvo) ([raw file](https://github.com/starkware-libs/blockifier/blob/282574a72f2dffcb6d453f94be6092b72be7efbe/scripts/merge_paths_test.py#L25)):*
> ```Python
>     if prev_dst_branch != FINAL_BRANCH:
>         print(f"The last destination is {prev_dst_branch} but must be {FINAL_BRANCH}.")
>         sys.exit(1)
> ```

same question as above



_Code quote:_
```Python
    if prev_dst_branch != FINAL_BRANCH:
        print(f"The last destination is {prev_dst_branch} but must be {FINAL_BRANCH}.")
        sys.exit(1)
```

**Comment by barak-b-starkware** [comment]
*[`scripts/merge_paths_test.py` line 20 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-Nqh6izp7Ad15C13mN8s:-Nqh7o4V7GKJwfi_KNSH:b-m6b2pc) ([raw file](https://github.com/starkware-libs/blockifier/blob/282574a72f2dffcb6d453f94be6092b72be7efbe/scripts/merge_paths_test.py#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why `if ... sys.exit(1)` and not `assert`?
</blockquote></details>

This is how you implemented it in the Pythonic repo [here](https://github.com/starkware-industries/starkware/commit/98d34273cdbd103e4efd568a74c903b70d854df8).

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @liorgold2, and @Yoni-Starkware)

___
*[`scripts/merge_paths_test.py` line 20 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-Nqh6izp7Ad15C13mN8s:-Nqh89BPDzT8-qxXIuyn:b-dremoj) ([raw file](https://github.com/starkware-libs/blockifier/blob/282574a72f2dffcb6d453f94be6092b72be7efbe/scripts/merge_paths_test.py#L20)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

This is how you implemented it in the Pythonic repo [here](https://github.com/starkware-industries/starkware/commit/98d34273cdbd103e4efd568a74c903b70d854df8).
</blockquote></details>

Right, I am not sure this is needed here.
1. Please try changing to `assert` and messing up the JSON, see if the CI fails.
2. If `assert` doesn't cause CI failures:
2a. See if running this test with `pytest` instead of `python` is easy to add to the CI; this should be better, and provide nicer printouts in CI on failures. This should also make the `assert` fail, IIUC.
2b. If it's not easy to add `pytest` in the CI, please add a TODO in the test / in the workflow file (I think it's a good idea in general, if we're testing python related code in the repo), and implement an `if_then_exit` function as I mentioned above

**Comment by barak-b-starkware** [comment]
*[`scripts/merge_paths_test.py` line 20 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-Nqh6izp7Ad15C13mN8s:-Nqh9g-c-NRiuWjGULk0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/282574a72f2dffcb6d453f94be6092b72be7efbe/scripts/merge_paths_test.py#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Right, I am not sure this is needed here.
1. Please try changing to `assert` and messing up the JSON, see if the CI fails.
2. If `assert` doesn't cause CI failures:
2a. See if running this test with `pytest` instead of `python` is easy to add to the CI; this should be better, and provide nicer printouts in CI on failures. This should also make the `assert` fail, IIUC.
2b. If it's not easy to add `pytest` in the CI, please add a TODO in the test / in the workflow file (I think it's a good idea in general, if we're testing python related code in the repo), and implement an `if_then_exit` function as I mentioned above
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @liorgold2, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 65 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqhAzyd5JMCAurRS9RG:-NqhAzyd5JMCAurRS9RH:b8c9fmh) ([raw file](https://github.com/starkware-libs/blockifier/blob/02b0db96c028c37c0ed0d6aa537e470060c8adca/.github/workflows/ci.yml#L65)):*
> ```YAML
>         with:
>           python-version: '3.9'
>       - run: scripts/merge_paths_test.py
> ```

did you mess up the JSON and make sure the CI runs the tests and blocks merging?



_Code quote:_
```YAML
  merge-paths-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: scripts/merge_paths_test.py
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @elintul, @liorgold2, and @Yoni-Starkware)

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @elintul, @liorgold2, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 69 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-Nqh44JGCQpXz-QtnXmZ:-NqhQmvl3kPKE78lNsXL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/282574a72f2dffcb6d453f94be6092b72be7efbe/.github/workflows/ci.yml#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe this should be a separate phase? You don't need python for anything else
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 65 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-NqhAzyd5JMCAurRS9RG:-NqhP_vL8IqRzWntxGgX:b-5kftlz) ([raw file](https://github.com/starkware-libs/blockifier/blob/02b0db96c028c37c0ed0d6aa537e470060c8adca/.github/workflows/ci.yml#L65)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

did you mess up the JSON and make sure the CI runs the tests and blocks merging?
</blockquote></details>

[prev_dst_branch == FINAL_BRANCH](https://github.com/starkware-libs/blockifier/actions/runs/7918421029/job/21616787536?pr=1513) failure
[prev_dst_branch == src_branch](https://github.com/starkware-libs/blockifier/actions/runs/7918449797/job/21616887469?pr=1513) failure
[oldest_branch not in merge_paths.values()](https://github.com/starkware-libs/blockifier/actions/runs/7918475410/job/21616977106?pr=1513) failure

and it's a required step right now (i.e., blocking).

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2 and @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1513#-:-NqhRtrW9HJ_OeI2g4nQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2 and @Yoni-Starkware)

**Pull request merged**
