### PR TITLE
Insert send message to L1 command to both validate and execute. For P…

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…R #601 debug.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXsaHko425wnINd0odt:-NXsaHkp1S0bu4-_UKk3:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/8b1f7fd98f9fb1e597eaf781b3a70c71abaf722b/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L79)):*
> ```Cairo
>     let scenario = tx_info.signature[0];
> 
>     // Maybe add a flag for the sendMsgToL1 in validate.
> ```

Why?



_Suggestion:_
```Cairo
// TODO(Mohammad,21/07/2023): Consider adding a flag to test sending messages to l1 in validate.
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXqT5YLEWb4Qed4N8QA:-NXqT5YLEWb4Qed4N8QB:b-945dn3) ([raw file](https://github.com/starkware-libs/blockifier/blob/8b1f7fd98f9fb1e597eaf781b3a70c71abaf722b/crates/blockifier/src/execution/entry_point.rs#L222)):*
> ```XML
>         for call in self.into_iter() {
>             for ordered_message_content in &call.execution.l2_to_l1_messages {
>                 if ordered_message_content.order >= n_messages {
> ```

Please define a variable 



_Code quote:_
```XML
ordered_message_content.order
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXsaHko425wnINd0odt:-NXsmtuy91jiRgXpiIl0:b-tpr9v2) ([raw file](https://github.com/starkware-libs/blockifier/blob/8b1f7fd98f9fb1e597eaf781b3a70c71abaf722b/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L79)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Actually, I'm not sure if we should add such a flag.
BTW, why in 21/7?
___
*[`crates/blockifier/src/execution/entry_point.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXqT5YLEWb4Qed4N8QA:-NXsmmbd1HjzYETp8OJY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8b1f7fd98f9fb1e597eaf781b3a70c71abaf722b/crates/blockifier/src/execution/entry_point.rs#L222)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please define a variable 
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXsaHko425wnINd0odt:-NXtpbc05dEh_yJBIhrC:btthg0a) ([raw file](https://github.com/starkware-libs/blockifier/blob/8b1f7fd98f9fb1e597eaf781b3a70c71abaf722b/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L79)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Actually, I'm not sure if we should add such a flag.
BTW, why in 21/7?
</blockquote></details>

The flag will affect only validate (and not `__execute___`) so I'm not sure what we're trying to achieve with it.
And I made a rough estimation :)
___
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 48 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXtrLQ3EBFjuVQr2b0Y:-NXtrLQ3EBFjuVQr2b0Z:b-thjxo3) ([raw file](https://github.com/starkware-libs/blockifier/blob/701cd65f755bd78a7cc34d88670807a0d4f4ed5f/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L48)):*
> ```Cairo
>     let to_address = 0;
> 
>     send_message_to_l1(to_address, calldata_len, calldata);
> ```

Can you please add a brief documentation of why we call it?



_Code quote:_
```Cairo
 send_message_to_l1(to_address, calldata_len, calldata);
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 226 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXtsAUbDv4QU7Aagz2M:-NXtsAUbDv4QU7Aagz2N:b-9qh6jj) ([raw file](https://github.com/starkware-libs/blockifier/blob/701cd65f755bd78a7cc34d88670807a0d4f4ed5f/crates/blockifier/src/execution/entry_point.rs#L226)):*
> ```XML
>                     return Err(TransactionExecutionError::UnexpectedHoles {
>                         object: "L2-to-L1 message".to_string(),
>                         order: message_order,
> ```

Note that the `TransactionExecutionError::UnexpectedHoles` error message is not quite appropriate in this case. Try to generalize it or think of another solution :)



_Code quote:_
```XML
                    return Err(TransactionExecutionError::UnexpectedHoles {
                        object: "L2-to-L1 message".to_string(),
                        order: message_order,
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXtsdO04UCCQ0EvsMpZ:-NXtsdO04UCCQ0EvsMp_:brhumzt) ([raw file](https://github.com/starkware-libs/blockifier/blob/701cd65f755bd78a7cc34d88670807a0d4f4ed5f/crates/blockifier/src/execution/entry_point.rs#L238)):*
> ```XML
>                 return Err(TransactionExecutionError::UnexpectedHoles {
>                     object: "L2-to-L1 message".to_string(),
>                     order: i,
> ```

Same here.



_Code quote:_
```XML
                return Err(TransactionExecutionError::UnexpectedHoles {
                    object: "L2-to-L1 message".to_string(),
                    order: i,
```

**Review by giladchase — CHANGES_REQUESTED** [review]
Should we add a unit test for this method? WDYT @noaov1 @MohammadNassar1 ?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606#-:-NXyMT-c46H7Tb-AA3Hv:b-9caijb)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXyJrYr4_75KXM7VhDt:-NXyJrYs4kAvvsv8JwKE:bgidl3z) ([raw file](https://github.com/starkware-libs/blockifier/blob/701cd65f755bd78a7cc34d88670807a0d4f4ed5f/crates/blockifier/src/execution/entry_point.rs#L243)):*
> ```XML
>         }
> 
>         Ok(starknet_l2_to_l1_payloads_length.into_iter().flatten().collect())
> ```

No need to iterate twice over the collection, it can be done using a single iteration. Possible implementation below (haven't tested it though).
There might be something better though (consider using chatGPT to investigate).



_Suggestion:_
```XML
        starknet_l2_to_l1_payloads_length.into_iter().enumerate().try_fold(
            Vec::new(),
            |mut acc, (i, option)| match option {
                Some(value) => {
                    acc.push(value);
                    Ok(acc)
                }
                None => Err(TransactionExecutionError::UnexpectedHoles {
                    object: "L2-to-L1 message".to_string(),
                    order: i,
                }),
            },
        )
```

**Review by MohammadNassar1 — COMMENTED** [review]
Actually, we already have a test that verifies this method. In this PR I included the method to an account contract.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606#-:-NXzYKes2G1_UL9f4ML6:b5fe3t)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXsaHko425wnINd0odt:-NXyqADz813q4ecxrIn3:b-vn2bf6) ([raw file](https://github.com/starkware-libs/blockifier/blob/8b1f7fd98f9fb1e597eaf781b3a70c71abaf722b/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L79)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The flag will affect only validate (and not `__execute___`) so I'm not sure what we're trying to achieve with it.
And I made a rough estimation :)
</blockquote></details>

As we did not employ any specific workarounds, I will remove these comments.
___
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 48 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXtrLQ3EBFjuVQr2b0Y:-NXyq7_c1ib24HeFLrky:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/701cd65f755bd78a7cc34d88670807a0d4f4ed5f/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L48)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please add a brief documentation of why we call it?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 226 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXtsAUbDv4QU7Aagz2M:-NXyv4914bV7tBrCPeKd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/701cd65f755bd78a7cc34d88670807a0d4f4ed5f/crates/blockifier/src/execution/entry_point.rs#L226)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note that the `TransactionExecutionError::UnexpectedHoles` error message is not quite appropriate in this case. Try to generalize it or think of another solution :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXtsdO04UCCQ0EvsMpZ:-NXyv6Ag2miHzFkxrzxl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/701cd65f755bd78a7cc34d88670807a0d4f4ed5f/crates/blockifier/src/execution/entry_point.rs#L238)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXyJrYr4_75KXM7VhDt:-NXzXilO2I-C3Dbr9QqM:b1uwffr) ([raw file](https://github.com/starkware-libs/blockifier/blob/701cd65f755bd78a7cc34d88670807a0d4f4ed5f/crates/blockifier/src/execution/entry_point.rs#L243)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

No need to iterate twice over the collection, it can be done using a single iteration. Possible implementation below (haven't tested it though).
There might be something better though (consider using chatGPT to investigate).
</blockquote></details>

Woow, your code works without any bugs :)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NXyJrYr4_75KXM7VhDt:-NYK-prf9h-a1I9FbPFQ:bj2972b) ([raw file](https://github.com/starkware-libs/blockifier/blob/701cd65f755bd78a7cc34d88670807a0d4f4ed5f/crates/blockifier/src/execution/entry_point.rs#L243)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Woow, your code works without any bugs :)
</blockquote></details>

Full props go to rust compiler :muscle:

**Review by giladchase — COMMENTED** [review]
Noice

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606#-:-NYK07xr7x-CaGPlgItK:b-83olaz)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606#-:-NYK6bXM5sIF0AKKtRtC:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — DISMISSED** [review]
> Reviewed 5 of 7 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by noaov1 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606#-:-NYNwX5N5uZwKH80-eOb:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/errors.rs` line 52 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NYO97Cg5RiDOG1htpOh:-NYO97Ch4A9GPm6EIkZ5:bpm4uie) ([raw file](https://github.com/starkware-libs/blockifier/blob/38f8b2f0283481ccddb35a1b8352ce8706c51491/crates/blockifier/src/transaction/errors.rs#L52)):*
> ```XML
>          {max_order}."
>     )]
>     InvalidOrder { object: String, order: usize, max_order: usize },
> ```

Please alphabetize. Can be done in a separate PR.



_Code quote:_
```XML
InvalidOrder { object: String, order: usize, max_order: usize },
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 54 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NYO9jG7Dl5k7zeTbt44:-NYO9jG7Dl5k7zeTbt45:b-n6d6dn) ([raw file](https://github.com/starkware-libs/blockifier/blob/38f8b2f0283481ccddb35a1b8352ce8706c51491/crates/blockifier/src/transaction/errors.rs#L54)):*
> ```XML
>     InvalidOrder { object: String, order: usize, max_order: usize },
>     #[error("Unknown chain ID '{chain_id:?}'.")]
>     UnknownChainId { chain_id: String },
> ```

Please remove



_Code quote:_
```XML
    #[error("Unknown chain ID '{chain_id:?}'.")]
    UnknownChainId { chain_id: String },
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/606)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/transaction/errors.rs` line 52 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NYO97Cg5RiDOG1htpOh:-NYOBd2XCn3Du55a_C-Y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/38f8b2f0283481ccddb35a1b8352ce8706c51491/crates/blockifier/src/transaction/errors.rs#L52)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please alphabetize. Can be done in a separate PR.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/errors.rs` line 54 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/606#-NYO9jG7Dl5k7zeTbt44:-NYOBcoo5Lbm2ulmrJiM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/38f8b2f0283481ccddb35a1b8352ce8706c51491/crates/blockifier/src/transaction/errors.rs#L54)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.

**Pull request merged**
