### PR TITLE
Convert felt252 to u64.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/668)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/execution_utils.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/668#-NYveTpN3bNJ5U77ITJL:-NYveTpO3wjbSnECWlHs:b5d4qhy) ([raw file](https://github.com/starkware-libs/blockifier/blob/38e68cb79a669afba3dcea3c80b5c2a9f5f193fb/crates/blockifier/src/execution/execution_utils.rs#L101)):*
> ```XML
>     let felt = felt_from_ptr(vm, ptr)?;
>     // TODO(Arni, 28/6/2023): Add correct VirtualMachineError. The error should idicate the felt
>     // cannot be converted to u64.
> ```

I tried moving this code into `crates/blockifier/src/execution/syscalls/mod.rs`. There is no `SyscallExecutionError` which fits better. 
Moreover - if `stark_felt_from_ptr` may raise a ` VirtualMachineError` - so should this convertor.



_Code quote:_
```XML
    // TODO(Arni, 28/6/2023): Add correct VirtualMachineError. The error should idicate the felt
    // cannot be converted to u64.
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/execution_utils.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/668#-NYveTpN3bNJ5U77ITJL:-NYw-qUD2gLnp1M_c0w-:b-v11c2w) ([raw file](https://github.com/starkware-libs/blockifier/blob/38e68cb79a669afba3dcea3c80b5c2a9f5f193fb/crates/blockifier/src/execution/execution_utils.rs#L101)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I agree that the error message is informative. We can return `SyscallExecutionError` but that means that this method is only relevant to syscalls (so we should move it), or either return an option and let the calling method deal with it.  I think that the error should be `SyscallExecutionError::InvalidSyscallInput`. WDYT?
</blockquote></details>

Reverted these changes.

Probably not the right thing to do... anyway.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 305 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/668#-NYw08k69YczxtP4DhT4:-NYw08k69YczxtP4DhT5:b-4r1ceh) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f3eea8a546f8e9dec9b2ea0d6a27a226d3be3e6/crates/blockifier/src/execution/syscalls/mod.rs#L305)):*
> ```XML
>         let block_number =
>             BlockNumber(felt.to_u64().ok_or(SyscallExecutionError::InvalidSyscallInput {
>                 input: felt_to_stark_felt(&felt),
> ```

No easy way to get a `StarkFelt` for the input of: `SyscallExecutionError::InvalidSyscallInput`. :(



_Code quote:_
```XML
input: felt_to_stark_felt(&felt),
```

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/668)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/668#-NZUnWJI5j8FXClWTX34:-NZUnWJI5j8FXClWTX35:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6acdf7c72e884acbb0b93507735b53181703a2b4/crates/blockifier/src/execution/syscalls/mod.rs#L21)):*
> ```XML
>     SyscallHintProcessor, BLOCK_NUMBER_OUT_OF_RANGE_ERROR,
> };
> use super::execution_utils::felt_to_stark_felt;
> ```





_Suggestion:_
```XML
use crate::execution::execution_utils::felt_to_stark_felt;
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 306 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/668#-NZUnPyN2K5yjLd3PzJJ:-NZUnPyN2K5yjLd3PzJK:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6acdf7c72e884acbb0b93507735b53181703a2b4/crates/blockifier/src/execution/syscalls/mod.rs#L306)):*
> ```XML
>                 input: felt_to_stark_felt(&felt),
>                 info: "Should be a u64, representing a block number.".to_string(),
>             }),
> ```





_Suggestion:_
```XML
        let block_number = felt.to_u64().ok_or_else(|| SyscallExecutionError::InvalidSyscallInput {
            input: felt_to_stark_felt(&felt),
            info: String::from("The block number must be representable with 64 bits."),
        })?;
        
        Ok(GetBlockHashRequest { block_number: BlockNumber(block_number) })
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/668)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/668#-NZUnWJI5j8FXClWTX34:-NZViFlBEVwr1p2ewyS7:b-1ybxko) ([raw file](https://github.com/starkware-libs/blockifier/blob/6acdf7c72e884acbb0b93507735b53181703a2b4/crates/blockifier/src/execution/syscalls/mod.rs#L21)):*
> ```XML
>     SyscallHintProcessor, BLOCK_NUMBER_OUT_OF_RANGE_ERROR,
> };
> use super::execution_utils::felt_to_stark_felt;
> ```

Done. See rebase change.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 306 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/668#-NZUnPyN2K5yjLd3PzJJ:-NZVkOD8-hLM4VSkW9wI:b92h54o) ([raw file](https://github.com/starkware-libs/blockifier/blob/6acdf7c72e884acbb0b93507735b53181703a2b4/crates/blockifier/src/execution/syscalls/mod.rs#L306)):*
Done.
Note the error message format: `Invalid syscall input: {input:?}; {info}`
Maybe?
> ```
> info: String::from("Block number must fit within 64 bits."),
> ```

**Review by noaov1 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/668#-:-NZVtSIu6fxGS2SNvfHA:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 306 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/668#-NZUnPyN2K5yjLd3PzJJ:-NZVtLi47fg9tysQ1wFW:b-piudi3) ([raw file](https://github.com/starkware-libs/blockifier/blob/6acdf7c72e884acbb0b93507735b53181703a2b4/crates/blockifier/src/execution/syscalls/mod.rs#L306)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
Note the error message format: `Invalid syscall input: {input:?}; {info}`
Maybe?
> ```
> info: String::from("Block number must fit within 64 bits."),
> ```
</blockquote></details>

Whatever you prefer :)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/668)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/668#-NZWvxkX2KNhst37YP2A:-NZWvxkX2KNhst37YP2B:b3fkxcf) (no related file):*
This PR should be rebased onto 0.12.1 - I assume.

___
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 306 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/668#-NZUnPyN2K5yjLd3PzJJ:-NZWvuBI3onLuqrWJEqx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6acdf7c72e884acbb0b93507735b53181703a2b4/crates/blockifier/src/execution/syscalls/mod.rs#L306)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Whatever you prefer :)
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This PR should be rebased onto 0.12.1 - I assume.
</blockquote></details>

Rebased over `main`.

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/668)* status: 1 of 2 files reviewed, all discussions resolved

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/668)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
