### PR TITLE
fix: offset segment arena instance counter for older vm versions

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2090)

### CODE REVIEW

**Comment by avi-starkware** [comment]
Python side: https://reviewable.io/reviews/starkware-industries/starkware/35539

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2090)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2090#-O1ui-wiAo556Gaw7b-0:-O1ui-wiAo556Gaw7b-1:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8b8dd9b75bd33a28c8e33e5dcf9b2efae1d569f/crates/blockifier/src/versioned_constants.rs#L55)):*
> ```XML
>     // used by instances of the builtin, instead of the number of instances.
>     #[serde(default)]
>     pub segment_arena_builtin_instance_counter_backward_compatibility: bool,
> ```

?



_Suggestion:_
```XML
    // BACKWARD COMPATIBILITY: If true, the segment_arena builtin instance counter will be
    // multiplied by 3. This offsets a bug in the vm where the counter counted the number of cells
    // used by instances of the builtin, instead of the number of instances.
    #[serde(default)]
    pub multiply_segment_arena_cells_by_instance_size: bool,
```
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2090#-O1uhr_p0Dtu_HiAv6Ym:-O1uhr_p0Dtu_HiAv6Yn:brtgsjx) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8b8dd9b75bd33a28c8e33e5dcf9b2efae1d569f/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L242)):*
> ```XML
> 
>     let mut full_call_resources = &*syscall_handler.resources - &previous_resources;
> ```

Consider defining `ARENA_BUILTIN_SIZE = 3`.
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2090#-O1uiX435CxQm7qmcpn8:-O1uiX446vfwMMJwX8Zt:b-h102gr) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8b8dd9b75bd33a28c8e33e5dcf9b2efae1d569f/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L248)):*
> ```XML
>             .get_mut(&BuiltinName::segment_arena)
>             .map_or_else(|| {}, |val| *val *= 3);
>     }
> ```

Please add it only for the `vm_resources_without_inner_calls` (those are the vm resources).  
Same for cairo1.



_Code quote:_
```XML
    if versioned_constants.segment_arena_builtin_instance_counter_backward_compatibility {
        full_call_resources
            .builtin_instance_counter
            .get_mut(&BuiltinName::segment_arena)
            .map_or_else(|| {}, |val| *val *= 3);
    }
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2090#-O1uiX435CxQm7qmcpn8:-O1ukbbvBkS-Caev5fyt:b-2mw3ip) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8b8dd9b75bd33a28c8e33e5dcf9b2efae1d569f/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L248)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add it only for the `vm_resources_without_inner_calls` (those are the vm resources).  
Same for cairo1.
</blockquote></details>

Should I do it before substract `&previous_resources`?
If the vm_resources are only in `vm_resources_without_inner_calls` shouldn't the value be the same whether I multiply it here or there?

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2090)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2090#-O1uiX435CxQm7qmcpn8:-O1ulT-C8YEFmuQI8mwm:b-y24sug) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8b8dd9b75bd33a28c8e33e5dcf9b2efae1d569f/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L248)):*
The only "risk" is if we use the segment arena in one of the syscalls. The current code will multiply it as well.

> Should I do it before substract `&previous_resources`?

Yes. We assume that we already fixed the previous resources.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2090)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2090#-O1ui-wiAo556Gaw7b-0:-O1v5BVx6uEOgiq1duAK:b-crrx2u) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8b8dd9b75bd33a28c8e33e5dcf9b2efae1d569f/crates/blockifier/src/versioned_constants.rs#L55)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

I made it `count_segment_arena_cells_not_instances`
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2090#-O1uhr_p0Dtu_HiAv6Ym:-O1v5cqw1dFaF1Bni5hd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8b8dd9b75bd33a28c8e33e5dcf9b2efae1d569f/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L242)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining `ARENA_BUILTIN_SIZE = 3`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2090#-O1uiX435CxQm7qmcpn8:-O1v5lgJ4v9J7ZqJ6gdS:be2fkgh) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8b8dd9b75bd33a28c8e33e5dcf9b2efae1d569f/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L248)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The only "risk" is if we use the segment arena in one of the syscalls. The current code will multiply it as well.

> Should I do it before substract `&previous_resources`?

Yes. We assume that we already fixed the previous resources.
</blockquote></details>

Done.
But won't the counting be wrong in the syscall as well?

**Review by noaov1 — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2090)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2090#-O1uiX435CxQm7qmcpn8:-O1vh38N9WPtYabfa_My:bhki9jy) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8b8dd9b75bd33a28c8e33e5dcf9b2efae1d569f/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L248)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.
But won't the counting be wrong in the syscall as well?
</blockquote></details>

The syscall are counted correctly.

**Pull request merged**
