### PR TITLE
chore: update max calldata length

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2045)

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
Python PR?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2045#-:-O1Bq8rX5rXVX_MPGfsH:bta0nby)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
Soon, along with other config fixes

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2045#-:-O1Bqi8oBPJepOXQ9h9U:b-eg4qmg)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2045#-:-O1Bt97uEpzETJ8Dyt7O:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
https://github.com/starkware-industries/starkware/pull/35432

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2045#-:-O1CD9CTB28y12zdVPf1:b-j59j61)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2045#-:-O1D7viU0Ui0ame6S3eH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
