### PR TITLE
Transaction execution failures log-level warn->debug

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/626)

### CODE REVIEW

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/626#-:-NYDBowZ9FjXTXTMNJzt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
Change log in py to debug
add logger to batcher

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/626#-:-NYDsIgKBvJ2zTe9xedJ:bqnb0je)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
Done, [PTAL](https://reviewable.io/reviews/starkware-industries/starkware/30473)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/626#-:-NYEVSZa37MSvADEj3SD:b-t0b11b)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/626#-:-NYEcp_9BZM2jcsVO3UP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
