### PR TITLE
Use stable clippy.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/787)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Interesting, this was a bug in nightly clippy?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/787#-:-NaBJy0O83x3MR3yy7dD:b-eml91v)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
I don't know if missing a bug in clippy is considered a bug.

But I got an error when I ran clippy locally.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/787#-:-NaBPwm_8UYzZfBZfg22:bgkryyy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/787)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`.github/workflows/ci.yml` line 37 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/787#-NaHvt4G0mr-NO4IUSmj:-NaHvt4G0mr-NO4IUSmk:b-2lcyd8) ([raw file](https://github.com/starkware-libs/blockifier/blob/576834ad133692b58f6a33e2627ea973f6de5fc0/.github/workflows/ci.yml#L37)):*
> ```YAML
>         with:
>           components: clippy
>           toolchain: stable
> ```

if you feel like it :grimacing: 



_Suggestion:_
```YAML
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/787)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`.github/workflows/ci.yml` line 37 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/787#-NaHvt4G0mr-NO4IUSmj:-Na_O7eB1p6bcUuFcNw-:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/576834ad133692b58f6a33e2627ea973f6de5fc0/.github/workflows/ci.yml#L37)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

if you feel like it :grimacing: 
</blockquote></details>

done.

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/787)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
replaced by #823

**Pull request closed without merging**
