### PR TITLE
Add simulate flag to external transactions.

### PR DESCRIPTION
**Pull request by noaov1**
[Python](https://reviewable.io/reviews/starkware-industries/starkware/32381).

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1053)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1053)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1053#-Ni4giuZAc4xo4huFGnD:-Ni4giu_2dVyqHUNraLM:b-4pxda5) (no related file):*
Consider adding `new` and `new_for_simulation` c-tors for the three transaction types.

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1053#-:-Ni5IYIo7LDZ0jaA7Nje:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1053)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1053#-Ni4giuZAc4xo4huFGnD:-Ni6PW3o9KG5y57kF2hQ:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider adding `new` and `new_for_simulation` c-tors for the three transaction types.
</blockquote></details>

Done.

___

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1053)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by dorimedini-starkware — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1053)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1053)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1053#-Ni9Z9aZ89rdZ4cxqQzJ:-Ni9Z9a_3q8DEHmjkCRR:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf11132ab1b55997ef17ea8269446d951ba5b653/crates/blockifier/src/transaction/transaction_execution.rs#L40)):*
> ```XML
>         contract_class: Option<ContractClass>,
>         paid_fee_on_l1: Option<Fee>,
>         query: bool,
> ```





_Suggestion:_
```XML
only_query
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1053#-Ni9ZONtAnaUNRMspapo:-Ni9ZONu3vSIcto_35yw:b-wyayli) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf11132ab1b55997ef17ea8269446d951ba5b653/crates/blockifier/src/transaction/transaction_execution.rs#L53)):*
> ```XML
>                 let contract_class =
>                     contract_class.expect("Declare should be created with a ContractClass");
>                 let declare_tx = if query {
> ```

Maybe use `match`, instead of `if-else`?
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1053#-Ni9ZCBOC1ZQ0IKWqngR:-Ni9ZCBOC1ZQ0IKWqngS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf11132ab1b55997ef17ea8269446d951ba5b653/crates/blockifier/src/transaction/transaction_execution.rs#L54)):*
> ```XML
>                     contract_class.expect("Declare should be created with a ContractClass");
>                 let declare_tx = if query {
>                     DeclareTransaction::new_query(declare, contract_class)
> ```





_Suggestion:_
```XML
new_for_query
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1053)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1053#-Ni9ZrlM67_91LXxJnYN:-Ni9ZrlN6XyQBTWqaKM_:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf11132ab1b55997ef17ea8269446d951ba5b653/crates/blockifier/src/transaction/transactions.rs#L99)):*
> ```XML
>     tx: starknet_api::transaction::DeclareTransaction,
>     contract_class: ContractClass,
>     // Flag indicating the presence of the query bit in the version.
> ```





_Suggestion:_
```XML
// Indicates the presence of the query bit in the version.
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1053)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1053#-Ni9ZONtAnaUNRMspapo:-Ni9mAs27YCnPykHTvEN:bpb5nqa) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf11132ab1b55997ef17ea8269446d951ba5b653/crates/blockifier/src/transaction/transaction_execution.rs#L53)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe use `match`, instead of `if-else`?
</blockquote></details>

Do you think it's more elegant?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1053#-:-Ni9oOY62xdmvl5OpYED:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
