### PR TITLE
chore: derive serialize for FeeTokenAddress and ChainInfo

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1896)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1896)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/context.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1896#-NyLLs7YD29M3jBqUsTp:-NyLLs7YD29M3jBqUsTq:bd3aya2) ([raw file](https://github.com/starkware-libs/blockifier/blob/d34cee3da7038c2c95f046d364fe56cc88333f17/crates/blockifier/src/context.rs#L83)):*
> ```XML
> 
> #[derive(Clone, Debug, Deserialize, PartialEq, Serialize, Validate)]
> pub struct ChainInfo {
> ```

consider moving this struct in the future to starknet-api



_Code quote:_
```XML
pub struct ChainInfo 
```
___
*[`crates/blockifier/src/context_test.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1896#-NyLN0P-BAdJ0PrH8IBa:-NyLN0P-BAdJ0PrH8IBb:b-bcqz6p) ([raw file](https://github.com/starkware-libs/blockifier/blob/d34cee3da7038c2c95f046d364fe56cc88333f17/crates/blockifier/src/context_test.rs#L27)):*
> ```XML
> 
> fn test_valid_config_body<
>     T: for<'a> Deserialize<'a> + SerializeConfig + Validate + PartialEq + Debug,
> ```

is Deserialize required here? I only see the usage of serialize.



_Code quote:_
```XML
Deserialize
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1896)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/context.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1896#-NyLLs7YD29M3jBqUsTp:-NyLSLPn98BgIFxL5Nju:b-7yd1q4) ([raw file](https://github.com/starkware-libs/blockifier/blob/d34cee3da7038c2c95f046d364fe56cc88333f17/crates/blockifier/src/context.rs#L83)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

consider moving this struct in the future to starknet-api
</blockquote></details>

Added a TODO.
___
*[`crates/blockifier/src/context_test.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1896#-NyLN0P-BAdJ0PrH8IBa:-NyLRKqC6icFqK9gZSW-:b2zr2x3) ([raw file](https://github.com/starkware-libs/blockifier/blob/d34cee3da7038c2c95f046d364fe56cc88333f17/crates/blockifier/src/context_test.rs#L27)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

is Deserialize required here? I only see the usage of serialize.
</blockquote></details>

`get_config_from_file` requires `Deserialize`

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1896#-:-NyOkn66EiekHe1_Mymj:bnfp4nl)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
Already in the sequencer.

**Pull request closed without merging**
