### PR TITLE
refactor(execution): the struct state changes and state changes count

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1417)

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1417)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-Np_RenG4wrDwvZWpUME:-Np_RenHAs6o_JVQXv3u:bg2fey5) ([raw file](https://github.com/starkware-libs/blockifier/blob/64442c8db8a9f0995820110e14455f9114929734/crates/blockifier/src/state/cached_state.rs#L113)):*
> ```XML
>         // Exclude the fee token contract modification, since it’s charged once throughout the
>         // block.
>         state_changes.modified_contracts.remove(&fee_token_address);
> ```

The value for modified contract is passed through the state_changes, in order for it to be unpacked in `deprecated_from`.



_Code quote:_
```XML
        // Exclude the fee token contract modification, since it’s charged once throughout the
        // block.
        state_changes.modified_contracts.remove(&fee_token_address);
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 697 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-Np_RENtE7PcSJLn8SHb:-Np_RENtE7PcSJLn8SHc:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/64442c8db8a9f0995820110e14455f9114929734/crates/blockifier/src/state/cached_state.rs#L697)):*
> ```XML
>     pub compiled_class_hash_updates: HashMap<ClassHash, CompiledClassHash>,
>     pub modified_contracts: HashSet<ContractAddress>,
> }
> ```





_Suggestion:_
```XML
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct StateChanges {
    pub storage_updates: HashMap<StorageEntry, StarkFelt>,
    pub nonce_updates: HashMap<ContractAddress, Nonce>,
    pub class_hash_updates: HashMap<ContractAddress, ClassHash>,
    pub compiled_class_hash_updates: HashMap<ClassHash, CompiledClassHash>,
    # This value can be Should be removed. It is saved just for 'get_actual_state_changes_for_fee_charge'.
    pub modified_contracts: HashSet<ContractAddress>,
}
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 765 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-Np_R6ePC2nnLnI_sXku:-Np_R6ePC2nnLnI_sXkv:bnb3udx) ([raw file](https://github.com/starkware-libs/blockifier/blob/64442c8db8a9f0995820110e14455f9114929734/crates/blockifier/src/state/cached_state.rs#L765)):*
> ```XML
>             n_modified_contracts: state_changes.modified_contracts.len(),
>         }
>     }
> ```

A `from` function that uses the value saved in StateChanges.



_Code quote:_
```XML
    pub fn deprecated_from(state_changes: &StateChanges) -> Self {
        Self {
            n_storage_updates: state_changes.storage_updates.len(),
            n_class_hash_updates: state_changes.class_hash_updates.len(),
            n_compiled_class_hash_updates: state_changes.compiled_class_hash_updates.len(),
            n_modified_contracts: state_changes.modified_contracts.len(),
        }
    }
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
Arni, why didn't you remove `modified_contracts`? 
You can create this set in StateChangesCount::for_fee_from(&self.state_changes, fee_type);

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-:-Np_mz1f7iyKyAUh55kC:b-7z332m)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by ArniStarkware** [comment]
Now, it is done. I called the method: `from_state_changes_for_fee_charge`.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1417)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-NpxiuXBEws4Qw5GqbcM:-NpxiuXBEws4Qw5GqbcN:bz9545n) ([raw file](https://github.com/starkware-libs/blockifier/blob/585420888f4140acc33653e6cd61c5e11cf7f5f3/crates/blockifier/src/state/cached_state.rs#L80)):*
> ```XML
>             class_hash_updates: class_hash_updates.clone(),
>             compiled_class_hash_updates: compiled_class_hash_updates.clone(),
>             nonce_updates: nonce_updates.clone(),
> ```

Why do we need to clone them?



_Code quote:_
```XML
            storage_updates: storage_updates.clone(),
            class_hash_updates: class_hash_updates.clone(),
            compiled_class_hash_updates: compiled_class_hash_updates.clone(),
            nonce_updates: nonce_updates.clone(),
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1417)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-NpxlDeN0i_no2kSoDmC:-NpxlDeN0i_no2kSoDmD:b-t7f8gz) ([raw file](https://github.com/starkware-libs/blockifier/blob/585420888f4140acc33653e6cd61c5e11cf7f5f3/crates/blockifier/src/state/cached_state.rs#L80)):*
> ```XML
>             class_hash_updates: class_hash_updates.clone(),
>             compiled_class_hash_updates: compiled_class_hash_updates.clone(),
>             nonce_updates: nonce_updates.clone(),
> ```

Can you do something like this?



_Suggestion:_
```XML
        Ok(StateChanges {
            storage_updates: self.cache.get_storage_updates(),
            nonce_updates: self.cache.get_nonce_updates(),
            // Class hash Update (deployed contracts + replace_class syscall).
            class_hash_updates: &self.cache.get_class_hash_updates();,
            // Compiled class hash updates (declare Cairo 1 contract).
            compiled_class_hash_updates: self.cache.get_compiled_class_hash_updates(),
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1417)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 717 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-Npxmbk-CEvlMHY5TKyO:-Npxmbk-CEvlMHY5TKyP:b-81v1fj) ([raw file](https://github.com/starkware-libs/blockifier/blob/585420888f4140acc33653e6cd61c5e11cf7f5f3/crates/blockifier/src/state/cached_state.rs#L717)):*
> ```XML
> 
> impl StateChangesCount {
>     pub fn from_state_changes_for_fee_charge(
> ```

Add a todo to change this method to consume `state_changes`

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1417)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-NpxiuXBEws4Qw5GqbcM:-NpyAbeg5N6wW08u2NV4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/585420888f4140acc33653e6cd61c5e11cf7f5f3/crates/blockifier/src/state/cached_state.rs#L80)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why do we need to clone them?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-NpxlDeN0i_no2kSoDmC:-NpyA_hw0D0uTGQPCfrK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/585420888f4140acc33653e6cd61c5e11cf7f5f3/crates/blockifier/src/state/cached_state.rs#L80)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you do something like this?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 717 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-Npxmbk-CEvlMHY5TKyO:-NpyCHGw-t3IwbE5L8uJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/585420888f4140acc33653e6cd61c5e11cf7f5f3/crates/blockifier/src/state/cached_state.rs#L717)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add a todo to change this method to consume `state_changes`
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1417#-:-NpyFyTu34akbwt4IrcL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
