### PR TITLE
Debug test contract

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1081)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1081)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 125 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1081#-NiYfuYb-WqjEEra-cTu:-NiYfuYb-WqjEEra-cTv:b-75ywm7) ([raw file](https://github.com/starkware-libs/blockifier/blob/f96bf95ae242e196ae02dacfd30d7ec85235b7be/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L125)):*
> ```Cairo
>         b: felt252
>     ) -> Span::<felt252> {
>         let mut nested_library_calldata: Array::<felt252> = Default::default();
> ```

why is this needed?



_Code quote:_
```Cairo
ta: Array::<felt252
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1081#-:-NiZ4Cu-0jkd0v4IDY-a:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1081)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 125 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1081#-NiYfuYb-WqjEEra-cTu:-NiZ4X2I6VVohxNMNGes:b-kdocyi) ([raw file](https://github.com/starkware-libs/blockifier/blob/f96bf95ae242e196ae02dacfd30d7ec85235b7be/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L125)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

Since otherwise it fails on:
"error: Ambiguous method call. More than one applicable trait function with a suitable self type was found: ArrayTrait::append and ByteArrayTrait::append. Consider adding type annotations or explicitly refer to the impl function."

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1081#-:-NiZNeR-32BKBZ8QQu6T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
