### PR TITLE
refactor: separate statful validator logic from py_validator

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1730)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1730** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1730?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1730)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/native_blockifier/src/py_validator.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJWMvV4WeYmEo-I8p5:-NuJWMvV4WeYmEo-I8p6:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb6c0fa80ae58634e0b9a7a991a6faa768508d55/crates/native_blockifier/src/py_validator.rs#L46)):*
> ```XML
>         let state_reader = PyStateReader::new(state_reader_proxy);
>         let global_contract_cache = GlobalContractCache::new(global_contract_cache_size);
>         let state = CachedState::new(state_reader, global_contract_cache);
> ```





_Suggestion:_
```XML
        let global_contract_cache = GlobalContractCache::new(global_contract_cache_size);
        // Create the state.
        let state_reader = PyStateReader::new(state_reader_proxy);
        let state = CachedState::new(state_reader, global_contract_cache);
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJWUhs-gQyU4ST-doa:-NuJWUhs-gQyU4ST-dob:b-vaba7d) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7acc173076a346c3a69a2d0c8c181e33b11044d/crates/native_blockifier/src/py_validator.rs#L55)):*
> ```XML
> 
>         let (block_info, chain_info) = into_block_context_args(&general_config, &next_block_info)?;
>         // TODO(Yael 24/01/24): calc block_context using pre_process_block
> ```

Where do you handle this TODO?



_Code quote:_
```XML
// TODO(Yael 24/01/24): calc block_context using pre_process_block
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJUK171uExJRdoZG_k:-NuJUK18AUnDy-fc3_cO:brws6vc) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb6c0fa80ae58634e0b9a7a991a6faa768508d55/crates/native_blockifier/src/py_validator.rs#L83)):*
> ```XML
> 
> /// Manages state related transaction validations for pre-execution flows.
> pub struct StatefulValidator<S: StateReader> {
> ```

Why are you using a general `StateReader`?
Are we planing to use a different stateReader fro mempool?



_Code quote:_
```XML
pub struct StatefulValidator<S: StateReader> {
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJVQqh2ZU50cW0547F:-NuJVQqh2ZU50cW0547G:buf66w6) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb6c0fa80ae58634e0b9a7a991a6faa768508d55/crates/native_blockifier/src/py_validator.rs#L141)):*
> ```XML
>         &mut self,
>         tx: AccountTransaction,
>     ) -> NativeBlockifierResult<(TransactionExecutionInfo, BouncerInfo)> {
> ```

Does it break the Python API?



_Code quote:_
```XML
    fn execute(
        &mut self,
        tx: AccountTransaction,
    ) -> NativeBlockifierResult<(TransactionExecutionInfo, BouncerInfo)> {
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJVrMXExIsc1ByjVVy:-NuJVrMXExIsc1ByjVVz:begl6sl) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb6c0fa80ae58634e0b9a7a991a6faa768508d55/crates/native_blockifier/src/py_validator.rs#L141)):*
> ```XML
>         &mut self,
>         tx: AccountTransaction,
>     ) -> NativeBlockifierResult<(TransactionExecutionInfo, BouncerInfo)> {
> ```

Why did you replace the Thin struct?
I think Dori added this struct since the python struct has less fields.



_Code quote:_
```XML
TransactionExecutionInfo
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1730)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJWMvV4WeYmEo-I8p5:-NuJbeZjCE7w3JKwfRxg:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb6c0fa80ae58634e0b9a7a991a6faa768508d55/crates/native_blockifier/src/py_validator.rs#L46)):*
> ```XML
>         let state_reader = PyStateReader::new(state_reader_proxy);
>         let global_contract_cache = GlobalContractCache::new(global_contract_cache_size);
>         let state = CachedState::new(state_reader, global_contract_cache);
> ```

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJWUhs-gQyU4ST-doa:-NuJZaav2DGhJ4QJTqql:baeu84o) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7acc173076a346c3a69a2d0c8c181e33b11044d/crates/native_blockifier/src/py_validator.rs#L55)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Where do you handle this TODO?
</blockquote></details>

It was moved to Monday. See: https://starkware.monday.com/boards/5536734411/pulses/5945099530

See discussion: https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc
___
*[`crates/native_blockifier/src/py_validator.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJcUaj10pFc57jIiJE:-NuJcUaj10pFc57jIiJF:b-funqi4) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7acc173076a346c3a69a2d0c8c181e33b11044d/crates/native_blockifier/src/py_validator.rs#L55)):*
> ```XML
> 
>         let (block_info, chain_info) = into_block_context_args(&general_config, &next_block_info)?;
>         // TODO(Yael 24/01/24): calc block_context using pre_process_block
> ```

This TODO is on Monday. See: [https://starkware.monday.com/boards/5536734411/pulses/5945099530](https://starkware.monday.com/boards/5536734411/pulses/5945099530)

See discussion: [https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc)



_Code quote:_
```XML
 // TODO(Yael 24/01/24): calc block_context using pre_process_block
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJUK171uExJRdoZG_k:-NuJZnbqCQtssp3tBffS:b-c7ysxj) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb6c0fa80ae58634e0b9a7a991a6faa768508d55/crates/native_blockifier/src/py_validator.rs#L83)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why are you using a general `StateReader`?
Are we planing to use a different stateReader fro mempool?
</blockquote></details>

Yes, we are. We do not plan to use `PyStateReader`.
Also - for testing - we want to use some `StateReader` for testing (like `DictStateReader`).
___
*[`crates/native_blockifier/src/py_validator.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJaKieE2NZG6EZ6VDi:-NuJaKieE2NZG6EZ6VDj:b7jmekd) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7acc173076a346c3a69a2d0c8c181e33b11044d/crates/native_blockifier/src/py_validator.rs#L85)):*
> ```XML
>             let sentinel_class_info = None;
>             let (_tx_execution_info, _py_bouncer_info) = self.execute(tx, sentinel_class_info)?;
>             // TODO(Ayelet, 09/11/2023): Check call succeeded.
> ```

This TODO is now on Monday. See: https://starkware.monday.com/boards/5536734411/pulses/6318033163



_Code quote:_
```XML
// TODO(Ayelet, 09/11/2023): Check call succeeded.
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJVQqh2ZU50cW0547F:-NuJaRdMCjMdJARtYjRe:bwm0j8i) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb6c0fa80ae58634e0b9a7a991a6faa768508d55/crates/native_blockifier/src/py_validator.rs#L141)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Does it break the Python API?
</blockquote></details>

No. This is not the `execute` method of `PyValidator`.
This is the `execute` method of `StatefulValidator`.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1730)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJVrMXExIsc1ByjVVy:-NuJmMsMBpki0Nh2RNXy:bwu774v) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb6c0fa80ae58634e0b9a7a991a6faa768508d55/crates/native_blockifier/src/py_validator.rs#L141)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why did you replace the Thin struct?
I think Dori added this struct since the python struct has less fields.
</blockquote></details>

This value is never returned. 
Changed the function to reflect that.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1730)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1730)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/native_blockifier/src/py_validator.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJcUaj10pFc57jIiJE:-NuNTyLkARJAGiCCldHY:b-ats2le) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7acc173076a346c3a69a2d0c8c181e33b11044d/crates/native_blockifier/src/py_validator.rs#L55)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This TODO is on Monday. See: [https://starkware.monday.com/boards/5536734411/pulses/5945099530](https://starkware.monday.com/boards/5536734411/pulses/5945099530)

See discussion: [https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc)
</blockquote></details>

This was addressed (See #1742) and rebased.
This discussion is no longer relevant. 
___
*[`crates/native_blockifier/src/py_validator.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJWUhs-gQyU4ST-doa:-NuNTyy67T2lLDooC1iB:b-ats2le) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7acc173076a346c3a69a2d0c8c181e33b11044d/crates/native_blockifier/src/py_validator.rs#L55)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It was moved to Monday. See: https://starkware.monday.com/boards/5536734411/pulses/5945099530

See discussion: https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc
</blockquote></details>

This was addressed (See #1742) and rebased.
This discussion is no longer relevant. 
___
*[`crates/native_blockifier/src/py_validator.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NuJaKieE2NZG6EZ6VDi:-NuNTbIN5Aupe4XjIvGs:b-ats2le) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7acc173076a346c3a69a2d0c8c181e33b11044d/crates/native_blockifier/src/py_validator.rs#L85)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This TODO is now on Monday. See: https://starkware.monday.com/boards/5536734411/pulses/6318033163
</blockquote></details>

This was addressed (See #1742) and rebased.
This discussion is no longer relevant.

**Comment by ArniStarkware** [comment]
Python side: https://github.com/starkware-industries/starkware/pull/34576.

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1730)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/native_blockifier/src/py_validator.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NucNmT3B19wfJoTa9Ak:-NucNmT3B19wfJoTa9Al:bevs0vi) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d3336fe2e9722731424eb7ebe083c79a3acaaa7/crates/native_blockifier/src/py_validator.rs#L84)):*
> ```XML
> pub struct StatefulValidator<S: StateReader> {
>     max_nonce_for_validation_skip: Nonce,
>     tx_executor: TransactionExecutor<S>,
> ```

Swap, so they're sorted by importance.



_Code quote:_
```XML
    max_nonce_for_validation_skip: Nonce,
    tx_executor: TransactionExecutor<S>,
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NucPzHn10Y14VgTbnqd:-NucPzHn10Y14VgTbnqe:b3u4s29) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d3336fe2e9722731424eb7ebe083c79a3acaaa7/crates/native_blockifier/src/py_validator.rs#L87)):*
> ```XML
> }
> 
> impl<S: StateReader> StatefulValidator<S> {
> ```

Can the methods be private (for now), and `pub` after it's moved to `blockifier` crate?



_Code quote:_
```XML
impl
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NucNyKl-F5QTY0pUvJs:-NucNyKl-F5QTY0pUvJt:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d3336fe2e9722731424eb7ebe083c79a3acaaa7/crates/native_blockifier/src/py_validator.rs#L95)):*
> ```XML
>         let tx_executor = TransactionExecutor::new(state, block_context);
> 
>         Self { max_nonce_for_validation_skip, tx_executor }
> ```





_Suggestion:_
```XML
        let tx_executor = TransactionExecutor::new(state, block_context);
        Self { max_nonce_for_validation_skip, tx_executor }
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NucReWm-QTngEXS0jmd:-NucReWm-QTngEXS0jme:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d3336fe2e9722731424eb7ebe083c79a3acaaa7/crates/native_blockifier/src/py_validator.rs#L124)):*
> ```XML
>         if skip_validate {
>             return Ok(());
>         }
> ```





_Suggestion:_
```XML
        // Deploy account transactions should be fully executed, since the constructor must run
        // before `__validate_deploy__`. The execution already includes all necessary validations,
        // so they are skipped here.
        if let AccountTransaction::DeployAccount(_) = tx {
            self.execute(tx)?;
            return Ok(());
        }
        
        self.perform_pre_validation_stage(&tx, &tx_context)?;

        // First, we check if the transaction should be skipped due to the deploy account not being
        // processed. It is done before the pre-validations checks because, in these checks, we
        // change the state (more precisely, we increment the nonce).
        let tx_context = self.tx_executor.block_context.to_tx_context(&tx);
        let skip_validate = self.skip_validate_due_to_unprocessed_deploy_account(
            &tx_context.tx_info,
            deploy_account_tx_hash,
        )?;
        if skip_validate {
            return Ok(());
        }
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1730)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NucNmT3B19wfJoTa9Ak:-NucUk6_-WjUPr7fN2UF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d3336fe2e9722731424eb7ebe083c79a3acaaa7/crates/native_blockifier/src/py_validator.rs#L84)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Swap, so they're sorted by importance.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NucPzHn10Y14VgTbnqd:-NucUiLT7wY9si04acbR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d3336fe2e9722731424eb7ebe083c79a3acaaa7/crates/native_blockifier/src/py_validator.rs#L87)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can the methods be private (for now), and `pub` after it's moved to `blockifier` crate?
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NucNyKl-F5QTY0pUvJs:-NucUldyD_ca_IPjPrdJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d3336fe2e9722731424eb7ebe083c79a3acaaa7/crates/native_blockifier/src/py_validator.rs#L95)):*
> ```XML
>         let tx_executor = TransactionExecutor::new(state, block_context);
> 
>         Self { max_nonce_for_validation_skip, tx_executor }
> ```

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-NucReWm-QTngEXS0jmd:-NucVcy26Xt_atWlsBCL:b-k4ilma) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d3336fe2e9722731424eb7ebe083c79a3acaaa7/crates/native_blockifier/src/py_validator.rs#L124)):*
> ```XML
>         if skip_validate {
>             return Ok(());
>         }
> ```

Partially done.

See the comment above the `skip_validate` step: 
```
It is done before the pre-validations checks because, in these checks, we change the state (more precisely, we increment the nonce).
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1730#-:-NucdKm8CraCldk57FjM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1730)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
