### PR TITLE
This PR is built over mohammad/Add_cairo1_account branch. Adding Cair…

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…o1 account to test_deploy_account_tx

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)

### CODE REVIEW

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/699#-NZV8lB2-UfYqmfpPJkF:-NZV8lB2-UfYqmfpPJkG:b369y8) ([raw file](https://github.com/starkware-libs/blockifier/blob/b81add1b5f7ede1dd79fa785c986d92ceea152ea/crates/blockifier/feature_contracts/cairo1/account.cairo#L5)):*
> ```Cairo
>     use array::{ArrayTrait, SpanTrait};
>     use box::BoxTrait;
>     use ecdsa::check_ecdsa_signature;
> ```

Is in needed?



_Code quote:_
```Cairo
use ecdsa::check_ecdsa_signature;
```
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/699#-NZV8jIeAc6fVpP3PquF:-NZV8jIf3T3wtPRQUC5u:bxtub52) ([raw file](https://github.com/starkware-libs/blockifier/blob/b81add1b5f7ede1dd79fa785c986d92ceea152ea/crates/blockifier/feature_contracts/cairo1/account.cairo#L9)):*
> ```Cairo
>     use starknet::account::Call;
>     use starknet::{ContractAddress, call_contract_syscall};
>     use zeroable::Zeroable;
> ```

Is it needed?



_Code quote:_
```Cairo
 use zeroable::Zeroable;
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/699#-NZV8lB2-UfYqmfpPJkF:-NZXAFJ11eh--P5IHOSm:b-8866f6) ([raw file](https://github.com/starkware-libs/blockifier/blob/b81add1b5f7ede1dd79fa785c986d92ceea152ea/crates/blockifier/feature_contracts/cairo1/account.cairo#L5)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is in needed?
</blockquote></details>

You are right; it is not needed, I've removed it in 3rd PR.
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/699#-NZV8jIeAc6fVpP3PquF:-NZXAObl6XpX4CqH4F_P:b-h4qxdf) ([raw file](https://github.com/starkware-libs/blockifier/blob/b81add1b5f7ede1dd79fa785c986d92ceea152ea/crates/blockifier/feature_contracts/cairo1/account.cairo#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Yes, it is needed in called address validation.

**Review by noaov1 — DISMISSED** [review]
> Reviewed 3 of 4 files at r5, 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 80 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_33JnWBLt2JDnkmGra:-N_33JnWBLt2JDnkmGrb:b-urv0i2) ([raw file](https://github.com/starkware-libs/blockifier/blob/3000ce67c009a1c4e4b69f76ff1fcd74d1faea03/crates/blockifier/src/transaction/transactions_test.rs#L80)):*
> ```XML
>         (constants::VALIDATE_DEPLOY_ENTRY_POINT_NAME, CairoVersion::Cairo1) => 69_usize,
>         (constants::VALIDATE_DECLARE_ENTRY_POINT_NAME, CairoVersion::Cairo0) => 12_usize,
>         (constants::VALIDATE_DECLARE_ENTRY_POINT_NAME, CairoVersion::Cairo1) => 49_usize,
> ```

I wonder why adding the `contract_address_salt: felt252` input adds 20 steps



_Code quote:_
```XML
        (constants::VALIDATE_DEPLOY_ENTRY_POINT_NAME, CairoVersion::Cairo1) => 69_usize,
        (constants::VALIDATE_DECLARE_ENTRY_POINT_NAME, CairoVersion::Cairo0) => 12_usize,
        (constants::VALIDATE_DECLARE_ENTRY_POINT_NAME, CairoVersion::Cairo1) => 49_usize,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 648 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_34Ds96pbQjhlXDCR7:-N_34Ds96pbQjhlXDCR8:b-f0o2bo) ([raw file](https://github.com/starkware-libs/blockifier/blob/3000ce67c009a1c4e4b69f76ff1fcd74d1faea03/crates/blockifier/src/transaction/transactions_test.rs#L648)):*
> ```XML
> fn test_deploy_account_tx(
>     state: &mut CachedState<DictStateReader>,
>     expected_actual_resources: ResourcesMapping,
> ```

Maybe it's better to pass only the parameter that differs between the two cairo versions. That way, it will be easier to notice that something is wrong (we expect the `l1_gas_usage` and the hash builting to be the same. (can be done in another PR).



_Code quote:_
```XML
expected_actual_resources: ResourcesMapping,
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 80 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_33JnWBLt2JDnkmGra:-N_4VOh3ETc8mxt-khFH:b-qp9raq) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1b04da1c909fc8dd268fc8ca013d5ae804d45df/crates/blockifier/src/transaction/transactions_test.rs#L80)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder why adding the `contract_address_salt: felt252` input adds 20 steps
</blockquote></details>

I've generated the account contract code and saw only a difference in the arguments, it uses Span<felt> for arguments.
How can I verify if the number of steps makes sense?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 648 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_34Ds96pbQjhlXDCR7:-N_4UyM-1SppWFxtFPr3:bs7wub4) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1b04da1c909fc8dd268fc8ca013d5ae804d45df/crates/blockifier/src/transaction/transactions_test.rs#L648)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe it's better to pass only the parameter that differs between the two cairo versions. That way, it will be easier to notice that something is wrong (we expect the `l1_gas_usage` and the hash builting to be the same. (can be done in another PR).
</blockquote></details>

Done!

**Review by noaov1 — DISMISSED** [review]
> Reviewed 2 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 80 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_33JnWBLt2JDnkmGra:-N_D31WZ9nDqLR0IRhPj:b-psyslq) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1b04da1c909fc8dd268fc8ca013d5ae804d45df/crates/blockifier/src/transaction/transactions_test.rs#L80)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I've generated the account contract code and saw only a difference in the arguments, it uses Span<felt> for arguments.
How can I verify if the number of steps makes sense?
</blockquote></details>

Maybe ask someone from the compilers team.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 65 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_D3Bc39ca5WLLdPROu:-N_D3Bc39ca5WLLdPROv:b-km8yey) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4283d136805675cf31869c4e8892f7db85ebad6/crates/blockifier/src/transaction/transactions_test.rs#L65)):*
> ```XML
>     class_hash: ClassHash,
>     entry_point_selector_name: &str,
>     retdata: Retdata,
> ```

Maybe it's redundant since you know what should be the return data of `validate` in Cairo 1 contracts. See https://github.com/starkware-libs/blockifier/blob/56d4efcddd55f932cf044b867204b0c758b5cf51/crates/blockifier/src/transaction/constants.rs#L13-L14 (should be merged to `main` soon)
(Can be done in next PR)



_Code quote:_
```XML
retdata: Retdata,
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 80 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_33JnWBLt2JDnkmGra:-N_DKFvq3B2M7hEZVD9f:brnqoaa) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1b04da1c909fc8dd268fc8ca013d5ae804d45df/crates/blockifier/src/transaction/transactions_test.rs#L80)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe ask someone from the compilers team.
</blockquote></details>

I asked IlyaL. Will keep you posted.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 65 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_D3Bc39ca5WLLdPROu:-N_DIhnE9km8QLdpmiYy:b8e990s) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4283d136805675cf31869c4e8892f7db85ebad6/crates/blockifier/src/transaction/transactions_test.rs#L65)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe it's redundant since you know what should be the return data of `validate` in Cairo 1 contracts. See https://github.com/starkware-libs/blockifier/blob/56d4efcddd55f932cf044b867204b0c758b5cf51/crates/blockifier/src/transaction/constants.rs#L13-L14 (should be merged to `main` soon)
(Can be done in next PR)
</blockquote></details>

It means that once the constant parameter is integrated into main, I should use it. However, it is still necessary to indicate whether it is a Cairo0 or Cairo1 contract (as an argument).

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 65 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_D3Bc39ca5WLLdPROu:-N_DYmHPD16-KUS6PtFY:b-1y937z) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4283d136805675cf31869c4e8892f7db85ebad6/crates/blockifier/src/transaction/transactions_test.rs#L65)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It means that once the constant parameter is integrated into main, I should use it. However, it is still necessary to indicate whether it is a Cairo0 or Cairo1 contract (as an argument).
</blockquote></details>

Right (as you already do :)).
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 591 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_DZgTu9jm2-UUMKj1Z:-N_DZgTu9jm2-UUMKj1_:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/802caaa210c2763a9b0b7e7368e47674248de20f/crates/blockifier/src/transaction/transactions_test.rs#L591)):*
> ```XML
>         revert_error: None,
>         actual_resources: ResourcesMapping(HashMap::from([
>             (abi_constants::GAS_USAGE.to_string(), (2 + 2) * 612),
> ```





_Suggestion:_
```XML
       // 1 modified contract, 1 storage update (sender balance).
       (abi_constants::GAS_USAGE.to_string(), (2 + 2) * 612),
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 65 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_D3Bc39ca5WLLdPROu:-N_DibH39wiXRLIOfxV5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4283d136805675cf31869c4e8892f7db85ebad6/crates/blockifier/src/transaction/transactions_test.rs#L65)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Right (as you already do :)).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 591 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/699#-N_DZgTu9jm2-UUMKj1Z:-N_DfUEj6rjPCwjW6IDB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/802caaa210c2763a9b0b7e7368e47674248de20f/crates/blockifier/src/transaction/transactions_test.rs#L591)):*
> ```XML
>         revert_error: None,
>         actual_resources: ResourcesMapping(HashMap::from([
>             (abi_constants::GAS_USAGE.to_string(), (2 + 2) * 612),
> ```

Done.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @alonh5)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/699)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
