### PR TITLE
Remove (some) max_fee() usages

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1044)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1044)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1044#-NhgQRxJ28ZXRA2jrZrR:-NhgQRxJ28ZXRA2jrZrS:bk12f) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/32336)

___

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1044)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1044)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 322 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1044#-NhxKA7QAYaaopM75gH_:-NhxKA7RC9h0NKJ19BFL:bu4npqp) ([raw file](https://github.com/starkware-libs/blockifier/blob/e020a16573170d374e490a9f44b793a5f04ca13b/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L322)):*
> ```XML
>                 }
>             })
>             .into(),
> ```

blocking self, want @elintul 's eyes here



_Code quote:_
```XML
            Felt252::from(match account_tx_context {
                AccountTransactionContext::Current(_) => 0,
                AccountTransactionContext::Deprecated(deprecated_context) => {
                    deprecated_context.max_fee.0
                }
            })
            .into(),
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1044)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 322 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1044#-NhxKA7QAYaaopM75gH_:-Ni-8y880sUxhqFCFt1b:b-jl7ic7) ([raw file](https://github.com/starkware-libs/blockifier/blob/e020a16573170d374e490a9f44b793a5f04ca13b/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L322)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

blocking self, want @elintul 's eyes here
</blockquote></details>

Can you please define a variable, so this line is easier to read?

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1044)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 276 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1044#-Ni4p3KH3TLoql9imE9s:-Ni4p3KI3FNRYK7Y8chh:b-pt9vxy) ([raw file](https://github.com/starkware-libs/blockifier/blob/284511aa3463f47dafef0cd67b4e8a16106c2115/crates/blockifier/src/execution/execution_utils.rs#L276)):*
> ```XML
> }
> 
> pub fn max_fee_for_tx_info(account_tx_context: &AccountTransactionContext) -> Felt252 {
> ```

Perhaps a method of `SyscallHintProcessor`?



_Suggestion:_
```XML
max_fee_for_execution_info
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1044)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1044)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 276 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1044#-Ni4p3KH3TLoql9imE9s:-Ni56ju96OmtE0IFwhhT:buzmihe) ([raw file](https://github.com/starkware-libs/blockifier/blob/284511aa3463f47dafef0cd67b4e8a16106c2115/crates/blockifier/src/execution/execution_utils.rs#L276)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps a method of `SyscallHintProcessor`?
</blockquote></details>

1. would be duplicated (deprecated and non-deprecated don't have shared traits defined in the blockifier; the hint processor trait is from the cairo-vm crate).
2. Doesn't need the struct, only the account execution context; could be an associated function, but why?
(renamed anyway)

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1044)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 276 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1044#-Ni4p3KH3TLoql9imE9s:-Ni9_e9p1X6UgtZGoSFw:b-jbck60) ([raw file](https://github.com/starkware-libs/blockifier/blob/284511aa3463f47dafef0cd67b4e8a16106c2115/crates/blockifier/src/execution/execution_utils.rs#L276)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. would be duplicated (deprecated and non-deprecated don't have shared traits defined in the blockifier; the hint processor trait is from the cairo-vm crate).
2. Doesn't need the struct, only the account execution context; could be an associated function, but why?
(renamed anyway)
</blockquote></details>

I thought it would take the context from the hint processor. Maybe a method of the account context? I tend to avoid floating functions if possible and makes sense.

**Pull request merged**
