### PR TITLE
refactor: change CustomHint error usage into VirtualMachineError::Other(anyhow::Error)

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1397)

### CODE REVIEW

**Review by ArniStarkware — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1397#-:-NpKobQn2M9WxtT1kHo7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1397)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/test_utils.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1397#-NpKpETD5qAIgIX_Fhh-:-NpKpETD5qAIgIX_Fhh0:b-8itqzd) ([raw file](https://github.com/starkware-libs/blockifier/blob/7dd7556cea494a9449e1e9901720ccb9d598be81/crates/blockifier/src/test_utils.rs#L239)):*
> ```XML
>             ) = &hint.1
>             {
>                 assert_eq!(error.to_string(), $expected_hint.to_string());
> ```

why is stringification needed? no `Eq` implemented on anyhow error?
I would prefer object comparison



_Code quote:_
```XML
error.to_string(), $expected_hint.to_string()
```

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1397#-:-NpLO6k36x6Wd4yVY46C:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 217 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1397#-NpL_MPu63mc_PUnK6Lx:-NpL_MPu63mc_PUnK6Ly:b-34w15e) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea0b088cff7536293217452ee152bbbb015b3511/crates/blockifier/src/execution/syscalls/hint_processor.rs#L217)):*
> ```XML
>     ) -> HintExecutionResult {
>         let StarknetHint::SystemCall { system: syscall } = hint else {
>             return Err(HintError::Internal(VirtualMachineError::Other(anyhow::anyhow!(
> ```

actually, is this better with just the `anyhow!` macro or should we keep the internal CustomHint error?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1397)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 217 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1397#-NpL_MPu63mc_PUnK6Lx:-NpOLQ47Euu0BwkRoGxv:b-fgngxd) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea0b088cff7536293217452ee152bbbb015b3511/crates/blockifier/src/execution/syscalls/hint_processor.rs#L217)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

actually, is this better with just the `anyhow!` macro or should we keep the internal CustomHint error?
</blockquote></details>

If we can completely eliminate usages of the CustomHint variant, and this was the last spot... then yeah let's do it

**Pull request merged**
