### PR TITLE
Add Secp256k1 get xy request and response structs.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/689)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/689)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5fFCA7B4CxAJ8dhx8:-NZ5fFCA7B4CxAJ8dhx9:bkt1bwz) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L22)):*
> ```XML
> pub struct Secp256k1GetXyRequest {
>     // The Id of a point as felt.
>     pub ec_point_id: Felt252,
> ```

The pr is too small to see that, but it is more convenient to keep this as felt and have a `secp256k1_get_point` utility function.



_Code quote:_
```XML
    // The Id of a point as felt.
    pub ec_point_id: Felt252,
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/689)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5gkenBpphfT8ycq48:-NZ5gkeoCMrw2C-qmgVR:b-ote7c9) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/execution_utils.rs#L114)):*
> ```XML
>     Ok((high.to_biguint() << 128) + low.to_biguint())
> }
> pub fn write_u256(
> ```

Add a blank line above. Please be mindful to those. :)



_Code quote:_
```XML
pub fn write_u256(
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5gwU34vgSvUlFhHOg:-NZ5gwU34vgSvUlFhHOh:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/execution_utils.rs#L117)):*
> ```XML
>     vm: &mut VirtualMachine,
>     ptr: &mut Relocatable,
>     val: BigUint,
> ```





_Suggestion:_
```XML
value: BigUint
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5h22H7BgX0FAMdvN3:-NZ5h22H7BgX0FAMdvN4:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L17)):*
> ```XML
> };
> 
> // Secp256k1 get xy syscall.
> ```





_Suggestion:_
```XML
Secp256k1GetXy
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5h7i-Dp2YcY9TAOFL:-NZ5h7i-Dp2YcY9TAOFM:bneqhz) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L21)):*
> ```XML
> #[derive(Debug, Eq, PartialEq)]
> pub struct Secp256k1GetXyRequest {
>     // The Id of a point as felt.
> ```

Comment unnecessary, IMO.



_Code quote:_
```XML
// The Id of a point as felt.
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5hK9dBRyFiPe243Og:-NZ5hK9dBRyFiPe243Oh:bu4j6nu) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L35)):*
> ```XML
>     pub x: BigUint,
>     pub y: BigUint,
> }
> ```

Let's define a `EcPoint` struct, and make `Secp256k1GetXyResponse` and `Secp256k1NewRequest`1alias it.



_Code quote:_
```XML
#[derive(Debug, Eq, PartialEq)]
pub struct Secp256k1GetXyResponse {
    pub x: BigUint,
    pub y: BigUint,
}
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5h-nFB56rnHHnDAzr:-NZ5h-nG6LjEdpNlMpBs:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L45)):*
> ```XML
> }
> 
> // Secp256k1 new syscall.
> ```





_Suggestion:_
```XML
Secp256k1New
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/689)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5gkenBpphfT8ycq48:-NZ5l1W19diHCaznDDHO:b-gbdxvz) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/execution_utils.rs#L114)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a blank line above. Please be mindful to those. :)
</blockquote></details>

done.
I'll try but it is pretty much invisible to me.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5gwU34vgSvUlFhHOg:-NZ5l6gT6O_pV9W8I3th:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/execution_utils.rs#L117)):*
> ```XML
>     vm: &mut VirtualMachine,
>     ptr: &mut Relocatable,
>     val: BigUint,
> ```

done
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5h22H7BgX0FAMdvN3:-NZ5l7m52bSpA8gTIBg5:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L17)):*
> ```XML
> };
> 
> // Secp256k1 get xy syscall.
> ```

done
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5h7i-Dp2YcY9TAOFL:-NZ5lA5h9g9DWb06ezhL:b-ql252) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Comment unnecessary, IMO.
</blockquote></details>

great, removed.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5h-nFB56rnHHnDAzr:-NZ5mQ304qjbH0FNArYm:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L45)):*
> ```XML
> }
> 
> // Secp256k1 new syscall.
> ```

done

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/689)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5hK9dBRyFiPe243Og:-NZ5my-JBgeR0c5eQWb5:bm13bbi) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L35)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We keep the point as secp256k1::Affine in the handler, so I think the name `EcPoint` could be somewhat confusing.
</blockquote></details>

but ok,
Done.

**Review by elintul — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/689)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5gkenBpphfT8ycq48:-NZ5nPrB7ATKc6M28Qcz:bgc7vqv) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/execution_utils.rs#L114)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

done.
I'll try but it is pretty much invisible to me.
</blockquote></details>

:heart: 
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5hK9dBRyFiPe243Og:-NZ5nayo1Kb0c7T1Qhpz:b-d4vxx5) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L35)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

but ok,
Done.
</blockquote></details>

Then perhaps `EcPointCoordinates`, or something similar?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/689)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/689#-NZ5hK9dBRyFiPe243Og:-NZ5pCkw1gHMiyYlrzyC:b-k6rpab) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9319247a1d41d78d241ab21bf8cf43f198fc38/crates/blockifier/src/execution/syscalls/secp.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Then perhaps `EcPointCoordinates`, or something similar?
</blockquote></details>

Sounds good, thanks.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/689#-:-NZ5qD-qEYMz_Xwk4Jid:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
