### PR TITLE
feat(execution): compute bouncer weight of reverted tx explicitly

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1576)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1576)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 454 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrG1QgZ8TywkAh8sw22:-NrG1QgZ8TywkAh8sw23:bfyunga) ([raw file](https://github.com/starkware-libs/blockifier/blob/01c52e9f2c1463c5c1248dcc9f7f392919f13bae/crates/blockifier/src/transaction/account_transaction.rs#L454)):*
> ```XML
>             n_allotted_execution_steps - execution_context.n_remaining_steps();
>         let bouncer_revert_resources =
>             actual_cost_builder_with_validation_changes.clone().build(&resources)?.actual_resources;
> ```





_Code quote:_
```XML
        let bouncer_revert_resources =
            actual_cost_builder_with_validation_changes.clone().build(&resources)?.actual_resources;
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1576)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrH2sii4PzQS4qoBjzj:-NrH2sii4PzQS4qoBjzk:b1masp) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/34116)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1576)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 201 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrQ645a58_NK3r4P_kK:-NrUtnvl6JLOkL1Kd0I0:b-gozp9o) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec5615df6d3238a2417235d20d6bc924814bd7a8/crates/blockifier/src/transaction/objects.rs#L201)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should this be part of the tx execution info? @elintul @Yoni-Starkware 
other options:
1. return the bouncer resources from `execute` and `execute_raw` next to the execution info (will require refactoring)
2. create an intermediate class between python's TransactionExecutionInfo and the current struct (perhaps rename current struct to `BlockifierTransactionExecutionInfo` and create a `TransactionExecutionInfo` that is the same, minus the bouncer resources)
</blockquote></details>

went with (2) (see [the PR under this one](https://reviewable.io/reviews/starkware-libs/blockifier/1583))

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1576)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 201 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrQ645a58_NK3r4P_kK:-NrZNK_H47pWtcuLldn1:b-cp2n08) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec5615df6d3238a2417235d20d6bc924814bd7a8/crates/blockifier/src/transaction/objects.rs#L201)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

went with (2) (see [the PR under this one](https://reviewable.io/reviews/starkware-libs/blockifier/1583))
</blockquote></details>

Also note that IMO keeping complete bouncer resources is better than keeping reverted steps...
In the future we may want to keep track of other starknet / OS resources used during execution, and revert the execution part of many resources types

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1576)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 141 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrkUBrgCpPt-iRjz8h7:-NrkUBrgCpPt-iRjz8h8:b-binb1d) ([raw file](https://github.com/starkware-libs/blockifier/blob/5422be8b8a10a5859d6533722d3f113a8e31210f/crates/blockifier/src/blockifier/transaction_executor.rs#L141)):*
> ```XML
> 
>                 // Finalize counting logic.
>                 // TODO(Dori, 1/6/2024): Take the bouncer resources, not the actual resources.
> ```

done [here](https://reviewable.io/reviews/starkware-libs/blockifier/1577)



_Code quote:_
```XML
// TODO(Dori, 1/6/2024): Take the bouncer resources, not the actual resources.
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1576)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrkWjQF1y0vt9fRcmfw:-NrkWjQF1y0vt9fRcmfx:b-s5n31k) ([raw file](https://github.com/starkware-libs/blockifier/blob/5422be8b8a10a5859d6533722d3f113a8e31210f/crates/blockifier/src/fee/actual_cost.rs#L91)):*
> ```XML
>     }
> 
>     /// Call the `build` method to construct the actual cost object, after feeding the builder
> ```

Do we have this convention in rust? (Call -> Calls etc)
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 454 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrG1QgZ8TywkAh8sw22:-Nrkb6XR2E_3gjwwKbqg:b32vi3) ([raw file](https://github.com/starkware-libs/blockifier/blob/01c52e9f2c1463c5c1248dcc9f7f392919f13bae/crates/blockifier/src/transaction/account_transaction.rs#L454)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>


</blockquote></details>

:0
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 637 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrkbvMB-e4mS2riDHSn:-NrkbvMB-e4mS2riDHSo:b-h98uef) ([raw file](https://github.com/starkware-libs/blockifier/blob/5422be8b8a10a5859d6533722d3f113a8e31210f/crates/blockifier/src/transaction/account_transaction.rs#L637)):*
> ```XML
>     revert_error: Option<String>,
>     final_cost: ActualCost,
>     bouncer_resources_override: Option<ResourcesMapping>,
> ```

Why option and why `_override`?



_Code quote:_
```XML
bouncer_resources_override: Option<ResourcesMapping>,
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 201 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrQ645a58_NK3r4P_kK:-NrkaWUz2Tqnv0eBEDhs:b-hfghm4) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec5615df6d3238a2417235d20d6bc924814bd7a8/crates/blockifier/src/transaction/objects.rs#L201)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Also note that IMO keeping complete bouncer resources is better than keeping reverted steps...
In the future we may want to keep track of other starknet / OS resources used during execution, and revert the execution part of many resources types
</blockquote></details>

Sounds good

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1576)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 637 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrkbvMB-e4mS2riDHSn:-Nrktgfp9A8_Yd1sYc8v:b-6stxj1) ([raw file](https://github.com/starkware-libs/blockifier/blob/5422be8b8a10a5859d6533722d3f113a8e31210f/crates/blockifier/src/transaction/account_transaction.rs#L637)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why option and why `_override`?
</blockquote></details>

If transaction is not reverted, the actual resources *are* the bouncer resources. No point in storing a duplicate (see [usage](https://reviewable.io/reviews/starkware-libs/blockifier/1577))

**Review by Yoni-Starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, 2 of 5 files at r3, 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1576)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 637 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrkbvMB-e4mS2riDHSn:-NrniMJO-IkwMPHa19-7:b-d2ddo9) ([raw file](https://github.com/starkware-libs/blockifier/blob/5422be8b8a10a5859d6533722d3f113a8e31210f/crates/blockifier/src/transaction/account_transaction.rs#L637)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

If transaction is not reverted, the actual resources *are* the bouncer resources. No point in storing a duplicate (see [usage](https://reviewable.io/reviews/starkware-libs/blockifier/1577))
</blockquote></details>

Oh, okay. Consider always passing the bouncer_resources for simplicity (they are already cloned and are not written to DB).

We may want to use `bouncer_resources` for more things (e.g., we currently re-calculate many things at the end of the tx execution just for the bouncer)

BTW, since you already de-coupled the execution info from python, wdyt about renaming `actual_resources` -> `fee_resources`, `actual_fee` -> `fee`, or something like this?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1576)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 637 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1576#-NrkbvMB-e4mS2riDHSn:-NrokNK51NKhLBXQKR4_:b-34qlau) ([raw file](https://github.com/starkware-libs/blockifier/blob/5422be8b8a10a5859d6533722d3f113a8e31210f/crates/blockifier/src/transaction/account_transaction.rs#L637)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh, okay. Consider always passing the bouncer_resources for simplicity (they are already cloned and are not written to DB).

We may want to use `bouncer_resources` for more things (e.g., we currently re-calculate many things at the end of the tx execution just for the bouncer)

BTW, since you already de-coupled the execution info from python, wdyt about renaming `actual_resources` -> `fee_resources`, `actual_fee` -> `fee`, or something like this?
</blockquote></details>

Incurs an extra `clone()` in `L1HandlerTransaction::execute_raw` (and extra clones in tests); but worth it IMO.

**Pull request merged**
