### PR TITLE
refactor: remove skip validation checks from stateful validator

### PR DESCRIPTION
**Pull request by Yael-Starkware**
cherry-pick from main: bad24f2543c848202f8fe2c833cd4149fef75d9f

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2034)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
This is a cherry-pick from main , original PR was https://reviewable.io/reviews/starkware-libs/blockifier/2013#-

I took only the blockifier part and ignored the py_validator part since this repo doesn't compile the native_blockifier

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2034#-:-O0sbMSBDUd4jUzw9Kgn:b-wojydu)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ArniStarkware and @dafnamatsry)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2034)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2034#-O0xFMCvEr8xO0WXxNMv:-O0xFMCvEr8xO0WXxNMw:b-m1ugad) ([raw file](https://github.com/starkware-libs/blockifier/blob/3511cd3730ecabea9f5133e83f9f70d75bde1037/crates/blockifier/src/blockifier/stateful_validator.rs#L117)):*
> ```XML
>     ) -> StatefulValidatorResult<Nonce> {
>         Ok(self.tx_executor.state.get_nonce_at(account_address)?)
>     }
> ```

I see this is quite different from the `main` branch. :/



_Code quote:_
```XML
    pub fn get_nonce(
        &mut self,
        account_address: ContractAddress,
    ) -> StatefulValidatorResult<Nonce> {
        Ok(self.tx_executor.state.get_nonce_at(account_address)?)
    }
```
___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2034#-O0xEjQ19XcQrVS7XJ5i:-O0xEjQ19XcQrVS7XJ5j:bw7kdxd) ([raw file](https://github.com/starkware-libs/blockifier/blob/3511cd3730ecabea9f5133e83f9f70d75bde1037/crates/blockifier/src/blockifier/stateful_validator_test.rs#L0)):*
I this PR creates this file on this branch.
IIUC - it is better to just copy the whole test file. This way, the conflict resolution will be simpler (when the time comes).
Another option is just skip the creation of this file.

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2034)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2034#-:-O0xQj1s6PGy5oH2ZfoH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2034)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2034#-O0xFMCvEr8xO0WXxNMv:-O0xpP8ADDMdP5GS7sr9:b-c1mnnh) ([raw file](https://github.com/starkware-libs/blockifier/blob/3511cd3730ecabea9f5133e83f9f70d75bde1037/crates/blockifier/src/blockifier/stateful_validator.rs#L117)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I see this is quite different from the `main` branch. :/
</blockquote></details>

yes unfortunately it is  
___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2034#-O0xEjQ19XcQrVS7XJ5i:-O0xpWDa2MBV2bantjRX:b-auue74) ([raw file](https://github.com/starkware-libs/blockifier/blob/3511cd3730ecabea9f5133e83f9f70d75bde1037/crates/blockifier/src/blockifier/stateful_validator_test.rs#L)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I this PR creates this file on this branch.
IIUC - it is better to just copy the whole test file. This way, the conflict resolution will be simpler (when the time comes).
Another option is just skip the creation of this file.
</blockquote></details>

Not sure, I want to commit only the code that is related to this PR.
Also since the code in not identical to the original PR in main, I think the test does serve a purpose and I wouldn't want to delete it.

**Pull request merged**
