### PR TITLE
chore(concurrency): remove check_done flow from scheduler

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1907)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1907)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1907#-NyTU2GY06tqtAUX1Ypc:-NyTU2GY06tqtAUX1Ypd:b-h2uevo) ([raw file](https://github.com/starkware-libs/blockifier/blob/95238baa2376a97d6807567b4dcb821bcb07659b/crates/blockifier/src/concurrency/scheduler.rs#L105)):*
> ```XML
> 
>         Task::NoTask
>     }
> ```

And call it (in the worker) only if aborted is true



_Suggestion:_
```XML
    /// Updates the Scheduler that a validation task has been finished and triggers the creation of
    /// new tasks in case of failure: schedules validation for higher transactions + re-executes the
    /// current transaction (if ready).
    pub fn finish_validation(&self, tx_index: TxIndex) -> Task {
        self.set_ready_status(tx_index);
        if self.execution_index.load(Ordering::Acquire) > tx_index
            && self.try_incarnate(tx_index)
        {
            return Task::ExecutionTask(tx_index);
        }

        Task::NoTask
    }
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1907#-NyTU2GY06tqtAUX1Ypc:-NyU4W78DcJ177M9mHuq:bmfan94) ([raw file](https://github.com/starkware-libs/blockifier/blob/95238baa2376a97d6807567b4dcb821bcb07659b/crates/blockifier/src/concurrency/scheduler.rs#L105)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

And call it (in the worker) only if aborted is true
</blockquote></details>

maybe rename the method to `finish_abort` then?

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1907)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1907#-NyTU2GY06tqtAUX1Ypc:-NyU6maqBH_uJdZCfTnW:b-hfghm4) ([raw file](https://github.com/starkware-libs/blockifier/blob/95238baa2376a97d6807567b4dcb821bcb07659b/crates/blockifier/src/concurrency/scheduler.rs#L105)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

maybe rename the method to `finish_abort` then?
</blockquote></details>

Sounds good

**Review by avi-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1907#-:-NyU3eZ7E-ZvPEeYGkYP:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1907#-NyTU2GY06tqtAUX1Ypc:-NyU7GSi8R-WM-sbyTy0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/95238baa2376a97d6807567b4dcb821bcb07659b/crates/blockifier/src/concurrency/scheduler.rs#L105)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Sounds good
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1907#-:-NyU9VF13WFIS1CdCOIw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1907)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

**Pull request merged**
