### PR TITLE
fix(concurrency): remove compiled_class_hashes check from validate_reads

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1954)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1954#-NzYBogr1OeLK-pV5K35:-NzYBogs8qS_MhoQZYQz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/28c3d6a4d70902ab92b2bcbb596fa45b9adfcd7b/crates/blockifier/src/concurrency/versioned_state.rs#L122)):*
> ```XML
>         }
> 
>         // We do not check the compiled_class_hashes mapping here because papyrus storage soes not
> ```





_Suggestion:_
```XML
does
```

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1954)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 311 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1954#-NzcTUwUBjW3ryoiJjXl:-NzcTUwUBjW3ryoiJjXm:b-nobkf4) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a788308a84c97f06742639a75222dacb1c18e91/crates/blockifier/src/concurrency/versioned_state.rs#L311)):*
> ```XML
>                 }
>                 Err(StateError::UndeclaredClassHash(class_hash)) => {
>                     state.declared_contracts.set_initial_value(class_hash, false);
> ```

And restore the above.



_Suggestion:_
```XML
                Err(StateError::UndeclaredClassHash(class_hash)) => {
                    state.declared_contracts.set_initial_value(class_hash, false);
                    state.compiled_class_hashes.set_initial_value(class_hash, CompiledClassHash(StarkFelt::ZERO))
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1954)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 311 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1954#-NzcTUwUBjW3ryoiJjXl:-Nzcet9w8tU1trMSOq2V:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a788308a84c97f06742639a75222dacb1c18e91/crates/blockifier/src/concurrency/versioned_state.rs#L311)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And restore the above.
</blockquote></details>

Done.

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1954#-:-NzcjIQI0szw9xMfkhDe:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1954#-NzcjBA277Yjyz-IdiUR:-NzcjBA277Yjyz-IdiUS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/24a7acb7b1acf380792216763e57ecf6546a4a6b/crates/blockifier/src/concurrency/versioned_state.rs#L318)):*
> ```XML
>                     state.declared_contracts.set_initial_value(class_hash, false);
>                     // Papyrus storage does not support read action for compiled_class_hashes
>                     //  values. We are artificially insert StarkFelt::ZERO for undeclared contracts.
> ```





_Suggestion:_
```XML
We artificially insert
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1954#-NzchglJ0gsK3l71RJFm:-NzchglK7cMHQiz6gdmf:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/24a7acb7b1acf380792216763e57ecf6546a4a6b/crates/blockifier/src/concurrency/versioned_state.rs#L318)):*
> ```XML
>                     state.declared_contracts.set_initial_value(class_hash, false);
>                     // Papyrus storage does not support read action for compiled_class_hashes
>                     //  values. We are artificially insert StarkFelt::ZERO for undeclared contracts.
> ```





_Suggestion:_
```XML
                    // Papyrus storage does not support read action for compiled class hashes
                    //  values. We are artificially insert zero for undeclared contracts.
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1954#-:-NzhoT4r3qTtuabiZ-h_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
