### PR TITLE
refactor(state): replace GlobalContractCache default with GlobalContractCache new

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1368)

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1368)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-Noqv7Gi4dXh_vHy5baz:-Noqv7Gj8bS5eqXL009T:b-jbil7y) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/blockifier/src/state/cached_state.rs#L190)):*
> ```XML
> impl<S: StateReader> From<S> for CachedState<S> {
>     fn from(state_reader: S) -> Self {
>         CachedState::new(state_reader, GlobalContractCache::new(100))
> ```

Can this constant be extracted to a shared constant, and coupled with a TODO or an explanation for this constant? How ideally this constant should come from general config, but for testing / other needs, it is set here.



_Code quote:_
```XML
100
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/state/cached_state.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-Nozf_ZM2oTQ3wuYzPBQ:-Nozf_ZN9RSQ7ZNEpB0d:b-85nnnw) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/blockifier/src/state/cached_state.rs#L369)):*
> ```XML
>             cache: Default::default(),
>             class_hash_to_class: Default::default(),
>             global_class_hash_to_class: GlobalContractCache::new(100),
> ```

Constant.

Can this function (Default for `CachedState`) be replaced with `create_for_testing`?
This will solve some of the missuse concerns we had. 



_Code quote:_
```XML
:new(100)
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1368)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 378 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-NozfPxsBlu435kgXRN3:-NozfPxsBlu435kgXRN4:bqsw4o9) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/blockifier/src/state/cached_state_test.rs#L378)):*
> ```XML
>     // Initialize the global cache with a single class, and initialize an empty state with this
>     // cache.
>     let mut global_cache = GlobalContractCache::new(100);
> ```

constant



_Code quote:_
```XML
ew(100
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-NozfO4N9l4NBdVdokLP:-NozfO4N9l4NBdVdokLQ:bqsw4o9) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/native_blockifier/src/py_block_executor.rs#L207)):*
> ```XML
>             max_recursion_depth: 50,
>             tx_executor: None,
>             global_contract_cache: GlobalContractCache::new(100),
> ```

constant



_Code quote:_
```XML
(100)
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-NozfM-D7hqubzy_8RaA:-NozfM-D7hqubzy_8RaB:bqsw4o9) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/native_blockifier/src/py_block_executor.rs#L230)):*
> ```XML
>             max_recursion_depth: 50,
>             tx_executor: None,
>             global_contract_cache: GlobalContractCache::new(100),
> ```

constant



_Code quote:_
```XML
100
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-NozfEcz9_OZ5bm262Ua:-NozfEd-44Kp_Mlfair6:bqsw4o9) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/native_blockifier/src/py_validator.rs#L119)):*
> ```XML
>             next_block_info,
>             max_recursion_depth,
>             GlobalContractCache::new(100),
> ```

constant



_Code quote:_
```XML
100
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1368)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-Nozf_ZM2oTQ3wuYzPBQ:-NozhS3oDH0JIMMuygDv:btok837) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/blockifier/src/state/cached_state.rs#L369)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Constant.

Can this function (Default for `CachedState`) be replaced with `create_for_testing`?
This will solve some of the missuse concerns we had.
</blockquote></details>

I think it is better with the constant as it is clear that it is for testing and we use the new explicitly.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 378 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-NozfPxsBlu435kgXRN3:-NozhK-T6unHg1vfQrbp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/blockifier/src/state/cached_state_test.rs#L378)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

constant
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-NozfO4N9l4NBdVdokLP:-NozhKcV2RqkVTcDBKhH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/native_blockifier/src/py_block_executor.rs#L207)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

constant
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-NozfM-D7hqubzy_8RaA:-NozhL2LB1ahAMQnO2Id:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/native_blockifier/src/py_block_executor.rs#L230)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

constant
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-NozfEcz9_OZ5bm262Ua:-NozhLZs4ev5ony00T0T:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/native_blockifier/src/py_validator.rs#L119)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

constant
</blockquote></details>

Done.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1368)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-Nozf_ZM2oTQ3wuYzPBQ:-NozicmM0--4WcCRjnOl:b-d9prz) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/blockifier/src/state/cached_state.rs#L369)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

I think it is better with the constant as it is clear that it is for testing and we use the new explicitly.
</blockquote></details>

Well, This is exactly the issue with default... people will use `default` unless they look into it. I like the idea of postponing this fix to another PR and adding a TODO here.

This is not a good default ATM. 
___
*[`crates/blockifier/src/state/cached_state.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-NozjVW25OktDBgSy89B:-NozjVW25OktDBgSy89C:b-xxd1as) ([raw file](https://github.com/starkware-libs/blockifier/blob/4ee9df5a2543bc150d3eaff97f2f4c548877caa8/crates/blockifier/src/state/cached_state.rs#L189)):*
> ```XML
> #[cfg(any(feature = "testing", test))]
> impl<S: StateReader> From<S> for CachedState<S> {
>     fn from(state_reader: S) -> Self {
> ```

Add a TODO: replace with: `from_for_testing`.



_Code quote:_
```XML
    fn from(state_reader: S) -> Self {
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 730 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-Nozjl_L-DgTNULe6Cr6:-Nozjl_L-DgTNULe6Cr7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4ee9df5a2543bc150d3eaff97f2f4c548877caa8/crates/blockifier/src/state/cached_state.rs#L730)):*
> ```XML
> pub struct GlobalContractCache(pub Arc<Mutex<ContractClassLRUCache>>);
> 
> pub const TEST_GLOBAL_CONTRACT_CACHE_SIZE: usize = 100;
> ```





_Suggestion:_
```XML
GLOBAL_CONTRACT_CACHE_SIZE_FOR_TEST
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1368)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-Nozf_ZM2oTQ3wuYzPBQ:-NozncLMCEeixhMGLJJG:bpdu4eu) ([raw file](https://github.com/starkware-libs/blockifier/blob/20660f6a1a21f4c91e20c63ceb7cfa763f7aa876/crates/blockifier/src/state/cached_state.rs#L369)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Well, This is exactly the issue with default... people will use `default` unless they look into it. I like the idea of postponing this fix to another PR and adding a TODO here.

This is not a good default ATM.
</blockquote></details>

No need, the comment limits this code for testing only.
___
*[`crates/blockifier/src/state/cached_state.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-NozjVW25OktDBgSy89B:-NoznXj64CXYAq9rePFl:bpdu4eu) ([raw file](https://github.com/starkware-libs/blockifier/blob/4ee9df5a2543bc150d3eaff97f2f4c548877caa8/crates/blockifier/src/state/cached_state.rs#L189)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add a TODO: replace with: `from_for_testing`.
</blockquote></details>

No need, the comment limits this code for testing only.
___
*[`crates/blockifier/src/state/cached_state.rs` line 730 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-Nozjl_L-DgTNULe6Cr6:-Nozo5R78CLY-soSRHUK:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/4ee9df5a2543bc150d3eaff97f2f4c548877caa8/crates/blockifier/src/state/cached_state.rs#L730)):*
> ```XML
> pub struct GlobalContractCache(pub Arc<Mutex<ContractClassLRUCache>>);
> 
> pub const TEST_GLOBAL_CONTRACT_CACHE_SIZE: usize = 100;
> ```

Done

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1368#-:-NozpNNhBfJQ2mV_8E80:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Pull request merged**
