### PR TITLE
Create intiail state for Python testing.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @dorimedini-starkware)

___
*[`crates/native_blockifier/native_blockifier/py_feature_contracts/dummy_account.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOxXsEMA0aRWnfG_cjk:-NOxXsEMA0aRWnfG_cjl:bruzfov) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da65bf6d5af76be7eca90c12345ce7aa309bc43/crates/native_blockifier/native_blockifier/py_feature_contracts/dummy_account.cairo#L1)):*
> ```Cairo
> // A dummy account contract without any validations.
> ```

Remove, this is `crates/blockifier/feature_contracts/account_without_validations.cairo`.
___
*[`crates/native_blockifier/native_blockifier/py_feature_contracts/test_contract.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOxXztv1PoXYhPOUwVW:-NOxXztw9Ck30g7NNrrA:bhjmzag) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da65bf6d5af76be7eca90c12345ce7aa309bc43/crates/native_blockifier/native_blockifier/py_feature_contracts/test_contract.cairo#L1)):*
> ```Cairo
> %lang starknet
> ```

Why duplicate this?
Why not access the existing contracts?
___
*[`crates/native_blockifier/src/py_test_utils.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOxYwgK2P0mHbHo3Rmk:-NOxYwgK2P0mHbHo3Rml:bfli0r1) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da65bf6d5af76be7eca90c12345ce7aa309bc43/crates/native_blockifier/src/py_test_utils.rs#L18)):*
> ```XML
> pub const ACCOUNT_CONTRACT_ADDRESS: &str = "0x2d2";
> 
> pub fn create_py_test_state() -> CachedState<DictStateReader> {
> ```

What about `token_for_testing,cairo`?
The test contract can be declared and deployed by transactions.
See [prepare_end_to_end_txs](https://github.com/starkware-industries/starkware/blob/5bde2277c083bfdc7dab5e2adf2c1c3e94c62b3e/src/starkware/starknet/services/utils/test_utils.py#L848). 

My intention was to only put in the state apriori (not through transactions) the minimum needed (i.e., the contracts declared with `Declare` of version 0), so the rest of the transactions created in this function can be used.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_test_utils.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOxYwgK2P0mHbHo3Rmk:-NOxebsw2PpHreNR4_yO:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da65bf6d5af76be7eca90c12345ce7aa309bc43/crates/native_blockifier/src/py_test_utils.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about `token_for_testing,cairo`?
The test contract can be declared and deployed by transactions.
See [prepare_end_to_end_txs](https://github.com/starkware-industries/starkware/blob/5bde2277c083bfdc7dab5e2adf2c1c3e94c62b3e/src/starkware/starknet/services/utils/test_utils.py#L848). 

My intention was to only put in the state apriori (not through transactions) the minimum needed (i.e., the contracts declared with `Declare` of version 0), so the rest of the transactions created in this function can be used. 
</blockquote></details>

Done.
___
*[`crates/native_blockifier/native_blockifier/py_feature_contracts/dummy_account.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOxXsEMA0aRWnfG_cjk:-NOxelpK6PVsjJRq0t3y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da65bf6d5af76be7eca90c12345ce7aa309bc43/crates/native_blockifier/native_blockifier/py_feature_contracts/dummy_account.cairo#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove, this is `crates/blockifier/feature_contracts/account_without_validations.cairo`.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/native_blockifier/py_feature_contracts/test_contract.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOxXztv1PoXYhPOUwVW:-NOxefof1Hz-iF__8eyu:bss4a2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da65bf6d5af76be7eca90c12345ce7aa309bc43/crates/native_blockifier/native_blockifier/py_feature_contracts/test_contract.cairo#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why duplicate this?
Why not access the existing contracts?
</blockquote></details>

Removed.

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_test_utils.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOyRBmt33k0dcT8U-q5:-NOyRBmuCPbRRW741Ivw:bozl8qa) ([raw file](https://github.com/starkware-libs/blockifier/blob/235fbeb02a3981487322be84b457dc76b35fd95b/crates/native_blockifier/src/py_test_utils.rs#L14)):*
> ```XML
> pub const TOKEN_FOR_TESTING_CONTRACT_PATH: &str =
>     "./src/starkware/starknet/core/test_contract/starknet_compiled_contracts_lib/starkware/\
>      starknet/core/test_contract/token_for_testing.json";
> ```

How does this work?
Not sure I want to depend on the Python repo.



_Code quote:_
```XML
    "./src/starkware/starknet/core/test_contract/starknet_compiled_contracts_lib/starkware/\
     starknet/core/test_contract/token_for_testing.json";
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_test_utils.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOxYwgK2P0mHbHo3Rmk:-NOyURLl5Sx2DA9jYVK5:bed2bon) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da65bf6d5af76be7eca90c12345ce7aa309bc43/crates/native_blockifier/src/py_test_utils.rs#L18)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we also need an account; note `prepare_end_to_end_txs()` uses two contracts.
___
*[`crates/native_blockifier/src/py_test_utils.rs` line 11 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOyUKI24uCtl2xDGviP:-NOyUKI24uCtl2xDGviQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/235fbeb02a3981487322be84b457dc76b35fd95b/crates/native_blockifier/src/py_test_utils.rs#L11)):*
> ```XML
> 
> pub const TOKEN_FOR_TESTING_CLASS_HASH: &str = "0x30";
> // This package is run within the starkware build directory.
> ```





_Suggestion:_
```XML
StarkWare repo.
```
___
*[`crates/native_blockifier/src/py_test_utils.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOyRBmt33k0dcT8U-q5:-NOyUC-u7QhtXU0ibIm5:b-kdsvgs) ([raw file](https://github.com/starkware-libs/blockifier/blob/235fbeb02a3981487322be84b457dc76b35fd95b/crates/native_blockifier/src/py_test_utils.rs#L14)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How does this work?
Not sure I want to depend on the Python repo.
</blockquote></details>

Perhaps it's okay, since it's temporary (until we support `Declare` of version 0).

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_test_utils.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/296#-NOxYwgK2P0mHbHo3Rmk:-NOyoiy_7Gd05ieQnfOv:b-5wccio) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da65bf6d5af76be7eca90c12345ce7aa309bc43/crates/native_blockifier/src/py_test_utils.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we also need an account; note `prepare_end_to_end_txs()` uses two contracts.
</blockquote></details>

I think we can declare and deploy an additional account with `token_for_testing.cairo` (which is also an account).

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296#-:-NOyqWKX1OZqs74df9m-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/296)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
