### PR TITLE
refactor(execution, native_blockifier): make TransactionExecutor.fina…

### PR DESCRIPTION
**Pull request by barak-b-starkware**
…lize() work without Py objects

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1418)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1418)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1418#-Npoy1qBEFInYRMtd74J:-Npoy1qBEFInYRMtd74K:b-91dlt) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7c6093a5da24ccd063d84ff0bafa0bad58bf62b/crates/native_blockifier/src/py_block_executor.rs#L125)):*
> ```XML
>             .iter()
>             .map(|(class_hash, class_visited_pcs_vec)| {
>                 (PyFelt::from(*class_hash), class_visited_pcs_vec.clone())
> ```

Any way to avoid this, can we take ownership?



_Code quote:_
```XML
clone()
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1418)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1418)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1418#-Npoy1qBEFInYRMtd74J:-NpsrV2z1ec8udKALLYS:bdqb31d) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7c6093a5da24ccd063d84ff0bafa0bad58bf62b/crates/native_blockifier/src/py_block_executor.rs#L125)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Any way to avoid this, can we take ownership?
</blockquote></details>

Can you explain the change?

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1418)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1418)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1418#-:-NptVBwQ5Om-Pam4LC2j:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Comment by barak-b-starkware** [comment]
*[`crates/native_blockifier/src/py_block_executor.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1418#-Npoy1qBEFInYRMtd74J:-Npty-d1CmomY-sdiTLP:bq65jru) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7c6093a5da24ccd063d84ff0bafa0bad58bf62b/crates/native_blockifier/src/py_block_executor.rs#L125)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain the change?
</blockquote></details>

Done.
I replace `iter()` with `into_iter()`. `into_iter()` takes ownership, as you suggested (:



_Code quote:_
```XML
            .into_iter()
```

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1418#-:-Npu1kkZ72Ybz-maiB-J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1418)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
