### PR TITLE
Refactor to use allocate_data_segment method

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgwtWvNEEg1Dih0n6nt:-NgwtWvNEEg1Dih0n6nu:b-bllr52) (no related file):*
Consider defining the method in this PR + usages (rebasing over `main`).
Then the other PR can be rebased over this one.

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgwuFSoB2KftGcMBFja:-NgwuFSoB2KftGcMBFjb:bs0b4c7) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4990c00076d8fa5932aab7f834e43a50ba5081a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L386)):*
> ```XML
>             self.read_only_segments.allocate(vm, &additional_info)?;
> 
>         Ok(execution_info_segment_start_ptr)
> ```

what about this?



_Code quote:_
```XML
        let block_info_ptr = self.allocate_block_info_segment(vm)?;
        let tx_info_ptr = self.allocate_tx_info_segment(vm)?;

        let additional_info: Vec<MaybeRelocatable> = vec![
            block_info_ptr.into(),
            tx_info_ptr.into(),
            stark_felt_to_felt(*self.caller_address().0.key()).into(),
            stark_felt_to_felt(*self.storage_address().0.key()).into(),
            stark_felt_to_felt(self.entry_point_selector().0).into(),
        ];
        let execution_info_segment_start_ptr =
            self.read_only_segments.allocate(vm, &additional_info)?;

        Ok(execution_info_segment_start_ptr)
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 433 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/988#-Ngwu3Vq0Y8A9jGsMAHA:-Ngwu3Vq0Y8A9jGsMAHB:b-du6xl6) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4990c00076d8fa5932aab7f834e43a50ba5081a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L433)):*
> ```XML
>             &self.allocate_data_segment(vm, resource_bounds)?;
>         let resource_bounds_end_ptr = (*resource_bounds_segment_start_ptr
>             + (RESOURCE_BOUNDS_ELEMENT_SIZE * context.resource_bounds.0.len()))?;
> ```

delete the constant (should be unused after my next comment)



_Code quote:_
```XML
RESOURCE_BOUNDS_ELEMENT_SIZE
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgwtpQE2y3NjNwlobL3:-NgwtpQFEWA_JG-PlbLa:bv0ee7c) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4990c00076d8fa5932aab7f834e43a50ba5081a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L435)):*
> ```XML
>             + (RESOURCE_BOUNDS_ELEMENT_SIZE * context.resource_bounds.0.len()))?;
> 
>         Ok((*resource_bounds_segment_start_ptr, resource_bounds_end_ptr))
> ```

`allocate_data_segment` computes the correct end ptr for you; no need for the computation. no?



_Suggestion:_
```XML
        self.allocate_data_segment(vm, resource_bounds)
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgwtWvNEEg1Dih0n6nt:-NgyXLra5glsRPnCdpwS:bd2demq) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider defining the method in this PR + usages (rebasing over `main`).
Then the other PR can be rebased over this one.
</blockquote></details>

Do you think it is worth changing the PRs' hierarchy?
What do you think about merging both PRs at the same time?

___
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgwuFSoB2KftGcMBFja:-NgyVkED0YZb2AKHFQ4S:b-ai3fb8) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4990c00076d8fa5932aab7f834e43a50ba5081a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L386)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about this?
</blockquote></details>

In this scenario, there is a bit of complexity. `block_info_ptr` and `tx_info_ptr` are of type `Relocatable`, while the data vector used in `allocate_data_segment` consists of `StarkFelt` elements.
The conversion is not straightforward.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 433 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/988#-Ngwu3Vq0Y8A9jGsMAHA:-NgyUHnfCIazK24Z6aBv:b-iht2gc) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4990c00076d8fa5932aab7f834e43a50ba5081a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L433)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete the constant (should be unused after my next comment)
</blockquote></details>

Please see my comment below.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgwtpQE2y3NjNwlobL3:-NgyToqVC6i8jLwan_F-:b-t5xuwz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4990c00076d8fa5932aab7f834e43a50ba5081a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L435)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`allocate_data_segment` computes the correct end ptr for you; no need for the computation. no?
</blockquote></details>

No, the calculation in `allocate_data_segment` is not accurate for this case because it assumes the array consists of felt elements. Here, each element comprises three felts, which leads to an incorrect end pointer calculation in `allocate_data_segment`.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgwtpQE2y3NjNwlobL3:-NgyevnNBpx-AUMhNUYy:bv7sekg) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4990c00076d8fa5932aab7f834e43a50ba5081a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L435)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM?
the `resource_bounds` vector you provide to ``allocate_data_segment` is after `flat_map(...).collect()`; shouldn't that result in a vector of 6 felts?
</blockquote></details>

You're correct.
Fixed.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 331 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgyvHmJ8_YwjG18HLt4:-NgyvHmJ8_YwjG18HLt5:b-cex8rd) ([raw file](https://github.com/starkware-libs/blockifier/blob/6657f85500d22a5cbb3239ae99df96f98cda287b/crates/blockifier/src/execution/syscalls/hint_processor.rs#L331)):*
> ```XML
>             &self.allocate_data_segment(vm, resource_bounds)?;
> 
>         Ok((*resource_bounds_segment_start_ptr, *resource_bounds_end_ptr))
> ```

isn't this equivalent?



_Suggestion:_
```XML
        self.allocate_data_segment(vm, resource_bounds)
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 331 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgyvHmJ8_YwjG18HLt4:-Nh0Okpl15d_UlUwbnsd:b-7lplc8) ([raw file](https://github.com/starkware-libs/blockifier/blob/6657f85500d22a5cbb3239ae99df96f98cda287b/crates/blockifier/src/execution/syscalls/hint_processor.rs#L331)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't this equivalent?
</blockquote></details>

Yes, it is.
Updated.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988#-:-Nh0TOyRCEfe8UEk9M8o:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgwtWvNEEg1Dih0n6nt:-Nh1CBzo86hdL_B55h0V:by2rjmi) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do you think it is worth changing the PRs' hierarchy?
What do you think about merging both PRs at the same time?
</blockquote></details>

I would have opened a preliminary PR with a util function, which will be much easier to merge; but your call.

___
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 425 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/988#-Nh1COGhAW2qfHNGF3uf:-Nh1COGhAW2qfHNGF3ug:b-ihmm1v) ([raw file](https://github.com/starkware-libs/blockifier/blob/81ed694a3d3ccebd13fccd9306d88935d82ba10a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L425)):*
> ```XML
>                 StarkFelt::from(block_context.block_timestamp.0),
>                 *block_context.sequencer_address.0.key(),
>             ],
> ```

Define a variable, so this line is easier to read.



_Code quote:_
```XML
            vec![
                StarkFelt::from(block_context.block_number.0),
                StarkFelt::from(block_context.block_timestamp.0),
                *block_context.sequencer_address.0.key(),
            ],
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NgwtWvNEEg1Dih0n6nt:-Nh68PUFBK1aG3a7Pshe:b-onz9bm) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I would have opened a preliminary PR with a util function, which will be much easier to merge; but your call.
</blockquote></details>

Do you suggest creating a new PR that only contains the `allocate_data_segment` function and making it the base branch for [this](https://reviewable.io/reviews/starkware-libs/blockifier/984)?
So, it means no further changes are needed for this PR, correct?

___

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NhWUcSLDe7eZdTvXVch:-NhWUcSM4w0w8GS2xymP:b-m74pgg) (no related file):*
After this PR all locations where we allocate a segment for an array of felts use your method?

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NhWUcSLDe7eZdTvXVch:-NhXaM9M6fPblQHo5oQa:bkrirbn) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

After this PR all locations where we allocate a segment for an array of felts use your method?
</blockquote></details>

Yes, it should be the case!

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 432 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NhXh4Vj7O46_YbtCu9W:-NhXh4Vj7O46_YbtCu9X:bruxd52) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f13b3f21062fe700f4276ee91395884d4145bd4/crates/blockifier/src/execution/syscalls/hint_processor.rs#L432)):*
> ```XML
>         let block_info: Vec<StarkFelt> = if self.is_validate_mode() {
>             vec![StarkFelt::ZERO; 3]
>         } else {
> ```

1. what's this...?
2. why the magic number? what defines the size of block info? maybe add a named const



_Code quote:_
```XML
        let block_info: Vec<StarkFelt> = if self.is_validate_mode() {
            vec![StarkFelt::ZERO; 3]
        } else {
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 432 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NhXh4Vj7O46_YbtCu9W:-NhXjKdJEEb0GT0A_ZgP:btdo9mh) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f13b3f21062fe700f4276ee91395884d4145bd4/crates/blockifier/src/execution/syscalls/hint_processor.rs#L432)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. what's this...?
2. why the magic number? what defines the size of block info? maybe add a named const
</blockquote></details>

I think it popped out when rebased. I think Yoni added this code.
Ill check it tomorrow.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 432 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NhXh4Vj7O46_YbtCu9W:-Nh_e5yS2DVeLzJx2CHI:b-bn11lf) ([raw file](https://github.com/starkware-libs/blockifier/blob/361af04dc4544cc049033a499e24e5c2b524a405/crates/blockifier/src/execution/syscalls/hint_processor.rs#L432)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think it popped out when rebased. I think Yoni added this code.
Ill check it tomorrow.
</blockquote></details>

It seems that @Yoni-Starkware has added this code.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NhWUcSLDe7eZdTvXVch:-Ni4ZgrC1TwR0Pt45kPC:b-ssybns) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Yes, it should be the case!
</blockquote></details>

Can you please make sure?

___
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 112 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/988#-Ni4ZY4vAR5HqUAODWeL:-Ni4ZY4vAR5HqUAODWeM:bng03sv) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad5fab84e3cf9555c4f1279deb73003140a56bc0/crates/blockifier/src/execution/syscalls/hint_processor.rs#L112)):*
> ```XML
>     "0x00000000000000000000000000000000496e76616c696420617267756d656e74";
> // Each resource bound contains three felts; see struct `Resource`.
> pub const RESOURCE_BOUNDS_ELEMENT_SIZE: usize = 3;
> ```

How come this isn't needed anymore?



_Code quote:_
```XML
pub const RESOURCE_BOUNDS_ELEMENT_SIZE: usize = 3;
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 325 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/988#-Ni4ZR0q8w2gIldbjHTI:-Ni4ZR0r4Wf2JtHhWzM1:b-rjj3xr) ([raw file](https://github.com/starkware-libs/blockifier/blob/361af04dc4544cc049033a499e24e5c2b524a405/crates/blockifier/src/execution/syscalls/hint_processor.rs#L325)):*
> ```XML
>             .iter()
>             .flat_map(|(resource, resource_bounds)| {
>                 // Convert the key (resource) to an int.
> ```

Remove, you're repeating the code.



_Code quote:_
```XML
// Convert the key (resource) to an int.
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 504 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/988#-Ni4ZmZxAC0WPdpLbWnu:-Ni4ZmZxAC0WPdpLbWnv:bk1pi81) ([raw file](https://github.com/starkware-libs/blockifier/blob/361af04dc4544cc049033a499e24e5c2b524a405/crates/blockifier/src/execution/syscalls/hint_processor.rs#L504)):*
> ```XML
>                 tx_info.extend_from_slice(&[
>                     zero_felt.clone(), // Empty list of ResourceBound
>                     zero_felt.clone(),
> ```

For all empty segments (change from last PR: to segment rather than array, and added the parenthesis).



_Suggestion:_
```XML
                    zero_felt.clone(), // Empty segment of resource bounds (start ptr).
                    zero_felt.clone(), // Empty segment of resource bounds (end ptr).
```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 112 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/988#-Ni4ZY4vAR5HqUAODWeL:-Ni4fLQa3Gk2kiQe3EPZ:b-58abbo) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad5fab84e3cf9555c4f1279deb73003140a56bc0/crates/blockifier/src/execution/syscalls/hint_processor.rs#L112)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come this isn't needed anymore?
</blockquote></details>

Since I used `flat_resource_bound`, which is already of size 3.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/988#-NhWUcSLDe7eZdTvXVch:-Ni4i58zCXJnS9CvnjXR:b-y5dvo1) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you please make sure?
</blockquote></details>

I think all the locations were updated.
I see that only `allocate_execution_info_segment` doesn't use our method. As cannot convert from an array of `Relocatable` to of `StarkFelt`.

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 433 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/988#-Ni4mZClAkULb7-DTwXx:-Ni4mZClAkULb7-DTwXy:b-j5syhi) ([raw file](https://github.com/starkware-libs/blockifier/blob/3fe6cbbbc317ed59ea06333ff0d02690f44299f6/crates/blockifier/src/execution/syscalls/hint_processor.rs#L433)):*
> ```XML
>                 StarkFelt::ZERO,
>                 // TODO(Yoni, 1/5/2024): set the timestamp to be zero for `validate``.
>                 StarkFelt::from(block_context.block_timestamp.0),
> ```

isn't it dangerous to merge like this...? we may end up with transactions in the system with nonzero timestamps in validate



_Code quote:_
```XML
                // TODO(Yoni, 1/5/2024): set the timestamp to be zero for `validate``.
                StarkFelt::from(block_context.block_timestamp.0),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 433 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/988#-Ni4mZClAkULb7-DTwXx:-Ni4nDG38Qc7Hvta3C4j:b-5fhlz9) ([raw file](https://github.com/starkware-libs/blockifier/blob/3fe6cbbbc317ed59ea06333ff0d02690f44299f6/crates/blockifier/src/execution/syscalls/hint_processor.rs#L433)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't it dangerous to merge like this...? we may end up with transactions in the system with nonzero timestamps in validate
</blockquote></details>

I think it was decided to turn zero-ing the TS on only in `0.13.0`.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988#-:-Ni4nQF0APBu5qIDU5qj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/988)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 433 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/988#-Ni4mZClAkULb7-DTwXx:-Ni55dJsAvTgkEqJ6Wng:b-47jotm) ([raw file](https://github.com/starkware-libs/blockifier/blob/3fe6cbbbc317ed59ea06333ff0d02690f44299f6/crates/blockifier/src/execution/syscalls/hint_processor.rs#L433)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it was decided to turn zero-ing the TS on only in `0.13.0`.
</blockquote></details>

ok there's a TODO... best we can do for now

**Pull request merged**
