### PR TITLE
feat(fee): add ClassLengths struct to ActualCostBuilder

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @ayeletstarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npu3H4U7Q1gFrHivdij:-Npu3H4U7Q1gFrHivdik:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0bb1cc3c7192a2951914b44fe875fe5bda9d465/crates/blockifier/src/execution/contract_class.rs#L58)):*
> ```XML
>     pub fn bytecode_length(&self) -> usize {
>         match self {
>             ContractClass::V0(_) => 0,
> ```





_Suggestion:_
```XML
ContractClass::V0(class) => class.bytecode_length(),
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npu3Nkh-P9IeiZDZFAD:-Npu3Nkh-P9IeiZDZFAE:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0bb1cc3c7192a2951914b44fe875fe5bda9d465/crates/blockifier/src/fee/actual_cost.rs#L59)):*
> ```XML
>     class_lengths: Option<ClassLengths>,
>     #[allow(dead_code)]
>     signature_length: usize,
> ```





_Suggestion:_
```XML
    // TODO(Avi,10/02/2024): use this field and remove the clippy tag.
    #[allow(dead_code)]
    signature_length: usize,
    class_lengths: Option<ClassLengths>,
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npu3c8n--F8pt5S-g8j:-Npu3c8n--F8pt5S-g8k:b-suv37h) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0bb1cc3c7192a2951914b44fe875fe5bda9d465/crates/blockifier/src/transaction/transactions.rs#L105)):*
> ```XML
> }
> 
> #[derive(Debug, Clone, Copy)]
> ```

Alphabetize?



_Code quote:_
```XML
Debug, Clone, Copy
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npu3hMABaSrST2ZKKuw:-Npu3hMABaSrST2ZKKux:btbd4t9) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0bb1cc3c7192a2951914b44fe875fe5bda9d465/crates/blockifier/src/transaction/transactions.rs#L138)):*
> ```XML
>             casm_length: contract_class.bytecode_length(),
>             sierra_length: 0,
>             abi_length: 0,
> ```

TODO to fill those values?



_Code quote:_
```XML
            sierra_length: 0,
            abi_length: 0,
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npu3oek5_MEPYR2DeJ4:-Npu3oek5_MEPYR2DeJ5:bwhauqh) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0bb1cc3c7192a2951914b44fe875fe5bda9d465/crates/blockifier/src/transaction/transactions.rs#L179)):*
> ```XML
>     pub fn class_lengths(&self) -> ClassLengths {
>         self.class_lengths
>     }
> ```

Is this needed?



_Code quote:_
```XML
    pub fn class_lengths(&self) -> ClassLengths {
        self.class_lengths
    }
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @elintul)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npu3H4U7Q1gFrHivdij:-NpxKRGJ7xeJnFyDPeZo:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0bb1cc3c7192a2951914b44fe875fe5bda9d465/crates/blockifier/src/execution/contract_class.rs#L58)):*
> ```XML
>     pub fn bytecode_length(&self) -> usize {
>         match self {
>             ContractClass::V0(_) => 0,
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npu3oek5_MEPYR2DeJ4:-NpxLIwc0zcw0FdNJoQc:b-o4i9xr) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0bb1cc3c7192a2951914b44fe875fe5bda9d465/crates/blockifier/src/transaction/transactions.rs#L179)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

field `class_lengths' of `DeclareTransaction` is private.
You can either create a getter function or make the field public.
I followed the pattern used for other fields and created this function.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @ayeletstarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npu3oek5_MEPYR2DeJ4:-NpxrtcRC3ZwayJAViaj:bwwegfm) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0bb1cc3c7192a2951914b44fe875fe5bda9d465/crates/blockifier/src/transaction/transactions.rs#L179)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

field `class_lengths' of `DeclareTransaction` is private.
You can either create a getter function or make the field public.
I followed the pattern used for other fields and created this function.
</blockquote></details>

Let's make it `pub`lic. In another PR: let's make the rest of the fields `pub`lic as well.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-NpxrMA6EsQN8mfN3UFu:-NpxrMA73CcB_c_oT6d0:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/61aba7a898d95bce4620ba44d94d4ae03d82da81/crates/blockifier/src/transaction/transactions.rs#L108)):*
> ```XML
> // TODO(Avi,10/02/2024): use this struct's fields and remove the clippy tag.
> #[allow(dead_code)]
> pub struct ClassLengths {
> ```





_Suggestion:_
```XML
ChargeableClassInfo
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npu3oek5_MEPYR2DeJ4:-Npy-6OO9aDjHUJYo_tF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0bb1cc3c7192a2951914b44fe875fe5bda9d465/crates/blockifier/src/transaction/transactions.rs#L179)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's make it `pub`lic. In another PR: let's make the rest of the fields `pub`lic as well.
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ayeletstarkware, and @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npy1qqo8zUG-y3LyfwU:-Npy1qqo8zUG-y3LyfwV:bwrcdd) ([raw file](https://github.com/starkware-libs/blockifier/blob/61aba7a898d95bce4620ba44d94d4ae03d82da81/crates/blockifier/src/transaction/transactions.rs#L111)):*
> ```XML
>     casm_length: usize,
>     sierra_length: usize,
>     abi_length: usize,
> ```

@ArielElp wants to count bytes.



_Code quote:_
```XML
pub struct ClassLengths {
    casm_length: usize,
    sierra_length: usize,
    abi_length: usize,
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npu3oek5_MEPYR2DeJ4:-Npy2odJ7TXmKyRDmZQl:b-9u6ir6) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0bb1cc3c7192a2951914b44fe875fe5bda9d465/crates/blockifier/src/transaction/transactions.rs#L179)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/blockifier/1441

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @ayeletstarkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npy5ZI40BuMm5oNxCkQ:-Npy5ZI40BuMm5oNxCkR:b-pfezly) ([raw file](https://github.com/starkware-libs/blockifier/blob/32ddbfddbae6b1b7a8f1eba7fcd28c493482d379/crates/blockifier/src/fee/actual_cost.rs#L59)):*
> ```XML
>     #[allow(dead_code)]
>     signature_length: usize,
>     chargeable_class_info: Option<ChargeableClassInfo>,
> ```

Let's keep the variable/function names shorter, so the code doesn't get cumbersome.



_Suggestion:_
```XML
class_info
```

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @avi-starkware, and @ayeletstarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npy1qqo8zUG-y3LyfwU:-NpyFbZL8ishrvyzMwqG:b-wo26z7) ([raw file](https://github.com/starkware-libs/blockifier/blob/61aba7a898d95bce4620ba44d94d4ae03d82da81/crates/blockifier/src/transaction/transactions.rs#L111)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@ArielElp wants to count bytes.
</blockquote></details>

Add a TODO? We'll do it separately.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 123 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-NpyFhMMBG5522FR6PZw:-NpyFhMMBG5522FR6PZx:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2e6198af6084a3166cc650d98341fa487a312253/crates/blockifier/src/transaction/transactions.rs#L123)):*
> ```XML
>     // TODO(Avi,10/02/2024): use this field and remove the clippy tag.
>     #[allow(dead_code)]
>     pub chargeable_class_info: ChargeableClassInfo,
> ```





_Suggestion:_
```XML
class_info
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @avi-starkware, and @ayeletstarkware)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @avi-starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Npy1qqo8zUG-y3LyfwU:-NpyGTK11ye5Qahxxbdy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/61aba7a898d95bce4620ba44d94d4ae03d82da81/crates/blockifier/src/transaction/transactions.rs#L111)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a TODO? We'll do it separately.
</blockquote></details>

Done.

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-:-NpyHElJ-cJbwuvlxHoL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @avi-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-:-NpzuQwP0FYKeJFNb0qE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @ayeletstarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 110 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Nq2TSDv4venB1C5OVuE:-Nq2TSDv4venB1C5OVuF:b-59sf3w) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce777df0c74f8813a5b579fdd29e2c7bad686659/crates/blockifier/src/transaction/transactions.rs#L110)):*
> ```XML
>     sierra_program_length: usize,
>     abi_length: usize,
> }
> ```

Why not in `native_blockifier`?



_Code quote:_
```XML
// TODO(Ayelet,10/02/2024): use this struct's fields and remove the clippy tag.
#[allow(dead_code)]
pub struct PyClassInfo {
    raw_contract_class: String,
    sierra_program_length: usize,
    abi_length: usize,
}
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @ayeletstarkware)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @ayeletstarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 106 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Nq2mFUxAK-9QAwFg-9e:-Nq2mFUxAK-9QAwFg-9f:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce777df0c74f8813a5b579fdd29e2c7bad686659/crates/blockifier/src/transaction/transactions.rs#L106)):*
> ```XML
> // TODO(Ayelet,10/02/2024): use this struct's fields and remove the clippy tag.
> #[allow(dead_code)]
> pub struct PyClassInfo {
> ```

.



_Suggestion:_
```XML
#[derive(FromPyObject)]
pub struct PyClassInfo {
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 106 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Nq2mFUxAK-9QAwFg-9e:-Nq34dog3D0Na42ExPZw:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce777df0c74f8813a5b579fdd29e2c7bad686659/crates/blockifier/src/transaction/transactions.rs#L106)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 110 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Nq2TSDv4venB1C5OVuE:-Nq2wrSV75nrKiTc5G-I:b-vcdui) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce777df0c74f8813a5b579fdd29e2c7bad686659/crates/blockifier/src/transaction/transactions.rs#L110)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not in `native_blockifier`?
</blockquote></details>

Moved to `py_transaction.rs`

**Review by noaov1 — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @ayeletstarkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 141 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Nq37fRx2Gkqvcj6u35j:-Nq37fRy2cZUnBPdlsGU:b469dg3) ([raw file](https://github.com/starkware-libs/blockifier/blob/d22703a3b51372ab4e42cad0a020f9ab4e6217eb/crates/native_blockifier/src/py_transaction.rs#L141)):*
> ```XML
> // TODO(Ayelet,10/02/2024): Use this struct's fields and remove the clippy tag.
> #[allow(dead_code)]
> #[derive(Clone, FromPyObject)]
> ```

You can do it in the next PR.



_Suggestion:_
```XML
#[derive(FromPyObject)]
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1434)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 141 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1434#-Nq37fRx2Gkqvcj6u35j:-Nq380BqAevTs5pb8XPe:b32w1t) ([raw file](https://github.com/starkware-libs/blockifier/blob/d22703a3b51372ab4e42cad0a020f9ab4e6217eb/crates/native_blockifier/src/py_transaction.rs#L141)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You can do it in the next PR.
</blockquote></details>

Ok

**Pull request merged**
