### PR TITLE
refactor: make transactiontreceipt  substruct of transactionexecutioninfo

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1972)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1972)* status: all files reviewed, 7 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 489 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwT3gp7Yf031kQA0sB:-NzwT3gp7Yf031kQA0sC:b245nfm) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/execution_flavors_test.rs#L489)):*
> ```XML
>         if charge_fee { limited_gas_used } else { unlimited_gas_used },
>         if charge_fee { fee_bound } else { unlimited_fee },
>         // Complete resources used are reported as.transaction_receipt.resources; but only the
> ```

find-replace error :)



_Suggestion:_
```XML
as transaction_receipt.resources; but only the
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 528 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwT8-i11b6MaMdyvcK:-NzwT8-i11b6MaMdyvcL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/execution_flavors_test.rs#L528)):*
> ```XML
>     .unwrap();
>     assert!(tx_execution_info.revert_error.clone().unwrap().contains("no remaining steps"));
>     // Complete resources used are reported as.transaction_receipt.resources; but only the charged
> ```





_Suggestion:_
```XML
as transaction_receipt.re
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwTFcy5kn8v5MeN5SQ:-NzwTFcy5kn8v5MeN5SR:b-yh64u6) ([raw file](https://github.com/starkware-libs/blockifier/blob/8fdc21965d3a7a956d58de6b98b070f9698a3476/crates/blockifier/src/transaction/objects.rs#L216)):*
> ```XML
>     // TODO(Dori, 1/8/2023): If the `Eq` and `PartialEq` traits are removed, or implemented on all
>     //   internal structs in this enum, this field should be `Option<TransactionExecutionError>`.
>     pub revert_error: Option<String>,
> ```

do these old comments appear with similar wording on the TransactionReceipt struct?



_Code quote:_
```XML
    /// The actual fee that was charged (in Wei).
    pub actual_fee: Fee,
    /// Actual gas consumption the transaction is charged for data availability.
    pub da_gas: GasVector,
    /// Actual execution resources the transaction is charged for,
    /// including L1 gas and additional OS resources estimation.
    pub actual_resources: TransactionResources,
    /// Error string for reverted transactions; [None] if transaction execution was successful.
    // TODO(Dori, 1/8/2023): If the `Eq` and `PartialEq` traits are removed, or implemented on all
    //   internal structs in this enum, this field should be `Option<TransactionExecutionError>`.
    pub revert_error: Option<String>,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 349 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwTQSG6qcIbtk6BH1E:-NzwTQSG6qcIbtk6BH1F:bnjjrho) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/transactions_test.rs#L349)):*
> ```XML
>     #[values(false, true)] use_kzg_da: bool,
> ) {
>     use crate::fee::actual_cost::TransactionReceipt;
> ```

why is this `use` here and not at the top of the module?



_Code quote:_
```XML
 use crate::fee::actual_cost::TransactionReceipt;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwTUmy43qBlDDTCMtG:-NzwTUmy43qBlDDTCMtH:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/transactions_test.rs#L1100)):*
> ```XML
>     #[values(false, true)] use_kzg_da: bool,
> ) {
>     use crate::fee::actual_cost::TransactionReceipt;
> ```

ditto



_Code quote:_
```XML
use crate::fee::actual_cost::TransactionReceipt;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwTX4p9vmTTVkCnOzL:-NzwTX4p9vmTTVkCnOzM:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/transactions_test.rs#L1228)):*
> ```XML
>     #[values(false, true)] use_kzg_da: bool,
> ) {
>     use crate::fee::actual_cost::TransactionReceipt;
> ```

ditto



_Code quote:_
```XML
 use crate::fee::actual_cost::TransactionReceipt;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1733 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwTZgI-Hewvy2DzpCT:-NzwTZgI-Hewvy2DzpCU:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/transactions_test.rs#L1733)):*
> ```XML
> #[rstest]
> fn test_l1_handler(#[values(false, true)] use_kzg_da: bool) {
>     use crate::fee::actual_cost::TransactionReceipt;
> ```

ditto

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1972)* status: all files reviewed, 7 unresolved discussions (waiting on @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1972)* status: 10 of 13 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 489 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwT3gp7Yf031kQA0sB:-NzwWwU06K75f9tll5wH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/execution_flavors_test.rs#L489)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

find-replace error :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 528 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwT8-i11b6MaMdyvcK:-NzwX-Oc2Ha2yCnfhO9Q:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/execution_flavors_test.rs#L528)):*
> ```XML
>     .unwrap();
>     assert!(tx_execution_info.revert_error.clone().unwrap().contains("no remaining steps"));
>     // Complete resources used are reported as.transaction_receipt.resources; but only the charged
> ```

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwTFcy5kn8v5MeN5SQ:-NzwVjr6EPggxM_psQkj:b-woqw6w) ([raw file](https://github.com/starkware-libs/blockifier/blob/8fdc21965d3a7a956d58de6b98b070f9698a3476/crates/blockifier/src/transaction/objects.rs#L216)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do these old comments appear with similar wording on the TransactionReceipt struct?
</blockquote></details>

No. I'll elaborate more 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 349 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwTQSG6qcIbtk6BH1E:-NzwWZYwCgOUSrNlEzcS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/transactions_test.rs#L349)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this `use` here and not at the top of the module?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwTUmy43qBlDDTCMtG:-NzwW_6d0IzsrvC743Kp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/transactions_test.rs#L1100)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwTX4p9vmTTVkCnOzL:-NzwW_lE2Kj7LeTCsu93:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/transactions_test.rs#L1228)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1733 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzwTZgI-Hewvy2DzpCT:-NzwWa906Fj1oAhBtv3Q:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce63a29685443eb42e1f3550958503955327623f/crates/blockifier/src/transaction/transactions_test.rs#L1733)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by AvivYossef-starkware — COMMENTED** [review]
python https://github.com/starkware-industries/starkware/pull/35185

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-:-NzwZyX_7wyY610aTHBP:b2c6sdo)* status: 10 of 13 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1972)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 209 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzxNUf193T-oV-R-Tws:-NzxNUf193T-oV-R-Twt:b-qo1jqw) ([raw file](https://github.com/starkware-libs/blockifier/blob/abd9d6927375d44fdc58a43489b942f365f21f19/crates/blockifier/src/transaction/objects.rs#L209)):*
> ```XML
>     pub revert_error: Option<String>,
>     /// The receipt of the transaction.
>     /// Including the actual fee that was charged (in Wei),
> ```

this was a mistake before, sorry... please fix (this could be in `Fri` units)



_Suggestion:_
```XML
/// Including the actual fee that was charged (in units of the relevant fee token),
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 210 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzxNfoO5vASmDKXegn9:-NzxNfoO5vASmDKXegnA:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/abd9d6927375d44fdc58a43489b942f365f21f19/crates/blockifier/src/transaction/objects.rs#L210)):*
> ```XML
>     /// The receipt of the transaction.
>     /// Including the actual fee that was charged (in Wei),
>     /// actual gas consumption the transaction is charged for data availability.
> ```





_Suggestion:_
```XML
lity,
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1972)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 209 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzxNUf193T-oV-R-Tws:-NzxPFlEDj0GvuKldaFm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/abd9d6927375d44fdc58a43489b942f365f21f19/crates/blockifier/src/transaction/objects.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this was a mistake before, sorry... please fix (this could be in `Fri` units)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 210 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-NzxNfoO5vASmDKXegn9:-NzxOm_D6JVkJ2Lg857e:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/abd9d6927375d44fdc58a43489b942f365f21f19/crates/blockifier/src/transaction/objects.rs#L210)):*
> ```XML
>     /// The receipt of the transaction.
>     /// Including the actual fee that was charged (in Wei),
>     /// actual gas consumption the transaction is charged for data availability.
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1972#-:-NzxUWzqBFNDniYNCdpz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
