### PR TITLE
Add invalid scenario to constructor test.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1251)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
TODO: Add a test for `get_block_hash` (See: #1243).

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1251)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1464 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1251#-Nm_k7RZ7msRsHqd3WhM:-Nm_k7RZ7msRsHqd3WhN:b-w11q4l) ([raw file](https://github.com/starkware-libs/blockifier/blob/37443df839947b211f3cde77f642079f4cd8d821/crates/blockifier/src/transaction/transactions_test.rs#L1464)):*
> ```XML
>         error,
>         ContractConstructorExecutionFailed,
>     );
> ```

Why twice? :)



_Code quote:_
```XML
    // Logic failure.
    let account_tx = create_account_tx_for_validate_test(
        &mut NonceManager::default(),
        FaultyAccountTxCreatorArgs {
            scenario: INVALID,
            contract_address_salt: salt_manager.next_salt(),
            ..default_args
        },
    );
    let error = account_tx.execute(state, block_context, true, true).unwrap_err();
    check_transaction_execution_error_for_invalid_scenario!(
        cairo_version,
        error,
        ContractConstructorExecutionFailed,
    );

    // Logic failure.
    let account_tx = create_account_tx_for_validate_test(
        &mut NonceManager::default(),
        FaultyAccountTxCreatorArgs {
            scenario: INVALID,
            contract_address_salt: salt_manager.next_salt(),
            ..default_args
        },
    );
    let error = account_tx.execute(state, block_context, true, true).unwrap_err();
    check_transaction_execution_error_for_invalid_scenario!(
        cairo_version,
        error,
        ContractConstructorExecutionFailed,
    );
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1251)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1464 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1251#-Nm_k7RZ7msRsHqd3WhM:-Nm_n6rFCRSWw4sJuAfe:b-w1izdc) ([raw file](https://github.com/starkware-libs/blockifier/blob/37443df839947b211f3cde77f642079f4cd8d821/crates/blockifier/src/transaction/transactions_test.rs#L1464)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why twice? :)
</blockquote></details>

Done.
(Cause I don't know how to solve merge conflicts.)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1251)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1434 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1251#-Nm_sHPa3Pxake6pux9l:-Nm_sHPa3Pxake6pux9m:btkmzy9) ([raw file](https://github.com/starkware-libs/blockifier/blob/26eb41d63bcb71f54863b4fb5e2b403f008a05a8/crates/blockifier/src/transaction/transactions_test.rs#L1434)):*
> ```XML
>     };
> 
>     // Logic failure.
> ```

Out of curiosity: Did we test it before? Why is it interesting?



_Code quote:_
```XML
    // Logic failure.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1251)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1434 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1251#-Nm_sHPa3Pxake6pux9l:-Nm_vlku34Z3IxBPIzyv:bftszx7) ([raw file](https://github.com/starkware-libs/blockifier/blob/26eb41d63bcb71f54863b4fb5e2b403f008a05a8/crates/blockifier/src/transaction/transactions_test.rs#L1434)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Out of curiosity: Did we test it before? Why is it interesting?
</blockquote></details>

We did not test it before.

This is the case for the function: `fn constructor` 
This case is as interesting as the same case for the functions: `fn __validate_declare__`, `fn __validate_deploy__` (for deploy_account), and `fn __validate__` (For invoke function).

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1251)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1434 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1251#-Nm_sHPa3Pxake6pux9l:-NmeE7gi0_4OGdDSiRlQ:bw7d6b2) ([raw file](https://github.com/starkware-libs/blockifier/blob/26eb41d63bcb71f54863b4fb5e2b403f008a05a8/crates/blockifier/src/transaction/transactions_test.rs#L1434)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We did not test it before.

This is the case for the function: `fn constructor` 
This case is as interesting as the same case for the functions: `fn __validate_declare__`, `fn __validate_deploy__` (for deploy_account), and `fn __validate__` (For invoke function).
</blockquote></details>

As discussed - Adding this scenario adds some coverage to the test.

We discussed the downsides of adding redundant tests f2f: Readability and Maintainability might be hurt - addressing some of it in this PR: #1292.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1434 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1251#-Nm_sHPa3Pxake6pux9l:-NmedGgXB_s4nD2acxno:b37v9mi) ([raw file](https://github.com/starkware-libs/blockifier/blob/26eb41d63bcb71f54863b4fb5e2b403f008a05a8/crates/blockifier/src/transaction/transactions_test.rs#L1434)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

As discussed - Adding this scenario adds some coverage to the test.

We discussed the downsides of adding redundant tests f2f: Readability and Maintainability might be hurt - addressing some of it in this PR: #1292.
</blockquote></details>

The downside is addressed by merging this test back into `test_validate_accounts_tx`.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1251)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @MohammadNassar1)

**Review by noaov1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1251)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
