### PR TITLE
Add calculate_tx_fee.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: all files reviewed, 8 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq0G_X67ecV7Qcgin2:-NSq21vb5LQ9u3pghmZA:b-traerr) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I called it `vm_resources`; consider renaming, so it's not confusing (can be done in another PR).
</blockquote></details>

Also in documentation; I'd consider using `Cairo VM` instead of `Cairo` when it comes to resources.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: all files reviewed, 8 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq0G_X67ecV7Qcgin2:-NSq2O2dESp8JUUJiyv4:b-8g7ivw) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Also in documentation; I'd consider using `Cairo VM` instead of `Cairo` when it comes to resources.
</blockquote></details>

Let's decide together on a convention: `[Cairo ]VM` and `resources/usage`.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq1ZXD-1sZv2x3Bnxc:-NStVk4h6o8dFT6gWlBF:bqq75gh) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L65)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is the L1 gas usage in the map to begin with?
</blockquote></details>

I guess it's because we need it when we calculate the transaction fee. `calculate_tx_resources` can return it separately. WDYT? 
Another question is whether we want it to appear as a resource in the `TransactionExecutionInfo`.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSpwW9JEYmrH7UXTpo1:-NStYKDK2aG5Lf1oGKEk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L92)):*
> ```XML
> }
> 
> /// Calculates the fee of a transaction given its execution resources.
> ```

Done.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq0V3DBV8nkzdHtmuq:-NStYL3E78QaS4J6EQiy:bxopmw7) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Doesn't that appear in the block context?
</blockquote></details>

It does. I don't know why I thought it is needed to be passed separately.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq06LT00mS_SV7QAfa:-NStZKrh0vPAXruzRYV0:b-7de6og) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps change the return type of the first argument, they you won't need `u128::try_from().expect()`.
</blockquote></details>

I will need to convert it in `extract_l1_gas_and_cairo_usage`, do you think it's better?
If we return the `l1_gas_usage` separately then we can calculate it as `u128` to begin with (and move the conversions to `calculate_tx_gas_usage`)
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq0G_X67ecV7Qcgin2:-NSt_-XkCFRh53FAFBvV:b-901ovu) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's decide together on a convention: `[Cairo ]VM` and `resources/usage`.
</blockquote></details>

Okay. Will do in another PR.
___
*[`crates/blockifier/src/fee/os_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSpvR7gEAiAQlUo-uMi:-NStbAASDg1yvtAjqQfU:b-f8ywtp) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/os_usage.rs#L31)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please move this to be a docstring.
</blockquote></details>

In that case- don't we need to add also `execute_transactions_inner()`?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq06LT00mS_SV7QAfa:-NStbrdI0uOrOi12wxs9:b-meoig7) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L100)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I will need to convert it in `extract_l1_gas_and_cairo_usage`, do you think it's better?
If we return the `l1_gas_usage` separately then we can calculate it as `u128` to begin with (and move the conversions to `calculate_tx_gas_usage`)
</blockquote></details>

I think we can change all the `usize`s to `u64`; WDYT?
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NStbn5j1t3bKpUkZYQm:-NStbn5j1t3bKpUkZYQn:bhjws3z) ([raw file](https://github.com/starkware-libs/blockifier/blob/e68c52c5fd9688b696dfb3176cccc2e646a80420/crates/blockifier/src/fee/fee_utils.rs#L105)):*
> ```XML
>         .expect("`l1_gas_usage` should be at most 128 bit number.")
>         + l1_gas_by_cairo_usage;
>     let gas_price = block_context.gas_price;
> ```

Why is this variable needed?



_Code quote:_
```XML
let gas_price = block_context.gas_price;
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSpvR7gEAiAQlUo-uMi:-NStbhbzEs1lXIA8vwkk:ba9v9wt) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/os_usage.rs#L31)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In that case- don't we need to add also `execute_transactions_inner()`?
</blockquote></details>

WDYM by add?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq1ZXD-1sZv2x3Bnxc:-NStdFqU3wJbNu93-fUi:b-iidtd5) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L65)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Re the last Q: I think the Bouncer currently uses it, so we need to.

Re the first sentence: can you explain the resource flow to me in a simple way? After executing a transaction we have `vm_resources`, `syscall_counter` (anything else?); then, what is done with them in terms of the resources map?
</blockquote></details>

1. So should we leave the `l1_gas_usage` inside the `ResourcesMapping` or should we add it before creating the `TransactionExecutionInfo`?
2. Execute transaction:
-> update the `resources_manager` (`vm_resources` + `syscall_counter`) -> used to fill the `ResourcesMapping` of the actual resources: 
The `syscall_counter` is used to create a `(Vm)ExecutionResources` which is combined with the `vm_resources` and both are inserted into the ResourcesMapping`.

-> update state ( from which we deduce the `n_modified_contracts`, `n_storage_changes` and `n_class_updates`) -> used to calculate `l1_gas_usage` (which is added to the `ResourcesMapping` of the actual resources).


We use the actual resources in `calculate_tx_fee`.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq06LT00mS_SV7QAfa:-NStcHCaC4an3h2OEhXV:bd7481w) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we can change all the `usize`s to `u64`; WDYT?
</blockquote></details>

The fee should be `u128` (64 bits is not big enough). But other than that we can change everything else to `u64` (I have a task to do this on Monday).
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NStbn5j1t3bKpUkZYQm:-NSthEVf1iM6t695UzLt:bvhnz81) ([raw file](https://github.com/starkware-libs/blockifier/blob/e68c52c5fd9688b696dfb3176cccc2e646a80420/crates/blockifier/src/fee/fee_utils.rs#L105)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this variable needed?
</blockquote></details>

It's not. I will remove it
___
*[`crates/blockifier/src/fee/os_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSpvR7gEAiAQlUo-uMi:-NSthMSkAlaWKyVZ8LSw:bckklkq) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/os_usage.rs#L31)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM by add?
</blockquote></details>

Mention it as well in the doc string?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq1ZXD-1sZv2x3Bnxc:-NSttaC92aK0CBzwwRpa:b-kl0bmo) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L65)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

1. So should we leave the `l1_gas_usage` inside the `ResourcesMapping` or should we add it before creating the `TransactionExecutionInfo`?
2. Execute transaction:
-> update the `resources_manager` (`vm_resources` + `syscall_counter`) -> used to fill the `ResourcesMapping` of the actual resources: 
The `syscall_counter` is used to create a `(Vm)ExecutionResources` which is combined with the `vm_resources` and both are inserted into the ResourcesMapping`.

-> update state ( from which we deduce the `n_modified_contracts`, `n_storage_changes` and `n_class_updates`) -> used to calculate `l1_gas_usage` (which is added to the `ResourcesMapping` of the actual resources).


We use the actual resources in `calculate_tx_fee`.
</blockquote></details>

Then IIUC, the L1 gas usage can be added only right before we return the `TransactionExecutionInfo`, right?
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq06LT00mS_SV7QAfa:-NStthi37cWmDXi_xewY:b3jqpb1) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L100)):*
> 64 bits is not big enough
Really? Do you have an example of a (sane) number that is bigger than 64 bits?
___
*[`crates/blockifier/src/fee/os_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSpvR7gEAiAQlUo-uMi:-NSttwnuE7QVG7-qeQAO:b-7tqq2x) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/os_usage.rs#L31)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Mention it as well in the doc string?
</blockquote></details>

Depends on what `get_additional_os_resources` represents. Where exactly is the extra OS resources come from?



_Code quote:_
```XML
get_additional_os_resources
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq1ZXD-1sZv2x3Bnxc:-NSu122uEdfUCJju1Y8z:biw8y1v) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L65)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Then IIUC, the L1 gas usage can be added only right before we return the `TransactionExecutionInfo`, right?
</blockquote></details>

Right. Done.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSq06LT00mS_SV7QAfa:-NSuBMN6EIYHydd1dQr_:b2re78o) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/fee_utils.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

> 64 bits is not big enough
Really? Do you have an example of a (sane) number that is bigger than 64 bits?
</blockquote></details>

Approximately 16 ETH (the fee is in wei).
___
*[`crates/blockifier/src/fee/os_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSpvR7gEAiAQlUo-uMi:-NSuj0tR9NiAxbewaJT-:b-jzeh3v) ([raw file](https://github.com/starkware-libs/blockifier/blob/517e998194c42161b4571faad95ae572a54255d1/crates/blockifier/src/fee/os_usage.rs#L31)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Depends on what `get_additional_os_resources` represents. Where exactly is the extra OS resources come from?
</blockquote></details>

IIUC it's from running `execute_transactions_inner` + the fee transfer resources.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 346 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSusNYcER2TgilDXWbY:-NSvd0rp6yi2o57FQtib:b-ue09o0) ([raw file](https://github.com/starkware-libs/blockifier/blob/da414bc6af36ac0fb1ce71d47c710778a54e5f2f/crates/blockifier/src/transaction/account_transaction.rs#L346)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Meaning, getting it back to how it was? And having to remove it in `calculate_tx_fee`?
</blockquote></details>

Something isn't clear to me, where are you passing `actual_resources` to `charge_fee`?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 346 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NSusNYcER2TgilDXWbY:-NT5OoJK--4vDWUkuePh:b-cjv3g0) ([raw file](https://github.com/starkware-libs/blockifier/blob/da414bc6af36ac0fb1ce71d47c710778a54e5f2f/crates/blockifier/src/transaction/account_transaction.rs#L346)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm not. I haven't change the fee flow yet (adding this change affects the tests and I wanted to do it in a separate PR).
</blockquote></details>

[#412](https://reviewable.io/reviews/starkware-libs/blockifier/412)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NT7szeN-J7qCe6nOipH:-NT7szeO3PIcsC4_-Hsy:b-u25fzi) (no related file):*
Restore the implementation, so it's equivalent to the Python one?
We'll try to simplify later (maybe we won't be able to...).

___

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @alonh5 and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/399#-NT7szeN-J7qCe6nOipH:-NT842nK13TJpf4wUJ5T:bb6un1j) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Restore the implementation, so it's equivalent to the Python one?
We'll try to simplify later (maybe we won't be able to...).
</blockquote></details>

Done

___

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/399#-:-NT8XyNX0TPcbCulfSPD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
