### PR TITLE
test(concurrency): test update sequencer balance in storage

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NxwFgwgCV9g2BPaW4Yl:-NxwFgwgCV9g2BPaW4Ym:b-pouilk) ([raw file](https://github.com/starkware-libs/blockifier/blob/a71a83fe8ac891d1bde9cf5f13a71c02617c944e/crates/blockifier/src/concurrency/worker_logic_test.rs#L22)):*
> ```XML
> 
> #[rstest]
> #[case::no_overflow_zero_sequencer_value_high(Fee(50_u128), felt_to_stark_felt(&Felt252::from(100_u128)), StarkFelt::ZERO)]
> ```

Why does it matter if `sequencer_value_high` is zero or not?

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NxwGTtG8HYuxYmOALyX:-NxwGTtG8HYuxYmOALyY:b-sxtqlw) ([raw file](https://github.com/starkware-libs/blockifier/blob/a71a83fe8ac891d1bde9cf5f13a71c02617c944e/crates/blockifier/src/concurrency/worker_logic_test.rs#L78)):*
> ```XML
>             .unwrap(),
>         felt_to_stark_felt(&(stark_felt_to_felt(sequencer_value_low)+ Felt252::from(actual_fee.0)))
>     );
> ```

I think it is better to calculate the values first and then compare them. This makes it easier to understand what is being compared.



_Suggestion:_
```XML
    let new_value_low = next_tx_versioned_state
                .get_storage_at(fee_token_address, sequencer_balance_key_low)
                .unwrap()
    let new_value_high = next_tx_versioned_state
                .get_storage_at(fee_token_address, sequencer_balance_key_high)
                .unwrap()
    let expected_value_low = stark_felt_to_felt(sequencer_value_low)+ Felt252::from(actual_fee.0))
    let overflow = sequencer_value_low > felt_to_stark_felt(&(Felt252::max_value() - Felt252::from(actual_fee.0)))
    let expected_value_high = if overflow {stark_felt_to_felt(sequencer_value_low) + 1} else {stark_felt_to_felt(sequencer_value_low)}
    
    assert_eq!(new_value_low, felt_to_stark_felt(&expected_value_low))
    assert_eq!(new_value_high, felt_to_stark_felt(&expected_value_high))
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NxwcWc_BMRzXRp6Wi6z:-NxwcWc_BMRzXRp6Wi7-:b-i7aihn) ([raw file](https://github.com/starkware-libs/blockifier/blob/a71a83fe8ac891d1bde9cf5f13a71c02617c944e/crates/blockifier/src/concurrency/worker_logic_test.rs#L31)):*
> ```XML
>     #[case] sequencer_value_high: StarkFelt,
> ) {
>     const TEST_CONTRACT_ADDRESS: &str = "0x1";
> ```

Avoid using `0x1` as the contract address. As far as I know, this address is reserved for the `block_hash`.



_Code quote:_
```XML
const TEST_CONTRACT_ADDRESS: &str = "0x1";
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NxwFgwgCV9g2BPaW4Yl:-NxwinHK3KtbXZV-VdHQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a71a83fe8ac891d1bde9cf5f13a71c02617c944e/crates/blockifier/src/concurrency/worker_logic_test.rs#L22)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why does it matter if `sequencer_value_high` is zero or not?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NxwcWc_BMRzXRp6Wi6z:-NxwioQbBUhcr5refxmj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a71a83fe8ac891d1bde9cf5f13a71c02617c944e/crates/blockifier/src/concurrency/worker_logic_test.rs#L31)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Avoid using `0x1` as the contract address. As far as I know, this address is reserved for the `block_hash`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NxwGTtG8HYuxYmOALyX:-Nxwip9h9cxQ4p0GjyMe:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a71a83fe8ac891d1bde9cf5f13a71c02617c944e/crates/blockifier/src/concurrency/worker_logic_test.rs#L78)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think it is better to calculate the values first and then compare them. This makes it easier to understand what is being compared.
</blockquote></details>

Done.

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-Ny-cJ6_3rpEgG1E_rR-:-Ny-cJ6_3rpEgG1E_rR0:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5502e18d85476c4c78eba88905c4b0381738bae3/crates/blockifier/src/concurrency/worker_logic_test.rs#L24)):*
> ```XML
>     #[case] actual_fee: Fee,
>     #[case] sequencer_value_low: StarkFelt,
>     #[case] sequencer_value_high: StarkFelt,
> ```





_Suggestion:_
```XML
    #[case] sequencer_balance_low: StarkFelt,
    #[case] sequencer_balance_high: StarkFelt,
```

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-:-Ny0VzDHDavqu6_s6Fc0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by avi-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 184 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-Ny0UyyY8hS5mroLODnr:-Ny1FpiH-HPNQspgTh_N:b-84vyxn) ([raw file](https://github.com/starkware-libs/blockifier/blob/3b222c1ff116e363d9eb47a4a46cb951e19e93c5/crates/blockifier/src/concurrency/worker_logic.rs#L184)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Makes the comment clearer, and removes a nesting of `if`s
</blockquote></details>

Like!
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 33 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-Ny1PTPq3-dbWgFdIE98:-Ny1PTPq3-dbWgFdIE99:b-azi55v) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f950b2c87d90a0cb41f05d3616cb85b246e1023/crates/blockifier/src/concurrency/worker_logic_test.rs#L33)):*
> ```XML
>         &[(account, 1)],
>     ));
>     let tx_versioned_state = safe_versioned_state.pin_version(0);
> ```

Please define `tx_index`. Use it here and below (in `next_tx_versioned_state`).



_Suggestion:_
```XML
    let tx_versioned_state = safe_versioned_state.pin_version(tx_index);
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 64 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-Ny1JJe17zD6zPsNH3MH:-Ny1JJe17zD6zPsNH3MI:b-g419sw) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f950b2c87d90a0cb41f05d3616cb85b246e1023/crates/blockifier/src/concurrency/worker_logic_test.rs#L64)):*
> ```XML
>     } else {
>         stark_felt_to_felt(sequencer_balance_high)
>     };
> ```

It reminds the code in the method. Consider using `BigUint`. E.g.



_Suggestion:_
```XML
    let expected_balance = (stark_felt_to_felt(sequencer_balance_low) + Felt252::from(actual_fee.0)).to_biguint();

    let expected_sequencer_balance_low =
        Felt252::from(&expected_balance);
    let expected_sequencer_balance_high = stark_felt_to_felt(sequencer_balance_high) + &expected_balance / Felt252::max_value().to_biguint()
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 64 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-Ny1JJe17zD6zPsNH3MH:-NyEP6j83QKh7E5HiZvC:bsituyn) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f950b2c87d90a0cb41f05d3616cb85b246e1023/crates/blockifier/src/concurrency/worker_logic_test.rs#L64)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It reminds the code in the method. Consider using `BigUint`. E.g.
</blockquote></details>

Edit:



_Code snippet:_
```XML
let expected_balance = (stark_felt_to_felt(sequencer_balance_low) + Felt252::from(actual_fee.0)).to_biguint();
let p = Felt252::max_value().to_biguint() + 1_u8;
let expected_sequencer_balance_low = Felt252::from(&expected_balance);
let expected_sequencer_balance_high = stark_felt_to_felt(sequencer_balance_high) + &expected_balance / p;
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
Wait

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-:-NyEVE_I5fH8Vc_-8__3:bb76hay)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

**Review by noaov1 — COMMENTED** [review]
Please change the base branch

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-:-Ny_ekKq6kjWH1Wa7w-h:bv8wug3)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`-- commits` line 6 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-Nyei0051qjlaXY7_MdV):*
Please rebase



_Code quote:_
```
- efac69d: fix(concurrency): fix add fee to sequencer balance so it will check u128
  overflow

- 633e66c: test(concurrency): test update sequencer balance in storage
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 197 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NyeeZrQ-tItkp4BvoSA:-NyeeZrQ-tItkp4BvoSB:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/633e66c60cc5e48c624b09e0dc78e651fc7e0c42/crates/blockifier/src/concurrency/worker_logic.rs#L197)):*
> ```XML
>             if tx_context.tx_info.sender_address()
>                 == self.block_context.block_info.sequencer_address
>             {
> ```





_Suggestion:_
```XML
        let tx_context = Arc::new(self.block_context.to_tx_context(tx));
        if let Ok(tx_info) = result_tx_info.as_mut() {
            // TODO(Meshi, 01/06/2024): check if this is also needed in the bouncer.
            // Update the sequencer balance.
            if tx_context.tx_info.sender_address()
                == self.block_context.block_info.sequencer_address
            {
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 200 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NyeefA60Aerdp1-tf3U:-NyeefA60Aerdp1-tf3V:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/633e66c60cc5e48c624b09e0dc78e651fc7e0c42/crates/blockifier/src/concurrency/worker_logic.rs#L200)):*
> ```XML
>                 // When the sequencer is the sender, we use the sequential fee transfer.
>                 // Meaning we don't remove the sequencer balance from the read and writes sets,
>                 // so we have nothing to fix.
> ```





_Suggestion:_
```XML
                // When the sequencer is the sender, we use the sequential (full) fee transfer.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 308 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NyehHm64SIvUuTCMK5-:-NyehHm64SIvUuTCMK50:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/633e66c60cc5e48c624b09e0dc78e651fc7e0c42/crates/blockifier/src/concurrency/worker_logic_test.rs#L308)):*
> ```XML
> #[rstest]
> #[case::no_overflow(Fee(50_u128), felt_to_stark_felt(&Felt252::from(100_u128)), StarkFelt::ZERO)]
> #[case::overflow(Fee(150_u128), stark_felt!(u128::max_value()), StarkFelt::from_u128(5_u128))]
> ```





_Suggestion:_
```XML
#[case::no_overflow(Fee(50_u128), stark_felt!(100_u128), StarkFelt::ZERO)]
#[case::overflow(Fee(150_u128), stark_felt!(u128::max_value()), stark_felt!(5_u128))]
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`-- commits` line 6 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-Nyei0051qjlaXY7_MdV):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 350 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-Ny_wOQZC28rBOTpT5MO:-NynVASVBQgOu9tzitEd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/633e66c60cc5e48c624b09e0dc78e651fc7e0c42/crates/blockifier/src/concurrency/worker_logic_test.rs#L350)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This is a mistake...
For example,
if `expected_balance == u128::max_value()` the division will give you 1, when there shouldn't be an overflow.

You can also add 1 to the denominator instead of my suggestion.
</blockquote></details>

Done.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 348 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-Nyn_hVQ0u5LaWrT8RSi:-Nyn_hVR9LI4juE_lrGu:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee700f73041a7286b2a89758d5b27cf03713ef1f/crates/blockifier/src/concurrency/worker_logic_test.rs#L348)):*
> ```XML
>         (stark_felt_to_felt(sequencer_balance_low) + Felt252::from(actual_fee.0)).to_biguint();
> 
>     let mask = (BigUint::from(1_u8) << 128) - 1_u8;
> ```





_Suggestion:_
```XML
 let mask_128_bit = (BigUint::from(1_u8) << 128) - 1_u8;
```

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 348 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-Nyn_hVQ0u5LaWrT8RSi:-NyuARpB92vb7KqIA7DI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee700f73041a7286b2a89758d5b27cf03713ef1f/crates/blockifier/src/concurrency/worker_logic_test.rs#L348)):*
> ```XML
>         (stark_felt_to_felt(sequencer_balance_low) + Felt252::from(actual_fee.0)).to_biguint();
> 
>     let mask = (BigUint::from(1_u8) << 128) - 1_u8;
> ```

Done.

**Review by avi-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 203 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NyuHuFH-3bYg-KBiIrb:-NyuHuFI9DjP57j7ciMy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/71a94210eddef2aadf433951113e8ffaf25d1038/crates/blockifier/src/concurrency/worker_logic.rs#L203)):*
> ```XML
>         if let Ok(tx_info) = result_tx_info.as_mut() {
>             // TODO(Meshi, 01/06/2024): ask the bouncer if there is enough room for the transaction.
>             if tx_context.tx_info.sender_address()
> ```





_Suggestion:_
```XML
            // TODO(Meshi, 01/06/2024): ask the bouncer if there is enough room for the transaction.
            // Update the sequencer balance (in state + call info).
            if tx_context.tx_info.sender_address()
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 210 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1898#-NyuIDLO5tdFv6sZjjjs:-NyuIDLO5tdFv6sZjjjt:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/71a94210eddef2aadf433951113e8ffaf25d1038/crates/blockifier/src/concurrency/worker_logic.rs#L210)):*
> ```XML
>             }
> 
>             // Update the sequencer balance in the storage.
> ```

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1898)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
