### PR TITLE
feat(native_blockifier): add naive implementation for execute_txs using execute function

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…ng execute function

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1579)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1579)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1579#-NrGSzh6CdJGJ99HAw1q:-NrGSzh6CdJGJ99HAw1r:b-a1zx2g) (no related file):*
Python's PR:
https://reviewable.io/reviews/starkware-industries/starkware/34119

___

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1579)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1579#-NrWUrUl8Rkw41NJio0T:-NrWUrUl8Rkw41NJio0U:bxqjgb1) ([raw file](https://github.com/starkware-libs/blockifier/blob/d28b09915c38d0e9b1a130fb403b75c6112c4219/crates/native_blockifier/src/py_block_executor.rs#L135)):*
> ```XML
>     pub fn execute_txs(
>         &mut self,
>         txs_with_class_infos: Vec<(&PyAny, Option<PyClassInfo>)>,
> ```

Out of scope comment (what you did is great since it is consistent with `execute_tx`):

@elintul 
I think i have an idea on how to create a proper `PyTransaction` struct that can handle ths PyAny tx object and the optional ClassInfo (which i'm assuming is the reason we're haven't defined a `PyTransaction` yet).
We can use an enum with some Pyo3 tricks (i'll explain f2f).
Context: i don't like the tuples here :grimacing:  



_Code quote:_
```XML
(&PyAny, Option<PyClassInfo>)
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1579#-NrWWGK67A9Vk5gQelQJ:-NrWWGK67A9Vk5gQelQK:b-o45xh3) ([raw file](https://github.com/starkware-libs/blockifier/blob/d28b09915c38d0e9b1a130fb403b75c6112c4219/crates/native_blockifier/src/py_block_executor.rs#L147)):*
> ```XML
>                 info: tx_execution_info,
>                 tx_type: tx_type.to_string(),
>             };
> ```

No need to pass through &str, `extract` can create `String`s.



_Suggestion:_
```XML
            let tx_type = tx.getattr("tx_type")?.getattr("name")?.extract()?;
            let tx: Transaction = py_tx(tx, optional_py_class_info)?;
            let (tx_execution_info, bouncer_info) = self.tx_executor().execute(tx, charge_fee)?;
            let typed_tx_execution_info = TypedTransactionExecutionInfo {
                info: tx_execution_info,
                tx_type,
            };
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1579)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1579#-NrWWGK67A9Vk5gQelQJ:-Nr_INjJ7kNrzYrilW8C:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d28b09915c38d0e9b1a130fb403b75c6112c4219/crates/native_blockifier/src/py_block_executor.rs#L147)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

No need to pass through &str, `extract` can create `String`s.
</blockquote></details>

Done.

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1579)* status: all files reviewed, 1 unresolved discussion

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1579)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
