### PR TITLE
Failed cairo1 execution

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/481)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #464** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/464" target="_blank">Graphite</a> 
    * **PR #465** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/465" target="_blank">Graphite</a> 
      * **PR #466** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/466" target="_blank">Graphite</a> 
        * **PR #469** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/469" target="_blank">Graphite</a> 
          * **PR #470** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/470" target="_blank">Graphite</a> 
            * **PR #472** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/472" target="_blank">Graphite</a> 
              * **PR #481** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/481" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/481?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/481)* status: all files reviewed, 11 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYo3Q0ZMXRQ8MuY06:-NVtYo3R5CxQh6s9mtLJ:bfjvxs7) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/cairo1_execution.rs#L77)):*
> ```XML
>     let call_info =
>         finalize_execution(vm, runner, syscall_handler, call, previous_vm_resources, n_total_args)?;
>     if call_info.failed {
> ```

Isn't `match`ing more elegant here?



_Code quote:_
```XML
if call_info.failed
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYiDm-pubVfLx8RGr:-NVtYiDm-pubVfLx8RGs:bfvbs6h) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/cairo1_execution.rs#L78)):*
> ```XML
>         finalize_execution(vm, runner, syscall_handler, call, previous_vm_resources, n_total_args)?;
>     if call_info.failed {
>         return Err(EntryPointExecutionError::ExecutionFailed(call_info.execution.retdata.0));
> ```

Give this a name, please: `error_data`.



_Code quote:_
```XML
call_info.execution.retdata.0
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYuqnCWw16Ed1hZpI:-NVtYuqnCWw16Ed1hZpJ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/cairo1_execution.rs#L245)):*
> ```XML
> 
>     // Get retdata.
>     let [success_tag, retdata_start, retdata_end]: [MaybeRelocatable; 3] =
> ```





_Suggestion:_
```XML
failure_flag
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtXzup5lL68qaE_0Bs:-NVtXzup5lL68qaE_0Bt:b-25w10m) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/entry_point.rs#L178)):*
> ```XML
>     pub vm_resources: VmExecutionResources,
>     pub inner_calls: Vec<CallInfo>,
>     pub failed: bool,
> ```

Move to `execution`, which represents the result of the execution of this call.



_Code quote:_
```XML
pub failed: bool,
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYLAC0apaXT9N-7Vm:-NVtYLAC0apaXT9N-7Vn:b4kq1xg) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/entry_point.rs#L178)):*
> ```XML
>     pub vm_resources: VmExecutionResources,
>     pub inner_calls: Vec<CallInfo>,
>     pub failed: bool,
> ```

If defult is `true`, we should change it to `false`.



_Code quote:_
```XML
pub failed: bool
```
___
*[`crates/blockifier/src/execution/errors.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtXRlM6dFUGIbTqhqs:-NVtXRlM6dFUGIbTqhqt:b-pfqnqe) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/errors.rs#L143)):*
> ```XML
> }
> 
> fn felts_as_str(felts: &[StarkFelt]) -> String {
> ```

Consider moving to `execution_utils.rs`, unless you think this will only be used in a negative flow.



_Code quote:_
```XML
felts_as_str
```
___
*[`crates/blockifier/src/execution/errors.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtXgy54keOn0gGtM2j:-NVtXgy54keOn0gGtM2k:b-m3e3ty) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/errors.rs#L149)):*
> ```XML
>             as_cairo_short_string(&stark_felt_to_felt(*felt)).unwrap_or_else(|| felt.to_string())
>         })
>         .collect::<Vec<_>>()
> ```

Why is this needed without the generic type? Does this help the compiler?



_Code quote:_
```XML
Vec<_>
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 388 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYYMGA74s0Km-I2F4:-NVtYYMGA74s0Km-I2F5:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/syscalls/hint_processor.rs#L388)):*
> ```XML
> ) -> SyscallResult<ReadOnlySegment> {
>     let call_info = call.execute(syscall_handler.state, syscall_handler.context)?;
>     let retdata = &call_info.execution.retdata.0;
> ```





_Suggestion:_
```XML
raw_retdata
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYd0h1T0ScIsbJUYM:-NVtYd0h1T0ScIsbJUYN:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/syscalls/hint_processor.rs#L391)):*
> ```XML
> 
>     if call_info.failed {
>         // TODO(spapini): Append an error word.
> ```

WDYM?



_Code quote:_
```XML
Append an error word.
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 394 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtY_ln31socgQKrKal:-NVtY_ln31socgQKrKam:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/syscalls/hint_processor.rs#L394)):*
> ```XML
>         return Err(SyscallExecutionError::SyscallError { error_data: retdata.clone() });
>     }
>     let retdata: Vec<MaybeRelocatable> =
> ```

Add a blank line above.



_Code quote:_
```XML
let retdata: Vec<MaybeRelocatable> =
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 397 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYTXDCTywloggYDpK:-NVtYTXDCTywloggYDpL:bzwi2i) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/syscalls/hint_processor.rs#L397)):*
> ```XML
>         retdata.iter().map(|&x| MaybeRelocatable::from(stark_felt_to_felt(x))).collect();
>     let retdata_segment_start_ptr = syscall_handler.read_only_segments.allocate(vm, &retdata)?;
>     syscall_handler.inner_calls.push(call_info);
> ```

Restore blank line above.



_Code quote:_
```XML
syscall_handler.inner_calls.push(call_info);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/481)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYo3Q0ZMXRQ8MuY06:-NVxBaD_DitYGWyf0HLY:bjczaya) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/cairo1_execution.rs#L77)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't `match`ing more elegant here?
</blockquote></details>

Match on a bool? I don't think it's better. I also think clippy might yell at me.
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYuqnCWw16Ed1hZpI:-NVxCDku5ZqH-0P4yFnV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/cairo1_execution.rs#L245)):*
> ```XML
> 
>     // Get retdata.
>     let [success_tag, retdata_start, retdata_end]: [MaybeRelocatable; 3] =
> ```

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtXzup5lL68qaE_0Bs:-NVxCbxeDm8C3davRKSO:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/entry_point.rs#L178)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move to `execution`, which represents the result of the execution of this call.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYLAC0apaXT9N-7Vm:-NVxCoYk7e_YEGOzKjPq:b-4agyge) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/entry_point.rs#L178)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

If defult is `true`, we should change it to `false`.
</blockquote></details>

Making sure I understand: you want me to imlpement Default manually for this struct?
___
*[`crates/blockifier/src/execution/errors.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtXgy54keOn0gGtM2j:-NVxDGqK0_QIlRXCZfdt:bl7hngl) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/errors.rs#L149)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this needed without the generic type? Does this help the compiler?
</blockquote></details>

Yes. `collect` Doesn't know that target, it must be inferred from somewhere else. Since I have a .join() afterwards, rthe compiler can't infer it.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/481)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVxFUrR7rD_t-B4M2Yk:-NVxFUrS0WAoDi9NIGZg:b-l9enlm) (no related file):*
@elintul Note that this uncovered an error in `test_get_execution_info()`

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/481)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVxFUrR7rD_t-B4M2Yk:-NVxwEVg7Qhi9-CiK_Jl:b-nyf01y) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

@elintul Note that this uncovered an error in `test_get_execution_info()`
</blockquote></details>

Can you please elaborate? Or you didn't debug?

___
___
*[`crates/blockifier/src/execution/entry_point.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYLAC0apaXT9N-7Vm:-NVxvtkrCuyL7JPTToOZ:btnlnme) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/entry_point.rs#L178)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Making sure I understand: you want me to imlpement Default manually for this struct?
</blockquote></details>

Only for this field, I think i makes sense the default would be that the call was successful, no?
___
*[`crates/blockifier/src/execution/errors.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtXgy54keOn0gGtM2j:-NVxw1zf03oRLq8KSAO_:b-k9p3rb) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/errors.rs#L149)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Yes. `collect` Doesn't know that target, it must be inferred from somewhere else. Since I have a .join() afterwards, rthe compiler can't infer it.
</blockquote></details>

How does the lacking annotation help it infer the type?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/481)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYLAC0apaXT9N-7Vm:-NVy1MyH8WSd0UBpMsk3:b-dvukr4) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/entry_point.rs#L178)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Only for this field, I think i makes sense the default would be that the call was successful, no?
</blockquote></details>

I don't think you can do this in rust. It's all teh type or nothing.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/481)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/errors.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtXgy54keOn0gGtM2j:-NVy1W-o6Czqpq1l7RWN:b-56rm3w) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/errors.rs#L149)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How does the lacking annotation help it infer the type?
</blockquote></details>

Oh, you mean why I used `_`? Because  the compiler doesn't need it, it infers it.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/481)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVxFUrR7rD_t-B4M2Yk:-NVy5JmN61DaVx5Pf-G5:badqvqw) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you please elaborate? Or you didn't debug?
</blockquote></details>

Didn't debug. Just found it it actually fails (This PR uncovers these failures)

___

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/481)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYLAC0apaXT9N-7Vm:-NVy90Bd6vKvJXHBPxZ5:b-azpfqp) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/entry_point.rs#L178)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think you can do this in rust. It's all teh type or nothing.
</blockquote></details>

Oh okay, WDYT of changing to `succeded` then?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/481)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/481#-NVtYLAC0apaXT9N-7Vm:-NVycPHr9Z2QSrK0dmTI:b6mabxs) ([raw file](https://github.com/starkware-libs/blockifier/blob/922fd2bd90bd40c312f653c703432ac6c5663d2b/crates/blockifier/src/execution/entry_point.rs#L178)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Oh okay, WDYT of changing to `succeded` then?
</blockquote></details>

I thought you might suggest that. Do we want to stay compatible with python code? It's called failure_flag there

**Pull request merged**
