### PR TITLE
Abstract fee transfer cost

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1265)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 2 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1265)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/prices.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-NlwrgvG9Yzi9CWi_C55:-NlwrgvG9Yzi9CWi_C56:b-etycfh) ([raw file](https://github.com/starkware-libs/blockifier/blob/346dd881b2954265223a34bae0337635fdcc819d/crates/blockifier/src/test_utils/prices.rs#L39)):*
> ```XML
> 
> /// Returns the expected VM resource consumption for a fee transfer call from the given address.
> #[memoize::memoize]
> ```

Can you please explain what it means?



_Code quote:_
```XML
#[memoize::memoize]
```
___
*[`crates/blockifier/src/test_utils/prices.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-NlwozfrA9dbnckm9g-o:-NlwozfrA9dbnckm9g-p:b-s92o36) ([raw file](https://github.com/starkware-libs/blockifier/blob/346dd881b2954265223a34bae0337635fdcc819d/crates/blockifier/src/test_utils/prices.rs#L54)):*
> ```XML
>     // Execute a fee transfer call and return the VM resources used.
>     let fee_transfer_call = CallEntryPoint {
>         class_hash: Some(token.get_class_hash()),
> ```

Only if you choose to use `execute()`.



_Suggestion:_
```XML
        class_hash: None,
```
___
*[`crates/blockifier/src/test_utils/prices.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-NlwpRGL6NwFZOjxvMbt:-NlwpRGL6NwFZOjxvMbu:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/346dd881b2954265223a34bae0337635fdcc819d/crates/blockifier/src/test_utils/prices.rs#L59)):*
> ```XML
>             *block_context.sequencer_address.0.key(), // Recipient.
>             stark_felt!(7_u8),                        // Amount.
>             stark_felt!(0_u8)
> ```





_Suggestion:_
```XML
            stark_felt!(7_u8),                        // LSB of some amount.
            stark_felt!(0_u8)                        // MSB of some amount.
```
___
*[`crates/blockifier/src/test_utils/prices.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-NlwpdnC-xPv2_1Xh1NU:-NlwpdnC-xPv2_1Xh1NV:b7ll9zo) ([raw file](https://github.com/starkware-libs/blockifier/blob/346dd881b2954265223a34bae0337635fdcc819d/crates/blockifier/src/test_utils/prices.rs#L61)):*
> ```XML
>             stark_felt!(0_u8)
>         ],
>         storage_address: block_context.fee_token_address(&FeeType::Eth),
> ```

Do we want to send the fee type? (currently it's the same contract, so it does not matter, maybe for future compatibility)



_Code quote:_
```XML
        storage_address: block_context.fee_token_address(&FeeType::Eth),
```
___
*[`crates/blockifier/src/test_utils/prices.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-NlwtEwiBk0KQkCHJ8WR:-NlwtEwiBk0KQkCHJ8WS:b-hxf5mb) ([raw file](https://github.com/starkware-libs/blockifier/blob/346dd881b2954265223a34bae0337635fdcc819d/crates/blockifier/src/test_utils/prices.rs#L65)):*
> ```XML
>         ..Default::default()
>     };
>     execute_entry_point_call(
> ```

Consider using `fee_transfer_call.execute(..)`.



_Code quote:_
```XML
 execute_entry_point_call(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1265)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/prices.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-NlwrgvG9Yzi9CWi_C55:-NlxZkFW3V6Wy2rIXWW0:btay6r8) ([raw file](https://github.com/starkware-libs/blockifier/blob/346dd881b2954265223a34bae0337635fdcc819d/crates/blockifier/src/test_utils/prices.rs#L39)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain what it means?
</blockquote></details>

It memoizes the function.
I.e, if this function is called twice with the same input, instead of recomputing the resources, a clone of the previously computed return value is returned.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1265)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/prices.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-Nm1dqqG-WB0G_SSNLi0:-Nm1dqqG-WB0G_SSNLi1:b54wvug) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e6536f506b86a459a0337d281c6296723ce97dc/crates/blockifier/src/test_utils/prices.rs#L42)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing();
>     let state = &mut test_state(block_context, BALANCE, &[(token, 1)]);
>     let token_address = token.get_instance_address(0);
> ```

Why? Isn't it deployed at the address set in the `block_context`?



_Code quote:_
```XML
    let token_address = token.get_instance_address(0);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1265)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/prices.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-Nm1dqqG-WB0G_SSNLi0:-Nm1eXgs01fazD5F8YjR:bs7wumb) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e6536f506b86a459a0337d281c6296723ce97dc/crates/blockifier/src/test_utils/prices.rs#L42)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why? Isn't it deployed at the address set in the `block_context`?
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1265)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/prices.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-Nm1dqqG-WB0G_SSNLi0:-Nm1fW9tEfTB0Hxnjspg:b-rms9fr) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e6536f506b86a459a0337d281c6296723ce97dc/crates/blockifier/src/test_utils/prices.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And, no; feature contracts are deployed at specific addresses; unlike the block context fee token addresses, which are decoupled.

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1265)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/prices.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-NlwpdnC-xPv2_1Xh1NU:-Nm1gN4S3cy35NlALHrs:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/346dd881b2954265223a34bae0337635fdcc819d/crates/blockifier/src/test_utils/prices.rs#L61)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we want to send the fee type? (currently it's the same contract, so it does not matter, maybe for future compatibility)
</blockquote></details>

?
___
*[`crates/blockifier/src/test_utils/prices.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-Nm1dqqG-WB0G_SSNLi0:-Nm1fjiAEu1QODWe4KYD:bd67wxq) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e6536f506b86a459a0337d281c6296723ce97dc/crates/blockifier/src/test_utils/prices.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

And, no; feature contracts are deployed at specific addresses; unlike the block context fee token addresses, which are decoupled.
</blockquote></details>

I see. You deployed it again (not assuming it was already deployed in the `test_state`).
___
*[`crates/blockifier/src/test_utils/prices.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-Nm1ggi91k5nCDoAkYzG:-Nm1ggi91k5nCDoAkYzH:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d3cfb1df3cb6521ac66cf09d69851a6517c6c79/crates/blockifier/src/test_utils/prices.rs#L69)):*
> ```XML
>                 block_context,
>                 &account_invoke_tx(InvokeTxArgs::default()).get_account_tx_context(),
>                 ExecutionMode::Validate,
> ```





_Suggestion:_
```XML
                ExecutionMode::Execute,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1265)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/prices.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-NlwpdnC-xPv2_1Xh1NU:-Nm1sWXW1XVCd5djRq6Y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/346dd881b2954265223a34bae0337635fdcc819d/crates/blockifier/src/test_utils/prices.rs#L61)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/prices.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-Nm1dqqG-WB0G_SSNLi0:-Nm1rrsY2CjkI-88SOUQ:b-1nlaeg) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e6536f506b86a459a0337d281c6296723ce97dc/crates/blockifier/src/test_utils/prices.rs#L42)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see. You deployed it again (not assuming it was already deployed in the `test_state`).
</blockquote></details>

technically no, the `token` I deployed in `test_state` was at a different (third) address.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1265#-:-Nm5UfroDwnUY-1KB1-4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
