### PR TITLE
Add mark_address_range_as_accessed.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/332)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/332)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/332#-NPw7O6J3yY1wN_A96kd:-NPw7O6K1wsuZYOvckAb:b-woolqm) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e66d980f2711f6a01a5b5e251479600de30b95e/crates/blockifier/src/execution/execution_utils.rs#L174)):*
> ```XML
> 
>     runner.run_from_entrypoint(entry_point_pc, &args, verify_secure, vm, hint_processor)?;
> ```

Perhaps this should be done in `finalize_execution`, where the other `mark_as_accessed` is called?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/332)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/332#-NPw7O6J3yY1wN_A96kd:-NPw9qlsCaOkDWuUtf7m:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e66d980f2711f6a01a5b5e251479600de30b95e/crates/blockifier/src/execution/execution_utils.rs#L174)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps this should be done in `finalize_execution`, where the other `mark_as_accessed` is called?
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/332)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/332#-NQK2SHV56-NJmyBCJrm:-NQK2SHV56-NJmyBCJrn:bio47dy) ([raw file](https://github.com/starkware-libs/blockifier/blob/bec0939f3acd91e911c9e5238c592ba0500ef20b/crates/blockifier/src/execution/execution_utils.rs#L182)):*
> ```XML
> pub fn finalize_execution(
>     runner: CairoRunner,
>     mut vm: VirtualMachine,
> ```

Move first; chances are that `mut` arguments to a function won't change.



_Code quote:_
```XML
mut vm: VirtualMachine,
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/332#-NQK2a0A4-VRDKjs8hGk:-NQK2a0A4-VRDKjs8hGl:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bec0939f3acd91e911c9e5238c592ba0500ef20b/crates/blockifier/src/execution/execution_utils.rs#L186)):*
> ```XML
>     syscall_handler: SyscallHintProcessor<'_>,
>     implicit_args: Vec<MaybeRelocatable>,
>     args_length: usize,
> ```





_Suggestion:_
```XML
n_total_args: usize,
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/332#-NQKowH11_3FZBV_gIIO:-NQKowH11_3FZBV_gIIP:b-w3cbp1) ([raw file](https://github.com/starkware-libs/blockifier/blob/bec0939f3acd91e911c9e5238c592ba0500ef20b/crates/blockifier/src/execution/execution_utils.rs#L188)):*
> ```XML
>     args_length: usize,
> ) -> Result<CallInfo, PostExecutionError> {
>     // When execution starts the stack holds entry_point_args + [ret_fp, ret_pc].
> ```

Move comment right above `.sub_usize(args_length + 2)?;`, if possible.
If moved, move the next comment to the start, so it explains all `mark_as_accessed` calls in this function ("The arguments and RO segments are touched...").



_Suggestion:_
```XML
// When execution starts the stack holds the EP arguments + [ret_fp, ret_pc].
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/332#-NQK2SHV56-NJmyBCJrm:-NQKtw4VEnoPTGtP8H7x:bopumrt) ([raw file](https://github.com/starkware-libs/blockifier/blob/bec0939f3acd91e911c9e5238c592ba0500ef20b/crates/blockifier/src/execution/execution_utils.rs#L182)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move first; chances are that `mut` arguments to a function won't change.
</blockquote></details>

Done. WDYM by "won't change"?
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/332#-NQK2a0A4-VRDKjs8hGk:-NQKu8FNAlsRCDarSzjH:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/bec0939f3acd91e911c9e5238c592ba0500ef20b/crates/blockifier/src/execution/execution_utils.rs#L186)):*
> ```XML
>     syscall_handler: SyscallHintProcessor<'_>,
>     implicit_args: Vec<MaybeRelocatable>,
>     args_length: usize,
> ```

Done
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/332#-NQKowH11_3FZBV_gIIO:-NQKubCP8wg-QRRZ1-be:b-fiygza) ([raw file](https://github.com/starkware-libs/blockifier/blob/bec0939f3acd91e911c9e5238c592ba0500ef20b/crates/blockifier/src/execution/execution_utils.rs#L188)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move comment right above `.sub_usize(args_length + 2)?;`, if possible.
If moved, move the next comment to the start, so it explains all `mark_as_accessed` calls in this function ("The arguments and RO segments are touched...").
</blockquote></details>

Done. The RO segments are the [ret_fp, ret_pc]?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/332#-:-NQLBh1u0DDtSFxg9m7_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/332#-NQK2SHV56-NJmyBCJrm:-NQLAuBkBaaPtYZqVVj8:bz6rbi3) ([raw file](https://github.com/starkware-libs/blockifier/blob/bec0939f3acd91e911c9e5238c592ba0500ef20b/crates/blockifier/src/execution/execution_utils.rs#L182)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done. WDYM by "won't change"?
</blockquote></details>

Won't be deleted as an argument to the function, since if they're `mut`able, they are changing inside the function and probably essential to it. 
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/332#-NQKowH11_3FZBV_gIIO:-NQLBdMY3sH6YC7Ouscd:b-1pndkl) ([raw file](https://github.com/starkware-libs/blockifier/blob/bec0939f3acd91e911c9e5238c592ba0500ef20b/crates/blockifier/src/execution/execution_utils.rs#L188)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done. The RO segments are the [ret_fp, ret_pc]?
</blockquote></details>

The read-only segments we are marking as accessed later.

**Pull request merged**
