### PR TITLE
Add code address to entry point.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/417)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/417)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTIkw0GEhpiKI-gEcNj:-NTIkw0GEhpiKI-gEcNk:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac582ba1d784892ceea931d3daefeb4eb61e42d9/crates/blockifier/src/test_utils.rs#L156)):*
> ```XML
>         storage_address: contract_address,
>         caller_address: ContractAddress::default(),
>         code_address: None,
> ```





_Suggestion:_
```XML
code_address: Some(contract_address),
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTIjoUhA5_wdueiYYJq:-NTIjoUhA5_wdueiYYJr:b-sxyt5v) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac582ba1d784892ceea931d3daefeb4eb61e42d9/crates/blockifier/src/execution/entry_point.rs#L44)):*
> ```XML
>     pub storage_address: ContractAddress,
>     pub caller_address: ContractAddress,
>     // There is no code address in a library call.
> ```

Add a backward compatibility comment, like we have in Python.



_Suggestion:_
```XML
// Optional, since there is no address to the code implementation in a library call.
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 458 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTIn9cg3GANWsy5xfzt:-NTIn9cg3GANWsy5xfzu:bg2mjm5) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac582ba1d784892ceea931d3daefeb4eb61e42d9/crates/blockifier/src/execution/execution_utils.rs#L458)):*
> ```XML
>     entry_point_selector: EntryPointSelector,
>     calldata: Calldata,
>     code_address: Option<ContractAddress>,
> ```

Pass after `class_hash`, in all changed functions (those two arguments are tightly coupled).



_Code quote:_
```XML
code_address: Option<ContractAddress>,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTIkPWz4brYgNZwb0ih:-NTIkPWz4brYgNZwb0ii:b-s0aeva) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac582ba1d784892ceea931d3daefeb4eb61e42d9/crates/blockifier/src/transaction/account_transaction.rs#L169)):*
> ```XML
>             calldata: self.validate_entrypoint_calldata(),
>             class_hash: None,
>             storage_address: account_tx_context.sender_address,
> ```

Define as a variable, so it's clear to the user it's the same one (also, to avoid future bugs); as you did in `test_invoke_tx`. In all locations.



_Code quote:_
```XML
account_tx_context.sender_address
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTIkpz9Bh1b_PjyH1--:-NTIkpz9Bh1b_PjyH1-0:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac582ba1d784892ceea931d3daefeb4eb61e42d9/crates/native_blockifier/src/py_transaction_execution_info.rs#L112)):*
> ```XML
>                 .collect(),
>             call_type: call.call_type as u8,
>             code_address: call.code_address.map(PyFelt::from),
> ```





_Suggestion:_
```XML
PyFelt::from(call.code_address)
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/417)* status: 1 of 9 files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTIkw0GEhpiKI-gEcNj:-NTNGq5gCQZH7GqRR7kh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac582ba1d784892ceea931d3daefeb4eb61e42d9/crates/blockifier/src/test_utils.rs#L156)):*
> ```XML
>         storage_address: contract_address,
>         caller_address: ContractAddress::default(),
>         code_address: None,
> ```

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTIjoUhA5_wdueiYYJq:-NTNHG3i6rYKZX1jVWKZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac582ba1d784892ceea931d3daefeb4eb61e42d9/crates/blockifier/src/execution/entry_point.rs#L44)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a backward compatibility comment, like we have in Python.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTIkPWz4brYgNZwb0ih:-NTN_-i71IbVIRBUvNY6:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac582ba1d784892ceea931d3daefeb4eb61e42d9/crates/blockifier/src/transaction/account_transaction.rs#L169)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Define as a variable, so it's clear to the user it's the same one (also, to avoid future bugs); as you did in `test_invoke_tx`. In all locations.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTIkpz9Bh1b_PjyH1--:-NTNX9A0CTn04adQHip-:bs3zwac) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac582ba1d784892ceea931d3daefeb4eb61e42d9/crates/native_blockifier/src/py_transaction_execution_info.rs#L112)):*
> ```XML
>                 .collect(),
>             call_type: call.call_type as u8,
>             code_address: call.code_address.map(PyFelt::from),
> ```

`code_address` is of type `Option`, so the `map` on it turns the inner value into a `PyFelt` (instead of unwrapping and rewrapping).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/417)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls.rs` line 319 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTOVQEd7Tmt8OTz2Crj:-NTOVQEd7Tmt8OTz2Crk:b5arize) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cf6adf078b772eef65b3461bc436fc8aaab5609/crates/blockifier/src/execution/syscalls.rs#L319)):*
> ```XML
> type DelegateCallResponse = CallContractResponse;
> 
> pub fn delegate_call(
> ```

Define `storage_address`, please. x2



_Code quote:_
```XML
let storage_address = request.contract_address;
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/417)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTIkpz9Bh1b_PjyH1--:-NTOVlPv8Tm611P58GG8:b-89q77x) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac582ba1d784892ceea931d3daefeb4eb61e42d9/crates/native_blockifier/src/py_transaction_execution_info.rs#L112)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

`code_address` is of type `Option`, so the `map` on it turns the inner value into a `PyFelt` (instead of unwrapping and rewrapping).
</blockquote></details>

Cool!

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/417)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls.rs` line 319 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTOVQEd7Tmt8OTz2Crj:-NTOfjdSEeSwRNFecqSr:bqblwmj) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cf6adf078b772eef65b3461bc436fc8aaab5609/crates/blockifier/src/execution/syscalls.rs#L319)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done. Thanks.
</blockquote></details>

In `delegate_l1_handler` too?



_Code quote:_
```XML
delegate_l1_handler
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/417)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls.rs` line 319 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/417#-NTOVQEd7Tmt8OTz2Crj:-NTOgGxf0MjXyGKWP74X:b-prne43) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cf6adf078b772eef65b3461bc436fc8aaab5609/crates/blockifier/src/execution/syscalls.rs#L319)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

In `delegate_l1_handler` too?
</blockquote></details>

Done. Thanks :)

**Pull request merged**
