### PR TITLE
fix: limit the syscall emit_event resources, keys, data and number of…

### PR DESCRIPTION
**Pull request by Yael-Starkware**
… events

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1463)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
corresponding python PR: https://github.com/starkware-industries/starkware/pull/33869

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1463#-:-Nq79ghM3bOip2MwHBMY:bk1auly)* status: 0 of 13 files reviewed, all discussions resolved

**Review by Yael-Starkware — COMMENTED** [review]
The constants that define the limitations are made up for now

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1463#-:-Nq7CKXKAnijqBbXOYQn:b-p5xy9a)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1463)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @Yael-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1463#-Nq7GzLJ9-6Ql1OqibDX:-Nq7GzLJ9-6Ql1OqibDY:bagnqsv) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cf66248f1e1991b9384a3f671ee39f8b355483a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L90)):*
> ```XML
>     SyscallError { error_data: Vec<StarkFelt> },
> }
> ```

Change `key` to plural.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1463#-Nq7GpotC74KZ7nvTgXI:-Nq7GpotC74KZ7nvTgXJ:b-cy1sr2) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cf66248f1e1991b9384a3f671ee39f8b355483a/crates/blockifier/src/execution/syscalls/mod.rs#L294)):*
> ```XML
> 
> pub fn exceeds_event_size_limit(
>     events_count: usize,
> ```

For consistency.



_Suggestion:_
```XML
n_emitted_events: usize,
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1463)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1463#-Nq7GzLJ9-6Ql1OqibDX:-Nq8-2hV5BKxpaU1XsB1:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cf66248f1e1991b9384a3f671ee39f8b355483a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L90)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Change `key` to plural.
</blockquote></details>

done
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1463#-Nq7GpotC74KZ7nvTgXI:-Nq8-1uDEgBLlCPE5HXR:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cf66248f1e1991b9384a3f671ee39f8b355483a/crates/blockifier/src/execution/syscalls/mod.rs#L294)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

For consistency.
</blockquote></details>

done
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1463#-Nq7CInIAB-_NJn9WejB:-Nq7wY339d_T76_m0ZOd:b3323iy) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cf66248f1e1991b9384a3f671ee39f8b355483a/crates/blockifier/src/execution/syscalls/mod.rs#L328)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why 2?
</blockquote></details>

first +1 is because n_emitted_events is starting to count from zero
second +1 is an unfortunate mistake , (I also changed the positive flow test case to check this edge case.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 13 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1463#-:-NqMuHN7-ahPmOq5zvac:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
