### PR TITLE
Add block pre process to blockifier

### PR DESCRIPTION
**Pull request by dafnamatsry**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 455 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz-fCzDPrvJllAPiFT:-NXz-fD-Bd7iaFRgwh2H:b-6na2hk) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/native_blockifier/src/py_transaction.rs#L455)):*
> ```XML
> 
>     // Block pre processing.
>     pub fn pre_process_block(&mut self, n_from_current_block_number_and_hash: &PyAny) {
> ```

Why together?



_Code quote:_
```XML
n_from_current_block_number_and_hash: &PyAny
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 460 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz-hsf7CofCFKUc6r6:-NXz-hsf7CofCFKUc6r7:b-4gnaoo) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/native_blockifier/src/py_transaction.rs#L460)):*
> ```XML
>         }
> 
>         let block_number = py_item(n_from_current_block_number_and_hash, 0).unwrap();
> ```

Fix `unwrap`s.



_Code quote:_
```XML
.unwrap()
```

**Comment by ArniStarkware** [comment]
IIUC, This PR should be over `main-v0.12.0`.

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz0HI-0D0PwFu9jT3G:-NYCHwPr95LhmhM-Y1zC:b-jpadzd) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/blockifier/src/block_execution.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This should be a struct; also, why `Option`?
</blockquote></details>

I started by making it a struct, and I changed it because this way the code is cleaner.
If you insist, I can change it back to a struct...

About Option:
None is a valid input in general. Because this function is only doing one thing right now, I don’t call it if it's None.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 455 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz-fCzDPrvJllAPiFT:-NYCSOgm5RwXUVlzwOwq:b-h3w56t) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/native_blockifier/src/py_transaction.rs#L455)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why together?
</blockquote></details>

They are coupled. Why not?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 460 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz-hsf7CofCFKUc6r6:-NYCSDDa6xZIKcZXto8T:b-lbut5x) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/native_blockifier/src/py_transaction.rs#L460)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Fix `unwrap`s.
</blockquote></details>

What do you mean?

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYCNasi6hiXjtedSTsh:-NYDGiRz3s20R0HWXAl3:b-prne43) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

IIUC, This PR should be over `main-v0.12.0`.
</blockquote></details>

Done. Thanks :)

___

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @noa)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 460 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz-hsf7CofCFKUc6r6:-NYDMbTx3hsL3Msl3wf3:b-8be886) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/native_blockifier/src/py_transaction.rs#L460)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

@noa?

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, @noa, and @Yoni-Starkware)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, @noa, and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 460 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz-hsf7CofCFKUc6r6:-NYDNPeN4GmLnwN1Hw_7:bpxndr0) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/native_blockifier/src/py_transaction.rs#L460)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@noa?
</blockquote></details>

We prefer to avoid using `unwrap()`s since it can lead to panicking. Try using `?`

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @elintul, @giladchase, and @noa)

___
*[`crates/blockifier/src/block_execution.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYDm2dYENoyCviKhbpe:-NYDm2dYENoyCviKhbpf:b-gsx39c) ([raw file](https://github.com/starkware-libs/blockifier/blob/7aa34fba85e60e3e88aaad8956f425fcbdedf2b3/crates/blockifier/src/block_execution.rs#L23)):*
> ```XML
>             ContractAddress::try_from(StarkFelt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS))
>                 .unwrap(),
>             StorageKey::try_from(StarkFelt::from(block_number.0)).unwrap(),
> ```

You'll have to return something like
https://github.com/starkware-libs/blockifier/blob/e66682bfa402213a053f3704f877c9429038613b/crates/native_blockifier/src/py_transaction.rs#L276



_Suggestion:_
```XML
            ContractAddress::try_from(StarkFelt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS))
    ?,
            StorageKey::try_from(StarkFelt::from(block_number.0))?,
```

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @elintul, @giladchase, and @noa)

___
*[`crates/blockifier/src/block_execution.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYHt-h14Ei_1PoqAeRX:-NYHt-h14Ei_1PoqAeRY:b-gbg8fu) ([raw file](https://github.com/starkware-libs/blockifier/blob/d140b7d69faf4a83a1b266bac79daa552673c6b4/crates/blockifier/src/block_execution.rs#L14)):*
> ```XML
> 
> // Block pre processing.
> // Writes to the block number -> hash mapping in the storage.
> ```

Can be fixed in another PR



_Suggestion:_
```XML
// Block pre-processing.
// Writes the hash of the (current_block_number - N) block under its block number in the dedicated
// contract state, where N=N_BLOCKS_FROM_CURRENT.
```

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @elintul, @giladchase, and @noa)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 457 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYHtWVp9qCRr_miZ5ON:-NYHtWVp9qCRr_miZ5OO:b-a8k3rw) ([raw file](https://github.com/starkware-libs/blockifier/blob/d140b7d69faf4a83a1b266bac79daa552673c6b4/crates/native_blockifier/src/py_transaction.rs#L457)):*
> ```XML
>     }
> 
>     // Block pre processing.
> ```

Next PR.



_Suggestion:_
```XML
// Block pre-processing; see `block_execution::pre_process_block` documentation.
```

**Review by Yoni-Starkware — APPROVED** [review]
> Dismissed @elintul from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @giladchase)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz0HI-0D0PwFu9jT3G:-NYIO47yB0gysoZQa79n:b-8ryd3d) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/blockifier/src/block_execution.rs#L18)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I started by making it a struct, and I changed it because this way the code is cleaner.
If you insist, I can change it back to a struct...

About Option:
None is a valid input in general. Because this function is only doing one thing right now, I don’t call it if it's None.
</blockquote></details>

When will you call it with `None`? And I think it's better to use a struct but can be done in another PR. 
___
*[`crates/blockifier/src/block_execution.rs` line 22 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYIInXj73eiwnyuzufz:-NYIInXj73eiwnyuzug-:b8riis4) ([raw file](https://github.com/starkware-libs/blockifier/blob/d140b7d69faf4a83a1b266bac79daa552673c6b4/crates/blockifier/src/block_execution.rs#L22)):*
> ```XML
>         state.set_storage_at(
>             ContractAddress::try_from(StarkFelt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS))
>                 .unwrap(),
> ```

And maybe return `Result<>`?



_Suggestion:_
```XML
?
```
___
*[`crates/blockifier/src/block_execution.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYIJItVBhLG4pwJbZVg:-NYIJItVBhLG4pwJbZVh:b-82z2o9) ([raw file](https://github.com/starkware-libs/blockifier/blob/d140b7d69faf4a83a1b266bac79daa552673c6b4/crates/blockifier/src/block_execution.rs#L24)):*
> ```XML
>                 .unwrap(),
>             StorageKey::try_from(StarkFelt::from(block_number.0))
>                 .expect("Failed to convert BlockNumber to StorageKey."),
> ```

Do we expect it to always work? Do we know that `block_number < 2^251`? 



_Code quote:_
```XML
.expect("Failed to convert BlockNumber to StorageKey.")
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 455 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz-fCzDPrvJllAPiFT:-NYIOkTC552BRxe7ARQ8:b750s0c) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/native_blockifier/src/py_transaction.rs#L455)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

They are coupled. Why not?
</blockquote></details>

WDYM by coupled? Can't you pass them separately as two objects?

**Review by Yoni-Starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 455 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz-fCzDPrvJllAPiFT:-NYIZMsq0MiaeNVeipD1:b5547f0) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/native_blockifier/src/py_transaction.rs#L455)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM by coupled? Can't you pass them separately as two objects?
</blockquote></details>

They are either both None or both not None

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz0HI-0D0PwFu9jT3G:-NYIZW47ExXySqWmgCB-:b6zy1o4) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/blockifier/src/block_execution.rs#L18)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When will you call it with `None`? And I think it's better to use a struct but can be done in another PR. 
</blockquote></details>

If block (current block number - 10) does not exist yet...
___
*[`crates/blockifier/src/block_execution.rs` line 22 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYIInXj73eiwnyuzufz:-NYIXeB3ADp-ZXAZ1sjI:bnbn88u) ([raw file](https://github.com/starkware-libs/blockifier/blob/d140b7d69faf4a83a1b266bac79daa552673c6b4/crates/blockifier/src/block_execution.rs#L22)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And maybe return `Result<>`?
</blockquote></details>

This can never happen; the contract address is a const u64 equals to 1, which can be converted to ContractAddress.
___
*[`crates/blockifier/src/block_execution.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYIJItVBhLG4pwJbZVg:-NYIYD351Gto5K-zxQPo:b-oo3frj) ([raw file](https://github.com/starkware-libs/blockifier/blob/d140b7d69faf4a83a1b266bac79daa552673c6b4/crates/blockifier/src/block_execution.rs#L24)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we expect it to always work? Do we know that `block_number < 2^251`? 
</blockquote></details>

Yes, BlockNumber is u64.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 455 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz-fCzDPrvJllAPiFT:-NYIX0_AAmWoEG8DnvIt:bqahzav) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/native_blockifier/src/py_transaction.rs#L455)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM by coupled? Can't you pass them separately as two objects?
</blockquote></details>

I can technically, but it makes sense to put them together because they are logically coupled.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 22 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYIInXj73eiwnyuzufz:-NYIl9I31IznNq4YXzaj:b-aahq84) ([raw file](https://github.com/starkware-libs/blockifier/blob/d140b7d69faf4a83a1b266bac79daa552673c6b4/crates/blockifier/src/block_execution.rs#L22)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

This can never happen; the contract address is a const u64 equals to 1, which can be converted to ContractAddress.
</blockquote></details>

In that case, can you please use `.expect()` instead?
___
*[`crates/blockifier/src/block_execution.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYIJItVBhLG4pwJbZVg:-NYIlGok5hPURRyR7Hzt:byr4flj) ([raw file](https://github.com/starkware-libs/blockifier/blob/d140b7d69faf4a83a1b266bac79daa552673c6b4/crates/blockifier/src/block_execution.rs#L24)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Yes, BlockNumber is u64.
</blockquote></details>

Right.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 460 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYIrlgDDEP9GWUZ4brT:-NYIrlgDDEP9GWUZ4brU:b-tuojwn) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ad8d4b2d9be7a47d0cb3a3978912debe0d9c28f/crates/native_blockifier/src/py_transaction.rs#L460)):*
> ```XML
>     pub fn pre_process_block(
>         &mut self,
>         n_from_current_block_number_and_hash: &PyAny,
> ```

And then you can remove `py_item` (assuming you pass it as a tuple)



_Suggestion:_
```XML
n_from_current_block_number_and_hash: Option<(u64, PyFelt)>
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 467 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYIpu9YDGDg5lXmB6Vh:-NYIpu9YDGDg5lXmB6Vi:b-b1h3zn) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ad8d4b2d9be7a47d0cb3a3978912debe0d9c28f/crates/native_blockifier/src/py_transaction.rs#L467)):*
> ```XML
> 
>         let block_number = py_item(n_from_current_block_number_and_hash, 0)?;
>         let block_hash = biguint_to_felt(py_item(n_from_current_block_number_and_hash, 1)?)?;
> ```

This way `n_from_current_block_number_and_hash` is not `Option`.
What is the meaning of `n_from_current_block_number_and_hash`? What is `n`?



_Suggestion:_
```XML
        let Some(n_from_current_block_number_and_hash) =  n_from_current_block_number_and_hash else {
            return Ok(());
        }

        let block_number = py_item(n_from_current_block_number_and_hash, 0)?;
        let block_hash = biguint_to_felt(py_item(n_from_current_block_number_and_hash, 1)?)?;
```

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/block_execution.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz0HI-0D0PwFu9jT3G:-NYJBUru7fWVDnRYfOGa:bd8391d) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/blockifier/src/block_execution.rs#L18)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

If block (current block number - 10) does not exist yet...
</blockquote></details>

How is the code cleaner using a tuple?

**Review by elintul — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 458 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYRmccz8JSt6HdlbUlm:-NYRmcd-57PZXO7RzEaC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/839972eb7097361291660e31580a434c742da70a/crates/native_blockifier/src/py_transaction.rs#L458)):*
> ```XML
> 
>     // Block pre-processing; see `block_execution::pre_process_block` documentation.
>     pub fn pre_process_block(
> ```





_Suggestion:_
```XML
 #[args(n_from_current_block_number_and_hash)]
pub fn pre_process_block(
```

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NXz0HI-0D0PwFu9jT3G:-NYS6Ud23benqrNXDOzW:bz05knu) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5dcd32547a0c38e2efa20f9003f6431a504faa9/crates/blockifier/src/block_execution.rs#L18)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

With a tuple, I can do `Some((block_number, block_hash))`...
</blockquote></details>

Also with a struct
___
*[`crates/blockifier/src/block_execution.rs` line 23 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYS6dRO31pzFvV5BguT:-NYS6dRO31pzFvV5BguU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/482ed689948a6d8cec40abe749dad4227be81c9b/crates/blockifier/src/block_execution.rs#L23)):*
> ```XML
>         state.set_storage_at(
>             ContractAddress::try_from(StarkFelt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS))
>                 .expect("Failed to convert BLOCK_HASH_CONTRACT_ADDRESS to ContractAddress."),
> ```





_Suggestion:_
```XML
`BLOCK_HASH_CONTRACT_ADDRESS`
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 467 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYIpu9YDGDg5lXmB6Vh:-NYS88ZO1sb_PhIA9M2m:b8d5twp) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ad8d4b2d9be7a47d0cb3a3978912debe0d9c28f/crates/native_blockifier/src/py_transaction.rs#L467)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Used map
</blockquote></details>

Got it. This way you call the ` pre_process_block` even when the input is `None` but I guess you do it for future use?

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 23 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYS6dRO31pzFvV5BguT:-NYSmctK5dEZ94wP8Q_N:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/482ed689948a6d8cec40abe749dad4227be81c9b/crates/blockifier/src/block_execution.rs#L23)):*
> ```XML
>         state.set_storage_at(
>             ContractAddress::try_from(StarkFelt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS))
>                 .expect("Failed to convert BLOCK_HASH_CONTRACT_ADDRESS to ContractAddress."),
> ```

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 467 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/608#-NYIpu9YDGDg5lXmB6Vh:-NYSmeFB4SnjDMKFkFlK:b2nhswy) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ad8d4b2d9be7a47d0cb3a3978912debe0d9c28f/crates/native_blockifier/src/py_transaction.rs#L467)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it. This way you call the ` pre_process_block` even when the input is `None` but I guess you do it for future use?
</blockquote></details>

Yes

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/608#-:-NYWqxkkATL9tuFw1y-c:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
