### PR TITLE
Elin/merge main mempool into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2018)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2018)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2018)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2018#-O0n3Fba8PsXPREjc73x:-O0n3Fba8PsXPREjc73y:bahapmr) ([raw file](https://github.com/starkware-libs/blockifier/blob/5b6d25e591af28d1e4d6f9c748ce4a759b982c36/crates/blockifier/src/test_utils/contracts.rs#L92)):*
> ```XML
>     }
> 
>     fn has_two_versions(&self) -> bool {
> ```

Code moved in `main-mempool`, changed in `main`; I took `main`'s changes with `main-mempool`'s locations.

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2018)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2018#-:-O0n41bf3JmFW4zjeGJH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
