### PR TITLE
test: add the tx_version parameter to faulty_account_tx_args

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1796)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1796?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1797** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1797?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1796** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1796?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1794** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1794?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
+reviewer:@MohammadNassar1 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-:-NvfHZ7O0HG5IZ6BpEpT:bfvmjeq)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/entry_point_test.rs` line 1016 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-NvfcGwKB2pTA1f8tzwv:-NvfcGwL6qogR-rRt8BQ:blnkl7v) ([raw file](https://github.com/starkware-libs/blockifier/blob/6593811d891fdd43ec992a4cea9dd6197f2e00a6/crates/blockifier/src/execution/entry_point_test.rs#L1016)):*
> ```XML
>     TransactionType::Declare,
>     VALIDATE_DECLARE_ENTRY_POINT_NAME,
>     TransactionVersion::ONE
> ```

Note the version was `ONE` before this change as well (Same is true for `declare`, `deploy_account` and `invoke`): https://github.com/starkware-libs/blockifier/blob/f84bed3adedd7aaafbce6f5532e7db701f45ca13/crates/blockifier/src/test_utils/declare.rs#L38



_Code quote:_
```XML
    TransactionVersion::ONE
```

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1796)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 1016 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-NvfcGwKB2pTA1f8tzwv:-NvkkIVF198L3LLYdK5e:bplcsnz) ([raw file](https://github.com/starkware-libs/blockifier/blob/6593811d891fdd43ec992a4cea9dd6197f2e00a6/crates/blockifier/src/execution/entry_point_test.rs#L1016)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Note the version was `ONE` before this change as well (Same is true for `declare`, `deploy_account` and `invoke`): https://github.com/starkware-libs/blockifier/blob/f84bed3adedd7aaafbce6f5532e7db701f45ca13/crates/blockifier/src/test_utils/declare.rs#L38
</blockquote></details>

Where it was defined as version 1?
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-Nvkk_DH9NG4_ivMVkq9:-Nvkk_DH9NG4_ivMVkqA:b-cguvoz) ([raw file](https://github.com/starkware-libs/blockifier/blob/6593811d891fdd43ec992a4cea9dd6197f2e00a6/crates/blockifier/src/transaction/test_utils.rs#L157)):*
> ```XML
>             contract_address_salt: ContractAddressSalt::default(),
>             validate_constructor: false,
>             max_fee: Fee::default(),
> ```

How can it be version 3 and still have max_fee arg?
and where are the new fields (resource_bound, nonce_da, fee_da, ...)?
What do I miss here? :)



_Code quote:_
```XML
            tx_version: TransactionVersion::THREE,
            scenario: VALID,
            additional_data: None,
            sender_address: ContractAddress::default(),
            class_hash: ClassHash::default(),
            contract_address_salt: ContractAddressSalt::default(),
            validate_constructor: false,
            max_fee: Fee::default(),
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1796)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 1016 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-NvfcGwKB2pTA1f8tzwv:-Nvkyvlc9iiCjYi7e5cT:b-y6tf70) ([raw file](https://github.com/starkware-libs/blockifier/blob/6593811d891fdd43ec992a4cea9dd6197f2e00a6/crates/blockifier/src/execution/entry_point_test.rs#L1016)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Where it was defined as version 1?
</blockquote></details>

As I linked in this message.
It is the default value used for `DeclareTxArgs` (etc).

https://github.com/starkware-libs/blockifier/blob/f84bed3adedd7aaafbce6f5532e7db701f45ca13/crates/blockifier/src/test_utils/declare.rs#L32-L38
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-Nvkk_DH9NG4_ivMVkq9:-NvkzQ6d9w7sLp32RHVE:b9u6g6v) ([raw file](https://github.com/starkware-libs/blockifier/blob/6593811d891fdd43ec992a4cea9dd6197f2e00a6/crates/blockifier/src/transaction/test_utils.rs#L157)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

How can it be version 3 and still have max_fee arg?
and where are the new fields (resource_bound, nonce_da, fee_da, ...)?
What do I miss here? :)
</blockquote></details>

See the comment below.

These fields get default values in the context of flows using `faulty-account`.
It is interesting to see where this struct is being called, where did it matter what the `max_fee` was, and try to convert that test to use V3 txs. If you wish, I will do it (and other similar conversions) in another PR. 
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 205 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-NvkzA2V9bEQY7nMzDYb:-NvkzA2V9bEQY7nMzDYc:bb3ug2) ([raw file](https://github.com/starkware-libs/blockifier/blob/6593811d891fdd43ec992a4cea9dd6197f2e00a6/crates/blockifier/src/transaction/test_utils.rs#L205)):*
> ```XML
>                 },
>                 class_info,
>             )
> ```

@MohammadNassar1, you missed the call to this function; the function `declare_tx` is a generic function that gets all sorts of variables - but ignores some of them based on the `tx_version.`

https://github.com/starkware-libs/blockifier/blob/f84bed3adedd7aaafbce6f5532e7db701f45ca13/crates/blockifier/src/test_utils/declare.rs#L70-L74



_Code quote:_
```XML
            declare_tx(
                declare_tx_args! {
                    max_fee,
                    signature,
                    sender_address,
                    version: tx_version,
                    nonce: nonce_manager.next(sender_address),
                    class_hash,
                },
                class_info,
            )
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-:-Nvl7sa5AbXVG2wcDTK0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 1016 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-NvfcGwKB2pTA1f8tzwv:-Nvl74u3CrSc6nEJyUdN:b-ucfknh) ([raw file](https://github.com/starkware-libs/blockifier/blob/6593811d891fdd43ec992a4cea9dd6197f2e00a6/crates/blockifier/src/execution/entry_point_test.rs#L1016)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

As I linked in this message.
It is the default value used for `DeclareTxArgs` (etc).

https://github.com/starkware-libs/blockifier/blob/f84bed3adedd7aaafbce6f5532e7db701f45ca13/crates/blockifier/src/test_utils/declare.rs#L32-L38
</blockquote></details>

Thanks!
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-Nvkk_DH9NG4_ivMVkq9:-Nvl7vIn46lJ3Nq6SVpf:bbfxn1u) ([raw file](https://github.com/starkware-libs/blockifier/blob/6593811d891fdd43ec992a4cea9dd6197f2e00a6/crates/blockifier/src/transaction/test_utils.rs#L157)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

See the comment below.

These fields get default values in the context of flows using `faulty-account`.
It is interesting to see where this struct is being called, where did it matter what the `max_fee` was, and try to convert that test to use V3 txs. If you wish, I will do it (and other similar conversions) in another PR.
</blockquote></details>

I see.
Thanks for the explanation!
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 205 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1796#-NvkzA2V9bEQY7nMzDYb:-Nvl7kE6D3guWRBCqb7F:bn3tslh) ([raw file](https://github.com/starkware-libs/blockifier/blob/6593811d891fdd43ec992a4cea9dd6197f2e00a6/crates/blockifier/src/transaction/test_utils.rs#L205)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@MohammadNassar1, you missed the call to this function; the function `declare_tx` is a generic function that gets all sorts of variables - but ignores some of them based on the `tx_version.`

https://github.com/starkware-libs/blockifier/blob/f84bed3adedd7aaafbce6f5532e7db701f45ca13/crates/blockifier/src/test_utils/declare.rs#L70-L74
</blockquote></details>

I see.
Thanks!

**Pull request merged**
