### PR TITLE
Fix simulate version

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1058)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1058)* status: 6 of 16 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-imU65f64hAIwbGXZ:-Ni-imU65f64hAIwbGX_:b-rkvbrm) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/objects.rs#L44)):*
> ```XML
>         }
> 
>         version
> ```

Can you work with a felt that supports `+`, instead of converters?



_Suggestion:_
```XML
        if !self.simulate {
            return self.version;
        }
        
        let simulate_version_base = BigUint::from(2_u8).pow(SIMULATE_VERSION_BASE_BIT);
        let simulate_version = simulate_version_base + felt_to_biguint(version.0);
        TransactionVersion(
            biguint_to_felt(simulate_version).expect("The version should be a field element."),
        );
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 10 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1058)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-imU65f64hAIwbGXZ:-Ni-l98pDFojoXA7esZc:b-jfd95m) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/objects.rs#L44)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you work with a felt that supports `+`, instead of converters?
</blockquote></details>

Also in the test.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-kTZu88YHYyb1HieY:-Ni-kTZu88YHYyb1HieZ:b-k9w5ia) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/transactions.rs#L173)):*
> ```XML
>     pub fn simulate(&self) -> bool {
>         self.simulate
>     }
> ```

Why is this getter needed?



_Code quote:_
```XML
    pub fn simulate(&self) -> bool {
        self.simulate
    }
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1036 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-kgM37cshOfqIzQU7:-Ni-kgM37cshOfqIzQU8:bprckbu) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/transactions_test.rs#L1036)):*
> ```XML
> }
> 
> #[rstest]
> ```

Consider using Mohammad's method `execute_directly_given_account_context`, for a more succinct test.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-krCM9LkhtAXxq9wi:-Ni-krCM9LkhtAXxq9wj:bwefagu) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/native_blockifier/src/py_transaction.rs#L107)):*
> ```XML
>     };
> 
>     Ok(DeclareTransaction::new(
> ```

Let's make `new` pass `simulate=false`, and add another c-tor: `new_for_simulate`.



_Code quote:_
```XML
new
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1058)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/objects.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-imU65f64hAIwbGXZ:-Ni-nje9746exXgO94Fk:b-1bqq28) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/objects.rs#L44)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Also in the test.
</blockquote></details>

Done.  Like.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1058)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-kTZu88YHYyb1HieY:-Ni-u9OJ37ty15yXr7Px:bl8bz0o) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/transactions.rs#L173)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this getter needed?
</blockquote></details>

Because it is a private field. I wanted to be consistent with the other fields.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1036 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-kgM37cshOfqIzQU7:-Ni-xuOzCHHaRbZGQ4jU:bmanb1r) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/transactions_test.rs#L1036)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider using Mohammad's method `execute_directly_given_account_context`, for a more succinct test.
</blockquote></details>

Done.
I think there is added value in checking the simulation flag in the context of executing an account transaction. WDYT?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-krCM9LkhtAXxq9wi:-Ni0kgcM5usT-KvZc6Bw:b830ph5) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/native_blockifier/src/py_transaction.rs#L107)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's make `new` pass `simulate=false`, and add another c-tor: `new_for_simulate`.
</blockquote></details>

Don't we want to be consistent with other transactions type? What should be used in the method `from_api`?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1058)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 231 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni4_E482mSNYTAEGsZI:-Ni4_E496I2-XM0FUzp1:b-tfj34c) ([raw file](https://github.com/starkware-libs/blockifier/blob/84d6c0601510229c0c82aa59aaf9cc1af0b8703f/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L231)):*
> ```XML
>     let mut state = create_test_state();
>     // TODO(spapini): Fix the "UNEXPECTED ERROR".
>     let account_tx_context = AccountTransactionContext { simulate, ..Default::default() };
> ```

Please restore the values, we lost coverage.



_Code quote:_
```XML
Default::default()
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-kTZu88YHYyb1HieY:-Ni4_pm_1ERxELOuBX3r:b-oq3bwk) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/transactions.rs#L173)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Because it is a private field. I wanted to be consistent with the other fields.
</blockquote></details>

And why didn't the rest of the transactions need it?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1036 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-kgM37cshOfqIzQU7:-Ni4_JjvD-qDa5fZRqon:b-iy3hiq) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/transactions_test.rs#L1036)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done.
I think there is added value in checking the simulation flag in the context of executing an account transaction. WDYT?
</blockquote></details>

You can leave both.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-krCM9LkhtAXxq9wi:-Ni4_VLR-uUT5R4RnLrm:b-cbh1md) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/native_blockifier/src/py_transaction.rs#L107)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Don't we want to be consistent with other transactions type? What should be used in the method `from_api`?
</blockquote></details>

I meant for all types. Can it be done? I think `from_api` should get the flag and call the corresponding c-tor.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1058)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 231 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni4_E482mSNYTAEGsZI:-Ni4dWy_63RXgFbhrQOl:b9wm8fn) ([raw file](https://github.com/starkware-libs/blockifier/blob/84d6c0601510229c0c82aa59aaf9cc1af0b8703f/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L231)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please restore the values, we lost coverage.
</blockquote></details>

WDYM? Which values?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-kTZu88YHYyb1HieY:-Ni4deyl21GEsuA_gY78:b-2mduch) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/transactions.rs#L173)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

And why didn't the rest of the transactions need it?
</blockquote></details>

The rest of the transactions has only public fields. 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1036 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-kgM37cshOfqIzQU7:-Ni4dkHp96Cua4fmSci2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/transactions_test.rs#L1036)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You can leave both.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1058)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 231 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni4_E482mSNYTAEGsZI:-Ni4h6vV6lFBtt5C1ZTV:b2c10we) ([raw file](https://github.com/starkware-libs/blockifier/blob/84d6c0601510229c0c82aa59aaf9cc1af0b8703f/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L231)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM? Which values?
</blockquote></details>

The ones changed from non-zero to zero.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-kTZu88YHYyb1HieY:-Ni4gzBv66LEc8shb54N:bhma6r7) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/transactions.rs#L173)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The rest of the transactions has only public fields.
</blockquote></details>

So declare should also have them `pub`lic (not in this PR).

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1058)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 231 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni4_E482mSNYTAEGsZI:-Ni4mBXaDrSJyZF0Hck_:b-evp4cs) ([raw file](https://github.com/starkware-libs/blockifier/blob/84d6c0601510229c0c82aa59aaf9cc1af0b8703f/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L231)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The ones changed from non-zero to zero.
</blockquote></details>

We used `unwrap_error()` which basically ignored the error, meaning the previous numbers did not work. Do you want me to set some numbers greater then zero?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-kTZu88YHYyb1HieY:-Ni5SwdZClRHLImTWrF5:b-kihalq) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/blockifier/src/transaction/transactions.rs#L173)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So declare should also have them `pub`lic (not in this PR).
</blockquote></details>

Agree. added to Monday.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1058#-Ni-krCM9LkhtAXxq9wi:-Ni5Sb2_8QHUU0JqoCv_:b4a8ar4) ([raw file](https://github.com/starkware-libs/blockifier/blob/26286edae31e88ab71f8eef0747c1d012a398787/crates/native_blockifier/src/py_transaction.rs#L107)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I meant for all types. Can it be done? I think `from_api` should get the flag and call the corresponding c-tor.
</blockquote></details>

It can be done. I don't follow: the corresponding c-tor will not allow passing `simulate=true` and FN are using the method `from_api`.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1058)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request closed without merging**
