### PR TITLE
refactor(concurrency): add deployed contracts check to validate_read_set

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-Nws1ats9H-JCCl4-b9h:-Nws1ats9H-JCCl4-b9i:b9udz9i) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa16c593117bdb5b3f1bd64d618f0d50c44127ad/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L97)):*
> ```XML
> 
>         for (&class_hash, expected_value) in &state_cache.declared_contract_initial_values {
>             let value = self.compiled_contract_classes.read(self.tx_index, class_hash).is_some();
> ```

Discussed offline (writing it here for documentation):
It's better to add a `declared_contracts` mapping and use it here. Why?
1. It saves us "going" all the way to papyrus to read a non-existing contract class (assuming a `false` in the read set is also written in the versioned state).
2. We will need the `declared_contracts` mapping anyway, for the `commit` method. An alternative to this mapping is to separate the contract class mapping to reads and writes (in the cached state). I personally think the former is better.

@Yoni-Starkware FYI



_Code quote:_
```XML
            let value = self.compiled_contract_classes.read(self.tx_index, class_hash).is_some();
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: all files reviewed, 2 unresolved discussions (waiting on @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NwsWAal7QvyGA02jKJW:-NwsWAam3HrvfbncKo23:b1tlzxg) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa16c593117bdb5b3f1bd64d618f0d50c44127ad/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L51)):*
> ```XML
>     // object (probabily `VersionedState`). As RefCell operations are not thread-safe. Therefore,
>     // accessing this function should be protected by a mutex to ensure thread safety.
>     pub fn validate_read_set(&mut self, tx_index: TxIndex, state_cache: &mut StateCache) -> bool {
> ```

Need to rebase



_Code quote:_
```XML
b fn validate_read_set(&mut self, tx_index: TxIndex, state_cache: &mut StateCache) -> bool {
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-Nws1ats9H-JCCl4-b9h:-NwsYZri1PQNv5LBlKuN:b-hfghm4) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa16c593117bdb5b3f1bd64d618f0d50c44127ad/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L97)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Discussed offline (writing it here for documentation):
It's better to add a `declared_contracts` mapping and use it here. Why?
1. It saves us "going" all the way to papyrus to read a non-existing contract class (assuming a `false` in the read set is also written in the versioned state).
2. We will need the `declared_contracts` mapping anyway, for the `commit` method. An alternative to this mapping is to separate the contract class mapping to reads and writes (in the cached state). I personally think the former is better.

@Yoni-Starkware FYI
</blockquote></details>

Sounds good

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NwsWAal7QvyGA02jKJW:-NxMq9rNAQqkpXAQzWG2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa16c593117bdb5b3f1bd64d618f0d50c44127ad/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L51)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Need to rebase
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-Nws1ats9H-JCCl4-b9h:-NxN4nOLA-I12iUgelMi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa16c593117bdb5b3f1bd64d618f0d50c44127ad/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L97)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Sounds good
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-Nws1ats9H-JCCl4-b9h:-NxR5hvv9XSHYSt8ULhB:ba71c91) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa16c593117bdb5b3f1bd64d618f0d50c44127ad/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L97)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@noaov1 we now have two mappings (declared, compiled_classes) that should be consistent.
We should assert this somewhere, probably in the method that finalizes the versioned state
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NxR7Rir9_cqV4fzq6qr:-NxR7Rir9_cqV4fzq6qs:blj6mrq) ([raw file](https://github.com/starkware-libs/blockifier/blob/3237acffd6e948b480fe14592ca05174cf955d50/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L32)):*
> ```XML
>     compiled_class_hashes: VersionedStorage<ClassHash, CompiledClassHash>,
>     compiled_contract_classes: VersionedStorage<ClassHash, ContractClass>,
>     declared_contracts: VersionedStorage<ClassHash, bool>,
> ```

Comment about compiled_contract_classes. Mention that this storage must be consistent with `declared_contracts` and its reads are not validated.

@noaov1, should this storage be versioned at all? 



_Suggestion:_
```XML
    declared_contracts: VersionedStorage<ClassHash, bool>,
    
    // ...
    compiled_contract_classes: VersionedStorage<ClassHash, ContractClass>,
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 246 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NxR9KUY3ltYfxI7K5iq:-NxR9KUY3ltYfxI7K5ir:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/3237acffd6e948b480fe14592ca05174cf955d50/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L246)):*
> ```XML
>             None => match state.initial_state.get_compiled_contract_class(class_hash) {
>                 Ok(initial_value) => {
>                     let initial_value = initial_value;
> ```

?



_Suggestion:_
```XML
                Ok(initial_value) => {
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: all files reviewed, 4 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-Nws1ats9H-JCCl4-b9h:-NxSQO6029v9KlRdg2A1:b-6l1yps) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa16c593117bdb5b3f1bd64d618f0d50c44127ad/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L97)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@noaov1 we now have two mappings (declared, compiled_classes) that should be consistent.
We should assert this somewhere, probably in the method that finalizes the versioned state
</blockquote></details>

Correct. Why is it different fro the `CachedState`? Should we check consistency there as well?
Added a task to monday.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NxR7Rir9_cqV4fzq6qr:-NxS5yIC7gkUGnj9aq5T:baebgto) ([raw file](https://github.com/starkware-libs/blockifier/blob/3237acffd6e948b480fe14592ca05174cf955d50/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L32)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Comment about compiled_contract_classes. Mention that this storage must be consistent with `declared_contracts` and its reads are not validated.

@noaov1, should this storage be versioned at all?
</blockquote></details>

I think that yes. I wrote why in the comment below. 
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NxSUNpV0SA8-xSKFPg2:-NxSUNpV0SA8-xSKFPg3:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3237acffd6e948b480fe14592ca05174cf955d50/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L117)):*
> ```XML
> 
>         // TODO(Mohammad, 01/04/2024): Edit the code to handle the case of a deploy preceding a
>         // decalre transaction.
> ```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-Nws1ats9H-JCCl4-b9h:-NxvvxaW1-i1XIXaEV9A:bhzpuz4) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa16c593117bdb5b3f1bd64d618f0d50c44127ad/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L97)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Correct. Why is it different fro the `CachedState`? Should we check consistency there as well?
Added a task to monday.
</blockquote></details>

IIUC, there is no action item for this PR.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NxR7Rir9_cqV4fzq6qr:-Nxvvq7T0L2boidYkF6i:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3237acffd6e948b480fe14592ca05174cf955d50/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L32)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that yes. I wrote why in the comment below.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NxSUNpV0SA8-xSKFPg2:-Nxw-4nsCOVoVaCrjS0K:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3237acffd6e948b480fe14592ca05174cf955d50/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L117)):*
> ```XML
> 
>         // TODO(Mohammad, 01/04/2024): Edit the code to handle the case of a deploy preceding a
>         // decalre transaction.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 246 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NxR9KUY3ltYfxI7K5iq:-NxvRVDDAKJPwUdAuCSv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3237acffd6e948b480fe14592ca05174cf955d50/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L246)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-:-Nxw2TqzAfgO3bw8RZUV:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-:-NxwplDv6x2DE1c46CjO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
Can you please add it to the existing test?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-:-NyF-M2E52sbxkZwYKsR:b7lshfa)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 136 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NyVAtD651keSG5isG7E:-NyVAtD651keSG5isG7F:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9deda109db8c0596b59b0c4c83ea5d0ccd9962a0/crates/blockifier/src/concurrency/versioned_state.rs#L136)):*
> ```XML
>                 self.compiled_contract_classes
>                     .get_writes_up_to_index(tx_index)
>                     .contains_key(&class_hash)
> ```





_Suggestion:_
```XML
                self.compiled_contract_classes.read(tx_index, class_hash).expect(READ_ERR).is_some();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 328 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NyVBo-z7aQ5-tnkwBAd:-NyVBo-z7aQ5-tnkwBAe:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9deda109db8c0596b59b0c4c83ea5d0ccd9962a0/crates/blockifier/src/concurrency/versioned_state_test.rs#L328)):*
> ```XML
> 
> #[rstest]
> fn test_validate_read_set(
> ```





_Suggestion:_
```XML
fn test_validate_reads(
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 363 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NyVBNNU2_VEkFj1kb3w:-NyVBNNV3ER7-RGcWRFh:b-gjcy9u) ([raw file](https://github.com/starkware-libs/blockifier/blob/9deda109db8c0596b59b0c4c83ea5d0ccd9962a0/crates/blockifier/src/concurrency/versioned_state_test.rs#L363)):*
> ```XML
>     } else {
>         panic!("get_compiled_contract_class returned an unexpected error: {:?}", result);
>     }
> ```

Please use `assert_matches`.



_Code quote:_
```XML
    assert!(result.is_err());
    if let Err(StateError::UndeclaredClassHash(err_class_hash)) = result {
        assert_eq!(err_class_hash, class_hash);
    } else {
        panic!("get_compiled_contract_class returned an unexpected error: {:?}", result);
    }
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 136 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NyVAtD651keSG5isG7E:-NyVYnNlASPNLZcAPux8:bsituyn) ([raw file](https://github.com/starkware-libs/blockifier/blob/9deda109db8c0596b59b0c4c83ea5d0ccd9962a0/crates/blockifier/src/concurrency/versioned_state.rs#L136)):*
> ```XML
>                 self.compiled_contract_classes
>                     .get_writes_up_to_index(tx_index)
>                     .contains_key(&class_hash)
> ```

Edit:



_Code snippet:_
```XML
// Reads the write made by the current transaction.
self.compiled_contract_classes.read(tx_index + 1, class_hash).is_some()
```

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 134 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-NyVukgBC1htjz9OU_eR:-NyVukgBC1htjz9OU_eS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/eea7166f3e5dd68785af8ef904cb8399440482d0/crates/blockifier/src/concurrency/versioned_state.rs#L134)):*
> ```XML
>             assert_eq!(
>                 value,
>                 self.compiled_contract_classes.read(tx_index + 1, class_hash).is_some()
> ```





_Suggestion:_
```XML
            let is_declared = self.declared_contracts.read(tx_index, class_hash).expect(READ_ERR);
            assert_eq!(
                is_declared,
                self.compiled_contract_classes.read(tx_index + 1, class_hash).is_some()
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @OriStarkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-:-Ny_74aVBZRwrI_-U6Jx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804#-:-NyZnyQx2lh56tayT9Mr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by Yoni-Starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
