### PR TITLE
chore: publish blockifier

### PR DESCRIPTION
**Pull request by aner-starkware**
version = "0.7.0-dev.1"

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1758)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1758)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/native_blockifier/Cargo.toml` line 30 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1758#-NurJVFrCvIoKnvxxy7o:-NurJVFrCvIoKnvxxy7p:bemquc0) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7552051d3864d6b5f444c89433f19fd9e62e14d/crates/native_blockifier/Cargo.toml#L30)):*
> ```TOML
> [dependencies]
> blockifier = { path = "../blockifier", features = ["testing"] }
> cairo-lang-casm = { workspace = true, features = ["parity-scale-codec"] }
> ```

I think you don't need it now

**Comment by aner-starkware** [comment]
Python side: https://reviewable.io/reviews/starkware-industries/starkware/34643

**Comment by aner-starkware** [comment]
*[`crates/native_blockifier/Cargo.toml` line 30 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1758#-NurJVFrCvIoKnvxxy7o:-NurKwc42XyhRTpPnw7g:b-udymgy) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7552051d3864d6b5f444c89433f19fd9e62e14d/crates/native_blockifier/Cargo.toml#L30)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think you don't need it now
</blockquote></details>

Should I delete it?

**Comment by aner-starkware** [comment]
*[`crates/native_blockifier/Cargo.toml` line 30 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1758#-NurJVFrCvIoKnvxxy7o:-NurMVvb3tcLaQfbiO7L:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7552051d3864d6b5f444c89433f19fd9e62e14d/crates/native_blockifier/Cargo.toml#L30)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Should I delete it?
</blockquote></details>

Done.

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1758#-:-NurNcZTC5RtkXhKjGTO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by yair-starkware — COMMENTED** [review]
Didn't mean to approve, needs someone from blockifier

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1758#-:-NurNgXX7K-s7A_wB83r:b5hqtw9)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Comment by aner-starkware** [comment]
Need to wait for Hodor to pass anyways...

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1758#-:-Nus-hLrAfIRFh-BWl5Q:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
