### PR TITLE
fix: add strict_subtract_mappings

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1632)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1632)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 496 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-NsMiSzHDLMLXbrkF3Pj:-NsMiSzHDLMLXbrkF3Pk:bq3i71e) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac28853575db7a332d6b866a3ad0d3746e4a46c3/crates/blockifier/src/state/cached_state.rs#L496)):*
> ```XML
> 
>     // strict_subtract_mappings is not fit for this case, as the keys of compiled_class_hash_writes
>     // are not a subset of the keys of compiled_class_hash_initial_values.
> ```

I think it can be a fit (it is indeed a different case, since it is a write once mapping).
Try to think why updating the initial values failed the tests (what value do we use for`compiled_class_hash`?).



_Code quote:_
```XML
    // strict_subtract_mappings is not fit for this case, as the keys of compiled_class_hash_writes
    // are not a subset of the keys of compiled_class_hash_initial_values.
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1632)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 496 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-NsMiSzHDLMLXbrkF3Pj:-NslYGwA8dOLFLdZWwCq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac28853575db7a332d6b866a3ad0d3746e4a46c3/crates/blockifier/src/state/cached_state.rs#L496)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it can be a fit (it is indeed a different case, since it is a write once mapping).
Try to think why updating the initial values failed the tests (what value do we use for`compiled_class_hash`?).
</blockquote></details>

Done.

**Comment by meship-starkware** [comment]
*[`crates/blockifier/src/state/cached_state.rs` line 155 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-NsrveRi9o8tjICXDShw:-NuIWozT5Fylx6aCNYD_:bc74std) ([raw file](https://github.com/starkware-libs/blockifier/blob/b9fcc177ff2680fca40fba062adf08abd084ef70/crates/blockifier/src/state/cached_state.rs#L155)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it won't work after all :( See [here](https://github.com/starkware-libs/blockifier/blob/ea76ae9b3ecac4f1f00d4c324e20c36deaabb0fc/crates/native_blockifier/src/state_readers/papyrus_state.rs#L115-L117).
So we may need to use the non-strict subtraction for this field.
</blockquote></details>

I am not sure I completely understand why this is problematic. Does this function also get papyrus state? if that's the case should I use non-strict subtraction with a todo? or just a comment to say why it is not used?

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1632)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-Nsrfy6T4Knca-JemqwT:-NuJk35i4kJx5DJhO7zc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b9fcc177ff2680fca40fba062adf08abd084ef70/crates/blockifier/src/state/cached_state.rs#L152)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1150 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-NsreA-m6QC4P6j2P2b4:-NuJkAlMDKpSsPlotC1g:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b9fcc177ff2680fca40fba062adf08abd084ef70/crates/blockifier/src/transaction/transactions_test.rs#L1150)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain this line?
Consider editing the declare tx args.
</blockquote></details>

Done.

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1632)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/utils.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-Nv0jxiKCVbr1uRHy5_T:-Nv0jxiLABn2I1DMPevy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d28eed066b0ef4cb0007efdd6bd44d6cd0e7e3/crates/blockifier/src/utils.rs#L8)):*
> ```XML
> #[path = "utils_test.rs"]
> pub mod test;
> pub const STRICT_SUBTRACT_MAPPING_ERROR: &str = "lhs keys are not a subset of rhs keys";
> ```





_Suggestion:_
```XML

pub const STRICT_SUBTRACT_MAPPING_ERROR: &str = "lhs keys are not a subset of rhs keys";
```
___
*[`crates/blockifier/src/utils.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-Nv0jJqR3XlmnVDzq4r0:-Nv0jJqR3XlmnVDzq4r1:b-h5092r) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d28eed066b0ef4cb0007efdd6bd44d6cd0e7e3/crates/blockifier/src/utils.rs#L18)):*
> ```XML
> {
>     lhs.iter().filter(|(k, v)| rhs.get(k) != Some(v)).map(|(k, v)| (k.clone(), v.clone())).collect()
> }
> ```

WDYT?
Same below + in the error above.



_Suggestion:_
```XML
/// Returns a `HashMap` containing key-value pairs from the source mapping that are not included in the subtract mapping (if
/// a key appears in the subtract mapping with a different value, it will be part of the output).
/// Usage: Get updated items from a mapping.
pub fn subtract_mappings<K, V>(source: &HashMap<K, V>, subtract: &HashMap<K, V>) -> HashMap<K, V>
where
    K: Clone + Eq + std::hash::Hash,
    V: Clone + PartialEq,
{
    lhs.iter().filter(|(k, v)| rhs.get(k) != Some(v)).map(|(k, v)| (k.clone(), v.clone())).collect()
}
```
___
*[`crates/blockifier/src/utils_test.rs` line 46 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-Nv0gVoA4X1QVCD-hu-0:-Nv0gVoA4X1QVCD-hu-1:b-2uc5ym) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d28eed066b0ef4cb0007efdd6bd44d6cd0e7e3/crates/blockifier/src/utils_test.rs#L46)):*
> ```XML
>     );
> 
>     let map1 = HashMap::from([("Yellow", 5), ("green", 2), ("blue", 3)]);
> ```

Same below.



_Suggestion:_
```XML
    let map1 = HashMap::from([("yellow", 5), ("green", 2), ("blue", 3)]);
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 499 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-Nv0gp654iIK4dC6kmD8:-Nv0gp654iIK4dC6kmD9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d28eed066b0ef4cb0007efdd6bd44d6cd0e7e3/crates/blockifier/src/state/cached_state.rs#L499)):*
> ```XML
>         // function. Therefore, we cannot write the class hash. Hence,
>         // compiled_class_hash_writes keys cannot be a subset of
>         // compiled_class_hash_initial_values keys
> ```





_Suggestion:_
```XML
        // This is not a strict subtraction, as Papyrus does not support the `get_compiled_class_hash`
        // method. When declaring a Cairo 1 class we update the writes mapping but cannot update the reads mapping.
        // As a result, the compiled class hash writes keys are not a subset of compiled class hash initial values keys.
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1632)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/utils.rs` line 10 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-Nv1UW-652t9rzBa3QE2:-Nv1UW-652t9rzBa3QE3:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f1024a56f00ec0dbe8f0a7e99d0338fe12a89c55/crates/blockifier/src/utils.rs#L10)):*
> ```XML
> 
> pub const STRICT_SUBTRACT_MAPPING_ERROR: &str =
>     "the source mapping keys are not a subset of the subtract mapping keys";
> ```





_Suggestion:_
```XML
    "The source mapping keys are not a subset of the subtract mapping keys";
```
___
*[`crates/blockifier/src/utils.rs` line 12 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-Nv1USps1Ckc17dlGLap:-Nv1USps1Ckc17dlGLaq:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f1024a56f00ec0dbe8f0a7e99d0338fe12a89c55/crates/blockifier/src/utils.rs#L12)):*
> ```XML
>     "the source mapping keys are not a subset of the subtract mapping keys";
> /// Returns a `HashMap` containing key-value pairs from the source mapping  that are not included in
> /// the subtract mapping  (if a key appears in the subtract mapping  with a different value, it will
> ```





_Suggestion:_
```XML
/// the subtract mapping (if a key appears in the subtract mapping  with a different value, it will
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1632#-:-Nv2BiF87CVDgcScLV7s:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
