### PR TITLE
Temporarily adding DataAvailabilityMode enum until bumping starknet_a…

### PR DESCRIPTION
**Pull request by barak-b-starkware**
…pi crate version so we can use it from there.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/841)

### CODE REVIEW

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/841)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/state/state_api.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/841#-NcSAgg692iV106f0ZZy:-NcSU0bf9Qn6g5XsBzR8:b-4z4rs3) ([raw file](https://github.com/starkware-libs/blockifier/blob/42e4e3e24e9b4c387765b95dd545f9b987b42245/crates/blockifier/src/state/state_api.rs#L14)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I don't think that you want it as a doc string (correct me if I'm wrong).
</blockquote></details>

Done.
Right (: I didn't understand the difference between 2 and 3 `/`
___
*[`crates/blockifier/src/state/state_api.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/841#-NcSAuv92S_xs4KxnUjb:-NcSWs_f2gsHW1w-FpTH:bu6xs77) ([raw file](https://github.com/starkware-libs/blockifier/blob/42e4e3e24e9b4c387765b95dd545f9b987b42245/crates/blockifier/src/state/state_api.rs#L17)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do you need all these derivations? Can you please alphabetize?
</blockquote></details>

Done. Removed.
I’ve added them because I remember that they were added in the past when `StorageDomain` enum was defined (it’s reverted). But then it was necessary as part of the `TransactionParametersV3` or something like this.
It’s better to remove it and, when needed, add it (: Thanks!

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/841)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/841#-NcSm-e82t2zXOVCsaZw:-NcSm-e82t2zXOVCsaZx:b-dvk5ct) ([raw file](https://github.com/starkware-libs/blockifier/blob/a4768abb870839db7567347af9cf79adb18c8153/crates/blockifier/src/execution/syscalls/hint_processor.rs#L82)):*
> ```XML
> 
> // Needed to convert the syscall output to an enum variant.
> impl TryFrom<StarkFelt> for DataAvailabilityMode {
> ```

I’m not sure about this `impl`, and I have some questions:
1. Would you choose another trait to implement to get this behavior?
2. When we’ll move the enum to the starknet_api repo, I would like to leave the `impl` block in the blockifier repo since those are inner details (how we convert the syscall output into this enum), so I placed it in the `hint_processor` file, WDYT?
3. I didn’t use the `match` mechanism and preferred the `if...else...` here. I had difficulty using variables in the `match` arms. Is this the right way to handle it?
4. The creation of the `zero` and `one` seems to be an overkill, but I'm not familiar with any other way to do that. I saw that the `one` is implemented in the starknet_api repo but is still unavailable in the blockifier repo. WDYT?
5. What about the use of `unwrap`? I remember it's an issue. What is our policy?

**Review by barak-b-starkware — COMMENTED** [review]
Yes, no more `StorageDomain` enum, from now its `DataAvailabilityMode`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/841#-:-NcSskaCElOezhK00jLM:bmtx3lg)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/841#-NcSm-e82t2zXOVCsaZw:-NcSrR_P9n3he0wiXgbB:b-au375u) ([raw file](https://github.com/starkware-libs/blockifier/blob/a4768abb870839db7567347af9cf79adb18c8153/crates/blockifier/src/execution/syscalls/hint_processor.rs#L82)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I’m not sure about this `impl`, and I have some questions:
1. Would you choose another trait to implement to get this behavior?
2. When we’ll move the enum to the starknet_api repo, I would like to leave the `impl` block in the blockifier repo since those are inner details (how we convert the syscall output into this enum), so I placed it in the `hint_processor` file, WDYT?
3. I didn’t use the `match` mechanism and preferred the `if...else...` here. I had difficulty using variables in the `match` arms. Is this the right way to handle it?
4. The creation of the `zero` and `one` seems to be an overkill, but I'm not familiar with any other way to do that. I saw that the `one` is implemented in the starknet_api repo but is still unavailable in the blockifier repo. WDYT?
5. What about the use of `unwrap`? I remember it's an issue. What is our policy?
</blockquote></details>

Moved to another file `mod.rs` and to another PR:
https://reviewable.io/reviews/starkware-libs/blockifier/845

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/841)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/state/state_api.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/841#-NcSAgg692iV106f0ZZy:-NcVtjAM0C9iXUMD-c2o:b4xguqr) ([raw file](https://github.com/starkware-libs/blockifier/blob/42e4e3e24e9b4c387765b95dd545f9b987b42245/crates/blockifier/src/state/state_api.rs#L14)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
Right (: I didn't understand the difference between 2 and 3 `/`
</blockquote></details>

Maybe write it as a TODO?
___
*[`crates/blockifier/src/state/state_api.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/841#-NcSAuv92S_xs4KxnUjb:-NcVto5dBiDGzEAgHVaw:bb6bd2v) ([raw file](https://github.com/starkware-libs/blockifier/blob/42e4e3e24e9b4c387765b95dd545f9b987b42245/crates/blockifier/src/state/state_api.rs#L17)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done. Removed.
I’ve added them because I remember that they were added in the past when `StorageDomain` enum was defined (it’s reverted). But then it was necessary as part of the `TransactionParametersV3` or something like this.
It’s better to remove it and, when needed, add it (: Thanks!
</blockquote></details>

I would leave the `Default`one :)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/841)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/state/state_api.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/841#-NcSAuv92S_xs4KxnUjb:-NcX2XCUBqRiCdEVZnN8:bffwwnz) ([raw file](https://github.com/starkware-libs/blockifier/blob/42e4e3e24e9b4c387765b95dd545f9b987b42245/crates/blockifier/src/state/state_api.rs#L17)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I want to document here what we’ve discussed:
1. The natural choice in this specific time for the default value is `L1`. However, it’s not a must to be the case 6 months or two years from now.
2. The `Default` derivation might be useful in tests: For structs that will use this enum and will derive `Default`.
Right now we decide to leave it w/o the `Default` derivation and it might be considered in the future again.
</blockquote></details>

Adding to that: in the near future we would like to have a default value, no? The users will not pass the data availability mode.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/841)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/841)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/state/state_api.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/841#-NcSAuv92S_xs4KxnUjb:-NcXDaRU8vdd190Bty6o:bl40ino) ([raw file](https://github.com/starkware-libs/blockifier/blob/42e4e3e24e9b4c387765b95dd545f9b987b42245/crates/blockifier/src/state/state_api.rs#L17)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Adding to that: in the near future we would like to have a default value, no? The users will not pass the data availability mode.
</blockquote></details>

Discussed.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/841)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
