### PR TITLE
Correctly calculating the state changes regarding balance changes.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
Don't forget python :)

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712#-:-NZdkIgA-5b6WYbUXlEa:b-e27x63)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZdl5kU7bUTHnv39kip:-NZdl5kU7bUTHnv39kiq:bl5mdn0) ([raw file](https://github.com/starkware-libs/blockifier/blob/76f6447414585ee7de56e9799abc13bc0eec53d8/crates/blockifier/src/state/cached_state.rs#L61)):*
> ```XML
>             // calculating the storage updates done in the fee transfer.
>             let (low_key, _high_key) = get_erc20_balance_var_addresses(&sender_address)?;
>             storage_updates.remove(&(sender_address, low_key));
> ```

`remove` is okay with nonexistent keys, right?

and let’s do a manual check for this PR



_Suggestion:_
```XML
            let (low_key, _high_key) = get_erc20_balance_var_addresses(&sender_address)?;
            storage_updates.remove(&(fee_token_address, low_key));
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZdkTiN64PuRUGcXwut:-NZdkTiN64PuRUGcXwuu:b-yibc4s) ([raw file](https://github.com/starkware-libs/blockifier/blob/76f6447414585ee7de56e9799abc13bc0eec53d8/crates/blockifier/src/state/cached_state.rs#L74)):*
> ```XML
>         modified_contracts.extend(nonce_updates.keys());
> 
>         // We exclude the ERC20 contract modification since it’s charged once throughout the batch.
> ```

ERC20 is a type, not **the** fee contract.



_Suggestion:_
```XML
the fee token contrac
```

**Review by noaov1 — COMMENTED** [review]
Sure :)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712#-:-NZdxT5f-ezjr5_U5CqH:bwf0ggl)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZdl5kU7bUTHnv39kip:-NZdxXnW3k-9R1oWP356:b8h99dl) ([raw file](https://github.com/starkware-libs/blockifier/blob/76f6447414585ee7de56e9799abc13bc0eec53d8/crates/blockifier/src/state/cached_state.rs#L61)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`remove` is okay with nonexistent keys, right?

and let’s do a manual check for this PR
</blockquote></details>

Right.
Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZdkTiN64PuRUGcXwut:-NZeDkrs9kV-w1P8KeuQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/76f6447414585ee7de56e9799abc13bc0eec53d8/crates/blockifier/src/state/cached_state.rs#L74)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

ERC20 is a type, not **the** fee contract.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZeUwbPBcKZQC3Q-6Bl:-NZeUwbPBcKZQC3Q-6Bm:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/adc71749de25aa2eb233ff4b010d409c2a909149/crates/blockifier/src/state/cached_state.rs#L75)):*
> ```XML
> 
>         // We exclude the fee token contract modification since it’s charged once throughout the
>         // batch.
> ```





_Suggestion:_
```XML
        // Exclude the fee token contract modification since it’s charged once throughout the
        // block.
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZeVl3VENJgfYZnQT3K:-NZeVl3VENJgfYZnQT3L:b9jn0h) ([raw file](https://github.com/starkware-libs/blockifier/blob/adc71749de25aa2eb233ff4b010d409c2a909149/crates/blockifier/src/state/cached_state_test.rs#L277)):*
> ```XML
>     // As the second access:
>     state.set_storage_at(contract_address, key, storage_val);
> ```

Please pass a non-default sender address, and make sure both addresses aren't there when asking the cached state for storage changes.
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZeW8tx15WUCYy8DK3V:-NZeW8tx15WUCYy8DK3W:b-bhtmn) ([raw file](https://github.com/starkware-libs/blockifier/blob/adc71749de25aa2eb233ff4b010d409c2a909149/crates/blockifier/src/transaction/transaction_utils.rs#L2)):*
> ```XML
> use std::collections::HashMap;
> ```

Can you explain the change in this file?
How is it related to the balance and fee token change?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZeVl3VENJgfYZnQT3K:-NZeiF9p4MwzFmODoodm:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/adc71749de25aa2eb233ff4b010d409c2a909149/crates/blockifier/src/state/cached_state_test.rs#L277)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please pass a non-default sender address, and make sure both addresses aren't there when asking the cached state for storage changes.
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZeW8tx15WUCYy8DK3V:-NZejat0Cy5yWq1e4LVT:b6licfm) ([raw file](https://github.com/starkware-libs/blockifier/blob/adc71749de25aa2eb233ff4b010d409c2a909149/crates/blockifier/src/transaction/transaction_utils.rs#L2)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain the change in this file?
How is it related to the balance and fee token change?
</blockquote></details>

Sure. 
Adding the `fee_token_address` parameter to `calculate_tx_resources` resulted in too many arguments so I separated the function (and the `l1_gas_usage` is not really a resource).

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZf4R8vDDO2CRzB03Pw:-NZf4R8vDDO2CRzB03Px:b-2kxhzt) ([raw file](https://github.com/starkware-libs/blockifier/blob/adc71749de25aa2eb233ff4b010d409c2a909149/crates/blockifier/src/transaction/transaction_utils.rs#L67)):*
> ```XML
>     l1_gas_usage: usize,
>     tx_type: TransactionType,
>     n_reverted_steps: usize,
> ```

@dorimedini-starkware that's not a good solution.
The goal of this function is to estimate OS resources. In particular, the bouncer uses this data as well. 
Reverted steps are not going to affect the OS program.

I suggest adding this cost in `calculate_tx_fee`.
Even some additive cost to the regular one
```
actual_fee + n_reverted_steps * STEP_COST * gas_price
```



_Code quote:_
```XML
n_reverted_steps: usize,
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZeW8tx15WUCYy8DK3V:-NZf9TWG8pUEScTcJnN6:byycb5m) ([raw file](https://github.com/starkware-libs/blockifier/blob/adc71749de25aa2eb233ff4b010d409c2a909149/crates/blockifier/src/transaction/transaction_utils.rs#L2)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Sure. 
Adding the `fee_token_address` parameter to `calculate_tx_resources` resulted in too many arguments so I separated the function (and the `l1_gas_usage` is not really a resource).
</blockquote></details>

How about making this a method of `Transaction`?
It'll receive `BlockContext` for the fee token address, take the sender address from `self`, and take the L1 message payload only in the `L1Handler` implementation.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @noaov1, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZf4R8vDDO2CRzB03Pw:-NZfDZ1k8cwwTco70HAQ:bmb129f) ([raw file](https://github.com/starkware-libs/blockifier/blob/adc71749de25aa2eb233ff4b010d409c2a909149/crates/blockifier/src/transaction/transaction_utils.rs#L67)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@dorimedini-starkware that's not a good solution.
The goal of this function is to estimate OS resources. In particular, the bouncer uses this data as well. 
Reverted steps are not going to affect the OS program.

I suggest adding this cost in `calculate_tx_fee`.
Even some additive cost to the regular one
```
actual_fee + n_reverted_steps * STEP_COST * gas_price
```
</blockquote></details>

@zuphitf

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, @Yoni-Starkware, and @zuphitf)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZeW8tx15WUCYy8DK3V:-NZfJGx0EHll4Opw3mRg:bs1imgj) ([raw file](https://github.com/starkware-libs/blockifier/blob/adc71749de25aa2eb233ff4b010d409c2a909149/crates/blockifier/src/transaction/transaction_utils.rs#L2)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How about making this a method of `Transaction`?
It'll receive `BlockContext` for the fee token address, take the sender address from `self`, and take the L1 message payload only in the `L1Handler` implementation.
</blockquote></details>

Sure. I'll do it in a separate PR.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/state/cached_state.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZpsZhWAeakP5Qx8IoM:-NZpsZhWAeakP5Qx8IoN:belu8dq) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/state/cached_state.rs#L48)):*
> ```XML
>     /// For each contract instance (address) we have three attributes: (class hash, nonce, storage
>     /// root); the state updates correspond to them.
>     pub fn count_actual_state_changes(
> ```

I think it isn't elegant to "lie" about the actual changes done as a result of acting on the state. Why not do the exclusion in the fee flow (it's only done for that purpose)?



_Code quote:_
```XML
count_actual_state_changes
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZpqtsUAboLShTORoAF:-NZpqtsUAboLShTORoAG:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/transaction/transaction_utils.rs#L76)):*
> ```XML
>     // Each instance requires approximately 10 steps in the OS.
>     // TODO(Noa, 01/07/23): Verify the removal of the segmen_arena builtin.
>     let n_steps = total_vm_usage.n_steps
> ```





_Suggestion:_
```XML
    // The segment arena" builtin is not part of SHAR (not in any proof layout).
    // Each instance requires approximately 10 steps in the OS.
    // TODO(Noa, 01/07/23): Verify the removal of the segmen_arena builtin.
    let n_steps = total_vm_usage.n_steps
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 830 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZps9qa2ZVgR4mTifHL:-NZps9qa2ZVgR4mTifHM:b516rt) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/transaction/transactions_test.rs#L830)):*
> ```XML
>         state_changes,
>         StateChanges {
>             n_storage_updates: 2, // For the recipient and the sequencer balance update (only).
> ```

Are we planning to remove this as well?
Add to the comment that the sender's address is excluded.



_Code quote:_
```XML
sequencer balance update
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/state/cached_state.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZpsZhWAeakP5Qx8IoM:-NZyVJo2BM_3hsVdPC-A:b-xl0q53) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/state/cached_state.rs#L48)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it isn't elegant to "lie" about the actual changes done as a result of acting on the state. Why not do the exclusion in the fee flow (it's only done for that purpose)?
</blockquote></details>

It is currently used only to calculate the tx resources (which later be used to calculate the fee). I can move it to `calculate_tx_resources` which will make more sense, given it is in a context of a transaction. WDYT?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 830 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZps9qa2ZVgR4mTifHL:-NZyWUdrBvkWDTg413X-:b6pxv2j) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/transaction/transactions_test.rs#L830)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are we planning to remove this as well?
Add to the comment that the sender's address is excluded.
</blockquote></details>

It appears here since I run it on the state after the fee transfer already occurred (usually we run it before). I'll add a comment.

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/state/cached_state.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZpsZhWAeakP5Qx8IoM:-NZyX24N92OeplwGa0CG:b-9x2r7d) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/state/cached_state.rs#L48)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It is currently used only to calculate the tx resources (which later be used to calculate the fee). I can move it to `calculate_tx_resources` which will make more sense, given it is in a context of a transaction. WDYT?
</blockquote></details>

Maybe, instead of `storage_updates.remove(&(fee_token_address, low_key));`
you can `storage_updates.add(&(fee_token_address, low_key));` and drop the `+1` constant.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/state/cached_state.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZpsZhWAeakP5Qx8IoM:-NZyXkyvDz5Y9LG8BIs_:bo7cbjs) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/state/cached_state.rs#L48)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Maybe, instead of `storage_updates.remove(&(fee_token_address, low_key));`
you can `storage_updates.add(&(fee_token_address, low_key));` and drop the `+1` constant.

</blockquote></details>

Sure, sounds good. I'll still remove the fee token address though.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/state/cached_state.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZpsZhWAeakP5Qx8IoM:-NZycDDnAs6VnTjl-TI0:b1dd4hp) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/state/cached_state.rs#L48)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Sure, sounds good. I'll still remove the fee token address though.
</blockquote></details>

(from the modified contracts)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 830 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZps9qa2ZVgR4mTifHL:-NZyoXdI-d4TaYJyeP-u:bom0j39) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/transaction/transactions_test.rs#L830)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It appears here since I run it on the state after the fee transfer already occurred (usually we run it before). I'll add a comment. 
</blockquote></details>

Also write in the TODO that when we have the separation of validation + execution from fee, you can use it here.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 830 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZps9qa2ZVgR4mTifHL:-NZysSDz7VpEAQaeMSSc:be9hvl0) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/transaction/transactions_test.rs#L830)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Also write in the TODO that when we have the separation of validation + execution from fee, you can use it here.
</blockquote></details>

Changed the test.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/state/cached_state.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZpsZhWAeakP5Qx8IoM:-NZzF5tcCMpw9ej3IIi3:buu4eex) ([raw file](https://github.com/starkware-libs/blockifier/blob/544927ba7393a1dcb1bd612909442d96e0e9468f/crates/blockifier/src/state/cached_state.rs#L48)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

(from the modified contracts)
</blockquote></details>

I added a suffix `for_fee_charge` which implies that this method count the state updates performed after the `__validate__` and `__execute___` (and before the fee transfer).

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712#-:-NZzcLo75hGPqVi9oD5k:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r6, 3 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712#-:-N_0SLgM69TJc66VnMbl:bnfp4nl)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul and @zuphitf)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Review by elintul — DISMISSED** [review]
> Reviewed 2 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/712#-NZf4R8vDDO2CRzB03Pw:-N_869wm8moULYege7lt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/adc71749de25aa2eb233ff4b010d409c2a909149/crates/blockifier/src/transaction/transaction_utils.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@zuphitf 
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/712)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Pull request merged**
