### PR TITLE
Dori/merge 0.12.0 into main 3

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/647)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 6 of 6 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/647)* status: 6 of 30 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @liorgold2)

___
*[`crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json` line 368 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/647#-NYhYXFv8WS_DLg0wwDT:-NYhYXFwASAOf13K7SnP:b-qkdgiu) ([raw file](https://github.com/starkware-libs/blockifier/blob/21496cbe34df545f00d01d6db6b6ba77c37e3a8e/crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json#L368)):*
> ```JSON
>             {
>                 "offset": 890,
> =======
> ```

Why did you chose `HEAD` over `origin/main-v0.12.0`?



_Code quote:_
```JSON
<<<<<<< HEAD
                "offset": 849,
                "selector": "0x1143aa89c8e3ebf8ed14df2a3606c1cd2dd513fac8040b0f8ab441f5c52fe4"
            },
            {
                "offset": 890,
=======
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 706 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/647#-NYhZWJuBfh2IyAzMta9:-NYhZWJv9FxOXh79o-fX:b-d16jzb) ([raw file](https://github.com/starkware-libs/blockifier/blob/21496cbe34df545f00d01d6db6b6ba77c37e3a8e/crates/blockifier/src/transaction/transactions_test.rs#L706)):*
> ```XML
> <<<<<<< HEAD
> =======
> fn create_account_tx_for_validate_test(
> ```

Note to self: Moved to `tets_utils.rs`
Because you will be using it in another file?



_Code quote:_
```XML
create_account_tx_for_validate_test
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/647)* status: 6 of 30 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json` line 368 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/647#-NYhYXFv8WS_DLg0wwDT:-NYlBuOmDxTHi-Wp3DRo:b-vss9l7) ([raw file](https://github.com/starkware-libs/blockifier/blob/21496cbe34df545f00d01d6db6b6ba77c37e3a8e/crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json#L368)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you chose `HEAD` over `origin/main-v0.12.0`?
</blockquote></details>

I chose HEAD and then ran
```
FIX_FEATURE_TEST=1 cargo test -- --ignored
```
this was the result
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 706 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/647#-NYhZWJuBfh2IyAzMta9:-NYlC97gE4Yit4KJDhtw:bmymp7r) ([raw file](https://github.com/starkware-libs/blockifier/blob/21496cbe34df545f00d01d6db6b6ba77c37e3a8e/crates/blockifier/src/transaction/transactions_test.rs#L706)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note to self: Moved to `tets_utils.rs`
Because you will be using it in another file?
</blockquote></details>

this file didn't change in the conflict resolution commit (no conflicts); so it shouldn't come up here. but yes, it is used in transaction_test and in account_transaction_test (or will be used there, [see this PR](https://reviewable.io/reviews/starkware-libs/blockifier/577))

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/647#-:-NYlz1rd5OaIsYf2Wtqd:bnfp4nl)* status: 6 of 30 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @liorgold2)

___
*[`crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json` line 368 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/647#-NYhYXFv8WS_DLg0wwDT:-NYltXXS2SeQiKUVex2Q:bsz9ysm) ([raw file](https://github.com/starkware-libs/blockifier/blob/21496cbe34df545f00d01d6db6b6ba77c37e3a8e/crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json#L368)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I chose HEAD and then ran
```
FIX_FEATURE_TEST=1 cargo test -- --ignored
```
this was the result
</blockquote></details>

Oh, right, since you added the function `write_and_revert`.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/647)* status: 6 of 30 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json` line 368 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/647#-NYhYXFv8WS_DLg0wwDT:-NYm0qIuAANms8lC3jyZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/21496cbe34df545f00d01d6db6b6ba77c37e3a8e/crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json#L368)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh, right, since you added the function `write_and_revert`.
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r13, 23 of 29 files at r19, 3 of 6 files at r20.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/647)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @noaov1)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
