### PR TITLE
feat(execution): implement a versioned client state data structure fo…

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…r implementing concurrency

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_E2RyBC49eX6fnzo2:-Nr_E2RyBC49eX6fnzo3:b73q3ml) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state.rs#L29)):*
> ```XML
>     Read,
>     Write,
> }
> ```

Can we merge this into a single enum?
Something like:
```rust
enum StateRequest {
  GetNonceAt { contract_address: ContractAddress },
  SetNonceAt { contract_address: ContractAddress, nonce: Nonce }.
  GetStorageAt {...
  ...
}
```

Would that be better? :thinking: 



_Code quote:_
```XML
enum Arg {
    ContractAddress(ContractAddress),
    StorageKey(StorageKey),
    ClassHash(ClassHash),
    Version(Version),
    StarkFelt(StarkFelt),
    Nonce(Nonce),
    CompiledClassHash(CompiledClassHash),
}

#[derive(Debug, Clone, Copy)]
enum AccessType {
    Read,
    Write,
}
```
___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_68ke52vc-20j4v4O:-Nr_68ke52vc-20j4v4P:b-7h7bn7) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state.rs#L38)):*
> ```XML
>         }
>     }
> }
> ```

also in the other Display below



_Suggestion:_
```XML
#[derive(Debug, derive_more::Display, Clone, Copy)]
enum AccessType {
    Read,
    Write,
}
```
___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_6ordDv77DmsXPiji:-Nr_6ordDv77DmsXPijj:b9geopo) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state.rs#L80)):*
> ```XML
>         key: StorageKey,
>     ) -> StateResult<StarkFelt> {
>         self.send_request::<StarkFelt>(
> ```

Would this work?



_Suggestion:_
```XML
  self.send_request(
```
___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_FHS_3FfE36q3lo2F:-Nr_FHSa6VsEaPF5IYoP:b-et50y5) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state.rs#L234)):*
> ```XML
>                 Arg::Version(self.version),
>                 Arg::CompiledClassHash(compiled_class_hash),
>             ],
> ```

I have a feeling that there is an abstraction hiding here (similar to the struct i posted in an earlier comment).
Do we have to pass the args as an array like this? :thinking: 



_Code quote:_
```XML
            AccessType::Write,
            StorageType::CompiledClassHash,
            &[
                Arg::ClassHash(class_hash),
                Arg::Version(self.version),
                Arg::CompiledClassHash(compiled_class_hash),
            ],
```
___
*[`crates/blockifier/src/concurrency/versioned_client_state_test.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_85Zn1bX4arST1SB4:-Nr_85Zn1bX4arST1SB5:bomwm0i) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state_test.rs#L11)):*
> ```XML
> 
> #[test]
> fn test_versioned_client_state() {
> ```

add comments to the state, so its clear what interaction you're simulating
___
*[`crates/blockifier/src/concurrency/versioned_client_state_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_7nO07GTKBAnSaPby:-Nr_7nO07GTKBAnSaPbz:bakmc72) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state_test.rs#L16)):*
> ```XML
> 
>     let versioned_client_1_state =
>         VersionedClientState::new(client_1_to_manager_sender, manager_to_client_1_receiver, 1);
> ```

Already said this in a separate PR, and still might be out of scope, but i wish there was a better way over passing the version as a free arg everywhere :(



_Code quote:_
```XML
    let versioned_client_1_state =
        VersionedClientState::new(client_1_to_manager_sender, manager_to_client_1_receiver, 1);
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-NrphH2gCUwUZur0bRxi:-NrphH2gCUwUZur0bRxj:bi9rfc6) (no related file):*
Please wait on reviewing this PR for now.
I have scheduled a design review, and we will discuss accessing the versioned state. Accordingly, I will update this PR.

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-NrphH2gCUwUZur0bRxi:-NsOpcmP2sCNR5HtNIWA:b-bu91xm) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please wait on reviewing this PR for now.
I have scheduled a design review, and we will discuss accessing the versioned state. Accordingly, I will update this PR.
</blockquote></details>

Updated

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nsbc7ef4Lf9x2Vdqq0M:-Nsbc7ef4Lf9x2Vdqq0N:bgtds71) (no related file):*
@giladchase, After the design review we had a week ago, I've replaced the channel implementation with mutexes. Thus, the comments you provided below are no longer relevant.

___
___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_E2RyBC49eX6fnzo2:-Nsbd-fRCRsTgxNnqmhN:bpwwwlj) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state.rs#L29)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can we merge this into a single enum?
Something like:
```rust
enum StateRequest {
  GetNonceAt { contract_address: ContractAddress },
  SetNonceAt { contract_address: ContractAddress, nonce: Nonce }.
  GetStorageAt {...
  ...
}
```

Would that be better? :thinking:
</blockquote></details>

This code was changed.
___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_68ke52vc-20j4v4O:-NsbcxvyAT2A7lF7LbmD:bpwwwlj) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state.rs#L38)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

also in the other Display below
</blockquote></details>

This code was changed.
___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_6ordDv77DmsXPiji:-Nsbd12-6hOK5fRurZ9a:bpwwwlj) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state.rs#L80)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Would this work?
</blockquote></details>

This code was changed.
___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_FHS_3FfE36q3lo2F:-Nsbd6Y39LzoUyt65KA3:bpwwwlj) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state.rs#L234)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I have a feeling that there is an abstraction hiding here (similar to the struct i posted in an earlier comment).
Do we have to pass the args as an array like this? :thinking:
</blockquote></details>

This code was changed.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_client_state_test.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_85Zn1bX4arST1SB4:-NsoA1jjEpnFpLYcGbP9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state_test.rs#L11)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

add comments to the state, so its clear what interaction you're simulating
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nssk95ODYVdu0MgK3ha:-Nssk95ODYVdu0MgK3hb:bwklguf) ([raw file](https://github.com/starkware-libs/blockifier/blob/be0b9c13ef4e976caf308f80580223f6d03eecab/crates/blockifier/src/concurrency/versioned_client_state.rs#L28)):*
> ```XML
>         key: StorageKey,
>     ) -> StateResult<StarkFelt> {
>         self.state.lock().unwrap().get_storage_at(self.version, contract_address, key)
> ```

And define an error message above.
When does this method return an error? Should we panic in that case?



_Suggestion:_
```XML
        self.state.lock().expect(error_message).get_storage_at(self.version, contract_address, key)
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_client_state_test.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-NssnG_s3Lmz0FPNVAqg:-NssnG_s3Lmz0FPNVAqh:bcfocin) ([raw file](https://github.com/starkware-libs/blockifier/blob/be0b9c13ef4e976caf308f80580223f6d03eecab/crates/blockifier/src/concurrency/versioned_client_state_test.rs#L29)):*
> ```XML
> use crate::transaction::transactions::ExecutableTransaction;
> 
> pub fn build_client_states(
> ```

Can you use `test_state` instead and avoid this function?
(then you do not need to fund the accounts in the test below).



_Code quote:_
```XML
pub fn build_client_states(
```
___
*[`crates/blockifier/src/concurrency/versioned_client_state_test.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nssn2Fg5_v3-g69zYIX:-Nssn2Fh9Mu1B5LKdpkM:bui0nmh) ([raw file](https://github.com/starkware-libs/blockifier/blob/be0b9c13ef4e976caf308f80580223f6d03eecab/crates/blockifier/src/concurrency/versioned_client_state_test.rs#L158)):*
> ```XML
>         build_client_states(chain_info, &[(account_without_validation, 1), (grindy_account, 1)]);
>     let mut state_1 = CachedState::from(VersionedClientState::new(1, Arc::clone(&versioned_state)));
>     let mut state_2 = CachedState::from(VersionedClientState::new(1, Arc::clone(&versioned_state)));
> ```

We need a new `create_transactional` :)



_Code quote:_
```XML
    let mut state_1 = CachedState::from(VersionedClientState::new(1, Arc::clone(&versioned_state)));
    let mut state_2 = CachedState::from(VersionedClientState::new(1, Arc::clone(&versioned_state)));
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-NswDo4q5NnYw7O6qogw:-NswDo4q5NnYw7O6qogx:b5squyn) ([raw file](https://github.com/starkware-libs/blockifier/blob/be0b9c13ef4e976caf308f80580223f6d03eecab/crates/blockifier/src/concurrency/versioned_client_state.rs#L17)):*
> ```XML
> pub mod test;
> 
> pub struct VersionedClientState<S: StateReader> {
> ```

(also the file name)



_Suggestion:_
```XML
VersionedStateProxy
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-NswDo4q5NnYw7O6qogw:-NswRroCAbKvCHeqZs78:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/be0b9c13ef4e976caf308f80580223f6d03eecab/crates/blockifier/src/concurrency/versioned_client_state.rs#L17)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(also the file name)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_client_state.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nssk95ODYVdu0MgK3ha:-NstF5k3BL-skRepsedM:b-endi6c) ([raw file](https://github.com/starkware-libs/blockifier/blob/be0b9c13ef4e976caf308f80580223f6d03eecab/crates/blockifier/src/concurrency/versioned_client_state.rs#L28)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And define an error message above.
When does this method return an error? Should we panic in that case?
</blockquote></details>

It returns an error if another user panics while holding the mutex and if the current thread is already locking the mutex.
Added error message for this case.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-NswhPmp00Gdl5TFoeqq:-NswhPmp00Gdl5TFoeqr:bqoijvr) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae5abde398e897c409a8db355985688acab59ae1/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L30)):*
> ```XML
>         key: StorageKey,
>     ) -> StateResult<StarkFelt> {
>         self.state.lock().expect(LOCK_ERR_MESSAGE).get_storage_at(
> ```

Can you share this code?



_Code quote:_
```XML
state.lock().expect(LOCK_ERR_MESSAGE)
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nsx2WBh37nTsEl7b9B9:-Nsx2WBh37nTsEl7b9BA:b-xc9ib) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae5abde398e897c409a8db355985688acab59ae1/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L62)):*
> ```XML
> }
> 
> impl<S: StateReader> VersionedStateProxy<S> {
> ```

Plz move in between the struct definition and the impl StateReader.
The struct's impl is always higher than the trait impls, that is, if it exists then it is always directly below the struct def.



_Code quote:_
```XML
impl<S: StateReader> VersionedStateProxy<S> {
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_client_state_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nr_7nO07GTKBAnSaPby:-Nsx7KEa8toQlnI4Q0J-:b-9hcg57) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdf66f938e45194c0f47da0879a56b9adcac4d61/crates/blockifier/src/concurrency/versioned_client_state_test.rs#L16)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Already said this in a separate PR, and still might be out of scope, but i wish there was a better way over passing the version as a free arg everywhere :(
</blockquote></details>

When we apply concurrency execution, each worker will execute a single transaction using the same version id.
The storage access would be through the `StateReader` API, which is not aware of the version.
___
*[`crates/blockifier/src/concurrency/versioned_client_state_test.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nssn2Fg5_v3-g69zYIX:-Nsx8AZsDNX0KKTdGz69:bsyoqic) ([raw file](https://github.com/starkware-libs/blockifier/blob/be0b9c13ef4e976caf308f80580223f6d03eecab/crates/blockifier/src/concurrency/versioned_client_state_test.rs#L158)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We need a new `create_transactional` :)
</blockquote></details>

What would it get as an input argument?
VersionedState or VersionedClient?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-NswhPmp00Gdl5TFoeqq:-Nsx6rzP-Me8QbTWY8si:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae5abde398e897c409a8db355985688acab59ae1/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L30)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you share this code?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-Nsx2WBh37nTsEl7b9B9:-Nsx6r_d5r-q95rN4z9B:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae5abde398e897c409a8db355985688acab59ae1/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L62)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Plz move in between the struct definition and the impl StateReader.
The struct's impl is always higher than the trait impls, that is, if it exists then it is always directly below the struct def.
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 31 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-NsxDGr7BF868ogecgRw:-NsxDGr83q_H12k3hC2G:bxflldi) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a5799cdfe18e5a1c0eaa19f8824038a55cb5882/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L31)):*
> ```XML
>     fn lock_state(&self) -> MutexGuard<'_, VersionedState<S>> {
>         self.state.lock().expect(LOCK_ERR_MESSAGE)
>     }
> ```

No need `LOCK_ERR_MESSAGE` anymore.



_Suggestion:_
```XML
    fn state(&self) -> MutexGuard<'_, VersionedState<S>> {
        self.state.lock().expect("Failed to acquire state lock.")
    }
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-NsxJYHnDcBMUOmtMUAp:-NsxJYHnDcBMUOmtMUAq:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a5799cdfe18e5a1c0eaa19f8824038a55cb5882/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L42)):*
> ```XML
>     // Initialize the versioned state.
>     let mut storage_view = HashMap::new();
>     storage_view.insert((contract_address, key), stark_felt);
> ```





_Suggestion:_
```XML
    let storage_view = HashMap::from([((contract_address, key), stark_felt)]);
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1573)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1573#-NsxcBxU94VLCHhQ2UUT:-NsxcBxU94VLCHhQ2UUU:b-8wrrys) (no related file):*
Following @giladchase suggestion,
I have implemented both the versioned state and versioned state proxy within the same file and included them in the same PR.

PR:
https://reviewable.io/reviews/starkware-libs/blockifier/1528

Thus, I'll close this PR soon.

___

**Pull request closed without merging**
