### PR TITLE
chore: add deploy function to dummy Cairo1 account and recompile with…

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
… 2.6.0

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1848)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1848)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/account_with_dummy_validate.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1848#-NwpIuJx0pN8W5fMvcIy:-NwpIuJx0pN8W5fMvcIz:b-qa2ohj) ([raw file](https://github.com/starkware-libs/blockifier/blob/bfbfc5bc0cc230cc4a625e4a97d7368fdcfdbf48/crates/blockifier/feature_contracts/cairo1/account_with_dummy_validate.cairo#L1)):*
> ```Cairo
> #[starknet::contract(account)]
> ```

required in v2.6.0 compiler (or compiler complains about implementing reserved methods `__validate__` and `__execute__`)



_Code quote:_
```Cairo
(account)
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1848#-:-Nwt1qq328fBUFH4ZwHm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1848)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1848#-:-NwtBp_e9HYBIBriXX8W:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
