### PR TITLE
Updates cache with initial cell values for compiled class hash.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/819)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/819)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/819#-NbJQyM10HPYxjwv64j1:-NbJQyM10HPYxjwv64j2:b-ym11f3) ([raw file](https://github.com/starkware-libs/blockifier/blob/858ec7496826c63497d0ee19999fee3b8968c8e8/crates/blockifier/src/state/cached_state.rs#L124)):*
> ```XML
>             }
>         }
> ```

Can be problematic for `compiled_class_hash = 0`.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/819)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/819#-NbJQyM10HPYxjwv64j1:-NbJVUR-6rUd3ArNM6OM:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/858ec7496826c63497d0ee19999fee3b8968c8e8/crates/blockifier/src/state/cached_state.rs#L124)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can be problematic for `compiled_class_hash = 0`.
</blockquote></details>

Why?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/819)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/819#-NbJQyM10HPYxjwv64j1:-NbJVk4P0_ll45LUBzdh:bww1uqh) ([raw file](https://github.com/starkware-libs/blockifier/blob/858ec7496826c63497d0ee19999fee3b8968c8e8/crates/blockifier/src/state/cached_state.rs#L124)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Because we insert to `cache.compiled_class_hash_initial_values` the pair `(class_hash, 0)` (the default return value of `self.state.get_compiled_class_hash`). When we subtract the two mappings we will get an empty dictionary. (I guess it's also true for python, no?)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/819)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/819#-NbJQyM10HPYxjwv64j1:-NbJlgSb87gfl_kkyF4j:bdahu95) ([raw file](https://github.com/starkware-libs/blockifier/blob/858ec7496826c63497d0ee19999fee3b8968c8e8/crates/blockifier/src/state/cached_state.rs#L124)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Because we insert to `cache.compiled_class_hash_initial_values` the pair `(class_hash, 0)` (the default return value of `self.state.get_compiled_class_hash`). When we subtract the two mappings we will get an empty dictionary. (I guess it's also true for python, no?)
</blockquote></details>

No - `(class_hash, 0) != (class_hash, some_nonzero_value)`

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/819)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/819#-NbJQyM10HPYxjwv64j1:-NbJmXfy5zobT19Ob13Z:b-c0u9jz) ([raw file](https://github.com/starkware-libs/blockifier/blob/858ec7496826c63497d0ee19999fee3b8968c8e8/crates/blockifier/src/state/cached_state.rs#L124)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No - `(class_hash, 0) != (class_hash, some_nonzero_value)`
</blockquote></details>

Yes. I said that it will be problematic if the calculated `compiled_class_hash` equals 0.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/819#-:-NbJvnZ58cg0HJpT6KRl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/819#-NbJQyM10HPYxjwv64j1:-NbJvYHuClmEboBXE3b2:b-z2da5q) ([raw file](https://github.com/starkware-libs/blockifier/blob/858ec7496826c63497d0ee19999fee3b8968c8e8/crates/blockifier/src/state/cached_state.rs#L124)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes. I said that it will be problematic if the calculated `compiled_class_hash` equals 0.
</blockquote></details>

Then we will be in a much bigger problem :)
(that's the indicator for a declared class)

**Pull request merged**
