### PR TITLE
Update default_invoke_tx_args and usages to new infra

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 422 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcApvkCHfEX2TowrGR:-NlcApvkCHfEX2TowrGS:bjjh9o9) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L422)):*
> ```XML
>                 CairoVersion::Cairo0 => 57,
>                 CairoVersion::Cairo1 => 59,
>             },
> ```

@noaov1 I now have to make this change, or the test fails on the Cairo0 case.
This aligns with what I've seen when I tried doing price abstraction.



_Code quote:_
```XML
            n_steps: match account_cairo_version {
                CairoVersion::Cairo0 => 529,
                CairoVersion::Cairo1 => 525,
            },
            n_memory_holes: match account_cairo_version {
                CairoVersion::Cairo0 => 57,
                CairoVersion::Cairo1 => 59,
            },
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 566 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcB4gY0FFlHBw3ykeb:-NlcB4gY0FFlHBw3ykec:b517j1g) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L566)):*
> ```XML
>     // Deploy.
>     let invalid_tx = AccountTransaction::DeployAccount(deploy_account_tx(
>         format!("{}", test_contract.get_class_hash().0).as_str(),
> ```

I added a TODO to change `deploy_account_tx` API, so we won't need to convert this class hash to hex string...



_Code quote:_
```XML
format!("{}", test_contract.get_class_hash().0).as_str()
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 905 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcBEOt8l13080B1EpI:-NlcBEOt8l13080B1EpJ:b-ton0h1) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L905)):*
> ```XML
>         },
>         fee_type,
>         class_hash!(TEST_ERC20_CONTRACT_CLASS_HASH),
> ```

temporary - this test is not using new infra yet, but I added this param to the test util



_Code quote:_
```XML
class_hash!(TEST_ERC20_CONTRACT_CLASS_HASH)
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcMCo53UAtejwzgWuT:-NlcMCo53UAtejwzgWuU:bjdbi7p) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L337)):*
> ```XML
>     test_contract_cairo_version: CairoVersion,
> ) {
>     let block_context = &BlockContext::create_for_account_testing();
> ```

As the code is presented here - `test_contract_cairo_version` is not different between the test cases:
Here is a start for the fix.



_Suggestion:_
```XML
#[test_case(
    ExpectedResultTestInvokeTx{
        range_check: 101,
        n_steps: 4269,
        vm_resources: VmExecutionResources {
            n_steps:  61,
            n_memory_holes:  0,
            builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 1)]),
        },
        validate_gas_consumed: 0,
        execute_gas_consumed: 0,
        inner_call_initial_gas: abi_constants::INITIAL_GAS_COST,
    },
    CairoVersion::Cairo0,
    "With Cairo0 account")]
#[test_case(
    ExpectedResultTestInvokeTx{
        range_check: 113,
        n_steps: 4689,
        vm_resources: VmExecutionResources {
            n_steps: 283,
            n_memory_holes: 1,
            builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 7)]),
        },
        validate_gas_consumed: 14360, // The gas consumption results from parsing the input
            // arguments.
        execute_gas_consumed: 103660,
        inner_call_initial_gas: 9999681980,
    },
    CairoVersion::Cairo1,
    "With Cairo1 account")]
fn test_invoke_tx(
    expected_arguments: ExpectedResultTestInvokeTx,
    account_cairo_version: CairoVersion,
) {
    let test_contract_cairo_version = CairoVersion::Cairo0;
    let block_context = &BlockContext::create_for_account_testing();
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 535 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcNiPu6eyC2NAx4vTS:-NlcNiPu6eyC2NAx4vTT:bs4q9op) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L535)):*
> ```XML
>     test_contract_cairo_version: CairoVersion,
> ) {
>     let block_context = &BlockContext::create_for_account_testing();
> ```

Ditto.



_Suggestion:_
```XML
#[test_case(CairoVersion::Cairo0; "With Cairo0 account")]
#[test_case(CairoVersion::Cairo1; "With Cairo1 account")]
fn test_max_fee_exceeds_balance(
    account_cairo_version: CairoVersion,
) {
    let test_contract_cairo_version = CairoVersion::Cairo0;
    let block_context = &BlockContext::create_for_account_testing();
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcPFS93IIgbH6J2gui:-NlcPFS93IIgbH6J2guj:b-4lcvgl) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L1286)):*
> ```XML
>     // A tx that changes the account and some other balance in execute.
>     let some_other_contract = FeatureContract::FaultyAccount(account_cairo_version);
>     let some_other_account_address = some_other_contract.get_instance_address(0);
> ```

Seems like the Faulty account does not play a role here.



_Suggestion:_
```XML
    let some_other_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
    let some_other_account_address = some_other_contract.get_instance_address(1);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1336 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcPW5JDnyo9hEmxahl:-NlcPW5JDnyo9hEmxahm:b248j9u) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L1336)):*
> ```XML
>     ));
> 
>     let actual_execution_info = account_tx.execute(state, block_context, true, false).unwrap();
> ```

:/ This has more lines than it originally had.

I understand it is because we want to expose the instances of feature contracts - and use the same ones throughout...
But we lose the upside of them being deterministic.



_Code quote:_
```XML
#[test]
fn test_valid_flag() {
    let account_cairo_version = CairoVersion::Cairo1;
    let test_contract_cairo_version = CairoVersion::Cairo0;
    let block_context = &BlockContext::create_for_account_testing();
    let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
    let test_contract = FeatureContract::TestContract(test_contract_cairo_version);
    let state =
        &mut test_state(block_context, BALANCE, &[(account_contract, 1), (test_contract, 1)]);

    let account_tx = account_invoke_tx(default_invoke_tx_args(
        account_contract.get_instance_address(0),
        test_contract.get_instance_address(0),
    ));

    let actual_execution_info = account_tx.execute(state, block_context, true, false).unwrap();
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcMCo53UAtejwzgWuT:-NlcQrdl2i-h6pK1-4ji:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L337)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

As the code is presented here - `test_contract_cairo_version` is not different between the test cases:
Here is a start for the fix.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 535 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcNiPu6eyC2NAx4vTS:-NlcR1wMC35m2pFdKh_X:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L535)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcPFS93IIgbH6J2gui:-NlcROPk2lKtE37xi06r:b-97rkk8) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L1286)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Seems like the Faulty account does not play a role here.
</blockquote></details>

reused existing feature contract to get a dummy address
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1336 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcPW5JDnyo9hEmxahl:-NlcRTJG72xbLrwIDOHy:b-vqjdcg) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L1336)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

:/ This has more lines than it originally had.

I understand it is because we want to expose the instances of feature contracts - and use the same ones throughout...
But we lose the upside of them being deterministic.
</blockquote></details>

yes, but now cairo versions involved are explicit, and you could easily parametrize.
there, done, for free

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 337 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcUVxo3cbbUXba2wbP:-NlcWj-x0NTFNICM7T7U:b-1fbw63) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2983639eb94c9a6d2df978e89da22ed0cc1b2fb/crates/blockifier/src/transaction/transactions_test.rs#L337)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Sorry for not saying earlier.
Also a few more times later.
</blockquote></details>

np
done

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1336 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcPW5JDnyo9hEmxahl:-NlcjHk-Epi0NtMcUbP4:bwhaqwf) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddc0189dc6cce254dfcf71d7028cee3222f3bcaf/crates/blockifier/src/transaction/transactions_test.rs#L1336)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, but now cairo versions involved are explicit, and you could easily parametrize.
there, done, for free
</blockquote></details>

You make design look easy! :crown: 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 532 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcigRqAVWu6lfm4R2W:-NlcigRqAVWu6lfm4R2X:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/836e3135936fb3734f158f1a335b4b15d40e8eb6/crates/blockifier/src/transaction/transactions_test.rs#L532)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing();
>     let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
>     let test_contract = FeatureContract::TestContract(test_contract_cairo_version);
> ```





_Suggestion:_
```XML
    let block_context = &BlockContext::create_for_account_testing();
    let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
    let test_contract = FeatureContract::TestContract(CairoVersion::Cairo0);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 587 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-Nlcile69mJpOTze-gwW:-Nlcile69mJpOTze-gwX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/836e3135936fb3734f158f1a335b4b15d40e8eb6/crates/blockifier/src/transaction/transactions_test.rs#L587)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing();
>     let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
>     let test_contract = FeatureContract::TestContract(test_contract_cairo_version);
> ```





_Suggestion:_
```XML
    let block_context = &BlockContext::create_for_account_testing();
    let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
    let test_contract = FeatureContract::TestContract(CairoVersion::Cairo0);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 666 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlciqjWDe91qh9ImlwQ:-NlciqjWDe91qh9ImlwR:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/836e3135936fb3734f158f1a335b4b15d40e8eb6/crates/blockifier/src/transaction/transactions_test.rs#L666)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing();
>     let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
>     let test_contract = FeatureContract::TestContract(test_contract_cairo_version);
> ```





_Suggestion:_
```XML
#[test_case(CairoVersion::Cairo0; "With Cairo0 account")]
#[test_case(CairoVersion::Cairo1; "With Cairo1 account")]
fn test_actual_fee_gt_resource_bounds(
    account_cairo_version: CairoVersion,
) {
    let block_context = &BlockContext::create_for_account_testing();
    let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
    let test_contract = FeatureContract::TestContract(CairoVersion::Cairo0);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 696 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-Nlcixzh-JGgZZ-BZkyG:-Nlcixzh-JGgZZ-BZkyH:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/836e3135936fb3734f158f1a335b4b15d40e8eb6/crates/blockifier/src/transaction/transactions_test.rs#L696)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing();
>     let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
>     let test_contract = FeatureContract::TestContract(test_contract_cairo_version);
> ```





_Suggestion:_
```XML
#[test_case(CairoVersion::Cairo0; "With Cairo0 account")]
#[test_case(CairoVersion::Cairo1; "With Cairo1 account")]
fn test_invalid_nonce(
    account_cairo_version: CairoVersion,
) {
    let block_context = &BlockContext::create_for_account_testing();
    let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
    let test_contract = FeatureContract::TestContract(CairoVersion::Cairo0);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 532 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcigRqAVWu6lfm4R2W:-NldBLcs-BqH004s2aZD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/836e3135936fb3734f158f1a335b4b15d40e8eb6/crates/blockifier/src/transaction/transactions_test.rs#L532)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing();
>     let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
>     let test_contract = FeatureContract::TestContract(test_contract_cairo_version);
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 587 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-Nlcile69mJpOTze-gwW:-NldB-OpAfq98GGhy0bj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/836e3135936fb3734f158f1a335b4b15d40e8eb6/crates/blockifier/src/transaction/transactions_test.rs#L587)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing();
>     let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
>     let test_contract = FeatureContract::TestContract(test_contract_cairo_version);
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 666 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlciqjWDe91qh9ImlwQ:-NldBBZv5r4ABPn9WfU2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/836e3135936fb3734f158f1a335b4b15d40e8eb6/crates/blockifier/src/transaction/transactions_test.rs#L666)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing();
>     let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
>     let test_contract = FeatureContract::TestContract(test_contract_cairo_version);
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 696 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-Nlcixzh-JGgZZ-BZkyG:-NldBHbt3xc30vUGeVKK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/836e3135936fb3734f158f1a335b4b15d40e8eb6/crates/blockifier/src/transaction/transactions_test.rs#L696)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing();
>     let account_contract = FeatureContract::AccountWithoutValidations(account_cairo_version);
>     let test_contract = FeatureContract::TestContract(test_contract_cairo_version);
> ```

Done.

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 424 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NldD29i7qfMZD8QQTIm:-NldD29i7qfMZD8QQTIn:b-vhokxy) ([raw file](https://github.com/starkware-libs/blockifier/blob/c9693e16d13b9cec86bb4bfba6c916f52503ff92/crates/blockifier/src/transaction/transactions_test.rs#L424)):*
> ```XML
>                 CairoVersion::Cairo0 => 57,
>                 CairoVersion::Cairo1 => 59,
>             },
> ```

@Yoni-Starkware PTAL



_Code quote:_
```XML
        // TODO(Dori, 1/2/2024): The exact resources required in fee transfer depends non-trivially
        //   on the contract address (see `normalize_address` function in `storage.cairo`; the
        //   input is the address hashed with other arguments). Currently we differentiate between
        //   the expected results of the fee transfer call based on the account cairo version, but
        //   this is incorrect.
        VmExecutionResources {
            n_steps: match account_cairo_version {
                CairoVersion::Cairo0 => 529,
                CairoVersion::Cairo1 => 525,
            },
            n_memory_holes: match account_cairo_version {
                CairoVersion::Cairo0 => 57,
                CairoVersion::Cairo1 => 59,
            },
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 424 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NldD29i7qfMZD8QQTIm:-Nlr2gURCgciXGS64cTj:b-ushw2d) ([raw file](https://github.com/starkware-libs/blockifier/blob/c9693e16d13b9cec86bb4bfba6c916f52503ff92/crates/blockifier/src/transaction/transactions_test.rs#L424)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware PTAL
</blockquote></details>

[follow-up PR](https://reviewable.io/reviews/starkware-libs/blockifier/1265) to "solve" this issue

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1260)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Pull request merged**
