### PR TITLE
feat(execution): pass correct bouncer info

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1692)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1692)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1692#-NtRCwP5B6T0r-N02gpC:-NtRCwP5B6T0r-N02gpD:b74v3xt) (no related file):*
cherry-pick of [this](https://reviewable.io/reviews/starkware-libs/blockifier/1577)

___

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1692#-:-NtRHWLl2B4z8V6r8nxE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1692)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1692#-NtRJlkzCr2LouyK-kCZ:-NtROufT8urYZorCyoUw:b-eg6kay) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[waiting for python side](https://reviewable.io/reviews/starkware-industries/starkware/34462)
</blockquote></details>

failed because [this cherry-pick](https://reviewable.io/reviews/starkware-libs/blockifier/1694) still needs to get in...

___

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1692)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Pull request merged**
