### PR TITLE
test(concurrency): test commit tx where the sequencer address is als…

### PR DESCRIPTION
**Pull request by meship-starkware**
…o the sender address

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935)

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-Nz8Ym_5214J48sFJgiN:-Nz8Ym_5214J48sFJgiO:bp2qbwt) ([raw file](https://github.com/starkware-libs/blockifier/blob/bca59bf04b02ba3c8030e31ea4f13cf5a01fd34b/crates/blockifier/src/concurrency/worker_logic_test.rs#L144)):*
> ```XML
> }
> 
> fn check_sequencer_sender_fee_transfer<S: StateReader>(
> ```

Make the name more similar to `validate_fee_transfer` to make it clear that it does the same thing only that the sender is the sequencer.



_Suggestion:_
```XML
fn validate_fee_transfer_when_sender_is_sequencer<S: StateReader>(
```

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-Nz8Ym_5214J48sFJgiN:-NzNRnNs7HgNFQ80Gz8R:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bca59bf04b02ba3c8030e31ea4f13cf5a01fd34b/crates/blockifier/src/concurrency/worker_logic_test.rs#L144)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Make the name more similar to `validate_fee_transfer` to make it clear that it does the same thing only that the sender is the sequencer.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-Nz8ZQPh53VrmAscp7q7:-NzNRntUCfjUjaZbCOZe:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bca59bf04b02ba3c8030e31ea4f13cf5a01fd34b/crates/blockifier/src/concurrency/worker_logic_test.rs#L186)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Add a docstring explaining why we need to check this case specifically. (The thing with skipping the last part of the commit in this case.)
</blockquote></details>

Done.

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-:-NzNTwDaE1UrifYuEiVP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 130 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-NzggUyBBYQEQhiNzLQH:-NzggUyBBYQEQhiNzLQI:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d2c58a0b280d1640e558178f3a85e27f89caf9e/crates/blockifier/src/concurrency/worker_logic_test.rs#L130)):*
> ```XML
>         .unwrap();
> 
>     // Commit tx and check that the commit did not affected the result and state.
> ```





_Suggestion:_
```XML
    // Commit tx and check that the commit made no changes in the execution result or the state.
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 100 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-Nzggvpl7duw9jf6fDQz:-NzggvpmBa4-fdkK_dbF:b-yywukj) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d2c58a0b280d1640e558178f3a85e27f89caf9e/crates/blockifier/src/concurrency/worker_logic_test.rs#L100)):*
> ```XML
>         account_address,
>         nonce_manager.next(account_address),
>     ))];
> ```

If there is only one transaction, there is no need to put it in an array



_Code quote:_
```XML
    let txs = [Transaction::AccountTransaction(trivial_calldata_invoke_tx(
        account_address,
        nonce_manager.next(account_address),
    ))];
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 103 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-NzghKpk8VJC9rUBcfJK:-NzghKpk8VJC9rUBcfJL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d2c58a0b280d1640e558178f3a85e27f89caf9e/crates/blockifier/src/concurrency/worker_logic_test.rs#L103)):*
> ```XML
> 
>     let cached_state =
>         test_state(&block_context.chain_info, BALANCE, &[(account, txs.len().try_into().unwrap())]);
> ```





_Suggestion:_
```XML
    let cached_state =
        test_state(&block_context.chain_info, BALANCE, &[(account, 1)]);
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 100 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-Nzggvpl7duw9jf6fDQz:-NzgsrPTATOJi4rb64M9:bbmrdp) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d2c58a0b280d1640e558178f3a85e27f89caf9e/crates/blockifier/src/concurrency/worker_logic_test.rs#L100)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

If there is only one transaction, there is no need to put it in an array
</blockquote></details>

The worker executer expects a transaction array
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 103 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-NzghKpk8VJC9rUBcfJK:-Nzgt-wp5zxMUs5ht9i-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d2c58a0b280d1640e558178f3a85e27f89caf9e/crates/blockifier/src/concurrency/worker_logic_test.rs#L103)):*
> ```XML
> 
>     let cached_state =
>         test_state(&block_context.chain_info, BALANCE, &[(account, txs.len().try_into().unwrap())]);
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 130 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-NzggUyBBYQEQhiNzLQH:-NzgtDPf5csExGJ1MPaF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d2c58a0b280d1640e558178f3a85e27f89caf9e/crates/blockifier/src/concurrency/worker_logic_test.rs#L130)):*
> ```XML
>         .unwrap();
> 
>     // Commit tx and check that the commit did not affected the result and state.
> ```

Done.

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 136 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-NzharrQAS8FQ6sBKVvK:-NzharrQAS8FQ6sBKVvL:b53k1to) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4ac56d133ddd0c35dd5514bed86223f7932ab04/crates/blockifier/src/concurrency/worker_logic_test.rs#L136)):*
> ```XML
>         commit_result.as_ref().unwrap().fee_transfer_call_info.as_ref().unwrap();
>     assert_eq!(read_values_before_commit, fee_transfer_call_info.storage_read_values);
>     drop(execution_task_outputs);
> ```

No need to drop it right?



_Code quote:_
```XML
    drop(execution_task_outputs);
```

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-:-NziIrIs-lNLfTGaub-9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-:-Nzvpb9J-U2YejrCp3CB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 91 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-NzxvODsErCxLqtn7jkT:-NzxvODsErCxLqtn7jkU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/912ea8c607aee47f0245d327f2ecbce14740fca2/crates/blockifier/src/concurrency/worker_logic_test.rs#L91)):*
> ```XML
>     let mut block_info = block_context.block_info.clone();
>     block_info.sequencer_address = account_address;
>     block_context.block_info = block_info;
> ```





_Suggestion:_
```XML
    block_context.block_info.sequencer_address = account_address;
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 99 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-NzxwoQsEBoD7vjzMsud:-NzxwoQsEBoD7vjzMsue:b-sx3flm) ([raw file](https://github.com/starkware-libs/blockifier/blob/912ea8c607aee47f0245d327f2ecbce14740fca2/crates/blockifier/src/concurrency/worker_logic_test.rs#L99)):*
> ```XML
>         test_contract_address,
>         nonce_manager.next(account_address),
>     ))];
> ```

Is the nonce manager needed?



_Suggestion:_
```XML
    let tx = Transaction::AccountTransaction(trivial_calldata_invoke_tx(
        account_address,
        test_contract_address,
        nonce_manager.next(account_address),
    ));
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 104 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-NzxvpEg1ioB0C-SRanR:-NzxvpEg1ioB0C-SRanS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/912ea8c607aee47f0245d327f2ecbce14740fca2/crates/blockifier/src/concurrency/worker_logic_test.rs#L104)):*
> ```XML
> 
>     let cached_state =
>         test_state(&block_context.chain_info, BALANCE, &[(account, 1), (test_contract, 1)]);
> ```





_Suggestion:_
```XML
    let state =
        test_state(&block_context.chain_info, BALANCE, &[(account, 1), (test_contract, 1)]);
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 125 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-Nzxw_nrAoYpBq0CxZMV:-Nzxw_nrAoYpBq0CxZMW:b3r34h8) ([raw file](https://github.com/starkware-libs/blockifier/blob/912ea8c607aee47f0245d327f2ecbce14740fca2/crates/blockifier/src/concurrency/worker_logic_test.rs#L125)):*
> ```XML
>     let sequencer_balance_high_before = tx_versioned_state
>         .get_storage_at(
>             executor.block_context.chain_info.fee_token_address(&FeeType::Strk),
> ```

Please define a variable and extract the fee type from the transaction context



_Code quote:_
```XML
 executor.block_context.chain_info.fee_token_address(&FeeType::Strk)
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 99 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-NzxwoQsEBoD7vjzMsud:-O--izFkA9uiFMaGqyYk:b-ykwc0z) ([raw file](https://github.com/starkware-libs/blockifier/blob/912ea8c607aee47f0245d327f2ecbce14740fca2/crates/blockifier/src/concurrency/worker_logic_test.rs#L99)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is the nonce manager needed?
</blockquote></details>

The executor expects a list of txes, so if I give it only one tx, it won't work. 
The nonce manager is not needed.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 104 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-NzxvpEg1ioB0C-SRanR:-O--v93g94b83cdPlF4m:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/912ea8c607aee47f0245d327f2ecbce14740fca2/crates/blockifier/src/concurrency/worker_logic_test.rs#L104)):*
> ```XML
> 
>     let cached_state =
>         test_state(&block_context.chain_info, BALANCE, &[(account, 1), (test_contract, 1)]);
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 125 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1935#-Nzxw_nrAoYpBq0CxZMV:-O--y3Bh7e2T9rbnttu2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/912ea8c607aee47f0245d327f2ecbce14740fca2/crates/blockifier/src/concurrency/worker_logic_test.rs#L125)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please define a variable and extract the fee type from the transaction context
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1935)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
