### PR TITLE
fix(execution): convert all local errors to stack trace

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1378)

### CODE REVIEW

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/execution/entry_point.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1378#-Np-XFOz2M6WBaWv1oCA:-Np-XFOz2M6WBaWv1oCB:b-t5qx7o) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b2072eb6f8a7f3957ab9847634b722467aaed5/crates/blockifier/src/execution/entry_point.rs#L117)):*
> ```XML
>                 }
>                 other_error => {
>                     // TODO(Zuphit): Handle errors such that `Execution failed. Failure reason: ...`
> ```

need to change this doc now



_Code quote:_
```XML
`Execution failed. Failure reason: ...`
```

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/execution/entry_point.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1378#-Np-XFOz2M6WBaWv1oCA:-Np-czzI02acS76Fo9hE:b-19qa13) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b2072eb6f8a7f3957ab9847634b722467aaed5/crates/blockifier/src/execution/entry_point.rs#L117)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the error prefix is printed twice ATM?
</blockquote></details>

It's not the error prefix, it's the (outermost) error content. like in the Cairo1 regression:
```
Error in the called contract (0x00000000000000000000000000000000000000000000000000000000c0000700):
Error at pc=0:8070:
Got an exception while executing a hint: Hint Error: Execution failed. Failure reason: 0x6661696c ('fail').
Cairo traceback (most recent call last):
Unknown location (pc=0:2561)

Error in the called contract (0x00000000000000000000000000000000000000000000000000000000c0000700):
Execution failed. Failure reason: 0x6661696c ('fail').
```

Here it was `EntryPointExecutionError::ExecutionFailed` variant so the previous comment pointed to that. But if you catch different types the content + formatting changes.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1378)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1378#-Np-XFOz2M6WBaWv1oCA:-Np-f1Tj5C_6TiVMPJ7_:bi7gtwx) ([raw file](https://github.com/starkware-libs/blockifier/blob/72b2072eb6f8a7f3957ab9847634b722467aaed5/crates/blockifier/src/execution/entry_point.rs#L117)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

It's not the error prefix, it's the (outermost) error content. like in the Cairo1 regression:
```
Error in the called contract (0x00000000000000000000000000000000000000000000000000000000c0000700):
Error at pc=0:8070:
Got an exception while executing a hint: Hint Error: Execution failed. Failure reason: 0x6661696c ('fail').
Cairo traceback (most recent call last):
Unknown location (pc=0:2561)

Error in the called contract (0x00000000000000000000000000000000000000000000000000000000c0000700):
Execution failed. Failure reason: 0x6661696c ('fail').
```

Here it was `EntryPointExecutionError::ExecutionFailed` variant so the previous comment pointed to that. But if you catch different types the content + formatting changes.
</blockquote></details>

I am removing this TODO then; will be handled properly when errors are non stringified objects

**Review by zuphitf — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1378)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Pull request merged**
