### PR TITLE
Add CurrentAccountTxContext with CommonFields object.

### PR DESCRIPTION
**Pull request by NirLevi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/968)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/968)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @NirLevi-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/968#-Nfup6DO-B5Ekvcy2Ept:-Nfup6DO-B5Ekvcy2Epu:b-39amfo) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b7bcdf9019f6ad895d2cf73bf704fa3716600ed/crates/blockifier/src/transaction/objects.rs#L39)):*
> ```XML
> pub enum AccountTransactionContext {
>     Deprecated(DeprecatedAccountTransactionContext),
>     Current(CurrentAccountTransactionContext),
> ```

Also in `match`es.



_Suggestion:_
```XML
    Current(CurrentAccountTransactionContext),
    Deprecated(DeprecatedAccountTransactionContext),
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/968#-NfupE1b9aFjZybLhSb_:-NfupE1b9aFjZybLhSba:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b7bcdf9019f6ad895d2cf73bf704fa3716600ed/crates/blockifier/src/transaction/objects.rs#L83)):*
> ```XML
>     }
> }
> #[derive(Clone, Debug, Eq, PartialEq)]
> ```





_Suggestion:_
```XML
}

#[derive(Clone, Debug, Eq, PartialEq)]
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/968#-NfupLaQ3rJOWk7-5Wbu:-NfupLaQ3rJOWk7-5Wbv:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b7bcdf9019f6ad895d2cf73bf704fa3716600ed/crates/blockifier/src/transaction/objects.rs#L102)):*
> ```XML
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> 
> pub struct CommonAccountTransactionContextFields {
> ```





_Suggestion:_
```XML
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct CommonAccountTransactionContextFields {
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/968)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @NirLevi-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/968#-Nfupk8i98H_i38Ap0jJ:-Nfupk8i98H_i38Ap0jK:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b7bcdf9019f6ad895d2cf73bf704fa3716600ed/crates/blockifier/src/transaction/objects.rs#L102)):*
> ```XML
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> 
> pub struct CommonAccountTransactionContextFields {
> ```





_Suggestion:_
```XML
CommonAccountFields
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/968#-NfupnklAkS-KN4SaKLt:-NfupnklAkS-KN4SaKLu:b-jzl3vv) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b7bcdf9019f6ad895d2cf73bf704fa3716600ed/crates/blockifier/src/transaction/transactions.rs#L176)):*
> ```XML
> 
>     pub fn get_account_tx_context(&self) -> AccountTransactionContext {
>         let common_fields = CommonAccountTransactionContextFields {
> ```

Add a TODO to consider instantiating this object in `AccountTransaction`.



_Code quote:_
```XML
let common_fields
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/968)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @NirLevi-starkware)

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/968)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/968#-NfupnklAkS-KN4SaKLt:-NfuvwmiCNHTPLW7It30:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b7bcdf9019f6ad895d2cf73bf704fa3716600ed/crates/blockifier/src/transaction/transactions.rs#L176)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a TODO to consider instantiating this object in `AccountTransaction`.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/968)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @NirLevi-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/968#-NfuwlsBAsZtPsRs_icM:-NfuwlsBAsZtPsRs_icN:b68qfoq) ([raw file](https://github.com/starkware-libs/blockifier/blob/658ab2dc78af299832530a51c9f497bbeeac6dde/crates/blockifier/src/transaction/objects.rs#L84)):*
> ```XML
> }
> 
> /// Contains the account information of the transaction (outermost call).
> ```

Convert to `AccountTransactionContext`'s docstring.



_Code quote:_
```XML
/// Contains the account information of the transaction (outermost call).
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/968#-NfupnklAkS-KN4SaKLt:-Nfuwsg6BQyCwr-fHrEp:b-ixu4sa) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b7bcdf9019f6ad895d2cf73bf704fa3716600ed/crates/blockifier/src/transaction/transactions.rs#L176)):*
<details><summary><i>Previously, NirLevi-starkware (Nir Levi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Next PR, please.

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/968)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/transaction/objects.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/968#-NfuwlsBAsZtPsRs_icM:-Nfuz46A37stJ4jZKBM0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/658ab2dc78af299832530a51c9f497bbeeac6dde/crates/blockifier/src/transaction/objects.rs#L84)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Convert to `AccountTransactionContext`'s docstring.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/968#-NfupnklAkS-KN4SaKLt:-NfuzW9F0BQqCT79C2Sb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b7bcdf9019f6ad895d2cf73bf704fa3716600ed/crates/blockifier/src/transaction/transactions.rs#L176)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Next PR, please.
</blockquote></details>

Done.

**Pull request merged**
