### PR TITLE
Support and test V3 invoke

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/949)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/949)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/949#-NfkDkXO8K8IJ3MnzWji:-NfkDkXO8K8IJ3MnzWjj:b9ww99k) ([raw file](https://github.com/starkware-libs/blockifier/blob/75912a69982eae3b1e79962abf4046d58bbc37b8/crates/blockifier/src/test_utils.rs#L391)):*
> ```XML
>     pub account_address: ContractAddress,
>     pub max_fee: Fee,
>     pub entry_point_selector: Option<EntryPointSelector>,
> ```

Do we actually needed? Aren't most of our tests invoke V0 on `__execute__` anyways?



_Code quote:_
```XML
pub entry_point_selector: Option<EntryPointSelector>,
```
___
*[`crates/blockifier/src/test_utils.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/949#-NfkDtmz1ZiF29z5jKN0:-NfkDtmz1ZiF29z5jKN1:bfaqytm) ([raw file](https://github.com/starkware-libs/blockifier/blob/75912a69982eae3b1e79962abf4046d58bbc37b8/crates/blockifier/src/test_utils.rs#L413)):*
> ```XML
>             signature: None,
>             tx_version: TransactionVersion::ZERO,
>             resource_bounds: ResourceBoundsMapping(BTreeMap::from([
> ```

Maybe add `new` from a list of tuples, or a generic map? The fact that it's `BTreeMap` is an implementation detail.



_Code quote:_
```XML
ResourceBoundsMapping
```
___
*[`crates/blockifier/src/test_utils.rs` line 415 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/949#-NfkDRAgEar7hmRAu-dx:-NfkDRAhE5Gq7w0ine-z:bqkdwbf) ([raw file](https://github.com/starkware-libs/blockifier/blob/75912a69982eae3b1e79962abf4046d58bbc37b8/crates/blockifier/src/test_utils.rs#L415)):*
> ```XML
>             resource_bounds: ResourceBoundsMapping(BTreeMap::from([
>                 (Resource::L1Gas, default_resource_bounds),
>                 (Resource::L2Gas, default_resource_bounds),
> ```

Unused until fee market; maybe put 0 for now?



_Code quote:_
```XML
Resource::L2Gas
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/949)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/949#-NfkDkXO8K8IJ3MnzWji:-NfkKaLEEPbn_4jxfdYz:b-dq6ny0) ([raw file](https://github.com/starkware-libs/blockifier/blob/75912a69982eae3b1e79962abf4046d58bbc37b8/crates/blockifier/src/test_utils.rs#L391)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we actually needed? Aren't most of our tests invoke V0 on `__execute__` anyways?
</blockquote></details>

When the `invoke_tx_args` macro is used, effectively we will never set it explicitly; however, since it *is* a parameter of v0 transactions, I think it is wise to allow explicitly setting it (what if we decide to test this edge case? we still support v0 txs, right?)
___
*[`crates/blockifier/src/test_utils.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/949#-NfkDtmz1ZiF29z5jKN0:-NfkJl1eBDX3WkWhMTo1:b-eeselh) ([raw file](https://github.com/starkware-libs/blockifier/blob/75912a69982eae3b1e79962abf4046d58bbc37b8/crates/blockifier/src/test_utils.rs#L413)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe add `new` from a list of tuples, or a generic map? The fact that it's `BTreeMap` is an implementation detail.
</blockquote></details>

This struct is defined in SN-API repo; I can't do `impl ResourceBoundsMapping` in the blockifier.
___
*[`crates/blockifier/src/test_utils.rs` line 415 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/949#-NfkDRAgEar7hmRAu-dx:-NfkKWubBeo-7-DfyOGP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/75912a69982eae3b1e79962abf4046d58bbc37b8/crates/blockifier/src/test_utils.rs#L415)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Unused until fee market; maybe put 0 for now?
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/949)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/949#-NfkDkXO8K8IJ3MnzWji:-NfkNlDp4G4J54eWZE9J:b-bztksd) ([raw file](https://github.com/starkware-libs/blockifier/blob/75912a69982eae3b1e79962abf4046d58bbc37b8/crates/blockifier/src/test_utils.rs#L391)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

When the `invoke_tx_args` macro is used, effectively we will never set it explicitly; however, since it *is* a parameter of v0 transactions, I think it is wise to allow explicitly setting it (what if we decide to test this edge case? we still support v0 txs, right?)
</blockquote></details>

Do we even have tests that test non-`__execute__` EP? If not, I'm not sure we should create infra. for that; if need be, we'll add it.
___
*[`crates/blockifier/src/test_utils.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/949#-NfkDtmz1ZiF29z5jKN0:-NfkNc7J7Akmq7VHDSjZ:b-dyika3) ([raw file](https://github.com/starkware-libs/blockifier/blob/75912a69982eae3b1e79962abf4046d58bbc37b8/crates/blockifier/src/test_utils.rs#L413)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This struct is defined in SN-API repo; I can't do `impl ResourceBoundsMapping` in the blockifier.
</blockquote></details>

TODO for now?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/949)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/949#-NfkDkXO8K8IJ3MnzWji:-Nfot5GU3Mmeb_0dCHsW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/75912a69982eae3b1e79962abf4046d58bbc37b8/crates/blockifier/src/test_utils.rs#L391)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we even have tests that test non-`__execute__` EP? If not, I'm not sure we should create infra. for that; if need be, we'll add it.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/949#-:-NfoxPK114GQ_ty6ATRl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Pull request merged**
