### PR TITLE
fix: post merge actions

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2017)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2017)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/2017#-O0msuC0Ed002l2Uy5dx:-O0msuC0Ed002l2Uy5dy:b-i92ikw) (no related file):*
should fix [this](https://github.com/starkware-libs/blockifier/actions/runs/9758593750/job/26933463274)

___

**Review by alon-dotan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2017)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2017#-:-O0nPC4D9Ss3JqpadhiW:bnfp4nl)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2017)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
