### PR TITLE
refactor: moved default_invoke_tx_args to be associated with InvokeTxArgs

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1495)

### CODE REVIEW

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1495)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/test_utils/invoke.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1495#-NqWYLqZEieTkcpRZcTK:-NqWYLqZEieTkcpRZcTL:b2g0oqf) ([raw file](https://github.com/starkware-libs/blockifier/blob/27a34a5bf8b2bc9cde04ea1906158570e2571a10/crates/blockifier/src/test_utils/invoke.rs#L15)):*
> ```XML
> use crate::test_utils::{create_calldata, default_testing_resource_bounds, stark_felt, MAX_FEE};
> use crate::transaction::constants::EXECUTE_ENTRY_POINT_NAME;
> use crate::transaction::transactions::InvokeTransaction;
> ```

Keep an empty line between `use` statements and code.
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1495#-NqWZjbR7dm52Adv6nXX:-NqWZjbR7dm52Adv6nXY:b-fqjpca) ([raw file](https://github.com/starkware-libs/blockifier/blob/27a34a5bf8b2bc9cde04ea1906158570e2571a10/crates/blockifier/src/test_utils/invoke.rs#L33)):*
> ```XML
> }
> 
> impl InvokeTxArgs {
> ```

Move below `impl Default for InvokeTxArgs`.
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1495#-NqWZXxjAsVpUrzNGOdG:-NqWZXxjAsVpUrzNGOdH:bw8vep5) ([raw file](https://github.com/starkware-libs/blockifier/blob/27a34a5bf8b2bc9cde04ea1906158570e2571a10/crates/blockifier/src/test_utils/invoke.rs#L47)):*
> ```XML
>             max_fee: Fee(MAX_FEE),
>             signature: TransactionSignature::default(),
>             nonce: Nonce::default(),
> ```

Are those really needed here?
I'm not sure it's possible, but try using the `..Default::default()` syntax instead of the macro. The macro, as you can see below, is defined to reduce boilerplate, but this refactor is adding a constructor, so it's nicer IMO to explicitly write what you use.



_Code quote:_
```XML
            signature: TransactionSignature::default(),
            nonce: Nonce::default(),
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/test_utils/invoke.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1495#-NqWtNlO3EKsGtVCWRKQ:-NqWtNlO3EKsGtVCWRKR:b1cad37) ([raw file](https://github.com/starkware-libs/blockifier/blob/3347c2ab4df7884f7e9ae82279822fb0a8bf4213/crates/blockifier/src/test_utils/invoke.rs#L66)):*
> ```XML
> 
>         InvokeTxArgs {
>             max_fee: Fee(MAX_FEE),
> ```

Please check if needed. If not, let the `..Default::default()` do the job. Otherwise, add something indicative to the constructor name.



_Code quote:_
```XML
max_fee: Fee(MAX_FEE),
```

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1495)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @giladchase, @nimrod-starkware, and @Yoni-Starkware)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1495)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/invoke.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1495#-NqWtNlO3EKsGtVCWRKQ:-NqWwaNk2UwK7GPqUBQZ:bbn6ifk) ([raw file](https://github.com/starkware-libs/blockifier/blob/3347c2ab4df7884f7e9ae82279822fb0a8bf4213/crates/blockifier/src/test_utils/invoke.rs#L66)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Please check if needed. If not, let the `..Default::default()` do the job. Otherwise, add something indicative to the constructor name.
</blockquote></details>

It is needed as the default value will be zero.
Do you mean something like "from_account_and_test_addresses_with_max_fee"?
Another option is to make MAX_FEE value as the default value of Fee, but I don't think it's the right way to do that..

**Review by giladchase — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1495)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

**Comment by nimrod-starkware** [comment]
duplicate
https://github.com/starkware-libs/blockifier/pull/1510

**Pull request closed without merging**
