### PR TITLE
Get actual_fee from python for validation.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403)

### CODE REVIEW

**Review by alonh5 — COMMENTED** [review]
Not for merging.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403#-:-NSuxiPLCgCxPebic0cD:bd4duoy)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/403#-NSyCj-2EPuZnuF51QHC:-NSyCj-2EPuZnuF51QHD:b1dh6xp) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ab15b16c7fa93c5bcd716f485624f1b861063a0/crates/blockifier/src/transaction/account_transaction.rs#L202)):*
> ```XML
>         }
> 
>         // let actual_fee = calculate_tx_fee(block_context);
> ```

Can be deleted.



_Code quote:_
```XML
// let actual_fee = calculate_tx_fee(block_context);
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/403#-NSyCdod7FPEf5NLlupG:-NSyCdod7FPEf5NLlupH:b-t9dsij) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ab15b16c7fa93c5bcd716f485624f1b861063a0/crates/blockifier/src/transaction/transaction_execution.rs#L28)):*
> ```XML
>         state: &mut TransactionalState<'_, S>,
>         block_context: &BlockContext,
>         _actual_fee: Fee,
> ```

Not needed here.



_Code quote:_
```XML
_actual_fee: Fee,
```

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

**Review by elintul — COMMENTED** [review]
> Reviewed 9 of 11 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by elintul — COMMENTED** [review]
> Reviewed 9 of 11 files at r6, 3 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/403#-NTZ3QwuEcuQ5uOw5kh9:-NTZ3QwuEcuQ5uOw5khA:b-9vg6pa) (no related file):*
I suggest rebasing over `main` instead of cherry-picking to this branch, which is a lot more maintainable (less diff. at any moment). 

___

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by elintul — COMMENTED** [review]
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by elintul — COMMENTED** [review]
> Reviewed 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by elintul — COMMENTED** [review]
> Reviewed 5 of 5 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/403)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Pull request closed without merging**
