### PR TITLE
refactor: move validate_block_number_rounding and validate_timestamp_…

### PR DESCRIPTION
**Pull request by OriStarkware**
…rounding to versioned_constants

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1506)

### CODE REVIEW

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1506)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1506#-:-NqbRvnb91EUfX4EwUx_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by giladchase — COMMENTED** [review]
I think i saw someone else do something very similar to this PR last week, was that you? :thinking: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1506#-:-NqbRyNrCXyyXOzHjHzm:b-8q7ulg)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by OriStarkware — COMMENTED** [review]
Yael :) https://reviewable.io/reviews/starkware-libs/blockifier/1490#-

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1506#-:-NqbUmIQCRVeT-sG4esy:b-sqtb3i)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
