### PR TITLE
Add negative flows to validate unit test.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: all files reviewed, 7 unresolved discussions (waiting on @Adi-Yakovian, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAUwcRAAZKbER_77E7:-NSAUwcRAAZKbER_77E8:bnjvfyc) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L51)):*
> ```XML
> 
> // Cairo constants.
> pub const CAIRO_FALSE: u64 = 0;
> ```

Move to `transaction/constants.rs`.



_Suggestion:_
```XML
pub const FELT_FALSE: u64 = 0;
pub const FELT_TRUE: u64 = 1;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 674 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSANT-X6Z-TeJ_QoSfU:-NSANT-X6Z-TeJ_QoSfV:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L674)):*
> ```XML
>     // Negative flows.
> 
>     // Logic failure
> ```





_Suggestion:_
```XML
// Logic failure.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 679 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAN_7-6sOv-HR7mElc:-NSAN_7-6sOv-HR7mEld:bkycpl9) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L679)):*
> ```XML
>         ..create_tx(INVALID, None)
>     });
>     let mut error = account_tx.execute(state, block_context).unwrap_err();
> ```

You can reassign with `let` instead of mutating.



_Suggestion:_
```XML
let error
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 682 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSANm6L-5ZbO89-ln3n:-NSANm6L-5ZbO89-ln3o:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L682)):*
> ```XML
>     assert_matches!(error, TransactionExecutionError::ValidateTransactionError(_));
> 
>     // Trying to call other contract (forbidden).
> ```





_Suggestion:_
```XML
another
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 689 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAOC1MDE26M5aWMFu7:-NSAOC1MDE26M5aWMFu8:b-adulvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L689)):*
> ```XML
>     error = account_tx.execute(state, block_context).unwrap_err();
>     assert_matches!(error, TransactionExecutionError::UnauthorizedInnerCall{entry_point_kind} if
>         entry_point_kind == "__validate__");
> ```

You can use `VALIDATE_ENTRY_POINT_NAME` from `constants.rs`.



_Code quote:_
```XML
__validate__
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 707 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAR3xi95V_2-wc4u_p:-NSAR3xi95V_2-wc4u_q:bw8bgux) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L707)):*
> ```XML
>     assert_matches!(error, TransactionExecutionError::ValidateTransactionError(_));
> 
>     // All other cases are covered in `test_validate_invoke_function`.
> ```

Is this the only case tested for `validate_declare` in python too? How is it different than the one in `test_validate_invoke_function`? (Same questions for `validate_deploy`).



_Code quote:_
```XML
// All other cases are covered in `test_validate_invoke_function`.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 727 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAOmmg8jPP60WP6z6w:-NSAOmmg8jPP60WP6z6x:b2nreh6) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L727)):*
> ```XML
>     );
> 
>     let mut account_tx = AccountTransaction::DeployAccount(tx1);
> ```

Same as above.



_Suggestion:_
```XML
    let account_tx = AccountTransaction::DeployAccount(tx1);
    let error = account_tx.execute(state, block_context).unwrap_err();
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: all files reviewed, 5 unresolved discussions (waiting on @Adi-Yakovian, @alonh5, and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAUwcRAAZKbER_77E7:-NSBAfbf35k3kttANSxa:b-k3z40m) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L51)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Move to `transaction/constants.rs`.
</blockquote></details>

Why move? It is only used in this test file.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 679 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAN_7-6sOv-HR7mElc:-NSBI6jb6uJ0M3zaBoSJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L679)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can reassign with `let` instead of mutating.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 689 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAOC1MDE26M5aWMFu7:-NSBIF8P5SRhJ-Og0s64:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L689)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can use `VALIDATE_ENTRY_POINT_NAME` from `constants.rs`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 707 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAR3xi95V_2-wc4u_p:-NSBIP21Ck474f0JXNxz:b-6nalrc) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L707)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this the only case tested for `validate_declare` in python too? How is it different than the one in `test_validate_invoke_function`? (Same questions for `validate_deploy`).
</blockquote></details>

Yes. WDYM? In all cases we check that when `__validate__` fail we fail the transaction with the appropriate error. In invoke we also test all the validate flows + trying to call another contract.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 727 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAOmmg8jPP60WP6z6w:-NSBLfKQ-NDboom4Gqap:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L727)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: all files reviewed, 2 unresolved discussions (waiting on @Adi-Yakovian, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAUwcRAAZKbER_77E7:-NSfALyE1nBLnWLNDggl:b2ikcs6) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L51)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why move? It is only used in this test file.
</blockquote></details>

Because their constant, maybe they can be used elsewhere in the future. Also, maybe in other tests, the values `0, 1` are used explicitly as booleans and should be replaced by these constants, could you TAL?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: all files reviewed, 2 unresolved discussions (waiting on @Adi-Yakovian, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAUwcRAAZKbER_77E7:-NSfC4Js0TsPzMX5dh4Q:b-ua2rtf) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L51)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Because their constant, maybe they can be used elsewhere in the future. Also, maybe in other tests, the values `0, 1` are used explicitly as booleans and should be replaced by these constants, could you TAL?
</blockquote></details>

They're

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: all files reviewed, 2 unresolved discussions (waiting on @Adi-Yakovian, @alonh5, and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAUwcRAAZKbER_77E7:-NSfO5dZ0sjqtu-zJywL:b-qfznaj) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L51)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

They're
</blockquote></details>

Found one and changed. Moved it to the constants file.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: all files reviewed, 1 unresolved discussion (waiting on @Adi-Yakovian, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAUwcRAAZKbER_77E7:-NStSVlr3YQOcQC8aL1l:b9ldnbq) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L51)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Found one and changed. Moved it to the constants file.
</blockquote></details>

Cool, thanks!
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 707 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAR3xi95V_2-wc4u_p:-NStT8u97NQGZ8shtBJH:bdbr0po) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L707)):*
> In invoke we also test all the validate flows + trying to call another contract.

I guess I'm asking why we don't need to test this in the declare/deploy validate also.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: all files reviewed, 1 unresolved discussion (waiting on @Adi-Yakovian, @alonh5, and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 707 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAR3xi95V_2-wc4u_p:-NT8Vqns51wtYGHiqmel:bo12t5h) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L707)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

> In invoke we also test all the validate flows + trying to call another contract.

I guess I'm asking why we don't need to test this in the declare/deploy validate also.
</blockquote></details>

Oh, I see. It's the same `__validate__` function, do you think it's necessary to check it in every transaction type?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: all files reviewed, 1 unresolved discussion (waiting on @Adi-Yakovian, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 707 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAR3xi95V_2-wc4u_p:-NStSzMx67bw2sU4lTbX:brh6s3h) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L707)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh, I see. It's the same `__validate__` function, do you think it's necessary to check it in every transaction type?
</blockquote></details>

Is it possible to reuse the same test and inject the tx type (invoke/deploy/declare)?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @Adi-Yakovian, @alonh5, and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 707 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAR3xi95V_2-wc4u_p:-NT9LNoO6WqhZusImZnR:b-qpatb6) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L707)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is it possible to reuse the same test and inject the tx type (invoke/deploy/declare)?
</blockquote></details>

Done. WDYT?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: all files reviewed, 6 unresolved discussions (waiting on @Adi-Yakovian, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 707 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NSAR3xi95V_2-wc4u_p:-NTNlVwa64BVHUnRK8wh:b3kmvpd) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7d926f5eb80438a4b769004ff3f87282822e6b6/crates/blockifier/src/transaction/transactions_test.rs#L707)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done. WDYT?
</blockquote></details>

Looks good :)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 630 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTNgc0ZEeJedf_nqc1M:-NTNgc0ZEeJedf_nqc1N:ba3dfmt) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a1e696c066d1b9f2304f91fe56f4961d45a7f60/crates/blockifier/src/transaction/transactions_test.rs#L630)):*
> ```XML
>                 Some(signature),
>             );
>             dbg!(deploy_account_tx.contract_address);
> ```

Remove.



_Code quote:_
```XML
dbg!(deploy_account_tx.contract_address);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 643 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTNk6FHDk1YuPpvNFN0:-NTNk6FHDk1YuPpvNFN1:b-17p3wp) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a1e696c066d1b9f2304f91fe56f4961d45a7f60/crates/blockifier/src/transaction/transactions_test.rs#L643)):*
> ```XML
>                 execute_calldata,
>                 ContractAddress(patricia_key!(TEST_FAULTY_ACCOUNT_CONTRACT_ADDRESS)),
>                 Fee(0),
> ```

Does it not work with `Fee(2)`? If so, why?



_Code quote:_
```XML
Fee(0)
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 648 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTNgkKg10h_VAbRT1VI:-NTNgkKg10h_VAbRT1VJ:b4url60) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a1e696c066d1b9f2304f91fe56f4961d45a7f60/crates/blockifier/src/transaction/transactions_test.rs#L648)):*
> ```XML
>             AccountTransaction::Invoke(invoke_tx)
>         }
>         TransactionType::L1Handler => panic!(),
> ```

I think is more suitable.



_Suggestion:_
```XML
unimplemented!()
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 693 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTNh2EeA1IZ7M0Tfq54:-NTNh2EeA1IZ7M0Tfq55:bciow9p) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a1e696c066d1b9f2304f91fe56f4961d45a7f60/crates/blockifier/src/transaction/transactions_test.rs#L693)):*
> ```XML
>         entry_point_kind == constants::VALIDATE_ENTRY_POINT_NAME);
> 
>         // Constructor
> ```

Could you explain the comment?



_Suggestion:_
```XML
// Constructor.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 701 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTNlgaL14I1v2vp6DLd:-NTNlgaL14I1v2vp6DLe:bkjo3z1) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a1e696c066d1b9f2304f91fe56f4961d45a7f60/crates/blockifier/src/transaction/transactions_test.rs#L701)):*
> ```XML
>                 TEST_FAULTY_ACCOUNT_CONTRACT_CLASS_HASH,
>                 Fee(0),
>                 Some(calldata![stark_felt!(constants::FELT_TRUE)]), // run  faulty_validate() in
> ```

Move the comment to its own line.



_Code quote:_
```XML
                Some(calldata![stark_felt!(constants::FELT_TRUE)]), // run  faulty_validate() in
                // the constructor.
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @Adi-Yakovian, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 643 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTNk6FHDk1YuPpvNFN0:-NTO41Su3CqhENcv_s5Y:b-6gtfs6) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a1e696c066d1b9f2304f91fe56f4961d45a7f60/crates/blockifier/src/transaction/transactions_test.rs#L643)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No. It's not enough (the actual fee is 463700000000000). I can use `BALANCE` but I think that the fee calculation is not the purpose of the test. 
</blockquote></details>

In Python, we have a (very large, 2 **100)`MAX_FEE` constant for tests like this. Maybe add it here too and use it?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 701 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTO4Tqw3RSzbjUSKZbr:-NTO4Tqw3RSzbjUSKZbs:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/474effca7358abc82b6c3cd7e28c99430e0c4ad9/crates/blockifier/src/transaction/transactions_test.rs#L701)):*
> ```XML
>                 Fee(0),
>                 Some(calldata![stark_felt!(constants::FELT_TRUE)]),
>                 // run  faulty_validate() in the constructor.
> ```





_Suggestion:_
```XML
// run faulty_validate() in the constructor.
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Adi-Yakovian, @alonh5, and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 643 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTNk6FHDk1YuPpvNFN0:-NTOJHTqE6Csbkjk0Lfx:b-ex2o6c) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a1e696c066d1b9f2304f91fe56f4961d45a7f60/crates/blockifier/src/transaction/transactions_test.rs#L643)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In Python, we have a (very large, 2 **100)`MAX_FEE` constant for tests like this. Maybe add it here too and use it?
</blockquote></details>

The main "problem" is with `DeployAccount`: we will need to update the balance of the about to be deployed account contract in the erc20 contract. WDYT?

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270#-:-NTONZbp9_IRKV8Gpv9w:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Adi-Yakovian, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 643 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTNk6FHDk1YuPpvNFN0:-NTONHJA-N8KJ1Pj3w9a:bcnr12d) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a1e696c066d1b9f2304f91fe56f4961d45a7f60/crates/blockifier/src/transaction/transactions_test.rs#L643)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The main "problem" is with `DeployAccount`: we will need to update the balance of the about to be deployed account contract in the erc20 contract. WDYT?
</blockquote></details>

Leave it as 0.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 692 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTONB21EJMxaRAEoaaH:-NTONB21EJMxaRAEoaaI:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0016c0c6d57263f39501e3dc80a4f71ad916481f/crates/blockifier/src/transaction/transactions_test.rs#L692)):*
> ```XML
>         entry_point_kind == constants::VALIDATE_ENTRY_POINT_NAME);
> 
>         // We verify that the contract does not call other contract in the constructor of deploy
> ```





_Suggestion:_
```XML
Verify that the contract does not call another
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/270)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Adi-Yakovian and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 692 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/270#-NTONB21EJMxaRAEoaaH:-NTObWJXD6UX72lXoqlc:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/0016c0c6d57263f39501e3dc80a4f71ad916481f/crates/blockifier/src/transaction/transactions_test.rs#L692)):*
> ```XML
>         entry_point_kind == constants::VALIDATE_ENTRY_POINT_NAME);
> 
>         // We verify that the contract does not call other contract in the constructor of deploy
> ```

Done

**Pull request merged**
