### PR TITLE
refactor: bouncer - update used state entries sets

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1582)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1582)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1582#-Nr_baKrBZEzeWkIn-E9:-Nr_cpAQ4UXjH2Z2wTZZ:bzfmns0) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c7326051b8a1272b5f534dc461849cc34f296d2/crates/blockifier/src/bouncer.rs#L135)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This modifies `state`, do we know if that's OK?
</blockquote></details>

This is exactly the same behaviour as today, so I assume it's fine.
who can I ask about this?

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1582)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1582#-Nr_baKrBZEzeWkIn-E9:-NsDHzJr3fQ5To-D1aBu:b-bly3qn) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c7326051b8a1272b5f534dc461849cc34f296d2/crates/blockifier/src/bouncer.rs#L135)):*
Who gave you the task?

>the same behaviour as today

Can you point to where it is currently done? so I can compare.

> so I assume it's fine.

Valid assumption, but it can still be unnecessary, even if it is legit.
Not talking about this change specifically (which i don't follow just yet), just in general for this task: taking care of the bouncer inside the blockifier rather than in python will probably make a bunch of stuff we do currently no longer necessary, because making things Python-safe probably required some boilerplate code.
___
*[`crates/blockifier/src/bouncer.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1582#-NsDH6oC9XWFGEcZpaqc:-NsDH6oD00xD3crT8RxS:b-xlpd42) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6bc89c495d820b1a2e1ca2f86bef29782c57f15/crates/blockifier/src/bouncer.rs#L56)):*
> ```XML
> }
> 
> #[derive(Add, Clone, Copy, Debug, Default, derive_more::Sub, Deserialize, PartialEq)]
> ```

We usually namespace `derive_more`s , since their names look like builtin types (well they are, but you know what I mean :sweat_smile:  We don't want anyone to think that `derive(Add)` is a rust builtin and start looking in `std` if they miss the import).

This isn't the case with serde's `Serialize` `Deserialize`, for example, since they don't mirror `std` types. 



_Suggestion:_
```XML
derive_more::Add, 
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1582)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @Yael-Starkware)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1582#-NsDIet69qdRq2PvA6da):*
needs rebase

**Review by Yael-Starkware — COMMENTED** [review]
> Dismissed @giladchase from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1582)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, @giladchase, and @noaov1)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1582#-NsDIet69qdRq2PvA6da):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

needs rebase
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1582#-Nr_baKrBZEzeWkIn-E9:-NsJQwRE96Uv5xJD6izo:b-vhy21f) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c7326051b8a1272b5f534dc461849cc34f296d2/crates/blockifier/src/bouncer.rs#L135)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Who gave you the task?

>the same behaviour as today

Can you point to where it is currently done? so I can compare.

> so I assume it's fine.

Valid assumption, but it can still be unnecessary, even if it is legit.
Not talking about this change specifically (which i don't follow just yet), just in general for this task: taking care of the bouncer inside the blockifier rather than in python will probably make a bunch of stuff we do currently no longer necessary, because making things Python-safe probably required some boilerplate code.
</blockquote></details>

After discussing this with @noaov1 , 
We should consider moving the state modification done by get_actual_state_changes() into the execute_raw() function instead of doing it here. 
But this is out of scope for the bouncer task, and should be dealt with in a separate task.
___
*[`crates/blockifier/src/bouncer.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1582#-NsDH6oC9XWFGEcZpaqc:-NsDg458BLwkfi2K4B8R:b3lpads) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6bc89c495d820b1a2e1ca2f86bef29782c57f15/crates/blockifier/src/bouncer.rs#L56)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

We usually namespace `derive_more`s , since their names look like builtin types (well they are, but you know what I mean :sweat_smile:  We don't want anyone to think that `derive(Add)` is a rust builtin and start looking in `std` if they miss the import).

This isn't the case with serde's `Serialize` `Deserialize`, for example, since they don't mirror `std` types.
</blockquote></details>

the add was removed atm

**Review by giladchase — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1582)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @elintul, @noaov1, and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1582#-:-Nsc6WXQ0JULha7cmevA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @elintul, and @noaov1)

**Pull request merged**
