### PR TITLE
refactor: delete gas_costs_map

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-:-NsEN4-6BmJJC7KlkMrJ:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 355 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-NslweAx7CP6r1DCLops:-NslweAy8_BAEtoNwjhb:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16303f982edc3d7cdbe50dc8002bf12dd8a32d1/crates/blockifier/src/versioned_constants.rs#L355)):*
> ```XML
> // conversion into actual values.
> // Assumption: if the json has a value that contains the expression "FOO * 2", then the key `FOO`
> // must appear before this value in the JSON.
> ```


___
*[`crates/blockifier/src/versioned_constants.rs` line 477 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-Nsm49Bd3KHGzLzaGPB5:-Nsm49Bd3KHGzLzaGPB6:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16303f982edc3d7cdbe50dc8002bf12dd8a32d1/crates/blockifier/src/versioned_constants.rs#L477)):*
> ```XML
>         let gas_costs_map = raw_json_data.parse_gas_costs()?;
>         let gas_costs: GasCosts =
>             serde_json::to_value(&gas_costs_map).and_then(serde_json::from_value).unwrap();
> ```





_Suggestion:_
```XML
        // TODO(Ori, 15/03/2024): Move this line to an implementation of TryFrom for GasCosts.
        let gas_costs: GasCosts =
            serde_json::to_value(&raw_json_data.parse_gas_costs()?).and_then(serde_json::from_value).unwrap();
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 486 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-Nsm4I5pCvvUQLSehLKe:-Nsm4I5q6C2Ae6DwqP3S:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16303f982edc3d7cdbe50dc8002bf12dd8a32d1/crates/blockifier/src/versioned_constants.rs#L486)):*
> ```XML
> 
> // Intermediate representation of the JSON file in order to make the deserialization easier, using a
> // regular the try_from.
> ```





_Suggestion:_
```XML
// Intermediate representation of the JSON file in order to make the deserialization easier, using a
// regular try_from.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 512 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-Nsm151N3Sjyk99M6rux:-Nsm151N3Sjyk99M6ruy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16303f982edc3d7cdbe50dc8002bf12dd8a32d1/crates/blockifier/src/versioned_constants.rs#L512)):*
> ```XML
> 
>     /// Adds the key its corrisponding value to the gas_costs dict. Adds the key's dependencies
>     /// recursivly first.
> ```





_Suggestion:_
```XML
    /// Recursively adds a key to gas costs, calculating its value after processing any nested keys.
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 355 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-NslweAx7CP6r1DCLops:-NsmOKr8DjNJRNmEhvER:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16303f982edc3d7cdbe50dc8002bf12dd8a32d1/crates/blockifier/src/versioned_constants.rs#L355)):*
> ```XML
> // conversion into actual values.
> // Assumption: if the json has a value that contains the expression "FOO * 2", then the key `FOO`
> // must appear before this value in the JSON.
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 477 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-Nsm49Bd3KHGzLzaGPB5:-NsmON_IExbpuHdp4VrS:b-n0z303) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16303f982edc3d7cdbe50dc8002bf12dd8a32d1/crates/blockifier/src/versioned_constants.rs#L477)):*
> ```XML
>         let gas_costs_map = raw_json_data.parse_gas_costs()?;
>         let gas_costs: GasCosts =
>             serde_json::to_value(&gas_costs_map).and_then(serde_json::from_value).unwrap();
> ```

Will fix that in PR7: https://reviewable.io/reviews/starkware-libs/blockifier/1660
___
*[`crates/blockifier/src/versioned_constants.rs` line 486 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-Nsm4I5pCvvUQLSehLKe:-NsmOYPI2SCfrr322E29:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16303f982edc3d7cdbe50dc8002bf12dd8a32d1/crates/blockifier/src/versioned_constants.rs#L486)):*
> ```XML
> 
> // Intermediate representation of the JSON file in order to make the deserialization easier, using a
> // regular the try_from.
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 512 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-Nsm151N3Sjyk99M6rux:-NsmOjTDDZAWUSNMMOWB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16303f982edc3d7cdbe50dc8002bf12dd8a32d1/crates/blockifier/src/versioned_constants.rs#L512)):*
> ```XML
> 
>     /// Adds the key its corrisponding value to the gas_costs dict. Adds the key's dependencies
>     /// recursivly first.
> ```

Done.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-:-Nsml3ou025i7ZitiaCK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by barak-b-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-:-Nsr_7ckA29xpAKOrPg7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 540 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-NtWaX7a1jsB3qRVrZG7:-NtWaX7a1jsB3qRVrZG8:b-pjf762) ([raw file](https://github.com/starkware-libs/blockifier/blob/d043498c207304a6c8a63bc17db50d4ea4d024ac/crates/blockifier/src/versioned_constants.rs#L540)):*
> ```XML
>                 // Ignore non-whitelist consts.
>                 continue;
>             }
> ```

Are we okay with having random strings in the json file as long as we ignore them?



_Code quote:_
```XML
            if !gas_cost_whitelist.contains(key.as_str()) {
                // Ignore non-whitelist consts.
                continue;
            }
```

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 540 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-NtWaX7a1jsB3qRVrZG7:-NtgxEij6mbAs5y3klQU:b2r2kej) ([raw file](https://github.com/starkware-libs/blockifier/blob/d043498c207304a6c8a63bc17db50d4ea4d024ac/crates/blockifier/src/versioned_constants.rs#L540)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Are we okay with having random strings in the json file as long as we ignore them?
</blockquote></details>

Please ignore.

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by noaov1 — DISMISSED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1620#-:-NtufKYv8DV-prjQjUxI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
