### PR TITLE
chore(concurrency): sleep if there are no tasks

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991)

### CODE REVIEW

**Comment by avi-starkware** [comment]
I don't like using `None`. It is vague, and it messes up some of the types. When do we want it to be `None` and when `Task::NoTask`? Why not use something descriptive?

I propose adding `Task::Wait`. `Task::Wait` will trigger the sleep, and `Task::NoTask` will immediately ask for another task.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eRJ9Z5n7XMuvDMzMi:-O-eRJ9_AqmOlgRbsDe1:be719b) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L219)):*
> ```XML
> #[case::returns_execution_task(0, 10, true)]
> #[case::does_not_return_execution_task(10, 0, true)]
> fn test_finish_validation(
> ```

I renamed the method but forgot to rename the corresponding test.



_Suggestion:_
```XML
fn test_finish_abort(
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eVEwg2zfBH-0UAUNs:-O-eVEwg2zfBH-0UAUNt:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L247)):*
> ```XML
>             assert_eq!(*new_status, TransactionStatus::Executed);
>         }
>     }
> ```





_Suggestion:_
```XML
    let scheduler =
        default_scheduler!(chunk_size: DEFAULT_CHUNK_SIZE, execution_index: execution_index);
    scheduler.set_tx_status(tx_index, TransactionStatus::Executed);
    let mut result = None;
    result = scheduler.finish_abort(tx_index);
    let new_status = scheduler.lock_tx_status(tx_index);
    if execution_index > tx_index {
        assert_eq!(result, Some(Task::ExecutionTask(tx_index)));
        assert_eq!(*new_status, TransactionStatus::Executing);
    } else {
        assert!(result.is_none());
        assert_eq!(*new_status, TransactionStatus::ReadyToExecute);
    }
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eVEwg2zfBH-0UAUNs:-O-eVeK7CRn6JsWhQv-m:bichasj) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L247)):*
> ```XML
>             assert_eq!(*new_status, TransactionStatus::Executed);
>         }
>     }
> ```

Oops, the status should be `TransactionStatus::Aborting`.

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eUdES9a1LKrRd5Yas:-O-eUdETCJMR87oUYCds:b4rx49f) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L216)):*
> ```XML
> 
> #[rstest]
> #[case::not_aborted(0, 10, false)]
> ```

We no longer have the not aborted flow inside this method (if it's not aborted we simply don't call the method).

Here's a PR that fixes this test, in case you don't want all these changes in your PR:
#1993 
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eRJ9Z5n7XMuvDMzMi:-O-eXbgK0xdaeNDW2jmC:bdc1bu8) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L219)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I renamed the method but forgot to rename the corresponding test.
</blockquote></details>

Here's a PR that fixes this test, in case you don't want all these changes in your PR:
#1993 
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eV0Rk-MY8PlKRYtf9:-O-eV0Rk-MY8PlKRYtfA:b4rx49f) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L222)):*
> ```XML
>     #[case] tx_index: TxIndex,
>     #[case] execution_index: TxIndex,
>     #[case] aborted: bool,
> ```

We no longer have the not aborted flow inside this method (if it's not aborted we simply don't call the method).

Here's a PR that fixes this test, in case you don't want all these changes in your PR:
#1993 
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eVEwg2zfBH-0UAUNs:-O-eXM3i6gu4WSk06O-V:bdc1bu8) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L247)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Oops, the status should be `TransactionStatus::Aborting`.
</blockquote></details>

Here's a PR that fixes this test, in case you don't want all these changes in your PR:
#1993

**Review by Yoni-Starkware — COMMENTED** [review]
None means that you're not holding any task and you need to query the scheduler.
NoTask means that there are no pending tasks at all (and you can go to sleep).
I needed to distinguish between these cases because I didn't want to sleep, for example, after every execute.

Not sure I like Wait, it's too specific - it describes what you do if there are no tasks. I can do nothing or call spin_loop for example

But I agree it's not ideal.I'll think

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-:-O-g1FmTDfEvAJl7zqyF:b-gntj8q)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eUdES9a1LKrRd5Yas:-O-g9ZTX58480mSRcIyZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L216)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

We no longer have the not aborted flow inside this method (if it's not aborted we simply don't call the method).

Here's a PR that fixes this test, in case you don't want all these changes in your PR:
#1993
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eRJ9Z5n7XMuvDMzMi:-O-g9Yki-rnQ5qdXF-ck:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L219)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Here's a PR that fixes this test, in case you don't want all these changes in your PR:
#1993
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eV0Rk-MY8PlKRYtf9:-O-g9_3mANyDSu515L0K:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L222)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

We no longer have the not aborted flow inside this method (if it's not aborted we simply don't call the method).

Here's a PR that fixes this test, in case you don't want all these changes in your PR:
#1993
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O-eVEwg2zfBH-0UAUNs:-O-g9_jYAicJTRysx4MN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/61c06f75f8945089c67a00ae0db49733af511153/crates/blockifier/src/concurrency/scheduler_test.rs#L247)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Here's a PR that fixes this test, in case you don't want all these changes in your PR:
#1993
</blockquote></details>

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
@avi-starkware I changed it a bit, WDYT?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-:-O-gHMOh-eZTKrM3Pe_w:b-rxqjy7)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avi-starkware** [comment]
I understood your usage of `None` and `Task::NoTask` after looking at how you use it in the code. My question was rhetorical - I meant to say that someone seeing this code for the first time will have a hard time understanding the distinction between the two.

**Review by Yoni-Starkware — COMMENTED** [review]
`finish_abort` can only return a re-execution task, so using option there is not so bad IMO
I can also change `validate` to return a boolean, something like this

```rust
                    if let Some(re_execute_task) = self.validate(tx_index) {
                        task = re_execute_task;
                        continue;
                    }
```
==>>
```rust
                    let should_re_execute = self.validate(tx_index) {
                    if should_re_execute {
                        task = Task::ExecuteTask(tx_index);
                        continue;
                    }

```

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-:-O-gITqg3zJcAJlW-yH-:b-3189f9)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avi-starkware** [comment]
How about something like:
1.`Task::GetNextTask`/ `Task::AskForTask` / `Task::GetTask` / `Task::Empty`
2. `Task::NoTaskAvailable` / `Task::NoneAvailable` / `Task::Pending`
This will make it clear what each is supposed to mean, with no prescribed wait.
I like it when all options are enum members, because it makes it so that each member clearly occupies a single match arm. With `None`,  the flow of a match arm splits into cases, making it less clean.

Also, note that when we add dependencies, `execute` will also return a task in some cases, making the `if let Some` appear twice in the worker loop...

**Review by Yoni-Starkware — COMMENTED** [review]
Good point, thanks.
Done (cc @noaov1)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-:-O-gPU-WAKY1-HdR65DH:b-g9otti)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-:-O08FTej-P1M2no_U2U8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 105 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O08cPL49eDkPUSckmMf:-O08cPL5CrOOStV_MzCa:b88yfru) ([raw file](https://github.com/starkware-libs/blockifier/blob/f52883df05ab53b223493675b2d5d50ef015d115/crates/blockifier/src/concurrency/scheduler.rs#L105)):*
> ```XML
>         }
> 
>         Task::NoTaskAvailable
> ```

This case will usually mean that the status of the transaction wasn't right for Execution/Validation.



_Suggestion:_
```XML
Task::AskForTask
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 61 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O08dFQqAH41bIbZ4wd8:-O08dFQqAH41bIbZ4wd9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f52883df05ab53b223493675b2d5d50ef015d115/crates/blockifier/src/concurrency/scheduler_test.rs#L61)):*
> ```XML
>     0,
>     TransactionStatus::ReadyToExecute,
>     Task::NoTaskAvailable
> ```





_Suggestion:_
```XML
    Task::AskForTask
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 105 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O08cPL49eDkPUSckmMf:-O08nUP-DlMSopbOC7yn:bw8ysch) ([raw file](https://github.com/starkware-libs/blockifier/blob/f52883df05ab53b223493675b2d5d50ef015d115/crates/blockifier/src/concurrency/scheduler.rs#L105)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This case will usually mean that the status of the transaction wasn't right for Execution/Validation.
</blockquote></details>

This means that there is no task available, and we should wait, right?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 105 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O08cPL49eDkPUSckmMf:-O09272U9fR_xDJ6g3Qm:b-wlgq08) ([raw file](https://github.com/starkware-libs/blockifier/blob/f52883df05ab53b223493675b2d5d50ef015d115/crates/blockifier/src/concurrency/scheduler.rs#L105)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This means that there is no task available, and we should wait, right?
</blockquote></details>

When we reach this line, it is usually because the transaction's status at the `execution_index` is not `ReadyToExecute`.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 105 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O08cPL49eDkPUSckmMf:-O0D-9g6CF_wbSmP8xKX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f52883df05ab53b223493675b2d5d50ef015d115/crates/blockifier/src/concurrency/scheduler.rs#L105)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

When we reach this line, it is usually because the transaction's status at the `execution_index` is not `ReadyToExecute`.
</blockquote></details>

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 95 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1991#-O0D-lYM5YkwhlnKijc6:-O0D-lYM5YkwhlnKijc7:b-chwcmh) ([raw file](https://github.com/starkware-libs/blockifier/blob/db34c5053d224b14708d55b58cc194951954eeb9/crates/blockifier/src/concurrency/scheduler.rs#L95)):*
> ```XML
>         let index_to_execute = self.execution_index.load(Ordering::Acquire);
> 
>         if min(index_to_validate, index_to_execute) >= self.chunk_size {
> ```

@barak-b-starkware FYI: I restored this check in order to know when to stop the busy loop

**Review by avi-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1991)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Pull request merged**
