### PR TITLE
Added (empty) field, updated converters

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP49vVZDoXW6798n60c:-NP49vVZDoXW6798n60d:b-3unhft) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L94)):*
> ```XML
> 
>         let mut declared_class_to_class = HashMap::<PyFelt, String>::new();
>         for (hash, class) in state_diff.declared_classes {
> ```

This is never actually filled.
I can fill it in `CachedState::to_state_diff`, but only from the `class_hash_to_class` field (and not from the `StateCache`, like the other diff fields); is that the correct flow?



_Code quote:_
```XML
state_diff.declared_classes
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP6EaVx9NvOpy6VCQMo:-NP6EaVx9NvOpy6VCQMp:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L24)):*
> ```XML
>     #[pyo3(get)]
>     // Class data stored as a JSON string.
>     pub declared_class_to_class: HashMap<PyFelt, String>,
> ```





_Suggestion:_
```XML
    // Classes are passed as a JSON string.
    pub declared_class_hash_to_class: HashMap<PyFelt, String>,
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP6EjL_2dnEQaKAtdNL:-NP6EjL_2dnEQaKAtdNM:bafiiwv) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L53)):*
> ```XML
> 
>         let mut declared_classes = IndexMap::<ClassHash, ContractClass>::new();
>         for (class_hash, class_json_str) in state_diff.declared_class_to_class {
> ```

I rather not to include implementation details in variable names.



_Suggestion:_
```XML
raw_class
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP6FudY5-ZeZV56w0S7:-NP6FudY5-ZeZV56w0S8:b-a1rtcn) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L56)):*
> ```XML
>             let contract_class: blockifier::execution::contract_class::ContractClass =
>                 serde_json::from_str(class_json_str.as_str())
>                     .map_err(NativeBlockifierError::from)?;
> ```

Maybe the annotation can be expressed in the name as well.

Q: `serde_json -> blockifier::ContractClass` is implemented thanks to `#[derive(Deserialize)]`, right?



_Suggestion:_
```XML
            let raw_blockifier_contract_class = serde_json::from_str(class_json_str.as_str())
                .map_err(NativeBlockifierError::from)?;   
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP6F-VX16pF-NDsJ2Bq:-NP6F-VX16pF-NDsJ2Br:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L93)):*
> ```XML
>         }
> 
>         let mut declared_class_to_class = HashMap::<PyFelt, String>::new();
> ```





_Suggestion:_
```XML
declared_class_hash_to_class
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP49vVZDoXW6798n60c:-NP6HKA-2zZ1ZIfQboVG:b5295iv) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This is never actually filled.
I can fill it in `CachedState::to_state_diff`, but only from the `class_hash_to_class` field (and not from the `StateCache`, like the other diff fields); is that the correct flow?
</blockquote></details>

Let's leave it empty, `0.10` doesn't need the declare classes, and for `0.11` we will pass a different mapping (`felt -> felt`; `sierra_hash -> casm_hash`).

Can this converter return too being `From`, instead of `TryFrom` in this case?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP6EaVx9NvOpy6VCQMo:-NP7Xqtx2v-cdbm-1ewE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L24)):*
> ```XML
>     #[pyo3(get)]
>     // Class data stored as a JSON string.
>     pub declared_class_to_class: HashMap<PyFelt, String>,
> ```

Done.
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP6FudY5-ZeZV56w0S7:-NP7Xx3A-hSDii2-J0Es:b-8gpedn) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L56)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe the annotation can be expressed in the name as well.

Q: `serde_json -> blockifier::ContractClass` is implemented thanks to `#[derive(Deserialize)]`, right?
</blockquote></details>

1. Yes
2. I can't delete the type annotation, how would serde know to which type to try to deserialize?
3. Renamed.
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP49vVZDoXW6798n60c:-NP7M0UNDkfdW6s_mQVy:bbz3hw7) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L94)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's leave it empty, `0.10` doesn't need the declare classes, and for `0.11` we will pass a different mapping (`felt -> felt`; `sierra_hash -> casm_hash`).

Can this converter return too being `From`, instead of `TryFrom` in this case?
</blockquote></details>

Aren't we aiming to deploy a 0.11 version for POTC?
(if we leave it empty then yes it can revert to `From`)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP6FudY5-ZeZV56w0S7:-NP7qFfY6y-L_MaEXgP7:b-srop1k) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. Yes
2. I can't delete the type annotation, how would serde know to which type to try to deserialize?
3. Renamed.
</blockquote></details>

Didn't know it inferred from the annotation.



_Code quote:_
```XML
from_str
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP49vVZDoXW6798n60c:-NP7qLnz-Gt9pQlF2f6G:b-8h2wk4) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Aren't we aiming to deploy a 0.11 version for POTC?
(if we leave it empty then yes it can revert to `From`)
</blockquote></details>

We haven't yet started working on supporting `0.11` (Cairo 1.0 and new `Declare`).
We will deploy `0.11` for POTC, but it is hybrid: can also run Cairo 0 and `Declare`s of version 0.
___
*[`crates/native_blockifier/src/storage.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP7qtRR6LLBLDGzjIWu:-NP7qtRR6LLBLDGzjIWv:b-f1vsmm) ([raw file](https://github.com/starkware-libs/blockifier/blob/0a10509df11df6b996585b9677de69dbc4a79052/crates/native_blockifier/src/storage.rs#L74)):*
> ```XML
>         py_block_info: PyBlockInfo,
>         py_state_diff: PyStateDiff,
>         declared_class_hash_to_class: HashMap<PyFelt, String>,
> ```

Why separately? It's part of `PyStateDiff`.



_Code quote:_
```XML
declared_class_hash_to_class: HashMap<PyFelt, String>,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP6FudY5-ZeZV56w0S7:-NP84E7R2unsmWCJ3mlr:bzazua0) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L56)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Didn't know it inferred from the annotation.
</blockquote></details>

I think that's how generics work... this is the serde signature:
```
pub fn from_str<'a, T>(s: &'a str) -> Result<T>
where
    T: de::Deserialize<'a>,
{
...
```
I need to give it the type somewhere.
I guess I could also do something like `let x = serde_json::from_str<My::Long::Type::Name>(obj)`, give or take some `:`s
___
*[`crates/native_blockifier/src/storage.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP7qtRR6LLBLDGzjIWu:-NP83Fs813eEJvnWcg5I:bzaapg9) ([raw file](https://github.com/starkware-libs/blockifier/blob/0a10509df11df6b996585b9677de69dbc4a79052/crates/native_blockifier/src/storage.rs#L74)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why separately? It's part of `PyStateDiff`.
</blockquote></details>

because in `Blockifier._append_state_diff` (on `dev`), this rust method is called and a pythonic `StateDiff` instance is given as input to `PyStateDiff` here.
Since we don't want to add this field to the pythonic `StateDiff`, this needs to be passed separately.

Second option, on the python side, I can define
```
@marshmallow_dataclass.dataclass(frozen=True)
class PyStateDiff(StateDiff):
    declared_class_hash_to_class: Dict[int, str] = field(default_factory=dict)

    @classmethod
    def from_state_diff(cls, state_diff: StateDiff) -> "PyStateDiff":
        ...
```
and use it to pass a fitting object to rust.

WDYT?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP6FudY5-ZeZV56w0S7:-NP85KLa4VThqR458Ay1:b-axqn4r) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think that's how generics work... this is the serde signature:
```
pub fn from_str<'a, T>(s: &'a str) -> Result<T>
where
    T: de::Deserialize<'a>,
{
...
```
I need to give it the type somewhere.
I guess I could also do something like `let x = serde_json::from_str<My::Long::Type::Name>(obj)`, give or take some `:`s
</blockquote></details>

Haha, `::` everywhere... Thanks!
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP49vVZDoXW6798n60c:-NP85Sj3CzJ_XHWHFiUd:b9fm1bb) ([raw file](https://github.com/starkware-libs/blockifier/blob/56f1a9617207988e7136bf8b0562f01feef2d629/crates/native_blockifier/src/py_state_diff.rs#L94)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We haven't yet started working on supporting `0.11` (Cairo 1.0 and new `Declare`).
We will deploy `0.11` for POTC, but it is hybrid: can also run Cairo 0 and `Declare`s of version 0.
</blockquote></details>

So, pass an empty map and revert to `From`?
___
*[`crates/native_blockifier/src/storage.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP7qtRR6LLBLDGzjIWu:-NP85pzK2xDcd1wTu4-i:b-efaokx) ([raw file](https://github.com/starkware-libs/blockifier/blob/0a10509df11df6b996585b9677de69dbc4a79052/crates/native_blockifier/src/storage.rs#L74)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because in `Blockifier._append_state_diff` (on `dev`), this rust method is called and a pythonic `StateDiff` instance is given as input to `PyStateDiff` here.
Since we don't want to add this field to the pythonic `StateDiff`, this needs to be passed separately.

Second option, on the python side, I can define
```
@marshmallow_dataclass.dataclass(frozen=True)
class PyStateDiff(StateDiff):
    declared_class_hash_to_class: Dict[int, str] = field(default_factory=dict)

    @classmethod
    def from_state_diff(cls, state_diff: StateDiff) -> "PyStateDiff":
        ...
```
and use it to pass a fitting object to rust.

WDYT?
</blockquote></details>

I'm confused, we're getting a Rust `PyStateDiff` here, and it _does_ contain the declared classes.
If it has to be coupled with the Pythonic `StateDiff`, I think we don't need to add them to `PyStateDiff` at all.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP7qtRR6LLBLDGzjIWu:-NP881GK3kuKtvzBCPqL:bkx79vy) ([raw file](https://github.com/starkware-libs/blockifier/blob/0a10509df11df6b996585b9677de69dbc4a79052/crates/native_blockifier/src/storage.rs#L74)):*
> I'm confused, we're getting a Rust PyStateDiff here
yes. from where? from python context. passed like this in python:
```
    def _append_state_diff(
        self,
        block_id: int,
        previous_block_id: int,
        state_diff: StateDiff,
        declared_class_hash_to_class: RawDeclaredClassMapping,
    ):
        """
        Appends the state diff corresponding to the given block number in the target storage.
        Raises an exception if the block number isn't the lastest one.
        """
        deployed_contract_class_definitions: List[Tuple[int, CompiledClassBase]] = []
        self.target_storage.append_state_diff(
            block_id=block_id,
            previous_block_id=previous_block_id,
            py_block_info=state_diff.block_info,
            py_state_diff=state_diff,
            declared_class_hash_to_class=declared_class_hash_to_class,
            _py_deployed_contract_class_definitions=deployed_contract_class_definitions,
        )
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP7qtRR6LLBLDGzjIWu:-NP88-M82G9VC_2qkqvp:b-1a7a1g) ([raw file](https://github.com/starkware-libs/blockifier/blob/0a10509df11df6b996585b9677de69dbc4a79052/crates/native_blockifier/src/storage.rs#L74)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> I'm confused, we're getting a Rust PyStateDiff here
yes. from where? from python context. passed like this in python:
```
    def _append_state_diff(
        self,
        block_id: int,
        previous_block_id: int,
        state_diff: StateDiff,
        declared_class_hash_to_class: RawDeclaredClassMapping,
    ):
        """
        Appends the state diff corresponding to the given block number in the target storage.
        Raises an exception if the block number isn't the lastest one.
        """
        deployed_contract_class_definitions: List[Tuple[int, CompiledClassBase]] = []
        self.target_storage.append_state_diff(
            block_id=block_id,
            previous_block_id=previous_block_id,
            py_block_info=state_diff.block_info,
            py_state_diff=state_diff,
            declared_class_hash_to_class=declared_class_hash_to_class,
            _py_deployed_contract_class_definitions=deployed_contract_class_definitions,
        )
```
</blockquote></details>

Assuming we're not adding the field to python's `StateDiff`, the line `py_state_diff=state_diff` won't work... right? or on the rust side, the `PyStateDiff` object won't have the declared classes map

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NP7qtRR6LLBLDGzjIWu:-NP8bC0U4_KhEWY4wv5E:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0a10509df11df6b996585b9677de69dbc4a79052/crates/native_blockifier/src/storage.rs#L74)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Right, so let's not add it to `PyStateDiff` as well (its sole existence is for _structural_ equivalence to `StateDiff`). Let's pass the mapping separately. 
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NPBRNrnE-ycRnkJ2Dn7:-NPBRNrnE-ycRnkJ2Dn8:bdxvqdw) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9952b226584f54bc76257b32d1cfaaeeb7f0537/crates/native_blockifier/src/storage.rs#L76)):*
> ```XML
>         declared_class_hash_to_class: HashMap<PyFelt, String>,
>         _py_deployed_contract_class_definitions: &PyAny,
>     ) -> NativeBlockifierResult<()> {
> ```

What I'd really like it a `try_from` equivalent from more than one input.
Or another c-tor! But a simple `impl` block isn't possible, since `StateDiff` is defined in another crate...
___
*[`crates/native_blockifier/src/storage.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NPBQnQz5IPL1jp3UPUL:-NPBQnQz5IPL1jp3UPUM:befsnco) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9952b226584f54bc76257b32d1cfaaeeb7f0537/crates/native_blockifier/src/storage.rs#L77)):*
> ```XML
>         _py_deployed_contract_class_definitions: &PyAny,
>     ) -> NativeBlockifierResult<()> {
>         let block_number = BlockNumber(py_block_info.block_number);
> ```

Mainly reordering and spacing.



_Suggestion:_
```XML
        let block_number = BlockNumber(py_block_info.block_number);

        // Deserialize contract classes.
        let mut declared_classes: IndexMap<ClassHash, ContractClass> = IndexMap::new();
        for (class_hash, raw_class) in declared_class_hash_to_class {
            let blockifier_contract_class: blockifier::execution::contract_class::ContractClass =
                serde_json::from_str(raw_class.as_str()).map_err(NativeBlockifierError::from)?;
            declared_classes
                .insert(ClassHash(class_hash.0), ContractClass::from(blockifier_contract_class));
        }
        
        // Construct state diff; manually add declared classes.
        let mut state_diff = StateDiff::try_from(py_state_diff)?;
        state_diff.declared_classes = declared_classes;
        let deployed_contract_class_definitions = IndexMap::<ClassHash, ContractClass>::new();
        
        let append_txn = self.writer.begin_rw_txn()?.append_state_diff(
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NPBRNrnE-ycRnkJ2Dn7:-NPBRxCz6fNmcCR2otNK:b-ucu8at) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9952b226584f54bc76257b32d1cfaaeeb7f0537/crates/native_blockifier/src/storage.rs#L76)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What I'd really like it a `try_from` equivalent from more than one input.
Or another c-tor! But a simple `impl` block isn't possible, since `StateDiff` is defined in another crate...
</blockquote></details>

Maybe a `TryFrom<(PyStateDiff, HashMap<PyFelt, String>)>`. Seems to work:

```rust
impl TryFrom<(PyStateDiff, HashMap<PyFelt, String>)> for StateDiff {
    type Error = NativeBlockifierError;

    fn try_from(inputs: (PyStateDiff, HashMap<PyFelt, String>)) -> NativeBlockifierResult<Self> {
        let (state_diff, declared_class_hash_to_class) = inputs;

        // Deserialize declared classes.
        let mut declared_classes: IndexMap<ClassHash, ContractClass> = IndexMap::new();
        for (class_hash, raw_class) in declared_class_hash_to_class {
            let blockifier_contract_class: blockifier::execution::contract_class::ContractClass =
                serde_json::from_str(raw_class.as_str()).map_err(NativeBlockifierError::from)?;
            declared_classes
                .insert(ClassHash(class_hash.0), ContractClass::from(blockifier_contract_class));
        }

        // Construct state diff; manually add declared classes.
        let mut state_diff = StateDiff::try_from(state_diff)?;
        state_diff.declared_classes = declared_classes;

        Ok(state_diff)
    }
}
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/301#-NPBRNrnE-ycRnkJ2Dn7:-NPBTiNT0hriBfYha_d9:b-g6illc) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9952b226584f54bc76257b32d1cfaaeeb7f0537/crates/native_blockifier/src/storage.rs#L76)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe a `TryFrom<(PyStateDiff, HashMap<PyFelt, String>)>`. Seems to work:

```rust
impl TryFrom<(PyStateDiff, HashMap<PyFelt, String>)> for StateDiff {
    type Error = NativeBlockifierError;

    fn try_from(inputs: (PyStateDiff, HashMap<PyFelt, String>)) -> NativeBlockifierResult<Self> {
        let (state_diff, declared_class_hash_to_class) = inputs;

        // Deserialize declared classes.
        let mut declared_classes: IndexMap<ClassHash, ContractClass> = IndexMap::new();
        for (class_hash, raw_class) in declared_class_hash_to_class {
            let blockifier_contract_class: blockifier::execution::contract_class::ContractClass =
                serde_json::from_str(raw_class.as_str()).map_err(NativeBlockifierError::from)?;
            declared_classes
                .insert(ClassHash(class_hash.0), ContractClass::from(blockifier_contract_class));
        }

        // Construct state diff; manually add declared classes.
        let mut state_diff = StateDiff::try_from(state_diff)?;
        state_diff.declared_classes = declared_classes;

        Ok(state_diff)
    }
}
```
</blockquote></details>

Okay, it doesn't work: `this is not defined in the current crate because tuples are always foreign`.
I hate it. Only with a wrapper to the tuple, but at this point it's not worth it...

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301#-:-NPBYr5e6RCVQVwsbVLe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/301)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
