### PR TITLE
Enforce minimal fee

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/684)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/684)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @noaov1 and @zuphitf)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZ1k1bo1XvDMx25Z5jP:-NZ1k1bp-VOmL6J--mVC:btypue2) ([raw file](https://github.com/starkware-libs/blockifier/blob/511b551650cb1135b7cd64cee5574566eb7496ab/crates/blockifier/src/fee/gas_usage.rs#L36)):*
> ```XML
>     + n_l2_to_l1_messages * eth_gas_constants::GAS_PER_ZERO_TO_NONZERO_STORAGE_SET
>     // StarkNet's updateState decreases a (storage) counter for each L1-to-L2 consumed message.
>     // (Note that we will probably get a refund of 15,000 gas for each consumed message but we 
> ```

how did this whitespace get here wtf

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/684)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZ5znooEIt0TbyXntQr:-NZ5znooEIt0TbyXntQs:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/895d7c760f89e231a0406bee5abf07009168f4a5/crates/blockifier/src/fee/gas_usage.rs#L145)):*
> ```XML
>     // Nonce increment + fee transfer change two storage cells on one contract.
>     let resources = ResourcesMapping(HashMap::from([
>         (constants::GAS_USAGE.to_string(), get_onchain_data_segment_length(1, 2, 0)),
> ```





_Suggestion:_
```XML
// Sender balance update (storage update) + nonce increment (contract modification) (we exclude the sequencer balance update and the ERC20 
// contract modification since it occurs fors every tx)
    let resources = ResourcesMapping(HashMap::from([
        (constants::GAS_USAGE.to_string(), get_onchain_data_segment_length(1, 1, 0)),
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 254 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZ5yId5BfiPxo6wGK8h:-NZ5yId5BfiPxo6wGK8i:b2ebw6i) ([raw file](https://github.com/starkware-libs/blockifier/blob/895d7c760f89e231a0406bee5abf07009168f4a5/crates/blockifier/src/transaction/account_transaction.rs#L254)):*
> ```XML
> 
>         // Check fee balance.
>         if self.enforce_fee() {
> ```

Why do we do that after incrementing the nonce?



_Code quote:_
```XML
if self.enforce_fee() {
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/684)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @zuphitf)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZ5znooEIt0TbyXntQr:-NZ6LSX5ESyq-Q5W97Q0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/895d7c760f89e231a0406bee5abf07009168f4a5/crates/blockifier/src/fee/gas_usage.rs#L145)):*
> ```XML
>     // Nonce increment + fee transfer change two storage cells on one contract.
>     let resources = ResourcesMapping(HashMap::from([
>         (constants::GAS_USAGE.to_string(), get_onchain_data_segment_length(1, 2, 0)),
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 254 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZ5yId5BfiPxo6wGK8h:-NZ6Lu1YBtRQ5lI-SBZf:b92vz5v) ([raw file](https://github.com/starkware-libs/blockifier/blob/895d7c760f89e231a0406bee5abf07009168f4a5/crates/blockifier/src/transaction/account_transaction.rs#L254)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why do we do that after incrementing the nonce?
</blockquote></details>

Done in separate PR, [PTAL](https://reviewable.io/reviews/starkware-libs/blockifier/696)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/684)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZ6giRc0iRfVBDV-BKk:-NZ6giRc0iRfVBDV-BKl:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0013d56d713e7da255ca0343f76a478da69c2aa5/crates/blockifier/src/fee/gas_usage.rs#L6)):*
> ```XML
> 
> use super::fee_utils::calculate_tx_fee;
> use super::os_resources::OS_RESOURCES;
> ```





_Suggestion:_
```XML
use crate::fee::fee_utils::calculate_tx_fee;
use crate::fee::os_resources::OS_RESOURCES;
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 144 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZPaaNo9dX0j07IaMFp:-NZPaaNo9dX0j07IaMFq:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0013d56d713e7da255ca0343f76a478da69c2aa5/crates/blockifier/src/fee/gas_usage.rs#L144)):*
> ```XML
> ) -> TransactionExecutionResult<Fee> {
>     // TODO(Dori, 1/8/2023): Give names to the constant VM step estimates and regression-test them.
>     let os_steps_for_type = OS_RESOURCES.execute_txs_inner().get(&tx.tx_type()).unwrap().n_steps;
> ```





_Suggestion:_
```XML
expect("OS_RESOURCES must contain all transaction types.")
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 148 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZPdfztB9Ttyfs9FOfN:-NZPdfztB9Ttyfs9FOfO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0013d56d713e7da255ca0343f76a478da69c2aa5/crates/blockifier/src/fee/gas_usage.rs#L148)):*
> ```XML
>         // Sender balance update (storage update) + nonce increment (contract modification) (we
>         // exclude the sequencer balance update and the ERC20 contract modification since it occurs
>         // for every tx).
> ```





_Suggestion:_
```XML
        // We consider the following state changes: sender balance update (storage update) + nonce increment (contract modification).
        // (we exclude the sequencer balance update and the ERC20 contract modification since it occurs
        // for every tx).
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZPcdnp5nQ8OpPFdrkZ:-NZPcdnp5nQ8OpPFdrk_:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0013d56d713e7da255ca0343f76a478da69c2aa5/crates/blockifier/src/fee/gas_usage.rs#L154)):*
> ```XML
>         AccountTransaction::DeployAccount(_) => (13, get_onchain_data_segment_length(1, 1, 1)),
>     };
>     let resources = ResourcesMapping(HashMap::from([
> ```





_Suggestion:_
```XML
// We assume that the n_steps is the heaviest resource.
let resources = ResourcesMapping(HashMap::from([
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 155 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZPbtXO2vdtkv3QDRyB:-NZPbtXO2vdtkv3QDRyC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0013d56d713e7da255ca0343f76a478da69c2aa5/crates/blockifier/src/fee/gas_usage.rs#L155)):*
> ```XML
>     };
>     let resources = ResourcesMapping(HashMap::from([
>         (constants::GAS_USAGE.to_string(), gas_for_type),
> ```





_Suggestion:_
```XML
 gas_for_type * eth_gas_constants::SHARP_GAS_PER_MEMORY_WORD
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/684)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @noaov1 and @zuphitf)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZ6giRc0iRfVBDV-BKk:-NZPrOjR-YHcyXCaB1om:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0013d56d713e7da255ca0343f76a478da69c2aa5/crates/blockifier/src/fee/gas_usage.rs#L6)):*
> ```XML
> 
> use super::fee_utils::calculate_tx_fee;
> use super::os_resources::OS_RESOURCES;
> ```

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 144 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZPaaNo9dX0j07IaMFp:-NZPrU3O7LIWrVN1KYHd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0013d56d713e7da255ca0343f76a478da69c2aa5/crates/blockifier/src/fee/gas_usage.rs#L144)):*
> ```XML
> ) -> TransactionExecutionResult<Fee> {
>     // TODO(Dori, 1/8/2023): Give names to the constant VM step estimates and regression-test them.
>     let os_steps_for_type = OS_RESOURCES.execute_txs_inner().get(&tx.tx_type()).unwrap().n_steps;
> ```

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 148 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZPdfztB9Ttyfs9FOfN:-NZPrbVo8J0GIVRtHU5Y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0013d56d713e7da255ca0343f76a478da69c2aa5/crates/blockifier/src/fee/gas_usage.rs#L148)):*
> ```XML
>         // Sender balance update (storage update) + nonce increment (contract modification) (we
>         // exclude the sequencer balance update and the ERC20 contract modification since it occurs
>         // for every tx).
> ```

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZPcdnp5nQ8OpPFdrkZ:-NZPrgQo6lRsNLlxcTxA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0013d56d713e7da255ca0343f76a478da69c2aa5/crates/blockifier/src/fee/gas_usage.rs#L154)):*
> ```XML
>         AccountTransaction::DeployAccount(_) => (13, get_onchain_data_segment_length(1, 1, 1)),
>     };
>     let resources = ResourcesMapping(HashMap::from([
> ```

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 155 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/684#-NZPbtXO2vdtkv3QDRyB:-NZPrlwG2Dy9_xgLErtp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0013d56d713e7da255ca0343f76a478da69c2aa5/crates/blockifier/src/fee/gas_usage.rs#L155)):*
> ```XML
>     };
>     let resources = ResourcesMapping(HashMap::from([
>         (constants::GAS_USAGE.to_string(), gas_for_type),
> ```

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/684#-:-NZQ1-_c8NNt6EQTW8SS:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @zuphitf)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/684)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
