### PR TITLE
test: remove redandant use of test util

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1604)

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1604)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 471 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1604#-NrqTLda7oB_qGxPH583:-NrqTLdbDU5iJ_qkS9ER:b1ge88l) ([raw file](https://github.com/starkware-libs/blockifier/blob/175e88054c830e6b7ae32d917967c96cd64dedd3/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L471)):*
> ```XML
>     let entry_point_call = CallEntryPoint {
>         entry_point_selector,
>         code_address: None,
> ```

The test passes even if we use `test_contract_address` as the code address, but I wanted the test to make the least amount of assumptions.



_Code quote:_
```XML
code_address: None,
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1604#-:-NrtZE1-C1lrDzCmxeav:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1604)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1604#-Nrw1v-SE-y4VduSTGSk:-Nrw1v-TED_ShWocyoRa:bn8jds3) (no related file):*
Re approve PLZ

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1604#-:-NryI-5m-VPMMEQqx-gj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1604)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
