### PR TITLE
impl Merge for CachedState

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/302)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/302)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP4PQyn3ToOcbCU7hT8:-NP4PQyn3ToOcbCU7hT9:b-h2omgq) (no related file):*
How should two `CachedState` objects with `PapyrusStateReader` readers merge?
My guess:
1. Set `latest_block` to max of `self` and `other`.
2. Assert `self.reader.txn` is equal to `other`'s (because this look to me like DB configuration detail...?).
3. Iterate over all entries of `other.reader.X` (where `X` is a `TableHandle`) and add them to `self`.

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/302)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP4PQyn3ToOcbCU7hT8:-NP4VyS30h03ITeLVQAX:b-rvj141) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

How should two `CachedState` objects with `PapyrusStateReader` readers merge?
My guess:
1. Set `latest_block` to max of `self` and `other`.
2. Assert `self.reader.txn` is equal to `other`'s (because this look to me like DB configuration detail...?).
3. Iterate over all entries of `other.reader.X` (where `X` is a `TableHandle`) and add them to `self`.
</blockquote></details>

(3) doesn't seem possible without changing papyrus, the DBs are private ATM (only getters are exposed)

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/302)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP4PQyn3ToOcbCU7hT8:-NP7ysRd2n1oRU30qa6l:b-ji7j06) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

(3) doesn't seem possible without changing papyrus, the DBs are private ATM (only getters are exposed)
</blockquote></details>

Readers are not changed, they're immutable (except maybe caches) and updated from Python (using `append_state_diff`).

___
___
*[`crates/blockifier/src/utils.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP7vm1ZAmthQbOF8jav:-NP7vm1ZAmthQbOF8jaw:b-ad9g4z) ([raw file](https://github.com/starkware-libs/blockifier/blob/1961bb36c55fd0d809a6f41f9e9c4006b924c075/crates/blockifier/src/utils.rs#L18)):*
> ```XML
> }
> 
> pub trait Merge {
> ```

Why is a trait needed?
Let's only implement for `CachedState`, since it's the only type that will be using it. 



_Code quote:_
```XML
pub trait Merge
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP7xohq3TJTYKF7HvP0:-NP7xohq3TJTYKF7HvP1:b-5grs64) ([raw file](https://github.com/starkware-libs/blockifier/blob/1961bb36c55fd0d809a6f41f9e9c4006b924c075/crates/blockifier/src/state/cached_state.rs#L25)):*
> ```XML
> /// initialization.
> #[derive(Debug, Default)]
> pub struct CachedState<S: StateReader + Merge> {
> ```

No need; the inner `state` doesn't need it.
- In the block level, we have `CachedState<PapyrusStateReader>`. Merging writes into the reader is not actually done, but instead we take the state diff.
- In the transaction level, we have `CachedState<CachedState<PapyrusStateReader>>` (to be able to drop the writes of the external wrapper if the transaction fails mid-way). In this case we merge the external cached state into the internal one (which implements `State`).

So a merge is never done on a reader. 



_Code quote:_
```XML
S: StateReader + Merge
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP7yaZ_DbqdWW3cP8iV:-NP7yaZ_DbqdWW3cP8iW:bn65u8o) ([raw file](https://github.com/starkware-libs/blockifier/blob/1961bb36c55fd0d809a6f41f9e9c4006b924c075/crates/blockifier/src/state/cached_state.rs#L39)):*
> ```XML
> 
> impl<S: StateReader + Merge> Merge for CachedState<S> {
>     fn merge(&mut self, other: Self) {
> ```

To express the face that we always merge an extension (lazy copy) of an existing state into its origin (or parent).



_Suggestion:_
```XML
child
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP7wdTM15zv4d1tZ3vR:-NP7wdTM15zv4d1tZ3vS:b-86850l) ([raw file](https://github.com/starkware-libs/blockifier/blob/1961bb36c55fd0d809a6f41f9e9c4006b924c075/crates/blockifier/src/state/cached_state.rs#L214)):*
> ```XML
> }
> 
> impl Merge for StateCache {
> ```

For `StateCache`, only the writes should be updated.
The initial values are kept for resource calculation (to recognize changes like `0 -> 5 -> 0` that got cancelled out, so no need to count them).
Perhaps it's not an actual merge here, let's rename to `fn merge_writes(&mut self, child: StateCache)`.



_Code quote:_
```XML
impl Merge for StateCache
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/302)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP4PQyn3ToOcbCU7hT8:-NP84jnp7tMB8y4Iwqda:b2k3xw8) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Readers are not changed, they're immutable (except maybe caches) and updated from Python (using `append_state_diff`).
</blockquote></details>

OK, so IIUC, in `CachedState::merge`:
1. `state` is untouched
2. `cache` is merged
3. `class_hash_to_class` is merged
right?

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/302)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/state/cached_state.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP7xohq3TJTYKF7HvP0:-NP86VOe6fZh076ytUFT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1961bb36c55fd0d809a6f41f9e9c4006b924c075/crates/blockifier/src/state/cached_state.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No need; the inner `state` doesn't need it.
- In the block level, we have `CachedState<PapyrusStateReader>`. Merging writes into the reader is not actually done, but instead we take the state diff.
- In the transaction level, we have `CachedState<CachedState<PapyrusStateReader>>` (to be able to drop the writes of the external wrapper if the transaction fails mid-way). In this case we merge the external cached state into the internal one (which implements `State`).

So a merge is never done on a reader. 
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP7wdTM15zv4d1tZ3vR:-NP86Zfh27NuZCAAQU9L:begdi4g) ([raw file](https://github.com/starkware-libs/blockifier/blob/1961bb36c55fd0d809a6f41f9e9c4006b924c075/crates/blockifier/src/state/cached_state.rs#L214)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

For `StateCache`, only the writes should be updated.
The initial values are kept for resource calculation (to recognize changes like `0 -> 5 -> 0` that got cancelled out, so no need to count them).
Perhaps it's not an actual merge here, let's rename to `fn merge_writes(&mut self, child: StateCache)`.
</blockquote></details>

Removed functionality from cache completely
___
*[`crates/blockifier/src/utils.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP7vm1ZAmthQbOF8jav:-NP86UaQ6VBe4SkLXkqn:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1961bb36c55fd0d809a6f41f9e9c4006b924c075/crates/blockifier/src/utils.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is a trait needed?
Let's only implement for `CachedState`, since it's the only type that will be using it. 

</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/302)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP4PQyn3ToOcbCU7hT8:-NP86yIC6XUyPNmOwbBN:b-t5z859) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

OK, so IIUC, in `CachedState::merge`:
1. `state` is untouched
2. `cache` is merged
3. `class_hash_to_class` is merged
right?
</blockquote></details>

Yes. :)

___
___
*[`crates/blockifier/src/state/cached_state.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/302#-NP86nyO98m2AS4Nx2EF:-NP86nyO98m2AS4Nx2EG:b-uzvgbz) ([raw file](https://github.com/starkware-libs/blockifier/blob/59fdbc741ff32ff40fbbe7ec5fc62e13e10ce2dc/crates/blockifier/src/state/cached_state.rs#L39)):*
> ```XML
>     pub fn merge(&mut self, child: Self) {
>         self.cache.nonce_writes.extend(child.cache.nonce_writes);
>         self.cache.class_hash_writes.extend(child.cache.class_hash_writes);
> ```

Consider a `for`, if it doesn't hurt readability.



_Code quote:_
```XML
        self.cache.nonce_writes.extend(child.cache.nonce_writes);
        self.cache.class_hash_writes.extend(child.cache.class_hash_writes);
        self.cache.storage_writes.extend(child.cache.storage_writes);
```

**Pull request merged**
