### PR TITLE
test(concurrency): add the method of the logic for the commit tx test

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1923)

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8PHSxE1o2uyHs2Z4X:-Nz8PHSyBZ9bhwd0Vr2i:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c522027ffcd8c9675a26a174a13cc7e6794c35/crates/blockifier/src/concurrency/worker_logic_test.rs#L144)):*
> ```XML
> }
> 
> fn _subtract_with_overflow(a_low: u128, a_high: u128, b_low: u128, b_high: u128) -> (u128, u128) {
> ```





_Suggestion:_
```XML
fn _subtract_with_underflow(a_low: u128, a_high: u128, b_low: u128, b_high: u128) -> (u128, u128) {
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 147 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8PVx0AW4wSGkRDS9C:-Nz8PVx0AW4wSGkRDS9D:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c522027ffcd8c9675a26a174a13cc7e6794c35/crates/blockifier/src/concurrency/worker_logic_test.rs#L147)):*
> ```XML
>     let (low, overflow) = a_low.overflowing_sub(b_low);
>     let high = a_high.wrapping_sub(b_high).wrapping_sub(overflow.into());
>     (low, high)
> ```





_Suggestion:_
```XML
    let (low, underflow) = a_low.overflowing_sub(b_low);
    let high = a_high.wrapping_sub(b_high).wrapping_sub(underflow.into());
    (low, high)
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8QMdV9fMsspRgBCzp:-Nz8QMdV9fMsspRgBCzq:bg5ieg9) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c522027ffcd8c9675a26a174a13cc7e6794c35/crates/blockifier/src/concurrency/worker_logic_test.rs#L156)):*
> ```XML
> }
> 
> fn _check_pre_commit_tx<S: StateReader>(
> ```

Please document the list of checks this function does in a docstring.



_Suggestion:_
```XML
fn _pre_commit_tx_checks<S: StateReader>(
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 182 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8Qo-fCMDNjN5mTpYp:-Nz8Qo-fCMDNjN5mTpYq:bg5ieg9) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c522027ffcd8c9675a26a174a13cc7e6794c35/crates/blockifier/src/concurrency/worker_logic_test.rs#L182)):*
> ```XML
> }
> 
> fn _check_post_commit_tx<S: StateReader>(
> ```

Please document the list of checks this function does in a docstring.



_Suggestion:_
```XML
fn _post_commit_tx_checks<S: StateReader>(
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 198 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8RJBRCy2ZoTIRqtFN:-Nz8RJBRCy2ZoTIRqtFO:b-fvmotd) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c522027ffcd8c9675a26a174a13cc7e6794c35/crates/blockifier/src/concurrency/worker_logic_test.rs#L198)):*
> ```XML
>     let execution_result = &execution_task_outputs.as_ref().unwrap().result;
>     if !should_fail {
>         // Check that fill_sequencer_balance_reads worked after commit.
> ```

Try not to use function names in comments. The name of the function might change in the future, and the person that changed it will not notice the name was used in a comment as well.



_Suggestion:_
```XML
       // Check that the sequencer balance reads were updated after commit.
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1923)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8PHSxE1o2uyHs2Z4X:-Nz8d9RQAuEdreuJ3XSR:b-88pzgl) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c522027ffcd8c9675a26a174a13cc7e6794c35/crates/blockifier/src/concurrency/worker_logic_test.rs#L144)):*
> ```XML
> }
> 
> fn _subtract_with_overflow(a_low: u128, a_high: u128, b_low: u128, b_high: u128) -> (u128, u128) {
> ```

It's no longer relevant because we assume the account balance can be represented as u128.  
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 147 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8PVx0AW4wSGkRDS9C:-Nz8dVv534KYjbBnnUzp:b-88pzgl) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c522027ffcd8c9675a26a174a13cc7e6794c35/crates/blockifier/src/concurrency/worker_logic_test.rs#L147)):*
> ```XML
>     let (low, overflow) = a_low.overflowing_sub(b_low);
>     let high = a_high.wrapping_sub(b_high).wrapping_sub(overflow.into());
>     (low, high)
> ```

It's no longer relevant because we assume the account balance can be represented as u128.  
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8QMdV9fMsspRgBCzp:-Nz8nfc97xxeHgZJ_8C-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c522027ffcd8c9675a26a174a13cc7e6794c35/crates/blockifier/src/concurrency/worker_logic_test.rs#L156)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Please document the list of checks this function does in a docstring.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 182 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8Qo-fCMDNjN5mTpYp:-Nz8ng9L97MdHREXrIwQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c522027ffcd8c9675a26a174a13cc7e6794c35/crates/blockifier/src/concurrency/worker_logic_test.rs#L182)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Please document the list of checks this function does in a docstring.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 198 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8RJBRCy2ZoTIRqtFN:-Nz8nh639ysoCmzRbVbe:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c522027ffcd8c9675a26a174a13cc7e6794c35/crates/blockifier/src/concurrency/worker_logic_test.rs#L198)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Try not to use function names in comments. The name of the function might change in the future, and the person that changed it will not notice the name was used in a comment as well.
</blockquote></details>

Done.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8sIwJ7BPdmqXh_7T0:-Nz8sIwKA6TcFi8GGbPU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5acdce5d0ed6d3eccc03af814100d50ebf33b68b/crates/blockifier/src/concurrency/worker_logic_test.rs#L154)):*
> ```XML
> // then that the actual fee was subtracted from the account balance
> // and that the sequencer balance remained the same.
> fn _pre_commit_tx_check<S: StateReader>(
> ```





_Suggestion:_
```XML
// This function checks the state of a transaction after execution and before commit.
// It verifies that the actual fee was subtracted from the account balance
// and that the sequencer balance remained the same.
fn _pre_commit_tx_checks<S: StateReader>(
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1923)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 185 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8spja1mf5-qzUL3e2:-Nz8spja1mf5-qzUL3e3:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5acdce5d0ed6d3eccc03af814100d50ebf33b68b/crates/blockifier/src/concurrency/worker_logic_test.rs#L185)):*
> ```XML
> // fee transfer callinfo was filled correctly,
> // and lastly, the actual fee was subtracted from the account balance
> // and added to the sequencer balance.
> ```





_Suggestion:_
```XML
// This function checks the state of a transaction after committing.
// It checks that the storage read of the sequencer balance in the
// fee transfer callinfo was filled correctly,
// It additionally checks that the actual fee was subtracted from the account balance
// and added to the sequencer balance.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 186 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8tTDl5sTdBPoEg3Mr:-Nz8tTDl5sTdBPoEg3Ms:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5acdce5d0ed6d3eccc03af814100d50ebf33b68b/crates/blockifier/src/concurrency/worker_logic_test.rs#L186)):*
> ```XML
> // and lastly, the actual fee was subtracted from the account balance
> // and added to the sequencer balance.
> fn _post_commit_tx_check<S: StateReader>(
> ```





_Suggestion:_
```XML
fn _post_commit_tx_checks<S: StateReader>(
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1923)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8sIwJ7BPdmqXh_7T0:-NzMi-8KAUuYIfTsnsy9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5acdce5d0ed6d3eccc03af814100d50ebf33b68b/crates/blockifier/src/concurrency/worker_logic_test.rs#L154)):*
> ```XML
> // then that the actual fee was subtracted from the account balance
> // and that the sequencer balance remained the same.
> fn _pre_commit_tx_check<S: StateReader>(
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 185 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8spja1mf5-qzUL3e2:-NzMi1E26RXu9oRqIK-0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5acdce5d0ed6d3eccc03af814100d50ebf33b68b/crates/blockifier/src/concurrency/worker_logic_test.rs#L185)):*
> ```XML
> // fee transfer callinfo was filled correctly,
> // and lastly, the actual fee was subtracted from the account balance
> // and added to the sequencer balance.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 186 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-Nz8tTDl5sTdBPoEg3Mr:-NzMi1io6dJI5kQ9MsSd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5acdce5d0ed6d3eccc03af814100d50ebf33b68b/crates/blockifier/src/concurrency/worker_logic_test.rs#L186)):*
> ```XML
> // and lastly, the actual fee was subtracted from the account balance
> // and added to the sequencer balance.
> fn _post_commit_tx_check<S: StateReader>(
> ```

Done.

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-:-NzMqNGcDYFQ_ofyWY_H:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1923)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 153 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-NzT5RsF-J9OeFKF2MjK:-NzT5RsF-J9OeFKF2MjL:b-cd2dtl) ([raw file](https://github.com/starkware-libs/blockifier/blob/87086436f75f3a88ce9ebaaa1f58d055e629f2a2/crates/blockifier/src/concurrency/worker_logic_test.rs#L153)):*
> ```XML
> // It verifies that the actual fee was subtracted from the account balance
> // and that the sequencer balance remained the same.
> fn _pre_commit_tx_checks<S: StateReader>(
> ```

Not needed



_Code quote:_
```XML
fn _pre_commit_tx_checks<S: StateReader>(
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 183 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-NzT5VO79UxISGCmL2WY:-NzT5VO79UxISGCmL2WZ:b-fmzqb0) ([raw file](https://github.com/starkware-libs/blockifier/blob/87086436f75f3a88ce9ebaaa1f58d055e629f2a2/crates/blockifier/src/concurrency/worker_logic_test.rs#L183)):*
> ```XML
> // fee transfer callinfo was filled correctly,
> // It additionally checks that the actual fee was subtracted from the account balance
> // and added to the sequencer balance.
> ```

`checks that the actual fee was subtracted from the account balance`- Is it needed?



_Suggestion:_
```XML
/// Checks the state of a transaction after committing.
/// It checks that the storage read of the sequencer balance in the
/// fee transfer call info was filled correctly,
/// It additionally checks that the actual fee was subtracted from the account balance
/// and added to the sequencer balance.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 198 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-NzOFwklDjW0RLDhVspm:-NzOFwklDjW0RLDhVspn:b-3mi89e) ([raw file](https://github.com/starkware-libs/blockifier/blob/87086436f75f3a88ce9ebaaa1f58d055e629f2a2/crates/blockifier/src/concurrency/worker_logic_test.rs#L198)):*
> ```XML
>     // Extract the actual fee. If the transaction fails, no fee should be charged.
>     let actual_fee = if should_fail { 0 } else { execution_result.as_ref().unwrap().actual_fee.0 };
>     let execution_result = &execution_task_outputs.as_ref().unwrap().result;
> ```

Already defined, no?



_Code quote:_
```XML
    let execution_result = &execution_task_outputs.as_ref().unwrap().result;
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1923)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 153 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-NzT5RsF-J9OeFKF2MjK:-NzWsDiE87C7fx5FGdvA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/87086436f75f3a88ce9ebaaa1f58d055e629f2a2/crates/blockifier/src/concurrency/worker_logic_test.rs#L153)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not needed
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 183 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-NzT5VO79UxISGCmL2WY:-NzWsK4R5domILIvFT5C:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/87086436f75f3a88ce9ebaaa1f58d055e629f2a2/crates/blockifier/src/concurrency/worker_logic_test.rs#L183)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

`checks that the actual fee was subtracted from the account balance`- Is it needed?
</blockquote></details>

Done.

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1923)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 116 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-NzYi5gsCalIZV1_pfTf:-NzYi5gsCalIZV1_pfTg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b74bb2fe1e06d4a0f3dcc8c4b45d0a76d08515c/crates/blockifier/src/concurrency/worker_logic_test.rs#L116)):*
> ```XML
> /// fee transfer call info was filled correctly,
> /// It additionally checks that the actual fee was subtracted from the account balance
> /// and added to the sequencer balance.
> ```





_Suggestion:_
```XML
/// Commits a transaction and then performs the following checks on the state:
/// 1. The storage read of the sequencer balance in the fee transfer call info was filled correctly.
/// 2. The actual fee was subtracted from the account balance and added to the sequencer balance.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 117 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1923#-NzYhuTZDUSaUFxLXu8o:-NzYhuTZDUSaUFxLXu8p:bruz16w) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b74bb2fe1e06d4a0f3dcc8c4b45d0a76d08515c/crates/blockifier/src/concurrency/worker_logic_test.rs#L117)):*
> ```XML
> /// It additionally checks that the actual fee was subtracted from the account balance
> /// and added to the sequencer balance.
> fn _commit_and_validate<S: StateReader>(
> ```

"validate" is an overloaded word in the concurrency module.



_Suggestion:_
```XML
fn _commit_and_check_the_state<S: StateReader>(
```

**Pull request closed without merging**
