### PR TITLE
fix: bug - os kzg resources is not zero in old versions

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1942)

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1942)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @avi-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1942#-NzOCG8x5sVtwb1Hu_XI:-NzOCG8y6gggrHbeXpCn:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/a112f6bf20633a6ac2811f14da38c9e2bd334f89/crates/blockifier/src/versioned_constants.rs#L379)):*
> ```XML
>     fn os_kzg_da_resources(&self, data_segment_length: usize) -> ExecutionResources {
>         // TODO(Avi, 15/6/2026): BACKWARD COMPATIBILITY: we set compute_os_kzg_commitment_info to
>         // empty in older versions where this was not yet computed.
> ```

WDYM?



_Code quote:_
```XML
        // TODO(Avi, 15/6/2026): BACKWARD COMPATIBILITY: we set compute_os_kzg_commitment_info to
        // empty in older versions where this was not yet computed.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1942#-NzOCOXG8yOkHGiUZGP9:-NzOCOXH6yswxTM98qXd:b-e9xtbb) ([raw file](https://github.com/starkware-libs/blockifier/blob/a112f6bf20633a6ac2811f14da38c9e2bd334f89/crates/blockifier/src/versioned_constants.rs#L381)):*
> ```XML
>         // empty in older versions where this was not yet computed.
>         let empty_resources = ExecutionResources::default();
>         if self.compute_os_kzg_commitment_info == empty_resources {
> ```

@Yoni-Starkware - Is there a scenario where the constant resources are zero but we want to add the poseidon cost?



_Code quote:_
```XML
        if self.compute_os_kzg_commitment_info == empty_resources {
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1942)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1942#-NzOCG8x5sVtwb1Hu_XI:-NzOCgUo-ulDI7IGDlIz:b-8it99u) ([raw file](https://github.com/starkware-libs/blockifier/blob/a112f6bf20633a6ac2811f14da38c9e2bd334f89/crates/blockifier/src/versioned_constants.rs#L379)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

As we discussed, these resources were not computed in 0.13.1, so we had to put `ExecutionResources::default()` in `compute_os_kzg_commitment_info` in older versions after we added this computation for backward compatibility.

Did I not understand correctly?

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1942)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @avi-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1942#-NzOCG8x5sVtwb1Hu_XI:-NzOdGm07RYRPgVvOUBi:bseky0o) ([raw file](https://github.com/starkware-libs/blockifier/blob/a112f6bf20633a6ac2811f14da38c9e2bd334f89/crates/blockifier/src/versioned_constants.rs#L379)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

As we discussed, these resources were not computed in 0.13.1, so we had to put `ExecutionResources::default()` in `compute_os_kzg_commitment_info` in older versions after we added this computation for backward compatibility.

Did I not understand correctly?
</blockquote></details>

You are right. What's let to do? Why is there a TODO?

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1942)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1942#-NzOCG8x5sVtwb1Hu_XI:-NzOnsFw9XaIUWPfBFLB:b-nfxkyg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a112f6bf20633a6ac2811f14da38c9e2bd334f89/crates/blockifier/src/versioned_constants.rs#L379)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You are right. What's let to do? Why is there a TODO?
</blockquote></details>

It is just a practice we had in the Python repo. Add a TODO whenever something is happening due to backward compatibility, so that we will be able to easily remove it if we no longer need the backward compatibility for some reason.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1942#-NzOCG8x5sVtwb1Hu_XI:-NzTM4gy4r06Cg3MdBf7:bplnm4y) ([raw file](https://github.com/starkware-libs/blockifier/blob/a112f6bf20633a6ac2811f14da38c9e2bd334f89/crates/blockifier/src/versioned_constants.rs#L379)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

It is just a practice we had in the Python repo. Add a TODO whenever something is happening due to backward compatibility, so that we will be able to easily remove it if we no longer need the backward compatibility for some reason.
</blockquote></details>

I removed the TODO but kept the comment.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1942#-:-NzTNMn62vNwXCYEhKqs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @avi-starkware, and @Yoni-Starkware)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1942#-NzOCOXG8yOkHGiUZGP9:-NzTTFtq7wqHbq4uelnm:bou4w6o) ([raw file](https://github.com/starkware-libs/blockifier/blob/a112f6bf20633a6ac2811f14da38c9e2bd334f89/crates/blockifier/src/versioned_constants.rs#L381)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@Yoni-Starkware - Is there a scenario where the constant resources are zero but we want to add the poseidon cost?
</blockquote></details>

Yoni said it's okay

**Pull request merged**
