### PR TITLE
test(concurrency): unit test the scheduler

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1792)

### CODE REVIEW

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1792)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvaoH2M1B2lSd5zxmIE:-NvfwqSyDCF3b6sG_Q5F:bm498zf) ([raw file](https://github.com/starkware-libs/blockifier/blob/b20b747aa2c0d0082f46beab40dcddad0340e9aa/crates/blockifier/src/concurrency/scheduler.rs#L145)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

How can we test for an overflow?
</blockquote></details>

I added an assert to make sure there was no overflow.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvakQkH78JrO36Tk-l3:-Nvfx-HF486wL-OOAtAW:b-4zsxeo) ([raw file](https://github.com/starkware-libs/blockifier/blob/b20b747aa2c0d0082f46beab40dcddad0340e9aa/crates/blockifier/src/concurrency/scheduler_test.rs#L105)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We assume the decrease counter is changed even if we did not decrease the execution index. Can you please add a documentation in the relevant method?
</blockquote></details>

I made it so that the decrease counter is only increased if the value is actually decreased.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1792)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvakQkH78JrO36Tk-l3:-Nvg9ul2BIFjyjse1kgb:b-o4qr87) ([raw file](https://github.com/starkware-libs/blockifier/blob/b20b747aa2c0d0082f46beab40dcddad0340e9aa/crates/blockifier/src/concurrency/scheduler_test.rs#L105)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I made it so that the decrease counter is only increased if the value is actually decreased.
</blockquote></details>

Can you please explain why? It does not seems to be the case in the paper.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvakQkH78JrO36Tk-l3:-NvgSvOp4jkbZJ1iEWEf:bu521qk) ([raw file](https://github.com/starkware-libs/blockifier/blob/b20b747aa2c0d0082f46beab40dcddad0340e9aa/crates/blockifier/src/concurrency/scheduler_test.rs#L105)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain why? It does not seems to be the case in the paper.
</blockquote></details>

The only use of the decrease counter is in the `check_done` method. It is used to ensure that no new tasks are created after we check that `validation_index` and execution_index` are both above the `chunk_size` and `n_active_tasks` is 0. The only case where incrementing the decrease counter could result in a task being created is when either `execution_index` or `validation_index` have been decreased below `chunk_size`. Since both indices were greater than `chunk_size` before incrementing the counter, this implies that one of these indices must have actually been decreased when the counter was incremented. Therefore, there is no need to increment the counter when no index has actually decreased.

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1792)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvkKCW_D8LtTm4cuJl1):*




_Suggestion:_
```
test(concurrency): unit test the scheduler
```
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvaoH2M1B2lSd5zxmIE:-NvkLOv35bVr5TB0BR6c:bpyi7bz) ([raw file](https://github.com/starkware-libs/blockifier/blob/b20b747aa2c0d0082f46beab40dcddad0340e9aa/crates/blockifier/src/concurrency/scheduler.rs#L145)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I added an assert to make sure there was no overflow.
</blockquote></details>

What is the flow that might cause it?
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvkKVBj3rGTCmMaMKt8:-NvkKVBk9kfNaTMpibhz:bhj1gdp) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e2e3d45fdfebe68d437afa338563c9b210bb7c8/crates/blockifier/src/concurrency/scheduler.rs#L112)):*
> ```XML
>         if target_index < previous_validation_index {
>             self.decrease_counter.fetch_add(1, Ordering::SeqCst);
>         }
> ```

Can you explain why this is the desired behavior?



_Code quote:_
```XML
        let previous_validation_index =
            self.validation_index.fetch_min(target_index, Ordering::SeqCst);
        if target_index < previous_validation_index {
            self.decrease_counter.fetch_add(1, Ordering::SeqCst);
        }
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvakQkH78JrO36Tk-l3:-NvkMjXOD_doAjPfgTeH:b2k9seh) ([raw file](https://github.com/starkware-libs/blockifier/blob/b20b747aa2c0d0082f46beab40dcddad0340e9aa/crates/blockifier/src/concurrency/scheduler_test.rs#L105)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

The only use of the decrease counter is in the `check_done` method. It is used to ensure that no new tasks are created after we check that `validation_index` and execution_index` are both above the `chunk_size` and `n_active_tasks` is 0. The only case where incrementing the decrease counter could result in a task being created is when either `execution_index` or `validation_index` have been decreased below `chunk_size`. Since both indices were greater than `chunk_size` before incrementing the counter, this implies that one of these indices must have actually been decreased when the counter was incremented. Therefore, there is no need to increment the counter when no index has actually decreased.
</blockquote></details>

I would like to talk about it f2f (:
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvkLwbU32lXa2WuBgTO:-NvkLwbU32lXa2WuBgTP:b-84vyxn) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e2e3d45fdfebe68d437afa338563c9b210bb7c8/crates/blockifier/src/concurrency/scheduler_test.rs#L47)):*
> ```XML
>     scheduler.check_done();
>     assert_eq!(scheduler.done_marker.load(Ordering::Acquire), expected);
> }
> ```

Like!



_Code quote:_
```XML
#[rstest]
#[case::done(DEFAULT_CHUNK_SIZE, DEFAULT_CHUNK_SIZE, 0, true)]
#[case::active_tasks(DEFAULT_CHUNK_SIZE, DEFAULT_CHUNK_SIZE, 1, false)]
#[case::execution_incomplete(DEFAULT_CHUNK_SIZE-1, DEFAULT_CHUNK_SIZE+1, 0, false)]
#[case::validation_incomplete(DEFAULT_CHUNK_SIZE, DEFAULT_CHUNK_SIZE-1, 0, false)]
fn test_check_done(
    #[case] execution_index: usize,
    #[case] validation_index: usize,
    #[case] n_active_tasks: usize,
    #[case] expected: bool,
) {
    let scheduler = default_scheduler!(
        chunk_size: DEFAULT_CHUNK_SIZE,
        execution_index: execution_index,
        validation_index: validation_index,
        n_active_tasks: n_active_tasks
    );
    scheduler.check_done();
    assert_eq!(scheduler.done_marker.load(Ordering::Acquire), expected);
}
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvkNpMXDNLwqzY6POi4:-NvkNpMXDNLwqzY6POi5:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e2e3d45fdfebe68d437afa338563c9b210bb7c8/crates/blockifier/src/concurrency/scheduler_test.rs#L110)):*
> ```XML
> #[rstest]
> #[case::ready(1, Some(1), 1)]
> #[case::index_out_of_bounds(DEFAULT_CHUNK_SIZE, None, 0)]
> ```





_Suggestion:_
```XML
#[case::from_ready_to_execute_to_executing(0, Some(0), 1)]
#[case::index_out_of_bounds(DEFAULT_CHUNK_SIZE, None, 0)]
#[should_panic(expected = "n_active_tasks underflowed)]
#[case::...(...)]
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvkPwzi2kTA1akNUk2h:-NvkPwzi2kTA1akNUk2i:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e2e3d45fdfebe68d437afa338563c9b210bb7c8/crates/blockifier/src/concurrency/scheduler_test.rs#L123)):*
> ```XML
> #[rstest]
> #[case::some(1, Some(1), 2, 1)]
> #[case::none(DEFAULT_CHUNK_SIZE, None, DEFAULT_CHUNK_SIZE, 0)]
> ```





_Suggestion:_
```XML
#[case::some(1, Some(1), 2, 1)]
#[case::none(DEFAULT_CHUNK_SIZE, None, DEFAULT_CHUNK_SIZE, 0)]
#[should_panic(expected = "n_active_tasks underflowed)]
#[case::...(...)]
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvkKVBj3rGTCmMaMKt8:-NvkTqjz3IuX-f9QGKTw:br0jytw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e2e3d45fdfebe68d437afa338563c9b210bb7c8/crates/blockifier/src/concurrency/scheduler.rs#L112)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Can you explain why this is the desired behavior?
</blockquote></details>

See explanation [here](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvakQkH78JrO36Tk-l3).

Note that this is probably just a temporary feature until we implement the commit mechanism. Once we can commit transactions, there is no reason for `check_done` (we are done when all transactions are committed), and without `check_done` there is no reason to maintain the `decrease_counter` (nor `n_active_tasks`...).

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvaoH2M1B2lSd5zxmIE:-NvkUjJ_DKnCPYT8n8_2:bbcr4bz) ([raw file](https://github.com/starkware-libs/blockifier/blob/b20b747aa2c0d0082f46beab40dcddad0340e9aa/crates/blockifier/src/concurrency/scheduler.rs#L145)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

What is the flow that might cause it?
</blockquote></details>

I don't know. But we want to make sure this doesn't happen, since it will cause the done_marker to always be false.

Note that, as explained in the [previous discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvkKVBj3rGTCmMaMKt8), we will probably not need `n_active_tasks` once we have a mechanism for committing transactions.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvkPwzi2kTA1akNUk2h:-NvkX9-82zWpQhhv-8nI:bx1wz7o) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e2e3d45fdfebe68d437afa338563c9b210bb7c8/crates/blockifier/src/concurrency/scheduler_test.rs#L123)):*
> ```XML
> #[rstest]
> #[case::some(1, Some(1), 2, 1)]
> #[case::none(DEFAULT_CHUNK_SIZE, None, DEFAULT_CHUNK_SIZE, 0)]
> ```

There is no easy way to get an underflow here because the method always increases `n_active_tasks` before decreasing it. The underflow would only happen if another thread decremented `n_active_tasks` before this thread decrements it.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1792)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvkKCW_D8LtTm4cuJl1):*
Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-NvkNpMXDNLwqzY6POi4:-NvkWYfN3cbJhxl3QYcj:b-e2azbc) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e2e3d45fdfebe68d437afa338563c9b210bb7c8/crates/blockifier/src/concurrency/scheduler_test.rs#L110)):*
> ```XML
> #[rstest]
> #[case::ready(1, Some(1), 1)]
> #[case::index_out_of_bounds(DEFAULT_CHUNK_SIZE, None, 0)]
> ```

I added a method called `safe_decrement_n_active_tasks` and tested the underflow panic in its own unit test.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1792#-:-NvlVnNG7E9p0Knqs8mz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Pull request merged**
