### PR TITLE
fix(concurrency): change versioned storage read to read the writes o…

### PR DESCRIPTION
**Pull request by meship-starkware**
…f a versioned state

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1944)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1944)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @meship-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzX2KD27iHbIQFU3eqN):*




_Suggestion:_
```
- 87319a9: fix(concurrency): in versioned storage - read the writes of the current transaction
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzX-nbI-uwB_wS9km9o:-NzX-nbJALnkYBcQL_yr:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/87319a9c0c846d484d1772e4ac508b26f96fe94c/crates/blockifier/src/concurrency/versioned_state.rs#L96)):*
> ```XML
>             return true;
>         }
>         // Otherwise we are checking the writes of the current transaction.
> ```





_Suggestion:_
```XML
        // Ignore values written by the current transaction. 
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzX1TBI2178HX3ODgSj:-NzX1TBI2178HX3ODgSk:b-lf1jmm) ([raw file](https://github.com/starkware-libs/blockifier/blob/87319a9c0c846d484d1772e4ac508b26f96fe94c/crates/blockifier/src/concurrency/versioned_state_test.rs#L133)):*
> ```XML
>         &HashMap::default(),
>     );
> ```

Why did you add the extra newline?
(in the entire file)
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzX1lV4ALWHb2mSkCkN:-NzX1lV4ALWHb2mSkCkO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/87319a9c0c846d484d1772e4ac508b26f96fe94c/crates/blockifier/src/concurrency/versioned_storage.rs#L44)):*
> ```XML
>     pub fn read(&self, tx_index: TxIndex, key: K) -> Option<V> {
>         // Reads the values that all transaction with an index leq then the given tx index.
>         // Note, the reads inclued the values that the transaction wrote.
> ```





_Suggestion:_
```XML
        //TODO: Ignore `ESTIMATE` values (when added).
```
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzX238I6n-gfh8z4KIq:-NzX238I6n-gfh8z4KIr:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/87319a9c0c846d484d1772e4ac508b26f96fe94c/crates/blockifier/src/concurrency/versioned_storage_test.rs#L36)):*
> ```XML
>     assert_eq!(storage.read(1, 10).unwrap(), 31);
> 
>     // Includs the value written by the current transaction.
> ```





_Suggestion:_
```XML
    assert_eq!(storage.read(1, 10).unwrap(), 31);
    // Includes the value written by the current transaction.
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1944)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzX2KD27iHbIQFU3eqN):*
Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzX1TBI2178HX3ODgSj:-NzXk7hk9O6omoo7T9bx:b-ofbb0y) ([raw file](https://github.com/starkware-libs/blockifier/blob/87319a9c0c846d484d1772e4ac508b26f96fe94c/crates/blockifier/src/concurrency/versioned_state_test.rs#L133)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you add the extra newline?
(in the entire file)
</blockquote></details>

I printed to debug and forgot to remove the new line
Done.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1944)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzX1lV4ALWHb2mSkCkN:-NzXszAy7P7APGqLg9Ij:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/87319a9c0c846d484d1772e4ac508b26f96fe94c/crates/blockifier/src/concurrency/versioned_storage.rs#L44)):*
> ```XML
>     pub fn read(&self, tx_index: TxIndex, key: K) -> Option<V> {
>         // Reads the values that all transaction with an index leq then the given tx index.
>         // Note, the reads inclued the values that the transaction wrote.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzX238I6n-gfh8z4KIq:-NzXsyce8ZxOdQ_BjOHM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/87319a9c0c846d484d1772e4ac508b26f96fe94c/crates/blockifier/src/concurrency/versioned_storage_test.rs#L36)):*
> ```XML
>     assert_eq!(storage.read(1, 10).unwrap(), 31);
> 
>     // Includs the value written by the current transaction.
> ```

Done.

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-:-NzYGejC09KwaK9G2ow4:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzYGnJW98Ro1sMNdZMY:-NzYGnJX6s3s2mNZY80b:bhpavra) ([raw file](https://github.com/starkware-libs/blockifier/blob/dddab8a095474be85b8755d51f2b620632e059d5/crates/blockifier/src/concurrency/versioned_state_test.rs#L177)):*
> ```XML
>         versioned_state_proxys[4].state().declared_contracts.read(4, another_class_hash).unwrap()
>     );
>     // Includes the writes in the current transaction.
> ```

Consider Include



_Suggestion:_
```XML
Include
```
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-NzYGDlw9Ny1e-WRQtiR:-NzYGDlw9Ny1e-WRQtiS:b426in7) ([raw file](https://github.com/starkware-libs/blockifier/blob/dddab8a095474be85b8755d51f2b620632e059d5/crates/blockifier/src/concurrency/versioned_storage_test.rs#L35)):*
> ```XML
>     storage.write(2, 10, 78);
>     assert_eq!(storage.read(1, 10).unwrap(), 31);
> ```

Is this new line intentional?

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1944#-:-Nzb1YZD0gs_H___OeNk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1944)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
