### PR TITLE
refactor: remove enum VirtualMachineExecutionError

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1453)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1453)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1453#-Nq2nL3d-QH2m3BWcFB4:-Nq2nL3d-QH2m3BWcFB5:b-sgj2ee) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d647f1505d6c5667ae394c7783705d8fbbda748/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L196)):*
> ```XML
>     entry_point_pc: usize,
>     args: Args,
> ) -> Result<(), EntryPointExecutionError> {
> ```

we already have the object defined, no reason not to use



_Suggestion:_
```XML
EntryPointExecutionErrorResult<()>
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1453#-Nq2naf14jq-zKaIhf6i:-Nq2naf14jq-zKaIhf6j:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d647f1505d6c5667ae394c7783705d8fbbda748/crates/blockifier/src/execution/entry_point_execution.rs#L290)):*
> ```XML
>     args: Args,
>     program_segment_size: usize,
> ) -> Result<(), EntryPointExecutionError> {
> ```





_Suggestion:_
```XML
EntryPointExecutionErrorResult<()>
```

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1453#-Nq2nL3d-QH2m3BWcFB4:-Nq2xJHe81v-Mg9kc811:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d647f1505d6c5667ae394c7783705d8fbbda748/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L196)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we already have the object defined, no reason not to use
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1453)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1453#-Nq2naf14jq-zKaIhf6i:-Nq2xzaj6InxURp6_RKF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d647f1505d6c5667ae394c7783705d8fbbda748/crates/blockifier/src/execution/entry_point_execution.rs#L290)):*
> ```XML
>     args: Args,
>     program_segment_size: usize,
> ) -> Result<(), EntryPointExecutionError> {
> ```

Done.

**Pull request merged**
