### PR TITLE
chore: wrapper for serialized TransactionExecutionInfo

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1694)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1694)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1694#-NtRP1PQ-LciMkXiiCFc:-NtRP1PQ-LciMkXiiCFd:b484ew9) (no related file):*
cherry pick of [this](https://reviewable.io/reviews/starkware-libs/blockifier/1583)

___

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1694#-:-NtRQkWeEm697rIXckoz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1694)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1694#-:-NtVDWtV7pdB7Uqpk6A9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
