### PR TITLE
refactor: adding code_size field to StarknetResources

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1585)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1585)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-Nrj2w9Y73bJbYQv4pN0:-Nrj2w9Y73bJbYQv4pN1:b-mihiod) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/fee/actual_cost.rs#L117)):*
> ```XML
> 
>     pub fn with_class_info(self, class_info: ClassInfo) -> Self {
>         // TODO - better name??
> ```

delete (the name is fine IMO).
also, if you want to add a TODO, need to conform to our todo format (`// TODO(<NAME>, <EST. DATE>): <TEXT>`)



_Code quote:_
```XML
// TODO - better name??
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-Nrj4L0D5ZjyTHcZV9Je:-Nrj4L0EAGel3b10oghH:b-r5ibf7) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/transaction/objects.rs#L262)):*
> ```XML
>     /// Sets the code_size field from a ClassInfo from (Sierra, Casm and ABI). Each code felt costs
>     /// a fixed and configurable amount of gas. The cost is 0 for non-Declare transactions.
>     pub fn set_code_size(mut self, class_info: Option<&ClassInfo>) {
> ```

Doesn't this consume `self`?
I see that the object is still alive after calling this (by above examples) but I though you need to pass a mutable reverence (`&mut self`) for this to work...
Why did you go with `mut self`?



_Code quote:_
```XML
mut self
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-Nrj3egR2SeLqkTGVFdA:-Nrj3egR2SeLqkTGVFdB:bgzy8k0) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/transaction/objects.rs#L272)):*
> ```XML
>             0
>         }
>     }
> ```

instead of this function (and I guess more functions like this), I suggest:
1. making the code_size field private
2. implementing a public constructor (`pub fn new`) that accepts an `Option<&ClassInfo>` as input, and computes the code size on construction.
3. future added fields will be computed similarly (via the ctor) without explicit setters

You will still need this function (the `ActualCostBuilder` needs a setter) but a `new` function is still useful when you want to construct a StarknetResources object when you already have all the input data required (some examples in tests in this PR)



_Code quote:_
```XML
    /// Sets the code_size field from a ClassInfo from (Sierra, Casm and ABI). Each code felt costs
    /// a fixed and configurable amount of gas. The cost is 0 for non-Declare transactions.
    pub fn set_code_size(mut self, class_info: Option<&ClassInfo>) {
        self.code_size = if let Some(class_info) = class_info {
            (class_info.bytecode_length()
                + class_info.sierra_program_length())
                    // We assume each felt is a word.
                    * eth_gas_constants::WORD_WIDTH
                + class_info.abi_length()
        } else {
            0
        }
    }
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-Nrj4oXJ2pN3M3YfiTB_:-Nrj4oXJ2pN3M3YfiTBa:bds39vx) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/transaction/objects.rs#L294)):*
> ```XML
>         GasVector {
>             l1_gas: (u128_from_usize(self.code_size)
>                 * versioned_constants.l2_resource_gas_costs.milligas_per_code_byte)
> ```

you will have a conflict with [your other PR](https://reviewable.io/reviews/starkware-libs/blockifier/1590). I suggest you rebase over it to avoid working twice



_Code quote:_
```XML
versioned_constants.l2_resource_gas_costs.milligas_per_code_byte
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1585)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-Nrj4L0D5ZjyTHcZV9Je:-NrjVXL64Pd3Dr6STtKM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/transaction/objects.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Doesn't this consume `self`?
I see that the object is still alive after calling this (by above examples) but I though you need to pass a mutable reverence (`&mut self`) for this to work...
Why did you go with `mut self`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-Nrj3egR2SeLqkTGVFdA:-NrjsqSZ5R3w-pXze78b:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/transaction/objects.rs#L272)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

instead of this function (and I guess more functions like this), I suggest:
1. making the code_size field private
2. implementing a public constructor (`pub fn new`) that accepts an `Option<&ClassInfo>` as input, and computes the code size on construction.
3. future added fields will be computed similarly (via the ctor) without explicit setters

You will still need this function (the `ActualCostBuilder` needs a setter) but a `new` function is still useful when you want to construct a StarknetResources object when you already have all the input data required (some examples in tests in this PR)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-Nrj4oXJ2pN3M3YfiTB_:-NrjsicD43jeacspb7S_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/transaction/objects.rs#L294)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you will have a conflict with [your other PR](https://reviewable.io/reviews/starkware-libs/blockifier/1590). I suggest you rebase over it to avoid working twice
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1585)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-NrjygJe97GiwZDJy8lh:-NrjygJe97GiwZDJy8li:b-93t8nw) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/fee/gas_usage.rs#L100)):*
> ```XML
>     Ok(starknet_gas_usage + sharp_gas_usage)
> }
> ```

add the newline back please
___
*[`crates/blockifier/src/transaction/objects.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-Nrj3egR2SeLqkTGVFdA:-Nrjz24x8d_YDqv2AeRZ:bk984xe) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/transaction/objects.rs#L272)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I'm still trying to figure out what is the best way to do that.. 
what do you think about what i did? changing all fields to be private
</blockquote></details>

looks good. consider finding an auto-getter-generating `#[derive]` macro to use, but not a blocker
___
*[`crates/blockifier/src/transaction/objects.rs` line 306 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-NrjnQvHEKmIg20ERY0Z:-NrjnQvHEKmIg20ERY0_:b-cr2hgt) ([raw file](https://github.com/starkware-libs/blockifier/blob/de0a3c82274fc197a255b21ed8321dfe00b33581/crates/blockifier/src/transaction/objects.rs#L306)):*
> ```XML
> 
>     // TODO(Nimrod, 29/2/2024): not sure this is the right way to get this field. needed for
>     // actual_cost.rs line 176
> ```

1. any reason to make `calldata_length` private? if it's public you don't need a getter
2. maybe check if there are some derive traits you can inherit to get auto-getters for all fields
3. before merging the PR, remove this TODO (after implementing whatever is decided)



_Code quote:_
```XML
    // TODO(Nimrod, 29/2/2024): not sure this is the right way to get this field. needed for
    // actual_cost.rs line 176
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1585)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-NrjygJe97GiwZDJy8lh:-Nrk5Qnp-ePHTdHfE-6-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/fee/gas_usage.rs#L100)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add the newline back please
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-Nrj3egR2SeLqkTGVFdA:-Nrk5TlCAZPSXdCdEQCK:b4782n2) ([raw file](https://github.com/starkware-libs/blockifier/blob/b133e4737e5d5a997bceefcefe5ae4fae83dddc1/crates/blockifier/src/transaction/objects.rs#L272)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

looks good. consider finding an auto-getter-generating `#[derive]` macro to use, but not a blocker
</blockquote></details>

IMO using the [Getters](https://docs.rs/derive-getters/latest/derive_getters/#) is too much. 
I've changed the `calldata_length` field to be public. 
___
*[`crates/blockifier/src/transaction/objects.rs` line 306 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-NrjnQvHEKmIg20ERY0Z:-Nrk60FK6ffZjmxTn9lV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de0a3c82274fc197a255b21ed8321dfe00b33581/crates/blockifier/src/transaction/objects.rs#L306)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. any reason to make `calldata_length` private? if it's public you don't need a getter
2. maybe check if there are some derive traits you can inherit to get auto-getters for all fields
3. before merging the PR, remove this TODO (after implementing whatever is decided)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1585#-:-Nrk6jeFDV6kyeQwmPYb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
