### PR TITLE
chore(concurrency): complete commit_tx - post re-execution, delete writes and invoke revalidate

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Ny_STKL5vF8KuTg5hvz:-Ny_STKMCSDkZTqhrWtc:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/874d15849e00df92e14b8ae82748c2a8ccf589e9/crates/blockifier/src/concurrency/worker_logic.rs#L165)):*
> ```XML
>     fn commit_tx(&self, tx_index: TxIndex) -> StateResult<bool> {
>         let execution_output = lock_mutex_in_array(&self.execution_outputs, tx_index);
>         let execution_output_ref = execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR);
> ```





_Suggestion:_
```XML
        let execution_output = execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Ny_YB5P5j2p88S6N2qu:-Ny_YB5P5j2p88S6N2qv:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/874d15849e00df92e14b8ae82748c2a8ccf589e9/crates/blockifier/src/concurrency/worker_logic.rs#L184)):*
> ```XML
>             let execution_output = lock_mutex_in_array(&self.execution_outputs, tx_index);
>             let read_set = &execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).reads;
>             self.scheduler.finish_execution_during_commit(tx_index);
> ```





_Suggestion:_
```XML
            self.execute_tx(tx_index);
            self.scheduler.finish_execution_during_commit(tx_index);
            let execution_output = lock_mutex_in_array(&self.execution_outputs, tx_index);
            let read_set = &execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).reads;
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Ny_YYMc6Vhe1d7E843b:-Ny_YYMc6Vhe1d7E843c:b-oxh682) ([raw file](https://github.com/starkware-libs/blockifier/blob/874d15849e00df92e14b8ae82748c2a8ccf589e9/crates/blockifier/src/concurrency/worker_logic.rs#L189)):*
> ```XML
>         } else {
>             drop(execution_output);
>         }
> ```

Is it working?
Dropping an already dropped variable.



_Suggestion:_
```XML
            drop(execution_output);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Ny_XXUY7eK00-uqKC9C:-Ny_XXUY7eK00-uqKC9D:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/874d15849e00df92e14b8ae82748c2a8ccf589e9/crates/blockifier/src/concurrency/worker_logic.rs#L204)):*
> ```XML
>             if tx_context.tx_info.sender_address()
>                 != self.block_context.block_info.sequencer_address
>             {
> ```





_Suggestion:_
```XML
        if let Ok(tx_info) = result_tx_info.as_mut() {
            // TODO(Meshi, 01/06/2024): ask the bouncer if there is enough room for the transaction.
            // Update the sequencer balance.
            // There is no need to update the balance when the sequencer transfers fee to itself, since we
            // use the sequential fee transfer in this case.
            if tx_context.tx_info.sender_address()
                != self.block_context.block_info.sequencer_address
            {
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Ny_XyLfEfjNnJV0idtl:-Ny_XyLg-ji_aKk7uh8n:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/874d15849e00df92e14b8ae82748c2a8ccf589e9/crates/blockifier/src/concurrency/worker_logic.rs#L227)):*
> ```XML
>                     sequencer_balance_value_low,
>                     sequencer_balance_value_high,
>                 );
> ```





_Suggestion:_
```XML
                    sequencer_balance_value_high,
                );
                // Changing the sequencer balance storage cell does not trigger (re-)validation of
                // the next transactions.
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Ny_STKL5vF8KuTg5hvz:-Ny_ZAd191MxsMyb7LDh:b-7hyisy) ([raw file](https://github.com/starkware-libs/blockifier/blob/874d15849e00df92e14b8ae82748c2a8ccf589e9/crates/blockifier/src/concurrency/worker_logic.rs#L165)):*
> ```XML
>     fn commit_tx(&self, tx_index: TxIndex) -> StateResult<bool> {
>         let execution_output = lock_mutex_in_array(&self.execution_outputs, tx_index);
>         let execution_output_ref = execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR);
> ```

The `drop` doesn't work if I do that:
```
calls to `std::mem::drop` with a reference instead of an owned value does nothing
use `let _ = ...` to ignore the expression or result
`-D dropping-references` implied by `-D warnings`
to override `-D warnings` add `#[allow(dropping_references)]`rustcClick for full compiler diagnostic
worker_logic.rs(178, 18): argument has type `&concurrency::worker_logic::ExecutionTaskOutput`
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Ny_YYMc6Vhe1d7E843b:-Ny_ZHOJAbr3XVJQ50HE:b9104tx) ([raw file](https://github.com/starkware-libs/blockifier/blob/874d15849e00df92e14b8ae82748c2a8ccf589e9/crates/blockifier/src/concurrency/worker_logic.rs#L189)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it working?
Dropping an already dropped variable.
</blockquote></details>

It doesn't work:
```
use of moved value: `execution_output`
value used here after moverustcClick for full compiler diagnostic
worker_logic.rs(180, 18): value moved here
worker_logic.rs(164, 13): move occurs because `execution_output` has type `std::sync::MutexGuard<'_, std::option::Option<concurrency::worker_logic::ExecutionTaskOutput>>`, which does not implement the `Copy` trait
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Ny_XXUY7eK00-uqKC9C:-Ny__g6l4g24J7GY-oKQ:b-rw5tz8) ([raw file](https://github.com/starkware-libs/blockifier/blob/874d15849e00df92e14b8ae82748c2a8ccf589e9/crates/blockifier/src/concurrency/worker_logic.rs#L204)):*
> ```XML
>             if tx_context.tx_info.sender_address()
>                 != self.block_context.block_info.sequencer_address
>             {
> ```

The comment was already fixed in Meshi's open PR (#1898).
Changing it here will create a conflict.

I reworded the TODO.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Ny_XyLfEfjNnJV0idtl:-Ny_aFTs9ArWUyIY3Q7v:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/874d15849e00df92e14b8ae82748c2a8ccf589e9/crates/blockifier/src/concurrency/worker_logic.rs#L227)):*
> ```XML
>                     sequencer_balance_value_low,
>                     sequencer_balance_value_high,
>                 );
> ```

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-NyeexYl41IkZ4OReILk):*




_Suggestion:_
```
- 022616f: chore(concurrency): complete commit_tx: post re-execution: delete writes and invoke re-validate.
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 180 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Nyeg0rh2SjwUHA_r7t-:-Nyeg0riA1pScJcZ6PNM:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/022616f5f0136885163f98e53a08ac7a9d6fabf2/crates/blockifier/src/concurrency/worker_logic.rs#L180)):*
> ```XML
>                 &execution_output_ref.contract_classes,
>             );
>             drop(execution_output);
> ```





_Suggestion:_
```XML
            );
            // Release the execution output lock as it is acquired in execution (avoid dead-lock)
            drop(execution_output);
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-NynZvTmEl9VJSYC9JZh:-NynZvTmEl9VJSYC9JZi:b-r267o8) ([raw file](https://github.com/starkware-libs/blockifier/blob/022616f5f0136885163f98e53a08ac7a9d6fabf2/crates/blockifier/src/concurrency/worker_logic.rs#L171)):*
> ```XML
> 
>         let reads = &execution_output_ref.reads;
>         let reads_valid = tx_versioned_state.validate_reads(reads);
> ```

If we are dropping execution_output inside the condition there is no need for reads_valid we can just write 
if !tx_versioned_state.validate_reads(reads):
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 231 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Nyn_hfXCeMIKemLeUi7:-Nyn_hfXCeMIKemLeUi8:b-4mrfgd) ([raw file](https://github.com/starkware-libs/blockifier/blob/022616f5f0136885163f98e53a08ac7a9d6fabf2/crates/blockifier/src/concurrency/worker_logic.rs#L231)):*
> ```XML
>                 );
>                 // Changing the sequencer balance storage cell does not trigger (re-)validation of
>                 // the next transactions.
> ```

Is this working because any transaction that updates the sequencer balance (outside fee transfer) will fail in the commit re-validation?

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 231 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Nyn_hfXCeMIKemLeUi7:-NyncBbk0Yuk_89RXg_m:b-ky8le3) ([raw file](https://github.com/starkware-libs/blockifier/blob/022616f5f0136885163f98e53a08ac7a9d6fabf2/crates/blockifier/src/concurrency/worker_logic.rs#L231)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Is this working because any transaction that updates the sequencer balance (outside fee transfer) will fail in the commit re-validation?
</blockquote></details>

I think validation does not include this storage cell, so there is no way for it to trigger invalidation.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-NynZvTmEl9VJSYC9JZh:-NyncNGQ9foHxYn1E9BS:b-bgbcmg) ([raw file](https://github.com/starkware-libs/blockifier/blob/022616f5f0136885163f98e53a08ac7a9d6fabf2/crates/blockifier/src/concurrency/worker_logic.rs#L171)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

If we are dropping execution_output inside the condition there is no need for reads_valid we can just write 
if !tx_versioned_state.validate_reads(reads):
</blockquote></details>

I think it's cleaner with the `reads_valid` variable.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-NyeexYl41IkZ4OReILk):*
Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 180 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-Nyeg0rh2SjwUHA_r7t-:-Nynd1pvCDPqFTw4nL2q:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/022616f5f0136885163f98e53a08ac7a9d6fabf2/crates/blockifier/src/concurrency/worker_logic.rs#L180)):*
> ```XML
>                 &execution_output_ref.contract_classes,
>             );
>             drop(execution_output);
> ```

Done.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916#-:-Nynl7md4ijd58t3FWb5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

**Review by avi-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1916)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
