### PR TITLE
Add StateReader with callbacks to Python.

### PR DESCRIPTION
**Pull request by dafnamatsry**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/827)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/827)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @giladchase)

___
*[`crates/native_blockifier/src/py_state_reader.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NbnQJkT-05gyDVDwsZC:-NbnQJkU528lHwOpUYhB:b-xdn7sj) ([raw file](https://github.com/starkware-libs/blockifier/blob/b76fd5a2895fa4e704bbf9adaec06e81c0908d42/crates/native_blockifier/src/py_state_reader.rs#L103)):*
> ```XML
>     }
> 
>     fn get_fee_token_balance(
> ```

I don't think this is needed (it is implemented in StateReader trait and uses `get_storage_at`)

**Review by giladchase — CHANGES_REQUESTED** [review]
Was this tested in Python? If so, can you please open a PR in the Python repo so I can test it out?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/827#-:-NbjR8ivAC_RXM5Xg9oV:b-vmeuo7)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/native_blockifier/src/errors.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NbxUxFxCeIoE4vwU4_W:-NbxUxFyAU-rgfIC17sv:beoylcn) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/errors.rs#L82)):*
> ```XML
> }
> 
> pyo3::import_exception!(starkware.starkware_utils.error_handling, StarkException);
> ```

No hardcoded paths from python repo plz :grimacing: 

Either don't use the macro, or make it into something configurable that can be passed in from outside (I think this will require the macro be moved inside the scope of the function, not sure if I like that though...)



_Code quote:_
```XML
pyo3::import_exception!(starkware.starkware_utils.error_handling, StarkException);
```
___
*[`crates/native_blockifier/src/errors.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-Nbx6QDKA1woAvmrjLPR:-Nbx6QDKA1woAvmrjLPS:b-mqm1zi) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/errors.rs#L93)):*
> ```XML
>         }
>         false
>     })
> ```

Perhaps we should have a dedicated py_state_reader module, which will store `py_state_reader.rs` as well as its own error enum and the function below.
Rationale: IIUC this will probably only be useful to the PyStateReader.



_Code quote:_
```XML
pub fn is_undeclared_class_error(err: &PyErr) -> bool {
    Python::with_gil(|py| {
        if err.is_instance_of::<StarkException>(py) {
            let err_code = py_enum_name::<String>(err.value(py), "code").unwrap_or_default();
            return err_code == "UNDECLARED_CLASS";
        }
        false
    })
```
___
*[`crates/native_blockifier/src/py_contract_class.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NbxwAiB2n4TzvP0CjA-:-NbxwAiB2n4TzvP0CjA0:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/py_contract_class.rs#L15)):*
> ```XML
>     type Error = NativeBlockifierError;
> 
>     fn try_from(py_value: PyRawCompiledClass) -> NativeBlockifierResult<Self> {
> ```





_Suggestion:_
```XML
py_raw_compiled_class // or just raw_compiled_class
```
___
*[`crates/native_blockifier/src/py_state_reader.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NbwVPY-AmPXQeVs9UAQ:-NbwVPY-AmPXQeVs9UAR:b-f9xokl) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/py_state_reader.rs#L16)):*
> ```XML
> 
> // The value of Python StorageDomain.ON_CHAIN enum.
> const ON_CHAIN_STORAGE_DOMAIN: u8 = 0;
> ```

Is the OFF variant of the enum not possible in this flow?



_Code quote:_
```XML
const ON_CHAIN_STORAGE_DOMAIN: u8 = 0;
```
___
*[`crates/native_blockifier/src/py_state_reader.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-Nbx2ecF8mnlWFHMhvFz:-Nbx2ecG860Ddu8KC4ip:bhf4bsm) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/py_state_reader.rs#L49)):*
> ```XML
>             Ok(result.0)
>         })
>         .map_err(|err| StateError::StateReadError(err.to_string()))
> ```

I think this (and the rest) can be made more concice; it may enhance readability. However, it's ultimately your decision, and the current implementation is also cool.

One option:
```rust
        Python::with_gil(|py| -> Result<PyFelt, PyErr> {
            let args = (ON_CHAIN_STORAGE_DOMAIN, PyFelt::from(contract_address), PyFelt::from(key));
            self.state_reader_proxy.as_ref(py).call_method1("get_storage_at", args)?.extract()
        })
        .map(|felt| felt.0)
        .map_err(|err| StateError::StateReadError(err.to_string()))
```

Another option that's even shorter, but I believe it may reduce readability to the point where it's less clear:
```rust
        let storage_result = Python::with_gil(|py| -> Result<PyFelt, PyErr> {
            let args = (ON_CHAIN_STORAGE_DOMAIN, PyFelt::from(contract_address), PyFelt::from(key));
            self.state_reader_proxy.as_ref(py).call_method1("get_storage_at", args)?.extract()
        });
        storage_result.map(|felt| felt.0).map_err(|err| StateError::StateReadError(err.to_string()))
```



_Code quote:_
```XML
        Python::with_gil(|py| -> Result<StarkFelt, PyErr> {
            let args = (ON_CHAIN_STORAGE_DOMAIN, PyFelt::from(contract_address), PyFelt::from(key));
            let result: PyFelt = self
                .state_reader_proxy
                .as_ref(py)
                .call_method1("get_storage_at", args)?
                .extract()?;

            Ok(result.0)
        })
        .map_err(|err| StateError::StateReadError(err.to_string()))
```
___
*[`crates/native_blockifier/src/py_state_reader.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NbwYyhG-3ga2GYDFVRL:-NbwYyhG-3ga2GYDFVRM:b-7m32ly) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/py_state_reader.rs#L55)):*
> ```XML
>         Python::with_gil(|py| -> Result<Nonce, PyErr> {
>             let args = (ON_CHAIN_STORAGE_DOMAIN, PyFelt::from(contract_address));
>             let result: PyFelt =
> ```

nonce



_Code quote:_
```XML
result
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/827)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NbxUxFxCeIoE4vwU4_W:-NcGU0tIAf6dKGOIQ-F2:basa8j2) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/errors.rs#L82)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

No hardcoded paths from python repo plz :grimacing: 

Either don't use the macro, or make it into something configurable that can be passed in from outside (I think this will require the macro be moved inside the scope of the function, not sure if I like that though...)
</blockquote></details>

I created a new type of exception here that will be returned from Python.
___
*[`crates/native_blockifier/src/errors.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-Nbx6QDKA1woAvmrjLPR:-NcGUUcUCv2ck3gsAvS5:b-5s2zdt) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/errors.rs#L93)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Perhaps we should have a dedicated py_state_reader module, which will store `py_state_reader.rs` as well as its own error enum and the function below.
Rationale: IIUC this will probably only be useful to the PyStateReader.
</blockquote></details>

What does it mean? A new py module like native_blockifier?
Not sure I like this idea. I can move this specific error to py_state_reader.rs if you prefer...
___
*[`crates/native_blockifier/src/py_contract_class.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NbxwAiB2n4TzvP0CjA-:-NbyCCmbCgxVXU3PpGoB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/py_contract_class.rs#L15)):*
> ```XML
>     type Error = NativeBlockifierError;
> 
>     fn try_from(py_value: PyRawCompiledClass) -> NativeBlockifierResult<Self> {
> ```

Done.
___
*[`crates/native_blockifier/src/py_state_reader.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NbwVPY-AmPXQeVs9UAQ:-Nby9wRi1qVlhIIQMhiW:b-yq0tst) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/py_state_reader.rs#L16)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is the OFF variant of the enum not possible in this flow?
</blockquote></details>

Not at the moment. 
I think the StorageDomain was added for volition in Python but wasn't added in Rust yet. Once it will be added, it will be passed as an argument to the state reader.
___
*[`crates/native_blockifier/src/py_state_reader.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-Nbx2ecF8mnlWFHMhvFz:-NbyIv7XBG7kWZLxsziU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/py_state_reader.rs#L49)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think this (and the rest) can be made more concice; it may enhance readability. However, it's ultimately your decision, and the current implementation is also cool.

One option:
```rust
        Python::with_gil(|py| -> Result<PyFelt, PyErr> {
            let args = (ON_CHAIN_STORAGE_DOMAIN, PyFelt::from(contract_address), PyFelt::from(key));
            self.state_reader_proxy.as_ref(py).call_method1("get_storage_at", args)?.extract()
        })
        .map(|felt| felt.0)
        .map_err(|err| StateError::StateReadError(err.to_string()))
```

Another option that's even shorter, but I believe it may reduce readability to the point where it's less clear:
```rust
        let storage_result = Python::with_gil(|py| -> Result<PyFelt, PyErr> {
            let args = (ON_CHAIN_STORAGE_DOMAIN, PyFelt::from(contract_address), PyFelt::from(key));
            self.state_reader_proxy.as_ref(py).call_method1("get_storage_at", args)?.extract()
        });
        storage_result.map(|felt| felt.0).map_err(|err| StateError::StateReadError(err.to_string()))
```
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_state_reader.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NbwYyhG-3ga2GYDFVRL:-Nc2CuKdDE7J5H-ioK5m:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/py_state_reader.rs#L55)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

nonce
</blockquote></details>

Done.

**Review by giladchase — DISMISSED** [review]
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/native_blockifier/src/errors.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NbxUxFxCeIoE4vwU4_W:-NcGcDKn5U8AZ-LvvPSU:b-e7obfy) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/errors.rs#L82)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I created a new type of exception here that will be returned from Python.
</blockquote></details>

Ohhh right cool!
___
*[`crates/native_blockifier/src/errors.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-Nbx6QDKA1woAvmrjLPR:-NcGcTD8CoK56elTAQ_D:b1xfx7m) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/errors.rs#L93)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What does it mean? A new py module like native_blockifier?
Not sure I like this idea. I can move this specific error to py_state_reader.rs if you prefer...
</blockquote></details>

It's a moot point now (now that you used Dori's cool macro :tipping_hand_man:), but I wasn't accurate previously.
I meant to add a new `py_state_reader` submodule to native_blockifier (I incorrectly wrote "module")  that holds special error handling functions that only had to do with `py_state_reader`.
___
*[`crates/native_blockifier/src/lib.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NcGdfIcCbmztou2e8jJ:-NcGdfIcCbmztou2e8jK:b-rzu9z5) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddcccecd0a5bb069b49b40afaf86b95a74a66290/crates/native_blockifier/src/lib.rs#L41)):*
> ```XML
>     py_module.add_class::<PyVmExecutionResources>()?;
>     py_module.add_class::<StorageConfig>()?;
>     py_module.add("UndeclaredClassHashError", py.get_type::<UndeclaredClassHashError>())?;
> ```

Just reminding that adding this new error here requires updating the error_type test in Python, which will now break.

I recommend git `blaming` on the other error variants in the (now failing) python test to see what places need to be updated (there are several).



_Code quote:_
```XML
    py_module.add("UndeclaredClassHashError", py.get_type::<UndeclaredClassHashError>())?;
```
___
*[`crates/native_blockifier/src/py_state_reader.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/827#-Nbx2ecF8mnlWFHMhvFz:-NcGiaVG8Z4UWbyasLEf:bdeavht) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d0031a8c0830556269037c18c956b5bbad6c654/crates/native_blockifier/src/py_state_reader.rs#L49)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:fire: 
___
*[`crates/native_blockifier/src/py_state_reader.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NcGieS-6Ak6_CqfA-Pc:-NcGieS-6Ak6_CqfA-Pd:bvbw2fm) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddcccecd0a5bb069b49b40afaf86b95a74a66290/crates/native_blockifier/src/py_state_reader.rs#L71)):*
> ```XML
>         Python::with_gil(|py| -> Result<ContractClass, PyErr> {
>             let args = (PyFelt::from(*class_hash),);
>             let result: PyRawCompiledClass = self
> ```

py_raw_compiled_class



_Code quote:_
```XML
result
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/native_blockifier/src/lib.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NcGdfIcCbmztou2e8jJ:-NcHC--Y8-4Wn071j_-2:b-8yyqwt) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddcccecd0a5bb069b49b40afaf86b95a74a66290/crates/native_blockifier/src/lib.rs#L41)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Just reminding that adding this new error here requires updating the error_type test in Python, which will now break.

I recommend git `blaming` on the other error variants in the (now failing) python test to see what places need to be updated (there are several).
</blockquote></details>

Note that I didn't use Dori's macro, which does other things besides adding a new exception type, so the test does pass.

I actually tried using it, but the exceptions defined there are mapped to a Rust type, which is unnecessary in this case.

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/827)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_state_reader.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NcGieS-6Ak6_CqfA-Pc:-NcHLsvS5Al1kPH9EBmf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddcccecd0a5bb069b49b40afaf86b95a74a66290/crates/native_blockifier/src/py_state_reader.rs#L71)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

py_raw_compiled_class
</blockquote></details>

Done.

**Review by dafnamatsry — COMMENTED** [review]
https://github.com/starkware-industries/starkware/pull/31524

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/827#-:-NcHLw4A5fa5mW22kgyO:b-j5c2e9)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/native_blockifier/src/lib.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/827#-NcGdfIcCbmztou2e8jJ:-NcaFWn_EdqGFb9A6Zcv:b8e8n35) ([raw file](https://github.com/starkware-libs/blockifier/blob/ddcccecd0a5bb069b49b40afaf86b95a74a66290/crates/native_blockifier/src/lib.rs#L41)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Note that I didn't use Dori's macro, which does other things besides adding a new exception type, so the test does pass.

I actually tried using it, but the exceptions defined there are mapped to a Rust type, which is unnecessary in this case.
</blockquote></details>

Oh i see, got it.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/827#-:-NcxQ6od0slrPSDmo5aU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request closed without merging**
