### PR TITLE
test(concurrency): test decrease_validation_index

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)

### CODE REVIEW

**Review by Yoni-Starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv2O2SjCFGbKkqyDzrS:-Nv2O2SjCFGbKkqyDzrT:bn8ncyu) ([raw file](https://github.com/starkware-libs/blockifier/blob/eafbeabe6eb6e0c6a6a173556334c2907d3607e4/crates/blockifier/src/concurrency/scheduler.rs#L11)):*
> ```XML
> 
> // TODO(Avi, 01/04/2024): Remove dead_code attribute.
> #[allow(dead_code)]
> ```

Can it be removed now?



_Code quote:_
```XML
// TODO(Avi, 01/04/2024): Remove dead_code attribute.
#[allow(dead_code)]
```
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv2Q4dZ8WOgKGBGF1z1:-Nv2Q4dZ8WOgKGBGF1z2:bkihvh2) ([raw file](https://github.com/starkware-libs/blockifier/blob/eafbeabe6eb6e0c6a6a173556334c2907d3607e4/crates/blockifier/src/concurrency/scheduler.rs#L81)):*
> ```XML
> 
>     fn decrease_execution_index(&self, target_index: TxIndex) {
>         self.execution_index.fetch_min(target_index, Ordering::SeqCst);
> ```

(Unrelated to this PR)
That's cool. Consider enforcing the convention (when to use seq/acquire etc)
by sharing this code. E.g., define your own atomic var



_Code quote:_
```XML
Ordering::SeqCst
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv2PBLZ7l2by4-nm-f1:-Nv2PBLZ7l2by4-nm-f2:bjqpv7t) ([raw file](https://github.com/starkware-libs/blockifier/blob/eafbeabe6eb6e0c6a6a173556334c2907d3607e4/crates/blockifier/src/concurrency/scheduler_test.rs#L62)):*
> ```XML
>     scheduler.decrease_validation_index(target_index);
>     assert_eq!(scheduler.validation_index.load(Ordering::Acquire), target_index);
>     assert_eq!(scheduler.decrease_counter.load(Ordering::Acquire), 1);
> ```

Can you remove the sanity check `assert!(target_index < scheduler.validation_index.load(Ordering::Acquire))` 
from the struct now, or are there other use cases?



_Suggestion:_
```XML
    let scheduler =
        default_scheduler!(chunk_size: DEFAULT_CHUNK_SIZE, validation_index: validation_index);
    
    // Before.
    assert!(target_index < scheduler.validation_index.load(Ordering::Acquire))
    assert_eq!(scheduler.decrease_counter.load(Ordering::Acquire), 0);
    
    scheduler.decrease_validation_index(target_index);
    // After.
    assert_eq!(scheduler.validation_index.load(Ordering::Acquire), target_index);
    assert_eq!(scheduler.decrease_counter.load(Ordering::Acquire), 1);
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv2O2SjCFGbKkqyDzrS:-Nv5OT9F8ZaGTkxzJJ_M:b-v3e9gj) ([raw file](https://github.com/starkware-libs/blockifier/blob/eafbeabe6eb6e0c6a6a173556334c2907d3607e4/crates/blockifier/src/concurrency/scheduler.rs#L11)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can it be removed now?
</blockquote></details>

Unfortunately, it still complains without it (:
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv2Q4dZ8WOgKGBGF1z1:-Nv5S7Sz4_5Lk6jnb7to:b-xj6i4d) ([raw file](https://github.com/starkware-libs/blockifier/blob/eafbeabe6eb6e0c6a6a173556334c2907d3607e4/crates/blockifier/src/concurrency/scheduler.rs#L81)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(Unrelated to this PR)
That's cool. Consider enforcing the convention (when to use seq/acquire etc)
by sharing this code. E.g., define your own atomic var
</blockquote></details>

Sounds good, @noaov1 Do you want to add it as a new task somewhere?
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv2PBLZ7l2by4-nm-f1:-Nv5Onqt9abi9dpo9DVu:b-j86i36) ([raw file](https://github.com/starkware-libs/blockifier/blob/eafbeabe6eb6e0c6a6a173556334c2907d3607e4/crates/blockifier/src/concurrency/scheduler_test.rs#L62)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Wait, is calling the function with `target >= validation` a legitimate flow?
If so, maybe change the assert:
```
assert_eq!(scheduler.validation_index.load(Ordering::Acquire), min(target_index, validation_index));
```
</blockquote></details>

@noaov1 and I talked about it yesterday. The assertion in the struct is temporary, and I put it there because we're unsure if there is or isn't a legitimate flow with `target_index >= validation_index`. We think there isn't, but we decided to put it there as a temporary solution to "catch special flows" to better understand the algorithm.
On the one hand, in the current phase of the algorithm implementation, we think that we will call it only from `finish_execution` (which is still unimplemented). There, we check that `validation_index > tx_index` and only then call `decrease_validation_index`. On the other hand, we might have multiple threads flow that can change the `validation_index` behind the scenes.

Moving the assertion to the test (instead of the struct) is optional, but this test will not catch the multiple threads flow I talked about.

I've added a TODO to rethink this question once we have a multiple threads flow. WDYT now?

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-:-Nv5ifEm1aTiLTm6Z3OA:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv2PBLZ7l2by4-nm-f1:-Nv5iLNK6O2o1qvFzjf-:bu6dy1n) ([raw file](https://github.com/starkware-libs/blockifier/blob/eafbeabe6eb6e0c6a6a173556334c2907d3607e4/crates/blockifier/src/concurrency/scheduler_test.rs#L62)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

@noaov1 and I talked about it yesterday. The assertion in the struct is temporary, and I put it there because we're unsure if there is or isn't a legitimate flow with `target_index >= validation_index`. We think there isn't, but we decided to put it there as a temporary solution to "catch special flows" to better understand the algorithm.
On the one hand, in the current phase of the algorithm implementation, we think that we will call it only from `finish_execution` (which is still unimplemented). There, we check that `validation_index > tx_index` and only then call `decrease_validation_index`. On the other hand, we might have multiple threads flow that can change the `validation_index` behind the scenes.

Moving the assertion to the test (instead of the struct) is optional, but this test will not catch the multiple threads flow I talked about.

I've added a TODO to rethink this question once we have a multiple threads flow. WDYT now?
</blockquote></details>

Ok, I understand now. Good to keep it as-is until we are sure about the multiple threads flow

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv5ijrwBNlVqKNYTYeU:-Nv5ijrwBNlVqKNYTYeV:bwokbep) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/concurrency/scheduler_test.rs#L62)):*
> ```XML
>     scheduler.decrease_validation_index(target_index);
>     assert_eq!(scheduler.validation_index.load(Ordering::Acquire), target_index);
>     assert_eq!(scheduler.decrease_counter.load(Ordering::Acquire), 1);
> ```

To show the reader the effect of the call



_Suggestion:_
```XML
    
    assert_eq!(scheduler.decrease_counter.load(Ordering::Acquire), 0);
    scheduler.decrease_validation_index(target_index);
    assert_eq!(scheduler.validation_index.load(Ordering::Acquire), target_index);
    assert_eq!(scheduler.decrease_counter.load(Ordering::Acquire), 1);
```

**Review by Yoni-Starkware — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv2Q4dZ8WOgKGBGF1z1:-Nv5X5AY75uK4f9iGje9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/eafbeabe6eb6e0c6a6a173556334c2907d3607e4/crates/blockifier/src/concurrency/scheduler.rs#L81)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Sounds good, @noaov1 Do you want to add it as a new task somewhere?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv60SH6B4hwYjQRg8CR:-Nv60SH7DSzoS9swipPS:bts7ku7) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/concurrency/scheduler_test.rs#L8)):*
> ```XML
> use crate::concurrency::scheduler::{Scheduler, TransactionStatus};
> use crate::concurrency::TxIndex;
> use crate::default_scheduler;
> ```

Interesting. How come the import does not include the full path? Is it thanks to the `#[macro_export]` decorator?



_Code quote:_
```XML
use crate::default_scheduler;
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv68C149xMgbCa-6EgW:-Nv68C149xMgbCa-6EgX:b-83sjoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/concurrency/scheduler_test.rs#L51)):*
> ```XML
> #[rstest]
> #[case::happy_flow(1, 3)]
> #[should_panic(expected = "assertion failed: target_index < self.validation_index")]
> ```

Nice!



_Code quote:_
```XML
#[should_panic(expected = "assertion failed: target_index < self.validation_index")]
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv5Y33A-f2ddu7jb2za:-Nv5Y33A-f2ddu7jb2zb:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L187)):*
> ```XML
> // Concurrency.
> 
> #[macro_export]
> ```





_Suggestion:_
```XML
#[cfg(feature = "concurrency")]
#[macro_export]
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 208 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv68nccBgkNWptl-Fef:-Nv68nccBgkNWptl-Feg:b-xojses) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L208)):*
> ```XML
>             ..Default::default()
>         }
>     };
> ```

Can you please explain why it appears twice (with small difference)?



_Code quote:_
```XML
    ($chunk_size:ident $(, $field:ident $(: $value:expr)?),+ $(,)?) => {
        Scheduler {
            $chunk_size,
            $($field $(: $value.into())?,)*
            tx_statuses: std::iter::repeat_with(|| std::sync::Mutex::new(TransactionStatus::ReadyToExecute))
                .take($chunk_size)
                .collect(),
            ..Default::default()
        }
    };
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv60SH6B4hwYjQRg8CR:-NvB9WgWEzBi-NWqGKfb:bno5gec) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/concurrency/scheduler_test.rs#L8)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Interesting. How come the import does not include the full path? Is it thanks to the `#[macro_export]` decorator?
</blockquote></details>

It's like that everywhere in our repo (: ChatGPT explanation:
```
In Rust, when you define a macro in a crate, it's automatically available to all
modules within that crate without needing to specify the full path. This is because
macros are resolved differently from regular items like functions or structs.
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv5ijrwBNlVqKNYTYeU:-NvBAnjDE1jx2_W70XrG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/concurrency/scheduler_test.rs#L62)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

To show the reader the effect of the call
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv5Y33A-f2ddu7jb2za:-NvBAyUq1wqhaQFnQGol:b-b7ur9u) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L187)):*
> ```XML
> // Concurrency.
> 
> #[macro_export]
> ```

If I add it, it doesn't let to use the macro outside of this file.
However, I'm not sure this is the right place for this macro. On the one hand, it's kind of an `impl` for the `Scheduler`, on the other hand, it's not. So maybe it should be in the:
1. `crates/blockifier/src/test_utils.rs`
2. Somewhere in the `concurrency` dir, maybe in a new `test_utils` file?
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 208 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv68nccBgkNWptl-Fef:-NvBBY_34P5YJ7M9UONb:b-msio3e) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L208)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain why it appears twice (with small difference)?
</blockquote></details>

Yes, it's for these two kinds of calls:
1. `default_scheduler!(chunk_size: 100);`
2. `let chunk_size = 4; default_scheduler!(chunk_size);`

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-:-NvBIKdu86q06EVVhnZF:bnfp4nl)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv5Y33A-f2ddu7jb2za:-NvC02ywA_xJD_IDeZIS:bisc3st) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L187)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

If I add it, it doesn't let to use the macro outside of this file.
However, I'm not sure this is the right place for this macro. On the one hand, it's kind of an `impl` for the `Scheduler`, on the other hand, it's not. So maybe it should be in the:
1. `crates/blockifier/src/test_utils.rs`
2. Somewhere in the `concurrency` dir, maybe in a new `test_utils` file?
</blockquote></details>

WDYM? Which error do you get?
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 208 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv68nccBgkNWptl-Fef:-NvByn6ICczjjmPUIgee:b-37wm2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L208)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Yes, it's for these two kinds of calls:
1. `default_scheduler!(chunk_size: 100);`
2. `let chunk_size = 4; default_scheduler!(chunk_size);`
</blockquote></details>

Why do you need both?

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv5Y33A-f2ddu7jb2za:-NvC2I4O9cEskkS3dJCh:b-g98wl6) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L187)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM? Which error do you get?
</blockquote></details>

`error: cannot determine resolution for the macro 'default_scheduler'`
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 208 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv68nccBgkNWptl-Fef:-NvC2LP-1stPgFFxOWFZ:bkg76ic) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L208)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why do you need both?
</blockquote></details>

To make it more convenient and robust for use in the future (more like a function or a constructor).
I can remove one for now if you think it's redundant.

**Review by noaov1 — DISMISSED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv5Y33A-f2ddu7jb2za:-NvCUPh1AGH4DfhYhjwe:bxizwcj) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L187)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The test is not needed since it's a module defined in `test_utils` :)
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 208 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv68nccBgkNWptl-Fef:-NvCUX_r6ob7WcqgV0EL:b2edkb6) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L208)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

To make it more convenient and robust for use in the future (more like a function or a constructor).
I can remove one for now if you think it's redundant.
</blockquote></details>

I don't have a strong opinion.  I think that one option is okay but your choice

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv5Y33A-f2ddu7jb2za:-NvCWgKQ7kGXw34K86ZI:bolqsl8) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L187)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The test is not needed since it's a module defined in `test_utils` :)
</blockquote></details>

Do you think it's the right place for this macro?
WDYT about:
1. `crates/blockifier/src/test_utils.rs`
2. Somewhere in the `concurrency` dir, maybe in a new `test_utils` file?

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 208 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv68nccBgkNWptl-Fef:-NvCWttR-_JPr2kCLL9E:bkkmja2) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L208)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I don't have a strong opinion.  I think that one option is okay but your choice
</blockquote></details>

I think it could drive crazy someone who will try to use the second option and will not understand why it doesn't compile. If he notices that it works the other way around, he will use the "working but not ideal" option instead of trying to modify the macro, so I leave it with the two options.

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv5Y33A-f2ddu7jb2za:-NvCXrmp0brjoboEjpsF:b-owtpjr) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L187)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Do you think it's the right place for this macro?
WDYT about:
1. `crates/blockifier/src/test_utils.rs`
2. Somewhere in the `concurrency` dir, maybe in a new `test_utils` file?
</blockquote></details>

Option 2 sounds good.

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-Nv5Y33A-f2ddu7jb2za:-NvCa3WU58_BFX7sSp34:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e18f0f531ffbaa63a1c24c8f9cb707aa10e1181/crates/blockifier/src/test_utils/struct_impls.rs#L187)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Option 2 sounds good.
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1776#-:-NvQYu5b1oeHqRZVLDud:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
