### PR TITLE
Pass file max size to Papyrus reader.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/326)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/326)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/326#-NPrQR5R9kD7pEn2P6GR:-NPrQR5R9kD7pEn2P6GS:bk8fl2j) ([raw file](https://github.com/starkware-libs/blockifier/blob/11e00a3ec848a9611d558c0b6ba134116c80ccba/crates/native_blockifier/src/py_transaction.rs#L186)):*
> ```XML
>         block_info: &PyAny,
>         storage_path: String,
>         max_size: usize,
> ```

Maybe add a TODO to see how to refactor this? (RE the duplication of storage_path/max_size here and in the storage constructor)



_Code quote:_
```XML
    #[args(general_config, block_info, storage_path, max_size)]
    pub fn create(
        general_config: &PyAny,
        block_info: &PyAny,
        storage_path: String,
        max_size: usize,
```
___
*[`crates/native_blockifier/src/storage.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/326#-NPrQ9oS5TDi6n4wd9fp:-NPrQ9oT-UMDVaNkzwiJ:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/11e00a3ec848a9611d558c0b6ba134116c80ccba/crates/native_blockifier/src/storage.rs#L27)):*
> ```XML
> impl Storage {
>     #[new]
>     #[args(path)]
> ```





_Suggestion:_
```XML
    #[args(path, max_size)]
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/326)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/326#-NPrQ9oS5TDi6n4wd9fp:-NPw-PSR1RmQhPNuB25S:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/11e00a3ec848a9611d558c0b6ba134116c80ccba/crates/native_blockifier/src/storage.rs#L27)):*
> ```XML
> impl Storage {
>     #[new]
>     #[args(path)]
> ```

Done.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/326)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/326#-NPw-ndP53INw9vd22Re:-NPw-ndQ4NMWtdMq3F5G:b51nt6w) (no related file):*
Blocking: merge after backporting is done.

___

**Review by giladchase — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/326)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Pull request merged**
