### PR TITLE
chore: release v0.5.0

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1624)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
Python https://github.com/starkware-industries/starkware/pull/34273

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1624#-:-Ns9O2a0EqxAKu8Rs_8e:b-v0bs8j)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1624)* status: all files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1624#-Ns9V2O-8dhsb0x09v2-:-Ns9V2O-8dhsb0x09v20:b234tav) (no related file):*
this PR should not be merged until native is reconnected

___
___
*[`Cargo.toml` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1624#-Ns9V0p82UyIKnzaYCwH:-Ns9V0p82UyIKnzaYCwI:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2cacbeb9676fd28e994f0c9ea54469077b5a9806/Cargo.toml#L6)):*
> ```TOML
> resolver = "2"
> 
> members = ["crates/blockifier", "crates/native_blockifier"]
> ```





_Suggestion:_
```TOML
members = ["crates/blockifier"]
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1624)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`Cargo.toml` line 39 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1624#-Ns9J7nX9UGfx8YefY54:-Ns9aQQiAo8fOxCza2Lh:b4ebshh) ([raw file](https://github.com/starkware-libs/blockifier/blob/2cacbeb9676fd28e994f0c9ea54469077b5a9806/Cargo.toml#L39)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not sure this is needed now that the native is disconnected: did you already publish this non-RC blockifier version, and is papyrus v0.3.0 (non-RC) pointing to blockifier v0.5.0 (non-RC)?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1624)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`Cargo.toml` line 39 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1624#-Ns9J7nX9UGfx8YefY54:-Ns9xSbb7h2shnigT-Iv:b-vtvh3r) ([raw file](https://github.com/starkware-libs/blockifier/blob/2cacbeb9676fd28e994f0c9ea54469077b5a9806/Cargo.toml#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not sure this is needed now that the native is disconnected: did you already publish this non-RC blockifier version, and is papyrus v0.3.0 (non-RC) pointing to blockifier v0.5.0 (non-RC)?
</blockquote></details>

Published non-rc blockifier.
Waiting for Yair to publish papyrus.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1624)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`Cargo.toml` line 39 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1624#-Ns9J7nX9UGfx8YefY54:-NsC_iZJ2w9sOQytBEZN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2cacbeb9676fd28e994f0c9ea54469077b5a9806/Cargo.toml#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how is this PR passing if papyrus 0.3.0 isn't published yet...?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1624#-:-NsChYrbEVrboKfNN3hV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
