### PR TITLE
Dori/merge 0.12.0 into main 2

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/643)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/643)* status: 25 of 30 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/643#-NYS1xFV0tCLEAJ9ejSF:-NYS1xFV0tCLEAJ9ejSG:b-df009r) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7cfdb8c0771069d0c312f556f009c38e9a1bc2c/crates/blockifier/src/transaction/account_transactions_test.rs#L68)):*
> ```XML
> <<<<<<< HEAD
> #[test]
> fn test_fee_enforcement() {
> ```

test moved down (+ added nonce manager usage)



_Code quote:_
```XML
test_fee_enforcement
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/643#-NYS20M47DWmBfWTx2hn:-NYS20M47DWmBfWTx2ho:bbrat8s) ([raw file](https://github.com/starkware-libs/blockifier/blob/08655c50fc0f1a8f8ec07aacdf2bb23b3c27d989/crates/blockifier/src/transaction/account_transactions_test.rs#L214)):*
> ```XML
>     // Try two runs for each recursion type: one short run (success), and one that reverts due to
>     // step limit.
>     [(1_u32, true, true), (1000_u32, false, true), (3_u32, true, false), (1000_u32, false, false)]
> ```

on main, txs failing execution will be reverted, no failed.
that means:
1. nonce is increased even for the failures (no need to manually track nonce anymore, just use nonce manager)
2. no error is returned - need to read the `revert_reason`
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 703 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/643#-NYS2FVH5C5YdzWZk90v:-NYS2FVH5C5YdzWZk90w:bfbw59r) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7cfdb8c0771069d0c312f556f009c38e9a1bc2c/crates/blockifier/src/transaction/transactions_test.rs#L703)):*
> ```XML
> <<<<<<< HEAD
> =======
> fn create_account_tx_for_validate_test(
> ```

function moved to test utils on main-v0.12.0, now on main :)



_Code quote:_
```XML
create_account_tx_for_validate_test
```

**Comment by ilyalesokhin-starkware** [comment]
*[`-- commits` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/643#-NYS2n4747xrYHjWe0-A):*




_Suggestion:_
```
erge remote-tracking branch 'origin/main-v0.12.0' into 'main' (with conflicts)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/643)* status: 25 of 30 files reviewed, 4 unresolved discussions (waiting on @giladchase, @ilyalesokhin-starkware, and @noaov1)

___
*[`-- commits` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/643#-NYS2n4747xrYHjWe0-A):*
`git rebase -i HEAD~X` doesn't show this commit, so... nah

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/643)* status: 27 of 30 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

___
*[`-- commits` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/643#-NYS2n4747xrYHjWe0-A):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`git rebase -i HEAD~X` doesn't show this commit, so... nah
</blockquote></details>

ok

**Review by giladchase — APPROVED** [review]
> Reviewed 25 of 29 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/643)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/643)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/643)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
