### PR TITLE
test(concurrency): test finish execution and finish validation in scheduler

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
Is the code rebased over `main`?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-:-NxI3L_R9VWiXEXjwKSt:b-hrw729)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801)* status: all files reviewed, 8 unresolved discussions (waiting on @avi-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxINTyyDCeCKDpLZNd3:-NxINTyz2UT1br7_C4YG:b3ihjak) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler.rs#L177)):*
> ```XML
>             self.decrease_counter.fetch_add(1, Ordering::SeqCst);
>         }
>     }
> ```

I think we should remove this method



_Code quote:_
```XML
    // TODO(Avi, 01/04/2024): Remove dead_code attribute.
    #[allow(dead_code)]
    fn decrease_execution_index(&self, target_index: TxIndex) {
        let previous_execution_index =
            self.execution_index.fetch_min(target_index, Ordering::SeqCst);
        if target_index < previous_execution_index {
            self.decrease_counter.fetch_add(1, Ordering::SeqCst);
        }
    }
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIOtJZ3BarwXKtmNfy:-NxIOtJZ3BarwXKtmNfz:bnqkd6e) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L132)):*
> ```XML
> #[should_panic(expected = "Only executing transactions can gain status executed. Transaction 0 \
>                            is not executing. Transaction status: Aborting.")]
> #[case::wrong_status_aborting(0, TransactionStatus::Aborting, 0)]
> ```

all three last cases in a different test for `set_executed_status`



_Code quote:_
```XML
#[should_panic(expected = "Only executing transactions can gain status executed. Transaction 0 \
                           is not executing. Transaction status: ReadyToExecute.")]
#[case::wrong_status_ready(0, TransactionStatus::ReadyToExecute, 0)]
#[should_panic(expected = "Only executing transactions can gain status executed. Transaction 0 \
                           is not executing. Transaction status: Executed.")]
#[case::wrong_status_executed(0, TransactionStatus::Executed, 0)]
#[should_panic(expected = "Only executing transactions can gain status executed. Transaction 0 \
                           is not executing. Transaction status: Aborting.")]
#[case::wrong_status_aborting(0, TransactionStatus::Aborting, 0)]
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 136 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxINfHN0WC0UCSJgeyF:-NxINfHN0WC0UCSJgeyG:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L136)):*
> ```XML
>     #[case] tx_index: usize,
>     #[case] tx_status: TransactionStatus,
>     #[case] validation_index: usize,
> ```





_Suggestion:_
```XML
    #[case] tx_index: TxIndex,
    #[case] tx_status: TransactionStatus,
    #[case] validation_index: TxIndex,
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 138 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIOHPi5zTXfiXkTGBV:-NxIOHPi5zTXfiXkTGBW:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L138)):*
> ```XML
>     #[case] validation_index: usize,
> ) {
>     let n_active_tasks = 5;
> ```





_Suggestion:_
```XML
let n_active_tasks = 1
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 166 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIPAWXBFtw5eg85ino:-NxIPAWXBFtw5eg85inp:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L166)):*
> ```XML
>     if result {
>         assert_eq!(*scheduler.lock_tx_status(0), TransactionStatus::Aborting);
>     }
> ```





_Suggestion:_
```XML
    let tx_index = 0;
    let scheduler = Scheduler::new(DEFAULT_CHUNK_SIZE);
    scheduler.set_tx_status(tx_index, target_status);
    let result = scheduler.try_validation_abort(tx_index);
    assert_eq!(result, expected_result);
    if result {
        assert_eq!(*scheduler.lock_tx_status(tx_index), TransactionStatus::Aborting);
    }
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 187 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIPSS96E584igky9PP:-NxIPSS96E584igky9PQ:b-ojr0yu) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L187)):*
> ```XML
> #[should_panic(expected = "Only aborting transactions can be re-executed. Transaction 0 is not \
>                            aborting. Transaction status: Executing.")]
> #[case::wrong_status_executing(0, TransactionStatus::Executing, 0, true, None)]
> ```

all three last cases in a different test for `set_ready_status`



_Code quote:_
```XML
#[should_panic(expected = "Only aborting transactions can be re-executed. Transaction 0 is not \
                           aborting. Transaction status: ReadyToExecute.")]
#[case::wrong_status_ready(0, TransactionStatus::ReadyToExecute, 0, true, None)]
#[should_panic(expected = "Only aborting transactions can be re-executed. Transaction 0 is not \
                           aborting. Transaction status: Executed.")]
#[case::wrong_status_executed(0, TransactionStatus::Executed, 0, true, None)]
#[should_panic(expected = "Only aborting transactions can be re-executed. Transaction 0 is not \
                           aborting. Transaction status: Executing.")]
#[case::wrong_status_executing(0, TransactionStatus::Executing, 0, true, None)]
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 193 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIPYE38T-w-thVUEET:-NxIPYE38T-w-thVUEEU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L193)):*
> ```XML
>     #[case] execution_index: usize,
>     #[case] aborted: bool,
>     #[case] expected_result: Option<Task>,
> ```





_Suggestion:_
```XML
    #[case] tx_index: TxIndex,
    #[case] tx_status: TransactionStatus,
    #[case] execution_index: TxIndex,
    #[case] aborted: bool,
    #[case] expected_result: Option<Task>,
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 218 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIQ2YX8p9xxYzcTWBU:-NxIQ2YY7Q_ZZV-d5G5U:b-cplv9b) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L218)):*
> ```XML
>         assert_eq!(new_n_active_tasks, n_active_tasks - 1);
>         assert_eq!(*new_status, TransactionStatus::ReadyToExecute);
>     }
> ```

Can we manage without this `if` block as we did in the last test PR?
Some ideas:
1. add args to the test?
2. `result` is already been checked?
3. use some `match` in the beginning to divide 2 cases?



_Code quote:_
```XML
    if !aborted {
        assert!(result.is_none());
        assert_eq!(new_n_active_tasks, n_active_tasks - 1);
        assert_eq!(*new_status, TransactionStatus::Executed);
    } else if execution_index > tx_index {
        assert!(result.is_some());
        assert_eq!(new_n_active_tasks, n_active_tasks);
        assert_eq!(*new_status, TransactionStatus::Executing);
    } else {
        assert!(result.is_none());
        assert_eq!(new_n_active_tasks, n_active_tasks - 1);
        assert_eq!(*new_status, TransactionStatus::ReadyToExecute);
    }
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxINTyyDCeCKDpLZNd3:-NxIRyuY9arBgwKVIGfn:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler.rs#L177)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I think we should remove this method
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIOtJZ3BarwXKtmNfy:-NxIa5WP2qPr07TFBpUI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L132)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

all three last cases in a different test for `set_executed_status`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 136 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxINfHN0WC0UCSJgeyF:-NxIa6DcErmD2TQwe4IX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L136)):*
> ```XML
>     #[case] tx_index: usize,
>     #[case] tx_status: TransactionStatus,
>     #[case] validation_index: usize,
> ```

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 138 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIOHPi5zTXfiXkTGBV:-NxIaBno-ual23_3MJva:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L138)):*
> ```XML
>     #[case] validation_index: usize,
> ) {
>     let n_active_tasks = 5;
> ```

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 166 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIPAWXBFtw5eg85ino:-NxIaSFFAJN0d8LiJKWY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L166)):*
> ```XML
>     if result {
>         assert_eq!(*scheduler.lock_tx_status(0), TransactionStatus::Aborting);
>     }
> ```

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 187 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIPSS96E584igky9PP:-NxIaSslA_ZKqUYWRlQl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L187)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

all three last cases in a different test for `set_ready_status`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 193 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIPYE38T-w-thVUEET:-NxIaT4q1abdH0mTb4Dc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L193)):*
> ```XML
>     #[case] execution_index: usize,
>     #[case] aborted: bool,
>     #[case] expected_result: Option<Task>,
> ```

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 218 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxIQ2YX8p9xxYzcTWBU:-NxIaTkM5hEHn3uEWitB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L218)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Can we manage without this `if` block as we did in the last test PR?
Some ideas:
1. add args to the test?
2. `result` is already been checked?
3. use some `match` in the beginning to divide 2 cases?
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801)* status: all files reviewed, 12 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 158 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxILMAs9P1z4OQyjpyq:-NxILMAs9P1z4OQyjpyr:b-yabo6w) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L158)):*
> ```XML
> fn test_try_validation_abort(
>     #[case] target_status: TransactionStatus,
>     #[case] expected_result: bool,
> ```

I'm wondering if it's needed. You can check `target_status == TransactionStatus::Executed`.



_Code quote:_
```XML
    #[case] expected_result: bool,
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 203 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLubEr1KR_lTKGAGzl:-NxLubEr1KR_lTKGAGzm:btdaxks) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L203)):*
> ```XML
>     #[case] aborted: bool,
> ) {
>     let n_active_tasks = 5;
> ```

For consistency



_Suggestion:_
```XML
    let n_active_tasks = 1;
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLvtKv3YF7Tc_lPLTW:-NxLvtKv3YF7Tc_lPLTX:b-oj98rz) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L215)):*
> ```XML
>     match aborted {
>         true => {
>             if execution_index > tx_index {
> ```

What if `try_incarnate` returns false? We don't want to check it?



_Code quote:_
```XML
if execution_index > tx_index {
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 227 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLw3oX0yPBiugltQPv:-NxLw3oX0yPBiugltQPw:bxtub52) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L227)):*
> ```XML
>         false => {
>             assert!(result.is_none());
>             assert_eq!(*new_status, TransactionStatus::Executed);
> ```

Is it needed?



_Code quote:_
```XML
            assert_eq!(*new_status, TransactionStatus::Executed);
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLvtKv3YF7Tc_lPLTW:-NxMfvtICdVhH1FbjnGF:bk58ivq) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L215)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What if `try_incarnate` returns false? We don't want to check it?
</blockquote></details>

The `finish_validation` calls `set_ready_status`, so it makes the `try_incarnate` return `true` anyway.

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 227 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLw3oX0yPBiugltQPv:-NxMjy2rEMWVufupJNjf:b901ape) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L227)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

not needed IMO

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 130 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxMJxiLCHEzHJQbA3wh:-NxMJxiLCHEzHJQbA3wi:bttwku) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L130)):*
> ```XML
> #[should_panic(expected = "Only executing transactions can gain status executed. Transaction 0 \
>                            is not executing. Transaction status: Aborting.")]
> #[case::wrong_status_aborting(TransactionStatus::Aborting)]
> ```

Add positive flow?



_Code quote:_
```XML
#[should_panic(expected = "Only executing transactions can gain status executed. Transaction 0 \
                           is not executing. Transaction status: ReadyToExecute.")]
#[case::wrong_status_ready(TransactionStatus::ReadyToExecute)]
#[should_panic(expected = "Only executing transactions can gain status executed. Transaction 0 \
                           is not executing. Transaction status: Executed.")]
#[case::wrong_status_executed(TransactionStatus::Executed)]
#[should_panic(expected = "Only executing transactions can gain status executed. Transaction 0 \
                           is not executing. Transaction status: Aborting.")]
#[case::wrong_status_aborting(TransactionStatus::Aborting)]
```

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801)* status: all files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 202 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxMxy642IrpbGFD_XSR:-NxMxy642IrpbGFD_XSS:b-a13q61) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L202)):*
> ```XML
>     #[case] execution_index: TxIndex,
>     #[case] aborted: bool,
> ) {
> ```

As discussed offline 



_Suggestion:_
```XML
fn test_finish_validation(
    #[case] tx_index: TxIndex,
    #[case] execution_index: TxIndex,
    #[case] aborted: bool,
) {
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 158 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxILMAs9P1z4OQyjpyq:-NxNBp_u4r3jOCOYOWDb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/722e94d5e1cf641f8da6764e49fe731d231cad6f/crates/blockifier/src/concurrency/scheduler_test.rs#L158)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm wondering if it's needed. You can check `target_status == TransactionStatus::Executed`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 130 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxMJxiLCHEzHJQbA3wh:-NxNBqhQ3q0Ys34GaMuR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L130)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Add positive flow?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 202 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxMxy642IrpbGFD_XSR:-NxN9FxZ6DStNf0PUfLN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L202)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

As discussed offline
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 203 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLubEr1KR_lTKGAGzl:-NxN7pL00yzlGV-PCExf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L203)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

For consistency
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLvtKv3YF7Tc_lPLTW:-NxNB4ST3NB29DbLdt1B:bj12qcq) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L215)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

The `finish_validation` calls `set_ready_status`, so it makes the `try_incarnate` return `true` anyway.
</blockquote></details>

Yes, and if `set_ready_status` fails it panics, so this flow of `finish_validation` would stop at the call to `set_ready_status`. Moreover, the panic flow is checked in `test_set_ready_status`, so no need to check it again here.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 227 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLw3oX0yPBiugltQPv:-NxN9OpzBFkwx9eOWz_O:bwgh2oq) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L227)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

not needed IMO
</blockquote></details>

I think it is needed. The function changes the status of the tx, so I think we should check the status even in the flow where it shouldn't change.

It also makes this flow of the test slightly more explicit, and makes all three flows comparable (each checks the same three parameters have their expected values).

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 227 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLw3oX0yPBiugltQPv:-NxRDcMZ8WO5Bq2PWpRQ:b-ucxlcb) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L227)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think it is needed. The function changes the status of the tx, so I think we should check the status even in the flow where it shouldn't change.

It also makes this flow of the test slightly more explicit, and makes all three flows comparable (each checks the same three parameters have their expected values).
</blockquote></details>

Convincing (:
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 122 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxRDsj65Il5vJmmALbA:-NxRDsj7CHw4gkTUEEOS:b-6uhohy) ([raw file](https://github.com/starkware-libs/blockifier/blob/c715432d39cd68e8bd04aef3574883e9427976ae/crates/blockifier/src/concurrency/scheduler_test.rs#L122)):*
> ```XML
> 
> #[rstest]
> #[case::positive_flow(TransactionStatus::Executing)]
> ```

Rename the case name in `test_set_ready_status` as well



_Suggestion:_
```XML
#[case::happy_flow(TransactionStatus::Executing)]
```

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLvtKv3YF7Tc_lPLTW:-NxRWCTO3GgAuRZQXoZi:bzbh6l3) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L215)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Yes, and if `set_ready_status` fails it panics, so this flow of `finish_validation` would stop at the call to `set_ready_status`. Moreover, the panic flow is checked in `test_set_ready_status`, so no need to check it again here.
</blockquote></details>

I see. Since this test is not multi-threaded. 
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 227 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLw3oX0yPBiugltQPv:-NxRBFPk19CnNO1LVXog:b-fr4ugn) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L227)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Convincing (:
</blockquote></details>

But the status does not have to be executed, no? We can finish validation with another status

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 227 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLw3oX0yPBiugltQPv:-NxRX7CDE8odfzGPMssX:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L227)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

But the status does not have to be executed, no? We can finish validation with another status
</blockquote></details>

.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 215 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLvtKv3YF7Tc_lPLTW:-NxRcMn19G-A5rOvhevB:bb77ufg) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L215)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see. Since this test is not multi-threaded.
</blockquote></details>

Yes.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 227 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxLw3oX0yPBiugltQPv:-NxRcRI2AyMYQC7132h0:b6t4ghp) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f80b8d4baba48e446afb1db3f9975c84d2c50b5/crates/blockifier/src/concurrency/scheduler_test.rs#L227)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

.
</blockquote></details>

We can't start validation unless the status is Executed. Another thread might change the status while the validation is running, but in this specific unit-test we manually set the status to Executed, so we are just making sure the status hasn't changed.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 122 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-NxRDsj65Il5vJmmALbA:-NxReEy_Dniz65ffn22H:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c715432d39cd68e8bd04aef3574883e9427976ae/crates/blockifier/src/concurrency/scheduler_test.rs#L122)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Rename the case name in `test_set_ready_status` as well
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-:-NxReZuH2zQ-390p5w-A:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1801#-:-NxRf4KTBG7L2BZrZRGi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
