### PR TITLE
chore(execution): fix the tests using create_state_changes_for_test for readability and correctness

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1430)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/state/cached_state_test.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-NpotCqT3aWIAoROqrqy:-NpotCqT3aWIAoROqrqz:b7rrfcj) ([raw file](https://github.com/starkware-libs/blockifier/blob/f06bea6b66c6ebaf8b53687ada905a0e535aca38/crates/blockifier/src/state/cached_state_test.rs#L286)):*
> ```XML
>     //     let sender_balance_key = get_fee_token_var_address(sender_address);
>     //     state.set_storage_at(fee_token_address, sender_balance_key,
>     // stark_felt!("0x1999")).unwrap(); }
> ```

We might want to add this for future tests....



_Code quote:_
```XML
    // if let Some(sender_address) = sender_address {
    //     // Charge fee from the sender.
    //     let sender_balance_key = get_fee_token_var_address(sender_address);
    //     state.set_storage_at(fee_token_address, sender_balance_key,
    // stark_felt!("0x1999")).unwrap(); }
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1430)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-NpotCqT3aWIAoROqrqy:-Npoz8-d62xg-yeFMXOw:b-sgs89z) ([raw file](https://github.com/starkware-libs/blockifier/blob/f06bea6b66c6ebaf8b53687ada905a0e535aca38/crates/blockifier/src/state/cached_state_test.rs#L286)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We might want to add this for future tests....
</blockquote></details>

can you explain? I think I'm not in context
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 299 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-Npoyc__6wkEKx4KkfH9:-Npoyc__6wkEKx4KkfHA:b-h65ltq) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b74ff783ca312f874cc8c12114ac5b07bbb1a4c/crates/blockifier/src/state/cached_state_test.rs#L299)):*
> ```XML
>         } else {
>             1 // 1 for storage update.
>         },
> ```

... assuming it's a `usize`



_Suggestion:_
```XML
        // 1 for storage update + 1 for sender balance update if sender is defined..
        n_storage_updates: 1 + usize::from(sender_address.is_some()),
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 343 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-NpozDCp9fIiTq0fc9kM:-NpozDCp9fIiTq0fc9kN:b-i5v2vi) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a5c14185c65804298b2a84cfb38d2e9aeaaa499/crates/blockifier/src/state/cached_state_test.rs#L343)):*
> ```XML
>         .unwrap();
>     transactional_state
>         .set_storage_at(contract_address2, storage_key2, stark_felt!("0x4321"))
> ```

why was this extra write dropped...?



_Code quote:_
```XML
    let (contract_address2, storage_key2) = *storage_updates_keys.next().unwrap();
    // A new address, not included in state_changes1, to write to.
    let new_contract_address = ContractAddress(patricia_key!("0x111"));

    // Overwrite existing and new storage values.
    transactional_state
        .set_storage_at(contract_address, storage_key, stark_felt!("0x1234"))
        .unwrap();
    transactional_state
        .set_storage_at(contract_address2, storage_key2, stark_felt!("0x4321"))
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1430)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-NpotCqT3aWIAoROqrqy:-NpsGDQi3-00VOs3AmoX:bj2mtio) ([raw file](https://github.com/starkware-libs/blockifier/blob/f06bea6b66c6ebaf8b53687ada905a0e535aca38/crates/blockifier/src/state/cached_state_test.rs#L286)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you explain? I think I'm not in context
</blockquote></details>

The context is a refactor in `get_actual_state_changes_for_fee_charge` - more remove it and replace with a simpler function.
We want to include an update to the balance of `sender_address` as a part of the `state`, for tests.
The function `get_actual_state_changes_for_fee_charge` then returns a `StateChanges` objects where the balance of `sender_address` is set to `0`. 


I added it to the test, thanks to you asking and me rethinking it.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 299 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-Npoyc__6wkEKx4KkfH9:-NpsIRsf3PJgsay-5Xyw:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b74ff783ca312f874cc8c12114ac5b07bbb1a4c/crates/blockifier/src/state/cached_state_test.rs#L299)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... assuming it's a `usize`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 343 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-NpozDCp9fIiTq0fc9kM:-NpsG4963EvZd0MXj5Or:bl7fvtx) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a5c14185c65804298b2a84cfb38d2e9aeaaa499/crates/blockifier/src/state/cached_state_test.rs#L343)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was this extra write dropped...?
</blockquote></details>

All of the references to `contract_address2` are:
1. Wrong. This unwrap returns the fee toke address - when there is a sender address.
2. unhelpful - it is not used in a way that helps test some interesting scenarios. 
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 266 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-NpsdcTV7y9mnK-txn6_:-NpsdcTV7y9mnK-txn6a:bpirony) ([raw file](https://github.com/starkware-libs/blockifier/blob/5965fe41908bdcec1b35d8cc90262fc16ee7e85c/crates/blockifier/src/state/cached_state_test.rs#L266)):*
> ```XML
>     fee_token_address: ContractAddress,
> ) -> StateChanges {
>     let contract_address = contract_address!(CONTRACT_ADDRESS);
> ```

@dorimedini-starkware, This infra screams for our feature contract infra.
I am not using it because I am diverging as is. 



_Code quote:_
```XML
let contract_address = contract_address!(CONTRACT_ADDRESS);
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1430)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-Npt-Le7C_ngGjpsvx2t:-Npt-Le7C_ngGjpsvx2u:b-rgx5va) ([raw file](https://github.com/starkware-libs/blockifier/blob/34aa07d3b35bef0380b2599b0e4085e283418ab1/crates/blockifier/src/state/cached_state_test.rs#L17)):*
> ```XML
> use crate::test_utils::{get_test_contract_class, TEST_CLASS_HASH, TEST_EMPTY_CONTRACT_CLASS_HASH};
> 
> pub const CONTRACT_ADDRESS: &str = "0x100";
> ```

to make sure this custom infra isn't reused too much...



_Suggestion:_
```XML
const CONTRACT_ADDRESS: &str = "0x100";
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 349 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-Npt2m1K4wwUG1ErHCbe:-Npt2m1L8oSQPDe9mfnJ:bijecpl) ([raw file](https://github.com/starkware-libs/blockifier/blob/34aa07d3b35bef0380b2599b0e4085e283418ab1/crates/blockifier/src/state/cached_state_test.rs#L349)):*
> ```XML
>     // The hash map 'storage_updates' is unordered, so we make sure we use the correct contract
>     // address.
>     let (contract_address, storage_key) = {
> ```

maybe use `find` instead of this ultra-explicit if-else-if stuff?



_Suggestion:_
```XML
let (contract_address, storage_key) = storage_updates_keys.find(...)
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1430)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-Npt-Le7C_ngGjpsvx2t:-Npt93LK0jcFNDbK8pea:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/34aa07d3b35bef0380b2599b0e4085e283418ab1/crates/blockifier/src/state/cached_state_test.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

to make sure this custom infra isn't reused too much...
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 349 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-Npt2m1K4wwUG1ErHCbe:-Npt91TH7xPt_Kwhlr-D:b-pzd2uf) ([raw file](https://github.com/starkware-libs/blockifier/blob/34aa07d3b35bef0380b2599b0e4085e283418ab1/crates/blockifier/src/state/cached_state_test.rs#L349)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe use `find` instead of this ultra-explicit if-else-if stuff?
</blockquote></details>

Done.
TY!

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1430)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-Nptj9gYErGNOv64QGBZ:-Nptj9gYErGNOv64QGB_:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/48d5ca59495b22524c380358b635f9efb0868d37/crates/blockifier/src/state/cached_state_test.rs#L348)):*
> ```XML
>     let mut storage_updates_keys = state_changes1.storage_updates.keys();
>     let &(contract_address, storage_key) = storage_updates_keys
>         .find(|(contract_address, _)| contract_address == &contract_address!("0x100"))
> ```





_Suggestion:_
```XML
CONTRACT_ADDRESS
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-:-NptkprR20rN1s6e9FPz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1430)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1430#-Nptj9gYErGNOv64QGBZ:-NptkyqiBrww7HQD_cWm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/48d5ca59495b22524c380358b635f9efb0868d37/crates/blockifier/src/state/cached_state_test.rs#L348)):*
> ```XML
>     let mut storage_updates_keys = state_changes1.storage_updates.keys();
>     let &(contract_address, storage_key) = storage_updates_keys
>         .find(|(contract_address, _)| contract_address == &contract_address!("0x100"))
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1430)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
