### PR TITLE
refactor: change variable and function names for gas_vector

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1400)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1400)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-NpP6HB1B97JILgiwtxr:-NpP6HB1B97JILgiwtxs:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/72dd465fdd2411ccccaa5206eb1e4ded0ad54130/crates/blockifier/src/fee/fee_utils.rs#L80)):*
> ```XML
> }
> 
> pub fn get_fee_by_gas_usage_vector(
> ```





_Suggestion:_
```XML
pub fn get_fee_by_gas_vector(
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-NpPCNADDdCULa4audHW:-NpPCNADDdCULa4audHX:bv4nacf) ([raw file](https://github.com/starkware-libs/blockifier/blob/72dd465fdd2411ccccaa5206eb1e4ded0ad54130/crates/blockifier/src/transaction/account_transaction.rs#L181)):*
> ```XML
>     ) -> TransactionPreValidationResult<()> {
>         // TODO(Aner, 21/01/24) modify for 4844 (blob_gas).
>         let minimal_l1_gas_amount_vector = estimate_minimal_l1_gas(block_context, self)?;
> ```

In the next PR we deal with minimal vectors.



_Code quote:_
```XML
minimal_l1_gas_amount_vector
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-NpP8EiL3V1nXpKfIo_G:-NpP8EiL3V1nXpKfIo_H:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/72dd465fdd2411ccccaa5206eb1e4ded0ad54130/crates/blockifier/src/transaction/transaction_utils.rs#L23)):*
> ```XML
> pub fn calculate_tx_resources(
>     execution_resources: &ExecutionResources,
>     l1_gas_usage_vector: GasVector,
> ```





_Suggestion:_
```XML
gas_vector
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1400)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-NpPSpIv29OxdaGCnsPT:-NpPSpIv29OxdaGCnsPU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/72dd465fdd2411ccccaa5206eb1e4ded0ad54130/crates/blockifier/src/fee/fee_utils.rs#L82)):*
> ```XML
> pub fn get_fee_by_gas_usage_vector(
>     block_info: &BlockInfo,
>     l1_gas_usage_vector: GasVector,
> ```





_Suggestion:_
```XML
l1_gas_vector
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-NpPT3Cw1hTCrIV0CoXY:-NpPT3Cw1hTCrIV0CoXZ:b-g32iy3) ([raw file](https://github.com/starkware-libs/blockifier/blob/72dd465fdd2411ccccaa5206eb1e4ded0ad54130/crates/blockifier/src/transaction/account_transactions_test.rs#L337)):*
> ```XML
>         estimate_minimal_l1_gas(&block_context, &account_tx).unwrap();
>     let estimated_min_l1_gas = estimated_min_gas_usage_vector.l1_gas;
>     let estimated_min_fee = get_fee_by_gas_usage_vector(
> ```

In the next PR you will also need to change this check...



_Code quote:_
```XML
    let estimated_min_gas_usage_vector =
        estimate_minimal_l1_gas(&block_context, &account_tx).unwrap();
    let estimated_min_l1_gas = estimated_min_gas_usage_vector.l1_gas;
    let estimated_min_fee = get_fee_by_gas_usage_vector(
```

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/fee/fee_utils.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-NpPSpIv29OxdaGCnsPT:-NpPVNqJBbMuI5zmLXRo:b-9hlu9p) ([raw file](https://github.com/starkware-libs/blockifier/blob/72dd465fdd2411ccccaa5206eb1e4ded0ad54130/crates/blockifier/src/fee/fee_utils.rs#L82)):*
> ```XML
> pub fn get_fee_by_gas_usage_vector(
>     block_info: &BlockInfo,
>     l1_gas_usage_vector: GasVector,
> ```

I guess just `gas_vector`, since later it might contain l2?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1400)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-NpPSpIv29OxdaGCnsPT:-NpPVwNQ5F6UuKteNsID:byl40pd) ([raw file](https://github.com/starkware-libs/blockifier/blob/72dd465fdd2411ccccaa5206eb1e4ded0ad54130/crates/blockifier/src/fee/fee_utils.rs#L82)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I guess just `gas_vector`, since later it might contain l2?
</blockquote></details>

even better

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-:-NpPXD8Q7DsXpmwzczBO:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @Yoni-Starkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/fee/fee_utils.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-NpP6HB1B97JILgiwtxr:-NpPc4d1-c-jiy6p3MWH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/72dd465fdd2411ccccaa5206eb1e4ded0ad54130/crates/blockifier/src/fee/fee_utils.rs#L80)):*
> ```XML
> }
> 
> pub fn get_fee_by_gas_usage_vector(
> ```

Done.

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-NpPT3Cw1hTCrIV0CoXY:-NpPcz7J3AckxqOe3-6N:b-r19fls) ([raw file](https://github.com/starkware-libs/blockifier/blob/72dd465fdd2411ccccaa5206eb1e4ded0ad54130/crates/blockifier/src/transaction/account_transactions_test.rs#L337)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

In the next PR you will also need to change this check...
</blockquote></details>

Right: https://reviewable.io/reviews/starkware-libs/blockifier/1401

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-NpP8EiL3V1nXpKfIo_G:-NpPd2HSBfpGSpROh2l_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/72dd465fdd2411ccccaa5206eb1e4ded0ad54130/crates/blockifier/src/transaction/transaction_utils.rs#L23)):*
> ```XML
> pub fn calculate_tx_resources(
>     execution_resources: &ExecutionResources,
>     l1_gas_usage_vector: GasVector,
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1400)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1400)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1400#-:-NpPmEuA8hdMyel8UL4W:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
