### PR TITLE
Update validate_final_balances and usages

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/910#-Nemv0DGE1MH4j0qxCT6:-Nemv0DGE1MH4j0qxCT7:b-1mlqo3) ([raw file](https://github.com/starkware-libs/blockifier/blob/827c6e50bb584d93ad74c7fafdf63f0a5dd8e250/crates/blockifier/src/transaction/transactions_test.rs#L239)):*
> ```XML
>         FeeType::Eth => (initial_account_balance - expected_actual_fee.0, 0_u128),
>         FeeType::Strk => (0_u128, initial_account_balance - expected_actual_fee.0),
>     };
> ```

There must be a better way :thinking:  can't think of anything off the top, so approving for now



_Code quote:_
```XML
    let (expected_sequencer_balance_eth, expected_sequencer_balance_strk) = match fee_type {
        FeeType::Eth => (stark_felt!(expected_actual_fee.0), StarkFelt::ZERO),
        FeeType::Strk => (StarkFelt::ZERO, stark_felt!(expected_actual_fee.0)),
    };
    let (expected_account_balance_eth, expected_account_balance_strk) = match fee_type {
        FeeType::Eth => (initial_account_balance - expected_actual_fee.0, 0_u128),
        FeeType::Strk => (0_u128, initial_account_balance - expected_actual_fee.0),
    };
```

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/910#-Nemv0DGE1MH4j0qxCT6:-NemwrOYChH0vS6yWDHx:b7q2w1w) ([raw file](https://github.com/starkware-libs/blockifier/blob/367055552d35a62c5d7e530f47e76075de1f2768/crates/blockifier/src/transaction/transactions_test.rs#L239)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

There must be a better way :thinking:  can't think of anything off the top, so approving for now
</blockquote></details>

we can do something like
```
let a = if Eth { X } else { Y };
let b = Y - a;
```
... but not with `StarkFelt`s (no arithmetic).

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/910#-Nemv0DGE1MH4j0qxCT6:-Nen4q64CeOHTRPmXmST:b-pszvlw) ([raw file](https://github.com/starkware-libs/blockifier/blob/367055552d35a62c5d7e530f47e76075de1f2768/crates/blockifier/src/transaction/transactions_test.rs#L239)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we can do something like
```
let a = if Eth { X } else { Y };
let b = Y - a;
```
... but not with `StarkFelt`s (no arithmetic).
</blockquote></details>

Mmm i think we can leave it as it is, until we think of a better methodology altogether

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, @giladchase, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 430 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/910#-NfuPphuE4GCv4U2bYVa:-NfuPphv-tBkTElf4lde:b1khdib) ([raw file](https://github.com/starkware-libs/blockifier/blob/04514747f6f19a015486da72e23420720172541b/crates/blockifier/src/transaction/transactions_test.rs#L430)):*
> ```XML
>         fee_type,
>         BALANCE,
>         BALANCE,
> ```

It works as long as the `eth_fee_token_address=strk_fee_token_address`, no?
Are we planning to change that?
Do we plan to update the account contract test balance in both ERC20 contracts on each test?



_Code quote:_
```XML
        BALANCE,
        BALANCE,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 430 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/910#-NfuPphuE4GCv4U2bYVa:-NfuRkF43jVID_thHz-L:b-y0muqb) ([raw file](https://github.com/starkware-libs/blockifier/blob/04514747f6f19a015486da72e23420720172541b/crates/blockifier/src/transaction/transactions_test.rs#L430)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It works as long as the `eth_fee_token_address=strk_fee_token_address`, no?
Are we planning to change that?
Do we plan to update the account contract test balance in both ERC20 contracts on each test?
</blockquote></details>

WDYM? balances are set for [both contracts](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/transaction/test_utils.rs#L93), and the block context is set up with [two different addresses](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/test_utils.rs#L348) (`0x1001` and `0x1102`)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 430 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/910#-NfuPphuE4GCv4U2bYVa:-NfuSB8u0LcOa2zSF14e:b-dud32c) ([raw file](https://github.com/starkware-libs/blockifier/blob/04514747f6f19a015486da72e23420720172541b/crates/blockifier/src/transaction/transactions_test.rs#L430)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM? balances are set for [both contracts](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/transaction/test_utils.rs#L93), and the block context is set up with [two different addresses](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/test_utils.rs#L348) (`0x1001` and `0x1102`)
</blockquote></details>

*`0x1002`

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @giladchase, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 430 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/910#-NfuPphuE4GCv4U2bYVa:-NfuSJHs9IOK3aJbuCFt:bc8lu4a) ([raw file](https://github.com/starkware-libs/blockifier/blob/04514747f6f19a015486da72e23420720172541b/crates/blockifier/src/transaction/transactions_test.rs#L430)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

*`0x1002`
</blockquote></details>

:woman_facepalming: 
I was looking at an old commit, sorry.
We initialize it also for cairo0 tests, right?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 895 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/910#-NfuY-KO6dFuzk8Xjt2Q:-NfuY-KO6dFuzk8Xjt2R:b-xnlv7n) ([raw file](https://github.com/starkware-libs/blockifier/blob/04514747f6f19a015486da72e23420720172541b/crates/blockifier/src/transaction/transactions_test.rs#L895)):*
> ```XML
>         fee_type,
>         BALANCE,
>         0,
> ```

Do we want to update the balance of the about to be deployed contract also in the strk_fee_token contract?



_Code quote:_
```XML
        0,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 430 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/910#-NfuPphuE4GCv4U2bYVa:-NfuYaDC0mk5CR3PIEUk:bs1ya3t) ([raw file](https://github.com/starkware-libs/blockifier/blob/04514747f6f19a015486da72e23420720172541b/crates/blockifier/src/transaction/transactions_test.rs#L430)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

:woman_facepalming: 
I was looking at an old commit, sorry.
We initialize it also for cairo0 tests, right?
</blockquote></details>

yes, both `create_state_with_trivial_validation_account` and `create_state_with_cairo1_account` use `create_account_tx_test_state` internally (which sets these)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 895 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/910#-NfuY-KO6dFuzk8Xjt2Q:-NfuYoqVCUoMigi0d9dk:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/04514747f6f19a015486da72e23420720172541b/crates/blockifier/src/transaction/transactions_test.rs#L895)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we want to update the balance of the about to be deployed contract also in the strk_fee_token contract?
</blockquote></details>

WDYM?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, @giladchase, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 895 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/910#-NfuY-KO6dFuzk8Xjt2Q:-NfuYyRUA7EVBNlnvofq:b-3jri1k) ([raw file](https://github.com/starkware-libs/blockifier/blob/04514747f6f19a015486da72e23420720172541b/crates/blockifier/src/transaction/transactions_test.rs#L895)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

In the test itself we update the balance of the about to be deployed account contract in the eth erc20 contract only. When we will use a V3 deploy account transaction we will have to update it also in the strk erc20 contract, no?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @amosStarkware, @giladchase, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 895 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/910#-NfuY-KO6dFuzk8Xjt2Q:-NfutjUv6TPFc9bP-BeG:b66gf) ([raw file](https://github.com/starkware-libs/blockifier/blob/04514747f6f19a015486da72e23420720172541b/crates/blockifier/src/transaction/transactions_test.rs#L895)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In the test itself we update the balance of the about to be deployed account contract in the eth erc20 contract only. When we will use a V3 deploy account transaction we will have to update it also in the strk erc20 contract, no?
</blockquote></details>

Ahh!! right, good catch!
Done

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/910)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @zuphitf)

**Pull request merged**
