### PR TITLE
chore: move tx-too-big check to execute_raw

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1959)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1959)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/bouncer_test.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1959#-NzdN9LDCkUI77PJlK3v:-NzdN9LDCkUI77PJlK3w:bm833wh) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2cfead340c28223686a865e5ef750497e915581/crates/blockifier/src/bouncer_test.rs#L187)):*
> ```XML
>         TransactionExecutionError::TransactionTooLarge
>     ))
> )]
> ```

No worries, tx-too-large is covered in this test: https://github.com/starkware-libs/blockifier/blob/7d9ebe996796cc6c4f38a104599630da0177b13c/crates/blockifier/src/blockifier/transaction_executor_test.rs#L240



_Code quote:_
```XML
#[case::transaction_too_large(
    0,
    21,
    0,
    Err(TransactionExecutorError::TransactionExecutionError(
        TransactionExecutionError::TransactionTooLarge
    ))
)]
#[case::positive_flow_with_keccak(0, 0, 1, Ok(()))]
#[case::block_full_with_keccak(1, 0, 1, Err(TransactionExecutorError::BlockFull))]
#[case::transaction_too_large_with_keccak(
    0,
    0,
    2,
    Err(TransactionExecutorError::TransactionExecutionError(
        TransactionExecutionError::TransactionTooLarge
    ))
)]
#[case::block_full_with_keccak_ecdsa_exceeds(0, 11, 1, Err(TransactionExecutorError::BlockFull))]
#[case::transaction_too_large_with_keccak_ecdsa_too_large(
    0,
    21,
    1,
    Err(TransactionExecutorError::TransactionExecutionError(
        TransactionExecutionError::TransactionTooLarge
    ))
)]
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/bouncer_test.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1959#-NzdN9LDCkUI77PJlK3v:-NzhSGEKCcPCplHgke5p:b-qb0ect) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2cfead340c28223686a865e5ef750497e915581/crates/blockifier/src/bouncer_test.rs#L187)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No worries, tx-too-large is covered in this test: https://github.com/starkware-libs/blockifier/blob/7d9ebe996796cc6c4f38a104599630da0177b13c/crates/blockifier/src/blockifier/transaction_executor_test.rs#L240
</blockquote></details>

The test only checks the first case you removed here. Don't we want the case "too_large_with_keccak" and the case "too_larg_with_keccak_ecdsa"?

**Review by avi-starkware — DISMISSED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1959)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1959)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/bouncer_test.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1959#-NzdN9LDCkUI77PJlK3v:-NzieUBi23RD1tWUh1ap:b-ezkjqj) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2cfead340c28223686a865e5ef750497e915581/crates/blockifier/src/bouncer_test.rs#L187)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

The test only checks the first case you removed here. Don't we want the case "too_large_with_keccak" and the case "too_larg_with_keccak_ecdsa"?
</blockquote></details>

Done (kind of)
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 223 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1959#-NzhSqnmDt_Semwnw7iE:-NziL3-e0mSULuSu4TsI:b2o1hoc) ([raw file](https://github.com/starkware-libs/blockifier/blob/917944a38e3d7cdb2ba19138d18e99fc14cce635/crates/blockifier/src/concurrency/worker_logic.rs#L223)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Nonblocking
</blockquote></details>

```
binary operation `==` cannot be applied to type `blockifier::transaction\_executor::TransactionExecutorError`
```

**Review by avi-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1959)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1959#-:-NzvqSou6UnYLitnGiQe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1959)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
