### PR TITLE
Verify can pay 'max fee' for v3

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-NjDWQxm1UkLjuNPF_4D:-NjDWQxm1UkLjuNPF_4E:btayiyv) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ac25858a991c8568dd30192771d444abb286421/crates/blockifier/src/transaction/objects.rs#L74)):*
> ```XML
>             Self::Deprecated(context) => Ok(context.max_fee),
>         }
>     }
> ```

hooray!!



_Code quote:_
```XML
    pub fn max_fee(&self) -> TransactionExecutionResult<Fee> {
        match self {
            Self::Current(context) => {
                let l1_resource_bounds = context.l1_resource_bounds()?;
                // TODO(nir, 01/11/2023): Change to max_amount * block_context.gas_price.
                Ok(Fee(
                    l1_resource_bounds.max_amount as u128 * l1_resource_bounds.max_price_per_unit
                ))
            }
            Self::Deprecated(context) => Ok(context.max_fee),
        }
    }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-NjH3PLW-V1yciS3uL8D:-NjH3PLW-V1yciS3uL8E:bi7mckj) (no related file):*
[Python side](https://reviewable.io/reviews/starkware-industries/starkware/32604)

___

**Review by amosStarkware — CHANGES_REQUESTED** [review]
blocking until HODOR is nice on commit bump PR

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-:-NjLL5Jx7N9R1oWOjgYu:b-swguup)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 126 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-NjLIMjXEZp5IA60Mxno:-NjLIMjXEZp5IA60Mxnp:br99wz8) ([raw file](https://github.com/starkware-libs/blockifier/blob/2bcd15b83786611b44279de4c0758cbd5e68db41/crates/blockifier/src/fee/fee_utils.rs#L126)):*
> ```XML
>         Err(match account_tx_context {
>             AccountTransactionContext::Current(context) => {
>                 let l1_bounds = context.l1_resource_bounds()?;
> ```

unneeded, I think



_Code quote:_
```XML
let l1_bounds = context.l1_resource_bounds()?;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1086 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-NjLKdeZEqt_Ff4bRlGT:-NjLKde_E3JxxVw45Lkd:bdonnem) ([raw file](https://github.com/starkware-libs/blockifier/blob/2bcd15b83786611b44279de4c0758cbd5e68db41/crates/blockifier/src/transaction/account_transactions_test.rs#L1086)):*
> ```XML
> #[case(TransactionVersion::ONE, FeeType::Eth)]
> #[case(TransactionVersion::THREE, FeeType::Strk)]
> fn test_insufficient_balance_for_committed_bounds(
> ```

you're definitely right that the test should be here, but since a test for this already exists please add it there instead:
https://github.com/starkware-libs/blockifier/blob/2af191fd524611bf7fffa5eb6dabfe0e3b4a102e/crates/blockifier/src/transaction/transactions_test.rs#L505



_Code quote:_
```XML
n test_insufficient_balance_for_committed_bounds(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 126 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-NjLIMjXEZp5IA60Mxno:-NjMRlY29ZTuk_SLI6T6:b1u5vsl) ([raw file](https://github.com/starkware-libs/blockifier/blob/2bcd15b83786611b44279de4c0758cbd5e68db41/crates/blockifier/src/fee/fee_utils.rs#L126)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

unneeded, I think
</blockquote></details>

WDYM? Needed for `L1GasBoundsExceedBalance` error below
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1086 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-NjLKdeZEqt_Ff4bRlGT:-NjMUqI09dmyQWnmNk-b:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2bcd15b83786611b44279de4c0758cbd5e68db41/crates/blockifier/src/transaction/account_transactions_test.rs#L1086)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

you're definitely right that the test should be here, but since a test for this already exists please add it there instead:
https://github.com/starkware-libs/blockifier/blob/2af191fd524611bf7fffa5eb6dabfe0e3b4a102e/crates/blockifier/src/transaction/transactions_test.rs#L505
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-NjH3PLW-V1yciS3uL8D:-NjN3hqHBBZQNWRDPdOF:b-oxsoxz) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[Python side](https://reviewable.io/reviews/starkware-industries/starkware/32604)
</blockquote></details>

python side passed hodor, no hitting merge conflicts, so I think we're good as long as no real changes happen here

___

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1086 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-NjLKdeZEqt_Ff4bRlGT:-NjNISIt8x8uaemUMr0r:b-qy7hhi) ([raw file](https://github.com/starkware-libs/blockifier/blob/2bcd15b83786611b44279de4c0758cbd5e68db41/crates/blockifier/src/transaction/account_transactions_test.rs#L1086)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the test I mentioned already tests deprecated txs IIUC. so I think it would be better to add the V3 test case there, WYT?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1086 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-NjLKdeZEqt_Ff4bRlGT:-NjNNhBv9KPbhugH099C:byumf2c) ([raw file](https://github.com/starkware-libs/blockifier/blob/2bcd15b83786611b44279de4c0758cbd5e68db41/crates/blockifier/src/transaction/account_transactions_test.rs#L1086)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

the test I mentioned already tests deprecated txs IIUC. so I think it would be better to add the V3 test case there, WYT?
</blockquote></details>

Done. Good idea!
Had to edit `assert_failure_if_max_fee_exceeds_balance` (and rename) to get this to work; hope it's ok to review

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-NjDWQxm1UkLjuNPF_4D:-NjbA79cDbz1jDXRii5y:btd6mim) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ac25858a991c8568dd30192771d444abb286421/crates/blockifier/src/transaction/objects.rs#L74)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hooray!!
</blockquote></details>

:+1: :100: 
___
*[`crates/blockifier/src/transaction/transactions.rs` line 232 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-Njb4Vdr0EFFEcM82UqQ:-Njb4Vdr0EFFEcM82UqR:b-sprkd) ([raw file](https://github.com/starkware-libs/blockifier/blob/73ec4dae85d3679cd29d5c09b5d6d71c962661aa/crates/blockifier/src/transaction/transactions.rs#L232)):*
> ```XML
>                         Ok(None)
>                     }
>                     Err(error) => Err(TransactionExecutionError::from(error)),
> ```

why not just use `?` ?
sorry, didn't think about it before



_Code quote:_
```XML
Err(error) => Err(TransactionExecutionError::from(error)),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 232 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1101#-Njb4Vdr0EFFEcM82UqQ:-NjbCi7O01F1SJOMaVMF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/73ec4dae85d3679cd29d5c09b5d6d71c962661aa/crates/blockifier/src/transaction/transactions.rs#L232)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why not just use `?` ?
sorry, didn't think about it before
</blockquote></details>

Done.

**Review by amosStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
