### PR TITLE
Bundle eth/strk gas prices in `GasPrices`

### PR DESCRIPTION
**Pull request by giladchase**
Implemented exactly like with `FeeTokenAddresses`. If this pattern is used once more, replace all three with a generic implementation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/894)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/894)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @giladchase)

___
*[`crates/blockifier/src/block_context.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/894#-Nddh3VG1VM-pnOlypU1:-Nddh3VG1VM-pnOlypU2:b-itjqir) ([raw file](https://github.com/starkware-libs/blockifier/blob/aba72d0eb6137347b591901d1d2bab996493a24d/crates/blockifier/src/block_context.rs#L60)):*
> ```XML
> impl GasPrices {
>     pub fn get_for_version(&self, has_version: &dyn HasTransactionVersion) -> u128 {
>         if has_version.version() >= TransactionVersion(StarkFelt::from(3_u128)) {
> ```

duplicated...
please define and use `fn is_strk_version(has_version) -> bool` (I leave the name to you :P)



_Code quote:_
```XML
if has_version.version() >= TransactionVersion(StarkFelt::from(3_u128)) {
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/894#-:-NdedhcT2K9bDwa-dFID:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/894)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/894)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/894)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/block_context.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/894#-NdegBSoAI1YT4rD9hsr:-NdehDvU-eGEugm_yx_i:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e77deb5412fefd26b2a2c8482ed3ef7b4a45c5ec/crates/blockifier/src/block_context.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would just delete the function
I devved it without seeing your PR
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/894)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
