### PR TITLE
Refactor in prep for post-validation usage

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj6xPwj3uDCvdlMs2L1:-Nj6xPwj3uDCvdlMs2L2:b3e99vt) ([raw file](https://github.com/starkware-libs/blockifier/blob/e22848227465eb462f7eae1d21e103f3de719ee2/crates/blockifier/src/fee/actual_cost.rs#L174)):*
> ```XML
> /// revert flow) and an error if the check failed.
> struct FeeCheckReport {
>     post_execution_recommended_fee: Fee,
> ```

Why post execution? It can also be the recommended fee for the post validations, no?



_Code quote:_
```XML
    post_execution_recommended_fee: Fee,
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj6x2Ga1fl6cCUYuPpJ:-Nj6x2Ga1fl6cCUYuPpK:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/e22848227465eb462f7eae1d21e103f3de719ee2/crates/blockifier/src/fee/actual_cost.rs#L194)):*
> ```XML
> 
> impl FeeCheckReport {
>     pub fn passing_report(actual_fee: Fee) -> Self {
> ```

?



_Suggestion:_
```XML
    pub fn success_report(actual_fee: Fee) -> Self {
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj6xnmC7yiLuu2WVK1C:-Nj6xnmC7yiLuu2WVK1D:b-2mk3gq) ([raw file](https://github.com/starkware-libs/blockifier/blob/e22848227465eb462f7eae1d21e103f3de719ee2/crates/blockifier/src/fee/actual_cost.rs#L201)):*
> ```XML
> /// If the actual cost exceeds the resource bounds on the transaction, returns a report with an
> /// error and a post-execution fee recommendation.
> fn check_actual_cost_within_bounds(
> ```

Why not making it a method of `FeeCheckReport`?
Same question for `check_can_pay_fee`.



_Code quote:_
```XML
fn check_actual_cost_within_bounds(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj6xPwj3uDCvdlMs2L1:-Nj7abGeB1ODToPLMuGm:bws2ist) ([raw file](https://github.com/starkware-libs/blockifier/blob/e22848227465eb462f7eae1d21e103f3de719ee2/crates/blockifier/src/fee/actual_cost.rs#L174)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why post execution? It can also be the recommended fee for the post validations, no?
</blockquote></details>

Don't think so: we do not have a revert flow after post-validation (before `__execute__`)
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj6x2Ga1fl6cCUYuPpJ:-Nj7apXh1Zunm0bJMkqL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e22848227465eb462f7eae1d21e103f3de719ee2/crates/blockifier/src/fee/actual_cost.rs#L194)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj6xnmC7yiLuu2WVK1C:-Nj7aqWc9ja0do82bCEZ:b-gxk6vl) ([raw file](https://github.com/starkware-libs/blockifier/blob/e22848227465eb462f7eae1d21e103f3de719ee2/crates/blockifier/src/fee/actual_cost.rs#L201)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not making it a method of `FeeCheckReport`?
Same question for `check_can_pay_fee`.
</blockquote></details>

I want to prevent code outside this module from creating an instance of `FeeCheckReport`.
Only creation of `PostExecutionReport` (wrapper type) is allowed.
You're right though, these can be public methods; code outside this module can't use them because the struct itself is private.

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj6xPwj3uDCvdlMs2L1:-Nj7l1MCBD0STdec_TrM:bb77ugb) ([raw file](https://github.com/starkware-libs/blockifier/blob/e22848227465eb462f7eae1d21e103f3de719ee2/crates/blockifier/src/fee/actual_cost.rs#L174)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Don't think so: we do not have a revert flow after post-validation (before `__execute__`)
</blockquote></details>

Yet.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj6xnmC7yiLuu2WVK1C:-Nj7lBh8-9mrkTdqDWZh:b-viccng) ([raw file](https://github.com/starkware-libs/blockifier/blob/e22848227465eb462f7eae1d21e103f3de719ee2/crates/blockifier/src/fee/actual_cost.rs#L201)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I want to prevent code outside this module from creating an instance of `FeeCheckReport`.
Only creation of `PostExecutionReport` (wrapper type) is allowed.
You're right though, these can be public methods; code outside this module can't use them because the struct itself is private.
</blockquote></details>

Document it?
Why not making it a private method of `FeeCheckReport`?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj6xPwj3uDCvdlMs2L1:-Nj8LXOy29X8SbxKc486:b7nhlti) ([raw file](https://github.com/starkware-libs/blockifier/blob/e22848227465eb462f7eae1d21e103f3de719ee2/crates/blockifier/src/fee/actual_cost.rs#L174)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IMO (if and) when we have it... we can rename this field
</blockquote></details>

We will have it now in the post validate, no?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj6xPwj3uDCvdlMs2L1:-Nj8Novh4l_7ZQpngD2Y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e22848227465eb462f7eae1d21e103f3de719ee2/crates/blockifier/src/fee/actual_cost.rs#L174)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We will have it now in the post validate, no?
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 199 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj8VdsI3qTjjgCJO12E:-Nj8VdsJCQX0AmFCBmSo:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9ed8950985d383e9780760cb99f07eae0ee1ea0/crates/blockifier/src/fee/actual_cost.rs#L199)):*
> ```XML
> 
>     /// If the actual cost exceeds the resource bounds on the transaction, returns a report with an
>     /// error and a post-execution fee recommendation.
> ```





_Suggestion:_
```XML
    /// If the actual cost exceeds the resource bounds on the transaction, returns a report with an
    /// error and a fee recommendation.
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 262 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj8WDUw-_QFHBgng_Ge:-Nj8WDUw-_QFHBgng_Gf:b7p1p51) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9ed8950985d383e9780760cb99f07eae0ee1ea0/crates/blockifier/src/fee/actual_cost.rs#L262)):*
> ```XML
>         }
>         Ok(Self {
>             recommended_fee: *actual_fee,
> ```

Technically, there is no justification here to set `recommended_fee = actual_fee`.



_Code quote:_
```XML
 recommended_fee: *actual_fee,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 199 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj8VdsI3qTjjgCJO12E:-NjBmaJt90B-Aiyd9O2y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9ed8950985d383e9780760cb99f07eae0ee1ea0/crates/blockifier/src/fee/actual_cost.rs#L199)):*
> ```XML
> 
>     /// If the actual cost exceeds the resource bounds on the transaction, returns a report with an
>     /// error and a post-execution fee recommendation.
> ```

Done.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 262 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj8WDUw-_QFHBgng_Ge:-NjBm5-98y_9ahGlVUbT:b-a8ldrz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9ed8950985d383e9780760cb99f07eae0ee1ea0/crates/blockifier/src/fee/actual_cost.rs#L262)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Technically, there is no justification here to set `recommended_fee = actual_fee`.
</blockquote></details>

there is, if (a) the previous check was run first and passed, and (b) balance was checked (in pre-validation).
This is the required recommended fee in the post-execution flow.
What would you suggest? Rename the field?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 262 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj8WDUw-_QFHBgng_Ge:-NjC0m2g18w0mwiEhWAF:bgcqt7b) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9ed8950985d383e9780760cb99f07eae0ee1ea0/crates/blockifier/src/fee/actual_cost.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there is, if (a) the previous check was run first and passed, and (b) balance was checked (in pre-validation).
This is the required recommended fee in the post-execution flow.
What would you suggest? Rename the field?
</blockquote></details>

I am not sure. Can you return an error and the `PostExecutionReport` struct will create the report?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 262 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-Nj8WDUw-_QFHBgng_Ge:-NjC5D8e7R5LJO7tIq7Y:b48ju2d) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9ed8950985d383e9780760cb99f07eae0ee1ea0/crates/blockifier/src/fee/actual_cost.rs#L262)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I am not sure. Can you return an error and the `PostExecutionReport` struct will create the report?
</blockquote></details>

Done. See if you like

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 204 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-NjCfuBs4ZAr_jMDatp9:-NjCfuBtDsuJR08G6_80:bdicdeo) ([raw file](https://github.com/starkware-libs/blockifier/blob/048d518c62736482cc7c3d47d7a79bad7f756cf5/crates/blockifier/src/fee/actual_cost.rs#L204)):*
> ```XML
>     pub fn from_fee_check_results(
>         actual_fee: Fee,
>         results: Vec<FeeCheckResult>,
> ```

Why a vector? 



_Code quote:_
```XML
        results: Vec<FeeCheckResult>,
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 235 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-NjCgISh0ancMI3umFAc:-NjCgISh0ancMI3umFAd:bmed8ba) ([raw file](https://github.com/starkware-libs/blockifier/blob/048d518c62736482cc7c3d47d7a79bad7f756cf5/crates/blockifier/src/fee/actual_cost.rs#L235)):*
> ```XML
>         account_tx_context: &AccountTransactionContext,
>         actual_cost: &ActualCost,
>     ) -> TransactionExecutionResult<FeeCheckResult> {
> ```

And then return the error directly.



_Suggestion:_
```XML
  ) -> TransactionExecutionResult<()> {
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1121)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 204 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-NjCfuBs4ZAr_jMDatp9:-NjCs7QfBEjfPeIK8vA0:b-ul1ydo) ([raw file](https://github.com/starkware-libs/blockifier/blob/048d518c62736482cc7c3d47d7a79bad7f756cf5/crates/blockifier/src/fee/actual_cost.rs#L204)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why a vector?
</blockquote></details>

No longer a vector; I do iterate though to prevent code dup
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 235 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1121#-NjCgISh0ancMI3umFAc:-NjCs6ku1PhxO_R1_l2g:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/048d518c62736482cc7c3d47d7a79bad7f756cf5/crates/blockifier/src/fee/actual_cost.rs#L235)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And then return the error directly.
</blockquote></details>

Done.

**Pull request closed without merging**
