### PR TITLE
Implement secp256k1_get_xy.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5ulvt2lEq_rduAzW2:-NZ5ulvt2lEq_rduAzW3:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/hint_processor.rs#L26)):*
> ```XML
> use thiserror::Error;
> 
> use super::secp::secp256k1_get_xy;
> ```





_Suggestion:_
```XML
crate::execution::syscalls
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5v02h1uXYejYDdEfu:-NZ5v02h1uXYejYDdEfv:b-4tlhvg) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L48)):*
> ```XML
> 
> /// Given a felt `ec_point_id` returns the corresponding secp256k1 point.
> pub fn secp256k1_get_point<'a>(
> ```

Why is this function needed? The other one is quite short.



_Code quote:_
```XML
secp256k1_get_point
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5vOeq24_6je0YIeMM:-NZ5vOer0J2U8d8340n2:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L52)):*
> ```XML
>     ec_point_id: Felt252,
> ) -> SyscallResult<&'a ark_secp256k1::Affine> {
>     ec_point_id.to_usize().and_then(|idx| syscall_handler.secp256k1_points.get(idx)).ok_or_else(
> ```





_Suggestion:_
```XML
id
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5vSd40rNanKX26NBp:-NZ5vSd40rNanKX26NBq:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L55)):*
> ```XML
>         || SyscallExecutionError::InvalidSyscallInput {
>             input: felt_to_stark_felt(&ec_point_id),
>             info: "Invalid secp256k1 point Id".to_string(),
> ```





_Suggestion:_
```XML
Invalid Secp256K1 point ID
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5vSd40rNanKX26NBp:-NZ5w3vF2MQgKI5OpIo7:bhgqx2j) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L55)):*
> ```XML
>         || SyscallExecutionError::InvalidSyscallInput {
>             input: felt_to_stark_felt(&ec_point_id),
>             info: "Invalid secp256k1 point Id".to_string(),
> ```

`Secp256k1` *

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5v02h1uXYejYDdEfu:-NZ5wYau9gGn6MOlz8cn:bsg2joi) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L48)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this function needed? The other one is quite short.
</blockquote></details>

It is going to be used by Secp256k1Add and Secp256k1Mul

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5vSd40rNanKX26NBp:-NZ5wvju1pRotTEevBU2:b-l2ad3v) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L55)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`Secp256k1` *
</blockquote></details>

I think the k should be small.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5ulvt2lEq_rduAzW2:-NZ5xRGH2VnzqXaCEwuK:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/hint_processor.rs#L26)):*
> ```XML
> use thiserror::Error;
> 
> use super::secp::secp256k1_get_xy;
> ```

done.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5vOeq24_6je0YIeMM:-NZ5wv8d0d4XqByMwocU:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L52)):*
> ```XML
>     ec_point_id: Felt252,
> ) -> SyscallResult<&'a ark_secp256k1::Affine> {
>     ec_point_id.to_usize().and_then(|idx| syscall_handler.secp256k1_points.get(idx)).ok_or_else(
> ```

done

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5v02h1uXYejYDdEfu:-NZ5xDDn8CXMuo2xQRND:b-ek8d4q) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It is going to be used by Secp256k1Add and Secp256k1Mul
</blockquote></details>

Got it. And should it be `pub`lic?
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5xLi8DpB9Jpq5UWUd:-NZ5xLi8DpB9Jpq5UWUe:buqvl7a) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L48)):*
> ```XML
> 
> /// Given a felt `ec_point_id` returns the corresponding secp256k1 point.
> pub fn secp256k1_get_point<'a>(
> ```

Consider making this a method of `SyscallHintProcessor`.



_Suggestion:_
```XML
pub fn get_secp256k1_point_by_id<'a>(
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5vSd40rNanKX26NBp:-NZ5xVR314jeCqjFlITP:b-o419a3) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L55)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think the k should be small.
</blockquote></details>

Right, fixed.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5v02h1uXYejYDdEfu:-NZ61iFYBU3SwyH1W60b:b-vfmjd0) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L48)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Got it. And should it be `pub`lic?
</blockquote></details>

no, but if I make it a method then it does need to be public.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5xLi8DpB9Jpq5UWUd:-NZ61n9OAmYNTlqG6leS:bixuct) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L48)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider making this a method of `SyscallHintProcessor`.
</blockquote></details>

I've considered it and thought that it is less modular this way.
but I guess the secp256k1_points vector is stored in the handler anyways.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 419 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ63BMi6lOAOqz4fZnr:-NZ63BMi6lOAOqz4fZns:bw70oh9) ([raw file](https://github.com/starkware-libs/blockifier/blob/467a7567cde5d67dc048a4b38a51ea061e2a61e3/crates/blockifier/src/execution/syscalls/hint_processor.rs#L419)):*
> ```XML
>     }
> 
>     /// Given a felt `ec_point_id` returns the corresponding secp256k1 point.
> ```

I think you can delete this docstring.



_Code quote:_
```XML
/// Given a felt `ec_point_id` returns the corresponding secp256k1 point.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 419 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ63BMi6lOAOqz4fZnr:-NZ64AhUEyMwGHPDBGia:b32wtd) ([raw file](https://github.com/starkware-libs/blockifier/blob/467a7567cde5d67dc048a4b38a51ea061e2a61e3/crates/blockifier/src/execution/syscalls/hint_processor.rs#L419)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think you can delete this docstring.
</blockquote></details>

ok

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/693#-:-NZ64iWM6O3gqizrNKSv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/693#-NZ5xLi8DpB9Jpq5UWUd:-NZ64Z_k78N3rOV7nJO7:bargtnp) ([raw file](https://github.com/starkware-libs/blockifier/blob/d532875793e4f3c456cb4c5454368997287e174f/crates/blockifier/src/execution/syscalls/secp.rs#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I've considered it and thought that it is less modular this way.
but I guess the secp256k1_points vector is stored in the handler anyways.
</blockquote></details>

Yup, exactly.

**Pull request merged**
