### PR TITLE
Use constants for transaction versions.

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/904)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/904)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @dan-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/904#-NdxQxaj5Aos0RSDeWCt:-NdxQxaj5Aos0RSDeWCu:b-bjdmln) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fa81844e261558a1dfd0b846c7c2b9f2accab3d/crates/blockifier/src/transaction/account_transaction.rs#L165)):*
> ```XML
>                 vec![TransactionVersion::ZERO, TransactionVersion::ONE, TransactionVersion::TWO]
>             }
>             Self::Invoke(_) => {
> ```

Zero too in Invoke?

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/904)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/904)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/904#-NdxQxaj5Aos0RSDeWCt:-Ne8PIB79r4-e1kLOeir:b-5tt86v) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fa81844e261558a1dfd0b846c7c2b9f2accab3d/crates/blockifier/src/transaction/account_transaction.rs#L165)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Zero too in Invoke?
</blockquote></details>

From starknet_api:
```
/// An invoke V0 transaction.
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct InvokeTransactionV0 {
pub max_fee: Fee,
pub signature: TransactionSignature,
pub contract_address: ContractAddress,
pub entry_point_selector: EntryPointSelector,
pub calldata: Calldata,
}

/// An invoke V1 transaction.
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct InvokeTransactionV1 {
pub max_fee: Fee,
pub signature: TransactionSignature,
pub nonce: Nonce,
pub sender_address: ContractAddress,
pub calldata: Calldata,
}
```
I'm not sure if it should be here or not, but it was here before, so I just replaced the `TransactionVersion(StarkFelt::from(0_u8))` with `TransactionVersion::ZERO`

Do you want the `verify_tx_version` to fail on Invoke version 0?

**Review by elintul — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/904)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/904#-NdxQxaj5Aos0RSDeWCt:-Ne8S06Z-VwNKC-JDRaB:byc6qip) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fa81844e261558a1dfd0b846c7c2b9f2accab3d/crates/blockifier/src/transaction/account_transaction.rs#L165)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

From starknet_api:
```
/// An invoke V0 transaction.
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct InvokeTransactionV0 {
pub max_fee: Fee,
pub signature: TransactionSignature,
pub contract_address: ContractAddress,
pub entry_point_selector: EntryPointSelector,
pub calldata: Calldata,
}

/// An invoke V1 transaction.
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct InvokeTransactionV1 {
pub max_fee: Fee,
pub signature: TransactionSignature,
pub nonce: Nonce,
pub sender_address: ContractAddress,
pub calldata: Calldata,
}
```
I'm not sure if it should be here or not, but it was here before, so I just replaced the `TransactionVersion(StarkFelt::from(0_u8))` with `TransactionVersion::ZERO`

Do you want the `verify_tx_version` to fail on Invoke version 0?
</blockquote></details>

No no, we _should_ support it, I may have thought you deleted V0.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/904#-:-Ne8SL657s9gGzpqTbcB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/904)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by barak-b-starkware** [comment]
Merged in the following PRs: [1](https://github.com/starkware-libs/blockifier/pull/918), [2](https://github.com/starkware-libs/blockifier/pull/919), [3](https://github.com/starkware-libs/blockifier/pull/920).

**Pull request closed without merging**
