### PR TITLE
Performance_fix: Move serialize to Rust

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1305)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1305)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_utils.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1305#-Nn9WyG8BV5T9KsHQ2O3:-Nn9WyG8BV5T9KsHQ2O4:bj670pn) ([raw file](https://github.com/starkware-libs/blockifier/blob/42675641b2900c5a01e95918c05a94fc713f9844/crates/native_blockifier/src/py_utils.rs#L15)):*
> ```XML
> 
> #[derive(Clone, Copy, Default, Eq, FromPyObject, Hash, PartialEq, Debug, Serialize)]
> pub struct PyFelt(#[pyo3(from_py_with = "int_to_stark_felt")] pub StarkFelt);
> ```

Does this mean that it already knows to map it into an `int` on serialize?



_Code quote:_
```XML
#[derive(Clone, Copy, Default, Eq, FromPyObject, Hash, PartialEq, Debug, Serialize)]
pub struct PyFelt(#[pyo3(from_py_with = "int_to_stark_felt")] pub StarkFelt);
```

**Review by giladchase — COMMENTED** [review]
Good.
While this is being tested, if you want @elintul,  we can check if this can be done solely with derive `serde::Serialize` in those structs + some serde customizations for specific serialization logic, i believe it can. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1305#-:-Nn9XQB34EXlKEZthdKR:b2vyxnn)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @elintul and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
Also, you can consult with DanB team, they do stuff like this efficiently.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1305#-:-Nn9tG8i-2S1qCSpuhaG:b-3ex8pf)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @elintul)

**Review by giladchase — COMMENTED** [review]
Is this PR still relevant given your other PR that uses Serialize?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1305#-:-Nnc7uZT2qqpWlFURCku:b-wbk7k4)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @elintul)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1305)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1305#-Nnhug7V6OFyxNw2LmxF:-Nnhug7V6OFyxNw2LmxG:b-u1hl9k) (no related file):*
I will close this PR., as we've decide to change the Python class instead.

Python PR: https://github.com/starkware-industries/starkware/pull/33327
Rust PR: https://github.com/starkware-libs/blockifier/pull/1315

___

**Pull request closed without merging**
