### PR TITLE
Merge main contract segmentation into main

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1331)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 5 of 9 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1331)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1331)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1331#-No2Bk5D-dicb-nU38YO:-No2Bk5D-dicb-nU38YP:bxjj1y5) (no related file):*
Merge instead of squash

___

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 5 of 9 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1331#-:-No62IXiE0LawMbZBdQs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1331)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1331#-No2Bk5D-dicb-nU38YO:-No6PaOrCG4SDX5rU3WB:b6fykfa) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Merge instead of squash
</blockquote></details>

Please open a Python PR with the commit hash of your branch and wait for its CI to pass before this is merged.

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1331)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1331)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1331#-No2Bk5D-dicb-nU38YO:-No6gX8m3z0Z_x9sL4lr:bkmllif) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please open a Python PR with the commit hash of your branch and wait for its CI to pass before this is merged.
</blockquote></details>

It'll be https://reviewable.io/reviews/starkware-industries/starkware/33401#- once it passes Hodor.

___

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1331)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1331#-No2Bk5D-dicb-nU38YO:-No6ri2M9NHA5VW7bp1L:bdqzvlc) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

It'll be https://reviewable.io/reviews/starkware-industries/starkware/33401#- once it passes Hodor.
</blockquote></details>

Actually, https://reviewable.io/reviews/starkware-industries/starkware/33398#-. The other one is not ready yet.

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1331)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Pull request merged**
