### PR TITLE
refactor(concurrency): change block_state of TransactionExecutor to A…

### PR DESCRIPTION
**Pull request by barak-b-starkware**
…rc<Mutex<_>>

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1927)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1927)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1927#-Nz78Ub364niB_fRhs4-:-Nz78Ub40A2poYGcUP-v:b-lcn1qn) ([raw file](https://github.com/starkware-libs/blockifier/blob/29e7e42097a7348767cf56de4fe987520afa8c63/crates/blockifier/src/blockifier/transaction_executor.rs#L67)):*
> ```XML
>             bouncer: Bouncer::new(bouncer_config),
>             config,
>             block_state: Arc::new(Mutex::new(block_state)),
> ```

 Are you sure this is needed?
Isn't it enough if the state is on the VersionedState and the VersionedState is behind a Mutex?



_Code quote:_
```XML
block_state: Arc::new(Mutex::new(block_state)),
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1927)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1927#-Nz78Ub364niB_fRhs4-:-Nz7huRU36SrUBDagICz:bjfobww) ([raw file](https://github.com/starkware-libs/blockifier/blob/29e7e42097a7348767cf56de4fe987520afa8c63/crates/blockifier/src/blockifier/transaction_executor.rs#L67)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Are you sure this is needed?
Isn't it enough if the state is on the VersionedState and the VersionedState is behind a Mutex?
</blockquote></details>

The issue is the ref cells in the cached state, i.e., the (IIUC, only) alternative is to refactor the 'CachedState' and @noaov1, and I thought it's better for now to add the `Arc<Mutex<_>>` on the block state

**Review by OriStarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1927)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, @MohammadNassar1, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1927#-Nz8H1wOC0AeIxhE5jXz:-Nz8H1wPDluCn70ND7rI:bx5m0xd) (no related file):*
Can you explain what is the motivation behind this change?

___

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1927#-Nz78Ub364niB_fRhs4-:-Nz8Jrrf7inuhitUMruP:b-xoolg5) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a24ca988c0f1c397166abb8509ef288e0af40fc/crates/blockifier/src/blockifier/transaction_executor.rs#L67)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

The issue is the ref cells in the cached state, i.e., the (IIUC, only) alternative is to refactor the 'CachedState' and @noaov1, and I thought it's better for now to add the `Arc<Mutex<_>>` on the block state
</blockquote></details>

Aptos have a refcell in their state struct. I haven't figured out how they do it. Try to take a look:
https://github.com/igor-aptos/aptos-core/blob/6a2fee68cce24e6bf0b8e64bf23dfb545df35bfb/aptos-move/block-executor/src/view.rs#L152-L158

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1927)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1927#-NzJEdQNCNfDjJrlBXvK:-NzJEdQNCNfDjJrlBXvL:b-ktv412) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc1f62b1523ffa8470e24703b81f04795fa750ad/crates/blockifier/src/blockifier/stateful_validator.rs#L113)):*
> ```XML
>         let charge_fee = true;
>         tx.perform_pre_validation_stage(
>             &mut *self.tx_executor.block_state.lock().expect("Failed to acquire state lock."),
> ```

Consider adding a getter to the `TransactionExecutor`.



_Code quote:_
```XML
&mut *self.tx_executor.block_state.lock().expect("Failed to acquire state lock."),
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1927#-NzJEjbe6GG9FKQ2hNKt:-NzJEjbe6GG9FKQ2hNKu:b-5w0po6) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc1f62b1523ffa8470e24703b81f04795fa750ad/crates/blockifier/src/blockifier/transaction_executor.rs#L49)):*
> ```XML
>     // State-related fields.
>     // The transaction executor operates at the block level. It moves the block's state across
>     // threads, so it needs to be wrapped with Arc<Mutex<_>>.
> ```

The block state is shared between chunks (and actually also between streams of transactions), hence the `Arc`.
Please add a documentation noting that it is not needed for the sequential run, but we share code.. 



_Code quote:_
```XML
    // The transaction executor operates at the block level. It moves the block's state across
    // threads, so it needs to be wrapped with Arc<Mutex<_>>.
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1927#-Nz78Ub364niB_fRhs4-:-NzJHC3bEIRf2oJOg2KQ:bqmcrkm) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc1f62b1523ffa8470e24703b81f04795fa750ad/crates/blockifier/src/blockifier/transaction_executor.rs#L67)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Aptos have a refcell in their state struct. I haven't figured out how they do it. Try to take a look:
https://github.com/igor-aptos/aptos-core/blob/6a2fee68cce24e6bf0b8e64bf23dfb545df35bfb/aptos-move/block-executor/src/view.rs#L152-L158
</blockquote></details>

The problem with the Refcell is that we wrap the `CahedState` (and the Refcell) with an Arc (having a reference will have the same effect).

**Review by OriStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1927)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, @MohammadNassar1, and @Yoni-Starkware)

**Pull request closed without merging**
