### PR TITLE
Custom Derive for InvokeTxArgs

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/946)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/946)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/test_utils.rs` line 402 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/946#-NfkCIrz3FWgPZYiRE0i:-NfkCIrz3FWgPZYiRE0j:bvmjsl5) ([raw file](https://github.com/starkware-libs/blockifier/blob/2084e97b4629641e7ddbc204b28eaa569fd29421/crates/blockifier/src/test_utils.rs#L402)):*
> ```XML
>             entry_point_selector: Some(selector_from_name(EXECUTE_ENTRY_POINT_NAME)),
>             signature: None,
>             tx_version: TransactionVersion::ZERO,
> ```

I think it should be one, and change to V3 once supported.



_Code quote:_
```XML
tx_version: TransactionVersion::ZERO
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/946)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/test_utils.rs` line 402 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/946#-NfkCIrz3FWgPZYiRE0i:-NfkI4-XA3Ts_Uvj2HKi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2084e97b4629641e7ddbc204b28eaa569fd29421/crates/blockifier/src/test_utils.rs#L402)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it should be one, and change to V3 once supported.
</blockquote></details>

Done.

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/946#-:-NfkNS460QCwSRbtEXzc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/test_utils.rs` line 394 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/946#-NfkNMpF3OlgtaqFpf9_:-NfkNMpF3OlgtaqFpf9a:b-r8vsay) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c5c5fa79adeba34ef2b1272b6f46cfa5c7130e6/crates/blockifier/src/test_utils.rs#L394)):*
> ```XML
> impl Default for InvokeTxArgs {
>     fn default() -> Self {
>         InvokeTxArgs {
> ```

Consider ordering the fields as they are in the struct definition.



_Code quote:_
```XML
InvokeTxArgs
```

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/946)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase, @noaov1, and @zuphitf)

**Pull request merged**
