### PR TITLE
Change AccountTransactionContext struct to enum.

### PR DESCRIPTION
**Pull request by NirLevi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @NirLevi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXkfC-zDJghc8lNTz:-NfRXkfC-zDJghc8lNU-:b-t3lc78) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/account_transaction.rs#L126)):*
> ```XML
>     fn get_account_transaction_context(
>         &self,
>     ) -> TransactionExecutionResult<AccountTransactionContext> {
> ```

Not sure why this is needed, but if it is: better to have an `unreachable!()` branch for now, instead of converting to `Result` and back.



_Code quote:_
```XML
TransactionExecutionResult
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXa0k15x6I3Ar0KGa:-NfRXa0k15x6I3Ar0KGb:bn23drc) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/account_transaction.rs#L129)):*
> ```XML
>         let allowed_versions =
>             vec![TransactionVersion::ZERO, TransactionVersion::ONE, TransactionVersion::TWO];
>         match self.version() {
> ```

Why do you suddenly need to `match` on the version?



_Code quote:_
```XML
match self.version()
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXO-G-ltSZKvyy-ZO:-NfRXO-G-ltSZKvyy-ZP:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/objects.rs#L18)):*
> ```XML
>         $(pub fn $field(&self) -> $field_type {
>             match self{
>                 Self::Deprecated(deprecated_account_tx_context) => deprecated_account_tx_context.$field.clone(),
> ```





_Suggestion:_
```XML
context
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXGr3CxwaxbLi2HRp:-NfRXGr3CxwaxbLi2HRq:b3147he) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/objects.rs#L66)):*
> ```XML
>     pub signature: TransactionSignature,
>     pub nonce: Nonce,
>     pub sender_address: ContractAddress,
> ```

Can those fields become non-`pub`lic?



_Code quote:_
```XML
    pub transaction_hash: TransactionHash,
    pub max_fee: Fee,
    pub version: TransactionVersion,
    pub signature: TransactionSignature,
    pub nonce: Nonce,
    pub sender_address: ContractAddress,
```

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXkfC-zDJghc8lNTz:-NfdtRezANzBuE0yJBVh:b-j1itvx) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/account_transaction.rs#L126)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure why this is needed, but if it is: better to have an `unreachable!()` branch for now, instead of converting to `Result` and back.
</blockquote></details>

I added this because I created an ENUM that does not support V3 but only DEPRECATED in this PR. I'll change it to unreachable!().
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXa0k15x6I3Ar0KGa:-NfduKHa--JZlMtCGOBI:b4zu249) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/account_transaction.rs#L129)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why do you suddenly need to `match` on the version?
</blockquote></details>

To separate the DEPRECATED from the CURRENT.
___
*[`crates/blockifier/src/transaction/objects.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXGr3CxwaxbLi2HRp:-Nfdw1oNBCnNrIWYYRas:b-i97zci) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/objects.rs#L66)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can those fields become non-`pub`lic?
</blockquote></details>

Yes, they can be private. I thought of doing it in the following PR because it requires creating a constructor, and this PR seemed big enough to me.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @NirLevi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXkfC-zDJghc8lNTz:-NferJftEiQKS5Yijt5-:b-hg4k6p) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/account_transaction.rs#L126)):*
<details><summary><i>Previously, NirLevi-starkware (Nir Levi) wrote…</i></summary><blockquote>

I added this because I created an ENUM that does not support V3 but only DEPRECATED in this PR. I'll change it to unreachable!().
</blockquote></details>

Please rebase your PR, I changed this function.
___
*[`crates/blockifier/src/transaction/objects.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXGr3CxwaxbLi2HRp:-Nfeuhd16AL2Ah6e1V3e:b-sgoyp3) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/objects.rs#L66)):*
<details><summary><i>Previously, NirLevi-starkware (Nir Levi) wrote…</i></summary><blockquote>

Yes, they can be private. I thought of doing it in the following PR because it requires creating a constructor, and this PR seemed big enough to me.
</blockquote></details>

Next PR then. If you're planning something, let your reviewer know in a comment.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: all files reviewed, 7 unresolved discussions (waiting on @NirLevi-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfewTJbAxhBrCFpL-Kk:-NfewTJbAxhBrCFpL-Kl:biivjjt) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/test_utils.rs#L327)):*
> ```XML
> impl CallEntryPoint {
>     // Executes the call directly, without account context.
>     pub fn execute_directly(self, state: &mut dyn State) -> EntryPointExecutionResult<CallInfo> {
> ```

We should think about this: please add a TODO to adjust to V3: either accepting a context as an argument, or at least the testing mode (V3, or <V3).



_Code quote:_
```XML
execute_directly
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfevsRo0gDPxWz9LCSp:-NfevsRo0gDPxWz9LCSq:bax3yki) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/transaction_execution.rs#L100)):*
> ```XML
>         let tx = &self.tx;
>         let tx_context =
>             AccountTransactionContext::Deprecated(DeprecatedAccountTransactionContext {
> ```

This has moved as well.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-Nfew23b20eTRuo2zSR2:-Nfew23b20eTRuo2zSR3:b-kji5vg) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/native_blockifier/src/py_transaction.rs#L148)):*
> ```XML
>         Fee::default()
>     };
> ```

This effectively makes Blockifier reject V3 transactions. Let's return `Deprecated` for now.

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: 4 of 11 files reviewed, 6 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfewTJbAxhBrCFpL-Kk:-NffoLpgEuCIfX-mAZ1n:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/test_utils.rs#L327)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We should think about this: please add a TODO to adjust to V3: either accepting a context as an argument, or at least the testing mode (V3, or <V3).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXkfC-zDJghc8lNTz:-NffoOAkEvVNn0X380dQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/account_transaction.rs#L126)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please rebase your PR, I changed this function.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXO-G-ltSZKvyy-ZO:-NffobksBh2Be5iZ9iiJ:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/objects.rs#L18)):*
> ```XML
>         $(pub fn $field(&self) -> $field_type {
>             match self{
>                 Self::Deprecated(deprecated_account_tx_context) => deprecated_account_tx_context.$field.clone(),
> ```

Done
___
*[`crates/native_blockifier/src/py_transaction.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-Nfew23b20eTRuo2zSR2:-Nffpw034CBKRaL6lZub:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/native_blockifier/src/py_transaction.rs#L148)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This effectively makes Blockifier reject V3 transactions. Let's return `Deprecated` for now.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfevsRo0gDPxWz9LCSp:-NffqW8L1KnMOo_uajD_:b-v7raxe) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/transaction_execution.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This has moved as well.
</blockquote></details>

Didn't understand this comment.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul, @NirLevi-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXO-G-ltSZKvyy-ZO:-NfgzGAz7vjZ922CD3KF:bvgqihv) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/objects.rs#L18)):*
<details><summary><i>Previously, NirLevi-starkware (Nir Levi) wrote…</i></summary><blockquote>

Done
</blockquote></details>

do all fields need cloning...? is it worth it, implementing a separate macro for `Copy`-able fields?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfgzZVR4XqP6XNLz1ub:-NfgzZVR4XqP6XNLz1uc:b-9796sl) ([raw file](https://github.com/starkware-libs/blockifier/blob/79636d9e4c21f499c130b35030e97f1051f00da4/crates/blockifier/src/transaction/transactions.rs#L174)):*
> ```XML
>     }
> 
>     pub fn get_account_tx_context(&self) -> AccountTransactionContext {
> ```

IIUC, the deprecated account tx context is for versions < 3, right?
why is the Deprecated variant hard-coded here?
Consider `match`ing `self.tx_version` and panicking if the version is >= 3 (with a TODO)
(non-blocking, I'm no in full context)

x3 (for all three getters)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @NirLevi-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 605 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfimmNdEx2GJCpTGS4v:-NfimmNdEx2GJCpTGS4w:b4ghq20) ([raw file](https://github.com/starkware-libs/blockifier/blob/2b889f4805664e22dcef31a9ed49c74f9828c1f5/crates/blockifier/src/transaction/account_transaction.rs#L605)):*
> ```XML
>     }
> 
>     fn is_non_revertible(&self) -> bool {
> ```

Why suddenly a result? 
___
*[`crates/blockifier/src/transaction/transactions.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfgzZVR4XqP6XNLz1ub:-NfimzafAzU-CBqWYFBz:b-2tfgex) ([raw file](https://github.com/starkware-libs/blockifier/blob/79636d9e4c21f499c130b35030e97f1051f00da4/crates/blockifier/src/transaction/transactions.rs#L174)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IIUC, the deprecated account tx context is for versions < 3, right?
why is the Deprecated variant hard-coded here?
Consider `match`ing `self.tx_version` and panicking if the version is >= 3 (with a TODO)
(non-blocking, I'm no in full context)

x3 (for all three getters)
</blockquote></details>

Next PR, or now but I don't want a temporary result only to revert it.
Do you know of a more elegant (shorter) way to instantiate variants of this now enum? 
___
*[`crates/native_blockifier/src/py_transaction.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-Nfew23b20eTRuo2zSR2:-NfinQgCBm1ptozCFt2K:b34irlf) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/native_blockifier/src/py_transaction.rs#L148)):*
<details><summary><i>Previously, NirLevi-starkware (Nir Levi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add a TODO with a label that you can find later. 
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfevsRo0gDPxWz9LCSp:-Nfinez04e2YkDhLd0SP:b8ps9yw) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/transaction_execution.rs#L100)):*
<details><summary><i>Previously, NirLevi-starkware (Nir Levi) wrote…</i></summary><blockquote>

Didn't understand this comment.
</blockquote></details>

Where's the impl. of the L1 handler getter?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @NirLevi-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfgzZVR4XqP6XNLz1ub:-Nfj1Egk0vi9wYR7GNm9:b17omum) ([raw file](https://github.com/starkware-libs/blockifier/blob/79636d9e4c21f499c130b35030e97f1051f00da4/crates/blockifier/src/transaction/transactions.rs#L174)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Next PR, or now but I don't want a temporary result only to revert it.
Do you know of a more elegant (shorter) way to instantiate variants of this now enum?
</blockquote></details>

I don't understand the comment.
Assuming this getter does (or, will) actually return different variants depending on tx version,
matching *is* the rusty way to do it.
(actually tx version isn't an enum, which is a shame, but I would still `match` like this:)
```
match v {
    TransactionVersion::ZERO | TransactionVersion::ONE => AccountTransactionContext::Deprecated(...),
    _ => panic!("Not implemented for tx version {:?}.", v)
}
```
The `panic` is temporary, but so is the current implementation, and the `panic` protects us from accidentally doing something we don't want to do.

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 605 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfimmNdEx2GJCpTGS4v:-NfjLyn65l3_6qJ3jtFM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2b889f4805664e22dcef31a9ed49c74f9828c1f5/crates/blockifier/src/transaction/account_transaction.rs#L605)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why suddenly a result?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfRXO-G-ltSZKvyy-ZO:-NfjBKcrEyD9ZXk-pTKM:bnubnj2) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/blockifier/src/transaction/objects.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do all fields need cloning...? is it worth it, implementing a separate macro for `Copy`-able fields?
</blockquote></details>

No, only the TransactionSignature is not copy-able. 
___
*[`crates/native_blockifier/src/py_transaction.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/947#-Nfew23b20eTRuo2zSR2:-NfjGwBQAAx5o_YCbSDM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/304c1c066b35810a5b38922b5d49b34cf17644e5/crates/native_blockifier/src/py_transaction.rs#L148)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a TODO with a label that you can find later.
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: all files reviewed, 2 unresolved discussions (waiting on @NirLevi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 339 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfjpOPs6iH0NBESIzSl:-NfjpOPs6iH0NBESIzSm:bndnnoi) ([raw file](https://github.com/starkware-libs/blockifier/blob/52449b174be2fb89e06998f1f1c8bad5934405d4/crates/blockifier/src/transaction/transactions.rs#L339)):*
> ```XML
>     pub fn get_account_tx_context(&self) -> AccountTransactionContext {
>         match self.tx.version() {
>             TransactionVersion::ZERO | TransactionVersion::ONE | TransactionVersion::TWO => {
> ```

there is no invoke v2, right? please remove.
Also check declare, deploy account and L1 handlers: which versions are actually relevant?



_Code quote:_
```XML
TransactionVersion::TWO
```

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 339 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfjpOPs6iH0NBESIzSl:-NfjuqjD5orsqa_-0int:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/52449b174be2fb89e06998f1f1c8bad5934405d4/crates/blockifier/src/transaction/transactions.rs#L339)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there is no invoke v2, right? please remove.
Also check declare, deploy account and L1 handlers: which versions are actually relevant?
</blockquote></details>

Done.

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfjVgsF4koVImWJqvk4:-Nfjv8uK5xxBkD40yLpK:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Make sure you can easily identify the locations that need to be changed when a new variant will be added.
</blockquote></details>

Done.

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 339 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfjpOPs6iH0NBESIzSl:-Nfjv55d2SJ-udUpE4-2:b-v02dwf) ([raw file](https://github.com/starkware-libs/blockifier/blob/52449b174be2fb89e06998f1f1c8bad5934405d4/crates/blockifier/src/transaction/transactions.rs#L339)):*
<details><summary><i>Previously, NirLevi-starkware (Nir Levi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sooo... declare has all three versions?
there are no new versions of L1 handler transactions (after zero)?
deploy account is only version 1?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: all files reviewed, 1 unresolved discussion (waiting on @NirLevi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 439 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/947#-Nfk6eAvAVL6rGjmbPow:-Nfk6eAvAVL6rGjmbPox:b8vg80o) ([raw file](https://github.com/starkware-libs/blockifier/blob/e425a7014a4cca8bf1ea876f54b9136f45edf711/crates/blockifier/src/transaction/transactions.rs#L439)):*
> ```XML
> impl L1HandlerTransaction {
>     pub fn get_account_tx_context(&self) -> AccountTransactionContext {
>         match self.tx.version {
> ```

I think this is going to stay this way, so let's leave it hardcoded.

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 339 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/947#-NfjpOPs6iH0NBESIzSl:-NfkAJpT9Fuk5U-lmsC6:b-o2bw0v) ([raw file](https://github.com/starkware-libs/blockifier/blob/52449b174be2fb89e06998f1f1c8bad5934405d4/crates/blockifier/src/transaction/transactions.rs#L339)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

sooo... declare has all three versions?
there are no new versions of L1 handler transactions (after zero)?
deploy account is only version 1?
</blockquote></details>

Yes, that's what i saw.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 439 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/947#-Nfk6eAvAVL6rGjmbPow:-NfkCaBE194WuxqMT36U:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e425a7014a4cca8bf1ea876f54b9136f45edf711/crates/blockifier/src/transaction/transactions.rs#L439)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think this is going to stay this way, so let's leave it hardcoded.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947#-:-NfkD6EI5y4l0Mi5aCJw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947#-:-NfkMLMO523PmzpzQ7gO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
