### PR TITLE
feat(fee): add gas cost for code bytes

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1475)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1475)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ayeletstarkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-NqNVN4LBDib0piJxDOz:-NqNVN4LBDib0piJxDP-:b-mln1wt) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/fee/gas_usage.rs#L115)):*
> ```XML
>             (class_info.bytecode_length() + class_info.sierra_program_length)
>                 * eth_gas_constants::WORD_WIDTH
>                 + class_info.abi_length,
> ```

Why only the first two are code words?



_Code quote:_
```XML
            (class_info.bytecode_length() + class_info.sierra_program_length)
                * eth_gas_constants::WORD_WIDTH
                + class_info.abi_length,
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-NqNWan435PvSy3l1gjY:-NqNWan435PvSy3l1gjZ:bwkj762) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/fee/gas_usage_test.rs#L85)):*
> ```XML
>         0,
>         None,
>         None,
> ```

Add a non-none case?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/fee/gas_usage.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-NqNVN4LBDib0piJxDOz:-NqNXb7OE5qs25ZzZ0k0:bv67kg6) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/fee/gas_usage.rs#L115)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why only the first two are code words?
</blockquote></details>

Because the abi is saved as a string, and we count the number of chars of the string.
the bytecode and the sierra are lists of felts, so the length is in felts.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1475)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ayeletstarkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-NqNVN4LBDib0piJxDOz:-NqNY8_g1zu6Pboyt-TY:b-z7r6k9) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/fee/gas_usage.rs#L115)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Because the abi is saved as a string, and we count the number of chars of the string.
the bytecode and the sierra are lists of felts, so the length is in felts.
</blockquote></details>

Oh, I see. So we assume a `felt == word`? (if so, add a comment?)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/fee/gas_usage.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-NqNVN4LBDib0piJxDOz:-NqNfdTR-REzR-ZjDkoB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/fee/gas_usage.rs#L115)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh, I see. So we assume a `felt == word`? (if so, add a comment?)
</blockquote></details>

Done.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-NqNWan435PvSy3l1gjY:-NqNfAQ-8NysPZYfa2PS:bnkv3ep) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/fee/gas_usage_test.rs#L85)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Add a non-none case?
</blockquote></details>

I added a test.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 3 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-:-NqNgpQeDC-QYrr_7MoG:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @ayeletstarkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-NqNgXs-5qVXEPLcUnzq:-NqNgXs-5qVXEPLcUnzr:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/fee/gas_usage.rs#L105)):*
> ```XML
> }
> 
> // Returns the gas cost of class information added to L2 via a Declare transaction. Each code felt
> ```





_Suggestion:_
```XML
s cost of declared class codes (both Sierra and Casm)
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1137 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-NqNfyCv6inZ30n7kUQn:-NqNfyCv6inZ30n7kUQo:bukfqut) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/transaction/transactions_test.rs#L1137)):*
> ```XML
> 
>     let da_gas = declare_expected_gas_vector(tx_version, use_kzg_da);
>     let code_gas: GasVector = get_code_gas_cost(Some(class_info.clone()), versioned_constants);
> ```

Necessary?



_Code quote:_
```XML
: GasVector
```

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1475)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ayeletstarkware, @barak-b-starkware, and @noaov1)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1475)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @barak-b-starkware, and @noaov1)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1475)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @barak-b-starkware)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/fee/gas_usage.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-NqNgXs-5qVXEPLcUnzq:-NqR98T82jXxSpZjZfBf:bvst1vt) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/fee/gas_usage.rs#L105)):*
> ```XML
> }
> 
> // Returns the gas cost of class information added to L2 via a Declare transaction. Each code felt
> ```

Done. ([Followup PR](https://github.com/starkware-libs/blockifier/pull/1484).)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1137 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1475#-NqNfyCv6inZ30n7kUQn:-NqR9FoABxNToLtFUJyc:b-idrskh) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/transaction/transactions_test.rs#L1137)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Necessary?
</blockquote></details>

Nope. Added by mistake.

Removed in a [followup PR](https://github.com/starkware-libs/blockifier/pull/1484).

**Pull request merged**
