### PR TITLE
Cargo update; use `+= &rhs` on VM resources.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/350)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/350)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`Cargo.lock` line 1463 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/350#-NR1vatO8-hseWEdfz-w:-NR1vatO8-hseWEdfz-x:btfgggl) ([raw file](https://github.com/starkware-libs/blockifier/blob/93743e9a21a1f98dec78283dd87daa7c04dae67b/Cargo.lock#L1463)):*
> ```TOML
> name = "papyrus_storage"
> version = "0.1.0"
> source = "git+https://github.com/starkware-libs/papyrus#f536f3c7045ef9708b6fa528539c8a2ab31ee710"
> ```

@giladchase mentioned a breaking change in updated papyrus, are you aware of that?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/350)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`Cargo.lock` line 1463 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/350#-NR1vatO8-hseWEdfz-w:-NR2K08V6lM8yyz5dWGc:bor1nv2) ([raw file](https://github.com/starkware-libs/blockifier/blob/93743e9a21a1f98dec78283dd87daa7c04dae67b/Cargo.lock#L1463)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@giladchase mentioned a breaking change in updated papyrus, are you aware of that?
</blockquote></details>

Breaking change already walks among us :zombie: 
Working on the fix.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/350)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/350)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/350)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/350#-NROP2hC72H6f3EruzL-:-NROP2hC72H6f3EruzL0:boerfn5) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2100f4d0a1885fe181b41cda88d0cd89a540d1b/crates/blockifier/src/execution/syscalls_test.rs#L146)):*
> ```XML
>     // Nested library call cost: library_call(inner) + library_call(library_call(inner)).
>     let mut main_call_vm_resources = VmExecutionResources { n_steps: 45, ..Default::default() };
>     main_call_vm_resources += &(&library_call_vm_resources * 2);
> ```

... doesn't seem equivalent to computation in previous revision, but ok



_Code quote:_
```XML
    // Nested library call cost: library_call(inner) + library_call(library_call(inner)).
    let mut main_call_vm_resources = VmExecutionResources { n_steps: 45, ..Default::default() };
    main_call_vm_resources += &(&library_call_vm_resources * 2);
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/350)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/350#-NROP2hC72H6f3EruzL-:-NRR-Vs53-PvBCPsR3ep:b37ez3h) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2100f4d0a1885fe181b41cda88d0cd89a540d1b/crates/blockifier/src/execution/syscalls_test.rs#L146)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... doesn't seem equivalent to computation in previous revision, but ok
</blockquote></details>

Got a more readable way to express it?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/350)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/350#-NROP2hC72H6f3EruzL-:-NRS7RESCcGmBlkGWeys:bd60vik) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2100f4d0a1885fe181b41cda88d0cd89a540d1b/crates/blockifier/src/execution/syscalls_test.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Got a more readable way to express it?
</blockquote></details>

previously you had
```
main = {83 steps + 1 rc} + lib_call + storage_entrypoint
```
now you have
```
main = { 45 steps } + (lib_call * 2)
```
second is easier to read, but the two lines don't look equivalent. If the second is the correct computation, then NP

**Pull request merged**
