### PR TITLE
Change Bouncer callback from Executor.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/665)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
Python side?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/665#-:-NYrl4pX1yueOilLznXX:b8qdezt)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/665#-NYrkpDB4aXhj2_CIpz0:-NYrkpDB4aXhj2_CIpz1:b-cvpfne) ([raw file](https://github.com/starkware-libs/blockifier/blob/9207937fe82fd71b683295289f8ea65959584e5a/crates/native_blockifier/src/py_transaction_executor.rs#L183)):*
> ```XML
>                     executor
>                         .executed_class_hashes
>                         .extend(&tx_executed_class_hashes);
> ```

Just making sure, we don't need this in the `not_enough_weight_error` branch cause it isn't being added to the batch?



_Code quote:_
```XML
                    executor
                        .executed_class_hashes
                        .extend(&tx_executed_class_hashes);
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/665)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/665#-NYrkpDB4aXhj2_CIpz0:-NYrvmCHAlWMSEPZKnjo:bucrcy6) ([raw file](https://github.com/starkware-libs/blockifier/blob/9207937fe82fd71b683295289f8ea65959584e5a/crates/native_blockifier/src/py_transaction_executor.rs#L183)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Just making sure, we don't need this in the `not_enough_weight_error` branch cause it isn't being added to the batch?
</blockquote></details>

Yup.
It doesn't really matter (block will be closed), but as you said - it's cleaner.

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/665)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
[Python PR](https://reviewable.io/reviews/starkware-industries/starkware/30569).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/665#-:-NZ0Ct44BGsd9h25vALW:b-bflai2)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/665)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
