### PR TITLE
refactor(execution, native_blockifier): move Bouncer to blockifier crate

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1445)

### CODE REVIEW

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1445#-:-Npyk68NCgjo9ZVUvIED:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1445#-Npyk2Qu2RY7P2pOWXEk:-Npyk2QvCYFs6GcjJu3s:b-dewb1l) (no related file):*
Python side? 

___

**Comment by barak-b-starkware** [comment]
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Python side?
</blockquote></details>

https://reviewable.io/reviews/starkware-industries/starkware/33827

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1445#-:-Nq16mmg5krW-gE4wk1R:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1445)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1445)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1445)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1445)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1445#-:-NqLcNR-6RAOU7LbaYeo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
