### PR TITLE
Dori/use macros

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/797)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/797)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/797#-NaLms6s7nFzYPS88KuK:-NaLms6s7nFzYPS88KuL:b7xbtrg) (no related file):*
no need to review r1<->r2, it's [this](https://reviewable.io/reviews/starkware-libs/blockifier/792)

___

**Review by noaov1 — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 10 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/797#-:-NaLofCZDa2xuixW-jxG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/797)* status: 10 of 16 files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/797)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/797)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
