### PR TITLE
Update SN API before version release.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)

### CODE REVIEW

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/792#-NaCcHBtBtihjJu6P15b:-NaCcHBtBtihjJu6P15c:b9ywud0) (no related file):*
Python [PR](https://reviewable.io/reviews/starkware-industries/starkware/31065)

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/792#-NaCcrRs3bO9p1VmO-GR:-NaCcrRs3bO9p1VmO-GS:b-xi04vs) ([raw file](https://github.com/starkware-libs/blockifier/blob/749b8aa53e23bd78a50c25517c044f8b522952d6/crates/blockifier/src/transaction/account_transaction.rs#L135)):*
> ```XML
>         match self {
>             Self::Declare(tx) => {
>                 let transaction_hash = tx.tx_hash();
> ```

why is this var needed...?



_Code quote:_
```XML
let transaction_hash = tx.tx_hash();
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/792#-NaCe8Xz3iz6GF16JiDv:-NaCe8Xz3iz6GF16JiDw:b-e5wbnk) ([raw file](https://github.com/starkware-libs/blockifier/blob/749b8aa53e23bd78a50c25517c044f8b522952d6/crates/blockifier/src/transaction/transactions_test.rs#L73)):*
> ```XML
> }
> 
> impl From<InvokeTransactionV1> for InvokeTransaction {
> ```

doesn't look safe in production, right?
is it legal to add
```
#[cfg(any(feature = "testing", test))]
```
above this...?



_Code quote:_
```XML
impl From<InvokeTransactionV1> for InvokeTransaction
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/792#-NaCcrRs3bO9p1VmO-GR:-NaG5a_T0A9JEQha2jXy:b-30iavd) ([raw file](https://github.com/starkware-libs/blockifier/blob/749b8aa53e23bd78a50c25517c044f8b522952d6/crates/blockifier/src/transaction/account_transaction.rs#L135)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this var needed...?
</blockquote></details>

Because tx was later shadowed, but you're right it's not a good enough reason. I changed it.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/792#-NaCe8Xz3iz6GF16JiDv:-NaGPt-J-6qhh9UhwP-3:b-mw5siq) ([raw file](https://github.com/starkware-libs/blockifier/blob/749b8aa53e23bd78a50c25517c044f8b522952d6/crates/blockifier/src/transaction/transactions_test.rs#L73)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

doesn't look safe in production, right?
is it legal to add
```
#[cfg(any(feature = "testing", test))]
```
above this...?
</blockquote></details>

Impl blocks defined in test files can't be used in non-test files. I couldn't find it in he docs, but I remember reading it and I verified this in the code.

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792#-:-NaGQmFX4CoM0VW4o8T6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/792#-NaGW2146GKpxtcNlQAm:-NaGm-00Do9x2ulXq1oZ:bveyzus) ([raw file](https://github.com/starkware-libs/blockifier/blob/563ba78ea165ccfcf2aee2dec1fa39ace90b2787/crates/blockifier/src/transaction/transactions.rs#L167)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why only this field? (and not also `max_fee` for instance)
Same question for `Invoke`. 
You can change now the nesting in `validate_entrypoint_calldata()`
</blockquote></details>

Right, thanks. I didn't see that nesting. Do you know of any other places?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/792#-NaGW2146GKpxtcNlQAm:-NaH66gqDRs1EEGufKC-:b-7qnegs) ([raw file](https://github.com/starkware-libs/blockifier/blob/563ba78ea165ccfcf2aee2dec1fa39ace90b2787/crates/blockifier/src/transaction/transactions.rs#L167)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Right, thanks. I didn't see that nesting. Do you know of any other places? 
</blockquote></details>

Nope. 
I still don't quite understand how you choose which fields to include :)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/792#-NaGW2146GKpxtcNlQAm:-NaH8Qk6-cZfz-nAkf5E:bo4g634) ([raw file](https://github.com/starkware-libs/blockifier/blob/563ba78ea165ccfcf2aee2dec1fa39ace90b2787/crates/blockifier/src/transaction/transactions.rs#L167)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Nope. 
I still don't quite understand how you choose which fields to include :)
</blockquote></details>

Oh. Only the ones that were used with the nesting.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by dorimedini-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`Cargo.toml` line 34 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/792#-NaHXN9d1OICWE0SqV3W:-NaHXN9d1OICWE0SqV3X:bfh4mva) ([raw file](https://github.com/starkware-libs/blockifier/blob/b66078c1a8c81655870f7927b8a88015fc519319/Cargo.toml#L34)):*
> ```TOML
> num-traits = "0.2"
> rstest = "0.17.0"
> papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", rev = "31f8cec" }
> ```

not released yet? why not 0.0.2?



_Code quote:_
```TOML
{ git = "https://github.com/starkware-libs/papyrus", rev = "31f8cec" }
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`Cargo.toml` line 34 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/792#-NaHXN9d1OICWE0SqV3W:-NaHXZzDDsX-zGtnLYrc:bvapi34) ([raw file](https://github.com/starkware-libs/blockifier/blob/b66078c1a8c81655870f7927b8a88015fc519319/Cargo.toml#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not released yet? why not 0.0.2?
</blockquote></details>

It is released but I had trouble building in Python with it. I asked they do another release without using a certain macro that caused the failure. Tagged you in the thread.
I pushed just to make sure it was the only problem.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/792)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
