### PR TITLE
feat(state): bouncer DA count: define StateWriteKeys

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1461)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1461)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 683 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1461#-Nq7AMji-8o1zmoYospp:-Nq7ObTO2EENWu_9cEMt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b756d3b38be4c7eac48f4eb485e90fa8d6abe53c/crates/blockifier/src/state/cached_state.rs#L683)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

There is a typo.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 712 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1461#-Nq78zLn2ccwwVC_ZlRk:-Nq7OdMg316edLChHe-3:bof5b3k) ([raw file](https://github.com/starkware-libs/blockifier/blob/b756d3b38be4c7eac48f4eb485e90fa8d6abe53c/crates/blockifier/src/state/cached_state.rs#L712)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

If you implement the `sub` method, you can use the minus sign (`-`).  (nonblocking).
</blockquote></details>

I tried, this trait consumes both self and other. And other is big
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 559 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1461#-Nq7ElST5oFWo7B8Yh0a:-Nq7PAp4DfANpQ6v5OHV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b756d3b38be4c7eac48f4eb485e90fa8d6abe53c/crates/blockifier/src/state/cached_state_test.rs#L559)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is this on purpose?
You mutated `keys1`, and then extended `keys0` with the mutated instance.

Is the intention or was the intension checking `extend` is commutative* (*except for the fact it affects the left hand side).
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1461)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1461#-:-Nq7RjRlD_H_L6MJNDcW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1461)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
