### PR TITLE
Data gas prices in block context

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1336)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1336)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1336#-NoBChiBBtBrFNUXg7DY:-NoBChiBBtBrFNUXg7DZ:b14fvr) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/33425)

___

**Review by Yoni-Starkware — COMMENTED** [review]
@giladchase FYI

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1336#-:-NoBVYQIAjp3lSVeKCG6:b-7xw26)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 10 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1336#-:-NoB_PcP0u2BHUunuuVj:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1336)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1336)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1336#-NoBChiBBtBrFNUXg7DY:-NoByhub5sOZmQv3N9Pp:btjvgl1) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[python side](https://reviewable.io/reviews/starkware-industries/starkware/33425)
</blockquote></details>

passed hodor

___

**Pull request merged**
