### PR TITLE
Added get_message_segment_length.

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/366)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware +reviewer:@noaov1 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/366#-:-NRcw1Lr7kNtDYkxlfEM:bd7uazw)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/366#-NRcw8Lh2TUoTRkYVwqc:-NRcw8Li9vqFwkQZUIvR:byvexim) ([raw file](https://github.com/starkware-libs/blockifier/blob/53cf8c497533f8dec43f161ede5d8661e1143efc/crates/blockifier/src/fee/gas_usage.rs#L27)):*
> ```XML
> /// that holds the segment size - are not counted.
> pub fn get_message_segment_length(
>     payload_lengths: Vec<u64>,
> ```

@noaov1 you said it's ok for it to be Vec[64] for now, right?



_Code quote:_
```XML
payload_lengths: Vec<u64>,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/366)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/366#-NRcw8Lh2TUoTRkYVwqc:-NRcxDmCCs_Znooy9szN:b-t4lkoi) ([raw file](https://github.com/starkware-libs/blockifier/blob/53cf8c497533f8dec43f161ede5d8661e1143efc/crates/blockifier/src/fee/gas_usage.rs#L27)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@noaov1 you said it's ok for it to be Vec[64] for now, right?
</blockquote></details>

maybe `&Vec<u64>` so we don't copy? `&` means borrow, right?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/366)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/366)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/366#-NRcw8Lh2TUoTRkYVwqc:-NRcySqP8COP1zpY7bpU:bbx8t0o) ([raw file](https://github.com/starkware-libs/blockifier/blob/53cf8c497533f8dec43f161ede5d8661e1143efc/crates/blockifier/src/fee/gas_usage.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe `&Vec<u64>` so we don't copy? `&` means borrow, right?
</blockquote></details>

צודק

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/366#-:-NRcyadk3pyTbOgEgzLH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/366)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/366#-NRcw8Lh2TUoTRkYVwqc:-NRh-GT323yazyL_UrtR:bche1nl) ([raw file](https://github.com/starkware-libs/blockifier/blob/53cf8c497533f8dec43f161ede5d8661e1143efc/crates/blockifier/src/fee/gas_usage.rs#L27)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes. I think that maybe using `usize` is better (it's the return type of `len()`)  and is more general. WDYT?
</blockquote></details>

Changed everything to usize, as requested

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/366)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/abi/constants.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/366#-NRgGvH_E_eqdBJuxK5m:-NRh0EoXErOYTkNAJlSh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0a2abbc6f8991742e3f70755d3cdb50f62ccf395/crates/blockifier/src/abi/constants.rs#L7)):*
> ```XML
> // The version is considered 0 for L1-Handler transaction hash calculation purposes.
> pub const L1_HANDLER_VERSION: u64 = 0;
> pub const CLASS_UPDATE_SIZE: u64 = 1;
> ```

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/366#-:-NRh9yvsAMxwv3DE4sxp:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @amosStarkware and @dorimedini-starkware)

**Pull request merged**
