### PR TITLE
feature: replace ctor by lazy_static

### PR DESCRIPTION
**Pull request by tdelabro**
ctor is not supported for madara wasm target
So let's use lazy static instead

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/427)

### CODE REVIEW

**Comment by Oppen** [comment]
I'd suggest using [once_cell](https://crates.io/crates/once_cell) instead, as it will be incorporated into the stdlib soon (meaning one fewer dep).

**Comment by tdelabro** [comment]
Once cell is not compatible with no_std for now: https://docs.rs/once_cell/1.17.1/once_cell/#faq (second line)
So I would prefer you avoid it, as I will have to change it in my fork

**Comment by Oppen** [comment]
> Once cell is not compatible with no_std for now: https://docs.rs/once_cell/1.17.1/once_cell/#faq (second line)
So I would prefer you avoid it, as I will have to change it in my fork

Crap. Thanks for pointing that out, I've been planning to change our `lazy_static` uses in cairo-rs and would have brought problems down the line. I think I'll subscribe to the tracking issue to see if that changes.

**Comment by tdelabro** [comment]
superseded by #1262

**Comment by tdelabro** [comment]
superseded by https://github.com/starkware-libs/blockifier/pull/1262

**Pull request closed without merging**
