### PR TITLE
Remove PyKzgResources. Reveal the state diff size.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1341)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
This PR should be merged before the Python side PR. Wait for the Python side PR to be created and to pass CI.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1341)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1341#-NoG9MyKDx-gEFjy8Pyo:-NoGMPgPEZzdGp40YspM:b7q02lx) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This PR should be merged before the Python side PR. Wait for the Python side PR to be created and to pass CI.
</blockquote></details>

... link to python side?
also, why this change? python side's bouncer info has indirection for KZG related fields, correct?

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1341)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yoni-Starkware)

**Comment by ArniStarkware** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... link to python side?
also, why this change? python side's bouncer info has indirection for KZG related fields, correct?
</blockquote></details>

Python side PR: https://github.com/starkware-industries/starkware/pull/33442

**Comment by ArniStarkware** [comment]
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Python side PR: https://github.com/starkware-industries/starkware/pull/33442
</blockquote></details>

The indirection is also removed on the Python side.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1341#-:-NoGQGB09o9gEyjLMHqk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1341)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Pull request merged**
