### PR TITLE
chore(concurrency): add execute method to the thread logic

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxHpZD08gKfMBoGPNQ-:-NxHpZD08gKfMBoGPNQ0:bmar9n) ([raw file](https://github.com/starkware-libs/blockifier/blob/2289cfb3feca8d2fec81f93f093546500e26980f/crates/blockifier/src/concurrency/worker_logic.rs#L80)):*
> ```XML
>     // Write the transaction execution outputs.
>     execution_output.result = execution_result;
>     let tx_reads_writes = transactional_state.cache.take();
> ```

I wanted to avoid clone. This code can panic though. 



_Code quote:_
```XML
    let tx_reads_writes = transactional_state.cache.take();
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: 3 of 4 files reviewed, 1 unresolved discussion

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: all files reviewed, 1 unresolved discussion

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxIA21OBDxfcFCe1a7C:-NxIILxj58-Y3c4LEijH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2289cfb3feca8d2fec81f93f093546500e26980f/crates/blockifier/src/concurrency/worker_logic.rs#L73)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please extract all the code that is relevant to try_commit_tx to a method.
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: 3 of 4 files reviewed, 1 unresolved discussion

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: all files reviewed, 1 unresolved discussion

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxMUsGr8tJmtPPfnOdW:-NxMUsGr8tJmtPPfnOdX:bt4y8ti) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6dac016e5ec33b398cf5b2a26b56a857155f57/crates/blockifier/src/concurrency/worker_logic.rs#L67)):*
> ```XML
>     tx_index: TxIndex,
> ) {
>     let ConcurrentExecutionContext { state, chunk, execution_outputs, block_context, .. } =
> ```

Hmmm, maybe we do need to make these functions methods of some struct



_Code quote:_
```XML
let ConcurrentExecutionContext { state, chunk, execution_outputs, block_context, .. } =
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxMThYJBNE3Z_5yrge9:-NxMV_qkCUzHTLx5CIaq:b-diz8wb) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6dac016e5ec33b398cf5b2a26b56a857155f57/crates/blockifier/src/concurrency/worker_logic.rs#L84)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

How does it work? can someone else take the lock on the struct while you update it?
</blockquote></details>

NVM, it's a common pattern I guess. The lock is probably released once the object is dropped or something like that.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
Lgtm ( but better to wait for a basic unit test)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-:-NxMWP6I3F075zWEgW50:bwcyinv)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxMZ7aA8TLWY0Viyglv:-NxMZ7aA8TLWY0Viyglw:b-upzpt3) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6dac016e5ec33b398cf5b2a26b56a857155f57/crates/blockifier/src/concurrency/worker_logic.rs#L82)):*
> ```XML
> 
>     // Write the transaction execution outputs.
>     execution_output.result = execution_result;
> ```

You assume that this is initialized, right?
Should we make it optional?



_Code quote:_
```XML
execution_output
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxMYWgh8comTuT9eDK_:-NxMYWgh8comTuT9eDKa:bq0o05i) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6dac016e5ec33b398cf5b2a26b56a857155f57/crates/blockifier/src/concurrency/worker_logic.rs#L86)):*
> ```XML
>     execution_output.reads = tx_reads_writes.initial_reads;
>     execution_output.writes = tx_reads_writes.writes;
>     execution_output.visited_pcs = transactional_state.visited_pcs;
> ```

It's better to use the constructor syntax, that way, the compiler tells you if you forget some field



_Code quote:_
```XML
    execution_output.reads = tx_reads_writes.initial_reads;
    execution_output.writes = tx_reads_writes.writes;
    execution_output.visited_pcs = transactional_state.visited_pcs;
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxMZ7aA8TLWY0Viyglv:-NxNKEYCAqPNr3jkY7Xp:bn3wtg6) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6dac016e5ec33b398cf5b2a26b56a857155f57/crates/blockifier/src/concurrency/worker_logic.rs#L82)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You assume that this is initialized, right?
Should we make it optional?
</blockquote></details>

Yes. 
Good idea. 
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxMThYJBNE3Z_5yrge9:-NxNLxD-BBvPWX82kK6a:b-14nw6e) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6dac016e5ec33b398cf5b2a26b56a857155f57/crates/blockifier/src/concurrency/worker_logic.rs#L84)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

NVM, it's a common pattern I guess. The lock is probably released once the object is dropped or something like that.
</blockquote></details>

Yes. the lock is dropped when we the `MutexGuard` goes out of scope (here at the end of the function). I changed the order of the operations in the method for a minimal lock time.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxMYWgh8comTuT9eDK_:-NxNMIbgAOnhmDCkQBp5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6dac016e5ec33b398cf5b2a26b56a857155f57/crates/blockifier/src/concurrency/worker_logic.rs#L86)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It's better to use the constructor syntax, that way, the compiler tells you if you forget some field
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxMThYJBNE3Z_5yrge9:-NxNyqHg8EpBOz89lQfA:b-zcjvte) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6dac016e5ec33b398cf5b2a26b56a857155f57/crates/blockifier/src/concurrency/worker_logic.rs#L84)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes. the lock is dropped when we the `MutexGuard` goes out of scope (here at the end of the function). I changed the order of the operations in the method for a minimal lock time.
</blockquote></details>

Thanks
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxNzXaS4Rmvn6c2j2oi:-NxNzXaTBgAX0n5srrD-:brb2iqw) ([raw file](https://github.com/starkware-libs/blockifier/blob/e59b2710db6ac855f7b35c89103b2acdbdbc3916/crates/blockifier/src/concurrency/worker_logic.rs#L94)):*
> ```XML
>     *execution_output = Some(ExecutionTaskOutput {
>         reads: tx_reads_writes.initial_reads,
>         writes: tx_reads_writes.writes,
> ```

The writes of failed txs are corrupted. 
It may not affect us (other than "undoing" writes that were never applied), but I think we should empty it at some level (similar to what is done in reverted txs).



_Code quote:_
```XML
writes: tx_reads_writes.writes,
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxMNY50D1RSx2LZgH2g:-NxMNY50D1RSx2LZgH2h:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e26a900cea70f5ecf29523b2eb4300eb6e80dc5/crates/blockifier/src/concurrency/worker_logic.rs#L37)):*
> ```XML
>         panic!("Cell of transaction index {} is poisoned. Data: {:?}.", tx_index, *error.get_ref())
>     })
> }
> ```





_Suggestion:_
```XML
pub fn lock_mutex_in_array<T: Debug>(array: &[Mutex<T>], tx_index: TxIndex) -> MutexGuard<'_, T> {
    array[tx_index].lock().unwrap_or_else(|error| {
        panic!("Cell of transaction index {} is poisoned. Data: {:?}.", tx_index, *error.get_ref())
    })
}
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxMNY50D1RSx2LZgH2g:-NxOgqcbAzRfIY9PsMEf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e26a900cea70f5ecf29523b2eb4300eb6e80dc5/crates/blockifier/src/concurrency/worker_logic.rs#L37)):*
> ```XML
>         panic!("Cell of transaction index {} is poisoned. Data: {:?}.", tx_index, *error.get_ref())
>     })
> }
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxNzXaS4Rmvn6c2j2oi:-NxOgs4N9at78xnFU83L:b-6i9r62) ([raw file](https://github.com/starkware-libs/blockifier/blob/e59b2710db6ac855f7b35c89103b2acdbdbc3916/crates/blockifier/src/concurrency/worker_logic.rs#L94)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The writes of failed txs are corrupted. 
It may not affect us (other than "undoing" writes that were never applied), but I think we should empty it at some level (similar to what is done in reverted txs).
</blockquote></details>

You are right. In my mind I thought to add an if before undoing writes (meaning, skipping the undo writes if `tx_info = error`), but this way it's more explicit.
And I added a similar behaviour for the visited pcs

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-:-NxQzaXgC4IX4CVbQ_Lp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 5 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxQz6BF5E2W6kyIHX7F:-NxQz6BF5E2W6kyIHX7G:b-7txcg3) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe7d1ea4c1eb340bc8cbddd85cc45e417ea79026/crates/blockifier/src/concurrency/scheduler.rs#L5)):*
> ```XML
> use std::sync::{Mutex, MutexGuard};
> 
> use crate::concurrency::worker_logic::lock_mutex_in_array;
> ```

Sounds like it should be in some utils file (non-blocking)



_Code quote:_
```XML
use crate::concurrency::worker_logic::lock_mutex_in_array;
```

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 31 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxR-4neA4BTCC83rmtW:-NxR-4neA4BTCC83rmtX:bh2w252) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe7d1ea4c1eb340bc8cbddd85cc45e417ea79026/crates/blockifier/src/concurrency/worker_logic.rs#L31)):*
> ```XML
> }
> 
> pub struct WorkersExecutor<S: StateReader> {
> ```

TaskExecutor/WorkExecutor



_Code quote:_
```XML
WorkersExecutor
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxQzwpmExrm9PUAYQeR:-NxQzwpmExrm9PUAYQeS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe7d1ea4c1eb340bc8cbddd85cc45e417ea79026/crates/blockifier/src/concurrency/worker_logic.rs#L49)):*
> ```XML
>                 }
>                 Task::ValidationTask(tx_index) => self.validate(tx_index),
>                 Task::NoTask => scheduler.next_task(),
> ```





_Suggestion:_
```XML
        let mut task = Task::NoTask;
        loop {
            task = match task {
                Task::ExecutionTask(tx_index) => {
                    self.execute(tx_index);
                    Task::NoTask
                }
                Task::ValidationTask(tx_index) => self.validate(tx_index),
                Task::NoTask => self.scheduler.next_task(),
```

**Review by avi-starkware — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 5 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxQz6BF5E2W6kyIHX7F:-NxSFcfQ4ZeexJnvHaKN:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe7d1ea4c1eb340bc8cbddd85cc45e417ea79026/crates/blockifier/src/concurrency/scheduler.rs#L5)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Sounds like it should be in some utils file (non-blocking)
</blockquote></details>

Done
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 31 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-NxR-4neA4BTCC83rmtW:-NxSGbWb4A_Q-q0W4tzG:b-rdf7o2) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe7d1ea4c1eb340bc8cbddd85cc45e417ea79026/crates/blockifier/src/concurrency/worker_logic.rs#L31)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

TaskExecutor/WorkExecutor
</blockquote></details>

I added the s to indicate that it's one executor to all the workers. Maybe it's confusing. Done.

**Review by Yoni-Starkware — DISMISSED** [review]
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882#-:-Nxf6qfnDsl-3Jq3dZKy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 3 of 4 files at r5, 1 of 5 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1882)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
