### PR TITLE
feat: add the new stack trace to ValidateTransactionError

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1712)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1712)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1712#-Ntp4_r418NCtxO0b6tP:-Ntp4_r418NCtxO0b6tQ:b-mq9rwt) (no related file):*
Please add a regression test for this

___

**Comment by zuphitf** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Please add a regression test for this
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1712)* status: all files reviewed, 3 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/Cargo.toml` line 57 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1712#-NtvHYyz1ylzrcjQ8VyD:-NtvHYyz1ylzrcjQ8VyE:bl1hjo1) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f66070dc071d50740d65397b6ae69800de40f28/crates/blockifier/Cargo.toml#L57)):*
> ```TOML
> pretty_assertions.workspace = true
> rstest.workspace = true
> test-case.workspace = true
> ```

only used in tests, right?



_Suggestion:_
```TOML
phf.workspace = true
rstest = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
sha3.workspace = true
starknet-crypto.workspace = true
starknet_api = { workspace = true, features = ["testing"] }
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
regex.workspace = true
rstest.workspace = true
test-case.workspace = true
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 1072 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1712#-NtvI1Bm0l4kKmKafI6i:-NtvI1Bm0l4kKmKafI6j:b-2ohusw) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f66070dc071d50740d65397b6ae69800de40f28/crates/blockifier/src/execution/entry_point_test.rs#L1072)):*
> ```XML
> "
>         ),
>     };
> ```

cleaner, no need for regex, checks basically the same thing; or am I missing something?



_Suggestion:_
```XML
    let expected_error_prefix = format!(
        "Transaction validation has failed:
0: Error in the called contract (contract address: {contract_address}, class hash: {class_hash}, \
             selector: {selector}):"
             );
    let expected_error_suffix = match cairo_version {
        CairoVersion::Cairo0 => "An ASSERT_EQ instruction failed: 1 != 0.",
        CairoVersion::Cairo1 => "Execution failed. Failure reason: 0x496e76616c6964207363656e6172696f ('Invalid scenario')."
    };
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 1081 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1712#-NtvIQ1k2fKo5yRhV1V3:-NtvIQ1k2fKo5yRhV1V4:byr4ffv) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f66070dc071d50740d65397b6ae69800de40f28/crates/blockifier/src/execution/entry_point_test.rs#L1081)):*
> ```XML
>     let cleaned_actual_error = &re.replace_all(&actual_error_str, "pc=0:*");
>     // Compare actual trace to the expected trace (sans pc locations).
>     assert_eq!(cleaned_actual_error.to_string(), cleaned_expected_error.to_string());
> ```

see above



_Suggestion:_
```XML
    let actual_error = account_tx.execute(state, block_context, true, true).unwrap_err();
    let actual_error_str = actual_error.to_string();
    assert!(actual_error_str.startswith(expected_error_prefix));
    assert!(actual_error_str.endswith(expected_error_suffix));
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1712)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 1072 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1712#-NtvI1Bm0l4kKmKafI6i:-NtvMcY9-XnKTNwtr07P:bbwrl4i) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f66070dc071d50740d65397b6ae69800de40f28/crates/blockifier/src/execution/entry_point_test.rs#L1072)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

cleaner, no need for regex, checks basically the same thing; or am I missing something?
</blockquote></details>

ah no nevermind... asserting equality is better, you assert the number of frames as well. retracting
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 1081 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1712#-NtvIQ1k2fKo5yRhV1V3:-NtvMhfW7x2Xxw-sx0uf:bbwrl4i) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f66070dc071d50740d65397b6ae69800de40f28/crates/blockifier/src/execution/entry_point_test.rs#L1081)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

ah no nevermind... asserting equality is better, you assert the number of frames as well. retracting

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1712)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/Cargo.toml` line 57 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1712#-NtvHYyz1ylzrcjQ8VyD:-NtvVQ6p5UmPxRp_jF2X:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f66070dc071d50740d65397b6ae69800de40f28/crates/blockifier/Cargo.toml#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

only used in tests, right?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1712#-:-NtzqjCoCBnEuuJhK9HL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
