### PR TITLE
Unify the gateway validations to all transactions' types.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1134)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
[Python PR](https://reviewable.io/reviews/starkware-industries/starkware/32537).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1134#-:-NjCehUABYNj4okVAhrq:b-ahk05n)* status: 0 of 2 files reviewed, all discussions resolved

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1134)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1134#-NjCrZvp5ZCYfaLx4ko1:-NjCrZvp5ZCYfaLx4ko2:b-9nczb6) ([raw file](https://github.com/starkware-libs/blockifier/blob/d085c7944caa5bf7accd151424bef19760d2a737/crates/native_blockifier/src/py_validator.rs#L119)):*
> ```XML
>         if let AccountTransaction::DeployAccount(_deploy_account_tx) = account_tx {
>             let (_py_tx_execution_info, _py_casm_hash_calculation_resources) =
>                 self.execute(tx, raw_contract_class)?;
> ```

this also performs `__validate__` IIRC; `AccountTransaction::execute_raw` is called.
Why not `match` on the account transaction and perform different "perform validations" logic in each branch?



_Code quote:_
```XML
self.execute(tx, raw_contract_class)?;
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1134)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1134#-NjCs90-1k-SY41ZpNOJ:-NjCs90-1k-SY41ZpNOK:bg7o8qe) ([raw file](https://github.com/starkware-libs/blockifier/blob/d085c7944caa5bf7accd151424bef19760d2a737/crates/native_blockifier/src/py_transaction.rs#L137)):*
> ```XML
> // Transactions creation.
> 
> pub fn py_account_tx(
> ```

Use in `py_tx`?



_Code quote:_
```XML
py_account_tx
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1134#-NjCsJZX5X_oN6UOFEAh:-NjCsJZX5X_oN6UOFEAi:b-jh46zm) ([raw file](https://github.com/starkware-libs/blockifier/blob/d085c7944caa5bf7accd151424bef19760d2a737/crates/native_blockifier/src/py_validator.rs#L132)):*
> ```XML
>         // Post validations.
>         // TODO(Noa, 09/11/2023): Add post-validation checks.
>         // TODO(Ayelet, 09/11/2023): Check call succeeded.
> ```

Why not once? `let validate_call_info = match ...; // Then check once`.



_Code quote:_
```XML
// TODO(Ayelet, 09/11/2023): Check call succeeded.
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1134)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_validator.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1134#-NjCrZvp5ZCYfaLx4ko1:-NjCsbWA678ciN9_HUoE:be6e52k) ([raw file](https://github.com/starkware-libs/blockifier/blob/d085c7944caa5bf7accd151424bef19760d2a737/crates/native_blockifier/src/py_validator.rs#L119)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this also performs `__validate__` IIRC; `AccountTransaction::execute_raw` is called.
Why not `match` on the account transaction and perform different "perform validations" logic in each branch?
</blockquote></details>

I forgot the return. Fixed.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1134)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1134)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1134#-NjCs90-1k-SY41ZpNOJ:-NjCtJJL60n-dQhectYZ:b-z10uk8) ([raw file](https://github.com/starkware-libs/blockifier/blob/d085c7944caa5bf7accd151424bef19760d2a737/crates/native_blockifier/src/py_transaction.rs#L137)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use in `py_tx`?
</blockquote></details>

Very good point. Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1134#-NjCsJZX5X_oN6UOFEAh:-NjCtaEA2MRVExW5aGIR:b-idvei3) ([raw file](https://github.com/starkware-libs/blockifier/blob/d085c7944caa5bf7accd151424bef19760d2a737/crates/native_blockifier/src/py_validator.rs#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not once? `let validate_call_info = match ...; // Then check once`.
</blockquote></details>

We also check the `execute_call_info` for deploy account.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1134)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1134#-:-NjD-Fsq6MUqxM0n5e2f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
