### PR TITLE
Merge main-v0.13.1 into main

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1755)

### CODE REVIEW

**Comment by noaov1** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/5cf3a4f3a7bc4f6abc7de6077b6f68b9eb928b55..main-v0.13.1#diff-79227bb6cc8b8dd82bfcc791f0a911f73dcfec44d04b56e7dfc940c78311e76c) [Dst](https://github.com/starkware-libs/blockifier/compare/5cf3a4f3a7bc4f6abc7de6077b6f68b9eb928b55..main#diff-79227bb6cc8b8dd82bfcc791f0a911f73dcfec44d04b56e7dfc940c78311e76c) crates/blockifier/resources/versioned_constants.json
[Src](https://github.com/starkware-libs/blockifier/compare/5cf3a4f3a7bc4f6abc7de6077b6f68b9eb928b55..main-v0.13.1#diff-59bda33934a9347c3c17bc26b66692dff387808f8f1628da0204cf3f08a29ea8) [Dst](https://github.com/starkware-libs/blockifier/compare/5cf3a4f3a7bc4f6abc7de6077b6f68b9eb928b55..main#diff-59bda33934a9347c3c17bc26b66692dff387808f8f1628da0204cf3f08a29ea8) crates/blockifier/src/fee/gas_usage.rs
[Src](https://github.com/starkware-libs/blockifier/compare/5cf3a4f3a7bc4f6abc7de6077b6f68b9eb928b55..main-v0.13.1#diff-c60befa67313a64cd2f9ad156230755f2c7b08840d587adc35eabb224651da72) [Dst](https://github.com/starkware-libs/blockifier/compare/5cf3a4f3a7bc4f6abc7de6077b6f68b9eb928b55..main#diff-c60befa67313a64cd2f9ad156230755f2c7b08840d587adc35eabb224651da72) crates/blockifier/src/fee/gas_usage_test.rs
[Src](https://github.com/starkware-libs/blockifier/compare/5cf3a4f3a7bc4f6abc7de6077b6f68b9eb928b55..main-v0.13.1#diff-7acba1e848a679c11d945d81c43b284ae91a493ac7aa8e1d6d3759777ce68d42) [Dst](https://github.com/starkware-libs/blockifier/compare/5cf3a4f3a7bc4f6abc7de6077b6f68b9eb928b55..main#diff-7acba1e848a679c11d945d81c43b284ae91a493ac7aa8e1d6d3759777ce68d42) crates/blockifier/src/versioned_constants.rs

**Review by noaov1 — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1755)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1755)* status: 2 of 8 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1755#-Nu_QzAcDiARCc_45nMl:-Nu_QzAd3f-fMEck-OGZ:b-s7w6zs) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e5016f0ee93fff126f7758fad6ddeef717f8286/crates/blockifier/src/fee/gas_usage_test.rs#L68)):*
> ```XML
>     let call_infos_iter = call_infos.iter();
>     let expected = GasVector::from_l1_gas(
>         // 8 keys and 11 data words overall.
> ```

An indication to the bug.



_Code quote:_
```XML
        // 8 keys and 11 data words overall.
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1755#-:-NubiBWu9sYykRvTMzKM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1755)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1755)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
