### PR TITLE
feat: expose versioned constants from past versions

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2049)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2049)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @Yoni-Starkware)

___
*[`Cargo.toml` line 41 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-O1G6Z7Q9hx8J-j7tOaK:-O1G6Z7Q9hx8J-j7tOaL:b-5rr7xn) ([raw file](https://github.com/starkware-libs/blockifier/blob/8617d83532f100d38690788635038e7ca54d58aa/Cargo.toml#L41)):*
> ```TOML
> once_cell = "1.19.0"
> papyrus_storage = "0.4.0-dev.4"
> paste = "1.0.15"
> ```

Used to concatenate identifiers, for example:
```
paste! { [<VERSIONED_CONSTANTS_ $variant>] }
```
for `$variant = V0_13_0` becomes
```
VERSIONED_CONSTANTS_V0_13_0
```



_Code quote:_
```TOML
paste = "1.0.15"
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2049)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-O1GnyT-1lhVtK1qGBcO:-O1GnyT-1lhVtK1qGBcP:b-c23a80) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c24692d075d092057d9e0002e7f755a09e12454/crates/blockifier/src/versioned_constants.rs#L42)):*
> ```XML
>         paste! {
>             $(
>                 pub(crate) const [<VERSIONED_CONSTANTS_ $variant:upper _JSON>]: &str =
> ```

`VERSIONED_CONSTANTS_V0_13_0_JSON` for example.
If `$variant` is `Latest` then we'll get `VERSIONED_CONSTANTS_LATEST_JSON`



_Code quote:_
```XML
[<VERSIONED_CONSTANTS_ $variant:upper _JSON>]
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
Can you change the py_block_executor to use the new getter?

> Reviewed 2 of 6 files at r2, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-:-O24gO2p-B6iqBChMHfz:b-f77vaj)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @giladchase)

___
*[`crates/blockifier/src/versioned_constants.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-O1Gquxb9Zm1mwG-NEjT:-O24h_bKCi3-ccFqw0U1:b1zz2tb) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c24692d075d092057d9e0002e7f755a09e12454/crates/blockifier/src/versioned_constants.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

name suggestions?
</blockquote></details>

VersionedConstantsByStarknetVersion?
___
*[`crates/blockifier/src/versioned_constants.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-O24guaJ1aJEDJNEGZ1S:-O24guaJ1aJEDJNEGZ1T:bki17bw) ([raw file](https://github.com/starkware-libs/blockifier/blob/f970b61ae8c7dcf7f4d8d39cf5eaa85deeccc61d/crates/blockifier/src/versioned_constants.rs#L119)):*
> ```XML
>     /// To use custom constants, initialize the struct from a file using `try_from`.
>     pub fn latest_constants() -> &'static Self {
>         &VERSIONED_CONSTANTS_LATEST
> ```

Use the new impl

(how can you refer to a name that is not defined?)



_Suggestion:_
```XML
   Self::from(StarknetVersion::Latest)
```

**Review by dorimedini-starkware — COMMENTED** [review]
WDYM?
It calls the latest_constants endpoint, why change it?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-:-O24sHlL5soXsLW76WdD:b-g10mi8)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-O1Gquxb9Zm1mwG-NEjT:-O24s3CTAQy85eYQt62A:b-h5uk7r) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c24692d075d092057d9e0002e7f755a09e12454/crates/blockifier/src/versioned_constants.rs#L35)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

VersionedConstantsByStarknetVersion?
</blockquote></details>

isn't `StarknetVersion` better...?
___
*[`crates/blockifier/src/versioned_constants.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-O24guaJ1aJEDJNEGZ1S:-O24sA_I24uVIUMQvc7H:biqivnd) ([raw file](https://github.com/starkware-libs/blockifier/blob/f970b61ae8c7dcf7f4d8d39cf5eaa85deeccc61d/crates/blockifier/src/versioned_constants.rs#L119)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use the new impl

(how can you refer to a name that is not defined?)
</blockquote></details>

`Self::from` or `Self::get`? I'm in favor of the latter

**Review by Yoni-Starkware — COMMENTED** [review]
It is a step towards getting the version from Python, but it can be a separate PR.
:lgtm: 

> Reviewed 1 of 4 files at r5, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-:-O25Cmz_3V7WiIn8ySiJ:b-qhm3qp)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @giladchase)

___
*[`crates/blockifier/src/versioned_constants.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-O1Gquxb9Zm1mwG-NEjT:-O25D-wC61lPSm4J_nYG:b-mie3yv) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c24692d075d092057d9e0002e7f755a09e12454/crates/blockifier/src/versioned_constants.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't `StarknetVersion` better...?
</blockquote></details>

Ok, but it contains more than just the version

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2049)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @giladchase)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2049)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @giladchase)

___
*[`crates/blockifier/src/versioned_constants.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2049#-O1Gquxb9Zm1mwG-NEjT:-O25ZcKs2PHTXahKu5ho:b-3jmg39) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c24692d075d092057d9e0002e7f755a09e12454/crates/blockifier/src/versioned_constants.rs#L35)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Ok, but it contains more than just the version
</blockquote></details>

WDYM? the enum is *just* the version, no data

**Pull request merged**
