### PR TITLE
Bump `cairo-[vm/felt]` to `0.8.3`.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1240)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1240)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1240#-NlMLTWv4iy8y0wM0P6H:-NlMLTWv4iy8y0wM0P6I:b-afblaj) (no related file):*
[Python PR](https://reviewable.io/reviews/starkware-industries/starkware/32955).

___

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1240)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`Cargo.toml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1240#-NlMLmJa59B74KE5GJT2:-NlMLmJa59B74KE5GJT3:b-g1b94r) ([raw file](https://github.com/starkware-libs/blockifier/blob/0cf631d11cafc631bb299ecbe4767485393b42a4/Cargo.toml#L9)):*
> ```TOML
> 
> [workspace.package]
> version = "0.4.0-rc0"
> ```

This was preliminary bumped to `0.4.0`; should stay `0.3.0`. Will set a tag after this is merged.



_Code quote:_
```TOML
0.4.0-rc0
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1240)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1240#-NlMMIHu2FTdiKSwrokH:-NlMMIHu2FTdiKSwrokI:blar4mx) ([raw file](https://github.com/starkware-libs/blockifier/blob/8240244b4cb5c8cabbaa6788644b637debd061ae/crates/blockifier/src/transaction/transactions.rs#L215)):*
> ```XML
>                         Ok(None)
>                     }
>                     Err(error) => Err(TransactionExecutionError::from(error)),
> ```

`clippy` in CI is more up-to-date, so it fails; this was fixed in `main-0.13.0`.



_Code quote:_
```XML
Err(TransactionExecutionError::from(error))
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1240#-:-NlMMPxa3THaqduZe6zR:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @giladchase)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1240)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @giladchase)

___
*[`Cargo.toml` line 21 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1240#-NlMMUTxEB5O56sLrJrp:-NlMMUTxEB5O56sLrJrq:b3r14j8) ([raw file](https://github.com/starkware-libs/blockifier/blob/8240244b4cb5c8cabbaa6788644b637debd061ae/Cargo.toml#L21)):*
> ```TOML
> ark-secp256r1 = "0.4.0"
> assert_matches = "1.5.0"
> cairo-felt = "=0.8.3"
> ```

`"0.8.3"` took `0.8.7` for some reason, will understand with Gilad why.



_Code quote:_
```TOML
"=0.8.3"
```

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1240)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
