### PR TITLE
feat: define ctor entry point error

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1840)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1840)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1840#-NwjiUn9BFFv8s3FZaWP:-NwjiUn9BFFv8s3FZaWQ:b-pgpspe) (no related file):*
split of [this](https://reviewable.io/reviews/starkware-libs/blockifier/1838)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1840)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/execution/errors.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1840#-NwnIfaW7VWkn5vM5Nrb:-NwnIfaX3x6HLmJ6ExZc:b-bilgdg) ([raw file](https://github.com/starkware-libs/blockifier/blob/eef106b6e990ba9928f498f2b4868cb277841519/crates/blockifier/src/execution/errors.rs#L116)):*
> ```XML
> }
> 
> // TODO(Dori, 5/5/2024): Delete this converter.
> ```

done [here](https://reviewable.io/reviews/starkware-libs/blockifier/1844)



_Code quote:_
```XML
// TODO(Dori, 5/5/2024): Delete this converter.
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1840#-NwnIiGu981n_lM-5Koj:-NwnIiGu981n_lM-5Kok:b-bilgdg) ([raw file](https://github.com/starkware-libs/blockifier/blob/eef106b6e990ba9928f498f2b4868cb277841519/crates/blockifier/src/transaction/transactions.rs#L312)):*
> ```XML
>         let call_info = deployment_result.map_err(|error| {
>             TransactionExecutionError::ContractConstructorExecutionFailed {
>                 // TODO(Dori, 5/5/2024): Add the constructor error to the error enum.
> ```

done [here](https://reviewable.io/reviews/starkware-libs/blockifier/1844)



_Code quote:_
```XML
// TODO(Dori, 5/5/2024): Add the constructor error to the error enum.
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1840)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1840#-Nwnl_ma1p71kmexKM8I:-Nwnl_mb4hZhwT9lE_xa:bfopuvs) ([raw file](https://github.com/starkware-libs/blockifier/blob/eef106b6e990ba9928f498f2b4868cb277841519/crates/blockifier/src/execution/entry_point.rs#L307)):*
> ```XML
>             contract_address,
>             constructor_selector: None,
>         };
> ```

You use this "lambda function" in more than one place. (here and something similar in `crates/blockifier/src/execution/execution_utils.rs`).

Define this util in `crates/blockifier/src/execution/errors.rs` as a "class method" of `ConstructorEntryPointExecutionError`: a function that gets `class_hash` and `contract_address` and returns the lambda function.  (OK, tell me if this is possible).



_Code quote:_
```XML
    let wrap_error_no_selector =
        |error: EntryPointExecutionError| ConstructorEntryPointExecutionError::ExecutionError {
            error,
            class_hash,
            contract_address,
            constructor_selector: None,
        };
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1840#-Nwnk-py39CLijoUmx18:-Nwnk-py39CLijoUmx19:b-nn7ntp) ([raw file](https://github.com/starkware-libs/blockifier/blob/eef106b6e990ba9928f498f2b4868cb277841519/crates/blockifier/src/execution/entry_point.rs#L338)):*
> ```XML
>             constructor_selector: Some(constructor_selector),
>         }
>     })
> ```

Or the reverse in the `Utility to reduce boilerplate`.



_Suggestion:_
```XML
        ConstructorEntryPointExecutionError::ExecutionError {
            error,
            class_hash,
            contract_address,
            constructor_selector: Some(constructor_selector),
        }
    })
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1840)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1840#-Nwnl_ma1p71kmexKM8I:-Nwoc3NnBUC7lNJBLTbf:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/eef106b6e990ba9928f498f2b4868cb277841519/crates/blockifier/src/execution/entry_point.rs#L307)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

You use this "lambda function" in more than one place. (here and something similar in `crates/blockifier/src/execution/execution_utils.rs`).

Define this util in `crates/blockifier/src/execution/errors.rs` as a "class method" of `ConstructorEntryPointExecutionError`: a function that gets `class_hash` and `contract_address` and returns the lambda function.  (OK, tell me if this is possible).
</blockquote></details>

done
___
*[`crates/blockifier/src/execution/entry_point.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1840#-Nwnk-py39CLijoUmx18:-Nwodijf7ANL6Oy0KP6a:b-132xnq) ([raw file](https://github.com/starkware-libs/blockifier/blob/eef106b6e990ba9928f498f2b4868cb277841519/crates/blockifier/src/execution/entry_point.rs#L338)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Or the reverse in the `Utility to reduce boilerplate`.
</blockquote></details>

no longer relevant

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/entry_point.rs` line 328 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1840#-Nwp3P5A7YFuZPdx0UOi:-Nwp3P5A7YFuZPdx0UOj:b-6r4wfu) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad1484c499bb7f7ad91d6669df6e4cdf923a2dbe/crates/blockifier/src/execution/entry_point.rs#L328)):*
> ```XML
>             contract_address: ctor_context.storage_address,
>             constructor_selector: Some(constructor_selector),
>         }
> ```

use `ConstructorEntryPointExecutionError::new`



_Code quote:_
```XML
        ConstructorEntryPointExecutionError::ExecutionError {
            error,
            class_hash: ctor_context.class_hash,
            contract_address: ctor_context.storage_address,
            constructor_selector: Some(constructor_selector),
        }
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1840)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1840)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 328 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1840#-Nwp3P5A7YFuZPdx0UOi:-NwpAegK1To1RCD2p4nI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad1484c499bb7f7ad91d6669df6e4cdf923a2dbe/crates/blockifier/src/execution/entry_point.rs#L328)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

use `ConstructorEntryPointExecutionError::new`
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1840#-:-Nwrptiy-JxGPa-0B3dX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1840)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
