### PR TITLE
refactor(state): move global cache to papyrus reader

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1774)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
Python side https://github.com/starkware-industries/starkware/pull/34684

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1774#-:-Nv1e6hs4HEdSRqS4Xw9:bu3n3ss)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @noaov1 and @OriStarkware)

**Review by noaov1 — APPROVED** [review]
Nice!

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1774#-:-Nv6zHT-1bDv_LiUbSwc:b-83sjoh)* status: all files reviewed, 2 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1774#-Nv6yPdIEfZu2XFZweWn:-Nv6yPdIEfZu2XFZweWo:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f5d7dfd33a619f6fde3252fdfc8f8a11978bd124/crates/native_blockifier/src/py_block_executor_test.rs#L22)):*
> ```XML
>     let casm = CasmContractClass::default();
>     let contract_class = ContractClass::V1(ContractClassV1::try_from(casm.clone()).unwrap());
>     let class_hash = class_hash!("0x1");
> ```





_Suggestion:_
```XML
    let test_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
    let class_hash = test_contract.get_class_hash();
    let contract_class = test_contract.get_class();
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1774#-Nv6u1mv6qs1OQcMRJLs:-Nv6u1mv6qs1OQcMRJLt:b-ttztnx) ([raw file](https://github.com/starkware-libs/blockifier/blob/f5d7dfd33a619f6fde3252fdfc8f8a11978bd124/crates/native_blockifier/src/py_state_diff.rs#L18)):*
> ```XML
> 
> #[pyclass]
> #[derive(FromPyObject, Default)]
> ```

Alphabetize :)



_Code quote:_
```XML
#[derive(FromPyObject, Default)]
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1774)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @OriStarkware)

___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1774#-Nv6yPdIEfZu2XFZweWn:-Nv7I08CA-TAEvPXSlcA:b4pvtll) ([raw file](https://github.com/starkware-libs/blockifier/blob/f5d7dfd33a619f6fde3252fdfc8f8a11978bd124/crates/native_blockifier/src/py_block_executor_test.rs#L22)):*
> ```XML
>     let casm = CasmContractClass::default();
>     let contract_class = ContractClass::V1(ContractClassV1::try_from(casm.clone()).unwrap());
>     let class_hash = class_hash!("0x1");
> ```

I need the casm :(

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1774#-:-Nv7qTxY2yW9Xn15GBYe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
