### PR TITLE
Prepare cairo1 vm for entrypoint call

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/464)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #464** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/464" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/464?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/464)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAGWBO5tn3FB2uGqiO:-NVAGWBO5tn3FB2uGqiP:b-458asg) ([raw file](https://github.com/starkware-libs/blockifier/blob/f70384fead0ef8a8c433658b4dc3b53cbb71bd7a/crates/blockifier/src/execution/cairo1_execution.rs#L46)):*
> ```XML
>     } = initialize_execution_context(&call, &contract_class, state, context)?;
> 
>     let (implicit_args, args) = prepare_call_arguments(
> ```

No usage here for separating implicit args.?
Currently we need them separately to [validate the run](https://github.com/starkware-libs/blockifier-old/blob/74d4c1b41d041a5f46c22d43ec4bb8038bb82f40/crates/blockifier/src/execution/deprecated_execution.rs#L250). I see you commented it out.



_Code quote:_
```XML
(implicit_args, args) 
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAIDa_-_jxVy54xLqC:-NVAIDa_-_jxVy54xLqD:basvgby) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L49)):*
> ```XML
>         entry_point,
>     } = initialize_execution_context(&call, &contract_class, state, context)?;
>     let args = prepare_call_arguments(
> ```

Please restore blank line above.



_Code quote:_
```XML
let args = prepare_call_arguments(
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAML0nBdOPe2rfO8Zm:-NVAML0nBdOPe2rfO8Zn:bgtlp0x) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L61)):*
> ```XML
>     let previous_vm_resources = syscall_handler.context.resources.vm_resources.clone();
> 
>     prepare_builtin_costs(&mut vm, &contract_class);
> ```

This can be move before `previous_vm_resources` definition, right?



_Code quote:_
```XML
prepare_builtin_costs(&mut vm, &contract_class);
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVALLBj602wl3Y47XrB:-NVALLBj602wl3Y47XrC:b-xi2gj6) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L69)):*
> ```XML
> }
> 
> fn prepare_builtin_costs(vm: &mut VirtualMachine, contract_class: &ContractClassV1) {
> ```

Please move after `prepare_call_arguments`.
And fix `unwrap`s?



_Code quote:_
```XML
prepare_builtin_costs
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVALgogBxGz_nUjnkCV:-NVALgogBxGz_nUjnkCW:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L72)):*
> ```XML
>     // Create the builtin cost segment, with dummy values.
>     let mut builtin_cost_segment = vm.add_memory_segment();
>     let builtin_cost_segment_start = builtin_cost_segment;
> ```





_Suggestion:_
```XML
builtin_cost_segment_start_ptr
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAM4vaAZ4NZ2rdCRjO:-NVAM4vaAZ4NZ2rdCRjP:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L77)):*
> ```XML
>         write_felt(vm, &mut builtin_cost_segment, 0.into()).unwrap();
>     }
>     // Put a pointer to the builtin cost segment at the end of the program (after the
> ```

Add a blank line above.



_Code quote:_
```XML
// Put a pointer to the builtin cost segment at the end of the program (after the
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAMD5i1D4x3yPntk4l:-NVAMD5i1D4x3yPntk4m:bany0bc) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L82)):*
> ```XML
>     // Push a "ret" opcode.
>     write_felt(vm, &mut ptr, stark_felt!("0x208b7fff7fff7ffe")).unwrap();
>     // Push a pointer to the builtin cost segment.
> ```

Why is the segment length not needed?



_Code quote:_
```XML
// Push a pointer to the builtin cost segment.
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAMTDr5FQtmpu_WjO7:-NVAMTDr5FQtmpu_WjO8:b-is1vh2) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L92)):*
> ```XML
>     context: &'a mut ExecutionContext,
> ) -> Result<VmExecutionContext<'a>, PreExecutionError> {
>     let entry_point = get_entry_point(call, contract_class)?;
> ```

Maybe a method of `CallEntryPoint`, or of `ContractClassV1`?



_Code quote:_
```XML
get_entry_point
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAMeRr-ngquiZ7Ojxq:-NVAMeRr-ngquiZ7Ojxr:b-v8vziw) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L155)):*
> ```XML
>             continue;
>         }
>         panic!("Unsupported builtin");
> ```

Plan to handle gracefully?



_Code quote:_
```XML
panic!("Unsupported builtin");
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAMrZN5hVS4HxbSjdh:-NVAMrZN5hVS4HxbSjdi:b2jrokj) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L170)):*
> ```XML
>     let calldata_start_ptr = read_only_segments.allocate(vm, &calldata)?;
>     args.push(CairoArg::Single(calldata_start_ptr.into()));
>     args.push(CairoArg::Single((calldata_start_ptr + calldata.len()).unwrap().into()));
> ```

Define `calldata_end_ptr`, please.



_Code quote:_
```XML
calldata_start_ptr + calldata.len()
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/464)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAMD5i1D4x3yPntk4l:-NVAPqJU37rZowHnin_c:b-88cv7d) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is the segment length not needed?
</blockquote></details>

Asked Yoni and he said the convention is `[start, end]`. Let's add a method for that (something like `allocate_segment(&mut vm, data)`, or use the `allocate` method I showed you.
You repeat this code next PR as well.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/464)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAMD5i1D4x3yPntk4l:-NVAQWqQAhiTDAuKrAjt:bbejal1) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Asked Yoni and he said the convention is `[start, end]`. Let's add a method for that (something like `allocate_segment(&mut vm, data)`, or use the `allocate` method I showed you.
You repeat this code next PR as well.
</blockquote></details>

Meanwhile in Python we _do_ still collect all allocated-during-run segments and validate they are of fixed length after execution (no one wrote after them). Let's preserve this for now, or mindfully decide otherwise. 

We also have a huge security test, and I want to understand what parts of it we still need.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/464)* status: 2 of 3 files reviewed, 10 unresolved discussions (waiting on @spapinistarkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/464)* status: all files reviewed, 10 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/464)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAGWBO5tn3FB2uGqiO:-NVASwNg23M0oAkXdfuS:b-n2x7s0) ([raw file](https://github.com/starkware-libs/blockifier/blob/f70384fead0ef8a8c433658b4dc3b53cbb71bd7a/crates/blockifier/src/execution/cairo1_execution.rs#L46)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No usage here for separating implicit args.?
Currently we need them separately to [validate the run](https://github.com/starkware-libs/blockifier-old/blob/74d4c1b41d041a5f46c22d43ec4bb8038bb82f40/crates/blockifier/src/execution/deprecated_execution.rs#L250). I see you commented it out.
</blockquote></details>

There's no real need in alidation potentially, since this is coming from Sierra.
It could still be a good sanity check.
But it's might be a bit more complicated, sinc we have things like segment arena. I guess this could be a future PR to readd validation, but it's not necessary.
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVALgogBxGz_nUjnkCV:-NVAUPAq0sJji_LXduFl:bwygxsx) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L72)):*
> ```XML
>     // Create the builtin cost segment, with dummy values.
>     let mut builtin_cost_segment = vm.add_memory_segment();
>     let builtin_cost_segment_start = builtin_cost_segment;
> ```

Noted.
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVAMD5i1D4x3yPntk4l:-NVAVgLo6VrXutFNua8F:b-xcu6jq) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb1c3f43fdecfc27ea98fcec561a089802a96cf0/crates/blockifier/src/execution/cairo1_execution.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Meanwhile in Python we _do_ still collect all allocated-during-run segments and validate they are of fixed length after execution (no one wrote after them). Let's preserve this for now, or mindfully decide otherwise. 

We also have a huge security test, and I want to understand what parts of it we still need.
</blockquote></details>

You can take care of it later.

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/464)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVXwNCJAMTf7elhszVK:-NVXwNCJAMTf7elhszVL:b-h2hksj) ([raw file](https://github.com/starkware-libs/blockifier/blob/27360f938c66356bd8c3a03dcecc8701a8b2eb8f/crates/blockifier/src/execution/cairo1_execution.rs#L243)):*
> ```XML
> }
> 
> pub fn validate_run(
> ```

Plan to reintroduce this?
If we're going to call it, let's not delete it.



_Code quote:_
```XML
validate_run
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVXw8kSDPqlBNW9r9zu:-NVXw8kSDPqlBNW9r9zv:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b6e17522c9a2340d1f4c44a004fad9c1941b91a/crates/blockifier/src/execution/cairo1_execution.rs#L116)):*
> ```XML
>     // additional `ret` statement).
>     let mut ptr = (vm.get_pc() + contract_class.program.data.len())?;
>     // Push a "ret" opcode.
> ```





_Suggestion:_
```XML
`ret`
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/464)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/464)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/464#-NVXwNCJAMTf7elhszVK:-NVc5Iht1VxswyEyc4KO:b-jasqwi) ([raw file](https://github.com/starkware-libs/blockifier/blob/27360f938c66356bd8c3a03dcecc8701a8b2eb8f/crates/blockifier/src/execution/cairo1_execution.rs#L243)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Plan to reintroduce this?
If we're going to call it, let's not delete it.
</blockquote></details>

It's going to be completely changed. I added a TODO to validate things.

**Pull request merged**
