### PR TITLE
Support Invoke V0.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/429)

### CODE REVIEW

**Review by alonh5 — COMMENTED** [review]
Depends on this PR:
https://reviewable.io/reviews/starkware-libs/starknet-api/55

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/429#-:-NU1ssTu4l5VBhmm6ria:b-hhh5gr)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

**Review by elintul — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/429)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/429#-NU274xM2PhvXI9rx07B:-NU274xM2PhvXI9rx07C:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2801a8ba3e208405b3dbefcd7834f568c1339d4f/crates/blockifier/src/transaction/account_transaction.rs#L121)):*
> ```XML
>     fn verify_tx_version(&self, version: TransactionVersion) -> TransactionExecutionResult<()> {
>         let allowed_versions: Vec<TransactionVersion> = match self {
>             Self::Declare(_, _) | Self::Invoke(_) => {
> ```





_Suggestion:_
```XML
            // Support `Declare` of version 0 in order to allow bootstrapping of a new system.
            Self::Declare(_, _) | Self::Invoke(_) => {
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/429#-:-NUGeOOp6J6yd5HiaVaP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/429)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
