### PR TITLE
test(concurrency): test commit phase in the worker logic

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1918)

### CODE REVIEW

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1918)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NypKMLsCHjCrUcGZ44w:-NypKMLsCHjCrUcGZ44x:b-wbcs2d) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/scheduler.rs#L159)):*
> ```XML
>         *self.commit_index.lock().unwrap()
>     }
> ```

I think it should be expect here in case of a poisoned lock 
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 352 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NypMeKX45YPQJB8AbG3:-NypMeKX45YPQJB8AbG4:bb6f423) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L352)):*
> ```XML
>         nonce: nonce_manager.next(account_address)
>     });
> ```

Is there a reason to use TX ver1 here and not ver 3?

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1918)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NypKMLsCHjCrUcGZ44w:-NypU3ZQ23yTPEGlt21q:bhhimhp) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/scheduler.rs#L159)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think it should be expect here in case of a poisoned lock
</blockquote></details>

There is `expect` here. It is inside the function `lock_mutex_in_array`.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 352 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NypMeKX45YPQJB8AbG3:-NypTCYuBh5M_WOB-Obv:bfa528q) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L352)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Is there a reason to use TX ver1 here and not ver 3?
</blockquote></details>

The transactions are arbitrary. I am just testing that all executed transactions get committed during the commit phase. The actual flow of individual commits should be tested in the `commit_tx` test.

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1918)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1918)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuQ4IbEO1I9jnUc6rK:-NyuQ4Ic9qN3n0eDjZtb:b-s00old) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L342)):*
> ```XML
>     });
> 
>     let account_tx2 = account_invoke_tx(invoke_tx_args! {
> ```

Why is this transaction needed?



_Code quote:_
```XML
    let account_tx2 = account_invoke_tx(invoke_tx_args! {
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 362 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuPIC6EcP5wxuMEvpw:-NyuPIC6EcP5wxuMEvpx:bw7lr57) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L362)):*
> ```XML
>     // Creates 2 active tasks.
>     worker_executor.scheduler.next_task();
>     worker_executor.scheduler.next_task();
> ```

I wonder if it's needed now after we removed the `n_active_tasks` field



_Code quote:_
```XML
    // Creates 2 active tasks.
    worker_executor.scheduler.next_task();
    worker_executor.scheduler.next_task();
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 363 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuQolJ2wcF43nPZJMM:-NyuQolKERRfLXZvUzts:bf2oayc) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L363)):*
> ```XML
>     worker_executor.scheduler.next_task();
>     worker_executor.scheduler.next_task();
> ```

Please add a call to `commit_while_possible()` and see that the commit index remained the same (no `Executed` status)
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 376 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuPjtF42gTqJTdQDjU:-NyuPjtF42gTqJTdQDjV:bxxzoiq) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L376)):*
> ```XML
>     // Verify the status of the first two transactions is `Committed`.
>     assert_eq!(*worker_executor.scheduler.get_tx_status(0), TransactionStatus::Committed);
>     assert_eq!(*worker_executor.scheduler.get_tx_status(1), TransactionStatus::Committed);
> ```

Can you please add a call to `commit_while_possible()` after all the transactions were committed and see that the commit index remained the same?
+ Check the `done` marker after committing the last transaction?
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 377 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuR1aL6k4u3YmhKkHu:-NyuR1aL6k4u3YmhKkHv:b-nt33tz) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L377)):*
> ```XML
>     assert_eq!(*worker_executor.scheduler.get_tx_status(0), TransactionStatus::Committed);
>     assert_eq!(*worker_executor.scheduler.get_tx_status(1), TransactionStatus::Committed);
> }
> ```

Please add a TODO to check the halt mechanism when we support the bouncer

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1918)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuQ4IbEO1I9jnUc6rK:-Nyul3oXBgb9I4yMMCr8:bj4thu2) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L342)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is this transaction needed?
</blockquote></details>

The flow is:
1. Execute 2 out of 3 transactions.
2. Run `commit_while_possible`.
3. Check that the first two transactions have been committed.

I wanted to check that the function can commit more the one tx and that it stops at the first tx with status != `Executed`.
Therefore, I need at least three transactions.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 362 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuPIC6EcP5wxuMEvpw:-NyukSyF2ZxMIfrr_Kxm:b-6ei7fh) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L362)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if it's needed now after we removed the `n_active_tasks` field
</blockquote></details>

It's needed to change the status of the first two transactions from `ReadyToExecute` to `Executing`. Otherwise, executing them would panic when reaching `finish_execution` and trying to change the status to `Executed`.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 363 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuQolJ2wcF43nPZJMM:-NyumLbUC3oEcz-1UfuA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L363)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add a call to `commit_while_possible()` and see that the commit index remained the same (no `Executed` status)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 376 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuPjtF42gTqJTdQDjU:-NyumOZI3zZi164nTxTD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L376)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please add a call to `commit_while_possible()` after all the transactions were committed and see that the commit index remained the same?
+ Check the `done` marker after committing the last transaction?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 377 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuR1aL6k4u3YmhKkHu:-NyumkG87nX3mKnPwoIe:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L377)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add a TODO to check the halt mechanism when we support the bouncer
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1918)* status: all files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 362 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuPIC6EcP5wxuMEvpw:-NzJBEVe12IGmX_grx0B:b-6hhw19) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L362)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

It's needed to change the status of the first two transactions from `ReadyToExecute` to `Executing`. Otherwise, executing them would panic when reaching `finish_execution` and trying to change the status to `Executed`.
</blockquote></details>

Can you please document that?
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 391 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-Nz2MLrE4CBqnOtismog:-Nz2MLrE4CBqnOtismoh:bydlvqt) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L391)):*
> ```XML
>             &[*storage_key.0.key(),storage_value ], // Calldata:  address, value.
>         ),
>         max_fee: Fee(MAX_FEE),
> ```

Please define variables. 



_Code quote:_
```XML
        calldata: create_calldata(
            test_contract_address,
            "test_storage_read_write",
            &[*storage_key.0.key(),storage_value ], // Calldata:  address, value.
        ),
        max_fee: Fee(MAX_FEE),
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 425 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-Nz2MSXZ54iz2XXx6NV6:-Nz2MSXZ54iz2XXx6NV7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L425)):*
> ```XML
> 
>     // Enter commit phase.
>     worker_executor.commit_while_possible().unwrap();
> ```





_Suggestion:_
```XML
    // Try to commit before any transaction is ready. 
    worker_executor.commit_while_possible().unwrap();
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 438 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NzJBSt94hPvnHin7kgN:-NzJBSt94hPvnHin7kgO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L438)):*
> ```XML
>     worker_executor.execute(1);
> 
>     // Enter commit phase.
> ```





_Suggestion:_
```XML
    // Commit ythe first two transactions (only).
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 452 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NzJBhSH4bZy6JoZ3yng:-NzJBhSI7xDZT5N-sr7s:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L452)):*
> ```XML
>     worker_executor.execute(2);
> 
>     // Enter commit phase.
> ```





_Suggestion:_
```XML
    // Commit the third (and last) transaction.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 460 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NzJCd5kC5u-ap9lWTkE:-NzJCd5kC5u-ap9lWTkF:b-rloj6e) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L460)):*
> ```XML
>     assert_eq!(*worker_executor.scheduler.get_tx_status(2), TransactionStatus::Committed);
>     assert_eq!(worker_executor.scheduler.next_task(), Task::Done);
> ```

Please add:



_Code snippet:_
```XML
// Try to commit when all transactions are already committed.
worker_executor.commit_while_possible().unwrap();
assert_eq!(worker_executor.scheduler.get_n_committed_txs(), 3);
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1918)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 362 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuPIC6EcP5wxuMEvpw:-NzOrZCY4F3X0UgfCDiq:bbc3ybh) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L362)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please document that?
</blockquote></details>

Done.

Note that creating such tasks happens in most of the other tests in this file. Do we want to document there as well?
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 391 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-Nz2MLrE4CBqnOtismog:-NzOqJrND93B6fX5JQte:b-c7l3jg) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L391)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please define variables.
</blockquote></details>

Done.

Note that this is copied from another test in this file. Do you want me to change it there as well?
Additionally, meshi's util functions for her commit_tx test might be useful for creating these transactions once they get in.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 425 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-Nz2MSXZ54iz2XXx6NV6:-NzOqxnv40blhOpDHee-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L425)):*
> ```XML
> 
>     // Enter commit phase.
>     worker_executor.commit_while_possible().unwrap();
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 438 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NzJBSt94hPvnHin7kgN:-NzOrn-XDtKfgbhSSl9V:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L438)):*
> ```XML
>     worker_executor.execute(1);
> 
>     // Enter commit phase.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 452 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NzJBhSH4bZy6JoZ3yng:-NzOsoOuBRUwB6mkWMeT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L452)):*
> ```XML
>     worker_executor.execute(2);
> 
>     // Enter commit phase.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 460 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NzJCd5kC5u-ap9lWTkE:-NzOso0s43jQPu1m_PyV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L460)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add:
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1918)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 362 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-NyuPIC6EcP5wxuMEvpw:-NzTOoqa55Gnsg6-P6t_:b-hfghm4) ([raw file](https://github.com/starkware-libs/blockifier/blob/b37ea37c7154d610faf95656d9ec9f7f39ccdac3/crates/blockifier/src/concurrency/worker_logic_test.rs#L362)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.

Note that creating such tasks happens in most of the other tests in this file. Do we want to document there as well?
</blockquote></details>

Sounds good
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 391 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1918#-Nz2MLrE4CBqnOtismog:-NzTOZ520hwNsYbdSxsV:b-orumjy) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34e6eb3626731b750b143850e02273355fcfd8d/crates/blockifier/src/concurrency/worker_logic_test.rs#L391)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.

Note that this is copied from another test in this file. Do you want me to change it there as well?
Additionally, meshi's util functions for her commit_tx test might be useful for creating these transactions once they get in.
</blockquote></details>

Good point

**Pull request merged**
