### PR TITLE
Add validate positive flow test.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/266)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/266)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgL21q0mrB69cbnW0M:-NNgL21q0mrB69cbnW0N:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L206)):*
> ```XML
> }
> 
> fn create_state_account_without_validation() -> CachedState<DictStateReader> {
> ```





_Suggestion:_
```XML
create_state_with_no_validation_account
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgLJzi4J8wtOUVaWT2:-NNgLJzi4J8wtOUVaWT3:b1d2mop) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L212)):*
> ```XML
>         ACCOUNT_CONTRACT_PATH,
>         TEST_ERC20_ACCOUNT_BALANCE_KEY,
>         actual_fee().0 as u64,
> ```

Please give this a name, since we can't pass arguments by name.
I actually don't understand why we need `actual_fee` function.



_Code quote:_
```XML
actual_fee().0 as u64
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgLAB-CdcaF0yc7kIp:-NNgLAB-CdcaF0yc7kIq:b-4m2740) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L216)):*
> ```XML
> }
> 
> fn create_state_faulty_account() -> CachedState<DictStateReader> {
> ```

Not sure this function is needed; are you planning to use it in more than one test?



_Suggestion:_
```XML
create_state_with_faulty_account
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/266)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgM-bHCL-sQHn8fpkZ:-NNgM-bHCL-sQHn8fpk_:b661zra) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L552)):*
> ```XML
> }
> 
> #[test]
> ```

If the negative scenarios are easy to add with the given infrastructure, let's add then in a subsequent PR.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 569 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgLtJPCwapBA0BjcJm:-NNgLtJPCwapBA0BjcJn:bhxbkvz) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L569)):*
> ```XML
>             version: TransactionVersion(stark_felt!(1)),
>             signature: TransactionSignature(vec![
>                 StarkFelt::from(scenario),
> ```

Let's define this before, as you did with the calldata.



_Code quote:_
```XML
            signature: TransactionSignature(vec![
                StarkFelt::from(scenario),
                additional_data.unwrap_or_else(|| StarkFelt::from(0)),
            ]),
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/266)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgL21q0mrB69cbnW0M:-NNgMv1a2dHax9PE1QRM:b-1xh52b) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L206)):*
> ```XML
> }
> 
> fn create_state_account_without_validation() -> CachedState<DictStateReader> {
> ```

Do you think that with the given change it is more clear that this is a state for an account with no validations?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgLJzi4J8wtOUVaWT2:-NNgNfgaD5PAvelxPiSm:b-9izpkl) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L212)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please give this a name, since we can't pass arguments by name.
I actually don't understand why we need `actual_fee` function.
</blockquote></details>

Done. We use it in order to know what is the expected actual fee. 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgLAB-CdcaF0yc7kIp:-NNgLu2S6ItK9wMnj6oQ:b-mal9lu) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L216)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure this function is needed; are you planning to use it in more than one test?
</blockquote></details>

Yes. In `__validate_declare__` and `__validate_deploy__` negative flow test. 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgM-bHCL-sQHn8fpkZ:-NNgMF6k0xMAM9cqra_m:bhy9ot6) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L552)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

If the negative scenarios are easy to add with the given infrastructure, let's add then in a subsequent PR.
</blockquote></details>

Will do.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/266)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgL21q0mrB69cbnW0M:-NS5JGqt5g8QChjNB3_q:ba0eh2f) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L206)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do you think that with the given change it is more clear that this is a state for an account with no validations?
</blockquote></details>

Perhaps `create_state_with_trivial_validation_account`.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgLAB-CdcaF0yc7kIp:-NS5JekIDIbcjrjVEmy2:b-hd7py0) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L216)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes. In `__validate_declare__` and `__validate_deploy__` negative flow test. 
</blockquote></details>

Perhaps `create_state_with_falliable_validation_account`.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 628 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NS5HjYM7NdlOvdC7NGP:-NS5HjYM7NdlOvdC7NGQ:b6clctb) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c2841ecc224cb39e600d7939dcd08803b261888/crates/blockifier/src/transaction/transactions_test.rs#L628)):*
> ```XML
>             stark_felt!(0)                                     // Calldata length.
>         ];
>         let signature = TransactionSignature(vec![
> ```

Please add a comment explaining how the signature is used in the test contract.



_Code quote:_
```XML
        let signature = TransactionSignature(vec![
            StarkFelt::from(scenario),
            additional_data.unwrap_or_else(|| StarkFelt::from(0)),
        ]);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 633 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NS5Frdr7ZS4hfThj49E:-NS5Frdr7ZS4hfThj49F:ba7kxv2) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c2841ecc224cb39e600d7939dcd08803b261888/crates/blockifier/src/transaction/transactions_test.rs#L633)):*
> ```XML
>         ]);
> 
>         InvokeTransaction {
> ```

Maybe use `crate::test_utils::invoke_tx()`?



_Code quote:_
```XML
InvokeTransaction {
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/266)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NNgLAB-CdcaF0yc7kIp:-NS63tT-4W1SHKYtdp62:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c603843802d06934956b13e97010565e0d968/crates/blockifier/src/transaction/transactions_test.rs#L216)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Perhaps `create_state_with_falliable_validation_account`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 628 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NS5HjYM7NdlOvdC7NGP:-NS67EYuC4QDXGoqCuBo:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c2841ecc224cb39e600d7939dcd08803b261888/crates/blockifier/src/transaction/transactions_test.rs#L628)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Please add a comment explaining how the signature is used in the test contract.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 633 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NS5Frdr7ZS4hfThj49E:-NS68Vb9EXeygNstQlVd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c2841ecc224cb39e600d7939dcd08803b261888/crates/blockifier/src/transaction/transactions_test.rs#L633)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe use `crate::test_utils::invoke_tx()`?
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/266#-:-NSAId6-7ulJ1lCbxGAV:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 630 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/266#-NSAI3GY-leM2Z9U39Qz:-NSAI3GY-leM2Z9U39R-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6fd0d546ddd20f352f7b442fb43c3f37d827371b/crates/blockifier/src/transaction/transactions_test.rs#L630)):*
> ```XML
>         ];
>         // We use the signature to set the scenario. If the scenario is `CALL_CONTRACT` we also use
>         // it to set the contract_address.
> ```





_Suggestion:_
```XML
        // The first felt of the signature is used to set the scenario. If the scenario is `CALL_CONTRACT` the second
        // felt is used to pass the contract address.
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 6 of 9 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/266)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by noaov1 — COMMENTED** [review]
> Dismissed @elintul from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/266)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
