### PR TITLE
refactor(execution): clean PyBlockExecutor

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1850)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1850)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1850#-NwpctFPBj1jIqjWe93-:-NwpctFPBj1jIqjWe930:b-n6rwnn) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d4766fde9876848e379add121025a8506dccb8c/crates/native_blockifier/src/py_block_executor.rs#L169)):*
> ```XML
>         let charge_fee = true;
>         let tx_type: String = get_py_tx_type(tx).expect(PY_TX_PARSING_ERR).to_string();
>         let tx: Transaction = py_tx(tx, optional_py_class_info).expect(PY_TX_PARSING_ERR);
> ```

The given txs were validated and constructed in python. Parsing error must lead to panic, and not failing the tx



_Code quote:_
```XML
        let tx_type: String = get_py_tx_type(tx).expect(PY_TX_PARSING_ERR).to_string();
        let tx: Transaction = py_tx(tx, optional_py_class_info).expect(PY_TX_PARSING_ERR);
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1850#-NwpcoGu2MFzQIRqqFMo:-NwpcoGu2MFzQIRqqFMp:bkkkerw) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b87bdce1f5ef3e0648874cc1de8a92cedc8bc1e/crates/native_blockifier/src/py_block_executor.rs#L188)):*
> ```XML
> 
>     #[pyo3(signature = (txs_with_class_infos))]
>     pub fn execute_txs(
> ```

Buggy (and not in use) implementation

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1850)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1850#-NwpctFPBj1jIqjWe93-:-NwrwE2m-HS6ybnJKFT_:b-fbnxb0) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d4766fde9876848e379add121025a8506dccb8c/crates/native_blockifier/src/py_block_executor.rs#L169)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The given txs were validated and constructed in python. Parsing error must lead to panic, and not failing the tx
</blockquote></details>

Can you please use `expect` also in `perform_validations`? [py_account_tx](https://github.com/starkware-libs/blockifier/blob/e9eb19edf874ff18f44ac29c95abb4e3af8978f5/crates/native_blockifier/src/py_validator.rs#L68)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1850)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1850#-NwpctFPBj1jIqjWe93-:-Nwry0Dg3-af7ZQl5OGR:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d4766fde9876848e379add121025a8506dccb8c/crates/native_blockifier/src/py_block_executor.rs#L169)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please use `expect` also in `perform_validations`? [py_account_tx](https://github.com/starkware-libs/blockifier/blob/e9eb19edf874ff18f44ac29c95abb4e3af8978f5/crates/native_blockifier/src/py_validator.rs#L68)
</blockquote></details>

Done

**Review by noaov1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1850)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1850#-NwpctFPBj1jIqjWe93-:-Nws0GrFCwqXBauxtcom:bsdsp2m) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d4766fde9876848e379add121025a8506dccb8c/crates/native_blockifier/src/py_block_executor.rs#L169)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I now wonder if the function itself should panic (if exists a scenario where we want `py_tx` to return an error)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1850)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1850#-NwpctFPBj1jIqjWe93-:-Nws0ZqH10I1yjrfVGyR:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d4766fde9876848e379add121025a8506dccb8c/crates/native_blockifier/src/py_block_executor.rs#L169)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I now wonder if the function itself should panic (if exists a scenario where we want `py_tx` to return an error)
</blockquote></details>

.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1850)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1850#-NwpctFPBj1jIqjWe93-:-NwsSo0L30wIoA24o2WS:b6x68rj) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d4766fde9876848e379add121025a8506dccb8c/crates/native_blockifier/src/py_block_executor.rs#L169)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

.
</blockquote></details>

Probably should not panic, but it's easier the unwrap at the end right now

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1850)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1850)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
