### PR TITLE
refactor: construct ActualCost without a Builder pattern

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1686)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1686)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1686#-NtMSqeT9DIolhoevwtM:-NtMSqeT9DIolhoevwtN:b-z3dmqq) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9b401d91934e572deb8dd93f3b4fe1df7a043d0/crates/blockifier/src/fee/actual_cost.rs#L32)):*
> ```XML
>     tx_type: TransactionType,
>     reverted_steps: usize,
> }
> ```

without this we get a `too many arguments` clippy error in `from_params`



_Code quote:_
```XML
/// Parameters required to compute actual cost of a transaction.
struct ActualCostParameters<'a, T: Iterator<Item = &'a CallInfo> + Clone> {
    tx_context: &'a TransactionContext,
    calldata_length: usize,
    signature_length: usize,
    code_size: usize,
    state_changes: &'a StateChanges,
    sender_address: Option<ContractAddress>,
    l1_handler_payload_size: Option<usize>,
    call_infos: T,
    execution_resources: &'a ExecutionResources,
    tx_type: TransactionType,
    reverted_steps: usize,
}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1686)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1686#-NtQ6vrG35425k3jYlAX:-NtQ6vrG35425k3jYlAY:b1oap7) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/34455)

___

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1686)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1686#-NtQBWVGBu9N1lD7wdHT:-NtQBWVGBu9N1lD7wdHU:b-dx96lt) ([raw file](https://github.com/starkware-libs/blockifier/blob/5b7229623fd9ec901f678f6650672b0ffb72058d/crates/blockifier/src/fee/actual_cost.rs#L42)):*
> ```XML
>     pub actual_resources: TransactionResources,
>     pub actual_gas_cost: GasVector,
> }
> ```

Non-blocking - can be done in a separate PR



_Suggestion:_
```XML
pub struct TransactionReceipt {
    pub fee: Fee,
    pub da_gas: GasVector,
    pub resources: TransactionResources,
    pub gas: GasVector,
}
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1686)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1686#-NtQCbYe5nR4Wr7fnfUR:-NtQCbYe5nR4Wr7fnfUS:b32vzt) ([raw file](https://github.com/starkware-libs/blockifier/blob/5b7229623fd9ec901f678f6650672b0ffb72058d/crates/blockifier/src/fee/actual_cost.rs#L71)):*
> ```XML
>         );
> 
>         let mut vm_resources = (execution_resources
> ```

NB



_Suggestion:_
```XML
cairo_resources
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1686#-NtQDQ5cEu5kjqwN-W4d:-NtQDQ5cEu5kjqwN-W4e:behgsp5) ([raw file](https://github.com/starkware-libs/blockifier/blob/5b7229623fd9ec901f678f6650672b0ffb72058d/crates/blockifier/src/fee/actual_cost.rs#L80)):*
> ```XML
>         // TODO(Dori, 1/5/2024): Once TransactionResources keeps reverted steps separately, do not
>         //   add them to the VM resources.
>         vm_resources.n_steps += reverted_steps;
> ```

What about the bouncer resourcers? this reverts the fix, right?



_Code quote:_
```XML
        // TODO(Dori, 1/5/2024): Once TransactionResources keeps reverted steps separately, do not
        //   add them to the VM resources.
        vm_resources.n_steps += reverted_steps;
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1686)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1686#-NtQDQ5cEu5kjqwN-W4d:-NtQDoRu7XMzM5SIaybC:b-xjugdp) ([raw file](https://github.com/starkware-libs/blockifier/blob/5b7229623fd9ec901f678f6650672b0ffb72058d/crates/blockifier/src/fee/actual_cost.rs#L80)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What about the bouncer resourcers? this reverts the fix, right?
</blockquote></details>

Oh, NVM

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1686#-:-NtQE4dj43caL8oakkBz:bnfp4nl)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1686)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1686#-NtQ6vrG35425k3jYlAX:-NtTIYtC6jh7oOPt79Zq:btjvgl1) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[python side](https://reviewable.io/reviews/starkware-industries/starkware/34455)
</blockquote></details>

passed hodor

___

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1686)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware and @noaov1)

**Pull request merged**
