### PR TITLE
Fix logic of test_fail_deploy_account.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 508 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlwDvn7DVSOs7gd9dil:-NlwDvn86qOcNIUoL5wO:bhzwtgs) ([raw file](https://github.com/starkware-libs/blockifier/blob/7faf566f994b8a56aef6bd1a99984acb61deff8c/crates/blockifier/src/transaction/account_transactions_test.rs#L508)):*
> ```XML
>         contract_address!(0_u32), // Dummy value.
>         contract_address_salt,
>     );
> ```

TY @noaov1.
Create the tx with MAX_FEE != 0.



_Code quote:_
```XML
    let deploy_account_tx = create_account_tx_for_validate_test(
        TransactionType::DeployAccount,
        INVALID,
        None,
        &mut NonceManager::default(),
        faulty_account_feature_contract,
        contract_address!(0_u32), // Dummy value.
        contract_address_salt,
    );
```

**Review by dorimedini-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 508 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlwDvn7DVSOs7gd9dil:-NlxBXYp8SrE0jxhb9n9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7faf566f994b8a56aef6bd1a99984acb61deff8c/crates/blockifier/src/transaction/account_transactions_test.rs#L508)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

TY @noaov1.
Create the tx with MAX_FEE != 0.
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxBP_y2D48iTSX9SyQ:-NlxBP_y2D48iTSX9SyR:b73rl7o) ([raw file](https://github.com/starkware-libs/blockifier/blob/145b2adcac0e9d94552b6c2c41c79700213fd7e4/crates/blockifier/src/test_utils/initial_test_state.rs#L17)):*
> ```XML
> 
> // Utility to set an account as minter in both fee tokens, and fund it.
> pub fn privileged_account(
> ```

@dorimedini-starkware - I am breaking the abstraction. Is this a good idea?



_Code quote:_
```XML
// Utility to set an account as minter in both fee tokens, and fund it.
pub fn privileged_account(
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxBP_y2D48iTSX9SyQ:-NlxSz7cBi-soqRvBN83:b-pywz8u) ([raw file](https://github.com/starkware-libs/blockifier/blob/145b2adcac0e9d94552b6c2c41c79700213fd7e4/crates/blockifier/src/test_utils/initial_test_state.rs#L17)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@dorimedini-starkware - I am breaking the abstraction. Is this a good idea?
</blockquote></details>

not really.
1. I don't like how the input is a storage view. If you really want to use this function, change the input to a `CachedState<DictStateReader>`.
2. This function also sets the account as the (only!) minter on both fee tokens. If you only want to fund the account, write another `fund_account` function (and call it from `privileged_account`).
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 516 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxTehU7GKsQlqKhbaf:-NlxTehV5r103IcEI7cC:b-fwj1hk) ([raw file](https://github.com/starkware-libs/blockifier/blob/52218fc6aae8601f0244f5348de2cb7372911195/crates/blockifier/src/transaction/account_transactions_test.rs#L516)):*
> ```XML
>         _ => unreachable!("deploy_account_tx is a DeployAccount"),
>     };
>     privileged_account(&block_context, deploy_address, BALANCE * 2, &mut state.state.storage_view);
> ```

does the account really need mint privileges?



_Code quote:_
```XML
privileged_account(&block_context, deploy_address, BALANCE * 2, &mut state.state.storage_view);
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 242 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxTkyY2pNX0RRgjhzW:-NlxTkyY2pNX0RRgjhzX:b3n2kan) ([raw file](https://github.com/starkware-libs/blockifier/blob/52218fc6aae8601f0244f5348de2cb7372911195/crates/blockifier/src/transaction/test_utils.rs#L242)):*
> ```XML
>         // Assumes the default value of StarkFelt is 0.
>         additional_data.unwrap_or_default(),
>     ]);
> ```

add `let max_fee = max_fee.unwrap_or_default()`, and then instead of `max_fee: max_fee.unwrap_or_default()` everywhere just write `max_fee,`.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 292 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxTzbZArwE9xbPiaOH:-NlxTzbZArwE9xbPiaOI:bq99urc) ([raw file](https://github.com/starkware-libs/blockifier/blob/52218fc6aae8601f0244f5348de2cb7372911195/crates/blockifier/src/transaction/test_utils.rs#L292)):*
> ```XML
> }
> 
> pub fn create_deploy_account_tx_for_faulty_account(
> ```

where is this used...?



_Code quote:_
```XML
pub fn create_deploy_account_tx_for_faulty_account(
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxBP_y2D48iTSX9SyQ:-Nm-alum1PzbVvtvmkd2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/145b2adcac0e9d94552b6c2c41c79700213fd7e4/crates/blockifier/src/test_utils/initial_test_state.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not really.
1. I don't like how the input is a storage view. If you really want to use this function, change the input to a `CachedState<DictStateReader>`.
2. This function also sets the account as the (only!) minter on both fee tokens. If you only want to fund the account, write another `fund_account` function (and call it from `privileged_account`).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 516 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxTehU7GKsQlqKhbaf:-Nm-d0OnD1xl-oGt2-UA:b-i01wcs) ([raw file](https://github.com/starkware-libs/blockifier/blob/52218fc6aae8601f0244f5348de2cb7372911195/crates/blockifier/src/transaction/account_transactions_test.rs#L516)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does the account really need mint privileges?
</blockquote></details>

No. Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 242 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxTkyY2pNX0RRgjhzW:-Nm-dUKo7B3yjUDClawk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/52218fc6aae8601f0244f5348de2cb7372911195/crates/blockifier/src/transaction/test_utils.rs#L242)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add `let max_fee = max_fee.unwrap_or_default()`, and then instead of `max_fee: max_fee.unwrap_or_default()` everywhere just write `max_fee,`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 292 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxTzbZArwE9xbPiaOH:-Nm-dQro1XU_a7xT_wf8:b65dkle) ([raw file](https://github.com/starkware-libs/blockifier/blob/52218fc6aae8601f0244f5348de2cb7372911195/crates/blockifier/src/transaction/test_utils.rs#L292)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is this used...?
</blockquote></details>

It is not. Sorry. Removed.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 235 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm-sloBCs4R6lN7vy5P:-Nm-sloBCs4R6lN7vy5Q:bwrttxk) ([raw file](https://github.com/starkware-libs/blockifier/blob/52218fc6aae8601f0244f5348de2cb7372911195/crates/blockifier/src/transaction/test_utils.rs#L235)):*
> ```XML
>     contract_address_salt: ContractAddressSalt,
>     max_fee: Option<Fee>,
> ) -> AccountTransaction {
> ```

clipy complained about too many args:
https://github.com/starkware-libs/blockifier/actions/runs/7257976607/job/19772585093



_Code quote:_
```XML
pub fn create_account_tx_for_validate_test(
    tx_type: TransactionType,
    scenario: u64,
    additional_data: Option<StarkFelt>,
    nonce_manager: &mut NonceManager,
    faulty_account: FeatureContract,
    sender_address: ContractAddress,
    contract_address_salt: ContractAddressSalt,
    max_fee: Option<Fee>,
) -> AccountTransaction {
```

**Comment by ArniStarkware** [comment]
This PR might conflict with #1283.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: all files reviewed, 10 unresolved discussions (waiting on @ArniStarkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0GqKd0UN_xS-yUEAv:-Nm0Jvck1v9g_vF8xHx4:b-647c40) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This PR might conflict with #1283.
</blockquote></details>

yes, should rebase... sorry

___
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxBP_y2D48iTSX9SyQ:-Nm0I5xg4JISPLiCADvb:b-10sqju) ([raw file](https://github.com/starkware-libs/blockifier/blob/145b2adcac0e9d94552b6c2c41c79700213fd7e4/crates/blockifier/src/test_utils/initial_test_state.rs#L17)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

rebase over [this](https://reviewable.io/reviews/starkware-libs/blockifier/1284) please
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0HsmK43q0CB-VBFCK:-Nm0HsmK43q0CB-VBFCL:bu6uued) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/test_utils/initial_test_state.rs#L24)):*
> ```XML
> ) {
>     fund_account(block_context, account_address, initial_balance, &mut state.state.storage_view);
> }
> ```

no need for a public wrapper to `fund_account`; just make `fund_account` public



_Code quote:_
```XML
// A public utility to fund an account.
pub fn set_account_balance(
    block_context: &BlockContext,
    account_address: ContractAddress,
    initial_balance: u128,
    state: &mut CachedState<DictStateReader>,
) {
    fund_account(block_context, account_address, initial_balance, &mut state.state.storage_view);
}
```
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0HzSV2n01u1niHRO8:-Nm0HzSV2n01u1niHRO9:b88wskm) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/test_utils/initial_test_state.rs#L39)):*
> ```XML
>     ] {
>         storage_view.insert((*fee_token, balance_key), stark_felt!(initial_balance));
>     }
> ```

rebase over [this](https://reviewable.io/reviews/starkware-libs/blockifier/1284)? or use `FeeType::iter()`



_Code quote:_
```XML
    for fee_token in &[
        block_context.fee_token_address(&FeeType::Strk),
        block_context.fee_token_address(&FeeType::Eth),
    ] {
        storage_view.insert((*fee_token, balance_key), stark_felt!(initial_balance));
    }
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 511 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0IbghDjq2CysCcvuq:-Nm0IbghDjq2CysCcvur:b-iex077) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/account_transactions_test.rs#L511)):*
> ```XML
>         },
>         &mut NonceManager::default(),
>     );
> ```

1. Add `#[derive(Default)]` to the struct
2. make this change (unless the salt variable is needed below, in which case define and use it in the struct as well) 



_Suggestion:_
```XML
    // Create and execute (failing) deploy account transaction.
    let deploy_account_tx = create_account_tx_for_validate_test(
        FaultyAccountTxCreatorArgs {
            tx_type: TransactionType::DeployAccount,
            scenario: INVALID,
            faulty_account: faulty_account_feature_contract,
            max_fee: Some(Fee(BALANCE)),
            ..Default::default()
        },
        &mut NonceManager::default(),
    );
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1355 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0J2wl1jGwwew4i0fS:-Nm0J2wl1jGwwew4i0fT:bdknxs) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1355)):*
> ```XML
>     let salt_manager = &mut SaltManager::default();
> 
>     // Negative flows.
> ```

define the default args in a variable and reuse (derive `Default` and `Clone` on the struct)



_Suggestion:_
```XML
// Negative flows.
let default_args = FaultyAccountTxCreatorArgs {
    tx_type,
    faulty_account,
    sender_address,
    ..Default::default()
};
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1367 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0IqhB2p6IoBKZ_-Ea:-Nm0IqhB2p6IoBKZ_-Eb:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1367)):*
> ```XML
>             contract_address_salt: salt_manager.next_salt(),
>             max_fee: None,
>         },
> ```





_Suggestion:_
```XML
        FaultyAccountTxCreatorArgs {
            scenario: INVALID,
            contract_address_salt: salt_manager.next_salt(),
            ..default_args.clone()
        },
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1384 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0JLnC2fbgTFIWTCaH:-Nm0JLnC2fbgTFIWTCaI:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1384)):*
> ```XML
>             contract_address_salt: salt_manager.next_salt(),
>             max_fee: None,
>         },
> ```





_Suggestion:_
```XML
        FaultyAccountTxCreatorArgs {
            scenario: CALL_CONTRACT,
            additional_data: Some(stark_felt!("0x1991")), /* Some address different than the
                                                           * address of faulty_account. */
            contract_address_salt: salt_manager.next_salt(),
            ..default_args.clone()
        },
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1434 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0JYMfCju_1yter9t3:-Nm0JYMfCju_1yter9t4:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1434)):*
> ```XML
>             contract_address_salt: salt_manager.next_salt(),
>             max_fee: None,
>         },
> ```





_Suggestion:_
```XML
        FaultyAccountTxCreatorArgs {
            scenario: VALID,
            contract_address_salt: salt_manager.next_salt(),
            ..default_args.clone()
        },
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1450 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0JgUoAX1_z7KYWbeP:-Nm0JgUoAX1_z7KYWbeQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1450)):*
> ```XML
>                 contract_address_salt: ContractAddressSalt::default(),
>                 max_fee: None,
>             },
> ```





_Suggestion:_
```XML
            FaultyAccountTxCreatorArgs {
                scenario: CALL_CONTRACT,
                additional_data: Some(*sender_address.0.key()),
                ..default_args
            },
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0GqKd0UN_xS-yUEAv:-Nm0Ko9I87Hab8Egd5EZ:b-27ziwf) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, should rebase... sorry
</blockquote></details>

Whatever it takes!

___
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-NlxBP_y2D48iTSX9SyQ:-Nm0QKqN32UVRlf2e8dB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/145b2adcac0e9d94552b6c2c41c79700213fd7e4/crates/blockifier/src/test_utils/initial_test_state.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rebase over [this](https://reviewable.io/reviews/starkware-libs/blockifier/1284) please
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0HsmK43q0CB-VBFCK:-Nm0QGNc7lFW1c8vp4Ac:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/test_utils/initial_test_state.rs#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need for a public wrapper to `fund_account`; just make `fund_account` public
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0HzSV2n01u1niHRO8:-Nm0QHYo5SOGaDJrXtjn:b-proyl) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/test_utils/initial_test_state.rs#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rebase over [this](https://reviewable.io/reviews/starkware-libs/blockifier/1284)? or use `FeeType::iter()`
</blockquote></details>

Irrelevant.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 511 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0IbghDjq2CysCcvuq:-Nm0SoD-3tyuwnQHKeBO:bs7wun7) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/account_transactions_test.rs#L511)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. Add `#[derive(Default)]` to the struct
2. make this change (unless the salt variable is needed below, in which case define and use it in the struct as well)
</blockquote></details>

Done.*
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1355 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0J2wl1jGwwew4i0fS:-Nm0WtN103wGQaYgeIO0:b-oy024t) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1355)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

define the default args in a variable and reuse (derive `Default` and `Clone` on the struct)
</blockquote></details>

That is not exactly what you suggested. The issue is that tx_type has no natural default value. 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1367 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0IqhB2p6IoBKZ_-Ea:-Nm0gvmi8IItWd8sun7D:bbe9wwv) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1367)):*
> ```XML
>             contract_address_salt: salt_manager.next_salt(),
>             max_fee: None,
>         },
> ```

Done. - No need to clone.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1384 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0JLnC2fbgTFIWTCaH:-Nm0gwA7BHe9c6jbSByz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1384)):*
> ```XML
>             contract_address_salt: salt_manager.next_salt(),
>             max_fee: None,
>         },
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1434 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0JYMfCju_1yter9t3:-Nm0gwmrD6ztIKPUFQlV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1434)):*
> ```XML
>             contract_address_salt: salt_manager.next_salt(),
>             max_fee: None,
>         },
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1450 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0JgUoAX1_z7KYWbeP:-Nm0gxIjD20TWL6HERWh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1450)):*
> ```XML
>                 contract_address_salt: ContractAddressSalt::default(),
>                 max_fee: None,
>             },
> ```

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 506 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm18LSM2fFi042t6AW0:-Nm1deVpA2fdxiFTBnYI:bs7wumb) ([raw file](https://github.com/starkware-libs/blockifier/blob/381241275f3bcdcecc82d1538b6f73f0f2224c90/crates/blockifier/src/transaction/account_transactions_test.rs#L506)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe make the default type `Invoke`, and just pass type explicitly? Seems cleaner
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 515 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm18UaX66Gylyovk4OO:-Nm2546y2pSiAQ7fVgZ8:b-gfjeuj) ([raw file](https://github.com/starkware-libs/blockifier/blob/381241275f3bcdcecc82d1538b6f73f0f2224c90/crates/blockifier/src/transaction/account_transactions_test.rs#L515)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, no... this is still not clean. please edit the `fund_account` function to accept a state to mutate, and pass `&mut state`
</blockquote></details>

Done.
Is this what you had in mind?
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 242 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm18q61EaJ_4rnM0-uR:-Nm1djRqB1y2JUDT3-m2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/381241275f3bcdcecc82d1538b6f73f0f2224c90/crates/blockifier/src/transaction/test_utils.rs#L242)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer implementing the actual standard trait unless you see a really good reason not to (we have, for example, default value of `ONE` for `TransactionVersion` in `InvokeTxArgs`)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1355 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm0J2wl1jGwwew4i0fS:-Nm1dmOQB0AwVXon1_yE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1cad07ef8584ff6b5b27c59803663e3568ff7860/crates/blockifier/src/transaction/transactions_test.rs#L1355)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

It's ok IMO to set a default. See above
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 515 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm18UaX66Gylyovk4OO:-Nm25caZ3O2jim0mm19T:bogsb27) ([raw file](https://github.com/starkware-libs/blockifier/blob/381241275f3bcdcecc82d1538b6f73f0f2224c90/crates/blockifier/src/transaction/account_transactions_test.rs#L515)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
Is this what you had in mind?
</blockquote></details>

yes, thanks
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 507 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm25LRP0eMwedTRt739:-Nm25LRP0eMwedTRt73A:b-151q81) ([raw file](https://github.com/starkware-libs/blockifier/blob/c9a8b321bab0698b9346b35419aa449a72be4b91/crates/blockifier/src/transaction/account_transactions_test.rs#L507)):*
> ```XML
>             class_hash: faulty_account_feature_contract.get_class_hash(),
>             max_fee: Fee(BALANCE),
>             ..FaultyAccountTxCreatorArgs::default()
> ```

We usually use `Default::default()`, non-blocking



_Code quote:_
```XML
FaultyAccountTxCreatorArgs
```

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-:-Nm25f7_Axk7v-DKKC-Y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 507 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1277#-Nm25LRP0eMwedTRt739:-Nm27IPZ8asBPkIQhRBW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c9a8b321bab0698b9346b35419aa449a72be4b91/crates/blockifier/src/transaction/account_transactions_test.rs#L507)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

We usually use `Default::default()`, non-blocking
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
