### PR TITLE
Collect the set of visited PCs in the block.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1233)

### CODE REVIEW

**Review by Yoni-Starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1233)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @elintul and @liorgold2)

___
*[`crates/blockifier/src/state/state_api.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-Nm6Fu06AG5iU8c9zEiD:-Nm6Fu06AG5iU8c9zEiE:ba5j3ol) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/state/state_api.rs#L111)):*
> ```XML
> 
>     /// Marks the given set of PC values as visited for the given class hash.
>     fn add_visited_pcs(&mut self, class_hash: ClassHash, pcs: &HashSet<usize>);
> ```

Non-blocking - I think we should put this functionality on a new struct. `BlockReasorces` or something like this.
We could put the rusty bouncer on it as well.

I don't think it should delay your progress. If you agree with the approach, just add a TODO and our teams will do it once we implement the bouncer

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1233)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @liorgold2 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBY-gZ-GMmCZUVeUcU:-NmBY-gZ-GMmCZUVeUcV:b-dtf3ws) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/execution/entry_point_execution.rs#L57)):*
> ```XML
>     context: &mut EntryPointExecutionContext,
> ) -> EntryPointExecutionResult<CallInfo> {
>     // Fetch the class hash from `call`.
> ```

Unnecessary, code is simple.



_Code quote:_
```XML
// Fetch the class hash from `call`.
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBY4_78O7dKVpNJVAT:-NmBY4_78O7dKVpNJVAU:bc64ese) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/execution/entry_point_execution.rs#L59)):*
> ```XML
>     // Fetch the class hash from `call`.
>     let class_hash = call.class_hash.ok_or(EntryPointExecutionError::InternalError(
>         "CallEntryPoint::class_hash must not be None when calling execute_entry_point_call.".into(),
> ```

To prevent false-positives when searching the code.



_Suggestion:_
```XML
`CallEntryPoint::class_hash` must not be None when calling `execute_entry_point_call`
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBYEaT24bs8AOV4Af1:-NmBYEaT24bs8AOV4Af2:b-z82sez) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/execution/entry_point_execution.rs#L94)):*
> ```XML
>         program_segment_size,
>     )?;
> ```

Consider moving PCs-handling into a small function; this one is getting long.
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBYJs6BAaeSbzFqu--:-NmBYJs6BAaeSbzFqu-0:by7qaht) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/execution/entry_point_execution.rs#L97)):*
> ```XML
>     // Collect the set PC values that were visited during the entry point execution.
>     let mut class_visited_pcs = HashSet::new();
>     vm.relocate_trace(&[1, 1 + program_segment_size])?;
> ```

Can you explain (and add a short comment)?



_Code quote:_
```XML
vm.relocate_trace(&[1, 1 + program_segment_size])?;
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBYYT_ClC3Q1GYgQ8h:-NmBYYT_ClC3Q1GYgQ8i:bllfiwq) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/execution/entry_point_execution.rs#L106)):*
> ```XML
>         }
>         let real_pc = pc - 1;
>         if real_pc < bytecode_length {
> ```

When won't it be the case?



_Code quote:_
```XML
if real_pc < bytecode_length
```
___
*[`crates/blockifier/src/execution/errors.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBYc93DY2JzPZn5Aab:-NmBYc93DY2JzPZn5Aac:b-v53drf) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/execution/errors.rs#L128)):*
> ```XML
>     #[error("Execution failed. Failure reason: {}.", format_panic_data(.error_data))]
>     ExecutionFailed { error_data: Vec<StarkFelt> },
>     #[error(transparent)]
> ```

Keep alphabetized.
___
*[`crates/blockifier/src/state/cached_state.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBYomH7cwGCU8vfHdm:-NmBYomH7cwGCU8vfHdn:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/state/cached_state.rs#L143)):*
> ```XML
>     }
> 
>     pub fn update_visited_pc_cache(&mut self, visited_pcs: &HashMap<ClassHash, HashSet<usize>>) {
> ```





_Suggestion:_
```XML
pcs
```

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1233)* status: all files reviewed, 11 unresolved discussions (waiting on @liorgold2)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBY4_78O7dKVpNJVAT:-NmBZK2n2JkZ_guRoVgb:b9jd9rx) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/execution/entry_point_execution.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

To prevent false-positives when searching the code.
</blockquote></details>

Or even behavioral phrasing, without variable names: `Class hash must not be None when executing an entry point.`.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBZEcA9jn8iB6avvCG:-NmBZEcA9jn8iB6avvCH:btsucfy) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/native_blockifier/src/transaction_executor.rs#L141)):*
> ```XML
>         }
> 
>         // Extract visited_pcs from block_context, and convert it to a python-friendly type.
> ```

The Python bit is clear from the context.



_Suggestion:_
```XML
// Extract visited PCs from block_context.
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBZW8k4d5LHQilOsJ7:-NmBZW8k4d5LHQilOsJ8:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/native_blockifier/src/transaction_executor.rs#L142)):*
> ```XML
> 
>         // Extract visited_pcs from block_context, and convert it to a python-friendly type.
>         let visited_pcs_vec = self
> ```





_Suggestion:_
```XML
visited_pcs
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBZ9Yz2XXMiKDd2OBk:-NmBZ9Yz2XXMiKDd2OBl:b1rfqh7) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/native_blockifier/src/transaction_executor.rs#L144)):*
> ```XML
>         let visited_pcs_vec = self
>             .state
>             .visited_pcs
> ```

Is this the reason `visited_pcs` is `pub`?



_Code quote:_
```XML
            .state
            .visited_pcs
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1233)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/state_api.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-Nm6Fu06AG5iU8c9zEiD:-NmBdR_69S-djMsW0DOB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/state/state_api.rs#L111)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Non-blocking - I think we should put this functionality on a new struct. `BlockReasorces` or something like this.
We could put the rusty bouncer on it as well.

I don't think it should delay your progress. If you agree with the approach, just add a TODO and our teams will do it once we implement the bouncer
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1233)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBY-gZ-GMmCZUVeUcU:-NmBg8utCMKLvwZgMBcv:b-6avclv) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/execution/entry_point_execution.rs#L57)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

WDYM?
Note that this must be done here since `call` is moved into `initialize_execution_context` and cannot be used after that call.
</blockquote></details>

I meant the comment isn't needed.
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBY4_78O7dKVpNJVAT:-NmBgET38G3ZfdOBkSAO:b-n5izel) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d4201eb51944d16d82b44b17b2f3bd8bec7429/crates/blockifier/src/execution/entry_point_execution.rs#L59)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Done.
What are you trying to achieve by this?
</blockquote></details>

Prevent false-positives when searching the code.
___
*[`crates/blockifier/src/execution/errors.rs` line 150 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBgbdJ78HThahbXMY_:-NmBgbdJ78HThahbXMYa:b8eka3s) ([raw file](https://github.com/starkware-libs/blockifier/blob/39db8434bc056f7f20b75da50123e79e987861bb/crates/blockifier/src/execution/errors.rs#L150)):*
> ```XML
>     },
>     #[error("Internal error: {0}")]
>     InternalError(String),
> ```

This too?



_Code quote:_
```XML
    #[error("Internal error: {0}")]
    InternalError(String),
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1233)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/blockifier/src/execution/errors.rs` line 150 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-NmBgbdJ78HThahbXMY_:-NmBvUeXEratn3uQxFSZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/39db8434bc056f7f20b75da50123e79e987861bb/crates/blockifier/src/execution/errors.rs#L150)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This too?
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1233#-:-NmBwL3WC2N9mTM2OyWY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
