### PR TITLE
test: test feature contract files structure and consistency with rust

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1866)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Does this still need a review? or is it superseded by that stack PR you made?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1866#-:-NyJAu0c1sGiAY1-Fe1m:b-2u4vv9)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @OriStarkware and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
still needs review, as do the next 7 PRs in the stack

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1866#-:-NyJlK-D6xrpL9LMEWlW:b-jgqgsf)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @OriStarkware and @Yoni-Starkware)

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1866#-:-NyOMXnuAsu79pGJrmUr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1866)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware and @Yoni-Starkware)

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1866#-:-NyPB82rAKouscoYfz3B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware and @Yoni-Starkware)

**Pull request merged**
