### PR TITLE
Added test_calculate_l1_gas_by_cairo_usage

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/383)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware +reviewer:@noaov1 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/383#-:-NS2kMmQAux1VlKKEMIr:bd7uazw)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/383)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @noaov1)

___
*[`crates/blockifier/Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2qLuk4nMSIuqDCmXO:-NS2qLuk4nMSIuqDCmXP:b-weiwxl) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/Cargo.toml#L23)):*
> ```TOML
> once_cell = { version = "1.16.0" }
> papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", rev = "14a7f0f" }
> rstest = { version = "0.17.0" }
> ```

I think it would be better to just call setup functions for now (fixtures are only used once). If this test starts getting larger and we start duplicating setup then let's think about adding dependencies. WDYT?
___
*[`crates/blockifier/src/fee/fee_test.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2p5GP9vHg-F3SUlH4:-NS2p5GQ9zjpF_aDUM4F:b-n8wqfb) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/src/fee/fee_test.rs#L4)):*
> ```XML
> use std::panic;
> 
> use ::rstest::{fixture, rstest};
> ```

why the leading `::`?



_Code quote:_
```XML
::
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2pUR9DPHEUSzBI6KM:-NS2pUR9DPHEUSzBI6KN:b4o9tdd) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/src/fee/fee_test.rs#L35)):*
> ```XML
>     cairo_resource_fee_weights.insert(String::from("output_builtin"), 1);
>     cairo_resource_fee_weights.insert(String::from("ec_op_builtin"), 1);
>     block_context.cairo_resource_fee_weights = cairo_resource_fee_weights;
> ```

I prefer this, WDYT?



_Suggestion:_
```XML
    let mut block_context = BlockContext::create_for_testing();
    block_context.cairo_resource_fee_weights = HashMap::from([
        (String::from("n_steps"), 1),
        (String::from("pedersen_builtin"), 1),
        (String::from("range_check_builtin"), 1),
        (String::from("ecdsa_builtin"), 1),
        (String::from("bitwise_builtin"), 1),
        (String::from("poseidon_builtin"), 1),
        (String::from("output_builtin"), 1),
        (String::from("ec_op_builtin"), 1),
    ]);
    block_context
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2rOXwAAIlIEhqXD4x:-NS2rOXwAAIlIEhqXD4y:b-dn002z) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/src/fee/fee_test.rs#L40)):*
> ```XML
> 
> #[fixture]
> fn cairo_resource_usage() -> ResourcesMapping {
> ```

where is output_builtin and ec_op_builtin in `ResourcesMapping`? They shouldn't be there?
___
*[`crates/blockifier/src/fee/fee_test.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2q7Sy6nKmN09fyslW:-NS2q7Sy6nKmN09fyslX:bb7od0r) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/src/fee/fee_test.rs#L45)):*
> ```XML
>     cairo_resource_usg.0.insert(String::from("pedersen_builtin"), 10);
>     cairo_resource_usg.0.insert(String::from("range_check_builtin"), 24);
>     cairo_resource_usg.0.insert(String::from("ecdsa_builtin"), 1);
> ```

same



_Suggestion:_
```XML
    ResourcesMapping(HashMap::from([ ... ]))
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2rki62Rr77p9LrwYn:-NS2rki62Rr77p9LrwYo:b-kmraqn) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/src/fee/fee_test.rs#L78)):*
> ```XML
>         })
>         .err()
>         .and_then(|a| a.downcast_ref::<&str>().map(|s| { s == expected_panic_msg })),
> ```

`a` in this context is an `Error` object...? Is this the rusty way of checking a panic message?



_Code quote:_
```XML
|a| a.downcast_ref::<&str>().map(|s| { s == expected_panic_msg })
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/383)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @noaov1)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/383)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2qLuk4nMSIuqDCmXO:-NS6xRit-ZAlgXSBv6p0:bg5gyjp) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/Cargo.toml#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it would be better to just call setup functions for now (fixtures are only used once). If this test starts getting larger and we start duplicating setup then let's think about adding dependencies. WDYT?
</blockquote></details>

the test `test_execute_fee_transfer` will probably also be added to this file, and it will probable also use the `block_context` fixture
___
*[`crates/blockifier/src/fee/fee_test.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2p5GP9vHg-F3SUlH4:-NS6y4FsCs5FhLOyO7fy:boqypc8) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/src/fee/fee_test.rs#L4)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why the leading `::`?
</blockquote></details>

I saw in a comment that it's good practice to import external crates this way. but I didn't see it anywhere else so deleting.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2pUR9DPHEUSzBI6KM:-NS7-o2wE-d21Hg2SoJj:bqe8amv) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/src/fee/fee_test.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer this, WDYT?
</blockquote></details>

Looks better, Done
___
*[`crates/blockifier/src/fee/fee_test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2rOXwAAIlIEhqXD4x:-NS71RZ55E0r9S6Jvb7p:brae5wg) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/src/fee/fee_test.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is output_builtin and ec_op_builtin in `ResourcesMapping`? They shouldn't be there?
</blockquote></details>

I don't think so - I think only builtins with use > 0 appear here (this is how it's in python too:
https://github.com/starkware-industries/starkware/blob/a6fdf799c9aacd81b784e340f29ea8c2bae0f024/src/starkware/starknet/business_logic/transaction/fee_test.py#L63
)
___
*[`crates/blockifier/src/fee/fee_test.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2q7Sy6nKmN09fyslW:-NS72pMhE-wA1UGJaf7r:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/src/fee/fee_test.rs#L45)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same
</blockquote></details>

Done
___
*[`crates/blockifier/src/fee/fee_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/383#-NS2rki62Rr77p9LrwYn:-NS73G078tZHZBqfif5E:b-1rubi8) ([raw file](https://github.com/starkware-libs/blockifier/blob/18cac7d624df851f9eedb431d2bc3de3fc673fb0/crates/blockifier/src/fee/fee_test.rs#L78)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`a` in this context is an `Error` object...? Is this the rusty way of checking a panic message?
</blockquote></details>

a is the `String` from the `Err` returned by `catch_unwind_silent`, I think.
this ugly assert is the rusty way to assert a panic with a certain message was thrown, I think.
The following comment has a link to rust tests with something almost identical (that's where I got this from, should have sent this link earlier)
https://stackoverflow.com/questions/26469715/how-do-i-write-a-rust-unit-test-that-ensures-that-a-panic-has-occurred#:~:text=If%20you%20want,use%20this%20technique.

I changed a -> panic_str, hopefully more readable

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/383)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/383)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request closed without merging**
