### PR TITLE
Use fee token address in count actual state changes for fee charge.

### PR DESCRIPTION
**Pull request by ArniStarkware**
Also, disregard the sequencer in this computation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/749)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/749#-N_YO6Gf0JaMkdoB3GyJ:-N_YO6Gf0JaMkdoB3GyK:bz9rbdx) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ce185c19c8182660dd5c9ce9ba95fed51906278/crates/blockifier/src/transaction/transaction_utils.rs#L36)):*
> ```XML
>     state: &mut TransactionalState<'_, S>,
>     l1_handler_payload_size: Option<usize>,
>     block_context: &BlockContext,
> ```

We don't need the whole BlockContext here.



_Suggestion:_
```XML
    fee_token_address: ContractAddress,
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/749)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/749#-N_YP6rSE0oqHLE9_9Qs:-N_YP6rTAvKOBk-w7lpu:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ce185c19c8182660dd5c9ce9ba95fed51906278/crates/blockifier/src/state/cached_state_test.rs#L297)):*
> ```XML
>         StateChanges {
>             // 1 for storage update + 1 for sender balance update + 1 for sequncer balance update.
>             n_storage_updates: 3,
> ```





_Suggestion:_
```XML
    let state_changes = state
        .count_actual_state_changes_for_fee_charge(
            block_context.fee_token_address,
            Some(contract_address),
        )
        .unwrap();

    assert_eq!(
        state_changes,
        StateChanges {
            // 1 for storage update + 1 for sender balance update.
            n_storage_updates: 2,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 925 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/749#-N_YPgcFEkAJfcCgpzYC:-N_YPgcGBygOejFlX9IO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ce185c19c8182660dd5c9ce9ba95fed51906278/crates/blockifier/src/transaction/transactions_test.rs#L925)):*
> ```XML
>         entry_point_selector.0,                   // EP selector.
>         stark_felt!(3_u8),                        // Calldata length.
>         *block_context.sequencer_address.0.key(), // Calldata: recipient.
> ```





_Suggestion:_
```XML
    // A tx that changes the account and some other balance in execute.
    let entry_point_selector = selector_from_name(constants::TRANSFER_ENTRY_POINT_NAME);
    let execute_calldata = calldata![
        *block_context.fee_token_address.0.key(), // Contract address.
        entry_point_selector.0,                   // EP selector.
        stark_felt!(3_u8),                        // Calldata length.
        some other address, // Calldata: recipient.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 943 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/749#-N_YQ05zEV3MHw7Blb6V:-N_YQ05zEV3MHw7Blb6W:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ce185c19c8182660dd5c9ce9ba95fed51906278/crates/blockifier/src/transaction/transactions_test.rs#L943)):*
> ```XML
> 
>     let tx_execution_info = account_tx.execute(state, block_context).unwrap();
>     // For the balance update of the sender and the sequencer.
> ```





_Suggestion:_
```XML
 of the sender and the recipient.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/749)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/749#-N_YP6rSE0oqHLE9_9Qs:-N_YQn-wBSLNg5mR8Dsb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ce185c19c8182660dd5c9ce9ba95fed51906278/crates/blockifier/src/state/cached_state_test.rs#L297)):*
> ```XML
>         StateChanges {
>             // 1 for storage update + 1 for sender balance update + 1 for sequncer balance update.
>             n_storage_updates: 3,
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 925 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/749#-N_YPgcFEkAJfcCgpzYC:-N_YSd25Ex5LRTD2k8SI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ce185c19c8182660dd5c9ce9ba95fed51906278/crates/blockifier/src/transaction/transactions_test.rs#L925)):*
> ```XML
>         entry_point_selector.0,                   // EP selector.
>         stark_felt!(3_u8),                        // Calldata length.
>         *block_context.sequencer_address.0.key(), // Calldata: recipient.
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 943 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/749#-N_YQ05zEV3MHw7Blb6V:-N_YRTXe6WFQ4dWYGQ-3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ce185c19c8182660dd5c9ce9ba95fed51906278/crates/blockifier/src/transaction/transactions_test.rs#L943)):*
> ```XML
> 
>     let tx_execution_info = account_tx.execute(state, block_context).unwrap();
>     // For the balance update of the sender and the sequencer.
> ```

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/749#-:-N_YcIW93rNwC5ueCeKZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
