### PR TITLE
Wrap declare tx and contract class with struct.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442)

### CODE REVIEW

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NUW79BQ-LkOSgTH72YT:-NUW79BRBJvJemHPdU3f:b-emxslq) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fc17a5785bbbd51ccc72a0409869947d000e3bb/crates/blockifier/src/transaction/transactions.rs#L95)):*
> ```XML
>             Err(StateError::UndeclaredClassHash(_)) => {
>                 // Class is undeclared; declare it.
>                 state.set_contract_class(&class_hash, self.contract_class.clone())?;
> ```

This clone will be fine once `contract_class` is an `Arc`, done in this [PR](https://reviewable.io/reviews/starkware-libs/blockifier/441#-).



_Code quote:_
```XML
clone()
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU_O2dU69mCZL7VwRIt:-NU_O2dU69mCZL7VwRIu:b561056) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fc17a5785bbbd51ccc72a0409869947d000e3bb/crates/blockifier/src/transaction/account_transaction.rs#L82)):*
> ```XML
>     fn get_account_transaction_context(&self) -> AccountTransactionContext {
>         match self {
>             Self::Declare(tx) => AccountTransactionContext {
> ```

`Self::Declare(tx)` -> `Self::Declare(declare)`
`let tx = declare.tx`
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU_ODe0CD6-dSRcCHxN:-NU_ODe0CD6-dSRcCHxO:b-sbgbgz) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fc17a5785bbbd51ccc72a0409869947d000e3bb/crates/blockifier/src/transaction/account_transaction.rs#L278)):*
> ```XML
>         let mut execution_resources = ExecutionResources::default();
>         match self {
>             Self::Declare(ref tx) => {
> ```

`ref tx`: do we still need `ref`?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU_NYGFA9Y9KW-n5tHi:-NU_NYGFA9Y9KW-n5tHj:brpl4b) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fc17a5785bbbd51ccc72a0409869947d000e3bb/crates/blockifier/src/transaction/transactions.rs#L78)):*
> ```XML
> #[derive(Debug)]
> pub struct DeclareTransaction {
>     pub starknet_api_tx: StarknetApiDeclareTransaction,
> ```

`tx: StarknetApiDeclareTransaction` -> `starknet_api::transaction::DeclareTransaction`.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU_ODe0CD6-dSRcCHxN:-NU_W6Yf4KJUDHYq7kb3:b-33jcv2) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fc17a5785bbbd51ccc72a0409869947d000e3bb/crates/blockifier/src/transaction/account_transaction.rs#L278)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`ref tx`: do we still need `ref`?
</blockquote></details>

Yes, because otherwise `self` would be partially moved because of that binding to tx, and `self.validate_tx` would be trying to call on a partially moved variable.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @alonh5, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU_ODe0CD6-dSRcCHxN:-NU_Z8Gi6R6lkAwe35g3:b4fql9v) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fc17a5785bbbd51ccc72a0409869947d000e3bb/crates/blockifier/src/transaction/account_transaction.rs#L278)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yes, because otherwise `self` would be partially moved because of that binding to tx, and `self.validate_tx` would be trying to call on a partially moved variable.
</blockquote></details>

I think we can use ergonomics here and do `match &self` instead of the `ref`s (I think it wasn't possible previously before due to the mem::take, but I can’t remember why)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 418 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU__7M5-JfHsIWmZu1y:-NU__7M5-JfHsIWmZu1z:b-ye60yo) ([raw file](https://github.com/starkware-libs/blockifier/blob/de3cbe68c7e5a2d6fb8c6910f677b67dc48b5b87/crates/blockifier/src/transaction/transactions_test.rs#L418)):*
> ```XML
>     let contract_class = get_contract_class(TEST_EMPTY_CONTRACT_PATH);
>     let account_tx = AccountTransaction::Declare(DeclareTransaction {
>         tx: starknet_api::transaction::DeclareTransaction::V1(declare_tx),
> ```

We think we need to settle on a convention with these since we'll see this a lot of them during the transition to cairo1, and it might be a bit too long :(

Maybe:
```rust
use starknet_api::transaction::DeclareTransaction as DeclareTransactionApi // or `as StarknetDeclareTransaction`
```
Alternatives seem ambiguous: 
```rust
use starknet_api::transaction::DeclareTransaction // Clashes with our own
use starknet_api::transaction::DeclareTransaction::V1 // Clashes with V1 for other structs that might appear in the module
```



_Code quote:_
```XML
starknet_api::transaction::DeclareTransaction::
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU_ODe0CD6-dSRcCHxN:-NU_dCwW65s64RB9OkcW:bhbys4p) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fc17a5785bbbd51ccc72a0409869947d000e3bb/crates/blockifier/src/transaction/account_transaction.rs#L278)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think we can use ergonomics here and do `match &self` instead of the `ref`s (I think it wasn't possible previously before due to the mem::take, but I can’t remember why)
</blockquote></details>

You're right. Changed it.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 418 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU__7M5-JfHsIWmZu1y:-NU_dPtZ6p6fLQCf93R0:b-c7rneg) ([raw file](https://github.com/starkware-libs/blockifier/blob/de3cbe68c7e5a2d6fb8c6910f677b67dc48b5b87/crates/blockifier/src/transaction/transactions_test.rs#L418)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

We think we need to settle on a convention with these since we'll see this a lot of them during the transition to cairo1, and it might be a bit too long :(

Maybe:
```rust
use starknet_api::transaction::DeclareTransaction as DeclareTransactionApi // or `as StarknetDeclareTransaction`
```
Alternatives seem ambiguous: 
```rust
use starknet_api::transaction::DeclareTransaction // Clashes with our own
use starknet_api::transaction::DeclareTransaction::V1 // Clashes with V1 for other structs that might appear in the module
```
</blockquote></details>

I'm okay with either. Elin asked in a comment above to use the full import path like this.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @alonh5, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU_g1nd2K3JJRB5mAN1:-NU_g1nd2K3JJRB5mAN2:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/de3cbe68c7e5a2d6fb8c6910f677b67dc48b5b87/crates/blockifier/src/transaction/account_transaction.rs#L96)):*
> ```XML
>                             TransactionVersion(StarkFelt::from(2))
>                         }
>                     },
> ```





_Suggestion:_
```XML
                    version: declare.tx.version(),
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU_g1nd2K3JJRB5mAN1:-NU_lNPN5QJ2vBJq4_fx:bmijt8f) ([raw file](https://github.com/starkware-libs/blockifier/blob/de3cbe68c7e5a2d6fb8c6910f677b67dc48b5b87/crates/blockifier/src/transaction/account_transaction.rs#L96)):*
> ```XML
>                             TransactionVersion(StarkFelt::from(2))
>                         }
>                     },
> ```

Cool thanks. Done.

**Review by giladchase — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442#-:-NU_tQiO-z1MQsvlQjsG:bnfp4nl)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU_O2dU69mCZL7VwRIt:-NUa2wkN4TJ9S1Fu2uIE:b-dd87cc) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fc17a5785bbbd51ccc72a0409869947d000e3bb/crates/blockifier/src/transaction/account_transaction.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`Self::Declare(tx)` -> `Self::Declare(declare)`
`let tx = declare.tx`
</blockquote></details>

Perhaps `Self::Declare(tx)` for consistency with other `match`es in this file; sorry.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/442#-NU_O2dU69mCZL7VwRIt:-NUa5oe-3d5PWucQA2JF:bygtfeh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fc17a5785bbbd51ccc72a0409869947d000e3bb/crates/blockifier/src/transaction/account_transaction.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps `Self::Declare(tx)` for consistency with other `match`es in this file; sorry.
</blockquote></details>

All good. Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/442#-:-NUa6vqz5W209cdgHOGB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Pull request merged**
