### PR TITLE
Run cargo update and fix errors

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/308)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/308)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/308#-NPIVxCd4UzZEx4PjFzP:-NPIVxCd4UzZEx4PjFzQ:b-bnf6nz) (no related file):*
I think the problem now is papyrus storage takes a [different starknet-api version](https://github.com/starkware-libs/papyrus/blob/main/crates/papyrus_storage/Cargo.toml#L22)... papyrus uses `rev = "9a1fca8"` and the blockifier has `rev = "0a11ad3"`

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/308)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/308#-NPIVxCd4UzZEx4PjFzP:-NPIbTuwEwmlISU5I7nu:b-p7mk7u) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think the problem now is papyrus storage takes a [different starknet-api version](https://github.com/starkware-libs/papyrus/blob/main/crates/papyrus_storage/Cargo.toml#L22)... papyrus uses `rev = "9a1fca8"` and the blockifier has `rev = "0a11ad3"`
</blockquote></details>

fixed starknet-api version to `9a1fca8`

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/308)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 326 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/308#-NPIy-TI-XMcp42s5OjK:-NPIy-TI-XMcp42s5OjL:b-o3udx) ([raw file](https://github.com/starkware-libs/blockifier/blob/78f620d4b891f8ee6d84750554b52cf63a5e4919/crates/blockifier/src/execution/entry_point_test.rs#L326)):*
> ```XML
> 
>     run_security_test(
>         "Custom Hint Error: Found a memory gap when calling get_continuous_range",
> ```

this is the new error raised, I see this is from a commit in LC's VM from four days ago.
is this actually the expected error here?
the function being called is
```
@external
func test_bad_syscall_request_arg_type{syscall_ptr: felt*}() {
    assert syscall_ptr[0] = CALL_CONTRACT_SELECTOR;
    // Contract address.
    assert syscall_ptr[1] = 0;
    // Function selector.
    assert syscall_ptr[2] = 0;
    // Calldata size.
    assert syscall_ptr[3] = 1;
    // Calldata - should be a pointer, but we are passing a felt.
    assert syscall_ptr[4] = 0;
    %{ syscall_handler.call_contract(segments=segments, syscall_ptr=ids.syscall_ptr) %}
    return ();
}
```



_Code quote:_
```XML
Custom Hint Error: Found a memory gap when calling get_continuous_range
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/308)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/308#-NPIyaod3qb3rx9PXwdU:-NPIyaod3qb3rx9PXwdV:bb5gkg6) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cc71cc28f9d31d81fd4b454545d634d335d4d11/crates/blockifier/Cargo.toml#L25)):*
> ```TOML
> serde_json = { version = "1.0.81", features = ["arbitrary_precision"] }
> sha3 = { version = "0.10.6" }
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "9a1fca8", features = [
> ```

@giladchase was this the idea? without this we have conflicting revision hashes between here and papyrus



_Code quote:_
```TOML
9a1fca8
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/308)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 326 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/308#-NPIy-TI-XMcp42s5OjK:-NPLQ8ScBh5Du-TIJzyo:b-quv5dz) ([raw file](https://github.com/starkware-libs/blockifier/blob/78f620d4b891f8ee6d84750554b52cf63a5e4919/crates/blockifier/src/execution/entry_point_test.rs#L326)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is the new error raised, I see this is from a commit in LC's VM from four days ago.
is this actually the expected error here?
the function being called is
```
@external
func test_bad_syscall_request_arg_type{syscall_ptr: felt*}() {
    assert syscall_ptr[0] = CALL_CONTRACT_SELECTOR;
    // Contract address.
    assert syscall_ptr[1] = 0;
    // Function selector.
    assert syscall_ptr[2] = 0;
    // Calldata size.
    assert syscall_ptr[3] = 1;
    // Calldata - should be a pointer, but we are passing a felt.
    assert syscall_ptr[4] = 0;
    %{ syscall_handler.call_contract(segments=segments, syscall_ptr=ids.syscall_ptr) %}
    return ();
}
```
</blockquote></details>

@alonh5, can you PTAL?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/308)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 326 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/308#-NPIy-TI-XMcp42s5OjK:-NPMoMix03Gw9QQH5Wbv:bsxti92) ([raw file](https://github.com/starkware-libs/blockifier/blob/78f620d4b891f8ee6d84750554b52cf63a5e4919/crates/blockifier/src/execution/entry_point_test.rs#L326)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@alonh5, can you PTAL?
</blockquote></details>

It looks like they simplified how they read memory (PR: https://github.com/lambdaclass/cairo-rs/pull/852/files#diff-f9eb247281a8f35a2e92707ac46de9e2133f3da1414d40a53194b3d15049d665), so we get a later different error. We should ask them why they allow pointers to be `MaybeRelocatable` and don't require them to be `Relocatable` (in `get_continuous_range`, for example). I'll ask them.

If everything else is good, I think we can merge this in the meantime.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/308)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/Cargo.toml` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/308#-NPIyaod3qb3rx9PXwdU:-NPNAeGACveACHTmPzCn:b-85masu) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cc71cc28f9d31d81fd4b454545d634d335d4d11/crates/blockifier/Cargo.toml#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@giladchase was this the idea? without this we have conflicting revision hashes between here and papyrus
</blockquote></details>

Exactly, it has to match the one that papyrus_storage has.

**Pull request merged**
