### PR TITLE
Aa/data gas prices in block context3

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1343)

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1343)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMFpe11Lk_zfkUH2Q0:-NoMFpe11Lk_zfkUH2Q1:b-r29z0s) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L26)):*
> ```XML
>         .expect("`ResourcesMapping` does not have the key `l1_gas_usage`.");
> 
>     let l1_gas_usage_data = vm_resource_usage.remove(constants::DATA_GAS_USAGE).unwrap_or(0);
> ```

Add a comment explaining what is going on here.
Add a TODO to solve this issue (The issue is this field does not appear in some instances of `ResourcesMapping`).
Please open a PR to solve this issue.



_Suggestion:_
```XML
    // Returns the default value 0 for l1_gas_usage_data if it does not appear in resources.
    // TODO(Aner, 21/1/2024): Make sure the value l1_gas_usage_data always appears in resources.
    let l1_gas_usage_data = vm_resource_usage.remove(constants::DATA_GAS_USAGE).unwrap_or(0);
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMGrWH2rGjSqLOrLIG:-NoMGrWH2rGjSqLOrLIH:b-qgdq1n) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L67)):*
> ```XML
>     let total_l1_gas_usage = l1_gas_usage as f64 + l1_gas_by_vm_usage;
> 
>     Ok([total_l1_gas_usage.ceil() as u128, total_l1_gas_usage_data as u128])
> ```

Document this function.
Have the return value as a tuple.



_Suggestion:_
```XML
/// Returns the l1 gas usage and data gas usage.
pub fn calculate_tx_l1_gas_usages(
    resources: &ResourcesMapping,
    block_context: &BlockContext,
) -> TransactionFeeResult<(u128, u128)> {
    let (l1_gas_usage, l1_data_gas_usage, vm_resources) =
        extract_l1_gas_and_vm_usage(resources);
    let l1_gas_by_vm_usage = calculate_l1_gas_by_vm_usage(block_context, &vm_resources)?;
    let total_l1_gas_usage = l1_gas_usage as f64 + l1_gas_by_vm_usage;

    Ok((total_l1_gas_usage.ceil() as u128, l1_data_gas_usage as u128))
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMHc-43LTQH5m2jya2:-NoMHc-52jnMA54pgt9Q:b-76k19i) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L67)):*
> ```XML
>     let total_l1_gas_usage = l1_gas_usage as f64 + l1_gas_by_vm_usage;
> 
>     Ok([total_l1_gas_usage.ceil() as u128, total_l1_gas_usage_data as u128])
> ```

is the `as u128` needed?



_Suggestion:_
```XML
total_l1_gas_usage_data])
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMHwjmBB9PC9pac5mT:-NoMHwjmBB9PC9pac5mU:bw2ddhf) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L80)):*
> ```XML
>         true => block_context.gas_prices.get_data_gas_price_by_fee_type(fee_type),
>         false => gas_price,
>     };
> ```

There is an issue here.

The name of the variable `data_gas_price` does not match the value it stores.
Maybe: 



_Suggestion:_
```XML
    // If we use KZG, we use 'data gas' to pay for data availability of state diff changes. Otherwise, we use 'gas' for the old data availability scheme.
        let gas_price_for_da_segment = match block_context.use_kzg_da {
        true => block_context.gas_prices.get_data_gas_price_by_fee_type(fee_type),
        false => gas_price,
    };
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/fee/fee_utils.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMGrWH2rGjSqLOrLIG:-NoMNeJpDAZszIkPXKOK:bwkh2t5) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L67)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Document this function.
Have the return value as a tuple.
</blockquote></details>

About the return type. You can wait with that - until I finish the review of the other tests.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1343)* status: 2 of 13 files reviewed, 4 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMOfW9CAB1NUUlq7nQ:-NoMOfW9CAB1NUUlq7nR:b-co4rcc) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_checks.rs#L77)):*
> ```XML
>                         0,
>                         &FeeType::Strk,
>                     ),
> ```

This zero is odd but fine.

If the tx is reverted, there will be no DA changes.



_Code quote:_
```XML
                    AccountTransactionContext::Current(context) => get_fee_by_l1_gas_usage(
                        block_context,
                        context.l1_resource_bounds()?.max_amount.into(),
                        0,
                        &FeeType::Strk,
                    ),
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1343)* status: 2 of 13 files reviewed, 5 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1658 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMgt8V8n6znNbpuJVY:-NoMgt8V8n6znNbpuJVZ:b-tfkfnh) ([raw file](https://github.com/starkware-libs/blockifier/blob/41fe8d365faf3b6690e736b6d64bdfbd8ce59069/crates/blockifier/src/transaction/transactions_test.rs#L1658)):*
> ```XML
>         (RANGE_CHECK_BUILTIN_NAME.to_string(), 23),
>         (abi_constants::GAS_USAGE.to_string(), 16023),
>         (abi_constants::DATA_GAS_USAGE.to_string(), 1652),
> ```

bad name...



_Code quote:_
```XML
DATA_GAS_USAGE
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1343)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMOfW9CAB1NUUlq7nQ:-NoQqbDF1hBEUTFRJ9MY:b58bi31) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_checks.rs#L77)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This zero is odd but fine.

If the tx is reverted, there will be no DA changes.
</blockquote></details>

This should be changed to be 0/other according to the flag, but I need your help on this change.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMFpe11Lk_zfkUH2Q0:-NoQp8sv1X9B8vNYYP3Z:b-4gxcnb) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L26)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add a comment explaining what is going on here.
Add a TODO to solve this issue (The issue is this field does not appear in some instances of `ResourcesMapping`).
Please open a PR to solve this issue.
</blockquote></details>

Is this still relevant?
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMHc-43LTQH5m2jya2:-NoQqE_mAd7HGceDcjIb:b-ox0x1i) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L67)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

is the `as u128` needed?
</blockquote></details>

It has to be done somewhere; here seems best for consistency.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMGrWH2rGjSqLOrLIG:-NoQrdS_E8LbOqVtFsFn:b24q6vu) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L67)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

About the return type. You can wait with that - until I finish the review of the other tests.
</blockquote></details>

Waiting, but why is tuple preferable?
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMHwjmBB9PC9pac5mT:-NoQqRNb26Pd5eAbDR5z:b-a2ujfl) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L80)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

There is an issue here.

The name of the variable `data_gas_price` does not match the value it stores.
Maybe:
</blockquote></details>

Changed.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1658 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMgt8V8n6znNbpuJVY:-NoQqXDzDygMYeB6hJaa:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/41fe8d365faf3b6690e736b6d64bdfbd8ce59069/crates/blockifier/src/transaction/transactions_test.rs#L1658)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

bad name...
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/fee/fee_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMFpe11Lk_zfkUH2Q0:-NoRIWEj9tcds9MweUJb:b-pf048k) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L26)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Is this still relevant?
</blockquote></details>

Yes.
The TODO is about replacing the `unwarp_or` with an `expect` (By making sure the value always appears).

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1343)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMGrWH2rGjSqLOrLIG:-NoRJLg5E7O0By_yNZI3:b-6peeth) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L67)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Waiting, but why is tuple preferable?
</blockquote></details>

1. note the request to rename the function.
`calculate_tx_l1_gas_usage` -> `calculate_tx_l1_gas_usages`.

2. About the return type - see the discussions below.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 857 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoRK3_D6QXvJ8f7T5fr:-NoRK3_D6QXvJ8f7T5fs:b-3sz9xy) ([raw file](https://github.com/starkware-libs/blockifier/blob/44031a666ace15bbd7c24fff1e9a06aab6800ae2/crates/blockifier/src/transaction/account_transactions_test.rs#L857)):*
> ```XML
>             .unwrap()
>             .iter()
>             .sum();
> ```

Is the sum still needed? Shouldn't the whole value be in the first variable?
This comment is connected to the fact the return type should be a tuple.

X2.



_Suggestion:_
```XML
    let [gas_used1, _blob_gas_used1] =
        calculate_tx_l1_gas_usage(&tx_execution_info1.actual_resources, &block_context)
            .unwrap();
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 113 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoRKMbfEFMq9_nInnzd:-NoRKMbfEFMq9_nInnze:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/44031a666ace15bbd7c24fff1e9a06aab6800ae2/crates/blockifier/src/transaction/execution_flavors_test.rs#L113)):*
> ```XML
>             .sum::<u128>(),
>         expected_actual_gas.into()
>     );
> ```





_Suggestion:_
```XML
    let [gas_used, _blob_gas_used] = calculate_tx_l1_gas_usage(&tx_execution_info.actual_resources, block_context)
            .unwrap();
    assert_eq!(
        gas_used1,
        expected_actual_gas.into()
    );
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 206 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoRKgXv2wsd7e-IqqkP:-NoRKgXwCWyduQd5taHz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/44031a666ace15bbd7c24fff1e9a06aab6800ae2/crates/blockifier/src/transaction/objects.rs#L206)):*
> ```XML
> 
>     #[cfg(test)]
>     pub fn gas_usage_data(&self) -> usize {
> ```





_Suggestion:_
```XML
blob_gas_usage
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1343)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMFpe11Lk_zfkUH2Q0:-NoRyzVY5HQYtWCCF0ik:byvcf8s) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L26)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Yes.
The TODO is about replacing the `unwarp_or` with an `expect` (By making sure the value always appears).
</blockquote></details>

But why does blob_gas have to appear in the case where the flag is False?
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoMGrWH2rGjSqLOrLIG:-NoRsE566I6oOtTJcO4Q:bgif92i) ([raw file](https://github.com/starkware-libs/blockifier/blob/ded541947968b88a93f76fe674c48a50002ea5d7/crates/blockifier/src/fee/fee_utils.rs#L67)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

1. note the request to rename the function.
`calculate_tx_l1_gas_usage` -> `calculate_tx_l1_gas_usages`.

2. About the return type - see the discussions below.
</blockquote></details>

Regarding 2, your suggestion below can be done with a slice as well. The reason to use a tuple would seem to be if you want/expect `l1_gas_usage` and `l1_blob_gas_usage` to be of different types (now or in the future).
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 857 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoRK3_D6QXvJ8f7T5fr:-NoRuHa33jjdXZrWeiBI:b-3svb0) ([raw file](https://github.com/starkware-libs/blockifier/blob/44031a666ace15bbd7c24fff1e9a06aab6800ae2/crates/blockifier/src/transaction/account_transactions_test.rs#L857)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is the sum still needed? Shouldn't the whole value be in the first variable?
This comment is connected to the fact the return type should be a tuple.

X2.
</blockquote></details>

Done. I guess we should also add asserts for`blob_gas`?
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 113 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoRKMbfEFMq9_nInnzd:-NoRxQnKExsQCSByzN-T:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/44031a666ace15bbd7c24fff1e9a06aab6800ae2/crates/blockifier/src/transaction/execution_flavors_test.rs#L113)):*
> ```XML
>             .sum::<u128>(),
>         expected_actual_gas.into()
>     );
> ```

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 206 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1343#-NoRKgXv2wsd7e-IqqkP:-NoRrhi-E36JC2Kvn3wZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/44031a666ace15bbd7c24fff1e9a06aab6800ae2/crates/blockifier/src/transaction/objects.rs#L206)):*
> ```XML
> 
>     #[cfg(test)]
>     pub fn gas_usage_data(&self) -> usize {
> ```

Done.

**Pull request closed without merging**
