### PR TITLE
refactor(execution): add messages info to ExecutionSummary

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1666)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1666)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-NsvyY9e6DFnhbE8TNTw:-NsvyY9e6DFnhbE8TNTx:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad2c8e2f9e642eb8f733d2af51fc3af868f80c9b/crates/blockifier/src/transaction/objects.rs#L229)):*
> ```XML
> 
>     /// Returns a summary of transaction execution, including executed class hashes, visited storage
>     /// entries, l2_to_l1_payload_lengths, and the number of emitted events.
> ```





_Suggestion:_
```XML
L2-to-L1 payload lengths,
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-Nsvz7Vq8QTz-1Mppsih:-Nsvz7Vr3rpTuQKOg4U0:b-pydlku) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad2c8e2f9e642eb8f733d2af51fc3af868f80c9b/crates/blockifier/src/transaction/objects.rs#L234)):*
> ```XML
>             self.non_optional_call_infos().map(|call_info| call_info.summarize()).collect();
>         Ok(execution_summary_vec?.into_iter().sum())
>     }
> ```

Why do you need the variable? can't you do it in one line?
I think you can keep it as-is



_Code quote:_
```XML
        let execution_summary_vec: TransactionExecutionResult<Vec<ExecutionSummary>> =
            self.non_optional_call_infos().map(|call_info| call_info.summarize()).collect();
        Ok(execution_summary_vec?.into_iter().sum())
    }
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1666)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-Nsvz7Vq8QTz-1Mppsih:-Nsw-iDHB5sWeo0PciAe:b8anij6) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad2c8e2f9e642eb8f733d2af51fc3af868f80c9b/crates/blockifier/src/transaction/objects.rs#L234)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why do you need the variable? can't you do it in one line?
I think you can keep it as-is
</blockquote></details>

Anyway, this function https://github.com/starkware-libs/blockifier/blob/20a895343ec21b6b2eebee41f4087159df126096/crates/blockifier/src/execution/call_info.rs#L187
need not return a Result. You can use `assert!` there.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1666)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-Nsw0kXF5r6PNsttVqlN:-Nsw0kXF5r6PNsttVqlO:bksibqt) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad2c8e2f9e642eb8f733d2af51fc3af868f80c9b/crates/blockifier/src/bouncer.rs#L144)):*
> ```XML
> /// Calculates the L1 resources used by L1<>L2 messages.
> /// Returns the total message segment length and the L1 gas usage.
> pub fn calc_message_l1_resources(
> ```

`calculate`
___
*[`crates/blockifier/src/bouncer.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-Nsw0mtE9FSoz_MsVjha:-Nsw0mtE9FSoz_MsVjhb:b-41rjcz) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad2c8e2f9e642eb8f733d2af51fc3af868f80c9b/crates/blockifier/src/bouncer.rs#L145)):*
> ```XML
> /// Returns the total message segment length and the L1 gas usage.
> pub fn calc_message_l1_resources(
>     execution_summary: &ExecutionSummary,
> ```

Pass just `l2_to_l1_payload_lengths`



_Code quote:_
```XML
execution_summary: &ExecutionSummary,
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1666)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-Nsw0kXF5r6PNsttVqlN:-NswLlJT1FmtV5QrXVKo:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad2c8e2f9e642eb8f733d2af51fc3af868f80c9b/crates/blockifier/src/bouncer.rs#L144)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`calculate`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-Nsw0mtE9FSoz_MsVjha:-NswLl_S4Mo_F2n1KaSD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad2c8e2f9e642eb8f733d2af51fc3af868f80c9b/crates/blockifier/src/bouncer.rs#L145)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Pass just `l2_to_l1_payload_lengths`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-NsvyY9e6DFnhbE8TNTw:-NswLq4A3H1ULJzSpsgs:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad2c8e2f9e642eb8f733d2af51fc3af868f80c9b/crates/blockifier/src/transaction/objects.rs#L229)):*
> ```XML
> 
>     /// Returns a summary of transaction execution, including executed class hashes, visited storage
>     /// entries, l2_to_l1_payload_lengths, and the number of emitted events.
> ```

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-Nsvz7Vq8QTz-1Mppsih:-NswLqgiERiFXHRmggcY:b-ro1od2) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad2c8e2f9e642eb8f733d2af51fc3af868f80c9b/crates/blockifier/src/transaction/objects.rs#L234)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Anyway, this function https://github.com/starkware-libs/blockifier/blob/20a895343ec21b6b2eebee41f4087159df126096/crates/blockifier/src/execution/call_info.rs#L187
need not return a Result. You can use `assert!` there.
</blockquote></details>

as discussed on huddles, I removed the Result return value, and changed get_sorted_l2_to_l1_payload_lengths() to be unsorted.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1666)* status: 3 of 12 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-NswqaFX7om8U2qo1JRJ:-NswqaFX7om8U2qo1JRK:b-8d3ux1) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b73e369c0a46128c736e108efde9a15f684c789/crates/blockifier/src/execution/call_info.rs#L196)):*
> ```XML
>             .map(|message| message.message.payload.0.len())
>             .collect()
>     }
> ```

Make it a function that gets `l2_to_l1_messages` (not self)
(Why? function names are too complicated)



_Code quote:_
```XML
    pub fn get_call_info_l2_to_l1_payload_lengths(&self) -> Vec<usize> {
        self.execution
            .l2_to_l1_messages
            .iter()
            .map(|message| message.message.payload.0.len())
            .collect()
    }
```

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 12 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-:-Nsx3q6h5-ty9nLPTjb9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1666#-:-Nsx9cs72hp7_jmruBz8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
