### PR TITLE
Move utils from test to test utils module

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1165)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1165)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1165#-NjvJlD843K3UnVUu8di:-NjvJlD843K3UnVUu8dj:b-9osm8) ([raw file](https://github.com/starkware-libs/blockifier/blob/39aff5b846a404fe140d13820a574cbe96764a8e/crates/blockifier/src/transaction/account_transactions_test.rs#L91)):*
> ```XML
>         mut nonce_manager,
>         block_context,
>     } = create_test_init_data(max_fee, block_context);
> ```

@noaov1 the only part that is not exactly cut-paste is that there is no more third argument (state) in `create_test_init_data`. `create_test_init_data` now just calls `create_state` first



_Code quote:_
```XML
create_test_init_data(max_fee, block_context);
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1165)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1165#-NjvJlD843K3UnVUu8di:-NjwS8gZ20bHMNPVKFg5:b-3qn7ii) ([raw file](https://github.com/starkware-libs/blockifier/blob/39aff5b846a404fe140d13820a574cbe96764a8e/crates/blockifier/src/transaction/account_transactions_test.rs#L91)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@noaov1 the only part that is not exactly cut-paste is that there is no more third argument (state) in `create_test_init_data`. `create_test_init_data` now just calls `create_state` first
</blockquote></details>

And why isn't a fixture?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1165)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1165#-NjvJlD843K3UnVUu8di:-NjwVQwv3jz7lTYENRMf:blx3k7l) ([raw file](https://github.com/starkware-libs/blockifier/blob/39aff5b846a404fe140d13820a574cbe96764a8e/crates/blockifier/src/transaction/account_transactions_test.rs#L91)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And why isn't a fixture?
</blockquote></details>

`fixture` is in `rstest` which isn't available in test_utils.rs, because in the module:
```
#[cfg(any(feature = "testing", test))]
pub mod test_utils;
```
and I think `rstest` isn't available in `feature = "testing"` mode

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1165#-:-NjwabErBsGE-IyD1AXg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
