### PR TITLE
Elin/merge main v0.13.0 hotfix into main v0.13.1

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1494)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1494)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1714 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1494#-NqVy35c0Y0CzU5GffTS:-NqVy35c0Y0CzU5GffTT:bj7jhpw) ([raw file](https://github.com/starkware-libs/blockifier/blob/fdfba79eac787a919d3734de01d4e490139ca8da/crates/blockifier/src/transaction/transactions_test.rs#L1714)):*
> ```XML
>     None;
>     "Positive flow")]
> #[test_case(
> ```

This test should stay for 0.13.1, checking the case that the event exceeds the number of emitted events.
I guess it means that nothing from the 0.13.1-hotfix should be taken.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1494)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1709 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1494#-NqW5gMb3OIzPhBVaLGe:-NqW5gMb3OIzPhBVaLGf:b-mw9knw) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3c28eefe610c1b6a3a823f70614202bb8af5d7/crates/blockifier/src/transaction/transactions_test.rs#L1709)):*
> ```XML
>     vec![stark_felt!(1_u16); SYSCALL_MAX_EVENT_KEYS],
>     vec![stark_felt!(2_u16); SYSCALL_MAX_EVENT_DATA],
>     10,
> ```

this should be SYSCALL_MAX_N_EMITTED_EVENTS, to test the edge case of sending exactly the max amount of events.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1494)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1709 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1494#-NqW5gMb3OIzPhBVaLGe:-NqWlncs88cuAVUxEGQE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3c28eefe610c1b6a3a823f70614202bb8af5d7/crates/blockifier/src/transaction/transactions_test.rs#L1709)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this should be SYSCALL_MAX_N_EMITTED_EVENTS, to test the edge case of sending exactly the max amount of events.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1714 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1494#-NqVy35c0Y0CzU5GffTS:-NqWm0GY6FPZlYjiR87I:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fdfba79eac787a919d3734de01d4e490139ca8da/crates/blockifier/src/transaction/transactions_test.rs#L1714)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

This test should stay for 0.13.1, checking the case that the event exceeds the number of emitted events.
I guess it means that nothing from the 0.13.1-hotfix should be taken.
</blockquote></details>

Done.

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1494#-:-NqWmzYA2iJUwyiMoMxn:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1494)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
