### PR TITLE
Renaming:

### PR DESCRIPTION
**Pull request by noaov1**
- `cairo` -> `vm` 
- `cairo_resource_fee_weights` -> `vm_resource_fee_cost` (because the values in this map indicate the cost of the resource)

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/421)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/421)* status: 0 of 10 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/transaction/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/421#-NTTcrbk3GodGUC1c9GP:-NTTcrbk3GodGUC1c9GQ:b-lqza50) ([raw file](https://github.com/starkware-libs/blockifier/blob/d492c7d88e1fbe8d51df81144afc6ae14c4a82f7/crates/blockifier/src/transaction/errors.rs#L11)):*
> ```XML
> #[derive(Debug, Error)]
> pub enum TransactionExecutionError {
>     #[error("Cairo resource names must be contained in fee cost dict.")]
> ```

Not sure if it's okay because it will differ from python. Should it be an error? Who is responsible to provide the `cairo_resource_fee_weights` in the `general_config`?



_Code quote:_
```XML
#[error("Cairo resource names must be contained in fee cost dict.")]
```

**Review by elintul — APPROVED** [review]
Amazing, thanks!
How do you define "cost"? What's the difference from "weight"?

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/421#-:-NTZFJw-BsMyrNBqZz5e:b-b9gdwq)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/421#-NTTcrbk3GodGUC1c9GP:-NTZF_bjAPhT3psxkPaF:b-3ej1fe) ([raw file](https://github.com/starkware-libs/blockifier/blob/d492c7d88e1fbe8d51df81144afc6ae14c4a82f7/crates/blockifier/src/transaction/errors.rs#L11)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not sure if it's okay because it will differ from python. Should it be an error? Who is responsible to provide the `cairo_resource_fee_weights` in the `general_config`?
</blockquote></details>

By "it" do you mean the error message? If so, it's fine; so many error messages are changes with out implementation... :)
The Python backend provides those weights (they are a configuration of the SN env.).

**Review by elintul — APPROVED** [review]
I see "weight" as a proportion relative to other factors. Do you think "cost" represents this semantically?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/421#-:-NTZGKEhB7fo6UlA09eU:bm9muwu)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

**Review by noaov1 — COMMENTED** [review]
The values in `cairo_resource_fee_weights` represent the L1 gas per resource (instance). I think that "cost"  captures this meaning better than "weight". WDYT? 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/421#-:-NTh1HYQ00hRXcXaHlBf:budg9he)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by elintul — APPROVED** [review]
I thought this vector (coming from the general config) represented the weights (or: coefficients) of the different VM resources. To get the actual fee we multiply the usage vector by the weights vector.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/421#-:-NTha9d1AfJQzcD02vmA:b-35sceo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/421#-:-NTig-ZC2eIOurQTD_KC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
