### PR TITLE
refactor(concurrency): use TransactionalState::create_transactional i…

### PR DESCRIPTION
**Pull request by OriStarkware**
…n tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1920)

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 441 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1920#-Nz40JRuEIizik_w15-H:-Nz40JRv-YDBrbw4wtpV:b77ehju) ([raw file](https://github.com/starkware-libs/blockifier/blob/26606011bfa3fc11fdc0874f3a4aadf279e75dbc/crates/blockifier/src/concurrency/versioned_state_test.rs#L441)):*
> ```XML
>         &transactional_states[tx_index_to_delete_writes].cache.borrow().writes,
>         &transactional_states[tx_index_to_delete_writes].class_hash_to_class.borrow(),
>     );
> ```

Why not use the transactional states here?



_Code quote:_
```XML
            .unwrap();
        safe_versioned_state.pin_version(i).apply_writes(
            &tx_state.cache.borrow().writes,
            &tx_state.class_hash_to_class.borrow(),
            &HashMap::default(),
        );
    }

    safe_versioned_state.pin_version(tx_index_to_delete_writes).delete_writes(
        &transactional_states[tx_index_to_delete_writes].cache.borrow().writes,
        &transactional_states[tx_index_to_delete_writes].class_hash_to_class.borrow(),
    );
```

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1920#-:-Nz7Aag-1zX8Gewt-EaM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1920)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 338 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1920#-Nz9P4sUEILscSRUaFx6:-Nz9P4sV8qDweDg6sqMa:bcn5ppi) ([raw file](https://github.com/starkware-libs/blockifier/blob/26606011bfa3fc11fdc0874f3a4aadf279e75dbc/crates/blockifier/src/concurrency/versioned_state_test.rs#L338)):*
> ```XML
>     for proxy_state in &mut versioned_proxy_states {
>         transactional_states.push(TransactionalState::create_transactional(proxy_state));
>     }
> ```

In the entire file



_Suggestion:_
```XML
    let mut transactional_states = versioned_proxy_states
        .iter_mut()
        .map(|proxy_state| TransactionalState::create_transactional(proxy_state));
```

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1920)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1920#-:-NzNbEsG8uSi8TAvSMwl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
