### PR TITLE
Dori/add rstest

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/660)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/660)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by giladchase — APPROVED** [review]
:lgtm:
Let's just make sure we use it only when it's necessary, that is, when there's duplication that fixtures remove, or when parameterization is required.
The reason I think so is because this does introduce a bunch magiks and boilerplate, which I prefer to avoid when possible.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/660#-:-NYrheLrC2xUzaouMKs4:b-achupi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/660)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/Cargo.toml` line 39 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/660#-NYriXfL8mbZK1F1iYO3:-NYriXfL8mbZK1F1iYO4:b-xkse4m) ([raw file](https://github.com/starkware-libs/blockifier/blob/19d9dec65499e7a5e221968d7d8a2cfc4326add4/crates/blockifier/Cargo.toml#L39)):*
> ```TOML
> assert_matches.workspace = true
> pretty_assertions.workspace = true
> test-case.workspace = true
> ```

Move to dev-dep plz



_Suggestion:_
```TOML
num-bigint.workspace = true
num-integer.workspace = true
num-traits.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
sha3.workspace = true
starknet_api = { workspace = true, features = ["testing"] }
starknet-crypto.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
phf.workspace = true
ctor.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
test-case.workspace = true
```

**Review by dorimedini-starkware — COMMENTED** [review]
Do my usages here fit the profile?
The `#[case]`es do IMO, but I'm not sure about the fixturization. WDYT?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/660#-:-NYruGE61Rld1CtLc77Y:b-smazdv)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/660)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 39 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/660#-NYriXfL8mbZK1F1iYO3:-NYruk1k5eyIXFQO74eC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/19d9dec65499e7a5e221968d7d8a2cfc4326add4/crates/blockifier/Cargo.toml#L39)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Move to dev-dep plz
</blockquote></details>

Done.

**Review by giladchase — COMMENTED** [review]
Oh yes yes, that's what i meant.
Your's definitely fit, I meant for future use

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/660#-:-NYsC2JuE9dDiXkiXvxd:brfslon)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
