### PR TITLE
Dori/stop checking chain ids

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/637)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/637)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/637#-NYJ9ouB7i5F7mIV8_1_:-NYJ9ouB7i5F7mIV8_1a:b-rp7qsf) (no related file):*
This is basically a revert of [this](https://github.com/starkware-libs/blockifier/pull/312).
Reason is, we don't want POTC to appear in the code...
If there is no reason to verify chain ID validity in the blockifier, let's delete it

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/637)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/637#-NYJAeYyBjbrmRl77nsZ:-NYJAeYz7wEKPfjx9Evw:b-fw52q) (no related file):*
Why not validate the other public chains, of transactions coming from the Pythonic sequencer? 

___

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/637)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/637)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/637#-NYJAeYyBjbrmRl77nsZ:-NYJCQ630f0S7vmMJB6P:b-efy9br) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not validate the other public chains, of transactions coming from the Pythonic sequencer? 
</blockquote></details>

WDYM? The blockifier needs to also allow txs from non-public chains; what should I verify?

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/637)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/637#-NYJAeYyBjbrmRl77nsZ:-NYMzOhu0YpVhMqLOzCT:b5e16qd) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yes, but note the check is done in `native_blockifier`, which is an extension meant to be specifically integrated with the Pythonic sequencer. Why did you add this check there to begin with? 
</blockquote></details>

Not sure... and this caused another iteration trying to deploy a new env with a new chain ID.
1. Lior suggested to only check on the python side... native_blockifier should get the chain ID from outside
2. Keeping this list here makes a double point of truth - chain IDs should be defined in a single place IMO

___

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/637#-:-NYN7m2x0IshFSwpgDTB:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/637#-NYJAeYyBjbrmRl77nsZ:-NYN7J-_DtJEzqPMJBWu:b3s6qvj) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Not sure... and this caused another iteration trying to deploy a new env with a new chain ID.
1. Lior suggested to only check on the python side... native_blockifier should get the chain ID from outside
2. Keeping this list here makes a double point of truth - chain IDs should be defined in a single place IMO
</blockquote></details>

I agree with 2, although not sure we comply with 1 on all fields we pass from Python.
If `native_blockifier` only exists for integration with the Pythonic sequencer, indeed no point to double-check things; when Python will get deprecated, the extension will too. 

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/637)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Pull request merged**
