### PR TITLE
Use native bazel rules for build rust and cargo

### PR DESCRIPTION
**Pull request by alon-dotan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355#-:-NRRMirHDgNRz5wZYuQO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/355#-NRRgQQsA6aMjr1TaCoD:-NRRgQQsA6aMjr1TaCoE:b6x0238) ([raw file](https://github.com/starkware-libs/blockifier/blob/474ceb47225b7dc53290c0ba980773bb609d390c/crates/blockifier/Cargo.toml#L10)):*
> ```TOML
> 
> # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
> ```

Why were libraries fixed?

**Review by elintul — COMMENTED** [review]
> Reviewed 7 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @giladchase)

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/355#-NRRgQQsA6aMjr1TaCoD:-NRRmW0n2UtZeHuUghz1:b-fyh79e) ([raw file](https://github.com/starkware-libs/blockifier/blob/474ceb47225b7dc53290c0ba980773bb609d390c/crates/blockifier/Cargo.toml#L10)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why were libraries fixed?
</blockquote></details>

cargo impl in bazel requires this... (its bad practice to don't do so anyway)

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/355#-NRRgQQsA6aMjr1TaCoD:-NRSMRH17nw5xBMHsfAB:bfy9hvo) ([raw file](https://github.com/starkware-libs/blockifier/blob/474ceb47225b7dc53290c0ba980773bb609d390c/crates/blockifier/Cargo.toml#L10)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

cargo impl in bazel requires this... (its bad practice to don't do so anyway)
</blockquote></details>

Why commits and not versions? Do those crates not maintain an ordered versioning?

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/355#-NRRgQQsA6aMjr1TaCoD:-NRSNhwTECyNUk2WvXOp:bkdgcn9) ([raw file](https://github.com/starkware-libs/blockifier/blob/474ceb47225b7dc53290c0ba980773bb609d390c/crates/blockifier/Cargo.toml#L10)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why commits and not versions? Do those crates not maintain an ordered versioning? 
</blockquote></details>

In general commits are immutable and releases are not... bazel claim to fame is deterministic builds... so all the best practices around it

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/355#-NRRgQQsA6aMjr1TaCoD:-NRSOLXN-0I4SGhzuOTD:b-lzs20s) ([raw file](https://github.com/starkware-libs/blockifier/blob/474ceb47225b7dc53290c0ba980773bb609d390c/crates/blockifier/Cargo.toml#L10)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

In general commits are immutable and releases are not... bazel claim to fame is deterministic builds... so all the best practices around it
</blockquote></details>

How do we know this PR and its SW repo. pair will work? Can you please add a test for the whole flow you're building?

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/355#-NRRgQQsA6aMjr1TaCoD:-NRSOx5W1jC-QxW0TAKL:bh0prn2) ([raw file](https://github.com/starkware-libs/blockifier/blob/474ceb47225b7dc53290c0ba980773bb609d390c/crates/blockifier/Cargo.toml#L10)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How do we know this PR and its SW repo. pair will work? Can you please add a test for the whole flow you're building?
</blockquote></details>

there is this one `//src/starkware/starknet/services/batcher:starknet_batcher_test` thanks to @giladchase

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/355#-NRRgQQsA6aMjr1TaCoD:-NRSP7AxA3yNaiZ1J-IC:b6c5hix) ([raw file](https://github.com/starkware-libs/blockifier/blob/474ceb47225b7dc53290c0ba980773bb609d390c/crates/blockifier/Cargo.toml#L10)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

there is this one `//src/starkware/starknet/services/batcher:starknet_batcher_test` thanks to @giladchase 
</blockquote></details>

in starkware main repo

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/355#-NRRgQQsA6aMjr1TaCoD:-NRSShjs5T6Vupypbf5J:bl0tge4) ([raw file](https://github.com/starkware-libs/blockifier/blob/474ceb47225b7dc53290c0ba980773bb609d390c/crates/blockifier/Cargo.toml#L10)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

in starkware main repo
</blockquote></details>

One what?

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @giladchase)

___
*[`crates/native_blockifier/BUILD` line 23 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/355#-NRTC8wF3kkK_l7nBqbK:-NRTC8wF3kkK_l7nBqbL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/23384aa06a7bd9f59e5e2335e1e50ada043b8e48/crates/native_blockifier/BUILD#L23)):*
> ```Starlark
>     srcs = ["native_blockifier/__init__.py"],
>     data = ["native_blockifier.so"],
>     imports = ["."], # Allow using "import native_blockifier" directly in any python code.
> ```





_Suggestion:_
```Starlark
Python
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/355#-NRRgQQsA6aMjr1TaCoD:-NRTCedmA-9HNqj_eEdy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/474ceb47225b7dc53290c0ba980773bb609d390c/crates/blockifier/Cargo.toml#L10)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

One what?
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

The parts I understood...

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/355#-:-NRTKvaw2P4lq2MVLglT:bk7ull8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
