### PR TITLE
Secp256k1GetPointFromXRequest structs.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6TH4z7eY_4VbN_veL:-NZ6TH4z7eY_4VbN_veM:b-etoipe) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d212e5ae14e89282fccd467308ae2c9eec6ded4/crates/blockifier/src/execution/syscalls/secp.rs#L175)):*
> ```XML
> }
> 
> type Secp256k1NewResponse = Secp256k1OptionalEcPointResponse;
> ```

I'm going to add
type Secp256k1GetPointFromXResponse = Secp256k1OptionalEcPointResponse;



_Code quote:_
```XML
type Secp256k1NewResponse = Secp256k1OptionalEcPointResponse;
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6ToYP0JPEc1hd9bRK:-NZ6ToYP0JPEc1hd9bRL:b-6p56ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d212e5ae14e89282fccd467308ae2c9eec6ded4/crates/blockifier/src/execution/syscalls/secp.rs#L97)):*
> ```XML
> struct Secp256k1GetPointFromXRequest {
>     x: BigUint,
>     y_parity: bool,
> ```

Add an inline comment on what is what, or maybe I'm unfamiliar with the terminology and it's clear?



_Code quote:_
```XML
y_parity: bool,
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6TkxM1DhmMzFSSbDd:-NZ6TkxM1DhmMzFSSbDe:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d212e5ae14e89282fccd467308ae2c9eec6ded4/crates/blockifier/src/execution/syscalls/secp.rs#L109)):*
> ```XML
>         let y_parity = felt_from_ptr(vm, ptr)?.is_zero();
> 
>         Ok(Secp256k1GetPointFromXRequest { x, y_parity })
> ```





_Suggestion:_
```XML
        let x = u256_from_ptr(vm, ptr)?;
        let y_parity = felt_from_ptr(vm, ptr)?.is_zero();
        Ok(Secp256k1GetPointFromXRequest { x, y_parity })
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6ToYP0JPEc1hd9bRK:-NZ6VA4WBhsuCQuzNDyH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d212e5ae14e89282fccd467308ae2c9eec6ded4/crates/blockifier/src/execution/syscalls/secp.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add an inline comment on what is what, or maybe I'm unfamiliar with the terminology and it's clear?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6TkxM1DhmMzFSSbDd:-NZ6VPVn0yNUr2NFG7Pd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d212e5ae14e89282fccd467308ae2c9eec6ded4/crates/blockifier/src/execution/syscalls/secp.rs#L109)):*
> ```XML
>         let y_parity = felt_from_ptr(vm, ptr)?.is_zero();
> 
>         Ok(Secp256k1GetPointFromXRequest { x, y_parity })
> ```

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6ToYP0JPEc1hd9bRK:-NZ6WbXo6xehr_DUt_RM:bofpp56) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d212e5ae14e89282fccd467308ae2c9eec6ded4/crates/blockifier/src/execution/syscalls/secp.rs#L97)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So... `true` is even?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6ToYP0JPEc1hd9bRK:-NZ6Y5dbCb2DPCDO6SqY:bl3ui17) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d212e5ae14e89282fccd467308ae2c9eec6ded4/crates/blockifier/src/execution/syscalls/secp.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So... `true` is even?
</blockquote></details>

Good catch, I've copied it from here:
https://github.com/starkware-libs/cairo/blob/ecb35ac50e64ee2e0a8eab109f363ed0206c330e/crates/cairo-lang-runner/src/casm_run/mod.rs#L672

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6ToYP0JPEc1hd9bRK:-NZ6a2t25x3ngGOZIqDc:b-v1u7ym) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d212e5ae14e89282fccd467308ae2c9eec6ded4/crates/blockifier/src/execution/syscalls/secp.rs#L97)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Good catch, I've copied it from here:
https://github.com/starkware-libs/cairo/blob/ecb35ac50e64ee2e0a8eab109f363ed0206c330e/crates/cairo-lang-runner/src/casm_run/mod.rs#L672

</blockquote></details>

what type do you think I should use for the parity?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6cZd-2ei-UY_Fq3wf:-NZ6cZd-2ei-UY_Fq3wg:b-mpd329) ([raw file](https://github.com/starkware-libs/blockifier/blob/21280815460cca1c38b22678e8cff1046ab493c6/crates/blockifier/src/execution/syscalls/secp.rs#L114)):*
> ```XML
>                 input: felt_to_stark_felt(&y_parity_felt),
>                 info: "Invalid y parity".to_string(),
>             });
> ```

This should never happen unless we have a bug in sierra.

but we also have such checks in other places.



_Code quote:_
```XML
            return Err(SyscallExecutionError::InvalidSyscallInput {
                input: felt_to_stark_felt(&y_parity_felt),
                info: "Invalid y parity".to_string(),
            });
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6ToYP0JPEc1hd9bRK:-NZ6Z59gAzYVjIUaV9Ps:b-tugopd) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d212e5ae14e89282fccd467308ae2c9eec6ded4/crates/blockifier/src/execution/syscalls/secp.rs#L97)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what type do you think I should use for the parity?
</blockquote></details>

`bool` is good, simply document it as "sign" in the comment, and say `true` is positive.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZBtRCW6ihbqU3g7WGp:-NZBtRCW6ihbqU3g7WGq:bwl5xig) ([raw file](https://github.com/starkware-libs/blockifier/blob/21280815460cca1c38b22678e8cff1046ab493c6/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
> ```XML
> 
>         let y_parity = y_parity_felt.is_one();
>         if y_parity && !y_parity_felt.is_zero() {
> ```

Can you explain this?



_Code quote:_
```XML
        let y_parity = y_parity_felt.is_one();
        if y_parity && !y_parity_felt.is_zero() {
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6cZd-2ei-UY_Fq3wf:-NZBtTXiEdpoKnF_e31m:bhk8et9) ([raw file](https://github.com/starkware-libs/blockifier/blob/21280815460cca1c38b22678e8cff1046ab493c6/crates/blockifier/src/execution/syscalls/secp.rs#L114)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This should never happen unless we have a bug in sierra.

but we also have such checks in other places.
</blockquote></details>

Where else? I'm contemplating whether we can define an error variant for those cases.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6cZd-2ei-UY_Fq3wf:-NZKH1Jn7MsXXxsHAhLe:b-qhzm4r) ([raw file](https://github.com/starkware-libs/blockifier/blob/21280815460cca1c38b22678e8cff1046ab493c6/crates/blockifier/src/execution/syscalls/secp.rs#L114)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where else? I'm contemplating whether we can define an error variant for those cases.
</blockquote></details>

in keccak
https://github.com/starkware-libs/blockifier/blob/ffe6708631a5d8224d5c244d29088b57a16089d0/crates/blockifier/src/execution/syscalls/mod.rs#L667.

I thought all the error variants except SyscallError shouldn't happen with cairo1.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZ6ToYP0JPEc1hd9bRK:-NZKLOuVEuE15Nc9e-iE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d212e5ae14e89282fccd467308ae2c9eec6ded4/crates/blockifier/src/execution/syscalls/secp.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`bool` is good, simply document it as "sign" in the comment, and say `true` is positive.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZBtRCW6ihbqU3g7WGp:-NZKLQFv6a2o-c1laisK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/21280815460cca1c38b22678e8cff1046ab493c6/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain this?
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 98 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLNGFe2tSwbij6fGnI:-NZLNGFe2tSwbij6fGnJ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L98)):*
> ```XML
>     x: BigUint,
>     // The parity of the y coordinate, assuming a point with the given x coordinate exists.
>     // True means the y coordinate is odd, false means the y coordinate is even.
> ```





_Suggestion:_
```XML
    // The parity (sign) of the y coordinate, assuming a point with the given x coordinate exists.
    // True means the y coordinate is odd.
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZLRswI6wy3_qwe7CFq:bqw82fe) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
> ```XML
>         let y_parity_felt = felt_from_ptr(vm, ptr)?;
> 
>         // y_parity should be bool.
> ```

Now that the condition is clearer, this comment is redundant.



_Code quote:_
```XML
 // y_parity should be bool.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 98 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLNGFe2tSwbij6fGnI:-NZLSEBeB7xoZ4wBuFj0:bd13ubi) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L98)):*
> ```XML
>     x: BigUint,
>     // The parity of the y coordinate, assuming a point with the given x coordinate exists.
>     // True means the y coordinate is odd, false means the y coordinate is even.
> ```

it is the lsb, not the msb (sign)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZLSYOt4N3afWirfJtF:b-x01r48) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Now that the condition is clearer, this comment is redundant.
</blockquote></details>

the condition is if it is zero or once, it is not obvious that the argument is a boolean.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 98 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLNGFe2tSwbij6fGnI:-NZLTXEP-ntzsotBdLXF:b-y9nmdm) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L98)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is the lsb, not the msb (sign)
</blockquote></details>

The second half of the second sentence can still be deleted.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZLT7d49F0q7AS_pn79:bmvukth) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the condition is if it is zero or once, it is not obvious that the argument is a boolean.
</blockquote></details>

Please use [this](https://github.com/starkware-libs/blockifier/blob/51d9bc4556048741efd77e06097335206d1e5a46/crates/blockifier/src/execution/syscalls/hint_processor.rs#L443) instead. Should format the error message (currently it's says "deploy_from_zero" hardcoded).

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZLW4ZBASQ00u8X4xFt:b-5d3975) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please use [this](https://github.com/starkware-libs/blockifier/blob/51d9bc4556048741efd77e06097335206d1e5a46/crates/blockifier/src/execution/syscalls/hint_processor.rs#L443) instead. Should format the error message (currently it's says "deploy_from_zero" hardcoded).
</blockquote></details>

I'm not sure I want to map both to the same error.

deploy_from_zero  can be reached for cairo0 contracts, so a non-boolean value is possible.

here  a non-boolean value indicates a bug.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZLXqKP9FouuOfNY063:b-5t87q4) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not sure I want to map both to the same error.

deploy_from_zero  can be reached for cairo0 contracts, so a non-boolean value is possible.

here  a non-boolean value indicates a bug.
</blockquote></details>

Not sure I understand; they are currently both mapped to same variant.

"deploy_from_zero can be reached for cairo0 contracts, so a non-boolean value is possible."
WDYM?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZLYDBPE3C0IfOmxudH:b-dq3egj) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure I understand; they are currently both mapped to same variant.

"deploy_from_zero can be reached for cairo0 contracts, so a non-boolean value is possible."
WDYM?
</blockquote></details>

a Cairo 0 contract can pass deploy_from_zero=17.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZLYOMH4XMxyV2HPd4u:bkbndeg) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

a Cairo 0 contract can pass deploy_from_zero=17.
</blockquote></details>

I guess we can treat cairo0 and cairo1 contracts differently when we catch the error.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZLYR2W4tnmEmBAvKpM:ba646o5) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess we can treat cairo0 and cairo1 contracts differently when we catch the error.
</blockquote></details>

This error code is treated [like any other](https://github.com/starkware-libs/blockifier/blob/51d9bc4556048741efd77e06097335206d1e5a46/crates/blockifier/src/execution/syscalls/hint_processor.rs#L280). What do you think should happen on such an unexpected failure?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZLZHcO6rjxW2sRzw_q:b-i8vj7g) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This error code is treated [like any other](https://github.com/starkware-libs/blockifier/blob/51d9bc4556048741efd77e06097335206d1e5a46/crates/blockifier/src/execution/syscalls/hint_processor.rs#L280). What do you think should happen on such an unexpected failure?
</blockquote></details>

I don't know what should happen.

in any case, felt\_to\_bool returns DeprecatedSyscallResult and I need SyscallExecutionError here.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZL_6MoEtHpbrBSl1nl:b-eug58m) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't know what should happen.

in any case, felt\_to\_bool returns DeprecatedSyscallResult and I need SyscallExecutionError here.
</blockquote></details>

There are two `felt_to_bool`, unfortunately; this code is duplicated until Cairo 0 is no longer supported.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 98 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLNGFe2tSwbij6fGnI:-NZLbFUW9RCvROmdA9CY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L98)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The second half of the second sentence can still be deleted.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/698#-NZLRswI6wy3_qwe7CFp:-NZLbFxHAZqDmid_8Sdk:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/6dded5dceffcd4723e309cabc0e0ee73eae0d606/crates/blockifier/src/execution/syscalls/secp.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

There are two `felt_to_bool`, unfortunately; this code is duplicated until Cairo 0 is no longer supported.
</blockquote></details>

done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/698#-:-NZLoGEF7VSN2H9wQThO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
