### PR TITLE
Add L1HandlerTransaction.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/243)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/243)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/execute_transaction.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMhbDsg-QtmYQ9b2aOT:-NMhbDsh6apnAI436NdG:buj7e5y) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0470461caa1ecabcac593624bf4405a2822775e/crates/blockifier/src/transaction/execute_transaction.rs#L8)):*
> ```XML
> use crate::state::state_api::State;
> use crate::transaction::objects::{AccountTransactionContext, TransactionExecutionResult};
> ```

Do we really need those traits?
Perhaps move the two validation methods to `AccountTransaction` enum, and add `Transaction` enum with `execute_tx`.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/243)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/execute_transaction.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMhbDsg-QtmYQ9b2aOT:-NMi1BRt6cCAh552HAKq:b-gs7qz1) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0470461caa1ecabcac593624bf4405a2822775e/crates/blockifier/src/transaction/execute_transaction.rs#L8)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we really need those traits?
Perhaps move the two validation methods to `AccountTransaction` enum, and add `Transaction` enum with `execute_tx`.
</blockquote></details>

Yes, that's better. Done.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/243)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/execute_transaction.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMhbDsg-QtmYQ9b2aOT:-NMi6OXcCUPsFRGSFyU5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0470461caa1ecabcac593624bf4405a2822775e/crates/blockifier/src/transaction/execute_transaction.rs#L8)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we can delete `ValidatableTransaction`. 
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/243)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMiB327CXjYc9Lz6sWm:-NMiB327CXjYc9Lz6sWn:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ead72b88509a2d08763b362c77cbc4de1c784cf5/crates/blockifier/src/transaction/account_transaction.rs#L108)):*
> ```XML
>         match self {
>             Self::Declare(_) => selector_from_name(constants::VALIDATE_DECLARE_ENTRY_POINT_NAME),
>             Self::DeployAccount(_) => {
> ```





_Suggestion:_
```XML
        let validate_entry_point_name = match self {
            Self::Declare(_) => constants::VALIDATE_DECLARE_ENTRY_POINT_NAME,
            Self::DeployAccount(_) => constants::VALIDATE_DEPLOY_ENTRY_POINT_NAME,
            Self::Invoke(_) => constants::VALIDATE_ENTRY_POINT_NAME,
        };
        
        selector_from_name(validate_entry_point_name)
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMiCHssCIi-dV4mjs6C:-NMiCHssCIi-dV4mjs6D:b-nunx5v) ([raw file](https://github.com/starkware-libs/blockifier/blob/ead72b88509a2d08763b362c77cbc4de1c784cf5/crates/blockifier/src/transaction/account_transaction.rs#L115)):*
> ```XML
>     }
> 
>     fn validate_entrypoint_calldata(&self) -> Calldata {
> ```

Let's encapsulate `Arc` impl. detail (with `.into()` and `.clone()`).



_Code quote:_
```XML
validate_entrypoint_calldata
```
___
*[`crates/blockifier/src/transaction/execute_transaction.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMiCr7ADN6x_S2hnpxe:-NMiCr7ADN6x_S2hnpxf:bvp0s5h) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd4c2582d239e24092201d71fb645d96374ccdbd/crates/blockifier/src/transaction/execute_transaction.rs#L18)):*
> ```XML
> 
>     // Calldata for validation contains transaction fields that cannot be obtained by calling
>     // `get_tx_info()`.
> ```

Restore.



_Code quote:_
```XML
    // Calldata for validation contains transaction fields that cannot be obtained by calling
    // `get_tx_info()`.
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMiCoT3Ep3TqYlq_3T7:-NMiCoT3Ep3TqYlq_3T8:bvp0s5h) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd4c2582d239e24092201d71fb645d96374ccdbd/crates/blockifier/src/transaction/transactions.rs#L94)):*
> ```XML
>     }
> 
>     // Calldata for validation is the same calldata as for the execution itself.
> ```

Restore.



_Code quote:_
```XML
// Calldata for validation is the same calldata as for the execution itself.
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/243)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMiB327CXjYc9Lz6sWm:-NMiEdtD8KYep2EYwD2h:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ead72b88509a2d08763b362c77cbc4de1c784cf5/crates/blockifier/src/transaction/account_transaction.rs#L108)):*
> ```XML
>         match self {
>             Self::Declare(_) => selector_from_name(constants::VALIDATE_DECLARE_ENTRY_POINT_NAME),
>             Self::DeployAccount(_) => {
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMiCHssCIi-dV4mjs6C:-NMiEtxV-M1U_85r2EO9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ead72b88509a2d08763b362c77cbc4de1c784cf5/crates/blockifier/src/transaction/account_transaction.rs#L115)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's encapsulate `Arc` impl. detail (with `.into()` and `.clone()`).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/execute_transaction.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMiCr7ADN6x_S2hnpxe:-NMiEN6fCtjeCObq9cd_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd4c2582d239e24092201d71fb645d96374ccdbd/crates/blockifier/src/transaction/execute_transaction.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Restore.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMiCoT3Ep3TqYlq_3T7:-NMiEMR45CZbvVcG3OIp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd4c2582d239e24092201d71fb645d96374ccdbd/crates/blockifier/src/transaction/transactions.rs#L94)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Restore.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/243#-:-NMiGkvjB3NV_qf1kaEd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/243)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/243#-NMiLSuoCLVwzLkJVc4C:-NMiLSuoCLVwzLkJVc4D:bta75a9) ([raw file](https://github.com/starkware-libs/blockifier/blob/fad7b434d28b6eab96436023381de7af5ab00195/crates/blockifier/src/transaction/transactions.rs#L21)):*
> ```XML
> #[path = "transactions_test.rs"]
> mod test;
> ```

Let's rename to `Executable` and the method to `execute`.
We'll have a `Transaction` enum.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/243)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

**Pull request merged**
