### PR TITLE
Release 0.4.0 rc6

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1123)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1123)* status: 0 of 7 files reviewed, all discussions resolved

___
*[`crates/native_blockifier/Cargo.toml` line 26 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1123#-Nj3cdhD6Oiqpnw9bZfv:-Nj3cdhD6Oiqpnw9bZfw:bph3onc) ([raw file](https://github.com/starkware-libs/blockifier/blob/da9ffe0ba12ddae6240576f4ce26db01e802870d/crates/native_blockifier/Cargo.toml#L26)):*
> ```TOML
> 
> [dependencies]
> blockifier = { path = "../blockifier", version = "0.4.0-rc4", features = [
> ```

Removed this cause this is only relevant for crates.io (which can't use the `path` dependency), but since we aren't publishing `native_blockifier` it is dead code ATM.



_Code quote:_
```TOML
 version = "0.4.0-rc4",
```

**Review by giladchase — COMMENTED** [review]
Python: https://reviewable.io/reviews/starkware-industries/starkware/32554#-

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1123#-:-Nj3dlAG3ma-LkkOFGMv:b-8cd1vj)* status: 0 of 7 files reviewed, all discussions resolved

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1123#-:-Nj3jsfD0hX603SL0amc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

**Pull request merged**
