### PR TITLE
Grab blockifier by path instead of by git

### PR DESCRIPTION
**Pull request by giladchase**
Taking by git creates divergence of versions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/283)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/283#-:-NOL-Ys1-Wuz9Eni_Zg3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/283)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @giladchase)

___
*[`scripts/build.sh` line 3 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/283#-NOO52VU8Qe8XrsFerdW:-NOO52VVBhNwnn0II2s1:bd4adew) ([raw file](https://github.com/starkware-libs/blockifier/blob/aefbfdd637f8f07b0d37eea0ce3841cf3dd32fae/scripts/build.sh#L3)):*
> ```Shell
> #!/bin/bash
> set -ex
> ```

Can you explain what you do here?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/283)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @elintul)

___
*[`scripts/build.sh` line 3 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/283#-NOO52VU8Qe8XrsFerdW:-NOOBLUd8Efs0LGvnku3:b-tzybfn) ([raw file](https://github.com/starkware-libs/blockifier/blob/aefbfdd637f8f07b0d37eea0ce3841cf3dd32fae/scripts/build.sh#L3)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain what you do here? 
</blockquote></details>

Alon did everything :grimacing: i'll talk to him in the office today and figure out

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/283)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @elintul)

___
*[`scripts/build.sh` line 3 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/283#-NOO52VU8Qe8XrsFerdW:-NOOCxCq3iXPECs-yMc_:b-23yok4) ([raw file](https://github.com/starkware-libs/blockifier/blob/aefbfdd637f8f07b0d37eea0ce3841cf3dd32fae/scripts/build.sh#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Alon did everything :grimacing: i'll talk to him in the office today and figure out 
</blockquote></details>

Merging this.
Will still update you about what's being done here after I find Alon.

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/283)* status: all files reviewed, 1 unresolved discussion

___
*[`scripts/build.sh` line 3 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/283#-NOO52VU8Qe8XrsFerdW:-NOOJzoaB33fFYtliYr8:b-kcr2ug) ([raw file](https://github.com/starkware-libs/blockifier/blob/aefbfdd637f8f07b0d37eea0ce3841cf3dd32fae/scripts/build.sh#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Merging this.
Will still update you about what's being done here after I find Alon.
</blockquote></details>

I moved to build scripts to more common path in repo in order to share the entire code with the build flow

```root_dir="$(cd `dirname $0` && pwd -P)/../"``` == ```DIR = os.path.dirname(__file__)``` in python

**Pull request merged**
