### PR TITLE
Make previous_block_id optional.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/362)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/362)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/362#-NRbEcbB1vfaaQbw5ERP:-NRbEcbB1vfaaQbw5ERQ:b346tkl) ([raw file](https://github.com/starkware-libs/blockifier/blob/5720ffaa963ffa3df621d1c1374b986359e42ce9/crates/native_blockifier/src/storage.rs#L98)):*
> ```XML
>         );
>         let append_txn = append_txn?;
> ```

Isn't there a shorthand for taking `Some(value)`, else another value? 
___
*[`crates/native_blockifier/src/storage.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/362#-NRbESsS3zRy3OosxyE9:-NRbESsS3zRy3OosxyEA:b-379ko9) ([raw file](https://github.com/starkware-libs/blockifier/blob/5720ffaa963ffa3df621d1c1374b986359e42ce9/crates/native_blockifier/src/storage.rs#L101)):*
> ```XML
>         let previous_block_id = match previous_block_id {
>             Some(id) => id,
>             None => (2_u128.pow(64) - 1) as u64,
> ```

Make this a constant: `GENESIS_BLOCK_ID = MAX_U64`.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/362)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/362#-NRbEcbB1vfaaQbw5ERP:-NRbJKZu0ajelp3xrKHa:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5720ffaa963ffa3df621d1c1374b986359e42ce9/crates/native_blockifier/src/storage.rs#L98)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't there a shorthand for taking `Some(value)`, else another value? 
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/storage.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/362#-NRbESsS3zRy3OosxyE9:-NRbIzIE3dVAlmGJK6H0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5720ffaa963ffa3df621d1c1374b986359e42ce9/crates/native_blockifier/src/storage.rs#L101)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Make this a constant: `GENESIS_BLOCK_ID = MAX_U64`. 
</blockquote></details>

Done.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/362)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/362#-NRbEcbB1vfaaQbw5ERP:-NRb_ozGBpbixmG38mYp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5720ffaa963ffa3df621d1c1374b986359e42ce9/crates/native_blockifier/src/storage.rs#L98)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps lose the intermediate variable?
</blockquote></details>

Done.



_Code quote:_
```XML
us_block_id.unwrap_or(GENESIS_BLOCK_ID);
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/362#-:-NRba3XT-qt5XtOSzaLZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
Should we bump version?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/362#-:-NRba5RK6eBy_BnRbfua:btm33uv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by alonh5 — COMMENTED** [review]
If there aren't any other imminent changes, yes.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/362#-:-NRbaIeQ4rS47tk2hCP9:bslbpwe)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
There's going to be a Python PR complying to this change, so I think we should.
Also, build and deploy so that Python can see it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/362#-:-NRbaz_lE16BSvTLM6zi:b-3ld3r9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/362#-:-NRcRoDF1BC-ZrbbNTCN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
