### PR TITLE
build(fee): added new struct and field in preparation for using blob_gas

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1356)

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1356)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1356#-NogOsIx67J8dS3EE6ko:-NogOsIyDqaeykyeg2J8:b149p6) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c3b9820d30ca1d5ace2c6366ab21aedcac6d966/crates/blockifier/src/fee/fee_utils.rs#L29)):*
> ```XML
> pub fn extract_l1_blob_gas_usage(resources: &ResourcesMapping) -> (usize, ResourcesMapping) {
>     let mut vm_resource_usage = resources.0.clone();
>     // TODO(Aner, 21/01/24) change unwrap_or to expect
> ```

Add a dot at the end of the sentence.



_Suggestion:_
```XML
    // TODO(Aner, 21/01/24) change unwrap_or to expect.
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1356#-NogPHzg2Lvetdg2uRwu:-NogPHzg2Lvetdg2uRwv:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c3b9820d30ca1d5ace2c6366ab21aedcac6d966/crates/blockifier/src/fee/fee_utils.rs#L30)):*
> ```XML
>     let mut vm_resource_usage = resources.0.clone();
>     // TODO(Aner, 21/01/24) change unwrap_or to expect
>     let l1_gas_usage = vm_resource_usage.remove(constants::BLOB_GAS_USAGE).unwrap_or(0);
> ```





_Suggestion:_
```XML
let l1_blob_gas_usage = vm_resource_usage.remove(constants::BLOB_GAS_USAGE).unwrap_or(0);
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 4 of 4 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1356)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1356)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 196 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1356#-NolUbuh0Xkx4_aeL3VY:-NolUbuh0Xkx4_aeL3VZ:b-4lgm02) ([raw file](https://github.com/starkware-libs/blockifier/blob/94e67964cf4e701fe6cc8e5ab838b8566db36520/crates/blockifier/src/transaction/objects.rs#L196)):*
> ```XML
> 
> /// A mapping from a transaction execution resource to its actual usage.
> /// TODO(Aner, 21/01/24) change to use the new struct GasAndBlobGasUsages for gas_usage
> ```

1. double slash for TODOs (not part of the docstring)
2. punctuation



_Suggestion:_
```XML
// TODO(Aner, 21/01/24) change to use the new struct GasAndBlobGasUsages for gas_usage.
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1356)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 196 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1356#-NolUbuh0Xkx4_aeL3VY:-Nopiws_9ntJwOJrb6kS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/94e67964cf4e701fe6cc8e5ab838b8566db36520/crates/blockifier/src/transaction/objects.rs#L196)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. double slash for TODOs (not part of the docstring)
2. punctuation
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 4 of 4 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1356)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Comment by aner-starkware** [comment]
PTAL.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1356)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/abi/constants.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1356#-NouSL556Ny-tQRRKZds:-NouSL556Ny-tQRRKZdt:b-ev9axh) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc06430c24d008ce024a937e6903a66bfa5b7324/crates/blockifier/src/abi/constants.rs#L35)):*
> ```XML
> pub const MAX_STEPS_PER_TX: usize = 4_000_000;
> pub const GAS_USAGE: &str = "l1_gas_usage";
> pub const BLOB_GAS_USAGE: &str = "l1_blob_gas_usage";
> ```

where in the code is this constant used for *insertion*?



_Code quote:_
```XML
BLOB_GAS_USAGE
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 196 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1356#-NouS8cUBv3tpp938lHo:-NouS8cUBv3tpp938lHp:bfhkr03) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc06430c24d008ce024a937e6903a66bfa5b7324/crates/blockifier/src/transaction/objects.rs#L196)):*
> ```XML
> 
> /// A mapping from a transaction execution resource to its actual usage.
> // TODO(Aner, 21/01/24) change to use the new struct GasAndBlobGasUsages for gas_usage.
> ```

actually, for forward-compatibility, I think the ResourcesMapping should stay a `HashMap<str, usize>`.
WDYM by this TODO?



_Code quote:_
```XML
// TODO(Aner, 21/01/24) change to use the new struct GasAndBlobGasUsages for gas_usage.
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1356#-:-NoukZeD63O5OKUxu0_n:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/abi/constants.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1356#-NouSL556Ny-tQRRKZds:-NounmoM54tAkZQS9uQw:b-gogkz4) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc06430c24d008ce024a937e6903a66bfa5b7324/crates/blockifier/src/abi/constants.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where in the code is this constant used for *insertion*?
</blockquote></details>

In the next PR, this one is only preparation for it.
https://reviewable.io/reviews/starkware-libs/blockifier/1357

**Review by aner-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1356)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
