### PR TITLE
Change DeprecatedAccountTransactionContext fields from public to private

### PR DESCRIPTION
**Pull request by NirLevi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/961)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/961#-:-Nfh-h-P1Cn0m1qZ0nPv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @NirLevi-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/961#-Nfh-VYh1RKV_CiXAzIt:-Nfh-VYh1RKV_CiXAzIu:brfquoz) ([raw file](https://github.com/starkware-libs/blockifier/blob/6cffd38eb7c9d5ec06d90659f859f09d6b793e14/crates/blockifier/src/transaction/objects.rs#L80)):*
> ```XML
>         Self { transaction_hash, max_fee, version, signature, nonce, sender_address }
>     }
> }
> ```

... I'm surprised there isn't some `derive` attribute for structs that auto-generates this `new` function



_Code quote:_
```XML
impl DeprecatedAccountTransactionContext {
    pub fn new(
        transaction_hash: TransactionHash,
        max_fee: Fee,
        version: TransactionVersion,
        signature: TransactionSignature,
        nonce: Nonce,
        sender_address: ContractAddress,
    ) -> Self {
        Self { transaction_hash, max_fee, version, signature, nonce, sender_address }
    }
}
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/961)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @NirLevi-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/961#-NfioLh33E9nY8k8r796:-NfioLh33E9nY8k8r797:b-mjj8w8) ([raw file](https://github.com/starkware-libs/blockifier/blob/6cffd38eb7c9d5ec06d90659f859f09d6b793e14/crates/blockifier/src/transaction/objects.rs#L71)):*
> ```XML
> impl DeprecatedAccountTransactionContext {
>     pub fn new(
>         transaction_hash: TransactionHash,
> ```

WDYT of another c-tor that accepts a transaction? 
___
*[`crates/blockifier/src/transaction/objects.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/961#-Nfh-VYh1RKV_CiXAzIt:-NfioAyw1e5LSMqOyv9f:b-4wd1hx) ([raw file](https://github.com/starkware-libs/blockifier/blob/6cffd38eb7c9d5ec06d90659f859f09d6b793e14/crates/blockifier/src/transaction/objects.rs#L80)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... I'm surprised there isn't some `derive` attribute for structs that auto-generates this `new` function
</blockquote></details>

Agreed. Nir, have you checked?

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/961)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @NirLevi-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/961#-Nfh-VYh1RKV_CiXAzIt:-Nfj2xcP8djbqDNdx1wZ:b-inrdn8) ([raw file](https://github.com/starkware-libs/blockifier/blob/6cffd38eb7c9d5ec06d90659f859f09d6b793e14/crates/blockifier/src/transaction/objects.rs#L80)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Agreed. Nir, have you checked?
</blockquote></details>

I looked and didn't find something very popular; the `AllArgsConstructor` [here](https://github.com/sokomishalov/lombok-rs/blob/master/src/lib.rs) seems to do it but it only has 40 stars

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/961#-:-Nfk7D7kDPOCOubvMmj_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/961)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/961)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
