### PR TITLE
Dori/use eq trait on exec info

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/525)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/525)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 202 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/525#-NW7fY3i1jY6CWKTyevI:-NW7fY3i1jY6CWKTyevJ:bfdvr0b) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3dc52fcea529f22d70314ac9bc6ae1bd865fc71/crates/blockifier/src/transaction/transactions_test.rs#L202)):*
> ```XML
>             stark_felt!(0_u8),
>             stark_felt!(0_u8),
>             stark_felt!(0_u8),
> ```

I don't understand what the `storage_read_values` should actually contain here... this is just what it contained when I ran the test



_Code quote:_
```XML
            stark_felt!(BALANCE),
            stark_felt!(0_u8),
            stark_felt!(BALANCE),
            stark_felt!(0_u8),
            stark_felt!(0_u8),
            stark_felt!(0_u8),
            stark_felt!(0_u8),
            stark_felt!(0_u8),
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/525)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/525#-NW7fkGy1k0pVbsjHK10:-NW7fkGy1k0pVbsjHK11:b-7wqqdn) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3dc52fcea529f22d70314ac9bc6ae1bd865fc71/crates/blockifier/src/transaction/transactions_test.rs#L114)):*
> ```XML
>     let vm_resources = VmExecutionResources {
>         n_steps,
>         n_memory_holes: 0,
> ```

Why did it change? Same question for all other changes



_Code quote:_
```XML
0
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 202 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/525#-NW7fY3i1jY6CWKTyevI:-NW7hOPA0kTKlbpHwONj:b-q9bdxq) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3dc52fcea529f22d70314ac9bc6ae1bd865fc71/crates/blockifier/src/transaction/transactions_test.rs#L202)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't understand what the `storage_read_values` should actually contain here... this is just what it contained when I ran the test
</blockquote></details>

I'm not sure it's corresponding to [this](https://github.com/starkwareindustries/starkware/blob/9f0313351af79f0a188be9f3fa47766a5887f817/src/starkware/starknet/std_contracts/ERC20/ERC20_base.cairo#L134). Should it?

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/525)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/525)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/525#-NW7fkGy1k0pVbsjHK10:-NWBkTfgCQBBWwIn-so0:bf2u1g) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3dc52fcea529f22d70314ac9bc6ae1bd865fc71/crates/blockifier/src/transaction/transactions_test.rs#L114)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did it change? Same question for all other changes
</blockquote></details>

I checked the numbers in `__validate__` in python and they also changed (meaning they match the rust code). On the other hand, the numbers in the fee transfer are different from python. I compared the numbers in declare and deploy account. I'm checking it.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 202 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/525#-NW7fY3i1jY6CWKTyevI:-NWBmcq48f8oq8QCbTsF:btojbfq) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3dc52fcea529f22d70314ac9bc6ae1bd865fc71/crates/blockifier/src/transaction/transactions_test.rs#L202)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes; added comment
</blockquote></details>

Great.

**Pull request merged**
