### PR TITLE
Gas handling in new syscalls

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a> 
    * **PR #449** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/449" target="_blank">Graphite</a> 
      * **PR #450** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/450" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/450?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpejMK2GYqm7TV3c4d:-NUpejMK2GYqm7TV3c4e:b-dgu96f) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/mod.rs#L59)):*
> ```XML
> pub enum SyscallResponseWrapper<T: SyscallResponse> {
>     Success { gas_counter: StarkFelt, response: T },
>     Failure { gas_counter: StarkFelt, data: Vec<StarkFelt> },
> ```

Are we leaving the name opaque? Isn't it the failure reason?
Perhaps `error_data`, as below? Although maybe the word "error" is redundant here.
I'm basically having monologues with myself... :heart: 



_Code quote:_
```XML
data: Vec<StarkFelt>
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpf-j7-7r6HY_Ai-aU:-NUpf-j7-7r6HY_Ai-aV:b3jb46y) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/mod.rs#L65)):*
> ```XML
>         match self {
>             Self::Success { gas_counter, response } => {
>                 write_felt(vm, *ptr, gas_counter)?;
> ```

WDYT of embedding `ptr` advancing into `write_felt` (or `write` methods in general)?



_Code quote:_
```XML
write_felt
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpf9Vz5gdEsd2JvJF8:-NUpf9Vz5gdEsd2JvJF9:b-5cl2e3) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/mod.rs#L68)):*
> ```XML
>                 *ptr += 1;
>                 // 0 to indicate success.
>                 write_felt(vm, *ptr, 0.into())?;
> ```

Time for all the Qs I never got to ask you: don't you think `Felt::from(0)` is mo explicit? What's your opinion here?
We use `T::from` as a convention, except for errors where we use `.into`, since it gets long...



_Code quote:_
```XML
0.into()
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpffm2EqHpdalkCCgR:-NUpffm313z1be7EdyFg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/mod.rs#L76)):*
> ```XML
>                 *ptr += 1;
>                 // 1 to indicate failure.
>                 write_felt(vm, *ptr, 0.into())?;
> ```





_Suggestion:_
```XML
1
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpg2_q6uhr0Qn_Qq7C:-NUpg2_q6uhr0Qn_Qq7D:bhbzb69) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/mod.rs#L85)):*
> ```XML
>                     write_felt(vm, revert_reason_end, value)?;
>                     revert_reason_end = (revert_reason_end + 1)?;
>                 }
> ```

We have [this](https://github.com/starkware-libs/blockifier-old/blob/612b1b62015b82b88dc3b79459f31e90f1bcb864/crates/blockifier/src/execution/execution_utils.rs#L376) method. Should we add the new segment to the RO segments of the syscall hint processor?



_Code quote:_
```XML
                // Write the error data to a new memory segment.
                let revert_reason_start = vm.add_memory_segment();
                let mut revert_reason_end = revert_reason_start;
                for value in error_data {
                    write_felt(vm, revert_reason_end, value)?;
                    revert_reason_end = (revert_reason_end + 1)?;
                }
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450)* status: all files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpi4L22nO3VYfM22X4:-NUpi4L22nO3VYfM22X5:b-3j6ri3) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/hint_processor.rs#L70)):*
> ```XML
>     #[error(transparent)]
>     VirtualMachineError(#[from] VirtualMachineError),
>     #[error("Syscall error.")]
> ```

Can you explain this line, please? :)



_Code quote:_
```XML
error("Syscall error.")
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpiK9PDUz3M-iRtjWu:-NUpiK9PDUz3M-iRtjWv:b6b9xkt) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/hint_processor.rs#L248)):*
> ```XML
>                 SyscallResponseWrapper::Failure { gas_counter, data }
>             }
>             Err(err) => return Err(err.into()),
> ```

Is it okay that in this case we don't advance the syscall ptr?



_Suggestion:_
```XML
Err(error) => return Err(error.into())
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpi4L22nO3VYfM22X4:-NUpvYcC8ouaNwe_GLhh:b-obnjyc) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/hint_processor.rs#L70)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain this line, please? :)
</blockquote></details>

The syscall should fail the blockifier, it's not that something bad happened in execution. The system call returneda failure, and we should add the failure data to the caller and return to it. For example, out of gas.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpiK9PDUz3M-iRtjWu:-NUpvuNQ0i02U0U1lyZM:bw3d6zf) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/hint_processor.rs#L248)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is it okay that in this case we don't advance the syscall ptr?
</blockquote></details>

We don't have anything to write. This indicates a bug I assume, write? the execution failed for some reason that it shouldn't (Sierra txs can't just fail).
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpf9Vz5gdEsd2JvJF8:-NUq0IHX0z2R3GONWxiv:bbhadtt) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/mod.rs#L68)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Time for all the Qs I never got to ask you: don't you think `Felt::from(0)` is mo explicit? What's your opinion here?
We use `T::from` as a convention, except for errors where we use `.into`, since it gets long...
</blockquote></details>

I think there is no ambiguity in this case. It's `write_felt`, and you give it 0.into().
That said, I don't mind using your syntax.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpg2_q6uhr0Qn_Qq7C:-NUqD77wCloqOvVgs9bN:b-ekugsw) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/mod.rs#L85)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We have [this](https://github.com/starkware-libs/blockifier-old/blob/612b1b62015b82b88dc3b79459f31e90f1bcb864/crates/blockifier/src/execution/execution_utils.rs#L376) method. Should we add the new segment to the RO segments of the syscall hint processor?
</blockquote></details>

What is this struct? Can I get more info?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450)* status: 3 of 6 files reviewed, 9 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 322 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUv7BwJA_5ojuMnwtKn:-NUv7BwKBl3r0YQyD1Fg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee862a5c9fe942c4adfce74a62bf45ad63e0088/crates/blockifier/src/execution/execution_utils.rs#L322)):*
> ```XML
>     ptr: &mut Relocatable,
> ) -> Result<StarkFelt, VirtualMachineError> {
>     let res = felt_to_stark_felt(vm.get_integer(*ptr)?.as_ref());
> ```





_Suggestion:_
```XML
felt
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 468 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUvA0rI8UnzVKRkSamy:-NUvA0rI8UnzVKRkSamz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee862a5c9fe942c4adfce74a62bf45ad63e0088/crates/blockifier/src/execution/execution_utils.rs#L468)):*
> ```XML
>     vm: &VirtualMachine,
>     ptr: &mut Relocatable,
> ) -> Result<Vec<StarkFelt>, TErr> {
> ```





_Suggestion:_
```XML
pub fn read_felt_array<TErr>(
    vm: &VirtualMachine,
    ptr: &mut Relocatable,
) -> Result<Vec<StarkFelt>, TErr>
where TErr: From<StarknetApiError> + From<VirtualMachineError> + From<MemoryError>
{
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 470 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUvA4aFDw0p09z22XE7:-NUvA4aFDw0p09z22XE8:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee862a5c9fe942c4adfce74a62bf45ad63e0088/crates/blockifier/src/execution/execution_utils.rs#L470)):*
> ```XML
> ) -> Result<Vec<StarkFelt>, TErr> {
>     let array_size = felt_from_ptr(vm, ptr)?;
>     let array_data_ptr = vm.get_relocatable(*ptr)?;
> ```





_Suggestion:_
```XML
array_data_start_ptr
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 473 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUvAA389Y4JXRROQvfO:-NUvAA396DCwCQ8GbXkX:bdj8it5) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee862a5c9fe942c4adfce74a62bf45ad63e0088/crates/blockifier/src/execution/execution_utils.rs#L473)):*
> ```XML
>     *ptr += 1;
> 
>     Ok(felt_range_from_ptr(vm, array_data_ptr, usize::try_from(array_size)?)?)
> ```

Don't you think it's better for `felt_range_from_ptr` to advance the pointer, similarly to `felt_from_ptr`?



_Code quote:_
```XML
felt_range_from_ptr
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUv8lmv7mP_5b9_LDcM:-NUv8lmv7mP_5b9_LDcN:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee862a5c9fe942c4adfce74a62bf45ad63e0088/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L21)):*
> ```XML
>     DeprecatedSyscallExecutionError, DeprecatedSyscallHintProcessor,
> };
> use super::execution_utils::{read_felt_array, write_felt};
> ```





_Suggestion:_
```XML
crate
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpiK9PDUz3M-iRtjWu:-NV2kyOR8Sm0vXHaQUGk:bd4f8x9) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/hint_processor.rs#L248)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We don't have anything to write. This indicates a bug I assume, write? the execution failed for some reason that it shouldn't (Sierra txs can't just fail).
</blockquote></details>

So do we really need the other error variants in this enum?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpf9Vz5gdEsd2JvJF8:-NUv9qRy9ILkAmAbASSa:b-kij51u) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/mod.rs#L68)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think there is no ambiguity in this case. It's `write_felt`, and you give it 0.into().
That said, I don't mind using your syntax.
</blockquote></details>

Let's keep the convention then.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpg2_q6uhr0Qn_Qq7C:-NV2l2-r7q6qsh4IbrLX:bytffo1) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/mod.rs#L85)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What is this struct? Can I get more info?
</blockquote></details>

Keeps track of RO segments, but in Cairo 1, as you said, user can write after this data. So perhaps consider sharing this code. Can be done in another PR.

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450)* status: all files reviewed, 10 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpi4L22nO3VYfM22X4:-NV2p7wZ2QeWmpK-TQmv:brxmg25) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/hint_processor.rs#L70)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The syscall should fail the blockifier, it's not that something bad happened in execution. The system call returneda failure, and we should add the failure data to the caller and return to it. For example, out of gas.
</blockquote></details>

What does the syntax of `error(str)` mean?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NV2pP-q8jVd-l8RHu0D:-NV2pP-q8jVd-l8RHu0E:bknwrjc) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee862a5c9fe942c4adfce74a62bf45ad63e0088/crates/blockifier/src/execution/syscalls/mod.rs#L84)):*
> ```XML
>                 // Write the start and end pointers of the error data.
>                 vm.insert_value(*ptr, revert_reason_start)?;
>                 *ptr += 1;
> ```

Consider adding a `write_relocatable` function that also advances the `ptr`.



_Code quote:_
```XML
                vm.insert_value(*ptr, revert_reason_start)?;
                *ptr += 1;
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 473 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUvAA389Y4JXRROQvfO:-NV36u2Y1JQSJtLS0uX3:b-bbcok8) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee862a5c9fe942c4adfce74a62bf45ad63e0088/crates/blockifier/src/execution/execution_utils.rs#L473)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Don't you think it's better for `felt_range_from_ptr` to advance the pointer, similarly to `felt_from_ptr`?
</blockquote></details>

It seems less convinient in the 2 places its called.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpi4L22nO3VYfM22X4:-NV37G2s48REBYxIoVDU:b-oye1rn) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/hint_processor.rs#L70)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does the syntax of `error(str)` mean?
</blockquote></details>

I don't think I understand what you're asking. This syntax is an attribute for `thiserror` Error derive. It's what get's displayed in the Debug/Display of the Error.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpiK9PDUz3M-iRtjWu:-NV37ZQ_3zt4X8cwIIvR:b-b8okdq) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/hint_processor.rs#L248)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So do we really need the other error variants in this enum?
</blockquote></details>

What do you suggest I do when these errors are thrown? There are a few places I've seen, and maybe more I haven't that need to handle these error from the vm.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpg2_q6uhr0Qn_Qq7C:-NV38sfu3nVxAkiMIb0Q:bet2wx7) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/mod.rs#L85)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Keeps track of RO segments, but in Cairo 1, as you said, user can write after this data. So perhaps consider sharing this code. Can be done in another PR.
</blockquote></details>

I used the load_data() method(), that's practically what RO does.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUv8lmv7mP_5b9_LDcM:-NV3JXEJDevOF3FJr67x:bt4kyol) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee862a5c9fe942c4adfce74a62bf45ad63e0088/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L21)):*
> ```XML
>     DeprecatedSyscallExecutionError, DeprecatedSyscallHintProcessor,
> };
> use super::execution_utils::{read_felt_array, write_felt};
> ```

`super -> crate`, please?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpi4L22nO3VYfM22X4:-NV3JnVBCdfQsNLh4IB3:b-ucfkn4) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/hint_processor.rs#L70)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think I understand what you're asking. This syntax is an attribute for `thiserror` Error derive. It's what get's displayed in the Debug/Display of the Error.
</blockquote></details>

Thanks.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUpiK9PDUz3M-iRtjWu:-NV3JqLRAgtxfSJVnQzI:b-oi8ubk) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff243034a4cd003f3bb96494b8f15ff709c35878/crates/blockifier/src/execution/syscalls/hint_processor.rs#L248)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What do you suggest I do when these errors are thrown? There are a few places I've seen, and maybe more I haven't that need to handle these error from the vm.
</blockquote></details>

I'll TAL separately.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUv8lmv7mP_5b9_LDcM:-NV3MAlv0uNFr_h30gv_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee862a5c9fe942c4adfce74a62bf45ad63e0088/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`super -> crate`, please?
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/450#-:-NV3PMi2D1h5ZvrC58dR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/450#-NUv8lmv7mP_5b9_LDcM:-NV3PIGf1noT_78Ds9Yg:b-x2esgh) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee862a5c9fe942c4adfce74a62bf45ad63e0088/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Any idea how can I make it the rule when fixing? Gilad didn't manage to do so.

**Pull request merged**
