### PR TITLE
chore(fee): update os resources to include 4844 calculations

### PR DESCRIPTION
**Pull request by dafnamatsry**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1498)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1498)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/blockifier/src/versioned_constants.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-NqY2nmWAb_34j9Koc8u:-NqY2nmWAb_34j9Koc8v:bncxvec) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aeeef948b40938595aeea397ac9d98969612ac3/crates/blockifier/src/versioned_constants.rs#L182)):*
> ```XML
>     // Resources needed for the OS to compute the KZG commitment info, as a factor of the data
>     // segment length.
>     compute_os_kzg_commitment_info: ExecutionResources,
> ```

Mention that it does not include `poseidon_hash_many` cost



_Code quote:_
```XML
    compute_os_kzg_commitment_info: ExecutionResources,
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-NqY2aRr0skpM0wgHClv:-NqY2aRr0skpM0wgHClw:bunflsa) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aeeef948b40938595aeea397ac9d98969612ac3/crates/blockifier/src/execution/contract_class.rs#L251)):*
> ```XML
> 
> /// Returns the VM resources required for running `poseidon_hash_many` in the Starknet OS.
> pub fn poseidon_hash_many_cost(data_length: usize) -> ExecutionResources {
> ```

Do you see a better place for this function? 
If not, please add a TODO.



_Code quote:_
```XML
pub fn poseidon_hash_many_cost(data_length: usize) -> ExecutionResources {
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-NqY4GgN0N5jU-7pAnnK:-NqY4GgN0N5jU-7pAnnL:b22pzrt) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aeeef948b40938595aeea397ac9d98969612ac3/crates/blockifier/src/fee/actual_cost.rs#L154)):*
> ```XML
>                 .fee_token_address(&self.tx_context.tx_info.fee_type()),
>         );
>         let da_gas = get_da_gas_cost(state_changes_count, use_kzg_da);
> ```

Add a TODO to compute the DA size and pass it instead `state_changes_count`
(don't do it because there are 23523432 tests to refactor) 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 476 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-NqY59gv2vUJJpsysInV:-NqY59gv2vUJJpsysInW:br28b51) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aeeef948b40938595aeea397ac9d98969612ac3/crates/blockifier/src/transaction/transactions_test.rs#L476)):*
> ```XML
>             (abi_constants::N_STEPS_RESOURCE.to_string(), 509),
>             (POSEIDON_BUILTIN_NAME.to_string(), 3),
>         ];
> ```

Can you change the tests here to depend on a single magic number - the DA size?
Maintaining these tests is not fun :)
(it's okay to repeat the calculation IMO: `da_size * resources + poseidon_cost(da_size)`)



_Code quote:_
```XML
    if use_kzg_da {
        let kzg_da_resources = [
            (RANGE_CHECK_BUILTIN_NAME.to_string(), 68),
            (abi_constants::N_STEPS_RESOURCE.to_string(), 509),
            (POSEIDON_BUILTIN_NAME.to_string(), 3),
        ];
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1498)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-NqY2nmWAb_34j9Koc8u:-NqaL9nb-ER-15FvGEC8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aeeef948b40938595aeea397ac9d98969612ac3/crates/blockifier/src/versioned_constants.rs#L182)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Mention that it does not include `poseidon_hash_many` cost
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-NqY2aRr0skpM0wgHClv:-NqaMXIBAeqZs12C2dEM:bty8g59) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aeeef948b40938595aeea397ac9d98969612ac3/crates/blockifier/src/execution/contract_class.rs#L251)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Do you see a better place for this function? 
If not, please add a TODO.
</blockquote></details>

Maybe execution_utils.rs?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 476 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-NqY59gv2vUJJpsysInV:-NqaZshu74zuK9IGy-yz:bvg7s0u) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aeeef948b40938595aeea397ac9d98969612ac3/crates/blockifier/src/transaction/transactions_test.rs#L476)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you change the tests here to depend on a single magic number - the DA size?
Maintaining these tests is not fun :)
(it's okay to repeat the calculation IMO: `da_size * resources + poseidon_cost(da_size)`)
</blockquote></details>

Done. I reused the code in versioned_constants.

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-:-Nqbc8LR3LtE0xEjChTU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-NqY2aRr0skpM0wgHClv:-NqbaTab9rhGI8nn4noQ:bb6u032) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aeeef948b40938595aeea397ac9d98969612ac3/crates/blockifier/src/execution/contract_class.rs#L251)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Maybe execution_utils.rs?
</blockquote></details>

Cool

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1498)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-NqY2aRr0skpM0wgHClv:-Nqbxl3gAXbxuuL0VF-Q:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aeeef948b40938595aeea397ac9d98969612ac3/crates/blockifier/src/execution/contract_class.rs#L251)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Cool
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1498#-:-NqflFXb7h77LIZkOnvt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
