### PR TITLE
Merge main-v0.12.1 into main

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/759)

### CODE REVIEW

**Comment by alonh5** [comment]
[Src](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main-v0.12.1#diff-783357e44344438283415c291d26cd2bb0fc6a53a607037495d43459cea04f12) [Dst](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main#diff-783357e44344438283415c291d26cd2bb0fc6a53a607037495d43459cea04f12) crates/blockifier/feature_contracts/cairo1/compiled/account_contract.casm.json
[Src](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main-v0.12.1#diff-c9b60ac7ffd07ea976565a4f73ee20657f90bb003d77440d956368786801b80b) [Dst](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main#diff-c9b60ac7ffd07ea976565a4f73ee20657f90bb003d77440d956368786801b80b) crates/blockifier/src/execution/syscalls/syscalls_test.rs
[Src](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main-v0.12.1#diff-ec73f506940d2ffac36e120aa9bcfc30205cb6fd31180e10784759375d03bb26) [Dst](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main#diff-ec73f506940d2ffac36e120aa9bcfc30205cb6fd31180e10784759375d03bb26) crates/blockifier/src/transaction/transactions_test.rs
[Src](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main-v0.12.1#diff-166eca1e561f1617bfb4a865282d5725bacc60ee8a85da3aed2a384a6173f5aa) [Dst](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main#diff-166eca1e561f1617bfb4a865282d5725bacc60ee8a85da3aed2a384a6173f5aa) crates/native_blockifier/src/storage.rs

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 7 files at r3, 4 of 6 files at r4, 14 of 17 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/759)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/759)* status: 26 of 31 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/759#-N_i1omzAMbvcWnUOycF:-N_i1on-2w5Vu3YCQquX:bjw6ri0) (no related file):*
I had to revert Gilad's PR: [Storage cleanup](https://reviewable.io/reviews/starkware-libs/blockifier/731) because of conflicting papyrus and sn API versions.
After this merge, I'll update the versions and cherry-pick this PR back into main.

___

**Review by alonh5 — COMMENTED** [review]
Corresponding Python [commit update](https://reviewable.io/reviews/starkware-industries/starkware/30947)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/759#-:-N_i4Dsl0VGe159FLE2p:b-a7w7c5)* status: 26 of 31 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, @giladchase, and @noaov1)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/759)* status: 26 of 31 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dorimedini-starkware, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/759#-N_i1omzAMbvcWnUOycF:-N_iLEho5hQU42APPPPp:b-9f49iy) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I had to revert Gilad's PR: [Storage cleanup](https://reviewable.io/reviews/starkware-libs/blockifier/731) because of conflicting papyrus and sn API versions.
After this merge, I'll update the versions and cherry-pick this PR back into main.
</blockquote></details>

Where did you revert it?
Please link to the Python PR. 

___

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/759)* status: 26 of 31 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/759#-N_i1omzAMbvcWnUOycF:-N_iM1kmEIXdXJR1l8Ey:bs1kdlq) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where did you revert it?
Please link to the Python PR. 
</blockquote></details>

I reverted the changes here in `sotrage.rs` and in`lib.rs`.
The link to the python PR is above, I'll copy it here:
Corresponding Python [commit update](https://reviewable.io/reviews/starkware-industries/starkware/30947)

___

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/759)* status: 26 of 31 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 263 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/759#-N_iP9tf9xOPBC5v2xXo:-N_iP9tf9xOPBC5v2xXp:b-w8lgux) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad129eb5207a943c1c50d617c51124de1ed42b07/crates/blockifier/src/transaction/transactions_test.rs#L263)):*
> ```XML
> }
> 
> <<<<<<< HEAD
> ```

This and the following similar conflicts in the tests are just `n_steps` value changes.

**Pull request closed without merging**
