### PR TITLE
Merge main-v0.13.1 into main

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1780)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main-v0.13.1#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e) [Dst](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e) Cargo.lock
[Src](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main-v0.13.1#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) [Dst](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) Cargo.toml
[Src](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main-v0.13.1#diff-59bda33934a9347c3c17bc26b66692dff387808f8f1628da0204cf3f08a29ea8) [Dst](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main#diff-59bda33934a9347c3c17bc26b66692dff387808f8f1628da0204cf3f08a29ea8) crates/blockifier/src/fee/gas_usage.rs
[Src](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main-v0.13.1#diff-c60befa67313a64cd2f9ad156230755f2c7b08840d587adc35eabb224651da72) [Dst](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main#diff-c60befa67313a64cd2f9ad156230755f2c7b08840d587adc35eabb224651da72) crates/blockifier/src/fee/gas_usage_test.rs
[Src](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main-v0.13.1#diff-d04d552c3a81553b8faab105c9c4747436e500fd358eddf33f60c09b8cb4ed8c) [Dst](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main#diff-d04d552c3a81553b8faab105c9c4747436e500fd358eddf33f60c09b8cb4ed8c) crates/blockifier/src/transaction/account_transaction.rs
[Src](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main-v0.13.1#diff-16626e3925925b8f6e86403a3786831d26edc78b97f81324255442e45226c73c) [Dst](https://github.com/starkware-libs/blockifier/compare/534daaa059dda933fa2de4bb94578095f96e39d2..main#diff-16626e3925925b8f6e86403a3786831d26edc78b97f81324255442e45226c73c) crates/blockifier/src/utils_test.rs

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1780)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1780#-:-NvB7fNaA7lCRb95Ym2u:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1780)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1780#-:-NvBDLKx3aaH8DAZvF48:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
