### PR TITLE
Elin/merge main v0.13.0 into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1279)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 5 files at r3, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1279)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 5 of 7 files at r8, 3 of 3 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1279)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_validator.rs` line 273 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1279#-Nm6qENl49-JcfSpKIb4:-Nm6qENl49-JcfSpKIb5:bmeyqrb) ([raw file](https://github.com/starkware-libs/blockifier/blob/c8e5b2a8399cd70782ee6fb4d06b07cd7b82cd84/crates/native_blockifier/src/py_validator.rs#L273)):*
> ```XML
>     fn tx_executor(&mut self) -> &mut TransactionExecutor<PyStateReader> {
>         self.tx_executor.as_mut().expect("Transaction executor should be initialized")
>     }
> ```

Why did you remove it?



_Code quote:_
```XML
    fn tx_executor(&mut self) -> &mut TransactionExecutor<PyStateReader> {
        self.tx_executor.as_mut().expect("Transaction executor should be initialized")
    }
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1279)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 273 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1279#-Nm6qENl49-JcfSpKIb4:-Nm6vQlT37EtHS3nJY9X:bhrzxwp) ([raw file](https://github.com/starkware-libs/blockifier/blob/c8e5b2a8399cd70782ee6fb4d06b07cd7b82cd84/crates/native_blockifier/src/py_validator.rs#L273)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you remove it?
</blockquote></details>

I think Gilad removed it in `main-v0.13.0` (with the setup and teardown methods).

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1279)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1279)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`Cargo.toml` line 39 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1279#-Nm6-9Nu-GexzjXZBO2H:-Nm7-EKo41F1p4L-dwX4:b505v0l) ([raw file](https://github.com/starkware-libs/blockifier/blob/c9e27e0060251a5fcf0cd2b811421f015cf12255/Cargo.toml#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think this version is missing the `enforce_file_exists` flag.
@yair-starkware which version
</blockquote></details>

This one was released with the requirement to be `>0.2.1` and contain this flag.
___
*[`crates/native_blockifier/src/py_validator.rs` line 273 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1279#-Nm6qENl49-JcfSpKIb4:-Nm7-Ma45vvmg6ZEErL9:b-rqhzm5) ([raw file](https://github.com/starkware-libs/blockifier/blob/c8e5b2a8399cd70782ee6fb4d06b07cd7b82cd84/crates/native_blockifier/src/py_validator.rs#L273)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think Gilad removed it in `main-v0.13.0` (with the setup and teardown methods).
</blockquote></details>

[Appears in `PyBlockExecutor`](https://github.com/starkware-libs/blockifier/blob/93717a4f20b1dfe406d60b3fbecff8612bc99832/crates/native_blockifier/src/py_block_executor.rs#L208-L211).

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1279)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1279#-:-Nm75Q4U7krvL40dWvT4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1279)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
