### PR TITLE
test(execution): add get_execution_info scenario to test

### PR DESCRIPTION
**Pull request by ArniStarkware**
test(execution): add get_execution_info scenario to test_validate_accounts_tx

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1486)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1441 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1486#-NqRT2xE2IZqTtG8Jttk:-NqRT2xE2IZqTtG8Jttl:bw2dqq0) ([raw file](https://github.com/starkware-libs/blockifier/blob/20175077ac0e21a74e966afe859a22ea7898caf5/crates/blockifier/src/transaction/transactions_test.rs#L1441)):*
> ```XML
>     if let CairoVersion::Cairo1 = cairo_version {
>         // Trying to use the syscall get_block_hash (forbidden).
>         // TODO(Arni, 12/12/2023): Test this scenario with the constructor.
> ```

We are :)



_Code quote:_
```XML
        // TODO(Arni, 12/12/2023): Test this scenario with the constructor.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1486)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @MohammadNassar1, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/feature_contracts/cairo1/compiled/account_faulty.casm.json` line 3153 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1486#-NqRTCtq2X5EHgJoS0Bo:-NqRTCtq2X5EHgJoS0Bp:bnnmqme) ([raw file](https://github.com/starkware-libs/blockifier/blob/357c63af38cb8272e7d77611887a39e887c127c9/crates/blockifier/feature_contracts/cairo1/compiled/account_faulty.casm.json#L3153)):*
> ```JSON
>     ]
>   }
> }
> ```

@noaov1 Should we fix this? I just committed the result of the compilation.

**Review by MohammadNassar1 — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1486#-:-NqSW6Wn-6WhhuBmMF7W:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @TzahiTaub)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1481 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1486#-NqXnGHM8PfQnTstO5B6:-NqXnGHM8PfQnTstO5B7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/dfb193ad880114952a1237d812b6caed5d16048d/crates/blockifier/src/transaction/transactions_test.rs#L1481)):*
> ```XML
>                 ]),
>                 ..default_args
>             },
> ```





_Suggestion:_
```XML
        let account_tx = create_account_tx_for_validate_test(
            // Calling the syscall get_execution_info and get block_info which was modified for validate.
            nonce_manager,
            FaultyAccountTxCreatorArgs {
                scenario: GET_EXECUTION_INFO,
                contract_address_salt: salt_manager.next_salt(),
                additional_data: Some(vec![
                    StarkFelt::from(CURRENT_BLOCK_NUMBER_FOR_VALIDATE),
                    StarkFelt::from(CURRENT_BLOCK_TIMESTAMP_FOR_VALIDATE),
                    StarkFelt::from(0_u64), // Sequencer address for validate.
                ]),
                ..default_args
            },
```

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1486)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @TzahiTaub)

**Pull request merged**
