### PR TITLE
feat: use jemalloc in native blockifier

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1750)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1750)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-NuPRjeFEaFViMhTumlD:-NuPRjeFEaFViMhTumlE:b1ozv3) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/34583)

___

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1750)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/Cargo.toml` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-NuPVRk1AnyXuevXGlXJ:-NuPVRk1AnyXuevXGlXK:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/093b3290fd29d0e0a13adea2332f23b486314323/crates/native_blockifier/Cargo.toml#L15)):*
> ```TOML
> extension-module = ["pyo3/extension-module"]
> jemalloc = []
> testing = []
> ```





_Suggestion:_
```TOML
[features]
# Required for `cargo test` to work with Pyo3.
# On Python, make sure to compile this with the extension-module feature enabled.
# https://pyo3.rs/v0.19.1/faq#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror
extension-module = ["pyo3/extension-module"]
jemalloc = []
testing = []
```
___
*[`crates/native_blockifier/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-NuPWGRV3b9V3IecK-ZO:-NuPWGRV3b9V3IecK-ZP:b-kthzvv) ([raw file](https://github.com/starkware-libs/blockifier/blob/093b3290fd29d0e0a13adea2332f23b486314323/crates/native_blockifier/src/lib.rs#L11)):*
> ```XML
> // Override default allocator.
> #[cfg(jemalloc)]
> #[global_allocator]
> ```

We run this line only if the blockifier was compiled with the `jemalloc` flag, right? 



_Suggestion:_
```XML
#[cfg(jemalloc)]
// Override default allocator.
#[global_allocator]
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-:-NuPyzsh9h7Y9bLeMfuv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-:-Nv5kQH79h0sTTzqazmP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Comment by avi-starkware** [comment]
*[`Cargo.toml` line 34 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-O0Nj900-ucE9vRYLTP3:-O0Nj900-ucE9vRYLTP4:b-4rtgxe) ([raw file](https://github.com/starkware-libs/blockifier/blob/1eab12b07cf641760416105aedd90eb838aaaefe/Cargo.toml#L34)):*
Are you sure you shouldn't be using `tikv-jemallocator`? In the crate [page](https://crates.io/crates/jemallocator) they say:

> The project is also published as `jemallocator` for historical reasons. The two crates are the same except names. For new projects, it's recommended to use `tikv-xxx` versions instead.



_Code quote:_
```TOML
jemallocator = "0.5.4"
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1750)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @dorimedini-starkware)

___
*[`Cargo.toml` line 34 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-O0Nj900-ucE9vRYLTP3:-O0NqBVK2WQ-zb91Wo-O:b-papxiy) ([raw file](https://github.com/starkware-libs/blockifier/blob/1eab12b07cf641760416105aedd90eb838aaaefe/Cargo.toml#L34)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Are you sure you shouldn't be using `tikv-jemallocator`? In the crate [page](https://crates.io/crates/jemallocator) they say:

> The project is also published as `jemallocator` for historical reasons. The two crates are the same except names. For new projects, it's recommended to use `tikv-xxx` versions instead.
</blockquote></details>

Hmmm, let's change it

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1750)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/BUILD` line 9 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-O0cn0xkB0E7rtGw8iaS:-O0cn0xkB0E7rtGw8iaT:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d229a671d011844a99167329bbc876edbd8e7fa4/crates/blockifier/BUILD#L9)):*
> ```Starlark
>     crate_features = [
>         "concurrency",
>         "jemalloc",
> ```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1750)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/BUILD` line 9 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-O0cn0xkB0E7rtGw8iaS:-O0cu5-oE8SWyZLVw9o0:b-s418kd) ([raw file](https://github.com/starkware-libs/blockifier/blob/d229a671d011844a99167329bbc876edbd8e7fa4/crates/blockifier/BUILD#L9)):*
> ```Starlark
>     crate_features = [
>         "concurrency",
>         "jemalloc",
> ```

I'll do you one better

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-:-O0cuoZg3WOYWPRY-q0m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/BUILD` line 9 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1750#-O0cn0xkB0E7rtGw8iaS:-O0cuj4HARD0wNw6AoXE:b32vi3) ([raw file](https://github.com/starkware-libs/blockifier/blob/d229a671d011844a99167329bbc876edbd8e7fa4/crates/blockifier/BUILD#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I'll do you one better
</blockquote></details>

:0

**Pull request merged**
