### PR TITLE
refactor(concurrency, execution): add concurrency_mode parameter to T…

### PR DESCRIPTION
**Pull request by barak-b-starkware**
…ransfersGenerator::new

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1966)

### CODE REVIEW

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1966#-:-NzhtKR86O7Ydex9_muY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware, @meship-starkware, and @noaov1)

**Comment by avi-starkware** [comment]
This PR is redundant.
I have a PR that adds a config struct for the transfers generator.
#1945 
I think we should merge that and not cause a merge conflict.

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1966)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @barak-b-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1966#-NzviHOiBcEtpuLomWlK:-NzviHOiBcEtpuLomWlL:b-fj05td) ([raw file](https://github.com/starkware-libs/blockifier/blob/57c7b8537a2e0c54f3d06dadb0ad381ac4b023f8/crates/blockifier/src/test_utils/transfers_generator.rs#L124)):*
> ```XML
>         Self::new(false)
>     }
> }
> ```

Can be removed, IMO.



_Code quote:_
```XML
impl Default for TransfersGenerator {
    fn default() -> Self {
        Self::new(false)
    }
}
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1966)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1966#-NzviHOiBcEtpuLomWlK:-Nzyfu97-KCr-_w2xpFz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/57c7b8537a2e0c54f3d06dadb0ad381ac4b023f8/crates/blockifier/src/test_utils/transfers_generator.rs#L124)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can be removed, IMO.
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1966#-:-O--WNPC2y6QtX5z06yj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @meship-starkware)

**Pull request merged**
