### PR TITLE
Merge main-v0.12.3 into main

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 5 files at r3, 1 of 3 files at r4, 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by giladchase — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008#-:-Nh70GLg0hXRgCbVrrWu:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @elintul, and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dorimedini-starkware, and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 526 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1008#-Nh6ym4w4NeK-mqpqH-I:-Nh723bp6UhLL8PseNsR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a6f0833540ac4e320c2f01bc0b0d588de260e581/crates/blockifier/src/transaction/account_transaction.rs#L526)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please revert this change - this is a mistake.
deploy_account txs are non-revertible, and they get a validation context initialized separately.
These two functions currently expect the `__execute__` execution context...
[PR to remove this redundant param... PTAL](https://reviewable.io/reviews/starkware-libs/blockifier/1009)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 390 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1008#-Nh75FLu9tA6asOs_vfr:-Nh75FLu9tA6asOs_vfs:b2awpjh) ([raw file](https://github.com/starkware-libs/blockifier/blob/555a88f1b76ef7386140e8f6f4c405561799d8b3/crates/blockifier/src/test_utils.rs#L390)):*
> ```XML
>         let mut context = EntryPointExecutionContext::new_validate(
>             &block_context,
>             &AccountTransactionContext::Deprecated(DeprecatedAccountTransactionContext::default()),
> ```

why...? please sync with @MohammadNassar1 on this



_Code quote:_
```XML
&AccountTransactionContext::Deprecated(DeprecatedAccountTransactionContext::default())
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dorimedini-starkware, and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 526 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1008#-Nh6ym4w4NeK-mqpqH-I:-Nh7AlDv-bTXHdy2eM4Y:b-bnsyh1) ([raw file](https://github.com/starkware-libs/blockifier/blob/a6f0833540ac4e320c2f01bc0b0d588de260e581/crates/blockifier/src/transaction/account_transaction.rs#L526)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, that was a real issue. DeployAccount's c-tor has to get `validate` ctx

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @elintul)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 526 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1008#-Nh6ym4w4NeK-mqpqH-I:-Nh7BKAJ5adR0plpVINP:b-twnuir) ([raw file](https://github.com/starkware-libs/blockifier/blob/a6f0833540ac4e320c2f01bc0b0d588de260e581/crates/blockifier/src/transaction/account_transaction.rs#L526)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No, that was a real issue. DeployAccount's c-tor has to get `validate` ctx
</blockquote></details>

what??? why? this is executed in the `__execute__` phase...
waiting with my above PR until you merge

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @elintul, @MohammadNassar1, and @NirLevi-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 390 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1008#-Nh75FLu9tA6asOs_vfr:-Nh7BZbS2kQY-e1fGezJ:bhf7jwf) ([raw file](https://github.com/starkware-libs/blockifier/blob/555a88f1b76ef7386140e8f6f4c405561799d8b3/crates/blockifier/src/test_utils.rs#L390)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why...? please sync with @MohammadNassar1 on this
</blockquote></details>

Maybe @NirLevi-starkware?
Anyway I copied the change from `execute_directly` which has the same purpose.
It shouldn't block this merge.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @elintul, @MohammadNassar1, and @NirLevi-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 526 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1008#-Nh6ym4w4NeK-mqpqH-I:-Nh7Bs8YEds39Ww1rKvK:b-pu0e0r) ([raw file](https://github.com/starkware-libs/blockifier/blob/a6f0833540ac4e320c2f01bc0b0d588de260e581/crates/blockifier/src/transaction/account_transaction.rs#L526)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what??? why? this is executed in the `__execute__` phase...
waiting with my above PR until you merge
</blockquote></details>

Because we run the c-tor before the validate, so any DDOS you can do with validate, can be done with the c-tor.

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1008)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware and @elintul)

**Pull request merged**
