### PR TITLE
perf(execution): benchmark random transfers

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1824)

### CODE REVIEW

**Comment by avi-starkware** [comment]
+reviewer:@Yoni-Starkware 
+reviewer:@OriStarkware

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
Can you move this dir from the native to the blockfiier?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1824#-:-Nwhkh15BC5cttqwrElN:b-5tzacb)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @OriStarkware)

___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1824#-NwhkSsjCDYzw1Gh5FuL:-NwhkSsjCDYzw1Gh5FuM:bg39ltc) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe17104561dca7015b31c6f9276e65d96043cd99/crates/native_blockifier/bench/blockifier_bench.rs#L69)):*
> ```XML
> ) {
>     let n_accounts = accounts.len();
>     let recipient_account = random_generator.gen::<usize>() % n_accounts;
> ```

Better to keep this function deterministic - i.e., pass the recipient account as an argument



_Code quote:_
```XML
fn do_transfer(
    sender_account: usize,
    accounts: &[ContractAddress],
    nonce_manager: &mut NonceManager,
    block_context: &BlockContext,
    state: &mut CachedState<DictStateReader>,
    random_generator: &mut rand::rngs::StdRng,
) {
    let n_accounts = accounts.len();
    let recipient_account = random_generator.gen::<usize>() % n_accounts;
```

**Review by OriStarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1824)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1824#-NwieF3c7clhSG57u3Uj:-NwieF3c7clhSG57u3Uk:b-uvp2j5) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe17104561dca7015b31c6f9276e65d96043cd99/crates/native_blockifier/bench/blockifier_bench.rs#L29)):*
> ```XML
> 
> const N_ACCOUNTS: u16 = 10000;
> const RANDOM_SEED: u64 = 0;
> ```

Random_seed can be confusing because the seed is not random. Consider randomization_seed or simply seed.



_Code quote:_
```XML
RANDOM_SEED
```

**Review by avi-starkware — COMMENTED** [review]
I did it in a follow-up PR: #1836

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1824#-:-Nwj7z-V8Nc_HeQgDJOm:blg1fkq)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1824#-NwieF3c7clhSG57u3Uj:-Nwj3C585wkQdhGmribq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe17104561dca7015b31c6f9276e65d96043cd99/crates/native_blockifier/bench/blockifier_bench.rs#L29)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Random_seed can be confusing because the seed is not random. Consider randomization_seed or simply seed.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1824#-NwhkSsjCDYzw1Gh5FuL:-Nwj38AZ4u-TF9bKGysR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe17104561dca7015b31c6f9276e65d96043cd99/crates/native_blockifier/bench/blockifier_bench.rs#L69)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Better to keep this function deterministic - i.e., pass the recipient account as an argument
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1824#-:-NwjIxEQ-n_bdvSAGuC0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @OriStarkware)

**Review by OriStarkware — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1824)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1824#-:-Nwmn1jm0RGnmIMLUMjj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
