### PR TITLE
test(concurrency): test finish_execution_during_commit

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1904)

### CODE REVIEW

**Comment by avi-starkware** [comment]
+reviewer:@meship-starkware

**Review by noaov1 — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1904)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1904#-NyuK6fi-2eWfW20Hf5S:-NyuK6fjDpp_ObwHSKFm:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/644e4612eb45c6526025d7964bf4b023171f8f9f/crates/blockifier/src/concurrency/scheduler_test.rs#L127)):*
> ```XML
> #[rstest]
> #[case::target_index_lt_validation_index(0, 3)]
> #[case::target_index_gt_validation_index(1, 0)]
> ```





_Suggestion:_
```XML
#[case::reduces_validation_index(0, 3)]
#[case::does_not_reduce_validation_index(1, 0)]
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1904)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1904#-NyuK6fi-2eWfW20Hf5S:-NyukEfy4RuoH8EcQ__8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/644e4612eb45c6526025d7964bf4b023171f8f9f/crates/blockifier/src/concurrency/scheduler_test.rs#L127)):*
> ```XML
> #[rstest]
> #[case::target_index_lt_validation_index(0, 3)]
> #[case::target_index_gt_validation_index(1, 0)]
> ```

Done.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1904)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
