### PR TITLE
fix: make the test pass wthout using magic numbers

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)

### CODE REVIEW

**Comment by meship-starkware** [comment]
I am still going. There are more tests to fix, but I would like a review of my changes.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NrUE2bG0JvMyNYZxehz:-NrUE2bG0JvMyNYZxei-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2081a715446a6a4f850383c7b17c33ec83e0cfb6/crates/blockifier/src/test_utils.rs#L362)):*
> ```XML
> }
> 
> pub fn create_one_syscall(syscall_selector: DeprecatedSyscallSelector) -> (usize, usize) {
> ```





_Suggestion:_
```XML
pub fn get_syscall_resources(syscall_selector: SyscallSelector) -> ExecutionResources {
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NrUEiqeAgHe1YpbLVL9:-NrUEiqeAgHe1YpbLVLA:b-kvue0h) ([raw file](https://github.com/starkware-libs/blockifier/blob/2081a715446a6a4f850383c7b17c33ec83e0cfb6/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L156)):*
> ```XML
>         ..Default::default()
>     };
>     let (n_steps, range_check) = create_one_syscall(DeprecatedSyscallSelector::LibraryCall);
> ```

Add this to the total resources using a simple `+`



_Suggestion:_
```XML
let library_call_os_resources = create_one_syscall(DeprecatedSyscallSelector::LibraryCall);
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NrUE2bG0JvMyNYZxehz:-NrUwIE54zEyWCVX0Lwv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2081a715446a6a4f850383c7b17c33ec83e0cfb6/crates/blockifier/src/test_utils.rs#L362)):*
> ```XML
> }
> 
> pub fn create_one_syscall(syscall_selector: DeprecatedSyscallSelector) -> (usize, usize) {
> ```

Done.
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NrUEiqeAgHe1YpbLVL9:-NrUwK0sCSuihGsY0t0u:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2081a715446a6a4f850383c7b17c33ec83e0cfb6/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L156)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add this to the total resources using a simple `+`
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NrUE2bG0JvMyNYZxehz:-Nr_TSU88fwigTe976UC:bf83zmg) ([raw file](https://github.com/starkware-libs/blockifier/blob/2081a715446a6a4f850383c7b17c33ec83e0cfb6/crates/blockifier/src/test_utils.rs#L362)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Forgot to push?

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 505 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NsCHBBr3jRRc6f-k7ak:-NsCHBBr3jRRc6f-k7al:ba854ie) ([raw file](https://github.com/starkware-libs/blockifier/blob/e005df7bbee0384dffa866d046b3e3e89eda4f9e/crates/blockifier/resources/versioned_constants.json#L505)):*
> ```JSON
>         ]
>     }
> }
> ```

Revert?
___
*[`crates/blockifier/src/test_utils.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NrUE2bG0JvMyNYZxehz:-NsCHN2L0wDdM82n05or:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/2081a715446a6a4f850383c7b17c33ec83e0cfb6/crates/blockifier/src/test_utils.rs#L362)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Forgot to push?
</blockquote></details>

?

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NrUE2bG0JvMyNYZxehz:-NsCL3e78gUlDiruWzf9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2081a715446a6a4f850383c7b17c33ec83e0cfb6/crates/blockifier/src/test_utils.rs#L362)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NrUE2bG0JvMyNYZxehz:-NsCNN6ADQLHanvWXs6Q:b-ykghfh) ([raw file](https://github.com/starkware-libs/blockifier/blob/2081a715446a6a4f850383c7b17c33ec83e0cfb6/crates/blockifier/src/test_utils.rs#L362)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

SyscallSelector is private and the DeprecatedSyscallSelector seems to include nondeprecated syscalls. 
 https://github.com/starkware-libs/blockifier/blob/meship/tests/rm-magic-numbers-cont/crates/blockifier/src/execution/deprecated_syscalls/mod.rs

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r6, 2 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 3 of 9 files reviewed, 4 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 326 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NsCXsvSEtz6Fvx2lrLN:-NsCXsvTENUItNT_L85Z:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/12557237fbb820aea440e00bbedb996d3ecd38ef/crates/blockifier/src/test_utils.rs#L326)):*
> ```XML
> }
> 
> pub fn get_transaction_resources(tx_type: TransactionType) -> ExecutionResources {
> ```





_Suggestion:_
```XML
get_tx_resources
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 154 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NsCY7zD2PsUfepGIhWG:-NsCY7zE6AYfM3I5UEib:b8b4i2x) ([raw file](https://github.com/starkware-libs/blockifier/blob/12557237fbb820aea440e00bbedb996d3ecd38ef/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L154)):*
> ```XML
>         ..Default::default()
>     };
>     let mut library_call_resources = &get_syscall_resources(DeprecatedSyscallSelector::LibraryCall)
> ```

Why ref?



_Code quote:_
```XML
&g
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 840 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NsCYMIb08RBHfi_MPSq:-NsCYMIb08RBHfi_MPSr:b-o1ttkj) ([raw file](https://github.com/starkware-libs/blockifier/blob/12557237fbb820aea440e00bbedb996d3ecd38ef/crates/blockifier/src/transaction/account_transactions_test.rs#L840)):*
> ```XML
>         u64_from_usize(get_syscall_resources(SyscallSelector::CallContract).n_steps)
>             + u64_from_usize(get_transaction_resources(TransactionType::InvokeFunction).n_steps)
>             + 1751;
> ```

Why not summing and then converting to u64 once?



_Code quote:_
```XML
        u64_from_usize(get_syscall_resources(SyscallSelector::CallContract).n_steps)
            + u64_from_usize(get_transaction_resources(TransactionType::InvokeFunction).n_steps)
            + 1751;
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 326 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NsCXsvSEtz6Fvx2lrLN:-NsD35_bDxfEhqFTf_R5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/12557237fbb820aea440e00bbedb996d3ecd38ef/crates/blockifier/src/test_utils.rs#L326)):*
> ```XML
> }
> 
> pub fn get_transaction_resources(tx_type: TransactionType) -> ExecutionResources {
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 840 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NsCYMIb08RBHfi_MPSq:-NsD37uu4MDfF6Uc1Tr3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/12557237fbb820aea440e00bbedb996d3ecd38ef/crates/blockifier/src/transaction/account_transactions_test.rs#L840)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not summing and then converting to u64 once?
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 505 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NsCHBBr3jRRc6f-k7ak:-NsD4DoN7oyIOWnNp3xn:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e005df7bbee0384dffa866d046b3e3e89eda4f9e/crates/blockifier/resources/versioned_constants.json#L505)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Revert?
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r7, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 141 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NsDTmNg5TbtkWT6YEKh:-NsDTmNg5TbtkWT6YEKi:byp6rt5) ([raw file](https://github.com/starkware-libs/blockifier/blob/7f49b91e29d986533b5c9fb2d717ebd0d09934b9/crates/blockifier/src/transaction/execution_flavors_test.rs#L141)):*
> ```XML
> #[case(TransactionVersion::ONE, FeeType::Eth, true)]
> #[case(TransactionVersion::THREE, FeeType::Strk, false)]
> fn l(
> ```

Revert



_Code quote:_
```XML
fn l(
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 141 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-NsDTmNg5TbtkWT6YEKh:-NsDVBq52brzXTIpzKyz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7f49b91e29d986533b5c9fb2d717ebd0d09934b9/crates/blockifier/src/transaction/execution_flavors_test.rs#L141)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Revert
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1567#-:-NsDYZxV1JqNIyApsf0m:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
