### PR TITLE
Add external transactions.

### PR DESCRIPTION
**Pull request by noaov1**
[Python](https://reviewable.io/reviews/starkware-industries/starkware/32380)

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1052)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1052)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1052#-NhvmhIr3-e5lmNweWnL:-NhvmhIsE7mZcSXmeqAP:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/552d1ecd3b83fc2eeb5e5217b7a993441d692369/crates/blockifier/src/transaction/transactions.rs#L43)):*
> ```XML
>         })*
>     };
> }
> ```

Remove?



_Code quote:_
```XML
macro_rules! implement_inner_tx_getter_fields {
    ($(($field:ident, $field_type:ty)),*) => {
        $(pub fn $field(&self) -> $field_type {
            self.tx.$field.clone()
        })*
    };
}
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1052)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1052#-NhvmhIr3-e5lmNweWnL:-Ni4nW-sAHXxgZbH2Nzc:b2ybhy) ([raw file](https://github.com/starkware-libs/blockifier/blob/552d1ecd3b83fc2eeb5e5217b7a993441d692369/crates/blockifier/src/transaction/transactions.rs#L43)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why? It is used in `DeployAccountTransaction`? You think it's not needed?
</blockquote></details>

I think it's duplicated.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1052)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1052#-NhvmhIr3-e5lmNweWnL:-Ni5F_uAAC1dYRUXiwQe:bfr2jxq) ([raw file](https://github.com/starkware-libs/blockifier/blob/552d1ecd3b83fc2eeb5e5217b7a993441d692369/crates/blockifier/src/transaction/transactions.rs#L43)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it's duplicated.
</blockquote></details>

It is not. `implement_inner_tx_getter_fields` is different from `implement_inner_tx_getter_calls`. The first one returns `self.tx.$field.clone()` while the second one returns `self.tx.$field().clone()`  (notice the parenthesis after the field).  
Reason: `DeployAccountTransaction` in SN API is not an enum, hence has no getters :(

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1052)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1052#-NhvmhIr3-e5lmNweWnL:-Ni5D_lcECL9i1qvqW_9:b6xinpx) ([raw file](https://github.com/starkware-libs/blockifier/blob/552d1ecd3b83fc2eeb5e5217b7a993441d692369/crates/blockifier/src/transaction/transactions.rs#L43)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it's duplicated.
</blockquote></details>

one has an extra `()` in it (uses internal getter, not field)
___
*[`crates/blockifier/src/transaction/transactions.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1052#-Ni5EksHEnJERFY1pq0H:-Ni5EksHEnJERFY1pq0I:bjmlxua) ([raw file](https://github.com/starkware-libs/blockifier/blob/552d1ecd3b83fc2eeb5e5217b7a993441d692369/crates/blockifier/src/transaction/transactions.rs#L215)):*
> ```XML
>     pub fn tx(&self) -> &starknet_api::transaction::DeployAccountTransaction {
>         &self.tx
>     }
> ```

why the getter? the field is public



_Code quote:_
```XML
    pub fn tx(&self) -> &starknet_api::transaction::DeployAccountTransaction {
        &self.tx
    }
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1052)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1052#-Ni5EksHEnJERFY1pq0H:-Ni5KYsd9z5m_ZPyDIEI:b8nepq4) ([raw file](https://github.com/starkware-libs/blockifier/blob/552d1ecd3b83fc2eeb5e5217b7a993441d692369/crates/blockifier/src/transaction/transactions.rs#L215)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why the getter? the field is public
</blockquote></details>

For no good reason. Removed.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1052)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1052)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1052#-:-Ni9FhMVE7WisbqGDRpl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
