### PR TITLE
Return StateDiff from Transaction's execute().

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/259)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/259)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/state_api.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/259#-NNHcrvS3faOofnYzz7o:-NNHcrvS3faOofnYzz7p:b1j07r2) ([raw file](https://github.com/starkware-libs/blockifier/blob/95849b5a682f4234269df2d948bffe409b8dcc12/crates/blockifier/src/state/state_api.rs#L71)):*
> ```XML
>     fn get_contract_class(&mut self, class_hash: &ClassHash) -> StateResult<&ContractClass>;
> 
>     fn to_state_diff(&self) -> StateDiff;
> ```

I think you can enforce everyone who implements this trait to also implement `From StatDiff`.
```rust
trait State: Into<StateDiff> {...}
```
TAL here:
https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#using-supertraits-to-require-one-traits-functionality-within-another-trait



_Code quote:_
```XML
fn to_state_diff(&self) -> StateDiff;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/259#-NNHdVY18Ki3nLudn9K_:-NNHdVY18Ki3nLudn9Ka:b-jmxfoo) ([raw file](https://github.com/starkware-libs/blockifier/blob/95849b5a682f4234269df2d948bffe409b8dcc12/crates/blockifier/src/transaction/account_transaction.rs#L107)):*
> ```XML
>                 validate_call_info: Some(validate_call_info),
>                 execute_call_info,
>                 fee_transfer_call_info: Some(fee_transfer_call_info),
> ```

Same for all implementations.



_Suggestion:_
```XML
        tx_execution_info = TransactionExecutionInfo {
            validate_call_info: Some(validate_call_info),
            execute_call_info,
            fee_transfer_call_info: Some(fee_transfer_call_info),
            actual_fee,
            actual_resources,
        }
        Ok((state.to_state_diff(), tx_execution_info))
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/259#-NNHdmiR0cnF4GMm-nZB:-NNHdmiR0cnF4GMm-nZC:b-he7fyv) ([raw file](https://github.com/starkware-libs/blockifier/blob/95849b5a682f4234269df2d948bffe409b8dcc12/crates/blockifier/src/transaction/transactions_test.rs#L203)):*
> ```XML
> 
>     let account_tx = AccountTransaction::Invoke(invoke_tx);
>     let (_, actual_execution_info) = account_tx.execute(state, block_context).unwrap();
> ```

If we give this a name, does `clippy` approve?



_Suggestion:_
```XML
_state_diff
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/259)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/state/state_api.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/259#-NNHcrvS3faOofnYzz7o:-NNHgp1U30XgOSNQNo3_:bkqhm1y) ([raw file](https://github.com/starkware-libs/blockifier/blob/95849b5a682f4234269df2d948bffe409b8dcc12/crates/blockifier/src/state/state_api.rs#L71)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think you can enforce everyone who implements this trait to also implement `From StatDiff`.
```rust
trait State: Into<StateDiff> {...}
```
TAL here:
https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#using-supertraits-to-require-one-traits-functionality-within-another-trait
</blockquote></details>

I though so too but it's not possible since `From` (and also `Into`) inherits from `Sized` which cause the trait not to be "object safe". See [here](https://doc.rust-lang.org/reference/items/traits.html#object-safety).
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/259#-NNHdmiR0cnF4GMm-nZB:-NNHhyJ76lKG6C5UOUXI:bfvmsj2) ([raw file](https://github.com/starkware-libs/blockifier/blob/95849b5a682f4234269df2d948bffe409b8dcc12/crates/blockifier/src/transaction/transactions_test.rs#L203)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

If we give this a name, does `clippy` approve?
</blockquote></details>

Yes. Changed.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/259#-:-NNHmwfb9a63MQbqFerl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/state_api.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/259#-NNHcrvS3faOofnYzz7o:-NNHmsAW5plZNhEgAGna:b7tnvfe) ([raw file](https://github.com/starkware-libs/blockifier/blob/95849b5a682f4234269df2d948bffe409b8dcc12/crates/blockifier/src/state/state_api.rs#L71)):*
<details><summary><i>Previously, noaov1 wrote…</i></summary><blockquote>

I though so too but it's not possible since `From` (and also `Into`) inherits from `Sized` which cause the trait not to be "object safe". See [here](https://doc.rust-lang.org/reference/items/traits.html#object-safety).
</blockquote></details>

Wow, really? I wonder why...

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/259)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/state/state_api.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/259#-NNHcrvS3faOofnYzz7o:-NNHn2umDWwYqPDdBUJz:b-ssov40) ([raw file](https://github.com/starkware-libs/blockifier/blob/95849b5a682f4234269df2d948bffe409b8dcc12/crates/blockifier/src/state/state_api.rs#L71)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Wow, really? I wonder why...
</blockquote></details>

The exact error message is:



_Code snippet:_
```XML
37 |         state: &mut dyn State,
   |                     ^^^^^^^^^ `state_api::State` cannot be made into an object
   |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
  --> crates/blockifier/src/state/state_api.rs:38:18
   |
38 | pub trait State: Into<StateDiff> {
   |           -----  ^^^^^^^^^^^^^^^ ...because it requires `Self: Sized`
   |           |
   |           this trait cannot be made into an object...
```

**Pull request merged**
