### PR TITLE
feat(execution): add entry_point_syscall_counter

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1407)

### CODE REVIEW

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1407)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 411 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1407#-NpUd-MG908npLii3BKU:-NpUd-MG908npLii3BKV:b-l18fq1) ([raw file](https://github.com/starkware-libs/blockifier/blob/e93efdbd0ac30cdb6f81d427f0f45247765c2879/crates/blockifier/src/execution/syscalls/hint_processor.rs#L411)):*
> ```XML
>         let entry_point_syscall_count =
>             self.entry_point_syscall_counter.entry(*selector).or_default();
>         *entry_point_syscall_count += n;
> ```

This line is not very clear, and there are no other references similar to this in the repository. Is it possible to use something like "and_modify" or a similar alternative?

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1407)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 411 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1407#-NpUd-MG908npLii3BKU:-NpY_E7P-2ecjrmcZ8VT:buu5h0c) ([raw file](https://github.com/starkware-libs/blockifier/blob/e93efdbd0ac30cdb6f81d427f0f45247765c2879/crates/blockifier/src/execution/syscalls/hint_processor.rs#L411)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

This line is not very clear, and there are no other references similar to this in the repository. Is it possible to use something like "and_modify" or a similar alternative?
</blockquote></details>

The "and_modify" seems less readable to me, and I am not sure it fits here anyway. @noaov1 what do you think?

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1407)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @OriStarkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1407#-NpYtWBy66jTWn5SMwei:-NpYtWBy66jTWn5SMwej:b-3av4g5) ([raw file](https://github.com/starkware-libs/blockifier/blob/e93efdbd0ac30cdb6f81d427f0f45247765c2879/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L101)):*
> ```XML
>     pub events: Vec<OrderedEvent>,
>     pub l2_to_l1_messages: Vec<OrderedL2ToL1Message>,
>     pub entry_point_syscall_counter: SyscallCounter,
> ```

As done for other entry point fields.



_Suggestion:_
```XML
    pub syscall_counter: SyscallCounter,
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 411 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1407#-NpUd-MG908npLii3BKU:-NpYu1BB-sm5PV7w_pdJ:b-fbk62d) ([raw file](https://github.com/starkware-libs/blockifier/blob/e93efdbd0ac30cdb6f81d427f0f45247765c2879/crates/blockifier/src/execution/syscalls/hint_processor.rs#L411)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

The "and_modify" seems less readable to me, and I am not sure it fits here anyway. @noaov1 what do you think?
</blockquote></details>

I don't have a strong opinion about it :)

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1407)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

**Pull request merged**
