### PR TITLE
fix: update the event limit constants

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1483)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1483)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1483#-NqRTaUMCe-e13BMMquy:-NqRTaUMCe-e13BMMquz:b-pczju2) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c3940ee1aad7ad03a431d075b8f62d137011616/crates/blockifier/src/execution/syscalls/mod.rs#L47)):*
> ```XML
> pub const SYSCALL_MAX_EVENT_KEYS: usize = 40;
> pub const SYSCALL_MAX_EVENT_DATA: usize = 40;
> pub const SYSCALL_MAX_N_EMITTED_EVENTS: Option<usize> = None;
> ```

Why not 1000?



_Code quote:_
```XML
Option<usize> = None;
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1483)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1483#-NqRVQHV3dSgDg1O1fHn:-NqRVQHW7mKOepoNob-r:btja5io) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c3940ee1aad7ad03a431d075b8f62d137011616/crates/blockifier/src/execution/syscalls/mod.rs#L47)):*
> ```XML
> pub const SYSCALL_MAX_EVENT_KEYS: usize = 40;
> pub const SYSCALL_MAX_EVENT_DATA: usize = 40;
> pub const SYSCALL_MAX_N_EMITTED_EVENTS: Option<usize> = None;
> ```

Make it ridiculously high instead (to avoid conflicts)



_Suggestion:_
```XML
usize = 1_000_000_000;
```

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1483)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1483)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1483#-NqRVQHV3dSgDg1O1fHn:-NqRbF_SCjRkGbGMh1KQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c3940ee1aad7ad03a431d075b8f62d137011616/crates/blockifier/src/execution/syscalls/mod.rs#L47)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Make it ridiculously high instead (to avoid conflicts)
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1483#-:-NqSzpWe65mT1w0B1TtN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
