### PR TITLE
feat(fee): add gas cost for calldata bytes

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTg7Y2eS8s-vDKFqL:-NptTg7Z-h7ioIqOiFb6:brm6o9u) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
> ```XML
> // L2 Calldata.
> pub const GAS_PER_CALLDATA_BYTE: usize = 2;
> pub const GAS_PER_CALLDATA_WORD: usize = GAS_PER_CALLDATA_BYTE * WORD_WIDTH;
> ```

When is it used?



_Code quote:_
```XML
pub const GAS_PER_CALLDATA_WORD: usize = GAS_PER_CALLDATA_BYTE * WORD_WIDTH;
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTHR77o9FFRm_DUHw:-NptTHR77o9FFRm_DUHx:bpxvwcr) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage.rs#L77)):*
> ```XML
> }
> 
> // Return the gas cost for transaction calldata.
> ```

Can you please elaborate which cost is it? 



_Code quote:_
```XML
// Return the gas cost for transaction calldata.
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTlsX5syrXqpXLuTs:-NptTlsX5syrXqpXLuTt:bvdfqtp) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage_test.rs#L116)):*
> ```XML
>         std::iter::empty(),
>         StateChangesCount::default(),
>         0,
> ```

As `l1_handler_payload_size = 4;`
Same below.



_Suggestion:_
```XML
        4,
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTg7Y2eS8s-vDKFqL:-NptsBUB2N1FZ5VT2Htg:b-3pus8b) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When is it used?
</blockquote></details>

I accidentally used the cost per byte instead of the cost per word. I fixed it.

Now it is used.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTHR77o9FFRm_DUHw:-Nptw7bm2RF5V1siFr22:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage.rs#L77)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please elaborate which cost is it?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTlsX5syrXqpXLuTs:-NptwDGg29UajXHeH0wK:bqa5tlv) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage_test.rs#L116)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

As `l1_handler_payload_size = 4;`
Same below.
</blockquote></details>

I don't want to consider the l1_handler_payload as calldata for now. I will change it in another PR depending on what ariel wants to do with it.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-Npu5SL14XNAnWSbsQlN:-Npu5SL14XNAnWSbsQlO:bb2ewvu) ([raw file](https://github.com/starkware-libs/blockifier/blob/686d9d138c2ee05c55b13d68ee4a207f76c5b01c/crates/blockifier/src/fee/gas_usage.rs#L82)):*
> ```XML
>     let calldata_gas_cost = calldata_length as f64 * eth_gas_constants::GAS_PER_CALLDATA_WORD;
>     GasVector { l1_gas: calldata_gas_cost.ceil() as u128, blob_gas: 0 }
> }
> ```

@dorimedini-starkware, can you suggest an alternatives to the floats?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTg7Y2eS8s-vDKFqL:-NpuCvIQ1Rb1y-1pXzvt:bi9i5wq) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I accidentally used the cost per byte instead of the cost per word. I fixed it.

Now it is used.
</blockquote></details>

Can you avoid using `as` ?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTg7Y2eS8s-vDKFqL:-NpuDEvM-LVykXCuiXhR:b-hrirlp) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you avoid using `as` ?
</blockquote></details>

Also in other places

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 3 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @avi-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTHR77o9FFRm_DUHw:-Nptev6ADHqBBCnsYVaS:bqab4z2) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage.rs#L77)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

By word do you mean a felt? What gas cost? Storing it in the storage?
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTlsX5syrXqpXLuTs:-NpuxovP34mjIqtJ6zg6:b-a8g8ub) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage_test.rs#L116)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I don't want to consider the l1_handler_payload as calldata for now. I will change it in another PR depending on what ariel wants to do with it.
</blockquote></details>

You already are :) 
(you use the `calldata_length` field, which, for an l1 handler equals the payload size). 
After you decide, please make it consistent. 
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 832 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptWO-_Etceg7Ll4xpY:-NptWO-_Etceg7Ll4xpZ:b-x2324z) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/transaction/account_transactions_test.rs#L832)):*
> ```XML
>     let TestInitData { mut state, account_address, contract_address, mut nonce_manager } =
>         create_test_init_data(&block_context.chain_info, CairoVersion::Cairo0);
>     let actual_gas_used = 6148;
> ```

6140 + 2 * 4 = 6148. Working!



_Code quote:_
```XML
let actual_gas_used = 6148;
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @avi-starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 7 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-Npxr8-x6t9azIm85Vgg:-Npxr8-y6w8nJ2SEbTIb:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/20f2f2e4f8ff8194b2d2f36a14ea40f15dbd9335/crates/blockifier/src/fee/gas_usage_test.rs#L7)):*
> ```XML
> use starknet_api::transaction::L2ToL1Payload;
> 
> use super::get_calldata_gas_cost;
> ```





_Suggestion:_
```XML
crate...
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/fee/gas_usage.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-Npu5SL14XNAnWSbsQlN:-NpxqXVO1apfzs8BOusU:b-wtfcgy) ([raw file](https://github.com/starkware-libs/blockifier/blob/686d9d138c2ee05c55b13d68ee4a207f76c5b01c/crates/blockifier/src/fee/gas_usage.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@dorimedini-starkware, can you suggest an alternatives to the floats?
</blockquote></details>

@liorgold2 told me to use integers (i.e., milligas instead of gas units) and then convert from milligas to gas units via integer division by 1000.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dorimedini-starkware, @elintul, @liorgold2, and @noaov1)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTg7Y2eS8s-vDKFqL:-NpxqVPO5EphWxDjhBey:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Also in other places
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTHR77o9FFRm_DUHw:-NpxfGjtAPReC-AhfI01:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage.rs#L77)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

By word do you mean a felt? What gas cost? Storing it in the storage?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTlsX5syrXqpXLuTs:-NpxeJOQ94RPKXhgBSF1:bgy7p0m) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage_test.rs#L116)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You already are :) 
(you use the `calldata_length` field, which, for an l1 handler equals the payload size). 
After you decide, please make it consistent.
</blockquote></details>

Okay, I added it everywhere in this test. Please check that it is correct. Especially the case with l2_to_l1 messages which I am the least sure about.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTlsX5syrXqpXLuTs:-NpxxXG2DsS2z1AfoM8T:b-nmniuy) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage_test.rs#L116)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Okay, I added it everywhere in this test. Please check that it is correct. Especially the case with l2_to_l1 messages which I am the least sure about.
</blockquote></details>

The l2_to_l1 messages are calculated separately. They are not part of the calldata as far as I can tell, so I am keeping the part of the test dealing with this case unchaged.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @elintul, @liorgold2, and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-Npu5SL14XNAnWSbsQlN:-NpyBjLR28wRVqCtlSTN:bb73djm) ([raw file](https://github.com/starkware-libs/blockifier/blob/686d9d138c2ee05c55b13d68ee4a207f76c5b01c/crates/blockifier/src/fee/gas_usage.rs#L82)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

@liorgold2 told me to use integers (i.e., milligas instead of gas units) and then convert from milligas to gas units via integer division by 1000.
</blockquote></details>

SGTM

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @elintul, @liorgold2, and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-Npu5SL14XNAnWSbsQlN:-NpyF1Sr86vjj7jMBHQR:b-9onkgx) ([raw file](https://github.com/starkware-libs/blockifier/blob/686d9d138c2ee05c55b13d68ee4a207f76c5b01c/crates/blockifier/src/fee/gas_usage.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

SGTM
</blockquote></details>

We discussed using rational numbers instead of integers, but they are not implemented yet.

I added a TODO to use rational numbers once they are implemented.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r5, 1 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, and @liorgold2)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTHR77o9FFRm_DUHw:-NpyTrd392OUDsNsfpG_:bg113u5) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage.rs#L77)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm confused :) You multiply the `MILLIGAS_PER_CALLDATA_WORD` by a `WORD_WIDTH`. Is it okay?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/fee/gas_usage.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTHR77o9FFRm_DUHw:-Npydqz-8Lzmy7ZF6Xp8:bgjnouv) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage.rs#L77)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm confused :) You multiply the `MILLIGAS_PER_CALLDATA_WORD` by a `WORD_WIDTH`. Is it okay?
</blockquote></details>

I multiply `MILLIGAS_PER_CALLDATA_BYTE` by `WORD_WIDTH` to get `MILLIGAS_PER_CALLDATA_WORD`, which is the price in milligas of a word. I assume each felt is the size of a word, so the milligas cost of a felt is `MILLIGAS_PER_CALLDATA_WORD`.

Note: this assumption is no longer correct, but I am working on another PR where I count the actual number of bytes each felt consists of. Within the scope of the current PR, a felt is always 32 bytes.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @giladchase, @liorgold2, and @noaov1)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NpyHaJo9II_ck-I2uY_:-Npyg6C01xa-DKQ4wHro:b-3t06ev) ([raw file](https://github.com/starkware-libs/blockifier/blob/fce2404d3caed9a4c1bc1874600267505cd85bc3/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Are these meant to be overridden by nodes that use the blockifier? (i think Ariel mentioned this at some channel)
</blockquote></details>

I don't know...

If so, does it affect my task in some way?

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-:-Npym1_C4IjnYRMo8dJw:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @liorgold2)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTHR77o9FFRm_DUHw:-Npyloft7LhX9DyEfAZ4:b-l0z8s4) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage.rs#L77)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I multiply `MILLIGAS_PER_CALLDATA_BYTE` by `WORD_WIDTH` to get `MILLIGAS_PER_CALLDATA_WORD`, which is the price in milligas of a word. I assume each felt is the size of a word, so the milligas cost of a felt is `MILLIGAS_PER_CALLDATA_WORD`.

Note: this assumption is no longer correct, but I am working on another PR where I count the actual number of bytes each felt consists of. Within the scope of the current PR, a felt is always 32 bytes.
</blockquote></details>

Oh, under your assumption it is correct. Thanks.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @liorgold2)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-Npu5SL14XNAnWSbsQlN:-Npz25wH97xOKDXJlBf6:bw934eg) ([raw file](https://github.com/starkware-libs/blockifier/blob/686d9d138c2ee05c55b13d68ee4a207f76c5b01c/crates/blockifier/src/fee/gas_usage.rs#L82)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

We discussed using rational numbers instead of integers, but they are not implemented yet.

I added a TODO to use rational numbers once they are implemented.
</blockquote></details>

(FYI, [in PR](https://reviewable.io/reviews/starkware-libs/blockifier/1419))

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @liorgold2)

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @liorgold2)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTHR77o9FFRm_DUHw:-Nq1pZn8COuPMTi4eW4e:b98fe5y) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage.rs#L77)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh, under your assumption it is correct. Thanks.
</blockquote></details>

Add a TODO?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/fee/gas_usage.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NptTHR77o9FFRm_DUHw:-Nq2B6ewBjl6xpoKYwXR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d0fd84e3023a471197b57c61ab3ccf3940d70912/crates/blockifier/src/fee/gas_usage.rs#L77)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Add a TODO?
</blockquote></details>

Done.

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @elintul, @liorgold2, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NpyHaJo9II_ck-I2uY_:-Nq2HqBu3AaT4pVVth1c:b-kwcoji) ([raw file](https://github.com/starkware-libs/blockifier/blob/fce2404d3caed9a4c1bc1874600267505cd85bc3/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I don't know...

If so, does it affect my task in some way?
</blockquote></details>

It affects, ya.
Verify with Yoni just to be sure.

If that's the case, then instead of defining them here, you need to define the consts as new keys in versioned_constants.json, and similarly as fields in `VersionedConstants` struct.

To access them you need to do it through the context instance you have available.
Lookup usages of versioned_constants for example, or talk to me about it.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @elintul, @liorgold2, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NpyHaJo9II_ck-I2uY_:-Nq2JBoq2BvgsC9tpqTn:blf94cu) ([raw file](https://github.com/starkware-libs/blockifier/blob/fce2404d3caed9a4c1bc1874600267505cd85bc3/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

It affects, ya.
Verify with Yoni just to be sure.

If that's the case, then instead of defining them here, you need to define the consts as new keys in versioned_constants.json, and similarly as fields in `VersionedConstants` struct.

To access them you need to do it through the context instance you have available.
Lookup usages of versioned_constants for example, or talk to me about it.
</blockquote></details>

The idea is that constant files will now only be for constants that are generally fixed.

Constants that are likely to vary between versions are set in versioned_constants.json, to make it easier for blockifier users to play around with them.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, @liorgold2, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NpyHaJo9II_ck-I2uY_:-Nq2KyFmB5E_J3EC9BKk:bdggq5q) ([raw file](https://github.com/starkware-libs/blockifier/blob/fce2404d3caed9a4c1bc1874600267505cd85bc3/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The idea is that constant files will now only be for constants that are generally fixed.

Constants that are likely to vary between versions are set in versioned_constants.json, to make it easier for blockifier users to play around with them.
</blockquote></details>

Are other constants in this file not configurable?

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, @liorgold2, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NpyHaJo9II_ck-I2uY_:-Nq2gOue8s_9xGYnmaAQ:bhygglu) ([raw file](https://github.com/starkware-libs/blockifier/blob/fce2404d3caed9a4c1bc1874600267505cd85bc3/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Are other constants in this file not configurable?
</blockquote></details>

I moved the constant to `versioned_constants.json`

**Review by noaov1 — DISMISSED** [review]
> Reviewed 2 of 5 files at r9, 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 9 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-NpyHaJo9II_ck-I2uY_:-Nq3EMMr0etj5SH_Da0g:b-dchlz8) ([raw file](https://github.com/starkware-libs/blockifier/blob/fce2404d3caed9a4c1bc1874600267505cd85bc3/crates/blockifier/src/fee/eth_gas_constants.rs#L9)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I moved the constant to `versioned_constants.json`
</blockquote></details>

You may need to change the file in python as well. @giladchase ?

**Review by elintul — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 8 of 8 files at r11, 3 of 3 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by noaov1 — APPROVED** [review]
Python PR?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1426#-:-Nq8BXaV3ZMhgEiDDPG8:bta0nby)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by avi-starkware** [comment]
https://reviewable.io/reviews/starkware-industries/starkware/33890#-

**Pull request merged**
