### PR TITLE
Move deprecated hint processor

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/448)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/448?utm_source=stack-comment).

**Review by elintul — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/448)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/errors.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/448#-NUovEtz4nBIGyM5tgWx:-NUovEtz4nBIGyM5tgWy:b-tkv9ub) ([raw file](https://github.com/starkware-libs/blockifier/blob/e66682bfa402213a053f3704f877c9429038613b/crates/blockifier/src/execution/errors.rs#L65)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum DeprecatedSyscallExecutionError {
> ```

Planning to add here the new error enum?
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/448#-NUov4q93o3Kbmey4kdh:-NUov4q93o3Kbmey4kdi:b-9p3o0p) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5abbf696e168ef36eb3c3a445d191ca23d77f97/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L29)):*
> ```XML
> #[path = "deprecated_syscalls_test.rs"]
> pub mod deprecated_syscalls_test;
> pub mod hint_processor;
> ```

Why not `lib.rs` in the new directory? What's the difference?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/448)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/errors.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/448#-NUovEtz4nBIGyM5tgWx:-NUowQFHAzFEjJNFt3uh:b7dwlx0) ([raw file](https://github.com/starkware-libs/blockifier/blob/e66682bfa402213a053f3704f877c9429038613b/crates/blockifier/src/execution/errors.rs#L65)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Planning to add here the new error enum?
</blockquote></details>

I plan to copy the deprecated directory, and remove all "Deprecated" :)
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/448#-NUov4q93o3Kbmey4kdh:-NUowbkz6X2MOQq1MIZK:b-vm64q5) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5abbf696e168ef36eb3c3a445d191ca23d77f97/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L29)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not `lib.rs` in the new directory? What's the difference?
</blockquote></details>

lib.rs is only in the crate top level. In modules we have mod.rs. Do we not use it in the blockifier repo?

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/448)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/448#-NUov4q93o3Kbmey4kdh:-NUoxwQ2Ak0XVe_dtnnB:b-bqy7wc) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5abbf696e168ef36eb3c3a445d191ca23d77f97/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L29)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

lib.rs is only in the crate top level. In modules we have mod.rs. Do we not use it in the blockifier repo?
</blockquote></details>

No... :(

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/448#-:-NUoy3Um28RQe2jhRVg8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/448)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/448#-NUov4q93o3Kbmey4kdh:-NUp0SC36TNm2JFe1ziX:b-22m7n7) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5abbf696e168ef36eb3c3a445d191ca23d77f97/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L29)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No... :(
</blockquote></details>

Can I use it? I jsut wanted to contain everything re deprecated syscalls in a folder

**Pull request merged**
