### PR TITLE
refactor: pass bouncer_config from python

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
matching Python PR: https://github.com/starkware-industries/starkware/pull/34322

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-:-NsbBniy2LXyAXYPsV5n:bfh9wrl)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NsOaftc2yYlt5hYd31L):*
need to create and review the matching python PR before merging

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NsOaftc2yYlt5hYd31L):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

need to create and review the matching python PR before merging
</blockquote></details>

created : https://github.com/starkware-industries/starkware/pull/34322
now need to review

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 5 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NtAj5jwEzHHst3OvPz-:-NtAj5jwEzHHst3OvPz0:bnuz7sl) ([raw file](https://github.com/starkware-libs/blockifier/blob/166ad94ad36d9838378ca8acc8937600732ec87e/crates/blockifier/src/bouncer.rs#L42)):*
> ```XML
> pub type HashMapWrapper = HashMap<String, usize>;
> 
> #[derive(Clone, Copy, Debug)]
> ```

Does this make sense?
I don't want to derive Clone anywhere else but testing.

On the other hand, this is only the configuration. There is no security issue with cloning or copying it.



_Suggestion:_
```XML
#[derive(Debug)]
#[cfg_attr(test, derive(Clone, Copy))]
```
___
*[`crates/blockifier/src/bouncer.rs` line 106 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NtAjOcC6piS3dtb3o2z:-NtAjOcC6piS3dtb3o3-:bb8kzvb) ([raw file](https://github.com/starkware-libs/blockifier/blob/166ad94ad36d9838378ca8acc8937600732ec87e/crates/blockifier/src/bouncer.rs#L106)):*
> ```XML
>             builtin_count: BuiltinCount::from(data),
>         }
>     }
> ```

Does this make more sense as a `try_from` and then deal with the appropriate error messages - and don't panic?

If so, don't use `expect`; use the appropriate error.



_Suggestion:_
```XML
    fn try_from(mut data: HashMapWrapper) -> Reuslt<Self, ErrorForTheSituation> {
        Self {
            gas: data.remove(constants::L1_GAS_USAGE).expect("gas_weight must be present"),
            n_steps: data.remove(constants::N_STEPS_RESOURCE).expect("n_steps must be present"),
            message_segment_length: data
                .remove(constants::MESSAGE_SEGMENT_LENGTH)
                .expect("message_segment_length must be present"),
            state_diff_size: data
                .remove(constants::STATE_DIFF_SIZE)
                .expect("state_diff_size must be present"),
            n_events: data.remove(constants::N_EVENTS).expect("n_events must be present"),
            builtin_count: BuiltinCount::from(data),
        }
    }
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NtAlXnR1T2yFFznv6_a:-NtAlXnR1T2yFFznv6_b:b-rlrjjm) ([raw file](https://github.com/starkware-libs/blockifier/blob/166ad94ad36d9838378ca8acc8937600732ec87e/crates/blockifier/src/blockifier/transaction_executor.rs#L46)):*
> ```XML
>     pub block_context: BlockContext,
>     pub bouncer: Bouncer,
>     pub bouncer_config: BouncerConfig,
> ```

Isn't it strange both of these members are here?

Isn't the bouncer_config a member of the bouncer? At least logically?



_Code quote:_
```XML
    pub bouncer: Bouncer,
    pub bouncer_config: BouncerConfig,
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 5 of 8 files reviewed, 6 unresolved discussions (waiting on @Yael-Starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NtKpnBK2FbN1YimwIEM:-NtKpnBK2FbN1YimwIEN:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/166ad94ad36d9838378ca8acc8937600732ec87e/crates/blockifier/src/bouncer.rs#L120)):*
> ```XML
>         map
>     }
> }
> ```





_Suggestion:_
```XML
impl From<BouncerWeights> for HashMapWrapper {
    fn from(val: BouncerWeights) -> Self {
        let mut map = HashMapWrapper::from([
            (constants::L1_GAS_USAGE.to_string(), val.gas),
            (constants::N_STEPS_RESOURCE.to_string(), val.n_steps),
            (constants::MESSAGE_SEGMENT_LENGTH.to_string(), val.message_segment_length),
            (constants::STATE_DIFF_SIZE.to_string(), val.state_diff_size),
            (constants::N_EVENTS.to_string(), val.n_events),
        ]);
        map.extend::<HashMap<String, usize>>(val.builtin_count.into());
        map
    }
}
```
___
*[`crates/blockifier/src/bouncer.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NtKpw4iCIWWfD260iGC:-NtKpw4iCIWWfD260iGD:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/166ad94ad36d9838378ca8acc8937600732ec87e/crates/blockifier/src/bouncer.rs#L195)):*
> ```XML
>         map
>     }
> }
> ```





_Suggestion:_
```XML
impl From<BuiltinCount> for HashMapWrapper {
    fn from(val: BuiltinCount) -> Self {
        HashMapWrapper::from([(BuiltinName::bitwise.name().to_string(), val.bitwise), ...])
    }
}
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NtKn9qNBvJHcNlMuGy2:-NtKn9qO2oE9Fph7sDa4:buxclna) ([raw file](https://github.com/starkware-libs/blockifier/blob/166ad94ad36d9838378ca8acc8937600732ec87e/crates/native_blockifier/src/py_validator.rs#L58)):*
> ```XML
>         let block_context =
>             BlockContext::new_unchecked(&block_info, &chain_info, &versioned_constants);
>         let tx_executor = TransactionExecutor::new(state, block_context, bouncer_config.into());
> ```

In https://github.com/starkware-industries/starkware/pull/34322, you defined: `BlockifierBouncerConfig.max`.
What do you think about defining it in this repo and using it here?
This way the verifier will not get the bouncer config as a variable in create.

It will also be useful for mempool.



_Code quote:_
```XML
let tx_executor = TransactionExecutor::new(state, block_context, bouncer_config.into());
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NtAj5jwEzHHst3OvPz-:-Nu36_RcB0k7fRX5udSY:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/166ad94ad36d9838378ca8acc8937600732ec87e/crates/blockifier/src/bouncer.rs#L42)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Does this make sense?
I don't want to derive Clone anywhere else but testing.

On the other hand, this is only the configuration. There is no security issue with cloning or copying it.
</blockquote></details>

done
___
*[`crates/blockifier/src/bouncer.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NtKpnBK2FbN1YimwIEM:-Nu36vnb8hQ0mVvWsWNA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/166ad94ad36d9838378ca8acc8937600732ec87e/crates/blockifier/src/bouncer.rs#L120)):*
> ```XML
>         map
>     }
> }
> ```

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NtKpw4iCIWWfD260iGC:-Nu376m_9oRBZiznUU0W:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/166ad94ad36d9838378ca8acc8937600732ec87e/crates/blockifier/src/bouncer.rs#L195)):*
> ```XML
>         map
>     }
> }
> ```

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NtKn9qNBvJHcNlMuGy2:-Nu37Mn11R4CcTB2Z3zD:btxg81o) ([raw file](https://github.com/starkware-libs/blockifier/blob/166ad94ad36d9838378ca8acc8937600732ec87e/crates/native_blockifier/src/py_validator.rs#L58)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

In https://github.com/starkware-industries/starkware/pull/34322, you defined: `BlockifierBouncerConfig.max`.
What do you think about defining it in this repo and using it here?
This way the verifier will not get the bouncer config as a variable in create.

It will also be useful for mempool.
</blockquote></details>

max is just a temporary solution until we figure out how to pass the real values of the config. I should add a TODO on the python side.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, 1 of 3 files at r3, 4 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 99 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3hKhV1xHKkQVHGqXG:-Nu3hKhV1xHKkQVHGqXH:b-2y506o) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L99)):*
> ```XML
> 
> impl From<BouncerWeights> for HashMapWrapper {
>     fn from(val: BouncerWeights) -> Self {
> ```

Why do you need this?
___
*[`crates/blockifier/src/bouncer.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3gOaKEgpHNSndF6kx:-Nu3gOaKEgpHNSndF6ky:bieshfz) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L110)):*
> ```XML
>         map
>     }
> }
> ```

Can you push this code to one of the `py` files? it's only relevant for them and it's a shame to show this mess to everyone



_Code quote:_
```XML
impl From<HashMapWrapper> for BouncerWeights {
    fn from(mut data: HashMapWrapper) -> Self {
        Self {
            gas: data.remove(constants::L1_GAS_USAGE).expect("gas_weight must be present"),
            n_steps: data.remove(constants::N_STEPS_RESOURCE).expect("n_steps must be present"),
            message_segment_length: data
                .remove(constants::MESSAGE_SEGMENT_LENGTH)
                .expect("message_segment_length must be present"),
            state_diff_size: data
                .remove(constants::STATE_DIFF_SIZE)
                .expect("state_diff_size must be present"),
            n_events: data.remove(constants::N_EVENTS).expect("n_events must be present"),
            builtin_count: BuiltinCount::from(data),
        }
    }
}

impl From<BouncerWeights> for HashMapWrapper {
    fn from(val: BouncerWeights) -> Self {
        let mut map = HashMapWrapper::from([
            (constants::L1_GAS_USAGE.to_string(), val.gas),
            (constants::N_STEPS_RESOURCE.to_string(), val.n_steps),
            (constants::MESSAGE_SEGMENT_LENGTH.to_string(), val.message_segment_length),
            (constants::STATE_DIFF_SIZE.to_string(), val.state_diff_size),
            (constants::N_EVENTS.to_string(), val.n_events),
        ]);
        map.extend::<HashMap<String, usize>>(val.builtin_count.into());
        map
    }
}
```
___
*[`crates/blockifier/src/bouncer.rs` line 159 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3h38t5rpkJtKriVVU:-Nu3h38t5rpkJtKriVVV:b-w58n8k) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L159)):*
> ```XML
> }
> 
> impl From<BuiltinCount> for HashMapWrapper {
> ```

Same (push the mess to `py` files)
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3gmRW63LOy6Zj6Iot:-Nu3gmRW63LOy6Zj6Iou:b-9k06l6) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/native_blockifier/src/py_state_diff.rs#L126)):*
> ```XML
>     pub price_in_wei: u128,
>     pub price_in_fri: u128,
> }
> ```

Why in `py_state_diff`?

**Comment by ArniStarkware** [comment]
*[`crates/native_blockifier/src/py_validator.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3tuNP6EfMlkyAJTzH:-Nu3tuNP6EfMlkyAJTzI:b8245c6) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/native_blockifier/src/py_validator.rs#L48)):*
> ```XML
>         global_contract_cache_size: usize,
>         max_nonce_for_validation_skip: PyFelt,
>     ) -> NativeBlockifierResult<Self> {
> ```

Be aware of conflicts with #1730 



_Code quote:_
```XML
    pub fn create(
        general_config: PyGeneralConfig,
        state_reader_proxy: &PyAny,
        next_block_info: PyBlockInfo,
        bouncer_config: PyBouncerConfig,
        validate_max_n_steps: u32,
        max_recursion_depth: usize,
        global_contract_cache_size: usize,
        max_nonce_for_validation_skip: PyFelt,
    ) -> NativeBlockifierResult<Self> {
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 7 of 9 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 99 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3hKhV1xHKkQVHGqXG:-Nu41RRxDsfoT7Q37tLh:bi6letu) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L99)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why do you need this?
</blockquote></details>

it is for testing. moved to test_utils.rs
___
*[`crates/blockifier/src/bouncer.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3gOaKEgpHNSndF6kx:-Nu46YQV1Deud86PZpSk:b-9zovio) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L110)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you push this code to one of the `py` files? it's only relevant for them and it's a shame to show this mess to everyone
</blockquote></details>

I don't think I can, there is some rust orphan rule, saying I can implement these traits only in the crate that they were defined.
___
*[`crates/blockifier/src/bouncer.rs` line 159 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3h38t5rpkJtKriVVU:-Nu46qEL5Q5GVjagpvTY:bn5z5t5) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L159)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Same (push the mess to `py` files)
</blockquote></details>

same answer, I must stay in the same crate.
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3gmRW63LOy6Zj6Iot:-Nu424Vg5qoUUuC6VY5L:bkj1gnh) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/native_blockifier/src/py_state_diff.rs#L126)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why in `py_state_diff`?
</blockquote></details>

Right that's wrong, 
moved to py_transaction_execution_info.
___
*[`crates/native_blockifier/src/py_validator.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3tuNP6EfMlkyAJTzH:-Nu47WcwDR2fOQ9cJ35h:b-k24zno) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/native_blockifier/src/py_validator.rs#L48)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Be aware of conflicts with #1730
</blockquote></details>

that's scary stuff

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 5 of 11 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3gOaKEgpHNSndF6kx:-Nu4DQXi5HEg3OXWpQh5:blogv1g) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L110)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I don't think I can, there is some rust orphan rule, saying I can implement these traits only in the crate that they were defined.
</blockquote></details>

If it is used only once, no need for a trait. Push it to the py file somehow

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 5 of 11 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3gOaKEgpHNSndF6kx:-NuPAOy8C0Ujk4G5uIb9:brykeqv) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L110)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

If it is used only once, no need for a trait. Push it to the py file somehow
</blockquote></details>

it is used twice in for PyBouncerConfig :


pub struct PyBouncerConfig {
    pub full_total_weights_with_keccak: HashMap<String, usize>,
    pub full_total_weights: HashMap<String, usize>,
}

impl From<PyBouncerConfig> for BouncerConfig {
    fn from(py_bouncer_config: PyBouncerConfig) -> Self {
        BouncerConfig {
            block_max_capacity: BouncerWeights::from(py_bouncer_config.full_total_weights.clone()),
            block_max_capacity_with_keccak: BouncerWeights::from(
                py_bouncer_config.full_total_weights_with_keccak.clone(),
            ),
        }
    }
}

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 5 of 11 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3gOaKEgpHNSndF6kx:-NuPAfU47k0P17hynNH9:b-ocwbot) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L110)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it is used twice in for PyBouncerConfig :


pub struct PyBouncerConfig {
    pub full_total_weights_with_keccak: HashMap<String, usize>,
    pub full_total_weights: HashMap<String, usize>,
}

impl From<PyBouncerConfig> for BouncerConfig {
    fn from(py_bouncer_config: PyBouncerConfig) -> Self {
        BouncerConfig {
            block_max_capacity: BouncerWeights::from(py_bouncer_config.full_total_weights.clone()),
            block_max_capacity_with_keccak: BouncerWeights::from(
                py_bouncer_config.full_total_weights_with_keccak.clone(),
            ),
        }
    }
}
</blockquote></details>

because PyBouncerConfig has two fields of bouncer_weights. one with keccak and one without keccak.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-:-NuSC0gp--X4ElEx562A:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: all files reviewed, 1 unresolved discussion

**Review by ArniStarkware — DISMISSED** [review]
:lgtm: (specifically - on the transaction validator related stuff). 

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-:-Nuy842Y9wQBh1rew0l0:b-bqy9ec)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 218 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nv0RROR7R-d6fLvzH8B:-Nv0RROR7R-d6fLvzH8C:b-6aet8d) ([raw file](https://github.com/starkware-libs/blockifier/blob/87e4ce14e604ea08bb0802775841a05ed9ad6487/crates/blockifier/src/test_utils/struct_impls.rs#L218)):*
> ```XML
>             poseidon: 78125,
>             range_check: 156250,
>         }
> ```

Hopefully, the auto formatter will be happier with this.



_Suggestion:_
```XML
        let keccak = if with_keccak {1220} else {0};
        Self {
            bitwise: 39062,
            ecdsa: 1220,
            ec_op: 2441,
            keccak,
            pedersen: 78125,
            poseidon: 78125,
            range_check: 156250,
        }
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-:-Nv1kW2nAPBDIyua8vlM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: 3 of 12 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 218 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nv0RROR7R-d6fLvzH8B:-Nv6stfh8_VIZwEhCxPR:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/87e4ce14e604ea08bb0802775841a05ed9ad6487/crates/blockifier/src/test_utils/struct_impls.rs#L218)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Hopefully, the auto formatter will be happier with this.
</blockquote></details>

Done

**Review by ArniStarkware — DISMISSED** [review]
> Reviewed 4 of 9 files at r10, 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 9 files at r10, 4 of 5 files at r11, 2 of 3 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Dismissed @Yael-Starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-:-NvAlcFK15tBYQkzmaOd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-:-NvAtDiTEeG8o92nGVLa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3gOaKEgpHNSndF6kx:-NuS6K6A7YErNwXf1hcc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L110)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

because PyBouncerConfig has two fields of bouncer_weights. one with keccak and one without keccak.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 159 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-Nu3h38t5rpkJtKriVVU:-NuS6LOD3usXUhx9VMEW:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd6bdd5af41b54c5c3c3ad42494e0c5c94d1d7d6/crates/blockifier/src/bouncer.rs#L159)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same answer, I must stay in the same crate.
</blockquote></details>

done.

**Comment by ArniStarkware** [comment]
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1648#-NsOaftc2yYlt5hYd31L):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

created : https://github.com/starkware-industries/starkware/pull/34322
now need to review
</blockquote></details>

Can be unblocked.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r12, 3 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1648)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by Yoni-Starkware** [comment]
CI is stuck

**Comment by Yoni-Starkware** [comment]
Try reopen

**Pull request closed without merging**
