### PR TITLE
feat(fee): set the resources slope values

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1363)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1363#-:-Np-PshHBY8nzOyvyY90:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1363)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 423 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1363#-NpJVSyLDYKVd90b4qXA:-NpJVSyLDYKVd90b4qXB:bll60ef) ([raw file](https://github.com/starkware-libs/blockifier/blob/f8cc1f0d2a21e50ee07a9b6a3af36e5d3583add1/crates/blockifier/src/transaction/transactions_test.rs#L423)):*
> ```XML
>                 }),
>             ),
>             (HASH_BUILTIN_NAME.to_string(), 20),
> ```

At least something like this in these tests



_Suggestion:_
```XML
 16 + 1 * len(calldata)),
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1363)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 423 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1363#-NpJVSyLDYKVd90b4qXA:-NpUw7pN-A8UO6X0ULh8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f8cc1f0d2a21e50ee07a9b6a3af36e5d3583add1/crates/blockifier/src/transaction/transactions_test.rs#L423)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

At least something like this in these tests
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1363)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1363#-:-NpVAoHuDjQ71BZiTF99:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1363)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1363)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
