### PR TITLE
Take enforce_fee into account in post-execution

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1104)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
Do we want to test it? 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1104#-:-Nijbj0R6KpQAokht4wW:b5awn0j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1104)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1104#-Nj19P451VCi43Qn0BZz:-Nj19P451VCi43Qn0B_-:ba59p7s) ([raw file](https://github.com/starkware-libs/blockifier/blob/36813725a9123f61745ad57a0e81f551ac66a5f3/crates/blockifier/src/transaction/account_transactions_test.rs#L229)):*
> ```XML
> #[case(TransactionVersion::ONE)]
> #[case(TransactionVersion::THREE)]
> fn test_enforce_fee_false_works(
> ```

What exactly are you testing? :)



_Code quote:_
```XML
fn test_enforce_fee_false_works(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1104)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1104#-Nj19P451VCi43Qn0BZz:-Nj1OiSM8Mv6bYKoE6as:b-rvi1j2) ([raw file](https://github.com/starkware-libs/blockifier/blob/36813725a9123f61745ad57a0e81f551ac66a5f3/crates/blockifier/src/transaction/account_transactions_test.rs#L229)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What exactly are you testing? :)
</blockquote></details>

`enforce_fee`.
This test ensures that when max_fee / max_amount is zero:
1. No minimal fee enforced
2. No step limit in validate
3. No step limit in execute
I'll add a check that actual_fee is zero

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1104)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1104#-Nj19P451VCi43Qn0BZz:-Nj1QxMyA7svEUDNSnvy:b-tzifu) ([raw file](https://github.com/starkware-libs/blockifier/blob/36813725a9123f61745ad57a0e81f551ac66a5f3/crates/blockifier/src/transaction/account_transactions_test.rs#L229)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`enforce_fee`.
This test ensures that when max_fee / max_amount is zero:
1. No minimal fee enforced
2. No step limit in validate
3. No step limit in execute
I'll add a check that actual_fee is zero
</blockquote></details>

Where can I see it? I only see that you run an invoke transaction

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1104)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1104#-Nj19P451VCi43Qn0BZz:-Nj1UdYlEg91wa4J7iqy:bk4co43) ([raw file](https://github.com/starkware-libs/blockifier/blob/36813725a9123f61745ad57a0e81f551ac66a5f3/crates/blockifier/src/transaction/account_transactions_test.rs#L229)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Where can I see it? I only see that you run an invoke transaction
</blockquote></details>



:P

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1104#-:-Nj1fohH1AZYSTaPO73r:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
