### PR TITLE
Update the os resources.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/840)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/840#-:-Nc2txLO5b_CnPd9Nes7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/840)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/840#-Nc2u-gp4qtDaQGTe15H:-Nc2u6J62W49ejsdkCKZ:b-fim9zd) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Python PR?
</blockquote></details>

[PR](https://reviewable.io/reviews/starkware-industries/starkware/31233)

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/840)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/840#-Nc2u-gp4qtDaQGTe15H:-Nc2yJ1bCnyOpPU2kLg5:b-auy1qz) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

[PR](https://reviewable.io/reviews/starkware-industries/starkware/31233)
</blockquote></details>

No, I mean, bumping the commit. :)

___

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/840)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/840)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/840)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/840)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/840#-Nc2u-gp4qtDaQGTe15H:-Nc6MSif1KW9bflmRBrB:bp2xfz9) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh, sorry. [Here](https://reviewable.io/reviews/starkware-industries/starkware/31477)
</blockquote></details>

The reason is that 0.12.2 is being released on Monday. 

___

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/840)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
