### PR TITLE
refactor: rename OSConstants to OsConstants

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1661)

### CODE REVIEW

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:
:crown::crown::crown::crown::crown::crown:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1661#-:-NsnUSfB1Tlc-aN75rzl:b-a382x3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1661#-:-NsrantX3qZpF3Eyyvw4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by noaov1 — COMMENTED** [review]
Note the structs `OsResources`, `PyOsConfig`. Consider changing `OSConstants` -> `OsConstants`.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1661#-:-Nttm5fXB_L0PiExR_HZ:b-xc0q7f)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by OriStarkware — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1661#-:-NttzrbgCseywQUoLnyu:bb6un1j)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1661#-:-Ntu-tQU4SxzHUcdKe7s:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1661)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1661)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
