### PR TITLE
Extract post-execution checks

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1032)

### CODE REVIEW

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1032)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1032#-NhgSwdC6WQnrIJoUsVY:-NhgSwdDC0Yv_-X-5CxV:bp3md83) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac91f6db04068646f313de0a4bfbed5b6f77bcf2/crates/blockifier/src/transaction/account_transaction.rs#L267)):*
> ```XML
>     /// After successful execution and fee computation, checks that the sender can pay the fee.
>     /// Returns the actual fee to pay and an optional revert error (if revert is needed).
>     fn post_execution_check<S: StateReader>(
> ```

consider a more informative name for this function.
something along the lines of `get_error_and_final_fee`



_Code quote:_
```XML
post_execution_check
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 271 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1032#-NhgUmH87aif1psJJZaB:-NhgUmH929_44oviGrBV:b-4x5e3x) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac91f6db04068646f313de0a4bfbed5b6f77bcf2/crates/blockifier/src/transaction/account_transaction.rs#L271)):*
> ```XML
>         account_tx_context: &AccountTransactionContext,
>         execution_state: &mut TransactionalState<'_, S>,
>         fee: Fee,
> ```

`actual_fee` or `precalculated_fee` might be better here (?)



_Code quote:_
```XML
fee
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 425 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1032#-NhgX8jq91cB2arC3lko:-NhgX8jrBUfbQKbJwnXV:b-v077s) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac91f6db04068646f313de0a4bfbed5b6f77bcf2/crates/blockifier/src/transaction/account_transaction.rs#L425)):*
> ```XML
> 
>                 // Post-execution: check senders ability and willingness to pay the fee.
>                 let (fee_to_pay, revert_error) = Self::post_execution_check(
> ```

consider replacing this with `let (revert_error, reverted_tx_fee) = ...` 
and using this only in `new_reverted`. see comments below.



_Code quote:_
```XML
let (fee_to_pay, revert_error)
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 430 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1032#-NhgU1mpDhDZqr1VL80t:-NhgU1mpDhDZqr1VL80u:boz31ai) ([raw file](https://github.com/starkware-libs/blockifier/blob/91d7ab3593320b9c82668ab6372e69aedb6dcb35/crates/blockifier/src/transaction/account_transaction.rs#L430)):*
> ```XML
>                         validate_call_info,
>                         revert_error,
>                         final_fee,
> ```

What was wrong with the name `final_fee`?

If changing this, I'd actually name it something like `reverted_tx_fee` and use it here, while keeping the `actual_fee` below



_Code quote:_
```XML
final_fee
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 457 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1032#-NhgW27Y2R2872GjYgqe:-NhgW27Y2R2872GjYgqf:bkmz6ez) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac91f6db04068646f313de0a4bfbed5b6f77bcf2/crates/blockifier/src/transaction/account_transaction.rs#L457)):*
> ```XML
>                         validate_call_info,
>                         execute_call_info,
>                         fee_to_pay,
> ```

why do you actually need the replacement from `actual_fee` here? for the error cases, sure. here I'm not at all sure it's more straight forward. Keeping the original `actual_fee` in `new_accepted` I think is better.



_Code quote:_
```XML
fee_to_pay,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1032)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1032#-NhgSwdC6WQnrIJoUsVY:-NhkKkds1ONijvx-bvak:b-efmy4s) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac91f6db04068646f313de0a4bfbed5b6f77bcf2/crates/blockifier/src/transaction/account_transaction.rs#L267)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

consider a more informative name for this function.
something along the lines of `get_error_and_final_fee`
</blockquote></details>

Done. I want to keep the `post_execution` part though
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 271 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1032#-NhgUmH87aif1psJJZaB:-NhkKs5V0_SKZ5XIixLN:b682rxi) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac91f6db04068646f313de0a4bfbed5b6f77bcf2/crates/blockifier/src/transaction/account_transaction.rs#L271)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

`actual_fee` or `precalculated_fee` might be better here (?)
</blockquote></details>

I like neither... how about this?

**Review by zuphitf — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1032#-:-Nhu_K2u51xjN_Uq-6EI:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 271 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1032#-NhgUmH87aif1psJJZaB:-NhuZmXv7Te3QU78HNXR:b920q39) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac91f6db04068646f313de0a4bfbed5b6f77bcf2/crates/blockifier/src/transaction/account_transaction.rs#L271)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I like neither... how about this?
</blockquote></details>

alright, better than just `fee`

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1032)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
