### PR TITLE
Upgrade cairo-vm

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/462)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a> 
    * **PR #449** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/449" target="_blank">Graphite</a> 
      * **PR #451** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/451" target="_blank">Graphite</a> 
        * **PR #450** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/450" target="_blank">Graphite</a> 
          * **PR #452** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/452" target="_blank">Graphite</a> 
            * **PR #458** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/458" target="_blank">Graphite</a> 
              * **PR #459** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/459" target="_blank">Graphite</a> 
                * **PR #460** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/460" target="_blank">Graphite</a> 
                  * **PR #461** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/461" target="_blank">Graphite</a> 
                    * **PR #462** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/462" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/462?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/462)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`Cargo.toml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/462#-NV9ZGOw13mfont87jVy:-NV9ZGOw13mfont87jVz:bnggcmh) ([raw file](https://github.com/starkware-libs/blockifier/blob/914848e69a8297d81c18fb8568cb8df15a021eed/Cargo.toml#L11)):*
> ```TOML
> assert_matches = "1.5.0"
> cairo-felt = "0.3.0-rc1"
> cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo", rev="04606debbffff7839689a1d1e826aed80286ef50" }
> ```

Why commit and not version?



_Code quote:_
```TOML
rev
```
___
*[`crates/blockifier/src/test_utils.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/462#-NV9ZnX3DLM10G66744M:-NV9ZnX3DLM10G66744N:b-yvfjjh) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e92231611b8461a8ec06980a1949b85397ebf72/crates/blockifier/src/test_utils.rs#L311)):*
> ```XML
>     pub fn create_for_account_testing() -> BlockContext {
>         let vm_resource_fee_cost = HashMap::from([
>             (String::from("n_steps"), 1_f64),
> ```

I think we added the suffix for the builtin names to match the fee calculation flow.
___
*[`crates/blockifier/src/abi/abi_utils.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/462#-NV9ZOCdBukFmqxecC0M:-NV9ZOCeC17azvoWnML0:b5krxr1) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e92231611b8461a8ec06980a1949b85397ebf72/crates/blockifier/src/abi/abi_utils.rs#L1)):*
> ```XML
> use cairo_vm::felt::Felt252;
> ```

I think they reexported `cairo_felt` from `cairo_vm` to not do that. TAL [here](https://github.com/lambdaclass/cairo-rs/pull/981).



_Code quote:_
```XML
cairo_vm::felt::Felt252;
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/462#-NV9_2Lm9pWUY9SWRTx9:-NV9_2Lm9pWUY9SWRTxA:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/914848e69a8297d81c18fb8568cb8df15a021eed/crates/blockifier/src/fee/fee_utils.rs#L33)):*
> ```XML
>     let vm_resource_names = HashSet::<&String>::from_iter(vm_resource_usage.0.keys());
>     println!("vm_resource_names: {:?}", vm_resource_names);
>     println!("vm_resource_fee_costs: {:?}", vm_resource_fee_costs);
> ```

Remove?



_Code quote:_
```XML
    println!("vm_resource_names: {:?}", vm_resource_names);
    println!("vm_resource_fee_costs: {:?}", vm_resource_fee_costs);
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/462#-NV9_Dhv420K5_vToEF7:-NV9_Dhv420K5_vToEF8:ba6xw9b) ([raw file](https://github.com/starkware-libs/blockifier/blob/914848e69a8297d81c18fb8568cb8df15a021eed/crates/blockifier/src/transaction/transaction_utils.rs#L13)):*
> ```XML
> use crate::transaction::transaction_types::TransactionType;
> 
> pub const BUILTIN_NAME_SUFFIX: &str = "";
> ```

Can this be removed?



_Code quote:_
```XML
pub const BUILTIN_NAME_SUFFIX: &str = "";
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/462)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul)

___
*[`Cargo.toml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/462#-NV9ZGOw13mfont87jVy:-NV9_KKa1tTESFr4922i:bttvdvq) ([raw file](https://github.com/starkware-libs/blockifier/blob/914848e69a8297d81c18fb8568cb8df15a021eed/Cargo.toml#L11)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why commit and not version?
</blockquote></details>

I need a change I just pushed - externalizing some functions. We should move to a version when its released.
___
*[`crates/blockifier/src/test_utils.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/462#-NV9ZnX3DLM10G66744M:-NV9__835f2VkuTnf3ql:b6sfflj) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e92231611b8461a8ec06980a1949b85397ebf72/crates/blockifier/src/test_utils.rs#L311)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we added the suffix for the builtin names to match the fee calculation flow.
</blockquote></details>

I had an error that these didnt match, and traced it down to cairo-rs bultin names changed to exclude "_builtin"
___
*[`crates/blockifier/src/abi/abi_utils.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/462#-NV9ZOCdBukFmqxecC0M:-NV9_WVp982sufd9Pf8U:bx43dal) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e92231611b8461a8ec06980a1949b85397ebf72/crates/blockifier/src/abi/abi_utils.rs#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think they reexported `cairo_felt` from `cairo_vm` to not do that. TAL [here](https://github.com/lambdaclass/cairo-rs/pull/981).
</blockquote></details>

Don't you think it's better to use it from cairo_felt?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/462)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/abi/abi_utils.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/462#-NV9ZOCdBukFmqxecC0M:-NV9aBdJCfPkkgmUmC1M:b12fy8k) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e92231611b8461a8ec06980a1949b85397ebf72/crates/blockifier/src/abi/abi_utils.rs#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Don't you think it's better to use it from cairo_felt?
</blockquote></details>

In that case we need to maintain both crates' versions. What's your opinion here?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/462)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/abi/abi_utils.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/462#-NV9ZOCdBukFmqxecC0M:-NV9aRiu8BDYHYKuEvin:busu7lo) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e92231611b8461a8ec06980a1949b85397ebf72/crates/blockifier/src/abi/abi_utils.rs#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

In that case we need to maintain both crates' versions. What's your opinion here?
</blockquote></details>

They are synced in version, like cairo-lang, so I think it's fine.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/462#-:-NV9aj-m98f2Qw5uQcia:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
