### PR TITLE
feat(fee): add os resources to versioned constants

### PR DESCRIPTION
**Pull request by giladchase**
- Move hardcoded os resources json into the versioned constants json, move `OsResources` into into `OsResources` module.
- Delete os_usage.rs: all logic is now called from methods in `VersionedConstants`(todo: extract into submodules, currently just a big module).
- Delete os_usage_test.rs: these are not post-deserialize validations of `OsResources`.
- the rest are getters and patching things up.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1393)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1393)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants.json` line 252 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1393#-NpJ8mND1eX-khWqhmp2:-NpJ8mND1eX-khWqhmp3:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d9a08cd9f303e456c5db7e7904b6d88cac4a4db/crates/blockifier/resources/versioned_constants.json#L252)):*
> ```JSON
>     }
>   },
>   "starknet_os_constants": {
> ```





_Suggestion:_
```JSON
os_constants
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1393#-NpJ7qaD-aLaP3jjz43F:-NpJ7qaD-aLaP3jjz43G:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d9a08cd9f303e456c5db7e7904b6d88cac4a4db/crates/blockifier/src/versioned_constants.rs#L93)):*
> ```XML
>     }
> 
>     pub fn resources_for_tx_type(&self, tx_type: &TransactionType) -> &VmExecutionResources {
> ```





_Suggestion:_
```XML
os_resources_for_tx_type
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1393#-NpJ8123B5xNM7jNizWx:-NpJ8123B5xNM7jNizWy:b-suv37h) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d9a08cd9f303e456c5db7e7904b6d88cac4a4db/crates/blockifier/src/versioned_constants.rs#L133)):*
> ```XML
> }
> 
> #[derive(Debug, Deserialize, Clone, Default)]
> ```

Alphabetize?



_Code quote:_
```XML
Debug, Deserialize, Clone, Default
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1393#-NpJ8vH9BvIC_Ndj8QPD:-NpJ8vHA3HWcvyRmup5r:b-ec3xh8) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d9a08cd9f303e456c5db7e7904b6d88cac4a4db/crates/blockifier/src/versioned_constants.rs#L136)):*
> ```XML
> // Serde trick for adding validations via a customr deserializer, without forgoing the derive.
> // See: https://github.com/serde-rs/serde/issues/1220.
> #[serde(remote = "Self")]
> ```

Can you shortly elaborate more?



_Code quote:_
```XML
#[serde(remote = "Self")]
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1393#-NpJ8S5J1HauMgpZN9uC:-NpJ8S5J1HauMgpZN9uD:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d9a08cd9f303e456c5db7e7904b6d88cac4a4db/crates/blockifier/src/versioned_constants.rs#L221)):*
> ```XML
>             os_resources.execute_syscalls.values().chain(os_resources.execute_txs_inner.values());
> 
>         for resources in all_resources {
> ```





_Suggestion:_
```XML
        let all_resources =
            os_resources.execute_syscalls.values().chain(os_resources.execute_txs_inner.values());
        for resources in all_resources {
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1393)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1393#-NpJ8vH9BvIC_Ndj8QPD:-NpQjeorE0vUe3X8MV60:b3xjtq9) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d9a08cd9f303e456c5db7e7904b6d88cac4a4db/crates/blockifier/src/versioned_constants.rs#L136)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you shortly elaborate more?
</blockquote></details>

Not sure if you meant in docstring or here :sweat_smile: 

Adding `remote = X` tells serde that the decorated struct's serialization/deserialization will be applied to the struct X whenever X is [de]serialized.

If X is `Self`, then without any custom [de]serializers, nothing happens, because its just saying "deserialize myself with myself".

However, if `remote = Self` apparently the _implementation_ ensures that Self's derived deserialization still applies, and the custom deserializer can access it.
(It looks like a "useful coincidence which is not in the official docs AFAICS, but the answer in the issue i linked is from serde's author, so it's legit.)

For our usage (and as stated in the issue), it allowed us to treat the custom deserializer of OsResources as a validator (which fails the deserialization if it does pass), without having to deserialize the fields manually.
In particular, this allowed us to use this line inside the deserializer `let os_resources = Self::deserialize(deserializer)?;` which is typically impossible to use inside a custom deserializer, because without the remote=self trick the custom deserializer _defines_ the dserializer, so it can't use it inside the definition (here it is using the derived deserizliaer... very confusing indeed).

**Review by elintul — COMMENTED** [review]
> Reviewed 5 of 21 files at r2, 3 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1393)* status: 8 of 22 files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r3, 15 of 20 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1393)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 425 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1393#-NpoODtlCWM7C5ilxjwp:-NpoODtlCWM7C5ilxjwq:b-3rhaso) ([raw file](https://github.com/starkware-libs/blockifier/blob/5bf08235fbd73965751b16454869e6c65fb05695/crates/blockifier/src/versioned_constants.rs#L425)):*
> ```XML
> 
> #[derive(Clone, Debug, Deserialize)]
> pub struct ResourcesParams {
> ```

How come it appears as added in this PR?



_Code quote:_
```XML
ResourcesParams
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1393)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 425 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1393#-NpoODtlCWM7C5ilxjwp:-NpoRkK2ERqpJnxMtGav:bsqtpdz) ([raw file](https://github.com/starkware-libs/blockifier/blob/5bf08235fbd73965751b16454869e6c65fb05695/crates/blockifier/src/versioned_constants.rs#L425)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come it appears as added in this PR?
</blockquote></details>

It's original location, os_usage.rs, has been deleted: that module isn't necessary anymore, since `OsResources` is now a private member of `VersionedConstants`.
(We should probably split up `VersionedConstants` into submodules? it's getting chubby, but probably should do that after we merge everything and agree on the design.)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1393#-:-Npowh8P9g46bdR2Zaq4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — DISMISSED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
