### PR TITLE
Added non strict nonce option.

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 571 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgIheY2C-nHBn7RNak:-NhgIheY2C-nHBn7RNal:b-34pmt9) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/transactions_test.rs#L571)):*
> ```XML
>     &mut create_state_with_cairo1_account();
>     "With Cairo1 account")]
> fn test_invalid_nonce(state: &mut CachedState<DictStateReader>) {
> ```

positive flow for non-strict case is also needed... i.e. non-strict mode accepts tx nonce strictly greater than account nonce
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 595 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgIOBMAgeAztCSOZCC:-NhgIOBMAgeAztCSOZCD:b5f1a86) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/transactions_test.rs#L595)):*
> ```XML
>     let invalid_tx_context = invalid_tx.get_account_tx_context();
>     // Increment account nonce to 1.
>     let _ = state.increment_nonce(invalid_tx_context.sender_address());
> ```

why the `let`?



_Suggestion:_
```XML
sta
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 597 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgIYEv9iimwFx1JhiQ:-NhgIYEv9iimwFx1JhiR:b-j0ybof) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/transactions_test.rs#L597)):*
> ```XML
>     let _ = state.increment_nonce(invalid_tx_context.sender_address());
>     let execution_error =
>         AccountTransaction::check_nonce(state, &invalid_tx_context, false).unwrap_err();
> ```

why not `execute` like in the previous negative flow...?



_Suggestion:_
```XML
invalid_tx.execute
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgHdUb8BLoIpjefc9p:-NhgHdUc7T6LpN8EUqZ2:bww4l59) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
> ```XML
>     }
> 
>     pub fn check_nonce(
> ```

This function should not be public, but I'm not sure what the alternatives are:
maybe the tests for pre-validation checks should be moved to `account_transaction_test`? This test has access to private `AccountTransaction` methods, and IMO it makes sense for the tests to be there (since the pre-validation checks are for account txs). if yes - maybe the method should remain public for now, and a TODO to move the tests and make the method private should be added?



_Code quote:_
```XML
pub fn check_nonce(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgHdUb8BLoIpjefc9p:-NhgKUurBRQko3IH7SjF:bsanzy8) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

This function should not be public, but I'm not sure what the alternatives are:
maybe the tests for pre-validation checks should be moved to `account_transaction_test`? This test has access to private `AccountTransaction` methods, and IMO it makes sense for the tests to be there (since the pre-validation checks are for account txs). if yes - maybe the method should remain public for now, and a TODO to move the tests and make the method private should be added?
</blockquote></details>

1. how does the account_transaction_test module have access to private functions, when the transaction_test module does not...?
2. Why call this directly in the test, instead of `execute`?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @elintul)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgHdUb8BLoIpjefc9p:-NhgKjm0-GnoTBrbwtkU:b-hsjozz) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. how does the account_transaction_test module have access to private functions, when the transaction_test module does not...?
2. Why call this directly in the test, instead of `execute`?
</blockquote></details>

1. because it's a submodule or something like that, I'm not sure, look here:
https://stackoverflow.com/questions/27978377/how-do-i-test-private-methods-in-rust#:~:text=That%20is%20unnecessary.%20Rust%20allows%20you%20to%20test%20private%20methods%20directly%3A%20play.rust%2Dlang.org/%E2%80%A6
2. because with execute the nonce check is strict, and I want to test the non-strict case
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 571 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgIheY2C-nHBn7RNak:-NhgMjTq9A0SY59ni5jC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/transactions_test.rs#L571)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

positive flow for non-strict case is also needed... i.e. non-strict mode accepts tx nonce strictly greater than account nonce
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 595 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgIOBMAgeAztCSOZCC:-NhgJYMt0XIsI-sPQl4k:b-ra758) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/transactions_test.rs#L595)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why the `let`?
</blockquote></details>

otherwise clippy complains
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 597 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgIYEv9iimwFx1JhiQ:-NhgJda49AKCcNmUVst9:bn42lbd) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/transactions_test.rs#L597)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not `execute` like in the previous negative flow...?
</blockquote></details>

because then it will be strict

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgHdUb8BLoIpjefc9p:-NhudfbjAJB5RvSw79Ta:b-jkpysz) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah...
so let's move it to account_transaction_test module
</blockquote></details>

I'll just call `perform_pre_validation_checks` directly, my mistake, duh
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 595 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgIOBMAgeAztCSOZCC:-NhudQ6p95fKWtv40Shq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1250684842fb39b5a4f9813c34022c71f1d20f/crates/blockifier/src/transaction/transactions_test.rs#L595)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because of unused result...? why?
if it's unused result, just call `unwrap` on the result (asserts ok result)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 597 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NhgQeiw4rvIbaQEUUvH:-NhudNp274yFy78WCie_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ceef312cbd57894c030ddb70921d197b7b851df/crates/blockifier/src/transaction/transactions_test.rs#L597)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

just unwrapping is fine, no need to assert ok.
unwrapping is nice because if the test fails, you'll see the failure reason
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-:-NhuucM66ozXWjVpKsEX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiT2T7gEPo3lMXEnk7W:-NiT2T7gEPo3lMXEnk7X:b7qs79l) (no related file):*
Add `PyValidator` call with `strict=false`?

___
___
*[`-- commits` line 3 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiT14UuBpJkbL7nXDjS):*
Please make sure this is the final message that will appear in master when you (automatically?) squash the commits.



_Code quote:_
```
Added non strict nonce option.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 183 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiT1l3m9fDjwQQ7t04z:-NiT1l3m9fDjwQQ7t05-:b-jpouzd) ([raw file](https://github.com/starkware-libs/blockifier/blob/025d090e8b79296e8311aa514521d1447bbb2661/crates/blockifier/src/transaction/account_transaction.rs#L183)):*
> ```XML
>             });
>         }
>         Ok(())
> ```

Less indentation.



_Suggestion:_
```XML
        let incoming_tx_nonce = account_tx_context.nonce();
        let valid_nonce =
            if strict { tx_nonce != account_nonce } else { tx_nonce >= account_nonce };

        if valid_nonce {
            Ok(())
        }
        
        Err(TransactionExecutionError::InvalidNonce { address, account_nonce, tx_nonce });
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 585 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiT2Qpw6Z8fQ8AFU7bT:-NiT2Qpw6Z8fQ8AFU7bU:b7u96ry) ([raw file](https://github.com/starkware-libs/blockifier/blob/025d090e8b79296e8311aa514521d1447bbb2661/crates/blockifier/src/transaction/account_transaction.rs#L585)):*
> ```XML
>             block_context,
>             charge_fee,
>             true,
> ```

Give this a name, please.



_Code quote:_
```XML
true,
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiT2T7gEPo3lMXEnk7W:-NiT4q2W-4cJEn4FNXi5:b7udqem) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add `PyValidator` call with `strict=false`?
</blockquote></details>

Nevermind, I see there's a separate PR. :grimacing: 

___

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 183 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiT1l3m9fDjwQQ7t04z:-NiU3ubk0VlxKsd50ZbB:b-v3y5o9) ([raw file](https://github.com/starkware-libs/blockifier/blob/025d090e8b79296e8311aa514521d1447bbb2661/crates/blockifier/src/transaction/account_transaction.rs#L183)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Less indentation.
</blockquote></details>

changed `tx_nonce` -> `incoming_tx_nonce`
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 585 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiT2Qpw6Z8fQ8AFU7bT:-NiU4U0i5iEADQVKI4bk:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/025d090e8b79296e8311aa514521d1447bbb2661/crates/blockifier/src/transaction/account_transaction.rs#L585)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give this a name, please.
</blockquote></details>

Done

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 183 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiT1l3m9fDjwQQ7t04z:-NiUI8V2A_6HRVDXl--v:b-h5nu57) ([raw file](https://github.com/starkware-libs/blockifier/blob/025d090e8b79296e8311aa514521d1447bbb2661/crates/blockifier/src/transaction/account_transaction.rs#L183)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

changed `tx_nonce` -> `incoming_tx_nonce`
</blockquote></details>

I suggested changing to `valid_nonce` for less indentation (positive flow if an early `return`).
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 551 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiUIMH99dQFyl9g2M5u:-NiUIMH99dQFyl9g2M5v:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/443336562bcd796c02612a6065997a27999ccb99/crates/blockifier/src/transaction/transactions_test.rs#L551)):*
> ```XML
>     );
> 
>     // Max_fee lower than actual fee.
> ```





_Suggestion:_
```XML
 Max fee
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 575 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiUJ0YE9O90l3mrVkTB:-NiUJ0YE9O90l3mrVkTC:bgvjkl8) ([raw file](https://github.com/starkware-libs/blockifier/blob/443336562bcd796c02612a6065997a27999ccb99/crates/blockifier/src/transaction/transactions_test.rs#L575)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing();
>     let valid_invoke_tx_args = default_invoke_tx_args();
> ```

Add a positive flow for `strict` flavor? Or does that already exist?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 576 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiUISzZ-60KyCvuRIOK:-NiUISzZ-60KyCvuRIOL:bszismt) ([raw file](https://github.com/starkware-libs/blockifier/blob/443336562bcd796c02612a6065997a27999ccb99/crates/blockifier/src/transaction/transactions_test.rs#L576)):*
> ```XML
>     let valid_invoke_tx_args = default_invoke_tx_args();
> 
>     // Strict, negative flow: account_nonce = 0, incoming_tx_nonce = 1.
> ```

x3

Try to refrain from using variable/function names in documentation (if you have to, use backticks), so you won't get false-positives when searching the code. 



_Suggestion:_
```XML
account nonce is 0, incoming transaction nonce is 1.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 599 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiUJBwb5wXQLiN5Wk7J:-NiUJBwb5wXQLiN5Wk7K:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/443336562bcd796c02612a6065997a27999ccb99/crates/blockifier/src/transaction/transactions_test.rs#L599)):*
> ```XML
>     );
> 
>     // Non-strict
> ```





_Suggestion:_
```XML
    // Non-strict.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 601 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiUJD2s78h_eZj10wEu:-NiUJD2s78h_eZj10wEv:bvnc2mb) ([raw file](https://github.com/starkware-libs/blockifier/blob/443336562bcd796c02612a6065997a27999ccb99/crates/blockifier/src/transaction/transactions_test.rs#L601)):*
> ```XML
>     // Non-strict
> 
>     // Positive flow: account_nonce = 0, incoming_tx_nonce = 1.
> ```

Can you check if we can combine some cases? Perhaps a `for` loop on `strict x case`? Or usage of parametrisation of `rstest`?
You can ask ChatGPT, can be done in another PR.

**Review by dorimedini-starkware — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 7 unresolved discussions

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 151 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NiVEkDeEHl2lC47Blne:-NiVEkDeEHl2lC47Blnf:b5e9kpu) ([raw file](https://github.com/starkware-libs/blockifier/blob/443336562bcd796c02612a6065997a27999ccb99/crates/blockifier/src/transaction/account_transaction.rs#L151)):*
> ```XML
>         block_context: &BlockContext,
>         charge_fee: bool,
>         strict: bool,
> ```

blocking myself: rename this `strict_nonce_check`



_Code quote:_
```XML
strict: bool,
```

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 138 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NijIxMP4-eh0zEpMyBr:-NijIxMP4-eh0zEpMyBs:b-75u0ve) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc74e8ed7cef8494582c48421e3e837adf52dbfd/crates/blockifier/src/transaction/account_transaction.rs#L138)):*
> ```XML
>     // Performs static checks before executing validation entry point.
>     // Note that nonce is incremented during these checks.
>     pub fn perform_pre_validation_checks<S: StateReader>(
> ```

needs to be clear (IMO) from function name that this call effects the state; just because we pass `&mut state` doesn't mean we change something (CachedState is always mutable because it can cache reads)



_Suggestion:_
```XML
pre_validation_and_nonce_increment
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NijIbn52qOLP3mOCE8X:-NijIbn52qOLP3mOCE8Y:byrq2m7) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc74e8ed7cef8494582c48421e3e837adf52dbfd/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
> ```XML
>         strict_nonce_check: bool,
>     ) -> TransactionExecutionResult<()> {
>         Self::handle_nonce(state, account_tx_context, strict_nonce_check)?;
> ```

see below



_Suggestion:_
```XML
self.handle_nonce
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 162 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NijISoH3467Jh1MRkfI:-NijISoH3467Jh1MRkfJ:boob34r) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc74e8ed7cef8494582c48421e3e837adf52dbfd/crates/blockifier/src/transaction/account_transaction.rs#L162)):*
> ```XML
>         if account_tx_context.version() == TransactionVersion::ZERO {
>             return Ok(());
>         }
> ```

use existing function please



_Suggestion:_
```XML
    fn handle_nonce(
        &self,
        state: &mut dyn State,
        account_tx_context: &AccountTransactionContext,
        strict: bool,
    ) -> TransactionExecutionResult<()> {
        if self.is_v0() {
            return Ok(());
        }
```

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 138 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NijIxMP4-eh0zEpMyBr:-NincmlV9NvoWtHRDwfY:b1sh8od) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc74e8ed7cef8494582c48421e3e837adf52dbfd/crates/blockifier/src/transaction/account_transaction.rs#L138)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

needs to be clear (IMO) from function name that this call effects the state; just because we pass `&mut state` doesn't mean we change something (CachedState is always mutable because it can cache reads)
</blockquote></details>

Renamed `perform_pre_validation_stage`
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NijIbn52qOLP3mOCE8X:-NindXbo2SWtia_6gHim:bhi2l1l) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc74e8ed7cef8494582c48421e3e837adf52dbfd/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see below
</blockquote></details>

`is_v0` is in `AccountTransactionContext`
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 162 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-NijISoH3467Jh1MRkfI:-Ninci_M5WSi8gokmmFJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc74e8ed7cef8494582c48421e3e837adf52dbfd/crates/blockifier/src/transaction/account_transaction.rs#L162)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use existing function please
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1043#-:-NisTYI22opXq7ICCykq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
