### PR TITLE
chore(execution): move compiled class fetch upwards in deploy call stack

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1674)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
Motivation?

`run_execute` is currently fairly high-level'y, and fetching things from the state can be thought of as part of the implementation of the deploy (but maybe not? :thinking: ) which is slightly lower level'y.

Perhaps this can be part of the constructor of ConstructorContext? 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1674#-:-Nu340YZDK27jwvdf_FR:bmi1lly)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1674#-Nu2sQgm1iChay3NGtVO:-Nu2sQgm1iChay3NGtVP:bcx7325) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d300596d9e86ec99e7b356eeb844ee9051d2676/crates/blockifier/src/execution/entry_point.rs#L132)):*
> ```XML
>     pub storage_address: ContractAddress,
>     pub caller_address: ContractAddress,
>     pub contract_class: &'a ContractClass,
> ```

This can be a clone (it's an `Arc` underneath).



_Code quote:_
```XML
    pub contract_class: &'a ContractClass,
```

**Review by dorimedini-starkware — COMMENTED** [review]
Motivation: on failure to deploy due to error in ctor, we want to display the ctor entry point selector in the error

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1674#-:-Nu39U8aBugl-k6lb-v8:b-t26aab)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @giladchase and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1674#-Nu2sQgm1iChay3NGtVO:-Nu39I6W7P_nmEdZUQ8R:b-w0zown) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d300596d9e86ec99e7b356eeb844ee9051d2676/crates/blockifier/src/execution/entry_point.rs#L132)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This can be a clone (it's an `Arc` underneath).
</blockquote></details>

I would rather not rely on this implementation detail; if it's no longer Arc we would unecessarily clone. Why not keep it as a lifetimed reference?

**Review by giladchase — CHANGES_REQUESTED** [review]
Can you explain more plz? i don't see why this means that it must be hoisted up the stuck?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1674#-:-Nu3DoyP0MSyWqvAKYlQ:br9k2gy)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1674#-Nu2sQgm1iChay3NGtVO:-Nu3Bl797cvmRvExbXnm:b-jplegc) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d300596d9e86ec99e7b356eeb844ee9051d2676/crates/blockifier/src/execution/entry_point.rs#L132)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would rather not rely on this implementation detail; if it's no longer Arc we would unecessarily clone. Why not keep it as a lifetimed reference?
</blockquote></details>

A lifetime reference to an `Arc`?
This might imply special meaning to readers, who would assume a clone is problematic.

Also, i suggest thinking about this as relying on StateReader API, rather than its implementation, which returns things by value.
So if you get something by value, it makes sense to own it, especially if you're a context object, which typically owns it's values (cause it's typically passed around).

**Review by dorimedini-starkware — COMMENTED** [review]
the other option is to add this data to the low-level error variant; as it is part of a containing error enum, this would mean we need to add this data to all error variants in the path to the top level error (from which we extract the selector), which doesn't make sense (not all of these variants are aware this is a ctor error, they will not all really need the selector)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1674#-:-Nu3NF97AbpP4NADUZ-T:b-y3rmi)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @giladchase and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1674#-Nu2sQgm1iChay3NGtVO:-Nu3N9XcE9Q2GyoEltjS:b7297lm) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d300596d9e86ec99e7b356eeb844ee9051d2676/crates/blockifier/src/execution/entry_point.rs#L132)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

A lifetime reference to an `Arc`?
This might imply special meaning to readers, who would assume a clone is problematic.

Also, i suggest thinking about this as relying on StateReader API, rather than its implementation, which returns things by value.
So if you get something by value, it makes sense to own it, especially if you're a context object, which typically owns it's values (cause it's typically passed around).
</blockquote></details>

would you prefer we extract only the selector and store it by value?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1674)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @giladchase and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1674#-Nu2sQgm1iChay3NGtVO:-NuNrzbm27TM1aq1wDj4:brx5hdn) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d300596d9e86ec99e7b356eeb844ee9051d2676/crates/blockifier/src/execution/entry_point.rs#L132)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

would you prefer we extract only the selector and store it by value?
</blockquote></details>

or we store the class itself by value in the context?

**Review by giladchase — COMMENTED** [review]
Can you reword this, i think there's a disconnect.
if we add something to a nested error variant we have to add to all containing variants? Don't they have access to it through the inner variant? I also don't understand the part about selector extraction, we are currently extracting it in the lower level, extracting it in the top-level is introduced in this PR...

Here what i propose:
Move the `map_err` into `execute_constructor_entry_point`, and make sure its error includes the necessary information.
If this info isn't relevant to `EntryPointExecutionResult` and only to the deploy flow, then the deploy flow should have its own error variant contained inside `EntryPointExecutionResult` (or whatever higher level error enum containing it).

Regardless, i don't think transaction#run_execute should be handling flow-specific error handling/logic (in arguably shouldn't be aware of it).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1674#-:-NuNlH7o-TXPB8WmwYXg:b-18ic8g)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Pull request closed without merging**
