### PR TITLE
Elin/merge main v0.13.1 into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 5 of 6 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, 13 of 13 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: 25 of 27 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1384#-NpAcPJp1R3RITsmRyQT:-NpAcPJq3AZ7VRUmrCRz:b-pn85jm) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae52305cfa8c8d42fb4047aef08be3e6d053b6b4/crates/blockifier/src/fee/gas_usage.rs#L34)):*
> ```XML
> }
> 
> pub fn calculate_tx_gas_and_blob_gas_usage<'a>(
> ```

Why was this merged into both branches, not via a merge?



_Code quote:_
```XML
calculate_tx_gas_and_blob_gas_usage
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: 25 of 27 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1384#-NpAcd3r9li5r7wqlNKh:-NpAcd3s3_gUoQIVudGT:b-i3ewsr) (no related file):*
@dorimedini-starkware - how should I phrase my commit message?

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384#-:-NpBRy1S1SEaIe8IKj24:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1384#-NpAcd3r9li5r7wqlNKh:-NpBRYkD-nwBFhIEipsY:b-fuhajz) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@dorimedini-starkware - how should I phrase my commit message?
</blockquote></details>

This should pass... this code block isn't doing what it should be, IIUC:
```
- name: Validate PR title with commitlint
  if: github.event_name != 'merge_group' && github.event_name != 'push'
  run: echo "${{ github.event.pull_request.title }}" | commitlint --verbose
```
will TAL tomorrow; for now you can probably write `ci: merge main-v0.13.1 into main` as a title

___
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1384#-NpAcPJp1R3RITsmRyQT:-NpBQszB6jYtZ_4mNvYl:b-wn9abr) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae52305cfa8c8d42fb4047aef08be3e6d053b6b4/crates/blockifier/src/fee/gas_usage.rs#L34)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why was this merged into both branches, not via a merge?
</blockquote></details>

Merged to main the same day main-v0.13.1 was opened; cherry-picked back after we saw the branch was opened.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1384#-NpAcd3r9li5r7wqlNKh:-NpDZJD5CTwHjdYWl08n:bfojtou) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This should pass... this code block isn't doing what it should be, IIUC:
```
- name: Validate PR title with commitlint
  if: github.event_name != 'merge_group' && github.event_name != 'push'
  run: echo "${{ github.event.pull_request.title }}" | commitlint --verbose
```
will TAL tomorrow; for now you can probably write `ci: merge main-v0.13.1 into main` as a title
</blockquote></details>

I'll wait for you to TAL.

___
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1384#-NpAcPJp1R3RITsmRyQT:-NpDZMi1Da-s5oPPuWof:b9gznte) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae52305cfa8c8d42fb4047aef08be3e6d053b6b4/crates/blockifier/src/fee/gas_usage.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Merged to main the same day main-v0.13.1 was opened; cherry-picked back after we saw the branch was opened.
</blockquote></details>

Then we should ask to rebase PRs right after a master branch is opened. I'll remember that.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1384#-NpAcd3r9li5r7wqlNKh:-NpEBf4JCIosjwxAICxw:b-imzzgs) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'll wait for you to TAL.
</blockquote></details>

try applying this diff to ci.yml?


___

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

**Review by dorimedini-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1384#-NpAcd3r9li5r7wqlNKh:-NpEBxoS4Q0d7ASRWiFl:boo752p) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

try applying this diff to ci.yml?

</blockquote></details>

this will ignore PR titles that contain the string `merge-main`

___

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 5 of 6 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, 11 of 13 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384#-:-NpEVJASErIFO6SvTORY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1384)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
