### PR TITLE
refactor: restructure old_block_number_and_hash as a struct

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1386)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1386#-NpE8dBz2j2RryxLw_op:-NpE8dBz2j2RryxLw_oq:b-ogdzet) ([raw file](https://github.com/starkware-libs/blockifier/blob/90af4fcbd44891d6bce72fd3331e10fc416d4933/crates/blockifier/src/block_execution.rs#L13)):*
> ```XML
> pub mod test;
> 
> pub struct BlockNumberHashPair {
> ```

Please shortly document this struct (assuming it's not the same number and hash, is it?).



_Code quote:_
```XML
BlockNumberHashPair
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1386)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1386#-NpE8dBz2j2RryxLw_op:-NpEMyNYBDYHQnzdL9Sn:bjofnfa) ([raw file](https://github.com/starkware-libs/blockifier/blob/90af4fcbd44891d6bce72fd3331e10fc416d4933/crates/blockifier/src/block_execution.rs#L13)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please shortly document this struct (assuming it's not the same number and hash, is it?).
</blockquote></details>

not sure what you mean by the same?
the block_number and the block_hash correspond to the same block.

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1386)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1386#-NpE8dBz2j2RryxLw_op:-NpEPKleD94iEfOAS1_-:bhqh28w) ([raw file](https://github.com/starkware-libs/blockifier/blob/90af4fcbd44891d6bce72fd3331e10fc416d4933/crates/blockifier/src/block_execution.rs#L13)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure what you mean by the same?
the block_number and the block_hash correspond to the same block.
</blockquote></details>

Right, okay. I thought it was number `n-10` and hash of `n`.
___
*[`crates/blockifier/src/block_execution.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1386#-NpEPX8G1UFviv_u6hWR:-NpEPX8HEiIhBSZ_UQWv:bk6xty0) ([raw file](https://github.com/starkware-libs/blockifier/blob/37b31c08d2681c6f3f68b8735f6fd15a7c915e7b/crates/blockifier/src/block_execution.rs#L27)):*
> ```XML
> // Writes the hash of the (current_block_number - N) block under its block number in the dedicated
> // contract state, where N=STORED_BLOCK_HASH_BUFFER.
> pub fn pre_process_block(
> ```

While you're here, can you change to an early `return` if `old_block_number_and_hash` is `None`? So that the code is less indented.



_Code quote:_
```XML
pre_process_block
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1386#-NpEPX8G1UFviv_u6hWR:-NpIsCWW8prW-Dkk9f8I:b-c7q5bd) ([raw file](https://github.com/starkware-libs/blockifier/blob/37b31c08d2681c6f3f68b8735f6fd15a7c915e7b/crates/blockifier/src/block_execution.rs#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

While you're here, can you change to an early `return` if `old_block_number_and_hash` is `None`? So that the code is less indented.
</blockquote></details>

I think it's unnecessary since in the next PR I do continue to run and create the block_context (or return error) even when it is none.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1386#-:-NpJ6skv3VKueBUByTOU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1386#-NpJ71p2Ewrw_n4dyz_C:-NpJ71p2Ewrw_n4dyz_D:b-m2asqv) (no related file):*
Please open a corresponding Python PR.

___

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1386#-NpJ71p2Ewrw_n4dyz_C:-NpK7KA1E_aLAhZj_qKN:bm7bq4h) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please open a corresponding Python PR.
</blockquote></details>

python PR: https://github.com/starkware-industries/starkware/pull/33658

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1386)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1386#-NpODSyZ8r6daPac0h_W:-NpODSyZ8r6daPac0h_X:b-83ho35) (no related file):*
Rebase over `main-v0.13.1`?

___

**Review by elintul — APPROVED** [review]
BTW, note that since you separated the PRs they can now be independent: another advantage of small self-contained PRs. ;) 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1386#-:-NpOsvP0-19qNU2RqeO8:bmt61r)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
