### PR TITLE
Add `RsStateReaderProxy` and create state_readers module

### PR DESCRIPTION
**Pull request by giladchase**
- Add `RsStateReaderProxy`, which holds a State Reader as a Python object
that implements the Rust StateReader trait. Currently unused, will be
enabled in a subsequent PR.
- Move `PapyrusReader` and `RsStateReaderProxy` into their own module
  `state_readers` (no changes in PapyrusReader).
- Export `UndeclaredClassHash` into Python so that Python will be able
  to raise it when reading state --- this is why the
  `native_blockifier_errors!` wasn't used, since we aren't wrapping a
  Rust error, we're only exporting.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/979)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/979)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/979#-NgONoJ35tfotVAnIPub:-NgONoJ35tfotVAnIPuc:b-70mc74) ([raw file](https://github.com/starkware-libs/blockifier/blob/975cc068f525c9044d05725b6f63201f84463091/crates/native_blockifier/src/errors.rs#L79)):*
> ```XML
>     UnsupportedTransactionVersion { tx_type: TransactionType, version: usize },
>     #[error("Contract class of version {version} is unsupported.")]
>     UnsupportedContractClassVersion { version: usize },
> ```

Keep variants alphabetized?
___
*[`crates/native_blockifier/src/lib.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/979#-NgOOH502QdbzGlRodHV:-NgOOH51CEm4u6qqBCWh:b-danoof) ([raw file](https://github.com/starkware-libs/blockifier/blob/975cc068f525c9044d05725b6f63201f84463091/crates/native_blockifier/src/lib.rs#L45)):*
> ```XML
>     py_module.add_class::<PyVmExecutionResources>()?;
>     py_module.add_class::<StorageConfig>()?;
>     py_module.add("UndeclaredClassHashError", py.get_type::<UndeclaredClassHashError>())?;
> ```

Why suddenly needed?
So far, we've added errors [here](https://github.com/starkware-libs/blockifier/blob/4e075aafcd338001dcbb4f1ab95931d898c8631d/crates/native_blockifier/src/errors.rs#L59).



_Code quote:_
```XML
py_module.add("UndeclaredClassHashError", py.get_type::<UndeclaredClassHashError>())?;
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/979#-NgOO1lQ7zs6Q9EJHRNm:-NgOO1lQ7zs6Q9EJHRNn:b6va7zq) ([raw file](https://github.com/starkware-libs/blockifier/blob/975cc068f525c9044d05725b6f63201f84463091/crates/native_blockifier/src/py_validator.rs#L45)):*
> ```XML
>     fn setup_validation_context(
>         &mut self,
>         next_block_info: PyBlockInfo,
> ```

If this is not used during validation, consider not passing it from Python.



_Code quote:_
```XML
next_block_info: PyBlockInfo,
```
___
*[`crates/native_blockifier/src/state_readers/py_state_reader.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/979#-NgOOD-D8NEFogY90zr4:-NgOOD-E8IddlYPFcM83:b-x3dnka) ([raw file](https://github.com/starkware-libs/blockifier/blob/975cc068f525c9044d05725b6f63201f84463091/crates/native_blockifier/src/state_readers/py_state_reader.rs#L18)):*
> ```XML
> const ON_CHAIN_STORAGE_DOMAIN: u8 = 0;
> 
> pub struct PyStateReader {
> ```

Please separate to another PR.



_Code quote:_
```XML
 PyStateReader
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/979)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/native_blockifier/src/lib.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/979#-NgOOH502QdbzGlRodHV:-NgOaWk_6GaKvM7hijJY:bhxrurc) ([raw file](https://github.com/starkware-libs/blockifier/blob/975cc068f525c9044d05725b6f63201f84463091/crates/native_blockifier/src/lib.rs#L45)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why suddenly needed?
So far, we've added errors [here](https://github.com/starkware-libs/blockifier/blob/4e075aafcd338001dcbb4f1ab95931d898c8631d/crates/native_blockifier/src/errors.rs#L59).
</blockquote></details>

Thought about this too when Dafna showed it to me back when, but it doesn't quite fit the macro's API.

The macro concerns with converting a Rust error into a Python exception and exporting it to Python.
Here, however, we only want to export this error type into Python, so that the Python State Reader could _raise_ it when it encounters an error while reading the state.
This way, since `Blockifier defined this error and exported it to Python, `Blockifier` will be able to catch the error raised from Python and handle it properly.
___
*[`crates/native_blockifier/src/py_validator.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/979#-NgOO1lQ7zs6Q9EJHRNm:-NgO_b44Br00aMkf-Zfs:b-qth06k) ([raw file](https://github.com/starkware-libs/blockifier/blob/975cc068f525c9044d05725b6f63201f84463091/crates/native_blockifier/src/py_validator.rs#L45)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

If this is not used during validation, consider not passing it from Python.
</blockquote></details>

Currently it's still needed it for `execute_raw` (which needs a `BlockContext`).
I think we need to wait for Arni's change until we can remove it, otherwise I might be encroaching on his work.
___
*[`crates/native_blockifier/src/state_readers/py_state_reader.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/979#-NgOOD-D8NEFogY90zr4:-NgO_AOAAXxPPLzQocAM:b-t829qr) ([raw file](https://github.com/starkware-libs/blockifier/blob/975cc068f525c9044d05725b6f63201f84463091/crates/native_blockifier/src/state_readers/py_state_reader.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please separate to another PR.
</blockquote></details>

OK, since this has to come before the PyValidator changes above, I'll leave it here and move the rest to a different Pr.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/979)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/native_blockifier/src/state_readers/py_state_reader.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/979#-NgOOD-D8NEFogY90zr4:-NgOl-YT8UvW1ybiMXn-:b-bd83lt) ([raw file](https://github.com/starkware-libs/blockifier/blob/975cc068f525c9044d05725b6f63201f84463091/crates/native_blockifier/src/state_readers/py_state_reader.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

OK, since this has to come before the PyValidator changes above, I'll leave it here and move the rest to a different Pr.
</blockquote></details>

Done:  https://reviewable.io/reviews/starkware-libs/blockifier/980#-

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/979)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/979#-NgTfplK6CGn_27PngZZ:-NgTfplK6CGn_27PngZ_:b-1shvm9) (no related file):*
Python side PR link?
Would like to see a test for this object [here](https://github.com/starkware-industries/starkware/blob/dev/src/starkware/starknet/business_logic/blockifier/blockifier_test.py#L406), even just accessing it and asserting it's not None would do for now.
maybe define
```
def undeclared_class_hash_exception() -> Exception:
    return native_blockifier.UndeclaredClassHashError
```
so the attribute is defined in a single place
not sure it's possible to do this though:
```
try:
    pass
except undeclared_class_hash_exception() as error:
    pass
```

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/979)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @dorimedini-starkware, and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/979#-NgTfplK6CGn_27PngZZ:-NgTlM2H7emQXHyXe9rU:b-te2nj9) (no related file):*
> Python side PR link?

Added it for the [second PR](https://reviewable.io/reviews/starkware-libs/blockifier/980), since here all of the code is disabled.

> Would like to see a test for this object [here](https://github.com/starkware-industries/starkware/blob/dev/src/starkware/starknet/business_logic/blockifier/blockifier_test.py#L406), even just accessing it and asserting it's not None would do for now.

Added to the Python PR.
I put it in a separate test, since this error is used "in the opposite direction" as the rest: those are raised from Rust, while this one is raised in Python while running as a callback from Rust.

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/979#-:-NgXv3Wi5y8F52rkFHjZ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/979)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
