### PR TITLE
Add replaced classes to append_block

### PR DESCRIPTION
**Pull request by giladchase**
Add replaced classes to append_block

- Hopefully fixes sporadic hint error during execution, of undeclared class_hash.
  Not sure why this was sporadic though
- Hoisted the reused `state_number`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXf-OvUE_5wKQuLTM0D:-NXf-OvUE_5wKQuLTM0E:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/99cbb2e713a8cc25d8fad5c0a4744cdcac91b59c/crates/native_blockifier/src/storage.rs#L146)):*
> ```XML
>             }
>         }
>         let mut declared_classes: IndexMap<ClassHash, (CompiledClassHash, ContractClass)> =
> ```

Add a blank line above.



_Code quote:_
```XML
let mut declared_classes: IndexMap<ClassHash, (CompiledClassHash, ContractClass)> =
```
___
*[`crates/native_blockifier/src/storage.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXf-SYP2xocx3f1p38E:-NXf-SYP2xocx3f1p38F:b-z8i2c6) ([raw file](https://github.com/starkware-libs/blockifier/blob/99cbb2e713a8cc25d8fad5c0a4744cdcac91b59c/crates/native_blockifier/src/storage.rs#L167)):*
> ```XML
>         }
> 
>         let mut replaced_classes: IndexMap<ContractAddress, ClassHash> = IndexMap::new();
> ```

Add a short header for this section, please.



_Code quote:_
```XML
let mut replaced_classes: IndexMap<ContractAddress, ClassHash> = IndexMap::new();
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXf0lBQ4FyGLI1ah09E:-NXf0lBQ4FyGLI1ah09F:b-43r41e) ([raw file](https://github.com/starkware-libs/blockifier/blob/688bfa2999c3a8482805f9eae78d1738340f7f93/crates/native_blockifier/src/storage.rs#L111)):*
> ```XML
>     // Previous block ID can either be a block hash (starting from a Papyrus snapshot), or a
>     // sequential ID (throughout sequencing).
>     #[allow(clippy::too_many_arguments)]
> ```

:smiling_face_with_tear: 



_Code quote:_
```XML
 #[allow(clippy::too_many_arguments)]
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXf-SYP2xocx3f1p38E:-NXf1K7v7pTlm4EO4XK1:b-18f2zs) ([raw file](https://github.com/starkware-libs/blockifier/blob/99cbb2e713a8cc25d8fad5c0a4744cdcac91b59c/crates/native_blockifier/src/storage.rs#L167)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a short header for this section, please.
</blockquote></details>

This is not true, Cairo1<>Cairo1 can only happen (i.e., upgrading flow). 
Only say these are the replaces classes.
___
*[`crates/native_blockifier/src/storage.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXf0lBQ4FyGLI1ah09E:-NXf1E8i0MrKEINK6xq9:b29o7q0) ([raw file](https://github.com/starkware-libs/blockifier/blob/688bfa2999c3a8482805f9eae78d1738340f7f93/crates/native_blockifier/src/storage.rs#L111)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

:smiling_face_with_tear: 
</blockquote></details>

Damn. We'll bundle some stuff later.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXf-SYP2xocx3f1p38E:-NXfMixX11Ks8lwVt6Mq:b-yhiqrt) ([raw file](https://github.com/starkware-libs/blockifier/blob/99cbb2e713a8cc25d8fad5c0a4744cdcac91b59c/crates/native_blockifier/src/storage.rs#L167)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is not true, Cairo1<>Cairo1 can only happen (i.e., upgrading flow). 
Only say these are the replaces classes.
</blockquote></details>

Gotcha, fixed (for the changed code).

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfY7Id3V_UT1Poog1V:-NXfY7IeB3jVd1G7B7b1:bw1rrja) ([raw file](https://github.com/starkware-libs/blockifier/blob/3594158ba17695957b678914fc99bdbe6b4bd253/crates/native_blockifier/src/storage.rs#L185)):*
> ```XML
>         let mut py_state_diff = py_state_diff;
>         replaced_classes.keys().for_each(|&address| {
>             py_state_diff.address_to_class_hash.remove(&address.into());
> ```

This seemed more readable than `PyFelt::from(address)`.
Logic being that `PyFelt` is just glue, so should probably be hid when possible and without harming readability.



_Code quote:_
```XML
(&address.into());
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfXXq31s5KoaGKe8nn:-NXfXXq31s5KoaGKe8no:b-czr4bp) ([raw file](https://github.com/starkware-libs/blockifier/blob/52d08a22421546f766c778939cd7d120dff368f6/crates/native_blockifier/src/storage.rs#L168)):*
> ```XML
>         // These entries correspond to contract addresses whose class has been replaced with a new
>         // contract.
>         // Note: Replacing `cairo1` contracts with `cairo0` contracts is not supported.
> ```

I think that's enough.



_Suggestion:_
```XML
        // Collect replaced classes (changed class hash of an already allocated address; 
        // i.e.: pointing to a non-zeroed class hash). Rest would be (newly) deployed classe.
```
___
*[`crates/native_blockifier/src/storage.rs` line 177 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfYI-LEp-BrOCMx_Mp:-NXfYI-LEp-BrOCMx_Mq:b-eyu56f) ([raw file](https://github.com/starkware-libs/blockifier/blob/52d08a22421546f766c778939cd7d120dff368f6/crates/native_blockifier/src/storage.rs#L177)):*
> ```XML
>                 .get_state_reader()?
>                 .get_class_hash_at(state_number, &address)
>                 .is_ok();
> ```

It would also be `Ok` for non-existent or replaced class; you should check if `is_some()`.



_Code quote:_
```XML
.is_ok();
```
___
*[`crates/native_blockifier/src/storage.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfY7Id3V_UT1Poog1V:-NXfYV6qA3xzb43o0kQ1:b-ddrx25) ([raw file](https://github.com/starkware-libs/blockifier/blob/3594158ba17695957b678914fc99bdbe6b4bd253/crates/native_blockifier/src/storage.rs#L185)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This seemed more readable than `PyFelt::from(address)`.
Logic being that `PyFelt` is just glue, so should probably be hid when possible and without harming readability.
</blockquote></details>

Yeah, I think we should reconsider this convention...

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 177 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfYI-LEp-BrOCMx_Mp:-NXfZ0o3E0CqFQbFYIyt:bkkxxoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/52d08a22421546f766c778939cd7d120dff368f6/crates/native_blockifier/src/storage.rs#L177)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It would also be `Ok` for non-existent or replaced class; you should check if `is_some()`.
</blockquote></details>

Sorry, `is_deployed = !X.is_none()`.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 177 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfYI-LEp-BrOCMx_Mp:-NXfZ9aaEhKQjDAjaEcA:b-6tezuf) ([raw file](https://github.com/starkware-libs/blockifier/blob/52d08a22421546f766c778939cd7d120dff368f6/crates/native_blockifier/src/storage.rs#L177)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Sorry, `is_deployed = !X.is_none()`.
</blockquote></details>

Sorry, `address_unassigned = X.is_none()`. Then if `!address_unassigned`, it is a replace. :hot_face:

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfXXq31s5KoaGKe8nn:-NXfagwh6lTBxWJycVEO:b-l0xsdl) ([raw file](https://github.com/starkware-libs/blockifier/blob/52d08a22421546f766c778939cd7d120dff368f6/crates/native_blockifier/src/storage.rs#L168)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think that's enough.
</blockquote></details>

TulGPTinsky.
___
*[`crates/native_blockifier/src/storage.rs` line 177 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfYI-LEp-BrOCMx_Mp:-NXfb5T92d0KrL06uywP:b-qhlbny) ([raw file](https://github.com/starkware-libs/blockifier/blob/52d08a22421546f766c778939cd7d120dff368f6/crates/native_blockifier/src/storage.rs#L177)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Sorry, `address_unassigned = X.is_none()`. Then if `!address_unassigned`, it is a replace. :hot_face: 
 
</blockquote></details>

:facepalm: right right THANK YOU, that would have been hard to spot later.
Why the last change? couldn't it be `address_assigned` without the double negative?
___
*[`crates/native_blockifier/src/storage.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfY7Id3V_UT1Poog1V:-NXfbFDe6XCrKsBORCx7:b-xon3ct) ([raw file](https://github.com/starkware-libs/blockifier/blob/3594158ba17695957b678914fc99bdbe6b4bd253/crates/native_blockifier/src/storage.rs#L185)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yeah, I think we should reconsider this convention...
</blockquote></details>

Not altogether; sometimes it will obfuscate IMO.
For example, `let state_diff = StateDiff::from(py_state_diff)` is IMO better than `let state_diff = py_state_diff::into()`, even though the latter might compile due to the compiler deducing the type.
And of course `let state_diff: StateDiff = py_state_diff.into()` is a bit awk.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfXXq31s5KoaGKe8nn:-NXfYmsL5JNT15vOjEvK:b-rpahry) ([raw file](https://github.com/starkware-libs/blockifier/blob/52d08a22421546f766c778939cd7d120dff368f6/crates/native_blockifier/src/storage.rs#L168)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

TulGPTinsky.
</blockquote></details>

:grimacing:

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 177 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXfYI-LEp-BrOCMx_Mp:-NXhSEuG3dXKIpfG5gDm:bjyhdo4) ([raw file](https://github.com/starkware-libs/blockifier/blob/52d08a22421546f766c778939cd7d120dff368f6/crates/native_blockifier/src/storage.rs#L177)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

:facepalm: right right THANK YOU, that would have been hard to spot later.
Why the last change? couldn't it be `address_assigned` without the double negative?
</blockquote></details>

I meant that if it's `Some`, it's no necessarily deployed, but taken. You can also go with `address_assigned` or `address_taken`.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`-- commits` line 1 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/595#-NXiLjxF5W0PKany0jGB):*
Blocking this PR until main-v0.12.0 is stable in Python.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/595#-:-NXk5x-eBjF84wARM9ft:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
