### PR TITLE
chore: clean fee utils

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1968)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1968)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1968#-Nzmjec21hJ3yCXWmraf:-Nzmjec21hJ3yCXWmrag:b-7506bi) ([raw file](https://github.com/starkware-libs/blockifier/blob/e440026c30d1d1571fc308be8612ad6bc0c801d2/crates/blockifier/src/test_utils.rs#L455)):*
> ```XML
>         .to_gas_vector(&block_context.versioned_constants, block_context.block_info.use_kzg_da)?;
>     Ok(get_fee_by_gas_vector(&block_context.block_info, gas_vector, fee_type))
> }
> ```

make this a method of TransactionResources please, next to `to_gas_vector`



_Code quote:_
```XML
pub fn calculate_tx_fee(
    tx_resources: &TransactionResources,
    block_context: &BlockContext,
    fee_type: &FeeType,
) -> TransactionFeeResult<Fee> {
    let gas_vector = tx_resources
        .to_gas_vector(&block_context.versioned_constants, block_context.block_info.use_kzg_da)?;
    Ok(get_fee_by_gas_vector(&block_context.block_info, gas_vector, fee_type))
}
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1968)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1968#-Nzmjec21hJ3yCXWmraf:-NzmvWv12gXvK0x1Esk1:b4vqk6e) ([raw file](https://github.com/starkware-libs/blockifier/blob/e440026c30d1d1571fc308be8612ad6bc0c801d2/crates/blockifier/src/test_utils.rs#L455)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

make this a method of TransactionResources please, next to `to_gas_vector`
</blockquote></details>

Why? It is used only in tests.
Or did you mean to put it under `test` config?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1968)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1968#-Nzmjec21hJ3yCXWmraf:-NzqwJnuAN5-rm_cFVU2:bgwwqbw) ([raw file](https://github.com/starkware-libs/blockifier/blob/e440026c30d1d1571fc308be8612ad6bc0c801d2/crates/blockifier/src/test_utils.rs#L455)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why? It is used only in tests.
Or did you mean to put it under `test` config?
</blockquote></details>

I would simply like all fee manipulation logic to be encapsulated in one object, instead of many utilities floating around without context.
maybe add an `impl TransactionResources` block in a test_utils module, with this function?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1968)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1968#-Nzmjec21hJ3yCXWmraf:-Nzw2dOP4OMkq4uYTbl6:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e440026c30d1d1571fc308be8612ad6bc0c801d2/crates/blockifier/src/test_utils.rs#L455)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would simply like all fee manipulation logic to be encapsulated in one object, instead of many utilities floating around without context.
maybe add an `impl TransactionResources` block in a test_utils module, with this function?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1968#-:-Nzw44VvABBIoTJWUPRe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
