### PR TITLE
Handle __default__ in resolve_entry_point_pc

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/errors.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQu0UzI0qBT-4Ux4giq:-NQu0UzI0qBT-4Ux4gir:bfhambl) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb598ae5519b7ce8f6c64569771bc4729bb235a5/crates/blockifier/src/execution/errors.rs#L18)):*
> ```XML
>     EntryPointNotFound(EntryPointSelector),
>     #[error("No entry points of type {0:?} found in contract.")]
>     NoEntryPointOfTypeFound(EntryPointType),
> ```

Why did you add this error? Do we want to differentiate it from the case where a `__default__` of the same type was not found?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/errors.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQu0UzI0qBT-4Ux4giq:-NQu39Hu4t_DRDMDuF3A:bbdjg6o) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb598ae5519b7ce8f6c64569771bc4729bb235a5/crates/blockifier/src/execution/errors.rs#L18)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you add this error? Do we want to differentiate it from the case where a `__default__` of the same type was not found?
</blockquote></details>

I assumed so, why not? It will help debug situations where `__default__` is expected but `__l1_default__` is implemented and vice-versa, no?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/errors.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQu0UzI0qBT-4Ux4giq:-NQu6eTi1lCTCW7jy8KA:bu112rw) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb598ae5519b7ce8f6c64569771bc4729bb235a5/crates/blockifier/src/execution/errors.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I assumed so, why not? It will help debug situations where `__default__` is expected but `__l1_default__` is implemented and vice-versa, no?
</blockquote></details>

hmmm but I think you're right... if the contract has an external func and an l1 handler, neither of them `__default__`, its not informative... I'll make it the same error

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQu6Olf8KiC7i9smal0:-NQu6Olf8KiC7i9smal1:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb598ae5519b7ce8f6c64569771bc4729bb235a5/crates/blockifier/src/execution/entry_point.rs#L84)):*
> ```XML
>             None => {
>                 // If there are entry points at all, and the first one is the default entry point,
>                 // return it's offset.
> ```





_Suggestion:_
```XML
                // Returns the default entrypoint if the given selector is missing.
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQuauIH3UclTOnOdwA2:-NQuauIH3UclTOnOdwA3:b-jdgqja) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb598ae5519b7ce8f6c64569771bc4729bb235a5/crates/blockifier/src/execution/entry_point.rs#L81)):*
> ```XML
>             &contract_class.entry_points_by_type[&self.entry_point_type];
>         match entry_points_of_same_type.iter().find(|ep| ep.selector == self.entry_point_selector) {
>             Some(entry_point) => Ok(entry_point.offset.0),
> ```

Can you please add [this](https://github.com/starkware-industries/starkware/blob/653b434bbe126b57fbd66f2da740e4ef182d1cef/src/starkware/starknet/business_logic/execution/execute_entry_point.py#L415:~:text=len(filtered_entry_points)%20%3D%3D%201%2C) assertion as well?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQuauIH3UclTOnOdwA2:-NQuxGnV3yqnoR4ZMSTV:b-moccck) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb598ae5519b7ce8f6c64569771bc4729bb235a5/crates/blockifier/src/execution/entry_point.rs#L81)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please add [this](https://github.com/starkware-industries/starkware/blob/653b434bbe126b57fbd66f2da740e4ef182d1cef/src/starkware/starknet/business_logic/execution/execute_entry_point.py#L415:~:text=len(filtered_entry_points)%20%3D%3D%201%2C) assertion as well?
</blockquote></details>

OK, but the only logical change now is that we assert there is no more than one entry point with a matching selector. Is this a necessary check?
___
*[`crates/blockifier/src/execution/entry_point.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQu6Olf8KiC7i9smal0:-NQuwM8-2O04Rj085DSt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb598ae5519b7ce8f6c64569771bc4729bb235a5/crates/blockifier/src/execution/entry_point.rs#L84)):*
> ```XML
>             None => {
>                 // If there are entry points at all, and the first one is the default entry point,
>                 // return it's offset.
> ```

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQuauIH3UclTOnOdwA2:-NQyGoW76A-97CBvGSKQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb598ae5519b7ce8f6c64569771bc4729bb235a5/crates/blockifier/src/execution/entry_point.rs#L81)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes. We only allow one EP from each name (i.e. no overloading allowed). When calculating the selector we hash only the name (and not the full signature of the EP). That is, when more than one EP matches the given selector it means that we have two EPs with the same name, which is not allowed.
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQu6Olf8KiC7i9smal0:-NQyTLpf49dkHGVLrUJ4:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb598ae5519b7ce8f6c64569771bc4729bb235a5/crates/blockifier/src/execution/entry_point.rs#L84)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>





_Suggestion:_
```XML
Returns
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQygJQD0YT5qICyFiMt:-NQygJQD0YT5qICyFiMu:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L98)):*
> ```XML
>                 }
>                 None => {
>                     // No entry points of the correct type.
> ```





_Suggestion:_
```XML
No default entry points of the correct type.
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQyeixJ3OsLXGrHdcwF:-NQyeixJ3OsLXGrHdcwG:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L104)):*
> ```XML
>         }
> 
>         // At least two entry points with same selector.
> ```





_Suggestion:_
```XML
Non-unique entry points are not possible.
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQyfBsw0W0S58fyUcOi:-NQyfBsw0W0S58fyUcOj:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L113)):*
> ```XML
>             None => not_found_error, // Unreachable, but error is better than panic.
>             Some(entry_point) => Ok(entry_point.offset.0),
>         }
> ```





_Suggestion:_
```XML
       let entry_point = filtered_entry_points.get(0).expect("The number of entry points with the given selector is exactly one.");
       
      Ok(entry_point.offset.0),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQygJQD0YT5qICyFiMt:-NQzNRpa54fYmyHklybS:b9kla0c) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L98)):*
> ```XML
>                 }
>                 None => {
>                     // No entry points of the correct type.
> ```

why? if `entry_points_of_same_type.get(0)` is `None` then there are no entry points of that type, default or not
___
*[`crates/blockifier/src/execution/entry_point.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQyeixJ3OsLXGrHdcwF:-NQzNbAwEoFyWn52axBN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L104)):*
> ```XML
>         }
> 
>         // At least two entry points with same selector.
> ```

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQyfBsw0W0S58fyUcOi:-NQzOFj82ftbM0Smvdxx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L113)):*
> ```XML
>             None => not_found_error, // Unreachable, but error is better than panic.
>             Some(entry_point) => Ok(entry_point.offset.0),
>         }
> ```

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 90 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQz_YHHAmmNBHpHGEpg:-NQz_YHHAmmNBHpHGEph:by0bz0w) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L90)):*
> ```XML
>             match entry_points_of_same_type.get(0) {
>                 Some(entry_point) => {
>                     if entry_point.selector == selector_from_name(DEFAULT_ENTRY_POINT_NAME) {
> ```

@noaov1 what if `self.entry_point_type` is `L1Handler`?
shouldn't we check for it's default selector in this case?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 90 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQz_YHHAmmNBHpHGEpg:-NQzbIo6Aord2oZORHV-:bf42u4i) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@noaov1 what if `self.entry_point_type` is `L1Handler`?
shouldn't we check for it's default selector in this case?
</blockquote></details>

added a TODO on you :P

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 90 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQz_YHHAmmNBHpHGEpg:-NQzkfpK2yUD5TcHh4E1:b-aedmc9) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

added a TODO on you :P
</blockquote></details>

I think you can remove it. Lior said that the selector of the default entry point should always be 0. Maybe add a note?
___
*[`crates/blockifier/src/execution/entry_point.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQygJQD0YT5qICyFiMt:-NQzktIeEJHqmBaQXvxq:b-3r8r1s) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L98)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why? if `entry_points_of_same_type.get(0)` is `None` then there are no entry points of that type, default or not
</blockquote></details>

You are right. My bad. Maybe the note is redundant given the error. WDYT?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 90 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/344#-NQz_YHHAmmNBHpHGEpg:-NR--Lc9BIr2Rpg0bdPX:bx2o68f) ([raw file](https://github.com/starkware-libs/blockifier/blob/c06d42ff2b1f8b83fc932f6bb3389dfa40cca3eb/crates/blockifier/src/execution/entry_point.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Like this?
</blockquote></details>

nvm, I just used the selector value directly... seems better to me, even though there *is* a `selector_from_name`. Now it's clear the entry point type doesn't matter

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/344#-:-NR2A9416YTsEhDXD-fc:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
