### PR TITLE
refactor: add gas_costs_struct to OSConstants

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 374 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NsEJNCO4iqNU430JaJM:-NsEJNCO4iqNU430JaJN:bucuucs) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6f73166230561abee83e51de0bbfc86162019c4/crates/blockifier/src/versioned_constants.rs#L374)):*
> ```XML
> // FIXME FOLLOWUP: if we switch from JSON, we can switch to strongly typed fields, instead of an
> // internal indexmap: using strongly typed fields breaks the order under serialization, making
> // testing very difficult.
> ```

Can do in a separate PR if you want, or wherever
___
*[`crates/blockifier/src/versioned_constants.rs` line 384 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NsEJeH14F0sw7egAwFE:-NsEJeH14F0sw7egAwFF:b-w61eb2) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6f73166230561abee83e51de0bbfc86162019c4/crates/blockifier/src/versioned_constants.rs#L384)):*
> ```XML
>     // Invariant: fixed keys.
>     gas_costs: IndexMap<String, u64>,
> }
> ```

This will be removed in favor of the struct in later PR I'm assuming?



_Code quote:_
```XML
    gas_costs: IndexMap<String, u64>,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NsEFfuSBhHqIdBTi3Kp:-NsEFfuSBhHqIdBTi3Kq:b-v4yej) ([raw file](https://github.com/starkware-libs/blockifier/blob/f469b095b30ba3e7d7837236d3d0cb06f69ae54e/crates/blockifier/src/versioned_constants.rs#L390)):*
> ```XML
> // ignored. See documentation in core/os/constants.cairo.
> #[derive(Clone, Debug, Default, Deserialize)]
> pub struct GasCosts {
> ```

I'd remove the `Clone`, this is a big struct...
Technically, it can even derive `Copy`, but I wouldn't expose that unless we must.
If we only expose it via an Arc, then it shouldn't matter anyway, cause it's cloned via `Arc` anyway.



_Code quote:_
```XML
#[derive(Clone, Debug, Default, Deserialize)]
pub struct GasCosts {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 497 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NsEHo0P-zEU4byeAbY5:-NsEHo0P-zEU4byeAbY6:b-8tbplw) ([raw file](https://github.com/starkware-libs/blockifier/blob/f469b095b30ba3e7d7837236d3d0cb06f69ae54e/crates/blockifier/src/versioned_constants.rs#L497)):*
> ```XML
>         let gas_costs = raw_json_data.parse_gas_costs()?;
>         let json_value = serde_json::to_value(&gas_costs).unwrap();
>         let gas_costs_struct: GasCosts = serde_json::from_value(json_value).unwrap();
> ```

WDYT? I'm not a fan of `and_then` generally, but maybe it works in this instance?



_Suggestion:_
```XML
        let gas_costs_struct: GasCosts =
            serde_json::to_value(&gas_costs).and_then(serde_json::from_value).unwrap();
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 384 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NsEJeH14F0sw7egAwFE:-NsZRfS8-3tjgDspx9Ue:bcp3t3l) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6f73166230561abee83e51de0bbfc86162019c4/crates/blockifier/src/versioned_constants.rs#L384)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This will be removed in favor of the struct in later PR I'm assuming?
</blockquote></details>

Yes, in this PR: https://reviewable.io/reviews/starkware-libs/blockifier/1620
___
*[`crates/blockifier/src/versioned_constants.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NsEFfuSBhHqIdBTi3Kp:-NsZV2YI7u3hqI-iGI3z:b-s0hz5b) ([raw file](https://github.com/starkware-libs/blockifier/blob/f469b095b30ba3e7d7837236d3d0cb06f69ae54e/crates/blockifier/src/versioned_constants.rs#L390)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I'd remove the `Clone`, this is a big struct...
Technically, it can even derive `Copy`, but I wouldn't expose that unless we must.
If we only expose it via an Arc, then it shouldn't matter anyway, cause it's cloned via `Arc` anyway.
</blockquote></details>

`OSConstants` has `clone`, can `GasCosts` be a field of `OSConstants` without having `clone`?
___
*[`crates/blockifier/src/versioned_constants.rs` line 497 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NsEHo0P-zEU4byeAbY5:-NsZVhuC8x6nDyi8_M2S:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f469b095b30ba3e7d7837236d3d0cb06f69ae54e/crates/blockifier/src/versioned_constants.rs#L497)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

WDYT? I'm not a fan of `and_then` generally, but maybe it works in this instance?
</blockquote></details>

Done.

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @giladchase, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 497 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NscPPQS6_pf9U9WPasE:-NscPPQS6_pf9U9WPasF:bnzivji) ([raw file](https://github.com/starkware-libs/blockifier/blob/8df431966ad22915d089e718bce590b51d58202d/crates/blockifier/src/versioned_constants.rs#L497)):*
> ```XML
>         let gas_costs = raw_json_data.parse_gas_costs()?;
>         let gas_costs_struct: GasCosts =
>             serde_json::to_value(&gas_costs).and_then(serde_json::from_value).unwrap();
> ```

the `_struct` is an implementation detail, IMO shouldn't be used as a suffix.
I suggest moving this logic to a `TryFrom` implementation to `GasCosts` and then something like:



_Suggestion:_
```XML
        let gas_costs = GasCosts::try_from(raw_json_data);
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 497 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NscPPQS6_pf9U9WPasE:-NscV6EgBl03w8WJcKyA:b-be2v7m) ([raw file](https://github.com/starkware-libs/blockifier/blob/8df431966ad22915d089e718bce590b51d58202d/crates/blockifier/src/versioned_constants.rs#L497)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

the `_struct` is an implementation detail, IMO shouldn't be used as a suffix.
I suggest moving this logic to a `TryFrom` implementation to `GasCosts` and then something like:
</blockquote></details>

Great idea. I will open another PR at the end. I can not do this efficiently now because I use both gas_costs and gas_costs_struct. Adding TODO.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-:-NsmhnGc92p8ai9-H8yl:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

**Review by barak-b-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

**Review by barak-b-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-:-NsrZOCJ984bUO-boyHx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: all files reviewed, 9 unresolved discussions (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NsEFfuSBhHqIdBTi3Kp:-NtWKQ8b4qnHi8ZjifvD:b-hj4j0y) ([raw file](https://github.com/starkware-libs/blockifier/blob/f469b095b30ba3e7d7837236d3d0cb06f69ae54e/crates/blockifier/src/versioned_constants.rs#L390)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

`OSConstants` has `clone`, can `GasCosts` be a field of `OSConstants` without having `clone`?
</blockquote></details>

Consider removing the clone from `OsConstants`
___
*[`crates/blockifier/src/versioned_constants.rs` line 427 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWL-pSEM4cGyd8picz:-NtWL-pSEM4cGyd8pid-:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L427)):*
> ```XML
> 
> // List of all gas cost constants that *must* be present in the JSON file, all other consts are
> // ignored. See documentation in core/os/constants.cairo.
> ```





_Suggestion:_
```XML
/// Gas cost constants. For more documentation see in core/os/constants.cairo.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 434 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWLnIC4p7QBGUHK8db:-NtWLnIDEextABOAnaNX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L434)):*
> ```XML
>     pub memory_hole_gas_cost: u64,
>     // An estimation of the initial gas for a transaction to run with. This solution is
>     // temporary and this value will become a field of the transaction.
> ```





_Suggestion:_
```XML
    // An estimation of the initial gas for a transaction to run with. This solution is
    // temporary and this value will be deduced from the transaction's fields.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 436 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWMCPs-awDg9lyxgUT:-NtWMCPs-awDg9lyxgUU:bmp3lmd) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L436)):*
> ```XML
>     // temporary and this value will become a field of the transaction.
>     pub initial_gas_cost: u64,
>     // ** Compiler gas costs **
> ```

What does it mean?



_Suggestion:_
```XML
    // Compiler gas costs.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 439 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWM2u04m2HauSC_GWM:-NtWM2u1Bys3sBImmNqU:b-2q9cuv) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L439)):*
> ```XML
>     pub entry_point_initial_budget: u64,
>     // The initial gas budget for a system call (this value is hard-coded by the compiler).
>     // This needs to be high enough to cover OS costs in the case of failure due to out of gas.
> ```

Written in `core/os/constants.cairo`.
___
*[`crates/blockifier/src/versioned_constants.rs` line 441 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWMFNv8cdXD7RhS2Be:-NtWMFNv8cdXD7RhS2Bf:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L441)):*
> ```XML
>     // This needs to be high enough to cover OS costs in the case of failure due to out of gas.
>     pub syscall_base_gas_cost: u64,
>     // ** OS gas costs **
> ```





_Suggestion:_
```XML
    // OS gas costs.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 445 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWMUYO1RYmIQ9qITSf:-NtWMUYO1RYmIQ9qITSg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L445)):*
> ```XML
>     pub fee_transfer_gas_cost: u64,
>     pub transaction_gas_cost: u64,
>     // ** Required gas for each syscall **
> ```





_Suggestion:_
```XML
    // Syscall gas costs.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 553 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWNQeQ7UPZNltC3HvD:-NtWNQeQ7UPZNltC3HvE:b-ovggg7) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L553)):*
> ```XML
>         let gas_costs = raw_json_data.parse_gas_costs()?;
>         let gas_costs_struct: GasCosts =
>             serde_json::to_value(&gas_costs).and_then(serde_json::from_value).unwrap();
> ```

When will it fail?



_Suggestion:_
```XML
        let gas_costs_raw = raw_json_data.parse_gas_costs()?;
        let gas_costs: GasCosts =
            serde_json::to_value(&gas_costs).and_then(serde_json::from_value).expect("some error message);
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: all files reviewed, 10 unresolved discussions (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 420 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWbBa94Dqj9GQqHBQb:-NtWbBaAAeX81-myUXez:b-ha8w9y) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L420)):*
> ```XML
> pub struct OSConstants {
>     pub gas_costs_struct: GasCosts,
>     validate_rounding_consts: ValidateRoundingConsts,
> ```

Why isn't this field public?



_Code quote:_
```XML
    validate_rounding_consts: ValidateRoundingConsts,
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: all files reviewed, 9 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NsEFfuSBhHqIdBTi3Kp:-Ntq16U5DzdRbP_wsmzq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f469b095b30ba3e7d7837236d3d0cb06f69ae54e/crates/blockifier/src/versioned_constants.rs#L390)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider removing the clone from `OsConstants`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 420 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWbBa94Dqj9GQqHBQb:-Ntq-n77E8lrDc571oQ0:b-jribqh) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L420)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why isn't this field public?
</blockquote></details>

I am not sure, we can make it public in a different PR if you prefer
___
*[`crates/blockifier/src/versioned_constants.rs` line 427 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWL-pSEM4cGyd8picz:-Ntq08tX5BZ1bYlHV82M:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L427)):*
> ```XML
> 
> // List of all gas cost constants that *must* be present in the JSON file, all other consts are
> // ignored. See documentation in core/os/constants.cairo.
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 436 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWMCPs-awDg9lyxgUT:-Ntq0SS78e6eFBJUsrNv:b-wnp0wm) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L436)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What does it mean?
</blockquote></details>

This was the original comment from ALLOWED_GAS_COST_NAMES, but we can change that.
___
*[`crates/blockifier/src/versioned_constants.rs` line 439 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWM2u04m2HauSC_GWM:-Ntq0f7-Eam8cjCZ2a5z:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L439)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Written in `core/os/constants.cairo`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 441 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWMFNv8cdXD7RhS2Be:-Ntq0hs5AwDqx7Ue2t-2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L441)):*
> ```XML
>     // This needs to be high enough to cover OS costs in the case of failure due to out of gas.
>     pub syscall_base_gas_cost: u64,
>     // ** OS gas costs **
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 445 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWMUYO1RYmIQ9qITSf:-Ntq0lfy-yBH-3RcknHo:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L445)):*
> ```XML
>     pub fee_transfer_gas_cost: u64,
>     pub transaction_gas_cost: u64,
>     // ** Required gas for each syscall **
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 553 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWNQeQ7UPZNltC3HvD:-Ntq1jtu21tBEiDhad4F:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L553)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When will it fail?
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
Please move the `create_for_testing_from_subset` method to be a method of `GasCost` struct.  

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-:-NttZWi--VOAdhFPzUCa:b-mn36rv)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 420 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWbBa94Dqj9GQqHBQb:-NttWN3Y6utE5MYpMJ6J:b-ame29z) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L420)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

I am not sure, we can make it public in a different PR if you prefer
</blockquote></details>

Can you please ask @giladchase ?
___
*[`crates/blockifier/src/versioned_constants.rs` line 553 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWNQeQ7UPZNltC3HvD:-NttXNZk23zDeukbky7d:brnvkk1) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L553)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm asking to understand if it's okay to panic in this case.

**Review by OriStarkware — COMMENTED** [review]
Let's consider that in a different PR

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-:-NttrjrK9T-PU6zYcpsK:b-bru6l)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 420 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWbBa94Dqj9GQqHBQb:-NttjQZp3p2ZM7PHCw2R:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L420)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please ask @giladchase ?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 553 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWNQeQ7UPZNltC3HvD:-NttlUZwEjdiWgpdbasC:b5uwr46) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L553)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm asking to understand if it's okay to panic in this case.
</blockquote></details>

We should not panic. I added an error.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/versioned_constants.rs` line 439 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWM2u04m2HauSC_GWM:-NttzCvc-TmK23DvkuuE:bub23fi) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L439)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant in the `GasCost` struct doc.
___
*[`crates/blockifier/src/versioned_constants.rs` line 441 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWMFNv8cdXD7RhS2Be:-Nttys6j86o--VJr_3Uu:bub23fi) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L441)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant in the `GasCost` struct doc.
___
*[`crates/blockifier/src/versioned_constants.rs` line 445 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWMUYO1RYmIQ9qITSf:-Nttyu-lD1AVZHepRGAy:bub23fi) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L445)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant in the `GasCost` struct doc.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @OriStarkware)

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 439 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWM2u04m2HauSC_GWM:-Ntu06953F-JkDPxztZj:bxe5hf5) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L439)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I meant in the `GasCost` struct doc.
</blockquote></details>

You are correct, my bad.
___
*[`crates/blockifier/src/versioned_constants.rs` line 441 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWMFNv8cdXD7RhS2Be:-Ntu0A0H9RfkUCO3fQJ3:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L441)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I meant in the `GasCost` struct doc.
</blockquote></details>

Done
___
*[`crates/blockifier/src/versioned_constants.rs` line 445 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWMUYO1RYmIQ9qITSf:-Ntu0ANQ01jsbtOOWjxh:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L445)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I meant in the `GasCost` struct doc.
</blockquote></details>

Done

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 420 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1617#-NtWbBa94Dqj9GQqHBQb:-Ntu6m_01SY28LAUoagu:bkjio00) ([raw file](https://github.com/starkware-libs/blockifier/blob/cff7469fe677f1aee2662dd7e9e01b15923f7464/crates/blockifier/src/versioned_constants.rs#L420)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It can be pub

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1617)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
