### PR TITLE
chore: use the fixture block_context in transaction_test

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1790)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1790?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1790** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1790?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1789** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1789?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1790#-:-NvS-jwiB2UShotzfs7r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1375 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1790#-NvS-YDM5vt-ZEcx17IY:-NvS-YDM5vt-ZEcx17IZ:b-ej3gpy) ([raw file](https://github.com/starkware-libs/blockifier/blob/aed914298e36081d793242515a18c07313a4b62b/crates/blockifier/src/transaction/transactions_test.rs#L1375)):*
> ```XML
> #[rstest]
> fn test_fail_deploy_account_undeclared_class_hash(block_context: BlockContext) {
>     let block_context = &block_context;
> ```

are these lines still required?
can you change the fixture to be `block_context: &BlockContext`?
seems redundant

ditto on the other `bc = &bc;` assignments



_Code quote:_
```XML
let block_context = &block_context;
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1375 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1790#-NvS-YDM5vt-ZEcx17IY:-NvS4ArJ6RnCXjNSNahx:b-azvmxl) ([raw file](https://github.com/starkware-libs/blockifier/blob/aed914298e36081d793242515a18c07313a4b62b/crates/blockifier/src/transaction/transactions_test.rs#L1375)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

are these lines still required?
can you change the fixture to be `block_context: &BlockContext`?
seems redundant

ditto on the other `bc = &bc;` assignments
</blockquote></details>

About changing the type of fixture `block_context: BlockContext` to `&BlockContext`, I can try doing it in another PR. 

About the assignments `let bc = &bc`. I tried deleting this assignment on each of the 12 instances. Indeed, not required on one of those 12 instances! On the other 11 times - the `execute` method requires a reference (a `&BlockContext`).

**Review by ArniStarkware — COMMENTED** [review]
> Dismissed @dorimedini-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1790)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1790)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1375 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1790#-NvS-YDM5vt-ZEcx17IY:-NvSAmCe71L4-2HmWAWD:b-iu8dn1) ([raw file](https://github.com/starkware-libs/blockifier/blob/aed914298e36081d793242515a18c07313a4b62b/crates/blockifier/src/transaction/transactions_test.rs#L1375)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

About changing the type of fixture `block_context: BlockContext` to `&BlockContext`, I can try doing it in another PR. 

About the assignments `let bc = &bc`. I tried deleting this assignment on each of the 12 instances. Indeed, not required on one of those 12 instances! On the other 11 times - the `execute` method requires a reference (a `&BlockContext`).
</blockquote></details>

what I'm asking is: doesn't `block_context: &BlockContext` work out of the box without need to edit the fixture?
if not, then ok, keep it like this for now

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1790)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1375 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1790#-NvS-YDM5vt-ZEcx17IY:-NvSBgBk4DGpfDJ-3txT:b-eo1bsc) ([raw file](https://github.com/starkware-libs/blockifier/blob/aed914298e36081d793242515a18c07313a4b62b/crates/blockifier/src/transaction/transactions_test.rs#L1375)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what I'm asking is: doesn't `block_context: &BlockContext` work out of the box without need to edit the fixture?
if not, then ok, keep it like this for now
</blockquote></details>

Does not work:
```
error[E0308]: mismatched types
    --> crates/blockifier/src/transaction/transactions_test.rs:1583:5
     |
1582 | fn test_valid_flag(
     |    --------------- arguments to this function are incorrect
1583 |     block_context: &BlockContext,
     |     ^^^^^^^^^^^^^ expected `&BlockContext`, found `BlockContext`
```

**Comment by ArniStarkware** [comment]
### Merge activity

* **Apr 14, 11:23 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/1790).

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1790)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
