### PR TITLE
refactor(execution): type of additional_data in test_validate_accounts_tx

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1485)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
Prep for #1486.

**Review by MohammadNassar1 — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1485#-:-NqSUUZYA3R4wZn66pCc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1485#-NqSUGev1zBwXrscO0t8:-NqSUGewD9hExGIHhVoB:bu6qrw4) ([raw file](https://github.com/starkware-libs/blockifier/blob/20175077ac0e21a74e966afe859a22ea7898caf5/crates/blockifier/src/transaction/test_utils.rs#L197)):*
> ```XML
>     pub scenario: u64,
>     // Should be None unless scenario is CALL_CONTRACT.
>     pub additional_data: &'a Option<Vec<StarkFelt>>,
> ```

Can you avoid lifetime usage?



_Code quote:_
```XML
pub additional_data: &'a Option<Vec<StarkFelt>>,
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1485)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1485#-NqSUGev1zBwXrscO0t8:-NqT3XsY7Mnxcbh7kCw2:bg4ascv) ([raw file](https://github.com/starkware-libs/blockifier/blob/20175077ac0e21a74e966afe859a22ea7898caf5/crates/blockifier/src/transaction/test_utils.rs#L197)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you avoid lifetime usage?
</blockquote></details>

It's just in a test, so you can be liberal with clones (unless it's for really huge stuff).

Remove the reference and use additional_data.clone() in the test every time you initialize the struct

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/test_utils.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1485#-NqSUGev1zBwXrscO0t8:-NqWb6MN9FLMecj0ICmC:bln0jlc) ([raw file](https://github.com/starkware-libs/blockifier/blob/20175077ac0e21a74e966afe859a22ea7898caf5/crates/blockifier/src/transaction/test_utils.rs#L197)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

It's just in a test, so you can be liberal with clones (unless it's for really huge stuff).

Remove the reference and use additional_data.clone() in the test every time you initialize the struct
</blockquote></details>

It is even simpler than that. Sorry for not going with the simpler design (from r2) in the first place. Done.

The other other option is to `.clone()` `default_args` every time.

**Review by giladchase — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1485)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1, @noaov1, and @TzahiTaub)

**Pull request merged**
