### PR TITLE
chore(fee): update vm resource and l2 resource costs

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1479)

### CODE REVIEW

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1479#-:-NqNqkpw9eM4s_SYRS-7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1479)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/resources/versioned_constants.json` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1479#-NqNsvqd-QRCuiYWbkRr:-NqNsvqd-QRCuiYWbkRs:b-1kewdy) ([raw file](https://github.com/starkware-libs/blockifier/blob/c24b4d54511cb620ee0e25fc7fdbd08cbdf11d6c/crates/blockifier/resources/versioned_constants.json#L11)):*
> ```JSON
>         "milligas_per_code_byte": 875
>     },
>     "invoke_tx_max_n_steps": 3000000,
> ```

Are you sure that @giladchase is on it?



_Code quote:_
```JSON
"invoke_tx_max_n_steps": 3000000,
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1479)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @elintul, and @giladchase)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1479)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @avi-starkware, @elintul, and @giladchase)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1479)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @elintul, and @giladchase)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/resources/versioned_constants.json` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1479#-NqNsvqd-QRCuiYWbkRr:-NqNyFiYC5Q2px69jLkt:botg7hw) ([raw file](https://github.com/starkware-libs/blockifier/blob/c24b4d54511cb620ee0e25fc7fdbd08cbdf11d6c/crates/blockifier/resources/versioned_constants.json#L11)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Are you sure that @giladchase is on it?
</blockquote></details>

I thought I was on top of his PR.

Fixed now.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1479#-:-NqNyiRWAFbhexqk2HIR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Comment by avi-starkware** [comment]
Python PR:
https://reviewable.io/reviews/starkware-industries/starkware/33923#-

**Pull request merged**
