### PR TITLE
fix(concurrency): change version to tx_index

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1739)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1739)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1739#-NuNDuHT4DNJWpA1wJmT:-NuNDuHT4DNJWpA1wJmU:bwiwabk) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2db76aef83b6de48917ce5f2a7d7907c721ef3d/crates/blockifier/src/concurrency.rs#L5)):*
> ```XML
> pub mod versioned_storage;
> 
> type Version = u64;
> ```

I wonder if we want to leave the type definition (change it to `TXIndex`) to have some abstraction (and to allow easier changes). 



_Code quote:_
```XML
type Version = u64;
```

**Review by noaov1 — COMMENTED** [review]
I wonder if it's confusing to have a versioned state with version == transaction index.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1739#-:-NuNZ5hmEanRd7ZPhNHa:bpvj3x1)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1739#-NuNDuHT4DNJWpA1wJmT:-NuN_yRPBYrF2nyvomEA:b-n352l9) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2db76aef83b6de48917ce5f2a7d7907c721ef3d/crates/blockifier/src/concurrency.rs#L5)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if we want to leave the type definition (change it to `TXIndex`) to have some abstraction (and to allow easier changes).
</blockquote></details>

Consider name it `TxChunkIdx` (as it is the index in the chunk, and not in the block)
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1739#-NuNWKAFEVBIzWernFai:-NuNWKAG4D2UGNQwDJE3:b6ezovm) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc7fb0d1879cbd1b7dd5a63a7c8c6c8473f494d5/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
> ```XML
>     pub fn validate_read_set(&mut self, tx_index: usize, state_cache: &mut StateCache) -> bool {
>         // If the tx_index is 0, then the read set is valid. Since tx_index 0 has no predecessors,
>         // there's nothing to compare it to.
> ```

I prefer avoiding variable names in documentation.



_Suggestion:_
```XML
        // If it is the first transaction in the chunk, then the read set is valid. Since it has no predecessors,
        // there's nothing to compare it to.
```
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1739#-NuNX6Ty2XM02SwPDz3d:-NuNX6Tz-2OL58l0j7di:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc7fb0d1879cbd1b7dd5a63a7c8c6c8473f494d5/crates/blockifier/src/concurrency/versioned_storage_test.rs#L28)):*
> ```XML
>     storage.write(2, 10, 78);
>     assert_eq!(storage.read(1, 10).unwrap(), 31);
>     // Ignore the value written by the current tx_index.
> ```





_Suggestion:_
```XML
// Ignore the value written by the current transaction.
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1739)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1739#-NuNWKAFEVBIzWernFai:-NuNk2B38k4Q6sGzv8NY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc7fb0d1879cbd1b7dd5a63a7c8c6c8473f494d5/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I prefer avoiding variable names in documentation.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1739#-NuNX6Ty2XM02SwPDz3d:-NuNjn5_8mndyws2kAFG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc7fb0d1879cbd1b7dd5a63a7c8c6c8473f494d5/crates/blockifier/src/concurrency/versioned_storage_test.rs#L28)):*
> ```XML
>     storage.write(2, 10, 78);
>     assert_eq!(storage.read(1, 10).unwrap(), 31);
>     // Ignore the value written by the current tx_index.
> ```

Done.

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1739#-NuNDuHT4DNJWpA1wJmT:-NuO91O20ocEzCiiMVrh:biipcpr) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2db76aef83b6de48917ce5f2a7d7907c721ef3d/crates/blockifier/src/concurrency.rs#L5)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider name it `TxChunkIdx` (as it is the index in the chunk, and not in the block)
</blockquote></details>

After an offline discussion, we decided to continue as is (w/o `type`) and to consider it again later.
For future discussion:
1. w/o `type`: keep it simple, `usize` tells the "tx_index" story, and the chunk context is given wherever it's used (at his point of time).
2. with `type`: more abstract for future use.

resolving for now.

**Comment by barak-b-starkware** [comment]
I agree, it's confusing. When I asked myself this question, I wondered what are the alternatives and decided that the alternatives were worse.
Moreover, it makes sense to do that for future use.
WDYT?

**Review by noaov1 — COMMENTED** [review]
> it makes sense to do that for future use.

Can you please elaborate?

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1739#-:-NuSced77_r34A34vW-F:bhf6ltq)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

___
*[`crates/blockifier/src/concurrency.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1739#-NuNDuHT4DNJWpA1wJmT:-NuSbASKCFVuoP3FgvdL:by8w8em) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2db76aef83b6de48917ce5f2a7d7907c721ef3d/crates/blockifier/src/concurrency.rs#L5)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

After an offline discussion, we decided to continue as is (w/o `type`) and to consider it again later.
For future discussion:
1. w/o `type`: keep it simple, `usize` tells the "tx_index" story, and the chunk context is given wherever it's used (at his point of time).
2. with `type`: more abstract for future use.

resolving for now.
</blockquote></details>

I thought about it more and I tend now to prefer the `type`. 
Reasons:
1. It makes the code more readable, and distinguishes between variables with different meaning but with the same primitive type.
2. Makes it easier to replace the primitive type.

WDYT?
RE the name: we can change it to `TxIndex`.

**Review by noaov1 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1739)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
