### PR TITLE
Return `actual_fee` from native validation API

### PR DESCRIPTION
**Pull request by giladchase**
This should have been added before, since Python needs blockifier to
calculate the actual fee in order to validate that there is sufficient
fee for the validation call.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/993)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/993)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/993#-NgxiOg7C0Wh91X8I0WS:-NgxiOg7C0Wh91X8I0WT:ba1jiub) (no related file):*
wait
since when do we check balance covers validation cost...?
in the blockifier we check:
1. balance covers max fee
2. balance covers "minimal estimated tx cost"

Check (2) should be enough for validate, no? Plus, we can't revert if we're out of resources in validate, right?

___
___
*[`crates/native_blockifier/src/py_validator.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/993#-NgxiiZo4ubQGkkrQPvs:-NgxiiZo4ubQGkkrQPvt:b9tw7u1) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd94b4707a1f0ca92e9f6ca692e6214fa7710e40/crates/native_blockifier/src/py_validator.rs#L87)):*
> ```XML
>             self.tx_executor().validate(tx, remaining_gas, raw_contract_class)?;
>         let py_maybe_call_info = maybe_call_info.map(PyCallInfo::from);
>         Ok((py_maybe_call_info, actual_fee.0))
> ```

breaking change, you have a python-side PR to paste here?



_Code quote:_
```XML
 Ok((py_maybe_call_info, actual_fee.0))
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/993#-NgxiuxM1Cn0O0leCWXr:-NgxiuxM1Cn0O0leCWXs:b-rnzqvu) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd94b4707a1f0ca92e9f6ca692e6214fa7710e40/crates/native_blockifier/src/transaction_executor.rs#L121)):*
> ```XML
>         let ActualCostMetrics { actual_fee, .. } = account_tx
>             .into_cost_metrics_builder(&self.block_context)
>             .try_add_state_changes(&mut self.state)?
> ```

don't you need to add the validate callinfo here?



_Code quote:_
```XML
            .into_cost_metrics_builder(&self.block_context)
            .try_add_state_changes(&mut self.state)?
```

**Review by giladchase — COMMENTED** [review]
Python side: https://reviewable.io/reviews/starkware-industries/starkware/31652#-

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/993#-:-NgxvHFY1MmNRGqvSvHO:b4c0sxi)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_validator.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/993#-NgxiiZo4ubQGkkrQPvs:-NgxvIMg7abuP1SN1Lq5:b-1rcp6j) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd94b4707a1f0ca92e9f6ca692e6214fa7710e40/crates/native_blockifier/src/py_validator.rs#L87)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

breaking change, you have a python-side PR to paste here?
</blockquote></details>

Whoops forgot. It's the same validation PR we have (added it to the description here).
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/993#-NgxiuxM1Cn0O0leCWXr:-NgxvVPD9qELtpy3LL4Y:b4slh2i) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd94b4707a1f0ca92e9f6ca692e6214fa7710e40/crates/native_blockifier/src/transaction_executor.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't you need to add the validate callinfo here?
</blockquote></details>

YES!
Thanks.
fixed.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/993)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yoni-Starkware)

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/993#-:-Ngy0qf0D3XHjGNF4dRk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request closed without merging**
