### PR TITLE
Add a `new()` method to `DeclareTransaction` struct 

### PR DESCRIPTION
**Pull request by noaov1**
to enforce compatibility between declare version and the cairo version.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/468)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/468)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/468#-NVU8Qpp7QGLDqcUpDPs:-NVU8Qpp7QGLDqcUpDPt:bl5uf4v) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ff699dc2a3c9a2356923f45bcb3e70c5cbf5fe/crates/blockifier/src/transaction/transactions.rs#L74)):*
> ```XML
>     contract_class: ContractClass,
> }
> ```

Perhaps a `DeclareTransaction` enum is simpler?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/468)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/468#-NVU8Qpp7QGLDqcUpDPs:-NVUkw3d1BvD2L4CdGcC:b-18era4) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ff699dc2a3c9a2356923f45bcb3e70c5cbf5fe/crates/blockifier/src/transaction/transactions.rs#L74)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps a `DeclareTransaction` enum is simpler?
</blockquote></details>

Using the `DeclareTransaction` enum creates more complicated code: it leads to a chain of enums (not so critical) + it adds a `match` every time we want to access an internal field + it adds the need to wrap the `contract_class` (with the `ClassClass` enum ). On the other hand, the main advantage of it (thanks @alonh5 for pointing this out) is that we will know the mismatch at compile time.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/468)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/468#-NVZ3nSC967DYMSnOSl5:-NVZ8tAdAL3--fjycN5g:b28d70j) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ff699dc2a3c9a2356923f45bcb3e70c5cbf5fe/crates/blockifier/src/transaction/transaction_execution.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where is this method used?
</blockquote></details>

This was added by Gilad for the performance evaluation task.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/468#-NVZ4M6CAcy5OGBJs9pI:-NVZE96KAmnSHEDa-sYI:br6eph4) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ff699dc2a3c9a2356923f45bcb3e70c5cbf5fe/crates/blockifier/src/transaction/transactions.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we consolidate `V0V1` case? I thought we had this `Declare` transaction in SN API.
</blockquote></details>

We have an enum `DeclareTransaction` in SN API, but it distinguishes between `V0` and ` V1`.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/468#-NVZ4WgN1XUD_MDMNCGu:-NVZFdIM38B9maMHwxUU:b-81la7d) ([raw file](https://github.com/starkware-libs/blockifier/blob/76ff699dc2a3c9a2356923f45bcb3e70c5cbf5fe/crates/blockifier/src/transaction/transactions.rs#L125)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is an `Arc`, right?
</blockquote></details>

Right

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/468)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/468#-:-NW1JtSaEAXya6rc4PsQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by elintul — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
