### PR TITLE
Update `os_resources` file

### PR DESCRIPTION
**Pull request by noaov1**
- Following the PR: Add keccak syscall support. [#29729](https://github.com/starkware-industries/starkware/pull/29729)
- According to [os_resources.json](https://github.com/starkware-industries/starkware/blob/31d1934aa8ed96c5f10486829d0c58c1d445c4c7/src/starkware/starknet/business_logic/execution/os_resources.json#L1)

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/543)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/543)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/543#-NWVyZLa0CxvpbIAcBdc:-NWVyZLbDBvexamyefIV:bflyb8x) (no related file):*
Please check in what `0.11.*` version this change was made and consult with Alon on how to update his validation branch. This is going to fail our transaction traces checks. 

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/543)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/543)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/543#-NWVyZLa0CxvpbIAcBdc:-NWW18xP3-OlHaAkLO48:bp9c1xw) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please check in what `0.11.*` version this change was made and consult with Alon on how to update his validation branch. This is going to fail our transaction traces checks. 
</blockquote></details>

It changed only in `0.12.0`. 

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/543)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/543#-NWVyZLa0CxvpbIAcBdc:-NWW5yiU1EnbK-j_hQC7:b832mqa) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It changed only in `0.12.0`. 
</blockquote></details>

Then please let him know.
After he rebases over `main-v0.12.0`, he should not take this commit.

___

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/543)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/543#-NWVyZLa0CxvpbIAcBdc:-NWWBq-4DKSyTEtWAVoC:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Then please let him know.
After he rebases over `main-v0.12.0`, he should not take this commit.
</blockquote></details>

Done.

___

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/543#-:-NWWO_or75BjBd5zKMr0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
