### PR TITLE
Refactor, no business logic changes

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1098)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1098)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZLgd3r1g4_JftfkQ:-NiiZLgd3r1g4_JftfkR:b-831pr5) (no related file):*
Perhaps rename `actual_cost.rs` to `post_execution.rs`?

___
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiYmIO8p21dF_p0yLj:-NiiYmIPCUc82R6EsJf8:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L8)):*
> ```XML
> use thiserror::Error;
> 
> use super::fee_utils::{calculate_tx_l1_gas_usage, get_fee_by_l1_gas_usage};
> ```





_Suggestion:_
```XML
crate::...
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZ1y04BdcQSevds42:-NiiZ1y04BdcQSevds43:b-suv37h) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L24)):*
> ```XML
> #[derive(Clone, Debug, Error)]
> pub enum PostExecutionFeeError {
>     #[error("Insufficient max L1 gas: max amount: {max_amount}, actual used: {actual_amount}.")]
> ```

Alphabetize?
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZ7zL9wFGQ_poM_Qn:-NiiZ7zM731yeyCKb2F9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L187)):*
> ```XML
> 
> impl PostExecutionReport {
>     /// Utility to check the actual cost can be paid by the account. If not, returns an error.
> ```





_Suggestion:_
```XML
// Verifies the actual cost can be paid by the account. If not, returns an error that 
// triggers revert flow.
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZEHc3gm_EwK91zSe:-NiiZEHc3gm_EwK91zSf:b-ouy0wv) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L200)):*
> ```XML
>         }
> 
>         let ActualCost { actual_fee: post_execute_fee, actual_resources: post_execute_resources } =
> ```

Why not keep `actual_`?



_Code quote:_
```XML
post_execute_
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZIX-DSYyMVuJ1Xyf:-NiiZIX-DSYyMVuJ1Xyg:b-p9um0p) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L244)):*
> ```XML
>         // Initial check passed; verify against the account balance, which may have changed after
>         // execution.
>         let (balance_low, balance_high, can_pay) = get_balance_and_if_covers_fee(
> ```

Consider returning an `Err` if can't pay; balance o/w (can be done in a separate PR).



_Code quote:_
```XML
get_balance_and_if_covers_fee
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1098)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZLgd3r1g4_JftfkQ:-NiifsqZ5IU484cyNzvI:bqrgrv4) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps rename `actual_cost.rs` to `post_execution.rs`?
</blockquote></details>

I'll split modules; `actual_cost.rs` contains the cost builder

___
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZ7zL9wFGQ_poM_Qn:-NiifE8D2ugII79d5wlP:bs2q1x5) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L187)):*
> ```XML
> 
> impl PostExecutionReport {
>     /// Utility to check the actual cost can be paid by the account. If not, returns an error.
> ```

Done, kinda. The return value is never an error: always an instance of `Self` (unless we got a state reader error or something). Also, not always triggering revert flow - post-execution is done in non-revertible txs as well
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZIX-DSYyMVuJ1Xyf:-NiiffYlARNZHCboQgDW:b-7y9ge3) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L244)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider returning an `Err` if can't pay; balance o/w (can be done in a separate PR).
</blockquote></details>

WDYM?
I return an error in the report; I think it's better this way. The non-revertible flow unpacks this error and returns it (if it exists).

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1098)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 190 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-Nj1dCvo2BKR5zYD5i2s:-Nj1dCvo2BKR5zYD5i2t:bed0vjj) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6dc69e8e7c05a60e7320fb293dc4fbdd773150e/crates/blockifier/src/fee/actual_cost.rs#L190)):*
> ```XML
>     ) -> TransactionExecutionResult<Self> {
>         let passing_report = Self { recommended_fee: cost_to_audit.actual_fee, error: None };
>         if !charge_fee || !account_tx_context.enforce_fee()? {
> ```

result of rebase



_Code quote:_
```XML
 || !account_tx_context.enforce_fee()?
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 201 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-Nj1d8MUD2nIGSbemaRN:-Nj1d8MUD2nIGSbemaRO:bed0vjj) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6dc69e8e7c05a60e7320fb293dc4fbdd773150e/crates/blockifier/src/fee/actual_cost.rs#L201)):*
> ```XML
>             AccountTransactionContext::Current(context) => {
>                 // Check L1 gas limit.
>                 let max_l1_gas = context.l1_resource_bounds()?.max_amount as u128;
> ```

result of rebase



_Code quote:_
```XML
?
```

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1098)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiaXzOAO1YNX4E9qWq:-NiiaXzOAO1YNX4E9qWr:b-z5fl3t) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L188)):*
> ```XML
> impl PostExecutionReport {
>     /// Utility to check the actual cost can be paid by the account. If not, returns an error.
>     pub fn generate<S: StateReader>(
> ```

`new`/`create`?



_Code quote:_
```XML
generate
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 195 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiagPz2QuZAYqpTCS8:-NiiagPz2QuZAYqpTCS9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L195)):*
> ```XML
>         charge_fee: bool,
>     ) -> TransactionExecutionResult<Self> {
>         let passing_report = Self { recommended_fee: cost_to_audit.actual_fee, error: None };
> ```





_Suggestion:_
```XML
fee_report
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZIX-DSYyMVuJ1Xyf:-Nj1q8AHEW4uayaw46LF:b-qh2s43) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L244)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM?
I return an error in the report; I think it's better this way. The non-revertible flow unpacks this error and returns it (if it exists).
</blockquote></details>

It's weird IMO, you always use only one of the results; exactly the flow of positive/negative.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 261 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-Niif4kSDdJnenDWYXnt:-Niif4kTEpG0RVrICspC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L261)):*
> ```XML
>                 }),
>             })
>         }
> ```





_Suggestion:_
```XML
        if can_pay {
            return Ok(passing_report)
        }
            
        Ok(Self {
            recommended_fee: *post_execute_fee,
            error: Some(PostExecutionFeeError::InsufficientFeeTokenBalance {
                fee: *post_execute_fee,
                balance_low,
                balance_high,
            }),
        })
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1098)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 195 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiagPz2QuZAYqpTCS8:-Nj1ufCe1O-4b5BqFWV6:bc3k1mh) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L195)):*
> ```XML
>         charge_fee: bool,
>     ) -> TransactionExecutionResult<Self> {
>         let passing_report = Self { recommended_fee: cost_to_audit.actual_fee, error: None };
> ```

Why is this a better name?
I want the name to indicate "this is a GREEN post-execution report", i.e. no issues
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZIX-DSYyMVuJ1Xyf:-Nj1u4gu6divnxSAKtFH:b-hlwji7) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L244)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's weird IMO, you always use only one of the results; exactly the flow of positive/negative.
</blockquote></details>

Not following. Usages:
1. Non-revertible:
    (a) if no error, accept
    (b) if error in post-execution, return the error
2. Revertible:
    (a) if no error, accept
    (b) if error during execution, use recommended fee and execution error text as revert error.
    (c) if error in post-execution, use recommended fee and post-execution fee error as revert error.

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1098)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 195 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiagPz2QuZAYqpTCS8:-Nj2twGF-CazFondkWqA:b-4hvi0m) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L195)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Why is this a better name?
I want the name to indicate "this is a GREEN post-execution report", i.e. no issues
</blockquote></details>

Got it.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-NiiZIX-DSYyMVuJ1Xyf:-Nj2trrr7GwVuNw2udGb:bggxk6q) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a9a2142e7a9b0f2cd88cec08d2be77df4cb87b9/crates/blockifier/src/fee/actual_cost.rs#L244)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Not following. Usages:
1. Non-revertible:
    (a) if no error, accept
    (b) if error in post-execution, return the error
2. Revertible:
    (a) if no error, accept
    (b) if error during execution, use recommended fee and execution error text as revert error.
    (c) if error in post-execution, use recommended fee and post-execution fee error as revert error.
</blockquote></details>

Let's take this offline.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1098#-:-Nj2u-Ls0XGTwXGriuur:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
