### PR TITLE
refactor: add selector into selected TransactionExecutionError variants

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1673)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1673)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/execution/errors.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1673#-NtAuXiz32kbRgqSQZCr:-NtAuXiz32kbRgqSQZCs:b-lagx3m) ([raw file](https://github.com/starkware-libs/blockifier/blob/adee3ef8a7ac0260cae5ac783af66f23cda81c72/crates/blockifier/src/execution/errors.rs#L127)):*
> ```XML
>             error,
>             storage_address,
>         } => {
> ```

why is this no longer matched? previously we would see a stack trace (with no ctor entry point selector), but now it's stringified, right?



_Code quote:_
```XML
        | TransactionExecutionError::ContractConstructorExecutionFailed {
            error,
            storage_address,
        } => {
```

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1673)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/errors.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1673#-NtAuXiz32kbRgqSQZCr:-NtBNxSO1PZWLZEWkRS5:beibwif) ([raw file](https://github.com/starkware-libs/blockifier/blob/adee3ef8a7ac0260cae5ac783af66f23cda81c72/crates/blockifier/src/execution/errors.rs#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this no longer matched? previously we would see a stack trace (with no ctor entry point selector), but now it's stringified, right?
</blockquote></details>

It was never really matched. Still the only thing that is really matched is `TransactionExecutionError::ExecutionError` (since `gen_transaction_execution_error_trace` is only ever called on that variant currently)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1673)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/execution/errors.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1673#-NtAuXiz32kbRgqSQZCr:-NtBYBQS3dbQi0OIXgYw:b-kuaa85) ([raw file](https://github.com/starkware-libs/blockifier/blob/adee3ef8a7ac0260cae5ac783af66f23cda81c72/crates/blockifier/src/execution/errors.rs#L127)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

It was never really matched. Still the only thing that is really matched is `TransactionExecutionError::ExecutionError` (since `gen_transaction_execution_error_trace` is only ever called on that variant currently)
</blockquote></details>

yes but we plan on connecting the ctor and the validate errors eventually; why drop the match here?

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/execution/errors.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1673#-NtAuXiz32kbRgqSQZCr:-NtBaa_BEwqZOOaAR4D0:b-przfnb) ([raw file](https://github.com/starkware-libs/blockifier/blob/adee3ef8a7ac0260cae5ac783af66f23cda81c72/crates/blockifier/src/execution/errors.rs#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes but we plan on connecting the ctor and the validate errors eventually; why drop the match here?
</blockquote></details>

because I want to add the selector in the PR I'm building on top of this and I can't easily pry it out of the c'tor at the moment. it can easily be added back later.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1673)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/execution/errors.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1673#-NtAuXiz32kbRgqSQZCr:-NtBbvkb-RSYkLEJ5ImN:b-jkvvdl) ([raw file](https://github.com/starkware-libs/blockifier/blob/adee3ef8a7ac0260cae5ac783af66f23cda81c72/crates/blockifier/src/execution/errors.rs#L127)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

because I want to add the selector in the PR I'm building on top of this and I can't easily pry it out of the c'tor at the moment. it can easily be added back later.
</blockquote></details>

ok, I'll unblock when I see a PR that adds it (or put a TODO here to add it back, also works)

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/execution/errors.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1673#-NtAuXiz32kbRgqSQZCr:-NtBgcdtDr1GDcd60iW4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/adee3ef8a7ac0260cae5ac783af66f23cda81c72/crates/blockifier/src/execution/errors.rs#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, I'll unblock when I see a PR that adds it (or put a TODO here to add it back, also works)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1673#-:-NtBjIh5Ct7dw7aJwfK1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
