### PR TITLE
Export account transaction fields - add support in blockifier repo

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/789)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 6 of 13 files at r5, 2 of 4 files at r7, 4 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/789)* status: 14 of 18 files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 152 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nafwkpb2tNITXjIZT9N:-Nafwkpb2tNITXjIZT9O:b-lxohkh) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/account_transaction.rs#L152)):*
> ```XML
>                 nonce: tx.tx.nonce(),
>                 sender_address: tx.contract_address,
>             },
> ```

Can you please use `let sn_api_tx = &tx.tx();` as done in Decalre and invoke (and avoid `tx.tx`)



_Code quote:_
```XML
            Self::DeployAccount(tx) => AccountTransactionContext {
                transaction_hash: tx.tx_hash,
                max_fee: tx.tx.max_fee(),
                version: tx.version(),
                signature: tx.tx.signature(),
                nonce: tx.tx.nonce(),
                sender_address: tx.contract_address,
            },
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 172 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nafx0oZ2hVhd2_GMDN0:-Nafx0oZ2hVhd2_GMDN1:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/account_transaction.rs#L172)):*
> ```XML
>                             TransactionVersion(StarkFelt::from(1_u8))
>                         }
>                     },
> ```





_Suggestion:_
```XML
                    version: sn_api_tx.version()
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 179 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-NafxQR_-27UmrR2YO6B:-NafxQR_-27UmrR2YO6C:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/account_transaction.rs#L179)):*
> ```XML
>                         starknet_api::transaction::InvokeTransaction::V1(tx_v1) => {
>                             tx_v1.sender_address
>                         }
> ```





_Suggestion:_
```XML
                    sender_address: sn_api_tx.sender_address()
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 37 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nafy-g45FtgM4wDlr34:-Nafy-g45FtgM4wDlr35:bhjqkge) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/objects.rs#L37)):*
> ```XML
>     pub fn signature(&self) -> TransactionSignature {
>         self.signature.clone()
>     }
> ```

Why is it needed?



_Code quote:_
```XML
    pub fn max_fee(&self) -> Fee {
        self.max_fee
    }
    pub fn nonce(&self) -> Nonce {
        self.nonce
    }
    pub fn signature(&self) -> TransactionSignature {
        self.signature.clone()
    }
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nafyy2qE54C9BkuRXGj:-Nafyy2qE54C9BkuRXGk:bgylh3b) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/transactions.rs#L214)):*
> ```XML
> 
> impl DeployAccountTransaction {
>     implement_inner_tx_getters!(
> ```

No?
And You should leave those fields.



_Suggestion:_
```XML
implement_inner_tx_getter_calls!(
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/789)* status: 7 of 18 files reviewed, 5 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 152 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nafwkpb2tNITXjIZT9N:-Nagh6qAB00_R9opej4c:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/account_transaction.rs#L152)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please use `let sn_api_tx = &tx.tx();` as done in Decalre and invoke (and avoid `tx.tx`)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 172 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nafx0oZ2hVhd2_GMDN0:-Naghd9EDG6rwNE6810a:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/account_transaction.rs#L172)):*
> ```XML
>                             TransactionVersion(StarkFelt::from(1_u8))
>                         }
>                     },
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 179 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-NafxQR_-27UmrR2YO6B:-NaghlKKE2Z8FI76r7Nh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/account_transaction.rs#L179)):*
> ```XML
>                         starknet_api::transaction::InvokeTransaction::V1(tx_v1) => {
>                             tx_v1.sender_address
>                         }
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nafyy2qE54C9BkuRXGj:-NagkiZl5xBp1VHHmF10:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/transactions.rs#L214)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No?
And You should leave those fields.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 37 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nafy-g45FtgM4wDlr34:-Nagi7PW5-NhUwXZzv-R:bzhn3cb) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/objects.rs#L37)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

We don't need it :) 
It was needed when we had accout_params in this structure.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 13 files at r5, 1 of 4 files at r7, 1 of 5 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/789)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 166 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/789#-NakfOQ9EQr01Hqy15Ym:-NakfOQ9EQr01Hqy15Yn:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf161698871c0f9a82197b0cbe18f93a9ccacb9a/crates/blockifier/src/transaction/account_transaction.rs#L166)):*
> ```XML
>                         starknet_api::transaction::InvokeTransaction::V1(tx_v1) => {
>                             tx_v1.account_params.nonce()
>                         }
> ```





_Suggestion:_
```XML
                    nonce: sn_api_tx.nonce().unwrap_or_default()
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nafyy2qE54C9BkuRXGj:-Nakfk-CCUZ8nYQTjQQv:bl1rstu) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/transactions.rs#L214)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why did you delete the `max_fee`, `nonce` and `signature` fields?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 503 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nakg2pkBS7yPQDtSbqY:-Nakg2pkBS7yPQDtSbqZ:bttu9a) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf161698871c0f9a82197b0cbe18f93a9ccacb9a/crates/blockifier/src/transaction/transactions_test.rs#L503)):*
> ```XML
>             account_params: AccountParams {
>                 max_fee: invalid_max_fee,
>                 ..declare_tx(TEST_EMPTY_CONTRACT_CLASS_HASH, TEST_ACCOUNT_CONTRACT_ADDRESS, None)
> ```

Can you please store it in a variable? You use it twice



_Code quote:_
```XML
declare_tx(TEST_EMPTY_CONTRACT_CLASS_HASH, TEST_ACCOUNT_CONTRACT_ADDRESS, None)
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/789)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 166 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/789#-NakfOQ9EQr01Hqy15Ym:-NalV3OaBPH7TdxhXfY-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf161698871c0f9a82197b0cbe18f93a9ccacb9a/crates/blockifier/src/transaction/account_transaction.rs#L166)):*
> ```XML
>                         starknet_api::transaction::InvokeTransaction::V1(tx_v1) => {
>                             tx_v1.account_params.nonce()
>                         }
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nafyy2qE54C9BkuRXGj:-NalXv1748JWquXDVd7G:b-2ba5e3) ([raw file](https://github.com/starkware-libs/blockifier/blob/dffa348da41cfa93b550fb75f2fa251d32d62198/crates/blockifier/src/transaction/transactions.rs#L214)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you delete the `max_fee`, `nonce` and `signature` fields?
</blockquote></details>

Since DeployAccount doesn't have 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 503 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/789#-Nakg2pkBS7yPQDtSbqY:-Nalc4rv07PIGWQwc3R7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf161698871c0f9a82197b0cbe18f93a9ccacb9a/crates/blockifier/src/transaction/transactions_test.rs#L503)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please store it in a variable? You use it twice
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 7 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/789)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/789#-NapceHW7mf80kvQF0-K:-NapceHW7mf80kvQF0-L:b483wyg) ([raw file](https://github.com/starkware-libs/blockifier/blob/8173224b375c151e0b6a0435ed5a4ff84f4381ba/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
> ```XML
>         match self {
>             Self::Declare(tx) => {
>                 let sn_api_tx = &tx.tx();
> ```

Why is it needed now?



_Code quote:_
```XML
 let sn_api_tx = &tx.tx();
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/789)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/789#-NapceHW7mf80kvQF0-K:-NavoDSCDU80hfUW_F20:b-bw2wff) ([raw file](https://github.com/starkware-libs/blockifier/blob/8173224b375c151e0b6a0435ed5a4ff84f4381ba/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It was used for version, and sender_address.
I have added new getters, and removed the sn_api_tx.
</blockquote></details>

Relevant also for `Invoke` :)

**Comment by MohammadNassar1** [comment]
The changes made to AccountParams and V3 transactions were reverted,

**Pull request closed without merging**
