### PR TITLE
Refactor initial_test_state

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1283)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1283)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ArniStarkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1283#-Nlya81I6AOdzBsuyFED:-Nlya81I6AOdzBsuyFEE:b-as4pc4) (no related file):*
1. Remove the minter logic (only one minter allowed, so this was a bug, and no tests require minting privilege).
2. Remove deployment of cairo0 account as a default.

___

**Comment by ArniStarkware** [comment]
This PR may be seen as prep for #1277.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1283)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1283#-Nm0HDkI-vf42JvTkcV4:-Nm0HDkI-vf42JvTkcV5:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fe1064db8cc7aa664ab70614882bb5acf6b5f97/crates/blockifier/src/test_utils/initial_test_state.rs#L16)):*
> ```XML
> use crate::transaction::objects::FeeType;
> 
> /// Utility to set an account as minter in both fee tokens, and fund it.
> ```





_Suggestion:_
```XML
/// Utility to fund accounts.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1283)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1283#-Nm0Gtfd4jP8IzJlaZ1I:-Nm0HljEB115qvY27onb:b2nign6) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This PR may be seen as prep for #1277.
</blockquote></details>

yes

___
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1283#-Nm0HDkI-vf42JvTkcV4:-Nm0HghmCNNP8zyJJmqK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fe1064db8cc7aa664ab70614882bb5acf6b5f97/crates/blockifier/src/test_utils/initial_test_state.rs#L16)):*
> ```XML
> use crate::transaction::objects::FeeType;
> 
> /// Utility to set an account as minter in both fee tokens, and fund it.
> ```

Done.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1283)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1283#-Nm0HDkI-vf42JvTkcV4:-Nm0Ithd-21-XPFXf4HY:b-vr4p06) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fe1064db8cc7aa664ab70614882bb5acf6b5f97/crates/blockifier/src/test_utils/initial_test_state.rs#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1283)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1283#-Nm0HDkI-vf42JvTkcV4:-Nm0KGhY4lW82Ot9K0qW:bd1q06e) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fe1064db8cc7aa664ab70614882bb5acf6b5f97/crates/blockifier/src/test_utils/initial_test_state.rs#L16)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I don't see it.
</blockquote></details>

Done. (whoops)

**Review by ArniStarkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1283#-:-Nm0KSzl7c-6WqAFkbtL:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1283)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1283)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @noaov1)

**Pull request merged**
