### PR TITLE
Update the ACCOUNT_CONTRACT_PATH name to CAIRO0_ACCOUNT_CONTRACT_PATH

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/711)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/711)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/711#-NZ_CEut5F7bW5gydeBD:-NZ_CEut5F7bW5gydeBE:b4vojgw) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1f5971cfd3bec1f3df3228fc9c1529f659095e4/crates/blockifier/src/test_utils.rs#L61)):*
> ```XML
> 
> // Paths.
> pub const CAIRO0_ACCOUNT_CONTRACT_PATH: &str =
> ```

Can you please add the prefix/suffix (decide on a convention) to all the path constants?



_Code quote:_
```XML
pub const CAIRO0_ACCOUNT_CONTRACT_PATH
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/711)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/711#-NZ_CEut5F7bW5gydeBD:-NZ_HN2n7WwkZzNMXa8g:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1f5971cfd3bec1f3df3228fc9c1529f659095e4/crates/blockifier/src/test_utils.rs#L61)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please add the prefix/suffix (decide on a convention) to all the path constants?
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/711#-:-NZ_HqlL0T9JTOres-Tx:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @MohammadNassar1)

**Review by noaov1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/711)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
