### PR TITLE
Break up test_utils.rs: extract `DictStateReader`

### PR DESCRIPTION
**Pull request by giladchase**
and `CachedState` constructors

commit-id:dc18fb72

---

**Stack**:
- #1179
- #1178
- #1177
- #1176
- #1175 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1175)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/test_utils/dict_state_reader.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1175#-NjwYM667Kgfv3zV86-y:-NjwYM67CqarT7Q256U2:b-16kjwl) ([raw file](https://github.com/starkware-libs/blockifier/blob/f25607815a4690ffd078c20a82ee8116dd327eeb/crates/blockifier/src/test_utils/dict_state_reader.rs#L79)):*
> ```XML
> }
> 
> pub fn deprecated_create_test_state() -> CachedState<DictStateReader> {
> ```

why are the state creation utilities in the same module as the DictStateReader? does that make sense?



_Code quote:_
```XML
deprecated_create_test_state
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1175)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1175#-NjwYY80ClpfbcuRgbQx:-NjwYY80ClpfbcuRgbQy:b-6rg7h9) (no related file):*
Are we okay with having many test utils in a file called `dict_state_reader.rs`?

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1175)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1175#-NjwYY80ClpfbcuRgbQx:-NjwYt9Q-asQqEG_Qg9x:b-ofqevw) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are we okay with having many test utils in a file called `dict_state_reader.rs`?
</blockquote></details>

same question lol

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1175)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1175#-NjwYY80ClpfbcuRgbQx:-Njwbmmw2hVOh2Ni7NM2:b6uk3en) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same question lol
</blockquote></details>

Mmm i basically moved all of the DictStateReader-related funcs into the test_utils/dict_state_reader module, but i get why that might not be the best spot.

I was thinking that if test-utils has submodules now, then methods that are left inside test_utils.rs should either be usefull to all submodules or that don't fit into an existing submodule and are too small to create a new one for.

Should I move them back?

___
___
*[`crates/blockifier/src/test_utils/dict_state_reader.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1175#-NjwYM667Kgfv3zV86-y:-NjwbnMh1xakQdeDf8qz:b-wfxxxd) ([raw file](https://github.com/starkware-libs/blockifier/blob/f25607815a4690ffd078c20a82ee8116dd327eeb/crates/blockifier/src/test_utils/dict_state_reader.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why are the state creation utilities in the same module as the DictStateReader? does that make sense?
</blockquote></details>

Answered above

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1175)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1175#-NjwYY80ClpfbcuRgbQx:-NjwcHRW7vs7Pm2EJr8g:bdhknns) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Mmm i basically moved all of the DictStateReader-related funcs into the test_utils/dict_state_reader module, but i get why that might not be the best spot.

I was thinking that if test-utils has submodules now, then methods that are left inside test_utils.rs should either be usefull to all submodules or that don't fit into an existing submodule and are too small to create a new one for.

Should I move them back?
</blockquote></details>

I think they need their own module

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1175)* status: 3 of 16 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1175#-NjwYY80ClpfbcuRgbQx:-NkFOHKSC7UjieLbnMok:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think they need their own module
</blockquote></details>

Done.

___

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 12 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1175#-:-NkF_u3-3yt9QyQDn1K3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
