### PR TITLE
Implement the  syscall.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/deprecated_syscalls.rs` line 448 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUMXSKGD5MJilPddA8i:-NUMXSKH4eJSbMl55yQE:b96ir25) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3f319c216176583f4ab2768c39656617a32afa7/crates/blockifier/src/execution/deprecated_syscalls.rs#L448)):*
> ```XML
> }
> 
> // ReplaceClass syscall.
> ```

Move after `LibraryCallL1Handler`?



_Code quote:_
```XML
// ReplaceClass syscall.
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls.rs` line 473 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUMXhVhCXdaBAnEYfNh:-NUMXhVhCXdaBAnEYfNi:b24clp5) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3f319c216176583f4ab2768c39656617a32afa7/crates/blockifier/src/execution/deprecated_syscalls.rs#L473)):*
> ```XML
> ) -> DeprecatedSyscallResult<ReplaceClassResponse> {
>     // Ensure the class is declared (by reading it).
>     let _contract_class = syscall_handler.state.get_contract_class(&request.class_hash)?;
> ```

Can we avoid this?



_Code quote:_
```XML
let _contract_class = 
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/deprecated_syscalls.rs` line 448 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUMXSKGD5MJilPddA8i:-NUMZqzX8AXoXVBS7AMI:bfst039) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3f319c216176583f4ab2768c39656617a32afa7/crates/blockifier/src/execution/deprecated_syscalls.rs#L448)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move after `LibraryCallL1Handler`?
</blockquote></details>

Sure. Why there specifically?
___
*[`crates/blockifier/src/execution/deprecated_syscalls.rs` line 473 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUMXhVhCXdaBAnEYfNh:-NUMZVIb0q6uro2lnqIA:b1rhzw1) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3f319c216176583f4ab2768c39656617a32afa7/crates/blockifier/src/execution/deprecated_syscalls.rs#L473)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we avoid this?
</blockquote></details>

Yeah, my bad.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/deprecated_syscalls.rs` line 448 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUMXSKGD5MJilPddA8i:-NUQlDjk5H-hqcW9N6qM:b-5skaid) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3f319c216176583f4ab2768c39656617a32afa7/crates/blockifier/src/execution/deprecated_syscalls.rs#L448)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Sure. Why there specifically?
</blockquote></details>

I just want them to be alphabetized; I thought they were until now.
___
*[`crates/blockifier/src/execution/deprecated_syscalls_test.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQm7XG2go6H7zmcBjV:-NUQm7XG2go6H7zmcBjW:b-rwh16c) ([raw file](https://github.com/starkware-libs/blockifier/blob/e408d46ab55a320c92d2c58aaaf477b20c260d86/crates/blockifier/src/execution/deprecated_syscalls_test.rs#L206)):*
> ```XML
>     let new_class_hash = ClassHash(stark_felt!(TEST_EMPTY_CONTRACT_CLASS_HASH));
>     assert_eq!(state.get_class_hash_at(contract_address).unwrap(), old_class_hash);
>     let calldata = calldata![new_class_hash.0];
> ```

Remove variable?



_Code quote:_
```XML
let calldata = calldata![new_class_hash.0];
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 434 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmZ4w79Q5umtlUeZJ:-NUQmZ4w79Q5umtlUeZK:bq47hvw) ([raw file](https://github.com/starkware-libs/blockifier/blob/e408d46ab55a320c92d2c58aaaf477b20c260d86/crates/blockifier/src/execution/execution_utils.rs#L434)):*
> ```XML
>     if current_class_hash != ClassHash::default() {
>         return Err(EntryPointExecutionError::from(StateError::UnavailableContractAddress(
>             deployed_contract_address,
> ```

Is there a shorter way to build the error we want? Some kind of `map_err`, or other Rust ergonomics?



_Code quote:_
```XML
        return Err(EntryPointExecutionError::from(StateError::UnavailableContractAddress(
            deployed_contract_address,
        )));
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 438 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmPiC00Wr4zqSlYUT:-NUQmPiC00Wr4zqSlYUU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e408d46ab55a320c92d2c58aaaf477b20c260d86/crates/blockifier/src/execution/execution_utils.rs#L438)):*
> ```XML
>     }
>     state.set_class_hash_at(deployed_contract_address, class_hash)?;
>     let code_address = if is_deploy_account_tx { None } else { Some(deployed_contract_address) };
> ```





_Suggestion:_
```XML
    
    state.set_class_hash_at(deployed_contract_address, class_hash)?;
    
    let code_address = if is_deploy_account_tx { None } else { Some(deployed_contract_address) };
    execute_constructor_entry_point(
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmj8N8UnI2TqM1rvA:-NUQmj8N8UnI2TqM1rvB:bruyv32) ([raw file](https://github.com/starkware-libs/blockifier/blob/0db24f2d445ff777ad5c522bc30b031672d882f5/crates/blockifier/src/state/cached_state_test.rs#L172)):*
> ```XML
> 
> #[test]
> fn cannot_set_class_hash_to_deployed_address() {
> ```

We still want to check this for deployments (both `DeployAccount` and `deploy()` syscall), right?



_Code quote:_
```XML
cannot_set_class_hash_to_deployed_address
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/deprecated_syscalls.rs` line 448 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUMXSKGD5MJilPddA8i:-NUQougB0TOriadvRPnZ:b-igw16v) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3f319c216176583f4ab2768c39656617a32afa7/crates/blockifier/src/execution/deprecated_syscalls.rs#L448)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I just want them to be alphabetized; I thought they were until now.
</blockquote></details>

NP, I'll do it in a new PR.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 434 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmZ4w79Q5umtlUeZJ:-NUQp5O174qUsZwn-TEV:b-g0dx9y) ([raw file](https://github.com/starkware-libs/blockifier/blob/e408d46ab55a320c92d2c58aaaf477b20c260d86/crates/blockifier/src/execution/execution_utils.rs#L434)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there a shorter way to build the error we want? Some kind of `map_err`, or other Rust ergonomics?
</blockquote></details>

Yes, `.into()`. I remember you liked the explicit `from` more. WDYT?
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmj8N8UnI2TqM1rvA:-NUQq4IHEkx9cFfRenwW:b-3ei09h) ([raw file](https://github.com/starkware-libs/blockifier/blob/0db24f2d445ff777ad5c522bc30b031672d882f5/crates/blockifier/src/state/cached_state_test.rs#L172)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We still want to check this for deployments (both `DeployAccount` and `deploy()` syscall), right?
</blockquote></details>

It's already tested in the deploy syscall and I added to the deploy account tx test.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 434 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmZ4w79Q5umtlUeZJ:-NUR4qC09nqhSmjvN3ru:bfjwll7) ([raw file](https://github.com/starkware-libs/blockifier/blob/e408d46ab55a320c92d2c58aaaf477b20c260d86/crates/blockifier/src/execution/execution_utils.rs#L434)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there a shorter way to build the error we want? Some kind of `map_err`, or other Rust ergonomics?
</blockquote></details>

`into` is less readable than `EntryPointExecutionError::from`, which is more explicit. I thought there's another way. @giladchase, any ideas?
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmj8N8UnI2TqM1rvA:-NUR5lsr0SrOkZZb_QX1:b-xxcdwj) ([raw file](https://github.com/starkware-libs/blockifier/blob/0db24f2d445ff777ad5c522bc30b031672d882f5/crates/blockifier/src/state/cached_state_test.rs#L172)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It's already tested in the deploy syscall and I added to the deploy account tx test.
</blockquote></details>

Where?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 608 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUR50on-j4FrJLOms5p:-NUR50on-j4FrJLOms5q:bj4gq92) ([raw file](https://github.com/starkware-libs/blockifier/blob/98e75cf24b5d29fd71d8fa9d6ee9bc990a7baf18/crates/blockifier/src/transaction/transactions_test.rs#L608)):*
> ```XML
>     // Negative flow.
>     // Deploy to an existing address.
>     let copied_deploy_account_tx =
> ```

Why "copied"?



_Code quote:_
```XML
copied_
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 434 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmZ4w79Q5umtlUeZJ:-NUR6Pjg3U_2D3cvv2Ro:b-zeqxfl) ([raw file](https://github.com/starkware-libs/blockifier/blob/e408d46ab55a320c92d2c58aaaf477b20c260d86/crates/blockifier/src/execution/execution_utils.rs#L434)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`into` is less readable than `EntryPointExecutionError::from`, which is more explicit. I thought there's another way. @giladchase, any ideas?
</blockquote></details>

In this case, only the inner error is important for readability (the same way `?` converts implicitly), so I think you were right in asking for a shorter way. 
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmj8N8UnI2TqM1rvA:-NUR5vsM8GEsOrUKeGZr:b-4m635c) ([raw file](https://github.com/starkware-libs/blockifier/blob/0db24f2d445ff777ad5c522bc30b031672d882f5/crates/blockifier/src/state/cached_state_test.rs#L172)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where?
</blockquote></details>

https://github.com/starkware-libs/blockifier/blob/98e75cf24b5d29fd71d8fa9d6ee9bc990a7baf18/crates/blockifier/src/execution/deprecated_syscalls_test.rs#L326
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 608 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUR50on-j4FrJLOms5p:-NUR5yzfCHlyOAcL2fQA:b-gi9rmy) ([raw file](https://github.com/starkware-libs/blockifier/blob/98e75cf24b5d29fd71d8fa9d6ee9bc990a7baf18/crates/blockifier/src/transaction/transactions_test.rs#L608)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why "copied"?
</blockquote></details>

It's the same transaction as before with an advanced nonce. I don't love `copied` either; any ideas?

**Review by elintul — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 434 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmZ4w79Q5umtlUeZJ:-NUREELh6wbMkz2tPcAD:b-r6dow7) ([raw file](https://github.com/starkware-libs/blockifier/blob/e408d46ab55a320c92d2c58aaaf477b20c260d86/crates/blockifier/src/execution/execution_utils.rs#L434)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In this case, only the inner error is important for readability (the same way `?` converts implicitly), so I think you were right in asking for a shorter way. 
</blockquote></details>

But we currently don't use `.into`, only `::from`.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmj8N8UnI2TqM1rvA:-NUREa4c5Mt4N2iyZSJ1:bwjb1ku) ([raw file](https://github.com/starkware-libs/blockifier/blob/0db24f2d445ff777ad5c522bc30b031672d882f5/crates/blockifier/src/state/cached_state_test.rs#L172)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

https://github.com/starkware-libs/blockifier/blob/98e75cf24b5d29fd71d8fa9d6ee9bc990a7baf18/crates/blockifier/src/execution/deprecated_syscalls_test.rs#L326
</blockquote></details>

Cool, didn't find it.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 608 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUR50on-j4FrJLOms5p:-NUREdumCgMOwQLTBAyz:byx72ak) ([raw file](https://github.com/starkware-libs/blockifier/blob/98e75cf24b5d29fd71d8fa9d6ee9bc990a7baf18/crates/blockifier/src/transaction/transactions_test.rs#L608)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It's the same transaction as before with an advanced nonce. I don't love `copied` either; any ideas?
</blockquote></details>

Can we reuse the name?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 434 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmZ4w79Q5umtlUeZJ:-NURF2lK7yHiATu3Sk49:b-xwn2it) ([raw file](https://github.com/starkware-libs/blockifier/blob/e408d46ab55a320c92d2c58aaaf477b20c260d86/crates/blockifier/src/execution/execution_utils.rs#L434)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

But we currently don't use `.into`, only `::from`.
</blockquote></details>

I think `.into` is fine for errors especially, but it's not very important to me. Let me know which one you prefer.



_Code quote (from crates/blockifier/src/transaction/transactions_test.rs):_
```XML
copied_deploy_account_tx
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 608 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUR50on-j4FrJLOms5p:-NUREyJsEK7wv_tr-vA9:brgq1k0) ([raw file](https://github.com/starkware-libs/blockifier/blob/98e75cf24b5d29fd71d8fa9d6ee9bc990a7baf18/crates/blockifier/src/transaction/transactions_test.rs#L608)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we reuse the name?
</blockquote></details>

Sure. Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436#-:-NURFhMe9tMC8iq1HtP-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 434 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmZ4w79Q5umtlUeZJ:-NURFbMQ1vGOpDQkgeFT:b9gqans) ([raw file](https://github.com/starkware-libs/blockifier/blob/e408d46ab55a320c92d2c58aaaf477b20c260d86/crates/blockifier/src/execution/execution_utils.rs#L434)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think `.into` is fine for errors especially, but it's not very important to me. Let me know which one you prefer.
</blockquote></details>

Yeah, maybe you're right. We should fix in another PR then.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 434 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/436#-NUQmZ4w79Q5umtlUeZJ:-NURG-jC4P8gOI7suY6i:bhy9ot6) ([raw file](https://github.com/starkware-libs/blockifier/blob/e408d46ab55a320c92d2c58aaaf477b20c260d86/crates/blockifier/src/execution/execution_utils.rs#L434)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yeah, maybe you're right. We should fix in another PR then.
</blockquote></details>

Will do.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
