### PR TITLE
Add declare DA cost.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/724)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/724)* status: 0 of 6 files reviewed, 2 unresolved discussions

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 318 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzTQyd374rz_a5cQ6T:-NZzTQye8qgF2OVvbwlO:b-qd71pp) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ee5570b352390d9391f33549f15d107dc812a26/crates/blockifier/src/transaction/transactions_test.rs#L318)):*
> ```XML
>         actual_fee: expected_actual_fee,
>         actual_resources: ResourcesMapping(HashMap::from([
>             (abi_constants::GAS_USAGE.to_string(), 3060),
> ```

We add + 1 * 612 to the gas usage
Where `SHARP_GAS_PER_MEMORY_WORD = 612`



_Code quote:_
```XML
(abi_constants::GAS_USAGE.to_string(), 3060),
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 652 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzT_4t2gPdvZjtXErW:-NZzT_4t2gPdvZjtXErX:beonyq5) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ee5570b352390d9391f33549f15d107dc812a26/crates/blockifier/src/transaction/transactions_test.rs#L652)):*
> ```XML
> 
>     let expected_actual_resources = ResourcesMapping(HashMap::from([
>         (abi_constants::GAS_USAGE.to_string(), 4284),
> ```

`4284 = 2448 + 612 * 3`



_Code quote:_
```XML
(abi_constants::GAS_USAGE.to_string(), 4284),
```

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/724)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzn9he26AWA_-bhNcj:-NZzn9he26AWA_-bhNck:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/490dd16bfbb5c64e2fab7c4218f3a95c960d8aed/crates/blockifier/src/fee/gas_usage.rs#L71)):*
> ```XML
>     // For each compiled class updated (through declare): class_hash, compiled_class_hash + the
>     // number of classes that have been declared.
>     onchain_data_segment_length += state_changes.n_compiled_class_hash_updates * 2 + 1;
> ```





_Suggestion:_
```XML
    // For each newly modified contract: contract address, number of modified storage cells.
    let mut onchain_data_segment_length = state_changes.n_modified_contracts * 2;
    // For each class updated (through a deploy or a class replacement).
    onchain_data_segment_length +=
        state_changes.n_class_hash_updates * constants::CLASS_UPDATE_SIZE;
    // For each modified storage cell: key, new value.
    onchain_data_segment_length += state_changes.n_storage_updates * 2;
    // Number of declared classes, and for each compiled class updated (through declare): 
    // class_hash, compiled_class_hash.
    onchain_data_segment_length += state_changes.n_compiled_class_hash_updates * 2 + 1;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 318 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzTQyd374rz_a5cQ6T:-NZzrJjz0C0dEcOFtCN-:bgnoflo) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ee5570b352390d9391f33549f15d107dc812a26/crates/blockifier/src/transaction/transactions_test.rs#L318)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We add + 1 * 612 to the gas usage
Where `SHARP_GAS_PER_MEMORY_WORD = 612`
</blockquote></details>

Here also.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 652 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzT_4t2gPdvZjtXErW:-NZzqfFIDukF6RGH1I2h:b-8wg04t) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ee5570b352390d9391f33549f15d107dc812a26/crates/blockifier/src/transaction/transactions_test.rs#L652)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

`4284 = 2448 + 612 * 3`
</blockquote></details>

Write this calculation in the code. :)
Also, in other places where possible; it will improve readability.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/fee/gas_usage.rs` line 157 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzqP4h6vWDa58CFXFm:-NZzqP4h6vWDa58CFXFn:bbqjjb8) ([raw file](https://github.com/starkware-libs/blockifier/blob/7045dab5b8be8a4d64af292c40d6f6b8ad752fb3/crates/blockifier/src/fee/gas_usage.rs#L157)):*
> ```XML
>             n_storage_updates: 1,
>             n_class_hash_updates: 0,
>             n_compiled_class_hash_updates: 0,
> ```

A declare tx should add exactly one such update.



_Suggestion:_
```XML
n_compiled_class_hash_updates: 1,
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/724)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzrsjDB8Od3Q3IWvPd:-NZzrsjDB8Od3Q3IWvPe:bwd697w) ([raw file](https://github.com/starkware-libs/blockifier/blob/7045dab5b8be8a4d64af292c40d6f6b8ad752fb3/crates/blockifier/src/fee/gas_usage_test.rs#L118)):*
> ```XML
>     let expected_gas_usage =
>         l1_handler_gas_usage + l2_to_l1_messages_gas_usage + storage_writings_gas_usage
>             - 2 * eth_gas_constants::SHARP_GAS_PER_MEMORY_WORD;
> ```

I don’t understand what duplication you refer to.
I don’t understand what the magic number: `2` is.



_Code quote:_
```XML
    // Reduce the duplication in the cost of number of declared classes.
    let expected_gas_usage =
        l1_handler_gas_usage + l2_to_l1_messages_gas_usage + storage_writings_gas_usage
            - 2 * eth_gas_constants::SHARP_GAS_PER_MEMORY_WORD;
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/724)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 157 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzqP4h6vWDa58CFXFm:-NZzrXjo7H610RF8BXOt:b5peg56) ([raw file](https://github.com/starkware-libs/blockifier/blob/7045dab5b8be8a4d64af292c40d6f6b8ad752fb3/crates/blockifier/src/fee/gas_usage.rs#L157)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

A declare tx should add exactly one such update.
</blockquote></details>

You are right when referring to declare v2. When estimating the minimal fee we take into account declare v0/1 as well.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzrsjDB8Od3Q3IWvPd:-N_-RNjd656QK9Im1BYV:bppgd3g) ([raw file](https://github.com/starkware-libs/blockifier/blob/7045dab5b8be8a4d64af292c40d6f6b8ad752fb3/crates/blockifier/src/fee/gas_usage_test.rs#L118)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No relevant anymore :)
</blockquote></details>

Nice! In that case, remove the related comment.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/fee/gas_usage.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzn9he26AWA_-bhNcj:-N_-RuDr4cADG_Nm_LrE:b-xs643t) ([raw file](https://github.com/starkware-libs/blockifier/blob/490dd16bfbb5c64e2fab7c4218f3a95c960d8aed/crates/blockifier/src/fee/gas_usage.rs#L71)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I removed the number of declared classes since it written once in a block (as done for the number of modified contracts).
</blockquote></details>

Where are these counted, then? Both the number of modified contracts and the number of modified classes?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/724)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzn9he26AWA_-bhNcj:-N_30FDtDnIzXI4JkgEL:b-firqa2) ([raw file](https://github.com/starkware-libs/blockifier/blob/490dd16bfbb5c64e2fab7c4218f3a95c960d8aed/crates/blockifier/src/fee/gas_usage.rs#L71)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Where are these counted, then? Both the number of modified contracts and the number of modified classes?
</blockquote></details>

They are not. We could consider (in the future) calculating their cost and dividing it among the transactions according to their relative weight in the block.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 72 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/724#-N_-SLhfAPj1Joof0QMT:-N_3-kHw4Ru80_TQof_D:b-3slna9) ([raw file](https://github.com/starkware-libs/blockifier/blob/028609a1d72ec8b71aa7509060183a73eabf2677/crates/blockifier/src/fee/gas_usage.rs#L72)):*
> ```XML
>     // For each modified storage cell: key, new value.
>     onchain_data_segment_length += state_changes.n_storage_updates * 2;
>     // For each compiled class updated (through declare): class_hash, compiled_class_hash
> ```

IIUC replace class affects only the `contract_address -> class_hash` mapping (`n_class_hash_updates`).
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzrsjDB8Od3Q3IWvPd:-N_-Rm4o21f3f2vwcxLY:bdiecbc) ([raw file](https://github.com/starkware-libs/blockifier/blob/7045dab5b8be8a4d64af292c40d6f6b8ad752fb3/crates/blockifier/src/fee/gas_usage_test.rs#L118)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Nice! In that case, remove the related comment.
</blockquote></details>

Right :)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/fee/gas_usage.rs` line 72 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/724#-N_-SLhfAPj1Joof0QMT:-N_3FUSH4ueCT7H9p7UX:b-43wiqt) ([raw file](https://github.com/starkware-libs/blockifier/blob/028609a1d72ec8b71aa7509060183a73eabf2677/crates/blockifier/src/fee/gas_usage.rs#L72)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

IIUC replace class affects only the `contract_address -> class_hash` mapping (`n_class_hash_updates`).
</blockquote></details>

You are correct. Sorry.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/724#-:-N_3FsEp7w3Q8irxNh7p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/724)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 318 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/724#-NZzTQyd374rz_a5cQ6T:-N_-QG6r8DZ7eYZmcOxf:b96jwwo) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ee5570b352390d9391f33549f15d107dc812a26/crates/blockifier/src/transaction/transactions_test.rs#L318)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Write `(2 + 2) * 612` in the code, instead of the result; comment might get outdated.

**Review by ArniStarkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/724)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/724)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
