### PR TITLE
refactor(concurrency): remove concurrency_mode from block context

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2016)

### CODE REVIEW

**Review by avi-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 17 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2016#-:-O0idvIvAykPSXiXHC0X:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 6 of 17 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2016)* status: all files reviewed, 4 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2016#-O0m772S1DCd0-IEAkpM:-O0m772S1DCd0-IEAkpN:b-z1r0ua) ([raw file](https://github.com/starkware-libs/blockifier/blob/9343c9d2ec7af7e772665be63991f593acd1ba26/crates/blockifier/src/blockifier/transaction_executor.rs#L94)):*
> ```XML
>         let charge_fee = true;
>         // Executing a single transaction cannot be done in a concurrent mode.
>         let run_concurrently = false;
> ```

It indicates the mode of which to run the fee transfer. We can run transactions concurrently with ` concurrent_mode = false`.
Another suggestion: `concurrent_fee_transfer` (more infomative)



_Suggestion:_
```XML
let concurrent_mode = false;
```
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 273 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2016#-O0m95OO9041v8RZscI3:-O0m95OO9041v8RZscI4:b-58o8sk) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e9a26c622a889ea9cecca0b1d3d82a36dfe3e42/crates/blockifier/src/blockifier/transaction_executor_test.rs#L273)):*
> ```XML
>         max_n_events_in_block,
>         config.concurrency_config.enabled,
>     );
> ```

Note that this test ran both in concurrent and in non-concurrent mode. 



_Code quote:_
```XML
    let block_context = BlockContext::create_for_bouncer_testing(
        max_n_events_in_block,
        config.concurrency_config.enabled,
    );
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 261 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2016#-O0mBKykB3O3ZXi6f5Wr:-O0mBKykB3O3ZXi6f5Ws:b-uh7ql5) ([raw file](https://github.com/starkware-libs/blockifier/blob/9343c9d2ec7af7e772665be63991f593acd1ba26/crates/blockifier/src/concurrency/worker_logic.rs#L261)):*
> ```XML
>                 }
>             }
>             complete_fee_transfer_flow(
> ```

It is only called from the worker. Is the `run_concurrently` input necessary? 



_Code quote:_
```XML
 complete_fee_transfer_flow(
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1260 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2016#-O0mCqJAD_NzA5WXUMZQ:-O0mCqJAD_NzA5WXUMZR:bhjqkge) ([raw file](https://github.com/starkware-libs/blockifier/blob/9343c9d2ec7af7e772665be63991f593acd1ba26/crates/blockifier/src/transaction/account_transactions_test.rs#L1260)):*
> ```XML
> 
>     let mut outer_transactional_state =
>         TransactionalState::create_transactional(&mut transactional_state);
> ```

Why is it needed?



_Code quote:_
```XML
    let mut outer_transactional_state =
        TransactionalState::create_transactional(&mut transactional_state);
```

**Review by noaov1 — DISMISSED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2016#-:-O0mlZi5-g2rXgaDpzZc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2016)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
