### PR TITLE
Post execution checks with auditor struct

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiVWfu-EwqWdMhY5eEl:-NiVWfu-EwqWdMhY5eEm:bb3iuzc) (no related file):*
Replaces [this](https://reviewable.io/reviews/starkware-libs/blockifier/1045)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiVZC_ZBB4rDpRO3rtI:-NiVZC_ZBB4rDpRO3rtJ:b-x0uq2f) (no related file):*
[Test](https://reviewable.io/reviews/starkware-libs/blockifier/1049)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 268 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiV_v5J6RAe27tXWh5R:-NiV_v5J6RAe27tXWh5S:b-pfsf8y) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbb0a44e3f015b5433c1e45fc468345dacfa1048/crates/blockifier/src/fee/actual_cost.rs#L268)):*
> ```XML
>             // If sender bounds were exceeded, charge based on the sender bounds.
>             PostExecutionAuditorError::MaxL1GasAmountExceeded { .. }
>             | PostExecutionAuditorError::MaxFeeExceeded { .. } => {
> ```

we can choose to pack the max L1 gas / max fee into the errors and destructure,
but doesn't seem like good practice, business logic relying on internal fields of errors



_Code quote:_
```XML
            PostExecutionAuditorError::MaxL1GasAmountExceeded { .. }
            | PostExecutionAuditorError::MaxFeeExceeded { .. } => {
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiVa5yd8GFFwaXJsfH3:-NiVa5yd8GFFwaXJsfH4:b9uw4oz) ([raw file](https://github.com/starkware-libs/blockifier/blob/133eea8ca8203fce9c5522579098cbd2cc6dbeba/crates/blockifier/src/fee/fee_utils.rs#L122)):*
> ```XML
> 
> /// Returns `true` if and only if the balance covers the fee.
> pub fn can_pay_fee(
> ```

was needed in old post-execution checks for revertible transactions
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiV_9J30Dv7rZQh4-tO:-NiV_9J30Dv7rZQh4-tP:b19ib60) ([raw file](https://github.com/starkware-libs/blockifier/blob/133eea8ca8203fce9c5522579098cbd2cc6dbeba/crates/blockifier/src/transaction/account_transaction.rs#L225)):*
> ```XML
>         if actual_fee > max_fee {
>             return Err(TransactionExecutionError::FeeTransferError { max_fee, actual_fee });
>         }
> ```

1. This was wrong before: `actual_fee > max_fee()` is not the correct check for V3 transactions.
2. This was the *non-revertible* post-execution check; it has now been replaced by the auditor.



_Code quote:_
```XML
        let max_fee = account_tx_context.max_fee();
        if actual_fee > max_fee {
            return Err(TransactionExecutionError::FeeTransferError { max_fee, actual_fee });
        }
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 259 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiV_O0168lLWYllkmeY:-NiV_O0168lLWYllkmeZ:bfof4kg) ([raw file](https://github.com/starkware-libs/blockifier/blob/133eea8ca8203fce9c5522579098cbd2cc6dbeba/crates/blockifier/src/transaction/account_transaction.rs#L259)):*
> ```XML
>     /// After successful execution and fee computation, checks that the sender can pay the fee.
>     /// Returns the actual fee to pay and an optional revert error (if revert is needed).
>     fn post_execution_final_fee_and_error<S: StateReader>(
> ```

Replaced by auditor



_Code quote:_
```XML
post_execution_final_fee_and_error
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 322 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiVaEsz5mRtUE0jjbVP:-NiVaEsz5mRtUE0jjbVQ:bmeyv6m) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbb0a44e3f015b5433c1e45fc468345dacfa1048/crates/blockifier/src/transaction/account_transaction.rs#L322)):*
> ```XML
>             charge_fee,
>         }
>         .verify_valid_actual_cost(state)?;
> ```

in non-revertible flow, just propagate the error - we don't care why post-execution failed



_Code quote:_
```XML
.verify_valid_actual_cost(state)?;
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiV_9J30Dv7rZQh4-tO:-Ni_FpnuEo40hqIjXNJD:bghfe8k) ([raw file](https://github.com/starkware-libs/blockifier/blob/133eea8ca8203fce9c5522579098cbd2cc6dbeba/crates/blockifier/src/transaction/account_transaction.rs#L225)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. This was wrong before: `actual_fee > max_fee()` is not the correct check for V3 transactions.
2. This was the *non-revertible* post-execution check; it has now been replaced by the auditor.
</blockquote></details>

For the non-revertible flow we added the balance check, right?
Why?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiV_9J30Dv7rZQh4-tO:-Ni_H5J72y69EtpFw1OY:bsgiws) ([raw file](https://github.com/starkware-libs/blockifier/blob/133eea8ca8203fce9c5522579098cbd2cc6dbeba/crates/blockifier/src/transaction/account_transaction.rs#L225)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

For the non-revertible flow we added the balance check, right?
Why?
</blockquote></details>

1. To get a post-execution error instead of a fee transfer error (this previously would have failed in fee transfer)
2. To align non-revertible post-execution checks to revertible post-execution checks

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 203 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NicmeRl-4K2EzPdCMa6:-NicmeRl-4K2EzPdCMa7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ecb684f131d7dbc3c73bd6d0da3c08b5b80bc618/crates/blockifier/src/fee/actual_cost.rs#L203)):*
> ```XML
>         // First, compare actual resources used against the upper bound(s) defined by the sender.
>         // If the initial check fails, revert and charge based on the upper bound(s) and current
>         // price(s). The resources reported in the error
> ```





_Suggestion:_
```XML
        // price(s). The resources reported in the error.
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 211 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NictImKEbOPgBQ2uQ95:-NictImKEbOPgBQ2uQ96:boxbtx2) ([raw file](https://github.com/starkware-libs/blockifier/blob/ecb684f131d7dbc3c73bd6d0da3c08b5b80bc618/crates/blockifier/src/fee/actual_cost.rs#L211)):*
> ```XML
>                 let max_l1_gas =
>                     context.l1_resource_bounds().expect("L1 gas bounds must be set.").max_amount
>                         as u128;
> ```

It's a bit weird that the actual amount is a `u128` while the `max_amount` is a `u64`. 
Just sharing. No call for a specific action. 



_Code quote:_
```XML
                    context.l1_resource_bounds().expect("L1 gas bounds must be set.").max_amount
                        as u128;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 416 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-Nid20ZB1RdytrsA_Mhd:-Nid20ZC31uv601xZfzK:b8tx7jj) ([raw file](https://github.com/starkware-libs/blockifier/blob/ecb684f131d7dbc3c73bd6d0da3c08b5b80bc618/crates/blockifier/src/transaction/account_transaction.rs#L416)):*
> ```XML
> 
>                 // On error post-execution error, revert and update the actual fee.
>                 // Resources should remain the same.
> ```

Why? Do we want to report the resources of the transaction if it would have been succeeded? Why not the resources she actually consumed?
Why is it different from the case of an error during execution? 



_Code quote:_
```XML
                // Resources should remain the same.
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 416 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-Nid20ZB1RdytrsA_Mhd:-NidW3YE2ApFS393Tzry:b-pyjjue) ([raw file](https://github.com/starkware-libs/blockifier/blob/ecb684f131d7dbc3c73bd6d0da3c08b5b80bc618/crates/blockifier/src/transaction/account_transaction.rs#L416)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

The resources report should be as close to the "resources consumed during execution" as possible.
1. In post-execution error, this is the "same" resources, i.e. the resources consumed during validate+execute.
2. In mid-execution error, we do not really have a resources map constructed (for execute phase), because it didn't complete. We take the resources we *do* have (validate resources) and add the number of consumed cairo steps.
</blockquote></details>

Why is that? Why should the bouncer take those resources into account?
WDYM by "not really have a resources map constructed"?
I don't think this is how we behave today.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 416 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-Nid20ZB1RdytrsA_Mhd:-NidknaJ6m-SRQ2_mRO3:bwmmgi5) ([raw file](https://github.com/starkware-libs/blockifier/blob/ecb684f131d7dbc3c73bd6d0da3c08b5b80bc618/crates/blockifier/src/transaction/account_transaction.rs#L416)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is that? Why should the bouncer take those resources into account?
WDYM by "not really have a resources map constructed"?
I don't think this is how we behave today.
</blockquote></details>

You're right, changed it.
@Yoni-Starkware FYI

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 416 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-Nid20ZB1RdytrsA_Mhd:-Nie-5a-CrI7srmhQDjJ:b-mj9cgq) ([raw file](https://github.com/starkware-libs/blockifier/blob/ecb684f131d7dbc3c73bd6d0da3c08b5b80bc618/crates/blockifier/src/transaction/account_transaction.rs#L416)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

You're right, changed it.
@Yoni-Starkware FYI
</blockquote></details>

Change the comment?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 416 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-Nid20ZB1RdytrsA_Mhd:-NieObk-47HK9XPHFN7F:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ecb684f131d7dbc3c73bd6d0da3c08b5b80bc618/crates/blockifier/src/transaction/account_transaction.rs#L416)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Change the comment?
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 408 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NifTRQWBQfW5Bv-QvAb:-NifTRQWBQfW5Bv-QvAc:bezcdlz) ([raw file](https://github.com/starkware-libs/blockifier/blob/19b1c0cb62383b8a8c93b76c5e5f3d24cd5926be/crates/blockifier/src/transaction/account_transaction.rs#L408)):*
> ```XML
>                 // transactional state. If max_fee is insufficient, revert the `run_execute` part.
>                 let actual_cost = actual_cost_builder_with_validation_changes
>                     .clone()
> ```

You can avoid the clone now, no?



_Code quote:_
```XML
                    .clone()
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 451 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiheNC6-3RNLnkRVM_Q:-NiheNC6-3RNLnkRVM_R:biojwly) ([raw file](https://github.com/starkware-libs/blockifier/blob/19b1c0cb62383b8a8c93b76c5e5f3d24cd5926be/crates/blockifier/src/transaction/account_transaction.rs#L451)):*
> ```XML
>                     }
>                     // Propagate other errors.
>                     Err(other_error) => Err(other_error),
> ```

Why not revert in this case?



_Code quote:_
```XML
                    // Propagate other errors.
                    Err(other_error) => Err(other_error),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 408 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NifTRQWBQfW5Bv-QvAb:-Nihm6eZ-muDTKx4VZ1D:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/19b1c0cb62383b8a8c93b76c5e5f3d24cd5926be/crates/blockifier/src/transaction/account_transaction.rs#L408)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You can avoid the clone now, no?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 451 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiheNC6-3RNLnkRVM_Q:-NihljzAAEo5QpuemFzh:b-ase898) ([raw file](https://github.com/starkware-libs/blockifier/blob/19b1c0cb62383b8a8c93b76c5e5f3d24cd5926be/crates/blockifier/src/transaction/account_transaction.rs#L451)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not revert in this case?
</blockquote></details>

If we hit an error reading from the state, for example, what should we do?
We can only revert on specific errors we know how to deal with

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 451 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiheNC6-3RNLnkRVM_Q:-NihndbS3Pll9vkrk-k9:b6gtfi5) ([raw file](https://github.com/starkware-libs/blockifier/blob/19b1c0cb62383b8a8c93b76c5e5f3d24cd5926be/crates/blockifier/src/transaction/account_transaction.rs#L451)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

If we hit an error reading from the state, for example, what should we do?
We can only revert on specific errors we know how to deal with
</blockquote></details>

I'm confused. Isn't that what we are doing in the code below? `Err(_)`?
What am I missing?

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 451 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiheNC6-3RNLnkRVM_Q:-NihxDn03-8L6DczzBTH:b-vswl17) ([raw file](https://github.com/starkware-libs/blockifier/blob/19b1c0cb62383b8a8c93b76c5e5f3d24cd5926be/crates/blockifier/src/transaction/account_transaction.rs#L451)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm confused. Isn't that what we are doing in the code below? `Err(_)`?
What am I missing?
</blockquote></details>

no; the `Err(_)` below is if we hit an error during `__execute__`, not during post-execution check.
You're right that this error could, in theory, be a sequencer error; do you have a suggestion for a more specific error that captures *all possible* revert scenarios in `__execute__`?

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 451 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiheNC6-3RNLnkRVM_Q:-Nihxn6TBXjX5TdawCRA:b-tawcey) ([raw file](https://github.com/starkware-libs/blockifier/blob/19b1c0cb62383b8a8c93b76c5e5f3d24cd5926be/crates/blockifier/src/transaction/account_transaction.rs#L451)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no; the `Err(_)` below is if we hit an error during `__execute__`, not during post-execution check.
You're right that this error could, in theory, be a sequencer error; do you have a suggestion for a more specific error that captures *all possible* revert scenarios in `__execute__`?
</blockquote></details>

Oh. I see. So it makes no sense to revert a transaction due to a sequencer bug, but we might do it. Got it. Thanks. 
Add a comment?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 451 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1084#-NiheNC6-3RNLnkRVM_Q:-Nii0duwBL7E5jd-jITb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/19b1c0cb62383b8a8c93b76c5e5f3d24cd5926be/crates/blockifier/src/transaction/account_transaction.rs#L451)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh. I see. So it makes no sense to revert a transaction due to a sequencer bug, but we might do it. Got it. Thanks. 
Add a comment?
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1084)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

**Pull request merged**
