### PR TITLE
Recompile cairo1 feature contracts 2.1.0 -> 2.4.0

### PR DESCRIPTION
**Pull request by giladchase**
- In `account_with_dummy_validate` use unwrap instead of unwrap_syscall (the latter is no longer supported).
- Add newlines at end of files: this is part of valid json, and in particular once the fixer script is fixed it will generate them with newlines by default.
- `account_with_dummy_validate` has new resource values after recompilation.
- Fix resources in invoke_test that uses account_with_dummy_validate.cairo

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1259)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1259)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/account_with_dummy_validate.cairo` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1259#-Nlc_jFa4PoIvPe7eLMC:-Nlc_jFb1gm5548AamHU:bvci68m) ([raw file](https://github.com/starkware-libs/blockifier/blob/f1ae7a5f66dbedf70e72da8a252eddf6b9a066b3/crates/blockifier/feature_contracts/cairo1/account_with_dummy_validate.cairo#L50)):*
> ```Cairo
>             entry_point_selector: selector,
>             calldata: calldata.span()
>         ).unwrap()
> ```

`unwrap_syscall` is supported. You need to add:`use starknet::info::SyscallResultTrait`.



_Suggestion:_
```Cairo
).unwrap_syscall()
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1259)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1259#-Nlch4SVC_NVlPj-yedu:-Nlch4SWCOrIsFOGfw3p:bqw9tgc) ([raw file](https://github.com/starkware-libs/blockifier/blob/f1ae7a5f66dbedf70e72da8a252eddf6b9a066b3/crates/blockifier/src/transaction/transactions_test.rs#L316)):*
> ```XML
>     ExpectedResultTestInvokeTx{
>         range_check: 113,
>         n_steps: 4701,
> ```

The compilation affected invoke test only? Interesting. 



_Code quote:_
```XML
 n_steps: 4701,
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1259)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/account_with_dummy_validate.cairo` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1259#-Nlc_jFa4PoIvPe7eLMC:-NnDdNpqE5hGCU-CIwmR:b-5mv9wo) ([raw file](https://github.com/starkware-libs/blockifier/blob/f1ae7a5f66dbedf70e72da8a252eddf6b9a066b3/crates/blockifier/feature_contracts/cairo1/account_with_dummy_validate.cairo#L50)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

`unwrap_syscall` is supported. You need to add:`use starknet::info::SyscallResultTrait`.
</blockquote></details>

Ohhh thanks!
Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1259#-Nlch4SVC_NVlPj-yedu:-NnDg9dI-HvE6kX0yV71:b5cn7g1) ([raw file](https://github.com/starkware-libs/blockifier/blob/f1ae7a5f66dbedf70e72da8a252eddf6b9a066b3/crates/blockifier/src/transaction/transactions_test.rs#L316)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The compilation affected invoke test only? Interesting.
</blockquote></details>

Yep, not sure why :(

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1259#-:-NnIn4KyAAO7FVSnqwRG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Pull request merged**
