### PR TITLE
Remove `max_fee` getter from transactions.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/989)

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/989)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/989#-Ngx0EbNESmRKxALXoLd:-Ngx0EbNESmRKxALXoLe:b-34pkj9) ([raw file](https://github.com/starkware-libs/blockifier/blob/42acebfe750b61ee5c02aebed80a76bd085a7159/crates/blockifier/src/transaction/transactions.rs#L182)):*
> ```XML
>                     max_fee: tx.max_fee,
>                 })
>             }
> ```

Why can't this be combined with V2? Is it because it has a different struct type?



_Code quote:_
```XML
                AccountTransactionContext::Deprecated(DeprecatedAccountTransactionContext {
                    common_fields,
                    max_fee: tx.max_fee,
                })
            }
```

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/989)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/989)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/989#-Ngx0EbNESmRKxALXoLd:-NgxAJfsEOVHvlYxX-2R:bstmjb6) ([raw file](https://github.com/starkware-libs/blockifier/blob/42acebfe750b61ee5c02aebed80a76bd085a7159/crates/blockifier/src/transaction/transactions.rs#L182)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why can't this be combined with V2? Is it because it has a different struct type?
</blockquote></details>

Yes... :(

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/989#-:-NgxATp24E7DN5kqDlFd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
