### PR TITLE
refactor(concurrency): get rid of Result return type of the run metho…

### PR DESCRIPTION
**Pull request by barak-b-starkware**
…d of the WorkerExecutor

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1924)

### CODE REVIEW

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1924)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @meship-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1924#-Nz1imMF3Y_F586DI-mK:-Nz1imMF3Y_F586DI-mL:b-7rntaf) ([raw file](https://github.com/starkware-libs/blockifier/blob/926c552b4d41d5132c9acd86cbc8ecc48ab25ea7/crates/blockifier/src/concurrency/worker_logic.rs#L220)):*
> ```XML
>                         "Accesing the storage cells of the balance should succeed unless there is \
>                          a bug or some problem with papyrus.",
>                     );
> ```

If there's a problem with Papyrus and we are panicking, we would want to see the actual error so we can debug it.



_Suggestion:_
```XML
                    .unwrap_or_else(|error| {
                        panic!("Access to storage failed. Probably due to a bug in Papyrus. {error:?}: {error}")
                    })
```

**Review by meship-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1924)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1924#-:-Nz73yE_9O64r07EjOnD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1924#-Nz1imMF3Y_F586DI-mK:-Nz73Z8c4EJ-eb95JogN:b-q3bxn6) ([raw file](https://github.com/starkware-libs/blockifier/blob/926c552b4d41d5132c9acd86cbc8ecc48ab25ea7/crates/blockifier/src/concurrency/worker_logic.rs#L220)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

If there's a problem with Papyrus and we are panicking, we would want to see the actual error so we can debug it.
</blockquote></details>

Ideally, StateReadError would propagate to the batcher and restart it.
But the code is not consistent right now, so it's okay for now (with the TODO)

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1924)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1924#-Nz1imMF3Y_F586DI-mK:-Nz7cO7A8XXaxBfwkLVd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/926c552b4d41d5132c9acd86cbc8ecc48ab25ea7/crates/blockifier/src/concurrency/worker_logic.rs#L220)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Ideally, StateReadError would propagate to the batcher and restart it.
But the code is not consistent right now, so it's okay for now (with the TODO)
</blockquote></details>

Done.

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1924)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1924)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1924)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

**Pull request merged**
