### PR TITLE
Remove nonce_manager arg, pass nonce directly

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/952)

### CODE REVIEW

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/test_utils.rs` line 400 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/952#-NfjW8HK6VwP-Hat4fB0:-NfjW8HL8xxbza-878Ts:bulnkre) ([raw file](https://github.com/starkware-libs/blockifier/blob/78fa7c3922ec2fedb5423cfd902fb8348cc98e62/crates/blockifier/src/test_utils.rs#L400)):*
> ```XML
>     pub paymaster_data: PaymasterData,
>     pub account_deployment_data: AccountDeploymentData,
>     pub nonce: Nonce,
> ```

I think it's better to make this field optional. The default nonce value is 0, which can also be a valid value.

Similar arguments apply to all new fields. I think it's better to make them optional a la `signature` and `entry_point_selector` and be consistent.



_Code quote:_
```XML
pub nonce: Nonce,
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/952)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, @noaov1, and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/952#-NfkFLRAAjnyfVsmivAI:-NfkFLRAAjnyfVsmivAJ:bubllpz) (no related file):*
Why? You're repeating `nonce_managet.next()`.

___
___
*[`crates/blockifier/src/test_utils.rs` line 400 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/952#-NfjW8HK6VwP-Hat4fB0:-NfkFd1Y16mo6Y9a8BOl:b-5q6gfi) ([raw file](https://github.com/starkware-libs/blockifier/blob/78fa7c3922ec2fedb5423cfd902fb8348cc98e62/crates/blockifier/src/test_utils.rs#L400)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

I think it's better to make this field optional. The default nonce value is 0, which can also be a valid value.

Similar arguments apply to all new fields. I think it's better to make them optional a la `signature` and `entry_point_selector` and be consistent.
</blockquote></details>

Not sure I agree.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/952)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/952#-NfkFLRAAjnyfVsmivAI:-NfkMsxD6XFhEZtuOEZ-:bjjau0) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why? You're repeating `nonce_managet.next()`.
</blockquote></details>

well... first off it's `(15 - 4) - 16` =  5 lines less :P 
second, I think it's cleaner; however, you are right about the extra boilerplate.
I don't want the nonce manager to be a field of the tx args though.
You have any ideas?


___
___
*[`crates/blockifier/src/test_utils.rs` line 400 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/952#-NfjW8HK6VwP-Hat4fB0:-NfkNExmEaKxE4-AEkMY:bz1egzz) ([raw file](https://github.com/starkware-libs/blockifier/blob/78fa7c3922ec2fedb5423cfd902fb8348cc98e62/crates/blockifier/src/test_utils.rs#L400)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure I agree.
</blockquote></details>

This entire stack is to allow non-explicit construction of invoke transactions for testing, without knowing the tx version in advance.
That means: if a field is not passed explicitly, I would like the testing framework to *guess what I wanted* (not the rusty way to go in general, but for ease of testing I think this is a good compromise).
So, a default *valid* nonce value makes sense IMO. Same argument for the other fields

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/952)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/952#-NfkFLRAAjnyfVsmivAI:-NfkQZO27BhJbsmcop9h:b-odypqo) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

well... first off it's `(15 - 4) - 16` =  5 lines less :P 
second, I think it's cleaner; however, you are right about the extra boilerplate.
I don't want the nonce manager to be a field of the tx args though.
You have any ideas?

</blockquote></details>

Let's go with this for now and change if it's too painful in the future.

___

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/952#-:-NfkQe1G4Ex8syfmKmZO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/952)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Pull request merged**
