### PR TITLE
Use BigUint instead of felt pair

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1005)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Can you plz run the benchmark test before/after adding this? (bigint ops are no longer constant time I think)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1005#-:-Nh2HiWaDL4poaqnQkcj:bsxv3v5)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
```
     Running bench/blockifier_bench.rs (target/release/deps/blockifier_bench-452d9af635b0cca6)
Gnuplot not found, using plotters backend
transfers               time:   [617.31 µs 637.74 µs 658.36 µs]                      
```

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1005#-:-Nh6U01NE6pUB6i9CtS4:bo2bkqo)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
looks like a 10% perf hit... right?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1005#-:-Nh6UL2P5m5H5Llbilcs:bembo82)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by giladchase — COMMENTED** [review]
looks like it, for transfers at least.
The benchmark basically runs lots of transfers between a bunch of contracts.

It might not matter if this isn't hitting a bottleneck, but we should remember to check this out before we release a version , if tps changed

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1005#-:-Nh6X_T54d8dTzGImJPs:bfugzcm)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
Does the benchmark test measure time or number of ops...?
If the former, then how do I know I didn't have some CPU spike on my laptop that could cause this?
In any case maybe I'll just go with macros / some other boilerplate-reduction method instead of using BigUints

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1005#-:-Nh6m4J39_cd4GxTXmyz:bdjkd79)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by giladchase — COMMENTED** [review]
Measures time.
I tried running it myself and it's all over the place, not reliable even after changing the sample size.

Can be spikes, and I suspect also cache/compiler optimizations.
I'll TAL at it when I have a moment and try to tighten things up (perhaps using [criterion::black_box](https://docs.rs/criterion/latest/criterion/fn.black_box.html) will help?)

RE macros decision, the motivation for this change is purely boilerplate reduction?
I heard whispers about standardizing the field-element type across all repos, can you plz ask Elin if she knows when that happens? If that's true and happens soon, will that be consistent with this PR?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1005#-:-NhL5mjPAJkgjHlJQ_XM:b5g96v5)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by giladchase — COMMENTED** [review]
Well about my second point that not relevant now that I think about it, a different felt won't solve anything, ignore second point :grimacing: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1005#-:-NhLX101-Dxk_yO--izw:b-8iihpr)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request closed without merging**
