### PR TITLE
test(fee): add test to TransactionExecutionInfo n_events

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1565)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1565)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-NrAsSBBEZVSOpDI6Grf:-NrAsSBCANQKuJW5OXPx:b-md4i03) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a574d7e66e85d9513d43850d1005660abf2c3db/crates/blockifier/src/transaction/objects_test.rs#L10)):*
> ```XML
> use crate::transaction::objects::TransactionExecutionInfo;
> 
> fn default_call_info() -> CallInfo {
> ```

Please rename:
shared_call_info/test_call_info



_Code quote:_
```XML
default_call_info
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-NrAz8x_0WF4uiX0Z0Os:-NrAz8x_0WF4uiX0Z0Ot:brweb0z) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a574d7e66e85d9513d43850d1005660abf2c3db/crates/blockifier/src/transaction/objects_test.rs#L40)):*
> ```XML
>         ..default_call_info()
>     }
> }
> ```

Can you merge these two functions?



_Code quote:_
```XML
fn call_info_with_x_events(num_of_events: usize, num_of_inner_calls: usize) -> CallInfo {
    CallInfo {
        execution: CallExecution {
            events: (0..num_of_events).map(|_i| OrderedEvent::default()).collect(),
            ..Default::default()
        },
        inner_calls: (0..num_of_inner_calls).map(|_i| call_info_with_x_events(1, 0)).collect(),
        ..default_call_info()
    }
}

fn call_info_with_deep_inner_call() -> CallInfo {
    let inner_inner_call = call_info_with_x_events(0, 1);
    let inner_call = CallInfo { inner_calls: vec![inner_inner_call], ..default_call_info() };

    CallInfo {
        inner_calls: vec![inner_call],
        execution: CallExecution { events: vec![OrderedEvent::default()], ..Default::default() },
        ..default_call_info()
    }
}
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1565)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-NrAsSBBEZVSOpDI6Grf:-NrB-gjJDUoo4B5A1iV4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a574d7e66e85d9513d43850d1005660abf2c3db/crates/blockifier/src/transaction/objects_test.rs#L10)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please rename:
shared_call_info/test_call_info
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-NrAz8x_0WF4uiX0Z0Os:-NrF5DoS-Y1-X3HloGhw:b-qzvtq4) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a574d7e66e85d9513d43850d1005660abf2c3db/crates/blockifier/src/transaction/objects_test.rs#L40)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you merge these two functions?
</blockquote></details>

I tried to merge them, but it impacted readability

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1565)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-NrGWxHR3RdVKyn0Y9WL:-NrGWxHR3RdVKyn0Y9WM:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5060b28891bc21b315efbb08a7728bb423b2952a/crates/blockifier/src/transaction/objects_test.rs#L23)):*
> ```XML
>     CallInfo {
>         execution: CallExecution {
>             events: (0..num_of_events).map(|_i| OrderedEvent::default()).collect(),
> ```





_Suggestion:_
```XML
 events: (0..num_of_events).map(|_| OrderedEvent::default()).collect(),
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-NrGX-086tSoK-Ik7QaI:-NrGX-086tSoK-Ik7QaJ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5060b28891bc21b315efbb08a7728bb423b2952a/crates/blockifier/src/transaction/objects_test.rs#L26)):*
> ```XML
>             ..Default::default()
>         },
>         inner_calls: (0..num_of_inner_calls).map(|_i| call_info_with_x_events(1, 0)).collect(),
> ```





_Suggestion:_
```XML
inner_calls: (0..num_of_inner_calls).map(|_| call_info_with_x_events(1, 0)).collect(),
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-NrGXXgW6mXlA2-jLOPr:-NrGXXgW6mXlA2-jLOPs:b-vjghgk) ([raw file](https://github.com/starkware-libs/blockifier/blob/5060b28891bc21b315efbb08a7728bb423b2952a/crates/blockifier/src/transaction/objects_test.rs#L32)):*
> ```XML
> 
> fn call_info_with_deep_inner_call() -> CallInfo {
>     let inner_inner_call = call_info_with_x_events(0, 1);
> ```

Please add them as arguments



_Code quote:_
```XML
(0, 1
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1565)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-NrGXXgW6mXlA2-jLOPr:-Nr_HSWV9Ljr4FBrlq1n:b-xg03md) ([raw file](https://github.com/starkware-libs/blockifier/blob/5060b28891bc21b315efbb08a7728bb423b2952a/crates/blockifier/src/transaction/objects_test.rs#L32)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please add them as arguments
</blockquote></details>

I intentionally selected those options. otherwise, the CallInfo would become too complex.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1565)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-NrGXXgW6mXlA2-jLOPr:-Nr_gw9P2FXooELDO60O:b-j2qd75) ([raw file](https://github.com/starkware-libs/blockifier/blob/5060b28891bc21b315efbb08a7728bb423b2952a/crates/blockifier/src/transaction/objects_test.rs#L32)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I intentionally selected those options. otherwise, the CallInfo would become too complex.
</blockquote></details>

I believe you can define arguments for the function. In the test, you call `call_info_with_deep_inner_call(0, 1)` - passing the same arguments.
In this case, you are adding a generic function that can be used in different scenarios, and still, your test passes the same arguments.
WDYT?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1565)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-NrGXXgW6mXlA2-jLOPr:-Nr_vQF982SVfuiuUQ1i:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5060b28891bc21b315efbb08a7728bb423b2952a/crates/blockifier/src/transaction/objects_test.rs#L32)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I believe you can define arguments for the function. In the test, you call `call_info_with_deep_inner_call(0, 1)` - passing the same arguments.
In this case, you are adding a generic function that can be used in different scenarios, and still, your test passes the same arguments.
WDYT?
</blockquote></details>

Done.

**Review by MohammadNassar1 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-:-Nra-jCGA7hylA9lrWKN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 35 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-Nra-I8NEuikk1mbH2Xn:-Nra-I8NEuikk1mbH2Xo:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b547a594cc49c9de3ea89df1a82e4a17c87abc86/crates/blockifier/src/transaction/objects_test.rs#L35)):*
> ```XML
>     num_of_inner_calls: usize,
>     num_of_events_of_each_inner_call: usize,
>     num_of_calls_of_each_inner_call: usize,
> ```





_Suggestion:_
```XML
    n_events: usize,
    n_inner_calls: usize,
    n_events_of_each_inner_call: usize,
    n_inner_calls_of_each_inner_call: usize,
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1565#-:-Nrj4E3pDpIsyI7CH9Ma:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @OriStarkware)

**Pull request merged**
