### PR TITLE
chore: move get_tx_weights out of the Bouncer

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1940)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1940)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1940#-NzSzYO707w6HX0lqsB5:-NzSzYO707w6HX0lqsB6:bvg5y2v) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d74e3ade67d851c2a4370dea3341a3d81e4530e/crates/blockifier/src/bouncer.rs#L212)):*
> ```XML
>         // rather than the cumulative state attributes.
>         let state_changes_keys = tx_state_changes_keys.difference(&self.state_changes_keys);
>         let tx_executed_class_hashes = tx_execution_summary
> ```

incremental/marginal_executed_class_hashes



_Code quote:_
```XML
tx_executed_class_hashes
```
___
*[`crates/blockifier/src/bouncer.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1940#-NzSzeZzDa1GJv2JM_Fv:-NzSzeZzDa1GJv2JM_Fw:b-qdlqmt) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d74e3ade67d851c2a4370dea3341a3d81e4530e/crates/blockifier/src/bouncer.rs#L217)):*
> ```XML
>             .cloned()
>             .collect();
>         let tx_visited_storage_entries = tx_execution_summary
> ```

incremental/marginal_visited_storage_entries



_Code quote:_
```XML
tx_visited_storage_entries
```
___
*[`crates/blockifier/src/bouncer.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1940#-NzSzies23G8H48JU2xY:-NzSziet3Tddae6NE1fV:bvfuqd7) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d74e3ade67d851c2a4370dea3341a3d81e4530e/crates/blockifier/src/bouncer.rs#L220)):*
> ```XML
>             .visited_storage_entries
>             .difference(&self.visited_storage_entries)
>             .cloned()
> ```

why cloned?



_Code quote:_
```XML
.cloned()
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/bouncer.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1940#-NzT1oMv80UDauR3dPMy:-NzT1oMw3L_O8GSxFHr2:b-7edqrf) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d74e3ade67d851c2a4370dea3341a3d81e4530e/crates/blockifier/src/bouncer.rs#L211)):*
> ```XML
>         // The countings here should be linear in the transactional state changes and execution info
>         // rather than the cumulative state attributes.
>         let state_changes_keys = tx_state_changes_keys.difference(&self.state_changes_keys);
> ```

To be consistent with the other variable names in this test (all variables that only contain the new entries introduced by the tx).

Maybe use the word `new`/`newly` like it used to be in `get_casm_hash_calculation_resources` and `get_particia_update_resources` ?



_Suggestion:_
```XML
tx_state_changes_keys
```

**Review by avi-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1940)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1940)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1940#-NzSzYO707w6HX0lqsB5:-NzTHVNv5_UL-4SQvY4X:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d74e3ade67d851c2a4370dea3341a3d81e4530e/crates/blockifier/src/bouncer.rs#L212)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

incremental/marginal_executed_class_hashes
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1940#-NzSzeZzDa1GJv2JM_Fv:-NzTHVrw1L4WsvS-xrC-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d74e3ade67d851c2a4370dea3341a3d81e4530e/crates/blockifier/src/bouncer.rs#L217)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

incremental/marginal_visited_storage_entries
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1940#-NzSzies23G8H48JU2xY:-NzTAWiY9atr7QBIIZ7o:b1ypodi) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d74e3ade67d851c2a4370dea3341a3d81e4530e/crates/blockifier/src/bouncer.rs#L220)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why cloned?
</blockquote></details>

```
    /// Creates an iterator which [`clone`]s all of its elements.
    ///
    /// This is useful when you have an iterator over `&T`, but you need an
    /// iterator over `T`.
```

`difference` returns iterator over &ClassHash.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1940)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by avi-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1940)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1940#-:-NzTfH0F555QjAjapV86:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1940)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1940)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
