### PR TITLE
Deserialize os resources from file

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/360)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/360)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/360#-NRZKu6c3cPvaVzHjFEI:-NRZKu6c3cPvaVzHjFEJ:b-yjcii) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b54f14d9bc925928f1587e9e99573945609a3eb/crates/blockifier/Cargo.toml#L13)):*
> ```TOML
> [dependencies]
> cairo-felt = { git = "https://github.com/lambdaclass/cairo-rs.git", rev = "6e5340a" }
> cairo-vm = { git = "https://github.com/lambdaclass/cairo-rs.git", rev = "6e5340a" }
> ```

should I run some kind of update command instead of fixing a revision?



_Code quote:_
```TOML
cairo-felt = { git = "https://github.com/lambdaclass/cairo-rs.git", rev = "6e5340a" }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-rs.git", rev = "6e5340a" }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/360)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/360#-NRZL-AN2zcoA3soUQoP:-NRZL-AN2zcoA3soUQoQ:bg0iy70) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b54f14d9bc925928f1587e9e99573945609a3eb/crates/blockifier/src/execution/execution_utils.rs#L116)):*
> ```XML
>     implicit_args.push(MaybeRelocatable::from(initial_syscall_ptr));
>     implicit_args.extend(
>         vm.get_builtin_runners().iter().flat_map(|builtin_runner| builtin_runner.initial_stack()),
> ```

lambda function no longer expects a 2-tuple, now wants just the runner

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/360)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/os_resources.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/360#-NRZPRUd0UqsuiBG8bAA:-NRZPRUd0UqsuiBG8bAB:bvnmu56) ([raw file](https://github.com/starkware-libs/blockifier/blob/68ffe3a00b4df001ce05ccd1dc0222a95969d53e/crates/blockifier/src/fee/os_resources.json#L2)):*
> ```JSON
> {
>     "execute_syscalls": {
> ```

copied from `dev`, the `"deploy"` entry removed, and camel case converted to Pascal case (didn't know that's what ThisKindOfCasing is called but `ctrl+shift+P`ing it in VSCode gave this name)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/360)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/os_resources.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/360#-NRZPRUd0UqsuiBG8bAA:-NRcOYq3D6GtFnp76lQa:ben1m4i) ([raw file](https://github.com/starkware-libs/blockifier/blob/68ffe3a00b4df001ce05ccd1dc0222a95969d53e/crates/blockifier/src/fee/os_resources.json#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

copied from `dev`, the `"deploy"` entry removed, and camel case converted to Pascal case (didn't know that's what ThisKindOfCasing is called but `ctrl+shift+P`ing it in VSCode gave this name)
</blockquote></details>

also removed the `replace_class` entry

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/360#-:-NRcV0rQ2jEhDNgnYOBy:bnfp4nl)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

**Pull request merged**
