### PR TITLE
chore: clean pre_process_block

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1969)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1969)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/block.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-NziuRQK2YQ6edxVqm7f:-NziuRQK2YQ6edxVqm7g:b-xnlcya) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de3c4e54bce9c066ab96153effdfcc2dbe53c84/crates/blockifier/src/blockifier/block.rs#L68)):*
> ```XML
>     bouncer_config: BouncerConfig,
>     concurrency_mode: bool,
> ) -> StateResult<BlockContext> {
> ```

Moved out the creation of the BlockContext, which was completely trivial.

Next step is to move the pre-process call inside the tx executor.



_Code quote:_
```XML
    block_info: BlockInfo,
    chain_info: ChainInfo,
    versioned_constants: VersionedConstants,
    bouncer_config: BouncerConfig,
    concurrency_mode: bool,
) -> StateResult<BlockContext> {
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 523 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-NziuGVrAqVtBcwFvS1f:-NziuGVrAqVtBcwFvS1g:bj0qdg8) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de3c4e54bce9c066ab96153effdfcc2dbe53c84/crates/native_blockifier/src/py_block_executor.rs#L523)):*
> ```XML
>         },
>         use_kzg_da: block_info.use_kzg_da,
>     };
> ```

Moved to TryInto impl



_Code quote:_
```XML
    let block_info = BlockInfo {
        block_number: BlockNumber(block_info.block_number),
        block_timestamp: BlockTimestamp(block_info.block_timestamp),
        sequencer_address: ContractAddress::try_from(block_info.sequencer_address.0)?,
        gas_prices: GasPrices {
            eth_l1_gas_price: block_info.l1_gas_price.price_in_wei.try_into().map_err(|_| {
                NativeBlockifierInputError::InvalidNativeBlockifierInputError(
                    InvalidNativeBlockifierInputError::InvalidGasPriceWei(
                        block_info.l1_gas_price.price_in_wei,
                    ),
                )
            })?,
            strk_l1_gas_price: block_info.l1_gas_price.price_in_fri.try_into().map_err(|_| {
                NativeBlockifierInputError::InvalidNativeBlockifierInputError(
                    InvalidNativeBlockifierInputError::InvalidGasPriceFri(
                        block_info.l1_gas_price.price_in_fri,
                    ),
                )
            })?,
            eth_l1_data_gas_price: block_info.l1_data_gas_price.price_in_wei.try_into().map_err(
                |_| {
                    NativeBlockifierInputError::InvalidNativeBlockifierInputError(
                        InvalidNativeBlockifierInputError::InvalidDataGasPriceWei(
                            block_info.l1_data_gas_price.price_in_wei,
                        ),
                    )
                },
            )?,
            strk_l1_data_gas_price: block_info.l1_data_gas_price.price_in_fri.try_into().map_err(
                |_| {
                    NativeBlockifierInputError::InvalidNativeBlockifierInputError(
                        InvalidNativeBlockifierInputError::InvalidDataGasPriceFri(
                            block_info.l1_data_gas_price.price_in_fri,
                        ),
                    )
                },
            )?,
        },
        use_kzg_da: block_info.use_kzg_da,
    };
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 554 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-NziuKWg5bQGAw-L7n9A:-NziuKWg5bQGAw-L7n9B:b-cd2dtl) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de3c4e54bce9c066ab96153effdfcc2dbe53c84/crates/native_blockifier/src/py_block_executor.rs#L554)):*
> ```XML
> 
>     Ok(block_context)
> }
> ```

Not needed



_Code quote:_
```XML
// Executes block pre-processing; see `blockifier::blockifier::block::pre_process_block`
// documentation.
fn pre_process_block(
    state: &mut dyn State,
    old_block_number_and_hash: Option<(u64, PyFelt)>,
    general_config: &PyGeneralConfig,
    block_info: &PyBlockInfo,
    versioned_constants: &VersionedConstants,
    bouncer_config: BouncerConfig,
    concurrency_mode: bool,
) -> NativeBlockifierResult<BlockContext> {
    let old_block_number_and_hash = old_block_number_and_hash
        .map(|(block_number, block_hash)| BlockNumberHashPair::new(block_number, block_hash.0));

    let (block_info, chain_info) = into_block_context_args(general_config, block_info)?;
    let block_context = pre_process_block_blockifier(
        state,
        old_block_number_and_hash,
        block_info,
        chain_info,
        versioned_constants.clone(),
        bouncer_config,
        concurrency_mode,
    )?;

    Ok(block_context)
}
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1969)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/block_test.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-NzmlB914WEVUXSuP7iO:-NzmlB914WEVUXSuP7iP:braux98) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/blockifier/src/blockifier/block_test.rs#L38)):*
> ```XML
>     // block number interval.
>     let block_number = BlockNumber(constants::STORED_BLOCK_HASH_BUFFER - 1);
>     assert!(pre_process_block(&mut state, None, block_number,).is_ok());
> ```

why is rustfmt / clippy passing...?



_Code quote:_
```XML
block_number,)
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-Nzml_k90He12LKcVNrF:-Nzml_k90He12LKcVNrG:b49wy85) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/native_blockifier/src/py_block_executor.rs#L121)):*
> ```XML
>         bouncer_config: PyBouncerConfig,
>         concurrency_config: PyConcurrencyConfig,
>         // TODO(Yoni, 1/7/2024): pass chain_info instead.
> ```

What about versioned constants override data?



_Code quote:_
```XML
// TODO(Yoni, 1/7/2024): pass chain_info instead.
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-NzmllOCCG5s_bbSwHsS:-NzmllOCCG5s_bbSwHsT:b339ppu) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/native_blockifier/src/py_block_executor.rs#L177)):*
> ```XML
> 
>         let old_block_number_and_hash = old_block_number_and_hash
>             .map(|(block_number, block_hash)| BlockNumberHashPair::new(block_number, block_hash.0));
> ```

this looks like it belongs in the python-types-conversion area, there are similar parsing functions somewhere



_Code quote:_
```XML
        let old_block_number_and_hash = old_block_number_and_hash
            .map(|(block_number, block_hash)| BlockNumberHashPair::new(block_number, block_hash.0));
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 406 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-Nzmlspb2AMAUCbopjb0:-Nzmlspb2AMAUCbopjb1:b-65y8vk) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/native_blockifier/src/py_block_executor.rs#L406)):*
> ```XML
>                 .starknet_os_config
>                 .try_into()
>                 .expect("Failed to convert chain info."),
> ```

duplicated logic; move to function?



_Code quote:_
```XML
            chain_info: general_config
                .starknet_os_config
                .try_into()
                .expect("Failed to convert chain info."),
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-NzqvXajDv11qz3NPFaE:-NzqvXajDv11qz3NPFaF:bewpiv6) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/native_blockifier/src/py_validator.rs#L47)):*
> ```XML
>             general_config.starknet_os_config.try_into().expect("Failed to convert chain info."),
>             versioned_constants,
>             BouncerConfig::max(),
> ```

bouncer limits were previously not used in the block context...? why am I only seeing this input now?



_Code quote:_
```XML
BouncerConfig::max(),
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1969)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/block_test.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-NzmlB914WEVUXSuP7iO:-NzvpJM547tfXkYjnhhq:btn2brn) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/blockifier/src/blockifier/block_test.rs#L38)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is rustfmt / clippy passing...?
</blockquote></details>

Good Q
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-Nzml_k90He12LKcVNrF:-NzvkBXT5bph-VWz2oYK:b477rqh) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/native_blockifier/src/py_block_executor.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

What about versioned constants override data?
</blockquote></details>

Right, removing the TODO
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-NzmllOCCG5s_bbSwHsS:-NzvpMHG0Y0bo5MxR2Nz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/native_blockifier/src/py_block_executor.rs#L177)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this looks like it belongs in the python-types-conversion area, there are similar parsing functions somewhere
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 406 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-Nzmlspb2AMAUCbopjb0:-NzvlPFIBAXaNTp5niFG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/native_blockifier/src/py_block_executor.rs#L406)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

duplicated logic; move to function?
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-NzqvXajDv11qz3NPFaE:-NzvkbSI5hL0KEVApXo5:b8ch8tr) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/native_blockifier/src/py_validator.rs#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

bouncer limits were previously not used in the block context...? why am I only seeing this input now?
</blockquote></details>

`new_unchecked` set them to `max` by default

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1969)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-Nzml_k90He12LKcVNrF:-Nzw10vO5htZ-c9YbUVj:bvfmzwh) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/native_blockifier/src/py_block_executor.rs#L121)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Right, removing the TODO
</blockquote></details>

please do (TODO is still here)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1969)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-Nzml_k90He12LKcVNrF:-NzwAy5_60Hht2zFzKF9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cf39def1b5c005f2c9364957c02d3ba78eb7fbfa/crates/native_blockifier/src/py_block_executor.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please do (TODO is still here)
</blockquote></details>

Done.

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1969#-:-NzwKdC6BThVLsPcDxSg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1969)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
