### PR TITLE
Implement Casm hash calc. est. for Cairo0 class.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/556)

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/556)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/556#-NX4Ruk8A1AJLlK6NIo2:-NX4Ruk8A1AJLlK6NIo3:buxn1sp) ([raw file](https://github.com/starkware-libs/blockifier/blob/54eba015330e71b87affd0d35f5e32f2144baa19/crates/blockifier/src/execution/contract_class.rs#L88)):*
> ```XML
>     }
> 
>     pub fn estimate_casm_hash_computation_resources(&self) -> VmExecutionResources {
> ```

Do we call the deprecated class, casm?



_Code quote:_
```XML
casm
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/556)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/556#-NX4Tx7wBwpEo4ySABk8:-NX4Tx7wBwpEo4ySABk9:b3s21ly) ([raw file](https://github.com/starkware-libs/blockifier/blob/54eba015330e71b87affd0d35f5e32f2144baa19/crates/blockifier/src/execution/contract_class.rs#L86)):*
> ```XML
>     fn bytecode_length(&self) -> usize {
>         self.0.program.data.len()
>     }
> ```

Due to the `deref` above.



_Suggestion:_
```XML
    fn constructor_selector(&self) -> Option<EntryPointSelector> {
        Some(self.entry_points_by_type[&EntryPointType::Constructor].first()?.selector)
    }

    fn n_entry_points(&self) -> usize {
        self.entry_points_by_type.values().map(|vec| vec.len()).sum()
    }

    fn n_builtins(&self) -> usize {
        self.program.builtins.len()
    }

    fn bytecode_length(&self) -> usize {
        self.program.data.len()
    }
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/556)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/556#-NX4Tx7wBwpEo4ySABk8:-NX4q8RD4zSLby9hsvff:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/54eba015330e71b87affd0d35f5e32f2144baa19/crates/blockifier/src/execution/contract_class.rs#L86)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Due to the `deref` above.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/556#-NX4Ruk8A1AJLlK6NIo2:-NX4p45l7zymc4WkanDo:b-bke1dl) ([raw file](https://github.com/starkware-libs/blockifier/blob/54eba015330e71b87affd0d35f5e32f2144baa19/crates/blockifier/src/execution/contract_class.rs#L88)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we call the deprecated class, casm?
</blockquote></details>

Yes, it's still Cairo assembly. In fact, the new version goes through the same Casm repr. only because the current VM only supports this input.

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/556)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/556)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
