### PR TITLE
refactor(concurrency): use test_state instead of test_state_reader in…

### PR DESCRIPTION
**Pull request by OriStarkware**
… testing

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1943)

### CODE REVIEW

**Review by avi-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1943#-:-NzSwI-RAaZ1yvICEWeB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1943)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 374 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1943#-NzT1FlZ9HJnUb8e4uXm:-NzT1FlZ9HJnUb8e4uXn:b-sl6mbk) ([raw file](https://github.com/starkware-libs/blockifier/blob/b54fb18803450cf573c7ae964ed43d0b96b292a2/crates/blockifier/src/concurrency/worker_logic_test.rs#L374)):*
> ```XML
>     let chain_info = &block_context.chain_info;
>     let account_contract = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
>     let state_reader = test_state_reader(chain_info, BALANCE, &[(account_contract, 2)]);
> ```

Can you change the variable name to chached_state in all the relevant places?

**Review by meship-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1943)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 374 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1943#-NzT1FlZ9HJnUb8e4uXm:-NzT3YrQ0WANMNSpa3pq:b-mmi23w) ([raw file](https://github.com/starkware-libs/blockifier/blob/b54fb18803450cf573c7ae964ed43d0b96b292a2/crates/blockifier/src/concurrency/worker_logic_test.rs#L374)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Can you change the variable name to chached_state in all the relevant places?
</blockquote></details>

cached_state Sorry for the typo

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1943)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1943#-:-NzT9J8b1gAIWkciINZm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1943)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
