### PR TITLE
chore(concurrency): support fee token proxy pattern

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2057)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2057)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2057#-O1IsKf5CLYHCz_6BsV_:-O1IsKf67FGT-me3hk8H:b-oofou4) ([raw file](https://github.com/starkware-libs/blockifier/blob/32a8b202916801c02cf7a62c0022d1162d83fd09/crates/blockifier/src/concurrency/fee_utils.rs#L74)):*
> ```XML
> ) {
>     let storage_read_values = &mut fee_transfer_call_info.storage_read_values;
>     assert_eq!(storage_read_values.len(), 4, "Storage read values should have 4 elements");
> ```

Keep this assert + message
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2057#-O1IsPIo9bgEBAWn8NWd:-O1IsPIo9bgEBAWn8NWe:b-jzik7p) ([raw file](https://github.com/starkware-libs/blockifier/blob/306560c3b1e8e5e27dcd7a6a49eca1f01481b330/crates/blockifier/src/concurrency/fee_utils.rs#L78)):*
> ```XML
>     // Proxy pattern.
>     {
>         assert!(fee_transfer_call_info.inner_calls.len() == 1);
> ```

Add error message

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2057)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2057#-O1IsPIo9bgEBAWn8NWd:-O1KtdkHAkstfjjRNLK8:b-53xjo7) ([raw file](https://github.com/starkware-libs/blockifier/blob/306560c3b1e8e5e27dcd7a6a49eca1f01481b330/crates/blockifier/src/concurrency/fee_utils.rs#L78)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add error message
</blockquote></details>

(and use assert_eq)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2057)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2057)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2057#-O1IsKf5CLYHCz_6BsV_:-O1LDemQCf00EhQrOVW0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/32a8b202916801c02cf7a62c0022d1162d83fd09/crates/blockifier/src/concurrency/fee_utils.rs#L74)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Keep this assert + message
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2057#-O1IsPIo9bgEBAWn8NWd:-O1LDeL4CAmzmLh212Td:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/306560c3b1e8e5e27dcd7a6a49eca1f01481b330/crates/blockifier/src/concurrency/fee_utils.rs#L78)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(and use assert_eq)
</blockquote></details>

Done.

**Pull request merged**
