### PR TITLE
Add ` validate ` flag indicating if we want to run the validate entrypoint (used for simulation and fee estimation).

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785)* status: 0 of 7 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 431 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/785#-Na9CT4J4TK5zUvToYue:-Na9CT4J4TK5zUvToYuf:byeakap) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7404e1ddc40e0e0d072ea7f61549d621fc9d051/crates/blockifier/src/transaction/account_transaction.rs#L431)):*
> ```XML
>         }
> 
>         // V0 transactions do not have validation; we cannot deduct fee for execution.
> ```

@zuphitf - We do charge fee for (invoke)V0.
I think that for V0 we should have the same flow as for `validate=false`.
Another point to consider- remove the `overhead_steps` in case of `charge_fee=false`.



_Code quote:_
```XML
// V0 transactions do not have validation; we cannot deduct fee for execution.
```

**Review by alonh5 — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785#-:-NaAq8fCD0uNkZyedm6o:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 459 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/785#-NaAqNj_AooU3_gXjIly:-NaAqNj_AooU3_gXjIlz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7404e1ddc40e0e0d072ea7f61549d621fc9d051/crates/blockifier/src/transaction/account_transaction.rs#L459)):*
> ```XML
>             .execute_txs_inner()
>             .get(&self.tx_type())
>             .expect("OS_RESOURCES must contain all transaction types.")
> ```





_Suggestion:_
```XML
`OS_RESOURCES`
```
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/785#-NaAplt5DyDo8EfvUyx_:-NaAplt5DyDo8EfvUyxa:b1kkgzs) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7404e1ddc40e0e0d072ea7f61549d621fc9d051/crates/native_blockifier/src/py_transaction_executor.rs#L130)):*
> ```XML
>         let mut transactional_state = CachedState::create_transactional(&mut self.state);
>         let tx_execution_result = tx
>             .execute_raw(&mut transactional_state, &self.block_context, true, true)
> ```

Let's just put these `true`s into variables to clarify what they stand for.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 431 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/785#-Na9CT4J4TK5zUvToYue:-NaAyI1C62BtKfikYKnX:b-55qtzh) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7404e1ddc40e0e0d072ea7f61549d621fc9d051/crates/blockifier/src/transaction/account_transaction.rs#L431)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@zuphitf - We do charge fee for (invoke)V0.
I think that for V0 we should have the same flow as for `validate=false`.
Another point to consider- remove the `overhead_steps` in case of `charge_fee=false`.
</blockquote></details>

"we cannot deduct fee for execution" is misleading (cannot deduct fee for *reverted* execution).
This flow is just for all non-revertable txs

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 431 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/785#-Na9CT4J4TK5zUvToYue:-NaB24HiCWsi29CVb1bk:bkbidkm) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7404e1ddc40e0e0d072ea7f61549d621fc9d051/crates/blockifier/src/transaction/account_transaction.rs#L431)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

"we cannot deduct fee for execution" is misleading (cannot deduct fee for *reverted* execution).
This flow is just for all non-revertable txs
</blockquote></details>

So it has nothing to do with the fact that V0 transactions have no validation?
Is it just because we don't allow V0 transactions to be reverted?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/785#-NaAplt5DyDo8EfvUyx_:-NaB3vwB06lNp98E3RBL:b-7qmo62) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7404e1ddc40e0e0d072ea7f61549d621fc9d051/crates/native_blockifier/src/py_transaction_executor.rs#L130)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Let's just put these `true`s into variables to clarify what they stand for.
</blockquote></details>

Good point. Done

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 431 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/785#-Na9CT4J4TK5zUvToYue:-NaB4xGi8VVdXRJQc2-g:bj0lzvy) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7404e1ddc40e0e0d072ea7f61549d621fc9d051/crates/blockifier/src/transaction/account_transaction.rs#L431)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

So it has nothing to do with the fact that V0 transactions have no validation?
Is it just because we don't allow V0 transactions to be reverted?
</blockquote></details>

it is just because we don't allow V0 transactions to be reverted (which has everything to do with the fact that there is no validation on v0 txs :P)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 431 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/785#-Na9CT4J4TK5zUvToYue:-NaB69_W6CelXAQ04uYm:b-dsjnt5) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7404e1ddc40e0e0d072ea7f61549d621fc9d051/crates/blockifier/src/transaction/account_transaction.rs#L431)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it is just because we don't allow V0 transactions to be reverted (which has everything to do with the fact that there is no validation on v0 txs :P)
</blockquote></details>

As far as I know, invoke V0 has validation inside `__execute__` :)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 431 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/785#-Na9CT4J4TK5zUvToYue:-NaB7Gte6aTFbqqI5su8:b-npqx4n) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7404e1ddc40e0e0d072ea7f61549d621fc9d051/crates/blockifier/src/transaction/account_transaction.rs#L431)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

As far as I know, invoke V0 has validation inside `__execute__` :)
</blockquote></details>

so it can't be reverted... gotcha

**Review by alonh5 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/785)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
