### PR TITLE
Reconnect native_blockifier with blockifier and bump papyrus_storage

### PR DESCRIPTION
**Pull request by giladchase**
Added new new storage config options: they now have a separate storage
exclusively for large objects (memory mapped filed).

The config selected ensure (much) more than necessary space per object
(like a very large state diff or contract), and to compensate uses a
small dynamic growth step (if both the growth step and the max size will
be large then each growth step will hang for a bit until the malloc
completes).

Alternatively, the default configuration can be used, but it is a bit
less safe (but is probably fine).

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1099)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1099)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`crates/native_blockifier/src/storage.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1099#-NifaIVt2EUkkW_4ocxD:-NifaIVuD2p-pi2I5k96:b-ocyw5f) ([raw file](https://github.com/starkware-libs/blockifier/blob/2dcfb8ca1f0e8f123b03e63a5af4200b0ffe0d62/crates/native_blockifier/src/storage.rs#L46)):*
> ```XML
>             scope: papyrus_storage::StorageScope::FullArchive, // stores state diffs.
>             // BLOCKING TODO(Gilad): Figure out what this does.
>             mmap_file_config: papyrus_storage::mmap_file::MmapFileConfig::default(),
> ```

Blocking until we figure out what we need to set here.
Ditto with the scope config above but it's probably FullArchive since that's the one that has state-diffs?



_Code quote:_
```XML
            // BLOCKING TODO(Gilad): Figure out what this does.
            mmap_file_config: papyrus_storage::mmap_file::MmapFileConfig::default(),
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 9 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1099)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 216 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1099#-NiipYE_4-hfdXQjuC6N:-NiipYEa0_fBF1FYqTSW:b-i88v5m) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e9c4eea6310cc606d184718dcbcb118d711f27c/crates/native_blockifier/src/storage.rs#L216)):*
> ```XML
>             growth_step: 1 << 26, // 64MB
>         };
>         let storage_config = papyrus_storage::StorageConfig { db_config, ..Default::default() };
> ```

What other values are here? Are we sure they aren't critical?



_Code quote:_
```XML
Default::default()
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1099)* status: 2 of 12 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1099#-NifaIVt2EUkkW_4ocxD:-NijsRVw65j-zogz2-uy:b-6jeyzf) ([raw file](https://github.com/starkware-libs/blockifier/blob/2dcfb8ca1f0e8f123b03e63a5af4200b0ffe0d62/crates/native_blockifier/src/storage.rs#L46)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Blocking until we figure out what we need to set here.
Ditto with the scope config above but it's probably FullArchive since that's the one that has state-diffs?
</blockquote></details>

Unblocking since correct values and documentation were added
___
*[`crates/native_blockifier/src/storage.rs` line 216 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1099#-NiipYE_4-hfdXQjuC6N:-NijsZJN4Ym60kH1_gDd:b-bubbfy) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e9c4eea6310cc606d184718dcbcb118d711f27c/crates/native_blockifier/src/storage.rs#L216)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What other values are here? Are we sure they aren't critical?
</blockquote></details>

For `new_for_testing` defaults are fine.
The real values and documentation are explained at `new`.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1099#-:-NikAE400A3X68NDSjFg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
