### PR TITLE
refactor: make the BlockContext constructor private as preparation fo…

### PR DESCRIPTION
**Pull request by Yael-Starkware**
…r pre_process_block changes

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block_context.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpE8IAB4HDbg6_1o0Gu:-NpE8IAB4HDbg6_1o0Gv:bdn52w0) ([raw file](https://github.com/starkware-libs/blockifier/blob/7eda888c99d3e2e7dafe0b9357d96c690ed3ef0e/crates/blockifier/src/block_context.rs#L13)):*
> ```XML
> pub struct BlockContext {
>     pub(crate) block_info: BlockInfo,
>     pub chain_info: ChainInfo,
> ```

Why the visibility difference?



_Code quote:_
```XML
pub chain_info: ChainInfo
```
___
*[`crates/blockifier/src/block_context.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpE7wIW8Can_dXQFjQg:-NpE7wIW8Can_dXQFjQh:b-bndirn) ([raw file](https://github.com/starkware-libs/blockifier/blob/7eda888c99d3e2e7dafe0b9357d96c690ed3ef0e/crates/blockifier/src/block_context.rs#L128)):*
> ```XML
> }
> 
> impl Default for BlockContextArgs {
> ```

Can we simply derive default, or is `ChainId` the problem?



_Code quote:_
```XML
impl Default for BlockContextArgs
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 298 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpE8A3M4RmSeqK604yY:-NpE8A3M4RmSeqK604yZ:b-fjct5i) ([raw file](https://github.com/starkware-libs/blockifier/blob/7eda888c99d3e2e7dafe0b9357d96c690ed3ef0e/crates/native_blockifier/src/py_block_executor.rs#L298)):*
> ```XML
> }
> 
> pub fn into_block_context_args(
> ```

Is this the only usage of `BlockContextArgs`?
Not sure it justifies it's existence...



_Code quote:_
```XML
into_block_context_args
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_context.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpE8IAB4HDbg6_1o0Gu:-NpEEbH03WDUO2PlfTQA:b-71vfeo) ([raw file](https://github.com/starkware-libs/blockifier/blob/7eda888c99d3e2e7dafe0b9357d96c690ed3ef0e/crates/blockifier/src/block_context.rs#L13)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why the visibility difference?
</blockquote></details>

I remember I had a problem there, but now I don't see it anymore. 
So now it's the same, 
Done.
___
*[`crates/blockifier/src/block_context.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpE7wIW8Can_dXQFjQg:-NpED0-I0lwwPFtyVliI:b-w0z47l) ([raw file](https://github.com/starkware-libs/blockifier/blob/7eda888c99d3e2e7dafe0b9357d96c690ed3ef0e/crates/blockifier/src/block_context.rs#L128)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we simply derive default, or is `ChainId` the problem?
</blockquote></details>

yes exactly chain_id is the problem
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 298 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpE8A3M4RmSeqK604yY:-NpEEa4b-IUibWuwpU5O:b767qjv) ([raw file](https://github.com/starkware-libs/blockifier/blob/7eda888c99d3e2e7dafe0b9357d96c690ed3ef0e/crates/native_blockifier/src/py_block_executor.rs#L298)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the only usage of `BlockContextArgs`?
Not sure it justifies it's existence...
</blockquote></details>

Rust complier does not allow to pass so many arguments into a function.
It forces creating a struct.
this struct will be used also by full nodes when calling pre_process_block (in the next PR)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block_context.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpE7wIW8Can_dXQFjQg:-NpET_lTCVtxnl9lyp4E:b-wlnenb) ([raw file](https://github.com/starkware-libs/blockifier/blob/7eda888c99d3e2e7dafe0b9357d96c690ed3ef0e/crates/blockifier/src/block_context.rs#L128)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

yes exactly chain_id is the problem
</blockquote></details>

Can we do `..Default::deafult()` instead of writing all fields explicitly? What's the better practice?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_context.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpE7wIW8Can_dXQFjQg:-NpIqZSJ4rh6ighOHVv5:b-o2lzp7) ([raw file](https://github.com/starkware-libs/blockifier/blob/7eda888c99d3e2e7dafe0b9357d96c690ed3ef0e/crates/blockifier/src/block_context.rs#L128)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we do `..Default::deafult()` instead of writing all fields explicitly? What's the better practice?
</blockquote></details>

I checked, can't do this because it is recursive - it is trying to call the default function that I defined.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-:-NpJ6kWY4DIlYPQj7qig:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block_context.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpE7wIW8Can_dXQFjQg:-NpJ6jD1CFKGOKkVFYMr:b-7yvs6p) ([raw file](https://github.com/starkware-libs/blockifier/blob/7eda888c99d3e2e7dafe0b9357d96c690ed3ef0e/crates/blockifier/src/block_context.rs#L128)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I checked, can't do this because it is recursive - it is trying to call the default function that I defined.
</blockquote></details>

Thanks. :)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpJ6x_e1hg8nv1aCg3c:-NpJ6x_e1hg8nv1aCg3d:b-m2asqv) (no related file):*
Please open a corresponding Python PR.

___

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpJ6x_e1hg8nv1aCg3c:-NpJ9mSnDMv9O9jEkyxM:b-bn9wxu) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please open a corresponding Python PR.
</blockquote></details>

not sure what you mean, this change doesn't affect python

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpJ6x_e1hg8nv1aCg3c:-NpJAUnl0NZ03-jdHoFj:bq09ofm) (no related file):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure what you mean, this change doesn't affect python
</blockquote></details>

Why not? You're changing `native_blockifier` code. Need to open a PR in the main repo. and change the Blockifier commit hash.

___

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpJ6x_e1hg8nv1aCg3c:-NpK73VvAY1_CMo-RZnI:b-j5arlu) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not? You're changing `native_blockifier` code. Need to open a PR in the main repo. and change the Blockifier commit hash.
</blockquote></details>

https://github.com/starkware-industries/starkware/pull/33657

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1385#-NpODHCU0j3K1bkvTCCw:-NpODHCU0j3K1bkvTCCx:b-83ho35) (no related file):*
Rebase over `main-v0.13.1`?

___

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1385)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
