### PR TITLE
Update test_fail_deploy_account

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1274)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1274)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 502 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1274#-Nlsg_sU1bpDIe-Ds8MK:-Nlsg_sU1bpDIe-Ds8ML:b-za9265) ([raw file](https://github.com/starkware-libs/blockifier/blob/360dac1d2cbaf0fa1571f63fa9e3a3eeea1c06bc/crates/blockifier/src/transaction/account_transactions_test.rs#L502)):*
> ```XML
>         deployed_account_address,
>         ContractAddressSalt::default(),
>     );
> ```

Wait - isn't this test just wrong?
The address of the deployer is not  `deployed_account_address` - it is calculated during the deployment process. 

Using `create_account_tx_for_validate_test` is misleading here. 



_Code quote:_
```XML
    let deploy_account_tx = create_account_tx_for_validate_test(
        TransactionType::DeployAccount,
        INVALID,
        None,
        &mut NonceManager::default(),
        faulty_account_feature_contract,
        deployed_account_address,
        ContractAddressSalt::default(),
    );
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1274)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 489 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1274#-Nlw8s_H3zL7VydPKMrk:-Nlw8s_H3zL7VydPKMrl:bkzckhx) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4ba2375321f11f0b6cc6a29e079b9daabb60ba7/crates/blockifier/src/transaction/account_transactions_test.rs#L489)):*
> ```XML
>     #[values(CairoVersion::Cairo0, CairoVersion::Cairo1)] cairo_version: CairoVersion,
> ) {
>     let mut state = create_state_with_falliable_validation_account();
> ```

Previously, we only tested cairo0, no? Since it was the only contract that was declared.



_Code quote:_
```XML
    let mut state = create_state_with_falliable_validation_account();
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 491 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1274#-Nlvo-hc7OUz2EmwXQrN:-Nlvo-hdBVH-5dUjqIxM:b-fc8d81) ([raw file](https://github.com/starkware-libs/blockifier/blob/360dac1d2cbaf0fa1571f63fa9e3a3eeea1c06bc/crates/blockifier/src/transaction/account_transactions_test.rs#L491)):*
> ```XML
>     let faulty_account_feature_contract = FeatureContract::FaultyAccount(cairo_version);
>     let deployed_account_address = faulty_account_feature_contract.get_instance_address(0);
>     let state = &mut test_state(&block_context, BALANCE, &[(faulty_account_feature_contract, 1)]);
> ```

The initial balance is set to `2*BALANCE` in `create_state_with_falliable_validation_account`. I'm not sure if it matters.
Why do we need to deploy the faulty contract?



_Suggestion:_
```XML
   let state = &mut test_state(&block_context, BALANCE, &[(faulty_account_feature_contract, 0)]);
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 491 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1274#-Nlvo-hc7OUz2EmwXQrN:-NlwBSwHBVAW-DdqYYO_:b-oogqbs) ([raw file](https://github.com/starkware-libs/blockifier/blob/360dac1d2cbaf0fa1571f63fa9e3a3eeea1c06bc/crates/blockifier/src/transaction/account_transactions_test.rs#L491)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The initial balance is set to `2*BALANCE` in `create_state_with_falliable_validation_account`. I'm not sure if it matters.
Why do we need to deploy the faulty contract?
</blockquote></details>

Done. PTAL: #1277.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
This PR is replaced with #1277 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1274#-:-Nm-tkJq2YIZCYy9gK-X:bn7bwfv)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 502 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1274#-Nlsg_sU1bpDIe-Ds8MK:-Nm-tgbk2EiPK_xU72In:bn7bwfv) ([raw file](https://github.com/starkware-libs/blockifier/blob/360dac1d2cbaf0fa1571f63fa9e3a3eeea1c06bc/crates/blockifier/src/transaction/account_transactions_test.rs#L502)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Wait - isn't this test just wrong?
The address of the deployer is not  `deployed_account_address` - it is calculated during the deployment process. 

Using `create_account_tx_for_validate_test` is misleading here.
</blockquote></details>

This PR is replaced with #1277

**Pull request closed without merging**
