### PR TITLE
Update test_declare_tx

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1276)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1276)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1038 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1276#-Nm0EJjyANWAGQEDEBmA:-Nm0EJjyANWAGQEDEBmB:b7jcaye) ([raw file](https://github.com/starkware-libs/blockifier/blob/278582e5149d9118d2780ab60ec764e3c31213c9/crates/blockifier/src/transaction/transactions_test.rs#L1038)):*
> ```XML
>     #[case] tx_version: TransactionVersion,
>     #[case] empty_contract_version: CairoVersion,
> ) {
> ```

This is so much better.



_Code quote:_
```XML
#[rstest]
#[case(TransactionVersion::ZERO, CairoVersion::Cairo0)]
#[case(TransactionVersion::ONE, CairoVersion::Cairo0)]
#[case(TransactionVersion::TWO, CairoVersion::Cairo1)]
#[case(TransactionVersion::THREE, CairoVersion::Cairo1)]
fn test_declare_tx(
    #[values(CairoVersion::Cairo0, CairoVersion::Cairo1)] account_version: CairoVersion,
    #[case] tx_version: TransactionVersion,
    #[case] empty_contract_version: CairoVersion,
) {
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1045 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1276#-Nm0CqWrE_shKYGGG_8q:-Nm0CqWrE_shKYGGG_8r:b8ob761) ([raw file](https://github.com/starkware-libs/blockifier/blob/278582e5149d9118d2780ab60ec764e3c31213c9/crates/blockifier/src/transaction/transactions_test.rs#L1045)):*
> ```XML
>     let class_hash = empty_contract.get_class_hash();
>     let sender_address = account.get_instance_address(0);
>     let contract_class = empty_contract.get_class();
> ```

Group variables that come from the same feature contract together. 



_Suggestion:_
```XML
    let class_hash = empty_contract.get_class_hash();
    let contract_class = empty_contract.get_class();
    let sender_address = account.get_instance_address(0);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1070 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1276#-Nm0C3kE9fzGB8S8KeHn:-Nm0C3kFCbcAKURLobFZ:b-txc6di) ([raw file](https://github.com/starkware-libs/blockifier/blob/278582e5149d9118d2780ab60ec764e3c31213c9/crates/blockifier/src/transaction/transactions_test.rs#L1070)):*
> ```XML
>     let expected_validate_call_info = declare_validate_callinfo(
>         tx_version,
>         account_version,
> ```

Non-blocking - as I don't like my suggestion either....



_Suggestion:_
```XML
       cairo_version_of_account,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1096 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1276#-Nm0E-S1CeonkRby0DN9:-Nm0E-S24fzZC8ruDBVk:bvnqo4j) ([raw file](https://github.com/starkware-libs/blockifier/blob/278582e5149d9118d2780ab60ec764e3c31213c9/crates/blockifier/src/transaction/transactions_test.rs#L1096)):*
> ```XML
>                 CairoVersion::Cairo0 => 57,
>                 CairoVersion::Cairo1 => 59,
>             },
> ```

@noaov1 - What do you think?
Another related thread: https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcApvkCHfEX2TowrGR



_Code quote:_
```XML
        VmExecutionResources {
            n_steps: match account_version {
                CairoVersion::Cairo0 => 529,
                CairoVersion::Cairo1 => 525,
            },
            n_memory_holes: match account_version {
                CairoVersion::Cairo0 => 57,
                CairoVersion::Cairo1 => 59,
            },
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1276)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1038 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1276#-Nm0EJjyANWAGQEDEBmA:-Nm0GuR_7cz9JO9IbnKe:b-lgvfbx) ([raw file](https://github.com/starkware-libs/blockifier/blob/278582e5149d9118d2780ab60ec764e3c31213c9/crates/blockifier/src/transaction/transactions_test.rs#L1038)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is so much better.
</blockquote></details>

only because cairo version is now coupled with tx version
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1096 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1276#-Nm0E-S1CeonkRby0DN9:-Nm0HBTL71TG_KfpEvFh:b-msaoeu) ([raw file](https://github.com/starkware-libs/blockifier/blob/278582e5149d9118d2780ab60ec764e3c31213c9/crates/blockifier/src/transaction/transactions_test.rs#L1096)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@noaov1 - What do you think?
Another related thread: https://reviewable.io/reviews/starkware-libs/blockifier/1260#-NlcApvkCHfEX2TowrGR
</blockquote></details>

will be fixed [here](https://reviewable.io/reviews/starkware-libs/blockifier/1265)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1276#-:-Nm0K57S-E9eayiBXtY5:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @MohammadNassar1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1276)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
