### PR TITLE
invoke_tx_args macro

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/953)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/953)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/953#-NfXEKbkBqOGo6w5yhQ9:-NfXEKbkBqOGo6w5yhQA:b-37bib8) (no related file):*
For tests to pass, `DEFAULT_STRK_L1_GAS_PRICE` needs to be non-zero...

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/953)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 435 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/953#-Nfe9GgL29D0jxnCCzzK:-Nfe9GgL29D0jxnCCzzL:bnwuw7v) ([raw file](https://github.com/starkware-libs/blockifier/blob/3be74c852752c1deb82cbe22e55da2eedb92d5ad/crates/blockifier/src/test_utils.rs#L435)):*
> ```XML
>                 $($field $(: $value)?,)*
>                 ..Default::default()
>             };
> ```

Need to
1. Remove the `__execute__` selector from the implementation of `Default`
2. check if tx version is zero and the selector is no explicitly passed; if so, add the selector

@noaov1 re. your comment from [this PR](https://reviewable.io/reviews/starkware-libs/blockifier/938)

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/953)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/953#-NfXEKbkBqOGo6w5yhQ9:-NfkGFp93Wd5PqU19sg4:b-bdkejh) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

For tests to pass, `DEFAULT_STRK_L1_GAS_PRICE` needs to be non-zero...
</blockquote></details>

We should make it `1`, right?

___
___
*[`crates/blockifier/src/test_utils.rs` line 436 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/953#-NfkG9cH-aMC-Xgek6FR:-NfkG9cH-aMC-Xgek6FS:bxvcvj1) ([raw file](https://github.com/starkware-libs/blockifier/blob/3be74c852752c1deb82cbe22e55da2eedb92d5ad/crates/blockifier/src/test_utils.rs#L436)):*
> ```XML
>                 ..Default::default()
>             };
>             // If resource bounds aren't explicitly passed, derive them from max_fee.
> ```

Isn't this supposed to happen only for V3?



_Suggestion:_
```XML
// If resource bounds aren't explicitly passed, derive them from max fee.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 725 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/953#-NfkFsKa38NrawzoP7wf:-NfkFsKa38NrawzoP7wg:b-xh28ql) ([raw file](https://github.com/starkware-libs/blockifier/blob/3be74c852752c1deb82cbe22e55da2eedb92d5ad/crates/blockifier/src/transaction/account_transactions_test.rs#L725)):*
> ```XML
>     ];
> 
>     // First invocation of `with_arg` gets the exact pre-calculated actual fee as max_fee.
> ```

Remove blank lines?

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/953)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/953)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/953#-NfXEKbkBqOGo6w5yhQ9:-NfkRkrpEDZ4dc6un4PV:b7s1top) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We should make it `1`, right?
</blockquote></details>

done in previous PR

___

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/953)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/953)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 436 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/953#-NfkG9cH-aMC-Xgek6FR:-NfkRtDJCFmjtZdIEG5D:bgl1rnp) ([raw file](https://github.com/starkware-libs/blockifier/blob/3be74c852752c1deb82cbe22e55da2eedb92d5ad/crates/blockifier/src/test_utils.rs#L436)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't this supposed to happen only for V3?
</blockquote></details>

I can check if tx version is at least 3 as another condition in the `if`, would you prefer that?

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/953)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 436 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/953#-NfkG9cH-aMC-Xgek6FR:-NfpsiMo6H4Zy0RqfXw6:b-svnaoc) ([raw file](https://github.com/starkware-libs/blockifier/blob/3be74c852752c1deb82cbe22e55da2eedb92d5ad/crates/blockifier/src/test_utils.rs#L436)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I can check if tx version is at least 3 as another condition in the `if`, would you prefer that?
</blockquote></details>

In documentation: avoid using variable names, try to stick to behavioral description (if you have to, use backticks). Otherwise, you have false-positives when searching the code.

**Pull request merged**
