### PR TITLE
test: remove the test util trivial_external_entry_point

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1605)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1605)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @MohammadNassar1, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils.rs` line 181 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1605#-Nrt_-LH1PDAx2Kk-4Wh:-Nrt_-LH1PDAx2Kk-4Wi:bum0nl8) ([raw file](https://github.com/starkware-libs/blockifier/blob/8c91963b777004ff5b3c31dc044a50fc96e5b3ea/crates/blockifier/src/test_utils.rs#L181)):*
> ```XML
> }
> 
> pub fn get_deprecated_contract_class(contract_path: &str) -> DeprecatedContractClass {
> ```

1. why the split in this PR? can't see usage
2. this function is only used in papyrus_state_test, once; will you be deleting this function later (by updating the papyrus test to new infra)?



_Code quote:_
```XML
get_deprecated_contract_class
```
___
*[`crates/native_blockifier/src/state_readers/papyrus_state_test.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1605#-Nrt_iq1DnsKdipBjFIO:-Nrt_iq1DnsKdipBjFIP:b7defxl) ([raw file](https://github.com/starkware-libs/blockifier/blob/8c91963b777004ff5b3c31dc044a50fc96e5b3ea/crates/native_blockifier/src/state_readers/papyrus_state_test.rs#L33)):*
> ```XML
> 
>     let contract_class =
>         get_deprecated_contract_class_from_str(test_contract.get_raw_class().as_str());
> ```

I think this logic should be a method of the `FeatureContract` enum.
If there is no common enum type containing DeprecatedContractClass and ContractClass, the method can assert the correct cairo version (it's a test util).



_Code quote:_
```XML
get_deprecated_contract_class_from_str(test_contract.get_raw_class().as_str())
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1605)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils.rs` line 181 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1605#-Nrt_-LH1PDAx2Kk-4Wh:-NrukGjgCOr3vRdMXelU:b-5hwqoa) ([raw file](https://github.com/starkware-libs/blockifier/blob/8c91963b777004ff5b3c31dc044a50fc96e5b3ea/crates/blockifier/src/test_utils.rs#L181)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. why the split in this PR? can't see usage
2. this function is only used in papyrus_state_test, once; will you be deleting this function later (by updating the papyrus test to new infra)?
</blockquote></details>

1. I am not sure I understand what you are saying. This PR is self-contained.
2. Done. 
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 151 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1605#-NrusBpU71Ieuc0nyqif:-NrusBpU71Ieuc0nyqig:b-t1qhx9) ([raw file](https://github.com/starkware-libs/blockifier/blob/296f749bfa5e6623b5e179a61e052fdb8e2a1a2f/crates/blockifier/src/test_utils/contracts.rs#L151)):*
> ```XML
>             matches!(self.cairo_version(), CairoVersion::Cairo0),
>             "DeprecatedContractClass is supported for Cairo0 contracts only."
>         );
> ```

Are we sure we are making the correct assertion?



_Code quote:_
```XML
        assert!(
            matches!(self.cairo_version(), CairoVersion::Cairo0),
            "DeprecatedContractClass is supported for Cairo0 contracts only."
        );
```
___
*[`crates/native_blockifier/src/state_readers/papyrus_state_test.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1605#-Nrt_iq1DnsKdipBjFIO:-NruopU7CBG0hPBqTX5l:bxfpz9k) ([raw file](https://github.com/starkware-libs/blockifier/blob/8c91963b777004ff5b3c31dc044a50fc96e5b3ea/crates/native_blockifier/src/state_readers/papyrus_state_test.rs#L33)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think this logic should be a method of the `FeatureContract` enum.
If there is no common enum type containing DeprecatedContractClass and ContractClass, the method can assert the correct cairo version (it's a test util).
</blockquote></details>

Done. I think... I did not go much into `DeprecatedContractClass`. I could not easily convert `ContractClass` to `DeprecatedContractClass`.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1605)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @MohammadNassar1, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 151 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1605#-NrusBpU71Ieuc0nyqif:-NrvKGIK8P3jMXkeL60B:b-cwg1os) ([raw file](https://github.com/starkware-libs/blockifier/blob/296f749bfa5e6623b5e179a61e052fdb8e2a1a2f/crates/blockifier/src/test_utils/contracts.rs#L151)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Are we sure we are making the correct assertion?
</blockquote></details>

no; maybe replace the `unwrap` with an `expect` in the `from_value`? at what point is the object converted to DeprecatedContractClass?

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils/contracts.rs` line 151 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1605#-NrusBpU71Ieuc0nyqif:-Nrw-Gvn5LKLMevB0BpL:b3nymni) ([raw file](https://github.com/starkware-libs/blockifier/blob/296f749bfa5e6623b5e179a61e052fdb8e2a1a2f/crates/blockifier/src/test_utils/contracts.rs#L151)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no; maybe replace the `unwrap` with an `expect` in the `from_value`? at what point is the object converted to DeprecatedContractClass?
</blockquote></details>

Done.

I think you are correct - and this is where we stop playing with `serde_json` and convert to `DeprecatedContractClass`.

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1605#-:-NryI7Eb8B1VV9WXR8Xi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1605)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @TzahiTaub)

**Pull request merged**
