### PR TITLE
Add sierra_types.rs with SierraU128 and Sierra initial implementation (from_memory).

### PR DESCRIPTION
**Pull request by barak-b-starkware**
- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/854)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/cairo_types.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/854#-NcqlN_j2QYcMnQME2-j:-NcqlN_j2QYcMnQME2-k:b-dik711) ([raw file](https://github.com/starkware-libs/blockifier/blob/7971d9f4946e130dcdef41b8c06b45f91d9005b6/crates/blockifier/src/abi/cairo_types.rs#L11)):*
> ```XML
> #[derive(Debug, Error)]
> pub enum CairoTypeError {
>     #[error("Felt {0:?} is too big to convert to {1:?}.")]
> ```

why '?`



_Suggestion:_
```XML
{}
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/cairo_types.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/854#-NcqlT4G3RcnRaHPm5OQ:-NcqlT4G3RcnRaHPm5OR:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7971d9f4946e130dcdef41b8c06b45f91d9005b6/crates/blockifier/src/abi/cairo_types.rs#L12)):*
> ```XML
> pub enum CairoTypeError {
>     #[error("Felt {0:?} is too big to convert to {1:?}.")]
>     ValueTooLargeForType(Felt252, &'static str),
> ```





_Suggestion:_
```XML
  ValueTooLargeForType{value: Felt252, ty: &'static str},
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/cairo_types.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/854#-NcqlXef2WuU6GAH4qeg:-NcqlXef2WuU6GAH4qeh:byqb2v5) ([raw file](https://github.com/starkware-libs/blockifier/blob/7971d9f4946e130dcdef41b8c06b45f91d9005b6/crates/blockifier/src/abi/cairo_types.rs#L33)):*
> ```XML
> }
> 
> impl CairoType for CairoU128 {
> ```

@giladchase  suggested removing the `CairoU128` type if we have a trait.



_Suggestion:_
```XML
impl CairoType for u128 {
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/854)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/abi/cairo_types.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/854#-NcqlfDcBj12SKclX07j:-NcqlfDcBj12SKclX07k:b-9a1r7y) ([raw file](https://github.com/starkware-libs/blockifier/blob/7971d9f4946e130dcdef41b8c06b45f91d9005b6/crates/blockifier/src/abi/cairo_types.rs#L34)):*
> ```XML
> 
> impl CairoType for CairoU128 {
>     fn from_memory(vm: &VirtualMachine, ptr: &mut Relocatable) -> Result<Self, CairoTypeError> {
> ```

can you use it somewhere?



_Code quote:_
```XML
 fn from_memory(vm: &VirtualMachine, ptr: &mut Relocatable) -> Result<Self, CairoTypeError> {
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/854)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @giladchase and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/abi/cairo_types.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/854#-NcqlN_j2QYcMnQME2-j:-NcrRl74BfQSfBxxoZnj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7971d9f4946e130dcdef41b8c06b45f91d9005b6/crates/blockifier/src/abi/cairo_types.rs#L11)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why '?`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/abi/cairo_types.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/854#-NcqlT4G3RcnRaHPm5OQ:-NcrRmN_5nFMT72WL0q2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7971d9f4946e130dcdef41b8c06b45f91d9005b6/crates/blockifier/src/abi/cairo_types.rs#L12)):*
> ```XML
> pub enum CairoTypeError {
>     #[error("Felt {0:?} is too big to convert to {1:?}.")]
>     ValueTooLargeForType(Felt252, &'static str),
> ```

Done.
___
*[`crates/blockifier/src/abi/cairo_types.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/854#-NcqlXef2WuU6GAH4qeg:-NcrRomu7RHdKwlpJMvx:b-xozgbc) ([raw file](https://github.com/starkware-libs/blockifier/blob/7971d9f4946e130dcdef41b8c06b45f91d9005b6/crates/blockifier/src/abi/cairo_types.rs#L33)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

@giladchase  suggested removing the `CairoU128` type if we have a trait.
</blockquote></details>

Done. As discussed. `SierraU128`
___
*[`crates/blockifier/src/abi/cairo_types.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/854#-NcqlfDcBj12SKclX07j:-NcrRtMYDVs6ZEC7ltnK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7971d9f4946e130dcdef41b8c06b45f91d9005b6/crates/blockifier/src/abi/cairo_types.rs#L34)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you use it somewhere?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/abi_utils_test.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/854#-Ncus-4x2HI6KtQJVg5-:-Ncus-4x2HI6KtQJVg50:btvkmgk) ([raw file](https://github.com/starkware-libs/blockifier/blob/e49bd8e7714d7f7738f81f7c69ae5d6d4a7aadd1/crates/blockifier/src/abi/abi_utils_test.rs#L53)):*
> ```XML
>     let overflowed_u128: BigUint = BigUint::from(1_u8) << 128;
>     let overflowed_u128_as_felt = Felt252::from(overflowed_u128);
>     let error = felt_to_u128(&overflowed_u128_as_felt).unwrap_err();
> ```

can you add an assert to show me how the error is formatted?



_Code quote:_
```XML
error
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
can you fix the commit message and PR name?

> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/854#-:-NcusZ72CuVBukSYi6cZ:b-gv2lzj)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @giladchase)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/sierra_types.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/854#-NcusvSK6THH5_7QK5QA:-NcusvSK6THH5_7QK5QB:b312rgg) ([raw file](https://github.com/starkware-libs/blockifier/blob/e49bd8e7714d7f7738f81f7c69ae5d6d4a7aadd1/crates/blockifier/src/abi/sierra_types.rs#L64)):*
> ```XML
> impl SierraType for SierraU256 {
>     fn from_memory(vm: &VirtualMachine, ptr: &mut Relocatable) -> Result<Self, SierraTypeError> {
>         let low_val_as_felt = vm.get_integer(*ptr)?;
> ```

use  SierraU128::from_memory



_Code quote:_
```XML
  let low_val_as_felt = vm.get_integer(*ptr)?;
```

**Review by barak-b-starkware — COMMENTED** [review]
I've already changed the commit msg. WDYM by changing the PR name? in GitHub? (Changed)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/854#-:-Ncut0kS4ZAeqMdhP6Tk:bymdpqj)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @giladchase and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/abi/abi_utils_test.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/854#-Ncus-4x2HI6KtQJVg5-:-Ncuu2ev3c2mWZC4Xg93:b7qr731) ([raw file](https://github.com/starkware-libs/blockifier/blob/e49bd8e7714d7f7738f81f7c69ae5d6d4a7aadd1/crates/blockifier/src/abi/abi_utils_test.rs#L53)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you add an assert to show me how the error is formatted?
</blockquote></details>

Done. I’ve added `+ Felt252::from(1_u8)` at the end:
It prints:
```
panicked at 'assertion failed: `ValueTooLargeForType { val: 340282366920938463463374607431768211456, ty: "u128" }` does not match `SierraTypeError::ValueTooLargeForType { val: expected_val, ty: "u128" } if
expected_val == (overflowed_u128_as_felt + Felt252::from(1_u8))`'
```
BTW, it prints the exact same error msg (w/ the same `"`) when I replace the `{val}` with `{val:?}` and `{ty}` with `{ty:?}`.
___
*[`crates/blockifier/src/abi/sierra_types.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/854#-NcusvSK6THH5_7QK5QA:-Ncuvvj166crrCamB_gG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e49bd8e7714d7f7738f81f7c69ae5d6d4a7aadd1/crates/blockifier/src/abi/sierra_types.rs#L64)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

use  SierraU128::from_memory
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/abi_utils_test.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/854#-Ncus-4x2HI6KtQJVg5-:-Ncuyh_FD0rs5cfj41Mt:b95ud4b) ([raw file](https://github.com/starkware-libs/blockifier/blob/e49bd8e7714d7f7738f81f7c69ae5d6d4a7aadd1/crates/blockifier/src/abi/abi_utils_test.rs#L53)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done. I’ve added `+ Felt252::from(1_u8)` at the end:
It prints:
```
panicked at 'assertion failed: `ValueTooLargeForType { val: 340282366920938463463374607431768211456, ty: "u128" }` does not match `SierraTypeError::ValueTooLargeForType { val: expected_val, ty: "u128" } if
expected_val == (overflowed_u128_as_felt + Felt252::from(1_u8))`'
```
BTW, it prints the exact same error msg (w/ the same `"`) when I replace the `{val}` with `{val:?}` and `{ty}` with `{ty:?}`.
</blockquote></details>

it is because the assert prints the error.

notice that your error string is not in the message above.

assert\_eq!(format!("{error}", "")

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/sierra_types.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/854#-Ncuz8PG3vpAcuG9KtXh:-Ncuz8PG3vpAcuG9KtXi:b56vs6h) ([raw file](https://github.com/starkware-libs/blockifier/blob/1008b4ffc6269b003c87fbbc8eee0476302e720b/crates/blockifier/src/abi/sierra_types.rs#L71)):*
> ```XML
>     fn from_memory(vm: &VirtualMachine, ptr: &mut Relocatable) -> Result<Self, SierraTypeError> {
>         let low_val = SierraU128::from_memory(vm, ptr)?.as_value();
>         *ptr = (*ptr + 1)?;
> ```

this is already done by `SierraU128::from_memory`, right?



_Code quote:_
```XML
*ptr = (*ptr + 1)?;
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/854)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @giladchase and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/abi/abi_utils_test.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/854#-Ncus-4x2HI6KtQJVg5-:-NcvQ7gZ8szPeRxxRzQF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e49bd8e7714d7f7738f81f7c69ae5d6d4a7aadd1/crates/blockifier/src/abi/abi_utils_test.rs#L53)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is because the assert prints the error.

notice that your error string is not in the message above.

assert\_eq!(format!("{error}", "")
</blockquote></details>

Done.
___
*[`crates/blockifier/src/abi/sierra_types.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/854#-Ncuz8PG3vpAcuG9KtXh:-NcvHySf9ikrso53A6wC:b-aq0eqz) ([raw file](https://github.com/starkware-libs/blockifier/blob/1008b4ffc6269b003c87fbbc8eee0476302e720b/crates/blockifier/src/abi/sierra_types.rs#L71)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this is already done by `SierraU128::from_memory`, right?
</blockquote></details>

Done.
Right (: removed.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/854#-:-NcvdaFLDwrbhryf7ec-:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @giladchase)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
