### PR TITLE
feat(concurrency, state): add declared_contract hashmap to StateCache

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)

### CODE REVIEW

**Comment by barak-b-starkware** [comment]
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv0kxCg20Z9ZJDYiVQD):*




_Suggestion:_
```
feat(concurrency, state): add contract_class hashmap to StateCache
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv0kxCg20Z9ZJDYiVQD):*
Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv0OerRCAZzAVyLaR-Z:-NvRQ1ypC2qbnB6Ya7Se:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3ed5e8098be5ed56f55623d15b89715110df8b6/crates/blockifier/src/state/cached_state.rs#L74)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove.
This change is not considered a state diff.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv0_X990dXxn51NYG2B:-NvRQRZIEVA-wnd5z84X:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3ed5e8098be5ed56f55623d15b89715110df8b6/crates/blockifier/src/state/cached_state.rs#L258)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe there is a better way to "catch" and error and re-throw it
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 400 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv6EpTj2wwkTD0AnPmJ:-NvRbluYEKaq-5C1eUPk:b-u8qjoi) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3ed5e8098be5ed56f55623d15b89715110df8b6/crates/blockifier/src/state/cached_state.rs#L400)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

`declared_contract_initial_values: HashMap<ClassHash, bool>,`
</blockquote></details>

I think `declared_contracts_initial_values`is better.
___
*[`crates/blockifier/src/state/cached_state.rs` line 407 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvB5Lio99mNpeUNmHFt:-NvRbrliDGBuxGOh99Ap:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3ed5e8098be5ed56f55623d15b89715110df8b6/crates/blockifier/src/state/cached_state.rs#L407)):*
> ```XML
>     pub(crate) storage_writes: HashMap<StorageEntry, StarkFelt>,
>     pub(crate) compiled_class_hash_writes: HashMap<ClassHash, CompiledClassHash>,
>     pub(crate) contract_class_writes: HashMap<ClassHash, bool>,
> ```

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 417 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvB7wqI0vu-bHdjtu3_:-NvRcLv66ckil6LCuAia:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3ed5e8098be5ed56f55623d15b89715110df8b6/crates/blockifier/src/state/cached_state.rs#L417)):*
> ```XML
>     fn set_contract_class_initial_values(&mut self, class_hash: ClassHash, is_declared: bool) {
>         self.contract_class_initial_values.insert(class_hash, is_declared);
>     }
> ```

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 518 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv0b6gN4oFQNR36jFyu:-NvRcQ387ujeZxs6-wZD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3ed5e8098be5ed56f55623d15b89715110df8b6/crates/blockifier/src/state/cached_state.rs#L518)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 754 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv0b9E75xeFeTCmJNsg:-NvRcX9ABx3hnB9fRhvG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3ed5e8098be5ed56f55623d15b89715110df8b6/crates/blockifier/src/state/cached_state.rs#L754)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/dict_state_reader.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv0bJFa6GoIhRRyD4Jt:-NvRcrEBDzSFt1Gd6ESj:b-s3hmk9) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3ed5e8098be5ed56f55623d15b89715110df8b6/crates/blockifier/src/test_utils/dict_state_reader.rs#L20)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

Not needed.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 407 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvB5Lio99mNpeUNmHFt:-NvRm7UR1fvS__W_aft3:b-t4ee1t) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3ed5e8098be5ed56f55623d15b89715110df8b6/crates/blockifier/src/state/cached_state.rs#L407)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`declared_contracts_` -> `declared_contract_`

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 226 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvRmFuD8PbzGNNSvUS_:-NvRmFuD8PbzGNNSvUSa:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/c8e7218e88c31bf5b3b7ddfb6a4b1c3a4cb07960/crates/blockifier/src/state/cached_state.rs#L226)):*
> ```XML
>                 Ok(contract_class_from_db) => {
>                     vacant_entry.insert(contract_class_from_db);
>                 }
> ```

.



_Suggestion:_
```XML
                Ok(contract_class) => {
                    vacant_entry.insert(contract_class);
                }
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 380 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvRmbWuBnxvQyrhR0h8:-NvRmbWuBnxvQyrhR0h9:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/c8e7218e88c31bf5b3b7ddfb6a4b1c3a4cb07960/crates/blockifier/src/state/cached_state.rs#L380)):*
> ```XML
>     fn set_declared_contracts_initial_values(&mut self, class_hash: ClassHash, is_declared: bool) {
>         self.declared_contracts_initial_values.insert(class_hash, is_declared);
>     }
> ```

.



_Suggestion:_
```XML
    fn declare_contract(&mut self, class_hash: ClassHash, is_declared: bool) {
        self.declared_contract_writes.insert(class_hash, true);
    }

    fn set_declared_contract_initial_value(&mut self, class_hash: ClassHash, is_declared: bool) {
        self.declared_contracts_initial_values.insert(class_hash, is_declared);
    }
```

**Review by noaov1 — DISMISSED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @OriStarkware)

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 407 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvB5Lio99mNpeUNmHFt:-NvS4bbL1xr8D2hLyLCQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3ed5e8098be5ed56f55623d15b89715110df8b6/crates/blockifier/src/state/cached_state.rs#L407)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`declared_contracts_` -> `declared_contract_`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 380 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvRmbWuBnxvQyrhR0h8:-NvS4a9O1mwZeEgONPAY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c8e7218e88c31bf5b3b7ddfb6a4b1c3a4cb07960/crates/blockifier/src/state/cached_state.rs#L380)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by OriStarkware — COMMENTED** [review]
Added a test. Adding the is_declared to `VersionedState` will be a separate task.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-:-NvWZ6r-4q4vvxw3rNt-:b-pxe8e2)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 380 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvRmbWuBnxvQyrhR0h8:-NvWjn9tEXtuYIdnyQxz:bk06y07) ([raw file](https://github.com/starkware-libs/blockifier/blob/c8e7218e88c31bf5b3b7ddfb6a4b1c3a4cb07960/crates/blockifier/src/state/cached_state.rs#L380)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove the `is_declare` arg

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 220 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvWzXCw9UDaP-oqy4Yd:-NvWzXCw9UDaP-oqy4Ye:bnn061b) ([raw file](https://github.com/starkware-libs/blockifier/blob/332f3839d759076d7065dcb15adf540bde76b3ee/crates/blockifier/src/state/cached_state.rs#L220)):*
> ```XML
>             match self.state.get_compiled_contract_class(class_hash) {
>                 Err(StateError::UndeclaredClassHash(class_hash)) => {
>                     cache.set_declared_contract_initial_values(class_hash, false);
> ```

Need to consider the case of invalidated declare transaction, let's talk

**Review by Yoni-Starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 115 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvX6kjM2tVb4Y6GB5_J:-NvX6kjM2tVb4Y6GB5_K:bmievwc) ([raw file](https://github.com/starkware-libs/blockifier/blob/332f3839d759076d7065dcb15adf540bde76b3ee/crates/blockifier/src/state/cached_state_test.rs#L115)):*
> ```XML
>     let contract_class = test_contract.get_class();
> 
>     assert_eq!(state.cache.borrow().declared_contract_writes.get(&class_hash).is_none(), true);
> ```

Why writes and not initial values?



_Suggestion:_
```XML
    assert_eq!(state.cache.borrow().declared_contract_writes.get(&class_hash), None);
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 117 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvX7EbCAEWq4scUuyDK:-NvX7EbCAEWq4scUuyDL:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/332f3839d759076d7065dcb15adf540bde76b3ee/crates/blockifier/src/state/cached_state_test.rs#L117)):*
> ```XML
>     assert_eq!(state.cache.borrow().declared_contract_writes.get(&class_hash).is_none(), true);
> 
>     assert_eq!(state.get_compiled_contract_class(class_hash).is_err(), true);
> ```





_Suggestion:_
```XML
        // Reading an undecalrted contract class.
        assert_matches!(
        state.get_compiled_contract_class(class_hash).unwrap_err(),
        StateError::UndeclaredClassHash(undeclared_class_hash) if
        undeclared_class_hash == class_hash
    );
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 115 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvX6kjM2tVb4Y6GB5_J:-NvXAAstBlRB2112pjGu:bewz06o) ([raw file](https://github.com/starkware-libs/blockifier/blob/332f3839d759076d7065dcb15adf540bde76b3ee/crates/blockifier/src/state/cached_state_test.rs#L115)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why writes and not initial values?
</blockquote></details>

Added initial_Values as well.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 235 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvZzgRF4PFIFjHN05Xy:-NvZzgRF4PFIFjHN05Xz:bq9l0h7) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state.rs#L235)):*
> ```XML
>             .expect("The class hash must appear in the cache.");
> 
>         cache.set_declared_contract_initial_values(class_hash, true);
> ```

What would be the initial value after set + get for the same class, by the same tx?

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: all files reviewed, 6 unresolved discussions (waiting on @OriStarkware)

___
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv_cafH2XVQDiK2sIth):*




_Suggestion:_
```
add declared_contract hashmap to StateCache
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 221 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvXDZ9Y9n666lTg3F7m:-NvXDZ9Y9n666lTg3F7n:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state.rs#L221)):*
> ```XML
>                 Err(StateError::UndeclaredClassHash(class_hash)) => {
>                     cache.set_declared_contract_initial_values(class_hash, false);
>                     return Err(StateError::UndeclaredClassHash(class_hash));
> ```





_Suggestion:_
```XML
Err(StateError::UndeclaredClassHash(class_hash))?
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 109 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv_w8oB71d97I-_T6i3:-Nv_w8oC9-YbhenWL-I9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state_test.rs#L109)):*
> ```XML
> 
> #[test]
> fn declare_contract() {
> ```





_Suggestion:_
```XML
fn test_declared_contract_mapping() {
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 118 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv_wKUIEot8Lf2qWbt2:-Nv_wKUIEot8Lf2qWbt3:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state_test.rs#L118)):*
> ```XML
>     assert_eq!(state.cache.borrow().declared_contract_initial_values.get(&class_hash), None);
> 
>     // Reading an undecalrted contract class.
> ```





_Suggestion:_
```XML
// Reading an undeclared contract class.
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv_z-Uf8HG4VNaLhUsr:-Nv_z-Uf8HG4VNaLhUss:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state_test.rs#L123)):*
> ```XML
>         StateError::UndeclaredClassHash(undeclared_class_hash) if
>         undeclared_class_hash == class_hash
>     );
> ```





_Suggestion:_
```XML
    assert_matches!(
        state.get_compiled_contract_class(class_hash).unwrap_err(),
        StateError::UndeclaredClassHash(undeclared_class_hash) => {
            assert_eq!(class_hash, undeclared_class_hash)
        }
    );
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 235 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvZzgRF4PFIFjHN05Xy:-Nva4KxpEVROvIcz7QH3:bl9oef7) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state.rs#L235)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What would be the initial value after set + get for the same class, by the same tx?
</blockquote></details>

Fixing that by moving this line only if the first match is ok.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 118 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv_wKUIEot8Lf2qWbt2:-Nva65Ha80zKgSLiamsj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state_test.rs#L118)):*
> ```XML
>     assert_eq!(state.cache.borrow().declared_contract_initial_values.get(&class_hash), None);
> 
>     // Reading an undecalrted contract class.
> ```

Done.

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 221 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-NvXDZ9Y9n666lTg3F7m:-NvbC2FS8veJ2Yw3ygrT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state.rs#L221)):*
> ```XML
>                 Err(StateError::UndeclaredClassHash(class_hash)) => {
>                     cache.set_declared_contract_initial_values(class_hash, false);
>                     return Err(StateError::UndeclaredClassHash(class_hash));
> ```

Done.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 109 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv_w8oB71d97I-_T6i3:-NvbC3d_DlG_a2FSsBuR:b-8fl1fj) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state_test.rs#L109)):*
> ```XML
> 
> #[test]
> fn declare_contract() {
> ```

I think the name should be similar to the other tests in the file.
We can change all the names in a different PR, but let's talk about that f2f.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv_z-Uf8HG4VNaLhUsr:-NvbClNqCvEOXpOjT_ot:b-hnfjj7) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state_test.rs#L123)):*
> ```XML
>         StateError::UndeclaredClassHash(undeclared_class_hash) if
>         undeclared_class_hash == class_hash
>     );
> ```

All the other `assert_matches!` in our code use `if` and not `=>`, so I think we should keep it like that.

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv_cafH2XVQDiK2sIth):*
Done.

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-Nv_z-Uf8HG4VNaLhUsr:-NvjyakKBe-AcnrdmIOb:b-9xrafm) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c4f06acf5d4c0f607871cd1aef64d26bd427e8d/crates/blockifier/src/state/cached_state_test.rs#L123)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

All the other `assert_matches!` in our code use `if` and not `=>`, so I think we should keep it like that.
</blockquote></details>

There is only one place (line 179):
```
assert_matches!(
    state.get_compiled_contract_class(missing_class_hash).unwrap_err(),
    StateError::UndeclaredClassHash(undeclared) if undeclared == missing_class_hash
);
```
And if you agree that the `=>` is better, we can change it too in this PR. WDYT?

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1765#-:-Nvk0m4a5gBBhGEkUViM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
