### PR TITLE
fix(transaction): change deploy_account default version to be V3

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2064)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2064)* status: 0 of 4 files reviewed, 2 unresolved discussions

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2064#-O1QANc223wYFwuqt3zr:-O1QANc223wYFwuqt3zs:b-8hfrfg) ([raw file](https://github.com/starkware-libs/blockifier/blob/0263ed49d3e6388fec610c12ba4953be9efa758b/crates/blockifier/src/concurrency/versioned_state_test.rs#L234)):*
> ```XML
>     let constructor_calldata = calldata![ctor_grind_arg, ctor_storage_arg];
>     let deploy_tx_args = deploy_account_tx_args! {
>         class_hash,
> ```

it only worked here without the resource bounds 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1399 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2064#-O1QAe590KaCjGMTw1nd:-O1QAe590KaCjGMTw1ne:bp7pj2m) ([raw file](https://github.com/starkware-libs/blockifier/blob/0263ed49d3e6388fec610c12ba4953be9efa758b/crates/blockifier/src/transaction/transactions_test.rs#L1399)):*
> ```XML
>     let mut nonce_manager = NonceManager::default();
>     let undeclared_hash = class_hash!("0xdeadbeef");
>     let deploy_account = deploy_account_tx(
> ```

It only worked here without the resource bounds.

**Review by noaov1 — CHANGES_REQUESTED** [review]
Please rebase over `maon-v0.13.2`

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2064#-:-O1RiUnY15PKbjhpFqM9:b-7iqc0v)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 226 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2064#-O1RhAF4EjfYNgxuTsjP:-O1RhAF4EjfYNgxuTsjQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1705682c603a5357b2ec4e063a12ce2f2b135b/crates/blockifier/src/concurrency/versioned_state_test.rs#L226)):*
> ```XML
>             version: TransactionVersion::ONE,
>         },
>         &mut NonceManager::default(),
> ```





_Suggestion:_
```XML
    let deploy_account_tx_1 = deploy_account_tx(
        deploy_account_tx_args! {
            class_hash: account_without_validation.get_class_hash(),
            resource_bounds: l1_resource_bounds(u64::from(!zero_bounds), DEFAULT_STRK_L1_GAS_PRICE),
        },
        &mut NonceManager::default(),
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2064#-O1RhPwt-HTweJvJDL-C:-O1RhPwt-HTweJvJDL-D:b-1wezko) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1705682c603a5357b2ec4e063a12ce2f2b135b/crates/blockifier/src/concurrency/versioned_state_test.rs#L246)):*
> ```XML
> 
>     let deployed_account_balance_key = get_fee_token_var_address(account_address);
>     let fee_token_address = chain_info.fee_token_address(&FeeType::Strk);
> ```

Can you please extract it from `account_tx_2`?



_Code quote:_
```XML
   let fee_token_address = chain_info.fee_token_address(&FeeType::Strk);
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 261 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2064#-O1RheOk3C3nMAAFsEPK:-O1RheOk3C3nMAAFsEPL:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1705682c603a5357b2ec4e063a12ce2f2b135b/crates/blockifier/src/concurrency/versioned_state_test.rs#L261)):*
> ```XML
>         s.spawn(move || {
>             let result = account_tx_2.execute(&mut state_2, &block_context_2, true, true);
>             result.unwrap();
> ```

Why?



_Code quote:_
```XML
            let result = account_tx_2.execute(&mut state_2, &block_context_2, true, true);
            result.unwrap();
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2064)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 261 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2064#-O1RheOk3C3nMAAFsEPK:-O1RkZJC0yIf5RV6hQW_:bpdsft5) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1705682c603a5357b2ec4e063a12ce2f2b135b/crates/blockifier/src/concurrency/versioned_state_test.rs#L261)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

for Debug will revert

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2064)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 226 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2064#-O1RhAF4EjfYNgxuTsjP:-O1RnUe9Aw8nFpwBO0gb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1705682c603a5357b2ec4e063a12ce2f2b135b/crates/blockifier/src/concurrency/versioned_state_test.rs#L226)):*
> ```XML
>             version: TransactionVersion::ONE,
>         },
>         &mut NonceManager::default(),
> ```

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2064#-:-O1RoA488pA0K-2Nvtdn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
