### PR TITLE
Support v3 declare (and others)

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1200)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1200)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 67 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUOiLKBgS9KHtIq_cf:-NkUQXjL0e-I3SVgScfM:bovitam) ([raw file](https://github.com/starkware-libs/blockifier/blob/e516fbcc56285260c13489ab94517358c78b4a55/crates/blockifier/src/test_utils/declare.rs#L67)):*
> ```XML
>                         class_hash: declare_tx_args.class_hash,
>                         nonce: declare_tx_args.nonce,
>                     })
> ```

Fixed arg order to match struct (in several places)
___
*[`crates/blockifier/src/test_utils/declare.rs` line 100 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUPQNlEkPyFeuJBduB:-NkUR0g73cdqpxQJutZK:b-icpjqi) ([raw file](https://github.com/starkware-libs/blockifier/blob/e516fbcc56285260c13489ab94517358c78b4a55/crates/blockifier/src/test_utils/declare.rs#L100)):*
> ```XML
>                         paymaster_data: declare_tx_args.paymaster_data,
>                         account_deployment_data: declare_tx_args.account_deployment_data,
>                         nonce: declare_tx_args.nonce,
> ```

not exactly - reordered to match struct
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 76 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUONiS529n1-EWgyua:-NkURf2W5tFbbE10S9He:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e516fbcc56285260c13489ab94517358c78b4a55/crates/blockifier/src/transaction/transactions_test.rs#L76)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It can be removed.
See the below comment.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 772 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUNC0A8laav0iA2-uE:-NkUReLMASkDx7oFvRYi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e516fbcc56285260c13489ab94517358c78b4a55/crates/blockifier/src/transaction/transactions_test.rs#L772)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Perhaps you could consider rewriting it using a match pattern, as we did [here](https://github.com/starkware-libs/blockifier/blob/e516fbcc56285260c13489ab94517358c78b4a55/crates/blockifier/src/transaction/transactions_test.rs#L112-L119).
</blockquote></details>

Done.

**Review by MohammadNassar1 — DISMISSED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 100 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUPQNlEkPyFeuJBduB:-NkUTn6K8109tUX97_7H:b-5yfvi2) ([raw file](https://github.com/starkware-libs/blockifier/blob/e516fbcc56285260c13489ab94517358c78b4a55/crates/blockifier/src/test_utils/declare.rs#L100)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not exactly - reordered to match struct
</blockquote></details>

Maybe align `DeclareTransactionV0V1, DeclareTransactionV2, DeclareTransactionV3` to match declareStruct?

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1200)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 729 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUbeKw0zHom6ZmXemj:-NkUbeKw0zHom6ZmXemk:bts9hmj) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ea827e52efcc66b376cff80a5ae47745904dcf6/crates/blockifier/src/transaction/transactions_test.rs#L729)):*
> ```XML
>     );
> }
> ```

Can this test be split into multiple smaller tests?

For example, we extract the testing logic into a dedicated function, then either split by transaction version, or by cairo version.
WDYT?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 888 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUbRh-24pG2iHhpr2O:-NkUbRh-24pG2iHhpr2P:bwzfmm9) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ea827e52efcc66b376cff80a5ae47745904dcf6/crates/blockifier/src/transaction/transactions_test.rs#L888)):*
> ```XML
> // TODO(Noa, 01/07/23): Consider unify the decalre tx tests.
> #[test]
> fn test_declare_tx_v2() {
> ```

Is there overlap between the two tests?
@noaov1 



_Code quote:_
```XML
// TODO(Noa, 01/07/23): Consider unify the decalre tx tests.
#[test]
fn test_declare_tx_v2() {
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1200)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 100 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUPQNlEkPyFeuJBduB:-NkUgHYV76Ci9q21sKV5:bwdxp0r) ([raw file](https://github.com/starkware-libs/blockifier/blob/e516fbcc56285260c13489ab94517358c78b4a55/crates/blockifier/src/test_utils/declare.rs#L100)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Maybe align `DeclareTransactionV0V1, DeclareTransactionV2, DeclareTransactionV3` to match declareStruct?
</blockquote></details>

These are defined in starknet-api, would prefer not to touch them
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 729 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUbeKw0zHom6ZmXemj:-NkUgNUO-8gtBd9Lfuo-:b-h8v7zm) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ea827e52efcc66b376cff80a5ae47745904dcf6/crates/blockifier/src/transaction/transactions_test.rs#L729)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can this test be split into multiple smaller tests?

For example, we extract the testing logic into a dedicated function, then either split by transaction version, or by cairo version.
WDYT?
</blockquote></details>

why not parametrize...? make it easier to see the variation... splitting by versions / whatever will increase code dup, no matter how many extractions you do.
i.e. I'm afraid of the situation where you'll have
```
let state_init = init_declare_state_stuff(cairo_version);
let init_stuff = init_declare_test_stuff(declare_version);
let expected_validate = declare_test_expected_validate(version, cairo_version);
...
```
... etc, once for each test.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1200)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 888 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUbRh-24pG2iHhpr2O:-NkUmVVS63hBYH1uUq7F:b-8kjgsl) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ea827e52efcc66b376cff80a5ae47745904dcf6/crates/blockifier/src/transaction/transactions_test.rs#L888)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes. Both test the flow of a declare transaction.
</blockquote></details>

Deleted the v2 test

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1200)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 888 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUbRh-24pG2iHhpr2O:-NkUmqwC5y-bHU_ACN2K:bop4c2s) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ea827e52efcc66b376cff80a5ae47745904dcf6/crates/blockifier/src/transaction/transactions_test.rs#L888)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Deleted the v2 test
</blockquote></details>

Why? Here we test a declaration of a cairo1 contract. Do you test it?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1200)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 729 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUbeKw0zHom6ZmXemj:-Nkj-UoK4xw4Kr3UoyF3:bwh67d7) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ea827e52efcc66b376cff80a5ae47745904dcf6/crates/blockifier/src/transaction/transactions_test.rs#L729)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Unblocking this.

I like the no-duplication here don't get me wrong, but it might be bit lengthy and complex. 

Took me several minutes to fully grasp it, which might happen to others should they need to debug it later.

Maybe we keep the parametrization for the similar parts and split out the very different setups or logic, like the version=0 case?

 This way, we minimize duplication and maintain clarity.
</blockquote></details>

For this PR - which is mainly to support all declare types and showcase an example - I'd keep it like this.
We need a test-infra revamp anyway

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1200)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 888 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1200#-NkUbRh-24pG2iHhpr2O:-Nkj-psB4ZT37eTQnVDb:b-x0paxf) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ea827e52efcc66b376cff80a5ae47745904dcf6/crates/blockifier/src/transaction/transactions_test.rs#L888)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

@noaov1 Is this OK?
</blockquote></details>

Yes :)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
