### PR TITLE
chore(native_blockifier): return the block weights to python

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1895)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
Python: https://reviewable.io/reviews/starkware-industries/starkware/34963

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1895#-:-NxgquWnC4MHAWVEE_tP:bsg606v)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1895)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1895#-NxxYNpB4ybM0kd0cFPA:-NxxYNpB4ybM0kd0cFPB:b-fcfh24) ([raw file](https://github.com/starkware-libs/blockifier/blob/863933a5803e588328867acd952c56711bad3afd/crates/native_blockifier/src/py_block_executor.rs#L295)):*
> ```XML
>             PyBytes::new(
>                 py,
>                 &serde_json::to_vec(&block_weights).expect("Failed serializing bouncer weights."),
> ```

Move the serialization before the `with_gil` to reduce (gil) lock time.

**Review by liorgold2 — APPROVED** [review]
:lgtm: (see one comment below)

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1895#-:-NxxYnew2SfKb8WAt1Q3:bjbdo6x)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1895)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1895#-NxxYNpB4ybM0kd0cFPA:-Ny-6lmV4LLJGBO-A_Ab:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/863933a5803e588328867acd952c56711bad3afd/crates/native_blockifier/src/py_block_executor.rs#L295)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Move the serialization before the `with_gil` to reduce (gil) lock time.
</blockquote></details>

Done

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1895#-:-Ny698Ti6VvtZg6NfC_y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
