### PR TITLE
Add use_kzg_da flag to PyBlockInfo.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1319)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
I tested it manually - the value is populated as intended on the Python-Rust line.

**Review by ArniStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1319#-:-NnmLQka27683e980SDG:b-hz3kb8)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1319)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1319#-NnmZdjC8xcbJF41gSKJ:-NnmZPefEb3xLyomu-b1:b-eg9pa8) (no related file):*
Is there a python-side PR that passed hodor, pointing to this commit?

___

**Comment by ArniStarkware** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Is there a python-side PR that passed hodor, pointing to this commit?
</blockquote></details>

There is a PR now: https://github.com/starkware-industries/starkware/pull/33341

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1319#-:-Nnmu_Hq6mDPsqKlAA0P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1319#-NnmZdjC8xcbJF41gSKJ:-NnmuYl3DPyP5hOAF_2t:b-ttq2l0) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

There is a PR now: https://github.com/starkware-industries/starkware/pull/33341
</blockquote></details>

passes, lgtm

___

**Pull request merged**
