### PR TITLE
Builtin name consistency test

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/587)

### CODE REVIEW

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/587#-:-NXe2srEDjc6TyuZgIzp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/os_usage_test.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/587#-NXe2kST7kC8r7tGA5b8:-NXe2kSU1_GZawVa_I5L:b4hbxfy) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff70cd414159dbd6ac700e725286905f8fc01753/crates/blockifier/src/fee/os_usage_test.rs#L3)):*
> ```XML
> use std::collections::HashSet;
> 
> use cairo_vm::vm::runners::builtin_runner::{
> ```

Consider using the whole module name, so this line isn't so long.



_Code quote:_
```XML
cairo_vm::vm::runners::builtin_runner
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/587)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/587#-:-NXe643b-x3oC963vez-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/587)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
