### PR TITLE
Use ContractClass enum in blockifier

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/458)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a> 
    * **PR #449** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/449" target="_blank">Graphite</a> 
      * **PR #451** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/451" target="_blank">Graphite</a> 
        * **PR #450** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/450" target="_blank">Graphite</a> 
          * **PR #452** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/452" target="_blank">Graphite</a> 
            * **PR #458** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/458" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/458?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/458)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution/errors.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/458#-NV8n76nAYgdrQAAm0H7:-NV8n76nAYgdrQAAm0H8:baoro62) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3edd8a4188f76313356f81bb79ca60e4674f0d/crates/blockifier/src/execution/errors.rs#L33)):*
> ```XML
>     UninitializedStorageAddress(ContractAddress),
>     #[error("Cairo1 unsupported")]
>     Cairo1Unsupported,
> ```

Temporary, right? :grimacing: 



_Code quote:_
```XML
    #[error("Cairo1 unsupported")]
    Cairo1Unsupported,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/458#-NV8lPHPBhgHIJxDetDK:-NV8lPHPBhgHIJxDetDL:blbriqp) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3edd8a4188f76313356f81bb79ca60e4674f0d/crates/blockifier/src/transaction/account_transactions_test.rs#L69)):*
> ```XML
> 
>     // Declare a contract.
>     let contract_class = get_contract_class_v0(TEST_CONTRACT_PATH).into();
> ```

Why not make this function return `ContractClass::V0`?



_Code quote:_
```XML
get_contract_class_v0
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/458#-NV8liyY41rgh0pIXdjB:-NV8liyY41rgh0pIXdjC:b-pb4no2) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3edd8a4188f76313356f81bb79ca60e4674f0d/crates/native_blockifier/src/papyrus_state.rs#L69)):*
> ```XML
>         match self.reader.get_deprecated_class_definition_at(state_number, class_hash) {
>             Ok(Some(starknet_api_contract_class)) => {
>                 Ok(ContractClassV0::try_from(starknet_api_contract_class)?.into())
> ```

Please use `::from`.



_Code quote:_
```XML
.into()
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/458#-NV8lpK614ShybYbjWXJ:-NV8lpK614ShybYbjWXK:b-pb4no2) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3edd8a4188f76313356f81bb79ca60e4674f0d/crates/native_blockifier/src/py_transaction.rs#L197)):*
> ```XML
>                 .expect("A contract class must be passed in a Declare transaction.");
>             let contract_class =
>                 serde_json::from_str::<ContractClassV0>(raw_contract_class)?.into();
> ```

Please use `::from`.



_Suggestion:_
```XML
            let contract_class = ContractClass::
                serde_json::from_str::<ContractClassV0>(raw_contract_class)?.into();
```

**Review by elintul — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/458)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @spapinistarkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 21 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/458)* status: 32 of 33 files reviewed, 3 unresolved discussions (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/458#-NV97yVpCrVJPCCEKqg_:-NV97yVpCrVJPCCEKqga:bhg7a45) ([raw file](https://github.com/starkware-libs/blockifier/blob/30fd5b3a6849980861fd0646f080d5127520d630/crates/blockifier/src/execution/contract_class.rs#L3)):*
> ```XML
> use std::collections::HashMap;
> use std::sync::Arc;
> ```

I'm confused with all the PRs and rebases. Didn't it appear in another PR?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/458)* status: 12 of 33 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/errors.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/458#-NV8n76nAYgdrQAAm0H7:-NV96WUwAThJLr6_5Ldv:b-7xt4he) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3edd8a4188f76313356f81bb79ca60e4674f0d/crates/blockifier/src/execution/errors.rs#L33)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Temporary, right? :grimacing: 
</blockquote></details>

Yep:)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/458#-NV8lPHPBhgHIJxDetDK:-NV96Z1B0x_X9vcZOHrJ:b2igbdj) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3edd8a4188f76313356f81bb79ca60e4674f0d/crates/blockifier/src/transaction/account_transactions_test.rs#L69)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not make this function return `ContractClass::V0`?
</blockquote></details>

Belongs to previous PR
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/458#-NV8liyY41rgh0pIXdjB:-NV96r2O3jo4YRgA8HP1:bw5sawm) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3edd8a4188f76313356f81bb79ca60e4674f0d/crates/native_blockifier/src/papyrus_state.rs#L69)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please use `::from`.
</blockquote></details>

I'll disagree on this one:) The return type is clear from the signature. It doesn't add a lot of information. It beats the purpose of the quality of life of intoing a V0 or V1 contract class into the enum.
I think it just add distractors to the reader.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/458)* status: 12 of 33 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/458#-NV97yVpCrVJPCCEKqg_:-NV9Cy5LBNSt7jW7SpWM:b-apvkqm) ([raw file](https://github.com/starkware-libs/blockifier/blob/30fd5b3a6849980861fd0646f080d5127520d630/crates/blockifier/src/execution/contract_class.rs#L3)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm confused with all the PRs and rebases. Didn't it appear in another PR?
</blockquote></details>

It wasn't rebased yet. Now it's gone

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/458#-:-NV9FYMk4Wzs9tk_sLmN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
