### PR TITLE
feat: add ctor error frame to stack trace

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1845)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1845)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/errors.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1845#-NwnwvyLAZ_g78s1Px2K:-NwnwvyLAZ_g78s1Px2L:b-a1lsia) ([raw file](https://github.com/starkware-libs/blockifier/blob/f27a19035f66072d6f0625120f708f577fdfdfe4/crates/blockifier/src/execution/errors.rs#L157)):*
> ```XML
>                 // TODO(Dori, 5/5/2024): Also handle the no-selector case.
>                 constructor_selector: Some(selector),
>             },
> ```

This means this trace will not be created if in the given `error`: `constructor_selector` is `None`.

This is the intended behavior, is it?



_Code quote:_
```XML
        | TransactionExecutionError::ContractConstructorExecutionFailed(
            ConstructorEntryPointExecutionError::ExecutionError {
                error,
                class_hash,
                contract_address: storage_address,
                // TODO(Dori, 5/5/2024): Also handle the no-selector case.
                constructor_selector: Some(selector),
            },
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 482 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1845#-Nwny79579GkOSwLLQPY:-Nwny79579GkOSwLLQPZ:b-ggd5r0) ([raw file](https://github.com/starkware-libs/blockifier/blob/f27a19035f66072d6f0625120f708f577fdfdfe4/crates/blockifier/src/transaction/account_transactions_test.rs#L482)):*
> ```XML
> /// Tests that hitting an execution error in an account contract constructor outputs the correct
> /// traceback (including correct class hash, contract address and constructor entry point selector).
> fn test_account_ctor_frame_stack_trace(
> ```

Are there similar tests for: `ExecutionError`, and `ValidateTransactionError`?



_Code quote:_
```XML
fn test_account_ctor_frame_stack_trace(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1845)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/execution/errors.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1845#-NwnwvyLAZ_g78s1Px2K:-NwoeMy77vb7g9gmtNTf:b5en440) ([raw file](https://github.com/starkware-libs/blockifier/blob/f27a19035f66072d6f0625120f708f577fdfdfe4/crates/blockifier/src/execution/errors.rs#L157)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This means this trace will not be created if in the given `error`: `constructor_selector` is `None`.

This is the intended behavior, is it?
</blockquote></details>

no, hence the TODO :)
we would like to output "UNKNOWN" or something if the selector isn't known (for example, an error occurred reading the compiled class from storage), not ignore it.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 482 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1845#-Nwny79579GkOSwLLQPY:-Nwof9gs-9PKOZRU13yU:b2vrv70) ([raw file](https://github.com/starkware-libs/blockifier/blob/f27a19035f66072d6f0625120f708f577fdfdfe4/crates/blockifier/src/transaction/account_transactions_test.rs#L482)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Are there similar tests for: `ExecutionError`, and `ValidateTransactionError`?
</blockquote></details>

yes: `test_stack_trace`, `test_trace_callchain_ends_with_regular_call`, `test_trace_call_chain_with_syscalls`, `test_validate_trace` are the other stack trace tests we have

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1845#-:-Nwp3u8_4P-4U0A657C4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1845#-:-NwszRc04hnss6FKnM_g:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
