### PR TITLE
Check balance is at least max_fee

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVjs8ND98zMUJJDwgjZ:-NVksbx136PsBAVodMAn:bkz2fnh) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f8e3562f47b85d4dda70c58d368a999b54796b0/crates/blockifier/src/transaction/transactions_test.rs#L384)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What's this syntax?
</blockquote></details>

[`assert_matches`](https://doc.rust-lang.org/std/assert_matches/macro.assert_matches.html) macro, weird syntax

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVkzAke94zaCw4tREzN:-NVkzAke94zaCw4tREzO:bo54zcp) (no related file):*
@elintul should this go to `main`?
If this is for `0.12.1` maybe we need to fix a `main-v0.12.0` branch for the blockifier...?

___

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/state/state_api.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVmTLOpBtjNUZY2Pr0j:-NVmTLOq5ZQdGid2HARl:b-q9xpxu) ([raw file](https://github.com/starkware-libs/blockifier/blob/56218e533e2e6aa53b8ed44a34a7a696f710e068/crates/blockifier/src/state/state_api.rs#L50)):*
> ```XML
>         self.get_storage_at(
>             block_context.fee_token_address,
>             get_storage_var_address("ERC20_balances", &[*contract_address.0.key()])?,
> ```

Oops, the balance is a u256, you need to read two felts here

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/state_api.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVmTLOpBtjNUZY2Pr0j:-NVn0XHH43pnnVAlWTBx:bf3jkk3) ([raw file](https://github.com/starkware-libs/blockifier/blob/56218e533e2e6aa53b8ed44a34a7a696f710e068/crates/blockifier/src/state/state_api.rs#L50)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oops, the balance is a u256, you need to read two felts here
</blockquote></details>

Good catch!
IIUC, one storage key stores one field element.
If the only example of a storage key for the balance I see is
```
get_storage_var_address("ERC20_balances", &[contract_address.0.key()])
```
, and it is used in tests, my guess is this is the low 128 bits.
What is the storage key for the top 128 bits?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVkzAke94zaCw4tREzN:-NVtZFjs48Xu-dSt2xfy:b-3r020s) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@elintul should this go to `main`?
If this is for `0.12.1` maybe we need to fix a `main-v0.12.0` branch for the blockifier...?
</blockquote></details>

Yes... do you know how to do this? Let's coordinate this tomorrow.

___
___
*[`crates/blockifier/src/state/cached_state.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVjYxLfErojvj9B6u2U:-NVjYxLgA2Sady8JcbYy:b-isqha8) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f8e3562f47b85d4dda70c58d368a999b54796b0/crates/blockifier/src/state/cached_state.rs#L67)):*
> ```XML
>         (storage_updates.len(), modified_contracts.len(), class_hash_updates.len())
>     }
> ```

We decided not to go with a view method of the fee token contract?
___
*[`crates/blockifier/src/state/cached_state.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVjZ2v_7Xsxd7Pj7wZR:-NVjZ2v_7Xsxd7Pj7wZS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f8e3562f47b85d4dda70c58d368a999b54796b0/crates/blockifier/src/state/cached_state.rs#L69)):*
> ```XML
> 
>     /// Returns the storage value representing the balance (in fee token) at the given address.
>     pub fn get_balance(
> ```





_Suggestion:_
```XML
get_fee_token_balance
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVtZl1m1MreBcjNqSuX:-NVtZl1m1MreBcjNqSuY:b4fzkao) ([raw file](https://github.com/starkware-libs/blockifier/blob/56218e533e2e6aa53b8ed44a34a7a696f710e068/crates/blockifier/src/transaction/transactions_test.rs#L371)):*
> ```XML
>         if max_fee == invalid_max_fee
>     );
> ```

Perhaps a dedicated test is due, this can happen for all account transactions.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVkzAke94zaCw4tREzN:-NVttrnP7ntm3FEnHHZn:bnbpkn3) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yes... do you know how to do this? Let's coordinate this tomorrow.
</blockquote></details>

I know how to open a new branch, don't know if there's anything else involved.
Do we have some concept of nightly branches in the blockifier repo? Some periodic CI run on feature branches?

___
___
*[`crates/blockifier/src/state/cached_state.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVjYxLfErojvj9B6u2U:-NVttK8EE7UytpJEkA6g:b-4jbyee) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f8e3562f47b85d4dda70c58d368a999b54796b0/crates/blockifier/src/state/cached_state.rs#L67)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We decided not to go with a view method of the fee token contract?
</blockquote></details>

Hmm... I was hoping to avoid processing another `call` for every tx, but perhaps we don't have much choice... when volition comes around, computing the balance of a user on an ERC20 contract may not be a simple storage read.
WDYT?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/state/state_api.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVmTLOpBtjNUZY2Pr0j:-NVwdyAw8K7HADGVIDWh:b-geyww0) ([raw file](https://github.com/starkware-libs/blockifier/blob/56218e533e2e6aa53b8ed44a34a7a696f710e068/crates/blockifier/src/state/state_api.rs#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Good catch!
IIUC, one storage key stores one field element.
If the only example of a storage key for the balance I see is
```
get_storage_var_address("ERC20_balances", &[contract_address.0.key()])
```
, and it is used in tests, my guess is this is the low 128 bits.
What is the storage key for the top 128 bits?
</blockquote></details>

The one next to it :)
A storage var is written continuously in storage.
___
*[`crates/blockifier/src/state/cached_state.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVjYxLfErojvj9B6u2U:-NVweKfF5uqzXZ9_3vLN:b-6gfma6) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f8e3562f47b85d4dda70c58d368a999b54796b0/crates/blockifier/src/state/cached_state.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Hmm... I was hoping to avoid processing another `call` for every tx, but perhaps we don't have much choice... when volition comes around, computing the balance of a user on an ERC20 contract may not be a simple storage read.
WDYT?
</blockquote></details>

I'd also like to avoid a contract call. Note that even an empty call costs at least  O(called program length)
Volition won't be a problem - you'll have to specify the address domain somehow, it doesn't matter.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVkzAke94zaCw4tREzN:-NVxqFAN8esG7l74hNvN:b-sjjosq) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I know how to open a new branch, don't know if there's anything else involved.
Do we have some concept of nightly branches in the blockifier repo? Some periodic CI run on feature branches?
</blockquote></details>

Only a post-merge CI run.

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVkzAke94zaCw4tREzN:-NVy8yrc0YSU0p-zWuuf:bv6dy5d) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Only a post-merge CI run.
</blockquote></details>

Want me to open `main-v0.12.0` and post a message on the sequencer channel?

___
___
*[`crates/blockifier/src/state/state_api.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVmTLOpBtjNUZY2Pr0j:-NVy8br1-vq7noNEvtGr:bvixjay) ([raw file](https://github.com/starkware-libs/blockifier/blob/56218e533e2e6aa53b8ed44a34a7a696f710e068/crates/blockifier/src/state/state_api.rs#L50)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The one next to it :)
A storage var is written continuously in storage.
</blockquote></details>

separate PR
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVtZl1m1MreBcjNqSuX:-NVy8f-vB6kDpAwlxr89:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/56218e533e2e6aa53b8ed44a34a7a696f710e068/crates/blockifier/src/transaction/transactions_test.rs#L371)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps a dedicated test is due, this can happen for all account transactions.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVjZ2v_7Xsxd7Pj7wZR:-NVy8gdnCu6WBKoyaNre:b-e3lym3) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f8e3562f47b85d4dda70c58d368a999b54796b0/crates/blockifier/src/state/cached_state.rs#L69)):*
> ```XML
> 
>     /// Returns the storage value representing the balance (in fee token) at the given address.
>     pub fn get_balance(
> ```

separate PR (I'll rebase)

**Review by elintul — DISMISSED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 390 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVytKHs-0bab-5Frc1y:-NVytKHs-0bab-5Frc1z:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a14ade97ebd67fc7e86781ab94ae6f9569d3634/crates/blockifier/src/transaction/transactions_test.rs#L390)):*
> ```XML
> }
> 
> fn assert_max_fee_exceeds_balance(
> ```





_Suggestion:_
```XML
assert_failure_if_max_fee_exceeds_balance
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 395 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVyt2Gt0ZlvLLhbfTLf:-NVyt2Gu3rcpnjbgNwN-:bz5heol) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a14ade97ebd67fc7e86781ab94ae6f9569d3634/crates/blockifier/src/transaction/transactions_test.rs#L395)):*
> ```XML
>     invalid_tx: AccountTransaction,
> ) {
>     let sent_max_fee = invalid_tx.max_fee();
> ```

Consider removing variable.



_Code quote:_
```XML
let sent_max_fee = invalid_tx.max_fee();
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 395 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NVyt2Gt0ZlvLLhbfTLf:-NVzM0LqCwyfW5mSjo2K:b5q9ctv) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a14ade97ebd67fc7e86781ab94ae6f9569d3634/crates/blockifier/src/transaction/transactions_test.rs#L395)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider removing variable.
</blockquote></details>

can't; `invalid_tx` is moved into `execute`.
Got rid of the other var instead :P

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494#-:-NW0ltyL5c5feqHse7Cj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/494)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 196 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/494#-NW1EDH29f58thdM2g2Q:-NW1EDH37nvmYGxuDtSs:b-dsbv88) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf2e0c0d674c4e840849ee2b03c7c455728ae617/crates/blockifier/src/transaction/account_transaction.rs#L196)):*
> ```XML
>         &self,
>         state: &mut TransactionalState<'_, S>,
>         block_context: &BlockContext,
> ```

Isn't that part of the execution context?



_Code quote:_
```XML
block_context: &BlockContext,
```

**Pull request merged**
