### PR TITLE
New fee token TODOs

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/836)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/836#-:-Nc1iaurBCa-7RdfalSz:b-1m4vin)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Review by zuphitf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/836)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/block_context.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/836#-Nc1jYDY4sONBTDLJwqq:-Nc1jYDY4sONBTDLJwqr:b-scooz) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d0cb0f816f9dc4a3fd6ad396dd84d5fb44f6bd7/crates/blockifier/src/block_context.rs#L15)):*
> ```XML
>     // Fee-related.
>     pub sequencer_address: ContractAddress,
>     // TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT add new token address.
> ```

Already done in #837 
___
*[`crates/blockifier/src/test_utils.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/836#-Nc1ka2p0kKOyqfDpXMV:-Nc1ka2p0kKOyqfDpXMW:b-scooz) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d0cb0f816f9dc4a3fd6ad396dd84d5fb44f6bd7/crates/blockifier/src/test_utils.rs#L342)):*
> ```XML
>             block_timestamp: BlockTimestamp::default(),
>             sequencer_address: contract_address!(TEST_SEQUENCER_ADDRESS),
>             // TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT add new token address.
> ```

Already done in #837 



_Code quote:_
```XML
 // TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT add new token address.
```

**Review by zuphitf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/836)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/836#-Nc1ktuF7NV6JRKbJH7z:-Nc1ktuF7NV6JRKbJH8-:b-scooz) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d0cb0f816f9dc4a3fd6ad396dd84d5fb44f6bd7/crates/native_blockifier/src/py_block_executor.rs#L228)):*
> ```XML
>     #[pyo3(from_py_with = "int_to_chain_id")]
>     pub chain_id: ChainId,
>     // TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT add new token address.
> ```

Already done in #837 



_Code quote:_
```XML
 // TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT add new token address.
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 250 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/836#-Nc1kwAI5Tzb1fwrMHbi:-Nc1kwAI5Tzb1fwrMHbj:b-scooz) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d0cb0f816f9dc4a3fd6ad396dd84d5fb44f6bd7/crates/native_blockifier/src/py_block_executor.rs#L250)):*
> ```XML
>         block_timestamp: BlockTimestamp(block_info.block_timestamp),
>         sequencer_address: ContractAddress::try_from(block_info.sequencer_address.0)?,
>         // TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT also take new token address from os config.
> ```

Already done in #837 



_Code quote:_
```XML
// TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT also take new token address from os config.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/836)* status: all files reviewed, 4 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/block_context.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/836#-Nc1jYDY4sONBTDLJwqq:-Nc1mHrC51nTVuuK9k6a:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d0cb0f816f9dc4a3fd6ad396dd84d5fb44f6bd7/crates/blockifier/src/block_context.rs#L15)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Already done in #837
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/836#-Nc1ka2p0kKOyqfDpXMV:-Nc1mMHx6iYHsJpvTe-T:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d0cb0f816f9dc4a3fd6ad396dd84d5fb44f6bd7/crates/blockifier/src/test_utils.rs#L342)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Already done in #837
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/836#-Nc1ktuF7NV6JRKbJH7z:-Nc1mWNrBJUVCjycI9I3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d0cb0f816f9dc4a3fd6ad396dd84d5fb44f6bd7/crates/native_blockifier/src/py_block_executor.rs#L228)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Already done in #837
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 250 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/836#-Nc1kwAI5Tzb1fwrMHbi:-Nc1mGWC2qiso8RRxAo0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d0cb0f816f9dc4a3fd6ad396dd84d5fb44f6bd7/crates/native_blockifier/src/py_block_executor.rs#L250)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Already done in #837
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/836)* status: all files reviewed, 4 unresolved discussions (waiting on @zuphitf)

**Review by zuphitf — APPROVED** [review]
> Reviewed 8 of 11 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/836)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
