### PR TITLE
feat: implement ctor failure frame in stack trace

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1838)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1838)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 241 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1838#-NwjPObB4253Cj80VCKB:-NwjPObB4253Cj80VCKC:bmhm39z) ([raw file](https://github.com/starkware-libs/blockifier/blob/e868ab07dbdeef1ce9fe14a57a5105075101b423/crates/blockifier/src/test_utils.rs#L241)):*
> ```XML
>                 $crate::check_entry_point_execution_error!(error, $expected_hint)
>             }
>             $crate::transaction::errors::TransactionExecutionError::ValidateTransactionError { error, .. } => {
> ```

@ArniStarkware wasn't sure how to fix this... I moved to explicit-matching



_Code quote:_
```XML
            $crate::transaction::errors::TransactionExecutionError::ContractConstructorExecutionFailed {
                error: $crate::execution::errors::DeployError::ExecutionError { error, .. },
                ..
            } => {
                $crate::check_entry_point_execution_error!(error, $expected_hint)
            }
            $crate::transaction::errors::TransactionExecutionError::ValidateTransactionError { error, .. } => {
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils.rs` line 241 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1838#-NwjPObB4253Cj80VCKB:-NwjPUFq-PHaYKYGh1Xk:b3jzwxv) ([raw file](https://github.com/starkware-libs/blockifier/blob/e868ab07dbdeef1ce9fe14a57a5105075101b423/crates/blockifier/src/test_utils.rs#L241)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@ArniStarkware wasn't sure how to fix this... I moved to explicit-matching
</blockquote></details>

This means there is no assertion in the call that the specific correct variant is called :/

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1838#-NwjPkxM3gq_az7y6wZO:-NwjPkxM3gq_az7y6wZP:beoo0ym) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c118480d5caf9ae926dbba1060539543026e2f2/crates/blockifier/src/test_utils.rs#L233)):*
> ```XML
> #[macro_export]
> macro_rules! check_transaction_execution_error_inner {
>     ($error:expr, $expected_hint:expr, $variant:ident $(,)?) => {
> ```

the variant is no longer used.

But this is a problem on another level, as @dorimedini-starkware stated below.



_Suggestion:_
```XML
   ($error:expr, $expected_hint:expr $(,)?)
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1838)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1838#-NwjPkxM3gq_az7y6wZO:-NwjU69WDkVU2CUrVVlm:b-algq4j) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c118480d5caf9ae926dbba1060539543026e2f2/crates/blockifier/src/test_utils.rs#L233)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

the variant is no longer used.

But this is a problem on another level, as @dorimedini-starkware stated below.
</blockquote></details>

handled in #1839  (should be squashed into this PR)
___
*[`crates/blockifier/src/test_utils.rs` line 241 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1838#-NwjPObB4253Cj80VCKB:-NwjUEhY5kgG4LhEonU-:b-algq4j) ([raw file](https://github.com/starkware-libs/blockifier/blob/e868ab07dbdeef1ce9fe14a57a5105075101b423/crates/blockifier/src/test_utils.rs#L241)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This means there is no assertion in the call that the specific correct variant is called :/
</blockquote></details>

handled in #1839  (should be squashed into this PR)

**Pull request closed without merging**
