### PR TITLE
chore: simplify create_account_tx_for_validate_test

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1939** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1939?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)* status: 0 of 5 files reviewed, all discussions resolved

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1939#-NzNO12lCPOE7f_zHHML:-NzNO12lCPOE7f_zHHMM:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/e19f21803456dc9f7efcae92ee668426863b9f65/crates/blockifier/src/transaction/test_utils.rs#L181)):*
> ```XML
> /// should be used for unit tests. For example, it is not intended to deploy a contract
> /// and later call it.
> pub fn create_account_tx_for_validate_test(
> ```

WDYT?



_Suggestion:_
```XML
pub fn simple_create_faulty_account_tx(
    faulty_account_tx_creator_args: FaultyAccountTxCreatorArgs,
) -> AccountTransaction {
    create_account_tx_for_validate_test(
        &mut NonceManager::default(),
        faulty_account_tx_creator_args,
    )
}

/// Creates an account transaction to test the 'validate' method of account transactions. The
/// transaction is formatted to work with the account contract 'FaultyAccount'. These transactions
/// should be used for unit tests. For example, it is not intended to deploy a contract
/// and later call it.
pub fn create_faulty_account_tx(
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 486 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1939#-Nzh3V1xDKEya-Q4qQT6:-Nzh3V1y07rmi2NVRUqI:bhkf1wf) ([raw file](https://github.com/starkware-libs/blockifier/blob/e19f21803456dc9f7efcae92ee668426863b9f65/crates/blockifier/src/transaction/account_transactions_test.rs#L486)):*
> ```XML
>     let state = &mut test_state(chain_info, BALANCE, &[(faulty_account_feature_contract, 0)]);
> 
>     // Create and execute (failing) deploy account transaction.
> ```

failing



_Code quote:_
```XML
failing
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1939#-NzNO12lCPOE7f_zHHML:-Nzh2opCAHcg4u5ofT4w:bvkkcd4) ([raw file](https://github.com/starkware-libs/blockifier/blob/e19f21803456dc9f7efcae92ee668426863b9f65/crates/blockifier/src/transaction/test_utils.rs#L181)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

not sure I understand the purpose of this account, iiuc , it does not always fail, or is it?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 486 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1939#-Nzh3V1xDKEya-Q4qQT6:-Nzh8qCzC64CPpaAMmjp:bvy9z38) ([raw file](https://github.com/starkware-libs/blockifier/blob/e19f21803456dc9f7efcae92ee668426863b9f65/crates/blockifier/src/transaction/account_transactions_test.rs#L486)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

failing
</blockquote></details>

I don't understand the feedback.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1939#-NzNO12lCPOE7f_zHHML:-Nzh7gZ96eeHeP2ZtQ2r:bkr443w) ([raw file](https://github.com/starkware-libs/blockifier/blob/e19f21803456dc9f7efcae92ee668426863b9f65/crates/blockifier/src/transaction/test_utils.rs#L181)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure I understand the purpose of this account, iiuc , it does not always fail, or is it?
</blockquote></details>

It does not always fail. You are correct.

The issue is that the feature contract is called `FeatureContract::FaultyAccount`. Do you think this contract's name can change - to something like `FeatureContract::AccountForValidateTest`?

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 486 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1939#-Nzh3V1xDKEya-Q4qQT6:-Nzh9_qFEctgOFQPmbBj:b-okx2b3) ([raw file](https://github.com/starkware-libs/blockifier/blob/e19f21803456dc9f7efcae92ee668426863b9f65/crates/blockifier/src/transaction/account_transactions_test.rs#L486)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I don't understand the feedback.
</blockquote></details>

Never mind, I was probably hallucinating.
 
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1939#-NzNO12lCPOE7f_zHHML:-Nzh9kqF5FVcFqfnp7Io:bx5we88) ([raw file](https://github.com/starkware-libs/blockifier/blob/e19f21803456dc9f7efcae92ee668426863b9f65/crates/blockifier/src/transaction/test_utils.rs#L181)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It does not always fail. You are correct.

The issue is that the feature contract is called `FeatureContract::FaultyAccount`. Do you think this contract's name can change - to something like `FeatureContract::AccountForValidateTest`?
</blockquote></details>

this would be much more readable IMO

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1939#-NzNO12lCPOE7f_zHHML:-NzhBmyqDCKdiOSDbXMn:b-wrsx8n) ([raw file](https://github.com/starkware-libs/blockifier/blob/e19f21803456dc9f7efcae92ee668426863b9f65/crates/blockifier/src/transaction/test_utils.rs#L181)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this would be much more readable IMO
</blockquote></details>

In another PR.

**Review by Yael-Starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by ArniStarkware** [comment]
+reviewer:@giladchase

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @giladchase)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1939#-NzmiwsU8oZ8UmActrq-:-NzmiwsU8oZ8UmActrq0:b1aqj81) ([raw file](https://github.com/starkware-libs/blockifier/blob/e19f21803456dc9f7efcae92ee668426863b9f65/crates/blockifier/src/transaction/test_utils.rs#L168)):*
> ```XML
> /// the nonce manager. Should be used for transactions which are expected to fail or if the nonce is
> /// irrelevant to the test.
> pub fn simple_create_account_tx_for_validate_test(
> ```

Please rename to something more descriptive (suggestion below)



_Suggestion:_
```XML
create_account_tx_for_validate_test_nonce_0
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @Yael-Starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1939#-NzmiwsU8oZ8UmActrq-:-Nzvrnnr6-j23bfTVKjy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e19f21803456dc9f7efcae92ee668426863b9f65/crates/blockifier/src/transaction/test_utils.rs#L168)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Please rename to something more descriptive (suggestion below)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1939)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @Yael-Starkware)

**Pull request merged**
