### PR TITLE
Merge main-v0.13.1 into main

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1515)

### CODE REVIEW

**Comment by barak-b-starkware** [comment]
[Src](https://github.com/starkware-industries/starkware/compare/06ceabe93f587f1085fc5e5887f2b4e748de017a..main-v0.13.1#diff-5c8f1932b7622795200ea94aa34a434df0ce530f5a67de408abc6f5c3d25b423) [Dst](https://github.com/starkware-industries/starkware/compare/06ceabe93f587f1085fc5e5887f2b4e748de017a..main#diff-5c8f1932b7622795200ea94aa34a434df0ce530f5a67de408abc6f5c3d25b423) crates/native_blockifier/src/errors.rs

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1515)* status: 31 of 32 files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1515#-:-NqfNFM61Djj8e2tj1rK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dorimedini-starkware, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1515#-NqfNGwG8smE6uG5Ft_Z:-NqfNGwG8smE6uG5Ft__:be2ci16) (no related file):*
Don't forget to merge and not squash.

___

**Comment by barak-b-starkware** [comment]
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Don't forget to merge and not squash.
</blockquote></details>

No problem (:

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1515)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1486 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1515#-Nqg2U6B0fVF9vqCUFTp:-Nqg2U6B0fVF9vqCUFTq:b-hbszq6) ([raw file](https://github.com/starkware-libs/blockifier/blob/cb8be2efec081250968bd8042e796862647a6349/crates/blockifier/src/transaction/transactions_test.rs#L1486)):*
> ```XML
> 
>     // TODO(Aner, 14/4/24): Cover positive flows of Cairo 0 syscalls: get_block_number and
>     // get_block_timestamp.
> ```

The resolution of this TODO was already covered in `main-v0.13.1`.



_Code quote:_
```XML
    // TODO(Aner, 14/4/24): Cover positive flows of Cairo 0 syscalls: get_block_number and
    // get_block_timestamp.
```

**Pull request closed without merging**
