### PR TITLE
feat(fee): add GasVector to TransactionExecutionInfo

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-NpP0QDz8k6p39TAjyRB:-NpP0QDz8k6p39TAjyRC:b-2zptrf) (no related file):*
[py side](https://reviewable.io/reviews/starkware-industries/starkware/33677)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-NpPTqZS1a-xdQBPiK5H:-NpPTqZS1a-xdQBPiK5I:b3q02bi) ([raw file](https://github.com/starkware-libs/blockifier/blob/b858eeaabcb7725f7b88de0a53b1dcb23af21af3/crates/blockifier/src/fee/gas_usage.rs#L56)):*
> ```XML
>             .expect("Blob gas for DA conversion failed."),
>     }
> }
> ```

this should be in a separate PR, but I needed it now...



_Code quote:_
```XML
pub fn calculate_da_gas_usage(
    state_changes_count: StateChangesCount,
    use_kzg_da: bool,
) -> GasVector {
    GasVector {
        l1_gas: if use_kzg_da {
            0
        } else {
            u128_from_usize(get_onchain_data_cost(state_changes_count))
                .expect("Onchain DA segment length conversion failure.")
        },
        blob_gas: u128_from_usize(calculate_tx_blob_gas_usage(state_changes_count, use_kzg_da))
            .expect("Blob gas for DA conversion failed."),
    }
}
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/fee/gas_usage.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-NpPTqZS1a-xdQBPiK5H:-NpUFuaE8XXOaE0JY4Yo:bieoyf5) ([raw file](https://github.com/starkware-libs/blockifier/blob/b858eeaabcb7725f7b88de0a53b1dcb23af21af3/crates/blockifier/src/fee/gas_usage.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should be in a separate PR, but I needed it now...
</blockquote></details>

I don't follow. Is someone working on that PR?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-NpPTqZS1a-xdQBPiK5H:-NpUKUyU41ob-TdvtLF3:bbf0r3v) ([raw file](https://github.com/starkware-libs/blockifier/blob/b858eeaabcb7725f7b88de0a53b1dcb23af21af3/crates/blockifier/src/fee/gas_usage.rs#L56)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I don't follow. Is someone working on that PR?
</blockquote></details>

I'll do it. it will take time to get this PR in anyway

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-NpPTqZS1a-xdQBPiK5H:-NpUljM-5zXk07pjulOP:b-d9zbw) ([raw file](https://github.com/starkware-libs/blockifier/blob/b858eeaabcb7725f7b88de0a53b1dcb23af21af3/crates/blockifier/src/fee/gas_usage.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I'll do it. it will take time to get this PR in anyway
</blockquote></details>

[here](https://reviewable.io/reviews/starkware-libs/blockifier/1408)

**Comment by aner-starkware** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[py side](https://reviewable.io/reviews/starkware-industries/starkware/33677)
</blockquote></details>

Pls add `py_module.add_class::<PyGasVector>()?;` to native blockifier in  `crates/native_blockifier/src/lib.rs`

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/lib.rs` line 51 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-NpVKQbBAk1cef1T6oY6:-NpVKQbBAk1cef1T6oY7:b-vkp1iw) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb30f51ca6d60b2271ff2ee298b548858751b364/crates/native_blockifier/src/lib.rs#L51)):*
> ```XML
>     py_module.add_class::<PyValidator>()?;
>     py_module.add_class::<PyVmExecutionResources>()?;
>     py_module.add_class::<PyBouncerInfo>()?;
> ```

alphabetized



_Code quote:_
```XML
py_module.add_class::<PyBouncerInfo>()?;
```

**Review by ArniStarkware — COMMENTED** [review]
I just rebased over 0.13.1 to resolve conflicts.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-:-NpZKbKY6eCfrH1pCXkO:b-mmcjur)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @elintul and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: 1 of 10 files reviewed, all discussions resolved (waiting on @elintul and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npp-fSMEfvO_5XhTsby:-Npp-fSMEfvO_5XhTsbz:b14bj48) (no related file):*
[actual py side](https://reviewable.io/reviews/starkware-industries/starkware/33708#-)

___

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 9 files at r3, 1 of 8 files at r5, 1 of 8 files at r6, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 6 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npp34HL4XmkeSq3UPnn:-Npp34HL4XmkeSq3UPno:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9851855a5bc637b48e95272127bcba90757055d/crates/blockifier/src/fee/actual_cost.rs#L6)):*
> ```XML
> use starknet_api::transaction::Fee;
> 
> use super::gas_usage::get_da_gas_cost;
> ```





_Suggestion:_
```XML
crate
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 25 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npp6rOM4Aijksp1NlS7:-Npp6rOM4Aijksp1NlS8:b150vej) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9851855a5bc637b48e95272127bcba90757055d/crates/blockifier/src/fee/actual_cost.rs#L25)):*
> ```XML
> pub struct ActualCost {
>     pub actual_fee: Fee,
>     pub da_gas: GasVector,
> ```

Don't we always use exactly one of them? Why keep two entries?



_Code quote:_
```XML
GasVector
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 56 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npp7Jyo2yqUIxTcwune:-Npp7JypDNf-jlZDNbSa:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9851855a5bc637b48e95272127bcba90757055d/crates/native_blockifier/src/py_transaction_execution_info.rs#L56)):*
> ```XML
> 
> impl From<GasVector> for PyGasVector {
>     fn from(value: GasVector) -> Self {
> ```





_Suggestion:_
```XML
gas_vector
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 25 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npp6rOM4Aijksp1NlS7:-NppAI2BB5JPTjxtd9FC:b-s6atwe) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9851855a5bc637b48e95272127bcba90757055d/crates/blockifier/src/fee/actual_cost.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Don't we always use exactly one of them? Why keep two entries?
</blockquote></details>

you will need two entries anyway: an amount, and some indication of what the amount represents.
using vectors is simplest.
Also, it conforms to the spec (DA cost in this format, except we should say "l1_data_gas" (in response objects) instead of "blob_gas")

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-:-NprpU0p3sgpVI4F0oqc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by elintul — DISMISSED** [review]
> Reviewed 10 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1497 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npsj5rbA6kAZkU6hXWx:-Npsj5rbA6kAZkU6hXWy:ba854ie) ([raw file](https://github.com/starkware-libs/blockifier/blob/0083b294618df164c0b174a668e4a7ee86a43682/crates/blockifier/src/transaction/transactions_test.rs#L1497)):*
> ```XML
>     );
> 
>     // A tx that changes the account and sl1_data_gasr balance in execute.
> ```

Revert?



_Code quote:_
```XML
sl1_data_gasr 
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: 8 of 16 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1497 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npsj5rbA6kAZkU6hXWx:-NpslM7w9SJ-RECDtmuU:bj6oro1) ([raw file](https://github.com/starkware-libs/blockifier/blob/0083b294618df164c0b174a668e4a7ee86a43682/crates/blockifier/src/transaction/transactions_test.rs#L1497)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Revert?
</blockquote></details>

how did this happen
vscode is weird

**Review by elintul — DISMISSED** [review]
> Reviewed 7 of 8 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 9 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Comment by aner-starkware** [comment]
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 61 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npy2Jxh6Rustt7TVMTT:-Npy2Jxh6Rustt7TVMTU:b7zkx12) ([raw file](https://github.com/starkware-libs/blockifier/blob/5fa3e447a08daf219b0875f728791be6a7ab2ef6/crates/native_blockifier/src/py_transaction_execution_info.rs#L61)):*
> ```XML
> impl From<GasVector> for PyGasVector {
>     fn from(gas_vector: GasVector) -> Self {
>         Self { l1_gas: gas_vector.l1_gas, blob_gas: gas_vector.l1_data_gas }
> ```

If we already changed it to `l1_data_gas` everywhere, why leave it `blob_gas` here?



_Code quote:_
```XML
    #[pyo3(get)]
    pub blob_gas: u128,
}

impl From<GasVector> for PyGasVector {
    fn from(gas_vector: GasVector) -> Self {
        Self { l1_gas: gas_vector.l1_gas, blob_gas: gas_vector.l1_data_gas }
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r5, 1 of 6 files at r9, 2 of 10 files at r10, 3 of 8 files at r11, 7 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Comment by ArniStarkware** [comment]
I rebased again over 0.13.1.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npylh5Z-t82Bygfn4w3:-Npylh5Z-t82Bygfn4w4:b-1wz8tc) (no related file):*
Blob or L1 data gas? 

___

**Comment by aner-starkware** [comment]
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 61 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-NpyqBae9soP91ik71iw:-NpyqBae9soP91ik71ix:bpn55kx) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8aeeca7fe441647732c215780c1e2c612027917/crates/native_blockifier/src/py_transaction_execution_info.rs#L61)):*
> ```XML
> impl From<GasVector> for PyGasVector {
>     fn from(value: GasVector) -> Self {
>         Self { l1_gas: value.l1_gas, blob_gas: value.blob_gas }
> ```

IIUC, this part isn't required anymore



_Code quote:_
```XML
#[pyclass]
#[derive(Clone)]
pub struct PyGasVector {
    #[pyo3(get)]
    pub l1_gas: u128,
    #[pyo3(get)]
    pub blob_gas: u128,
}

impl From<GasVector> for PyGasVector {
    fn from(value: GasVector) -> Self {
        Self { l1_gas: value.l1_gas, blob_gas: value.blob_gas }
```

**Comment by ArniStarkware** [comment]
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Blob or L1 data gas?
</blockquote></details>

My fault. Fixing it.

**Comment by ArniStarkware** [comment]
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

My fault. Fixing it.
</blockquote></details>

Fixed.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: 2 of 16 files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @elintul, and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 61 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npy2Jxh6Rustt7TVMTT:-Npz4gbyCPFrQpkxVKEy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5fa3e447a08daf219b0875f728791be6a7ab2ef6/crates/native_blockifier/src/py_transaction_execution_info.rs#L61)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

If we already changed it to `l1_data_gas` everywhere, why leave it `blob_gas` here?
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 61 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-NpyqBae9soP91ik71iw:-Npz4h3BAU-QOYR9TDUE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8aeeca7fe441647732c215780c1e2c612027917/crates/native_blockifier/src/py_transaction_execution_info.rs#L61)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

IIUC, this part isn't required anymore
</blockquote></details>

Done.

**Comment by aner-starkware** [comment]
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 63 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npz8lAr96CSiBJn8KoA:-Npz8lAr96CSiBJn8KoB:bnpu288) ([raw file](https://github.com/starkware-libs/blockifier/blob/83ef48972d43155764ed638e75989deb35f00b4c/crates/native_blockifier/src/py_transaction_execution_info.rs#L63)):*
> ```XML
>         Self { l1_gas: gas_vector.l1_gas, blob_gas: gas_vector.l1_data_gas }
>     }
> }
> ```

Are we removing this part?



_Code quote:_
```XML
#[pyclass]
#[derive(Clone)]
pub struct PyGasVector {
    #[pyo3(get)]
    pub l1_gas: u128,
    #[pyo3(get)]
    pub blob_gas: u128,
}

impl From<GasVector> for PyGasVector {
    fn from(gas_vector: GasVector) -> Self {
        Self { l1_gas: gas_vector.l1_gas, blob_gas: gas_vector.l1_data_gas }
    }
}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: 2 of 16 files reviewed, 5 unresolved discussions (waiting on @aner-starkware, @elintul, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npylh5Z-t82Bygfn4w3:-NpzHU8C-w66b4XodWV9:b-896fix) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Done.

___
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 8 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-NpylbNbAb9Xvv6oIWuh:-NpzH0uNAbyOAloDX-FT:b40v9x7) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8aeeca7fe441647732c215780c1e2c612027917/crates/blockifier/src/test_utils/struct_impls.rs#L8)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use `crate` and not `super` throughout the code.
</blockquote></details>

done except for Gilad's well-argued (second code block [here](https://doc.rust-lang.org/book/ch11-01-writing-tests.html#checking-results-with-the-assert-macro)) use case:

"""
Note that we’ve added a new line inside the `tests` module: `use super::*;`. The `tests` module is a regular module that follows the usual visibility rules we covered in Chapter 7 in the [“Paths for Referring to an Item in the Module Tree”](https://doc.rust-lang.org/book/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.html) section. Because the `tests` module is an inner module, we need to bring the code under test in the outer module into the scope of the inner module. We use a glob here so anything we define in the outer module is available to this `tests` module.
"""
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 63 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-Npz8lAr96CSiBJn8KoA:-NpzHSai7821H7OLhHmp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/83ef48972d43155764ed638e75989deb35f00b4c/crates/native_blockifier/src/py_transaction_execution_info.rs#L63)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Are we removing this part?
</blockquote></details>

Done.

**Review by elintul — DISMISSED** [review]
> Reviewed 9 of 13 files at r15, 2 of 5 files at r17, 1 of 1 files at r18, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 9 of 13 files at r15, 2 of 5 files at r17, 1 of 1 files at r18, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-:-Nq1zN1B6v5U8ZbjDD83:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399#-:-Nq2oVx-3XHjiwd1t1eV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1399)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
