### PR TITLE
Validate invoke transaction entry point.

### PR DESCRIPTION
**Pull request by Adi-Yakovian**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242)* status: all files reviewed, 2 unresolved discussions (waiting on @Adi-Yakovian and @alonh5)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/242#-NMdv1BHCYZmEM7cYAO_:-NMdv1BI5-M7WvwdIRJZ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c4d9ade0e176aa3f3272a71b31ba86e80e13f6d/crates/blockifier/src/transaction/account_transaction.rs#L74)):*
> ```XML
>             }
>             Self::Invoke(tx) => {
>                 // Specifying an entry point selector is not allowed for invoke transactions.
> ```





_Suggestion:_
```XML
// Specifying an entry point selector is not allowed;
// `__execute__` is called, and inner selector appears in the calldata.
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/242#-NMdvKskCbYdnLjOo_lV:-NMdvKskCbYdnLjOo_lW:b-v53drf) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c4d9ade0e176aa3f3272a71b31ba86e80e13f6d/crates/blockifier/src/transaction/errors.rs#L38)):*
> ```XML
>     #[error(transparent)]
>     StateError(#[from] StateError),
>     #[error(transparent)]
> ```

Keep alphabetized.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242)* status: all files reviewed, 3 unresolved discussions (waiting on @Adi-Yakovian)

___
*[`crates/blockifier/src/transaction/errors.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/242#-NMhDxpICdQf0Ync2ZnP:-NMhDxpICdQf0Ync2ZnQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c4d9ade0e176aa3f3272a71b31ba86e80e13f6d/crates/blockifier/src/transaction/errors.rs#L18)):*
> ```XML
> pub enum InvokeTransactionError {
>     #[error("Entry point selector must not be specified for an invoke transaction.")]
>     UnauthorizedEntryPoint,
> ```





_Suggestion:_
```XML
SpecifiedEntryPoint
```

**Review by Adi-Yakovian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/errors.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/242#-NMhDxpICdQf0Ync2ZnP:-NMhpPIJ7ENflm06dlwc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c4d9ade0e176aa3f3272a71b31ba86e80e13f6d/crates/blockifier/src/transaction/errors.rs#L18)):*
> ```XML
> pub enum InvokeTransactionError {
>     #[error("Entry point selector must not be specified for an invoke transaction.")]
>     UnauthorizedEntryPoint,
> ```

Done.
___
*[`crates/blockifier/src/transaction/errors.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/242#-NMdvKskCbYdnLjOo_lV:-NMhpQQdA2kOSUq3Pw4K:b-7z430k) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c4d9ade0e176aa3f3272a71b31ba86e80e13f6d/crates/blockifier/src/transaction/errors.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Keep alphabetized.
</blockquote></details>

Thanks! :)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242#-:-NMi2YWxB51Z-z8jMH2_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Adi-Yakovian and @elintul)

___
*[`crates/blockifier/src/transaction/errors.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/242#-NMi2MF6B_4q1UbgeM2F:-NMi2MF6B_4q1UbgeM2G:b-8pb7e) ([raw file](https://github.com/starkware-libs/blockifier/blob/41fb36f058e9a1530e22222948659b74cf6cb1b3/crates/blockifier/src/transaction/errors.rs#L15)):*
> ```XML
> }
> 
> #[derive(Error, Debug)]
> ```

Alphabetize these also.



_Suggestion:_
```XML
#[derive(Debug, Error)]
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242)* status: all files reviewed, 2 unresolved discussions (waiting on @Adi-Yakovian)

___
*[`crates/blockifier/src/transaction/errors.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/242#-NMiAUfO4SrhrH1Q4p_i:-NMiAUfO4SrhrH1Q4p_j:b-ubkcef) ([raw file](https://github.com/starkware-libs/blockifier/blob/41fb36f058e9a1530e22222948659b74cf6cb1b3/crates/blockifier/src/transaction/errors.rs#L36)):*
> ```XML
>     #[error(transparent)]
>     InvokeTransactionError(#[from] InvokeTransactionError),
>     #[error(transparent)]
> ```

Move before `InvokeTransactionError`.



_Code quote:_
```XML
    InvokeTransactionError(#[from] InvokeTransactionError),
    #[error(transparent)]
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242)* status: all files reviewed, 2 unresolved discussions (waiting on @Adi-Yakovian)

**Comment by Adi-Yakovian** [comment]
*[`crates/blockifier/src/transaction/errors.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/242#-NMiAUfO4SrhrH1Q4p_i:-NMiEIR82WWA8KN93Zn6:b-tjgs7z) ([raw file](https://github.com/starkware-libs/blockifier/blob/41fb36f058e9a1530e22222948659b74cf6cb1b3/crates/blockifier/src/transaction/errors.rs#L36)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move before `InvokeTransactionError`.
</blockquote></details>

What should I move?

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242)* status: all files reviewed, 1 unresolved discussion (waiting on @Adi-Yakovian)

___
*[`crates/blockifier/src/transaction/errors.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/242#-NMiAUfO4SrhrH1Q4p_i:-NMiGVbU8e7yq9s083C5:b2k3eas) ([raw file](https://github.com/starkware-libs/blockifier/blob/41fb36f058e9a1530e22222948659b74cf6cb1b3/crates/blockifier/src/transaction/errors.rs#L36)):*
<details><summary><i>Previously, Adi-Yakovian wrote…</i></summary><blockquote>

What should I move?
</blockquote></details>

I read "InvokeVersion" haha never mind.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242#-:-NMiGaWY12OVPA-7UoY-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Adi-Yakovian)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Adi-Yakovian)

**Pull request merged**
