### PR TITLE
Change `ContractClass`, add `DeprecatedContractClassWithoutAbi`.

### PR DESCRIPTION
**Pull request by elintul**
…outAbi`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSaZGD04iTLMhYwyy4l:-NSaZGD04iTLMhYwyy4m:b-hibo2z) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/blockifier/src/execution/contract_class.rs#L21)):*
> ```XML
> }
> 
> impl TryFrom<DeprecatedContractClass> for ContractClass {
> ```

For [get_contract_class()](https://github.com/starkware-libs/blockifier-old/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/blockifier/src/state/papyrus_state.rs#L72).



_Code quote:_
```XML
impl TryFrom<DeprecatedContractClass> for ContractClass
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSaZ_Vf19I0vB5ImNPN:-NSaZ_Vf19I0vB5ImNPO:b-7nmaea) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/blockifier/src/execution/contract_class.rs#L33)):*
> ```XML
> }
> 
> impl TryFrom<DeprecatedContractClassWithoutAbi> for ContractClass {
> ```

For `TryFrom<&str>` and `TryFrom<std::path::PathBuf>` below, that go through `DeprecatedContractClassWithoutAbi`.



_Code quote:_
```XML
impl TryFrom<DeprecatedContractClassWithoutAbi> for ContractClass
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSaZl9444u3ZUtiALnt:-NSaZl9444u3ZUtiALnu:b-kshwcx) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/blockifier/src/execution/contract_class.rs#L44)):*
> ```XML
> }
> 
> impl TryFrom<&str> for ContractClass {
> ```

For when receiving a raw declare [from Python](https://github.com/starkware-libs/blockifier-old/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/native_blockifier/src/py_transaction.rs#L179).



_Code quote:_
```XML
impl TryFrom<&str> for ContractClass
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSa_5CuBYxPAkdBCHXH:-NSa_5CuBYxPAkdBCHXI:blsfoiy) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/blockifier/src/execution/contract_class.rs#L72)):*
> ```XML
> }
> 
> impl From<DeprecatedContractClassWithoutAbi> for DeprecatedContractClass {
> ```

For [appending state diff.](https://github.com/starkware-libs/blockifier-old/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/native_blockifier/src/storage.rs#L108), that goes through `DeprecatedContractClassWithoutAbi`.



_Code quote:_
```XML
impl From<DeprecatedContractClassWithoutAbi> for DeprecatedContractClass
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSaZuTOEmzn5efQXe3X:-NSaZuTOEmzn5efQXe3Y:b-8lmhsr) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/blockifier/src/execution/contract_class.rs#L82)):*
> ```XML
> }
> 
> impl TryFrom<&str> for DeprecatedContractClassWithoutAbi {
> ```

For [appending state diff.](https://github.com/starkware-libs/blockifier-old/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/native_blockifier/src/storage.rs#L108).



_Code quote:_
```XML
impl TryFrom<&str> for DeprecatedContractClassWithoutAbi
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSa_ADH3Tzfh0V2ugD3:-NSa_ADH3Tzfh0V2ugD4:bp5auls) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/blockifier/src/execution/contract_class.rs#L105)):*
> ```XML
>         let mut file =
>             std::fs::File::open(&path).unwrap_or_else(|_| panic!("File {path:?} does not exist."));
>         let mut raw_contract_class = String::new();
> ```

Better suggestion?



_Code quote:_
```XML
        let mut raw_contract_class = String::new();
        file.read_to_string(&mut raw_contract_class).expect("Malformed class JSON.");
```
___
*[`crates/blockifier/src/state/papyrus_state_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSa_FeF5l1PQq-gPb0B:-NSa_FeF5l1PQq-gPb0C:bupgj08) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/blockifier/src/state/papyrus_state_test.rs#L25)):*
> ```XML
> 
> #[test]
> fn test_entry_point_with_papyrus_state() {
> ```

Better suggestion for all the ugliness going on here?



_Code quote:_
```XML
test_entry_point_with_papyrus_state
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 180 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSa_SdT547QED-zxtGg:-NSa_SdT547QED-zxtGh:bp5auls) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/native_blockifier/src/py_transaction.rs#L180)):*
> ```XML
>                 .expect("A contract class must be passed in a Declare transaction.");
>             let contract_class = ContractClass::try_from(raw_contract_class).map_err(|err| {
>                 NativeBlockifierError::from(NativeBlockifierInputError::from(err))
> ```

Better suggestion?



_Code quote:_
```XML
            let contract_class = ContractClass::try_from(raw_contract_class).map_err(|err| {
                NativeBlockifierError::from(NativeBlockifierInputError::from(err))
            })?;
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 13 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: 9 of 13 files reviewed, 13 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSa_ADH3Tzfh0V2ugD3:-NSdtn_aExQfB3qzV8ZY:b-qjfsw7) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/blockifier/src/execution/contract_class.rs#L105)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Better suggestion?
</blockquote></details>

I tihnk you has fs::read_file_contents or something like that
___
*[`crates/blockifier/src/execution/contract_class.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSdsxVT4hvADWDXBTVW:-NSdsxVT4hvADWDXBTVX:b-j1gzh5) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/contract_class.rs#L21)):*
> ```XML
> }
> 
> impl TryFrom<DeprecatedContractClass> for ContractClass {
> ```

Consider making some of these try_intos into explicit ctors. e.g.
```
impl ContractClass {
  pub fn deserialize_from_str(...)
}
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSdtD78BoyAi5wBEBiG:-NSdtD78BoyAi5wBEBiH:b-wyrz1w) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/contract_class.rs#L55)):*
> ```XML
> 
> #[cfg(any(feature = "testing", test))]
> impl TryFrom<std::path::PathBuf> for ContractClass {
> ```

Especially this, it looks weird convertinf from path. One of the reasons is that this has side effects, and try_into() hides it. try_into() should mostly be to change representation between things that hold the same info.
Explicit is good.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSdtVZ24e-ch16CgROv:-NSdtVZ24e-ch16CgROw:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/contract_class.rs#L64)):*
> ```XML
> }
> 
> /// Represents a raw StarkNet contract class (non-runnable;
> ```





_Suggestion:_
```XML
ss (non-runnable),
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSdtavs2RCaUS-P7l-S:-NSdtavs2RCaUS-P7l-T:b-dh5xqh) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/contract_class.rs#L82)):*
> ```XML
> }
> 
> impl TryFrom<&str> for DeprecatedContractClassWithoutAbi {
> ```

This too
___
*[`crates/blockifier/src/execution/contract_class.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSdtcRxCgmUQPIooaSZ:-NSdtcRxCgmUQPIooaS_:b-ejnhgp) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/contract_class.rs#L101)):*
> ```XML
> 
> #[cfg(any(feature = "testing", test))]
> impl From<std::path::PathBuf> for DeprecatedContractClassWithoutAbi {
> ```

this too
___
*[`crates/native_blockifier/src/py_transaction.rs` line 180 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSa_SdT547QED-zxtGg:-NSdupiYEMidgs9toxvM:b5c4eqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/native_blockifier/src/py_transaction.rs#L180)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Better suggestion?
</blockquote></details>

Use thiserror and wrap this error? Implement from for this error?

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 2 of 4 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: all files reviewed, 13 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: all files reviewed, 13 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSdsxVT4hvADWDXBTVW:-NSdvb6CC3UCRBg9kRHe:b-58ww59) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/contract_class.rs#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider making some of these try_intos into explicit ctors. e.g.
```
impl ContractClass {
  pub fn deserialize_from_str(...)
}
```
</blockquote></details>

Is this more idiomatic? I thought using `[Try]From` is.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: all files reviewed, 13 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSdsxVT4hvADWDXBTVW:-NSe3dmJARJY5OfjI2zF:b-mtubmy) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/contract_class.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this more idiomatic? I thought using `[Try]From` is.
</blockquote></details>

You are being obscure and hiding things that are not trivial representation conversion.
Explicit is good. See my comment below. Thing about the reader.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: all files reviewed, 13 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSaZl9444u3ZUtiALnt:-NSe43r01P1ceDmqv22u:b-mmnzqw) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/blockifier/src/execution/contract_class.rs#L44)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

For when receiving a raw declare [from Python](https://github.com/starkware-libs/blockifier-old/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/native_blockifier/src/py_transaction.rs#L179).
</blockquote></details>

It's good that your explaining in the PR, but it's better if it's understable from the code.
Making this function explicit (not throught try_into) with an indicative function name can do that.
Oterhwise, comments in the code can do that.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: all files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSeAnMU7H4C3nAYkDjT:-NSeAnMU7H4C3nAYkDjU:b-9c9vx1) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/contract_class.rs#L50)):*
> ```XML
>         let deprecated_contract_class =
>             DeprecatedContractClassWithoutAbi::try_from(raw_contract_class)?;
>         ContractClass::try_from(deprecated_contract_class)
> ```

Looks like `serde` ignores extra-fields when deserializing, so I think the recommendation below works.

If this is readable,  then it might be short enough to make `DeprecatedContractClassWithoutAbi` no longer necessary.
The only other usage we had for this struct was in `papyrus_state_test.rs`, which can replace the `...WithoutAbi` cast with a similar method to the test_utils `get_contract_class`:
```rust
pub fn get_deprecated_contract_class(contract_path: &str) -> DeprecatedContractClass {
    let deprecated_contract_class = fs::read_to_string(contract_path).expect("Should be readable");
    serde_json::from_str(deprecated_contract_class.as_str()).expect("File must contain the content of a compiled contract")
 }
```



_Suggestion:_
```XML
        let contract_class_with_abi = serde_json::to_value(raw_contract_class)?;
        // Ignores the `abi` field
        Ok(serde_json::from_value(contract_class_with_abi)?)
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 106 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSds5Bs7PqpS93U7K6B:-NSds5Bt9zvdQjsV5Skd:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/contract_class.rs#L106)):*
> ```XML
>             std::fs::File::open(&path).unwrap_or_else(|_| panic!("File {path:?} does not exist."));
>         let mut raw_contract_class = String::new();
>         file.read_to_string(&mut raw_contract_class).expect("Malformed class JSON.");
> ```





_Suggestion:_
```XML
        let raw_contract_class = fs::read_to_string(path).expect("Malformed class JSON.");
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 180 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSa_SdT547QED-zxtGg:-NSdyFaO3PIgsuMA8Hcf:bk7xcmw) ([raw file](https://github.com/starkware-libs/blockifier/blob/54941b49df0bedb9b8cda081d81556387599292e/crates/native_blockifier/src/py_transaction.rs#L180)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Use thiserror and wrap this error? Implement from for this error?
</blockquote></details>

Yep we have it in `thiserror`, so we can do:
```rust
let contract_class = ContractClass::try_from(raw_contract_class).map_err(NativeBlockifierInputError::from)?;
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSeAnMU7H4C3nAYkDjT:-NSeNVZnAWlbf2JuVcul:btpm2f3) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/contract_class.rs#L50)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Looks like `serde` ignores extra-fields when deserializing, so I think the recommendation below works.

If this is readable,  then it might be short enough to make `DeprecatedContractClassWithoutAbi` no longer necessary.
The only other usage we had for this struct was in `papyrus_state_test.rs`, which can replace the `...WithoutAbi` cast with a similar method to the test_utils `get_contract_class`:
```rust
pub fn get_deprecated_contract_class(contract_path: &str) -> DeprecatedContractClass {
    let deprecated_contract_class = fs::read_to_string(contract_path).expect("Should be readable");
    serde_json::from_str(deprecated_contract_class.as_str()).expect("File must contain the content of a compiled contract")
 }
```
</blockquote></details>

Retracting, missed something...

**Review by giladchase — COMMENTED** [review]
> Reviewed 8 of 13 files at r1, 3 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: all files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @spapinistarkware)

___
*[`crates/blockifier/src/state/papyrus_state_test.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSfoLef5DIZCXmk4vXj:-NSfoLef5DIZCXmk4vXk:bp7dyol) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8b5dd7d1fad0b4469dd6c7ccf8f7d2ee6d2b719/crates/blockifier/src/state/papyrus_state_test.rs#L22)):*
> ```XML
> 
> #[test]
> fn test_entry_point_with_papyrus_state() -> papyrus_storage::StorageResult<()> {
> ```

Why don't we want it to return an error?



_Code quote:_
```XML
 papyrus_storage::StorageResult<()>
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: all files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 329 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSfohKg7qo1VUN3jCEi:-NSfohKh1hWuqraap2cC:bnymtjb) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfaa1d3cb4ede64c2922468d9e97f470af820bcf/crates/blockifier/src/execution/execution_utils.rs#L329)):*
> ```XML
> 
> // TODO(Elin,01/05/2023): aim to use LC's implementation once it's in a separate crate.
> pub fn sn_api_to_cairo_vm_program(program: DeprecatedProgram) -> Result<Program, ProgramError> {
> ```

This is only used by `ContractClass`, consider moving it there.



_Code quote:_
```XML
sn_api_to_cairo_vm_program
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/393)* status: all files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/393#-NSqp9-b5LPlgP2WPwwp:-NSqp9-c1ZcyuiGdpYDV:b-2du1y2) (no related file):*
Let's merge this please

___

**Pull request closed without merging**
