### PR TITLE
test: remove the test util create_account_tx_test_state

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1606)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1606#-:-NrvtezP5q4ydLibqrOG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1933 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1606#-Nrvt_AMCbd2So7Z8gcl:-Nrvt_AMCbd2So7Z8gcm:b-q3surm) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb8c11409a2378d0b2ce9cf98fd91730071d2649/crates/blockifier/src/transaction/transactions_test.rs#L1933)):*
> ```XML
>     let execute_calldata = Calldata(
>         [
>             vec![StarkFelt::from(test_contract.get_instance_address(0))],
> ```

can you use `into()` or `stark_felt!`?



_Code quote:_
```XML
StarkFelt::from(test_contract.get_instance_address(0))
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1933 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1606#-Nrvt_AMCbd2So7Z8gcl:-Nrw0YfM2WnAw0QYug-i:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb8c11409a2378d0b2ce9cf98fd91730071d2649/crates/blockifier/src/transaction/transactions_test.rs#L1933)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you use `into()` or `stark_felt!`?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1606)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1606#-:-NryQJVp5HbT4y3KkIL3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
