### PR TITLE
refactor(concurrency): move commit_chunk API to ThreadSafeVersionedState

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1926)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1926)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-Nz77JJlCNjNm5bN4ftA:-Nz77JJlCNjNm5bN4ftB:bivgvgb) ([raw file](https://github.com/starkware-libs/blockifier/blob/41a7e1e94f9559a92469030bcd3c5979cc07f133/crates/blockifier/src/concurrency/versioned_state.rs#L78)):*
> ```XML
>     fn commit_chunk(
>         &mut self,
>         chunk_size: usize,
> ```

I think that something with `index` is better than `chunk_size`



_Suggestion:_
```XML
    fn commit(
        &mut self,
        index: usize,
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-Nz779S36LOa6FJTERW8:-Nz779S44VgB6K9Y4Qf2:b2jo0ji) ([raw file](https://github.com/starkware-libs/blockifier/blob/41a7e1e94f9559a92469030bcd3c5979cc07f133/crates/blockifier/src/concurrency/versioned_state.rs#L79)):*
> ```XML
>         &mut self,
>         chunk_size: usize,
>         parent_state: Arc<Mutex<CachedState<impl StateReader>>>,
> ```

I this a better practice for this case?



_Code quote:_
```XML
impl StateReader
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-Nz77w6D1siQGoJTxNcs:-Nz77w6D1siQGoJTxNct:b-xceed5) ([raw file](https://github.com/starkware-libs/blockifier/blob/41a7e1e94f9559a92469030bcd3c5979cc07f133/crates/blockifier/src/concurrency/versioned_state.rs#L217)):*
> ```XML
>     }
> 
>     // TODO(barak, 01/07/2024): Re-consider where to place the 'commit_chunk' API.
> ```

I think it should be near `validate_reads`/`delete_writes` etc, for consistency



_Code quote:_
```XML
// TODO(barak, 01/07/2024): Re-consider where to place the 'commit_chunk' API.
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1926)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-Nz77JJlCNjNm5bN4ftA:-Nz7d1gC880AzqjCUp1B:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/41a7e1e94f9559a92469030bcd3c5979cc07f133/crates/blockifier/src/concurrency/versioned_state.rs#L78)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think that something with `index` is better than `chunk_size`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-Nz779S36LOa6FJTERW8:-Nz7fjcJ8hvFyac_zLdu:b-9j1poh) ([raw file](https://github.com/starkware-libs/blockifier/blob/41a7e1e94f9559a92469030bcd3c5979cc07f133/crates/blockifier/src/concurrency/versioned_state.rs#L79)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I this a better practice for this case?
</blockquote></details>

I like it more when possible.
BTW, it's different in some senses; the generic `T` is more robust: for example, when trying to "collect" things into parameter functions, you need a generic. The `impl <trait>` is cleaner IMO and stricter, so it's better to use it if possible. WDYT?
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-Nz77w6D1siQGoJTxNcs:-Nz7h5SY0r5LmhxAYxiF:bxtjs6z) ([raw file](https://github.com/starkware-libs/blockifier/blob/41a7e1e94f9559a92469030bcd3c5979cc07f133/crates/blockifier/src/concurrency/versioned_state.rs#L217)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think it should be near `validate_reads`/`delete_writes` etc, for consistency
</blockquote></details>

I talked about it with @noaov1 offline. The `ThreadSafeVersionedState`, `VersionedStateProxy`, and `VersionedState` are three structs that I think we need to re-arrange API-wise.
Do you want me to rephrase the comment?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1926)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-Nz779S36LOa6FJTERW8:-Nz8-B5t59lgeLQibapT:b7s7fkx) ([raw file](https://github.com/starkware-libs/blockifier/blob/41a7e1e94f9559a92469030bcd3c5979cc07f133/crates/blockifier/src/concurrency/versioned_state.rs#L79)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I like it more when possible.
BTW, it's different in some senses; the generic `T` is more robust: for example, when trying to "collect" things into parameter functions, you need a generic. The `impl <trait>` is cleaner IMO and stricter, so it's better to use it if possible. WDYT?
</blockquote></details>

Cool :)

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1926)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-Nz79eDG8cj8I6USBch-:-Nz8xvTqCBS3aq8aFKZ5:b-jiuclx) ([raw file](https://github.com/starkware-libs/blockifier/blob/41a7e1e94f9559a92469030bcd3c5979cc07f133/crates/blockifier/src/concurrency/versioned_state.rs#L79)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Actually, this is enough - you're supposed to call this method from the main thread.
For the same reason, you don't need to impl the `commit` method in the thread-safe state.

Another option: impl this method just for VersionedState where S is a CachedState, and then you don't need to pass the parent state. If you do that, this method should drop self (the VersionedState)
</blockquote></details>

We have two options:
1. Change the parameter type of the `commit` method (as you suggested) and then use `&mut *self.block_state.lock().expect("Failed to lock execution output.")` when calling `commit` (in [PR 6](https://reviewable.io/reviews/starkware-libs/blockifier/1929)) from the `execute_chunk`.
2. Leave the parameter type of the `commit` method as is and use `Arc::clone(&self.block_state))` when calling `commit` (in [PR 6](https://reviewable.io/reviews/starkware-libs/blockifier/1929)) from the `execute_chunk`.

Since we've agreed that the block state should be with wrapped by `Arc<Mutex<_>>`, I vote for option 2.

Re - "where S is a CachedState": How would you do that? `CachedState` isn't a trait
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-Nz77w6D1siQGoJTxNcs:-Nz8xdgk9O5uHUgByn7q:b3nn6c8) ([raw file](https://github.com/starkware-libs/blockifier/blob/41a7e1e94f9559a92469030bcd3c5979cc07f133/crates/blockifier/src/concurrency/versioned_state.rs#L217)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I talked about it with @noaov1 offline. The `ThreadSafeVersionedState`, `VersionedStateProxy`, and `VersionedState` are three structs that I think we need to re-arrange API-wise.
Do you want me to rephrase the comment?
</blockquote></details>

The comment was moved and rephrased.

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1926)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-NzES6Rl9lLuIhcXtjkX:-NzES6Rl9lLuIhcXtjkY:b-j9g2c8) ([raw file](https://github.com/starkware-libs/blockifier/blob/898197466fe5778d502b1214550a015f4e945199/crates/blockifier/src/concurrency/versioned_state.rs#L82)):*
> ```XML
>     pub fn commit(
>         &mut self,
>         index: TxIndex,
> ```

The new name is a bit confusing.
Note that it commits up to and including the specified index, not just the index.



_Code quote:_
```XML
index
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-NzET3lS-OSktDgEEVut:-NzET3lS-OSktDgEEVuu:b-k3ph1b) ([raw file](https://github.com/starkware-libs/blockifier/blob/898197466fe5778d502b1214550a015f4e945199/crates/blockifier/src/concurrency/versioned_state.rs#L83)):*
> ```XML
>         &mut self,
>         index: TxIndex,
>         parent_state: Arc<Mutex<CachedState<impl StateReader>>>,
> ```

Can you clarify why the Mutex was added?
I think `commit_chuck` would be run by the main thread.



_Code quote:_
```XML
Mutex
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1926#-NzERqfv7GpsEWMjMOwG:-NzERqfv7GpsEWMjMOwH:b-7od2oc) ([raw file](https://github.com/starkware-libs/blockifier/blob/898197466fe5778d502b1214550a015f4e945199/crates/blockifier/src/concurrency/versioned_state.rs#L86)):*
> ```XML
>     ) {
>         let writes = self.get_writes_up_to_index(index);
>         parent_state.lock().expect("Failed to acquire state lock.").update_cache(&writes);
> ```

Add as a const.



_Code quote:_
```XML
Failed to acquire state lock.
```

**Pull request closed without merging**
