### PR TITLE
Refactor test_validate_accounts_tx to use create test state util.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1231)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1231)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 550 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-NlHwj4mAsaiO833gxYb:-NlHwj4mAsaiO833gxYc:b69o9tc) ([raw file](https://github.com/starkware-libs/blockifier/blob/07dc8845cac5688c048efb16437616a96dd7f488/crates/blockifier/src/transaction/account_transactions_test.rs#L550)):*
> ```XML
> fn test_fail_deploy_account(
>     block_context: BlockContext,
>     #[values(CairoVersion::Cairo0, CairoVersion::Cairo1)] cairo_version: CairoVersion,
> ```

nice!
free coverage!



_Code quote:_
```XML
#[values(CairoVersion::Cairo0, CairoVersion::Cairo1)]
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 315 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-NlHwzxPCGt7CvW25PX-:-NlHwzxPCGt7CvW25PX0:bnc47zb) ([raw file](https://github.com/starkware-libs/blockifier/blob/07dc8845cac5688c048efb16437616a96dd7f488/crates/blockifier/src/transaction/test_utils.rs#L315)):*
> ```XML
>                 sender_address,
>                 signature,
>                 nonce: nonce_manager.next(sender_address)
> ```

why is this needed now...? or was it just a mistake before?



_Code quote:_
```XML
nonce: nonce_manager.next(sender_address)
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1130 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl4-QmjAOZi31MMx6kr:-NlHyJlU9LdDa0YHAmiK:b-aep8m) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/transactions_test.rs#L1130)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do not hard-code cairo version mid-test - `test_contract_cairo_version` should be defined at the start of the test and used here
</blockquote></details>

ok, but... see above comment... sorry
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1110 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-NlHxVtJBrgav28EXCgP:-NlHxVtJBrgav28EXCgQ:b-3ymd4f) ([raw file](https://github.com/starkware-libs/blockifier/blob/07dc8845cac5688c048efb16437616a96dd7f488/crates/blockifier/src/transaction/transactions_test.rs#L1110)):*
> ```XML
>     let account_balance = 0;
>     let faulty_account = FeatureContract::FaultyAccount(cairo_version);
>     let test_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
> ```

either pass this to contract to `test_state` (ATM it's not declared and deployed), or, use a dummy value as the target contract address instead of using the test_contract address.
ATM it's unclear that this contract will never be invoked



_Code quote:_
```XML
test_contract
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1112 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-NlHyD55CThXnOoRcBmu:-NlHyD55CThXnOoRcBmv:bb7phvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/07dc8845cac5688c048efb16437616a96dd7f488/crates/blockifier/src/transaction/transactions_test.rs#L1112)):*
> ```XML
>     let test_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
>     let instance_id_for_negative_scenarios = 0;
>     let instance_id_for_posative_scenarios = 1;
> ```

typo



_Suggestion:_
```XML
instance_id_for_positive_scenarios
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1231)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @MohammadNassar1, and @noaov1)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1231)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 562 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl40BmVCPAtgl93JFtJ:-NlHj1xK7hvM_7YXfrW3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/account_transactions_test.rs#L562)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

since I commented below anyway, while you're here...
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 301 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl3xRzzAo-OG3Hsm0o3:-NlHihTr4TM3bWAQqgR1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/test_utils.rs#L301)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. the test should control the cairo version (so it's easy to parametrize).
2. instead of address, I would send contract and instance_id.
you are creating the faulty contract in `test_validate_accounts_tx` (with an explicit cairo version), so you are getting a double point of truth with the cairo version. I think it's good practice that each test creates it's own `FeatureContract` instances
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl3zaNw3EVrYnjKqkVQ:-NlHjfSKAyIm5PguNoVh:bp4z598) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/test_utils.rs#L313)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add `test_contract_cairo_version` as additional input to this function
</blockquote></details>

Anything related to the test contract should not be a parameter of this function. This contract is not related to the logic of this util.
Also - this parameter is only relevant for the test on `declare` (it is odd to have this parameter when testing invoke / deploy-account). 
I see why this is unclean, though...
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl3xr866YqaHJWghiQM:-NlHtTsk-pS9dW2osShp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/test_utils.rs#L321)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

grammar
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 315 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-NlHwzxPCGt7CvW25PX-:-NlHzoA54ln7ra0UuJWA:b-mtp5aw) ([raw file](https://github.com/starkware-libs/blockifier/blob/07dc8845cac5688c048efb16437616a96dd7f488/crates/blockifier/src/transaction/test_utils.rs#L315)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed now...? or was it just a mistake before?
</blockquote></details>

I think it was a mistake before.
This allows us to have two instances - and not three.
This allows us to use the same positive scenario instance for both scenarios - for the declare and invoke (There is only one positive scenario in the deploy account).
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1101 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl4-mIvAUn8RgDZz0pK:-NlHafQ_0y6bcmb9A9ye:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/transactions_test.rs#L1101)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please define variables for (give names to) the instance IDs you use
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1107 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl3znESAr35p50Amz3q:-NlHaglR9W6uJXp2TPbZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/transactions_test.rs#L1107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl4-aTy3QR4-xV0nKmm:-NlHaieM-ezVuW3JR7c9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/transactions_test.rs#L1110)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you still need 5? maybe only 2?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1126 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl4-LsX-7NxwTPO4IIq:-NlHh1dT9UHZyR6QFKIt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/transactions_test.rs#L1126)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1130 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl4-QmjAOZi31MMx6kr:-NlHh8l27zCNiQRAVtBS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/transactions_test.rs#L1130)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, but... see above comment... sorry
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1147 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl4-ZhbAv-tUaCTx-Sa:-NlHh9cK7_LghMF993q8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/transactions_test.rs#L1147)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1110 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-NlHxVtJBrgav28EXCgP:-NlI42xED8vIuEPnqda2:bvpa56f) ([raw file](https://github.com/starkware-libs/blockifier/blob/07dc8845cac5688c048efb16437616a96dd7f488/crates/blockifier/src/transaction/transactions_test.rs#L1110)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

either pass this to contract to `test_state` (ATM it's not declared and deployed), or, use a dummy value as the target contract address instead of using the test_contract address.
ATM it's unclear that this contract will never be invoked
</blockquote></details>

Done. Using a dummy value. 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1112 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-NlHyD55CThXnOoRcBmu:-NlI-Xpm-orFMU2pql_q:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/07dc8845cac5688c048efb16437616a96dd7f488/crates/blockifier/src/transaction/transactions_test.rs#L1112)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1231)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl3zaNw3EVrYnjKqkVQ:-NlI5NcZAJ9uQvVcW2dW:bq6nrfx) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/test_utils.rs#L313)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Anything related to the test contract should not be a parameter of this function. This contract is not related to the logic of this util.
Also - this parameter is only relevant for the test on `declare` (it is odd to have this parameter when testing invoke / deploy-account). 
I see why this is unclean, though...
</blockquote></details>

Now, `test_contract` does not play a role. My issue now is that it might seem like faulty account plays a role - which it does not...

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-:-NlI6Kza8izddMQRBOq-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl3zaNw3EVrYnjKqkVQ:-NlI5tS67Cme1v6l9wOl:b-kvuf7o) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/test_utils.rs#L313)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Now, `test_contract` does not play a role. My issue now is that it might seem like faulty account plays a role - which it does not...
</blockquote></details>

it does, IMO. the validate_test tests problematic validation, so the faulty account it built in to the initial state. the test_contract is not - no need for an actual other contract to test validate in some scenarios

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1231)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl3zaNw3EVrYnjKqkVQ:-NlI7DXJ5Yipjpa1UggZ:b-e0n7r4) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/test_utils.rs#L313)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it does, IMO. the validate_test tests problematic validation, so the faulty account it built in to the initial state. the test_contract is not - no need for an actual other contract to test validate in some scenarios
</blockquote></details>

Faulty account does not play this role.
It does not matter that the `class_hash` is that of faulty account, and it does not matter that the `contract_class` is either (see ` faulty_account.get_class()`). 
Both of these can be dummy values.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1231)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl3zaNw3EVrYnjKqkVQ:-NlI8X8JAQWpbQWIt3SH:bdwr5py) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/test_utils.rs#L313)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Faulty account does not play this role.
It does not matter that the `class_hash` is that of faulty account, and it does not matter that the `contract_class` is either (see ` faulty_account.get_class()`). 
Both of these can be dummy values.
</blockquote></details>

ah, so maybe add a comment that it doesn't matter

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1231)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1231#-Nl3zaNw3EVrYnjKqkVQ:-NlIQIPSE4pEZzUGgPdC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/448d0aefe898782a9241b9ab971f14ffb7130c89/crates/blockifier/src/transaction/test_utils.rs#L313)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, so maybe add a comment that it doesn't matter
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1231)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

**Pull request merged**
