### PR TITLE
Change code according to dependecies' changes.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKhYqF1t-k57T6LFFv:-NQKhYqF1t-k57T6LFFw:bllh6yb) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/entry_point_test.rs#L191)):*
> ```XML
>         &mut state,
>     );
> ```

Is this what we want? Is it as informative as the Pythonic VM errors?
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKhf-lEf9T8_TsCz0m:-NQKhf-lEf9T8_TsCz0n:b-t4h5qg) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/execution_utils.rs#L185)):*
> ```XML
> ) -> Result<CallInfo, PostExecutionError> {
>     let [retdata_size, retdata_ptr]: [MaybeRelocatable; 2] =
>         vm.get_return_values(2)?.try_into().expect("Return values must be of size 2.");
> ```

Please explain those changes.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKhYqF1t-k57T6LFFv:-NQKk1zY2dW6VUzA4dsS:b-voxbwv) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/entry_point_test.rs#L191)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this what we want? Is it as informative as the Pythonic VM errors?
</blockquote></details>

Yes, in python it's `Can only subtract two relocatable values of the same segment`, which is basically the same. I'm not sure why they chose the reword it.



_Code quote:_
```XML
test_subtraction_between_relocatables
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKhf-lEf9T8_TsCz0m:-NQKkmb1418QihfuI-td:b-olw3fn) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/execution_utils.rs#L185)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please explain those changes.
</blockquote></details>

They implemented `Sub<usize>` for relocatable, so now we can use the `-` operator.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKlMghC55B1dDhgvoH:-NQKlMghC55B1dDhgvoI:b-szpo21) ([raw file](https://github.com/starkware-libs/blockifier/blob/c2aeea0584d4637f6977d597bb2bce7cd2990565/crates/blockifier/src/execution/execution_utils.rs#L328)):*
> ```XML
> }
> 
> pub fn felt_from_memory_ptr(
> ```

I moved this function above `felt_range_from_ptr` and used `get_integer` instead of `get_maybe` because this is used when we are expecting a felt to be there. Also renamed it for consistency.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKlJsd8-264MXzOQCC:-NQKlJsd8-264MXzOQCD:bqcs26u) ([raw file](https://github.com/starkware-libs/blockifier/blob/c2aeea0584d4637f6977d597bb2bce7cd2990565/crates/blockifier/src/execution/execution_utils.rs#L337)):*
> ```XML
> }
> 
> pub fn felt_from_memory_cell(
> ```

This function is no longer needed.
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKmEpJ5Txsz1DmJFPm:-NQKmEpJ5Txsz1DmJFPn:bfyl6rn) ([raw file](https://github.com/starkware-libs/blockifier/blob/c2aeea0584d4637f6977d597bb2bce7cd2990565/crates/blockifier/src/execution/syscall_handling.rs#L311)):*
> ```XML
> pub fn read_felt_array(vm: &VirtualMachine, ptr: Relocatable) -> SyscallResult<Vec<StarkFelt>> {
>     let array_size = felt_from_memory_ptr(vm, ptr)?;
>     let array_data_ptr = vm.get_maybe(&(ptr + 1)).ok_or(VirtualMachineError::NoneInMemoryRange)?;
> ```

Now that pointers are `Relocatable`, no need for all this. We can use `get_relocatable` instead`.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKhYqF1t-k57T6LFFv:-NQKo8Mg2Gg4aEp-imy-:b1nvjwx) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/entry_point_test.rs#L191)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yes, in python it's `Can only subtract two relocatable values of the same segment`, which is basically the same. I'm not sure why they chose the reword it.
</blockquote></details>

Also, I opened a PR over their repo to fix these typos.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337)* status: all files reviewed, 7 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKr_Xy8oGwMUnvbv6R:-NQKr_Xy8oGwMUnvbv6S:bbogfts) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/entry_point_test.rs#L334)):*
> ```XML
> 
>     run_security_test(
>         "Custom Hint Error: Expected relocatable",
> ```

Is this the error in Python?



_Code quote:_
```XML
"Custom Hint Error: Expected relocatable"
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 263 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKrFaHCBE96cMFaYux:-NQKrFaHCBE96cMFaYuy:bsuqyoq) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/execution_utils.rs#L263)):*
> ```XML
>     };
> 
>     Ok(Retdata(felt_range_from_ptr(&vm, Relocatable::try_from(&retdata_ptr)?, retdata_size)?))
> ```

Are you sure it's always `Relocatable`?



_Code quote:_
```XML
Relocatable::try_from(&retdata_ptr)?
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKqwes9UuGBAEvVo_l:-NQKqwes9UuGBAEvVo_m:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/execution_utils.rs#L268)):*
> ```XML
> pub fn felt_from_ptr(
>     vm: &VirtualMachine,
>     memory_ptr: Relocatable,
> ```





_Suggestion:_
```XML
ptr: Relocatable,
```
___
*[`crates/blockifier/src/execution/syscalls.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKrzX21N9bK014WI8V:-NQKrzX37RFYw7HT5zO2:bugwfol) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/syscalls.rs#L367)):*
> ```XML
>         let contract_address_salt = ContractAddressSalt(felt_from_ptr(vm, (ptr + 1)?)?);
>         let constructor_calldata = read_calldata(vm, (ptr + 2)?)?;
>         let deploy_from_zero = felt_from_ptr(vm, (ptr + (2 + ARRAY_METADATA_SIZE))?)?;
> ```

It actually looks worse. Why does their `Add` return `Result`?



_Code quote:_
```XML
felt_from_ptr(vm, (ptr + (2 + ARRAY_METADATA_SIZE))?)?;
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKr_Xy8oGwMUnvbv6R:-NQKuf84Ear_o0PweAXF:buasdmz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/entry_point_test.rs#L334)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the error in Python?
</blockquote></details>

No, but this was the previous error here (it was changed recently). Python returns `Argument calldata to CallContractRequest is of unexpected type.` which can be identified because of the `CairoStrutProxy` which we don't have.



_Code quote:_
```XML
test_bad_syscall_request_arg_type"
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 263 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKrFaHCBE96cMFaYux:-NQKtXuq9Bx2agC2cNak:b1wdird) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/execution_utils.rs#L263)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are you sure it's always `Relocatable`?
</blockquote></details>

If not, it would have failed later anyways when trying to get the range. It has to be a pointer.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKlJsd8-264MXzOQCC:-NQKxzv1CbNJu696Rum5:b-cf8oe4) ([raw file](https://github.com/starkware-libs/blockifier/blob/c2aeea0584d4637f6977d597bb2bce7cd2990565/crates/blockifier/src/execution/execution_utils.rs#L337)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This function is no longer needed.
</blockquote></details>

Because we're using get_integer(_range)() instead of get_maybe() /get_continuous_range so we're already getting an integer and not a maybe relocatable
___
*[`crates/blockifier/src/execution/syscalls.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKrzX21N9bK014WI8V:-NQKuFaK4qcECbgRsrnb:bqz1nyu) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/syscalls.rs#L367)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It actually looks worse. Why does their `Add` return `Result`?
</blockquote></details>

There could be an overflow.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337#-:-NQtuvew9J38hzw53mFt:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/337#-NQKr_Xy8oGwMUnvbv6R:-NQtqeKK240jG9vWQxZu:b-if7xt3) ([raw file](https://github.com/starkware-libs/blockifier/blob/e10ae4729a7cf53e79227e06b5c8ef1b021216ba/crates/blockifier/src/execution/entry_point_test.rs#L334)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

No, but this was the previous error here (it was changed recently). Python returns `Argument calldata to CallContractRequest is of unexpected type.` which can be identified because of the `CairoStrutProxy` which we don't have.
</blockquote></details>

Please add a TODO to make this match Python's error.

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @noaov1)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337#-:-NQtyskk7SZgAb6fAI_A:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337#-:-NQtzlTf0KAmf-hTBxFu:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @elintul)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/337)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5)

**Pull request merged**
