### PR TITLE
refactor: added L1<>L2 meesages related fields to StarknetResources

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 385 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3a_-rBP-Jmlcz7bfH:-Ns3a_-rBP-Jmlcz7bfI:b22p4mo) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L385)):*
> ```XML
>         call_infos: impl Iterator<Item = &'a CallInfo>,
>         l1_handler_payload_size: Option<usize>,
>     ) -> TransactionExecutionResult<(Vec<usize>, usize)> {
> ```

I would be happy to simply return the tuple `(Vec<usize>, usize)`, 
it comes from the output of `MessageL1CostInfo::calculate`  but i don't want to use `.unwrap()`. 
what do you think?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)* status: all files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3pTVk2H_N3LwaxyGd:-Ns3pTVk2H_N3LwaxyGe:b-z0yj2) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/fee/actual_cost.rs#L167)):*
> ```XML
>             self.validate_call_info.into_iter().chain(self.execute_call_info);
> 
>         self.starknet_resources.set_message_resources(non_optional_call_infos.clone())?;
> ```

This clone is painful I think.
Can you send a reference?



_Code quote:_
```XML
non_optional_call_infos.clone()
```
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3qDafDyjnkFMY2gjN:-Ns3qDafDyjnkFMY2gjO:bwvw40n) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/fee/actual_cost_test.rs#L288)):*
> ```XML
>     let gas_usage_vector = ActualCostBuilder::calculate_tx_gas_usage_vector(
>         &versioned_constants,
>         call_infos_iter,
> ```

why does `calculate_tx_gas_usage_vector` need `call_infos_iter` input? isn't the starknet resources enough?



_Code quote:_
```XML
    let gas_usage_vector = ActualCostBuilder::calculate_tx_gas_usage_vector(
        &versioned_constants,
        call_infos_iter,
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3bgom6D1k4JQB7asP:-Ns3bgom6D1k4JQB7asQ:bspqfr1) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L267)):*
> ```XML
>         state_changes_count: StateChangesCount,
>         l1_handler_payload_size: Option<usize>,
>         call_infos: impl Iterator<Item = &'a CallInfo>,
> ```

this is the first time you add actual processing to this ctor (i.e. you take `CallInfo` objects and compute usizes from them).
does it make sense to move computation of other usizes (calldata length, signature length, l1 handler payload size) also into this ctor?



_Code quote:_
```XML
        calldata_length: usize,
        signature_length: usize,
        class_info: Option<&ClassInfo>,
        state_changes_count: StateChangesCount,
        l1_handler_payload_size: Option<usize>,
        call_infos: impl Iterator<Item = &'a CallInfo>,
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3bGq93rS-NB9rlSlm:-Ns3bGq93rS-NB9rlSln:b6tc2cx) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L271)):*
> ```XML
>         let (l2_to_l1_payload_lengths, message_segment_length) =
>             StarknetResources::calculate_messages_resources(call_infos, l1_handler_payload_size)
>                 .unwrap();
> ```

no `unwrap`ping in production code (if absolutely necessary we use `expect`).
please change return type from `Self` to some `Result` object and propagate errors



_Suggestion:_
```XML
?;
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 380 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3d8nt6mfyqfvLU6pC:-Ns3d8nt6mfyqfvLU6pD:b5nt955) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L380)):*
> ```XML
> 
>     /// Private and static that calculates the l2_to_l1_payload_lengths, message_segment_length
>     /// fields
> ```

end in punctuation



_Suggestion:_
```XML
    /// Private and static that calculates the l2_to_l1_payload_lengths, message_segment_length
    /// fields.
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3d6fd4QtEgSDl7ckA:-Ns3d6fd4QtEgSDl7ckB:b-quuiuv) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L381)):*
> ```XML
>     /// Private and static that calculates the l2_to_l1_payload_lengths, message_segment_length
>     /// fields
> ```

remove this newline
___
*[`crates/blockifier/src/transaction/objects.rs` line 385 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3a_-rBP-Jmlcz7bfH:-Ns3cPxP5qdlWtiwLXwM:b-bm5w1h) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L385)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I would be happy to simply return the tuple `(Vec<usize>, usize)`, 
it comes from the output of `MessageL1CostInfo::calculate`  but i don't want to use `.unwrap()`. 
what do you think?
</blockquote></details>

why do you need this function? instead of
```
let (l2_to_l1_payload_lengths, message_segment_length) =
    Self::calculate_messages_resources(call_infos, l1_handler_payload_size)?;
```
why not
```
let MessageL1CostInfo { l2_to_l1_payload_lengths, message_segment_length } =
    MessageL1CostInfo::calculate(call_infos, l1_handler_payload_size)?;
```
?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)* status: all files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 345 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3sNfo0xPSmnuD-90e:-Ns3sNfo0xPSmnuD-90f:b-8trk4s) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L345)):*
> ```XML
>             ),
>             l1_data_gas: 0,
>         };
> ```

if [this](https://reviewable.io/reviews/starkware-libs/blockifier/1613) gets in first, update the code



_Suggestion:_
```XML
        let sharp_gas_usage = GasVector::from_l1_gas(u128_from_usize(
            self.message_segment_length * eth_gas_constants::SHARP_GAS_PER_MEMORY_WORD,
        ));
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)* status: all files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 345 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3sNfo0xPSmnuD-90e:-Ns3t8UuAyn8UqSUKakS:b6qtwc) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L345)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if [this](https://reviewable.io/reviews/starkware-libs/blockifier/1613) gets in first, update the code
</blockquote></details>

it got in :) please make this change

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3pTVk2H_N3LwaxyGd:-Ns7Cr_K-snYKLmstlcA:b-3fof9t) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/fee/actual_cost.rs#L167)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This clone is painful I think.
Can you send a reference?
</blockquote></details>

there was a clone before.. (inside `ActualCostBuilder::calculate_tx_gas_usage_vector`)
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3qDafDyjnkFMY2gjN:-Ns3tMsj2YRtrUrEOm4s:b-6759pj) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/fee/actual_cost_test.rs#L288)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why does `calculate_tx_gas_usage_vector` need `call_infos_iter` input? isn't the starknet resources enough?
</blockquote></details>

the events cost also depends on `call_infos_iter`
at the next PR i'll remove this function (all the calculation will come from `StarknetResources::to_gas_vector`)
___
*[`crates/blockifier/src/transaction/objects.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3bgom6D1k4JQB7asP:-Ns3v4c0BRyNBuAz4o4f:b7ff8mp) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L267)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is the first time you add actual processing to this ctor (i.e. you take `CallInfo` objects and compute usizes from them).
does it make sense to move computation of other usizes (calldata length, signature length, l1 handler payload size) also into this ctor?
</blockquote></details>

other fields need some extra context to be computed (for example versioned_constants)...
I think it's fine
___
*[`crates/blockifier/src/transaction/objects.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3bGq93rS-NB9rlSlm:-Ns3uHPF5WU0-I8o-F__:buzo0nc) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L271)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no `unwrap`ping in production code (if absolutely necessary we use `expect`).
please change return type from `Self` to some `Result` object and propagate errors
</blockquote></details>

that is what i want to avoid... 
it just doesn't seem related (to me) that constructing a `StarknetResources` may return `TransactionExecutionResult`.
same for `set_message_resources`
which option do you think is better? to return `TransactionExecutionResult` or to use `except`?
___
*[`crates/blockifier/src/transaction/objects.rs` line 345 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3sNfo0xPSmnuD-90e:-Ns3w94w4i4bGmQ6YZMl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L345)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it got in :) please make this change
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 380 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3d8nt6mfyqfvLU6pC:-Ns3xY0G1Mxxu9LDRoFR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L380)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

end in punctuation
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3d6fd4QtEgSDl7ckA:-Ns3xXj40sZ14dtOPNwu:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L381)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove this newline
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 385 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3a_-rBP-Jmlcz7bfH:-Ns3x2jQ8ip4MIZG5z5r:bphf3d3) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L385)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need this function? instead of
```
let (l2_to_l1_payload_lengths, message_segment_length) =
    Self::calculate_messages_resources(call_infos, l1_handler_payload_size)?;
```
why not
```
let MessageL1CostInfo { l2_to_l1_payload_lengths, message_segment_length } =
    MessageL1CostInfo::calculate(call_infos, l1_handler_payload_size)?;
```
?
</blockquote></details>

this function is needed for the constructor. 
if i simply call `set_message_resources` (which takes `&mut self`) it forces the constructor to return a mutable instance.
maybe there is a better solution...

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3bGq93rS-NB9rlSlm:-Ns7wjO-6CsBdQ7m0cSP:b-8jpm5s) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L271)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

that is what i want to avoid... 
it just doesn't seem related (to me) that constructing a `StarknetResources` may return `TransactionExecutionResult`.
same for `set_message_resources`
which option do you think is better? to return `TransactionExecutionResult` or to use `except`?
</blockquote></details>

I prefer a result
___
*[`crates/blockifier/src/transaction/objects.rs` line 385 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-Ns3a_-rBP-Jmlcz7bfH:-Ns7xHVYECuSXRi8p573:b-fih2f3) ([raw file](https://github.com/starkware-libs/blockifier/blob/94f44ad199d708f13a5b5a0edf3e17d087b049a4/crates/blockifier/src/transaction/objects.rs#L385)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

this function is needed for the constructor. 
if i simply call `set_message_resources` (which takes `&mut self`) it forces the constructor to return a mutable instance.
maybe there is a better solution...
</blockquote></details>

let's talk about this f2f

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)* status: all files reviewed, 8 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsDEfXuE7L4MPs9rWgA:-NsDEfXuE7L4MPs9rWgB:b-yk6k9z) ([raw file](https://github.com/starkware-libs/blockifier/blob/3975989b32d861261076375d68348fd546a1a9bb/crates/blockifier/src/blockifier/transaction_executor.rs#L105)):*
> ```XML
>                     &tx_execution_info.validate_call_info.as_ref(),
>                     &tx_execution_info.execute_call_info.as_ref(),
>                 ];
> ```

[`filter_map` filters `None` values](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter_map), after this change the `call_infos` variable can contain `None`s. Is this intended? What is the type of `call_infos` here?



_Code quote:_
```XML
                let call_infos = &[
                    &tx_execution_info.validate_call_info.as_ref(),
                    &tx_execution_info.execute_call_info.as_ref(),
                ];
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsDFw__3TYv11UUyWhg:-NsDFw__3TYv11UUyWhh:bacp4o7) ([raw file](https://github.com/starkware-libs/blockifier/blob/3975989b32d861261076375d68348fd546a1a9bb/crates/blockifier/src/execution/call_info.rs#L52)):*
> ```XML
>             .filter_map(|call_info| {
>                 call_info.map(|info| info.get_sorted_l2_to_l1_payload_lengths())
>             })
> ```

isn't this equivalent....?



_Suggestion:_
```XML
            .filter_map(|call_info| call_info.get_sorted_l2_to_l1_payload_lengths())
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsDG2S38I-z7b4J_jJP:-NsDG2S38I-z7b4J_jJQ:b-2dxky7) ([raw file](https://github.com/starkware-libs/blockifier/blob/3975989b32d861261076375d68348fd546a1a9bb/crates/blockifier/src/execution/call_info.rs#L53)):*
> ```XML
>                 call_info.map(|info| info.get_sorted_l2_to_l1_payload_lengths())
>             })
>             .try_collect::<Vec<usize>, Vec<Vec<usize>>, TransactionExecutionError>()?)
> ```

I am confused - `try_collect` uses 3 type variables? what does each represent? output, inputs, error?



_Code quote:_
```XML
.try_collect::<Vec<usize>, Vec<Vec<usize>>, TransactionExecutionError>()?)
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsDGJ_eAPYpv8XhBOFQ:-NsDGJ_eAPYpv8XhBOFR:bkiuaq8) ([raw file](https://github.com/starkware-libs/blockifier/blob/3975989b32d861261076375d68348fd546a1a9bb/crates/blockifier/src/execution/call_info.rs#L56)):*
> ```XML
>         .into_iter()
>         .flatten()
>         .collect();
> ```

are the "outer" parens necessary?



_Suggestion:_
```XML
        let l2_to_l1_payload_lengths: Vec<usize> = call_infos
            .iter()
            .filter_map(|call_info| {
                call_info.map(|info| info.get_sorted_l2_to_l1_payload_lengths())
            })
            .try_collect::<Vec<usize>, Vec<Vec<usize>>, TransactionExecutionError>()?
        .into_iter()
        .flatten()
        .collect();
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsDGmzbAi1dGXFpoQn1:-NsDGmzbAi1dGXFpoQn2:b-w8sing) ([raw file](https://github.com/starkware-libs/blockifier/blob/3975989b32d861261076375d68348fd546a1a9bb/crates/blockifier/src/fee/actual_cost.rs#L164)):*
> ```XML
>         // TODO(Dafna, 1/6/2024): Compute the DA size and pass it instead of state_changes_count.
>         let da_gas = self.starknet_resources.get_state_changes_cost(use_kzg_da);
>         let non_optional_call_infos = &[&self.validate_call_info, &self.execute_call_info];
> ```

it seems like `for info in non_optional_call_infos` will no longer include inner calls.
previously the `into_iter` method created a custom iterator over call infos (including nested call infos) by [inspecting inner calls](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/execution/call_info.rs#L244).

Consider simply *collecting* here and passing the constructed vector to two places (unsure of the type, just a guess).



_Suggestion:_
```XML
let non_optional_call_infos: Vec<Option<&CallInfo>> =
    self.validate_call_info.into_iter().chain(self.execute_call_info).collect();
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 28 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsDHpwzDOfpf5zsAXVi:-NsDHpwzDOfpf5zsAXVj:b-yb4qmo) ([raw file](https://github.com/starkware-libs/blockifier/blob/3975989b32d861261076375d68348fd546a1a9bb/crates/blockifier/src/fee/gas_usage.rs#L28)):*
> ```XML
>         .filter_map(|call_info| {
>             call_info.map(|info| get_events_gas_cost(&info.execution.events, versioned_constants))
>         })
> ```

why `map` twice?



_Suggestion:_
```XML
        .filter_map(|call_info| get_events_gas_cost(&call_info.execution.events, versioned_constants))
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)* status: all files reviewed, 11 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsDXpwJ0i18TwgSc3w0:-NsDXpwJ0i18TwgSc3w1:b-7ep5ag) ([raw file](https://github.com/starkware-libs/blockifier/blob/537dbbebb18aeed091162cd0c0e25ef9d6100edd/crates/blockifier/src/fee/gas_usage_test.rs#L28)):*
> ```XML
>     let call_info_2 = &CallInfo::default();
>     let call_info_3 = &CallInfo::default();
>     let call_infos = &[&Some(call_info_1), &Some(call_info_2), &Some(call_info_3)];
> ```

not equivalent... `into_iter` iterates over internal call infos as well



_Code quote:_
```XML
let call_infos = &[&Some(call_info_1), &Some(call_info_2), &Some(call_info_3)];
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsDXv6j-ws55XoyS5mr:-NsDXv6j-ws55XoyS5ms:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/537dbbebb18aeed091162cd0c0e25ef9d6100edd/crates/blockifier/src/fee/gas_usage_test.rs#L29)):*
> ```XML
>     let call_info_3 = &CallInfo::default();
>     let call_infos = &[&Some(call_info_1), &Some(call_info_2), &Some(call_info_3)];
>     // let call_infos = call_info_1.into_iter().chain(call_info_2).chain(call_info_3);
> ```

delete
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsDXtwt8bSi_iPGSY38:-NsDXtwt8bSi_iPGSY39:b-7ep5ag) ([raw file](https://github.com/starkware-libs/blockifier/blob/537dbbebb18aeed091162cd0c0e25ef9d6100edd/crates/blockifier/src/fee/gas_usage_test.rs#L61)):*
> ```XML
>         ..Default::default()
>     };
>     let call_infos = &[&Some(call_info_1), &Some(call_info_2), &Some(call_info_3)];
> ```

not equivalent... `into_iter` iterates over internal call infos as well



_Code quote:_
```XML
let call_infos = &[&Some(call_info_1), &Some(call_info_2), &Some(call_info_3)];
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r5, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 51 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsJSts2-bkkUTAGLmkX:-NsJSts2-bkkUTAGLmkY:be5xamt) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b91a58f82d27edd41db03301a996e55bb6aeefe/crates/blockifier/src/execution/call_info.rs#L51)):*
> ```XML
>             l2_to_l1_payload_lengths.extend(call_info.get_sorted_l2_to_l1_payload_lengths()?);
>         }
> ```

restore the newline (mainly so this file isn't diffed in this PR)
___
*[`crates/blockifier/src/transaction/objects.rs` line 265 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsJTZkEEG2Moz8DB6qb:-NsJTZkEEG2Moz8DB6qc:bdlf1g1) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1204ebaba230479fbbaeb451149d4e6d5e69ea2/crates/blockifier/src/transaction/objects.rs#L265)):*
> ```XML
>     signature_length: usize,
>     code_size: usize,
>     message_segment_length: usize,
> ```

sorry for waking up late, but please reuse existing structs when it makes sense



_Suggestion:_
```XML
    pub l1_handler_payload_size: Option<usize>,
    pub l1_message_cost: MessageL1CostInfo,
    signature_length: usize,
    code_size: usize,
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1610)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 265 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1610#-NsJTZkEEG2Moz8DB6qb:-NsMjbDp0blD9rscxuV_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1204ebaba230479fbbaeb451149d4e6d5e69ea2/crates/blockifier/src/transaction/objects.rs#L265)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

sorry for waking up late, but please reuse existing structs when it makes sense
</blockquote></details>

Done.

**Pull request merged**
