### PR TITLE
feat: scheduler basics

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1677)

### CODE REVIEW

**Comment by barak-b-starkware** [comment]
Maybe we want the scheduler to implement the "Singleton" pattern, there are many ways to do that, can TAL at some of them [here](https://stackoverflow.com/questions/27791532/how-do-i-create-a-global-mutable-singleton).

**Review by noaov1 — COMMENTED** [review]
Interesting. I think that the scheduler object will live withing an execution of one chunk (similar to the (shared) version state). Why not use an `Arc`?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-:-NtFRhNqDVVrI1hZI3d-:bjj2o4q)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtFSoRICueWqcIg92A8:-NtFSoRICueWqcIg92A9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c597025acbd5b1c41ce54c93fc117e21b6a0bcfb/crates/blockifier/src/concurrency/scheduler.rs#L41)):*
> ```XML
>     EXECUTION,
>     VALIDATION,
> }
> ```





_Suggestion:_
```XML
pub enum TaskType {
    EXECUTION,
    VALIDATION,
}
```
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtFSyNA1hv29XG7pZ6b:-NtFSyNA1hv29XG7pZ6c:b-stqqm5) ([raw file](https://github.com/starkware-libs/blockifier/blob/c597025acbd5b1c41ce54c93fc117e21b6a0bcfb/crates/blockifier/src/concurrency/scheduler.rs#L45)):*
> ```XML
> pub struct Task {
>     pub version: TaskVersion,
>     pub kind: Option<TaskKind>,
> ```

Why is it optional?



_Suggestion:_
```XML
    pub task_type: Option<TaskKind>,
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtLpWGg-hTMNlVvtoZo:-NtLpWGg-hTMNlVvtoZp:b9jwr6r) ([raw file](https://github.com/starkware-libs/blockifier/blob/c597025acbd5b1c41ce54c93fc117e21b6a0bcfb/crates/blockifier/src/concurrency/scheduler.rs#L19)):*
> ```XML
>     /// Schedules the required tasks necessitated by the last task of the thread.
>     /// Returns the next VALIDATION task that should be done by the thread if 'validation_idx` >
>     /// 'tx_idx', otherwise, Task.kind is 'None'.
> ```

What should `Task.version` be when `Task.kind` is `None`?
`Task.version` is only meaningful if the task is validation or execution. In the aptos repo, they added two additional types of tasks: Done and NoTask.



_Code quote:_
```XML
/// 'tx_idx', otherwise, Task.kind is 'None'.
```

**Review by barak-b-starkware — COMMENTED** [review]
`Arc` sounds good (:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-:-NtPtpqM4tBTT1QUAu-y:b-9svtyo)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtLpWGg-hTMNlVvtoZo:-NtPtzbjD7-W0umYfvos:b-d88mky) ([raw file](https://github.com/starkware-libs/blockifier/blob/c597025acbd5b1c41ce54c93fc117e21b6a0bcfb/crates/blockifier/src/concurrency/scheduler.rs#L19)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

What should `Task.version` be when `Task.kind` is `None`?
`Task.version` is only meaningful if the task is validation or execution. In the aptos repo, they added two additional types of tasks: Done and NoTask.
</blockquote></details>

Good point, In `try_execute` and in `needs_reexecution`, we return `Task` and pass the version. But in `next_task`, we internally create the version, so it might not exist.
One option is to add the `NoTask` variant, and another option is to convert the `TaskVersion` struct into an enum and add a `NoVersion` variant. The second option keeps the `Task` struct cleaner and allows to use a `match` expression on the kind (type after fixing PR comments) to decide whether it's `Some` or `None`. The first option is maybe more straightforward.
WDYT?
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtGh71q3N4xdgjddflp:-NtPwffl4a-WcsK5b_2c:be9xi4g) ([raw file](https://github.com/starkware-libs/blockifier/blob/c597025acbd5b1c41ce54c93fc117e21b6a0bcfb/crates/blockifier/src/concurrency/scheduler.rs#L35)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We will add the incarnation number when we need it.
</blockquote></details>

What `Version` is in the suggestion? Do we want it to be a struct even if it contains only one field?
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtFSoRICueWqcIg92A8:-NtPxc5nEwBJFGwcDY6W:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c597025acbd5b1c41ce54c93fc117e21b6a0bcfb/crates/blockifier/src/concurrency/scheduler.rs#L41)):*
> ```XML
>     EXECUTION,
>     VALIDATION,
> }
> ```

Done.
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtFSyNA1hv29XG7pZ6b:-NtPwtVhBbWDFrPUeFBR:b48lu6a) ([raw file](https://github.com/starkware-libs/blockifier/blob/c597025acbd5b1c41ce54c93fc117e21b6a0bcfb/crates/blockifier/src/concurrency/scheduler.rs#L45)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it optional?
</blockquote></details>

WDYT about `pub ty: Option<TaskType>`? When we call it, we prefer: `task.task_type` or `task.ty`? I'm not sure what I prefer, the `ty` shortcut gives some kind of "macro feeling".

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1677)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtGh71q3N4xdgjddflp:-NtV-v4y5GaQvV2BR8Tn:b-71mpar) ([raw file](https://github.com/starkware-libs/blockifier/blob/c597025acbd5b1c41ce54c93fc117e21b6a0bcfb/crates/blockifier/src/concurrency/scheduler.rs#L35)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

What `Version` is in the suggestion? Do we want it to be a struct even if it contains only one field?
</blockquote></details>

Actually, no need. Simply use `crate::concurrency::Version;`
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtFSyNA1hv29XG7pZ6b:-NtV0JFQ9cvyaGp7fNF8:b-aj1re3) ([raw file](https://github.com/starkware-libs/blockifier/blob/c597025acbd5b1c41ce54c93fc117e21b6a0bcfb/crates/blockifier/src/concurrency/scheduler.rs#L45)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT about `pub ty: Option<TaskType>`? When we call it, we prefer: `task.task_type` or `task.ty`? I'm not sure what I prefer, the `ty` shortcut gives some kind of "macro feeling".
</blockquote></details>

I would love you use `type` but we can't :( `ty` is not indicative enough (IMO).  Not relevant though, see my comment above. 
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtV6IvVBm0zKjiLZqhk:-NtV6IvVBm0zKjiLZqhl:b-vq33k4) ([raw file](https://github.com/starkware-libs/blockifier/blob/5991e1c0a01a553443e4ef1a3037f227a1c5e7f8/crates/blockifier/src/concurrency/scheduler.rs#L40)):*
> ```XML
>     EXECUTION,
>     VALIDATION,
> }
> ```

Consider adding an enum for the task itself (since in the `NoTask`` case we do not have version)



_Suggestion:_
```XML
pub enum Task {
    ExecutionTask(Version),
    NoTask,
    ValidationTask(Version),
}
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtLpWGg-hTMNlVvtoZo:-NtVIBC8EjBsLa7YO2lQ:b-ckmv0u) ([raw file](https://github.com/starkware-libs/blockifier/blob/c597025acbd5b1c41ce54c93fc117e21b6a0bcfb/crates/blockifier/src/concurrency/scheduler.rs#L19)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Good point, In `try_execute` and in `needs_reexecution`, we return `Task` and pass the version. But in `next_task`, we internally create the version, so it might not exist.
One option is to add the `NoTask` variant, and another option is to convert the `TaskVersion` struct into an enum and add a `NoVersion` variant. The second option keeps the `Task` struct cleaner and allows to use a `match` expression on the kind (type after fixing PR comments) to decide whether it's `Some` or `None`. The first option is maybe more straightforward.
WDYT?
</blockquote></details>

I think it is easier to understand what is happening when the scheduler returns `NoTask` or `Done`. Though `None` could also work as a response to `next_task` and it is not that bad.
Another nice thing about not using `Option` is that you don't need to add `Some()` to everything.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1677)* status: all files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtVA_ef4rwp3FDZwR3N:-NtVA_eg162FBOnvzdcx:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5991e1c0a01a553443e4ef1a3037f227a1c5e7f8/crates/blockifier/src/concurrency/scheduler.rs#L14)):*
> ```XML
>     pub fn next_task() -> Task {
>         todo!()
>     }
> ```





_Suggestion:_
```XML
    /// Return the next task to run. Prioratize validations tasks.
    pub fn next_task() -> Task {
        todo!()
    }
```
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtVJDVRB_Rf5Cu4nvcL:-NtVJDVRB_Rf5Cu4nvcM:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/5991e1c0a01a553443e4ef1a3037f227a1c5e7f8/crates/blockifier/src/concurrency/scheduler.rs#L19)):*
> ```XML
>     /// Schedules the required tasks necessitated by the last task of the thread.
>     /// Returns the next VALIDATION task that should be done by the thread if 'validation_idx` >
>     /// 'tx_idx', otherwise, Task.kind is 'None'.
> ```

WDYT?



_Suggestion:_
```XML
    /// Update the Scheduler that an execution task has been finished and trigger the creation of new tasks accordingly:
    /// schedule validation for the current and higher transactions, if not already scheduled. 
```
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtVK7oWCYZXT979zRaY:-NtVK7oWCYZXT979zRaZ:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/5991e1c0a01a553443e4ef1a3037f227a1c5e7f8/crates/blockifier/src/concurrency/scheduler.rs#L27)):*
> ```XML
>     /// Schedules the required tasks necessitated by the last task of the thread.
>     /// Returns the next EXECUTION task that should be done by the thread if 'execution_idx` >
>     /// 'tx_idx', otherwise, Task.kind is 'None'.
> ```

WDYT?



_Suggestion:_
```XML
    /// Update the Scheduler that a validation task has been finished and trigger the creation of new tasks accordingly:
    /// schedule validation for higher transactions + re-executes the current transaction (if ready).
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-:-NtVWFlEENJRgAAbibCD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1677#-NtV6IvVBm0zKjiLZqhk:-NtVUv6L1rnUJjLSVzJ3:bijutz0) ([raw file](https://github.com/starkware-libs/blockifier/blob/5991e1c0a01a553443e4ef1a3037f227a1c5e7f8/crates/blockifier/src/concurrency/scheduler.rs#L40)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
Do you want here `Done` too as a variant? as @avi-starkware suggested?
</blockquote></details>

Oh, do we want `next_task` to return `Done`? We can add it and see later according to our needs

**Pull request merged**
