### PR TITLE
Pass gas to cairo1 syscalls

### PR DESCRIPTION
**Pull request by noaov1**
Based on #546.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/547)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/547)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/547#-NWp9HBz8HnU4QkIT0n9:-NWp9HBz8HnU4QkIT0nA:b5n2wmb) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcf3e08ac1937df558e996f672bf45f9885fc400/crates/blockifier/src/execution/syscalls/hint_processor.rs#L449)):*
> ```XML
>     vm: &mut VirtualMachine,
>     syscall_handler: &mut SyscallHintProcessor<'_>,
>     remaining_gas: &mut Felt252,
> ```

Why does this API have to change? Only for inner calls?



_Code quote:_
```XML
remaining_gas: &mut Felt252
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 485 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/547#-NWgqxe-9TMB_QIcvc_c:-NWp8vng608E6GfsxDmX:b-tcl26e) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b2859c705ce784aed6ca12de399b0ba5155768f/crates/blockifier/src/execution/syscalls/hint_processor.rs#L485)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it okay? Do we have delegate calls in cairo1?
</blockquote></details>

We have library calls, I think we're going to need to support the code address in the output.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/547#-NWp95yl2FGdiB-IckLf:-NWp95yl2FGdiB-IckLg:bzwi2i) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b2859c705ce784aed6ca12de399b0ba5155768f/crates/blockifier/src/execution/syscalls/mod.rs#L238)):*
> ```XML
>         create_retdata_segment(vm, syscall_handler, &call_info.execution.retdata.0)?;
> 
>     syscall_handler.inner_calls.push(call_info);
> ```

Restore blank line above.



_Code quote:_
```XML
syscall_handler.inner_calls.push(call_info);
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/547)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/547#-NWp9HBz8HnU4QkIT0n9:-NWqJ7lUB60296kqM9zN:b-gkq25q) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcf3e08ac1937df558e996f672bf45f9885fc400/crates/blockifier/src/execution/syscalls/hint_processor.rs#L449)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why does this API have to change? Only for inner calls?
</blockquote></details>

I'm not sure I understand your question :) We need to pass the `remaining_gas` to the`execute` method of an entry point.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 485 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/547#-NWgqxe-9TMB_QIcvc_c:-NWqHmsMEvlIqUdaivQl:b-gszi2i) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b2859c705ce784aed6ca12de399b0ba5155768f/crates/blockifier/src/execution/syscalls/hint_processor.rs#L485)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We have library calls, I think we're going to need to support the code address in the output.
</blockquote></details>

Yes, but in library calls the code address is `None`, no?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/547)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/547#-NWp9HBz8HnU4QkIT0n9:-NXJBvil8D3v-qI8wvhg:bh677q0) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcf3e08ac1937df558e996f672bf45f9885fc400/crates/blockifier/src/execution/syscalls/hint_processor.rs#L449)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Even after adding the `initial_gas` to `CallEntryPoint`we need it to update the remaining gas after the execution. 
</blockquote></details>

I'm saying, we only need this for `call_contract` and `library_call`, so I was wondering if we need this API change for all syscalls.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/547#-NXJC8276KaffENrgORu:-NXJC8276KaffENrgORv:b-vko877) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ee12b26bc78c793b3f42ecda776ffd8f64a1dbf/crates/blockifier/src/execution/syscalls/mod.rs#L151)):*
> ```XML
>     vm: &mut VirtualMachine,
>     syscall_handler: &mut SyscallHintProcessor<'_>,
>     remaining_gas: &mut Felt252,
> ```


Can we ask LC for it to be `Copyable`?



_Code quote:_
```XML
Felt252
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/547)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/547#-NWp9HBz8HnU4QkIT0n9:-NXKm4JWDJabCSMCE-ZC:b-cmf8t6) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcf3e08ac1937df558e996f672bf45f9885fc400/crates/blockifier/src/execution/syscalls/hint_processor.rs#L449)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm saying, we only need this for `call_contract` and `library_call`, so I was wondering if we need this API change for all syscalls.
</blockquote></details>

Oh. I see. Yes, since `execute_syscall` receive the `execute_callback`of each syscall. 
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/547#-NXJC8276KaffENrgORu:-NXKmp0GExxDIS2aN_rJ:b-xbksvf) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ee12b26bc78c793b3f42ecda776ffd8f64a1dbf/crates/blockifier/src/execution/syscalls/mod.rs#L151)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we ask LC for it to be `Copyable`?
</blockquote></details>

Will be changed to `u128`.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/547)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/547#-NWp9HBz8HnU4QkIT0n9:-NXKy2hs1cQVkohITZVm:bnpz97u) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcf3e08ac1937df558e996f672bf45f9885fc400/crates/blockifier/src/execution/syscalls/hint_processor.rs#L449)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can't this be a member of the syscall handler?
</blockquote></details>

It can. This may be counterintuitive because we will initialize it to zero and change its value on every `execute_syscall`. I will think of a solution.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/547)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
