### PR TITLE
refactor(transaction): remove public fields, add new function

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1480)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1480)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqNrRnV0ppqc61VV5Y0:-NqNrRnW5dZGWD9NoKic:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/02f2fbb17108be6a23a3675a9434d7e7f81d9237/crates/blockifier/src/transaction/transactions.rs#L108)):*
> ```XML
> #[derive(Clone, Debug)]
> // TODO(Ayelet,10/02/2024): Change to bytes.
> #[allow(dead_code)]
> ```

Why?



_Code quote:_
```XML
#[allow(dead_code)]
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqNsJkE5j_jGrtkwPe3:-NqNsJkE5j_jGrtkwPe4:b-h9kmwn) ([raw file](https://github.com/starkware-libs/blockifier/blob/02f2fbb17108be6a23a3675a9434d7e7f81d9237/crates/native_blockifier/src/py_transaction.rs#L171)):*
> ```XML
>             py_class_info.abi_length,
>         )
>         .unwrap();
> ```

Please avoid `unwrap()` in a non-test code (lead to an unwanted panic)



_Code quote:_
```XML
        .unwrap();
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1480)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqNslP74Qs5PzWeTGq_:-NqNslP74Qs5PzWeTGqa:b4ajn3s) ([raw file](https://github.com/starkware-libs/blockifier/blob/02f2fbb17108be6a23a3675a9434d7e7f81d9237/crates/blockifier/src/transaction/test_utils.rs#L334)):*
> ```XML
>     };
>     ClassInfo::new(&contract_class, sierra_program_length, 100)
> }
> ```

No need to return a result object in test utils. 



_Suggestion:_
```XML
pub fn calculate_class_info_for_testing(
    contract_class: ContractClass,
) -> ClassInfo {
    let sierra_program_length = match contract_class {
        ContractClass::V0(_) => 0,
        ContractClass::V1(_) => 100,
    };
    ClassInfo::new(&contract_class, sierra_program_length, 100).unwrap()
}
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1480)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqNslP74Qs5PzWeTGq_:-NqOBYJy4NQLAjiRzQmz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/02f2fbb17108be6a23a3675a9434d7e7f81d9237/crates/blockifier/src/transaction/test_utils.rs#L334)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No need to return a result object in test utils.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqNrRnV0ppqc61VV5Y0:-NqOBobPC35itVBUKPCF:b-mpuuix) ([raw file](https://github.com/starkware-libs/blockifier/blob/02f2fbb17108be6a23a3675a9434d7e7f81d9237/crates/blockifier/src/transaction/transactions.rs#L108)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Without it, I get this error:



_Code snippet:_
```XML
fields `sierra_program_length` and `abi_length` are never read
`ClassInfo` has derived impls for the traits `Debug` and `Clone`, but these are intentionally ignored during dead code analysis
`#[warn(dead_code)]` on by default
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqNsJkE5j_jGrtkwPe3:-NqRGkVP9tXdF1jf6CJh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/02f2fbb17108be6a23a3675a9434d7e7f81d9237/crates/native_blockifier/src/py_transaction.rs#L171)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please avoid `unwrap()` in a non-test code (lead to an unwanted panic)
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1480)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/blockifier/src/transaction/errors.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqNvjA22WfknBAhZlAe:-NqNvjA22WfknBAhZlAf:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/02f2fbb17108be6a23a3675a9434d7e7f81d9237/crates/blockifier/src/transaction/errors.rs#L64)):*
> ```XML
>     )]
>     ContractClassVersionSierraProgramLengthMismatch {
>         contract_class_version: u64,
> ```





_Suggestion:_
```XML
        contract_class_version: u8,
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqRJqEu81V7p4crVIg0:-NqRJqEu81V7p4crVIg1:b-ozwuxd) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4a5aaa9314532fa1e99b4e719b750f1a7f66548/crates/blockifier/src/transaction/test_utils.rs#L15)):*
> ```XML
> use strum::IntoEnumIterator;
> 
> use super::transactions::ClassInfo;
> ```

Please avoid using `super` (non-blocking).



_Code quote:_
```XML
use super::transactions::ClassInfo;
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqNrRnV0ppqc61VV5Y0:-NqRKCmEAr8ca6eZ-mdp:b237c35) ([raw file](https://github.com/starkware-libs/blockifier/blob/02f2fbb17108be6a23a3675a9434d7e7f81d9237/crates/blockifier/src/transaction/transactions.rs#L108)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Without it, I get this error:
</blockquote></details>

Solved with  the getters.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqNvwIz2CxGf4M7xQNc:-NqNvwIz2CxGf4M7xQNd:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/02f2fbb17108be6a23a3675a9434d7e7f81d9237/crates/blockifier/src/transaction/transactions.rs#L124)):*
> ```XML
>         sierra_program_length: usize,
>         abi_length: usize,
>     ) -> Result<Self, TransactionExecutionError> {
> ```





_Suggestion:_
```XML
    ) -> TransactionExecutionResult<Self> {
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1480)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqSMMh2EA72VJEDsIQg:-NqSMMh2EA72VJEDsIQh:b-a20e17) (no related file):*
Python's PR:
https://reviewable.io/reviews/starkware-industries/starkware/33951

___

**Review by noaov1 — APPROVED** [review]
> Reviewed 9 of 12 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1480)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/native_blockifier/src/errors.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-NqSV9FN-wAPEcWaMANd:-NqSV9FN-wAPEcWaMANe:b-kxmnem) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc33d82d2f93f6bab0100daee55f4bb4e0fad810/crates/native_blockifier/src/errors.rs#L72)):*
> ```XML
>     (TransactionExecutionError, TransactionExecutionError, PyTransactionExecutionError),
>     (TransactionPreValidationError, TransactionPreValidationError, PyTransactionPreValidationError),
>     (ContractClassError, ContractClassError, PyContractClassError)
> ```

Please alphabatize.



_Code quote:_
```XML
    (ContractClassError, ContractClassError, PyContractClassError)
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1480#-:-NqX6QOg-wmOpAy9JzA9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Pull request merged**
