### PR TITLE
refactor(execution): delete enrty point ExecutionResources

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1447)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1447#-Nq6jnAoDVHyciQZoMx_:-Nq6jnAp1OcBlDVOzw0i:b5kmm8q) ([raw file](https://github.com/starkware-libs/blockifier/blob/1740a2ee650cdec80071755d1a7035f0a4d37442/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L246)):*
> ```XML
>         .get_additional_os_syscall_resources(&syscall_handler.syscall_counter)?;
> 
>     let full_call_resources = &syscall_handler.resources.clone() - &previous_resources;
> ```

Both being taken as a reference and need to clone?
Why is resources consumed here?



_Code quote:_
```XML
&syscall_handler.resources.clone()
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 25 files at r1, 1 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1447)* status: 3 of 25 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 340 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1447#-Nq6kHlHD7qwphi-nx3_:-Nq6kHlHD7qwphi-nx3a:bt7t2pt) ([raw file](https://github.com/starkware-libs/blockifier/blob/1740a2ee650cdec80071755d1a7035f0a4d37442/crates/blockifier/src/execution/entry_point_execution.rs#L340)):*
> ```XML
>         .get_additional_os_syscall_resources(&syscall_handler.syscall_counter)?;
> 
>     let full_call_resources = &syscall_handler.resources.clone() - &previous_resources;
> ```

Again, why clone?



_Code quote:_
```XML
    let full_call_resources = &syscall_handler.resources.clone() - &previous_resources;
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1447)* status: 22 of 25 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @noaov1)

___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 241 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1447#-Nq2so8D8aGy5XLp66LH:-Nq7DyDA4figtyf3nuxC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f72cc4c16290cbddf4b0d6c0914a301ff530ce7/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L241)):*
> ```XML
>         .get_execution_resources(&vm)
>         .map_err(VirtualMachineError::RunnerError)?
>         .filter_unused_builtins();
> ```

Done.
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1447#-Nq2t4J3A-imPxpCHpcK:-Nq7DaOoAo9yExMgP1z2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f72cc4c16290cbddf4b0d6c0914a301ff530ce7/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L248)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is the `clone()` needed now?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1447#-Nq6jnAoDVHyciQZoMx_:-Nq7Da6pESp8WoIpqtof:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1740a2ee650cdec80071755d1a7035f0a4d37442/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L246)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Both being taken as a reference and need to clone?
Why is resources consumed here?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 306 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1447#-Nq6kQkC3qDl81EkZqth:-Nq7Dzov7uEDZA3svmFn:bpyzff4) ([raw file](https://github.com/starkware-libs/blockifier/blob/1740a2ee650cdec80071755d1a7035f0a4d37442/crates/blockifier/src/execution/entry_point_execution.rs#L306)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Maybe we want to set this as a `mut`?
</blockquote></details>

No need
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 340 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1447#-Nq6kHlHD7qwphi-nx3_:-Nq7E0qt9iYBqnEwrUUB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1740a2ee650cdec80071755d1a7035f0a4d37442/crates/blockifier/src/execution/entry_point_execution.rs#L340)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Again, why clone?
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 19 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1447#-:-Nq7_eiD1NSOgyKRisK3:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 25 files at r1, 17 of 19 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1447#-:-Nq7KW121O-IfeIKfPDE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @OriStarkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 73 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1447#-Nq7irTY6oefYrGHKq1_:-Nq7irTY6oefYrGHKq1a:bbm1zni) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f65cdc7cd095251e97fc4e4fba8d942fa5cd47/crates/blockifier/src/fee/fee_utils.rs#L73)):*
> ```XML
>     let (l1_gas_usage, resources) = extract_l1_gas_and_vm_usage(resources);
>     let (l1_blob_gas_usage, resources) = extract_l1_blob_gas_usage(&resources);
>     let vm_usage_gas_vector = calculate_l1_gas_by_vm_usage(versioned_constants, &resources)?;
> ```

We use `vm` prefix here. Need to re-think about it. 



_Code quote:_
```XML
    let (l1_gas_usage, resources) = extract_l1_gas_and_vm_usage(resources);
    let (l1_blob_gas_usage, resources) = extract_l1_blob_gas_usage(&resources);
    let vm_usage_gas_vector = calculate_l1_gas_by_vm_usage(versioned_constants, &resources)?;
```

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1447)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @OriStarkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, 5 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1447)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @MohammadNassar1)

**Pull request merged**
