### PR TITLE
Fix segment_arena resource counting.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/613)

### CODE REVIEW

**Review by barak-b-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/613)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/613#-NXy99Z28stw4Hs6-9bh:-NXy8VAZDsKAhPGAukaR:b-f65lti) ([raw file](https://github.com/starkware-libs/blockifier/blob/b05029747f7db3db7b98c00dd3b0dd2e1a2ffe0a/crates/blockifier/src/transaction/transaction_utils.rs#L63)):*
> ```XML
> 
>     // Add additional Cairo resources needed for the OS to run the transaction.
>     let total_vm_usage = &execution_resources.vm_resources
> ```

I don't like the shadowing mechanism, but feel free to keep that way (:



_Suggestion:_
```XML
    let total_vm_usage_with_segment_arena_builtin = &execution_resources.vm_resources
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/613#-NXy9TBd7akYc9xCTgOT:-NXy9TBd7akYc9xCTgOU:b-shmiuq) ([raw file](https://github.com/starkware-libs/blockifier/blob/b05029747f7db3db7b98c00dd3b0dd2e1a2ffe0a/crates/blockifier/src/transaction/transaction_utils.rs#L65)):*
> ```XML
>     let total_vm_usage = &execution_resources.vm_resources
>         + &get_additional_os_resources(execution_resources.syscall_counter, tx_type)?;
>     let mut total_vm_usage = total_vm_usage.filter_unused_builtins();
> ```

And I don't think you use the `total_vm_usage_with_segment_arena_builtin` so maybe you can do something like (not sure that the syntax is correct):



_Suggestion:_
```XML
    let mut total_vm_usage = (&execution_resources.vm_resources + &get_additional_os_resources(execution_resources.syscall_counter, tx_type)?).filter_unused_builtins();
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/613)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/613#-NXy99Z28stw4Hs6-9bh:-NXyEFN04W-VkbIJ4v1h:b-wwwu13) ([raw file](https://github.com/starkware-libs/blockifier/blob/b05029747f7db3db7b98c00dd3b0dd2e1a2ffe0a/crates/blockifier/src/transaction/transaction_utils.rs#L63)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I don't like the shadowing mechanism, but feel free to keep that way (:
</blockquote></details>

The main problem is that I remove the `segment_arena_builtin` using a mutable object so using this name is inaccurate. WDYT?
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/613#-NXy9TBd7akYc9xCTgOT:-NXyEct02JwJPs07Rtp0:b-8cmzgs) ([raw file](https://github.com/starkware-libs/blockifier/blob/b05029747f7db3db7b98c00dd3b0dd2e1a2ffe0a/crates/blockifier/src/transaction/transaction_utils.rs#L65)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

And I don't think you use the `total_vm_usage_with_segment_arena_builtin` so maybe you can do something like (not sure that the syntax is correct):
</blockquote></details>

Maybe it's less readable?

**Review by barak-b-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/613)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/613#-NXy99Z28stw4Hs6-9bh:-NXyHhcRDd09Pkv22bS5:b-5bgw9) ([raw file](https://github.com/starkware-libs/blockifier/blob/b05029747f7db3db7b98c00dd3b0dd2e1a2ffe0a/crates/blockifier/src/transaction/transaction_utils.rs#L63)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The main problem is that I remove the `segment_arena_builtin` using a mutable object so using this name is inaccurate. WDYT?
</blockquote></details>

I think it's OK (:
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/613#-NXy9TBd7akYc9xCTgOT:-NXyHmBuAlA63oC93TNm:bjigxg2) ([raw file](https://github.com/starkware-libs/blockifier/blob/b05029747f7db3db7b98c00dd3b0dd2e1a2ffe0a/crates/blockifier/src/transaction/transaction_utils.rs#L65)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe it's less readable?
</blockquote></details>

Your decision (:

**Review by barak-b-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/613)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/613#-:-NYDDoNh-G6ZqeooOyba:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
