### PR TITLE
fix(native_blockifier): fix unused imports

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1442)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
Can you please give more context?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1442#-:-Npy_WnaA-2hBfjHh4cG:b-jgzu6s)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by OriStarkware — COMMENTED** [review]
Yes, these are the imports that cause the udeps to fail in all the other PRs. This is the fix.
We should use these imports only in the relevant tests.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1442#-:-NpyaIPmDDwG1DybL7DP:buzp75i)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by noaov1 — COMMENTED** [review]
Interesting. Why? Why suddenly?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1442#-:-NpybDf_D4SGDHO6ZyFv:b8hrdzf)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by OriStarkware — COMMENTED** [review]
It should have never passed CI; we are not sure why it passed.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1442#-:-NpybmiBBo46fbLh1bAt:bou2l9p)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1442#-:-NpyjU2R4TBaAHCI0S7h:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
