### PR TITLE
chore(native_blockifier): remove unnecessary checks

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1964)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
Python PR?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1964#-:-NzhU-Dk-0fFUGtBah-i:bta0nby)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
[Here](https://github.com/starkware-industries/starkware/pull/35177)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1964#-:-Nzhms5VDU2Q435WuXSy:bp8xehu)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1964)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1964#-NzmjFZg3jwYsTKSnMUJ:-NzmjFZg3jwYsTKSnMUK:b-kstni5) ([raw file](https://github.com/starkware-libs/blockifier/blob/a34e203e5865df358a15adf53a6618e6eccb7508/crates/native_blockifier/src/py_block_executor.rs#L59)):*
> ```XML
>     pub actual_resources: ResourcesMapping,
>     pub revert_error: Option<String>,
>     pub total_gas: GasVector,
> ```

this removal is still relevant...? did you rebase over Aviv's work?



_Code quote:_
```XML
pub total_gas: GasVector,
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1964)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1964#-NzmjFZg3jwYsTKSnMUJ:-NzwBtv_CMkSVHEjm9RD:b-vz40ak) ([raw file](https://github.com/starkware-libs/blockifier/blob/d179561f12391752e5e2f3d79981160908192a17/crates/native_blockifier/src/py_block_executor.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this removal is still relevant...? did you rebase over Aviv's work?
</blockquote></details>

Cool, Done

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1964)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Pull request merged**
