### PR TITLE
feat(fee): preparation-add the calldata length to the resource calculation

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1361)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1361)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1361#-NopdOs008hSIr8j62tX:-NopdOs008hSIr8j62tY:bo14o25) ([raw file](https://github.com/starkware-libs/blockifier/blob/af4524abd724af6ec6f4f69cbeb0033edd1528c2/crates/blockifier/src/fee/actual_cost.rs#L47)):*
> ```XML
>     sender_address: Option<ContractAddress>,
>     l1_payload_size: Option<usize>,
>     calldata_length: Option<usize>,
> ```

Why option?



_Code quote:_
```XML
: Option<usize>,
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1361)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1361#-NopdOs008hSIr8j62tX:-Nopdjod3APQERF_uEOM:b-avjp1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/af4524abd724af6ec6f4f69cbeb0033edd1528c2/crates/blockifier/src/fee/actual_cost.rs#L47)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why option?
</blockquote></details>

Oh, goaal nefesh
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1361#-Nope-vM5EQlzdAETzXh:-Nope-vM5EQlzdAETzXi:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/af4524abd724af6ec6f4f69cbeb0033edd1528c2/crates/blockifier/src/fee/actual_cost.rs#L113)):*
> ```XML
>     pub fn with_l1_payload_size(mut self, l1_payload_size: usize) -> Self {
>         self.l1_payload_size = Some(l1_payload_size);
>         self.calldata_length = self.l1_payload_size;
> ```

?



_Code quote:_
```XML
self.calldata_length = self.l1_payload_size;
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1361)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1361#-Nope-vM5EQlzdAETzXh:-NoqH-zXBNZ2l-v0LQrJ:b5irzs2) ([raw file](https://github.com/starkware-libs/blockifier/blob/af4524abd724af6ec6f4f69cbeb0033edd1528c2/crates/blockifier/src/fee/actual_cost.rs#L113)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

?
</blockquote></details>

The length of the payload is also the length of the calldata (each serves different purposes).

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1361#-:-NoqP52EA9FfLf0XZwKT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1361)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1361#-NopdOs008hSIr8j62tX:-NouIp9Z5HnCX72yWBfr:bz1x05w) ([raw file](https://github.com/starkware-libs/blockifier/blob/af4524abd724af6ec6f4f69cbeb0033edd1528c2/crates/blockifier/src/fee/actual_cost.rs#L47)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh, goaal nefesh
</blockquote></details>

Wait, sorry. are you sure you can't make it usize? every tx has calldata length (unlike other optional fields)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1361)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1361#-NopdOs008hSIr8j62tX:-NouJA-P0C0hVE9lAUAb:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/af4524abd724af6ec6f4f69cbeb0033edd1528c2/crates/blockifier/src/fee/actual_cost.rs#L47)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Wait, sorry. are you sure you can't make it usize? every tx has calldata length (unlike other optional fields)
</blockquote></details>

.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1361#-:-NoufDfQ2xRgodS-P3gN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
