### PR TITLE
build: add total gas to transactionexecutioninfo

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1933)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1933)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1933#-Nz7a5ML08Dco5yg64Yq:-Nz7a5ML08Dco5yg64Yr:b60ecgk) (no related file):*
link to python side PR?

___

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1933)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1933#-Nz7a5ML08Dco5yg64Yq:-Nz7amNB4-J7pwW1e0JA:bj52ukd) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

link to python side PR?
</blockquote></details>

https://reviewable.io/reviews/starkware-industries/starkware/35115#-

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1933)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1933#-Nz7a5ML08Dco5yg64Yq:-Nz86hQdCXjEmqT9LRrk:b-8fgk38) (no related file):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

https://reviewable.io/reviews/starkware-industries/starkware/35115#-
</blockquote></details>

blocking until python side passes

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1933#-:-Nzbualm3X89py71EO57:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
