### PR TITLE
Add Cairo 1 contract support for test_invoke_tx.

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/708#-NZae_dI4yeNCZYdFPz0:-NZae_dJAJBQjl-i6NJ2:b-fmmy84) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0277cfe8db276b29ce15addf23c27748caddfa9/crates/blockifier/feature_contracts/cairo1/account.cairo#L26)):*
> ```Cairo
> 
>     #[external(v0)]
>     fn __validate__(self: @ContractState, contract_address: felt252, selector: felt252, calldata_len: felt252, calldata: felt252) -> felt252 {
> ```

Why is it `felt252` here while in `__execute__` it is `ContractAddress`?
Same question for the different type you chose for the `calldata` parameter.



_Code quote:_
```Cairo
contract_address: felt252
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 629 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/708#-NZaix6t9N6LxEr5hmq5:-NZaix6t9N6LxEr5hmq6:b21uch3) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0277cfe8db276b29ce15addf23c27748caddfa9/crates/blockifier/src/transaction/transactions_test.rs#L629)):*
> ```XML
>     let expected_account_class_hash = ClassHash(stark_felt!(TEST_ACCOUNT_CONTRACT_CLASS_HASH));
>     let expected_account_address = ContractAddress(patricia_key!(TEST_ACCOUNT_CONTRACT_ADDRESS));
>     let expected_gas_consumed = 0;
> ```

I wonder why the gas consumed both by declare and deploy account txs is 0. All the `__validate__` functions are empty (they do have different input arguments though)



_Code quote:_
```XML
 let expected_gas_consumed = 0;
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/708#-NZae_dI4yeNCZYdFPz0:-NZfro00AKcD2gaNJqP1:b8z2fso) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0277cfe8db276b29ce15addf23c27748caddfa9/crates/blockifier/feature_contracts/cairo1/account.cairo#L26)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it `felt252` here while in `__execute__` it is `ContractAddress`?
Same question for the different type you chose for the `calldata` parameter.
</blockquote></details>

Updated. Mow the input arguments are aligned.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 629 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/708#-NZaix6t9N6LxEr5hmq5:-NZfsGcpCl_JQ7-qRWqM:bt4t9j4) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0277cfe8db276b29ce15addf23c27748caddfa9/crates/blockifier/src/transaction/transactions_test.rs#L629)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder why the gas consumed both by declare and deploy account txs is 0. All the `__validate__` functions are empty (they do have different input arguments though)
</blockquote></details>

Interesting, I'm asking the Compiler team about it.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_DB-DMD8CFuGJd_wb4:-N_DB-DN0cv5BvInoNse:b-4uveyo) ([raw file](https://github.com/starkware-libs/blockifier/blob/4653d79a72bb64a620b7eada2f6ba9e14eed370b/crates/blockifier/src/transaction/transactions_test.rs#L71)):*
> ```XML
>     expected_return_result_call_gas_cost: u64,
>     cairo_version: CairoVersion,
> }
> ```

I think `inner_call_initial_gas` is more clear (I don't think that `expected_return_result_call_gas_cost` is the actual gas cost of the inner call).



_Suggestion:_
```XML
struct ExpectedResultTestInvokeTx {
    range_check: usize,
    n_steps: usize,
    vm_resources: VmExecutionResources,
    retdata: Retdata,
    validate_gas_consumed: u64,
    execute_gas_consumed: u64,
    inner_call_initial_gas: u64,
}
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_D91Wk44UHbNDwFcAl:-N_D91Wl3-5iO6MXXqgc:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4653d79a72bb64a620b7eada2f6ba9e14eed370b/crates/blockifier/src/transaction/transactions_test.rs#L92)):*
> ```XML
>             7
>         }
>         CairoVersion::Cairo1 => 2,
> ```





_Suggestion:_
```XML
        CairoVersion::Cairo1 => {
            if entry_point_selector_name == constants::VALIDATE_ENTRY_POINT_NAME { 7 } else { 2 }
        }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_DB-DMD8CFuGJd_wb4:-N_E4VP29HxUXkwHE6i4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4653d79a72bb64a620b7eada2f6ba9e14eed370b/crates/blockifier/src/transaction/transactions_test.rs#L71)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think `inner_call_initial_gas` is more clear (I don't think that `expected_return_result_call_gas_cost` is the actual gas cost of the inner call).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_D91Wk44UHbNDwFcAl:-N_Dr0o-1mv-MVzJ0dBX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4653d79a72bb64a620b7eada2f6ba9e14eed370b/crates/blockifier/src/transaction/transactions_test.rs#L92)):*
> ```XML
>             7
>         }
>         CairoVersion::Cairo1 => 2,
> ```

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: all files reviewed, 7 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_DB-DMD8CFuGJd_wb4:-N_E7cJ3-3jhSYnjpTQj:b-wjcxsk) ([raw file](https://github.com/starkware-libs/blockifier/blob/4653d79a72bb64a620b7eada2f6ba9e14eed370b/crates/blockifier/src/transaction/transactions_test.rs#L71)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still missing the name of the struct :)
And given the new name: I think you can remove the `cairo_version` from the struct and pass it sepratly. 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 277 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_EGFan2JTf9Rs0gfpL:-N_EGFan2JTf9Rs0gfpM:b75osro) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L277)):*
> ```XML
>             builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 7)]),
>         },
>         validate_gas_consumed: 14760,
> ```

Add a note explaining where this is coming for (as opposed to other `validate` entry points)



_Code quote:_
```XML
validate_gas_consumed: 14760,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 278 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_EG9-mDe_d4L1Y-vr7:-N_EG9-mDe_d4L1Y-vr8:b-rxc29v) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L278)):*
> ```XML
>         },
>         validate_gas_consumed: 14760,
>         execute_gas_consumed: 104560,
> ```

How come validate consumes more gas than execute?



_Code quote:_
```XML
        validate_gas_consumed: 14760,
        execute_gas_consumed: 104560,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 321 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_ECNK713rc5CKuo-SI:-N_ECNK713rc5CKuo-SJ:bi886ga) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L321)):*
> ```XML
>         caller_address: sender_address,
>         call_type: CallType::Call,
>         initial_gas: abi_constants::INITIAL_GAS_COST - expected_arguments.inner_call_initial_gas,
> ```

It's not really the inner call initial gas. 



_Code quote:_
```XML
expected_arguments.inner_call_initial_gas
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 321 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_EDMec0onQywihdqzO:-N_EDMec0onQywihdqzP:b-xckdyk) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L321)):*
> ```XML
>         caller_address: sender_address,
>         call_type: CallType::Call,
>         initial_gas: abi_constants::INITIAL_GAS_COST - expected_arguments.inner_call_initial_gas,
> ```

In thoery, for Cairo1 it should be something like:
But it's not. Can you please ask someone from the compiler team?



_Suggestion:_
```XML
Transaction::initial_gas() - expected_arguments.validate_gas_consumed - constants::GET_EXECUTION_INFO_GAS_COST - constants::CALL_CONTRACT_GAS_COST - 
2 * SYSCALL_BASE,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 564 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_ERyq15fV9cTWHQ5NA:-N_ERyq15fV9cTWHQ5NB:b-tj3egc) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L564)):*
> ```XML
> #[test_case(
>     &mut create_state_with_trivial_validation_account(),
>     63, // RANGE_CHECK_BUILTIN_NAME
> ```

Can you please change it in all the relevant places?



_Suggestion:_
```XML
range_check_builtin
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 565 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_ES1pe02yrlH8lPdCU:-N_ES1pe02yrlH8lPdCV:brhumzt) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L565)):*
> ```XML
>     &mut create_state_with_trivial_validation_account(),
>     63, // RANGE_CHECK_BUILTIN_NAME
>     2715, // N_STEPS_RESOURCE
> ```

Same here.



_Suggestion:_
```XML
n_steps
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_DB-DMD8CFuGJd_wb4:-N_SRbVC2gibDQ7OrWm-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4653d79a72bb64a620b7eada2f6ba9e14eed370b/crates/blockifier/src/transaction/transactions_test.rs#L71)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Still missing the name of the struct :)
And given the new name: I think you can remove the `cairo_version` from the struct and pass it sepratly. 
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 278 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_EG9-mDe_d4L1Y-vr7:-N_SbBFx-tLbQOxZutym:bqwhree) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L278)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

How come validate consumes more gas than execute?
</blockquote></details>

It is not, the execute gas is seven times larger.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 321 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_ECNK713rc5CKuo-SI:-N_SWY_9EdU5gDyKFXVZ:b7m0zw2) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L321)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It's not really the inner call initial gas. 
</blockquote></details>

Changed to `abi_constants::INITIAL_GAS_COST - <prev. value>`. Now it is the inner call initial gas.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 564 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_ERyq15fV9cTWHQ5NA:-N_SR9sLBCeWOhoz6EPH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L564)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please change it in all the relevant places?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 565 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_ES1pe02yrlH8lPdCU:-N_SRAJo5aBXMxSmt_JA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L565)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 278 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_EG9-mDe_d4L1Y-vr7:-N_UCU8b2oiq_S-DmfWH:bdiecbc) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L278)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It is not, the execute gas is seven times larger.
</blockquote></details>

Right :)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 62 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_Ye9UO1--LpPTgYcm5:-N_Ye9UO1--LpPTgYcm6:bbqyvas) ([raw file](https://github.com/starkware-libs/blockifier/blob/f35bda544ab370b78a26c7a3ffe54b596af07c0e/crates/blockifier/src/transaction/transactions_test.rs#L62)):*
> ```XML
> }
> 
> struct ExpectedResultTestInvokeTx {
> ```

I'm not sure it defining a struct is better than simply ignoring the `too many arguments` error of clippy.  Do you think it's more readable?



_Code quote:_
```XML
struct ExpectedResultTestInvokeTx 
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 279 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_Z6jMqB-Gy7OVr9Jrn:-N_Z6jMqB-Gy7OVr9Jro:bh70zp0) ([raw file](https://github.com/starkware-libs/blockifier/blob/f35bda544ab370b78a26c7a3ffe54b596af07c0e/crates/blockifier/src/transaction/transactions_test.rs#L279)):*
> ```XML
>         validate_gas_consumed: 14760,
>         execute_gas_consumed: 104560,
>         inner_call_initial_gas: abi_constants::INITIAL_GAS_COST - 319320,
> ```

Please write the explicit number



_Suggestion:_
```XML
inner_call_initial_gas: number
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 277 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_EGFan2JTf9Rs0gfpL:-N_Z9MBx8viz2xHbO1ND:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L277)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Add a note explaining where this is coming for (as opposed to other `validate` entry points)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 278 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_EG9-mDe_d4L1Y-vr7:-N_Z9MYaES0bOmS-clb1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L278)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Right :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 321 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_EDMec0onQywihdqzO:-N_ZDP4p0azXguFs7bnN:bl507kc) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a9999caab9c6eef56038442ccbdff81fb5cdb58/crates/blockifier/src/transaction/transactions_test.rs#L321)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In thoery, for Cairo1 it should be something like:
But it's not. Can you please ask someone from the compiler team?
</blockquote></details>

I have sent you the calculation on Slack.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 62 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_Ye9UO1--LpPTgYcm5:-N_ZCDog8ZrTCtymQXz_:b-qh0myh) ([raw file](https://github.com/starkware-libs/blockifier/blob/f35bda544ab370b78a26c7a3ffe54b596af07c0e/crates/blockifier/src/transaction/transactions_test.rs#L62)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm not sure it defining a struct is better than simply ignoring the `too many arguments` error of clippy.  Do you think it's more readable?
</blockquote></details>

I find it more readable as each argument is preceded by its respective name.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 279 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_Z6jMqB-Gy7OVr9Jrn:-N_ZBjl082gmc4X09hB_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f35bda544ab370b78a26c7a3ffe54b596af07c0e/crates/blockifier/src/transaction/transactions_test.rs#L279)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please write the explicit number
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 278 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_ZM07e46oiCUz6fYMA:-N_ZM07e46oiCUz6fYMB:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc241f86c5d3563c205ffc20e541f3e7be1e0d86/crates/blockifier/src/transaction/transactions_test.rs#L278)):*
> ```XML
>         },
>         validate_gas_consumed: 14760, // A major portion of gas is consumed during the parsing of
>             // Array<felt252> variable within the `__validate__` function.
> ```

WDYT?



_Suggestion:_
```XML
        validate_gas_consumed: 14760, // The gas consumption results from parsing the input arguments.
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 278 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/708#-N_ZM07e46oiCUz6fYMA:-N_ZNlZv1uSajS-8o0mg:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc241f86c5d3563c205ffc20e541f3e7be1e0d86/crates/blockifier/src/transaction/transactions_test.rs#L278)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708#-:-N_ZQ21L4pj7xsde-OeQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/708)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
