### PR TITLE
refactor: bouncer add calculation for builtins and n_steps counting

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1581)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
This logic should be compared with the logic in the execute function of the transaction executor

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-:-NrUn8pv3kiOZj5Kw1aE:b-einztr)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1581)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Nr_17GG5s5uwOl5BWkA:-Nr_17GG5s5uwOl5BWkB:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b8ff0dd6afb94944bcc36cbe254afdf92c2f086/crates/blockifier/src/bouncer.rs#L83)):*
> ```XML
> 
> impl From<&ResourcesMapping> for BuiltinCount {
>     fn from(resource_mapping: &ResourcesMapping) -> Self {
> ```





_Suggestion:_
```XML
resources
```
___
*[`crates/blockifier/src/bouncer.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Nr_0i7P-Ckv7xt93h_P:-Nr_0i7P-Ckv7xt93h_Q:b-cfv58k) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b8ff0dd6afb94944bcc36cbe254afdf92c2f086/crates/blockifier/src/bouncer.rs#L84)):*
> ```XML
> impl From<&ResourcesMapping> for BuiltinCount {
>     fn from(resource_mapping: &ResourcesMapping) -> Self {
>         Self {
> ```

Use canonical names [from the VM](https://github.com/starkware-libs/blockifier/blob/d017ea67a27b28b9c8ce1437998c2c869ded623c/crates/blockifier/src/versioned_constants.rs#L234).
___
*[`crates/blockifier/src/bouncer.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Nr_0MQZ4hPaZPZtcgEb:-Nr_0MQZ4hPaZPZtcgEc:b-lb1oai) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b8ff0dd6afb94944bcc36cbe254afdf92c2f086/crates/blockifier/src/bouncer.rs#L148)):*
> ```XML
>         execution_info_resources: &ResourcesMapping,
>         state: &mut TransactionalState<'_, S>,
>     ) -> TransactionExecutorResult<(usize, BuiltinCount)> {
> ```

WDYT of returning `ExecutionResources` instead?



_Code quote:_
```XML
(usize, BuiltinCount)
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Nr_07kD-yT-til_lRoZ:-Nr_07kD-yT-til_lRo_:b-385eep) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b8ff0dd6afb94944bcc36cbe254afdf92c2f086/crates/blockifier/src/transaction/objects.rs#L257)):*
> ```XML
>     pub fn get_builtin_count_or_default(&self, name: &str) -> usize {
>         *self.0.get(name).unwrap_or(&0)
>     }
> ```

Can you use `unwrap_or_default`?



_Suggestion:_
```XML
    pub fn get_or_default(&self, builtin_name: &str) -> usize {
        *self.0.get(name).unwrap_or(&0)
    }
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1581)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/bouncer.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Nr_17GG5s5uwOl5BWkA:-NriRacBDUIp6jAkJO8v:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b8ff0dd6afb94944bcc36cbe254afdf92c2f086/crates/blockifier/src/bouncer.rs#L83)):*
> ```XML
> 
> impl From<&ResourcesMapping> for BuiltinCount {
>     fn from(resource_mapping: &ResourcesMapping) -> Self {
> ```

done
___
*[`crates/blockifier/src/bouncer.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Nr_0i7P-Ckv7xt93h_P:-NriRbDf2loaS7zDeS1s:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b8ff0dd6afb94944bcc36cbe254afdf92c2f086/crates/blockifier/src/bouncer.rs#L84)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use canonical names [from the VM](https://github.com/starkware-libs/blockifier/blob/d017ea67a27b28b9c8ce1437998c2c869ded623c/crates/blockifier/src/versioned_constants.rs#L234).
</blockquote></details>

done
___
*[`crates/blockifier/src/bouncer.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Nr_0MQZ4hPaZPZtcgEb:-NriRcKQBdpXW-SYo6IZ:b-xz2oa6) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b8ff0dd6afb94944bcc36cbe254afdf92c2f086/crates/blockifier/src/bouncer.rs#L148)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT of returning `ExecutionResources` instead?
</blockquote></details>

I'm intentionally returning the bouncer objects so eventually the transactional_bouncer.update() function will be simple to read.
this will become clear in the following PRs.
but we can revisit this later and see what you think.
(I'll add it to my list of notes to ask you later)
___
*[`crates/blockifier/src/transaction/objects.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Nr_07kD-yT-til_lRoZ:-NriS7vn5mfXV7pHS4Yt:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b8ff0dd6afb94944bcc36cbe254afdf92c2f086/crates/blockifier/src/transaction/objects.rs#L257)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you use `unwrap_or_default`?
</blockquote></details>

done

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1581)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/bouncer.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-NrkMyCh3DpLeIPvo1yP:-NrkMyCh3DpLeIPvo1yQ:beot7ld) ([raw file](https://github.com/starkware-libs/blockifier/blob/613f0a3595f9e823305f153b0ab089e04c83c764/crates/blockifier/src/bouncer.rs#L65)):*
> ```XML
>     poseidon: usize,
>     range_check: usize,
> }
> ```

after speaking to Lior , I removed segment_arena and output from the list since both should never be present in the transaction builtin count
segment_arena is counted as part of the steps and output just doesn't exist in transactions

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1581)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Ns3oLEa5OMym-1GolSK:-Ns3oLEa5OMym-1GolSL:b-2rsw7h) ([raw file](https://github.com/starkware-libs/blockifier/blob/613f0a3595f9e823305f153b0ab089e04c83c764/crates/blockifier/src/bouncer.rs#L74)):*
> ```XML
>     fn from(resources: &ResourcesMapping) -> Self {
>         Self {
>             bitwise: resources.get_or_default(BuiltinName::bitwise.name()),
> ```

is it possible to use `unwrap_or_default`?

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1581)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Ns3oLEa5OMym-1GolSK:-NsD7SMN0pvMF666t0ul:b-lv8072) ([raw file](https://github.com/starkware-libs/blockifier/blob/613f0a3595f9e823305f153b0ab089e04c83c764/crates/blockifier/src/bouncer.rs#L74)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

is it possible to use `unwrap_or_default`?
</blockquote></details>

great minds... see elin's comment inside get_or_default below
___
*[`crates/blockifier/src/bouncer.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-NsDAmXN9xxvnYreCkfm:-NsDAmXN9xxvnYreCkfn:b-hfpv1m) ([raw file](https://github.com/starkware-libs/blockifier/blob/613f0a3595f9e823305f153b0ab089e04c83c764/crates/blockifier/src/bouncer.rs#L78)):*
> ```XML
>             ec_op: resources.get_or_default(BuiltinName::ec_op.name()),
>             keccak: resources.get_or_default(BuiltinName::keccak.name()),
>             output: resources.get_or_default(BuiltinName::output.name()),
> ```

remove?



_Code quote:_
```XML
            output: resources.get_or_default(BuiltinName::output.name()),
```
___
*[`crates/blockifier/src/bouncer.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-NsDAwqO6laIeF7rAuYC:-NsDAwqO6laIeF7rAuYD:b-dr8eev) ([raw file](https://github.com/starkware-libs/blockifier/blob/613f0a3595f9e823305f153b0ab089e04c83c764/crates/blockifier/src/bouncer.rs#L83)):*
> ```XML
>             range_check: resources.get_or_default(BuiltinName::range_check.name()),
>         }
>         // TODO(yael) think how to enforce that all the builtins are present in the BuiltinCount struct
> ```

WDYMB enforce presence? it's a struct, they must be there, I'm missing something :sweat_smile: 
Maybe you meant in `ResourcesMapping`? if so see my rant below :grimacing:  



_Code quote:_
```XML
        // TODO(yael) think how to enforce that all the builtins are present in the BuiltinCount struct
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-Nr_07kD-yT-til_lRoZ:-NsD6uwq8yF-_dtJxAqF:b-utilx2) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b8ff0dd6afb94944bcc36cbe254afdf92c2f086/crates/blockifier/src/transaction/objects.rs#L257)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done
</blockquote></details>

She meant two changes: the first is what you changed, the second is to change the logic from `*self.0.get(name).unwrap_or(&0)` into `self.0.get(name).copied().unwrap_or_default()`, which generates the default value of the return value (which happens to be 0 for `usize`)
___
*[`crates/blockifier/src/transaction/objects.rs` line 237 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1581#-NsD9Ty-81wAJCBJrmll:-NsD9Ty-81wAJCBJrmlm:b-aovpyx) ([raw file](https://github.com/starkware-libs/blockifier/blob/b2abf3fd5495b3ae78602a0d3899ebd8a68d2a60/crates/blockifier/src/transaction/objects.rs#L237)):*
> ```XML
> #[cfg_attr(test, derive(Clone))]
> #[derive(Debug, Default, Eq, PartialEq, Serialize)]
> pub struct ResourcesMapping(pub HashMap<String, usize>);
> ```

Unrelated to this PR, but does this internal mapping have fixed keys? @noaov1 
(For example, it must have the keys "gas_usage", "n_steps",..., "other_name" and only them.)

If so, then (in a separate PR)   the inner map should not be `pub` (to protect against deleting them), and have getters/setters, or ideally it should just a a regular struct, but I'm guessing that option is blocked due to some implementation constraint.

If they aren't fixed and it's freely modifiable, then add `derive_more::deref` and remove all the `.0.` from accessors to this class (in a separate PR)



_Code quote:_
```XML
pub struct ResourcesMapping(pub HashMap<String, usize>);
```

**Comment by Yael-Starkware** [comment]
the code I'm working on has changed so I opening a new PR.

**Pull request closed without merging**
