### PR TITLE
Add transactional execution functionality.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/316)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/316)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/state/cached_state.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/316#-NPVZllsBwz1D8OFL-kU:-NPVZllsBwz1D8OFL-kV:bap2gtf) ([raw file](https://github.com/starkware-libs/blockifier/blob/aaaf682bd5704fc9c5ea23c8e1fd13fea3fcdc7e/crates/blockifier/src/state/cached_state.rs#L19)):*
> ```XML
> 
> pub type ContractClassMapping = HashMap<ClassHash, ContractClass>;
> pub type TransactionalState<'a, S> = CachedState<MutRefState<'a, CachedState<S>>>;
> ```

As discussed, later make the second CachedState just a State, or maybe add a trait that it can "multiupdate".
Perhaps add a todo for now
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/316#-NPV_puODkuksQaOfg9l:-NPV_puODkuksQaOfg9m:bmj7kz5) ([raw file](https://github.com/starkware-libs/blockifier/blob/aaaf682bd5704fc9c5ea23c8e1fd13fea3fcdc7e/crates/blockifier/src/transaction/account_transaction.rs#L55)):*
> ```XML
>     }
> 
>     /// Executes the transaction in a non-transactional manner.
> ```

Add some description about what may happen if it fails.
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/316#-NPVaESCEgpH-IjmRNUI:-NPVaESCEgpH-IjmRNUJ:baqlup7) ([raw file](https://github.com/starkware-libs/blockifier/blob/aaaf682bd5704fc9c5ea23c8e1fd13fea3fcdc7e/crates/blockifier/src/transaction/transaction_utils.rs#L30)):*
> ```XML
> }
> 
> pub fn execute_transactionally<'a, S, T, ExecuteCallback>(
> ```

You can do this in another kinda equivalent way which I personally like more.
Instead of getting a function that adhere to the specific execute signature,
Make a trait for the executable tx with the execute method, and constraint T to be of that trait.
Then you could call tx.execute_raw.

Another benefit: instead of having this as a floating function, and implementing execute () on each of the tx struct,
You can just add an impl (and maybe a trait TransactionEx) with this function.
You will also auto get it for everything that implements the Tx trait.

You also eant this for InvokeTx, DeclareTx, I think.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/316)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/316#-NPVZllsBwz1D8OFL-kU:-NPWfupI3ViAJR5KDt0X:bwer14r) ([raw file](https://github.com/starkware-libs/blockifier/blob/aaaf682bd5704fc9c5ea23c8e1fd13fea3fcdc7e/crates/blockifier/src/state/cached_state.rs#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

As discussed, later make the second CachedState just a State, or maybe add a trait that it can "multiupdate".
Perhaps add a todo for now
</blockquote></details>

Added [a Monday item](https://starkware.monday.com/boards/3469564484/pulses/4073343872).
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/316#-NPV_puODkuksQaOfg9l:-NPWfXL6-bp8A0zBPfLO:b-z8u9rr) ([raw file](https://github.com/starkware-libs/blockifier/blob/aaaf682bd5704fc9c5ea23c8e1fd13fea3fcdc7e/crates/blockifier/src/transaction/account_transaction.rs#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add some description about what may happen if it fails.
</blockquote></details>

Done (code only moved down as-is).
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/316#-NPVaESCEgpH-IjmRNUI:-NPWfY2i3YQLO8Gk9Zpb:bveorjb) ([raw file](https://github.com/starkware-libs/blockifier/blob/aaaf682bd5704fc9c5ea23c8e1fd13fea3fcdc7e/crates/blockifier/src/transaction/transaction_utils.rs#L30)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You can do this in another kinda equivalent way which I personally like more.
Instead of getting a function that adhere to the specific execute signature,
Make a trait for the executable tx with the execute method, and constraint T to be of that trait.
Then you could call tx.execute_raw.

Another benefit: instead of having this as a floating function, and implementing execute () on each of the tx struct,
You can just add an impl (and maybe a trait TransactionEx) with this function.
You will also auto get it for everything that implements the Tx trait.

You also eant this for InvokeTx, DeclareTx, I think.
</blockquote></details>

Done.
Requires other refactors (as we talked); all in [this Monday item](https://starkware.monday.com/boards/3469564484/pulses/4051708544).

**Review by spapinistarkware — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/316#-:-NPWnLfy3xnk-ZKKrxMG:bnfp4nl)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/316#-NPWn2953liyezNVDm7V:-NPWn2953liyezNVDm7W:bfczmzn) ([raw file](https://github.com/starkware-libs/blockifier/blob/0478d557ba4f047c0e5a849f3f1397a6e3033910/crates/blockifier/src/transaction/transaction_execution.rs#L28)):*
> ```XML
>             Self::AccountTransaction(account_tx) => account_tx.execute(state, block_context)?,
>             Self::L1HandlerTransaction(tx) => {
>                 let tx_context = AccountTransactionContext {
> ```

Can this be in the ExeutableTransaction impl for L1HandlerTransaction?
This will be helpful if someone has L1HandlerTx in their hands and he wants to execute.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/316)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/316#-NPWueIy0n2XFXUDZpWQ:-NPWueIy0n2XFXUDZpWR:b9zbs8g) ([raw file](https://github.com/starkware-libs/blockifier/blob/50c32d43100bf6e9f36897f059e4c08ad98bc69e/crates/blockifier/src/transaction/transactions.rs#L61)):*
> ```XML
> 
> pub trait Executable<S: State> {
>     fn run_execute(
> ```

Collided with `ExecutableTransaction`'s `execute`.



_Code quote:_
```XML
run_execute
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/316)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/316)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by alon-dotan-starkware — APPROVED** [review]

**Pull request merged**
