### PR TITLE
test: extract get test state reader function

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1799)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1799?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1799** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1799?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1798** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1798?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1799)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1799#-NvjzdMy78GY_aQbOb6E:-NvjzdMy78GY_aQbOb6F:b4mjirh) ([raw file](https://github.com/starkware-libs/blockifier/blob/296e486ef57c72bb9c863760fdb56242009b2d99/crates/blockifier/src/test_utils/initial_test_state.rs#L94)):*
> ```XML
> /// * "Declares" the input list of contracts.
> /// * "Deploys" the requested number of instances of each input contract.
> /// * Makes each input account contract privileged.
> ```

don't copy the comment (double point of doc)



_Suggestion:_
```XML
/// Initializes a state for testing, with the output of test_state_reader as the initial state.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1799)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1799#-NvjzdMy78GY_aQbOb6E:-Nvk-GWu0Mp07lLpxW-v:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/296e486ef57c72bb9c863760fdb56242009b2d99/crates/blockifier/src/test_utils/initial_test_state.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't copy the comment (double point of doc)
</blockquote></details>

Done.

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1799#-:-Nvk1jEP8-v0kkHqwg_0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Apr 18, 3:14 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/1799).

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1799)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
