### PR TITLE
prepare crate for no_std

### PR DESCRIPTION
**Pull request by tdelabro**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342)

### CODE REVIEW

**Comment by tdelabro** [comment]
@elintul wdyt?

**Review by abdelhamidbakhta — APPROVED** [review]
lgtm

**Review by abdelhamidbakhta — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342#-:-NR3BfWS4YsoWp9hF7o-:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @tdelabro)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/342#-NRSSncm3Cp55SFr2E3e:-NRSSncnE6lLAm5oXbfE:b-1a506f) (no related file):*
Please wait with this. I want to understand the ramifications of adding `unsafe` code to our repo.; also, it's my understanding we can't use `thiserror` anymore? 

___

**Comment by tdelabro** [comment]
@elintul I think @abdelhamidbakhta forwarded you some of my answers on telegram. Is there still questions about this PR?

**Review by elintul — COMMENTED** [review]
We reverted the `no_std` support on SN API since it blocked our critical path.
We decided with Abdel that you'll add it on a fork from both repos.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342#-:-NRcdSnN9Wj8cfdh01mm:bueyvad)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @tdelabro)

**Review by elintul — COMMENTED** [review]
We couldn't take a bugfix from SN API, since it also included `no_std`. It forbids us fro using `thiserror`, and this is a design decision we haven't made.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342#-:-NRftnpI0b-HQutIwoP0:b-p8r8cr)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @tdelabro)

**Comment by tdelabro** [comment]
If you have a hard commitment to using thiserror, you can use thiserror-no-std instead. It's just not my preferred way.
As I said to abdel, there is "nothing fundamentally wrong" with this crate, I an simply less confident about it's implem and the way it is maintained

**Comment by tdelabro** [comment]
About this specific PR, it does not introduce `no_std`, but it improves your code in several ways, using constant rather than lazy static, using a perfect hash map rather than a hash map, and making the users able to import the papyrus implem only if they actually need it.
I think it should be merged regardless of the `no_std` support.

**Review by elintul — COMMENTED** [review]
I'll review it. :)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342#-:-NRlahWI1dlm71U3stl0:b-bqcop5)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @tdelabro)

**Review by elintul — COMMENTED** [review]
Can this be done on the fork you're using?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342#-:-NSq30Wp92cxboFWdrwS:b-tozx8c)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @tdelabro)

**Comment by tdelabro** [comment]
@elintul  
Yeah it has been done on the fork we are using, otherwise, we wouldn't have been able to run blockifier in a no_std environment, but that is not the point with this PR.

My point here, is that PR add some straight up upgrade to your code. Making it usable outside of papyrus without having to import papyrus stuff (which is the case of everybody except people working on papyrys), replacing some statics by constants (which is better) and using a perfect hash function instead of a regular hashmap when possible (which is better).

So I thought you would like to have those stuff in your codebase, because it makes it better and more usable, regardless of any no_std concern.

**Review by elintul — COMMENTED** [review]
I understand that.
Wanted to make sure I'm not blocking you.
Given that, I'll review when times are calmer; we're on a tight schedule.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342#-:-NSyAa793rnEeH_bVsXT:b789l26)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @tdelabro)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @elintul and @tdelabro)

___
*[`crates/blockifier/src/state.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/342#-NSy_abFC7QRX81E8yTX:-NSy_abFC7QRX81E8yTY:b-kr9ynm) ([raw file](https://github.com/starkware-libs/blockifier/blob/9adfde11f4c07b2f5d1e8fed8a35ead835bc1594/crates/blockifier/src/state.rs#L3)):*
> ```XML
> pub mod cached_state;
> pub mod errors;
> #[cfg(feature = "papyrus")]
> ```

Blockifier is not using papyrus anymore (only native_blockifier). Please rebase
___
*[`crates/blockifier/src/test_utils.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/342#-NSya7t8AZfzYhjC35su:-NSya7t8AZfzYhjC35sv:b-fa88pj) ([raw file](https://github.com/starkware-libs/blockifier/blob/9adfde11f4c07b2f5d1e8fed8a35ead835bc1594/crates/blockifier/src/test_utils.rs#L77)):*
> ```XML
> 
> // Storage keys.
> pub const TEST_ERC20_SEQUENCER_BALANCE_KEY: StorageKey = unsafe {
> ```

Is this the recommended way? Is there no way to defined constants in a nostd manner, without using the unsafe keyword?
Also, is it no possible to make get_storage_var_address a const function?
Another option is to not make this a const at all, but a function. It's just for testing, so performance is not veyr important here, and if it would avoid unsafe code, I'd be happy.



_Code quote:_
```XML
pub const TEST_ERC20_SEQUENCER_BALANCE_KEY: StorageKey = unsafe {
    core::mem::transmute([
        0x07u8, 0x23, 0x97, 0x32, 0x08, 0x63, 0x9b, 0x78, 0x39, 0xce, 0x29, 0x8f, 0x7f, 0xfe, 0xa6,
        0x1e, 0x3f, 0x95, 0x33, 0x87, 0x2d, 0xef, 0xd7, 0xab, 0xdb, 0x91, 0x02, 0x3d, 0xb4, 0x65,
        0x88, 0x12,
    ])
};
```

**Review by spapinistarkware — COMMENTED** [review]
I'll check it

> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342#-:-NSybGcm8_CqaVjwm21a:b-vniym8)* status: all files reviewed, 3 unresolved discussions (waiting on @tdelabro)

**Comment by tdelabro** [comment]
Hey @spapinistarkware,

I just forced push a rebase.
I got rid of the const+unsafe part. I replaced it with functions instead. It is a downgrade, but if as you said, it's only used for tests, we don't really care.
The is still one place where you are using OnceCell, in `os_ressources`. Once cell is not compatible with no_std. So if you think you will try to support it at any point in the future, prefers either constants or the lazy_static crate, which is.

Tell me if there is other things that need to change :)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 4 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @tdelabro)

___
*[`crates/blockifier/src/execution/hint_code.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/342#-NTFS9iu4BlNu9gOpTbb:-NTHzDL-2uwD_tTAuFba:b7fv6uu) ([raw file](https://github.com/starkware-libs/blockifier/blob/48ca082350d5922e19cfe7169fee2947150ce895/crates/blockifier/src/execution/hint_code.rs#L3)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this a recommended and maintained crate?
</blockquote></details>

This crate is fine

**Review by spapinistarkware — COMMENTED** [review]
Suggestion: Instead of having a static value, add it as a ctor on OsResources type.
Make get_additional_os_resources (the only place that uses it outside tests) a method of OsResources.
Every user of get_additional_os_resources will now need an instance of OsResources - make sure to create it as further up as possible, preferably, creating it only once at the top

> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342#-:-NTI1FxvDOcPo2MTfiKv:bkvo4ws)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @tdelabro)

**Comment by spapinistarkware** [comment]
> > Suggestion: Instead of having a static value, add it as a ctor on OsResources type. Make get_additional_os_resources (the only place that uses it outside tests) a method of OsResources. Every user of get_additional_os_resources will now need an instance of OsResources - make sure to create it as further up as possible, preferably, creating it only once at the top
> > > Reviewed 1 of 10 files at r2.
> > > _[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342#-:-NTI1FxvDOcPo2MTfiKv:bkvo4ws)_ status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @tdelabro)
> 
> Why can't I just do this?
> 
> ```rust
> #[ctor]
> pub static OS_RESOURCES: OsResources = {
>     serde_json::from_value(os_resources())
>         .expect("os_resources json does not exist or cannot be deserialized.")
> };
> ```
> 
> It seems to work, and avoid the very likely footgun where users of the lib instantiate multiple `OsResources` for their program, therefore having multiple instances of the hashmap. Unless there is a use-case of having multiple instances of `OsResources` with different definitions?
> 
> That's what I did in the last commit. Tell me if it need a change

That looks good. Didn't know about it.
Eventually we will want it outside, I believe. There might be a use for another instance for all the I know, but it's out of scope for this PR.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 10 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342#-:-NTNKqcf64u6iVWcKAV0:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @tdelabro)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/342)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Pull request merged**
