### PR TITLE
feat(concurrency): add finish execution/validation methods to the scheduler

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-Nvl7DYI2nWvleGqwlX2:-Nvl7DYJ3W_1Q0kq2M-c:b-9pfsrd) ([raw file](https://github.com/starkware-libs/blockifier/blob/864bd246da4c16ae3bd2e61433d8c48dabe7a596/crates/blockifier/src/concurrency/scheduler.rs#L98)):*
> ```XML
>     fn set_ready_status(&self, tx_index: TxIndex) {
>         let mut status = self.tx_statuses[tx_index].lock().unwrap();
>         assert_eq!(*status, TransactionStatus::Aborting, "Transaction not aborting");
> ```

Maybe it is too long though. 



_Suggestion:_
```XML
        assert_eq!(*status, TransactionStatus::Aborting, "We initiate re-execution in case of aborted transaction only. Transaction {tx_index} is not aborting");
```
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-Nvl9ZW3Bbi_rK5R8Bni:-Nvl9ZW3Bbi_rK5R8Bnj:b-pxe9y2) ([raw file](https://github.com/starkware-libs/blockifier/blob/864bd246da4c16ae3bd2e61433d8c48dabe7a596/crates/blockifier/src/concurrency/scheduler.rs#L136)):*
> ```XML
>                 if new_version.is_some() {
>                     return Some(Task::ExecutionTask(tx_index));
>                 }
> ```

Why does `try_incarnate` returns `Option<TxIndex>` and not a bool? Is it because of `next_version_to_execute`?



_Suggestion:_
```XML
                if self.try_incarnate(tx_index).is_some() {
                    return Some(Task::ExecutionTask(tx_index));
                }
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-Nvl7DYI2nWvleGqwlX2:-NvlLl8y07qgPhiOiSPZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/864bd246da4c16ae3bd2e61433d8c48dabe7a596/crates/blockifier/src/concurrency/scheduler.rs#L98)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe it is too long though.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-Nvl9ZW3Bbi_rK5R8Bni:-NvlIx5x35Rpm0342KH_:b-4x9r9j) ([raw file](https://github.com/starkware-libs/blockifier/blob/864bd246da4c16ae3bd2e61433d8c48dabe7a596/crates/blockifier/src/concurrency/scheduler.rs#L136)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why does `try_incarnate` returns `Option<TxIndex>` and not a bool? Is it because of `next_version_to_execute`?
</blockquote></details>

Because we return it at the end of `next_version_to_execute` (its output is the output of `next_version_to_execute`).
It is supposed to get a tx_index and return a tuple of (tx_index, incarnation), but we don't have `incarnation`.

Done.

(Clippy made me unify the two `if`s, and now I think it is harder to understand what is going on. Take a look.)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwVKgpa1F-P-Q56YeSj:-NwVKgpa1F-P-Q56YeSk:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/244e8ce0d524dc3f17b47b9eec902a0f506a9721/crates/blockifier/src/concurrency/scheduler.rs#L112)):*
> ```XML
>             TransactionStatus::Aborting,
>             "We initiate re-execution in case of aborted transaction only. Transaction {tx_index} \
>              is not aborting."
> ```





_Suggestion:_
```XML
            "We initiate re-execution in case of aborted transaction only. Transaction {tx_index} \
             is not aborting, but {*status}."
```
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwVK_OrBAwKbKiztBq8:-NwVK_OrBAwKbKiztBq9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/244e8ce0d524dc3f17b47b9eec902a0f506a9721/crates/blockifier/src/concurrency/scheduler.rs#L126)):*
> ```XML
>             *status,
>             TransactionStatus::Executing,
>             "Transaction {tx_index} is not executing."
> ```





_Suggestion:_
```XML
            "Transaction {tx_index} should be executing. It has status {*status} instead."
```
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwVL7In0lB9WnTcu5vQ:-NwVL7In0lB9WnTcu5vR:b-im03g8) ([raw file](https://github.com/starkware-libs/blockifier/blob/244e8ce0d524dc3f17b47b9eec902a0f506a9721/crates/blockifier/src/concurrency/scheduler.rs#L128)):*
> ```XML
>             "Transaction {tx_index} is not executing."
>         );
>         *status = TransactionStatus::Executed;
> ```

I think you can drop the status lock after this line.



_Code quote:_
```XML
        *status = TransactionStatus::Executed;
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwVKgpa1F-P-Q56YeSj:-NwnK48F8y9YlDMvMt_v:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/244e8ce0d524dc3f17b47b9eec902a0f506a9721/crates/blockifier/src/concurrency/scheduler.rs#L112)):*
> ```XML
>             TransactionStatus::Aborting,
>             "We initiate re-execution in case of aborted transaction only. Transaction {tx_index} \
>              is not aborting."
> ```

Done.
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwVK_OrBAwKbKiztBq8:-NwnK5-n0qHcs3r3XQDI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/244e8ce0d524dc3f17b47b9eec902a0f506a9721/crates/blockifier/src/concurrency/scheduler.rs#L126)):*
> ```XML
>             *status,
>             TransactionStatus::Executing,
>             "Transaction {tx_index} is not executing."
> ```

Done.
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwVL7In0lB9WnTcu5vQ:-NwnK6G5EtMtprbq7xc4:b-86zoyu) ([raw file](https://github.com/starkware-libs/blockifier/blob/244e8ce0d524dc3f17b47b9eec902a0f506a9721/crates/blockifier/src/concurrency/scheduler.rs#L128)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think you can drop the status lock after this line.
</blockquote></details>

Done.
I did it by defining a method `set_executed_status`.

**Review by noaov1 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-:-NwtRSuo2bHy50a2-FrM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 127 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwtWfUC3qdjKZjsOV0D:-NwtWfUC3qdjKZjsOV0E:bbxoyda) ([raw file](https://github.com/starkware-libs/blockifier/blob/5e51715107f572237898087681af07a621f4fc13/crates/blockifier/src/concurrency/scheduler.rs#L127)):*
> ```XML
>         );
>         *status = TransactionStatus::ReadyToExecute;
>     }
> ```

Code duplication, I suggest something like:
(and add numbers to the variants in the `TransactionStatus` enum)



_Suggestion:_
```XML
    fn set_tx_status(&self, tx_index: TxIndex, tx_status: TransactionStatus) {
        let mut status = self.lock_tx_status(tx_index);
        assert_eq!(
            *status,
            tx_status as u8 - 1,
            "Transaction status: {status:?} can't be changed to {tx_status}."
        );
        *status = tx_status;
    }
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 150 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwtYbrM5uYLUE1inqjn:-NwtYbrM5uYLUE1inqjo:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5e51715107f572237898087681af07a621f4fc13/crates/blockifier/src/concurrency/scheduler.rs#L150)):*
> ```XML
>     }
> 
>     // TODO(barak, 01/04/2024): Ensure documentation matches logic.
> ```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 129 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwtY_Kx-euyBcnaU78O:-NwtY_Kx-euyBcnaU78P:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5e51715107f572237898087681af07a621f4fc13/crates/blockifier/src/concurrency/scheduler.rs#L129)):*
> ```XML
>     }
> 
>     // TODO(barak, 01/04/2024): Ensure documentation matches logic.
> ```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 127 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwtWfUC3qdjKZjsOV0D:-Nx7R2rN7PGBTUikjGIK:b-vg3z2m) ([raw file](https://github.com/starkware-libs/blockifier/blob/5e51715107f572237898087681af07a621f4fc13/crates/blockifier/src/concurrency/scheduler.rs#L127)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Code duplication, I suggest something like:
(and add numbers to the variants in the `TransactionStatus` enum)
</blockquote></details>

Interesting idea. We must set the enum accordingly (with explicit values). Do you find it readable?

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 127 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwtWfUC3qdjKZjsOV0D:-Nx7esBHDCRyTx_aSa5D:b-i1c7y2) ([raw file](https://github.com/starkware-libs/blockifier/blob/5e51715107f572237898087681af07a621f4fc13/crates/blockifier/src/concurrency/scheduler.rs#L127)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Interesting idea. We must set the enum accordingly (with explicit values). Do you find it readable?
</blockquote></details>

I think it is:
```
enum TransactionStatus {
    ReadyToExecute = 0,
    Executing = 1,
    Executed = 2,
    Aborting = 3,
}
```
instead of:
```
enum TransactionStatus {
    ReadyToExecute,
    Executing,
    Executed,
    Aborting,
}
```
There is a natural order between the statuses and it's even easier for the reader to understand it with the numbers

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 127 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwtWfUC3qdjKZjsOV0D:-Nx7fQPtEdXcyNSKUwfL:b-vqdsxi) ([raw file](https://github.com/starkware-libs/blockifier/blob/5e51715107f572237898087681af07a621f4fc13/crates/blockifier/src/concurrency/scheduler.rs#L127)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I think it is:
```
enum TransactionStatus {
    ReadyToExecute = 0,
    Executing = 1,
    Executed = 2,
    Aborting = 3,
}
```
instead of:
```
enum TransactionStatus {
    ReadyToExecute,
    Executing,
    Executed,
    Aborting,
}
```
There is a natural order between the statuses and it's even easier for the reader to understand it with the numbers
</blockquote></details>

sorry, `Aborting = 0`, which is not so natural, but still readable IMO

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 127 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwtWfUC3qdjKZjsOV0D:-Nx7fWRX8vXyGCp8ODzF:b-giqjdt) ([raw file](https://github.com/starkware-libs/blockifier/blob/5e51715107f572237898087681af07a621f4fc13/crates/blockifier/src/concurrency/scheduler.rs#L127)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

sorry, `Aborting = 0`, which is not so natural, but still readable IMO
</blockquote></details>

I think it is over abstraction.
Also, if we add a status `Committed`, then `Executed` can be changed to both `Committed` and `Aborting`; if we add `incarnation`, this complicates things further.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 129 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwtY_Kx-euyBcnaU78O:-Nx7hUHdDy-ZBMRG4L1y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5e51715107f572237898087681af07a621f4fc13/crates/blockifier/src/concurrency/scheduler.rs#L129)):*
> ```XML
>     }
> 
>     // TODO(barak, 01/04/2024): Ensure documentation matches logic.
> ```

Done.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 150 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NwtYbrM5uYLUE1inqjn:-Nx7hV7TAKI2Myno7iDX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5e51715107f572237898087681af07a621f4fc13/crates/blockifier/src/concurrency/scheduler.rs#L150)):*
> ```XML
>     }
> 
>     // TODO(barak, 01/04/2024): Ensure documentation matches logic.
> ```

Done.

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 152 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NxBnwJI4IqgTcSA0P66:-NxBnwJI4IqgTcSA0P67:bhre6r8) ([raw file](https://github.com/starkware-libs/blockifier/blob/3a6b0e689f0f9bbe67c285cb4b2da109c6e62e57/crates/blockifier/src/concurrency/scheduler.rs#L152)):*
> ```XML
>     /// new tasks in case of failure: schedules validation for higher transactions + re-executes the
>     /// current transaction (if ready).
>     pub fn finish_validation(&self, tx_index: TxIndex, aborted: bool) -> Option<Task> {
> ```

Move all `pub` methods to the top of the `impl` block.



_Code quote:_
```XML
    pub fn finish_execution(&self, tx_index: TxIndex) {
        self.set_executed_status(tx_index);
        if self.validation_index.load(Ordering::Acquire) > tx_index {
            self.decrease_validation_index(tx_index);
        }
        self.safe_decrement_n_active_tasks();
    }

    pub fn try_validation_abort(&self, tx_index: TxIndex) -> bool {
        let mut status = self.lock_tx_status(tx_index);
        if *status == TransactionStatus::Executed {
            *status = TransactionStatus::Aborting;
            return true;
        }
        false
    }

    /// Updates the Scheduler that a validation task has been finished and triggers the creation of
    /// new tasks in case of failure: schedules validation for higher transactions + re-executes the
    /// current transaction (if ready).
    pub fn finish_validation(&self, tx_index: TxIndex, aborted: bool) -> Option<Task> {
```
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 156 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NxBnLhm22ABJQ3JrJM2:-NxBnLhnBlueiEgGSu-B:b-fpca6t) ([raw file](https://github.com/starkware-libs/blockifier/blob/3a6b0e689f0f9bbe67c285cb4b2da109c6e62e57/crates/blockifier/src/concurrency/scheduler.rs#L156)):*
> ```XML
>             self.set_ready_status(tx_index);
>             if self.execution_index.load(Ordering::Acquire) > tx_index
>                 && self.try_incarnate(tx_index).is_some()
> ```

Since we don't have an incarnation number for each tx we need to make `try_incarnate` return `bool`.



_Suggestion:_
```XML
self.try_incarnate(tx_index)
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 152 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NxBnwJI4IqgTcSA0P66:-NxC4_sP9CneHXu9MJKE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3a6b0e689f0f9bbe67c285cb4b2da109c6e62e57/crates/blockifier/src/concurrency/scheduler.rs#L152)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Move all `pub` methods to the top of the `impl` block.
</blockquote></details>

Done.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 156 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-NxBnLhm22ABJQ3JrJM2:-NxC4ngV9yCU4zr2rsYV:b-h6m5h) ([raw file](https://github.com/starkware-libs/blockifier/blob/3a6b0e689f0f9bbe67c285cb4b2da109c6e62e57/crates/blockifier/src/concurrency/scheduler.rs#L156)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Since we don't have an incarnation number for each tx we need to make `try_incarnate` return `bool`.
</blockquote></details>

We might want to add an incarnation number, so let's keep it this way for now.

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1800#-:-NxCv0G0BkF9Nu_-1dOP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
