### PR TITLE
Add post_validate method.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj1QdiV2EyDN2HkWA7P:-Nj1QdiV2EyDN2HkWA7Q:bq3on22) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af121ba866d37d45208b5e9d3e6c69188376f6f/crates/native_blockifier/src/py_validator.rs#L99)):*
> ```XML
>         else {
>             panic!("L1 handlers should not be validated separately, only as part of execution")
>         };
> ```

TAL at `py_account_tx` in [this PR](https://reviewable.io/reviews/starkware-libs/blockifier/1061) (pre-validation area) and do the same (for less conflicts, hopefully)



_Code quote:_
```XML
        let tx_type: String = py_enum_name(tx, "tx_type")?;
        let Transaction::AccountTransaction(account_tx) = py_tx(&tx_type, tx, raw_contract_class)?
        else {
            panic!("L1 handlers should not be validated separately, only as part of execution")
        };
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj1Rrtm4h_IntrHIjb3:-Nj1Rrtm4h_IntrHIjb4:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af121ba866d37d45208b5e9d3e6c69188376f6f/crates/native_blockifier/src/py_validator.rs#L122)):*
> ```XML
>         else {
>             panic!("L1 handlers should not be validated separately, only as part of execution")
>         };
> ```

ditto



_Code quote:_
```XML
        let tx_type: String = py_enum_name(tx, "tx_type")?;
        let Transaction::AccountTransaction(account_tx) = py_tx(&tx_type, tx, raw_contract_class)?
        else {
            panic!("L1 handlers should not be validated separately, only as part of execution")
        };
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj1RvZr7qJiRgdVtxDt:-Nj1RvZr7qJiRgdVtxDu:b-xbe40r) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af121ba866d37d45208b5e9d3e6c69188376f6f/crates/native_blockifier/src/py_validator.rs#L132)):*
> ```XML
> 
>         // Post validations.
>         // TODO(Noa, 09/11/2023): Add post-validation checks.
> ```

still relevant?



_Code quote:_
```XML
// TODO(Noa, 09/11/2023): Add post-validation checks.
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj1ThFN7VzsKQVMfuyN:-Nj1ThFN7VzsKQVMfuyO:br7xglp) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af121ba866d37d45208b5e9d3e6c69188376f6f/crates/native_blockifier/src/py_validator.rs#L171)):*
> ```XML
>         // Note- The balance cannot be changed in `__validate__`, so there is no need to recheck
>         // that balance >= actual_cost.
>         auditor.verify_valid_actual_cost()
> ```

why not (rename and) use `verify_can_pay_max_fee` directly?



_Code quote:_
```XML
        let charge_fee = true;
        let auditor = PostExecutionAuditor::new(
            &self.tx_executor().block_context,
            account_tx_context,
            actual_cost,
            charge_fee,
        )?;

        // Note- The balance cannot be changed in `__validate__`, so there is no need to recheck
        // that balance >= actual_cost.
        auditor.verify_valid_actual_cost()
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_validator.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj1QdiV2EyDN2HkWA7P:-Nj1tKot0t_r9_8Achj7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af121ba866d37d45208b5e9d3e6c69188376f6f/crates/native_blockifier/src/py_validator.rs#L99)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

TAL at `py_account_tx` in [this PR](https://reviewable.io/reviews/starkware-libs/blockifier/1061) (pre-validation area) and do the same (for less conflicts, hopefully)
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj1Rrtm4h_IntrHIjb3:-Nj1tOa08TorW3ACYhzk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af121ba866d37d45208b5e9d3e6c69188376f6f/crates/native_blockifier/src/py_validator.rs#L122)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj1RvZr7qJiRgdVtxDt:-Nj1tPcI8Ybygzd8Q6rB:bf7zv3s) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af121ba866d37d45208b5e9d3e6c69188376f6f/crates/native_blockifier/src/py_validator.rs#L132)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

still relevant?
</blockquote></details>

Removed. Thanks.
___
*[`crates/native_blockifier/src/py_validator.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj1ThFN7VzsKQVMfuyN:-Nj1tTAo4t8EQbd-cI38:b912hh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af121ba866d37d45208b5e9d3e6c69188376f6f/crates/native_blockifier/src/py_validator.rs#L171)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not (rename and) use `verify_can_pay_max_fee` directly?
</blockquote></details>

I need the first part (`actual_cost <= sender's bound(s)`).

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj5yNp532dMNXxkD7Fd:-Nj5yNp532dMNXxkD7Fe:b-3of3ay) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1f651fbe0f0f8481ab30cca27f2a76306b5d60e/crates/native_blockifier/src/py_validator.rs#L91)):*
> ```XML
>     pub fn validate(
>         &mut self,
>         tx: &PyAny,
> ```

Let's pass here the account transaction, to need to create it twice.



_Code quote:_
```XML
tx: &PyAny,
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj5yTqM4Az-s18HeCfk:-Nj5yTqM4Az-s18HeCfl:bxybgr6) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1f651fbe0f0f8481ab30cca27f2a76306b5d60e/crates/native_blockifier/src/py_validator.rs#L148)):*
> ```XML
>     }
> 
>     fn post_validate(
> ```

Let's have a consistent naming for those methods, so far they all start with a present simple verb (validate, perform, etc.).



_Code quote:_
```XML
post_validate
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj5ycIY0ORo5lcEMZuI:-Nj5ycIY0ORo5lcEMZuJ:b-cbuoar) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1f651fbe0f0f8481ab30cca27f2a76306b5d60e/crates/native_blockifier/src/py_validator.rs#L154)):*
> ```XML
>     ) -> TransactionExecutionResult<()> {
>         // Post validations.
>         let charge_fee = true;
> ```

Please add a short (inline?) comment on the values of these flags (also in pre-validation of Amos; can you help him write such a comment?).



_Code quote:_
```XML
let charge_fee = true;
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj5ymqU5HwIdB9Mg7MY:-Nj5ymqVDyxqn8F2aYsB:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1f651fbe0f0f8481ab30cca27f2a76306b5d60e/crates/native_blockifier/src/py_validator.rs#L163)):*
> ```XML
> 
>         // Note- The balance cannot be changed in `__validate__`, so there is no need to recheck
>         // that balance >= actual_cost.
> ```





_Suggestion:_
```XML
        // Note: the balance cannot be changed in `__validate__` (which cannot call other
        // contracts), so there is no need to recheck that balance >= actual_cost.
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_validator.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj5yNp532dMNXxkD7Fd:-Nj6XgcX3mCiKVk_lpkI:b-o0qmes) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1f651fbe0f0f8481ab30cca27f2a76306b5d60e/crates/native_blockifier/src/py_validator.rs#L91)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's pass here the account transaction, to need to create it twice.
</blockquote></details>

I can't since it is called from python. Will do it once it's not.
___
*[`crates/native_blockifier/src/py_validator.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj5ycIY0ORo5lcEMZuI:-NjDDUIx1NznWwZuxc1b:bdtq0pc) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1f651fbe0f0f8481ab30cca27f2a76306b5d60e/crates/native_blockifier/src/py_validator.rs#L154)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please add a short (inline?) comment on the values of these flags (also in pre-validation of Amos; can you help him write such a comment?).
</blockquote></details>

Avoided :) I'll write to Amos in the PR.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 157 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-NjDESkV7Uqs-t-NNrnv:-NjDESkV7Uqs-t-NNrnw:bofppf8) ([raw file](https://github.com/starkware-libs/blockifier/blob/d75e81c7e2809207c12c05c3466e7359bbd513c1/crates/native_blockifier/src/py_validator.rs#L157)):*
> ```XML
>         if !account_tx_context.enforce_fee()? {
>             return Ok(());
>         }
> ```

I don't really like that this is kinda duplicated (`PostExecutionReport::new` checks this) but ok for now; maybe add a TODO to push this logic into the fee checker logic later?



_Code quote:_
```XML
        if !account_tx_context.enforce_fee()? {
            return Ok(());
        }
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 170 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-NjDEcYp03zTgeE-IBNv:-NjDEcYp03zTgeE-IBNw:b6n0byd) ([raw file](https://github.com/starkware-libs/blockifier/blob/d75e81c7e2809207c12c05c3466e7359bbd513c1/crates/native_blockifier/src/py_validator.rs#L170)):*
> ```XML
>         // contracts), so there is no need to recheck that balance >= actual_cost.
> 
>         Ok(())
> ```

I prefer this, your call



_Suggestion:_
```XML
        match resource_bounds_report.error() {
            Some(error) => return Err(error)?,
            // Note: the balance cannot be changed in `__validate__` (which cannot call other
            // contracts), so there is no need to recheck that balance >= actual_cost.
            None => Ok(()),
        }
```

**Review by noaov1 — COMMENTED** [review]
[Python PR](https://reviewable.io/reviews/starkware-industries/starkware/32597).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-:-NjDQGKQ2qMwywutPfgR:b-ahg68h)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-Nj5yNp532dMNXxkD7Fd:-NjECrKQ3h7LyrSb1xrV:bdgku2n) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1f651fbe0f0f8481ab30cca27f2a76306b5d60e/crates/native_blockifier/src/py_validator.rs#L91)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I can't since it is called from python. Will do it once it's not.
</blockquote></details>

NP, add to the TODO?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111#-:-NjHtijJ3pDeCUWD79Ia:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1111)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
