### PR TITLE
Add invoke v0 to invoke_tx, add test case

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/938)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/938)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/938#-NfGt7UH-Ge1BkvbHpyX:-NfGt7UH-Ge1BkvbHpyY:b50b6xt) ([raw file](https://github.com/starkware-libs/blockifier/blob/22873a5eea00180ce86469be498365265d8d3a40/crates/blockifier/src/transaction/test_utils.rs#L206)):*
> ```XML
>     nonce_manager: &mut NonceManager,
>     max_fee: Fee,
>     entry_point_selector: Option<EntryPointSelector>,
> ```

I think v3 has a bunch of new fields and missing some of the previous ones, does that mean we'll end up with a function with a lot of optional args?



_Code quote:_
```XML
    entry_point_selector: Option<EntryPointSelector>,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/938)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/938#-NfGt7UH-Ge1BkvbHpyX:-NfGu9NJ29JhsH5ZToYg:bjqv2bm) ([raw file](https://github.com/starkware-libs/blockifier/blob/22873a5eea00180ce86469be498365265d8d3a40/crates/blockifier/src/transaction/test_utils.rs#L206)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think v3 has a bunch of new fields and missing some of the previous ones, does that mean we'll end up with a function with a lot of optional args?
</blockquote></details>

Yes, hence... [this next PR](https://reviewable.io/reviews/starkware-libs/blockifier/939) in prep for the v3 situation

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/938)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/938#-NfGt7UH-Ge1BkvbHpyX:-NfGuQM6AWQhQYu4ssbW:b-qu16g) ([raw file](https://github.com/starkware-libs/blockifier/blob/22873a5eea00180ce86469be498365265d8d3a40/crates/blockifier/src/transaction/test_utils.rs#L206)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Yes, hence... [this next PR](https://reviewable.io/reviews/starkware-libs/blockifier/939) in prep for the v3 situation
</blockquote></details>

Better!
However, we still get a struct with a bunch of `Option` fields?
Can this be a versioned enum? or will that break the whole design?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/938)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/938#-NfGt7UH-Ge1BkvbHpyX:-NfGwLLR-Oz1cVkGak_2:b-ej3zcf) ([raw file](https://github.com/starkware-libs/blockifier/blob/22873a5eea00180ce86469be498365265d8d3a40/crates/blockifier/src/transaction/test_utils.rs#L206)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Better!
However, we still get a struct with a bunch of `Option` fields?
Can this be a versioned enum? or will that break the whole design?
</blockquote></details>

that will break the design.
you will want to write tests like this:
```
fn test_varying_versions(tx_version: TransactionVersion, ...) {
   ...
   let tx = invoke_tx(tx_version, ???);
```
you will need to pass something to `invoke_tx` that will capture all cases.
The point of the `InvokeTxArgs` is that (a) it implements `Default`, so you can generate with the specifics you need, and (b) you could implement `new()` or `create()` functions with partial arguments and intelligently construct an args struct that will work for all invoke versions.
WDYT?

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/938#-:-Nfe553d4Gt0QFrqv1qo:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/938#-NfR5NKo3170sIeTGpMe:-NfR5NKo3170sIeTGpMf:bjme58q) ([raw file](https://github.com/starkware-libs/blockifier/blob/22873a5eea00180ce86469be498365265d8d3a40/crates/blockifier/src/transaction/account_transactions_test.rs#L216)):*
> ```XML
>         &mut nonce_manager,
>         max_fee,
>         Some(selector_from_name(EXECUTE_ENTRY_POINT_NAME)),
> ```

WDYT about defining a variable:
`let entry_pont_selector = if  tx_version == TransactionVersion::ZERO {Some(selector_from_name(EXECUTE_ENTRY_POINT_NAME))} else {None};`
To avoid confusion. 



_Code quote:_
```XML
Some(selector_from_name(EXECUTE_ENTRY_POINT_NAME)),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/938)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/938#-NfR5NKo3170sIeTGpMe:-Nfe8vWh7PmLatfoDZ87:b876jfm) ([raw file](https://github.com/starkware-libs/blockifier/blob/22873a5eea00180ce86469be498365265d8d3a40/crates/blockifier/src/transaction/account_transactions_test.rs#L216)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYT about defining a variable:
`let entry_pont_selector = if  tx_version == TransactionVersion::ZERO {Some(selector_from_name(EXECUTE_ENTRY_POINT_NAME))} else {None};`
To avoid confusion.
</blockquote></details>

I'll add a comment [here](https://reviewable.io/reviews/starkware-libs/blockifier/946) (I think it's a better place to set this behavior, right?)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/938)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/938#-NfR5NKo3170sIeTGpMe:-Nfe97MZ4jMMTrNV_Idn:bib8qfs) ([raw file](https://github.com/starkware-libs/blockifier/blob/22873a5eea00180ce86469be498365265d8d3a40/crates/blockifier/src/transaction/account_transactions_test.rs#L216)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I'll add a comment [here](https://reviewable.io/reviews/starkware-libs/blockifier/946) (I think it's a better place to set this behavior, right?)
</blockquote></details>

ah no... maybe [here](https://reviewable.io/reviews/starkware-libs/blockifier/953) is better

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/938)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/938#-NfGt7UH-Ge1BkvbHpyX:-NfeCgeq2WhMWE0rED-x:b-vrbzv5) ([raw file](https://github.com/starkware-libs/blockifier/blob/22873a5eea00180ce86469be498365265d8d3a40/crates/blockifier/src/transaction/test_utils.rs#L206)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

that will break the design.
you will want to write tests like this:
```
fn test_varying_versions(tx_version: TransactionVersion, ...) {
   ...
   let tx = invoke_tx(tx_version, ???);
```
you will need to pass something to `invoke_tx` that will capture all cases.
The point of the `InvokeTxArgs` is that (a) it implements `Default`, so you can generate with the specifics you need, and (b) you could implement `new()` or `create()` functions with partial arguments and intelligently construct an args struct that will work for all invoke versions.
WDYT?
</blockquote></details>

Will be implemented [here](https://reviewable.io/reviews/starkware-libs/blockifier/953).

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/938)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Pull request merged**
