### PR TITLE
Elin/merge main v0.13.0 into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1327)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1327)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1327)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1327)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1327#-NnsnZve9uv3VbPs5eSI:-NnsnZve9uv3VbPs5eSJ:b-394zj8) (no related file):*
[Python side](https://reviewable.io/reviews/starkware-industries/starkware/33370).

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1327#-:-NnspPSuElukNuwtrwWP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1327#-NnspZm0DZ_I2wmA24Xb:-NnspZm0DZ_I2wmA24Xc:bawus02) (no related file):*
waiting for python side to pass

___

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1327)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1327#-NnspZm0DZ_I2wmA24Xb:-NnsttIm8qAGV_eChDDm:bpz5va7) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

waiting for python side to pass
</blockquote></details>

It did.

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1327#-:-NnsvQr_3yHk05g9AQze:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Pull request merged**
