### PR TITLE
Get paid_fee_on_l1 from tx.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/503)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/503)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/503#-NVyHBwd8HiyV02Evn5d:-NVyHBwe7H8nuSeKlVvP:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed78178d0617b5c6d3462a5454bc59df4ea65d3/crates/native_blockifier/src/py_transaction.rs#L253)):*
> ```XML
>         }
>         "L1_HANDLER" => {
>             let paid_fee_on_l1 = Fee(py_attr(tx, "paid_fee_on_l1")?);
> ```





_Suggestion:_
```XML
py_attr(tx, "paid_fee_on_l1").unwrap_or_default()
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/503)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/503)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/503#-NVyHBwd8HiyV02Evn5d:-NVyJSR7EABAnri-O5me:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed78178d0617b5c6d3462a5454bc59df4ea65d3/crates/native_blockifier/src/py_transaction.rs#L253)):*
> ```XML
>         }
>         "L1_HANDLER" => {
>             let paid_fee_on_l1 = Fee(py_attr(tx, "paid_fee_on_l1")?);
> ```

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/503)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/503#-NVyHBwd8HiyV02Evn5d:-NVyUiHq9NKT9bBNGDjA:bqznkwd) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed78178d0617b5c6d3462a5454bc59df4ea65d3/crates/native_blockifier/src/py_transaction.rs#L253)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can this be done in the same line?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/503)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/503#-NVyHBwd8HiyV02Evn5d:-NVy_40ACcqhLvP036TF:b-w7jju8) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed78178d0617b5c6d3462a5454bc59df4ea65d3/crates/native_blockifier/src/py_transaction.rs#L253)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can this be done in the same line?
</blockquote></details>

Yeah, a bit hard to read:
```
let paid_fee_on_l1 = Fee(py_attr::<Option<u128>>(tx, "paid_fee_on_l1")?.unwrap_or_default());
```

Do you prefer that?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/503#-:-NVyo2LJ4ExNcuH0hVgF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/503#-NVyHBwd8HiyV02Evn5d:-NVyny_89s_sJb59zyrZ:b-yuynh8) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed78178d0617b5c6d3462a5454bc59df4ea65d3/crates/native_blockifier/src/py_transaction.rs#L253)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yeah, a bit hard to read:
```
let paid_fee_on_l1 = Fee(py_attr::<Option<u128>>(tx, "paid_fee_on_l1")?.unwrap_or_default());
```

Do you prefer that?
</blockquote></details>

Oh, the type specification. NO :smiling_face_with_tear:

**Pull request merged**
