### PR TITLE
test(concurrency): add cairo0 contracts to deploy then declaer

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2052)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2052)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 569 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2052#-O1Hm2D7AjP1e5kOiX8K:-O1Hm2D7AjP1e5kOiX8L:b-v3ah4) ([raw file](https://github.com/starkware-libs/blockifier/blob/d49a6c29452ff5b2aa85eecf93d3d3a994b7155a/crates/blockifier/src/concurrency/worker_logic_test.rs#L569)):*
> ```XML
>     let invoke_tx = account_invoke_tx(invoke_tx_args! {
>         sender_address: account_address_1,
>         calldata: create_calldata(
> ```

Is there a reason it was zero here? It failed the test when the cario contract was cairo0. @OriStarkware

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2052)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 569 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2052#-O1Hm2D7AjP1e5kOiX8K:-O1QVWeF0HJ4yUHSpbTY:b-x6wzhb) ([raw file](https://github.com/starkware-libs/blockifier/blob/d49a6c29452ff5b2aa85eecf93d3d3a994b7155a/crates/blockifier/src/concurrency/worker_logic_test.rs#L569)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Is there a reason it was zero here? It failed the test when the cario contract was cairo0. @OriStarkware
</blockquote></details>

I talked with Noa and Ori offline. It was supposed to be account_address_0, but the cairo0 contract has an assert_only_self
check, so I changed it to account_address_1.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2052)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 532 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2052#-O1k0mIL4ZRYVY0GdZgz:-O1k0mIL4ZRYVY0GdZh-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff5915c74a3f8dd4b8753ce35a99851fcb7dbd0d/crates/blockifier/src/concurrency/worker_logic_test.rs#L532)):*
> ```XML
> #[rstest]
> #[case::transaction_version_one(CairoVersion::Cairo0, TransactionVersion::ONE)]
> #[case::transaction_version_three(CairoVersion::Cairo1, TransactionVersion::THREE)]
> ```





_Suggestion:_
```XML
#[case::declare_cairo0(CairoVersion::Cairo0, TransactionVersion::ONE)]
#[case::declare_cairo1(CairoVersion::Cairo1, TransactionVersion::THREE)]
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 542 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2052#-O1k1JmS8jd0b89MCYwK:-O1k1JmS8jd0b89MCYwL:b572pdt) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff5915c74a3f8dd4b8753ce35a99851fcb7dbd0d/crates/blockifier/src/concurrency/worker_logic_test.rs#L542)):*
> ```XML
>     let block_context = BlockContext::create_for_account_testing();
>     let chain_info = &block_context.chain_info;
>     let account_contract = FeatureContract::AccountWithoutValidations(cairo_version);
> ```

You can leave it as cairo1



_Code quote:_
```XML
    let account_contract = FeatureContract::AccountWithoutValidations(cairo_version);
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 582 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2052#-O1k29jEB4pX15tfJX8_:-O1k29jF5baJWpaib4db:b4h3jba) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff5915c74a3f8dd4b8753ce35a99851fcb7dbd0d/crates/blockifier/src/concurrency/worker_logic_test.rs#L582)):*
> ```XML
>         resource_bounds: max_resource_bounds,
>         max_fee,
>         version,
> ```

This can be removed if you leave the account contract as cairo1.



_Code quote:_
```XML
        max_fee,
        version,
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2052)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 582 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2052#-O1k29jEB4pX15tfJX8_:-O1l2XZt5tlF2Ryo2KPL:b-wjvhuq) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff5915c74a3f8dd4b8753ce35a99851fcb7dbd0d/crates/blockifier/src/concurrency/worker_logic_test.rs#L582)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

This can be removed if you leave the account contract as cairo1.
</blockquote></details>

But we want to test both V1 and V3 transactions, no?

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2052)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 582 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2052#-O1k29jEB4pX15tfJX8_:-O1l2sv10DcOSg1N1cWl:bhyn62b) ([raw file](https://github.com/starkware-libs/blockifier/blob/ff5915c74a3f8dd4b8753ce35a99851fcb7dbd0d/crates/blockifier/src/concurrency/worker_logic_test.rs#L582)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

But we want to test both V1 and V3 transactions, no?
</blockquote></details>

Not needed in this test. We only care about declaring cairo 0 and cairo 1

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2052#-:-O1l451m8WfEE57ZH67h:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
