### PR TITLE
chore: upgrade sn_api

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2020)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2020)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/2020#-O0nA5AmC5kIYYNUvkJm:-O0nA5AmC5kIYYNUvkJn:btbz62c) (no related file):*
sn_api feature branch was update.
In this PR, I run `cargo update starknet_api`.

___

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2020)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/2020#-O0nA5AmC5kIYYNUvkJm:-O0nDnX54uopZ4hPmPEk:bppa68q) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

sn_api feature branch was update.
In this PR, I run `cargo update starknet_api`.
</blockquote></details>

Why not in `Cargo.toml`?

___

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2020)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2020)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/2020#-O0nA5AmC5kIYYNUvkJm:-O0nFv4Q3B6tPUacYoe8:b-vxnj5x) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not in `Cargo.toml`?
</blockquote></details>

In `Cargo.toml`, we already have pointed to the feature branch:
`starknet_api = { git = "https://github.com/starkware-libs/starknet-api.git", branch = "main-mempool" }`

___

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2020#-:-O0x2hF16K7mWC10MEkD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
FYI Still relevant?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2020#-:-O1NxvFo6U115prjMts-:b-zgtqdh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2020)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
Not relevant. closing...

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2020#-:-O1RZukj5Ig_JjCxNHG4:b-gw958m)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request closed without merging**
