### PR TITLE
Make pyo3 testable, add tests and Defaults to `native_blockifier`

### PR DESCRIPTION
**Pull request by giladchase**
- Make pyo3's' `extension-module` feature optional. This is recommended in the PYO3 docs (added a reference to it in `native_blockifier`'s Cargo.toml)
- Add `py_block_executor_test.rs`, and add some `Default` to help testing.

Python: https://reviewable.io/reviews/starkware-industries/starkware/31115

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/807)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/807)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/Cargo.toml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/807#-NabYORz7HhLw8Eu2M_G:-NabYORz7HhLw8Eu2M_H:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d47e7a0a056c48be9fa8297db0f4e5c3731045fe/crates/native_blockifier/Cargo.toml#L11)):*
> ```TOML
> # Required for `cargo test` to work with pyo3.
> # On python, make sure to compile this with the extension-module feature enabled.
> # https://pyo3.rs/v0.19.1/faq#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror
> ```





_Suggestion:_
```TOML
# Required for `cargo test` to work with Pyo3.
# On Python, make sure to compile this with the extension-module feature enabled.
# https://pyo3.rs/v0.19.1/faq#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/807#-NabYrEE-_9sN0mOQNN2:-NabYrEE-_9sN0mOQNN3:b1ez3w2) ([raw file](https://github.com/starkware-libs/blockifier/blob/d47e7a0a056c48be9fa8297db0f4e5c3731045fe/crates/native_blockifier/src/py_block_executor.rs#L233)):*
> ```XML
> impl Default for PyOsConfig {
>     fn default() -> Self {
>         Self { chain_id: ChainId("".to_string()), fee_token_address: Default::default() }
> ```

Perhaps "TESTNET"?



_Code quote:_
```XML
ChainId("".to_string())
```
___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/807#-NabZ8bi5p40N4JrjoEh:-NabZ8bjCXh7vTvSEKDd:b-kq1cq) ([raw file](https://github.com/starkware-libs/blockifier/blob/d47e7a0a056c48be9fa8297db0f4e5c3731045fe/crates/native_blockifier/src/py_block_executor_test.rs#L14)):*
> ```XML
>     // Initialize executor and set a contract class on the state.
>     let mut block_executor =
>         PyBlockExecutor::create_for_testing(PyGeneralConfig::default(), "/tmp/foo".into());
> ```

Give this a name please.



_Code quote:_
```XML
"/tmp/foo".into()
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/807#-NabYxR1AeHNHwngKr8W:-NabYxR1AeHNHwngKr8X:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d47e7a0a056c48be9fa8297db0f4e5c3731045fe/crates/native_blockifier/src/py_state_diff.rs#L117)):*
> ```XML
> }
> 
> #[derive(FromPyObject, Default)]
> ```





_Suggestion:_
```XML
Default, FromPyObject
```
___
*[`crates/native_blockifier/src/py_utils.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/807#-NabZ09z7z488jVMK1UT:-NabZ09z7z488jVMK1UU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d47e7a0a056c48be9fa8297db0f4e5c3731045fe/crates/native_blockifier/src/py_utils.rs#L13)):*
> ```XML
> use crate::errors::NativeBlockifierResult;
> 
> #[derive(Eq, FromPyObject, Hash, PartialEq, Clone, Copy, Default)]
> ```





_Suggestion:_
```XML
Clone, Copy, Default, Eq, FromPyObject, Hash, PartialEq
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/807)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/807#-NabYrEE-_9sN0mOQNN2:-NabZjNkEvKnQNO90cIw:b-36ksjp) ([raw file](https://github.com/starkware-libs/blockifier/blob/d47e7a0a056c48be9fa8297db0f4e5c3731045fe/crates/native_blockifier/src/py_block_executor.rs#L233)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps "TESTNET"?
</blockquote></details>

Hmmm are we sure we want to involve it there? Couldn't that have some unforeseen consequences? 
___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/807#-NabZ8bi5p40N4JrjoEh:-Nab_Opp97ioY1-gyGHY:bv6dqng) ([raw file](https://github.com/starkware-libs/blockifier/blob/d47e7a0a056c48be9fa8297db0f4e5c3731045fe/crates/native_blockifier/src/py_block_executor_test.rs#L14)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give this a name please.
</blockquote></details>

Whoops missed that, thanks.

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/807)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/807#-NabYrEE-_9sN0mOQNN2:-Naba-0m8X4d7QhoxxIv:b3cz0rw) ([raw file](https://github.com/starkware-libs/blockifier/blob/d47e7a0a056c48be9fa8297db0f4e5c3731045fe/crates/native_blockifier/src/py_block_executor.rs#L233)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Hmmm are we sure we want to involve it there? Couldn't that have some unforeseen consequences? 
</blockquote></details>

Okay, leave it. If someone needs a specific value, they'll add it.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/807#-:-Naba53N7YTTjrfO4Ewi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
