### PR TITLE
chore: align creation of calldata from vec

### PR DESCRIPTION
**Pull request by ArniStarkware**
Aligned with this example: https://github.com/starkware-libs/blockifier/blob/20a895343ec21b6b2eebee41f4087159df126096/crates/blockifier/src/transaction/transactions_test.rs#L1687-L1696

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1647)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-NsO_uxr3vzvtDl_BZJT:-NsO_uxr3vzvtDl_BZJU:bsv2pu3) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e88fc0ea2ec9eccd7e6396bb26563d4b3004b25/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L353)):*
> ```XML
> 
>     let calldata =
>         calldata_for_deploy_test(class_hash, constructor_calldata.clone(), valid_deploy_from_zero);
> ```

There is a need to clone now :(
Let us revert this one.



_Code quote:_
```XML
calldata_for_deploy_test(class_hash, constructor_calldata.clone(), valid_deploy_from_zero);
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-NsO_uxr3vzvtDl_BZJT:-NsOaDhKAgM90jSEJGGM:b-mn6kpr) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e88fc0ea2ec9eccd7e6396bb26563d4b3004b25/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L353)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

There is a need to clone now :(
Let us revert this one.
</blockquote></details>

funny - this is the instance that made me want to do this refactor in the first place.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils.rs` line 341 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-Nsakx-f6MdC8s3hTXJB:-Nsakx-f6MdC8s3hTXJC:b-nlourz) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e88fc0ea2ec9eccd7e6396bb26563d4b3004b25/crates/blockifier/src/test_utils.rs#L341)):*
> ```XML
> ) -> Calldata {
>     let n_args = u128::try_from(entry_point_args.len()).expect("Calldata too big");
>     let n_args = StarkFelt::from(n_args);
> ```

Why two lines?



_Suggestion:_
```XML
    let n_args = StarkFelt::from(u128::try_from(entry_point_args.len()).expect("Calldata too big"));
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils.rs` line 350 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-NsalDaTDxHDS_rclpiS:-NsalDaU0tR1opBAqndt:b24z9vy) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e88fc0ea2ec9eccd7e6396bb26563d4b3004b25/crates/blockifier/src/test_utils.rs#L350)):*
> ```XML
>                 n_args,
>             ],
>             entry_point_args.into(),
> ```

Is into is as bad as clone?



_Code quote:_
```XML
entry_point_args.into()
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1647)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-NsOcOW39GmC4sZgiTmx:-NsbDzkS0oXbcrgJdo7N:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e88fc0ea2ec9eccd7e6396bb26563d4b3004b25/crates/blockifier/src/test_utils.rs#L335)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Document.

This returns the calldata formatted for the `__execute__` entrypoint of the accounts:
`FeatureContract::AccountWithoutValidations` and `FeatureContract::AccountWithLongValidations`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 341 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-Nsakx-f6MdC8s3hTXJB:-NsbEs0xC3Lyy8WdKowJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e88fc0ea2ec9eccd7e6396bb26563d4b3004b25/crates/blockifier/src/test_utils.rs#L341)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why two lines?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1647)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 350 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-NsalDaTDxHDS_rclpiS:-Nsczlsc2aJ3pH8Xi9HO:bgtzgwc) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e88fc0ea2ec9eccd7e6396bb26563d4b3004b25/crates/blockifier/src/test_utils.rs#L350)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is into is as bad as clone?
</blockquote></details>

IDK, but this is a test module, I wouldn't be super concerned about it... readability > efficiency here
___
*[`crates/blockifier/src/test_utils.rs` line 323 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-NsczX7a1bXNwIpqy_AG:-NsczX7a1bXNwIpqy_AH:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fb1eb20697e0afe824edf6f213d3aa704d63969/crates/blockifier/src/test_utils.rs#L323)):*
> ```XML
>                 class_hash.0,
>                 ContractAddressSalt::default().0,
>                 stark_felt!(u128::try_from(constructor_calldata.len()).expect("Calldata too big")),
> ```





_Suggestion:_
```XML
u128_from_usize(constructor_calldata.len())
```
___
*[`crates/blockifier/src/test_utils.rs` line 354 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-NsczboGBczoBW_SXGjZ:-NsczboGBczoBW_SXGj_:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fb1eb20697e0afe824edf6f213d3aa704d63969/crates/blockifier/src/test_utils.rs#L354)):*
> ```XML
>                 *contract_address.0.key(),              // Contract address.
>                 selector_from_name(entry_point_name).0, // EP selector name.
>                 stark_felt!(u128::try_from(entry_point_args.len()).expect("Calldata too big")),
> ```





_Suggestion:_
```XML
u128_from_usize(entry_point_args.len())
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-:-Nsd3Eij1AtcBzxcI2Lk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1647)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 323 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-NsczX7a1bXNwIpqy_AG:-Nsd1pRdDy-1BklXVSHj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fb1eb20697e0afe824edf6f213d3aa704d63969/crates/blockifier/src/test_utils.rs#L323)):*
> ```XML
>                 class_hash.0,
>                 ContractAddressSalt::default().0,
>                 stark_felt!(u128::try_from(constructor_calldata.len()).expect("Calldata too big")),
> ```

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 354 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1647#-NsczboGBczoBW_SXGjZ:-Nsd1q656FprmV7C_CXM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fb1eb20697e0afe824edf6f213d3aa704d63969/crates/blockifier/src/test_utils.rs#L354)):*
> ```XML
>                 *contract_address.0.key(),              // Contract address.
>                 selector_from_name(entry_point_name).0, // EP selector name.
>                 stark_felt!(u128::try_from(entry_point_args.len()).expect("Calldata too big")),
> ```

Done.

**Pull request merged**
