### PR TITLE
chore(execution): saturate step bound on overflow

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1429)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1429)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1429#-Nps_rNJAndR5a8s1BMj:-Nps_rNK6R3iyWSLifgw:by7sfmb) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ab63900e45c060e8e2cbf853591cdc432203bba/crates/blockifier/src/execution/entry_point.rs#L261)):*
> ```XML
>         // Use saturating upper bound to avoid overflow. This is safe because the upper bound is
>         // bounded above by the block's limit, which is a usize.
>         let upper_bound_u128 = (tx_gas_upper_bound as f64 / gas_per_step).floor() as u128;
> ```

the `as` is due to the float?



_Code quote:_
```XML
        let upper_bound_u128 = (tx_gas_upper_bound as f64 / gas_per_step).floor() as u128;
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1429#-Nps_w03-SD8MKhQt9Mb:-Nps_w03-SD8MKhQt9Mc:b-962yi9) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ab63900e45c060e8e2cbf853591cdc432203bba/crates/blockifier/src/execution/entry_point.rs#L262)):*
> ```XML
>         // bounded above by the block's limit, which is a usize.
>         let upper_bound_u128 = (tx_gas_upper_bound as f64 / gas_per_step).floor() as u128;
>         let tx_upper_bound = match usize_from_u128(upper_bound_u128) {
> ```

If you want



_Suggestion:_
```XML
        let tx_upper_bound = usize_from_u128(upper_bound_u128).unwrap_or_else(|| {
```

**Review by giladchase — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1429)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1429#-Nps_rNJAndR5a8s1BMj:-Npsz8Rb9PchjGgCJ1PD:b2nign6) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ab63900e45c060e8e2cbf853591cdc432203bba/crates/blockifier/src/execution/entry_point.rs#L261)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

the `as` is due to the float?
</blockquote></details>

yes

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
