### PR TITLE
fix(fee): fixed previous PR, wrong parentheses

### PR DESCRIPTION
**Pull request by nimrod-starkware**
previous PR- https://github.com/starkware-libs/blockifier/pull/1654

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)

### CODE REVIEW

**Review by OriStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by OriStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtC29ts3Qhve03d6C4V:-NtC29tt0jmYyxhpXPhB:b-lx8y8n) (no related file):*
Wait for python PR

___

**Review by noaov1 — DISMISSED** [review]
Consider adding a test

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-:-NtCGm9050O5UZeDYhoJ:b-v3o8i)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Review by OriStarkware — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtFcokZB-owd0UikQ6B:-NtFcok_CNov3C3lN5gR:boh76h5) ([raw file](https://github.com/starkware-libs/blockifier/blob/7106106f4a84d5a1ed0df5e327cdad7d615af0a8/crates/blockifier/src/test_utils/struct_impls.rs#L129)):*
> ```XML
>     }
> 
>     pub fn create_simple_for_account_testing() -> Self {
> ```

There is no need for this change, IMO. WDYT?



_Code quote:_
```XML
simple_
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtFctnICW_SdmxGFdff:-NtFctnJ4QcGDE58FH6x:boh76h5) ([raw file](https://github.com/starkware-libs/blockifier/blob/7106106f4a84d5a1ed0df5e327cdad7d615af0a8/crates/blockifier/src/test_utils/struct_impls.rs#L137)):*
> ```XML
>     }
> 
>     pub fn create_simple_for_account_testing_with_kzg(use_kzg_da: bool) -> Self {
> ```

There is no need for this change, IMO. WDYT?



_Code quote:_
```XML
simple_
```

**Review by OriStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtGtp-ADstFKVuj3LQ4:-NtGtp-ADstFKVuj3LQ5:b7q6yxd) (no related file):*
Please Fixed Comments

___

**Review by noaov1 — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)* status: all files reviewed, 8 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtHd4yhAmPhqb9ina9S:-NtHd4yhAmPhqb9ina9T:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e673fb272b06f7ec097b31598b07f9ca88465100/crates/blockifier/src/versioned_constants.rs#L182)):*
> ```XML
>     /// A more complicated instance to increase test coverage.
>     #[cfg(any(feature = "testing", test))]
>     pub fn create_float_for_account_testing() -> Self {
> ```





_Suggestion:_
```XML
    // A more complicated instance to increase test coverage.
    #[cfg(any(feature = "testing", test))]
    pub fn create_float_for_testing() -> Self {
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtHc_BO0BbSROh7yHM-:-NtHc_BPCLA684nXWj9X:bve6ik3) ([raw file](https://github.com/starkware-libs/blockifier/blob/e673fb272b06f7ec097b31598b07f9ca88465100/crates/blockifier/src/fee/fee_test.rs#L12)):*
> ```XML
> use starknet_api::transaction::{Fee, TransactionVersion};
> 
> use crate::abi::constants::{self, N_STEPS_RESOURCE};
> ```

And use `constants::N_STEPS_RESOURCE`



_Suggestion:_
```XML
use crate::abi::constants;
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtHdjWr8L0Q7-98ODD_:-NtHdjWsAT5cozyhJrrQ:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/e673fb272b06f7ec097b31598b07f9ca88465100/crates/blockifier/src/fee/fee_test.rs#L48)):*
> ```XML
>     // Positive flow.
>     // Verify calculation - in our case, n_steps is the heaviest resource.
>     let l1_gas_by_vm_usage = vm_resource_usage.n_steps;
> ```





_Suggestion:_
```XML
let l1_gas_by_vm_usage = vm_resource_usage.n_steps *  (*versioned_constants.vm_resource_fee_cost().get(constants::N_STEPS_RESOURCE).unwrap());
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtHf0Jk3RdPpUU8fsE4:-NtHf0Jk3RdPpUU8fsE5:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e673fb272b06f7ec097b31598b07f9ca88465100/crates/blockifier/src/fee/fee_test.rs#L55)):*
> ```XML
> 
>     // Another positive flow, this time the heaviest resource is range_check_builtin.
>     vm_resource_usage.n_steps = 5;
> ```





_Suggestion:_
```XML
    vm_resource_usage.n_steps = vm_resource_usage.builtin_instance_counter.get(RANGE_CHECK_BUILTIN_NAME).unwrap() - 1;
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtFcokZB-owd0UikQ6B:-NtKiAaWEAza3aJuWYAz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7106106f4a84d5a1ed0df5e327cdad7d615af0a8/crates/blockifier/src/test_utils/struct_impls.rs#L129)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

There is no need for this change, IMO. WDYT?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtFctnICW_SdmxGFdff:-NtKiAvY79S5ia3oowbg:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7106106f4a84d5a1ed0df5e327cdad7d615af0a8/crates/blockifier/src/test_utils/struct_impls.rs#L137)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

There is no need for this change, IMO. WDYT?
</blockquote></details>

Done.

**Review by OriStarkware — COMMENTED** [review]
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 52 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtKq_ddATZXtNAV3khX:-NtKq_ddATZXtNAV3khY:b-okgdik) ([raw file](https://github.com/starkware-libs/blockifier/blob/10df3581796d0796ffba340fd0634ae3963f41c6/crates/blockifier/src/fee/fee_test.rs#L52)):*
> ```XML
>             * u128_from_usize(vm_resource_usage.n_steps))
>         .ceil()
>         .to_integer();
> ```

Is it necessary?



_Code quote:_
```XML
        .ceil()
        .to_integer();
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-:-NtLAx0zE1tlLg-qcITR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1676#-NtC29ts3Qhve03d6C4V:-NtLBjm2DKXHdpIcIhQA:b-896fix) (no related file):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Wait for python PR
</blockquote></details>

Done.

___

**Review by OriStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1676)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
