### PR TITLE
Fix Dependency in build_wheels.

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/254)

### CODE REVIEW

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/254)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/build_wheels.sh` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/254#-NN2uK4TAtIGEbhv3MRR:-NN2uK4U9uRx8ia63UPo:bl40fvw) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c5fc3150b736a9f9ff4723010d0a252dae16c48/crates/native_blockifier/build_wheels.sh#L6)):*
> ```Shell
> # The starknet-api dependency requires the dependency `rust-openssl`, which needs openssl-devel
> # to be installed locally.
> yum -y openssl-devel
> ```

yum -y install openssl-devel



_Code quote:_
```Shell
yum -y openssl-devel
```

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/254#-:-NN5jUixBN9o6jva4aCb:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by alon-dotan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/native_blockifier/build_wheels.sh` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/254#-NN2uK4TAtIGEbhv3MRR:-NN5a2g9-BKoCOl5NByE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c5fc3150b736a9f9ff4723010d0a252dae16c48/crates/native_blockifier/build_wheels.sh#L6)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

yum -y install openssl-devel
</blockquote></details>

Done.

**Pull request merged**
