### PR TITLE
Estimate Patricia update resources for Bouncer.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1303)

### CODE REVIEW

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1303#-:-Nn-CGz54si4rYtLwqZz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1303#-:-Nn-OutdElbMpscmf4pf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1303)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 182 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1303#-Nn-ra-M6Ds98UnUeIES:-Nn-ra-M6Ds98UnUeIET:b-yr295e) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e00aa427d182c0681d423fbc64ad85eb62eb63d/crates/native_blockifier/src/transaction_executor.rs#L182)):*
> ```XML
>     }
> 
>     pub fn commit(&mut self) {
> ```

Update

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1303)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 182 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1303#-Nn-ra-M6Ds98UnUeIES:-Nn0KKG03YeKqaH-QiB3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e00aa427d182c0681d423fbc64ad85eb62eb63d/crates/native_blockifier/src/transaction_executor.rs#L182)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Update
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1303#-:-Nn0QlHlD09suUd0FJgC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
