### PR TITLE
fix(state): ignore writes of the current transaction upon read

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1718)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1718)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1718#-NtuA4Bu9OKGGuIFb2HZ:-NtuA4Bu9OKGGuIFb2H_:b-yrvoer) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca55cb5c0552cfbe522e7256b5c84aa43a43b0da/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L56)):*
> ```XML
>         if version == 0 {
>             return true;
>         }
> ```

Still needed?



_Code quote:_
```XML
        if version == 0 {
            return true;
        }
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1718#-Ntu9rfR4LIXBY-a5yW2:-Ntu9rfS3GMaplF_nUy_:b-f43miu) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca55cb5c0552cfbe522e7256b5c84aa43a43b0da/crates/blockifier/src/concurrency/versioned_storage.rs#L44)):*
> ```XML
>         // Ignore the writes in the current transaction (may contain an `ESTIMATE` value). Reading
>         // the value written in this transaction should be handled by the state.
>         let value = self.writes.get(&key).and_then(|cell| cell.range(..version).next_back());
> ```

Does it work well when `version=0`?



_Code quote:_
```XML
let value = self.writes.get(&key).and_then(|cell| cell.range(..version).next_back());
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1718)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1718#-NtuA4Bu9OKGGuIFb2HZ:-NtuAFv2DZCE1eX59cz5:b-huhfof) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca55cb5c0552cfbe522e7256b5c84aa43a43b0da/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L56)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Still needed?
</blockquote></details>

It is an early return.  In practice, the method can handle `version = 0`.

**Review by MohammadNassar1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1718)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1718)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1718#-Ntu9rfR4LIXBY-a5yW2:-Ntum0-d-wb-l1tTRXyE:b-d5ntr4) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca55cb5c0552cfbe522e7256b5c84aa43a43b0da/crates/blockifier/src/concurrency/versioned_storage.rs#L44)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Does it work well when `version=0`?
</blockquote></details>

Yes. It simply returns `None`.  I changed the test to catch a potential problem with version 0.

**Pull request merged**
