### PR TITLE
Tidy-up test utils.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/486)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/486)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/486#-NViJ1bp9RVqB8tCFagc:-NViJ1bp9RVqB8tCFagd:bq2r6is) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0f766d5140aae5c0424045230fbf14b8af638a1/crates/blockifier/src/test_utils.rs#L159)):*
> ```XML
> }
> 
> pub fn get_contract_class(contract_path: &str, is_cairo1: bool) -> ContractClass {
> ```

I generally don't like function that get a flag that chagnes their behavior. This specific pattern:
```
fn foof(flag) {
  if flag {
    // bla
  } else {
    // bla
}
```
is not nice, unless you haev a lot of shared places that have only flag without knowing what is is.
https://martinfowler.com/bliki/FlagArgument.html

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/486)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/486#-NViK7BX-UOkjNk6oaOZ:-NViK7BX-UOkjNk6oaO_:beirs4h) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0f766d5140aae5c0424045230fbf14b8af638a1/crates/blockifier/src/test_utils.rs#L251)):*
> ```XML
> }
> 
> fn create_deploy_test_state_by_version(is_cairo1: bool) -> CachedState<DictStateReader> {
> ```

Another option is to define a struct of contract classes for the tests. something like:
```
struct TestClasses {
  test_contract: ContractClass,
  empty: ContractClass,
}
...
```

Have a function that gets these for cairo0 or cairo1.
Then you can have `create_deploy_test_state_by_version` get this class. Or even be a method on create_deploy_test_state_by_version.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/486)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/486#-NViJ1bp9RVqB8tCFagc:-NVoobNn4ItpR3JbmmlJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0f766d5140aae5c0424045230fbf14b8af638a1/crates/blockifier/src/test_utils.rs#L159)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I generally don't like function that get a flag that chagnes their behavior. This specific pattern:
```
fn foof(flag) {
  if flag {
    // bla
  } else {
    // bla
}
```
is not nice, unless you haev a lot of shared places that have only flag without knowing what is is.
https://martinfowler.com/bliki/FlagArgument.html
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/486#-NViK7BX-UOkjNk6oaOZ:-NVoocfm0fP03KJpn4zH:b-ckhbop) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0f766d5140aae5c0424045230fbf14b8af638a1/crates/blockifier/src/test_utils.rs#L251)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Another option is to define a struct of contract classes for the tests. something like:
```
struct TestClasses {
  test_contract: ContractClass,
  empty: ContractClass,
}
...
```

Have a function that gets these for cairo0 or cairo1.
Then you can have `create_deploy_test_state_by_version` get this class. Or even be a method on create_deploy_test_state_by_version.
</blockquote></details>

Done, sort of.
No functions with flags.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/486#-:-NVxB1TO3X4C51iIZw8t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/486#-:-NVxybZo5wtNFYHXcr0x:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
