### PR TITLE
Elin/merge main v0.13.0 into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1311)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1311)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1311)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1311)* status: 3 of 4 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1311#-NnIXwZk6puMHjdqnsht:-NnIXwZk6puMHjdqnshu:b-4uozzh) ([raw file](https://github.com/starkware-libs/blockifier/blob/a78b227b2acac5ee6d01ac16c5ca1d80f1368ea6/crates/blockifier/src/state/cached_state_test.rs#L413)):*
> ```XML
>     assert_eq!(state.get_compiled_contract_class(&class_hash).unwrap(), contract_class);
>     assert_eq!(global_cache.lock().unwrap().cache_hits().unwrap(), 1);
>     assert_eq!(global_cache.lock().unwrap().cache_size(), 1);
> ```

Arni deleted the `unwrap()` in `main-v0.13.0`; other than that, I took changes from `main`.



_Code quote:_
```XML
global_cache.lock().unwrap()
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1311#-:-NnIZsQX2WmQe_pI5Kxx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1311#-NnIXwZk6puMHjdqnsht:-NnIZcja1BzyPNaaZBd_:bo6apac) ([raw file](https://github.com/starkware-libs/blockifier/blob/a78b227b2acac5ee6d01ac16c5ca1d80f1368ea6/crates/blockifier/src/state/cached_state_test.rs#L413)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Arni deleted the `unwrap()` in `main-v0.13.0`; other than that, I took changes from `main`.
</blockquote></details>

Indeed.

**Pull request merged**
