### PR TITLE
Add an account transactions flow test.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/269)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/269)* status: all files reviewed, 7 unresolved discussions (waiting on @Adi-Yakovian, @elintul, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPD0mzB3d7oxLPG_bQR:-NPD0mzB3d7oxLPG_bQS:b-24jvl7) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/test_utils.rs#L78)):*
> ```XML
> pub const TEST_ERC20_SEQUENCER_BALANCE_KEY: &str =
>     "0x723973208639b7839ce298f7ffea61e3f9533872defd7abdb91023db4658812";
> // Will be removed once `get_storage_var_address` is implemented.
> ```

Move above `// Storage keys.` and maybe as a TODO?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHLWJC0yKFUG-iWBKc:-NPHLWJC0yKFUG-iWBKd:b32wzk) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L35)):*
> ```XML
>         (test_erc20_class_hash, get_contract_class(ERC20_CONTRACT_PATH)),
>     ]);
>     // Deploy the erc20 contract
> ```

x3



_Suggestion:_
```XML
// Deploy the erc20 contract.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHLumr3Kn_4kugZT2T:-NPHLumr3Kn_4kugZT2U:b-crlw8u) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L51)):*
> ```XML
>     let max_fee = Fee(BALANCE as u128);
> 
>     // Update the balance of the about to be deployed account contract in the erc20 contract, so it
> ```

Move to `create_state()`.



_Code quote:_
```XML
    // Update the balance of the about to be deployed account contract in the erc20 contract, so it
    // can pay for the transaction execution.
    state.set_storage_at(
        block_context.fee_token_address,
        StorageKey(patricia_key!(TEST_ERC20_DEPLOYED_ACCOUNT_BALANCE_KEY)),
        stark_felt!(max_fee.0 as u64),
    );
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHMmA-AXP-LS9Mng-d:-NPHMmA-AXP-LS9Mng-e:b32wzl) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L65)):*
> ```XML
>     let mut account_tx = AccountTransaction::DeployAccount(deploy_account_tx);
> 
>     let mut _actual_execution_info = account_tx.execute(state, block_context).unwrap();
> ```

x4



_Suggestion:_
```XML
    let mut account_tx = AccountTransaction::DeployAccount(deploy_account_tx);
    account_tx.execute(state, block_context).unwrap();
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHWymPAONuBx4JJbWI:-NPHWymQCH-I2xM1SDJ1:b-4dcekc) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L67)):*
> ```XML
>     let mut _actual_execution_info = account_tx.execute(state, block_context).unwrap();
> 
>     // Verify deployment.
> ```

You can remove this from the flow test, it will fail the later transactions if the contract wasn't deployed.



_Code quote:_
```XML
    // Verify deployment.
    let mut class_hash_from_state = state.get_class_hash_at(deployed_account_address).unwrap();
    assert_eq!(class_hash_from_state, class_hash);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHXKHK1rSf0jYWJroU:-NPHXKHK1rSf0jYWJroV:buot105) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L82)):*
> ```XML
> 
>     // Check the class_hash -> contract_class mapping has been updated.
>     let contract_class_from_state = state.get_contract_class(&declare_class_hash).unwrap();
> ```

If this is also tested in a unit test, you can remove it from the flow test.



_Code quote:_
```XML
    // Check the class_hash -> contract_class mapping has been updated.
    let contract_class_from_state = state.get_contract_class(&declare_class_hash).unwrap();
    assert_eq!(contract_class_from_state, contract_class);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHYJFz9PGb9VTvxrnv:-NPHYJFz9PGb9VTvxrnw:brhumzt) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L113)):*
> ```XML
>     )
>     .unwrap();
>     class_hash_from_state = state.get_class_hash_at(contract_address).unwrap();
> ```

Same here.



_Code quote:_
```XML
    // Verify deployment.
    // Calculate the newly deployed contract address
    let contract_address = calculate_contract_address(
        ContractAddressSalt::default(),
        class_hash,
        &calldata![stark_felt!(1), stark_felt!(1)],
        deployed_account_address,
    )
    .unwrap();
    class_hash_from_state = state.get_class_hash_at(contract_address).unwrap();
    assert_eq!(class_hash_from_state, class_hash);
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/269)* status: all files reviewed, 7 unresolved discussions (waiting on @Adi-Yakovian, @alonh5, and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPD0mzB3d7oxLPG_bQR:-NPHxQIQ0HyVPV6Q7mUn:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/test_utils.rs#L78)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Move above `// Storage keys.` and maybe as a TODO?
</blockquote></details>

Done.



_Code quote (from crates/blockifier/src/transaction/account_transactions_test.rs):_
```XML
max_fee
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHLWJC0yKFUG-iWBKc:-NPIDi_O0gRnBX9yaruG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L35)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

x3
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHLumr3Kn_4kugZT2T:-NPIEBubANquEaMVIbcr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L51)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Move to `create_state()`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHMmA-AXP-LS9Mng-d:-NPIENthASjb3qUwN2gS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L65)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

x4
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHWymPAONuBx4JJbWI:-NPIEZLw8tVYtz32XCSB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L67)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can remove this from the flow test, it will fail the later transactions if the contract wasn't deployed.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHXKHK1rSf0jYWJroU:-NPIE_614Gm0SkUWYPuV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L82)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

If this is also tested in a unit test, you can remove it from the flow test.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPHYJFz9PGb9VTvxrnv:-NPIE_wn02UkDDoddlhZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/transaction/account_transactions_test.rs#L113)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/269)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @Adi-Yakovian, @elintul, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPD0mzB3d7oxLPG_bQR:-NPNELVc-VICidBuD3p3:b-6j5ti5) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/test_utils.rs#L78)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Above :) 
So it's clear we want to remove them all.
___
*[`crates/blockifier/src/test_utils.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNEmNy6SbsNqo1ithN:-NPNEmNy6SbsNqo1ithO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/test_utils.rs#L229)):*
> ```XML
> }
> 
> // Transactions
> ```





_Suggestion:_
```XML
// Transactions.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNFE8h82WdB29wwdvz:-NPNFE8h82WdB29wwdw-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/transaction/account_transactions_test.rs#L45)):*
> ```XML
>     });
> 
>     // Update the balance of the about to be deployed account contract in the erc20 contract, so it
> ```





_Suggestion:_
```XML
about-to-be
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNFeY83PIf-4UPr77h:-NPNFeY83PIf-4UPr77i:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/transaction/account_transactions_test.rs#L68)):*
> ```XML
>     account_tx.execute(state, block_context).unwrap();
> 
>     // Declare a contract
> ```





_Suggestion:_
```XML
// Declare a contract.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNFfzH2aPH9IsT7Epx:-NPNFfzH2aPH9IsT7Epy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/transaction/account_transactions_test.rs#L77)):*
> ```XML
>     account_tx.execute(state, block_context).unwrap();
> 
>     // Deploy a contract using syscall deploy
> ```





_Suggestion:_
```XML
// Deploy a contract using syscall deploy.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNHCRwDBF0o2-1XzAW:-NPNHCRx2YaNbn7C4JnQ:b-2gvofn) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/transaction/account_transactions_test.rs#L78)):*
> ```XML
> 
>     // Deploy a contract using syscall deploy
>     let mut entry_point_selector = selector_from_name("deploy_contract");
> ```

Don't use `mut` here; just use `let` when creating a new `entry_point_selector`.
Same for all the other `mut`s with the same reason.



_Code quote:_
```XML
let mut entry_point_selector
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNG3oD-bpdTInH7v3F:-NPNG3oE09w4_Ut5A-M0:b-mezybf) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/transaction/account_transactions_test.rs#L97)):*
> ```XML
> 
>     // Calculate the newly deployed contract address
>     let contract_address = calculate_contract_address(
> ```

This is still needed because you can't get the contract address from the deploy syscall, right?



_Code quote:_
```XML
let contract_address = calculate_contract_address(
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/269)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @Adi-Yakovian, @alonh5, and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPD0mzB3d7oxLPG_bQR:-NPNNJ31Aswebx8OIXQK:b-kih9l6) ([raw file](https://github.com/starkware-libs/blockifier/blob/de5e234bdb23acb0e2d9855b229e65612a089b99/crates/blockifier/src/test_utils.rs#L78)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Above :) 
So it's clear we want to remove them all.
</blockquote></details>

Got it. Done.
___
*[`crates/blockifier/src/test_utils.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNEmNy6SbsNqo1ithN:-NPNNXJeDvwnayBtq3A_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/test_utils.rs#L229)):*
> ```XML
> }
> 
> // Transactions
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNFE8h82WdB29wwdvz:-NPNNdEi-EHrExEg5lGd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/transaction/account_transactions_test.rs#L45)):*
> ```XML
>     });
> 
>     // Update the balance of the about to be deployed account contract in the erc20 contract, so it
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNFeY83PIf-4UPr77h:-NPNNgZjEusKHF_vZ4RX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/transaction/account_transactions_test.rs#L68)):*
> ```XML
>     account_tx.execute(state, block_context).unwrap();
> 
>     // Declare a contract
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNFfzH2aPH9IsT7Epx:-NPNNgoyB1VzMsbuRRPE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/transaction/account_transactions_test.rs#L77)):*
> ```XML
>     account_tx.execute(state, block_context).unwrap();
> 
>     // Deploy a contract using syscall deploy
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNHCRwDBF0o2-1XzAW:-NPNO9231ZrVTsWIDJw1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/transaction/account_transactions_test.rs#L78)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Don't use `mut` here; just use `let` when creating a new `entry_point_selector`.
Same for all the other `mut`s with the same reason.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/269#-NPNG3oD-bpdTInH7v3F:-NPNOCYx3wzJvTmJjX81:btqqu5l) ([raw file](https://github.com/starkware-libs/blockifier/blob/31cca4e6e1d9282b2993289680960e66cea109e9/crates/blockifier/src/transaction/account_transactions_test.rs#L97)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is still needed because you can't get the contract address from the deploy syscall, right?
</blockquote></details>

Correct.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/269#-:-NPNUgEK6Gh6eb35APT5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Adi-Yakovian and @elintul)

**Pull request merged**
