### PR TITLE
refactor: sort versioned_constants json

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1561)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Plz add another reviewer

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1561#-:-Nr9IVSU2IbrzCtvNyMM:bx8k9wo)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by giladchase — COMMENTED** [review]
Python PR

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1561#-:-Nr9WII80jKcKiHrh9sc:b-5xgmnz)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by OriStarkware — COMMENTED** [review]
Python PR: https://reviewable.io/reviews/starkware-industries/starkware/34100

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1561#-:-NrAQ5C52oR08cBT-qyC:b6160mq)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1561)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @OriStarkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1561#-NrAfUBTDxAe4NdF3VPv:-NrAfUBTDxAe4NdF3VPw:b-10o17o) ([raw file](https://github.com/starkware-libs/blockifier/blob/01e133e9a8ec437fc7aff4074f1451b79ec9884e/crates/blockifier/resources/versioned_constants.json#L23)):*
> ```JSON
>             "syscall_base_gas_cost": 1,
>             "step_gas_cost": 10,
>             "entry_point_gas_cost": 1
> ```

alphabetize



_Code quote:_
```JSON
            "syscall_base_gas_cost": 1,
            "step_gas_cost": 10,
            "entry_point_gas_cost": 1
```
___
*[`crates/blockifier/resources/versioned_constants.json` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1561#-NrAfcop2neS8BJnYJyv:-NrAfcop2neS8BJnYJyw:bf29064) ([raw file](https://github.com/starkware-libs/blockifier/blob/01e133e9a8ec437fc7aff4074f1451b79ec9884e/crates/blockifier/resources/versioned_constants.json#L30)):*
> ```JSON
>             "syscall_base_gas_cost": 1,
>             "step_gas_cost": 200,
>             "entry_point_gas_cost": 1
> ```

alphabetize x7?



_Code quote:_
```JSON
            "syscall_base_gas_cost": 1,
            "step_gas_cost": 200,
            "entry_point_gas_cost": 1
```

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1561)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1561)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 34 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1561#-NrV_vDEB3FPoyEGcHHv:-NrV_vDF3pdCpKE6I_lY:bq1sqpy) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a86f3e2a7049ff3db3e009d7fc1ef3bfbd9d6c9/crates/blockifier/src/versioned_constants.rs#L34)):*
> ```XML
> });
> 
> pub type ResourceCost = Ratio<u128>;
> ```

what's the reason for this change?

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1561)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by giladchase — DISMISSED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1561)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1561#-:-Nr_pWpm3O0m0blSyHf2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
