### PR TITLE
calculate_tx_fee may use strk gas price

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdVDY6UAkxvHgeq48Vk:-NdVDY6UAkxvHgeq48Vl:b-bw6er5) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transactions_test.rs#L301)):*
> ```XML
> 
>     let account_tx = AccountTransaction::Invoke(invoke_tx.into());
>     let pays_with_strk = account_tx.pays_with_strk();
> ```

I think we talked about this one, and I think on second thought these are beginning to multiply...

Could this be handled seamlessly via a trait?
So that we can do block_context.gas_price() and always get the right thing without the extra arg?



_Code quote:_
```XML
account_tx.pays_with_strk();
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdVDY6UAkxvHgeq48Vk:-NdVN4JI8xAbpWGjhxyk:bkmcgoq) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transactions_test.rs#L301)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think we talked about this one, and I think on second thought these are beginning to multiply...

Could this be handled seamlessly via a trait?
So that we can do block_context.gas_price() and always get the right thing without the extra arg?
</blockquote></details>

To know the correct gas price, one needs to know the tx version *and* the block context.
It cannot be a method of `BlockContext`, or of `AccountTransaction[Context]`.
What are you suggesting?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdVDY6UAkxvHgeq48Vk:-NdYoWst92VDv7zHG969:b-chtu4t) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transactions_test.rs#L301)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

To know the correct gas price, one needs to know the tx version *and* the block context.
It cannot be a method of `BlockContext`, or of `AccountTransaction[Context]`.
What are you suggesting?
</blockquote></details>

WDYT about this one:
- Group both prices into a `struct GasPrice` which we put in `BlockContext.gas_price`.
- Create `pub trait HasTransactionVersion` which will have a `tx_version() -> TransactionVersion`.
- Add to `GasPrice`:
```rust
get_for_version(&self, has_version: impl HasTransactionVersion) -> u128 {
  if has_version.tx_version() > TransactionVersion(StarkFelt::from(3_u128))
        self.strk_l1_gas_price
    } else {
        self.eth_l1_gas_price
    }
}
```
- `Impl` HasTransactionVersion for both `AccountTransaction, AccountTransactionContext`, where the former delegates to the latter like `pays_with_strk()`.

Then whenever we need to get the gas price from `BlockContext` we can do `block_context.gas_price.get_for_version(account_tx)` or
`block_context.gas_price.get_for_version(account_tx_context)`.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdVDY6UAkxvHgeq48Vk:-NdZE-Xe04LjchHGOgJv:b-xgz2i8) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transactions_test.rs#L301)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

WDYT about this one:
- Group both prices into a `struct GasPrice` which we put in `BlockContext.gas_price`.
- Create `pub trait HasTransactionVersion` which will have a `tx_version() -> TransactionVersion`.
- Add to `GasPrice`:
```rust
get_for_version(&self, has_version: impl HasTransactionVersion) -> u128 {
  if has_version.tx_version() > TransactionVersion(StarkFelt::from(3_u128))
        self.strk_l1_gas_price
    } else {
        self.eth_l1_gas_price
    }
}
```
- `Impl` HasTransactionVersion for both `AccountTransaction, AccountTransactionContext`, where the former delegates to the latter like `pays_with_strk()`.

Then whenever we need to get the gas price from `BlockContext` we can do `block_context.gas_price.get_for_version(account_tx)` or
`block_context.gas_price.get_for_version(account_tx_context)`.
</blockquote></details>

I like!
You on it?

**Review by amosStarkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdZmyxoAyoUrG40QIgH:-NdZmyxp45zRfPyt2I_D:b-pwry12) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transaction_execution.rs#L96)):*
> ```XML
>         _validate: bool,
>     ) -> TransactionExecutionResult<TransactionExecutionInfo> {
>         // L1 handler transactions never pay with STRK.
> ```

can you elaborate? non blocking



_Code quote:_
```XML
// L1 handler transactions never pay with STRK.
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdZnUe_CYQHWjc0H-gq:-NdZnUe_CYQHWjc0H-gr:b-ny3e2u) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transaction_execution.rs#L126)):*
> ```XML
>         let actual_resources =
>             calculate_tx_resources(&resources, l1_gas_usage, TransactionType::L1Handler)?;
>         let actual_fee = calculate_tx_fee(&actual_resources, &context.block_context, false)?;
> ```

add same comment here?
non blocking



_Code quote:_
```XML
let actual_fee = calculate_tx_fee(&actual_resources, &context.block_context, false)?;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 298 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdZrBTuC_MsUGElhatj:-NdZrBTuC_MsUGElhatk:b533vka) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transactions_test.rs#L298)):*
> ```XML
>     // transaction.
>     let calldata = Calldata(Arc::clone(&invoke_tx.calldata.0));
>     let sender_address = invoke_tx.sender_address;
> ```

do we need a TODO for adding V3 txs to tests (here or elsewhere in the blockifier)?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdZsSTg9Cc9mhd-8Ex4:-NdZsSTg9Cc9mhd-8Ex5:b-vgoau5) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transactions_test.rs#L301)):*
> ```XML
> 
>     let account_tx = AccountTransaction::Invoke(invoke_tx.into());
>     let pays_with_strk = account_tx.pays_with_strk();
> ```

why declare vars so many lines before they are used (relevant to the other tests too)?



_Code quote:_
```XML
let pays_with_strk = account_tx.pays_with_strk();
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdVDY6UAkxvHgeq48Vk:-NdZtr9DCumqMlmhwDpX:bge80kc) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transactions_test.rs#L301)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I like!
You on it?
</blockquote></details>

Just saw this now... so this version of the PR is not relevant?
publishing review in case it is

**Review by amosStarkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdVDY6UAkxvHgeq48Vk:-Ndck1M88A0OAQAFT2l-:biuph7l) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transactions_test.rs#L301)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Just saw this now... so this version of the PR is not relevant?
publishing review in case it is
</blockquote></details>

:woohoo:
Done, PTAL: https://reviewable.io/reviews/starkware-libs/blockifier/894

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdZmyxoAyoUrG40QIgH:-Ndeo5_83HViUnQ1Vr9n:b-t21dkb) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transaction_execution.rs#L96)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

can you elaborate? non blocking
</blockquote></details>

L1 handlers handler transactions from L1. These are always paid for in ETH.
@noaov1 am I correct on this?
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdZnUe_CYQHWjc0H-gq:-NdeoMgo62Kcv2pPA8L2:b5031gw) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transaction_execution.rs#L126)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

add same comment here?
non blocking
</blockquote></details>

added a TODO even
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 298 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdZrBTuC_MsUGElhatj:-NdeoRA97hep9Nm6Wqma:bnyllc) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transactions_test.rs#L298)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

do we need a TODO for adding V3 txs to tests (here or elsewhere in the blockifier)?
</blockquote></details>

We need to test V3 logic in general, have have items tracking that
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdZsSTg9Cc9mhd-8Ex4:-NdeodSY4kkFiupwQxbc:blx0uy1) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transactions_test.rs#L301)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why declare vars so many lines before they are used (relevant to the other tests too)?
</blockquote></details>

because `account_tx.execute` consumes `account_tx`, and I don't want to clone it.
:rust-life: (pretend it's an emoji, I'm lazy)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @giladchase)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NdZmyxoAyoUrG40QIgH:-NdfRNor-W15xhFVhxS5:b2nhswy) ([raw file](https://github.com/starkware-libs/blockifier/blob/a45000cf1474618444fc30a8b2106a2fa7b7bcbb/crates/blockifier/src/transaction/transaction_execution.rs#L96)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

L1 handlers handler transactions from L1. These are always paid for in ETH.
@noaov1 am I correct on this?
</blockquote></details>

Yes

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r4, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/885#-NebyK-MD-rviivfO11u:-NebyK-MD-rviivfO11v:bf89iui) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf7a60891a4fcf8cde1ec0b14341ea07c150dd64/crates/blockifier/src/fee/fee_utils.rs#L54)):*
> ```XML
>     block_context: &BlockContext,
>     fee_type: &FeeType,
> ) -> TransactionExecutionResult<Fee> {
> ```

Plz add a TODO(Gilad) on this for adding a calculate_tx_fee method/trait-method for AccountTransaction/L1-Handler that wraps this and feeds it `self.fee_type`.
The only non-`self.fee_type` usages are in tests.



_Code quote:_
```XML
pub fn calculate_tx_fee(
    resources: &ResourcesMapping,
    block_context: &BlockContext,
    fee_type: &FeeType,
) -> TransactionExecutionResult<Fee> {
```

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

**Review by giladchase — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/885)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

**Pull request merged**
