### PR TITLE
Add from_storage to CairoU128 impl.

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/856)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/sierra_types.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/856#-Nd-FhDe6KTUTwC4s-_z:-Nd-FhDe6KTUTwC4s-a-:by0plvc) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b68fd7dde0e60ed9abac1dd4eb3ff0f5efc93ec/crates/blockifier/src/abi/sierra_types.rs#L110)):*
> ```XML
>         key: &StorageKey,
>     ) -> SierraTypeResult<Self> {
>         let low_val_as_felt = stark_felt_to_felt(state.get_storage_at(*contract_address, *key)?);
> ```

use SierraU128::from_storage



_Code quote:_
```XML
   let low_val_as_felt = stark_felt_to_felt(state.get_storage_at(*contract_address, *key)?);
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/856)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/abi/sierra_types.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/856#-Nd-FhDe6KTUTwC4s-_z:-Nd-KaxO8fQGR5cOcnlI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b68fd7dde0e60ed9abac1dd4eb3ff0f5efc93ec/crates/blockifier/src/abi/sierra_types.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

use SierraU128::from_storage
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/sierra_types.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/856#-Nd-Ks7uBzxZ9_iCf6GQ:-Nd-Ks7uBzxZ9_iCf6GR:b65uiv) ([raw file](https://github.com/starkware-libs/blockifier/blob/3ec4182babd128ebc7206f5bb96d64fcf2f1f48e/crates/blockifier/src/abi/sierra_types.rs#L113)):*
> ```XML
>         let high_key = StorageKey(PatriciaKey::try_from(StarkFelt::from(
>             FieldElement::from(*key.0.key()) + FieldElement::ONE,
>         ))?);
> ```

Consider refactoring into a `next_storage_cell` function.



_Code quote:_
```XML
        let high_key = StorageKey(PatriciaKey::try_from(StarkFelt::from(
            FieldElement::from(*key.0.key()) + FieldElement::ONE,
        ))?);
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/856)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/abi/sierra_types.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/856#-Nd-Ks7uBzxZ9_iCf6GQ:-Nd-LAf-4zssI8HMY7h3:b-jvwido) ([raw file](https://github.com/starkware-libs/blockifier/blob/3ec4182babd128ebc7206f5bb96d64fcf2f1f48e/crates/blockifier/src/abi/sierra_types.rs#L113)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Consider refactoring into a `next_storage_cell` function.
</blockquote></details>

Done.
I've already done that that in the next PR:
https://reviewable.io/reviews/starkware-libs/blockifier/857

Do you prefer to move it here?

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/856#-:-Nd-KqjhBIyf2MXEAyoQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/856)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/abi/sierra_types.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/856#-Nd-Ks7uBzxZ9_iCf6GQ:-Nd-LgSYCTNCdVQty9xy:b-hzo8bm) ([raw file](https://github.com/starkware-libs/blockifier/blob/3ec4182babd128ebc7206f5bb96d64fcf2f1f48e/crates/blockifier/src/abi/sierra_types.rs#L113)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
I've already done that that in the next PR:
https://reviewable.io/reviews/starkware-libs/blockifier/857

Do you prefer to move it here?
</blockquote></details>

no, I put it as non-blocking.

**Pull request merged**
