### PR TITLE
feat(state): bouncer DA count: use StateWriteKeys to count state diff…

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
… size

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-Nq7GWlS693slZNAfjpw:-Nq7GWlTBFsgIME6uEXV:b-g9r3jn) ([raw file](https://github.com/starkware-libs/blockifier/blob/e386204c96419f693f201c0ef229f38bff3675d6/crates/native_blockifier/src/transaction_executor.rs#L121)):*
> ```XML
>                 // Count residual state diff size (w.r.t. the OS output encoding).
>                 let tx_state_write_keys = transactional_state.cache.get_write_keys();
>                 let tx_unique_write_keys = tx_state_write_keys.difference(&self.state_write_keys);
> ```

Isn't it still wrong here as it was in #1438? If it is relevant - can you explain the issue? write a TODO?



_Code quote:_
```XML
let tx_unique_write_keys = tx_state_write_keys.difference(&self.state_write_keys);
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-Nq7K3JTBlCHPILpfCmO:-Nq7K3JTBlCHPILpfCmP:bd9dwrm) ([raw file](https://github.com/starkware-libs/blockifier/blob/e386204c96419f693f201c0ef229f38bff3675d6/crates/native_blockifier/src/transaction_executor.rs#L91)):*
> ```XML
>             Ok(tx_execution_info) => {
>                 // Prepare bouncer info; the countings here should be linear in the transactional
>                 // state and execution info rather than the cumulative state attributes.
> ```

If my suggestion isn't true, what does "linear in transactional state" mean?



_Suggestion:_
```XML
                // Prepare bouncer info; the countings here should be linear in the transactional
                // state changes and execution info rather than the cumulative state attributes.
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-Nq7GWlS693slZNAfjpw:-Nq7N6lQC6udhzNfnDGQ:bymv9fp) ([raw file](https://github.com/starkware-libs/blockifier/blob/e386204c96419f693f201c0ef229f38bff3675d6/crates/native_blockifier/src/transaction_executor.rs#L121)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Isn't it still wrong here as it was in #1438? If it is relevant - can you explain the issue? write a TODO?
</blockquote></details>

No, I'm subtracting **keys**.

Consider this:
```
tx0_changes: {0: 100}
tx1_changes: {0: 200}

// Not good. The overall state diff size does not increase.
len(tx1 - tx0) == 1
//Good.
len(tx1.keys() - tx0.keys()) == 0 
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @noaov1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-Nq7Wy8700v1UWrJtsDv:-Nq7Wy8700v1UWrJtsDw:b-zhcw6t) ([raw file](https://github.com/starkware-libs/blockifier/blob/59d6db11785d1d647b7fe4e44f614518502f248e/crates/native_blockifier/src/transaction_executor.rs#L37)):*
> ```XML
>     // This member should (and must) be consistent with the state's write keys.
>     // Kept in separate since the cache's members are private.
>     pub state_write_keys: StateWriteKeys,
> ```

To keep the invariant you're describing.



_Suggestion:_
```XML
    // This member should (and must) be consistent with the state's write keys.
    // Kept in separate since the cache's members are private.
    state_write_keys: StateWriteKeys,
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-Nq7VgYhD2lXIPo7ZI96:-Nq7VgYi2PI_MW1rk2Zx:bo9xfit) ([raw file](https://github.com/starkware-libs/blockifier/blob/59d6db11785d1d647b7fe4e44f614518502f248e/crates/native_blockifier/src/transaction_executor.rs#L120)):*
> ```XML
> 
>                 // Count residual state diff size (w.r.t. the OS output encoding).
>                 let tx_state_write_keys = transactional_state.cache.get_write_keys();
> ```

You can implement `get_write_keys` in an `impl` block of `TransactioalState` and avoid changing `cache`'s visibility.



_Code quote:_
```XML
transactional_state.cache.get_write_keys()
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r5, 19 of 19 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: 20 of 22 files reviewed, 2 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-Nq7VgYhD2lXIPo7ZI96:-Nq7dc9j7LFBsi45oE7H:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/59d6db11785d1d647b7fe4e44f614518502f248e/crates/native_blockifier/src/transaction_executor.rs#L120)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You can implement `get_write_keys` in an `impl` block of `TransactioalState` and avoid changing `cache`'s visibility.
</blockquote></details>

Done.

**Review by elintul — DISMISSED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 345 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-Nq7dwxODL4oN6gxqrJ7:-Nq7dwxODL4oN6gxqrJ8:b-1qulw4) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b4e330f80886586501df3bfadc9fa99175811c6/crates/blockifier/src/state/cached_state.rs#L345)):*
> ```XML
> }
> 
> impl<S: StateReader> CachedState<S> {
> ```

I think it's better to `impl` this method for `TransactionalState`, since this is a transactional semantic.



_Code quote:_
```XML
impl<S: StateReader> CachedState<S>
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 57 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-Nq7jy7nCl0I7zLvBO1v:-Nq7l6Cy2PMLjZccOl_N:b1jw4j4) ([raw file](https://github.com/starkware-libs/blockifier/blob/d71a15eb1f45721eeab94592b02a71e34d816167/crates/native_blockifier/src/transaction_executor.rs#L57)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I wanted to suggest that, too. :)
Then you don't take into account the fact that `state` might not be empty?
</blockquote></details>

Yes but it's not too bad since I can only count (constant amount of) extra changes, which is fine

**Review by elintul — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-:-Nq7pk1m1NaP8dJPtUZZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 782 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-Nq81_oGDz0k4xEvBqUj:-Nq81_oGDz0k4xEvBqUk:bpvxya6) ([raw file](https://github.com/starkware-libs/blockifier/blob/65ee3c4e890b0f9221dde409b960281c4fef6feb/crates/blockifier/src/state/cached_state.rs#L782)):*
> ```XML
> 
>     pub fn into_keys(self) -> StateChangesKeys {
>         let modified_contracts = self.get_modified_contracts();
> ```

Pass directly.



_Code quote:_
```XML
self.get_modified_contracts()
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 123 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1462#-Nq82G437XeqNwIO5aK7:-Nq82G437XeqNwIO5aK8:brdw7l1) ([raw file](https://github.com/starkware-libs/blockifier/blob/65ee3c4e890b0f9221dde409b960281c4fef6feb/crates/native_blockifier/src/transaction_executor.rs#L123)):*
> ```XML
>                     transactional_state.get_actual_state_changes()?.into_keys();
>                 let tx_state_changes_keys =
>                     tx_state_changes_keys.difference(&self.state_changes_keys);
> ```

Consider moving into a small method.



_Code quote:_
```XML
                let tx_state_changes_keys =
                    transactional_state.get_actual_state_changes()?.into_keys();
                let tx_state_changes_keys =
                    tx_state_changes_keys.difference(&self.state_changes_keys);
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 3 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1462)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
