### PR TITLE
Call calculate_tx_fee.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/412)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/412)* status: 0 of 6 files reviewed, 2 unresolved discussions

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/412#-NT8DFrK3gwNfcCucKTE:-NT8DFrK3gwNfcCucKTF:bgwvrp4) ([raw file](https://github.com/starkware-libs/blockifier/blob/a83d918888ab4c38e7db311fa9a3f9021db8e1c6/crates/blockifier/src/transaction/transactions_test.rs#L430)):*
> ```XML
>     // Build expected fee transfer call info.
>     // TODO(Noa, 01/05/23): Calculate the actual fee using the transaction.
>     let expected_actual_fee = Fee(391200000000000);
> ```

The value corresponds to the amount calculated in the python code.



_Code quote:_
```XML
Fee(391200000000000)
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 539 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/412#-NT8DWmI95p4LEFNuLc2:-NT8DWmI95p4LEFNuLc3:bgwvrp4) ([raw file](https://github.com/starkware-libs/blockifier/blob/a83d918888ab4c38e7db311fa9a3f9021db8e1c6/crates/blockifier/src/transaction/transactions_test.rs#L539)):*
> ```XML
>     // Build expected fee transfer call info.
>     // TODO(Noa, 01/05/23): Calculate the actual fee using the transaction.
>     let expected_actual_fee = Fee(664400000000000);
> ```

The value corresponds to the amount calculated in the python code.



_Code quote:_
```XML
Fee(664400000000000);
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/412)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/412#-NT8a3QP0LJ0B1TWDOiM:-NT8a3QP0LJ0B1TWDOiN:b-bpa6tf) (no related file):*
Can you please add Dori to review this PR?

___

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/412)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/412#-NT8jEeO615qdea3Wv0i:-NT8jEeO615qdea3Wv0j:be6bs19) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4e496bbcfb82d5a254844ddfeb9823f1e9c307f/crates/blockifier/src/test_utils.rs#L79)):*
> ```XML
> 
> // The amount of test-token allocated to the account in this test.
> pub const BALANCE: u64 = 1000000 * 100000000000; // 1000000 * min_gas_price.
> ```

why is min gas price 100gwei? (non-blocking)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 294 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/412#-NT8joKb4ub2vsuZsNbG:-NT8joKb4ub2vsuZsNbH:b-g1igph) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4e496bbcfb82d5a254844ddfeb9823f1e9c307f/crates/blockifier/src/transaction/transactions_test.rs#L294)):*
> ```XML
>     // Build expected fee transfer call info.
>     // TODO(Noa, 01/05/23): Calculate the actual fee using the transaction.
>     let expected_actual_fee = Fee(530600000000000);
> ```

WDYM by the TODO?
1. compute the expected fee using named values?
2. compute the expected fee by calling calculate_fee?



_Code quote:_
```XML
    // TODO(Noa, 01/05/23): Calculate the actual fee using the transaction.
    let expected_actual_fee = Fee(530600000000000);
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/412)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/412#-NT8jEeO615qdea3Wv0i:-NT8rugV0-nRWM1vXDQB:b5ymbeo) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4e496bbcfb82d5a254844ddfeb9823f1e9c307f/crates/blockifier/src/test_utils.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is min gas price 100gwei? (non-blocking)
</blockquote></details>

Great question. It is copied from the python code [here](https://github.com/starkware-industries/starkware/blob/9698a87b65d70c73317bce5b401a63254c8a0787/src/starkware/starknet/business_logic/transaction/objects_test.py#L121).
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 294 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/412#-NT8joKb4ub2vsuZsNbG:-NT908UbAgAIopy8AjDU:b-brrwhf) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4e496bbcfb82d5a254844ddfeb9823f1e9c307f/crates/blockifier/src/transaction/transactions_test.rs#L294)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM by the TODO?
1. compute the expected fee using named values?
2. compute the expected fee by calling calculate_fee?
</blockquote></details>

I meant: `let expected_actual_fee = calculate_tx_fee(&actual_execution_info.actual_resources, block_context).unwrap();`. 
I can change it now. WDYT?

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/412)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/412)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 294 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/412#-NT8joKb4ub2vsuZsNbG:-NT9isY99iFuJvvoUET9:b-b0yy53) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4e496bbcfb82d5a254844ddfeb9823f1e9c307f/crates/blockifier/src/transaction/transactions_test.rs#L294)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I meant: `let expected_actual_fee = calculate_tx_fee(&actual_execution_info.actual_resources, block_context).unwrap();`. 
I can change it now. WDYT?
</blockquote></details>

I think it's better; this is a unit test, you are not testing the fee calculation, only the fact that the result of the calculation is deducted from the balance.
You could also assert that the calculated value is `530600000000000` as a regression test, but don't know if it's the right place

**Review by noaov1 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/412#-:-NTD8A4R8gLSLEzIcqfh:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @elintul)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/412)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/412#-:-NTD8XdG2YEAnzgQHgpI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
