### PR TITLE
Elin/merge main v0.13.0 into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1228)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1228)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1228)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1228#-Nl3fE7DC0T8ZeLXKY6p:-Nl3fE7DC0T8ZeLXKY6q:b-afcy8d) (no related file):*
[Python PR](https://reviewable.io/reviews/starkware-industries/starkware/32931).

___

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1228#-:-Nl3h7rhDw7GJ6JZGlzd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1228)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
