### PR TITLE
Add cairo file verification workflow

### PR DESCRIPTION
**Pull request by giladchase**
If someone touches cairo source code or compiled contracts, they must pass the verification check before being merged.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/231)

### CODE REVIEW

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/231#-:-NMU6PJg-oj17VFD8EV3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`.github/workflows/compiled_cairo.yml` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/231#-NMU5yyp4V74Xah9wiZp:-NMU5yyp4V74Xah9wiZq:b42wub6) ([raw file](https://github.com/starkware-libs/blockifier/blob/018efe2358765b3d31bd9e91481df56f5bbb40bf/.github/workflows/compiled_cairo.yml#L17)):*
> ```YAML
>     paths:
>      - '**.cairo'
>      - 'crates/blockifier/feature_contracts/**'
> ```

Only the contracts in this directory are tested, so I think that's enough.



_Suggestion:_
```YAML
     - 'crates/blockifier/feature_contracts/**'
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/231)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5 and @elintul)

___
*[`.github/workflows/compiled_cairo.yml` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/231#-NMU5yyp4V74Xah9wiZp:-NMU6yxWBT6wikAJnzhp:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/018efe2358765b3d31bd9e91481df56f5bbb40bf/.github/workflows/compiled_cairo.yml#L17)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Only the contracts in this directory are tested, so I think that's enough.
</blockquote></details>

Done

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
