### PR TITLE
Elin/merge main v0.12.3 into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1054)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1054)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1054)* status: 11 of 16 files reviewed, all discussions resolved (waiting on @elintul)

**Review by giladchase — COMMENTED** [review]
:lgtm:  But better have Noa look at it too? i didn't write any of the commits here :thinking: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1054#-:-Ni-Q-wD1v7U4_OLT2cP:b-gmbvya)* status: 9 of 16 files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1054#-:-Ni-keki9Qc86xdEizTh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
