### PR TITLE
refactor(concurrency): add UpdatableState trait and change Transactio…

### PR DESCRIPTION
**Pull request by OriStarkware**
…nalState to be a struct

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 13 files at r1, 1 of 3 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 276 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyKFABP5YvE_ZGeLB8U:-NyKFABP5YvE_ZGeLB8V:b-n029uv) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2880d2bcb7f5063dfc26d8cb980d02a8a592e99/crates/blockifier/src/bouncer.rs#L276)):*
> ```XML
>         state: &mut TransactionalState<'_, U>,
>     ) -> TransactionExecutorResult<StateChangesKeys> {
>         let tx_state_changes_keys = state.cached_state.get_actual_state_changes()?.into_keys();
> ```

Consider adding `get_actual_state_changes` method to the transactional state.



_Code quote:_
```XML
let tx_state_changes_keys = state.cached_state.get_actual_state_changes()?.into_keys();
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyLf-kp1L6qK7riF_c2:-NyLf-kp1L6qK7riF_c3:b-uxpekx) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c760c743629fbed70832d54882e0d5ebf4e586a/crates/blockifier/src/state/cached_state.rs#L51)):*
> ```XML
>     /// will either all happen (will be committed) or none of them (will be discarded).
>     pub fn create_transactional(state: &mut CachedState<S>) -> TransactionalState<'_, S> {
>         CachedState::new(MutRefState::new(state))
> ```

Interesting.
Previously, the generic parameter `S` of the `CachedState` struct associated to the method, was the same as the one in the input.
The generic parameter of the newly created `CachedState` was `S=MutRefState( CachedState<S>)`, which allow the compiler to infer it directly from the input.



_Code quote:_
```XML
        CachedState::new(MutRefState::new(state))
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 546 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyLkVoV7JvOYXQ8yxdA:-NyLkVoV7JvOYXQ8yxdB:b-ldwv0x) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2880d2bcb7f5063dfc26d8cb980d02a8a592e99/crates/blockifier/src/state/cached_state.rs#L546)):*
> ```XML
> }
> 
> pub struct TransactionalState<'a, U: UpdatableState> {
> ```

Consider implementing getters of the cached state inner fields



_Code quote:_
```XML
pub struct TransactionalState<'a, U: UpdatableState> {
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 547 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyLFQWACCImJbfxOKPq:-NyLFQWACCImJbfxOKPr:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2880d2bcb7f5063dfc26d8cb980d02a8a592e99/crates/blockifier/src/state/cached_state.rs#L547)):*
> ```XML
> 
> pub struct TransactionalState<'a, U: UpdatableState> {
>     pub cached_state: CachedState<MutRefState<'a, U>>,
> ```

?



_Suggestion:_
```XML
    pub state: CachedState<MutRefState<'a, U>>,
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: 12 of 13 files reviewed, 8 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyO_b-W21yQ_FwT7uar:-NyO_b-W21yQ_FwT7uas:b-2477b9) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2880d2bcb7f5063dfc26d8cb980d02a8a592e99/crates/blockifier/src/concurrency/worker_logic.rs#L92)):*
> ```XML
> 
>         let execution_result =
>             tx.execute_raw(&mut transactional_state, &self.block_context, charge_fee, validate);
> ```

This is the end game, right? (next PR?)



_Suggestion:_
```XML
        let mut tx_state = CachedState::new(tx_versioned_state);
        let validate = true;
        let charge_fee = true;

        let execution_result =
            tx.execute_raw(&mut tx_state, &self.block_context, charge_fee, validate);
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 546 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyLkVoV7JvOYXQ8yxdA:-NyOWuVe7yCe0g5XmXqu:btkkjk9) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2880d2bcb7f5063dfc26d8cb980d02a8a592e99/crates/blockifier/src/state/cached_state.rs#L546)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider implementing getters of the cached state inner fields
</blockquote></details>

Why can't it be 
```rust
pub type TransactionalState<'a, U: UpdateableState> = CachedState<MutRefState<'a, U>>;
```
(To avoid reimplementing the getters and setters)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: 4 of 13 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 548 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyP86ydCc5a9qjhoggR:-NyP86ydCc5a9qjhoggS:b-6crakn) ([raw file](https://github.com/starkware-libs/blockifier/blob/20f7cf9d572618b9e4af403d982f5d50b28c8a60/crates/blockifier/src/state/cached_state.rs#L548)):*
> ```XML
> pub struct TransactionalState<'a, U: UpdatableState> {
>     pub state: CachedState<MutRefState<'a, U>>,
> }
> ```

Consider using `derive_more`.



_Suggestion:_
```XML
pub struct TransactionalState<'a, U: UpdatableState>(pub CachedState<MutRefState<'a, U>>);
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: 4 of 13 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 548 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyP86ydCc5a9qjhoggR:-NyPHYAsCuFN0GwrPky_:b-2q1ujy) ([raw file](https://github.com/starkware-libs/blockifier/blob/20f7cf9d572618b9e4af403d982f5d50b28c8a60/crates/blockifier/src/state/cached_state.rs#L548)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider using `derive_more`.
</blockquote></details>

Solved with a type instead of a struct.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 9 files at r4, 2 of 5 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 236 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyVLkfc7ZjClPNQePhd:-NyVLkfc7ZjClPNQePhe:b-icud5p) ([raw file](https://github.com/starkware-libs/blockifier/blob/67d2bb20d88e850493837b2d03a75e2aabf110a7/crates/blockifier/src/concurrency/worker_logic.rs#L236)):*
> ```XML
> fn add_fee_to_sequencer_balance(
>     fee_token_address: ContractAddress,
>     tx_versioned_state: &mut VersionedStateProxy<impl StateReader>,
> ```

Why was it not needed before?



_Code quote:_
```XML
    tx_versioned_state: &mut VersionedStateProxy<impl StateReader>,
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: 12 of 15 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyVJlHCEnR4yhomiXCf:-NyVMfDW7EJcZZbQFVMS:bb77ufg) ([raw file](https://github.com/starkware-libs/blockifier/blob/67d2bb20d88e850493837b2d03a75e2aabf110a7/crates/blockifier/src/concurrency/versioned_state_test.rs#L45)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Are you planning to do it in a separate PR?
</blockquote></details>

Yes.
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 325 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyVI0az8PNkqU-c0HiD:-NyVNaHp5PGAaLwCJ2rS:b-7yd1q4) ([raw file](https://github.com/starkware-libs/blockifier/blob/67d2bb20d88e850493837b2d03a75e2aabf110a7/crates/blockifier/src/concurrency/versioned_state_test.rs#L325)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It seems wrong. Maybe we should refer to the visited pcs as writes as well.
</blockquote></details>

Added a TODO.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 236 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyVLkfc7ZjClPNQePhd:-NyVOE9g8oMakO7F3aoS:b-yi9zdw) ([raw file](https://github.com/starkware-libs/blockifier/blob/67d2bb20d88e850493837b2d03a75e2aabf110a7/crates/blockifier/src/concurrency/worker_logic.rs#L236)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why was it not needed before?
</blockquote></details>

Because now apply_writes requires a mutable reference.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: 12 of 15 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 76 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyVXLSt4aNEzDtmAM_e:-NyVXLSuEnykv9xvlwKa:b-l2j4vp) ([raw file](https://github.com/starkware-libs/blockifier/blob/68647ec39f29ce77fdce05ee808f57515df31ba6/crates/blockifier/src/blockifier/transaction_executor.rs#L76)):*
> ```XML
>         charge_fee: bool,
>     ) -> TransactionExecutorResult<TransactionExecutionInfo> {
>         let mut transactional_state = TransactionalState::create_transactional(&mut self.state);
> ```

Struct name is informative now



_Suggestion:_
```XML
TransactionalState::new
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: 3 of 15 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 76 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyVXLSt4aNEzDtmAM_e:-NyVchIL6URx5fcDhOEW:blf4nxe) ([raw file](https://github.com/starkware-libs/blockifier/blob/68647ec39f29ce77fdce05ee808f57515df31ba6/crates/blockifier/src/blockifier/transaction_executor.rs#L76)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Struct name is informative now
</blockquote></details>

`new` is taken by CachesState. I am using `create` instead.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r8, 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 521 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyVut046y2m7nTgdt1D:-NyVut046y2m7nTgdt1E:b708uv0) ([raw file](https://github.com/starkware-libs/blockifier/blob/63516b3c47eb7135f20b51f4f877ff22aa4f66ae/crates/blockifier/src/state/cached_state.rs#L521)):*
> ```XML
>     /// will either all happen (will be updated in the state and committed)
>     /// or none of them (will be discarded).
>     pub fn create(state: &mut U) -> TransactionalState<'_, U> {
> ```

I think that it can be confusing. Note that the `TransactionalState` is a type, so, in practice, you can write:
`CachedState::create(state)` and that creates you a transactional state.



_Code quote:_
```XML
    pub fn create(state: &mut U) -> TransactionalState<'_, U> {
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 521 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyVut046y2m7nTgdt1D:-NyW-6sw6XNKKZhS5Uvb:b-6c2n7z) ([raw file](https://github.com/starkware-libs/blockifier/blob/63516b3c47eb7135f20b51f4f877ff22aa4f66ae/crates/blockifier/src/state/cached_state.rs#L521)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that it can be confusing. Note that the `TransactionalState` is a type, so, in practice, you can write:
`CachedState::create(state)` and that creates you a transactional state.
</blockquote></details>

Oh, okay. @OriStarkware you can revert if you want

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 113 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyZKKdNA7d6avWy-KAw:-NyZKKdNA7d6avWy-KAx:bw21gf7) ([raw file](https://github.com/starkware-libs/blockifier/blob/63516b3c47eb7135f20b51f4f877ff22aa4f66ae/crates/blockifier/src/concurrency/worker_logic.rs#L113)):*
> ```XML
>                 &transactional_state.class_hash_to_class.borrow(),
>                 &HashMap::default(),
>             );
> ```

It should work now (it was not moved)



_Suggestion:_
```XML
            tx_versioned_state.apply_writes(
                &transactional_state.cache.borrow().writes,
                &transactional_state.class_hash_to_class.borrow(),
                &HashMap::default(),
            );
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902)* status: 4 of 15 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 113 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyZKKdNA7d6avWy-KAw:-NyZT_iw6bdHRKXI31Ms:baw80pa) ([raw file](https://github.com/starkware-libs/blockifier/blob/63516b3c47eb7135f20b51f4f877ff22aa4f66ae/crates/blockifier/src/concurrency/worker_logic.rs#L113)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It should work now (it was not moved)
</blockquote></details>

apply_writes borrows tx_versioned_state as mutable, so we can not use tx_versioned_state twice.
___
*[`crates/blockifier/src/state/cached_state.rs` line 521 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-NyVut046y2m7nTgdt1D:-NyZTVrDAGP4iQtyX8s3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/63516b3c47eb7135f20b51f4f877ff22aa4f66ae/crates/blockifier/src/state/cached_state.rs#L521)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh, okay. @OriStarkware you can revert if you want
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1902#-:-NyZlcSxByM8zfZdvFk6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
