### PR TITLE
Added gas_price to block_context.

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@noaov1 +reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373#-:-NRh6zf68OfQQiBW4PYl:b-1ebcic)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRh8CFL11hbKw91EN6W:-NRh8CFL11hbKw91EN6X:b-jqcrml) ([raw file](https://github.com/starkware-libs/blockifier/blob/62f12229f9ff65c73afe6ad0e17b29d46edbb496/crates/blockifier/src/test_utils.rs#L201)):*
> ```XML
>             fee_token_address: ContractAddress(patricia_key!(TEST_ERC20_CONTRACT_ADDRESS)),
>             cairo_resource_fee_weights: HashMap::default(),
>             gas_price: 33.3,
> ```

Why? Why not `DEFAULT_GAS_PRICE = 100 * 10**9`?  Or maybe`100000000000`(`min_gas_price`)?



_Code quote:_
```XML
33.3
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/block_context.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhFAi4DJ6IjSICbRxc:-NRhFAi4DJ6IjSICbRxd:b-47wi8x) ([raw file](https://github.com/starkware-libs/blockifier/blob/62f12229f9ff65c73afe6ad0e17b29d46edbb496/crates/blockifier/src/block_context.rs#L16)):*
> ```XML
>     pub fee_token_address: ContractAddress,
>     pub cairo_resource_fee_weights: HashMap<String, u32>,
>     pub gas_price: f64,
> ```

why is gas price not an integer? on ethereum gas price is given in `wei` (integers)



_Code quote:_
```XML
pub gas_price: f64
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhKY_B17Ba8S6jxyI4:-NRhKY_B17Ba8S6jxyI5:b-wa1j94) ([raw file](https://github.com/starkware-libs/blockifier/blob/e7016be1263fc9178f2f670ff309d8172361adba/crates/blockifier/src/fee/fee_utils.rs#L4)):*
> ```XML
> use std::collections::HashMap;
> 
> pub fn extract_l1_gas_and_cairo_usage(resources: &ResourcesMapping) -> (usize, HashMap<std::string::String, usize>){
> ```

you shouldn't need this prefix



_Suggestion:_
```XML
String
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhKfM262yMLPPIxbCA:-NRhKfM262yMLPPIxbCB:bqzi0gg) ([raw file](https://github.com/starkware-libs/blockifier/blob/e7016be1263fc9178f2f670ff309d8172361adba/crates/blockifier/src/fee/fee_utils.rs#L8)):*
> ```XML
>     let l1_gas_usage = match cairo_resource_usage.get("l1_gas_usage") {
>         Some(l1_gas_usage) => *l1_gas_usage,
>         _ => panic!("ResourcesMapping does not have the key l1_gas_usage.")
> ```

this is equivalent, and more precise



_Suggestion:_
```XML
None
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhL4xn7_OvMlIgWW2d:-NRhL4xn7_OvMlIgWW2e:b-5w30lg) ([raw file](https://github.com/starkware-libs/blockifier/blob/e7016be1263fc9178f2f670ff309d8172361adba/crates/blockifier/src/fee/fee_utils.rs#L11)):*
> ```XML
>     };
>     cairo_resource_usage.remove("l1_gas_usage");
>     (l1_gas_usage, cairo_resource_usage)
> ```

squash lines?



_Suggestion:_
```XML
    (l1_gas_usage, cairo_resource_usage.remove("l1_gas_usage"))
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/block_context.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhFAi4DJ6IjSICbRxc:-NRhXdMr-5Pf0aSnLvOD:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/62f12229f9ff65c73afe6ad0e17b29d46edbb496/crates/blockifier/src/block_context.rs#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is gas price not an integer? on ethereum gas price is given in `wei` (integers)
</blockquote></details>

Done
___
*[`crates/blockifier/src/test_utils.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRh8CFL11hbKw91EN6W:-NRhGnvO4Iq0P-_azfwN:b4rrtd5) ([raw file](https://github.com/starkware-libs/blockifier/blob/62f12229f9ff65c73afe6ad0e17b29d46edbb496/crates/blockifier/src/test_utils.rs#L201)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why? Why not `DEFAULT_GAS_PRICE = 100 * 10**9`?  Or maybe`100000000000`(`min_gas_price`)?
</blockquote></details>

that's the average gas price I saw on google, but I forgot to convert wei -> gwei.
Done (with `DEFAULT_GAS_PRICE = 100 * 10**9`)
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhKY_B17Ba8S6jxyI4:-NRhXPKA5lnzD-SWLF9e:b-gvce2e) ([raw file](https://github.com/starkware-libs/blockifier/blob/e7016be1263fc9178f2f670ff309d8172361adba/crates/blockifier/src/fee/fee_utils.rs#L4)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you shouldn't need this prefix
</blockquote></details>

This function was pushed here accidentally,
please see here
https://reviewable.io/reviews/starkware-libs/blockifier/374#-
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhKfM262yMLPPIxbCA:-NRhXYmG1PrVrPtbxTOa:byr4ffv) ([raw file](https://github.com/starkware-libs/blockifier/blob/e7016be1263fc9178f2f670ff309d8172361adba/crates/blockifier/src/fee/fee_utils.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is equivalent, and more precise
</blockquote></details>

see above
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhL4xn7_OvMlIgWW2d:-NRhXa2h-K-k-OtG4fFf:byr4ffv) ([raw file](https://github.com/starkware-libs/blockifier/blob/e7016be1263fc9178f2f670ff309d8172361adba/crates/blockifier/src/fee/fee_utils.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

squash lines?
</blockquote></details>

see above

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373#-:-NRhYzY5CR7RBwGpd-t3:bnfp4nl)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/block_context.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhFAi4DJ6IjSICbRxc:-NRiKIpz3GBCRsfhihE3:b-y7poks) ([raw file](https://github.com/starkware-libs/blockifier/blob/62f12229f9ff65c73afe6ad0e17b29d46edbb496/crates/blockifier/src/block_context.rs#L16)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

this was an actual question, there may be a good reason. @noaov1 ?
also, I don't think this gas price is the ethereum gas price... or is it? if it's the starknet fee, then it won't be in wei

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373#-:-NRlNaHd0KwAOKCHnxCg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/block_context.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhFAi4DJ6IjSICbRxc:-NRlNWND2ZHQADuCNcnF:brkhkxx) ([raw file](https://github.com/starkware-libs/blockifier/blob/62f12229f9ff65c73afe6ad0e17b29d46edbb496/crates/blockifier/src/block_context.rs#L16)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I made it a float because I searched google for average gas price and the price was a float
</blockquote></details>

sababa, :lgtm: and worst case we'll change to float if needed

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/block_context.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhFAi4DJ6IjSICbRxc:-NRlRQj0A_sOBl3Kdzy4:bkffhmt) ([raw file](https://github.com/starkware-libs/blockifier/blob/62f12229f9ff65c73afe6ad0e17b29d46edbb496/crates/blockifier/src/block_context.rs#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

sababa, :lgtm: and worst case we'll change to float if needed
</blockquote></details>

In python it is an [`int`](https://github.com/starkware-industries/starkware/blob/db4a71daa240a18b613769dd8c296c5a4216657f/src/starkware/starknet/business_logic/state/state_api_objects.py#L18:~:text=gas_price%3A%20int%20%3D%20field(metadata%3Dfields.gas_price_metadata)) so I assume it's an integer.

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/block_context.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/373#-NRhFAi4DJ6IjSICbRxc:-NRxSZ_92r_NmTPubn3I:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/62f12229f9ff65c73afe6ad0e17b29d46edbb496/crates/blockifier/src/block_context.rs#L16)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

BTW: [here](https://github.com/starkware-libs/blockifier/blob/f8cd9a2d75ced39d78d92c3477fb1c658c359197/crates/native_blockifier/src/py_state_diff.rs#L89) I see that we use `u128`. Maybe it's better to do the same.
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373#-:-NRy3XTE1NuBTM3Gdzfw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/373)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
