### PR TITLE
refactor(execution): remove syscall_counter from ExecutionResources

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1424)

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1424)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @OriStarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1424#-NpoXbmF2BFGP7PVLVJM:-NpoXbmF2BFGP7PVLVJN:b-fl2po1) ([raw file](https://github.com/starkware-libs/blockifier/blob/1bc8787e5582c3580cae0d28c5755c99b36eae80/crates/blockifier/src/execution/entry_point.rs#L136)):*
> ```XML
> pub struct ExecutionResources {
>     pub vm_resources: VmExecutionResources,
> }
> ```

As you mentioned: please add a TODO to remove this struct and rename:
 `VmExecutionResources` -> `ExecutionResources`
`vm_resources` -> `resources`



_Code quote:_
```XML
pub struct ExecutionResources {
    pub vm_resources: VmExecutionResources,
}
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1424#-:-Npy_3zXEwv5TlHkhafc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1424)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @OriStarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1424#-Npz5PUu2tcFxLDOgzP-:-Npz5PUv7GFt9tXuAR69:bbix72d) ([raw file](https://github.com/starkware-libs/blockifier/blob/e5e413d64fd902eab488910093eee2fc06e72216/crates/blockifier/src/execution/entry_point.rs#L136)):*
> ```XML
> pub struct ExecutionResources {
>     pub vm_resources: VmExecutionResources,
> }
> ```

Please add a TODO to remove this struct (if you haven't added already)



_Code quote:_
```XML
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ExecutionResources {
    pub vm_resources: VmExecutionResources,
}
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1424#-:-Nq6eiNR-MLhtKDDmUln:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
