### PR TITLE
test: recompiled test contract with cairo 2.6.3

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1757)

### CODE REVIEW

**Review by noaov1 — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1757)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @orizi, and @TomerStarkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 142 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1757#-NucPz687gdE2H42BIn-:-NucPz687gdE2H42BIn0:b-wq7oy9) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b73de51f51a654eaa59fa86c8dc1f82bf20869b/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L142)):*
> ```Cairo
>         nested_library_calldata.append(a + 1);
>         nested_library_calldata.append(b + 1);
>         let _res = starknet::library_call_syscall(
> ```

Why did you move the `_` prefix?



_Code quote:_
```Cairo
let _res = starknet::library_call_syscall(
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1757)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @noaov1, and @orizi)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 142 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1757#-NucPz687gdE2H42BIn-:-Nucewza6h6ktGSfojyM:bvhhjdc) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b73de51f51a654eaa59fa86c8dc1f82bf20869b/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L142)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you move the `_` prefix?
</blockquote></details>

I get a warning with the new compiler since the variable is unused.

**Review by noaov1 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1757#-:-Nuch295DcfiEJDF5Hjs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1757)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1757#-:-NuctVPSEgvmGzj3GfEw:bnfp4nl)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @noaov1, @orizi, and @TomerStarkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1757#-:-Nuctf_w2FC4zrKobGgx:bnfp4nl)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @noaov1, @orizi, and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1757)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @noaov1, and @orizi)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 691 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1757#-NucnG680OGPxUQAY1VT:-NuctiYPD7Jr4338Ixf4:b-hfpv0l) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3be6bfb83a87a0e4baa8af01925adda18c7fc62/crates/blockifier/src/execution/entry_point_test.rs#L691)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this here?
</blockquote></details>

removed

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1757)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @orizi)

**Pull request merged**
