### PR TITLE
Implement and use AccountTransaction.fee_token_address

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/847#-NcWsn0n5SNS4S6KDGJr:-NcWsn0n5SNS4S6KDGJs:b-9gknv6) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0cfce6004b79e708a3a40a6c61a87c4954578ba/crates/blockifier/src/transaction/account_transaction.rs#L228)):*
> ```XML
>         if version == TransactionVersion(StarkFelt::from(0_u8))
>             || version == TransactionVersion(StarkFelt::from(1_u8))
>             || version == TransactionVersion(StarkFelt::from(2_u8))
> ```

not a match statement because these are not compile-time values



_Code quote:_
```XML
        let version = self.get_account_transaction_context().version;
        if version == TransactionVersion(StarkFelt::from(0_u8))
            || version == TransactionVersion(StarkFelt::from(1_u8))
            || version == TransactionVersion(StarkFelt::from(2_u8))
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @amosStarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/847#-NcX-Oal1o9npKw4bNRJ:-NcX-Oal1o9npKw4bNRK:b4aelsj) (no related file):*
[blockifier side](https://reviewable.io/reviews/starkware-industries/starkware/31559)

___

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/847#-NcWsn0n5SNS4S6KDGJr:-Ncl74A48xBCZiiM5Hn7:bbil47) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0cfce6004b79e708a3a40a6c61a87c4954578ba/crates/blockifier/src/transaction/account_transaction.rs#L228)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not a match statement because these are not compile-time values
</blockquote></details>

How about checking if `StarkFelt::try_from(version)? < 3`?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/847#-NcWsn0n5SNS4S6KDGJr:-Nd0cWGo4LED9SJxCgMH:b-vb02ww) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0ad877a88d5dd2eaea29a9e004cf197599c04c0/crates/blockifier/src/transaction/account_transaction.rs#L228)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How about checking if `StarkFelt::try_from(version)? < 3`?
</blockquote></details>

didn't work:
"required for \`TransactionVersion\` to implement \`Into<StarkFelt>\`  
required for \`StarkFelt\` to implement \`TryFrom<TransactionVersion>\`"
I rebased the PR. anything else that you would like done in this PR?

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/847#-NcWsn0n5SNS4S6KDGJr:-Nd5fd25BjgnTtmGfoQR:b1jghbe) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0ad877a88d5dd2eaea29a9e004cf197599c04c0/crates/blockifier/src/transaction/account_transaction.rs#L228)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe even:

```rs
fn fee_token_address(&self, block_context: &BlockContext) -> ContractAddress {
    let version = self.get_account_transaction_context().version;
    
    match version { 
        TransactionVersion(StarkFelt::U8(0..=2)) => block_context.deprecated_fee_token_address,
        _ => block_context.fee_token_address, 
    }
}
```

(ChatGPT's suggestion, need to make sure it works)
</blockquote></details>

That didn't work, but how about this?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/847#-NdP7e5a5V_zucCsjzKK:-NdP7e5a5V_zucCsjzKL:b7j878) ([raw file](https://github.com/starkware-libs/blockifier/blob/923598c513a84f35417fc4b7dba833a2dd088877/crates/blockifier/src/transaction/account_transaction.rs#L229)):*
> ```XML
>             block_context.deprecated_fee_token_address
>         } else {
>             assert_eq!(version_felt, StarkFelt::from(3_u8));
> ```

is this necessary?
future versions (above 3) will also use new fee token,
and we want no panics in business logic



_Code quote:_
```XML
assert_eq!(version_felt, StarkFelt::from(3_u8));
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/847#-NdP7e5a5V_zucCsjzKK:-NdPLVXN9rPmGIqxkqjk:ba3dfob) ([raw file](https://github.com/starkware-libs/blockifier/blob/923598c513a84f35417fc4b7dba833a2dd088877/crates/blockifier/src/transaction/account_transaction.rs#L229)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this necessary?
future versions (above 3) will also use new fee token,
and we want no panics in business logic
</blockquote></details>

Removed

**Review by dorimedini-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847#-:-NdPQ_o45PzK_gxiX1u8:bnfp4nl)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by giladchase — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/847#-NcWsn0n5SNS4S6KDGJr:-NdU6uwL84YV9uFo_qJR:b2ldk4w) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0ad877a88d5dd2eaea29a9e004cf197599c04c0/crates/blockifier/src/transaction/account_transaction.rs#L228)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

That didn't work, but how about this?
</blockquote></details>

Good, no need for the felt though, txVersion has `PartialOrd` as well.
```rust
 let version = self.get_account_transaction_context().version;
 if version < TransactionVersion(StarkFelt::from(3_u8)) {
```
(Ya at some point we'll need to take care of all the constant constructor for SN_API types...)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by giladchase — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/847)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Pull request closed without merging**
