### PR TITLE
Add order to events and l2 to l1 messages.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/306)

### CODE REVIEW

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/306)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/306)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/306#-NPI1WWF8-0wdUstCLyp:-NPIFRES6f_a62VxpZrs:b-8f7akw) ([raw file](https://github.com/starkware-libs/blockifier/blob/2e2c8553b3b085bfdf4265967ff1c2ecaae57f32/crates/blockifier/src/execution/entry_point.rs#L79)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps we can rename to `Event`, and the field to `event/message`?
</blockquote></details>

SN API already have a struct named `Event`. I can change the name of the fields, though.



_Code snippet:_
```XML
pub struct Event {
    pub from_address: ContractAddress,
    #[serde(flatten)]
    pub content: EventContent,
}
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/306)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls.rs` line 460 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/306#-NPI18gV99ljoCUpRe33:-NPIMXztCb7Q1Q4dmSqJ:b-upip2c) ([raw file](https://github.com/starkware-libs/blockifier/blob/2e2c8553b3b085bfdf4265967ff1c2ecaae57f32/crates/blockifier/src/execution/syscalls.rs#L460)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give this a name, so this line is easier to read. x2
</blockquote></details>

I meant defining `ordered_[event/message_to_l1]` variables.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/306)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls.rs` line 460 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/306#-NPI18gV99ljoCUpRe33:-NPIOFD3AnyC0j1PHCF6:b15orrk) ([raw file](https://github.com/starkware-libs/blockifier/blob/2e2c8553b3b085bfdf4265967ff1c2ecaae57f32/crates/blockifier/src/execution/syscalls.rs#L460)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I meant defining `ordered_[event/message_to_l1]` variables.
</blockquote></details>

Oh, I see. Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/306)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/306#-NPI1WWF8-0wdUstCLyp:-NPIeqiy7xXEs2fxfG3g:b-lnz21) ([raw file](https://github.com/starkware-libs/blockifier/blob/2e2c8553b3b085bfdf4265967ff1c2ecaae57f32/crates/blockifier/src/execution/entry_point.rs#L79)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

SN API already have a struct named `Event`. I can change the name of the fields, though.
</blockquote></details>

Oh, I see, it's of SN API. 
Then WDYT of renaming `content -> [event/message]`?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/306#-:-NPIpg2_BvzlTU_l-vCD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
