### PR TITLE
upgrade cairo-vm to 0.8.7

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1230)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1230)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @zuphitf)

___
*[`crates/blockifier/src/execution/errors.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1230#-Nl3gd4NCqWMQKLPu-5t:-Nl3gd4NCqWMQKLPu-5u:b-spub6b) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2edb7a45161d6b78bca3a41927bcc60fd5241b3/crates/blockifier/src/execution/errors.rs#L95)):*
> ```XML
>                 // description of the error; if it is unavailable, use the inner exception string.
>                 let outer_call_prefix = "Got an exception while executing a hint: Custom Hint \
>                                          Error: Error in the called contract";
> ```

import the public constant defined in the VM for this? I think it contains part of the required prefix...



_Code quote:_
```XML
                let outer_call_prefix = "Got an exception while executing a hint: Custom Hint \
                                         Error: Error in the called contract";
```

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/execution/errors.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1230#-Nl3gd4NCqWMQKLPu-5t:-Nl3nfHD5xa9JOJFVGzr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2edb7a45161d6b78bca3a41927bcc60fd5241b3/crates/blockifier/src/execution/errors.rs#L95)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

import the public constant defined in the VM for this? I think it contains part of the required prefix...
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1230)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1230#-Nl3x44B844g0pUR7yoF:-Nl3x44B844g0pUR7yoG:b-mjvy12) (no related file):*
python version bump PR?

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1230#-:-NlHufYr8pcmSRgyJLww:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
