### PR TITLE
Delete create_state, update create_test_init_data

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1271)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1271)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1271#-NlsHZwM5Dgj5fzN0r47:-NlsHZwM5Dgj5fzN0r48:bj0a2mv) ([raw file](https://github.com/starkware-libs/blockifier/blob/83f55beef64cb558e981272a72a8a678a3bb9b42/crates/blockifier/src/transaction/test_utils.rs#L125)):*
> ```XML
>         class_hash!(TEST_GRINDY_ACCOUNT_CONTRACT_CLASS_HASH_CAIRO0);
>     let test_grindy_validate_account_class_hash_cairo1 =
>         class_hash!(TEST_GRINDY_ACCOUNT_CONTRACT_CLASS_HASH_CAIRO1);
> ```

these two contracts were set here, but in all tests that use `create_test_init_data`, only `test_max_fee_limit_validate` uses the grindy account - but declares + deploys it itself.



_Code quote:_
```XML
    let test_grindy_validate_account_class_hash_cairo0 =
        class_hash!(TEST_GRINDY_ACCOUNT_CONTRACT_CLASS_HASH_CAIRO0);
    let test_grindy_validate_account_class_hash_cairo1 =
        class_hash!(TEST_GRINDY_ACCOUNT_CONTRACT_CLASS_HASH_CAIRO1);
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1271#-:-NlsUsCR7oBDO6VY6DTs:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1271#-NlsRU9kD88LyluIQPZf:-NlsRU9kD88LyluIQPZg:bzewbn1) ([raw file](https://github.com/starkware-libs/blockifier/blob/056c090904a030e8dc8fd3a9726df937dc565e21/crates/blockifier/src/transaction/account_transactions_test.rs#L261)):*
> ```XML
>     let account_tx = declare_tx(
>         declare_tx_args! {
>             class_hash: class_hash!(TEST_GRINDY_ACCOUNT_CONTRACT_CLASS_HASH_CAIRO0),
> ```

Use `FeatureContract`
It can be in a different PR. 



_Code quote:_
```XML
 class_hash!(TEST_GRINDY_ACCOUNT_CONTRACT_CLASS_HASH_CAIRO0),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1271)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1271#-NlsRU9kD88LyluIQPZf:-NlsWaSdErcoWDXoPqiA:b34udkg) ([raw file](https://github.com/starkware-libs/blockifier/blob/056c090904a030e8dc8fd3a9726df937dc565e21/crates/blockifier/src/transaction/account_transactions_test.rs#L261)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Use `FeatureContract`
It can be in a different PR.
</blockquote></details>

yes, planning on it :)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1271)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
