### PR TITLE
test: stateful_validator, skelaton

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1779)

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1779)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-NvaxyU68brQMTitpwaq:-Nw05PnP2GUgN_o2K4Wb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76abc13e9c9c0e1420fcf7311fa3a9397bf0fa0/crates/blockifier/src/blockifier/stateful_validator_test.rs#L23)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

please test with non-zero balance and non-zero max_fee, to make sure we go through balance validations
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-NvayJtl3vGGEzoNBK9L:-Nw05R5c8Jf2LZqxHRnN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76abc13e9c9c0e1420fcf7311fa3a9397bf0fa0/crates/blockifier/src/blockifier/stateful_validator_test.rs#L49)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

please test also a V3 transaction
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-NvaelWT7WnXj-0YhkaV:-Nw05XUu0PDoQPD7s_ML:b2sipui) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76abc13e9c9c0e1420fcf7311fa3a9397bf0fa0/crates/blockifier/src/blockifier/stateful_validator_test.rs#L51)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think the assignment is not needed here since the default values are the same.
</blockquote></details>

I would like to be explicit about the scenario for readability.

Partaly Done.

**Comment by ArniStarkware** [comment]
* **#1827** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1827?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1779** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1779?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1779)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @barak-b-starkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-Nwhokxe7cpNHffXbnm4:-Nwhokxe7cpNHffXbnm5:btivcbf) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb9e7f43ec8e8e142b6568ed56d0e7abf74b9363/crates/blockifier/src/blockifier/stateful_validator_test.rs#L48)):*
> ```XML
>     // TODO(Arni, 1/5/2024): Cover resource bounds in version 3 txs. Test the validator validate
>     // enough "fee" in version 3 txs.
>     let default_args = FaultyAccountTxCreatorArgs {
> ```

I think these are just tx_args, not default_args.



_Code quote:_
```XML
default_args
```
___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 73 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-NwhotJE62L96eqwJ_IT:-NwhotJE62L96eqwJ_IU:bbzrsit) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb9e7f43ec8e8e142b6568ed56d0e7abf74b9363/crates/blockifier/src/blockifier/stateful_validator_test.rs#L73)):*
> ```XML
>         state,
>         block_context,
>         Nonce(stark_felt!(1_u32)),
> ```

why 1?
if I understand correctly the validation for nonce 0 and 1 will be skipped.



_Code quote:_
```XML
1_u32
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1779)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-Nwhokxe7cpNHffXbnm4:-NwhrCPr9T68MzMVsiMT:b-89ynlo) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb9e7f43ec8e8e142b6568ed56d0e7abf74b9363/crates/blockifier/src/blockifier/stateful_validator_test.rs#L48)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think these are just tx_args, not default_args.
</blockquote></details>

Done.

These are tx_args for now. When more scenarios are covered, they will be default args. You are correct for now.
___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 73 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-NwhotJE62L96eqwJ_IT:-Nwhsudi1P880PiLZFKb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb9e7f43ec8e8e142b6568ed56d0e7abf74b9363/crates/blockifier/src/blockifier/stateful_validator_test.rs#L73)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why 1?
if I understand correctly the validation for nonce 0 and 1 will be skipped.
</blockquote></details>

Done.

**Review by Yael-Starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1779)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1779)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @barak-b-starkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-NwiEQZ1CtEie_t67pLY:-NwiEQZ2DYXFwZ8zvJxH:bzhnlfl) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d2ed416d4c490aaaa7d59b1c52c875de6153a0d/crates/blockifier/src/blockifier/stateful_validator_test.rs#L77)):*
> ```XML
>     );
> 
>     stateful_validator.perform_validations(tx, None).unwrap()
> ```

`assert!(....is_ok())`



_Code quote:_
```XML
stateful_validator.perform_validations(tx, None).unwrap()
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1779)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @dafnamatsry)

___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-NwiEQZ1CtEie_t67pLY:-NwiHTgM2hEs4n9LsxIF:bjdcu0k) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d2ed416d4c490aaaa7d59b1c52c875de6153a0d/crates/blockifier/src/blockifier/stateful_validator_test.rs#L77)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

`assert!(....is_ok())`
</blockquote></details>

Done.*

The error message presented on error with your suggestion is not verbose.
See output (I changed the test - and copied the stdout):
```
---- blockifier::stateful_validator::stateful_validator_test::test_transaction_validator::case_4_validate_declare_version_2::cairo_version_2_CairoVersion__Cairo1 stdout ----
thread 'blockifier::stateful_validator::stateful_validator_test::test_transaction_validator::case_4_validate_declare_version_2::cairo_version_2_CairoVersion__Cairo1' panicked at crates/blockifier/src/blockifier/stateful_validator_test.rs:77:5:
assertion failed: stateful_validator.perform_validations(tx, None).is_ok()
```

Post-change (with `unwrap_or_else`),
```
---- blockifier::stateful_validator::stateful_validator_test::test_transaction_validator::case_4_validate_declare_version_2::cairo_version_2_CairoVersion__Cairo1 stdout ----
thread 'blockifier::stateful_validator::stateful_validator_test::test_transaction_validator::case_4_validate_declare_version_2::cairo_version_2_CairoVersion__Cairo1' panicked at crates/blockifier/src/blockifier/stateful_validator_test.rs:79:31:
Execution failed: TransactionPreValidationError(TransactionFeeError(MaxFeeTooLow { min_fee: Fee(486000000000000), max_fee: Fee(1) }))
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1779)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @dafnamatsry)

___
*[`crates/blockifier/src/blockifier/stateful_validator_test.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-NwiEQZ1CtEie_t67pLY:-NwimuMkDuiWuvXIoN1t:b-kfindu) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d2ed416d4c490aaaa7d59b1c52c875de6153a0d/crates/blockifier/src/blockifier/stateful_validator_test.rs#L77)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.*

The error message presented on error with your suggestion is not verbose.
See output (I changed the test - and copied the stdout):
```
---- blockifier::stateful_validator::stateful_validator_test::test_transaction_validator::case_4_validate_declare_version_2::cairo_version_2_CairoVersion__Cairo1 stdout ----
thread 'blockifier::stateful_validator::stateful_validator_test::test_transaction_validator::case_4_validate_declare_version_2::cairo_version_2_CairoVersion__Cairo1' panicked at crates/blockifier/src/blockifier/stateful_validator_test.rs:77:5:
assertion failed: stateful_validator.perform_validations(tx, None).is_ok()
```

Post-change (with `unwrap_or_else`),
```
---- blockifier::stateful_validator::stateful_validator_test::test_transaction_validator::case_4_validate_declare_version_2::cairo_version_2_CairoVersion__Cairo1 stdout ----
thread 'blockifier::stateful_validator::stateful_validator_test::test_transaction_validator::case_4_validate_declare_version_2::cairo_version_2_CairoVersion__Cairo1' panicked at crates/blockifier/src/blockifier/stateful_validator_test.rs:79:31:
Execution failed: TransactionPreValidationError(TransactionFeeError(MaxFeeTooLow { min_fee: Fee(486000000000000), max_fee: Fee(1) }))
```
</blockquote></details>

Post Huddle discussion. Now prints: 
```
---- blockifier::stateful_validator::stateful_validator_test::test_transaction_validator::case_4_validate_declare_version_2::cairo_version_2_CairoVersion__Cairo1 stdout ----
thread 'blockifier::stateful_validator::stateful_validator_test::test_transaction_validator::case_4_validate_declare_version_2::cairo_version_2_CairoVersion__Cairo1' panicked at crates/blockifier/src/blockifier/stateful_validator_test.rs:78:5:
Validation failed: TransactionPreValidationError(TransactionFeeError(MaxFeeTooLow { min_fee: Fee(486000000000000), max_fee: Fee(1) }))
```

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1779)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1779#-:-NwioJSuCULJfVrrxloe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
