### PR TITLE
feat: add support for circuits

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fuZUg-5bSpbIRR6Bb:-O-fuZUg-5bSpbIRR6Bc:b5i3ao9) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/Cargo.toml#L23)):*
> ```TOML
> assert_matches = "1.5.0"
> cached = "0.44.0"
> cairo-lang-casm = "2.7.0-dev.1"
> ```

what's new here...? non-blocking



_Code quote:_
```TOML
2.7.0-dev.1
```
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 552 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-furymENVe4ISOduEJ:-O-furymENVe4ISOduEK:b-7cqfpi) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L552)):*
> ```Cairo
>         let modulus = TryInto::<_, CircuitModulus>::try_into([7, 0, 0, 0]).unwrap();
>         let _outputs =
>             match (mul,).new_inputs().next([3, 0, 0, 0]).next([6, 0, 0, 0]).done().eval(modulus) {
> ```

why the `(x,)` single-tuple? non-blocking



_Code quote:_
```Cairo
(mul,).new_inputs()
```
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 555 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fuwts4QIc1Wq1-fJL:-O-fuwts4QIc1Wq1-fJM:b-hij70q) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L555)):*
> ```Cairo
>             EvalCircuitResult::Success(outputs) => { outputs },
>             EvalCircuitResult::Failure((_, _)) => { panic!("Expected success") }
>         };
> ```

can't you just `match` without a dummy variable?
or even better, call `unwrap()` instead of asserting success by `match`?



_Suggestion:_
```Cairo
        match (mul,).new_inputs().next([3, 0, 0, 0]).next([6, 0, 0, 0]).done().eval(modulus) {
            EvalCircuitResult::Success(outputs) => { () },
            EvalCircuitResult::Failure((_, _)) => { panic!("Expected success") }
        };
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvKSy7AKmBcOX-17q:-O-fvKSy7AKmBcOX-17r:bv68oie) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/execution/entry_point_execution.rs#L167)):*
> ```XML
>         BuiltinName::range_check96,
>         BuiltinName::add_mod,
>         BuiltinName::mul_mod,
> ```

@Yonatan-Starkware PTAL?



_Code quote:_
```XML
        BuiltinName::range_check96,
        BuiltinName::add_mod,
        BuiltinName::mul_mod,
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 560 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvS7V7hwHkDNP0XF2:-O-fvS7V7hwHkDNP0XF3:b-hgt12c) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/execution/entry_point_test.rs#L560)):*
> ```XML
>     assert_eq!(
>         entry_point_call.execute_directly(&mut state).unwrap().execution,
>         CallExecution { gas_consumed: 95800, ..CallExecution::from_retdata(retdata![]) }
> ```

is there a formula for this number?
asking because upgrading the compiler and recompiling cairo1 contracts is painful because of magic numbers like these; every one needs to be manually updated to get tests to pass. if the number is a function of some other maintainable numbers / named values that would help...



_Code quote:_
```XML
gas_consumed: 95800
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fviyjBlXUH0pYrU-E:-O-fviyjBlXUH0pYrU-F:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/transaction/account_transactions_test.rs#L66)):*
> ```XML
>     // Invoke a function that changes the state and reverts.
> 
>     let tx_execution_info = run_invoke_tx(
> ```





_Suggestion:_
```XML
    // Invoke a function that changes the state and reverts.
    let tx_execution_info = run_invoke_tx(
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvper6i_XqloT0e1W:-O-fvper6i_XqloT0e1X:b-yda5ar) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/transaction/account_transactions_test.rs#L70)):*
> ```XML
>         &block_context,
>         invoke_tx_args! {
>             max_fee,
> ```

replace this with `resource_bounds`, this is a v3 transaction.
test is currently passing because resource bounds are zero, i.e. fee is ignored



_Code quote:_
```XML
max_fee,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvxPh0yZzpBdu62Lu:-O-fvxPh0yZzpBdu62Lv:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/transaction/account_transactions_test.rs#L82)):*
> ```XML
>     )
>     .unwrap();
>     eprintln!("tx_execution_info: {:?}", tx_execution_info.revert_error);
> ```

delete



_Code quote:_
```XML
eprintln!("tx_execution_info: {:?}", tx_execution_info.revert_error);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 552 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-furymENVe4ISOduEJ:-O-fy5285vIgJdh-jIdm:btvvnlu) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L552)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why the `(x,)` single-tuple? non-blocking
</blockquote></details>

yes, it's a tuple with a single value.

A circuit is defined using a tuple of outputs.
(out1, out2, out3, ...)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/entry_point_test.rs` line 560 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvS7V7hwHkDNP0XF2:-O-fyageCnESY1YHJuUw:b-v7lghf) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/execution/entry_point_test.rs#L560)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is there a formula for this number?
asking because upgrading the compiler and recompiling cairo1 contracts is painful because of magic numbers like these; every one needs to be manually updated to get tests to pass. if the number is a function of some other maintainable numbers / named values that would help...
</blockquote></details>

I can remove it and leave just the account test.

There are other places where we have such costs:
https://github.com/starkware-libs/blockifier/blob/b22fb076a7db5e0fcdd2048a6fb579b0b1d25561/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L132

You do want to make sure that those costs don't change without changes to the compiler.
maybe we need a consts file and a fix script?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvper6i_XqloT0e1W:-O-jSJ_Q25NxWj3BAf1G:b-fhkcb1) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/transaction/account_transactions_test.rs#L70)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

replace this with `resource_bounds`, this is a v3 transaction.
test is currently passing because resource bounds are zero, i.e. fee is ignored
</blockquote></details>

should I use?



_Code snippet:_
```XML
l1_resource_bounds(u64::from(!zero_bounds), DEFAULT_STRK_L1_GAS_PRICE)
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvper6i_XqloT0e1W:-O-jSNaY6bnXfj155YaV:b-1l969g) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/transaction/account_transactions_test.rs#L70)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

should I use?
</blockquote></details>

why is it called l1_resource_bounds?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvper6i_XqloT0e1W:-O-k4_jrBslJ6nItBObP:b-mpug3k) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/transaction/account_transactions_test.rs#L70)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it called l1_resource_bounds?
</blockquote></details>

because it creates a ResourceBounds instance without L2 bounds, only L1 bounds.
And please use a non-zero bound on the amount, so fee limits aren;t ignored (the average-case usage of execution layer)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O030sKID-Qx-xFDqbxq:-O030sKJ0LKKXoNONBrS:bb738d5) ([raw file](https://github.com/starkware-libs/blockifier/blob/3b999e561066b28f43340778e235f52c704718df/crates/blockifier/src/transaction/account_transactions_test.rs#L108)):*
> ```XML
> 
>     eprint!("tx_execution_info: {:?}", tx_execution_info.revert_error);
>     assert!(tx_execution_info.revert_error.is_none());
> ```

this fails with:
tx_execution_info: Some("Insufficient max L1 gas: max amount: 5537, actual used: 6175.")thread 'transaction::account_transaction::test::test_circuit' panicked at crates/blockifier/src/transaction/account_transactions_test.rs:108:5:

How am I supposed to get the resource_bound?



_Code quote:_
```XML
assert!(tx_execution_info.revert_error.is_none());
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvper6i_XqloT0e1W:-O02yzzQD5uczeL4l5-8:brn2tq0) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/transaction/account_transactions_test.rs#L70)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because it creates a ResourceBounds instance without L2 bounds, only L1 bounds.
And please use a non-zero bound on the amount, so fee limits aren;t ignored (the average-case usage of execution layer)
</blockquote></details>

What do you mean by "use a non-zero bound on the amount"?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvper6i_XqloT0e1W:-O03HluU7nn6kJCYKdvL:b-bxdbf7) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/transaction/account_transactions_test.rs#L70)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What do you mean by "use a non-zero bound on the amount"?
</blockquote></details>

if max_price_per_unit * max_amount is zero, fee is not enforced.
make sure both are strictly positive (it's fine now, using max_resource_bounds)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O03I40a-zVAhQkscDBt:-O03I40a-zVAhQkscDBu:b-av9jvs) ([raw file](https://github.com/starkware-libs/blockifier/blob/3b999e561066b28f43340778e235f52c704718df/crates/blockifier/src/transaction/account_transactions_test.rs#L81)):*
> ```XML
>     let account_tx = account_invoke_tx(invoke_tx_args! {
>         // Temporary upper bounds; just for gas estimation.
>         max_fee: Fee(MAX_FEE),
> ```

as long as the version is hard-coded to THREE this field is redundant (ignored in `account_invoke_tx`).
non-blocking in case this test will be generalized to V1 txs



_Code quote:_
```XML
max_fee: Fee(MAX_FEE),
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O03JJz94TJNtT4ZekHM:-O03JJzA-suqYNYkwlJc:becc148) ([raw file](https://github.com/starkware-libs/blockifier/blob/3b999e561066b28f43340778e235f52c704718df/crates/blockifier/src/transaction/account_transactions_test.rs#L107)):*
> ```XML
>     .unwrap();
> 
>     eprint!("tx_execution_info: {:?}", tx_execution_info.revert_error);
> ```

still delete



_Code quote:_
```XML
eprint!("tx_execution_info: {:?}", tx_execution_info.revert_error);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O030sKID-Qx-xFDqbxq:-O03IOqxBVJJFNuOoXTO:b-wnj9qu) ([raw file](https://github.com/starkware-libs/blockifier/blob/3b999e561066b28f43340778e235f52c704718df/crates/blockifier/src/transaction/account_transactions_test.rs#L108)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this fails with:
tx_execution_info: Some("Insufficient max L1 gas: max amount: 5537, actual used: 6175.")thread 'transaction::account_transaction::test::test_circuit' panicked at crates/blockifier/src/transaction/account_transactions_test.rs:108:5:

How am I supposed to get the resource_bound?
</blockquote></details>

the `estimate_minimal_gas_vector` is the *minimal* gas required without knowing how "heavy" the tx is. this won't help you.
know way to know the gas amount with actually running the tx first.
I suggest you don't test the gas amount using this method: just give a max bound and assert the hard-coded number...
maybe add a TODO to write a fix-script

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 57 files at r3, 2 of 3 files at r4, 5 of 59 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: 62 of 63 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/config.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0dWyFF6WHc-t7b5spq:-O0dWyFF6WHc-t7b5spr:brew7np) ([raw file](https://github.com/starkware-libs/blockifier/blob/d08fe8cf6fae7fd8531915d8def61cac16eabf46/crates/blockifier/src/blockifier/config.rs#L8)):*
> ```XML
>     pub fn create_for_testing() -> Self {
>         Self {
>             concurrency_config: ConcurrencyConfig { enabled: false, n_workers: 0, chunk_size: 0 },
> ```

why this change?
@noaov1 PTAL



_Code quote:_
```XML
ConcurrencyConfig { enabled: false, n_workers: 0, chunk_size: 0 }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/blockifier/config.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0dWyFF6WHc-t7b5spq:-O0dXXyW68VDD8JnAeaj:bgxmowv) ([raw file](https://github.com/starkware-libs/blockifier/blob/d08fe8cf6fae7fd8531915d8def61cac16eabf46/crates/blockifier/src/blockifier/config.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why this change?
@noaov1 PTAL
</blockquote></details>

I was unable to compile the code without it.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 57 files at r3, 1 of 3 files at r4, 5 of 59 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @ilyalesokhin-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/blockifier/config.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0dWyFF6WHc-t7b5spq:-O0mpLmS8-jNoCYO6D6a:bjdnhc8) ([raw file](https://github.com/starkware-libs/blockifier/blob/d08fe8cf6fae7fd8531915d8def61cac16eabf46/crates/blockifier/src/blockifier/config.rs#L8)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I was unable to compile the code without it.
</blockquote></details>

Can you please explain?
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvKSy7AKmBcOX-17q:-O0mqrw75zYG9d36edre:b-e98979) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/execution/entry_point_execution.rs#L167)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yonatan-Starkware PTAL?
</blockquote></details>

What is the `range_check96` builtin? We only have mul and add (sub and inverse are obtained from those?)?
Do you need to add it [here](https://github.com/starkware-libs/blockifier/blob/605b4bd52fa1c3d68dd3dfa9a63f1e9d4b57dece/crates/blockifier/src/bouncer.rs#L163) as well? 
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0mq1zc-Gk7Kuy-4VPv:-O0mq1zc-Gk7Kuy-4VPw:bnkr3wy) ([raw file](https://github.com/starkware-libs/blockifier/blob/d08fe8cf6fae7fd8531915d8def61cac16eabf46/crates/blockifier/src/transaction/account_transactions_test.rs#L54)):*
> ```XML
> 
> #[rstest]
> fn test_circuit(block_context: BlockContext, max_resource_bounds: ResourceBoundsMapping) {
> ```

Why do we need to test it in a context of an account transaction?
(just curious) 



_Code quote:_
```XML
fn test_circuit(block_context: BlockContext, max_resource_bounds: ResourceBoundsMapping) {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 555 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fuwts4QIc1Wq1-fJL:-O0dXiQ0-SgS_i9UrtDy:bt84yjc) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L555)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can't you just `match` without a dummy variable?
or even better, call `unwrap()` instead of asserting success by `match`?
</blockquote></details>

I've used output.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O-fvKSy7AKmBcOX-17q:-O0n85lOAWkPOdkMa8K3:b84wnvj) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d206fc1b97fdc4ac887b1e4b243089244815cde/crates/blockifier/src/execution/entry_point_execution.rs#L167)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is the `range_check96` builtin? We only have mul and add (sub and inverse are obtained from those?)?
Do you need to add it [here](https://github.com/starkware-libs/blockifier/blob/605b4bd52fa1c3d68dd3dfa9a63f1e9d4b57dece/crates/blockifier/src/bouncer.rs#L163) as well?
</blockquote></details>

`range_check96` is a 96bit rangecheck instead of 128.
yes, the only builtins are mul and add.

I guess I should add the builtins in the place you suggested.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0mq1zc-Gk7Kuy-4VPv:-O0n8LL1-mUnhwF5eKQD:b-we1uuk) ([raw file](https://github.com/starkware-libs/blockifier/blob/d08fe8cf6fae7fd8531915d8def61cac16eabf46/crates/blockifier/src/transaction/account_transactions_test.rs#L54)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why do we need to test it in a context of an account transaction?
(just curious)
</blockquote></details>

I don't mind removing it, @dorimedini-starkware  said that this is a better testing framework.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/blockifier/config.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0dWyFF6WHc-t7b5spq:-O0nBF8H8W3MovYm2C5Z:b-d04ism) ([raw file](https://github.com/starkware-libs/blockifier/blob/d08fe8cf6fae7fd8531915d8def61cac16eabf46/crates/blockifier/src/blockifier/config.rs#L8)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain?
</blockquote></details>

When I press run test in vscode, I get the error below.

Maybe it's a vscode only error.



_Code snippet:_
```XML
error[E0599]: no function or associated item named `create_for_testing` found for struct `ConcurrencyConfig` in the current scope
  --> crates/blockifier/src/blockifier/config.rs:7:55
   |
7  |         Self { concurrency_config: ConcurrencyConfig::create_for_testing() }
   |                                                       ^^^^^^^^^^^^^^^^^^ function or associated item not found in `ConcurrencyConfig`
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 22 of 22 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: all files reviewed, 3 unresolved discussions (waiting on @Yonatan-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: 63 of 65 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yonatan-Starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/resources/versioned_constants.json` line 560 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0nR5rZEwsaX6Zi5SNp:-O0nR5r_CRgX4nwI2Rku:b-w62t4v) ([raw file](https://github.com/starkware-libs/blockifier/blob/096d32de924ebb99d9ea8739e8eab5ddd2834d1f/crates/blockifier/resources/versioned_constants.json#L560)):*
> ```JSON
>             16,
>             100
>         ],
> ```

What do I put here and in the older versions?



_Code quote:_
```JSON
        "add_mod_builtin": [
            16,
            100
        ],
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: 63 of 69 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @noaov1, and @Yonatan-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0rBaXlBanzKaulHcKx:-O0rBaXlBanzKaulHcKy:bv7k6t7) (no related file):*
rebase over main-v0.13.2

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: 63 of 69 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @Yonatan-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0rBaXlBanzKaulHcKx:-O0rEIgCCEKyLZnCnceI:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rebase over main-v0.13.2
</blockquote></details>

Done.

___

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0mq1zc-Gk7Kuy-4VPv:-O0rEsF55fSnk-SfxcI7:b-wg6ggl) ([raw file](https://github.com/starkware-libs/blockifier/blob/d08fe8cf6fae7fd8531915d8def61cac16eabf46/crates/blockifier/src/transaction/account_transactions_test.rs#L54)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't mind removing it, @dorimedini-starkware  said that this is a better testing framework.
</blockquote></details>

@dorimedini-starkware  what test do you think we should keep?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: 63 of 69 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @noaov1, and @Yonatan-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 560 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0nR5rZEwsaX6Zi5SNp:-O0rbVlB1m1tGjPhqXrh:b-3q5ouw) ([raw file](https://github.com/starkware-libs/blockifier/blob/096d32de924ebb99d9ea8739e8eab5ddd2834d1f/crates/blockifier/resources/versioned_constants.json#L560)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What do I put here and in the older versions?
</blockquote></details>

I think in older versions (where this is unsupported) you put `[0,1]`, see `sha256_process_block_gas_cost` for another example (right @noaov1 ?)
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 50 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0rbk5W9zBODqiCPCUc:-O0rbk5W9zBODqiCPCUd:b-4u4kiw) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d0daa804a3a29354aadb46a6947c6794b17c44/crates/blockifier/src/fee/fee_utils.rs#L50)):*
> ```XML
>         "{:#?} should contain {:#?}",
>         vm_resource_fee_costs.keys(),
>         vm_resource_usage_for_fee,
> ```

what's this change?



_Code quote:_
```XML
vm_resource_usage_for_fee,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0mq1zc-Gk7Kuy-4VPv:-O0rbnzH2oXy8J3pXsey:b-jc3hy0) ([raw file](https://github.com/starkware-libs/blockifier/blob/d08fe8cf6fae7fd8531915d8def61cac16eabf46/crates/blockifier/src/transaction/account_transactions_test.rs#L54)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware  what test do you think we should keep?
</blockquote></details>

I am in favor of keeping tests that use newer and more maintainable testing infra

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/fee/fee_utils.rs` line 50 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0rbk5W9zBODqiCPCUc:-O0seAMZ-bOY4eTQpfOi:b-fvqehc) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d0daa804a3a29354aadb46a6947c6794b17c44/crates/blockifier/src/fee/fee_utils.rs#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this change?
</blockquote></details>

debugging, I'll revet it.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 22 files at r6, 4 of 4 files at r9, 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: 68 of 69 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 560 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-O0nR5rZEwsaX6Zi5SNp:-O0tpdwKDDJEFmWM0ony:b2nhswy) ([raw file](https://github.com/starkware-libs/blockifier/blob/096d32de924ebb99d9ea8739e8eab5ddd2834d1f/crates/blockifier/resources/versioned_constants.json#L560)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think in older versions (where this is unsupported) you put `[0,1]`, see `sha256_process_block_gas_cost` for another example (right @noaov1 ?)
</blockquote></details>

Yes

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: 68 of 70 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 1 of 57 files at r3, 2 of 3 files at r4, 35 of 59 files at r5, 20 of 22 files at r6, 1 of 2 files at r7, 4 of 4 files at r9, 1 of 2 files at r11, 5 of 5 files at r12, 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994#-:-O0xQD2W2lsWeBgsZNa_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1994)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
