### PR TITLE
Update the syntax on test contract.

### PR DESCRIPTION
**Pull request by ArniStarkware**
Align with the changes in:
https://github.com/starkware-libs/cairo/pull/3291

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/578)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
Note that the file `crates/blockifier/feature_contracts/cairo1/compiled/test_contract.casm.json` did not change. (Tested manually - and the file should stay the same).

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/578#-:-NXK3gaP036056UfGzJR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Comment by ArniStarkware** [comment]
We need to align the .toml file with the "correct" version.

**Comment by ArniStarkware** [comment]
The current version used in `Cargo.toml` is `cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo", rev = "e71724e4" }`. Which does not match the suggested syntax.

**Comment by ArniStarkware** [comment]
The current version used in Cargo.toml is cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo", rev = "e71724e4" }. Which does not match the suggested syntax.

**Comment by ArniStarkware** [comment]
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We need to align the .toml file with the "correct" version.
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/578)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
