### PR TITLE
Add fields to `PyCallInfo` so it will be identical to the pythonic class.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: 0 of 1 files reviewed, 2 unresolved discussions

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOnmjD76lHXqWCRtOt9:-NOnmjD76lHXqWCRtOtA:b2beekr) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L16)):*
> ```XML
>     pub validate_call_info: Option<PyCallInfo>,
>     #[pyo3(get)]
>     pub execute_call_info: Option<PyCallInfo>,
> ```

The pythonic class has an equivalent field named `call_info`. I can change it here as well but I think `execute_call_info` is more informative and it does not affect the python conversion.



_Code quote:_
```XML
  pub execute_call_info: Option<PyCallInfo>,
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOnmJfd4GQLRJzm5XF2:-NOnmJfd4GQLRJzm5XF3:b1wsakv) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L120)):*
> ```XML
> }
> 
> #[pyclass]
> ```

No sure if it is needed (same for the other substructs). I will test it.



_Code quote:_
```XML
#[pyclass]
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOnmjD76lHXqWCRtOt9:-NOntPGz7DH-v1fPtDXi:b-412ujz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L16)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The pythonic class has an equivalent field named `call_info`. I can change it here as well but I think `execute_call_info` is more informative and it does not affect the python conversion.
</blockquote></details>

I agree. :)
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOntYpi8bh5lMXFTp0E:-NOntYpi8bh5lMXFTp0F:b-u4o3rz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L40)):*
> ```XML
> #[derive(Clone)]
> pub struct PyCallInfo {
>     pub caller_address: PyFelt,
> ```

Reorder accordingly in the call.



_Suggestion:_
```XML
    // Call params.
    pub caller_address: PyFelt,
    pub contract_address: PyFelt,
    pub class_hash: Option<PyFelt>,
    pub entry_point_selector: PyFelt,
    pub entry_point_type: usize,
    pub calldata: Vec<PyFelt>,
    
    // Call results.
    pub gas_consumed: PyFelt,  // Currently not in use.
    pub failure_flag: PyFelt,  // Currently not in use.
    pub retdata: Vec<PyFelt>,
    pub execution_resources: PyExecutionResources,
    pub events: Vec<PyEvent>,
    pub l2_to_l1_messages: Vec<PyL2ToL1Message>,
    
    // Internal calls invoked by this call.
    pub internal_calls: Vec<PyCallInfo>,
    
    // Information kept for following flows (fee, OS).
    pub storage_read_values: Vec<PyFelt>,
    pub accessed_storage_keys: HashSet<PyFelt>,
    
    // Deprecated fields; maintained for backward compatibility to Python.
    pub call_type: usize,
    pub code_address: Option<PyFelt>,
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOnuBLC7T0CX2QASz51:-NOnuBLC7T0CX2QASz52:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L66)):*
> ```XML
>         Self {
>             caller_address: PyFelt::from(call.caller_address),
>             call_type: 0, // CALL
> ```





_Suggestion:_
```XML
// CallType::CALL.
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOnuROA2MR5BdJu6dz_:-NOnuROA2MR5BdJu6dza:bmzk55u) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L83)):*
> ```XML
>                 .map(PyL2ToL1Message::from)
>                 .collect(),
>             storage_read_values: vec![],
> ```

This will be filled next PR?



_Code quote:_
```XML
            storage_read_values: vec![],
            accessed_storage_keys: HashSet::new(),
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOnmJfd4GQLRJzm5XF2:-NOnuOMfBOXwcz6qPIa0:b-iv9kwc) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L120)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No sure if it is needed (same for the other substructs). I will test it.
</blockquote></details>

Why is `Clone` needed?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOnuROA2MR5BdJu6dz_:-NOnuet_2nOT5aWPCEM5:b-izdfrj) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L83)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This will be filled next PR?
</blockquote></details>

Yes, after I will add it to the rust structs.
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOnmJfd4GQLRJzm5XF2:-NOnuu3k-WmVCVGwIitk:b-j5u3dk) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L120)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is `Clone` needed?
</blockquote></details>

For get the field type must implement both `IntoPy<PyObject>` and `Clone` so I needed it for `PyCallInfo` which implies needing it for `PyExecutionResources` as well.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOntYpi8bh5lMXFTp0E:-NOo6Z7G759gt8JYlova:b-s7ep5m) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L40)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Reorder accordingly in the call.
</blockquote></details>

WDYM BY in the call?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOntYpi8bh5lMXFTp0E:-NOpGDlv-jC0eC6XPoTJ:bdxfs8w) ([raw file](https://github.com/starkware-libs/blockifier/blob/e688264b4bcc2a09a1b2de510bbaefcef170ed86/crates/native_blockifier/src/py_transaction_execution_info.rs#L40)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM BY in the call?
</blockquote></details>

Arrange the fields when calling the c-tor, in the order they are in the struct. You almost did that. :)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/293#-NOrXZLMDAqDMqCgnZQc:-NOrXZLMDAqDMqCgnZQd:be9kskj) ([raw file](https://github.com/starkware-libs/blockifier/blob/ccb491b82b2edf96221f12d1e1fd14d008cc69e6/crates/native_blockifier/src/py_transaction_execution_info.rs#L92)):*
> ```XML
>         Self {
>             caller_address: PyFelt::from(call.caller_address),
>             call_type: 0, // CallType::CALL.
> ```

Move above `code_address`.



_Code quote:_
```XML
call_type: 0, // CallType::CALL.
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293#-:-NOsJQ1p2RnB_hPYOTeZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
