### PR TITLE
add recursive functions to cairo1 test_contract and add cairo_version parameter into create_test_init_data

### PR DESCRIPTION
**Pull request by zuphitf**
…

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1282)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1282)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 362 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1282#-NlyNrWqEHJG1yBOnIif:-NlyNrWqEHJG1yBOnIig:b-ip3csk) ([raw file](https://github.com/starkware-libs/blockifier/blob/fabfff08d9ce2efccb3b1d12b0f388b76117c50f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L362)):*
> ```Cairo
>     fn recursive_fail(ref self: ContractState, depth: felt252) {
>         if depth == 0 {
>             panic_with_felt252('panic');
> ```

better be clear, panic is very general



_Suggestion:_
```Cairo
'recursive fail'
```

**Comment by zuphitf** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 362 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1282#-NlyNrWqEHJG1yBOnIif:-NlyRvRs52lS0ICqNuQB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fabfff08d9ce2efccb3b1d12b0f388b76117c50f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L362)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

better be clear, panic is very general
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1282)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 362 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1282#-NlyNrWqEHJG1yBOnIif:-NlyYFNwEQ2mfgBAcT_4:b-dkgejg) ([raw file](https://github.com/starkware-libs/blockifier/blob/fabfff08d9ce2efccb3b1d12b0f388b76117c50f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L362)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Done.
</blockquote></details>

recompile?

**Comment by zuphitf** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 362 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1282#-NlyNrWqEHJG1yBOnIif:-Nm-XStP-jxu8WEMSz4-:b-7jzv7t) ([raw file](https://github.com/starkware-libs/blockifier/blob/fabfff08d9ce2efccb3b1d12b0f388b76117c50f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L362)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

recompile?
</blockquote></details>

right

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1282#-:-Nm0K9MT00YvrAMv2hf8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
