### PR TITLE
test(concurrency): test scenarios of validate_reads with unvalid reads

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)

### CODE REVIEW

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 350 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-Nzcc7UKAQPOcPIHErYa:-Nzcc7UL5soFC3ZxonvX:b6uc3r) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4f43f5d64b1dc6d185d5593cb06e42cf6b5f935/crates/blockifier/src/concurrency/versioned_state_test.rs#L350)):*
> ```XML
>             declared_contracts: HashMap::from([(class_hash, true)]),
>             ..Default::default()
>         },
> ```

It's the same test as the one below. (7, 8)

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 350 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-Nzcc7UKAQPOcPIHErYa:-Nzcg9KUDn7aRuJwmvlp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4f43f5d64b1dc6d185d5593cb06e42cf6b5f935/crates/blockifier/src/concurrency/versioned_state_test.rs#L350)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

It's the same test as the one below. (7, 8)
</blockquote></details>

Done.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 365 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-NzciWND45AHW9TJUrhD:-NzciWND45AHW9TJUrhE:b-eltdvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/558c1a432314a04f6852964ca1c627129ab939ec/crates/blockifier/src/concurrency/versioned_state_test.rs#L365)):*
> ```XML
>         TransactionalState::create_transactional(&mut version_state_proxy_5);
> 
>     transactional_state_5.get_class_hash_at(contract_address).unwrap();
> ```

This line is to get the contract_address in the read set of transactional_state_5?

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 365 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-NzciWND45AHW9TJUrhD:-NzcpRsI4_n3XPQtiQ1J:b-tuik1l) ([raw file](https://github.com/starkware-libs/blockifier/blob/558c1a432314a04f6852964ca1c627129ab939ec/crates/blockifier/src/concurrency/versioned_state_test.rs#L365)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This line is to get the contract_address in the read set of transactional_state_5?
</blockquote></details>

Exactly

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-:-NzhpbUR9On9jGW2EKY9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 331 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-NzxLbP37QabSfykqCMs:-NzxLbP37QabSfykqCMt:bu2tnnh) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ff9a45e8b306fcb3f0bf4926a0f399cfe5f4335/crates/blockifier/src/concurrency/versioned_state_test.rs#L331)):*
> ```XML
>     contract_address: ContractAddress,
>     safe_versioned_state: ThreadSafeVersionedState<CachedState<DictStateReader>>,
> ) {
> ```

Can you try applying different cases with `arg1` for the state maps and `arg2` for the contract class mapping and maintain the body of the test something like:
```
let proxy_for_writing = safe_versioned_State.pin_version(0);
let proxy_for_reading = safe_versioned_State.pin_version(1);
let transactional_state_for_reading = ...;

proxy_for_writing.state().apply_writes(0, &arg1, &arg2);
assert(!proxy_for_reading.validate_reads(&state_maps);
```



_Suggestion:_
```XML
#[rstest]
#[case::get_storage_at(...)]
#[case::get_nonce(...)]
.
.
.
fn test_false_validate_reads(
    contract_address: ContractAddress,
    safe_versioned_state: ThreadSafeVersionedState<CachedState<DictStateReader>>,
    #[case] arg1,
    #[case] arg2,
) {
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 331 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-NzxLbP37QabSfykqCMs:-O-04vli-_jZc7CNmztp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ff9a45e8b306fcb3f0bf4926a0f399cfe5f4335/crates/blockifier/src/concurrency/versioned_state_test.rs#L331)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Can you try applying different cases with `arg1` for the state maps and `arg2` for the contract class mapping and maintain the body of the test something like:
```
let proxy_for_writing = safe_versioned_State.pin_version(0);
let proxy_for_reading = safe_versioned_State.pin_version(1);
let transactional_state_for_reading = ...;

proxy_for_writing.state().apply_writes(0, &arg1, &arg2);
assert(!proxy_for_reading.validate_reads(&state_maps);
```
</blockquote></details>

Done.

**Review by meship-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 328 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-O-0KuCB2smvs9lYCm9P:-O-0KuCB2smvs9lYCm9Q:b-gm78tw) ([raw file](https://github.com/starkware-libs/blockifier/blob/61f2af1e109b2d5eaa4c2def38aea2ae8368f091/crates/blockifier/src/concurrency/versioned_state_test.rs#L328)):*
> ```XML
> 
> #[rstest]
> #[case::check_declared_contracts(
> ```

In all cases:



_Suggestion:_
```XML
#[case::declared_contracts(
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 372 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-O-0Lhgz8FjC3DTPxYFH:-O-0Lhgz8FjC3DTPxYFI:b-r5kxof) ([raw file](https://github.com/starkware-libs/blockifier/blob/61f2af1e109b2d5eaa4c2def38aea2ae8368f091/crates/blockifier/src/concurrency/versioned_state_test.rs#L372)):*
> ```XML
>     }
> )]
> fn test_false_validate_reads(
> ```

What about the "compiled contract classes validation"? Can it be added as another case here? Maybe adding another test for that?



_Code quote:_
```XML
fn test_false_validate_reads(
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 328 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-O-0KuCB2smvs9lYCm9P:-O-F_0Lw96F-H-zn0dcH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/61f2af1e109b2d5eaa4c2def38aea2ae8368f091/crates/blockifier/src/concurrency/versioned_state_test.rs#L328)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

In all cases:
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 372 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-O-0Lhgz8FjC3DTPxYFH:-O-F_1zM9VRa0PsuCcz9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/61f2af1e109b2d5eaa4c2def38aea2ae8368f091/crates/blockifier/src/concurrency/versioned_state_test.rs#L372)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

What about the "compiled contract classes validation"? Can it be added as another case here? Maybe adding another test for that?
</blockquote></details>

Done.

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 381 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-O-Fg-kP6Wug4YDZ4E8Z:-O-Fg-kQ2PkbZ3kGdNm7:b-vr7uee) ([raw file](https://github.com/starkware-libs/blockifier/blob/9916468a633d616ab3c781688e1413f13be9d07e/crates/blockifier/src/concurrency/versioned_state_test.rs#L381)):*
> ```XML
>         ..Default::default()
>     }
> )]
> ```

I would expect this case to panic for the assertion:
```
            assert_eq!(
                is_declared,
                self.compiled_contract_classes.read(tx_index + 1, class_hash).is_some()
            );
```
what do I miss here?



_Code quote:_
```XML
#[case::declared_contracts(
    StateMaps {
        declared_contracts: HashMap::from([(class_hash!(1_u8), false)]),
        ..Default::default()
    },
    StateMaps {
        declared_contracts: HashMap::from([(class_hash!(1_u8), true)]),
        ..Default::default()
    }
)]
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 381 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-O-Fg-kP6Wug4YDZ4E8Z:-O-GOWdYAWJ5y5k0LCm8:buzfn09) ([raw file](https://github.com/starkware-libs/blockifier/blob/9916468a633d616ab3c781688e1413f13be9d07e/crates/blockifier/src/concurrency/versioned_state_test.rs#L381)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I would expect this case to panic for the assertion:
```
            assert_eq!(
                is_declared,
                self.compiled_contract_classes.read(tx_index + 1, class_hash).is_some()
            );
```
what do I miss here?
</blockquote></details>

The code will not panic because the state is ok.

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-O-H3Y6W6ZXQPQpVAiFm):*
Two commits by mistake?



_Code quote:_
```
- 50f7c2a: fix(concurrency): remove compiled_class_hashes check from validate_reads

- c4f43f5: test(concurrency): test scenarios of validate_reads with unvalid reads
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-O-H3Y6W6ZXQPQpVAiFm):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Two commits by mistake?
</blockquote></details>

I don't see 2 commits.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1955#-:-O-Uns1u0T-6umGlFPxR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Pull request merged**
