### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/317)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/317)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`scripts/build_wheels.sh` line 17 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/317#-NPXjnpV4mq8413adAm8:-NPXjnpV4mq8413adAm9:bbfrjvh) ([raw file](https://github.com/starkware-libs/blockifier/blob/5da9640efef2901cfb6e598b2bc3942c058900d8/scripts/build_wheels.sh#L17)):*
> ```Shell
> source "$HOME/.cargo/env"
> rustup toolchain install nightly-2022-11-03
> rustup override set nightly-2022-11-03
> ```

@giladchase should I merge this?
and how will it pass CI? Do I need to edit the workflow?



_Code quote:_
```Shell
# Override build to nightly version for experimental features.
source "$HOME/.cargo/env"
rustup toolchain install nightly-2022-11-03
rustup override set nightly-2022-11-03
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/317)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`scripts/build_wheels.sh` line 17 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/317#-NPXjnpV4mq8413adAm8:-NPXoIh2AHfzGooxsoCM:b-afz6ga) ([raw file](https://github.com/starkware-libs/blockifier/blob/5da9640efef2901cfb6e598b2bc3942c058900d8/scripts/build_wheels.sh#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@giladchase should I merge this?
and how will it pass CI? Do I need to edit the workflow?
</blockquote></details>

waitaminute
the workflows are already set to `nightly-2022-11-3`
WTF?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/317)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`scripts/build_wheels.sh` line 17 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/317#-NPXjnpV4mq8413adAm8:-NPXqBoZ8wigeI4dFyY5:buin92n) ([raw file](https://github.com/starkware-libs/blockifier/blob/5da9640efef2901cfb6e598b2bc3942c058900d8/scripts/build_wheels.sh#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

waitaminute
the workflows are already set to `nightly-2022-11-3`
WTF?
</blockquote></details>

"fixed" CI, original question still stands

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/317)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/lib.rs` line 2 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/317#-NPXsm741noSz-1mxZpk:-NPXsm741noSz-1mxZpl:bmgugbm) ([raw file](https://github.com/starkware-libs/blockifier/blob/e5503e57ee05a8c6219d491fa9a3e141e7099b32/crates/native_blockifier/src/lib.rs#L2)):*
> ```XML
> #![feature(error_generic_member_access)]
> #![feature(provide_any)]
> ```

Can you add a short comment on what each one of those features give?



_Code quote:_
```XML
#![feature(error_generic_member_access)]
#![feature(provide_any)]
```

**Pull request closed without merging**
