### PR TITLE
chore: add a config struct for transfers generator

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945)

### CODE REVIEW

**Review by OriStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzTPIyI6swOJWjxwZRX:-NzTPIyI6swOJWjxwZRY:b-hvii4k) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b081146bc616f882353611b5bfd6d63707a22cc/crates/blockifier/src/test_utils/transfers_generator.rs#L41)):*
> ```XML
>     pub transaction_version: TransactionVersion,
>     pub recipient_iterator_kind: RecipientIteratorKind,
> ```

Can you remove this empty line?
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzTOo3t7u0rdkHXbIjN:-NzTOo3t7u0rdkHXbIjO:b-q1m39p) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b081146bc616f882353611b5bfd6d63707a22cc/crates/blockifier/src/test_utils/transfers_generator.rs#L123)):*
> ```XML
>         let chain_info = block_context.chain_info().clone();
>         let state =
>             test_state(&chain_info, BALANCE * 1000, &[(account_contract, config.n_accounts)]);
> ```

Shouldn't BALANCE be in the config as well?



_Code quote:_
```XML
BALANCE
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzTPIyI6swOJWjxwZRX:-NzTgW_KCTdmS57hbT0F:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b081146bc616f882353611b5bfd6d63707a22cc/crates/blockifier/src/test_utils/transfers_generator.rs#L41)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Can you remove this empty line?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzTOo3t7u0rdkHXbIjN:-NzTfQC46IV-30iE0_RU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b081146bc616f882353611b5bfd6d63707a22cc/crates/blockifier/src/test_utils/transfers_generator.rs#L123)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Shouldn't BALANCE be in the config as well?
</blockquote></details>

Done.

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-:-NzWw1vtE_rcGCJAg7zC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by OriStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Comment by avi-starkware** [comment]
+reviewer:@barak-b-starkware

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945)* status: all files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-Nzvg29j-C4DwTopygbP:-Nzvg29j-C4DwTopygbQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L36)):*
> ```XML
>     pub n_accounts: u16,
>     pub balance: u128,
>     pub max_fee: u128,
> ```





_Suggestion:_
```XML
    pub balance: SierraU256,
    pub max_fee: SierraU256,
```
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzvgLVc1vV9uAW80YuX:-NzvgLVd53Z0BQTJcTGU:bpt74m3) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L41)):*
> ```XML
>     pub charge_fee: bool,
>     pub transaction_version: TransactionVersion,
>     pub recipient_iterator_kind: RecipientIteratorKind,
> ```

Non-blocking but if you agree you can add a TODO for that since it's a different task of refactoring.



_Suggestion:_
```XML
pub recipient_iterator_type: RecipientIteratorType,
```
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 43 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-Nzvfxkb9_3jsESvVlKR:-NzvfxkcEx4Yu_GIks5D:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L43)):*
> ```XML
>     pub recipient_iterator_kind: RecipientIteratorKind,
>     // Concurrency config.
>     pub concurrency_mode: bool,
> ```





_Suggestion:_
```XML
    pub concurrency_mode: bool,
```
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzvgvxfEbVWCJHyVKqc:-NzvgvxfEbVWCJHyVKqd:b-q3hgfi) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L61)):*
> ```XML
>             concurrency_mode: CONCURRENCY_MODE,
>             n_workers: N_WORKERS,
>             chunk_size: CHUNK_SIZE,
> ```

WDYT sharing code with `ConcurrencyConfig`?



_Suggestion:_
```XML
            concurrency_config: ConcurrencyConfig::default(),
```
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzvjNpd1RKyoQM01CqD:-NzvjNpd1RKyoQM01CqE:b2vdw8a) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L115)):*
> ```XML
>     recipient_iterator: Box<dyn Iterator<Item = ContractAddress>>,
>     sender_index: usize,
>     config: TransfersGeneratorConfig,
> ```

What is the "line" that separates config members from other members?



_Code quote:_
```XML
    account_addresses: Vec<ContractAddress>,
    chain_info: ChainInfo,
    executor: TransactionExecutor<DictStateReader>,
    nonce_manager: NonceManager,
    recipient_iterator: Box<dyn Iterator<Item = ContractAddress>>,
    sender_index: usize,
    config: TransfersGeneratorConfig,
```
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-Nzvhb_U1U-0tU6QadTs:-Nzvhb_U1U-0tU6QadTt:b8u2lr9) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L120)):*
> ```XML
> impl TransfersGenerator {
>     pub fn new(config: TransfersGeneratorConfig) -> Self {
>         let account_contract = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo0);
> ```

WDYT about?



_Suggestion:_
```XML
let account_contract = FeatureContract::AccountWithoutValidations(config.cairo_version);
```
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 159 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-Nzviurb9z7ILngcbrPK:-Nzviurb9z7ILngcbrPL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L159)):*
> ```XML
>                         index: first_recipient_index,
>                     })
>                 }
> ```





_Suggestion:_
```XML
                RecipientIteratorKind::RoundRobin => {
                    // Explaining comment?
                    let first_recipient_index = 1;
                    Box::new(RoundRobinRecipientIterator {
                        account_addresses: account_addresses.clone(),
                        index: first_recipient_index,
                    })
                }
                RecipientIteratorKind::DisjointFromSenders => {
                    // Explaining comment?
                    let first_recipient_index = 0;
                    // Explaining comment?
                    let account_addresses = (config.n_accounts..2 * config.n_accounts)
                        .map(|instance_id| account_contract.get_instance_address(instance_id))
                        .collect::<Vec<_>>();
                    Box::new(RoundRobinRecipientIterator {
                        account_addresses,
                        index: first_recipient_index,
                    })
                }
```

**Review by OriStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945)* status: all files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzvgvxfEbVWCJHyVKqc:-Nzw4cOlEbPwYCyYgauo:b-s5vwbe) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L61)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT sharing code with `ConcurrencyConfig`?
</blockquote></details>

Done.

I think it is best to have the default for the transfers generator be defined in the constants of these files and not be the default of the general ConcurrencyConfig. This way, it is easier to play around with these numbers when we use the benchmark.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-Nzvg29j-C4DwTopygbP:-Nzw764XDalK4nmYNAd4:bl9w88z) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L36)):*
> ```XML
>     pub n_accounts: u16,
>     pub balance: u128,
>     pub max_fee: u128,
> ```

The balance and the fee are taken as default from test_utils. They both have a type of `u128` and this is the type used for balances and fees everywhere in the code. Moreover, the type in the corresponding sierra code that uses balances / charges fees is `u128` (balances are represented by two `u128` values in fact - high and low - but we don't need a balance of more than 2^128 here).
`SierraU256` is only used in `secp.rs`, so I think `u128` is better suited here.
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzvgLVc1vV9uAW80YuX:-Nzw8JSTC1WmUTUK5qZk:bzbokw7) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L41)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Non-blocking but if you agree you can add a TODO for that since it's a different task of refactoring.
</blockquote></details>

Done.

I originally used "kind" and not "type" since I thought "type" might imply it is a variable type.
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 43 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-Nzvfxkb9_3jsESvVlKR:-Nzw4bUg5nd09DtlldTI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L43)):*
> ```XML
>     pub recipient_iterator_kind: RecipientIteratorKind,
>     // Concurrency config.
>     pub concurrency_mode: bool,
> ```

Done.
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzvjNpd1RKyoQM01CqD:-Nzw5ZC2-wB9Vr5C22yZ:bj9o5hd) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L115)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

What is the "line" that separates config members from other members?
</blockquote></details>

Everything that is not in the config is essentially derived from the config at initialization.
Note that the starting `sender_index` doesn't matter. We need it as a member of the struct to keep track of who the next sender should be, but since we loop around senders, any sender we start with would be symmetric and produce similar behavior.
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-Nzvhb_U1U-0tU6QadTs:-Nzw74Dv9UH7oSNanUPq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L120)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT about?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 159 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-Nzviurb9z7ILngcbrPK:-NzwAi614jQZPs0lVxQw:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L159)):*
> ```XML
>                         index: first_recipient_index,
>                     })
>                 }
> ```

Done.

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzvjNpd1RKyoQM01CqD:-O-0yx2b6037yZtzYfyE:bfvlhzg) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L115)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Everything that is not in the config is essentially derived from the config at initialization.
Note that the starting `sender_index` doesn't matter. We need it as a member of the struct to keep track of who the next sender should be, but since we loop around senders, any sender we start with would be symmetric and produce similar behavior.
</blockquote></details>

If all are derived from the config, either expand or push them into it.
If the `sender_index` is redundant, how about removing it and using the default values or something similar?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-NzvjNpd1RKyoQM01CqD:-O-1RStNDr0_VStnuqtF:b-sy8itz) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4d7aa22acf66e230d9a7b8fb1375081a749a6b7/crates/blockifier/src/test_utils/transfers_generator.rs#L115)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I can move it to the refactor PR if you want to merge it, LMK :pray:
</blockquote></details>

In the current PR, I need the `sender_index` field to keep track of the current sender. Note that the TransfersGenerator struct persists between calls to `execute_transfers` and the next sender in a new call to `execute_transfers` is the sender that follows the last sender in the previous call to `execute_transfers`. Therefore, we need to always keep track of the current sender_index and this is done via the `sender_index` field in the `TransfersGenerator` struct.

The starting value always defaults to 0 currently.

There is no reason to change it in the refactor PR, since there we keep track of the sender via `sender_iterator`.

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945#-:-O1Gz6NrAfJ_rXL-3RAl:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by avi-starkware — COMMENTED** [review]
> Dismissed @barak-b-starkware from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1945)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Pull request merged**
