### PR TITLE
Add updated version of estimate_casm_hash_computation_resources().

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)* status: all files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnYYjt-4YSoNr7gMZyR:-NnYYjt-4YSoNr7gMZyS:b-vr19r3) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L188)):*
> ```XML
> }
> 
> // TODO(lior): Remove this and use `NestedIntList` from the cairo compiler repo once available.
> ```

Do we need a release for that?



_Code quote:_
```XML
once available.
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnY_3JG11bsY2_xcVRl:-NnY_3JHCmpslIFavRDl:b-4regwh) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L217)):*
> ```XML
>                 n_memory_holes: 0,
>                 builtin_instance_counter: HashMap::from([(POSEIDON_BUILTIN_NAME.to_string(), 11)]),
>             };
> ```

Where to these initial resources come from? Consider adding  short comment.



_Code quote:_
```XML
            let mut execution_resources = VmExecutionResources {
                n_steps: 491,
                n_memory_holes: 0,
                builtin_instance_counter: HashMap::from([(POSEIDON_BUILTIN_NAME.to_string(), 11)]),
            };
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnY_puS6GY1rbCMZ2HF:-NnY_puT9emC8pOWGr0-:b-ttfbh1) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L226)):*
> ```XML
>                 let NestedIntList::Leaf(length) = segment else {
>                     panic!(
>                         "Estimating hash cost is only supported for segmentation depth at most 1."
> ```

Are you planning to extend this logic with your DS?



_Code quote:_
```XML
Estimating hash cost is only supported for segmentation depth at most 1.
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnYZNgN2I0inF5wHVm8:-NnYZNgN2I0inF5wHVm9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L238)):*
> ```XML
> 
> /// Returns the VM resources required for running `poseidon_hash_many` in the Starknet OS.
> fn poseidon_hash_many_cost(data_len: usize) -> VmExecutionResources {
> ```





_Suggestion:_
```XML
data_length
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnYYjt-4YSoNr7gMZyR:-NnYfzb23CIsKKYZvqSF:b2nign6) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L188)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we need a release for that?
</blockquote></details>

yes
___
*[`crates/blockifier/src/execution/contract_class.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnY_3JG11bsY2_xcVRl:-NnYhCXsBSR6YSwr_O01:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L217)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where to these initial resources come from? Consider adding  short comment.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnY_puS6GY1rbCMZ2HF:-NnYgEDYBXH51v0SAEgW:b-y6evd9) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L226)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are you planning to extend this logic with your DS?
</blockquote></details>

What's DS?
Currently, we don't use depth > 1 (we split to functions, but don't do subfunction segmentation). If this changes, the code here will need to change, but this won't happen soon.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnYZNgN2I0inF5wHVm8:-NnYhB2b-4UPs77E-c_P:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L238)):*
> ```XML
> 
> /// Returns the VM resources required for running `poseidon_hash_many` in the Starknet OS.
> fn poseidon_hash_many_cost(data_len: usize) -> VmExecutionResources {
> ```

Done.

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnY_3JG11bsY2_xcVRl:-NnYmbLE1Dik7OkIDpry:b-nt5lo4) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L217)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I feel it's not yet clear; what's the first cost of _besides_ the segments' cost?
___
*[`crates/blockifier/src/execution/contract_class.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnY_puS6GY1rbCMZ2HF:-NnYmnWx6s2bBX21Oeh1:b-9nuwwh) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L226)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What's DS?
Currently, we don't use depth > 1 (we split to functions, but don't do subfunction segmentation). If this changes, the code here will need to change, but this won't happen soon.
</blockquote></details>

Data structure.
Then I don't understand this `match`. :(
___
*[`crates/blockifier/src/execution/contract_class.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnYmXVZ9JdWGJlqg--l:-NnYmXVZ9JdWGJlqg--m:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7c54d823725ad3000821fbb4bef977ffd768693b/crates/blockifier/src/execution/contract_class.rs#L202)):*
> ```XML
>     bytecode_segment_lengths: NestedIntList,
> ) -> VmExecutionResources {
>     // The constants in this function were computed by running the Casm code on a few configurations
> ```





_Suggestion:_
```XML
values
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnY_puS6GY1rbCMZ2HF:-NnYupjg6x5xJBW8VKmW:buub7ny) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L226)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Data structure.
Then I don't understand this `match`. :(
</blockquote></details>

Depth 0 - No segmentation at all
Depth 1 - Segmentation by functions
Depth 2 - Subfunction segmentation

The code supports the first two (the first one is important for backward compatibility)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnY_3JG11bsY2_xcVRl:-NnYv53p3v4fznr90ato:b-8vkll5) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L217)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I feel it's not yet clear; what's the first cost of _besides_ the segments' cost?
</blockquote></details>

For example the cost of hashing the entry points and other fields in the Casm class. It's chosen according to the way the python test is written now.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnYmXVZ9JdWGJlqg--l:-NnZCmZNAO9obwduyk_R:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7c54d823725ad3000821fbb4bef977ffd768693b/crates/blockifier/src/execution/contract_class.rs#L202)):*
> ```XML
>     bytecode_segment_lengths: NestedIntList,
> ) -> VmExecutionResources {
>     // The constants in this function were computed by running the Casm code on a few configurations
> ```

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnY_puS6GY1rbCMZ2HF:-NnZX_NH8R7Xsp1icNYA:bezh6m) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L226)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Depth 0 - No segmentation at all
Depth 1 - Segmentation by functions
Depth 2 - Subfunction segmentation

The code supports the first two (the first one is important for backward compatibility)
</blockquote></details>

Consider shortly documenting this.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-:-NnZXcChAUR2koD-W07z:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @Yoni-Starkware)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-NnY_puS6GY1rbCMZ2HF:-NnZfgD3A-L6Mx159gfv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dfd31a7f6c41809aa7dc67c93e6bb9d23be1faf/crates/blockifier/src/execution/contract_class.rs#L226)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider shortly documenting this.
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314#-:-NnZhP3sDDe54ZZ95kZf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1314)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
