### PR TITLE
feat(execution): implement execute_chunk naively

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841)

### CODE REVIEW

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841)* status: all files reviewed, 10 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoPCZe5qGTUhjB2R0A:-NwoPCZe5qGTUhjB2R0B:b-75fpln) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b87bdce1f5ef3e0648874cc1de8a92cedc8bc1e/crates/blockifier/src/bouncer.rs#L324)):*
> ```XML
> 
>     Ok(patricia_update_resources)
> }
> ```

Why was it so in the first place?
(I agree that it doesn't look like it's needed)



_Code quote:_
```XML
pub fn get_particia_update_resources(
    block_visited_storage_entries: &HashSet<StorageEntry>,
    tx_visited_storage_entries: &HashSet<StorageEntry>,
) -> TransactionExecutorResult<ExecutionResources> {
    let newly_visited_storage_entries: HashSet<&StorageEntry> =
        tx_visited_storage_entries.difference(block_visited_storage_entries).collect();
    let n_newly_visited_leaves = newly_visited_storage_entries.len();

    const TREE_HEIGHT_UPPER_BOUND: usize = 24;
    let n_updates = n_newly_visited_leaves * TREE_HEIGHT_UPPER_BOUND;

    let patricia_update_resources = ExecutionResources {
        // TODO(Yoni, 1/5/2024): re-estimate this.
        n_steps: 32 * n_updates,
        // For each Patricia update there are two hash calculations.
        builtin_instance_counter: HashMap::from([(HASH_BUILTIN_NAME.to_string(), 2 * n_updates)]),
        n_memory_holes: 0,
    };

    Ok(patricia_update_resources)
}
```
___
*[`crates/blockifier/src/test_utils.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoTINU5_i9Dvnn7uJJ:-NwoTINU5_i9Dvnn7uJK:btm7zz7) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/test_utils.rs#L121)):*
> ```XML
> // TODO(Yoni, 1/1/2025): move to SN API.
> /// A utility macro to create a [`Nonce`] from a hex string / unsigned integer representation.
> #[cfg(any(feature = "testing", test))]
> ```

Why both?
If you want to move it to SN_API, WDYT about making it not so easy to use in our repo?



_Suggestion:_
```XML
#[cfg(test)]
```
___
*[`crates/blockifier/src/test_utils.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoTBhW2peZ_SWbMu1-:-NwoTBhW2peZ_SWbMu10:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/test_utils.rs#L127)):*
> ```XML
>         Nonce(StarkHash::try_from($s).unwrap())
>     };
> }
> ```





_Suggestion:_
```XML
macro_rules! nonce {
    ($s:expr) => {
        starknet_api::core::Nonce(StarkHash::try_from($s).unwrap())
    };
}
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoH8K45j5GMwIcF0gi:-NwoH8K45j5GMwIcF0gj:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor.rs#L98)):*
> ```XML
>         txs: &Vec<Transaction>,
>         charge_fee: bool,
>     ) -> Vec<TransactionExecutorResult<TransactionExecutionInfo>> {
> ```





_Suggestion:_
```XML
    pub fn execute_chunk(
        &mut self,
        txs: &[Transaction],
        charge_fee: bool,
    ) -> Vec<TransactionExecutorResult<TransactionExecutionInfo>> {
```
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoT3Qa8RIejBH1APca:-NwoT3Qb6bUaW82wGIT0:bjizk3c) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L4)):*
> ```XML
> use pretty_assertions::assert_eq;
> use rstest::rstest;
> use starknet_api::core::Nonce;
> ```

Import it inside the macro
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoMh_k8RolYjURq0Jp:-NwoMh_l3mb-ats0pROX:bl6mkho) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L279)):*
> ```XML
> }
> 
> #[rstest]
> ```

I'm not sure we want to use `rstest` unless we use one of its features. Maybe it's time to decide what is our convention.



_Suggestion:_
```XML
#[test]
```
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 282 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoMdASDNVsqXUSu9Eq:-NwoMdASDNVsqXUSu9Er:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L282)):*
> ```XML
> fn test_execute_chunk_bouncing(block_context: BlockContext) {
>     let TestInitData { state, account_address, contract_address, nonce_manager: _ } =
>         create_test_init_data(&block_context.chain_info, CairoVersion::Cairo1);
> ```





_Suggestion:_
```XML
    let TestInitData { state, account_address, contract_address, .. } =
        create_test_init_data(&block_context.chain_info, CairoVersion::Cairo1);
```
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoNwrFA5KeCfCffS0p:-NwoNwrFA5KeCfCffS0q:bok2zc7) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L295)):*
> ```XML
>             ..BouncerConfig::default()
>         },
>     );
> ```

I think `n` in `emit_n_events` should be `usize` and not `u32`, that way, we can:



_Suggestion:_
```XML
    let max_n_events_in_block = 10;
    let mut tx_executor = TransactionExecutor::new(
        state,
        block_context,
        BouncerConfig {
            block_max_capacity: BouncerWeights {
                n_events: max_n_events_in_block,
                ..BouncerWeights::max(false)
            },
            ..BouncerConfig::default()
        },
    );
```
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoHGKf2gecH23oE9hY:-NwoHGKf2gecH23oE9hZ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L314)):*
> ```XML
>     .into_iter()
>     .map(Transaction::AccountTransaction)
>     .collect();
> ```





_Suggestion:_
```XML
    let txs: Vec<Transaction> = [
        emit_n_events_tx(1, account_address, contract_address, nonce!(0_u32)),
        // Transaction too big.
        emit_n_events_tx(
            max_n_events_in_block + 1,
            account_address,
            contract_address,
            nonce!(1_u32),
        ),
        emit_n_events_tx(8, account_address, contract_address, nonce!(1_u32)),
        // No room for this on in block - execution should halt.
        emit_n_events_tx(2, account_address, contract_address, nonce!(2_u32)),
        // Has room for this one, but should not be processed at all.
        emit_n_events_tx(1, account_address, contract_address, nonce!(3_u32)),
    ]
    .into_iter()
    .map(Transaction::AccountTransaction)
    .collect();
```
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoOU3b3UubtkuPqsVe:-NwoOU3c2GM1_hj9SJPv:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L320)):*
> ```XML
> 
>     // Check execution results.
>     assert_eq!(results.len(), 3);
> ```





_Suggestion:_
```XML
    // Run.
    let results = tx_executor.execute_chunk(&txs, true);

    // Check execution results.
    assert_eq!(results.len(), 3);
    
    let new_offset = txs.len() - results.len();
    let results2 = tx_executor.execute_chunk(&txs[new_offset..], true);
    ...more assertions...
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841)* status: all files reviewed, 11 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoTINU5_i9Dvnn7uJJ:-NwonLIfEaCdtmNRv6hf:b-cnt3iv) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/test_utils.rs#L121)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Why both?
If you want to move it to SN_API, WDYT about making it not so easy to use in our repo?
</blockquote></details>

You do not need this at all as the `test_utils` file is already decorated with it (see [here](https://github.com/starkware-libs/blockifier/blob/cb464f5ac2ada88f2844d9f7d62bd6732ceb5b2c/crates/blockifier/src/lib.rs#L21)).
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-Nwoov1C5dOcFIqU7EbD:-Nwoov1C5dOcFIqU7EbE:b59sqep) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor.rs#L94)):*
> ```XML
>     /// Stops if and when there is no more room in the block, and returns the executed transactions'
>     /// results.
>     pub fn execute_chunk(
> ```

What about the `execute_txs` [method](https://github.com/starkware-libs/blockifier/blob/20a6a9e4da1dd5fd328d238c6928dfffc5e3a0b9/crates/native_blockifier/src/py_block_executor.rs#L188)? Are you planning it calls `execute_chunk`?



_Code quote:_
```XML
    pub fn execute_chunk(
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841)* status: 3 of 7 files reviewed, 11 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoPCZe5qGTUhjB2R0A:-NwpPKuc6Qh1QuZh8aq6:b-w7la9j) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b87bdce1f5ef3e0648874cc1de8a92cedc8bc1e/crates/blockifier/src/bouncer.rs#L324)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Why was it so in the first place?
(I agree that it doesn't look like it's needed)
</blockquote></details>

Seems like a bug. I went to the original PR and there was no reason to wrap it with result in the first place
___
*[`crates/blockifier/src/test_utils.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoTINU5_i9Dvnn7uJJ:-NwpPYU3ChAqocOMXWT3:bvqymg2) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/test_utils.rs#L121)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You do not need this at all as the `test_utils` file is already decorated with it (see [here](https://github.com/starkware-libs/blockifier/blob/cb464f5ac2ada88f2844d9f7d62bd6732ceb5b2c/crates/blockifier/src/lib.rs#L21)).
</blockquote></details>

Great, thanks. I copied this pattern as-is from SN API.
___
*[`crates/blockifier/src/test_utils.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoTBhW2peZ_SWbMu1-:-NwpQD-DCnYq6j5Uz7Xz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/test_utils.rs#L127)):*
> ```XML
>         Nonce(StarkHash::try_from($s).unwrap())
>     };
> }
> ```

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-Nwoov1C5dOcFIqU7EbD:-NwpQGxS9G-5Nozc28IG:b-9ib9xc) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor.rs#L94)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What about the `execute_txs` [method](https://github.com/starkware-libs/blockifier/blob/20a6a9e4da1dd5fd328d238c6928dfffc5e3a0b9/crates/native_blockifier/src/py_block_executor.rs#L188)? Are you planning it calls `execute_chunk`?
</blockquote></details>

Yes. The current impl there is incorrect, and I want py_block_executor to be as thin as possible.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoH8K45j5GMwIcF0gi:-NwpR4kR3Y-aTFvzniyI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor.rs#L98)):*
> ```XML
>         txs: &Vec<Transaction>,
>         charge_fee: bool,
>     ) -> Vec<TransactionExecutorResult<TransactionExecutionInfo>> {
> ```

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoT3Qa8RIejBH1APca:-NwpR78X97AflrYBzes7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L4)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Import it inside the macro
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoMh_k8RolYjURq0Jp:-NwpRIA1D12Q9MRyrA6X:b-qj5hz5) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L279)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I'm not sure we want to use `rstest` unless we use one of its features. Maybe it's time to decide what is our convention.
</blockquote></details>

I need this for the `block_context`. I can construct some default struct though, don't care about that
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 282 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoMdASDNVsqXUSu9Eq:-NwpRhGS2h5cCtpM7BE3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L282)):*
> ```XML
> fn test_execute_chunk_bouncing(block_context: BlockContext) {
>     let TestInitData { state, account_address, contract_address, nonce_manager: _ } =
>         create_test_init_data(&block_context.chain_info, CairoVersion::Cairo1);
> ```

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoNwrFA5KeCfCffS0p:-NwpS3Pz87M5fohSpaV3:byhx3gu) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L295)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I think `n` in `emit_n_events` should be `usize` and not `u32`, that way, we can:
</blockquote></details>

Done (the conversion is pushed to `emit_n_events_tx`)
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoHGKf2gecH23oE9hY:-NwpSWg6EK1bLqJQyIVf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L314)):*
> ```XML
>     .into_iter()
>     .map(Transaction::AccountTransaction)
>     .collect();
> ```

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoOU3b3UubtkuPqsVe:-NwpXi-nEVUgt5AXdcu8:b-ezkjqj) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L320)):*
> ```XML
> 
>     // Check execution results.
>     assert_eq!(results.len(), 3);
> ```

Done (kind of)

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-NwoMh_k8RolYjURq0Jp:-Nwq3hajCMOUbroea9yo:b-7cy6lx) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef6907d57507edfe2256c05399b22cc7454d8173/crates/blockifier/src/blockifier/transaction_executor_test.rs#L279)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I need this for the `block_context`. I can construct some default struct though, don't care about that
</blockquote></details>

Right! I missed it...
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 337 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-Nwq7ErsCNd3DdH9oMiO:-Nwq7ErsCNd3DdH9oMiP:b1hyltn) ([raw file](https://github.com/starkware-libs/blockifier/blob/69c26527c1cfdba65188f042dc9a9f71c9054c5b/crates/blockifier/src/blockifier/transaction_executor_test.rs#L337)):*
> ```XML
> 
>     // Reset the bouncer and add the remaining transactions.
>     tx_executor.bouncer = Bouncer::new(bouncer_config);
> ```

WDYT about adding to the `Bouncer` struct:
```
#[cfg(test)]
    pub fn reset(&mut self) {
        <logic that doesn't change the config and reset all the other fields>
    }
```
and than remove the `.clone()` in line 291, maybe even returning the `BouncerConfig` initialization into the `TransactionExecutor` constructor.



_Suggestion:_
```XML
tx_executor.bouncer.reset();
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 337 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-Nwq7ErsCNd3DdH9oMiO:-NwryIghEqZbUWjMvLTj:b-iqb72g) ([raw file](https://github.com/starkware-libs/blockifier/blob/69c26527c1cfdba65188f042dc9a9f71c9054c5b/crates/blockifier/src/blockifier/transaction_executor_test.rs#L337)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT about adding to the `Bouncer` struct:
```
#[cfg(test)]
    pub fn reset(&mut self) {
        <logic that doesn't change the config and reset all the other fields>
    }
```
and than remove the `.clone()` in line 291, maybe even returning the `BouncerConfig` initialization into the `TransactionExecutor` constructor.
</blockquote></details>

Hmmm, I don't think it would be useful. That's a hacky flow in general (reset the bouncer and not the state). If I'll find myself doing this in another test, I'll add it :)

**Review by noaov1 — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 279 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-Nws-BV99EkanIGJe1Nm:-Nws-BVA6Qm2xQaaeObg:bds3i29) ([raw file](https://github.com/starkware-libs/blockifier/blob/69c26527c1cfdba65188f042dc9a9f71c9054c5b/crates/blockifier/src/blockifier/transaction_executor_test.rs#L279)):*
> ```XML
> 
> #[rstest]
> fn test_execute_chunk_bouncing(block_context: BlockContext) {
> ```

Nice test!



_Code quote:_
```XML
fn test_execute_chunk_bouncing(block_context: BlockContext) {
```
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 303 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-Nwrz7jI5thJkPDIT9kY:-Nwrz7jJ44kCJMxmhG-k:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/69c26527c1cfdba65188f042dc9a9f71c9054c5b/crates/blockifier/src/blockifier/transaction_executor_test.rs#L303)):*
> ```XML
>         ),
>         emit_n_events_tx(8, account_address, contract_address, nonce!(1_u32)),
>         // No room for this on in block - execution should halt.
> ```





_Suggestion:_
```XML
        // No room for this in block - execution should halt.
```

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-:-Nws0MRh4Aflp6XMl3Ww:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 279 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-Nws-BV99EkanIGJe1Nm:-NwsTR3sDgW5deEZp4J8:b32vhw) ([raw file](https://github.com/starkware-libs/blockifier/blob/69c26527c1cfdba65188f042dc9a9f71c9054c5b/crates/blockifier/src/blockifier/transaction_executor_test.rs#L279)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Nice test!
</blockquote></details>

:)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1841#-:-NwsUweq7o_FuXv3P-o_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
