### PR TITLE
refactor(execution): clean TransactionExecutor - move validate to Sta…

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
…tefulValidator

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1961)

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1961#-:-NzgLdP4Epgu88Q1B-m-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1961#-NzgKxgsB9P4ihTTxE8d:-NzgKxgsB9P4ihTTxE8e:bht3y2c) ([raw file](https://github.com/starkware-libs/blockifier/blob/eee19226fa16c06d23dc8e3af1c373360308caf8/crates/blockifier/src/blockifier/stateful_validator.rs#L149)):*
> ```XML
>         mut remaining_gas: u64,
>     ) -> StatefulValidatorResult<(Option<CallInfo>, TransactionReceipt)> {
>         let mut execution_resources = ExecutionResources::default();
> ```

Consider defining: `let tx_executor = self.tx_executor`.
___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1961#-NzgLWGb3Kdsqin631wb:-NzgLWGb3Kdsqin631wc:b-4gxcnb) ([raw file](https://github.com/starkware-libs/blockifier/blob/eee19226fa16c06d23dc8e3af1c373360308caf8/crates/blockifier/src/blockifier/stateful_validator.rs#L154)):*
> ```XML
> 
>         // TODO(Amos, 01/12/2023): Delete this once deprecated txs call
>         // PyValidator.perform_validations().
> ```

Is this still relevant?



_Code quote:_
```XML
        // TODO(Amos, 01/12/2023): Delete this once deprecated txs call
        // PyValidator.perform_validations().
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1961)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1961#-NzgKxgsB9P4ihTTxE8d:-NzgiK8m01O9aVogxFDx:b-cgjjsb) ([raw file](https://github.com/starkware-libs/blockifier/blob/eee19226fa16c06d23dc8e3af1c373360308caf8/crates/blockifier/src/blockifier/stateful_validator.rs#L149)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining: `let tx_executor = self.tx_executor`.
</blockquote></details>

Hmm doesn't save much
___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1961#-NzgLWGb3Kdsqin631wb:-Nzgi9Tr4rbjur7Fa0-q:b-7xvq5o) ([raw file](https://github.com/starkware-libs/blockifier/blob/eee19226fa16c06d23dc8e3af1c373360308caf8/crates/blockifier/src/blockifier/stateful_validator.rs#L154)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is this still relevant?
</blockquote></details>

Yalla

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1961#-NzgjhOZ4cidt_7RHik4:-NzgjhOZ4cidt_7RHik5:bbvvat) ([raw file](https://github.com/starkware-libs/blockifier/blob/759a99d2d8fb7b973b026b97967d45f070dace81/crates/blockifier/src/blockifier/stateful_validator.rs#L147)):*
> ```XML
>         &mut self,
>         tx: &AccountTransaction,
>         mut remaining_gas: u64,
> ```

Does this work as intended for sure?
What is the expected behavior here?
Is the original value supposed to change?



_Code quote:_
```XML
mut remaining_gas: u64,
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1961#-NzgjhOZ4cidt_7RHik4:-NzguH_K1BKn8CqRVlf4:bvky39v) ([raw file](https://github.com/starkware-libs/blockifier/blob/759a99d2d8fb7b973b026b97967d45f070dace81/crates/blockifier/src/blockifier/stateful_validator.rs#L147)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Does this work as intended for sure?
What is the expected behavior here?
Is the original value supposed to change?
</blockquote></details>

Well - it does not matter - in any case, this value will not change in the calling function. So we are good.

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
