### PR TITLE
Apply validate+nonce changes on execution failures

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXG6LAECZqRl0xaWDle:-NXG6LAFCjFdROuBNy7a:bmhbdql) ([raw file](https://github.com/starkware-libs/blockifier/blob/533edbb17b5e54fc295a311afcb7f0d15f069477/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L82)):*
> ```Cairo
>     assert 0 = 1;
>     return ();
> }
> ```

used to test that the execute-incurred state diffs are reverted.



_Code quote:_
```Cairo
func write_and_revert{syscall_ptr: felt*}(address: felt, value: felt) {
    storage_write(address=address, value=value);
    assert 0 = 1;
    return ();
}
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 532 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXG6QjEATCsn-anikGm:-NXG6QjEATCsn-anikGn:b-mnn1oz) ([raw file](https://github.com/starkware-libs/blockifier/blob/533edbb17b5e54fc295a311afcb7f0d15f069477/crates/blockifier/src/execution/entry_point_test.rs#L532)):*
> ```XML
> Cairo traceback (most recent call last):
> Unknown location (pc=0:658)
> Unknown location (pc=0:641)
> ```

I added a function to the test contract, so old function locations moved... would be nice to dynamically get these values somehow, but that sounds like WORK



_Code quote:_
```XML
Unknown location (pc=0:658)
Unknown location (pc=0:641)
Error in the called contract ({}):
Error at pc=0:19:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:658)
Unknown location (pc=0:641)
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXG6am7DC6aS6ze_bQh:-NXG6am7DC6aS6ze_bQi:bhnntdq) ([raw file](https://github.com/starkware-libs/blockifier/blob/533edbb17b5e54fc295a311afcb7f0d15f069477/crates/blockifier/src/transaction/account_transactions_test.rs#L154)):*
> ```XML
> /// Tests that an account invoke transaction that fails the execution phase, still incurs a nonce
> /// increase and a fee deduction.
> fn test_revert_invoke() {
> ```

for public knowledge, I'll comment locations in this test that were NOT written by copilot :P



_Code quote:_
```XML
#[test]
/// Tests that an account invoke transaction that fails the execution phase, still incurs a nonce
/// increase and a fee deduction.
fn test_revert_invoke() {
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXG6it21VjWF6AYTuPm:-NXG6it21VjWF6AYTuPn:bn2plhn) ([raw file](https://github.com/starkware-libs/blockifier/blob/533edbb17b5e54fc295a311afcb7f0d15f069477/crates/blockifier/src/transaction/account_transactions_test.rs#L186)):*
> ```XML
>         storage_key,
>         stark_felt!(99_u8) // Dummy, non-zero value.
>     ];
> ```

copilot wrote:
```
let entry_point_selector = selector_from_name("revert");
    let execute_calldata = calldata![
        *deployed_account_address.0.key(), // Contract address.
        entry_point_selector.0,            // EP selector.
        stark_felt!(0_u8),                 // Calldata length.
    ];
```
and this WORKED, because executing a non-existing entry point (`"revert"`) causes execution failure :) but, I wanted a function that changes the state as well..



_Code quote:_
```XML
    let storage_key = stark_felt!(9_u8);
    let entry_point_selector = selector_from_name("write_and_revert");
    let execute_calldata = calldata![
        *deployed_account_address.0.key(), // Contract address.
        entry_point_selector.0,            // EP selector.
        stark_felt!(2_u8),                 // Calldata length.
        storage_key,
        stark_felt!(99_u8) // Dummy, non-zero value.
    ];
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXG6z-v4v27gWQR5hWc:-NXG6z-w4jCUxuwOWail:bp5qo85) ([raw file](https://github.com/starkware-libs/blockifier/blob/533edbb17b5e54fc295a311afcb7f0d15f069477/crates/blockifier/src/transaction/account_transactions_test.rs#L192)):*
> ```XML
>         ..tx
>     }));
>     let tx_execution_info = account_tx.execute(state, block_context).unwrap();
> ```

copilot thought this should be
```
account_tx.execute(state, block_context).unwrap_err();
```
... which is a good guess, but a reverted tx is a "successful" tx.



_Code quote:_
```XML
let tx_execution_info = account_tx.execute(state, block_context).unwrap();
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXG78002rnJ1f-2vsmM:-NXG78002rnJ1f-2vsmN:bcotehr) ([raw file](https://github.com/starkware-libs/blockifier/blob/533edbb17b5e54fc295a311afcb7f0d15f069477/crates/blockifier/src/transaction/account_transactions_test.rs#L205)):*
> ```XML
>         state.get_fee_token_balance(block_context, &deployed_account_address).unwrap(),
>         (stark_felt!(BALANCE - total_deducted_fee), stark_felt!(0_u8))
>     );
> ```

copilot errors:
1. did not check `revert_error.is_some()` (I would have been creeped out if it did)
2. did not guess `total_deducted_fee` correctly - it just went with checking balance against `BALANCE - MAX_FEE`



_Code quote:_
```XML
    // Check that the transaction was reverted.
    assert!(tx_execution_info.revert_error.is_some());

    // Check that the nonce was increased and the fee was deducted.
    let total_deducted_fee = deploy_execution_info.actual_fee.0 + tx_execution_info.actual_fee.0;
    assert_eq!(
        state.get_fee_token_balance(block_context, &deployed_account_address).unwrap(),
        (stark_felt!(BALANCE - total_deducted_fee), stark_felt!(0_u8))
    );
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXG7NJT1OlH7GV6yZ9T:-NXG7NJT1OlH7GV6yZ9U:b-c1u62d) ([raw file](https://github.com/starkware-libs/blockifier/blob/533edbb17b5e54fc295a311afcb7f0d15f069477/crates/blockifier/src/transaction/account_transactions_test.rs#L217)):*
> ```XML
>             )
>             .unwrap()
>     );
> ```

my addition



_Code quote:_
```XML
    // Check that execution state changes were reverted.
    assert_eq!(
        stark_felt!(0_u8),
        state
            .get_storage_at(
                ContractAddress(patricia_key!(TEST_CONTRACT_ADDRESS)),
                StorageKey::try_from(storage_key).unwrap(),
            )
            .unwrap()
    );
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 322 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXGZKLH6WhgaQ5Idttp:-NXGZKLH6WhgaQ5Idttq:b-1at8lp) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7dcca6f708101c6923ce517667165c6bc72e399/crates/blockifier/src/transaction/account_transaction.rs#L322)):*
> ```XML
>         // validation state change should be applied, and nonce should be bumped.
>         let mut execution_state = CachedState::new(MutRefState::new(state));
>         let is_deploy_account = early_validate_call_info.is_none();
> ```

That is not accurate - this could be a V0 transaction. 

WDYT about handling DEPLOY_ACCOUNT at the beginning of this function? (execute + validate and shalom al Israel)

This would make this function much more readable



_Code quote:_
```XML
let is_deploy_account = early_validate_call_info.is_none();
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXGeCGeC2Dyks3XV51w:-NXGeCGfBzSt8m8TdHBv:b8sm6ic) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7dcca6f708101c6923ce517667165c6bc72e399/crates/blockifier/src/transaction/account_transaction.rs#L301)):*
> ```XML
>     }
> 
>     /// Runs validation and execution.
> ```

More documentation than code... :(
Please make it shorter.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXGeHBuBGvNnNuu_4D4:-NXGeHBuBGvNnNuu_4D5:b-xiwg9h) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7dcca6f708101c6923ce517667165c6bc72e399/crates/blockifier/src/transaction/account_transaction.rs#L313)):*
> ```XML
>         state: &mut TransactionalState<'_, S>,
>         context: &mut ExecutionContext,
>     ) -> TransactionExecutionResult<(Option<CallInfo>, Option<CallInfo>, Option<String>)> {
> ```

Those are couupled, maybe bundle them in some king of Result object?



_Code quote:_
```XML
Option<CallInfo>, Option<String>
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 322 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXGZKLH6WhgaQ5Idttp:-NXGfq713lTFRZlJUWbh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7dcca6f708101c6923ce517667165c6bc72e399/crates/blockifier/src/transaction/account_transaction.rs#L322)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

That is not accurate - this could be a V0 transaction. 

WDYT about handling DEPLOY_ACCOUNT at the beginning of this function? (execute + validate and shalom al Israel)

This would make this function much more readable
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @elintul, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXGeHBuBGvNnNuu_4D4:-NXGh6GvB8zgh1dGLiKe:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7dcca6f708101c6923ce517667165c6bc72e399/crates/blockifier/src/transaction/account_transaction.rs#L313)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Those are couupled, maybe bundle them in some king of Result object?
</blockquote></details>

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 322 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXGZKLH6WhgaQ5Idttp:-NXGhagGDwzlAPl0SvyI:bxztp5g) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7dcca6f708101c6923ce517667165c6bc72e399/crates/blockifier/src/transaction/account_transaction.rs#L322)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Beautiful

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @elintul, and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXQ-1OT0UUEOwdZaAaF:-NXQ-1OT0UUEOwdZaAaG:bukehek) (no related file):*
[python-side PR](https://reviewable.io/reviews/starkware-industries/starkware/30323)

___

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572#-:-NXfYnIh-ImvHuVHKUNQ:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 532 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXG6QjEATCsn-anikGm:-NXfUyZKANJZGA_0o0S2:b-x9r47k) ([raw file](https://github.com/starkware-libs/blockifier/blob/533edbb17b5e54fc295a311afcb7f0d15f069477/crates/blockifier/src/execution/entry_point_test.rs#L532)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I added a function to the test contract, so old function locations moved... would be nice to dynamically get these values somehow, but that sounds like WORK
</blockquote></details>

In dev we replace these numbers with ??? before checking

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 368 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXjk0DE-5ztm5FWvbsL:-NXo3QaT1IdDrsGZHLKx:bekrsrm) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6950bbd89fa38bf297d73e39f22fd1645797bab/crates/blockifier/src/transaction/account_transaction.rs#L368)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

what's the flow if validation fails?
</blockquote></details>

Validation error is propagated up the call stack.
Check the call to `execute_raw`, you'll see the state changes are aborted

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXGeHBuBGvNnNuu_4D4:-NXojNgq70gz4b4kcZyG:b-4rr6w4) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7dcca6f708101c6923ce517667165c6bc72e399/crates/blockifier/src/transaction/account_transaction.rs#L313)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant, if call info. isn't `None`; error must be and vice versa.
Perhaps check this in a `new` method?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 314 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXoj89w9JyvSdXmAEQJ:-NXoj89w9JyvSdXmAEQK:bd0h7pf) ([raw file](https://github.com/starkware-libs/blockifier/blob/c5afb8f22634dac1f1fcd30d317c6422a4f671a8/crates/blockifier/src/transaction/account_transaction.rs#L314)):*
> ```XML
> 
>     /// Runs validation and execution.
>     /// An Ok() result indicates either successful or reverted transaction; Err() means failure.
> ```

What info. are you adding to the reader?



_Code quote:_
```XML
/// An Ok() result indicates either successful or reverted transaction; Err() means failure.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 322 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXojYbACd5-99v7RWZG:-NXojYbACd5-99v7RWZH:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c5afb8f22634dac1f1fcd30d317c6422a4f671a8/crates/blockifier/src/transaction/account_transaction.rs#L322)):*
> ```XML
>         remaining_gas: &mut Felt252,
>     ) -> TransactionExecutionResult<ValidateExecuteCallInfo> {
>         // Handle `DeployAccount` transactions separately.
> ```





_Suggestion:_
```XML
// Handle `DeployAccount` transactions separately, due to different order of things.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 326 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXojFpl2McMVJ-4yj70:-NXojFpl2McMVJ-4yj71:b-utt4ex) ([raw file](https://github.com/starkware-libs/blockifier/blob/c5afb8f22634dac1f1fcd30d317c6422a4f671a8/crates/blockifier/src/transaction/account_transaction.rs#L326)):*
> ```XML
>             let execute_call_info = self.run_execute(state, context, remaining_gas)?;
>             return Ok(ValidateExecuteCallInfo {
>                 validate_call_info: self.validate_tx(state, context, remaining_gas)?,
> ```

Make it symmetric?
Either run both in the struct init. line, or define two variables.



_Code quote:_
```XML
            let execute_call_info = self.run_execute(state, context, remaining_gas)?;
            return Ok(ValidateExecuteCallInfo {
                validate_call_info: self.validate_tx(state, context, remaining_gas)?,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 335 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXojk-RDLvT0GIrTxs2:-NXojk-RDLvT0GIrTxs3:b95uv5k) ([raw file](https://github.com/starkware-libs/blockifier/blob/c5afb8f22634dac1f1fcd30d317c6422a4f671a8/crates/blockifier/src/transaction/account_transaction.rs#L335)):*
> ```XML
>         let validate_call_info = self.validate_tx(state, context, remaining_gas)?;
>         let mut execution_state = CachedState::new(MutRefState::new(state));
>         match self.run_execute(&mut execution_state, context, remaining_gas) {
> ```

Swap positive an negative case?



_Code quote:_
```XML
match self.run_execute
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @amosStarkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 352 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXv2eu31TAMhTqNOGPn:-NXv2eu40kTT34XimPJw:b3g81p9) ([raw file](https://github.com/starkware-libs/blockifier/blob/f45eb6d2592cd9b807f421b6c7a721f62d06d801/crates/blockifier/src/transaction/account_transaction.rs#L352)):*
> ```XML
>                 execute_call_info,
>             ));
>         }
> ```

@Yoni-Starkware for you



_Code quote:_
```XML
        // V0 transactions do not have validation; we cannot deduct fee for execution.
        if context.account_tx_context.is_v0() {
            let validate_call_info = self.validate_tx(state, context, remaining_gas)?;
            let execute_call_info = self.run_execute(state, context, remaining_gas)?;
            return Ok(ValidateExecuteCallInfo::new_accepted(
                validate_call_info,
                execute_call_info,
            ));
        }
```

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572#-:-NXynPDI7UUG6nzku93t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @zuphitf)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 342 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXzhfP3AAG3Oh2jp_zX:-NXzhfP3AAG3Oh2jp_zY:b-cy1sr2) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdcf80457f478e8f271c1ed9d3ba826c2469097b/crates/blockifier/src/transaction/account_transaction.rs#L342)):*
> ```XML
>         resources: &mut ExecutionResources,
>         remaining_gas: &mut Felt252,
>         context: &mut EntryPointExecutionContext,
> ```

For consistency.



_Suggestion:_
```XML
        state: &mut S,
        resources: &mut ExecutionResources,
        context: &mut EntryPointExecutionContext,
        remaining_gas: &mut Felt252,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 361 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXzhpTX8ePsS6lzrkOD:-NXzhpTYBvMPsQPU2kgC:b-cng6fg) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdcf80457f478e8f271c1ed9d3ba826c2469097b/crates/blockifier/src/transaction/account_transaction.rs#L361)):*
> ```XML
>     ) -> TransactionExecutionResult<ValidateExecuteCallInfo> {
>         let account_tx_context = self.get_account_transaction_context();
>         let is_v0 = account_tx_context.is_v0();
> ```

Move just before usage; also, not sure a variable is needed.



_Code quote:_
```XML
let is_v0 = account_tx_context.is_v0();
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 362 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXzhxDbDNm3rK-EknDF:-NXzhxDbDNm3rK-EknDG:b-cy1sr2) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdcf80457f478e8f271c1ed9d3ba826c2469097b/crates/blockifier/src/transaction/account_transaction.rs#L362)):*
> ```XML
>         let account_tx_context = self.get_account_transaction_context();
>         let is_v0 = account_tx_context.is_v0();
>         let mut execution_context = EntryPointExecutionContext::new(
> ```

For consistency.



_Suggestion:_
```XML
let mut context
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 361 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXzhpTX8ePsS6lzrkOD:-NXznrZoEkM0Mzim-_ZA:blfaake) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdcf80457f478e8f271c1ed9d3ba826c2469097b/crates/blockifier/src/transaction/account_transaction.rs#L361)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move just before usage; also, not sure a variable is needed.
</blockquote></details>

can't, `account_tx_context` is moved into `EntryPointExecutionContext::new`

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 361 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/572#-NXzhpTX8ePsS6lzrkOD:-NXzu4Q-6k4PZS_ykqN5:b-7xj55n) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdcf80457f478e8f271c1ed9d3ba826c2469097b/crates/blockifier/src/transaction/account_transaction.rs#L361)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can't, `account_tx_context` is moved into `EntryPointExecutionContext::new`
</blockquote></details>

Yuck.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/572#-:-NXzu8jZ2YQ0ZVyLwgJ1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @zuphitf)

**Pull request merged**
