### PR TITLE
chore: update costs

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2044)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
The costs updates happen due to the OS changes here:
https://reviewable.io/reviews/starkware-industries/starkware/35349#-

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2044)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 292 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2044#-O1BQh_E4aLVBrTkA8-J:-O1BQh_E4aLVBrTkA8-K:b-8u8tk6) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae0ae009f6197ee097763560f9595fa9abeaf441/crates/blockifier/resources/versioned_constants.json#L292)):*
> ```JSON
>                 "n_memory_holes": 0,
>                 "n_steps": 1852
>             },
> ```

not sure why it was here before.



_Code quote:_
```JSON
            "Sha256ProcessBlock": {
                "builtin_instance_counter": {
                    "range_check_builtin": 65,
                    "bitwise_builtin": 1115
                },
                "n_memory_holes": 0,
                "n_steps": 1852
            },
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2044)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 292 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2044#-O1BQh_E4aLVBrTkA8-J:-O1BXgHO1Cn6xHGsWPR5:b-ini7t3) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae0ae009f6197ee097763560f9595fa9abeaf441/crates/blockifier/resources/versioned_constants.json#L292)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not sure why it was here before.
</blockquote></details>

@dan-starkware FYI...

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2044)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
