### PR TITLE
refactor: share benchmark code with simple flow test

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`crates/blockifier/Cargo.toml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Ny_h8VJ52B40S7CUb4c:-Ny_h8VJ52B40S7CUb4d:bqavsng) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2fd9582b57af45c3e5d22b521a894d5b19e480e/crates/blockifier/Cargo.toml#L57)):*
> ```TOML
> glob.workspace = true
> pretty_assertions.workspace = true
> rand.workspace = true
> ```

I wanted to keep it here, but rust doesn't let me. Are test utils not considered "dev" for the purpose of dependencies?



_Code quote:_
```TOML
rand.workspace = true
```

**Comment by avi-starkware** [comment]
+reviewer:@OriStarkware

**Review by OriStarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-NypDXu4027aGtYw-qlm:-NypDXu4027aGtYw-qln:b-st0k5t) (no related file):*
Can you split this into a code-moving PR and a code-changing PR?

___

**Comment by avi-starkware** [comment]
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Can you split this into a code-moving PR and a code-changing PR?
</blockquote></details>

Done.

The code change happens in a preliminary PR: #1919 .
The current PR moves the code, and introduces the file `transfers_flow_test.rs`.

**Review by OriStarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/Cargo.toml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Ny_h8VJ52B40S7CUb4c:-NysruPM6hPtbZ4S1OYl:b-9homvk) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2fd9582b57af45c3e5d22b521a894d5b19e480e/crates/blockifier/Cargo.toml#L57)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I wanted to keep it here, but rust doesn't let me. Are test utils not considered "dev" for the purpose of dependencies?
</blockquote></details>

Please check that
___
*[`crates/blockifier/src/blockifier/transfers_flow_test.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-NysqWdpCQBsr35FNFWE:-NysqWdqAvGBAAgW_c1X:b8qqyks) ([raw file](https://github.com/starkware-libs/blockifier/blob/f1e9882866c3a2ceab5f3de2a71d00f2aa4bf6f2/crates/blockifier/src/blockifier/transfers_flow_test.rs#L5)):*
> ```XML
> #[test]
> pub fn transfers_flow_test() {
>     let n_chunks = 100;
> ```

Why do we need so many chunks?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/blockifier/transfers_flow_test.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-NysqWdpCQBsr35FNFWE:-Nytu8Ut8sliDTE3_8cg:b-7ck6fu) ([raw file](https://github.com/starkware-libs/blockifier/blob/f1e9882866c3a2ceab5f3de2a71d00f2aa4bf6f2/crates/blockifier/src/blockifier/transfers_flow_test.rs#L5)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Why do we need so many chunks?
</blockquote></details>

This is just an arbitrary number. i'll reduce it to 10.

**Review by OriStarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-:-Nyu4Yzc1iduuoT4oc8_:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/Cargo.toml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Ny_h8VJ52B40S7CUb4c:-NyyESZ7AffIllngWwiz:bjdnhc8) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2fd9582b57af45c3e5d22b521a894d5b19e480e/crates/blockifier/Cargo.toml#L57)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Please check that
</blockquote></details>

Can you please explain?
___
*[`crates/blockifier/src/blockifier/transfers_flow_test.rs` line 5 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Nz2E8yS0AKxkPF55T8x:-Nz2E8yS0AKxkPF55T8y:b-cc9phh) ([raw file](https://github.com/starkware-libs/blockifier/blob/41feedd231bef9fddc1067f2d523ad30c87ed2d2/crates/blockifier/src/blockifier/transfers_flow_test.rs#L5)):*
> ```XML
> #[test]
> pub fn transfers_flow_test() {
>     let n_chunks = 10;
> ```

Given the new implantation of `execute_txs` (execute a stream of transactions and divides it to chunks) consider running it one time.



_Code quote:_
```XML
    let n_chunks = 10;
```
___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Nz2FHhwA59TniO3xzzm:-Nz2FHhwA59TniO3xzzn:b-e8n7dq) ([raw file](https://github.com/starkware-libs/blockifier/blob/41feedd231bef9fddc1067f2d523ad30c87ed2d2/crates/blockifier/src/test_utils/transfers_simulator.rs#L25)):*
> ```XML
> const CHUNK_SIZE: usize = 10;
> const RANDOMIZATION_SEED: u64 = 0;
> const CHARGE_FEE: bool = false;
> ```

Can you please remind me why it's off? In the flow test we might want to charge fee. 



_Code quote:_
```XML
const CHARGE_FEE: bool = false;
```
___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Nz2FRBX-u1G882PitVu:-Nz2FRBX-u1G882PitVv:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/41feedd231bef9fddc1067f2d523ad30c87ed2d2/crates/blockifier/src/test_utils/transfers_simulator.rs#L26)):*
> ```XML
> const RANDOMIZATION_SEED: u64 = 0;
> const CHARGE_FEE: bool = false;
> const TRANSACTION_VERSION: TransactionVersion = TransactionVersion(StarkFelt::ONE);
> ```





_Suggestion:_
```XML
const TRANSACTION_VERSION: TransactionVersion = TransactionVersion(StarkFelt::THREE);
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transfers_flow_test.rs` line 5 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Nz2E8yS0AKxkPF55T8x:-Nz3qG3oAjVbx6Fz2po7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/41feedd231bef9fddc1067f2d523ad30c87ed2d2/crates/blockifier/src/blockifier/transfers_flow_test.rs#L5)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Given the new implantation of `execute_txs` (execute a stream of transactions and divides it to chunks) consider running it one time.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Nz2FHhwA59TniO3xzzm:-Nz3o5Qx25eWhlD4PrrO:blph6pr) ([raw file](https://github.com/starkware-libs/blockifier/blob/41feedd231bef9fddc1067f2d523ad30c87ed2d2/crates/blockifier/src/test_utils/transfers_simulator.rs#L25)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please remind me why it's off? In the flow test we might want to charge fee.
</blockquote></details>

This is a block of code I moved from elsewhere. I suggest not changing anything in this file in this PR, and doing it in the next PR: #1921.

If I make changes here, anything changed in the previous PR will mess everything up in this PR.
___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Nz2FRBX-u1G882PitVu:-Nz3pvVs1N13ulmGBZxX:bu6xv6u) ([raw file](https://github.com/starkware-libs/blockifier/blob/41feedd231bef9fddc1067f2d523ad30c87ed2d2/crates/blockifier/src/test_utils/transfers_simulator.rs#L26)):*
> ```XML
> const RANDOMIZATION_SEED: u64 = 0;
> const CHARGE_FEE: bool = false;
> const TRANSACTION_VERSION: TransactionVersion = TransactionVersion(StarkFelt::ONE);
> ```

See previous comment.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Nz2FHhwA59TniO3xzzm:-Nz3tz5i0UFgLmNEsBLd:b5uh021) ([raw file](https://github.com/starkware-libs/blockifier/blob/41feedd231bef9fddc1067f2d523ad30c87ed2d2/crates/blockifier/src/test_utils/transfers_simulator.rs#L25)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This is a block of code I moved from elsewhere. I suggest not changing anything in this file in this PR, and doing it in the next PR: #1921.

If I make changes here, anything changed in the previous PR will mess everything up in this PR.
</blockquote></details>

I changed it to `true` in #1921.
___
*[`crates/blockifier/src/test_utils/transfers_simulator.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Nz2FRBX-u1G882PitVu:-Nz3u4er6d1UnmJzhJxM:b41sj5y) ([raw file](https://github.com/starkware-libs/blockifier/blob/41feedd231bef9fddc1067f2d523ad30c87ed2d2/crates/blockifier/src/test_utils/transfers_simulator.rs#L26)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

See previous comment.
</blockquote></details>

Done in #1921.

**Review by OriStarkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/Cargo.toml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Ny_h8VJ52B40S7CUb4c:-NzDLZpj-a3vtfgGo-Is:b-2ffukm) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2fd9582b57af45c3e5d22b521a894d5b19e480e/crates/blockifier/Cargo.toml#L57)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Test code is compiled when the create is built, so it is not considered a dev-dependency when we use it in `test-utils` as opposed to when we use it in the benchmark.
</blockquote></details>

Does it have some negative affect?

**Review by OriStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/Cargo.toml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Ny_h8VJ52B40S7CUb4c:-Nzb_23FDdsXKb-x7K0Z:bvnttvr) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2fd9582b57af45c3e5d22b521a894d5b19e480e/crates/blockifier/Cargo.toml#L57)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Does it have some negative affect?
</blockquote></details>

I changed it to be the same as `rstest`:
1. set `optional = true`.
2. add `rand` to the feature `testing`.
3. add `rand` to dev-dependencies.

This ensures that rand is available for cargo test and cargo bench, but is not included in the production build.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/Cargo.toml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1917#-Ny_h8VJ52B40S7CUb4c:-Nzc4j1ZA03-CAJ9sa7Z:b-83sjoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/e2fd9582b57af45c3e5d22b521a894d5b19e480e/crates/blockifier/Cargo.toml#L57)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I changed it to be the same as `rstest`:
1. set `optional = true`.
2. add `rand` to the feature `testing`.
3. add `rand` to dev-dependencies.

This ensures that rand is available for cargo test and cargo bench, but is not included in the production build.
</blockquote></details>

Nice!

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1917)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
