### PR TITLE
Use Cairo 1 account faulty in validate test.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1227)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
This PR is blocked until #1225 gets in (Maybe even #1226).

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1227)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @MohammadNassar1, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1227#-Nl2VVTx2l4p54UjcJCG:-Nl2Vv1w7IkKUmafTEtu:beegcky) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This PR is blocked until #1225 gets in (Maybe even #1226).
</blockquote></details>

no need to wait for 1226

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1227#-:-NlIbQjGEgqfxzW099Lo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @MohammadNassar1, and @noaov1)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1227)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1227#-Nl2U0yD-7pcqitVboJJ:-NlIc0uXC9ALfOhv_M95:bmeuzlw) ([raw file](https://github.com/starkware-libs/blockifier/blob/037f0a56a012ca2776332a4d8f85a271b6ee2604/crates/blockifier/src/test_utils.rs#L76)):*
> ```XML
> pub const TEST_FAULTY_ACCOUNT_CONTRACT_CAIRO0_PATH: &str =
>     "./feature_contracts/cairo0/compiled/account_faulty_compiled.json";
> pub const TEST_FAULTY_ACCOUNT_CONTRACT_PATH: &str =
> ```

Irrelevant :)
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 324 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1227#-NlIb8s8AkL6_9Pz9FXe:-NlIb8s94qzRfqkAz4mJ:b7paxfb) ([raw file](https://github.com/starkware-libs/blockifier/blob/13a90e66d3e7ffc91a2d22292130f84be9db598b/crates/blockifier/src/transaction/test_utils.rs#L324)):*
> ```XML
>                 contract_class,
>             )
>         }
> ```

This returns a V1- Declare transaction to declare a Cairo 0 contract.
Note: the contract class of the declared contract should be compatible with the transaction type - thus, we can not simply use the input `FeatureContract`.
Note: If we update this test to use V3 txs - the contract should again be chosen statically - in a compatible way.



_Code quote:_
```XML
        TransactionType::Declare => {
            // It does not matter which class is declared for this test.
            let declared_contract = FeatureContract::TestContract(CairoVersion::Cairo0);
            let class_hash = declared_contract.get_class_hash();
            let contract_class = declared_contract.get_class();
            declare_tx(
                declare_tx_args! {
                    class_hash,
                    sender_address,
                    signature,
                    nonce: nonce_manager.next(sender_address)
                },
                contract_class,
            )
        }
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1104 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1227#-NlIaxHgD554aHWwrl42:-NlIaxHgD554aHWwrl43:b-7fe84q) ([raw file](https://github.com/starkware-libs/blockifier/blob/13a90e66d3e7ffc91a2d22292130f84be9db598b/crates/blockifier/src/transaction/transactions_test.rs#L1104)):*
> ```XML
>     )]
>     tx_type: TransactionType,
>     #[values(CairoVersion::Cairo0, CairoVersion::Cairo1)] cairo_version: CairoVersion,
> ```

This is the change.



_Code quote:_
```XML
    #[values(CairoVersion::Cairo0, CairoVersion::Cairo1)] cairo_version: CairoVersion,
```

**Pull request merged**
