### PR TITLE
Split test_validate_accounts_tx to a test for constructor.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1250)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
See motivation for this PR: the next PR: #1251.

**Comment by ArniStarkware** [comment]
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1250#-NlcozFV0GFWjPbcXXA2):*
fix



_Suggestion:_
```
- fb4bdf6: Split test_validate_accounts_tx to a test for constructor.
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1250)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 238 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1250#-Nm_Un359_rpcSc497Nl:-Nm_Un359_rpcSc497Nm:b-sztayc) ([raw file](https://github.com/starkware-libs/blockifier/blob/f47a04b98b93b0cbadc229dc8e55d949aa41b2d3/crates/blockifier/src/transaction/test_utils.rs#L238)):*
> ```XML
>         class_hash,
>         contract_address_salt,
>         validate_constructor: test_constructor,
> ```

Can you please explain why it has two different names?



_Code quote:_
```XML
validate_constructor: test_constructor
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1443 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1250#-Nm_VwFD-EnWuf66ygU0:-Nm_VwFE-LNmN5dvzFoT:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f47a04b98b93b0cbadc229dc8e55d949aa41b2d3/crates/blockifier/src/transaction/transactions_test.rs#L1443)):*
> ```XML
> 
> #[rstest]
> fn test_constructor_on_deploy_account_acts_as_validate(
> ```





_Suggestion:_
```XML
fn test_constructor_on_deploy_account_run_in_validate_mode(
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1459 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1250#-Nm_WqJq1vQnWRTOZZ7h:-Nm_WqJr0g9Ne1RoSq37:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f47a04b98b93b0cbadc229dc8e55d949aa41b2d3/crates/blockifier/src/transaction/transactions_test.rs#L1459)):*
> ```XML
>     };
> 
>     // Verify that the contract does not call another contract in the constructor of deploy account.
> ```





_Suggestion:_
```XML
    // Verify that the contract cannot call another contract in the constructor of deploy account.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1250)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 238 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1250#-Nm_Un359_rpcSc497Nl:-Nm_Z2XGClsOvHa9Ackv:b-v2gw22) ([raw file](https://github.com/starkware-libs/blockifier/blob/f47a04b98b93b0cbadc229dc8e55d949aa41b2d3/crates/blockifier/src/transaction/test_utils.rs#L238)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain why it has two different names?
</blockquote></details>

We are now using matching names. Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1443 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1250#-Nm_VwFD-EnWuf66ygU0:-Nm_Zek9E5gjOST720JM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f47a04b98b93b0cbadc229dc8e55d949aa41b2d3/crates/blockifier/src/transaction/transactions_test.rs#L1443)):*
> ```XML
> 
> #[rstest]
> fn test_constructor_on_deploy_account_acts_as_validate(
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1459 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1250#-Nm_WqJq1vQnWRTOZZ7h:-Nm_Zfsv-9bEPeaCKJEU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f47a04b98b93b0cbadc229dc8e55d949aa41b2d3/crates/blockifier/src/transaction/transactions_test.rs#L1459)):*
> ```XML
>     };
> 
>     // Verify that the contract does not call another contract in the constructor of deploy account.
> ```

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1250#-:-Nm_laFb7ksQdR2Tia31:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
