### PR TITLE
Add scenario to get block hash test.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1243)

### CODE REVIEW

**Review by MohammadNassar1 — DISMISSED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1243)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1243)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 120 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1243#-NlwdldyC2KcjKTUI0dB:-NlwdldyC2KcjKTUI0dC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7974ecfaecdff6378abc76f75a3f331fe0d07633/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L120)):*
> ```Cairo
>                 calldata: calldata.span()
>             )
>                 .unwrap();
> ```





_Suggestion:_
```Cairo
                .unwrap_syscall();
```

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1243)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1234 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1243#-NlwfHrD9y0uBWqB9PG1:-NlwfHrD9y0uBWqB9PG2:b-qgynws) ([raw file](https://github.com/starkware-libs/blockifier/blob/7974ecfaecdff6378abc76f75a3f331fe0d07633/crates/blockifier/src/transaction/transactions_test.rs#L1234)):*
> ```XML
>     if let CairoVersion::Cairo1 = cairo_version {
>         // Trying to use the syscall get_block_hash (forbidden).
>         // TODO(Arni, 12/12/2023): Test this scenario with the constructor.
> ```

Why not in this PR? 



_Code quote:_
```XML
        // TODO(Arni, 12/12/2023): Test this scenario with the constructor.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1243)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 120 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1243#-NlwdldyC2KcjKTUI0dB:-Nm06HguD_vfI6RbjgLG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7974ecfaecdff6378abc76f75a3f331fe0d07633/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L120)):*
> ```Cairo
>                 calldata: calldata.span()
>             )
>                 .unwrap();
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1234 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1243#-NlwfHrD9y0uBWqB9PG1:-Nlx5XrPAdsC-0Vk3r1R:b-4fsclv) ([raw file](https://github.com/starkware-libs/blockifier/blob/7974ecfaecdff6378abc76f75a3f331fe0d07633/crates/blockifier/src/transaction/transactions_test.rs#L1234)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not in this PR?
</blockquote></details>

Because, I have another set of PRs: #1250, #1251, which deal with the constructor - And I wanted to avoid conflicts.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1243#-:-Nm1eg-7EcbEXI2XVIo0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1243)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
