### PR TITLE
feat(execution): add the syscall resources to vm_resources

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1412)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1412)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @OriStarkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 341 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpYxEyF4ppFAJ-uNp52:-NpYxEyGDJYNiNOxxOJC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e5e5a5b7eb7dd06a859e592d0bbfbcd602832e53/crates/blockifier/src/execution/entry_point_execution.rs#L341)):*
> ```XML
>     syscall_handler.resources.vm_resources += &vm_resources_without_inner_calls;
>     syscall_handler.resources.vm_resources += &get_entry_point_syscall_resources(
>         &syscall_handler.resources.syscall_counter,
> ```





_Suggestion:_
```XML
        &syscall_handler.syscall_counter,
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1412)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 341 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpYxEyF4ppFAJ-uNp52:-NpZ5_ZA5w4YDNyzrwbE:b-dzx968) ([raw file](https://github.com/starkware-libs/blockifier/blob/e5e5a5b7eb7dd06a859e592d0bbfbcd602832e53/crates/blockifier/src/execution/entry_point_execution.rs#L341)):*
> ```XML
>     syscall_handler.resources.vm_resources += &vm_resources_without_inner_calls;
>     syscall_handler.resources.vm_resources += &get_entry_point_syscall_resources(
>         &syscall_handler.resources.syscall_counter,
> ```

Thanks, that is exactly why I wanted two different names.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1412)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @OriStarkware)

___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 238 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-Np_H1Xc-4aZviVUKdoC:-Np_H1Xc-4aZviVUKdoD:b-enq70f) ([raw file](https://github.com/starkware-libs/blockifier/blob/2e1de3643cbb6783990ed5371f35c1355a3114cf/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L238)):*
> ```XML
>     validate_run(&mut vm, &runner, &syscall_handler, implicit_args, implicit_args_end_ptr)?;
> 
>     // Take into account the VM execution resources of the current call, without inner calls.
> ```

Please restore the comment.



_Code quote:_
```XML
  // Take into account the VM execution resources of the current call, without inner calls.
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 554 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpnyLUsB9cZ8ieMTdKT:-NpnyLUsB9cZ8ieMTdKU:b755q94) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L554)):*
> ```XML
>         n_steps: 319,
>         n_memory_holes: 1,
>         builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 7)]),
> ```

Can you please verify the changes in this file? I.e. that the additional resources are indeed the addition of the syscall resources?
(please explain each change in this PR)



_Code quote:_
```XML
    let storage_entry_point_vm_resources = VmExecutionResources {
        n_steps: 319,
        n_memory_holes: 1,
        builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 7)]),
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpnoQ0-9XP-6-ILvU-G:-NpnoQ0-9XP-6-ILvU-H:bejx6gm) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/fee/os_usage.rs#L65)):*
> ```XML
> pub fn get_additional_os_syscall_resources(
>     syscall_counter: &SyscallCounter,
> ) -> Result<VmExecutionResources, PostExecutionError> {
> ```

Can you please explain this change?



_Code quote:_
```XML
) -> Result<VmExecutionResources, PostExecutionError> {
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1733 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpnxpEl9s11hZ43lPyA:-NpnxpEl9s11hZ43lPyB:b-hcw9cy) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/transaction/transactions_test.rs#L1733)):*
> ```XML
>         (abi_constants::L1_GAS_USAGE.to_string(), expected_gas_usage),
>         (abi_constants::BLOB_GAS_USAGE.to_string(), expected_blob_gas_usage),
>     ]));
> ```

It remained the same, great! 



_Code quote:_
```XML
    let expected_resource_mapping = ResourcesMapping(HashMap::from([
        (HASH_BUILTIN_NAME.to_string(), 11 + payload_size),
        (abi_constants::N_STEPS_RESOURCE.to_string(), 1416),
        (RANGE_CHECK_BUILTIN_NAME.to_string(), 23),
        (abi_constants::L1_GAS_USAGE.to_string(), expected_gas_usage),
        (abi_constants::BLOB_GAS_USAGE.to_string(), expected_blob_gas_usage),
    ]));
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1412)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @OriStarkware)

___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 249 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpoXIWA2RfFTqg7GNpS:-NpoXIWA2RfFTqg7GNpT:b9qrqvj) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L249)):*
> ```XML
>         &get_additional_os_syscall_resources(&syscall_handler.syscall_counter)?;
> 
>     let full_call_vm_resources = &syscall_handler.resources.vm_resources - &previous_vm_resources;
> ```

And please add a TODO to rename `vm_resources` -> `execution_resources`.



_Suggestion:_
```XML
   let full_call_resources = &syscall_handler.resources.vm_resources - &previous_vm_resources;
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1412)* status: 4 of 9 files reviewed, 14 unresolved discussions (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 238 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-Np_H1Xc-4aZviVUKdoC:-NpofUSaEJ6lF3aLKqyj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2e1de3643cbb6783990ed5371f35c1355a3114cf/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L238)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please restore the comment.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 249 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpoXIWA2RfFTqg7GNpS:-NpofpBh36fpM25JthKM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L249)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And please add a TODO to rename `vm_resources` -> `execution_resources`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 141 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpohCVe6gjWRYHHeCFW:-NpohCVf0SFvroUPLUVQ:bd2w8ek) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L141)):*
> ```XML
>         n_memory_holes: 0,
>         builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 2)]),
>     };
> ```

Syscalls: {StorageRead: 1, StorageWrite: 1}
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpsNbiW26Didz3BeVA7:-NpsNbiW26Didz3BeVA8:bvdratf) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L153)):*
> ```XML
>         n_steps: 790,
>         n_memory_holes: 4,
>         builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 21)]),
> ```

Syscalls: {LibraryCall: 1}
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-Npohffx2jxPH44i503r:-Npohffx2jxPH44i503s:bvdratf) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L177)):*
> ```XML
>         n_memory_holes: 4,
>         builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 20)]),
>     };
> ```

Syscalls: {LibraryCall: 1}
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 232 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpoiPVQ9LdiJ560rb0K:-NpoiPVQ9LdiJ560rb0L:bu3wkxm) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L232)):*
> ```XML
>             n_steps: 218,
>             n_memory_holes: 0,
>             builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 2)]),
> ```

{StorageRead: 1, StorageWrite: 1}
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 252 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-Npoj-oN3qUE7xaK-eNu:-Npoj-oN3qUE7xaK-eNv:b-oqiyzr) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L252)):*
> ```XML
>             n_steps: 1017,
>             n_memory_holes: 4,
>             builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 23)]),
> ```

{StorageRead: 1, StorageWrite: 1, CallContract: 1}
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 554 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpnyLUsB9cZ8ieMTdKT:-NpojNDq0fY4-8niCY2m:b6al0hc) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L554)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please verify the changes in this file? I.e. that the additional resources are indeed the addition of the syscall resources?
(please explain each change in this PR)
</blockquote></details>

Syscalls: {StorageWrite: 1, StorageRead: 1}
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 571 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpojmzE4LTvEfpH6na5:-NpojmzE4LTvEfpH6na6:bg2s2ly) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L571)):*
> ```XML
>         n_steps: 1338,
>         n_memory_holes: 6,
>         builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 35)]),
> ```

Syscalls: {LibraryCall: 1, StorageWrite: 1, StorageRead: 1}
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 600 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpolH8G3cKMm8RyN1Fd:-NpolH8G3cKMm8RyN1Fe:b-w4unmi) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L600)):*
> ```XML
>         n_steps: 3370,
>         n_memory_holes: 16,
>         builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 87)]),
> ```

Syscalls: {StorageWrite: 2, StorageRead: 2, LibraryCall: 3}
___
*[`crates/blockifier/src/fee/os_usage.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-NpnoQ0-9XP-6-ILvU-G:-NpsJZZUE3-fz10VUIMU:b48z1oc) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/fee/os_usage.rs#L65)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain this change?
</blockquote></details>

We are now using this function in finalize_execution which returns PostExecutionError on error instead of calculate_tx_resources.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 303 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-Npt0XwZBJzTLQ0Etxia:-Npt0XwZBJzTLQ0Etxib:bbyxka) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/transaction/transactions_test.rs#L303)):*
> ```XML
>             n_steps:  822,
>             n_memory_holes:  4,
>             builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 21)]),
> ```

Syscalls: {CallContract: 1}
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 317 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-Npt4_th313NKPEG8hoO:-Npt4_th313NKPEG8hoP:b-s1us1g) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/transaction/transactions_test.rs#L317)):*
> ```XML
>             n_steps: 1106,
>             n_memory_holes: 5,
>             builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 28)]),
> ```

Syscalls: {CallContract: 1, GetCallerAddress: 1}
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1715 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1412#-Npt5TGH7xI8pQGf4RDT:-Npt5TGH7xI8pQGf4RDU:b-pt3myq) ([raw file](https://github.com/starkware-libs/blockifier/blob/00bcbaf1d5aa70a78201f3ae36a5a97a9b16ee28/crates/blockifier/src/transaction/transactions_test.rs#L1715)):*
> ```XML
>             n_steps: 232,
>             n_memory_holes: 1,
>             builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 6)]),
> ```

Syscalls: {StorageWrite: 1}

**Pull request merged**
