### PR TITLE
perf(execution): support executing tx chunks in the transfers benchmark

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/bench/blockifier_bench.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJCDISC2VG80_BF2nz:-NxJCDISC2VG80_BF2o-:b3zgeke) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L40)):*
> ```XML
>     let state = test_state(chain_info, BALANCE * 1000, &[(account_contract, N_ACCOUNTS)]);
>     let executor =
>         &mut TransactionExecutor::new(state, block_context, Default::default(), Default::default());
> ```

Define `TransactionExecutorConfig` explicitly and add a TOOD to enable concurrency
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJBfoQ47Wu-tNbTtpB:-NxJBfoQ47Wu-tNbTtpC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L84)):*
> ```XML
>         );
>         chunk.push(Transaction::AccountTransaction(account_tx));
>         recipient_account = random_generator.gen::<usize>() % accounts.len();
> ```





_Suggestion:_
```XML
    for _ in 0..CHUNK_SIZE {
        let recipient_account = random_generator.gen::<usize>() % accounts.len();
        let account_tx = generate_transfer(
            accounts,
            sender_account,
            recipient_account,
            nonce_manager,
            chain_info,
        );
        chunk.push(Transaction::AccountTransaction(account_tx));
```
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJA9JZA79lZViZfZWX:-NxJA9JZA79lZViZfZWY:b8b25vt) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L86)):*
> ```XML
>         recipient_account = random_generator.gen::<usize>() % accounts.len();
>     }
>     executor.execute_txs(chunk.as_slice(), CHARGE_FEE);
> ```

Why not?



_Suggestion:_
```XML
txs(&chunk, CHARGE_FEE);
```
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJCM4V4u3U0_wg01A8:-NxJCM4V4u3U0_wg01A9:bnertiw) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L86)):*
> ```XML
>         recipient_account = random_generator.gen::<usize>() % accounts.len();
>     }
>     executor.execute_txs(chunk.as_slice(), CHARGE_FEE);
> ```

Assert that you got CHUNK_SIZE results and all of them are OK + not reverted
(many things can go wrong - bad bouncer weights, concurrency bug...)

Also, please add a TODO to run the same txs concurrently on a new state, and compare state diff



_Suggestion:_
```XML
let results = executor.execute_txs(chunk.as_slice(), CHARGE_FEE);
...
```
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJAYgwCvVZYVX8Op2X:-NxJAYgxAy7kSIxRj37k:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L92)):*
> ```XML
>     accounts: &[ContractAddress],
>     sender_account: usize,
>     recipient_account: usize,
> ```





_Suggestion:_
```XML
    sender_index: usize,
    recipient_index: usize,
```
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJCmqb8ciMuk5HXUVG:-NxJCmqb8ciMuk5HXUVH:b-2tw0rx) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L128)):*
> ```XML
> 
> criterion_group!(benches, transfers_benchmark);
> criterion_main!(benches);
> ```

How does it work? how can I run it?



_Code quote:_
```XML
criterion_group!(benches, transfers_benchmark);
criterion_main!(benches);
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJBfoQ47Wu-tNbTtpB:-NxLjrvyA5JNqplSDSfm:bsqn0gh) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L84)):*
> ```XML
>         );
>         chunk.push(Transaction::AccountTransaction(account_tx));
>         recipient_account = random_generator.gen::<usize>() % accounts.len();
> ```

Is it better to use shadowing than mutable variables?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJCmqb8ciMuk5HXUVG:-NxLkIoY1A0mFSXBXfvD:b-1b5h6z) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L128)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

How does it work? how can I run it?
</blockquote></details>

There's a short explanation at the start of the file.
`cargo bench --bench blockifier_bench`
it also generates a detailed report in:
`./target/criterion/report/transfers/`

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJCmqb8ciMuk5HXUVG:-NxLlP8s4iSKuZeirIjX:btfhqv3) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L128)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

There's a short explanation at the start of the file.
`cargo bench --bench blockifier_bench`
it also generates a detailed report in:
`./target/criterion/report/transfers/`
</blockquote></details>

To get consistent results, you have to run the command without other processes running on your laptop (I think chrome and slack are the big ones that need to be closed).

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJBfoQ47Wu-tNbTtpB:-NxLoDbW29q-F2zmrg9v:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L84)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Is it better to use shadowing than mutable variables?
</blockquote></details>

Done.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/bench/blockifier_bench.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJCDISC2VG80_BF2nz:-NxLo5MX6QrHyB36sNVG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L40)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Define `TransactionExecutorConfig` explicitly and add a TOOD to enable concurrency
</blockquote></details>

Done.
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJA9JZA79lZViZfZWX:-NxLmhvgCUFyjlngByWp:b-m24o05) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L86)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

Because I don't know rust :(
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJCM4V4u3U0_wg01A8:-NxLn86Q1bsGywceVXKV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L86)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Assert that you got CHUNK_SIZE results and all of them are OK + not reverted
(many things can go wrong - bad bouncer weights, concurrency bug...)

Also, please add a TODO to run the same txs concurrently on a new state, and compare state diff
</blockquote></details>

Done.
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJAYgwCvVZYVX8Op2X:-NxLmoBV2w0LUv9ilCmx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L92)):*
> ```XML
>     accounts: &[ContractAddress],
>     sender_account: usize,
>     recipient_account: usize,
> ```

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/bench/blockifier_bench.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJBfoQ47Wu-tNbTtpB:-NxLpas2EXstrv6xfSWv:b-3204ta) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L84)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In this case, I think so, yes.
And it's consistent with the `let account_tx`
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJCmqb8ciMuk5HXUVG:-NxLqgn143ROX9fs1uJ8:b-zcjvte) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L128)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

To get consistent results, you have to run the command without other processes running on your laptop (I think chrome and slack are the big ones that need to be closed).
</blockquote></details>

Thanks
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLqmL32LOe2C1Sfi07:-NxLqmL32LOe2C1Sfi08:byjwo37) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L69)):*
> ```XML
> 
> fn execute_chunk_of_transfers(
>     sender_index: usize,
> ```

Hmmm, this makes the entire chunk unparallelizable (nonce). 



_Code quote:_
```XML
fn execute_chunk_of_transfers(
    sender_index: usize,
```
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLpzftBhmrdBhvpRY6:-NxLpzftBhmrdBhvpRY7:b42sf1u) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L85)):*
> ```XML
>     let results = executor.execute_txs(&chunk, CHARGE_FEE);
>     for result in results {
>         assert!(result.is_ok());
> ```

(Check that the tx is not reverted)



_Suggestion:_
```XML
assert!(result.is_ok_and(|execution_info| execution_info.revert_error.is_none()));
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: all files reviewed, 7 unresolved discussions (waiting on @avi-starkware)

___
*[`crates/blockifier/bench/blockifier_bench.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxMOLhT5NPT5WIOVG6X:-NxMOLhT5NPT5WIOVG6Y:b-elhr1h) ([raw file](https://github.com/starkware-libs/blockifier/blob/f8d578b48a9bf7c7dd7e7ff064aa4d95e64b12f8/crates/blockifier/bench/blockifier_bench.rs#L31)):*
> ```XML
> const RANDOMIZATION_SEED: u64 = 0;
> const CHARGE_FEE: bool = false;
> const RUN_VALIDATION: bool = false;
> ```

I know it's not possible given the current api, but I'm wondering if it's something we will be interested in.



_Code quote:_
```XML
const RUN_VALIDATION: bool = false;
```
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxMKO2C0JevNY8kTZA6:-NxMKO2C0JevNY8kTZA7:bh86lf9) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L43)):*
> ```XML
>     let executor_config = TransactionExecutorConfig::default();
>     let executor =
>         &mut TransactionExecutor::new(state, block_context, Default::default(), executor_config);
> ```

Is the default value good for us?



_Suggestion:_
```XML
    let executor =
        &mut TransactionExecutor::new(state, block_context, BouncerConfig::max(), executor_config);
```
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxMMx8A3O4L5EkjZbYw:-NxMMx8A3O4L5EkjZbYx:b6zsfyo) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L103)):*
> ```XML
> 
>     let entry_point_selector =
>         selector_from_name(blockifier::transaction::constants::TRANSFER_ENTRY_POINT_NAME);
> ```

And import `blockifier::transaction::constants`



_Suggestion:_
```XML
        selector_from_name(constants::TRANSFER_ENTRY_POINT_NAME);
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: all files reviewed, 6 unresolved discussions (waiting on @avi-starkware)

___
*[`crates/blockifier/bench/blockifier_bench.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxMKO2C0JevNY8kTZA6:-NxMcfTG5_1pX6QtI92D:bpbgvk3) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L43)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is the default value good for us?
</blockquote></details>

Should not be good.
@avi-starkware assert that the number of results equals the chunk size. This should fail (you should get 0 results)
then, fix Noa's comment

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLqmL32LOe2C1Sfi07:-NxMdzdT07lC4K3PiUDs:b14x5pb) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L69)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Hmmm, this makes the entire chunk unparallelizable (nonce).
</blockquote></details>

It doesn't. The sender is incremented each transaction.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/bench/blockifier_bench.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLqmL32LOe2C1Sfi07:-NxMjE5I0kw5_HA3_Kk9:bh3sihs) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L69)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

It doesn't. The sender is incremented each transaction.
</blockquote></details>

It looks like it's the same sender for the entire chunk

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLqmL32LOe2C1Sfi07:-NxMhIHiE_Q1CwwEB6_v:bsqy4x2) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L69)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

It doesn't. The sender is incremented each transaction.
</blockquote></details>

Actually, now I fixed it. I removed the line incrementing the sender_index by accident when moving code around.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxMKO2C0JevNY8kTZA6:-NxMkAMm1vN6hfsrkHYa:b-f5whcm) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L43)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Should not be good.
@avi-starkware assert that the number of results equals the chunk size. This should fail (you should get 0 results)
then, fix Noa's comment
</blockquote></details>

Done.

The assert works with both options though.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxJBfoQ47Wu-tNbTtpB:-NxMeFgr5PIEeQWBgQnn:b-837i3v) ([raw file](https://github.com/starkware-libs/blockifier/blob/3e18d47cfb87c08eb3761cf1a48481b1b13be0be/crates/blockifier/bench/blockifier_bench.rs#L84)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

In this case, I think so, yes.
And it's consistent with the `let account_tx`
</blockquote></details>

Okay.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/bench/blockifier_bench.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLpzftBhmrdBhvpRY6:-NxMkRGyEXJGMsVQuXjZ:b-9su95m) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L85)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(Check that the tx is not reverted)
</blockquote></details>

result.is_ok() panics for some reason. Trying to figure it out...
___
*[`crates/blockifier/bench/blockifier_bench.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxMMx8A3O4L5EkjZbYw:-NxMfeNQ4-4L5EzuPZpn:bctiwte) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L103)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And import `blockifier::transaction::constants`
</blockquote></details>

This is the only constant used in the file, so I can import the constant directly.

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/bench/blockifier_bench.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLpzftBhmrdBhvpRY6:-NxMm6bV96hkxAe-zod_:b7m9hb4) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L85)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

result.is_ok() panics for some reason. Trying to figure it out...
</blockquote></details>

TransactionTooLarge?
Should be resolved after changing to `BouncerConfig::max()`

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLpzftBhmrdBhvpRY6:-NxMq5Nn8ILMmBOY9B3U:b-pzs09p) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L85)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

TransactionTooLarge?
Should be resolved after changing to `BouncerConfig::max()`
</blockquote></details>

It failed validation. Changing it to account without validation makes it work. (The previous version of this benchmark had `RUN_VALIDATION = false`, so no validation as well...)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/bench/blockifier_bench.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLpzftBhmrdBhvpRY6:-NxMuujZBZItNucfc_B3:bnyj9bf) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L85)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

It failed validation. Changing it to account without validation makes it work. (The previous version of this benchmark had `RUN_VALIDATION = false`, so no validation as well...)
</blockquote></details>

What's the specific error?

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-:-NxMv4Ax4tjIKO5Y5U90:bnfp4nl)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLpzftBhmrdBhvpRY6:-NxMw9Xi9BPYq7itamaZ:b-e0jlm) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L85)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What's the specific error?
</blockquote></details>

```
    Err(TransactionExecutionError(ValidateTransactionError {
        error: CairoRunError(VmException(VmException {
            pc: 71,
            inst_location: None,
            inner_exc: UnfinishedExecution,
            error_attr_value: None,
            traceback: Some(
                "Cairo traceback (most recent call last):\nUnknown location (pc=0:73)\nUnknown \
                 location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location \
                 (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown \
                 location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location \
                 (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown \
                 location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location \
                 (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown \
                 location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location \
                 (pc=0:73)\nUnknown location (pc=0:73)\n",
            ),
        })),
        class_hash: ClassHash(StarkFelt(
            "0x0000000000000000000000000000000000000000000000000000000000010000",
        )),
        storage_address: ContractAddress(PatriciaKey(StarkFelt(
            "0x0000000000000000000000000000000000000000000000000000000040010000",
        ))),
        selector: EntryPointSelector(StarkFelt(
            "0x0162da33a4585851fe8d3af3c2a9c60b557814e221e0d4f30ff0b2189d9c7775",
        )),
    }));
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/bench/blockifier_bench.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxMOLhT5NPT5WIOVG6X:-NxMwTR48SHIGUkoKGDS:b-xp2wo1) ([raw file](https://github.com/starkware-libs/blockifier/blob/f8d578b48a9bf7c7dd7e7ff064aa4d95e64b12f8/crates/blockifier/bench/blockifier_bench.rs#L31)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I know it's not possible given the current api, but I'm wondering if it's something we will be interested in.
</blockquote></details>

We can do it by using an account without validation.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/bench/blockifier_bench.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1883#-NxLpzftBhmrdBhvpRY6:-NxMxPow0DkvI_GTdTDa:bysa46e) ([raw file](https://github.com/starkware-libs/blockifier/blob/74643363d515d246a8871b634a20b96037339649/crates/blockifier/bench/blockifier_bench.rs#L85)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

```
    Err(TransactionExecutionError(ValidateTransactionError {
        error: CairoRunError(VmException(VmException {
            pc: 71,
            inst_location: None,
            inner_exc: UnfinishedExecution,
            error_attr_value: None,
            traceback: Some(
                "Cairo traceback (most recent call last):\nUnknown location (pc=0:73)\nUnknown \
                 location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location \
                 (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown \
                 location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location \
                 (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown \
                 location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location \
                 (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown \
                 location (pc=0:73)\nUnknown location (pc=0:73)\nUnknown location \
                 (pc=0:73)\nUnknown location (pc=0:73)\n",
            ),
        })),
        class_hash: ClassHash(StarkFelt(
            "0x0000000000000000000000000000000000000000000000000000000000010000",
        )),
        storage_address: ContractAddress(PatriciaKey(StarkFelt(
            "0x0000000000000000000000000000000000000000000000000000000040010000",
        ))),
        selector: EntryPointSelector(StarkFelt(
            "0x0162da33a4585851fe8d3af3c2a9c60b557814e221e0d4f30ff0b2189d9c7775",
        )),
    }));
```
</blockquote></details>

Oh, `AccountWithLongValidate` :)
So it should fail, ok

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1883)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
