### PR TITLE
Fix resouce representation

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1078)

### CODE REVIEW

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1078#-:-NiUUBh45tvWR6dVpiOG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1078)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1078#-NiU_xGN-gw2dlk_lFVG:-NiU_xGN-gw2dlk_lFVH:bk8blhc) ([raw file](https://github.com/starkware-libs/blockifier/blob/d46d3eca419d6179a8810c2646a9ddd9cb89cda9/crates/blockifier/src/execution/syscalls/hint_processor.rs#L114)):*
> ```XML
> pub const L1_GAS: &str = "0x00000000000000000000000000000000000000000000000000004C315F474153";
> // "L2_GAS";
> pub const L2_GAS: &str = "0x00000000000000000000000000000000000000000000000000004C325F474153";
> ```

Why use capital letters?



_Code quote:_
```XML
// "L1_GAS";
pub const L1_GAS: &str = "0x00000000000000000000000000000000000000000000000000004C315F474153";
// "L2_GAS";
pub const L2_GAS: &str = "0x00000000000000000000000000000000000000000000000000004C325F474153";
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 331 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1078#-NiUaGf81iYe_uBPK1Dw:-NiUaGf81iYe_uBPK1Dx:b-kmkk3q) ([raw file](https://github.com/starkware-libs/blockifier/blob/d46d3eca419d6179a8810c2646a9ddd9cb89cda9/crates/blockifier/src/execution/syscalls/hint_processor.rs#L331)):*
> ```XML
>                 let resource = match resource {
>                     Resource::L1Gas => stark_felt!(L1_GAS),
>                     Resource::L2Gas => stark_felt!(L2_GAS),
> ```

To be consistent with the other cases in the code where we convert a hex string to a `StarkFelt`. Is it possible in a closure?
`stark_felt!` can panic (it's not necessarily bad, but worth noticing).



_Suggestion:_
```XML
                    Resource::L1Gas => StarkFelt::try_from(L1_GAS).map_err(SyscallExecutionError::from)?;
                    Resource::L2Gas => StarkFelt::try_from(L1_GAS).map_err(SyscallExecutionError::from)?;
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1078)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 331 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1078#-NiUaGf81iYe_uBPK1Dw:-NiV9iIu3ylrsb0WiC_8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d46d3eca419d6179a8810c2646a9ddd9cb89cda9/crates/blockifier/src/execution/syscalls/hint_processor.rs#L331)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

To be consistent with the other cases in the code where we convert a hex string to a `StarkFelt`. Is it possible in a closure?
`stark_felt!` can panic (it's not necessarily bad, but worth noticing).
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1078#-:-NiVAbdU-9BdDsUmiuwG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
