### PR TITLE
feat(concurrency, state): add is_declared to StateReader

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1767)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1767)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/state_api.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv1VxZNCoT5ckHrq2B6:-Nv1VxZNCoT5ckHrq2B7:bl5cak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/state_api.rs#L67)):*
> ```XML
> 
>     fn is_declared(&self, class_hash: ClassHash) -> bool {
>         self.get_compiled_contract_class(class_hash).is_ok()
> ```

Nice. 
The only problem might be if we get `StateReadError`. In that case we want to "throw" it and it does not necessarily mean that the class is not declared.



_Code quote:_
```XML
        self.get_compiled_contract_class(class_hash).is_ok()
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1767)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv5mwAT0fyHxC30jKWQ:-Nv5mwAT0fyHxC30jKWR:bpd47a0) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/cached_state.rs#L294)):*
> ```XML
>         self.get_compiled_contract_class(class_hash).is_ok()
>     }
> }
> ```

I feel like it should be completely symmetric to the other getters. No reason to break this pattern



_Suggestion:_
```XML
    fn is_declared(&self, class_hash: ClassHash) -> bool {
        let mut cache = self.cache.borrow_mut();

        if cache.is_declared(class_hash).is_none() {
            let is_declared = self.state.is_declared(class_hash)?;
            cache.set_is_declared_initial_value(class_hash, is_declared);
        }

        let is_declared = cache
            .is_declared(class_hash)
            .unwrap_or_else(|| panic!("Cannot retrieve '{class_hash:?}' from the cache."));
        Ok(*is_declared)
    }
    }
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 342 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv5o3xq9Ga5_W8pOUnW:-Nv5o3xq9Ga5_W8pOUnX:buq9fxp) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/cached_state.rs#L342)):*
> ```XML
>         // Update the contract_class_writes cache as well.
>         let mut cache = self.cache.borrow_mut();
>         cache.set_contract_class_write(class_hash, true);
> ```

No one can write "false" to this mapping



_Suggestion:_
```XML
cache.declare(class_hash);
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv5p91Y7Hk7AeWz9s8d:-Nv5p91Y7Hk7AeWz9s8e:b-sjy0mm) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/cached_state.rs#L353)):*
> ```XML
>         self.cache.get_mut().set_compiled_class_hash_write(class_hash, compiled_class_hash);
>         Ok(())
>     }
> ```

An `is_declared` check must precede these setters

Also, consider hiding these setters, and exposing instead `declare_cairo0`, `declare_cairo1`



_Code quote:_
```XML
    fn set_contract_class(
        &mut self,
        class_hash: ClassHash,
        contract_class: ContractClass,
    ) -> StateResult<()> {
        self.class_hash_to_class.get_mut().insert(class_hash, contract_class);
        // Update the contract_class_writes cache as well.
        let mut cache = self.cache.borrow_mut();
        cache.set_contract_class_write(class_hash, true);
        Ok(())
    }

    fn set_compiled_class_hash(
        &mut self,
        class_hash: ClassHash,
        compiled_class_hash: CompiledClassHash,
    ) -> StateResult<()> {
        self.cache.get_mut().set_compiled_class_hash_write(class_hash, compiled_class_hash);
        Ok(())
    }
```
___
*[`crates/blockifier/src/state/state_api.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv1VxZNCoT5ckHrq2B6:-Nv5oDs1-WazvKNZFuWZ:b-gpr2u9) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/state_api.rs#L67)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Nice. 
The only problem might be if we get `StateReadError`. In that case we want to "throw" it and it does not necessarily mean that the class is not declared.
</blockquote></details>

I think it's worth hiding this implementation.
I.e., keep it unimplemented here and implement it just for root readers (e.g., papyrus).

Papyrus has thin tables to answer this question, in the future (not now) we may be able to implement it differently

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1767)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv5p91Y7Hk7AeWz9s8d:-Nv6YkzB0w0XNxKW84Xz:btbxxyc) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/cached_state.rs#L353)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Interesting. 
Note- the `is_declared` check must appear in every implantation of `declare_cairo1`. We currently check it one time [here](https://github.com/starkware-libs/blockifier/blob/2c67cc01d48e4f7b253ce1d858987f0059308824/crates/blockifier/src/transaction/transactions.rs#L189).
</blockquote></details>

Oh, so we can put the this impl in `State` trait, and mark these setters as private

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1767)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-NvB8GSM0w1AlAyOVl3J):*




_Suggestion:_
```
feat(concurrency, state): add is_declared to StateReader
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1767)* status: all files reviewed, 5 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv5p91Y7Hk7AeWz9s8d:-NvRpOhIDTf45UFO6pFk:b-vlpusy) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/cached_state.rs#L353)):*
> mark these setters as private

WDYM?
If the trait is public, then all of it's methods are public.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1767)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv5p91Y7Hk7AeWz9s8d:-NvRz7quEl_oL0b8QS9l:b-wbtczx) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/cached_state.rs#L353)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

> mark these setters as private

WDYM?
If the trait is public, then all of it's methods are public.
</blockquote></details>

Oh, so NVM

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1767)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-NvB8GSM0w1AlAyOVl3J):*
Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv5mwAT0fyHxC30jKWQ:-NvX3mP15Qw__6_hb8cA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/cached_state.rs#L294)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I feel like it should be completely symmetric to the other getters. No reason to break this pattern
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 342 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv5o3xq9Ga5_W8pOUnW:-NvX3oaE3hVo3_rYYJNt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/cached_state.rs#L342)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No one can write "false" to this mapping
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/state_api.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv1VxZNCoT5ckHrq2B6:-NvWuiJi1DZda7ghkMWk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8754f2ab2acad02a302239543a9c1e8b6e696f36/crates/blockifier/src/state/state_api.rs#L67)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think it's worth hiding this implementation.
I.e., keep it unimplemented here and implement it just for root readers (e.g., papyrus).

Papyrus has thin tables to answer this question, in the future (not now) we may be able to implement it differently
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1767)* status: all files reviewed, 7 unresolved discussions (waiting on @barak-b-starkware, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv_bEuk15_ol0Lx1E-6:-Nv_bEuk15_ol0Lx1E-7:biowa2f) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f12abdc85fc516214ef5373aad4664ece110367/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L277)):*
> ```XML
>     fn is_declared(&self, class_hash: ClassHash) -> bool {
>         self.get_compiled_contract_class(class_hash).is_ok()
>     }
> ```

The implantation will change one we add the declared contract mapping, right?



_Code quote:_
```XML
    fn is_declared(&self, class_hash: ClassHash) -> bool {
        self.get_compiled_contract_class(class_hash).is_ok()
    }
```
___
*[`crates/native_blockifier/src/state_readers/papyrus_state.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv_e1k64nl9CeS_T7ER:-Nv_e1k73S42T2I017JH:b-gahgnv) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f12abdc85fc516214ef5373aad4664ece110367/crates/native_blockifier/src/state_readers/papyrus_state.rs#L141)):*
> ```XML
> 
>     fn is_declared(&self, class_hash: ClassHash) -> bool {
>         self.get_compiled_contract_class(class_hash).is_ok()
> ```

I wonder what we want to return in case of a `StateReadError` (does it mean the class was not declared?).
Maybe it's better to "throw" it.



_Code quote:_
```XML
        self.get_compiled_contract_class(class_hash).is_ok()
```
___
*[`crates/native_blockifier/src/state_readers/py_state_reader.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1767#-Nv_eVZs9ve_rOwgr6wr:-Nv_eVZs9ve_rOwgr6ws:bmiytp9) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f12abdc85fc516214ef5373aad4664ece110367/crates/native_blockifier/src/state_readers/py_state_reader.rs#L99)):*
> ```XML
>     fn is_declared(&self, class_hash: ClassHash) -> bool {
>         self.get_compiled_contract_class(class_hash).is_ok()
>     }
> ```

Why is it different than the above implantation? 



_Code quote:_
```XML
    fn is_declared(&self, class_hash: ClassHash) -> bool {
        self.get_compiled_contract_class(class_hash).is_ok()
    }
```

**Pull request closed without merging**
