### PR TITLE
fix: update the tx event limit constants

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1517)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
corresponding Python PR :https://github.com/starkware-industries/starkware/pull/34011

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-:-NqgCtO35sJmbHWOEEby:b-ft3a5w)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @elintul)

**Review by Yael-Starkware — COMMENTED** [review]
I renamed event_size_limit to tx_event_size_limit , because there are also block event limits and I wanted to make it clear which one we talking about.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-:-NqgIPBR-UbrxyV0ccKF:b-rm4vsw)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1517)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqhNwbM9-sfwqv07HRK:-NqhNwbNBM3q75iMafH9:bqm4vzk) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fd08294da7542cea0a7450d671732721ea87ba8/crates/blockifier/src/versioned_constants.rs#L157)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, Deserialize)]
> pub struct TxEventSizeLimit {
> ```

I think the struct name is good, and we can embed the meaning (block/transaction) in the variable name.



_Code quote:_
```XML
TxEventSizeLimit
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqhOE115ROOWwKqbff_:-NqhOE115ROOWwKqbffa:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fd08294da7542cea0a7450d671732721ea87ba8/crates/blockifier/src/versioned_constants.rs#L157)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, Deserialize)]
> pub struct TxEventSizeLimit {
> ```





_Suggestion:_
```XML
EventLimits
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqhO5DN6j7IDHyx3lqv:-NqhO5DN6j7IDHyx3lqw:b-cvsa1x) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fd08294da7542cea0a7450d671732721ea87ba8/crates/blockifier/src/execution/syscalls/mod.rs#L296)):*
> ```XML
>     n_emitted_events: usize,
>     event: &EventContent,
> ) -> Result<(), EmitEventError> {
> ```

Please define an `tx_event_limits` variable.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1517)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/versioned_constants.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqhOE115ROOWwKqbff_:-NquqQIL89u5R15Cs1Gm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fd08294da7542cea0a7450d671732721ea87ba8/crates/blockifier/src/versioned_constants.rs#L157)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, Deserialize)]
> pub struct TxEventSizeLimit {
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqhO5DN6j7IDHyx3lqv:-NquqRbUElytcJHRQVFE:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fd08294da7542cea0a7450d671732721ea87ba8/crates/blockifier/src/execution/syscalls/mod.rs#L296)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please define an `tx_event_limits` variable.
</blockquote></details>

done

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1517)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 2 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqvMPVDBKIFxAWVFDDj:-NqvMPVDBKIFxAWVFDDk:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f39a380e56d8f2261ca4a25843806e5f6352c79f/crates/blockifier/resources/versioned_constants.json#L2)):*
> ```JSON
> {
>     "event_limits": {
> ```





_Suggestion:_
```JSON
tx_event_limits
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqvLwXW62WaNwGn4TZE:-NqvLwXW62WaNwGn4TZF:b8su6xx) ([raw file](https://github.com/starkware-libs/blockifier/blob/64a3e135100b47067caa68ffde0a083a022ebd25/crates/blockifier/src/versioned_constants.rs#L38)):*
> ```XML
> pub struct VersionedConstants {
>     // Limits.
>     pub tx_event_size_limit: TxEventSizeLimit,
> ```

Embedding the behavior in the variable name is good.



_Suggestion:_
```XML
tx_event_limits
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 297 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqvMAmv4oKLKWwBtIQC:-NqvMAmv4oKLKWwBtIQD:b-6snp3x) ([raw file](https://github.com/starkware-libs/blockifier/blob/f39a380e56d8f2261ca4a25843806e5f6352c79f/crates/blockifier/src/execution/syscalls/mod.rs#L297)):*
> ```XML
>     event: &EventContent,
> ) -> Result<(), EmitEventError> {
>     let tx_event_limits = versioned_constants.event_limits;
> ```

That's even better, in all locations possible.



_Suggestion:_
```XML
let EventLimits { max_data_length, max_keys_length, max_n_emitted_events } = versioned_constants.event_limits;
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1517)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/resources/versioned_constants.json` line 2 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqvMPVDBKIFxAWVFDDj:-NqwAJYb3Vs3BIKtRD4n:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/f39a380e56d8f2261ca4a25843806e5f6352c79f/crates/blockifier/resources/versioned_constants.json#L2)):*
> ```JSON
> {
>     "event_limits": {
> ```

done
___
*[`crates/blockifier/src/versioned_constants.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqvLwXW62WaNwGn4TZE:-NqwAIf-4ZEH2xvdTrgS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/64a3e135100b47067caa68ffde0a083a022ebd25/crates/blockifier/src/versioned_constants.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Embedding the behavior in the variable name is good.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 297 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-NqvMAmv4oKLKWwBtIQC:-NqwAI-h39l_9rRsw5Ho:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f39a380e56d8f2261ca4a25843806e5f6352c79f/crates/blockifier/src/execution/syscalls/mod.rs#L297)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

That's even better, in all locations possible.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1517#-:-NqwFxIm4qWjr1psP-Tj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1517)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1517)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
