### PR TITLE
refactor(execution, native_blockifier): make TransactionExecutor.execute() work w/o Py objects

### PR DESCRIPTION
**Pull request by barak-b-starkware**
… PyAny.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_validator.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-NpZzwDiCTjK6pwVB8je:-NpZzwDj6FQ-cWK73xkX:b1377d5) ([raw file](https://github.com/starkware-libs/blockifier/blob/10847fd3242e04876f5a9863fe84cec551c6ef76/crates/native_blockifier/src/py_validator.rs#L130)):*
> ```XML
>         tx: &PyAny,
>         raw_contract_class: Option<&str>,
>     ) -> NativeBlockifierResult<(RawTransactionExecutionInfo, PyBouncerInfo)> {
> ```

I think it's not necessary to return bytes in the validator.
You can keep the same return types as in `tx_executor.execute`



_Code quote:_
```XML
 ) -> NativeBlockifierResult<(RawTransactionExecutionInfo, PyBouncerInfo)> {
```

**Comment by barak-b-starkware** [comment]
*[`crates/native_blockifier/src/py_validator.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-NpZzwDiCTjK6pwVB8je:-Np_6czk5B9C8BrJpsCq:b6jqdph) ([raw file](https://github.com/starkware-libs/blockifier/blob/10847fd3242e04876f5a9863fe84cec551c6ef76/crates/native_blockifier/src/py_validator.rs#L130)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think it's not necessary to return bytes in the validator.
You can keep the same return types as in `tx_executor.execute`
</blockquote></details>

IIUC it was there before this PR, right? So maybe it should be fixed in another PR?

**Comment by barak-b-starkware** [comment]
*[`crates/native_blockifier/src/py_validator.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-NpZzwDiCTjK6pwVB8je:-Np_7LUO4C4rBNK3lezM:b-vwbkz) ([raw file](https://github.com/starkware-libs/blockifier/blob/10847fd3242e04876f5a9863fe84cec551c6ef76/crates/native_blockifier/src/py_validator.rs#L130)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

IIUC it was there before this PR, right? So maybe it should be fixed in another PR?
</blockquote></details>

It was changed by you [here](https://github.com/starkware-libs/blockifier/pull/1315)

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_validator.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-NpZzwDiCTjK6pwVB8je:-Np_8747DDSVHPauu2Ff:b-cwt5x7) ([raw file](https://github.com/starkware-libs/blockifier/blob/10847fd3242e04876f5a9863fe84cec551c6ef76/crates/native_blockifier/src/py_validator.rs#L130)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

It was changed by you [here](https://github.com/starkware-libs/blockifier/pull/1315)
</blockquote></details>

Correct, but in this PR you've modified the inner method of `tx_executor`. 
Given that the validator doesn't necessarily need to return bytes, you can simplify the code.

**Comment by barak-b-starkware** [comment]
*[`crates/native_blockifier/src/py_validator.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-NpZzwDiCTjK6pwVB8je:-Np_BREo2_Kx3oEbXeKi:b-ivm7sl) ([raw file](https://github.com/starkware-libs/blockifier/blob/10847fd3242e04876f5a9863fe84cec551c6ef76/crates/native_blockifier/src/py_validator.rs#L130)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Correct, but in this PR you've modified the inner method of `tx_executor`. 
Given that the validator doesn't necessarily need to return bytes, you can simplify the code.
</blockquote></details>

Got it! good idea! That way it can save code duplication.. thank you!

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_validator.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-Np_EehQ9YCpUHg9f_Ax:-Np_EehR5vwYdHqwfyQK:b-z8ise8) ([raw file](https://github.com/starkware-libs/blockifier/blob/96e9bc0350af445573dd8486c0bb54186d6a7181/crates/native_blockifier/src/py_validator.rs#L126)):*
> ```XML
> }
> 
> impl PyValidator {
> ```

Why did you move the impl?



_Code quote:_
```XML
impl PyValidator {
```

**Comment by barak-b-starkware** [comment]
*[`crates/native_blockifier/src/py_validator.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-Np_EehQ9YCpUHg9f_Ax:-Np_G6ErDOctVA-aqGQi:bt4dmmq) ([raw file](https://github.com/starkware-libs/blockifier/blob/96e9bc0350af445573dd8486c0bb54186d6a7181/crates/native_blockifier/src/py_validator.rs#L126)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why did you move the impl?
</blockquote></details>

I moved `fn execute()` to the `impl PyValidator` not decorated with the `#[pymethods]` since the Python code shouldn't be familiar with the `execute` method. The Python code is familiar with the `perform_validations`method that calls the `execute` method.

**Review by MohammadNassar1 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-:-Np_Imh1AQTyTR96mUio:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-:-Np_TJYL9FTIU7qbgsNX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-NprqQ3hAIE1iCuTP0RS:-NprqQ3iBpiqDlRAqlOF:bta0nby) (no related file):*
Python PR?

___

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-:-NpsO-5i3UxP3rYv2MQS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)

**Review by elintul — DISMISSED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/native_blockifier/src/py_validator.rs` line 149 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1414#-NptBHI418ZJuCs4-SJ-:-NptBHI418ZJuCs4-SJ0:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8ed5763d584d864eaf56e963e3d655f24d3861d/crates/native_blockifier/src/py_validator.rs#L149)):*
> ```XML
>         let tx: Transaction = py_tx(tx, raw_contract_class)?;
> 
>         self.tx_executor.execute(tx, limit_execution_steps_by_resource_bounds)
> ```





_Suggestion:_
```XML
        let tx: Transaction = py_tx(tx, raw_contract_class)?;
        self.tx_executor.execute(tx, limit_execution_steps_by_resource_bounds)
```

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Comment by barak-b-starkware** [comment]
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Python PR?
</blockquote></details>

https://reviewable.io/reviews/starkware-industries/starkware/33789

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
