### PR TITLE
refactor: change l2_resource_cost to to be of type ResourceCost (Ratio)

### PR DESCRIPTION
**Pull request by nimrod-starkware**
python PR-
https://github.com/starkware-industries/starkware/pull/34155

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1590)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1590)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1590#-Nr_f7Df71CqiWwihuvl:-NrimZhsExhVYvjZAcSd:b-9emiif) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa5810cc790ddbebc028c76180fdc1b9319c0ae0/crates/blockifier/src/fee/gas_usage.rs#L29)):*
> ```XML
>         .map(|call_info| get_events_gas_cost(&call_info.execution.events, versioned_constants))
>         .sum();
>     GasVector { l1_gas: l1_gas.to_integer(), l1_data_gas: 0 }
> ```

I think that it is a more accurate calculation. Since we are working with rational numbers, the latest we do the floor division the more accurate the calculation will be.
With your suggestion, we will sum over integers and not over rational numbers
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1590#-Nr_fD8XCI-f9A3FanBN:-NrintMQ4ei9WPccfYLg:b2ss7xm) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa5810cc790ddbebc028c76180fdc1b9319c0ae0/crates/blockifier/src/fee/gas_usage.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why change return type?
</blockquote></details>

see comment above
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1590#-Nr_fLlDDt_V5dnECG2K:-Nrinx5Q-cav0blgwTCP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa5810cc790ddbebc028c76180fdc1b9319c0ae0/crates/blockifier/src/fee/gas_usage.rs#L101)):*
> ```XML
>     let l1_gas = versioned_constants.l2_resource_gas_costs.gas_per_data_felt * total_data_size;
> 
>     GasVector { l1_gas: l1_gas.to_integer(), l1_data_gas: 0 }
> ```

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1590#-Nr_fRxsDB25ePWCr1Pw:-Nrinwjd6RPyv1prwFpS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa5810cc790ddbebc028c76180fdc1b9319c0ae0/crates/blockifier/src/fee/gas_usage.rs#L118)):*
> ```XML
>         );
>         let l1_gas = versioned_constants.l2_resource_gas_costs.gas_per_code_byte * total_code_size;
>         GasVector { l1_gas: l1_gas.to_integer(), l1_data_gas: 0 }
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1590)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1590#-Nr_f7Df71CqiWwihuvl:-NripkM8-vOKXTQ97kPx:bo43j35) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa5810cc790ddbebc028c76180fdc1b9319c0ae0/crates/blockifier/src/fee/gas_usage.rs#L29)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I think that it is a more accurate calculation. Since we are working with rational numbers, the latest we do the floor division the more accurate the calculation will be.
With your suggestion, we will sum over integers and not over rational numbers
</blockquote></details>

why? `sum` is called before `to_integer`.
my take is: `l1_gas` is always an integer, no reason to make it a rational even temporarily.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1590#-Nr_fD8XCI-f9A3FanBN:-Nriq4m_4dfUMk6tZPZF:bek6gkl) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa5810cc790ddbebc028c76180fdc1b9319c0ae0/crates/blockifier/src/fee/gas_usage.rs#L48)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

see comment above
</blockquote></details>

as above: "gas cost" can never be a rational. it is an amount of gas, there is no such thing as 0.5 gas. the return type should reflect this fact

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1590)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1590#-Nr_f7Df71CqiWwihuvl:-Nriuzz516VjKyZHGnWY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa5810cc790ddbebc028c76180fdc1b9319c0ae0/crates/blockifier/src/fee/gas_usage.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why? `sum` is called before `to_integer`.
my take is: `l1_gas` is always an integer, no reason to make it a rational even temporarily.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1590#-Nr_fD8XCI-f9A3FanBN:-Nriv02c5moi3q6TZAJA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa5810cc790ddbebc028c76180fdc1b9319c0ae0/crates/blockifier/src/fee/gas_usage.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

as above: "gas cost" can never be a rational. it is an amount of gas, there is no such thing as 0.5 gas. the return type should reflect this fact
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1590#-:-NriwVKvAA63vaEXZRMF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — DISMISSED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1590)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
