### PR TITLE
Syscall tests: Libraray Call

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/470)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #464** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/464" target="_blank">Graphite</a> 
    * **PR #465** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/465" target="_blank">Graphite</a> 
      * **PR #466** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/466" target="_blank">Graphite</a> 
        * **PR #469** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/469" target="_blank">Graphite</a> 
          * **PR #470** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/470" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/470?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/470)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/470#-NVU9bn_-YKJxEKRDtmK:-NVU9bn_-YKJxEKRDtmL:bmixj27) ([raw file](https://github.com/starkware-libs/blockifier/blob/a50b195f09d3ab639ededd8ea02280dd7400915e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L27)):*
> ```Cairo
>             function_selector,
>             calldata.span(),
>         ).unwrap_syscall().snapshot.clone()
> ```

Why clone?



_Code quote:_
```Cairo
.clone()
```
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/470#-NVU9ksHDVQ-SmsdGSd2:-NVU9ksHDVQ-SmsdGSd3:b-imkrdh) ([raw file](https://github.com/starkware-libs/blockifier/blob/a50b195f09d3ab639ededd8ea02280dd7400915e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L27)):*
> ```Cairo
>             function_selector,
>             calldata.span(),
>         ).unwrap_syscall().snapshot.clone()
> ```

What does that do?



_Code quote:_
```Cairo
unwrap_syscall
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/470)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/470#-NVU9bn_-YKJxEKRDtmK:-NVUMpXn6bgZTrJc-UuM:b-sb5o9n) ([raw file](https://github.com/starkware-libs/blockifier/blob/a50b195f09d3ab639ededd8ea02280dd7400915e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why clone?
</blockquote></details>

Cairo1 issues (involving Span) that I plan to solve in the future.
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/470#-NVU9ksHDVQ-SmsdGSd2:-NVUMuZCEGxt5_1k6q9O:b-8tkc3t) ([raw file](https://github.com/starkware-libs/blockifier/blob/a50b195f09d3ab639ededd8ea02280dd7400915e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does that do?
</blockquote></details>

Panic on failure

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/470)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/470#-NVU9ksHDVQ-SmsdGSd2:-NVXqyCl3l0zPOB4Tcq2:b-pzazqn) ([raw file](https://github.com/starkware-libs/blockifier/blob/a50b195f09d3ab639ededd8ea02280dd7400915e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L27)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Panic on failure
</blockquote></details>

What does panic in Cairo 1 mean?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/470)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/470#-NVU9ksHDVQ-SmsdGSd2:-NVcCl_hDXt34dwBSPDD:b-bu75k0) ([raw file](https://github.com/starkware-libs/blockifier/blob/a50b195f09d3ab639ededd8ea02280dd7400915e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does panic in Cairo 1 mean?
</blockquote></details>

each entry point returns PanicResult<Array<felt252>>. This is an enum with 2 variants, Ok and Err (like Result). Panic means that we unwind all the way to the entrypoint and return Err(err_data).

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/470)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/470#-NVU9ksHDVQ-SmsdGSd2:-NVcou--Bw5FSVQQFz7A:b-yv626b) ([raw file](https://github.com/starkware-libs/blockifier/blob/a50b195f09d3ab639ededd8ea02280dd7400915e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L27)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

each entry point returns PanicResult<Array<felt252>>. This is an enum with 2 variants, Ok and Err (like Result). Panic means that we unwind all the way to the entrypoint and return Err(err_data).
</blockquote></details>

Do we ever want to panic?

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/470#-:-NVcp-7r5KSpZ7oXcmrv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/470)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/470#-NVU9ksHDVQ-SmsdGSd2:-NVcsggn3v4JP6tGN26A:bk2n8l4) ([raw file](https://github.com/starkware-libs/blockifier/blob/a50b195f09d3ab639ededd8ea02280dd7400915e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we ever want to panic?
</blockquote></details>

Inside cairo code? Yes, it's a revert.

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/470).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/470) couldn't merge this pull request because a downstack PR #466 failed to merge.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/470#-:-NVd1Pim480vlW811foH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/470#-:-NVdo0KLBJGZ9wy6OxOp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
