### PR TITLE
feat(concurrency): update sequencer balance in storage

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)

### CODE REVIEW

**Comment by avi-starkware** [comment]
Why not add this method in the original PR?

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxILGEL6JIBi2Njtzhj:-NxILGEL6JIBi2Njtzhk:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9bd3d80fd6ea6267b63c97b0f834e6aa822a612d/crates/blockifier/src/concurrency/worker_logic.rs#L13)):*
> ```XML
> use crate::transaction::objects::TransactionExecutionInfo;
> 
> fn _add_fee_to_sequencer_balance(
> ```





_Suggestion:_
```XML
fn _finalize_commit(
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxIMNsD78SsftJ47tEY:-NxIMNsD78SsftJ47tEZ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9bd3d80fd6ea6267b63c97b0f834e6aa822a612d/crates/blockifier/src/concurrency/worker_logic.rs#L17)):*
> ```XML
>     pinned_versioned_state: &VersionedStateProxy<impl StateReader>,
>     tx_info: &TransactionExecutionInfo,
>     transactional_state: &mut CachedState<impl StateReader>,
> ```





_Suggestion:_
```XML
    fee_token_address: &ContractAddress,
    pinned_versioned_state: &VersionedStateProxy<impl StateReader>,
    actual_fee: &Fee,
    transactional_state: &mut CachedState<impl StateReader>,
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxILPYb4DSwlKwRyBz_:-NxILPYb4DSwlKwRyBza:bal65qk) ([raw file](https://github.com/starkware-libs/blockifier/blob/9bd3d80fd6ea6267b63c97b0f834e6aa822a612d/crates/blockifier/src/concurrency/worker_logic.rs#L20)):*
> ```XML
> ) -> StateResult<()> {
>     let seq_balance_key = get_fee_token_var_address(tx_context.fee_token_address());
>     let seq_balance_value =
> ```

The common practice is to use complete words (the only broad exception is "tx" instead of "transaction").



_Suggestion:_
```XML
    let sequencer_balance_key = get_fee_token_var_address(tx_context.fee_token_address());
    let sequencer_balance_value =
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxILGEL6JIBi2Njtzhj:-NxLhwcJ2fwIPUM2Ageu:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9bd3d80fd6ea6267b63c97b0f834e6aa822a612d/crates/blockifier/src/concurrency/worker_logic.rs#L13)):*
> ```XML
> use crate::transaction::objects::TransactionExecutionInfo;
> 
> fn _add_fee_to_sequencer_balance(
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxIMNsD78SsftJ47tEY:-NxLhwyt9kGwytf533q8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9bd3d80fd6ea6267b63c97b0f834e6aa822a612d/crates/blockifier/src/concurrency/worker_logic.rs#L17)):*
> ```XML
>     pinned_versioned_state: &VersionedStateProxy<impl StateReader>,
>     tx_info: &TransactionExecutionInfo,
>     transactional_state: &mut CachedState<impl StateReader>,
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxILPYb4DSwlKwRyBz_:-NxLhxK-B1DYmjBUpaBX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9bd3d80fd6ea6267b63c97b0f834e6aa822a612d/crates/blockifier/src/concurrency/worker_logic.rs#L20)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

The common practice is to use complete words (the only broad exception is "tx" instead of "transaction").
</blockquote></details>

Done.

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxNEzjR6Ye4-YCG9EQX:-NxNEzjR6Ye4-YCG9EQY:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec1a510a66f38e9caa9ff38f96b8fb2e6b28b4ec/crates/blockifier/src/concurrency/worker_logic.rs#L12)):*
> ```XML
> 
> fn _finalize_commit(
>     fee_token_adress: ContractAddress,
> ```





_Suggestion:_
```XML
fee_token_address: ContractAddress,
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxRDhIW7epBbLcvCM9S:-NxRDhIW7epBbLcvCM9T:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec1a510a66f38e9caa9ff38f96b8fb2e6b28b4ec/crates/blockifier/src/concurrency/worker_logic.rs#L13)):*
> ```XML
> fn _finalize_commit(
>     fee_token_adress: ContractAddress,
>     pinned_versioned_state: &VersionedStateProxy<impl StateReader>,
> ```





_Suggestion:_
```XML
tx_versioned_state:
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxILGEL6JIBi2Njtzhj:-NxSIqGt-qHNs364VJJM:b-frfpky) ([raw file](https://github.com/starkware-libs/blockifier/blob/9bd3d80fd6ea6267b63c97b0f834e6aa822a612d/crates/blockifier/src/concurrency/worker_logic.rs#L13)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I liked the former name. It's more informative. 
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxSKs3E75PWldOK6zRf:-NxSKs3E75PWldOK6zRg:bmo1ng0) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec1a510a66f38e9caa9ff38f96b8fb2e6b28b4ec/crates/blockifier/src/concurrency/worker_logic.rs#L20)):*
> ```XML
>     let sequencer_balance_value =
>         pinned_versioned_state.get_storage_at(fee_token_adress, sequencer_balance_key)?;
>     let value = stark_felt_to_felt(sequencer_balance_value) + Felt252::from(actual_fee.0);
> ```

What will happen in case of overflow?



_Code quote:_
```XML
let value = stark_felt_to_felt(sequencer_balance_value) + Felt252::from(actual_fee.0);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxSL4_24f15WhQiaYSU:-NxSL4_35ZkCRNUidDzA:b70mndr) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec1a510a66f38e9caa9ff38f96b8fb2e6b28b4ec/crates/blockifier/src/concurrency/worker_logic.rs#L25)):*
> ```XML
>         sequencer_balance_key,
>         felt_to_stark_felt(&value),
>     )?;
> ```

Why update the transactional state?
This need to be done on the shared versioned state (using `apply_writes`).



_Code quote:_
```XML
    transactional_state.set_storage_at(
        fee_token_adress,
        sequencer_balance_key,
        felt_to_stark_felt(&value),
    )?;
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxNEzjR6Ye4-YCG9EQX:-NxgzPheC6VRIpZyreLp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec1a510a66f38e9caa9ff38f96b8fb2e6b28b4ec/crates/blockifier/src/concurrency/worker_logic.rs#L12)):*
> ```XML
> 
> fn _finalize_commit(
>     fee_token_adress: ContractAddress,
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxSLz4UDVvFgf_sqWoY:-NxgzQsmDD7gDCAnR2st:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec1a510a66f38e9caa9ff38f96b8fb2e6b28b4ec/crates/blockifier/src/concurrency/worker_logic.rs#L15)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxSLVw371xR9RIacGbZ:-NxgzX-fCYWpSA5qBIkX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec1a510a66f38e9caa9ff38f96b8fb2e6b28b4ec/crates/blockifier/src/concurrency/worker_logic.rs#L19)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Following our discussion: Note that if the transaction wrote to this cell we will not read this value.
Consider the ERC20 account. Assume it sends a transaction that writes to the sequencer balance (without reading it before). 
Which value do we want to read here?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxSL4_24f15WhQiaYSU:-Nxgzb4e2IDE25gSpquC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec1a510a66f38e9caa9ff38f96b8fb2e6b28b4ec/crates/blockifier/src/concurrency/worker_logic.rs#L25)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why update the transactional state?
This need to be done on the shared versioned state (using `apply_writes`).
</blockquote></details>

Done.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-Nxh7x8DCMWo_EuTehge:-Nxh7x8DCMWo_EuTehgf:b-14bw2c) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d102395d7ff42792ad2247b37692cc1ee1317e7/crates/blockifier/src/concurrency/worker_logic.rs#L34)):*
> ```XML
>     actual_fee: &Fee,
>     sequencer_keys: (StorageKey, StorageKey),
>     sequencer_values: (StarkFelt, StarkFelt),
> ```

I think these tuples are confusing. Better to use explicit names.



_Suggestion:_
```XML
    // The sequencer balance 
    sequencer_balance_key_low: StorageKey,
    sequencer_balance_key_high: StorageKey,
    sequencer_balance_value_low: StarkFelt,
    sequencer_balance_value_high: StarkFelt,
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxhaploDspHKS-0fYyA:-NxhaploDspHKS-0fYyB:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d102395d7ff42792ad2247b37692cc1ee1317e7/crates/blockifier/src/concurrency/worker_logic.rs#L47)):*
> ```XML
>         };
> 
>     let sequencer_value_high = stark_felt_to_felt(sequencer_values.1) + reminder;
> ```





_Suggestion:_
```XML
    let new_value_low = stark_felt_to_felt(sequencer_values.0) + felt_fee.clone()
    let overflow = stark_felt_to_felt(sequencer_values.0) > Felt252::max_value() + felt_fee
    let new_value_high = if overflow {stark_felt_to_felt(sequencer_values.1) + 1} else {stark_felt_to_felt(sequencer_values.1)};
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxhaploDspHKS-0fYyA:-Nxhnlm-BDxL3CUKawbr:bt8xfw8) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d102395d7ff42792ad2247b37692cc1ee1317e7/crates/blockifier/src/concurrency/worker_logic.rs#L47)):*
> ```XML
>         };
> 
>     let sequencer_value_high = stark_felt_to_felt(sequencer_values.1) + reminder;
> ```

Note that `Felt252` wraps around the maximum so the `value_low` will always be correct.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxRDhIW7epBbLcvCM9S:-NxkvWed2IvLQoc7lNS2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec1a510a66f38e9caa9ff38f96b8fb2e6b28b4ec/crates/blockifier/src/concurrency/worker_logic.rs#L13)):*
> ```XML
> fn _finalize_commit(
>     fee_token_adress: ContractAddress,
>     pinned_versioned_state: &VersionedStateProxy<impl StateReader>,
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-Nxh7x8DCMWo_EuTehge:-NxkpHrN33K5sZS65cso:b-k79360) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d102395d7ff42792ad2247b37692cc1ee1317e7/crates/blockifier/src/concurrency/worker_logic.rs#L34)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think these tuples are confusing. Better to use explicit names.
</blockquote></details>

I fear there will be too many arguments for this function :(  A function is limited to 7 arguments. 
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxhaploDspHKS-0fYyA:-NxktsW--E6ppvNgVdaw:bbyzjp2) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d102395d7ff42792ad2247b37692cc1ee1317e7/crates/blockifier/src/concurrency/worker_logic.rs#L47)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Note that `Felt252` wraps around the maximum so the `value_low` will always be correct.
</blockquote></details>

I would like to sit on it on Wednesday if you have some time. Shouldn't it be Felt252::max_value()  - felt_fee?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-Nxh7x8DCMWo_EuTehge:-NxuvIIs1E1U8M5YMsFt:b-nr6n7f) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d102395d7ff42792ad2247b37692cc1ee1317e7/crates/blockifier/src/concurrency/worker_logic.rs#L34)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I fear there will be too many arguments for this function :(  A function is limited to 7 arguments.
</blockquote></details>

1. This limit is a style limit, not a hard limit.
2. I think this change makes the number of parameters precisely 7, so it should be fine.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxhaploDspHKS-0fYyA:-Nxuw-DXBcT8mSO0ByLH:b-80tlqk) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d102395d7ff42792ad2247b37692cc1ee1317e7/crates/blockifier/src/concurrency/worker_logic.rs#L47)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I would like to sit on it on Wednesday if you have some time. Shouldn't it be Felt252::max_value()  - felt_fee?
</blockquote></details>

Sure.

**Review by avi-starkware — COMMENTED** [review]
I think you have some code here that is not related to your PR (due to rebasing).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-:-NxuwSCP0xPM1GRPhljx:bbretma)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-Nxh7x8DCMWo_EuTehge:-NxvrMOH-30xxoah3IHR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d102395d7ff42792ad2247b37692cc1ee1317e7/crates/blockifier/src/concurrency/worker_logic.rs#L34)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

1. This limit is a style limit, not a hard limit.
2. I think this change makes the number of parameters precisely 7, so it should be fine.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxhaploDspHKS-0fYyA:-NxvrP9ECmUevZIyElGA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d102395d7ff42792ad2247b37692cc1ee1317e7/crates/blockifier/src/concurrency/worker_logic.rs#L47)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-NxvrRVODZPVFdPP9BU0:-NxvrRVODZPVFdPP9BU1:b1g1tjg) ([raw file](https://github.com/starkware-libs/blockifier/blob/b3604540760d0039d2d02a112fd094e8707b089c/crates/blockifier/src/concurrency/worker_logic_test.rs#L20)):*
> ```XML
> use crate::transaction::objects::FeeType;
> ```

I still need to think about edge cases, but I would like your thoughts about the test style.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-Nxh7x8DCMWo_EuTehge:-Nxw7OUOAeSRwvpWd94A:b-7tkzck) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d102395d7ff42792ad2247b37692cc1ee1317e7/crates/blockifier/src/concurrency/worker_logic.rs#L34)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Make it `sequencer_balance_<key/value>_<low/high>`

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-:-NxwDD199d7Z8roYGH3i:bnfp4nl)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-Ny-9OUvBIXJbB5wYRPy:-Ny-9OUvBIXJbB5wYRPz:bb4gug0) ([raw file](https://github.com/starkware-libs/blockifier/blob/03b947f16710ef8f332edb20df967a0f77860835/crates/blockifier/src/concurrency/worker_logic.rs#L32)):*
> ```XML
>     sequencer_balance_key_low: StorageKey,
>     sequencer_balance_value_high: StarkFelt,
>     sequencer_balance_value_low: StarkFelt,
> ```

Please extract the `sequencer_balance_key`s using the `block_context`.

If this method receives `ThreadSafeVersionedState` you can extract the  `sequencer_balance_value`s (using `tx_id +1` ) and assuming we already re-executed the transaction
BTW- I think you can also use ` tx_versioned_state`: 
If the current transaction wrote to the sequencer balance, then the re-validation fails (note, every write must have a read first), we re-execute the transaction and skip this step. Otherwise, the last value was written by the previous transaction. Anyway, maybe it's "more correct" to use `tx_id + 1`. 



_Suggestion:_
```XML
    actual_fee: Fee,
    block_context:&BlockContext,
    sequencer_balance_value_high: StarkFelt,
    sequencer_balance_value_low: StarkFelt,
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-Ny-DJ9QC9NRBm45CPRB:-Ny-DJ9QC9NRBm45CPRC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/03b947f16710ef8f332edb20df967a0f77860835/crates/blockifier/src/concurrency/worker_logic.rs#L35)):*
> ```XML
> ) {
>     let felt_fee = Felt252::from(actual_fee.0);
>     let new_value_low = stark_felt_to_felt(sequencer_balance_value_low) + felt_fee.clone();
> ```





_Suggestion:_
```XML
    let felt_fee = &Felt252::from(actual_fee.0);
    let new_value_low = stark_felt_to_felt(sequencer_balance_value_low) + felt_fee;
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-Ny-9OUvBIXJbB5wYRPy:-Ny-KXgf2SrwrjEaUSNw:borkke3) ([raw file](https://github.com/starkware-libs/blockifier/blob/03b947f16710ef8f332edb20df967a0f77860835/crates/blockifier/src/concurrency/worker_logic.rs#L32)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please extract the `sequencer_balance_key`s using the `block_context`.

If this method receives `ThreadSafeVersionedState` you can extract the  `sequencer_balance_value`s (using `tx_id +1` ) and assuming we already re-executed the transaction
BTW- I think you can also use ` tx_versioned_state`: 
If the current transaction wrote to the sequencer balance, then the re-validation fails (note, every write must have a read first), we re-execute the transaction and skip this step. Otherwise, the last value was written by the previous transaction. Anyway, maybe it's "more correct" to use `tx_id + 1`.
</blockquote></details>

Do you mean writing the changes to tx_index +1?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-Ny-9OUvBIXJbB5wYRPy:-Ny-MPmu9WWj3wo7v3VD:bbx58r9) ([raw file](https://github.com/starkware-libs/blockifier/blob/03b947f16710ef8f332edb20df967a0f77860835/crates/blockifier/src/concurrency/worker_logic.rs#L32)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Do you mean writing the changes to tx_index +1?
</blockquote></details>

No, reading it from there

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1870)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1870#-Ny-9OUvBIXJbB5wYRPy:-Ny-OyBuEOt-ECIqrT28:bw2go5z) ([raw file](https://github.com/starkware-libs/blockifier/blob/03b947f16710ef8f332edb20df967a0f77860835/crates/blockifier/src/concurrency/worker_logic.rs#L32)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No, reading it from there
</blockquote></details>

In the commit PR, I use these values for fill_sequencer_balance_reads, so I don't think sending ThreadSafeVersionedState and extracting the values inside the function will be better.  https://github.com/starkware-libs/blockifier/blob/ccdcce2733535bd9bce09e60c84ece31cbaad526/crates/blockifier/src/concurrency/worker_logic.rs#L192

**Pull request merged**
