### PR TITLE
Implement `get_execution_info` syscall.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/497)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/497)* status: 2 of 8 files reviewed, all discussions resolved (waiting on @spapinistarkware and @Yoni-Starkware)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/497#-:-NVjiH2X99Pqva_B24ye:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/497)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @spapinistarkware and @Yoni-Starkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/497#-:-NVk-2qeCITWXXNbyaRi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
