### PR TITLE
fix(concurrency): test disable re-declaration of cairo0 contracts

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2050)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2050)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1HAYhv8dkSBb3H0YG0:-O1HAYhv8dkSBb3H0YG1:be1qt6f) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c20c8a7f7b9bcb276d9bc772cb164360aedd70c/crates/blockifier/src/transaction/transactions_test.rs#L1219)):*
> ```XML
> }
> 
> #[rstest]
> ```

To avoid code duplication, it might be a better idea to do this as part of the decalre_tx test.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1HAYhv8dkSBb3H0YG0:-O1MC3f86E1yJhrHhu2n:b-xnxb80) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c20c8a7f7b9bcb276d9bc772cb164360aedd70c/crates/blockifier/src/transaction/transactions_test.rs#L1219)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

To avoid code duplication, it might be a better idea to do this as part of the decalre_tx test.
</blockquote></details>

I agree.
All you need to do is add the last part of this test at the end of `test_declare_tx`:
```
    let account_tx2 = declare_tx(
        declare_tx_args! {
            max_fee: Fee(MAX_FEE),
            sender_address,
            version,
            resource_bounds: max_resource_bounds,
            class_hash,
            compiled_class_hash,
            nonce: nonce_manager.next(sender_address),
        },
        class_info.clone(),
    );
    let result = account_tx2.execute_raw(&mut transactional_state, block_context, execution_flags);
    assert_eq!(
        result.err().unwrap().to_string(),
        TransactionExecutionError::DeclareTransactionError { class_hash }.to_string()
    );
```

All the setup is already there.

Also, maybe use `execute` instead of `execute_raw` to be consistent with the first declaration of the test (or change it there from `execute` to `execute_raw`).

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1HAYhv8dkSBb3H0YG0:-O1MDECE70AYloMbz8dI:b-eobwjp) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c20c8a7f7b9bcb276d9bc772cb164360aedd70c/crates/blockifier/src/transaction/transactions_test.rs#L1219)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I agree.
All you need to do is add the last part of this test at the end of `test_declare_tx`:
```
    let account_tx2 = declare_tx(
        declare_tx_args! {
            max_fee: Fee(MAX_FEE),
            sender_address,
            version,
            resource_bounds: max_resource_bounds,
            class_hash,
            compiled_class_hash,
            nonce: nonce_manager.next(sender_address),
        },
        class_info.clone(),
    );
    let result = account_tx2.execute_raw(&mut transactional_state, block_context, execution_flags);
    assert_eq!(
        result.err().unwrap().to_string(),
        TransactionExecutionError::DeclareTransactionError { class_hash }.to_string()
    );
```

All the setup is already there.

Also, maybe use `execute` instead of `execute_raw` to be consistent with the first declaration of the test (or change it there from `execute` to `execute_raw`).
</blockquote></details>

Add a comment explaining why you are declaring again before this new block of code.

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2050)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2050)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1HAYhv8dkSBb3H0YG0:-O1MWKWh1vqiCzAEWBKj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c20c8a7f7b9bcb276d9bc772cb164360aedd70c/crates/blockifier/src/transaction/transactions_test.rs#L1219)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Add a comment explaining why you are declaring again before this new block of code.
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2050)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1107 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1MWNkbDFxH6Qed6J76:-O1MWNkc8q-OhMOLhUEx:b-f4941e) ([raw file](https://github.com/starkware-libs/blockifier/blob/269b17fc941536222f2569e8a8e399d80a1b9582/crates/blockifier/src/transaction/transactions_test.rs#L1107)):*
> ```XML
>     let class_info = calculate_class_info_for_testing(empty_contract.get_class());
>     let sender_address = account.get_instance_address(0);
>     let mut nonce_manager = NonceManager::default();
> ```

Note: I do not check the concurrency mode anymore. I checked V1 declared in the Oris test but not in a contract re-declaration.

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2050)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1107 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1MWNkbDFxH6Qed6J76:-O1kRSFW645YNV02w1ng:b8b25vt) ([raw file](https://github.com/starkware-libs/blockifier/blob/269b17fc941536222f2569e8a8e399d80a1b9582/crates/blockifier/src/transaction/transactions_test.rs#L1107)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Note: I do not check the concurrency mode anymore. I checked V1 declared in the Oris test but not in a contract re-declaration.
</blockquote></details>

Why not?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1233 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1kRhwlCAz8_0TdC0r_:-O1kRhwlCAz8_0TdC0ra:b-wzj700) ([raw file](https://github.com/starkware-libs/blockifier/blob/039336c83f918e53dc18e5827ed5b5b64229758b/crates/blockifier/src/transaction/transactions_test.rs#L1233)):*
> ```XML
>         class_info.clone(),
>     );
>     let result = account_tx2.execute(state, block_context, true, true);
> ```

Is it okay to use `execute` here?
I don't fully remember why some tests use `execute_raw` while others use `execute`...



_Code quote:_
```XML
  let result = account_tx2.execute(state, block_context, true, true);
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2050)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1107 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1MWNkbDFxH6Qed6J76:-O1khFP2E7EMS-clZRlh:b-wimzob) ([raw file](https://github.com/starkware-libs/blockifier/blob/269b17fc941536222f2569e8a8e399d80a1b9582/crates/blockifier/src/transaction/transactions_test.rs#L1107)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

Because it means we will have to change the declare_tx test to support concurrency mode, I am not sure 
that's what we want to do. Generally, we don't want to test the concurrent run outside the concurrency model.
account_tx_tests is an exception, actually for no reason. Regardless, I think that if we change the declare_tx test to support concurrency, we should change all the txs tests to support concurrency to stay consistent.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1233 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1kRhwlCAz8_0TdC0r_:-O1khdNeCsBmd25dYAPl:blj1dxu) ([raw file](https://github.com/starkware-libs/blockifier/blob/039336c83f918e53dc18e5827ed5b5b64229758b/crates/blockifier/src/transaction/transactions_test.rs#L1233)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Is it okay to use `execute` here?
I don't fully remember why some tests use `execute_raw` while others use `execute`...
</blockquote></details>

Assuming we do not test concurrency, yes. the reason we used execute_raw is that we could pass the concurrency 
flag without changing the Python configurations.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1107 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1MWNkbDFxH6Qed6J76:-O1ku9tD5rntj2BmT54H:b-jx2ryk) ([raw file](https://github.com/starkware-libs/blockifier/blob/269b17fc941536222f2569e8a8e399d80a1b9582/crates/blockifier/src/transaction/transactions_test.rs#L1107)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Because it means we will have to change the declare_tx test to support concurrency mode, I am not sure 
that's what we want to do. Generally, we don't want to test the concurrent run outside the concurrency model.
account_tx_tests is an exception, actually for no reason. Regardless, I think that if we change the declare_tx test to support concurrency, we should change all the txs tests to support concurrency to stay consistent.
</blockquote></details>

Oh okay
Declaring twice has nothing to do with concurrency
So I think this is fine

**Review by avi-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-:-O1kuKEl4HvSu4USvdDD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2050)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1237 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-O1l0QIs3zpal7DcTSqM:-O1l0QIs3zpal7DcTSqN:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/039336c83f918e53dc18e5827ed5b5b64229758b/crates/blockifier/src/transaction/transactions_test.rs#L1237)):*
> ```XML
>         result.err().unwrap().to_string(),
>         TransactionExecutionError::DeclareTransactionError { class_hash }.to_string()
>     );
> ```





_Suggestion:_
```XML
    assert_matches!(
         result.unwrap_err(),
        TransactionExecutionError::DeclareTransactionError { already_declared_class_hash } if
        already_declared_class_hash == class_hash
    );
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2050#-:-O1l5lUo55YjIUeS--s2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
