### PR TITLE
 Add simulate flag to ` AccountTransactionContext ` and use it in the hint processor when reading the version of a transaction.

### PR DESCRIPTION
**Pull request by noaov1**
[Python](https://reviewable.io/reviews/starkware-industries/starkware/32382)

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1063)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1063)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-Ni4lrNi5_Dti77323eh:-Ni4lrNi5_Dti77323ei:bq0jhkl) ([raw file](https://github.com/starkware-libs/blockifier/blob/491c72405320a639c023759fe0d008ed1b0800e6/crates/blockifier/src/transaction/account_transaction.rs#L145)):*
> ```XML
> 
>     fn get_account_transaction_context(&self) -> AccountTransactionContext {
>         match self {
> ```

Why is there an asymmetry here? Can it be changed?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-Ni4m79G1rgNDcaPBQ95:-Ni4m79G1rgNDcaPBQ96:bar9e1l) ([raw file](https://github.com/starkware-libs/blockifier/blob/491c72405320a639c023759fe0d008ed1b0800e6/crates/blockifier/src/transaction/account_transactions_test.rs#L207)):*
> ```XML
> 
>     // Invoke a function from the newly deployed contract.
>     let entry_point_selector = selector_from_name("return_result");
> ```

Why not use `run_invoke_tx`?
___
*[`crates/blockifier/src/transaction/objects.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-Ni4mLbF6LmEaO2FODZ_:-Ni4mLbF6LmEaO2FODZa:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/491c72405320a639c023759fe0d008ed1b0800e6/crates/blockifier/src/transaction/objects.rs#L42)):*
> ```XML
>         let simulate_version = simulate_version_base + stark_felt_to_felt(self.version.0);
> 
>         TransactionVersion(felt_to_stark_felt(&simulate_version))
> ```





_Suggestion:_
```XML
        }
        
        let simulate_version_base = Pow::pow(Felt252::from(2_u8), SIMULATE_VERSION_BASE_BIT);
        let simulate_version = simulate_version_base + stark_felt_to_felt(self.version.0);
        TransactionVersion(felt_to_stark_felt(&simulate_version))
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1063)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-Ni4m79G1rgNDcaPBQ95:-Ni5JFzp5mXAPGr3v05v:b-t7q5zz) ([raw file](https://github.com/starkware-libs/blockifier/blob/491c72405320a639c023759fe0d008ed1b0800e6/crates/blockifier/src/transaction/account_transactions_test.rs#L207)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not use `run_invoke_tx`?
</blockquote></details>

`InvokeTxArgs` doesn't exist on main-v0.12.3... maybe better to refactor when it hits `main`...?
If we add a `simulate` arg to `run_invoke_tx` fixing the merge conflicts will be harder
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1096 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-Ni5Jk8G43hAMLEX9GTL:-Ni5Jk8H78WAUbrD6trv:b-9i7b2h) ([raw file](https://github.com/starkware-libs/blockifier/blob/491c72405320a639c023759fe0d008ed1b0800e6/crates/blockifier/src/transaction/transactions_test.rs#L1096)):*
> ```XML
>         let simulate_version_base =
>             Pow::pow(Felt252::from(2_u8), constants::SIMULATE_VERSION_BASE_BIT);
>         version = simulate_version_base + version;
> ```

not to nitpick but doesn't this work? not implemented for Felt252?



_Suggestion:_
```XML
version += simulate_version_base
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1108 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-Ni5KCW0EZIBH_SJHiy4:-Ni5KCW0EZIBH_SJHiy5:bw71l8v) ([raw file](https://github.com/starkware-libs/blockifier/blob/491c72405320a639c023759fe0d008ed1b0800e6/crates/blockifier/src/transaction/transactions_test.rs#L1108)):*
> ```XML
>         stark_felt!(0_u16),           // Nonce.
>     ];
>     let entry_point_selector = selector_from_name("test_get_execution_info");
> ```

I only see this defined on cairo1 contracts; is the deprecated syscall handler tested here?



_Code quote:_
```XML
test_get_execution_info
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1063)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-Ni4lrNi5_Dti77323eh:-Ni8gc6g2gaFsP4zd_0k:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/491c72405320a639c023759fe0d008ed1b0800e6/crates/blockifier/src/transaction/account_transaction.rs#L145)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is there an asymmetry here? Can it be changed?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1108 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-Ni5KCW0EZIBH_SJHiy4:-Ni8gzTrB8t3cPXcI4qy:b-zgvonu) ([raw file](https://github.com/starkware-libs/blockifier/blob/491c72405320a639c023759fe0d008ed1b0800e6/crates/blockifier/src/transaction/transactions_test.rs#L1108)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I only see this defined on cairo1 contracts; is the deprecated syscall handler tested here?
</blockquote></details>

Good point. Adding a test in a new PR.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1063)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-:-Ni9albf6gUf5yVVtriQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by dorimedini-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1063)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1063)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-NiA2Dl28WRud0hcqVxf:-NiA2Dl28WRud0hcqVxg:b-gwep6f) (no related file):*
Can you change to `only_query` everywhere?

___

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1063)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1063#-NiA2Dl28WRud0hcqVxf:-NiA8ZE68Ah9Ao7Zdeqn:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you change to `only_query` everywhere?
</blockquote></details>

Done.

___

**Review by elintul — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1063)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
