### PR TITLE
refactor(state,concurrency): add validate read set and apply writes to versioned state proxy

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1860)

### CODE REVIEW

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1860#-:-Nx7GkA8C7AQRdU74JEQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1860)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1860#-Nx7paGJ-IXqfcQZ_Ycn:-Nx7paGKEiG1pCshKGKt:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/0afc0e18fea9fced5202daec3feb4d4d21d71bf0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L72)):*
> ```XML
>     // TODO: Consider coupling the tx index with the read set to ensure any mismatch between them
>     // will cause the validation to fail.
>     pub fn validate_read_set(&mut self, tx_index: TxIndex, reads: &StateMaps) -> bool {
> ```

WDYT?



_Suggestion:_
```XML
fn validate_read_set(&mut self, tx_index: TxIndex, reads: &StateMaps) -> bool {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1860#-Nx7pc8w45WfvhJGNAkj:-Nx7pc8w45WfvhJGNAkk:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/0afc0e18fea9fced5202daec3feb4d4d21d71bf0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L120)):*
> ```XML
>     }
> 
>     pub fn apply_writes(
> ```

WDYT?



_Suggestion:_
```XML
fn apply_writes(
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1860)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1860#-Nx7paGJ-IXqfcQZ_Ycn:-Nx7rDD51e4fhs8voGf1:b-phepez) ([raw file](https://github.com/starkware-libs/blockifier/blob/0afc0e18fea9fced5202daec3feb4d4d21d71bf0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L72)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Interesting. It means that we cannot call this method. I'll do that and if we decide differently, we can change it back.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1860)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1860#-Nx7pc8w45WfvhJGNAkj:-Nx7tokf2b9gufEd0nfX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0afc0e18fea9fced5202daec3feb4d4d21d71bf0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L120)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1860#-:-Nx7tyZ90rUYoLkyKCkf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
