### PR TITLE
refactor: pass self by reference in count_for_fee_charge

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1687)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1687)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 761 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1687#-NtMSHSW2qU17rxiojMI:-NtMSHSW2qU17rxiojMJ:b-a9sir) ([raw file](https://github.com/starkware-libs/blockifier/blob/2fc99d1bf149fe3fe5d29bb3be8afcb25d9b88d1/crates/blockifier/src/state/cached_state.rs#L761)):*
> ```XML
>     ) -> StateChangesCount {
>         let mut modified_contracts = self.get_modified_contracts();
>         let mut storage_updates = self.storage_updates;
> ```

we do not actually need ownership of `storage_updates` for the count function; refactoring makes it possible to implement this method with `&self` instead of `self` (non-consuming)



_Code quote:_
```XML
let mut storage_updates = self.storage_updates;
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1687#-:-NtQ0qmBBOofPUP9Lf-P:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @noaov1)

**Review by noaov1 — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1687)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 761 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1687#-NtMSHSW2qU17rxiojMI:-NtQ5We5DtN6wvjpOkxe:bb6zmf0) ([raw file](https://github.com/starkware-libs/blockifier/blob/02dad795509a9720c243c929b811136875b38630/crates/blockifier/src/state/cached_state.rs#L761)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we do not actually need ownership of `storage_updates` for the count function; refactoring makes it possible to implement this method with `&self` instead of `self` (non-consuming)
</blockquote></details>

Like

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1687#-:-NtVKC2q0aGkJzVRDO2x:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
