### PR TITLE
Add post-execution cartesian tests

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1169)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1169)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 451 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBLs7WCcYqsQhUi__-:-NkBLs7X5_5DZnxwi0Ej:b-z7xetz) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L451)):*
> ```XML
> 
>     // Post-execution scenario: consumed too many resources. Actual fee should be equal to sender
>     // bounds, actual gas consumed should be equal to sender bounds plus overhead.
> ```

What is the overhead? The `n_reverted_steps`?



_Suggestion:_
```XML
    // bounds, actual gas consumed should be equal the gas consumed in `__validate__` plus the number of reverted steps.
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 454 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBOhZ7CH-FUsp5_fvS:-NkBOhZ7CH-FUsp5_fvT:b-j857n8) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L454)):*
> ```XML
>     let (just_not_enough_gas_bound, just_not_enough_fee_bound) = gas_and_fee(6000, validate);
>     let (unlimited_gas_used, unlimited_fee) = gas_and_fee(10688, validate);
>     let charged_gas = just_not_enough_gas_bound + 4 * 612;
> ```

For consistency.
Can you please explain this value? Aren't we reverting the execution changes? 



_Suggestion:_
```XML
    let charged_gas = just_not_enough_gas_bound + 4 * eth_gas_constants::SHARP_GAS_PER_MEMORY_WORD as u64;
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 481 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBSEdWBmcgRbv41aMP:-NkBSEdWBmcgRbv41aMQ:b-o90tny) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L481)):*
> ```XML
>         calculate_tx_fee(&tx_execution_info.actual_resources, &block_context, &fee_type).unwrap(),
>         if charge_fee { charged_fee } else { unlimited_fee }
>     );
> ```

Why is it needed? 



_Code quote:_
```XML
    assert_eq!(
        calculate_tx_fee(&tx_execution_info.actual_resources, &block_context, &fee_type).unwrap(),
        if charge_fee { charged_fee } else { unlimited_fee }
    );
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 488 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBTuDl-naKGhN81rZH:-NkBTuDl-naKGhN81rZI:bt7qzvm) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L488)):*
> ```XML
>         &block_context,
>         &fee_type,
>         charge_fee,
> ```

Consider adding the scenario where `balance < actual cost`.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1169)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 451 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBLs7WCcYqsQhUi__-:-NkGNmRh6sMQcGJQOsMP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L451)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is the overhead? The `n_reverted_steps`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 454 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBOhZ7CH-FUsp5_fvS:-NkGNnGp1rZ904Gh0OBC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L454)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

For consistency.
Can you please explain this value? Aren't we reverting the execution changes?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 481 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBSEdWBmcgRbv41aMP:-NkFB2KN-yMXbnCZ8MX8:b-bfeuci) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L481)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

This is a discrepancy between the actual resources reported and the charged fee; the name `charged_fee` variable name is misleading I think, I renamed.
The disconnect between reported resources and actual_fee is known; actual_fee is constrained by what we are allowed to charge, and actual_resources are not.
That's why - if `charge_fee` is `false` - the actual fee and the fee calculated from the actual resources are both `unlimited_fee`
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 488 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBTuDl-naKGhN81rZH:-NkGNj658dUAb-94nYzL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L488)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider adding the scenario where `balance < actual cost`.
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1169)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 451 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBLs7WCcYqsQhUi__-:-NkGWj6NDun1bxv0-n2M:b-53iiks) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L451)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not quite :)
I don't think it has anything to do with the sender's bounds. You did not stop the execution at any point. WDYT?
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 494 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkKVDgA2CIVlrg7wHTw:-NkKVDgA2CIVlrg7wHTx:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e6301986dcfff6d40118610e757a31a2e35ef6/crates/blockifier/src/transaction/execution_flavors_test.rs#L494)):*
> ```XML
>         &fee_type,
>         charge_fee,
>     );
> ```





_Suggestion:_
```XML
    let _current_balance = check_balance(
        current_balance,
        &mut state,
        account_address,
        &block_context,
        &fee_type,
        charge_fee,
    );
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 505 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkKXc0m4aiHJgJBUuLs:-NkKXc0m4aiHJgJBUuLt:bqut6kp) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e6301986dcfff6d40118610e757a31a2e35ef6/crates/blockifier/src/transaction/execution_flavors_test.rs#L505)):*
> ```XML
>         "approve",
>         &[
>             *contract_address.0.key(), // Calldata: to.
> ```

It is not an account contract, right? What is the meaning of the `approve` method?



_Code quote:_
```XML
            *contract_address.0.key(), // Calldata: to.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1169)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 451 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBLs7WCcYqsQhUi__-:-NkKbG446VfbDUSwfRHN:bskzvir) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L451)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not quite :)
I don't think it has anything to do with the sender's bounds. You did not stop the execution at any point. WDYT?
</blockquote></details>

It does; I don't stop execution, but after computing resources used, we see we overstep the bounds
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 494 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkKVDgA2CIVlrg7wHTw:-NkKbOkq7uDuoNJWN_vz:bfnd0ao) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e6301986dcfff6d40118610e757a31a2e35ef6/crates/blockifier/src/transaction/execution_flavors_test.rs#L494)):*
> ```XML
>         &fee_type,
>         charge_fee,
>     );
> ```

no; it's used again in line 523
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 505 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkKXc0m4aiHJgJBUuLs:-NkKbSSv9J07fMmjuqSh:b-pym3co) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e6301986dcfff6d40118610e757a31a2e35ef6/crates/blockifier/src/transaction/execution_flavors_test.rs#L505)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It is not an account contract, right? What is the meaning of the `approve` method?
</blockquote></details>

the account owns the funds, and can transfer.
the test contract implements the `test_write_and_transfer` function.
the test contract - to be able to transfer funds from the account - needs approval from the owner (the account) of the funds.
I'll call the token contract directly, seems better

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1169)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 451 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBLs7WCcYqsQhUi__-:-NkKlS0Z4dj3llJsFq7H:b-2tssr) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L451)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

It does; I don't stop execution, but after computing resources used, we see we overstep the bounds
</blockquote></details>

How does it affect the actual resources?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1169)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 451 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkBLs7WCcYqsQhUi__-:-NkLT5reAwiqslDC1wI9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/631c4d8302b2d7bd13e5048b742ae985396aa356/crates/blockifier/src/transaction/execution_flavors_test.rs#L451)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

How does it affect the actual resources?
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1169)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 465 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkPoE8c6HljpPEIzfTp:-NkPoE8c6HljpPEIzfTq:bgezu0p) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee9919f9adea1dd7be630c0a3d6a8b5248a0f4f1/crates/blockifier/src/transaction/execution_flavors_test.rs#L465)):*
> ```XML
>     // If `charge_fee` is true, we revert, charge the maximal allowed fee (derived from sender
>     // bounds), and report resources base on execution steps reverted + other overhead.
>     let base_gas_bound = 10000;
> ```

What is the meaning of this variable?



_Code quote:_
```XML
    let base_gas_bound = 10000;
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 468 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-NkPoSgtBEAjP_kSyZUY:-NkPoSgtBEAjP_kSyZUZ:b2nhkyh) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee9919f9adea1dd7be630c0a3d6a8b5248a0f4f1/crates/blockifier/src/transaction/execution_flavors_test.rs#L468)):*
> ```XML
>     let (just_not_enough_gas_bound, just_not_enough_fee_bound) =
>         gas_and_fee(base_gas_bound, validate);
>     // Execution steps + overhead, translated to L1 gas, comes out slightly less than the gas bound.
> ```

No?



_Suggestion:_
```XML
    // `__validate__` and overhead resources + number of reverted steps, translated to L1 gas, comes out slightly less than the gas bound.
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1169#-:-NkQ1MTdATf3s3PKUl_Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
