### PR TITLE
Refactor error unpacking in test_validate_accounts_tx.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1218)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1218)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkyQw3v064TbO-tZOlr:-NkyQw3v064TbO-tZOls:b-b3sgij) ([raw file](https://github.com/starkware-libs/blockifier/blob/80825f7a057e7226ddde2444e7aa160254b3979c/crates/blockifier/src/test_utils.rs#L219)):*
> ```XML
>     } else {
>         panic!("Unexpected structure for error: {:?}", error);
>     }
> ```

does this work? `error` has the same type



_Suggestion:_
```XML
    match error {
        TransactionExecutionError::ValidateTransactionError(error)
        | TransactionExecutionError::ContractConstructorExecutionFailed(error) => {
            check_entry_point_execution_error_for_custom_hint(error, expected_hint);
        }
        _ => panic!("Unexpected structure for error: {:?}", error);
    }
```
___
*[`crates/blockifier/src/test_utils.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkyRQF1E3z62-lWKaZ9:-NkyRQF1E3z62-lWKaZA:b-ei8g4l) ([raw file](https://github.com/starkware-libs/blockifier/blob/80825f7a057e7226ddde2444e7aa160254b3979c/crates/blockifier/src/test_utils.rs#L258)):*
> ```XML
>     ) = error
>     {
>     } else {
> ```

[damn](https://github.com/rust-lang/rfcs/issues/2616), this is the best we can do



_Code quote:_
```XML
    {
    } else {
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkyRaEZ1Q--q36f2F22:-NkyRaEZ1Q--q36f2F23:bl7h8yo) ([raw file](https://github.com/starkware-libs/blockifier/blob/80825f7a057e7226ddde2444e7aa160254b3979c/crates/blockifier/src/transaction/transactions_test.rs#L1110)):*
> ```XML
>         create_account_tx_for_validate_test(tx_type, INVALID, None, &mut NonceManager::default());
>     let error = account_tx.execute(state, block_context, true, true).unwrap_err();
>     check_transaction_execution_error_for_diff_assert_values(&error);
> ```

the problem with this is: when you run a test and fail on this, the line number you'll see is in the `test_utils` module.
if this were a macro, you would see the more interesting line number (here).
Maybe turn this into a macro?



_Code quote:_
```XML
check_transaction_execution_error_for_diff_assert_values(
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1119 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkyRnEJ9xnpc0QN9xcu:-NkyRnEJ9xnpc0QN9xcv:b-lzu6xt) ([raw file](https://github.com/starkware-libs/blockifier/blob/80825f7a057e7226ddde2444e7aa160254b3979c/crates/blockifier/src/transaction/transactions_test.rs#L1119)):*
> ```XML
>         &mut NonceManager::default(),
>     );
>     let error: TransactionExecutionError =
> ```

delete annotation

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkyQw3v064TbO-tZOlr:-NkyV9Sk4BK8Xp4xk6nu:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/80825f7a057e7226ddde2444e7aa160254b3979c/crates/blockifier/src/test_utils.rs#L219)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work? `error` has the same type
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkyRQF1E3z62-lWKaZ9:-NkyTNy3E-7-kWtRlFvx:bc45pod) ([raw file](https://github.com/starkware-libs/blockifier/blob/80825f7a057e7226ddde2444e7aa160254b3979c/crates/blockifier/src/test_utils.rs#L258)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[damn](https://github.com/rust-lang/rfcs/issues/2616), this is the best we can do
</blockquote></details>

Indeed, :\

We could make it into a more generic function that checks what type of `inner_exc` we have - and checks it matches the return type.
Kind of share code between this function and `check_entry_point_execution_error_for_custom_hint`.
This is killing two birds with one stone. However, they were two birds, each chilling on a different tree.
Something like: #1220. (I don't like it - it seems like over-design)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1119 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkyRnEJ9xnpc0QN9xcu:-NkyUJIG0_hF2ETLuSmP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/80825f7a057e7226ddde2444e7aa160254b3979c/crates/blockifier/src/transaction/transactions_test.rs#L1119)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete annotation
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1218)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkyRaEZ1Q--q36f2F22:-Nkz8UdB1gYpq1PjlyWE:b-jkx290) ([raw file](https://github.com/starkware-libs/blockifier/blob/80825f7a057e7226ddde2444e7aa160254b3979c/crates/blockifier/src/transaction/transactions_test.rs#L1110)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the problem with this is: when you run a test and fail on this, the line number you'll see is in the `test_utils` module.
if this were a macro, you would see the more interesting line number (here).
Maybe turn this into a macro?
</blockquote></details>

Done.
Macros are beautiful, and my tiny brain can't handle them. 

It makes the imports kind of confusing and repetitive IMO - but maybe it is just because I am not used to it.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-:-NkzFvc47iEUMXHWkxAd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 220 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkzFnZ-83IXVKzkEHCX:-NkzFnZ-83IXVKzkEHCY:b-j1sk9j) ([raw file](https://github.com/starkware-libs/blockifier/blob/c47334301d38b7ed0f37f07505bae2dc60d3ce93/crates/blockifier/src/test_utils.rs#L220)):*
> ```XML
> #[macro_export]
> macro_rules! check_transaction_execution_error_for_custom_hint {
>     ($error:expr, $expected_hint:expr) => {
> ```

you can add this if you want to be fancy and allow trailing commas when you call these macros.



_Suggestion:_
```XML
$error:expr, $expected_hint:expr $(,)?
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkyRaEZ1Q--q36f2F22:-NkzFaHwCezyNtiFgh_i:b-mp04v2) ([raw file](https://github.com/starkware-libs/blockifier/blob/80825f7a057e7226ddde2444e7aa160254b3979c/crates/blockifier/src/transaction/transactions_test.rs#L1110)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
Macros are beautiful, and my tiny brain can't handle them. 

It makes the imports kind of confusing and repetitive IMO - but maybe it is just because I am not used to it.
</blockquote></details>

to "solve" the invisible import issue you could use a full path to the objects you use, in the macro definition.
not sure which method I prefer, but looks good :)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1218)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1171 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-NkzGao66FExlo6gMzkb:-NkzGao66FExlo6gMzkc:b-qycmc2) ([raw file](https://github.com/starkware-libs/blockifier/blob/c47334301d38b7ed0f37f07505bae2dc60d3ce93/crates/blockifier/src/transaction/transactions_test.rs#L1171)):*
> ```XML
>         let account_tx = AccountTransaction::DeployAccount(deploy_account_tx);
>         let error = account_tx.execute(state, block_context, true, true).unwrap_err();
>         check_transaction_execution_error_for_custom_hint!(
> ```

I wonder if we care for the specific error type. Now, the test can pass even if we throw here `TransactionExecutionError::ValidateTransactionError`. 



_Code quote:_
```XML
check_transaction_execution_error_for_custom_hint!(
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1218#-:-Nkzba6Z-9WGjFjOqsYR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1218)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
