### PR TITLE
Elin/merge main v0.12.2 into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815)* status: 8 of 10 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/815#-NbDo0_q1nhoIDVP8gbG:-NbDo0_q1nhoIDVP8gbH:b65msuq) (no related file):*
Re conflicts: mainly took `main-v0.12.2` work with `handle_validate_tx` instead of `validate_tx`.

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 510 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/815#-NbDt53Z6vYSKIw0uTHF:-NbDt53_CZglTAeRoh34:b-4pmjrh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4383dd2df6109cf019ede48e6d45fc16ea22551a/crates/blockifier/src/transaction/account_transaction.rs#L510)):*
> ```XML
>         // transfer from the steps available to the run_execute context.
>         execution_context.subtract_steps(validate_steps + overhead_steps);
>         let n_allotted_steps = execution_context.vm_run_resources.get_n_steps().unwrap();
> ```

`expect` > `unwrap`



_Suggestion:_
```XML
.expect("The number of steps must be initialized.")
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 620 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/815#-NbDtC_PEe9J19kVAU6a:-NbDtC_QBH-3rzvaTv9O:b-4pmjrh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4383dd2df6109cf019ede48e6d45fc16ea22551a/crates/blockifier/src/transaction/account_transaction.rs#L620)):*
> ```XML
>                 // Error during execution. Revert.
>                 execution_state.abort();
>                 let n_remaining_steps = execution_context.vm_run_resources.get_n_steps().unwrap();
> ```

`expect` > `unwrap`



_Suggestion:_
```XML
.expect("The number of steps must be initialized.")
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 510 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/815#-NbDt53Z6vYSKIw0uTHF:-NbDtWoIAYGT6T36fl27:bhfamwj) ([raw file](https://github.com/starkware-libs/blockifier/blob/4383dd2df6109cf019ede48e6d45fc16ea22551a/crates/blockifier/src/transaction/account_transaction.rs#L510)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`expect` > `unwrap`
</blockquote></details>

Is this done on `main`? Why?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 510 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/815#-NbDt53Z6vYSKIw0uTHF:-NbDtlJ32e0kIYiv2Yy7:bp9baqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/4383dd2df6109cf019ede48e6d45fc16ea22551a/crates/blockifier/src/transaction/account_transaction.rs#L510)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this done on `main`? Why?
</blockquote></details>

In non-tests, `unwrap` is always bad IMO; at the very least, if we can possibly panic, I would always add a string saying why

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 510 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/815#-NbDt53Z6vYSKIw0uTHF:-NbDtqdw6C4kWrvP-4lD:b-oak0hr) ([raw file](https://github.com/starkware-libs/blockifier/blob/4383dd2df6109cf019ede48e6d45fc16ea22551a/crates/blockifier/src/transaction/account_transaction.rs#L510)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

In non-tests, `unwrap` is always bad IMO; at the very least, if we can possibly panic, I would always add a string saying why
</blockquote></details>

Also, this repeats three times (for now); I think a small method is due. 
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 620 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/815#-NbDtC_PEe9J19kVAU6a:-NbDtpwFB5vanhE59lHJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4383dd2df6109cf019ede48e6d45fc16ea22551a/crates/blockifier/src/transaction/account_transaction.rs#L620)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`expect` > `unwrap`
</blockquote></details>

Done.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 510 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/815#-NbDt53Z6vYSKIw0uTHF:-NbDu3-b0XN5TKJKr3cU:b-8xjizs) ([raw file](https://github.com/starkware-libs/blockifier/blob/4383dd2df6109cf019ede48e6d45fc16ea22551a/crates/blockifier/src/transaction/account_transaction.rs#L510)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Also, this repeats three times (for now); I think a small method is due. 
</blockquote></details>

I agree `expect` is better; I'm saying this change should have been made on `main-v0.12.2`.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/815#-:-NbDxPFD-WDxjSbryJHl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @Yoni-Starkware)

**Pull request merged**
