### PR TITLE
feat(concurrency): implement Default for ConcurrencyConfig

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1952)

### CODE REVIEW

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1952)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/config.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1952#-NzY6tSv38mgnw8te7pT:-NzY6tSv38mgnw8te7pU:b-m161tt) ([raw file](https://github.com/starkware-libs/blockifier/blob/ab6459d3702ec04a1a5bdf7a831ec6d288b63dac/crates/blockifier/src/blockifier/config.rs#L15)):*
> ```XML
> impl Default for ConcurrencyConfig {
>     fn default() -> Self {
>         Self { enabled: false, n_workers: 64, chunk_size: 4 }
> ```

`n_workers` and `chunk_size` here have swapped values from the default consts in `utils.rs`.

Why don't you use the constants here?



_Suggestion:_
```XML
        Self { enabled: false, n_workers: 4, chunk_size: 64 }
```
___
*[`crates/blockifier/src/concurrency/utils.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1952#-NzY5zr54Zw81MxN11RS:-NzY5zr54Zw81MxN11RT:b4b3eie) ([raw file](https://github.com/starkware-libs/blockifier/blob/ab6459d3702ec04a1a5bdf7a831ec6d288b63dac/crates/blockifier/src/concurrency/utils.rs#L15)):*
> ```XML
> 
> pub const DEFAULT_CHUNK_SIZE: usize = 64;
> pub const DEFAULT_N_WORKERS: usize = 4;
> ```

Ittay Dror said we should determine the number of workers automatically based on the actual hardware we are running on. Otherwise, we would have to reconfigure the batcher each time we change the machine it is running on.

This is probably not in the scope of this PR, but maybe add a TODO somewhere?

Nonblocking.



_Code quote:_
```XML
pub const DEFAULT_N_WORKERS: usize = 4;
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1952)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/config.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1952#-NzY6tSv38mgnw8te7pT:-NzYXMP7AJCRFZ3DxTaO:ba1tqj0) ([raw file](https://github.com/starkware-libs/blockifier/blob/ab6459d3702ec04a1a5bdf7a831ec6d288b63dac/crates/blockifier/src/blockifier/config.rs#L15)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

`n_workers` and `chunk_size` here have swapped values from the default consts in `utils.rs`.

Why don't you use the constants here?
</blockquote></details>

Done.
To use constants from the `concurrency` module, we need to find some workaround since the `concurrency` module can be seen only when adding `--feartures=concurrency`.
I think we can remove the `#[cfg(feature = concurrency)]`.
___
*[`crates/blockifier/src/concurrency/utils.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1952#-NzY5zr54Zw81MxN11RS:-NzYYC698pfe4peH6inj:bck8qu3) ([raw file](https://github.com/starkware-libs/blockifier/blob/ab6459d3702ec04a1a5bdf7a831ec6d288b63dac/crates/blockifier/src/concurrency/utils.rs#L15)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Ittay Dror said we should determine the number of workers automatically based on the actual hardware we are running on. Otherwise, we would have to reconfigure the batcher each time we change the machine it is running on.

This is probably not in the scope of this PR, but maybe add a TODO somewhere?

Nonblocking.
</blockquote></details>

Removed from this PR.

**Review by avi-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1952#-:-NzYehvkClfddaqVg_zL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1952#-:-Nzb1IrT2Std06Om0GmX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

**Pull request closed without merging**
