### PR TITLE
test(concurrency): change worker executor field chunk to reference, add test to execute method

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1897)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1897)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-NxvByPPAluaOq-Yt9s2:-NxvByPQ3XLX9cIUVkMk:b-hmwz9m) ([raw file](https://github.com/starkware-libs/blockifier/blob/64d7d0ff3c21f3008cdc25cd985cfa11b702d8e3/crates/blockifier/src/concurrency/worker_logic.rs#L41)):*
> ```XML
>     ) -> Self {
>         let execution_outputs =
>             std::iter::repeat_with(|| Mutex::new(None)).take(scheduler.chunk_size()).collect();
> ```

If that's the only reason for this getter, you can remove it and use `self.chunk.len()`

Also, note that the field `chunk_size` should be consistent with chunk.len() and `execution_outputs.len()`.
Maybe this constructor should just get the chunk, and create the outputs **and** the scheduler inside.
Not sure though. It's better to include some usage/test of a code in the PR to understand the flow



_Code quote:_
```XML
scheduler.chunk_size()
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1897)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-NxvByPPAluaOq-Yt9s2:-Ny-fML194sbB2TmahpL:b-7qmo62) ([raw file](https://github.com/starkware-libs/blockifier/blob/64d7d0ff3c21f3008cdc25cd985cfa11b702d8e3/crates/blockifier/src/concurrency/worker_logic.rs#L41)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

If that's the only reason for this getter, you can remove it and use `self.chunk.len()`

Also, note that the field `chunk_size` should be consistent with chunk.len() and `execution_outputs.len()`.
Maybe this constructor should just get the chunk, and create the outputs **and** the scheduler inside.
Not sure though. It's better to include some usage/test of a code in the PR to understand the flow
</blockquote></details>

Good point. Done

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1897)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny08TDg9SJh0DLoqWqx:-Ny08TDg9SJh0DLoqWqy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L47)):*
> ```XML
>     let nonce_manager = &mut NonceManager::default();
>     let storage_value = stark_felt!(93_u8);
>     let storage_key = 1993_u16;
> ```





_Suggestion:_
```XML
let storage_key = storage_key!(1993_u16);
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny08dehE09mZWKNlDuV:-Ny08dehE09mZWKNlDuW:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L89)):*
> ```XML
> 
>     // Concurrency settings.
>     let txs = [tx_success, tx_failure, tx_revert];
> ```





_Suggestion:_
```XML
    let tx_success = account_invoke_tx(invoke_tx_args! {
        sender_address: account_address,
        calldata: create_calldata(
            test_contract_address,
            "test_storage_read_write",
            &[stark_felt!(storage_key),storage_value ], // Calldata:  address, value.
        ),
        max_fee: Fee(MAX_FEE),
        nonce: nonce_manager.next(account_address)
    });

    let tx_failure = account_invoke_tx(invoke_tx_args! {
        sender_address: account_address,
        calldata: create_calldata(
            test_contract_address,
            "test_storage_read_write",
            &[stark_felt!(storage_key),storage_value ], // Calldata:  address, value.
        ),
        max_fee: Fee(1),
        nonce: nonce_manager.next(account_address)

    });
    nonce_manager.rollback(account_address);

    let tx_revert = account_invoke_tx(invoke_tx_args! {
        sender_address: account_address,
        calldata: create_calldata(
            test_contract_address,
            "write_and_revert",
            &[stark_felt!(1991_u16),storage_value ], // Calldata:  address, value.
        ),
        max_fee: Fee(MAX_FEE),
        nonce: nonce_manager.next(account_address)

    });

    // Concurrency settings.
    let txs = [tx_success, tx_failure, tx_revert].map(Transaction::AccountTransaction).collect();
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0RMOhCZT65KDkNoMw:-Ny0RMOhCZT65KDkNoMx:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L110)):*
> ```XML
>     // Verify the output was written. Validate its correctness.
>     let execution_output = worker_executor.execution_outputs[tx_index].lock().unwrap();
>     let result = execution_output.as_ref().unwrap().result.as_ref().unwrap();
> ```





_Suggestion:_
```XML
    let execution_output = worker_executor.execution_outputs[tx_index].lock().unwrap().as_ref().unwrap();
    let result = execution_output.result.as_ref().unwrap();
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0T1Nx0sRR8imb_UKr:-Ny0T1Nx0sRR8imb_UKs:b-3kxbi8) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L124)):*
> ```XML
>             ((erc_contract_address, account_balance_key_low), stark_felt!(account_balance)),
>             ((erc_contract_address, account_balance_key_high), stark_felt!(0_u8)),
>         ]),
> ```

Comment about the sequencer balance (that it's missing)



_Code quote:_
```XML
        storage: HashMap::from([
            ((test_contract_address, StorageKey(patricia_key!(storage_key))), storage_value),
            ((erc_contract_address, account_balance_key_low), stark_felt!(account_balance)),
            ((erc_contract_address, account_balance_key_high), stark_felt!(0_u8)),
        ]),
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 129 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0SFwC89rqzOV70tBO:-Ny0SFwDC2TKZrVVrV0A:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L129)):*
> ```XML
>     let reads = StateMaps {
>         nonces: HashMap::from([(account_address, nonce!(0_u8))]),
>         // Before running an entry point (call contract), we verify the contract is deployed
> ```





_Suggestion:_
```XML
erify the contract is deployed.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 140 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0SIoS9zZu-BE2pIXl:-Ny0SIoS9zZu-BE2pIXm:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L140)):*
> ```XML
>             ((erc_contract_address, account_balance_key_high), stark_felt!(0_u8)),
>         ]),
>         // When running an entry point, we load its contract
> ```





_Suggestion:_
```XML
/ When running an entry point, we load its contract class.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 156 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0TWY86HmdBy_2Lp0K:-Ny0TWY86HmdBy_2Lp0L:b-sshzcy) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L156)):*
> ```XML
>     let tx_index = 1;
>     worker_executor.execute(tx_index);
>     // No write was made by the transaction.
> ```

What about the read set? if it's too ugly, consider failing the tx on wrong nonce, and asserting that the read set contains just the nonce.



_Code quote:_
```XML
    // No write was made by the transaction.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0TFbh1g6TUVn3bvhy:-Ny0TFbh1g6TUVn3bvhz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L164)):*
> ```XML
>     assert!(execution_output.as_ref().unwrap().result.as_ref().is_err());
>     assert_eq!(execution_output.as_ref().unwrap().writes, StateMaps::default());
>     assert_eq!(execution_output.as_ref().unwrap().visited_pcs, HashMap::default());
> ```





_Suggestion:_
```XML
    let execution_output = worker_executor.execution_outputs[tx_index].lock().unwrap()as_ref().unwarp();
    assert!(execution_output.result.as_ref().is_err());
    assert_eq!(execution_output.writes, StateMaps::default());
    assert_eq!(execution_output.visited_pcs, HashMap::default());
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 177 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0U-X4D0S88fTkNay5:-Ny0U-X4D0S88fTkNay6:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L177)):*
> ```XML
>     assert!(execution_output.as_ref().unwrap().result.as_ref().unwrap().is_reverted());
>     assert_ne!(execution_output.as_ref().unwrap().writes, StateMaps::default());
>     assert_ne!(execution_output.as_ref().unwrap().visited_pcs, HashMap::default());
> ```





_Suggestion:_
```XML
    );
    let execution_output = worker_executor.execution_outputs[tx_index].lock().unwrap().as_ref().unwrap();
    assert!(execution_output.result.as_ref().unwrap().is_reverted());
    assert_ne!(execution_output.writes, StateMaps::default());
    assert_ne!(execution_output.visited_pcs, HashMap::default());
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1897)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny08dehE09mZWKNlDuV:-Ny18tZS0nnhWZ93C0Ko:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L89)):*
> ```XML
> 
>     // Concurrency settings.
>     let txs = [tx_success, tx_failure, tx_revert];
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 129 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0SFwC89rqzOV70tBO:-Ny19_4aAPOinVK7udae:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L129)):*
> ```XML
>     let reads = StateMaps {
>         nonces: HashMap::from([(account_address, nonce!(0_u8))]),
>         // Before running an entry point (call contract), we verify the contract is deployed
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 140 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0SIoS9zZu-BE2pIXl:-Ny19bm_0tDiuZsp8i2y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L140)):*
> ```XML
>             ((erc_contract_address, account_balance_key_high), stark_felt!(0_u8)),
>         ]),
>         // When running an entry point, we load its contract
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 156 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0TWY86HmdBy_2Lp0K:-Ny1CnAO7sOnK8Tp7eMR:b-87flyt) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L156)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What about the read set? if it's too ugly, consider failing the tx on wrong nonce, and asserting that the read set contains just the nonce.
</blockquote></details>

I thought that it is already covered in the successful execution, but maybe not. Added. 
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0TFbh1g6TUVn3bvhy:-Ny1A_0k4oy0Bh0tqHz3:b-bebmz3) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L164)):*
> ```XML
>     assert!(execution_output.as_ref().unwrap().result.as_ref().is_err());
>     assert_eq!(execution_output.as_ref().unwrap().writes, StateMaps::default());
>     assert_eq!(execution_output.as_ref().unwrap().visited_pcs, HashMap::default());
> ```

Done. (almost). I can't define `execution_output` this way. Compiler error:



_Code snippet:_
```XML
179 |     let execution_output = worker_executor.execution_outputs[tx_index].lock().unwrap().as_ref().unwrap();
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  - temporary value is freed at the end of this statement
    |                            |
    |                            creates a temporary value which is freed while still in use
180 |     assert!(execution_output.result.as_ref().unwrap().is_reverted());
    |             -------------------------------- borrow later used here
    |
help: consider using a `let` binding to create a longer lived value
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 177 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0U-X4D0S88fTkNay5:-Ny1BwdN0vN3ymBWP9Xz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L177)):*
> ```XML
>     assert!(execution_output.as_ref().unwrap().result.as_ref().unwrap().is_reverted());
>     assert_ne!(execution_output.as_ref().unwrap().writes, StateMaps::default());
>     assert_ne!(execution_output.as_ref().unwrap().visited_pcs, HashMap::default());
> ```

Done.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1897)* status: 4 of 7 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0T1Nx0sRR8imb_UKr:-Ny1DLp11XyrTHvYG3NF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L124)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Comment about the sequencer balance (that it's missing)
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-:-NyEopjY4ygnTeOmjZwU:bnfp4nl)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 156 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-Ny0TWY86HmdBy_2Lp0K:-NyEoBMjDku35uwIqosq:bec5wka) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a800e675676c070735da983d237e168b07c437/crates/blockifier/src/concurrency/worker_logic_test.rs#L156)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I thought that it is already covered in the successful execution, but maybe not. Added.
</blockquote></details>

(Not trivial here since the tx failed and all other sets are empty)
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 122 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1897#-NyEnlOl3-L1vrofNd_M:-NyEnlOl3-L1vrofNd_N:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d332964344d617b00ded502be431758c649b8744/crates/blockifier/src/concurrency/worker_logic_test.rs#L122)):*
> ```XML
>     // This is because when executing transaction in concurrency mode on, we manually remove the
>     // writes and reads to and from the sequencer balance (to avoid the inevitable dependency
>     // between all the transactions)
> ```





_Suggestion:_
```XML
tions).
```

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1897)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Pull request merged**
