### PR TITLE
refactor: move the event size limit constants into versioned_constants

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1490)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
python PR: https://reviewable.io/reviews/starkware-industries/starkware/33954#-

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1490#-:-NqSK1Sv1DOKFWEDT-at:b-z6qxh8)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by elintul — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1490)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1490#-NqSPqv4AUcu8q5USV1D:-NqSPqv4AUcu8q5USV1E:bstoy9p) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0a797c545bf9f5714918af608ff6a8569d83098/crates/blockifier/resources/versioned_constants.json#L11)):*
> ```JSON
>         "milligas_per_code_byte": 875
>     },
>     "event_size_limit": {
> ```

Alphabetize? 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1835 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1490#-NqSTcjN6lvdSX8eT6Kw:-NqSTcjN6lvdSX8eT6Kx:b-l22lm6) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0a797c545bf9f5714918af608ff6a8569d83098/crates/blockifier/src/transaction/transactions_test.rs#L1835)):*
> ```XML
> 
> fn max_n_emitted_events() -> usize {
>     let versioned_constants = VersionedConstants::create_for_testing();
> ```

Any way to create it once?



_Code quote:_
```XML
let versioned_constants = VersionedConstants::create_for_testing();
```

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1490)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1490)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/resources/versioned_constants.json` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1490#-NqSPqv4AUcu8q5USV1D:-NqW0Q3w77DbmZ7KoIPY:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0a797c545bf9f5714918af608ff6a8569d83098/crates/blockifier/resources/versioned_constants.json#L11)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Alphabetize?
</blockquote></details>

done
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1835 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1490#-NqSTcjN6lvdSX8eT6Kw:-NqW0Qy2CFuPgs0x576-:b9v2gjc) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0a797c545bf9f5714918af608ff6a8569d83098/crates/blockifier/src/transaction/transactions_test.rs#L1835)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Any way to create it once?
</blockquote></details>

done with lazy const

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1490#-:-NqX4wX57EE_DvUn_XTe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1490)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 329 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1490#-NqaxwO47djan8sPrATs:-NqaxwO5AugPermP7FwB:b32wzj) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b38fb9a253a16b39f763b2ed3cb4f288bd6a39b/crates/blockifier/src/execution/syscalls/mod.rs#L329)):*
> ```XML
>         execution_context.n_emitted_events + 1,
>         &request.content,
>     )?;
> ```

x2



_Suggestion:_
```XML
    exceeds_event_size_limit(
        &syscall_handler.context.versioned_constants(),
        execution_context.n_emitted_events + 1,
        &request.content,
    )?;
```

**Pull request merged**
