### PR TITLE
Add two additional fields to `CallExecution`: `gas_consumed` and `failure_flag`.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/477)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
These fields only exist in `CallInfo`s from 0.11 onwards, so @alonh5  - you'll have to handle them separately in older blocks when validating.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/477#-:-NVZacD0947BNVKYTQ0A:b-bkfsqf)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/477)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/477#-NVbuWby3J3EKA6hfipH:-NVbuWby3J3EKA6hfipI:b-6ec00o) ([raw file](https://github.com/starkware-libs/blockifier/blob/78f4874c464735e1b8063d8bf842af8d449c9c16/crates/blockifier/src/execution/entry_point.rs#L171)):*
> ```XML
>     pub l2_to_l1_messages: Vec<OrderedL2ToL1Message>,
>     pub gas_consumed: StarkFelt,
>     pub failure_flag: bool,
> ```

I wonder if we should entail this flag in a `Result` object.



_Code quote:_
```XML
pub failure_flag: bool,
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/477#-NVbuhT6EFvlOW8hCxMM:-NVbuhT6EFvlOW8hCxMN:b-u3b6a1) ([raw file](https://github.com/starkware-libs/blockifier/blob/78f4874c464735e1b8063d8bf842af8d449c9c16/crates/native_blockifier/src/py_transaction_execution_info.rs#L99)):*
> ```XML
>             calldata: to_py_vec(call.calldata.0.to_vec(), PyFelt),
>             gas_consumed: PyFelt(execution.gas_consumed),
>             failure_flag: PyFelt::from(execution.failure_flag as u64),
> ```

Can we use `u8`? Also for types (call type, EP type, etc.).



_Code quote:_
```XML
u64
```

**Review by noaov1 — COMMENTED** [review]
@giladchase  FYI

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/477#-:-NW1e1yO3fCrG6pReIJ0:b-6uv90m)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @spapinistarkware)

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/477#-:-NW1mmjW8BYrMzPaj4Q6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/477#-NVbuWby3J3EKA6hfipH:-NW1mex20RnPBE4q-g2y:b95walo) ([raw file](https://github.com/starkware-libs/blockifier/blob/78f4874c464735e1b8063d8bf842af8d449c9c16/crates/blockifier/src/execution/entry_point.rs#L171)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Still relevant? I think it's easier to convert from `MaybeRelocatable` to `bool` rather than `Result`. WDYT?
</blockquote></details>

Not here, I believe Shahar partially took care of it.

**Pull request merged**
