### PR TITLE
Pass remaining_gas between shared calls.

### PR DESCRIPTION
**Pull request by noaov1**
Based on #545.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWh39HaBA0JEtOXh1Bd:-NWh39HaBA0JEtOXh1Be:b-t1fw66) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b2859c705ce784aed6ca12de399b0ba5155768f/crates/blockifier/src/transaction/account_transaction.rs#L235)):*
> ```XML
>         };
> 
>         Ok(fee_transfer_call.execute(state, context, &abi_constants::INITIAL_GAS_COST.into())?)
> ```

Same as in [python](https://github.com/starkware-industries/starkware/blob/9698a87b65d70c73317bce5b401a63254c8a0787/src/starkware/starknet/business_logic/transaction/fee.py#L43). I will check why and add documentation.



_Code quote:_
```XML
abi_constants::INITIAL_GAS_COST
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWp8cHA4gYMS8rT1Ftj:-NWp8cHA4gYMS8rT1Ftk:bvb3nqw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b2859c705ce784aed6ca12de399b0ba5155768f/crates/blockifier/src/transaction/account_transaction.rs#L235)):*
> ```XML
>         };
> 
>         Ok(fee_transfer_call.execute(state, context, &abi_constants::INITIAL_GAS_COST.into())?)
> ```

Give this a name, although would be similar to the constant name.



_Code quote:_
```XML
&abi_constants::INITIAL_GAS_COST.into()
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWgMd7o6vnkRNfPe2ZG:-NWp84YU3rKc_hu_c4hr:b-8xk7n8) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b2859c705ce784aed6ca12de399b0ba5155768f/crates/blockifier/src/transaction/transaction_execution.rs#L31)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It corresponds to [this](https://github.com/starkware-industries/starkware/blob/6b440ea51a04e28628336e17c29581a8ecac263f/src/starkware/starknet/business_logic/transaction/state_objects.py#L170). 
</blockquote></details>

Add a short docstring.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWp8IcO0ls3mThQAkbr:-NWp8IcO0ls3mThQAkbs:b-7crvy5) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b2859c705ce784aed6ca12de399b0ba5155768f/crates/blockifier/src/transaction/transactions.rs#L189)):*
> ```XML
>         let call_info = deployment_result
>             .map_err(TransactionExecutionError::ContractConstructorExecutionFailed)?;
>         *remaining_gas -= stark_felt_to_felt(call_info.execution.gas_consumed);
> ```

This is duplicated; perhaps it can be done in a shared location (inside `execute`)?



_Code quote:_
```XML
*remaining_gas -= stark_felt_to_felt(call_info.execution.gas_consumed);
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 259 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWqgGPIAwr-elI-u0dn:-NWqgGPIAwr-elI-u0do:b-r6vhws) ([raw file](https://github.com/starkware-libs/blockifier/blob/983ad71a67c6330ed2d727c51c8ff641ba5cec68/crates/blockifier/src/execution/entry_point.rs#L259)):*
> ```XML
> 
> // TODO(Noa,01/06/2023): Consider refactoring to reduce the number of parameters.
> #[allow(clippy::too_many_arguments)]
> ```

Let's try to reduce it now.
Consider adding a TransactionContext for code_address, storage_address, caller_address

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 259 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWqgGPIAwr-elI-u0dn:-NWqgwmZCe_MNAeyVfoM:bzdb9gp) ([raw file](https://github.com/starkware-libs/blockifier/blob/983ad71a67c6330ed2d727c51c8ff641ba5cec68/crates/blockifier/src/execution/entry_point.rs#L259)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Let's try to reduce it now.
Consider adding a TransactionContext for code_address, storage_address, caller_address
</blockquote></details>

Also class_hash

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 3 of 9 files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWqhEf99EFPgzXdX2Qb:-NWqhEf99EFPgzXdX2Qc:b4972wa) ([raw file](https://github.com/starkware-libs/blockifier/blob/983ad71a67c6330ed2d727c51c8ff641ba5cec68/crates/blockifier/src/transaction/account_transaction.rs#L182)):*
> ```XML
>             String::from(constants::VALIDATE_ENTRY_POINT_NAME),
>         )?;
>         *remaining_gas -= stark_felt_to_felt(validate_call_info.execution.gas_consumed);
> ```

Where is this coming from? Can we trust it?



_Code quote:_
```XML
gas_consumed
```

**Review by elintul — COMMENTED** [review]
> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWqwTqU6IGYYrRpmW1m:-NWqwTqU6IGYYrRpmW1n:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/983ad71a67c6330ed2d727c51c8ff641ba5cec68/crates/blockifier/src/transaction/account_transaction.rs#L234)):*
> ```XML
>             call_type: CallType::Call,
>         };
>         // The fee-token contract is a cairo0 contract, hence the initial gas is irrelevant.
> ```





_Suggestion:_
```XML
Cairo 0
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 259 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWqgGPIAwr-elI-u0dn:-NXA4JC7AuWxH8TovsGr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/983ad71a67c6330ed2d727c51c8ff641ba5cec68/crates/blockifier/src/execution/entry_point.rs#L259)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Also class_hash
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 197 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWqh28-8nKfHHG2SSfY:-NXAHRR5EadIDfTHmNZz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/983ad71a67c6330ed2d727c51c8ff641ba5cec68/crates/blockifier/src/execution/execution_utils.rs#L197)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWqhEf99EFPgzXdX2Qb:-NWr4rgHA0NJV7RiTCD0:b-3whrbs) ([raw file](https://github.com/starkware-libs/blockifier/blob/983ad71a67c6330ed2d727c51c8ff641ba5cec68/crates/blockifier/src/transaction/account_transaction.rs#L182)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Where is this coming from? Can we trust it?
</blockquote></details>

This is the return result of an entry point execution (in one of the following PRs I read it from the stack).

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXAHw5CCuzKqk0q5dUz:-NXAHw5CCuzKqk0q5dV-:b-has79) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da2803db6710d6a0ac241d73ab7148f7cf1d85f/crates/blockifier/src/transaction/account_transaction.rs#L180)):*
> ```XML
>             caller_address: ContractAddress::default(),
>             call_type: CallType::Call,
>             initial_gas: remaining_gas.clone(),
> ```

I wonder if adding the `initial_gas` to `CallEntryPoint` is indeed better. This saves us passing`remaining_gas` to `execute_inner_call`, but it forces us to clone it before creating an entry point (we can't move it as we maintain it throughout the run). @spapinistarkware WDYT?
We can also change the `initial_gas` field to be of type `u128` (if it is big enough).



_Code quote:_
```XML
remaining_gas.clone()
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXAHw5CCuzKqk0q5dUz:-NXEuFtE4kgMS1Hooqe9:b3leupg) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da2803db6710d6a0ac241d73ab7148f7cf1d85f/crates/blockifier/src/transaction/account_transaction.rs#L180)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if adding the `initial_gas` to `CallEntryPoint` is indeed better. This saves us passing`remaining_gas` to `execute_inner_call`, but it forces us to clone it before creating an entry point (we can't move it as we maintain it throughout the run). @spapinistarkware WDYT?
We can also change the `initial_gas` field to be of type `u128` (if it is big enough).
</blockquote></details>

Correction: It saves us nothing. It just makes more sense (?).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 4 of 9 files reviewed, 9 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXJBfiw7cYe21zV7Ieo:-NXJBfiw7cYe21zV7Iep:b-xn5hqu) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5d614704bba3ca9ca4faf37848e9430828f287c/crates/blockifier/src/execution/entry_point.rs#L52)):*
> ```XML
> }
> 
> pub struct TransactionContext {
> ```

Add a comment on `code_address`; it's used only in `deploy()` syscall.



_Suggestion:_
```XML
ConstructorContext
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 304 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXJARBF80Pr-_wsAu4z:-NXJARBF80Pr-_wsAu5-:bal4l1n) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5d614704bba3ca9ca4faf37848e9430828f287c/crates/blockifier/src/execution/entry_point.rs#L304)):*
> ```XML
>     let Some(constructor_selector) = contract_class.constructor_selector() else {
>         // Contract has no constructor.
>         return handle_empty_constructor(
> ```

Can you squash lines?



_Code quote:_
```XML
return handle_empty_constructor
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 301 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXJAlxk31V-jFqiVqa1:-NXJAlxk31V-jFqiVqa2:bbqgda1) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5d614704bba3ca9ca4faf37848e9430828f287c/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L301)):*
> ```XML
>         },
>         request.constructor_calldata,
>         constants::INITIAL_GAS_COST.into(),
> ```

Give it a name.



_Code quote:_
```XML
constants::INITIAL_GAS_COST.into(),
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 226 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXJAq_g8imrozBlmk1m:-NXJAq_g8imrozBlmk1n:b-7ke797) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5d614704bba3ca9ca4faf37848e9430828f287c/crates/blockifier/src/execution/syscalls/mod.rs#L226)):*
> ```XML
>     )?;
> 
>     let call_info = execute_deployment(
> ```

Give both new arguments names.



_Code quote:_
```XML
 execute_deployment
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXAHw5CCuzKqk0q5dUz:-NXJB1As1Rhk1LYuZO93:b-tp7dln) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da2803db6710d6a0ac241d73ab7148f7cf1d85f/crates/blockifier/src/transaction/account_transaction.rs#L180)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Correction: It saves us nothing. It just makes more sense (?). 
</blockquote></details>

Please ask on Slack, so we can advance.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 4 of 9 files reviewed, 9 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWp8IcO0ls3mThQAkbr:-NXJCSzmB_dAXjLgNlkm:b3xu76v) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b2859c705ce784aed6ca12de399b0ba5155768f/crates/blockifier/src/transaction/transactions.rs#L189)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM? Inside `execute_raw` of an account transaction?
</blockquote></details>

In a common location that makes sense. Try to understand where are you making this action and see if you can find one. If repeating is still needed, consider defining a small utility.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWqhEf99EFPgzXdX2Qb:-NXKFI3I3GQ_TG2O2UXU:bmzg5di) ([raw file](https://github.com/starkware-libs/blockifier/blob/983ad71a67c6330ed2d727c51c8ff641ba5cec68/crates/blockifier/src/transaction/account_transaction.rs#L182)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

This is the return result of an entry point execution (in one of the following PRs I read it from the stack).
</blockquote></details>

The returned value usually is the remaining gas, not the consumed, right?

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 7 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: all files reviewed, 7 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXJBfiw7cYe21zV7Ieo:-NXK5JCz4n23q9bAbPMx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5d614704bba3ca9ca4faf37848e9430828f287c/crates/blockifier/src/execution/entry_point.rs#L52)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a comment on `code_address`; it's used only in `deploy()` syscall.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWqhEf99EFPgzXdX2Qb:-NXKG9_D6TJzH1m452sS:b-14ketm) ([raw file](https://github.com/starkware-libs/blockifier/blob/983ad71a67c6330ed2d727c51c8ff641ba5cec68/crates/blockifier/src/transaction/account_transaction.rs#L182)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The returned value usually is the remaining gas, not the consumed, right?
</blockquote></details>

You are right. We calculate the `gas_consumed` by subtracting the remaining gas from the initial gas. 
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXAHw5CCuzKqk0q5dUz:-NXKi9WGCZKbiGhCdtrx:b-35ucxb) ([raw file](https://github.com/starkware-libs/blockifier/blob/6da2803db6710d6a0ac241d73ab7148f7cf1d85f/crates/blockifier/src/transaction/account_transaction.rs#L180)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please ask on Slack, so we can advance.
</blockquote></details>

After asking- it's possible to change the `initial_gas` filed to type `u128`.  Will do after merging all the gas related PRs.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWp8IcO0ls3mThQAkbr:-NXKI0bv0kIdRIw2KNAR:b9k44rs) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b2859c705ce784aed6ca12de399b0ba5155768f/crates/blockifier/src/transaction/transactions.rs#L189)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

In a common location that makes sense. Try to understand where are you making this action and see if you can find one. If repeating is still needed, consider defining a small utility.
</blockquote></details>

I can't think of a common location. I think it's better to have this update following the call to an entry point. Added a utility.

**Review by elintul — COMMENTED** [review]
> Reviewed 5 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: 8 of 12 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 269 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXKpiCKC8oEgdZrQPQT:-NXKpiCKC8oEgdZrQPQU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/210c885d3f9a8f8c0b21828e1b11c7131356c0e3/crates/blockifier/src/execution/entry_point.rs#L269)):*
> ```XML
>     state: &mut dyn State,
>     context: &mut ExecutionContext,
>     constructor_context: ConstructorContext,
> ```





_Suggestion:_
```XML
ctor_context
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 277 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NXKpfJk5LgK-AxaD5Sz:-NXKpfJk5LgK-AxaD5T-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/210c885d3f9a8f8c0b21828e1b11c7131356c0e3/crates/blockifier/src/execution/entry_point.rs#L277)):*
> ```XML
>     let Some(constructor_selector) = contract_class.constructor_selector() else {
>         // Contract has no constructor.
>         return handle_empty_constructor( constructor_context, calldata,remaining_gas);
> ```





_Suggestion:_
```XML
(constructor_context
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/546#-NWp8IcO0ls3mThQAkbr:-NXKrvzr3vxYNythXwco:b4zs3gq) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b2859c705ce784aed6ca12de399b0ba5155768f/crates/blockifier/src/transaction/transactions.rs#L189)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I can't think of a common location. I think it's better to have this update following the call to an entry point. Added a utility. 
</blockquote></details>

Is this how it is in Python?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546#-:-NXKy2CwClJoV_PKy4q-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r2, 3 of 9 files at r5, 4 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/546#-:-NXLCNgoAFTnVNAeCC94:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
