### PR TITLE
refactor: use gas_costs instead of gas_costs_map

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)

### CODE REVIEW

**Review by giladchase — DISMISSED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 364 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NsEKFeZCB9rm6m2v32M:-NsEKFe_05sThhOuXCub:bhpiy7n) ([raw file](https://github.com/starkware-libs/blockifier/blob/a68f782d86a66b5fd5c7dcc890c07df0a604d359/crates/blockifier/src/versioned_constants.rs#L364)):*
> ```XML
> 
>     // Invariant: fixed keys.
>     gas_costs_map: IndexMap<String, u64>,
> ```

Can't we remove this and only use gas_costs?



_Code quote:_
```XML
    gas_costs_map: IndexMap<String, u64>,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NsEKNy94AsbePvvsG-T:-NsEKNy94AsbePvvsG-U:b-2j80k3) ([raw file](https://github.com/starkware-libs/blockifier/blob/a68f782d86a66b5fd5c7dcc890c07df0a604d359/crates/blockifier/src/versioned_constants.rs#L455)):*
> ```XML
>     ];
> 
>     pub fn validate(&self) -> Result<(), OsConstantsSerdeError> {
> ```

I think we can remove this function, now that we're strongly typing (assuming the map field can be removed, which I think it can).
___
*[`crates/blockifier/src/versioned_constants.rs` line 478 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NsEMLo55FLRYAkjaijx:-NsEMLo55FLRYAkjaijy:bxobz9i) ([raw file](https://github.com/starkware-libs/blockifier/blob/a68f782d86a66b5fd5c7dcc890c07df0a604d359/crates/blockifier/src/versioned_constants.rs#L478)):*
> ```XML
>         let gas_costs_map = raw_json_data.parse_gas_costs()?;
>         let json_value = serde_json::to_value(&gas_costs_map).unwrap();
>         let gas_costs: GasCosts = serde_json::from_value(json_value).unwrap();
> ```

I think we can remove the whitelist of keys, since any missing keys will raise a serialization exception here, but with a `?` in order to return the error to the user



_Suggestion:_
```XML
        let gas_costs: GasCosts = serde_json::from_value(json_value)?;
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: 5 of 12 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 364 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NsEKFeZCB9rm6m2v32M:-NsZWW3d59DxfIapzUMe:b-24p27v) ([raw file](https://github.com/starkware-libs/blockifier/blob/a68f782d86a66b5fd5c7dcc890c07df0a604d359/crates/blockifier/src/versioned_constants.rs#L364)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can't we remove this and only use gas_costs?
</blockquote></details>

Yes, it will be removed in the next PR: https://reviewable.io/reviews/starkware-libs/blockifier/1620
___
*[`crates/blockifier/src/versioned_constants.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NsEKNy94AsbePvvsG-T:-NsZW_fG0OHyEK_GVN95:b-24p27v) ([raw file](https://github.com/starkware-libs/blockifier/blob/a68f782d86a66b5fd5c7dcc890c07df0a604d359/crates/blockifier/src/versioned_constants.rs#L455)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think we can remove this function, now that we're strongly typing (assuming the map field can be removed, which I think it can).
</blockquote></details>

Yes, it will be removed in the next PR: https://reviewable.io/reviews/starkware-libs/blockifier/1620
___
*[`crates/blockifier/src/versioned_constants.rs` line 478 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NsEMLo55FLRYAkjaijx:-NsZY22BCPG81yOFuF0_:b-ewtowp) ([raw file](https://github.com/starkware-libs/blockifier/blob/a68f782d86a66b5fd5c7dcc890c07df0a604d359/crates/blockifier/src/versioned_constants.rs#L478)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think we can remove the whitelist of keys, since any missing keys will raise a serialization exception here, but with a `?` in order to return the error to the user
</blockquote></details>

I will change the whitelist to include additional fields to ignore during the conversion.
PR: https://reviewable.io/reviews/starkware-libs/blockifier/1621

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, 4 of 6 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 495 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NsmjWGp11Aazyz045gC:-NsmjWGp11Aazyz045gD:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2dc728a39eaeda411d6a81d1c71138d8190e5f44/crates/blockifier/src/versioned_constants.rs#L495)):*
> ```XML
>         let gas_costs_map = raw_json_data.parse_gas_costs()?;
>         let gas_costs: GasCosts =
>             serde_json::to_value(&gas_costs_map).and_then(serde_json::from_value).unwrap();
> ```





_Suggestion:_
```XML
serde_json::to_value(&gas_costs_map).and_then(serde_json::from_value)?;
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 623 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NsnOXnY2xDgdFBb3Hpt:-Nsr2psW2n5nidW6LhNU:bq3qac9) ([raw file](https://github.com/starkware-libs/blockifier/blob/125bde375b7ed82762e9b3f2f36c7db43f5e67ae/crates/blockifier/src/versioned_constants.rs#L623)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

In order to use `?` instead of `unwrap` in the try_from, it has to (this solution was suggested by Noa)
</blockquote></details>

Where is the `?` that throws this error?

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 623 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NsnOXnY2xDgdFBb3Hpt:-Nsr9roTCINZXKTarJLe:b-lg81s0) ([raw file](https://github.com/starkware-libs/blockifier/blob/125bde375b7ed82762e9b3f2f36c7db43f5e67ae/crates/blockifier/src/versioned_constants.rs#L623)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Where is the `?` that throws this error?
</blockquote></details>

In the try_from:
serde_json::to_value(&gas_costs_map).and_then(serde_json::from_value)?; 
(previous change)

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-:-NsrZafO8tCWlnImHkWn:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 663 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NtWZsog1V8LMihMSeVu:-NtWZsog1V8LMihMSeVv:b7qomp1) ([raw file](https://github.com/starkware-libs/blockifier/blob/06d0035575ec826270493347c671a519dd4fb7f3/crates/blockifier/src/versioned_constants.rs#L663)):*
> ```XML
>         "Failed to convert OSConstantsRawJson to serde_json::Value and then to GasCosts : {0}"
>     )]
>     ParseError(#[from] serde_json::Error),
> ```

Where is it used?



_Code quote:_
```XML
    #[error(
        "Failed to convert OSConstantsRawJson to serde_json::Value and then to GasCosts : {0}"
    )]
    ParseError(#[from] serde_json::Error),
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 37 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NtWZzet4KGHvZnrjQBE:-NtWZzet4KGHvZnrjQBF:bgn1f9q) ([raw file](https://github.com/starkware-libs/blockifier/blob/06d0035575ec826270493347c671a519dd4fb7f3/crates/blockifier/src/versioned_constants_test.rs#L37)):*
> ```XML
>         versioned_constants.os_constants.gas_costs_map.len(),
>         OSConstants::ALLOWED_GAS_COST_NAMES.len()
>     );
> ```

Note to self- Removed in the next PR.



_Code quote:_
```XML
    assert_eq!(
        versioned_constants.os_constants.gas_costs_map.len(),
        OSConstants::ALLOWED_GAS_COST_NAMES.len()
    );
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 285 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NtWZR3QEibLpR0VThWl:-NtWZR3QEibLpR0VThWm:bjdr5g4) ([raw file](https://github.com/starkware-libs/blockifier/blob/06d0035575ec826270493347c671a519dd4fb7f3/crates/blockifier/src/execution/entry_point.rs#L285)):*
> ```XML
>     pub fn gas_costs(&self) -> &GasCosts {
>         &self.versioned_constants().os_constants.gas_costs
>     }
> ```

Please use it in the entire repo. 



_Code quote:_
```XML
    pub fn gas_costs(&self) -> &GasCosts {
        &self.versioned_constants().os_constants.gas_costs
    }
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 663 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NtWZsog1V8LMihMSeVu:-Ntq43lT2taM3Z4ySAi7:b-79ts9p) ([raw file](https://github.com/starkware-libs/blockifier/blob/06d0035575ec826270493347c671a519dd4fb7f3/crates/blockifier/src/versioned_constants.rs#L663)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Where is it used?
</blockquote></details>

It is required for the last `?` in line 522:
`serde_json::to_value(&gas_costs_map).and_then(serde_json::from_value)?;`
___
*[`crates/blockifier/src/execution/entry_point.rs` line 285 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NtWZR3QEibLpR0VThWl:-Ntq4HO0CtfKUp_FggjA:b-2bujj5) ([raw file](https://github.com/starkware-libs/blockifier/blob/06d0035575ec826270493347c671a519dd4fb7f3/crates/blockifier/src/execution/entry_point.rs#L285)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please use it in the entire repo.
</blockquote></details>

I am using it; did I miss a place?

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 663 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NtWZsog1V8LMihMSeVu:-Nttb5iA9hzNtbhLtoRO:br3aue2) ([raw file](https://github.com/starkware-libs/blockifier/blob/06d0035575ec826270493347c671a519dd4fb7f3/crates/blockifier/src/versioned_constants.rs#L663)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

It is required for the last `?` in line 522:
`serde_json::to_value(&gas_costs_map).and_then(serde_json::from_value)?;`
</blockquote></details>

Why did we decide to return an error now as opposed to panicking (as was done previously)?
___
*[`crates/blockifier/src/execution/entry_point.rs` line 285 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NtWZR3QEibLpR0VThWl:-Nttaa_48kJW2o5PIIeT:b-bs84t3) ([raw file](https://github.com/starkware-libs/blockifier/blob/06d0035575ec826270493347c671a519dd4fb7f3/crates/blockifier/src/execution/entry_point.rs#L285)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

I am using it; did I miss a place?
</blockquote></details>

Yes. Search `versioned_constants.os_constants`

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 649 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NttibTy6pbjm6Ihc79b:-NttibTy6pbjm6Ihc79c:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a8806bb3d460b8436fd2ba29cbcd2d5d67c9f6c/crates/blockifier/src/versioned_constants.rs#L649)):*
> ```XML
>     #[error(
>         "Failed to convert OSConstantsRawJson to serde_json::Value and then to GasCosts : {0}"
>     )]
> ```

WDYT?



_Suggestion:_
```XML
#[error(transparent)]
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: 8 of 12 files reviewed, 6 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 663 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NtWZsog1V8LMihMSeVu:-NttwU-tEuvw9tF0sX-w:bvwmxe6) ([raw file](https://github.com/starkware-libs/blockifier/blob/06d0035575ec826270493347c671a519dd4fb7f3/crates/blockifier/src/versioned_constants.rs#L663)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did we decide to return an error now as opposed to panicking (as was done previously)?
</blockquote></details>

We should have returned an error; I fixed it in the previous PR.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 285 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1618#-NtWZR3QEibLpR0VThWl:-NttweNo-TaDyFfo63eq:b-8alnl1) ([raw file](https://github.com/starkware-libs/blockifier/blob/06d0035575ec826270493347c671a519dd4fb7f3/crates/blockifier/src/execution/entry_point.rs#L285)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes. Search `versioned_constants.os_constants`
</blockquote></details>

This is a function of `EntryPointExecutionContext`; we can not use this function when we only have the versioned_constants.
We can create another function for VersionedConstants, but I think it is unnecessary in this case.

**Review by noaov1 — DISMISSED** [review]
> Reviewed 4 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1618)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
