### PR TITLE
Don't handle nonce in Txs of version 0.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/311)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/311)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/311#-NPMYppu9FI1nNqdMUnC:-NPMYppu9FI1nNqdMUnD:bgj5ge6) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc2281a1349132a40935fc0e434a0633f1783b6c/crates/blockifier/src/transaction/account_transaction.rs#L173)):*
> ```XML
>     ) -> TransactionExecutionResult<()> {
>         if account_tx_context.version == TransactionVersion(StarkFelt::from(0)) {
>             return Ok(());
> ```

Please add a small utility `is_declare_version0`; check both enum variant to be declare and the version to be 0.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/311)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/311#-NPMYppu9FI1nNqdMUnC:-NPMjoq26qEOqBElyrtX:b-hogud6) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc2281a1349132a40935fc0e434a0633f1783b6c/crates/blockifier/src/transaction/account_transaction.rs#L173)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please add a small utility `is_declare_version0`; check both enum variant to be declare and the version to be 0.
</blockquote></details>

Technically, any transaction of version 0 isn't an account transaction and therefore should skip the nonce handling. We just are only allowing `Declare`s of version 0, so this would be more of a sanity check for that, and would require adding `&self` as an argument. Do you think it's necessary?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/311)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/311#-NPMYppu9FI1nNqdMUnC:-NPMm98V8Qrra4ETqgeB:bix2vl3) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc2281a1349132a40935fc0e434a0633f1783b6c/crates/blockifier/src/transaction/account_transaction.rs#L173)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Technically, any transaction of version 0 isn't an account transaction and therefore should skip the nonce handling. We just are only allowing `Declare`s of version 0, so this would be more of a sanity check for that, and would require adding `&self` as an argument. Do you think it's necessary?
</blockquote></details>

I don't want to allow other version 0 transactions, but I agree that it's better if it's contained only in `verify_version`. 
Can you then delete the `// Only old `Declare` transactions should reach here.` comment?
Also, can you please point me to the Python code where I can see the nonce is indeed not being advanced (makes sense, but I want to be sure)??

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/311)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/311#-NPMYppu9FI1nNqdMUnC:-NPNCgW888qm6r5XP3dl:bn54r4z) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc2281a1349132a40935fc0e434a0633f1783b6c/crates/blockifier/src/transaction/account_transaction.rs#L173)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I don't want to allow other version 0 transactions, but I agree that it's better if it's contained only in `verify_version`. 
Can you then delete the `// Only old `Declare` transactions should reach here.` comment?
Also, can you please point me to the Python code where I can see the nonce is indeed not being advanced (makes sense, but I want to be sure)??
</blockquote></details>

https://github.com/starkware-industries/starkware/blob/63c02ad8b2f2931ef2c358da1dc6731ed3148b86/src/starkware/starknet/business_logic/transaction/objects.py#L399

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/311#-:-NPNFV_U3Zt75M4yrGUa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
