### PR TITLE
Dori/create struct for invoke tx creation

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/939)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
I'm assuming it is big because it's all an aggregation of fields into a struct? any other changes besides this?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/939#-:-NfGuWAC9YWuHm1OCCMZ:bu4mgfb)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
No changes. But, I would pay attention to where `InvokeTxArgs::default()` is used, to make sure it is correct.
For example, in cases where `TransactionVersion::ONE` should be used, it must be set explicitly in the struct, because the `default` is `TransactionVersion::ZERO` IIUC

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/939#-:-NfGxWAhAYXSZiOJB7hm:bytlowt)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/939)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/test_utils.rs` line 387 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/939#-Nfk7z-l0zk8KBKQ3IDy:-Nfk7z-m7KloL47zMB7Y:bdifp1g) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c1c6e42d502268869107b4972b1f3cc9ab73013/crates/blockifier/src/test_utils.rs#L387)):*
> ```XML
>     pub account_address: ContractAddress,
>     pub max_fee: Fee,
>     pub entry_point_selector: Option<EntryPointSelector>,
> ```

What does `None` mean?
If it's only for V0, add a short comment on that.



_Code quote:_
```XML
Option<EntryPointSelector>
```
___
*[`crates/blockifier/src/test_utils.rs` line 388 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/939#-Nfk7sdgEVJYOYNWiJ1r:-Nfk7sdgEVJYOYNWiJ1s:b-42ck0q) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c1c6e42d502268869107b4972b1f3cc9ab73013/crates/blockifier/src/test_utils.rs#L388)):*
> ```XML
>     pub max_fee: Fee,
>     pub entry_point_selector: Option<EntryPointSelector>,
>     pub signature: Option<TransactionSignature>,
> ```

Why option, doesn't an empty signature do the trick?



_Code quote:_
```XML
Option<TransactionSignature>
```
___
*[`crates/blockifier/src/test_utils.rs` line 389 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/939#-Nfk7SSp4y_5HUoeI_va:-Nfk7SSp4y_5HUoeI_vb:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c1c6e42d502268869107b4972b1f3cc9ab73013/crates/blockifier/src/test_utils.rs#L389)):*
> ```XML
>     pub entry_point_selector: Option<EntryPointSelector>,
>     pub signature: Option<TransactionSignature>,
>     pub tx_version: TransactionVersion,
> ```





_Suggestion:_
```XML
    pub max_fee: Fee,
    pub signature: Option<TransactionSignature>,
    pub sender_address: ContractAddress,
    pub calldata: Calldata,
    pub entry_point_selector: Option<EntryPointSelector>,
    pub version: TransactionVersion,
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/939#-Nfk8iOO8ctDLqOcCifR:-Nfk8iOP7x34Qp0yPweP:bb775xb) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c9773b1ab676fa52888ed996a1f0b62e02048f9/crates/blockifier/src/transaction/test_utils.rs#L220)):*
> ```XML
> }
> 
> #[allow(clippy::too_many_arguments)]
> ```

YES!



_Code quote:_
```XML
#[allow(clippy::too_many_arguments)]
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/939)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/test_utils.rs` line 387 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/939#-Nfk7z-l0zk8KBKQ3IDy:-NfkF-oB3uEFsmwHk_Ij:b-rh9qn0) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c1c6e42d502268869107b4972b1f3cc9ab73013/crates/blockifier/src/test_utils.rs#L387)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does `None` mean?
If it's only for V0, add a short comment on that.
</blockquote></details>

It's only for v0. Maybe block me [here](https://reviewable.io/reviews/starkware-libs/blockifier/949) with this comment and tell me which fields are specific to which tx version?
___
*[`crates/blockifier/src/test_utils.rs` line 388 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/939#-Nfk7sdgEVJYOYNWiJ1r:-NfkFoieDS98p3AbSH3b:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c1c6e42d502268869107b4972b1f3cc9ab73013/crates/blockifier/src/test_utils.rs#L388)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why option, doesn't an empty signature do the trick?
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/939#-Nfk8iOO8ctDLqOcCifR:-NfkHCNY4lcSno2wPsMw:b-5tfs2t) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c9773b1ab676fa52888ed996a1f0b62e02048f9/crates/blockifier/src/transaction/test_utils.rs#L220)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

YES!
</blockquote></details>

that was the point :P glad you like it

**Pull request merged**
