### PR TITLE
test(concurrency): add versioned state proxy flow test

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1828)

### CODE REVIEW

**Review by OriStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1828)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1828#-Ny_9IHi8KAjawmB1lvO:-Ny_9IHi8KAjawmB1lvP:bccci6b) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7dc6ad3316fd5131cfd53627e4e95aae8ede8ff/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L391)):*
> ```XML
>     let safe_versioned_state = ThreadSafeVersionedState(Arc::clone(&versioned_state));
>     let mut transactional_states: Vec<CachedState<VersionedStateProxy<DictStateReader>>> =
>         (0..4).map(|i| CachedState::from(safe_versioned_state.pin_version(i))).collect();
> ```

Please use TransactionalState::create_transactinal.



_Code quote:_
```XML
CachedState::from
```

**Review by OriStarkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1828#-:-NynXFGK6C8WDRhVpBNO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1828)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 520 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1828#-NynkDx93WX3Z2vGznYn:-NynkDx93WX3Z2vGznYo:b-noown1) ([raw file](https://github.com/starkware-libs/blockifier/blob/95131d1d546a7664e045fd85d1f4e2fd925cf14c/crates/blockifier/src/concurrency/versioned_state_test.rs#L520)):*
> ```XML
> 
>     transactional_states[0].set_contract_class(class_hash, contract_class_0).unwrap();
>     transactional_states[2].set_contract_class(class_hash, contract_class_2.clone()).unwrap();
> ```

Do you think it can happen in a regular flow?
Two contract classes with the same class hash?



_Code quote:_
```XML
    transactional_states[0].set_contract_class(class_hash, contract_class_0).unwrap();
    transactional_states[2].set_contract_class(class_hash, contract_class_2.clone()).unwrap();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 523 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1828#-Nynkm_r9o8RQske1-tH:-Nynkm_r9o8RQske1-tI:b-kt0mo0) ([raw file](https://github.com/starkware-libs/blockifier/blob/95131d1d546a7664e045fd85d1f4e2fd925cf14c/crates/blockifier/src/concurrency/versioned_state_test.rs#L523)):*
> ```XML
> 
>     // Apply the changes.
>     for (i, transactional_state) in transactional_states.iter_mut().enumerate().take(4) {
> ```

What is the meaning of `take` here?



_Code quote:_
```XML
for (i, transactional_state) in transactional_states.iter_mut().enumerate().take(4) {
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1828)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 520 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1828#-NynkDx93WX3Z2vGznYn:-NysT2yc6Ctt1-pox4xi:b3i0w5u) ([raw file](https://github.com/starkware-libs/blockifier/blob/95131d1d546a7664e045fd85d1f4e2fd925cf14c/crates/blockifier/src/concurrency/versioned_state_test.rs#L520)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do you think it can happen in a regular flow?
Two contract classes with the same class hash?
</blockquote></details>

Hmmm, the same sender sent two transactions that declare the same contract. It generates the same class hash, right? 
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 523 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1828#-Nynkm_r9o8RQske1-tH:-NysSZbP0HomoK6l_6nk:bdak4lf) ([raw file](https://github.com/starkware-libs/blockifier/blob/95131d1d546a7664e045fd85d1f4e2fd925cf14c/crates/blockifier/src/concurrency/versioned_state_test.rs#L523)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is the meaning of `take` here?
</blockquote></details>

It limits the iterator to the first 4 elements.
I see that it's redundant, removed.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1828#-Ny_9IHi8KAjawmB1lvO:-Ny_bGxE6hlJUiNPr4sL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7dc6ad3316fd5131cfd53627e4e95aae8ede8ff/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L391)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Please use TransactionalState::create_transactinal.
</blockquote></details>

Done.

**Review by OriStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1828)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1828)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 520 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1828#-NynkDx93WX3Z2vGznYn:-Nz2vnBy-8u1n1Iaagao:b-4vaykf) ([raw file](https://github.com/starkware-libs/blockifier/blob/95131d1d546a7664e045fd85d1f4e2fd925cf14c/crates/blockifier/src/concurrency/versioned_state_test.rs#L520)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

But it is not the same contract, right?
</blockquote></details>

I see your point. It's cannot happen in a real scenario.
Though, I think we should keep it to check the contract class state that involves a different mapping, (it's not part of the `StateCache`).

WDYT?

**Review by OriStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1828)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 520 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1828#-NynkDx93WX3Z2vGznYn:-Nz3GSOBD_kimZfDppyH:b54w98) ([raw file](https://github.com/starkware-libs/blockifier/blob/95131d1d546a7664e045fd85d1f4e2fd925cf14c/crates/blockifier/src/concurrency/versioned_state_test.rs#L520)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I see your point. It's cannot happen in a real scenario.
Though, I think we should keep it to check the contract class state that involves a different mapping, (it's not part of the `StateCache`).

WDYT?
</blockquote></details>

I think we should keep the check :)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1828)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @Yoni-Starkware)

**Pull request merged**
