### PR TITLE
Add `actual_resources` to `PyTransactionExecutionInfo`.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/408)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
[Python PR](https://github.com/starkware-industries/starkware/pull/29433) (note to self)
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/408#-:-NT-9VTqCbCgRi3V-MxX:b-djs5hk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/408)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/408#-NT-DnYK32NBcSNXMNhZ:-NT-DnYK32NBcSNXMNh_:b-nutpd2) (no related file):*
Waiting with this too.

___

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/408)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/408)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/408#-:-NT9dbqC6iE0wBFI9H2-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
