### PR TITLE
refactor: restructure old_block_number_and_hash as a struct

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1403)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1403#-:-NpU8JkWDrh0-5xvvrcS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1403#-NpU8KzJAtw85ZUsNfuB:-NpU8KzK0ot_NCVR6o8M:bta0nby) (no related file):*
Python PR?

___

**Review by Yael-Starkware — COMMENTED** [review]
https://reviewable.io/reviews/starkware-industries/starkware/33658#-

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1403#-:-NpUCmuJDrSoc1nhTg1s:bi9t6wz)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1403)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1403#-NpU8KzJAtw85ZUsNfuB:-NpUCovIDC5wIYvSjFo5:bi9t6wz) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Python PR?
</blockquote></details>

https://reviewable.io/reviews/starkware-industries/starkware/33658#-

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1403)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
