### PR TITLE
Remove redundant invoke_tx implementation in transaction_test

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/964)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/964)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 326 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/964#-NgT9n-P0fd2sAxcoFxR:-NgT9n-Q10-fn_CHcpKn:b5wftle) ([raw file](https://github.com/starkware-libs/blockifier/blob/0f31610c0643df1a089febb25701a1257b3f7ebf/crates/blockifier/src/transaction/transactions.rs#L326)):*
> ```XML
>         (signature, TransactionSignature),
>         (sender_address, ContractAddress)
>     );
> ```

Two comments on this not related to yr PR, but just for consideration:
- should this be an SN API trait rather than a macro? It is defined also in SN API with the same signature but with different implementation.
- Specifically for Blockifier, I think we can remove the macro and use `derive_more::deref` to delegate stuff to the inner `tx` field (this won't work for enum's though so not relevant for SN API)
```rust
#[derive(Debug, Clone, derive_more::deref)]
pub struct InvokeTransaction {
    #[deref]
    pub tx: starknet_api::transaction::InvokeTransaction,
    pub tx_hash: TransactionHash,
}
```



_Code quote:_
```XML
    implement_inner_tx_getter_calls!(
        (calldata, Calldata),
        (signature, TransactionSignature),
        (sender_address, ContractAddress)
    );
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/964#-NgTFhOoBXRDv_vgPuEF:-NgTFhOoBXRDv_vgPuEG:b-v4lh0b) ([raw file](https://github.com/starkware-libs/blockifier/blob/0f31610c0643df1a089febb25701a1257b3f7ebf/crates/blockifier/src/transaction/transactions_test.rs#L239)):*
> ```XML
> }
> 
> fn default_invoke_tx_args() -> InvokeTxArgs {
> ```

Should this be an `InvokeTxArgs` constructor?
We can call it `for_simple_invoke_tx` (I'm not sure `default` is ok to use given that there is already a `Default` impl for the struct).



_Code quote:_
```XML
default_invoke_tx_args
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/964)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 326 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/964#-NgT9n-P0fd2sAxcoFxR:-NgTvOGYCnwrIyZKk8kz:b825o3o) ([raw file](https://github.com/starkware-libs/blockifier/blob/0f31610c0643df1a089febb25701a1257b3f7ebf/crates/blockifier/src/transaction/transactions.rs#L326)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Two comments on this not related to yr PR, but just for consideration:
- should this be an SN API trait rather than a macro? It is defined also in SN API with the same signature but with different implementation.
- Specifically for Blockifier, I think we can remove the macro and use `derive_more::deref` to delegate stuff to the inner `tx` field (this won't work for enum's though so not relevant for SN API)
```rust
#[derive(Debug, Clone, derive_more::deref)]
pub struct InvokeTransaction {
    #[deref]
    pub tx: starknet_api::transaction::InvokeTransaction,
    pub tx_hash: TransactionHash,
}
```
</blockquote></details>

hmm... what does `derive_more::deref` and `#[deref]` actually do?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/964#-NgTFhOoBXRDv_vgPuEF:-NgTvWmYEeo0ULWQXzbq:b6mxhv8) ([raw file](https://github.com/starkware-libs/blockifier/blob/0f31610c0643df1a089febb25701a1257b3f7ebf/crates/blockifier/src/transaction/transactions_test.rs#L239)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should this be an `InvokeTxArgs` constructor?
We can call it `for_simple_invoke_tx` (I'm not sure `default` is ok to use given that there is already a `Default` impl for the struct).
</blockquote></details>

Do you think this constructor is relevant for *all* tests?
Or just for this module?
I prefer test-specific defaults to be in their own module

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/964)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 326 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/964#-NgT9n-P0fd2sAxcoFxR:-Nh0svIUD_QjNFjDd_IV:b-ih3l9i) ([raw file](https://github.com/starkware-libs/blockifier/blob/0f31610c0643df1a089febb25701a1257b3f7ebf/crates/blockifier/src/transaction/transactions.rs#L326)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmm... what does `derive_more::deref` and `#[deref]` actually do?
</blockquote></details>

`derive_more::deref`: for Newtypes, it implements `Deref`on the inner type, that is, `&outer-type` is automatically cast to `&inner-type` on demand (for example &String is automatically cast to &str when given as an arg to a function).

When derive for non-newtypes like the above, the `#[deref]` attr tells derive_more to implement the Deref on that field,
So in this example, any method call that expects a `&starknet_api::transaction::InvokeTransaction`arg (or even without the `&` for methods that want it as `self`), can be called with the above InvokeTransaction and it'll automatically delegate to the `tx` field.

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/964)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 239 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/964#-NgTFhOoBXRDv_vgPuEF:-Nh77t3o5fyXQC9-fejC:b8oy044) ([raw file](https://github.com/starkware-libs/blockifier/blob/0f31610c0643df1a089febb25701a1257b3f7ebf/crates/blockifier/src/transaction/transactions_test.rs#L239)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Do you think this constructor is relevant for *all* tests?
Or just for this module?
I prefer test-specific defaults to be in their own module
</blockquote></details>

yes yes i agree with you, my issue is just with the word "default", which (to me) implies trivial values.
Maybe return_result(2) counts as trivial, not sure.
Yr call, unblocking.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/964)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 326 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/964#-NgT9n-P0fd2sAxcoFxR:-NhL0Oz2CZ0v3gYtyPOc:b-4hbbhx) ([raw file](https://github.com/starkware-libs/blockifier/blob/0f31610c0643df1a089febb25701a1257b3f7ebf/crates/blockifier/src/transaction/transactions.rs#L326)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

oooh... interesting
IDK, WDYT?
</blockquote></details>

IIUC nearly all usages of these transactions access the inner `tx`, if that is indeed the case then `deref`ing to it is appropriate, even if it's somewhat implicit.
RE using I trait, might be too verbose IMO.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/964)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by giladchase — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/964)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
