### PR TITLE
Elin/merge main v0.12.2 into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 12 files at r4, 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: 9 of 15 files reviewed, all discussions resolved

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: 9 of 15 files reviewed, 4 unresolved discussions

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 21 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabF3c1DKq_1rJj9K7e:-NabF3c26rdj21d9E0hJ:b-uanu55) ([raw file](https://github.com/starkware-libs/blockifier/blob/56066d26f105646d4e39afd01fd4daecf844fc40/crates/blockifier/src/transaction/account_transaction.rs#L21)):*
> ```XML
> use crate::fee::gas_usage::estimate_minimal_fee;
> use crate::fee::os_resources::OS_RESOURCES;
> use crate::retdata;
> ```

Mainly took `main-v0.12.2` logic + `validate: bool` flag from `main`.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 4 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabFFLl-NZX7GnFjKni:-NabFFLl-NZX7GnFjKnj:b-p7qi2c) ([raw file](https://github.com/starkware-libs/blockifier/blob/56066d26f105646d4e39afd01fd4daecf844fc40/crates/blockifier/src/transaction/account_transactions_test.rs#L4)):*
> ```XML
> 
> use cairo_vm::vm::runners::cairo_runner::ResourceTracker;
> use rstest::{fixture, rstest};
> ```

Mainly took `main-v0.12.2` changes with the shorter way to construct `AccountTransaction::Invoke`.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 36 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabFBL6D9lA1n_EfwsX:-NabFBL6D9lA1n_EfwsY:bj2ggau) ([raw file](https://github.com/starkware-libs/blockifier/blob/56066d26f105646d4e39afd01fd4daecf844fc40/crates/blockifier/src/transaction/test_utils.rs#L36)):*
> ```XML
> pub const CALL_CONTRACT: u64 = 2;
> 
> impl From<InvokeTransactionV1> for InvokeTransaction {
> ```

Moved from `transaction_test.rs` since also needed here.



_Code quote:_
```XML
impl From<InvokeTransactionV1> for InvokeTransaction
```
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 160 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabFQL17yEFC-wRkhna:-NabFQL17yEFC-wRkhnb:bm7mvs1) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4d205433344d68bbda0c42efdc161a1e92ed05d/crates/native_blockifier/src/py_transaction_executor.rs#L160)):*
> ```XML
> 
> <<<<<<< HEAD
> ||||||| merged common ancestors
> ```

Moved to `transaction_executor.rs`; changes applied there.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: 9 of 15 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 160 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabFQL17yEFC-wRkhna:-NabG6CE9B9mbfXlJNd_:boy9zr9) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4d205433344d68bbda0c42efdc161a1e92ed05d/crates/native_blockifier/src/py_transaction_executor.rs#L160)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Moved to `transaction_executor.rs`; changes applied there.
</blockquote></details>

Sorry, it's `py_block_executor.rs`.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: 9 of 15 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 465 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabGPFa0_3y76_V6V45:-NabGPFa0_3y76_V6V46:b-3rm1no) ([raw file](https://github.com/starkware-libs/blockifier/blob/56066d26f105646d4e39afd01fd4daecf844fc40/crates/blockifier/src/transaction/account_transaction.rs#L465)):*
> ```XML
>         block_context: &BlockContext,
>         mut execution_context: EntryPointExecutionContext,
>         validate: bool,
> ```

a revertable tx is always validatible. No? Why should `run_revertible` get this input?



_Code quote:_
```XML
validate: bool
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 124 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabGknW0gtjQXEuxLA_:-NabGknX-7htUG875tny:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/56066d26f105646d4e39afd01fd4daecf844fc40/crates/blockifier/src/transaction/account_transactions_test.rs#L124)):*
> ```XML
>     let entry_point_selector = selector_from_name("deploy_contract");
>     let salt = ContractAddressSalt::default();
>     let class_hash = class_hash!(stark_felt!(TEST_CLASS_HASH));
> ```





_Suggestion:_
```XML
class_hash!(TEST_CLASS_HASH)
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 465 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabGPFa0_3y76_V6V45:-NabHwsh2iIbVz-MplLD:biy3smf) ([raw file](https://github.com/starkware-libs/blockifier/blob/56066d26f105646d4e39afd01fd4daecf844fc40/crates/blockifier/src/transaction/account_transaction.rs#L465)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

a revertable tx is always validatible. No? Why should `run_revertible` get this input?
</blockquote></details>

It's an API FN asked for execution; I think it should be supported in all scenarios. @noaov1?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 124 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabGknW0gtjQXEuxLA_:-NabI5yEB-l0viiSwQwt:b-npvgzo) ([raw file](https://github.com/starkware-libs/blockifier/blob/56066d26f105646d4e39afd01fd4daecf844fc40/crates/blockifier/src/transaction/account_transactions_test.rs#L124)):*
> ```XML
>     let entry_point_selector = selector_from_name("deploy_contract");
>     let salt = ContractAddressSalt::default();
>     let class_hash = class_hash!(stark_felt!(TEST_CLASS_HASH));
> ```

Haha, sorry.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 465 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabGPFa0_3y76_V6V45:-NabIYj32DkUSQFP3m2Z:b-djjqei) ([raw file](https://github.com/starkware-libs/blockifier/blob/56066d26f105646d4e39afd01fd4daecf844fc40/crates/blockifier/src/transaction/account_transaction.rs#L465)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's an API FN asked for execution; I think it should be supported in all scenarios. @noaov1?
</blockquote></details>

unblocking, but seems strange to pass `run_revertible` (which charges users on execution failure) and arg that can indicate there is no validation.
if it's useful only for tests then... maybe we need to think of something better in the future

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 465 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/803#-NabGPFa0_3y76_V6V45:-NabIvkX4j1JvGogl2CT:b-a2aa8m) ([raw file](https://github.com/starkware-libs/blockifier/blob/56066d26f105646d4e39afd01fd4daecf844fc40/crates/blockifier/src/transaction/account_transaction.rs#L465)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

unblocking, but seems strange to pass `run_revertible` (which charges users on execution failure) and arg that can indicate there is no validation.
if it's useful only for tests then... maybe we need to think of something better in the future
</blockquote></details>

This whole API is a bit dirty and should be refactored.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/803)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
