### PR TITLE
Readd FromPyObject to PyStateDiff

### PR DESCRIPTION
**Pull request by giladchase**
Must have been deleted in a merge conflict.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/289)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/289)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/289#-NOe7mQw2gwt6NhVV77S:-NOe7mQw2gwt6NhVV77T:b9xqiw4) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4f781b594d3b546cf6c71b037a12444b59625a6/crates/native_blockifier/src/py_state_diff.rs#L13)):*
> ```XML
> 
> #[pyclass]
> #[derive(Clone)]
> ```

Why is it no longer necessary?



_Code quote:_
```XML
#[derive(Clone)]
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/289)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/289#-NOe7mQw2gwt6NhVV77S:-NOeCsfi89a5NQ2U-Pej:bhircmx) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4f781b594d3b546cf6c71b037a12444b59625a6/crates/native_blockifier/src/py_state_diff.rs#L13)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it no longer necessary?
</blockquote></details>

It shouldn't have been there in the first place.

Without `FromPyObject`, the compiler complains and erroneously requests that `Clone` be implemented (you can test it out by removing them both and `cargo build`ing)
This makes the code compile on the Rust side, but doesn't work in python (because there is no FromPyObject implementation).

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/289)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/289#-NOe7mQw2gwt6NhVV77S:-NOeDj3c8j-IQMrer_o3:b6w5w8p) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4f781b594d3b546cf6c71b037a12444b59625a6/crates/native_blockifier/src/py_state_diff.rs#L13)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

It shouldn't have been there in the first place.

Without `FromPyObject`, the compiler complains and erroneously requests that `Clone` be implemented (you can test it out by removing them both and `cargo build`ing)
This makes the code compile on the Rust side, but doesn't work in python (because there is no FromPyObject implementation).
</blockquote></details>

Isn't it needed for the `get` macro?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/289)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/289#-NOe7mQw2gwt6NhVV77S:-NOeKdLRDjvKH27IFu3e:b6vomjv) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4f781b594d3b546cf6c71b037a12444b59625a6/crates/native_blockifier/src/py_state_diff.rs#L13)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Isn't it needed for the `get` macro?
</blockquote></details>

IUUC it's the field that needs `clone`, rather than the class holding the getter

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/289#-:-NOeL7yGBiM4C9MRMR4i:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/289#-NOe7mQw2gwt6NhVV77S:-NOeL1NT2_E2EXzx3fBI:b-ewnzhy) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4f781b594d3b546cf6c71b037a12444b59625a6/crates/native_blockifier/src/py_state_diff.rs#L13)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

IUUC it's the field that needs `clone`, rather than the class holding the getter 
</blockquote></details>

Oh, I see. Thanks :)

**Pull request merged**
