### PR TITLE
V3 support in max_invoke_steps

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1036)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1036)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 851 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1036#-NhbZZ2eA9F0qdNFBEUg:-NhbZZ2eA9F0qdNFBEUh:b-n2ad3x) ([raw file](https://github.com/starkware-libs/blockifier/blob/164eac67cfaa5457500a389b4984060fed180988/crates/blockifier/src/transaction/account_transactions_test.rs#L851)):*
> ```XML
>     } = create_test_init_data(Fee(MAX_FEE), block_context, state);
>     let actual_fee = 659500000000000;
>     let actual_gas_used = 2448;
> ```

@zuphitf or @noaov1 will need help fixing the min-fee estimation:
`2448` is the result of
```
tx_execution_info1.actual_resources.0.get(abi_constants::GAS_USAGE).unwrap();
```
(asserted near the end of the test).
However, the test currently fails, on this error:
```
MaxFeeTooLow { min_fee: Fee(583_000_000_000_000), max_fee: Fee(244_800_000_000_000) }
```
1. Is the user actually going to be charged for *more gas usage* than the `GAS_USAGE` in the actual resources?
2. If not, how do I compute the actual gas usage, to set as the max_amount?
3. If so, why?



_Code quote:_
```XML
 let actual_gas_used = 2448;
```

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1036)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1036#-Nhet5go4Vr8O8x7KuHm):*
Please make a single commit.



_Code quote:_
```
New commits in r2 on 25/10/2023 at 19:01:
- 164eac6: Test

  Signed-off-by: Dori Medini <dori@starkware.co>
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1036#-NhepZsXCT76OcfJgtw4:-NhepZsXCT76OcfJgtw5:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/164eac67cfaa5457500a389b4984060fed180988/crates/blockifier/src/execution/entry_point.rs#L207)):*
> ```XML
>         let block_upper_bound =
>             min(constants::MAX_STEPS_PER_TX, block_context.invoke_tx_max_n_steps as usize);
>         if !account_tx_context.enforce_fee() {
> ```





_Suggestion:_
```XML
            min(constants::MAX_STEPS_PER_TX, block_context.invoke_tx_max_n_steps as usize);
            
        if !account_tx_context.enforce_fee() {
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 232 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1036#-NhephngAXo0wzuBYvPe:-NhephngAXo0wzuBYvPf:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/164eac67cfaa5457500a389b4984060fed180988/crates/blockifier/src/execution/entry_point.rs#L232)):*
> ```XML
>         };
> 
>         min((tx_gas_upper_bound as f64 / gas_per_step).floor() as usize, block_upper_bound)
> ```





_Suggestion:_
```XML
        let cairo_steps = (tx_gas_upper_bound as f64 / gas_per_step).floor() as usize;
        min(cairo_steps, block_upper_bound)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1036)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @amosStarkware and @MohammadNassar1)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1036#-Nhet5go4Vr8O8x7KuHm):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please make a single commit.
</blockquote></details>

Why? I can squash and merge; useful for now to separate test from feature

**Review by MohammadNassar1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1036)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1036)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 851 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1036#-NhbZZ2eA9F0qdNFBEUg:-NheulyH1pL2uOTLO1yU:bs6er94) ([raw file](https://github.com/starkware-libs/blockifier/blob/164eac67cfaa5457500a389b4984060fed180988/crates/blockifier/src/transaction/account_transactions_test.rs#L851)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@zuphitf or @noaov1 will need help fixing the min-fee estimation:
`2448` is the result of
```
tx_execution_info1.actual_resources.0.get(abi_constants::GAS_USAGE).unwrap();
```
(asserted near the end of the test).
However, the test currently fails, on this error:
```
MaxFeeTooLow { min_fee: Fee(583_000_000_000_000), max_fee: Fee(244_800_000_000_000) }
```
1. Is the user actually going to be charged for *more gas usage* than the `GAS_USAGE` in the actual resources?
2. If not, how do I compute the actual gas usage, to set as the max_amount?
3. If so, why?
</blockquote></details>

The `GAS_USAGE` in the actual resources refers to the the "direct"`l1_gas_usage` (which may include, for example, the direct cost of L2-to-L1 messages, the data availability cost). To that, we add the the gas consumed by Cairo VM resource (i.e. the L1 gas consumed when submitting the underlying Cairo program to SHARP).

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1036)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
