### PR TITLE
feat(fee): modified calculate_tx_l1_gas_usage(s) added calculate_tx_gas_and_blob_gas_usage

### PR DESCRIPTION
**Pull request by aner-starkware**
Moving PR over to main-v0.13.1.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1370)

### CODE REVIEW

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1370#-:-Now8YkPCNArUd87T-Zm:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1370)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by aner-starkware — COMMENTED** [review]
I can't seem to merge

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1370#-:-NozxMbH6-ygW4s4qmp3:b-au590m)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1370)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1370)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
