### PR TITLE
test(concurrency): test try_commit method of the scheduler

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1894)

### CODE REVIEW

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1894)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 205 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-Ny-ELStC75TJqUp6t0q:-Ny-ELStC75TJqUp6t0r:bexgdwl) ([raw file](https://github.com/starkware-libs/blockifier/blob/083193b125b2658852341c21d70f375d4cc908bf/crates/blockifier/src/concurrency/scheduler_test.rs#L205)):*
> ```XML
> #[case::wrong_status_executing(TransactionStatus::Executing)]
> #[should_panic(expected = "Only aborting transactions can be re-executed. Transaction 0 is not \
>                            aborting. Transaction status: Committed.")]
> ```

Could you explain this panic syntax? Does it mean that the case under it should fail with the expected message?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 205 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-Ny-ELStC75TJqUp6t0q:-Ny-a1dx7LVUkDkD-GxB:b-4p0kml) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7efff90fc935ca70fb9a8f85f2944aca5c62e23/crates/blockifier/src/concurrency/scheduler_test.rs#L205)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Could you explain this panic syntax? Does it mean that the case under it should fail with the expected message?
</blockquote></details>

Yes. Because the method `set_ready_status` should only be run on a transaction in status `Executing`.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1894)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyEpEhn5pk0OuqJISjm:-NyEpEhn5pk0OuqJISjn:b-ugzns8) ([raw file](https://github.com/starkware-libs/blockifier/blob/8010ef62a46a7bba14d920d2990f1b576f0e287f/crates/blockifier/src/concurrency/scheduler_test.rs#L128)):*
> ```XML
> #[case::wrong_status_aborting(0, TransactionStatus::Aborting)]
> #[case::wrong_status_committed(0, TransactionStatus::Committed)]
> fn test_try_commit(
> ```

Does this test allow you to remove the `dead_code` decorator?



_Code quote:_
```XML
fn test_try_commit(
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyEpYQ-AqGcZFPPitu9:-NyEpYQ-AqGcZFPPituA:b-p87shh) ([raw file](https://github.com/starkware-libs/blockifier/blob/8010ef62a46a7bba14d920d2990f1b576f0e287f/crates/blockifier/src/concurrency/scheduler_test.rs#L136)):*
> ```XML
>     assert!(scheduler.try_commit_lock());
>     // Lock is already acquired.
>     assert!(!scheduler.try_commit_lock());
> ```

I wonder if its' interesting to check if after an unlock we can lock again



_Code quote:_
```XML
    assert!(!scheduler.try_commit_lock());
```
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyEosR8-JkLv5fP50Qt:-NyEosR9-hTwRHvaBCJL:brlzrsk) ([raw file](https://github.com/starkware-libs/blockifier/blob/8010ef62a46a7bba14d920d2990f1b576f0e287f/crates/blockifier/src/concurrency/scheduler_test.rs#L144)):*
> ```XML
>         if commit_index + 1 == DEFAULT_CHUNK_SIZE {
>             assert_eq!(scheduler.done_marker.load(Ordering::Acquire), true);
>         }
> ```

Add `else`?



_Code quote:_
```XML
        if commit_index + 1 == DEFAULT_CHUNK_SIZE {
            assert_eq!(scheduler.done_marker.load(Ordering::Acquire), true);
        }
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1894)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyEpEhn5pk0OuqJISjm:-NyFUNOqDzDugfPkjUsZ:bdbrmsa) ([raw file](https://github.com/starkware-libs/blockifier/blob/8010ef62a46a7bba14d920d2990f1b576f0e287f/crates/blockifier/src/concurrency/scheduler_test.rs#L128)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Does this test allow you to remove the `dead_code` decorator?
</blockquote></details>

It doesn't unfortunately.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyEpYQ-AqGcZFPPitu9:-NyFUVbf4Vdg91Fmvxgc:br74h8m) ([raw file](https://github.com/starkware-libs/blockifier/blob/8010ef62a46a7bba14d920d2990f1b576f0e287f/crates/blockifier/src/concurrency/scheduler_test.rs#L136)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if its' interesting to check if after an unlock we can lock again
</blockquote></details>

I wasn't sure how to test the lock properly because it is not really enforced that the lock is taken by the thread that is running the `try_commit`.

So I just opted to check both flows of the `try_commit_lock` method.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyEosR8-JkLv5fP50Qt:-NyFV19R57eUPPRpnwzA:b9qidql) ([raw file](https://github.com/starkware-libs/blockifier/blob/8010ef62a46a7bba14d920d2990f1b576f0e287f/crates/blockifier/src/concurrency/scheduler_test.rs#L144)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Add `else`?
</blockquote></details>

Done.

(I just compared the `done_marker` to the condition instead of using an `if` clause.)

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1894)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyEpYQ-AqGcZFPPitu9:-NyFzT9LDQefJNjy2Dgr:b-qk6sau) ([raw file](https://github.com/starkware-libs/blockifier/blob/8010ef62a46a7bba14d920d2990f1b576f0e287f/crates/blockifier/src/concurrency/scheduler_test.rs#L136)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I wasn't sure how to test the lock properly because it is not really enforced that the lock is taken by the thread that is running the `try_commit`.

So I just opted to check both flows of the `try_commit_lock` method.
</blockquote></details>

I suggested modification at the end of the test.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyEosR8-JkLv5fP50Qt:-NyFz65-EkydB5ifJJMC:b-83sjoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/8010ef62a46a7bba14d920d2990f1b576f0e287f/crates/blockifier/src/concurrency/scheduler_test.rs#L144)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.

(I just compared the `done_marker` to the condition instead of using an `if` clause.)
</blockquote></details>

Nice!
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyFzPbH9PpJvkatWcjg:-NyFzPbH9PpJvkatWcjh:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/858d805c11d55db7e12bb3c66cf7050c3ab9634e/crates/blockifier/src/concurrency/scheduler_test.rs#L151)):*
> ```XML
>     }
>     scheduler.unlock_commit_lock();
>     assert_eq!(scheduler.commit_lock.load(Ordering::Acquire), false);
> ```





_Suggestion:_
```XML
assert!(scheduler.try_commit_lock());
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyFzPbH9PpJvkatWcjg:-NyG2NcDA74S5uaDtkdJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/858d805c11d55db7e12bb3c66cf7050c3ab9634e/crates/blockifier/src/concurrency/scheduler_test.rs#L151)):*
> ```XML
>     }
>     scheduler.unlock_commit_lock();
>     assert_eq!(scheduler.commit_lock.load(Ordering::Acquire), false);
> ```

Done.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1894)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyEpEhn5pk0OuqJISjm:-NyG3rgx5QC-_5rO4xxo:b-sj4ewf) ([raw file](https://github.com/starkware-libs/blockifier/blob/8010ef62a46a7bba14d920d2990f1b576f0e287f/crates/blockifier/src/concurrency/scheduler_test.rs#L128)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

It doesn't unfortunately.
</blockquote></details>

Actually the two lock functions are supposed to be public. And making them public allows us to remove the `dead_code` annotation.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-:-NyG4WKK07aXV7EFG8L4:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 128 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyG5Wv35JdHNqtYu5QF:-NyG5Wv35JdHNqtYu5QG:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbe6c4163a79497ad93084077db0af0c7b0fe0c2/crates/blockifier/src/concurrency/scheduler_test.rs#L128)):*
> ```XML
> #[case::wrong_status_aborting(0, TransactionStatus::Aborting)]
> #[case::wrong_status_committed(0, TransactionStatus::Committed)]
> fn test_try_commit(
> ```





_Suggestion:_
```XML
fn test_commit_flow(
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 128 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1894#-NyG5Wv35JdHNqtYu5QF:-NyG6XfJBHlEkICh8AhW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbe6c4163a79497ad93084077db0af0c7b0fe0c2/crates/blockifier/src/concurrency/scheduler_test.rs#L128)):*
> ```XML
> #[case::wrong_status_aborting(0, TransactionStatus::Aborting)]
> #[case::wrong_status_committed(0, TransactionStatus::Committed)]
> fn test_try_commit(
> ```

Done.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1894)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @meship-starkware)

**Pull request merged**
