### PR TITLE
Added a test of formatting an error of entry point execution failure.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1071)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1071)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1071#-NiEVFwh5DnBysLAiD1j:-NiEVFwh5DnBysLAiD1k:br6vyw5) ([raw file](https://github.com/starkware-libs/blockifier/blob/60f36e950343a9c83621bca2b006d2700b38222a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L100)):*
> ```XML
> 
> pub const BYTE_ARRAY_MAGIC: &str =
>     "0x46a6158a16a947e5916b2a2ca68501a45e93d7110e81aa2d6438b1c57c879a3";
> ```

This constant should be defined in the compiler repo, correct?
And imported into the blockifier?



_Code quote:_
```XML
pub const BYTE_ARRAY_MAGIC: &str =
    "0x46a6158a16a947e5916b2a2ca68501a45e93d7110e81aa2d6438b1c57c879a3";
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 629 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1071#-NiEVS3V4_Ftw6ngbPFt:-NiEVS3V4_Ftw6ngbPFu:b8d9zp9) ([raw file](https://github.com/starkware-libs/blockifier/blob/60f36e950343a9c83621bca2b006d2700b38222a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L629)):*
> ```XML
>         "Execution failed. Failure reason: \
>          \"0x046a6158a16a947e5916b2a2ca68501a45e93d7110e81aa2d6438b1c57c879a3, , Execution \
>          failure, \\u{11}\"."
> ```

use `format!` and the `BYTE_ARRAY_MAGIC` const, don't hard code the string twice



_Code quote:_
```XML
        "Execution failed. Failure reason: \
         \"0x046a6158a16a947e5916b2a2ca68501a45e93d7110e81aa2d6438b1c57c879a3, , Execution \
         failure, \\u{11}\"."
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 629 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1071#-NiEW9WHEmaYPDayudRk:-NiEW9WHEmaYPDayudRl:b-duf29g) ([raw file](https://github.com/starkware-libs/blockifier/blob/60f36e950343a9c83621bca2b006d2700b38222a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L629)):*
> ```XML
>         "Execution failed. Failure reason: \
>          \"0x046a6158a16a947e5916b2a2ca68501a45e93d7110e81aa2d6438b1c57c879a3, , Execution \
>          failure, \\u{11}\"."
> ```

I don't understand what would fail if we upgrade to 2.4.0?
the `to_string` of the error variant is defined in the blockifier, right? so even after upgrading the compiler version this test will still pass...?



_Code quote:_
```XML
        get_dummy_string_execution_error().to_string(),
        "Execution failed. Failure reason: \
         \"0x046a6158a16a947e5916b2a2ca68501a45e93d7110e81aa2d6438b1c57c879a3, , Execution \
         failure, \\u{11}\"."
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 633 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1071#-NiEVdY36xczaLCR8BbJ:-NiEVdY36xczaLCR8BbK:buuiizz) ([raw file](https://github.com/starkware-libs/blockifier/blob/60f36e950343a9c83621bca2b006d2700b38222a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L633)):*
> ```XML
> }
> 
> // "Execution failure"
> ```

I don't understand from this docstring what the function does



_Code quote:_
```XML
// "Execution failure"
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 634 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1071#-NiEVjzM0jTkfjsnxUT4:-NiEVjzN-B4GLu4ZZ5Nv:bhg6jq0) ([raw file](https://github.com/starkware-libs/blockifier/blob/60f36e950343a9c83621bca2b006d2700b38222a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L634)):*
> ```XML
> 
> // "Execution failure"
> const DUMMY_EXECUTION_FAILURE_ERROR: &str = "0x457865637574696f6e206661696c757265";
> ```

1. this const isn't needed outside of `get_dummy_string_execution_error`, right?
move the definition inside the function; or just hard-code the string in the function.
2. Please document what this string represents; looks like a highly specific value



_Code quote:_
```XML
const DUMMY_EXECUTION_FAILURE_ERROR: &str = "0x457865637574696f6e206661696c757265";
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1071)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1071)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 629 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1071#-NiEW9WHEmaYPDayudRk:-NiFKMxa0B1iFcX_1955:b-79ajy1) ([raw file](https://github.com/starkware-libs/blockifier/blob/60f36e950343a9c83621bca2b006d2700b38222a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L629)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't understand what would fail if we upgrade to 2.4.0?
the `to_string` of the error variant is defined in the blockifier, right? so even after upgrading the compiler version this test will still pass...?
</blockquote></details>

The to_string uses `as_cairo_short_string` from cairo-lang-runner under the hood.
It changed since 2.3.0-rc0 to 2.4.0 which makes non-printable characters be formatted differently. Here, the 0x11 is non printable and thus is printed differently. I tested it by copying the current as_cairo_short_string and using it instead (in felts_as_str), and the test indeed failed.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 633 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1071#-NiEVdY36xczaLCR8BbJ:-NiFFl9T3wRN2HDd_lSL:b30hvec) ([raw file](https://github.com/starkware-libs/blockifier/blob/60f36e950343a9c83621bca2b006d2700b38222a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L633)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't understand from this docstring what the function does
</blockquote></details>

This was the doc for the constant. Anyway, inlined the function.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 634 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1071#-NiEVjzM0jTkfjsnxUT4:-NiFEJax9Ne4meE_IeBf:b-ugd1c0) ([raw file](https://github.com/starkware-libs/blockifier/blob/60f36e950343a9c83621bca2b006d2700b38222a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L634)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. this const isn't needed outside of `get_dummy_string_execution_error`, right?
move the definition inside the function; or just hard-code the string in the function.
2. Please document what this string represents; looks like a highly specific value
</blockquote></details>

Yes, it's  "Execution failure", as documented, the same way as constants are defined in hint_processor.rs.
I hard coded it with a comment trying to make it clearer.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1071#-NiEVFwh5DnBysLAiD1j:-NiFEH_QE0LJflzD7zAr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/60f36e950343a9c83621bca2b006d2700b38222a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L100)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This constant should be defined in the compiler repo, correct?
And imported into the blockifier?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1071#-:-NiFSNW4Buvo_MTOHkN6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
