### PR TITLE
test: add cairo0 variants to the new stack trace regression tests

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1371)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1371)* status: all files reviewed, 4 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 227 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1371#-NozwvDf0ryJc9O-IkOm:-NozwvDf0ryJc9O-IkOn:b-6ch2qb) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e52543451cc6a3972b94e03aa174ca360c54940/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L227)):*
> ```Cairo
>     // If the chain is too short, fail with division by zero.
>     if ((calldata_len * (calldata_len - 1) * (calldata_len - 2)) == 0) {
>         tempvar zero = calldata_len - calldata_len;
> ```

so sneaky lol



_Code quote:_
```Cairo
tempvar zero = calldata_len - calldata_len;
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 758 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1371#-NozxQWDCJ5jjYkxjYnL:-NozxQWDCJ5jjYkxjYnM:b-qh6o4b) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e52543451cc6a3972b94e03aa174ca360c54940/crates/blockifier/src/execution/entry_point_test.rs#L758)):*
> ```XML
>         CairoVersion::Cairo0 => expected_trace_cairo0,
>         CairoVersion::Cairo1 => expected_trace_cairo1,
>     };
> ```

move both computations of the stack traces into a `let expected_trace = match cairo_version` statement, so you won't define `call_location`, `entry_point_location` and `pc_location` variables in unnecessary contexts



_Suggestion:_
```XML
    let expected_trace = match cairo_version {
        CairoVersion::Cairo0 => {
    let call_location = entry_point_offset.0 + 12;
    let entry_point_location = entry_point_offset.0 - 61;
    format!(
        "Error in the called contract ({contract_address_felt}):
Error at pc=0:37:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:{call_location})
Unknown location (pc=0:{entry_point_location})

Error in the called contract ({contract_address_felt}):
Error at pc=0:{}:
{expected_error}
Cairo traceback (most recent call last):
Unknown location (pc=0:{call_location})
Unknown location (pc=0:{})
",
        expected_pc_locations.0, expected_pc_locations.1
    )
}
    CairoVersion::Cairo1 => {
    let pc_location = entry_point_offset.0 + INNER_CALL_CONTRACT_IN_CALL_CHAIN_OFFSET;
    format!(
        "Error in the called contract ({contract_address_felt}):
Error at pc=0:7981:
Got an exception while executing a hint: Hint Error: Execution failed. Failure reason: \
         {expected_error}.
Cairo traceback (most recent call last):
Unknown location (pc=0:{pc_location})

Error in the called contract ({contract_address_felt}):
Execution failed. Failure reason: {expected_error}.
"
    )
}
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 838 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1371#-NozyI5H7ETjXYnxYuzE:-NozyI5I7-8ww34Y6Jkn:b3oii0y) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e52543451cc6a3972b94e03aa174ca360c54940/crates/blockifier/src/execution/entry_point_test.rs#L838)):*
> ```XML
> {expected_error}
> Cairo traceback (most recent call last):
> Unknown location (pc=0:{})
> ```

use PC locations relative to `entry_point_offset` here?



_Code quote:_
```XML
        "Error in the called contract ({address_felt}):
Error at pc=0:37:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:1156)
Unknown location (pc=0:1083)

Error in the called contract ({address_felt}):
Error at pc=0:{}:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:1156)
Unknown location (pc=0:{})

Error in the called contract ({address_felt}):
Error at pc=0:{}:
{expected_error}
Cairo traceback (most recent call last):
Unknown location (pc=0:{})
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 866 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1371#-Nozy1Gl-ZpQeYmWZ1DF:-Nozy1Gl-ZpQeYmWZ1DG:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e52543451cc6a3972b94e03aa174ca360c54940/crates/blockifier/src/execution/entry_point_test.rs#L866)):*
> ```XML
>         CairoVersion::Cairo0 => expected_trace_cairo0,
>         CairoVersion::Cairo1 => expected_trace_cairo1,
>     };
> ```





_Suggestion:_
```XML
    let expected_trace = match cairo_version {
        CairoVersion::Cairo0 => format!(
        "Error in the called contract ({address_felt}):
Error at pc=0:37:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:1156)
Unknown location (pc=0:1083)

Error in the called contract ({address_felt}):
Error at pc=0:{}:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:1156)
Unknown location (pc=0:{})

Error in the called contract ({address_felt}):
Error at pc=0:{}:
{expected_error}
Cairo traceback (most recent call last):
Unknown location (pc=0:{})
",
        expected_pcs.0, expected_pcs.1, expected_pcs.2, expected_pcs.3
    ),
    CairoVersion::Cairo1 => format!(
        "Error in the called contract ({address_felt}):
Error at pc=0:7981:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:{pc_location})

Error in the called contract ({address_felt}):
Error at pc=0:{}:
Got an exception while executing a hint: Hint Error: Execution failed. Failure reason: \
         {expected_error}.
Cairo traceback (most recent call last):
Unknown location (pc=0:{pc_location})

Error in the called contract ({address_felt}):
Execution failed. Failure reason: {expected_error}.
",
        expected_pcs.0
    )
}
```

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1371)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 227 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1371#-NozwvDf0ryJc9O-IkOm:-Np-XiSr63LFm7dJSZAI:b20q141) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e52543451cc6a3972b94e03aa174ca360c54940/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L227)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so sneaky lol
</blockquote></details>

the compiler was smart, didn't let me divide by zero explicitly. but not that smart.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 758 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1371#-NozxQWDCJ5jjYkxjYnL:-Np-_7GA7PqyeO-pb6iL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e52543451cc6a3972b94e03aa174ca360c54940/crates/blockifier/src/execution/entry_point_test.rs#L758)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move both computations of the stack traces into a `let expected_trace = match cairo_version` statement, so you won't define `call_location`, `entry_point_location` and `pc_location` variables in unnecessary contexts
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 838 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1371#-NozyI5H7ETjXYnxYuzE:-Np-c3roBghn72Ald8Cs:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e52543451cc6a3972b94e03aa174ca360c54940/crates/blockifier/src/execution/entry_point_test.rs#L838)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use PC locations relative to `entry_point_offset` here?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 866 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1371#-Nozy1Gl-ZpQeYmWZ1DF:-Np-ZUbO0IVT4boIj0wk:b9jiy4d) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e52543451cc6a3972b94e03aa174ca360c54940/crates/blockifier/src/execution/entry_point_test.rs#L866)):*
> ```XML
>         CairoVersion::Cairo0 => expected_trace_cairo0,
>         CairoVersion::Cairo1 => expected_trace_cairo1,
>     };
> ```

Kinda looks like a mess, but Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1371#-:-Np-egoXDpVPaMJTJZ4C:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1371)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
