### PR TITLE
Add_test_get_execution_info_v2

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiVHtB_2HFqFyLvvsgT:-NiVHtBaCyXPcHuLC0hD:brpq0jl) ([raw file](https://github.com/starkware-libs/blockifier/blob/09276c922960ba44a92cbb76507ec55751eebb5f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L132)):*
> ```Cairo
>         assert(tx_info.account_contract_address.into() == account_address, 'ACCOUNT_MISMATCH');
>         assert(tx_info.max_fee == 0_u128, 'MAX_FEE_MISMATCH');
>         assert(tx_info.signature.len() == 0_u32, 'SIGNATURE_MISMATCH');
> ```

Is this also the case for the current test? We should pass non-trivial signatures.



_Code quote:_
```Cairo
assert(tx_info.signature.len() == 0_u32, 'SIGNATURE_MISMATCH');
```
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 138 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiVI1aOANRH14jInsVI:-NiVI1aOANRH14jInsVJ:b-ednff6) ([raw file](https://github.com/starkware-libs/blockifier/blob/09276c922960ba44a92cbb76507ec55751eebb5f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L138)):*
> ```Cairo
> 
>         let mut resource_bounds_array = resource_bounds.span();
>         let mut tx_info_resource_bounds: Span<ResourceBounds> = tx_info.resource_bounds;
> ```

Is this the most elegant way? :(
Why not build the structs from the flat input and compare?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiVHtB_2HFqFyLvvsgT:-NiVOwQ34mU3rccLlqMe:b-cbuys6) ([raw file](https://github.com/starkware-libs/blockifier/blob/09276c922960ba44a92cbb76507ec55751eebb5f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this also the case for the current test? We should pass non-trivial signatures.
</blockquote></details>

Yes, it is the same case.
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 138 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiVI1aOANRH14jInsVI:-NiVNnFU25ZvT6AU0ek0:b9f4bvw) ([raw file](https://github.com/starkware-libs/blockifier/blob/09276c922960ba44a92cbb76507ec55751eebb5f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L138)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the most elegant way? :(
Why not build the structs from the flat input and compare?
</blockquote></details>

I couldn't find a way to compare two arrays of structs.
@ilyalesokhin-starkware , is there an elegant way?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 145 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiZQj_b3Q_jsrvHjkys:-NiZQj_b3Q_jsrvHjkyt:b-dbikeb) ([raw file](https://github.com/starkware-libs/blockifier/blob/1feb5dab52b03fd2926a4d8d0d74a41e1b3e7650/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L145)):*
> ```Cairo
>                 assert(*tx_info_resource_bounds.pop_front().unwrap().resource == *current_word, 'RESOURCE_BOUNDS_MISMATCH');
>                 assert(*tx_info_resource_bounds.pop_front().unwrap().max_amount == (*resource_bounds_array.pop_front().unwrap()).try_into().unwrap(), 'RESOURCE_BOUNDS_MISMATCH');
>                 assert(*tx_info_resource_bounds.pop_front().unwrap().max_price_per_unit == (*resource_bounds_array.pop_front().unwrap()).try_into().unwrap(), 'RESOURCE_BOUNDS_MISMATCH');
> ```

How many elements do you expect tx_info_resource_bounds?



_Code quote:_
```Cairo
                assert(*tx_info_resource_bounds.pop_front().unwrap().resource == *current_word, 'RESOURCE_BOUNDS_MISMATCH');
                assert(*tx_info_resource_bounds.pop_front().unwrap().max_amount == (*resource_bounds_array.pop_front().unwrap()).try_into().unwrap(), 'RESOURCE_BOUNDS_MISMATCH');
                assert(*tx_info_resource_bounds.pop_front().unwrap().max_price_per_unit == (*resource_bounds_array.pop_front().unwrap()).try_into().unwrap(), 'RESOURCE_BOUNDS_MISMATCH');
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 138 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiVI1aOANRH14jInsVI:-NiZQvkx138Nku2DpaAX:bcn9fk0) ([raw file](https://github.com/starkware-libs/blockifier/blob/09276c922960ba44a92cbb76507ec55751eebb5f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L138)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I couldn't find a way to compare two arrays of structs.
@ilyalesokhin-starkware , is there an elegant way?
</blockquote></details>

it seems that resource_bounds_array is not an array of structs...

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 138 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiVI1aOANRH14jInsVI:-NiZR4-10vta7qtBcBy0:b-xjh8ne) ([raw file](https://github.com/starkware-libs/blockifier/blob/09276c922960ba44a92cbb76507ec55751eebb5f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L138)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it seems that resource_bounds_array is not an array of structs...
</blockquote></details>

In anycase, you might want to implement PartialEq<ResourceBounds>

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 117 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiZQccq-qam_jGSPshy:-NiZQccq-qam_jGSPshz:bbaew6t) ([raw file](https://github.com/starkware-libs/blockifier/blob/1feb5dab52b03fd2926a4d8d0d74a41e1b3e7650/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L117)):*
> ```Cairo
>         chain_id: felt252,
>         nonce: felt252,
>         resource_bounds: Array::<felt252>,
> ```

why not ?



_Suggestion:_
```Cairo
resource_bounds: Array::<ResourceBounds>
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @elintul, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 138 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiVI1aOANRH14jInsVI:-NiZwwCeDlrZcuDtNj-8:b-rco6wo) ([raw file](https://github.com/starkware-libs/blockifier/blob/09276c922960ba44a92cbb76507ec55751eebb5f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L138)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

In anycase, you might want to implement PartialEq<ResourceBounds>
</blockquote></details>

Where to implement PartialEq?
The `ResourceBounds` struct is part of [the Cairo repo](https://github.com/starkware-libs/cairo/blob/d37a8caaff02d68ae5e1e41946bf67f6025caa75/corelib/src/starknet/info.cairo#L124-L132).
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 117 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiZQccq-qam_jGSPshy:-NiZbxcOCL8bfMsGQQCB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1feb5dab52b03fd2926a4d8d0d74a41e1b3e7650/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L117)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not ?
</blockquote></details>

Done.
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 145 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiZQj_b3Q_jsrvHjkys:-NiZxGjAE2VPTmS7hP68:bku12xk) ([raw file](https://github.com/starkware-libs/blockifier/blob/1feb5dab52b03fd2926a4d8d0d74a41e1b3e7650/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L145)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

How many elements do you expect tx_info_resource_bounds?
</blockquote></details>

Two `ResourceBounds`.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 252 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NidARPxDVEMosMOpWHm:-NidARPxDVEMosMOpWHn:b32wzj) ([raw file](https://github.com/starkware-libs/blockifier/blob/feef70cd615f1ac4b170ebdf037aa1d026ad9b81/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L252)):*
> ```XML
>         stark_felt!(&*ChainId(CHAIN_ID_NAME.to_string()).as_hex()), // Chain ID.
>         nonce.0,                      // Nonce.
>         stark_felt!(0_u16),           // Length of Resource bound.
> ```

x2



_Suggestion:_
```XML
resource bounds array.
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NidA8e56Q2wetHVO3Oe:-NidA8e66bgFpvGBrJF1:boi5zip) ([raw file](https://github.com/starkware-libs/blockifier/blob/feef70cd615f1ac4b170ebdf037aa1d026ad9b81/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
> ```XML
>         ..trivial_external_entry_point()
>     };
> ```

What causes the gas changes?

**Review by elintul — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiVHtB_2HFqFyLvvsgT:-NidFX3q-ywjnqMv3zlL:b-y7s7tf) ([raw file](https://github.com/starkware-libs/blockifier/blob/09276c922960ba44a92cbb76507ec55751eebb5f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's add a non-empty signature for both tests (old ones, not now; I'll add to Monday).
</blockquote></details>

As I merge both deprecated and V3 entry points, I prefer doing it in a separate PR.
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 138 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NiVI1aOANRH14jInsVI:-NidFg_06d4foRsYUwKR:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/09276c922960ba44a92cbb76507ec55751eebb5f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L138)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

add 
`impl ResourceBounds of PartialEq<ResourceBounds> `
inside this file/contract.
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NidA8e56Q2wetHVO3Oe:-NidFiVN23d97IR7Dy6L:b-2wjeoa) ([raw file](https://github.com/starkware-libs/blockifier/blob/feef70cd615f1ac4b170ebdf037aa1d026ad9b81/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What causes the gas changes?
</blockquote></details>

@ilyalesokhin-starkware do you have any idea why the gas consumption changes when compiling with different compiler versions?
Note that I didn't modify `secp256` code.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NidA8e56Q2wetHVO3Oe:-NidtTKZ2w4gpvZyi372:b-3njdvq) ([raw file](https://github.com/starkware-libs/blockifier/blob/feef70cd615f1ac4b170ebdf037aa1d026ad9b81/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

@ilyalesokhin-starkware do you have any idea why the gas consumption changes when compiling with different compiler versions?
Note that I didn't modify `secp256` code.
</blockquote></details>

Let's continue on Slack to merge this faster.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NidA8e56Q2wetHVO3Oe:-Nie1J2k5jQZcRLCCyQd:b-40gnfc) ([raw file](https://github.com/starkware-libs/blockifier/blob/feef70cd615f1ac4b170ebdf037aa1d026ad9b81/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's continue on Slack to merge this faster.
</blockquote></details>

Didn't we agree on updating the compiler in a separate PR?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 107 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nie3N6F3--bqmREQHhF:-Nie3N6F3--bqmREQHhG:b5xx8c2) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9fffb700fda98e4c5a21f9a57a77ca3c2173a05/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L107)):*
> ```Cairo
>             assert(tx_info.max_fee.into() == max_fee, 'MAX_FEE_MISMATCH');
>             assert(tx_info.resource_bounds.len() == 0_u32, 'RESOURCE_BOUND_MISMATCH');
>         }
> ```

is this 'if' needed? can't you pass the expect values in the test?



_Code quote:_
```Cairo
        if version == 3_u32.into() || version == POW_2_128 + 3_u32.into() {
            // Verify that for V3 transactions, `max_fee` is set to 0, and the resource bounds match the expected resource bounds.
            assert(tx_info.max_fee.into() == 0_u128, 'MAX_FEE_MISMATCH');
            assert (tx_info.resource_bounds == resource_bounds, 'RESOURCE_BOUND_MISMATCH')
        }
        else {
            assert(tx_info.max_fee.into() == max_fee, 'MAX_FEE_MISMATCH');
            assert(tx_info.resource_bounds.len() == 0_u32, 'RESOURCE_BOUND_MISMATCH');
        }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 107 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nie3N6F3--bqmREQHhF:-Nie6usw-LZ1x7-XecjT:bxs6ot1) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9fffb700fda98e4c5a21f9a57a77ca3c2173a05/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is this 'if' needed? can't you pass the expect values in the test?
</blockquote></details>

We still want to verify that for non-deprecated transactions, it's not possible to send `max_fee` with a value different from 0. And for deprecated transactions not possible to send `resource_bound`.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NidA8e56Q2wetHVO3Oe:-Nie597kDu-9h78eB1sf:b-mu334g) ([raw file](https://github.com/starkware-libs/blockifier/blob/feef70cd615f1ac4b170ebdf037aa1d026ad9b81/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Didn't we agree on updating the compiler in a separate PR?
</blockquote></details>

Yesterday I updated the compiler version to `2.3.0`[here](https://github.com/starkware-libs/blockifier/pull/1081) (without updating the `get_execution_info_syscall`). Also there we saw different gas consumption.
Today we got a new compiler release `2.4.0-rc0`. Do you think it's necessary to separate this compiler as well?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NidA8e56Q2wetHVO3Oe:-NieBhyP1h1ZU91h6r_i:bnklzjz) ([raw file](https://github.com/starkware-libs/blockifier/blob/feef70cd615f1ac4b170ebdf037aa1d026ad9b81/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Yesterday I updated the compiler version to `2.3.0`[here](https://github.com/starkware-libs/blockifier/pull/1081) (without updating the `get_execution_info_syscall`). Also there we saw different gas consumption.
Today we got a new compiler release `2.4.0-rc0`. Do you think it's necessary to separate this compiler as well?
</blockquote></details>

Yes, don't mix compiler changes with unrelated changes.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 107 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nie3N6F3--bqmREQHhF:-NieBwhUAFJ6QcJkB7Zk:bxubi86) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9fffb700fda98e4c5a21f9a57a77ca3c2173a05/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L107)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

We still want to verify that for non-deprecated transactions, it's not possible to send `max_fee` with a value different from 0. And for deprecated transactions not possible to send `resource_bound`.
</blockquote></details>

why can't the caller pass  max_fee = 0 when it passed version != 3?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 107 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nie3N6F3--bqmREQHhF:-NieNB6F58IK5c6l9yUm:b-sxrcsb) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9fffb700fda98e4c5a21f9a57a77ca3c2173a05/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why can't the caller pass  max_fee = 0 when it passed version != 3?
</blockquote></details>

He can.
But he cannot send `max_fee != 0` with `version == 3`, and that's what the if condition checks.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NidA8e56Q2wetHVO3Oe:-NieOOV43uN7_wk2u8_E:bce9qm2) ([raw file](https://github.com/starkware-libs/blockifier/blob/feef70cd615f1ac4b170ebdf037aa1d026ad9b81/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Yes, don't mix compiler changes with unrelated changes.
</blockquote></details>

Ok, I'll open a new PR for that.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 107 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nie3N6F3--bqmREQHhF:-NiePTSg48Hu5Bw6F5LK:b5knwvj) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9fffb700fda98e4c5a21f9a57a77ca3c2173a05/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L107)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

He can.
But he cannot send `max_fee != 0` with `version == 3`, and that's what the if condition checks.
</blockquote></details>

What is the problem with sending the expected_max_fee for v3?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @noaov1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 107 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nie3N6F3--bqmREQHhF:-Nihupwq-1Tarw_pX1ev:b-i41omx) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9fffb700fda98e4c5a21f9a57a77ca3c2173a05/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What is the problem with sending the expected_max_fee for v3?
</blockquote></details>

It is an extra check that can catch bugs in `TxInfo`.
@elintul, WDYT?

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 107 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nie3N6F3--bqmREQHhF:-NiibooTDIaOQ4Z7IreI:bzfgykr) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9fffb700fda98e4c5a21f9a57a77ca3c2173a05/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L107)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It is an extra check that can catch bugs in `TxInfo`.
@elintul, WDYT?
</blockquote></details>

We can leave it, although it can be embedded in the expected input.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 107 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nie3N6F3--bqmREQHhF:-NiifqiUDzxkVXuJdgSz:bw63cz5) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9fffb700fda98e4c5a21f9a57a77ca3c2173a05/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L107)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We can leave it, although it can be embedded in the expected input.
</blockquote></details>

Passing the correct expected values feels more natural to me.

**Review by elintul — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 107 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nie3N6F3--bqmREQHhF:-NiinmCTAzGujxBLxbTB:b-p7o2mz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9fffb700fda98e4c5a21f9a57a77ca3c2173a05/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Passing the correct expected values feels more natural to me.
</blockquote></details>

I'm okay with either.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 107 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nie3N6F3--bqmREQHhF:-NiiunRs2dxjxywYonLd:bss4a2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9fffb700fda98e4c5a21f9a57a77ca3c2173a05/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L107)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm okay with either.
</blockquote></details>

Removed.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-:-Nijc3n08pXgU0v1ATLh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1108 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nin5FZ40TkBX8-pJv6F:-Nin5FZ40TkBX8-pJv6G:b37v4s6) ([raw file](https://github.com/starkware-libs/blockifier/blob/3457f8c9c8e9cedee00020d3366ac118a193fe8a/crates/blockifier/src/transaction/transactions_test.rs#L1108)):*
> ```XML
>     );
>     let block_context = &BlockContext::create_for_account_testing();
>     let mut version = Felt252::from(1_u8);
> ```

Are you going to add v3?



_Code quote:_
```XML
 let mut version = Felt252::from(1_u8);
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r6, 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-:-Nin5JzV7QeFLqMajTTS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1108 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-Nin5FZ40TkBX8-pJv6F:-Nin68cGB9qI5NYOr4Kk:b-95hsjz) ([raw file](https://github.com/starkware-libs/blockifier/blob/3457f8c9c8e9cedee00020d3366ac118a193fe8a/crates/blockifier/src/transaction/transactions_test.rs#L1108)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Are you going to add v3?
</blockquote></details>

I have tested V3 transaction in `syscall_test` in [this](https://reviewable.io/reviews/starkware-libs/blockifier/987) PR.
I'm planning to run a new dedicated test that checks this syscall.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1097 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1080#-NinFWD77syBSArxAyna:-NinFWD77syBSArxAynb:b-qlwfkc) ([raw file](https://github.com/starkware-libs/blockifier/blob/3457f8c9c8e9cedee00020d3366ac118a193fe8a/crates/blockifier/src/transaction/transactions_test.rs#L1097)):*
> ```XML
> #[case(true)]
> #[case(false)]
> fn test_only_query_flag(#[case] only_query: bool) {
> ```

Can you document this test and how it differs from  `test_get_execution_info`?



_Code quote:_
```XML
fn test_only_query_flag(#[case] only_query: bool) {
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1080)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @MohammadNassar1, and @noaov1)

**Pull request merged**
