### PR TITLE
Add secp256k1_get_point_from_x.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/701)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/701)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/701#-NZLufAT8uwzQkQuUHQ7:-NZLufAT8uwzQkQuUHQ8:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/42025643a3dafb54ce168fbf9df367af3e1c6d3d/crates/blockifier/src/execution/syscalls/secp.rs#L134)):*
> ```XML
>         });
>     }
>     let maybe_ec_point = secp256k1::Affine::get_ys_from_x_unchecked(x)
> ```

Add a blank line above.



_Code quote:_
```XML
let maybe_ec_point = secp256k1::Affine::get_ys_from_x_unchecked(x)
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/701#-NZLv1MX1oOIr8d8m80A:-NZLv1MX1oOIr8d8m80B:bx9awqe) ([raw file](https://github.com/starkware-libs/blockifier/blob/42025643a3dafb54ce168fbf9df367af3e1c6d3d/crates/blockifier/src/execution/syscalls/secp.rs#L135)):*
> ```XML
>     }
>     let maybe_ec_point = secp256k1::Affine::get_ys_from_x_unchecked(x)
>         .map(|(smaller, greater)| match (smaller.0.is_even(), request.y_parity) {
> ```

I'm having a hard time understanding this code. Can you add a short comment?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/701#-NZLv1MX1oOIr8d8m80A:-NZLwJM8A9ATmREVKdSr:bdxa7c) ([raw file](https://github.com/starkware-libs/blockifier/blob/42025643a3dafb54ce168fbf9df367af3e1c6d3d/crates/blockifier/src/execution/syscalls/secp.rs#L135)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm having a hard time understanding this code. Can you add a short comment?
</blockquote></details>

I rewrote the code.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/701)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/701#-NZLufAT8uwzQkQuUHQ7:-NZLwIrkCCylAPGZakh3:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/42025643a3dafb54ce168fbf9df367af3e1c6d3d/crates/blockifier/src/execution/syscalls/secp.rs#L134)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a blank line above.
</blockquote></details>

done

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/701#-:-NZLzN0ZD6dP4AwJ0OXi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
