### PR TITLE
test(execution): get_block_number and get_block_timestamp in test_validate_accounts_tx for Cairo0

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1512)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 114 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcDtpQ9pTmbSuRT_Bb:-NqcDtpQ9pTmbSuRT_Bc:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/062cc10d34eaf42a8ea478d84dea6816c4b20d53/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L114)):*
> ```Cairo
>         let block_number = get_block_number();
>         return ();
>     }
> ```





_Suggestion:_
```Cairo
    if (scenario == GET_BLOCK_NUMBER) {
        let expected_block_number = tx_info.signature[1];
        let block_number = get_block_number();
        assert block_number = expected_block_number;
        return ();
    }
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1512)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @MohammadNassar1, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 114 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcDtpQ9pTmbSuRT_Bb:-NqcFv6V8wcTPYc9JMHK:bnybk7z) ([raw file](https://github.com/starkware-libs/blockifier/blob/062cc10d34eaf42a8ea478d84dea6816c4b20d53/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L114)):*
> ```Cairo
>         let block_number = get_block_number();
>         return ();
>     }
> ```

same for get_block_timestamp.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1507 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcEdO18JL4ulRXZgWI:-NqcEdO18JL4ulRXZgWJ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/062cc10d34eaf42a8ea478d84dea6816c4b20d53/crates/blockifier/src/transaction/transactions_test.rs#L1507)):*
> ```XML
>                 ..default_args
>             },
>         );
> ```





_Suggestion:_
```XML
    if let CairoVersion::Cairo0 = cairo_version {
        // Calling the syscall get_block_number and asserting the returned blocknumber was modified for validate.
        let account_tx = create_account_tx_for_validate_test(
            nonce_manager,
            FaultyAccountTxCreatorArgs {
                scenario: GET_BLOCK_NUMBER,
                contract_address_salt: salt_manager.next_salt(),
                additional_data: Some(vec![StarkFelt::from(CURRENT_BLOCK_NUMBER_FOR_VALIDATE)]),
                ..default_args
            },
        );
        assert!(account_tx.execute(state, block_context, true, true).err().is_none());
        // Calling the syscall get_block_timestamp and asserting the returned timestamp was modified for validate.
        let account_tx = create_account_tx_for_validate_test(
            nonce_manager,
            FaultyAccountTxCreatorArgs {
                scenario: GET_BLOCK_TIMESTAMP,
                contract_address_salt: salt_manager.next_salt(),
                additional_data: Some(vec![StarkFelt::from(CURRENT_BLOCK_TIMESTAMP_FOR_VALIDATE)]),
                ..default_args
            },
        );
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1514 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcFNBr0h-o9kiEBa0C:-NqcFNBr0h-o9kiEBa0D:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/062cc10d34eaf42a8ea478d84dea6816c4b20d53/crates/blockifier/src/transaction/transactions_test.rs#L1514)):*
> ```XML
>         let account_tx = create_account_tx_for_validate_test(
>             // Calling the syscall get_execution_info and get block_info which was modified for
>             // validate.
> ```





_Suggestion:_
```XML
            // Calling the syscall get_execution_info and asserting the returned block_info was modified for
            // validate.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1527 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcFo-R2U7uju_KsLWf:-NqcFo-R2U7uju_KsLWg:b-kqqxac) ([raw file](https://github.com/starkware-libs/blockifier/blob/062cc10d34eaf42a8ea478d84dea6816c4b20d53/crates/blockifier/src/transaction/transactions_test.rs#L1527)):*
> ```XML
>             },
>         );
>         assert!(account_tx.execute(state, block_context, true, true).err().is_none());
> ```

Nice! (readable).



_Code quote:_
```XML
assert!(account_tx.execute(state, block_context, true, true).err().is_none());
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1507 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcEdO18JL4ulRXZgWI:-NqcHd668iOaLU26WY8z:b8m2rop) ([raw file](https://github.com/starkware-libs/blockifier/blob/062cc10d34eaf42a8ea478d84dea6816c4b20d53/crates/blockifier/src/transaction/transactions_test.rs#L1507)):*
> ```XML
>                 ..default_args
>             },
>         );
> ```

Please use grammerly to check the comments.
Also - in the comments write:  `the returned blocknumber` -> `the returned block number`.
(`timestamp` as one word is correct).

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1514 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcFNBr0h-o9kiEBa0C:-NqcIEMz6PGXVW36iZZp:bwvqmna) ([raw file](https://github.com/starkware-libs/blockifier/blob/062cc10d34eaf42a8ea478d84dea6816c4b20d53/crates/blockifier/src/transaction/transactions_test.rs#L1514)):*
> ```XML
>         let account_tx = create_account_tx_for_validate_test(
>             // Calling the syscall get_execution_info and get block_info which was modified for
>             // validate.
> ```

This is from a different PR; should I modify it here?

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1512)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @MohammadNassar1, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 114 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcDtpQ9pTmbSuRT_Bb:-NqcLhNg1zoEX6Cuz7_B:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/062cc10d34eaf42a8ea478d84dea6816c4b20d53/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L114)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

same for get_block_timestamp.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1507 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcEdO18JL4ulRXZgWI:-NqcMoQ3Bb6KKc5QP1o2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/062cc10d34eaf42a8ea478d84dea6816c4b20d53/crates/blockifier/src/transaction/transactions_test.rs#L1507)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please use grammerly to check the comments.
Also - in the comments write:  `the returned blocknumber` -> `the returned block number`.
(`timestamp` as one word is correct).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1514 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcFNBr0h-o9kiEBa0C:-NqcMmgvCWSlj659OzuQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/062cc10d34eaf42a8ea478d84dea6816c4b20d53/crates/blockifier/src/transaction/transactions_test.rs#L1514)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Whichever is easier/ cleaner in your opinion.
</blockquote></details>

Done.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1512)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @MohammadNassar1, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 120 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcNYRuEkT4rDe4VjSx:-NqcNYRuEkT4rDe4VjSy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/24281387d28b680fce38610c0778f73d8fec86ab/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L120)):*
> ```Cairo
>         let expected_block_timestamp = tx_info.signature[1];
>         let block_timestamp = get_block_timestamp();
>         return ();
> ```





_Suggestion:_
```Cairo
    if (scenario == GET_BLOCK_TIMESTAMP) {
        let expected_block_timestamp = tx_info.signature[1];
        let block_timestamp = get_block_timestamp();
        assert block_timestamp = expected_block_timestamp;
        return ();
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-:-NqcXlUV6Jgc2syFV__T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware, @MohammadNassar1, @noaov1, and @TzahiTaub)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1474 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcdHO86QcxQDB8tB7p:-NqcdHO86QcxQDB8tB7q:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/65a0d22aea1030789a1953f5e116b12c816bea4d/crates/blockifier/src/transaction/transactions_test.rs#L1474)):*
> ```XML
> 
>     if tx_type != TransactionType::DeployAccount {
>         // Calling self (allowed).
> ```





_Suggestion:_
```XML
        // Call self (allowed).
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1403 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1512#-NqcdCJQD8v19Wx0l7s1:-NqcdCJQD8v19Wx0l7s2:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/65a0d22aea1030789a1953f5e116b12c816bea4d/crates/blockifier/src/transaction/transactions_test.rs#L1403)):*
> ```XML
>     );
> 
>     // Trying to call another contract (forbidden).
> ```





_Suggestion:_
```XML
    // Try to call another contract (forbidden).
```

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1512)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware, @MohammadNassar1, @noaov1, and @TzahiTaub)

**Pull request merged**
