### PR TITLE
refactor(concurrency): use ` ThreadSafeVersionedState ` in tests and define appropriate methods

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1857)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1857)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1857#-Nx6I018DB0Qrp1LENqf:-Nx6I018DB0Qrp1LENqg:b-l07d1t) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8656a7ea4c41713575ac072edfa2e0d049c59ca/crates/blockifier/src/concurrency/test_utils.rs#L32)):*
> ```XML
> }
> 
> // TODO(meshi, 01/06/2024): Consider making this a macro.
> ```

Do we need this function now that we have a new for ThreadSafeVersionedState? 
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1857#-Nx6P45n4GfHlyazbmTT:-Nx6P45n4GfHlyazbmTU:b-2r8brh) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8656a7ea4c41713575ac072edfa2e0d049c59ca/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L155)):*
> ```XML
>         VersionedStateProxy { tx_index, state: self.0.clone() }
>     }
> ```

When we leave this scope, should the state no longer be locked? In the previous flow, we entered validate_read_set with a locked state. 
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1857#-Nx6Ihpe07jBIJTiG7Fu:-Nx6Ihpe07jBIJTiG7Fv:b-ckluq) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8656a7ea4c41713575ac072edfa2e0d049c59ca/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L44)):*
> ```XML
>     contract_address_for_testing: ContractAddress,
>     class_hash_for_testing: ClassHash,
> ) -> ThreadSafeVersionedState<DictStateReader> {
> ```

Using ..DictStateReader::default() would be better than listing all the files. see  https://github.com/starkware-libs/blockifier/blob/4aedc114b19ed5aff044cc405f8a5bb0077a83d7/crates/blockifier/src/blockifier/transaction_executor_test.rs#L252

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1857)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1857#-Nx6I018DB0Qrp1LENqf:-Nx6ZtBm0cXBo2USv_sO:brhktr3) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8656a7ea4c41713575ac072edfa2e0d049c59ca/crates/blockifier/src/concurrency/test_utils.rs#L32)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Do we need this function now that we have a new for ThreadSafeVersionedState?
</blockquote></details>

I think it can help (with it, we avoid the two `new` calls)
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1857#-Nx6P45n4GfHlyazbmTT:-Nx6_HvYA6oIMPBZ3GsU:bnlqghg) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8656a7ea4c41713575ac072edfa2e0d049c59ca/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L155)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

When we leave this scope, should the state no longer be locked? In the previous flow, we entered validate_read_set with a locked state.
</blockquote></details>

Not this scope. The guard will be dropped when it goes out of scope at the caller method.
And you are right, here we have a semi- optimization: we can lock the state only when we need it.

**Review by meship-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1857#-:-Nx7_OA3C11SCle26E46:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by meship-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1857#-:-Nx7lBBaCMWIVxNwdnh_:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1857)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
