### PR TITLE
Update SN API version.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/732)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
python side?

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/732#-:-N_3niEqEkUgBPdmt5hQ:b60jgnd)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`Cargo.toml` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/732#-N_3lQte0FZzgVgjvj-Z:-N_3lQte0FZzgVgjvj-_:bh98ahn) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9006a1ffe3ce3ed9daa91cea7f698ca1360a24c/Cargo.toml#L35)):*
> ```TOML
> ouroboros = "0.15.6"
> rstest = "0.17.0"
> papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", rev = "90ad4bc" }
> ```

Any news about when this is released as a formal version?



_Code quote:_
```TOML
papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", rev = "90ad4bc" }
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/732#-N_3nIKRBYoJisqkJslo:-N_3nIKRBYoJisqkJslp:brm8is6) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9006a1ffe3ce3ed9daa91cea7f698ca1360a24c/crates/blockifier/src/transaction/transactions.rs#L214)):*
> ```XML
>             InvokeTransaction::V1(_) => selector_from_name(constants::EXECUTE_ENTRY_POINT_NAME),
>         };
>         let storage_address = context.account_tx_context.sender_address;
> ```

The API changed? `sender_address()` seemed convenient



_Code quote:_
```XML
        let storage_address = context.account_tx_context.sender_addres
```

**Review by alonh5 — COMMENTED** [review]
I'll open a PR before merging this one.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/732#-:-N_3pGGKC3GQV8GrP6UP:b-2xb3wc)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`Cargo.toml` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/732#-N_3lQte0FZzgVgjvj-Z:-N_3pK-3C3ihEBBnJvDE:bcgyeye) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9006a1ffe3ce3ed9daa91cea7f698ca1360a24c/Cargo.toml#L35)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Any news about when this is released as a formal version?
</blockquote></details>

Supposed to be this week. Elin didn't want to wait for that; I'll do it in a separate PR.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/732#-N_3nIKRBYoJisqkJslo:-N_3pdSkDo-ZQDoF1MZz:b-xwqkyr) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9006a1ffe3ce3ed9daa91cea7f698ca1360a24c/crates/blockifier/src/transaction/transactions.rs#L214)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The API changed? `sender_address()` seemed convenient
</blockquote></details>

Yes, invoke v0 no longer has a `sender_address` field, but a `contract_address` field as it should (and as it is in the specs).

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/732)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/732#-N_3nIKRBYoJisqkJslo:-N_3uVnX0jez5An0EBBs:begcngo) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9006a1ffe3ce3ed9daa91cea7f698ca1360a24c/crates/blockifier/src/transaction/transactions.rs#L214)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yes, invoke v0 no longer has a `sender_address` field, but a `contract_address` field as it should (and as it is in the specs).
</blockquote></details>

Got it, tnx.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/732)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/732#-N_4WFGL5SPgTPt-3Ey2:-N_4WFGM1bQv3-CTCLVj:bkbkf7l) (no related file):*
No need for this on `main-v0.12.0` in the end (i.e., VM upgrade does not require SN API upgrade)?

___

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/732#-:-N_4k-1N-wwnX9v_1Tz0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/732#-N_4WFGL5SPgTPt-3Ey2:-N_4jqKHBcdG3Sp3jeuT:b-rzfvr8) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I don't believe it does. The VM and SN API don't depend on each other.
</blockquote></details>

If you discover they do, please initiate a merge from `main-v0.12.0` to `main` after upgrading SN API on `main-v0.12.0`, so that we minimize conflicts.

___

**Review by elintul — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/732)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/732)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
