### PR TITLE
refactor(concurrency): add execution flags struct

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2024)

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2024#-O0n_ItMB80iDVXMEyIB:-O0n_ItMB80iDVXMEyIC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/44340e385e0f256c9d051feb42bb169516042171/crates/blockifier/src/blockifier/transaction_executor.rs#L92)):*
> ```XML
>         );
>         // Executing a single transaction cannot be done in a concurrent mode.
>         let excution_flags =
> ```





_Suggestion:_
```XML
let execution_flags =
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2024)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2024#-O0n_ItMB80iDVXMEyIB:-O0naApW4bP43jU5uv5x:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/44340e385e0f256c9d051feb42bb169516042171/crates/blockifier/src/blockifier/transaction_executor.rs#L92)):*
> ```XML
>         );
>         // Executing a single transaction cannot be done in a concurrent mode.
>         let excution_flags =
> ```

Done.

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2024)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2024#-O0na3tW7qII5MguAMwz:-O0na3tXBMtb_ww64EFz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/44340e385e0f256c9d051feb42bb169516042171/crates/blockifier/src/transaction/transaction_execution.rs#L164)):*
> ```XML
>         // types, since now running Transaction::execute_raw is not identical to
>         // AccountTransaction::execute_raw.
>         let concurrency_mode = execution_flags.concurrency_mode;
> ```

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2024#-:-O0nb6F76zU2HlbfxVzD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2024)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2024#-O0na3tW7qII5MguAMwz:-O0nb5qV1RRt61mKxjfg:b-9yrj3a) ([raw file](https://github.com/starkware-libs/blockifier/blob/44340e385e0f256c9d051feb42bb169516042171/crates/blockifier/src/transaction/transaction_execution.rs#L164)):*
> ```XML
>         // types, since now running Transaction::execute_raw is not identical to
>         // AccountTransaction::execute_raw.
>         let concurrency_mode = execution_flags.concurrency_mode;
> ```

Used in line 180

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2024)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2024#-O0na3tW7qII5MguAMwz:-O0uNclT10NAA3q8heLE:b4nmkfy) ([raw file](https://github.com/starkware-libs/blockifier/blob/44340e385e0f256c9d051feb42bb169516042171/crates/blockifier/src/transaction/transaction_execution.rs#L164)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Used in line 180
</blockquote></details>

I agree. I don't think it's needed. You can use `execution_flags.concurrency_mode` in line 180
___
*[`crates/blockifier/src/transaction/transactions.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2024#-O0uNoJACGy1naGlbDqW:-O0uNoJB6KlTEYdsQO0-:b-ebwr3q) ([raw file](https://github.com/starkware-libs/blockifier/blob/14befc87abeb4ab467f83432ebc101e9c8f9c3f2/crates/blockifier/src/transaction/transactions.rs#L44)):*
> ```XML
> }
> 
> #[derive(Clone)]
> ```

And remove the `.clone()` in the tests



_Suggestion:_
```XML
#[derive(Clone, Copy, Debug)]
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2024)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2024#-O0na3tW7qII5MguAMwz:-O0wIZ175PObDK47hnP9:bwr9dif) ([raw file](https://github.com/starkware-libs/blockifier/blob/44340e385e0f256c9d051feb42bb169516042171/crates/blockifier/src/transaction/transaction_execution.rs#L164)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I agree. I don't think it's needed. You can use `execution_flags.concurrency_mode` in line 180
</blockquote></details>

I can not, as it will cause a "use of moved value: execution_flags" compilation error.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2024#-:-O0wXglI6q6Vm7TCXHE0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
