### PR TITLE
Added a test for the scenario when a non deployed user invokes a transaction

### PR DESCRIPTION
**Pull request by nimrod-starkware**
tests the same scenario as test_internal_invoke_tx_failure in the Python tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/971)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/971)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/971#-NfymFU71-IKwzYOWDv5:-NfymFU71-IKwzYOWDv6:bwqc57h) ([raw file](https://github.com/starkware-libs/blockifier/blob/e94ee1ac341d9a00f3fe0414149054187be66c7b/crates/blockifier/src/transaction/account_transactions_test.rs#L235)):*
> ```XML
> #[case(TransactionVersion::ZERO)]
> #[case(TransactionVersion::ONE)]
> ```

remove newline between the `#[case]` and the TODO
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/971#-NfymZ8a4qAI5lfJdpa8:-NfymZ8a4qAI5lfJdpa9:b-ls8h0q) ([raw file](https://github.com/starkware-libs/blockifier/blob/e94ee1ac341d9a00f3fe0414149054187be66c7b/crates/blockifier/src/transaction/account_transactions_test.rs#L271)):*
> ```XML
>     );
>     match tx_result {
>         Ok(info) => assert!(info.revert_error.is_some()),
> ```

as with the `Err` case, need to explicitly check for the expected error.
The error is a string in this case, so just assert that some indicative string is a substring of the error (maybe "is not deployed"? not sure if it's the same text).
If it's the same text you're searching for, please put it in a variable



_Code quote:_
```XML
revert_error.is_some()
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/971#-NfynpoiEYSX4PkQclpv:-NfynpoiEYSX4PkQclpw:b-8dcn8) ([raw file](https://github.com/starkware-libs/blockifier/blob/e94ee1ac341d9a00f3fe0414149054187be66c7b/crates/blockifier/src/transaction/account_transactions_test.rs#L274)):*
> ```XML
>         Err(err) => {
>             assert!(matches!(err, TransactionExecutionError::ExecutionError(e) if
>             matches!(&e, EntryPointExecutionError::VirtualMachineExecutionErrorWithTrace { trace, .. } if trace.contains("is not deployed.")))); // make sure the error is because the account wasn't deployed
> ```

I think this is better, if possible; full destructuring instead of two `if`s



_Suggestion:_
```XML
            assert!(matches!(err, TransactionExecutionError::ExecutionError(
                EntryPointExecutionError::VirtualMachineExecutionErrorWithTrace { trace, .. }
                if trace.contains("is not deployed.")
            )));
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/971#-Nfyn2T06oGE7vsTLPAZ:-Nfyn2T06oGE7vsTLPA_:b-jy9i5h) ([raw file](https://github.com/starkware-libs/blockifier/blob/e94ee1ac341d9a00f3fe0414149054187be66c7b/crates/blockifier/src/transaction/account_transactions_test.rs#L275)):*
> ```XML
>             assert!(matches!(err, TransactionExecutionError::ExecutionError(e) if
>             matches!(&e, EntryPointExecutionError::VirtualMachineExecutionErrorWithTrace { trace, .. } if trace.contains("is not deployed.")))); // make sure the error is because the account wasn't deployed
>             assert!(matches!(tx_version, TransactionVersion::ZERO)); // we excpect to get an error only when tx_version is 0, on other versions to revert
> ```

@nimrod-starkware we start comments with capital letters and end with periods.
Also, they should be on the line above the line of code.
@giladchase shouldn't the formatter have failed this PR? Maybe your recent change did something...? These lines are over 100 chars long



_Suggestion:_
```XML
            // Make sure the error is because the account wasn't deployed.
            matches!(&e, EntryPointExecutionError::VirtualMachineExecutionErrorWithTrace { trace, .. } if trace.contains("is not deployed."))));
            // We excpect to get an error only when tx_version is 0, on other versions to revert.
            assert!(matches!(tx_version, TransactionVersion::ZERO));
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/971)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/971#-Nfyn2T06oGE7vsTLPAZ:-Nfz4aGH1PH24OLltnPq:b-sfkuvl) ([raw file](https://github.com/starkware-libs/blockifier/blob/e94ee1ac341d9a00f3fe0414149054187be66c7b/crates/blockifier/src/transaction/account_transactions_test.rs#L275)):*
>[@giladchase](https://github.com/giladchase) shouldn't the formatter have failed this PR? Maybe your recent change did something...? These lines are over 100 chars long

rustfmt doesn't work for items that include macros: https://github.com/rust-lang/rustfmt/issues/8
What recent change?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/971)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/971#-Nfyn2T06oGE7vsTLPAZ:-NfzB9La2KNCsFjeZc1N:b-6qbct5) ([raw file](https://github.com/starkware-libs/blockifier/blob/e94ee1ac341d9a00f3fe0414149054187be66c7b/crates/blockifier/src/transaction/account_transactions_test.rs#L275)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>[@giladchase](https://github.com/giladchase) shouldn't the formatter have failed this PR? Maybe your recent change did something...? These lines are over 100 chars long

rustfmt doesn't work for items that include macros: https://github.com/rust-lang/rustfmt/issues/8
What recent change?
</blockquote></details>

ah... nevermind then... damn
@nimrod-starkware please ensure no line is over 100 chars
(recent change was in SN-API repo.. my bad)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/971)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 276 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/971#-NfzJ93J1g2ayKhgkVDq:-NfzJ93J1g2ayKhgkVDr:bsd6s7g) ([raw file](https://github.com/starkware-libs/blockifier/blob/93261a4c0a75d8acbb2b0c95f4207c2bb38be3b7/crates/blockifier/src/transaction/account_transactions_test.rs#L276)):*
> ```XML
>         Ok(info) => {
>             //  Make sure the error is because the account wasn't deployed.
>             assert!(info.revert_error.is_some_and(|err_str| err_str.contains("is not deployed.")));
> ```

please add `let expected_error = "is not deployed"` before the match, and use it twice



_Code quote:_
```XML
"is not deployed."
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/971#-NfzJJ24BYc-i9lExFC7:-NfzJJ24BYc-i9lExFC8:bb7phvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/93261a4c0a75d8acbb2b0c95f4207c2bb38be3b7/crates/blockifier/src/transaction/account_transactions_test.rs#L284)):*
> ```XML
>                 if trace.contains("is not deployed.")
>             ));
>             // We excpect to get an error only when tx_version is 0, on other versions to revert.
> ```

typo



_Code quote:_
```XML
 excpect
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/971)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/971#-:-NfzKtNpBz8goKQ7yHPo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
