### PR TITLE
Only add undeclared classes to declared_classes

### PR DESCRIPTION
**Pull request by giladchase**
As is done with `deprecated_declared_classes`.

This has quite a bit of duplication with the `deprecated_declared_classes` logic just above it (crates/native_blockifier/src/storage.rs:125), any way of removing the duplication?

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/559)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
We can ask Papyrus to implement an `is_class_declared(class_hash: ClassHash, state_number: StateNumber) -> bool` method.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/559#-:-NX5ArL-5Si5VkhFJpIA:bhzl376)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/storage.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/559#-NX5AluF9So18tu1YUmD:-NX5AluF9So18tu1YUmE:b-3i2nya) ([raw file](https://github.com/starkware-libs/blockifier/blob/8cadb498fba6742003841a092c4b6993b9dfd5c3/crates/native_blockifier/src/storage.rs#L146)):*
> ```XML
>         for (class_hash, (compiled_class_hash, raw_class)) in declared_class_hash_to_class {
>             let py_contract_class: PyContractClass = serde_json::from_str(&raw_class)?;
>             let contract_class = ContractClass::from(py_contract_class);
> ```

We can instantiate with `::default()` since it's unused.



_Code quote:_
```XML
            let py_contract_class: PyContractClass = serde_json::from_str(&raw_class)?;
            let contract_class = ContractClass::from(py_contract_class);
```

**Comment by giladchase** [comment]
Already fixed by #562, closing.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/559)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/storage.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/559#-NXJcJtYDSSojZIJYeLD:-NXJcJtZ42Rp5V19Vota:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/8cadb498fba6742003841a092c4b6993b9dfd5c3/crates/native_blockifier/src/storage.rs#L136)):*
> ```XML
>                 .get_deprecated_class_definition_at(state_number, &class_hash)?
>                 .is_none();
>             if class_undeclared {
> ```

Add a blank line above.



_Code quote:_
```XML
if class_undeclared {
```
___
*[`crates/native_blockifier/src/storage.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/559#-NXJcPzJ0A5MutCwz0UY:-NXJcPzJ0A5MutCwz0UZ:bvxs99e) ([raw file](https://github.com/starkware-libs/blockifier/blob/8cadb498fba6742003841a092c4b6993b9dfd5c3/crates/native_blockifier/src/storage.rs#L146)):*
> ```XML
>         for (class_hash, (compiled_class_hash, raw_class)) in declared_class_hash_to_class {
>             let py_contract_class: PyContractClass = serde_json::from_str(&raw_class)?;
>             let contract_class = ContractClass::from(py_contract_class);
> ```

Move inside the `if`.



_Code quote:_
```XML
            let py_contract_class: PyContractClass = serde_json::from_str(&raw_class)?;
            let contract_class = ContractClass::from(py_contract_class);
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/559)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/559#-NX5AluF9So18tu1YUmD:-NXJdM2_8jXUlpalO88-:b-i74loh) ([raw file](https://github.com/starkware-libs/blockifier/blob/8cadb498fba6742003841a092c4b6993b9dfd5c3/crates/native_blockifier/src/storage.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We can instantiate with `::default()` since it's unused.
</blockquote></details>

Done in #561.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/559)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/559#-NX5AluF9So18tu1YUmD:-NXKfioi010SNynA4qCz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8cadb498fba6742003841a092c4b6993b9dfd5c3/crates/native_blockifier/src/storage.rs#L146)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done in #561.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/storage.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/559#-NXJcPzJ0A5MutCwz0UY:-NXKfmE13IMGJkexZ22A:b-jge671) ([raw file](https://github.com/starkware-libs/blockifier/blob/8cadb498fba6742003841a092c4b6993b9dfd5c3/crates/native_blockifier/src/storage.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move inside the `if`.
</blockquote></details>

No longer relevant? this class no longer exists

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/559)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/559#-:-NXKgTKV50AdMv-5w57B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
