### PR TITLE
Use try_from instead of as

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1322)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1322)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 297 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1322#-NnocyXg19iXql5tAytB:-NnocyXg19iXql5tAytC:b-vociab) ([raw file](https://github.com/starkware-libs/blockifier/blob/56c349bbdea4aca0783ca95200aa2f6ad2244ee9/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L297)):*
> ```XML
>         .get_segment_used_size(
>             usize::try_from(syscall_start_ptr.segment_index)
>                 .expect("Failed to convert isize to usize."),
> ```

In general and when possible, `expect` strings should document the assumption as to why you expected this to pass.
See [expect docs](https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style).



_Code quote:_
```XML
     .expect("Failed to convert isize to usize."),
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1322)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 297 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1322#-NnocyXg19iXql5tAytB:-No7-Rwq3jSIeM5H-piV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/56c349bbdea4aca0783ca95200aa2f6ad2244ee9/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L297)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

In general and when possible, `expect` strings should document the assumption as to why you expected this to pass.
See [expect docs](https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style).
</blockquote></details>

Done.

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r2, 2 of 14 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1322)* status: all files reviewed, 3 unresolved discussions (waiting on @OriStarkware)

___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 299 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1322#-NoC0ZUp98epYqra22Ed:-NoC0ZUp98epYqra22Ee:b-kia5nx) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3a5043d73fd83a29abea0682bffd1a2242a22df/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L299)):*
> ```XML
>                 .segment_index
>                 .try_into()
>                 .expect("The size of isize and usize should be the same."),
> ```

should it be isize < usize?



_Code quote:_
```XML
                .expect("The size of isize and usize should be the same."),
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 216 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1322#-NoC2oaj1g6Xj9VQm0Px:-NoC2oaj1g6Xj9VQm0Py:basq36d) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3a5043d73fd83a29abea0682bffd1a2242a22df/crates/blockifier/src/execution/entry_point.rs#L216)):*
> ```XML
>     ) -> TransactionExecutionResult<usize> {
>         let block_upper_bound = match mode {
>             // TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the convertion
> ```

Ditto for the rest



_Suggestion:_
```XML
          // TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the conversion
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 663 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1322#-NoC55NR0_3Ry2-7an5w:-NoC55NR0_3Ry2-7an5x:b-xhuvfh) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3a5043d73fd83a29abea0682bffd1a2242a22df/crates/blockifier/src/execution/syscalls/mod.rs#L663)):*
> ```XML
> 
>     // TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the convertion works.
>     let n_rounds_as_u64: u64 = n_rounds.try_into().expect("Failed to convert usize to u64.");
> ```

`from > (type inscription + into)`, at least for simple types, and when there isn't composition involved --- so no `try_from(<complicated expression)`, in that case try_into is better or extract to variable before the try_from, but that's usually too verbose.

I don't feel as strongly about the variable name, you can leave it as it is, your call.



_Suggestion:_
```XML
    let n_rounds = u64::try_from(n_rounds).expect("Failed to convert usize to u64.");
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 286 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1322#-NoC5vF5-oDoA2MlF8WL:-NoC5vF5-oDoA2MlF8WM:b-qsniq7) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3a5043d73fd83a29abea0682bffd1a2242a22df/crates/blockifier/src/state/cached_state.rs#L286)):*
> ```XML
>         // works.
>         let current_nonce_as_u64: u64 =
>             usize::try_from(current_nonce.0)?.try_into().expect("Failed to convert usize to u64.");
> ```

Can this be a u64::try_from? or is starkHash only castable into usize?



_Code quote:_
```XML
        let current_nonce_as_u64: u64 =
            usize::try_from(current_nonce.0)?.try_into().expect("Failed to convert usize to u64.");
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 835 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1322#-NoCf-9g-8vDa90MS3sp:-NoCf-9h7ckWEbFVqGOd:b-2iy159) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3a5043d73fd83a29abea0682bffd1a2242a22df/crates/blockifier/src/transaction/transactions_test.rs#L835)):*
> ```XML
>     // TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the convertion works.
>     let minimal_l1_gas_as_u64: u64 =
>         minimal_l1_gas.try_into().expect("Failed to convert u128 to u64.");
> ```

try_from



_Code quote:_
```XML
    let minimal_l1_gas_as_u64: u64 =
        minimal_l1_gas.try_into().expect("Failed to convert u128 to u64.");
```

**Review by giladchase — APPROVED** [review]
> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1322)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by giladchase — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1322#-:-NoGjJdb1aXljUyagKpz:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
