### PR TITLE
Add execution resource fields to PyTransactionExecutionInfo.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/323)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/323)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/323#-NPlhMYXDSfw0ydfpZ-p:-NPlhMYXDSfw0ydfpZ-q:bd4ms26) ([raw file](https://github.com/starkware-libs/blockifier/blob/c5e63ae83da9f9e856eaad5aea8f86d8dc78f31c/crates/native_blockifier/src/py_transaction_execution_info.rs#L25)):*
> ```XML
>     pub n_modified_contracts: usize,
>     #[pyo3(get)]
>     pub syscall_counter: usize,
> ```

This is a `HashMap`, please pass the one from the syscall handler.



_Code quote:_
```XML
pub syscall_counter: usize,
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/323)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/323#-NPlhMYXDSfw0ydfpZ-p:-NPllruH9655dqT9a2jr:bzhoiu6) ([raw file](https://github.com/starkware-libs/blockifier/blob/c5e63ae83da9f9e856eaad5aea8f86d8dc78f31c/crates/native_blockifier/src/py_transaction_execution_info.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is a `HashMap`, please pass the one from the syscall handler.
</blockquote></details>

Changed to a `HashMap`.
I'll get the values in the next PRs.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/323)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/323#-NPlhMYXDSfw0ydfpZ-p:-NPmX2QG7k4Q4C7Xdz6W:bbyt902) ([raw file](https://github.com/starkware-libs/blockifier/blob/c5e63ae83da9f9e856eaad5aea8f86d8dc78f31c/crates/native_blockifier/src/py_transaction_execution_info.rs#L25)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Changed to a `HashMap`.
I'll get the values in the next PRs.
</blockquote></details>

Okay, let's also add `n_class_updates`.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/323)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/323#-NPlhMYXDSfw0ydfpZ-p:-NPm_pdR52bIfBJn3VWD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c5e63ae83da9f9e856eaad5aea8f86d8dc78f31c/crates/native_blockifier/src/py_transaction_execution_info.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Okay, let's also add `n_class_updates`.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/323#-:-NPmeJY_29EIF47JJI3J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
