### PR TITLE
Fix: Updates the cache with the initial values of cells that were only accessed via write (affects the fee calculation and the state diff).

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/648)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/648)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/state/cached_state.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/648#-NYXgkDrC4oE5YMj20P6:-NYXgkDrC4oE5YMj20P7:b-1kzcq6) ([raw file](https://github.com/starkware-libs/blockifier/blob/675c598b952f7ae50be79533ac824d03d37c5a20/crates/blockifier/src/state/cached_state.rs#L215)):*
> ```XML
>     }
> 
>     // Assumes calling to `count_actual_state_changes` before. See its documentation.
> ```

I can call `update_initial_values_of_write_only_access`, but again it can return an error and that will change the state api.



_Code quote:_
```XML
 // Assumes calling to `count_actual_state_changes` before. See its documentation.
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/648)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/648#-NYXyc4q3TOLavSpgHEh:-NYY1t504MwAdrzjNgTI:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/659b9f7008d95cc68f0aa832f368ef9482562f1a/crates/blockifier/src/state/cached_state.rs#L75)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why do you need this?
</blockquote></details>

WDYM?

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/648)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/648#-NYYHE2uCDD-Fow-aO8w:-NYYHE2uCDD-Fow-aO8x:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/659b9f7008d95cc68f0aa832f368ef9482562f1a/crates/blockifier/src/state/cached_state.rs#L76)):*
> ```XML
>         // that `set_storage_at` does not affect the state field.
>         let mut storage_write_first_access: HashMap<ContractStorageKey, StarkFelt> = HashMap::new();
>         for (contract_storage_key, _v) in self.cache.storage_writes.iter() {
> ```





_Suggestion:_
```XML
for contract_storage_key in self.cache.storage_writes.keys()
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/648#-NYYN0_kC8_UdFqNShdm:-NYYN0_kC8_UdFqNShdn:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/659b9f7008d95cc68f0aa832f368ef9482562f1a/crates/blockifier/src/state/cached_state.rs#L78)):*
> ```XML
>         for (contract_storage_key, _v) in self.cache.storage_writes.iter() {
>             // First access to this cell was write; cache initial value.
>             if self.cache.storage_initial_values.get(contract_storage_key).is_none() {
> ```





_Suggestion:_
```XML
if !self.cache.storage_initial_values.contains_key(contract_storage_key) {
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 270 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/648#-NYYNx9-Ce2i3ZKzr085:-NYYNx9-Ce2i3ZKzr086:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a726b9cae060daee489a44d6c2a9fbf7854af22c/crates/blockifier/src/state/cached_state_test.rs#L270)):*
> ```XML
>     state.set_storage_at(contract_address, key, storage_val);
> 
>     // Set the storage with its already exists value (should't count as a change).
> ```





_Suggestion:_
```XML
    // Assign the existing value to the storage (this shouldn't be considered a change).
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/648)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/648#-NYYHE2uCDD-Fow-aO8w:-NYYSzZ1BzWpoEyGdW7a:boyexb3) ([raw file](https://github.com/starkware-libs/blockifier/blob/659b9f7008d95cc68f0aa832f368ef9482562f1a/crates/blockifier/src/state/cached_state.rs#L76)):*
> ```XML
>         // that `set_storage_at` does not affect the state field.
>         let mut storage_write_first_access: HashMap<ContractStorageKey, StarkFelt> = HashMap::new();
>         for (contract_storage_key, _v) in self.cache.storage_writes.iter() {
> ```

Done. Thanks!
___
*[`crates/blockifier/src/state/cached_state.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/648#-NYYN0_kC8_UdFqNShdm:-NYYT1a_2z47GBCC2a59:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/659b9f7008d95cc68f0aa832f368ef9482562f1a/crates/blockifier/src/state/cached_state.rs#L78)):*
> ```XML
>         for (contract_storage_key, _v) in self.cache.storage_writes.iter() {
>             // First access to this cell was write; cache initial value.
>             if self.cache.storage_initial_values.get(contract_storage_key).is_none() {
> ```

Done.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 270 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/648#-NYYNx9-Ce2i3ZKzr085:-NYYWLxNDW34xuOm9JZL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a726b9cae060daee489a44d6c2a9fbf7854af22c/crates/blockifier/src/state/cached_state_test.rs#L270)):*
> ```XML
>     state.set_storage_at(contract_address, key, storage_val);
> 
>     // Set the storage with its already exists value (should't count as a change).
> ```

Done.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/648#-:-NYkn0Wi9YezuFOQ9nNB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/648#-:-NYmMEey4kjO2jA-hIhM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Pull request merged**
