### PR TITLE
Rename gas price

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NcRtRWrCELWLZxyhQnr:-NcRtRWs9IMY79kWgSOx:b1iip) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/31539)

___

**Review by amosStarkware — CHANGES_REQUESTED** [review]
does [this] (https://github.com/starkware-libs/blockifier/blob/a7125b41280384a8f8d7431d359c9adcf59b05aa/crates/blockifier/src/test_utils.rs#L98)
also need to be changed to deprecated_l1_gas_price?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843#-:-NcWEFis-LAGJkYNvVhF:btky39f)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NcWCjUt5A1_L6icj4m5:-NcWCjUu2i_sX0VY48Kp:b-khj5kn) ([raw file](https://github.com/starkware-libs/blockifier/blob/a7125b41280384a8f8d7431d359c9adcf59b05aa/crates/native_blockifier/src/storage.rs#L190)):*
> ```XML
>             block_number,
>             // TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT need to add l1_gas_price to block header?
>             gas_price: GasPrice(py_block_info.deprecated_l1_gas_price),
> ```

why not rename this?



_Code quote:_
```XML
gas_price
```

**Review by dorimedini-starkware — COMMENTED** [review]
well, IMO no... `min_gas_price` shows up nowhere but here, and here it is a comment.
I'll add a TODO to add a max fee value for new gas price

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843#-:-NcWVURh9UeKeceuEtZg:bzcyd2c)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NcWCjUt5A1_L6icj4m5:-NcWZPUjE0pIG-_CzK1d:bu9gxie) ([raw file](https://github.com/starkware-libs/blockifier/blob/a7125b41280384a8f8d7431d359c9adcf59b05aa/crates/native_blockifier/src/storage.rs#L190)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why not rename this?
</blockquote></details>

Because this is a field of `BlockHeader`, which is not defined in the blockifier repo (starknet-api)

**Review by amosStarkware — COMMENTED** [review]
I don't understand the TODO - the new token will have the same MAX_FEE, no? why does it need a separate variable? 
and maybe the comment should be changed to `// 1000000 * min_l1_gas_price.`? or just deleted.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843#-:-NcY5BsM2XtsPW_OZ4rB:b-eiuizn)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by amosStarkware — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by amosStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by amosStarkware — CHANGES_REQUESTED** [review]
wait, it should be `min_deprecated_l1_gas_price`, no? sorry

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843#-:-Ncb3Y7F4Ohudxu1t9xx:b-wfjl0a)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NclBmEL0xPADVw1vcLW:-NclBmEL0xPADVw1vcLX:bw2icl6) (no related file):*
Do we want to call the new price `l1_gas_price` as well? Do both of them represent the same thing?

___

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NclBmEL0xPADVw1vcLW:-Ncqcj2hD100LUtKj7wR:b-gxcwcl) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we want to call the new price `l1_gas_price` as well? Do both of them represent the same thing?
</blockquote></details>

if I understood correctly (@dorimedini-starkware, please correct me if I'm wrong):
the current gas price is in Wei / Gwei, and it will be renamed `deprecated_l1_gas_price`.
the new gas price will be in STRK, and at first there will only be L1 gas (which will be named `l1_gas_price`), and in the future there will also be L2 gas, which will probably be called `l2_gas_price`.

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NclBmEL0xPADVw1vcLW:-NcqfLvzDR6nTXwE6-Fx:b-rftb87) (no related file):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

if I understood correctly (@dorimedini-starkware, please correct me if I'm wrong):
the current gas price is in Wei / Gwei, and it will be renamed `deprecated_l1_gas_price`.
the new gas price will be in STRK, and at first there will only be L1 gas (which will be named `l1_gas_price`), and in the future there will also be L2 gas, which will probably be called `l2_gas_price`.
</blockquote></details>

"the new gas price will be in STRK, and at first there will only be L1 gas" - I don't follow...
Do we plan to call the price of swapping STRK by ETH `l1_gas_price`?

___

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @EvyatarO)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NclBmEL0xPADVw1vcLW:-NcqgJQx2jI5vSq0u82i:b-cdb2yb) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

"the new gas price will be in STRK, and at first there will only be L1 gas" - I don't follow...
Do we plan to call the price of swapping STRK by ETH `l1_gas_price`?
</blockquote></details>

If the gas price on ethereum is 0.1 ETH and the new token is traded at 10 new_token per ETH, then I think:
`deprecated_l1_gas_price` (the current gas price) will be 0.1, and `l1_gas_price` will be 1.
I asked @EvyatarO, to see if I got it right

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @EvyatarO)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NclBmEL0xPADVw1vcLW:-NdPS_ST-YxTyzZIRft1:bjuh1j0) (no related file):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

If the gas price on ethereum is 0.1 ETH and the new token is traded at 10 new_token per ETH, then I think:
`deprecated_l1_gas_price` (the current gas price) will be 0.1, and `l1_gas_price` will be 1.
I asked @EvyatarO, to see if I got it right
</blockquote></details>

L1 gas is called L1 gas because ATM we only count the actual L1 cost to charge fees, right?
In the future we will have L2 gas (currently we count cairo steps, but that's not the same) to properly compute extra fees other than cost of L1 operations.
That's where the "L1" comes from.
I guess we don't actually need `strk_l1_gas_price`, as long as we have `eth_l1_gas_price` and a conversion ratio between STRK and ETH; right?

___

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @EvyatarO)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NclBmEL0xPADVw1vcLW:-NdQloAwBL5bX81VjrtA:bh7c7un) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

L1 gas is called L1 gas because ATM we only count the actual L1 cost to charge fees, right?
In the future we will have L2 gas (currently we count cairo steps, but that's not the same) to properly compute extra fees other than cost of L1 operations.
That's where the "L1" comes from.
I guess we don't actually need `strk_l1_gas_price`, as long as we have `eth_l1_gas_price` and a conversion ratio between STRK and ETH; right?
</blockquote></details>

First question - I think so, but I also think you're the one who told me that :-)
second question - Since `eth_l1_gas_price` will be deprecated, I think it makes sense to have the `strk_l1_gas_price` field and not convert it from the eth gas price. No?

___
___
*[`crates/blockifier/src/block_context.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NdQoPRx4mJfhDzwYLOw:-NdQoPRyDLpzhxDY72q8:bk02ye5) ([raw file](https://github.com/starkware-libs/blockifier/blob/8dbfcc0ff65f5e4dbc9b2b503cf3f8ea0f0aae93/crates/blockifier/src/block_context.rs#L18)):*
> ```XML
>     pub fee_token_address: ContractAddress,
>     pub vm_resource_fee_cost: Arc<HashMap<String, f64>>,
>     // TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT add l1_gas_price.
> ```

please rebase, it was added



_Code quote:_
```XML
// TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT add l1_gas_price.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @EvyatarO)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NclBmEL0xPADVw1vcLW:-NdUE11e5kTjif9InsUL:b38cd0a) (no related file):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

First question - I think so, but I also think you're the one who told me that :-)
second question - Since `eth_l1_gas_price` will be deprecated, I think it makes sense to have the `strk_l1_gas_price` field and not convert it from the eth gas price. No?
</blockquote></details>

I got mixed up - the conversion *is* the `strk_l1_gas_price` basically. Both gas prices are needed

___
___
*[`crates/blockifier/src/block_context.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NdQoPRx4mJfhDzwYLOw:-NdUEYvj5lLBWfohFk39:bcwnzwd) ([raw file](https://github.com/starkware-libs/blockifier/blob/8dbfcc0ff65f5e4dbc9b2b503cf3f8ea0f0aae93/crates/blockifier/src/block_context.rs#L18)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please rebase, it was added
</blockquote></details>

... rebased, still don't see it

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @EvyatarO)

___
*[`crates/blockifier/src/block_context.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NdQoPRx4mJfhDzwYLOw:-NdUFhCaBud6342DESyW:bkbi99n) ([raw file](https://github.com/starkware-libs/blockifier/blob/8dbfcc0ff65f5e4dbc9b2b503cf3f8ea0f0aae93/crates/blockifier/src/block_context.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... rebased, still don't see it
</blockquote></details>

now it's here, lol

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @EvyatarO and @giladchase)

___
*[`crates/blockifier/src/block_context.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NdQoPRx4mJfhDzwYLOw:-NdUHmDQ6tB9EaORCLx5:b-u61tdd) ([raw file](https://github.com/starkware-libs/blockifier/blob/8dbfcc0ff65f5e4dbc9b2b503cf3f8ea0f0aae93/crates/blockifier/src/block_context.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

now it's here, lol
</blockquote></details>

Sorry, I thought the PR that added it was already merged. I will review this later today (or @giladchase )

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @elintul and @EvyatarO)

___
*[`crates/native_blockifier/src/storage.rs` line 187 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NdUPF-n3HeqVjbzqVBC:-NdUPeij41mbWlCn3DQ-:b-cblik2) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f14dd244dc4d47b1f80f588f6fd0da20ba09dcb/crates/native_blockifier/src/storage.rs#L187)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You can leave only these two.
</blockquote></details>

isn't this out of scope of this PR...?
but ok... like this?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/storage.rs` line 187 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NdUPF-n3HeqVjbzqVBC:-NdUbkrc9jEv2cz4pfTE:bvrxr99) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f14dd244dc4d47b1f80f588f6fd0da20ba09dcb/crates/native_blockifier/src/storage.rs#L187)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't this out of scope of this PR...?
but ok... like this?
</blockquote></details>

I agree, but better make the code less confusing while at it.
Block number _is_ needed, sorry.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 187 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/843#-NdUPF-n3HeqVjbzqVBC:-NdUdT1KBmtQ6AMrjjPU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f14dd244dc4d47b1f80f588f6fd0da20ba09dcb/crates/native_blockifier/src/storage.rs#L187)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I agree, but better make the code less confusing while at it.
Block number _is_ needed, sorry.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843#-:-NdUepx-ExLftl-hgGN8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by amosStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/843#-:-NdUftq-2gU9zss0LFI6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
