### PR TITLE
chore(state): clean to_state_diff

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1911)

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/state/cached_state.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1911#-NyR2eaf3xHN7vI2GCky:-NyR2eaf3xHN7vI2GCkz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b85348010118efa9d7312ccaa118d63620234d4d/crates/blockifier/src/state/cached_state.rs#L63)):*
> ```XML
> 
>     // TODO(Yoni, 1/8/2024): remove this function.
>     /// Returns the state changes done through this state.
> ```





_Suggestion:_
```XML
    /// Returns the state changes made on this state.
```

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1911)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1911)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @dorimedini-starkware, and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1911#-NyR2eaf3xHN7vI2GCky:-NyTa_jmAwlBXZJw0li3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b85348010118efa9d7312ccaa118d63620234d4d/crates/blockifier/src/state/cached_state.rs#L63)):*
> ```XML
> 
>     // TODO(Yoni, 1/8/2024): remove this function.
>     /// Returns the state changes done through this state.
> ```

Done.

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
