### PR TITLE
refactor(fee): delete unused functions in TransactionExecutionInfo an…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…d in CallInfo

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1562)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1562)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1562#-Nr9MueV50AgpuGnPpJX:-Nr9MueV50AgpuGnPpJY:b-f1b55i) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d134273bf28f16090bd7b8a67339eda40d1de00/crates/blockifier/src/transaction/objects_test.rs#L23)):*
> ```XML
>         CallInfo {
>             call: CallEntryPoint {
>                 class_hash: Some(ClassHash(stark_felt!("0x1"))),
> ```

Could you please explain why you've added this?



_Code quote:_
```XML
class_hash: Some(ClassHash(stark_felt!("0x1"))),
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1562)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1562#-Nr9MueV50AgpuGnPpJX:-Nr9j9S18HI5xYMNdN-I:bc2aq2y) ([raw file](https://github.com/starkware-libs/blockifier/blob/0d134273bf28f16090bd7b8a67339eda40d1de00/crates/blockifier/src/transaction/objects_test.rs#L23)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Could you please explain why you've added this?
</blockquote></details>

talked F2F

**Review by MohammadNassar1 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1562#-:-Nr9k_BL5ziVCwRex-vI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1562#-:-NrAVaob5yTDEStCS8Zw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
