### PR TITLE
Make `run[_non]_revertible` use fee token address according to version

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/890)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/890)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/890#-Nd_hGQsEZoed8I7b5Qh:-Nd_haux3e5xs4TyzJ4V:bngxroi) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. Shouldn't this go together with [this](https://reviewable.io/reviews/starkware-libs/blockifier/891)?
2. Asking because both PRs (this and that) could use a unit test, but it can be the same test...
</blockquote></details>

Cause they are separate tasks on monday :grimacing: but I see you point re 2.

___
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 411 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/890#-Nd_gohF42gZoJR-5-sn:-Nd_i5VI37RfNcaykduE:b-5k9lvx) ([raw file](https://github.com/starkware-libs/blockifier/blob/8330b44be3dffdc09bbad09d5b366fa0b95dfce9/crates/blockifier/src/transaction/account_transaction.rs#L411)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`self` implements `HasTransactionVersion`, right? Why not pass it directly?
Or does AccountTransaction not implement this trait?
</blockquote></details>

So  `TransactionVersion` and `AccountTransactionContext` implement `HasTransactionVersion`.

I going for convenience, that is, you pass the one that makes most sense in context (technically they both compile into the same thing).

So here, in a "Transaction context" we have `account_tx_context` so I pass that, but in general (and in other contexts) getting fee_token_address doesn't need to depend on a Transaction, so passing just the `TransactionVersion` is also allowed.

Is this a mess? I'll rethink it if it is :thinking:

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/890)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 411 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/890#-Nd_gohF42gZoJR-5-sn:-Nd_jj7h5JSHezhkSp_p:b-ocxis5) ([raw file](https://github.com/starkware-libs/blockifier/blob/8330b44be3dffdc09bbad09d5b366fa0b95dfce9/crates/blockifier/src/transaction/account_transaction.rs#L411)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

So  `TransactionVersion` and `AccountTransactionContext` implement `HasTransactionVersion`.

I going for convenience, that is, you pass the one that makes most sense in context (technically they both compile into the same thing).

So here, in a "Transaction context" we have `account_tx_context` so I pass that, but in general (and in other contexts) getting fee_token_address doesn't need to depend on a Transaction, so passing just the `TransactionVersion` is also allowed.

Is this a mess? I'll rethink it if it is :thinking:
</blockquote></details>

nah, maybe better to prevent cloning, only implement on account_tx_context

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/890#-:-Nd_nwNIBFoAB_Ni0sRS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/890)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
