### PR TITLE
fix(native_blockifier): returns an error when a builtin is missed from the bouncer config

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2048)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2048)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2048#-O1Ceb6U7-wIZlbRGj1V:-O1Ceb6U7-wIZlbRGj1W:b-ux8ea8) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d3bc5012de8b3eaa8a0ce0e5a18f4747b2e5ba1/crates/blockifier/src/bouncer.rs#L135)):*
> ```XML
>     ($($field:ident),+) => {
>             pub fn all_non_zero(&self) -> bool {
>                 true $( && self.$field != 0 )+
> ```

isn't there some kind of delimiter syntax for this case?
non-blocking



_Suggestion:_
```XML
$( self.$field != 0 )&&+
```
___
*[`crates/blockifier/src/bouncer.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2048#-O1CepmM0yQVeAX-Yy-o:-O1CepmM0yQVeAX-Yy-p:b-c4v0gl) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d3bc5012de8b3eaa8a0ce0e5a18f4747b2e5ba1/crates/blockifier/src/bouncer.rs#L165)):*
> ```XML
>         range_check,
>         range_check96
>     );
> ```

no need to write the list twice



_Suggestion:_
```XML
macro_rules! impl_builtin_variants {
    ($($field:ident),+) => {
        impl_checked_sub!($($field:ident),+);
        impl_all_non_zero!($($field:ident),+);
    };
}

impl BuiltinCount {
    impl_builtin_variants!(
        add_mod,
        bitwise,
        ec_op,
        ecdsa,
        keccak,
        mul_mod,
        pedersen,
        poseidon,
        range_check,
        range_check96
    );
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2048)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2048#-O1CepmM0yQVeAX-Yy-o:-O1ChzK26tUHuwV52mkH:b-owists) ([raw file](https://github.com/starkware-libs/blockifier/blob/1d3bc5012de8b3eaa8a0ce0e5a18f4747b2e5ba1/crates/blockifier/src/bouncer.rs#L165)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need to write the list twice
</blockquote></details>

You are right. Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2048)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2048#-O1Cvj_m92wItibOO9I9:-O1Cvj_m92wItibOO9IA:b3xdl9m) ([raw file](https://github.com/starkware-libs/blockifier/blob/c5e0806b9be4f128ae246a0617bff2492f78f72a/crates/blockifier/src/bouncer.rs#L135)):*
> ```XML
>     ($($field:ident),+) => {
>             pub fn all_non_zero(&self) -> bool {
>                 $( self.$field != 0 )&&+
> ```

missed this... no auto-formatter for macro body defs apparently



_Suggestion:_
```XML
        pub fn all_non_zero(&self) -> bool {
            $( self.$field != 0 )&&+
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2048)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2048)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2048#-:-O1LJafeDC1bU7NiCYm-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
