### PR TITLE
refactor: use ADDITIONAL_FIELDS instead of ALLOWED_GAS_COST_NAMES

### PR DESCRIPTION
**Pull request by OriStarkware**
…S_COST_NAMES

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)

### CODE REVIEW

**Review by OriStarkware — COMMENTED** [review]
`ALLOWED_GAS_COST_NAMES` was the list of fields in GasCosts. We were using the list in the conversion by ignoring everything that wasn't whitelisted. Now, it is code duplication because it is simply whitelisting all of the `GasCosts` fields.
We can not remove this list either because we have other fields in the json that `GasCosts` does not contain, which should be filtered out.
So, in this PR, I am replacing the whitelist of the `GasCosts` fields with a different whitelist, `ALLOWED_GAS_COST_ADDITIONAL_NAMES`, that contains the names of the additional fields in the json that are not included in `GasCosts` so they could be filtered out.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-:-NsZZv_g54YJr6xyoblI:b5au75h)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 411 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsm5d805dGh8IxZR89q:-Nsm5d805dGh8IxZR89r:b17urgh) ([raw file](https://github.com/starkware-libs/blockifier/blob/f412aecfd38207cce6c0c86e18bc31603ca2361a/crates/blockifier/src/versioned_constants.rs#L411)):*
> ```XML
> impl OSConstants {
>     // List of all gas cost constants that *must* be present in the JSON file, all other consts are
>     // ignored. See documentation in core/os/constants.cairo.
> ```

Fix the comment, and explain why the following members are allowed but not in the struct (or give some reference to an explanation (the current one is not  in the repo?)



_Code quote:_
```XML
    // List of all gas cost constants that *must* be present in the JSON file, all other consts are
    // ignored. See documentation in core/os/constants.cairo.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 412 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsm7CIYEXWDIj6NkOaL:-Nsm7CIYEXWDIj6NkOaM:b-3hj3t) ([raw file](https://github.com/starkware-libs/blockifier/blob/f412aecfd38207cce6c0c86e18bc31603ca2361a/crates/blockifier/src/versioned_constants.rs#L412)):*
> ```XML
>     // List of all gas cost constants that *must* be present in the JSON file, all other consts are
>     // ignored. See documentation in core/os/constants.cairo.
>     const ALLOWED_GAS_COST_ADDITIONAL_NAMES: [&'static str; 25] = [
> ```

Move to `GasCosts` struct.



_Suggestion:_
```XML
const ALLOWED_ADDITIONAL_NAMES: [&'static str; 25] = [
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 485 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsm6pyF0qqOVf5hPJPD:-Nsm6pyGEYU4dNQVBe54:b1809aj) ([raw file](https://github.com/starkware-libs/blockifier/blob/f412aecfd38207cce6c0c86e18bc31603ca2361a/crates/blockifier/src/versioned_constants.rs#L485)):*
> ```XML
>     fn parse_gas_costs(&self) -> Result<IndexMap<String, u64>, OsConstantsSerdeError> {
>         let mut gas_costs = IndexMap::new();
>         let gas_cost_whitelist: IndexSet<_> =
> ```

or the following or removing this line and use the `GasCosts::ALLOWED_ADDITIONAL_NAMES.iter().copied().collect();` in the `if` condition with `contains(...)`



_Suggestion:_
```XML
let allowed_additional_names: IndexSet<_> =
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 489 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsm7glF16x51GKVk1p_:-Nsm7glF16x51GKVk1pa:b-429196) ([raw file](https://github.com/starkware-libs/blockifier/blob/f412aecfd38207cce6c0c86e18bc31603ca2361a/crates/blockifier/src/versioned_constants.rs#L489)):*
> ```XML
>         for (key, value) in &self.raw_json_file_as_dict {
>             if gas_cost_whitelist.contains(key.as_str()) {
>                 // Ignore non-whitelist consts.
> ```

Change according the new logic



_Code quote:_
```XML
// Ignore non-whitelist consts
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsm7qsYEKXx16Bxyq7A:-Nsm7qsYEKXx16Bxyq7B:bo144eu) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16303f982edc3d7cdbe50dc8002bf12dd8a32d1/crates/blockifier/src/versioned_constants_test.rs#L22)):*
> ```XML
>         "validate_timestamp_rounding": 222,
>         "ignore the gas string": "GAS!",
>         "I look like a gas cost but my name is all wrong": 0
> ```

Add an allowed additional name in this test with some explanatory comment (or better - in a new test to check the functionality).



_Code quote:_
```XML
        "ignore the gas string": "GAS!",
        "I look like a gas cost but my name is all wrong": 0
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 411 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsm5d805dGh8IxZR89q:-NsmWaX4BqHwTPzaaEDD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f412aecfd38207cce6c0c86e18bc31603ca2361a/crates/blockifier/src/versioned_constants.rs#L411)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Fix the comment, and explain why the following members are allowed but not in the struct (or give some reference to an explanation (the current one is not  in the repo?)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 412 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsm7CIYEXWDIj6NkOaL:-NsmWfTF4xgRsvR6h-NF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f412aecfd38207cce6c0c86e18bc31603ca2361a/crates/blockifier/src/versioned_constants.rs#L412)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Move to `GasCosts` struct.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 485 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsm6pyF0qqOVf5hPJPD:-NsmWyfq1KQHC6DWY-96:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f412aecfd38207cce6c0c86e18bc31603ca2361a/crates/blockifier/src/versioned_constants.rs#L485)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

or the following or removing this line and use the `GasCosts::ALLOWED_ADDITIONAL_NAMES.iter().copied().collect();` in the `if` condition with `contains(...)`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 489 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsm7glF16x51GKVk1p_:-NsmX-hG-G_1JqUu68pv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f412aecfd38207cce6c0c86e18bc31603ca2361a/crates/blockifier/src/versioned_constants.rs#L489)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Change according the new logic
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsm7qsYEKXx16Bxyq7A:-NsmXgBd3vP0a84Y2i0z:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16303f982edc3d7cdbe50dc8002bf12dd8a32d1/crates/blockifier/src/versioned_constants_test.rs#L22)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Add an allowed additional name in this test with some explanatory comment (or better - in a new test to check the functionality).
</blockquote></details>

Done.

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsmlf4jAnS80NxH1Z-V:-NsmrzWEACgc5187iyOm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0db889b049f416ef6ef6c1d4af716f232fa25081/crates/blockifier/src/versioned_constants.rs#L39)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Move or copy this comment or something in the same flavor above `const ADDITIONAL_ALLOWED_NAMES`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 397 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NsmltL49jJ5-CQzTfyx:-Nsmrz5B1mEJxLxBYTYr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0db889b049f416ef6ef6c1d4af716f232fa25081/crates/blockifier/src/versioned_constants.rs#L397)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

See the comment above, I suggest advising @giladchase what's the reason and deciding where to place this comment.
</blockquote></details>

Done.

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-:-NsnP3Y_3XZsY2jDq9om:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @OriStarkware)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NsnPD2J5oX5rxk5tccP):*




_Suggestion:_
```
refactor: use ALLOWED_ADDITIONAL_NAMES instead of ALLOWED_GAS_COST_NAMES
```

**Comment by barak-b-starkware** [comment]
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NsnPD2J5oX5rxk5tccP):*
PR name too

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/versioned_constants_test.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NsnSYR35iZfW4IyUdAs:-NsnSYR35iZfW4IyUdAt:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0cbfb451e6632994089ddc531a150ead2325ff59/crates/blockifier/src/versioned_constants_test.rs#L8)):*
> ```XML
> 
> #[test]
> fn test_successful_parsing() {
> ```





_Suggestion:_
```XML
#[test]
 // TODO: Add an unallowed field scenario.
fn test_successful_parsing() {
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/versioned_constants_test.rs` line 23 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NsnT29Y80sxuk9PinDq:-NsnT29Y80sxuk9PinDr:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0cbfb451e6632994089ddc531a150ead2325ff59/crates/blockifier/src/versioned_constants_test.rs#L23)):*
> ```XML
>         "validate_timestamp_rounding": 222,
>         "l2_gas_index": "This will be ignored as well",
>         "nop_entry_point_offset": "Ignored"
> ```





_Suggestion:_
```XML
        "error_out_of_gas": "An additional field in GasCosts::ADDITIONAL_ALLOWED_NAMES, this will be ignored.",
        "validate_block_number_rounding": 111,
        "validate_timestamp_rounding": 222,
        "l2_gas_index": "An additional field in GasCosts::ADDITIONAL_ALLOWED_NAMES, this will be ignored.",
        "nop_entry_point_offset": "An additional field in GasCosts::ADDITIONAL_ALLOWED_NAMES, this will be ignored."
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NsnPD2J5oX5rxk5tccP):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

PR name too
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 487 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NsnPfZFAkYcweMtSWmd:-NsrD3acAdqH9PPi5PwO:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0cbfb451e6632994089ddc531a150ead2325ff59/crates/blockifier/src/versioned_constants.rs#L487)):*
> ```XML
>         let mut gas_costs = IndexMap::new();
>         let allowed_additional_names: IndexSet<_> =
>             GasCosts::ADDITIONAL_ALLOWED_NAMES.iter().copied().collect();
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 492 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NsnRO3-Bf9Q3IpHzhgU:-NsrDbL816VOxOl4kE2N:baberh2) ([raw file](https://github.com/starkware-libs/blockifier/blob/0cbfb451e6632994089ddc531a150ead2325ff59/crates/blockifier/src/versioned_constants.rs#L492)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

IMO the list is too short to convert into a set. So I prefer the following way (but if you don't, change the name of the variable so it will be consistent with the list's name):

(notice the `&` addition, the `constants` instead of `consts` and additional instead of additional in the comment).
</blockquote></details>

I think I prefer to keep it a set for now and rethink it later if needed. Changed the typo.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NsnSYR35iZfW4IyUdAs:-NsrE0il0RN5Gtjv8d2v:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0cbfb451e6632994089ddc531a150ead2325ff59/crates/blockifier/src/versioned_constants_test.rs#L8)):*
> ```XML
> 
> #[test]
> fn test_successful_parsing() {
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 23 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NsnT29Y80sxuk9PinDq:-NsrEk9oBlWxRnVAFmOw:b-pnman4) ([raw file](https://github.com/starkware-libs/blockifier/blob/0cbfb451e6632994089ddc531a150ead2325ff59/crates/blockifier/src/versioned_constants_test.rs#L23)):*
> ```XML
>         "validate_timestamp_rounding": 222,
>         "l2_gas_index": "This will be ignored as well",
>         "nop_entry_point_offset": "Ignored"
> ```

I changed them a bit to make them fit, and also I think the values should not be the same.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-:-Nsra5KnDa0TFTmflsWd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 489 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-Nsr_Wrk8hudZCLLpqZs:-Nsr_WrlDZEm-GB6Q36p:bhafttr) ([raw file](https://github.com/starkware-libs/blockifier/blob/35a4a79feea7e85187e85728f9b1341c86e19e60/crates/blockifier/src/versioned_constants.rs#L489)):*
> ```XML
>         for (key, value) in &self.raw_json_file_as_dict {
>             if additional_fields.contains(key.as_str()) {
>                 // Ignore additional consts.
> ```

Not blocking, only if you want:



_Suggestion:_
```XML
// Ignore additional constants.
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: all files reviewed, 3 unresolved discussions (waiting on @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 436 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NtWdF2I3Wah_BjB48C0:-NtWdF2I3Wah_BjB48C1:b-dth6hi) ([raw file](https://github.com/starkware-libs/blockifier/blob/98f924065c13c4f7f2cda3bb80f25b6fad4a86f9/crates/blockifier/src/versioned_constants.rs#L436)):*
> ```XML
>     // List of additinal fields, beside the fields of GasCosts, that are not used by Blockifier but
>     // included for transparency. These fields will be ignored during the creation of the GasCosts
>     // object.
> ```

Try to avoid struct names in the doc (can "contaminate" the search).



_Suggestion:_
```XML
    // List of additinal os constants, beside the gas cost and validate rounding constants, that are not used by the blockifier but
    // included for transparency. These constanst will be ignored during the creation of the struct containing the gas costs.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 437 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NtWd1FXBy4nA0Z_iauF:-NtWd1FY69V8Px4gG1fY:b-er6f1) ([raw file](https://github.com/starkware-libs/blockifier/blob/98f924065c13c4f7f2cda3bb80f25b6fad4a86f9/crates/blockifier/src/versioned_constants.rs#L437)):*
> ```XML
>     // included for transparency. These fields will be ignored during the creation of the GasCosts
>     // object.
>     const ADDITIONAL_FIELDS: [&'static str; 25] = [
> ```

Consider moving it to the struct `OsConstants` (as it is no longer related to gas cost).



_Code quote:_
```XML
const ADDITIONAL_FIELDS: [&'static str; 25] = [
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 24 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NtWeMzZBkYKKaQc_NCJ:-NtWeMzZBkYKKaQc_NCK:b4d79uw) ([raw file](https://github.com/starkware-libs/blockifier/blob/98f924065c13c4f7f2cda3bb80f25b6fad4a86f9/crates/blockifier/src/versioned_constants_test.rs#L24)):*
> ```XML
>         "validate_timestamp_rounding": 222,
>         "l2_gas_index": "An additional field in GasCosts::ADDITIONAL_ALLOWED_NAMES, to ignore.",
>         "nop_entry_point_offset": "Another additional field in GasCosts::ADDITIONAL_ALLOWED_NAMES."
> ```

Why so many? Why isn't one additional field enough? 



_Code quote:_
```XML
        "error_out_of_gas": "An additional field in GasCosts::ADDITIONAL_ALLOWED_NAMES, ignored.",
        "validate_block_number_rounding": 111,
        "validate_timestamp_rounding": 222,
        "l2_gas_index": "An additional field in GasCosts::ADDITIONAL_ALLOWED_NAMES, to ignore.",
        "nop_entry_point_offset": "Another additional field in GasCosts::ADDITIONAL_ALLOWED_NAMES."
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 437 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NtWd1FXBy4nA0Z_iauF:-NtWl1im0UCbygklXLKM:b-opf4wj) ([raw file](https://github.com/starkware-libs/blockifier/blob/98f924065c13c4f7f2cda3bb80f25b6fad4a86f9/crates/blockifier/src/versioned_constants.rs#L437)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider moving it to the struct `OsConstants` (as it is no longer related to gas cost).
</blockquote></details>

I asked to move it here but didn't know that it's not related to gas cost. @OriStarkware, sorry for that (:

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 437 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NtWd1FXBy4nA0Z_iauF:-Ntq8WNG-f3hba2Nlq94:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/98f924065c13c4f7f2cda3bb80f25b6fad4a86f9/crates/blockifier/src/versioned_constants.rs#L437)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I asked to move it here but didn't know that it's not related to gas cost. @OriStarkware, sorry for that (:
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 24 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NtWeMzZBkYKKaQc_NCJ:-Ntq8XUw9n51jT0WO7dm:ba9g1lm) ([raw file](https://github.com/starkware-libs/blockifier/blob/98f924065c13c4f7f2cda3bb80f25b6fad4a86f9/crates/blockifier/src/versioned_constants_test.rs#L24)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why so many? Why isn't one additional field enough?
</blockquote></details>

One can be enough, but I think that three will add more coverage and do not add much complexity to the test.

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 24 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NtWeMzZBkYKKaQc_NCJ:-Nttbl-v1pGrr02NZJ52:b-hl8iv6) ([raw file](https://github.com/starkware-libs/blockifier/blob/98f924065c13c4f7f2cda3bb80f25b6fad4a86f9/crates/blockifier/src/versioned_constants_test.rs#L24)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

One can be enough, but I think that three will add more coverage and do not add much complexity to the test.
</blockquote></details>

What is the difference between the three cases? What additional coverage do we get by having more than one additional field?

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 24 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NtWeMzZBkYKKaQc_NCJ:-NttyGCl2ha6GqE2HHw8:bnii83z) ([raw file](https://github.com/starkware-libs/blockifier/blob/98f924065c13c4f7f2cda3bb80f25b6fad4a86f9/crates/blockifier/src/versioned_constants_test.rs#L24)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is the difference between the three cases? What additional coverage do we get by having more than one additional field?
</blockquote></details>

Different strings with different lengths. It will also cover the case when there is more than one extra value.

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 24 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1621#-NtWeMzZBkYKKaQc_NCJ:-Ntu8r8g1lTvF7ArXkR2:b-v7n72l) ([raw file](https://github.com/starkware-libs/blockifier/blob/98f924065c13c4f7f2cda3bb80f25b6fad4a86f9/crates/blockifier/src/versioned_constants_test.rs#L24)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Different strings with different lengths. It will also cover the case when there is more than one extra value.
</blockquote></details>

I am not sure I understand.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1621)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
