### PR TITLE
Change the weights in cairo_resource_fee_weights to float.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/397)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/397)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/block_context.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/397#-NSf4GCI1jfklbHQIX6X:-NSf4GCI1jfklbHQIX6Y:b-9jzsl2) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8aac97f6b95a4138bf21140ea85d2f49ebb8a77/crates/blockifier/src/block_context.rs#L15)):*
> ```XML
>     pub sequencer_address: ContractAddress,
>     pub fee_token_address: ContractAddress,
>     pub cairo_resource_fee_weights: HashMap<String, f64>,
> ```

I chose `f64` following [this](https://doc.rust-lang.org/book/ch03-02-data-types.html#:~:text=The%20default%20type%20is%20f64%20because%20on%20modern%20CPUs%2C%20it%E2%80%99s%20roughly%20the%20same%20speed%20as%20f32).



_Code quote:_
```XML
f64
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/397#-NSf3jwMADJ31Nivu9Wx:-NSf3jwNDk6H_VmUaiXW:b-ugmmau) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8aac97f6b95a4138bf21140ea85d2f49ebb8a77/crates/blockifier/src/fee/fee_utils.rs#L88)):*
> ```XML
>         .iter()
>         .map(|(key, resource_val)| {
>             (*resource_val) * cairo_resource_usage.0.get(key).cloned().unwrap_or_default() as f64
> ```

It is not safe because `usize` can be of 64 bits, hence we can loose precision. Do you have any alternatives?



_Code quote:_
```XML
as f64
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/397)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/397#-NSf3jwMADJ31Nivu9Wx:-NSfQ4zk6-gzIH-3_tpJ:b-kaherk) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8aac97f6b95a4138bf21140ea85d2f49ebb8a77/crates/blockifier/src/fee/fee_utils.rs#L88)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It is not safe because `usize` can be of 64 bits, hence we can loose precision. Do you have any alternatives?
</blockquote></details>

don't know what to say here, this is unsafe anyway (precision can always be lost with floats...). you mean unsafe i.e. panic? don't know how to solve this type of problem

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/397)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/397#-NSf3jwMADJ31Nivu9Wx:-NSfUttUEZhfppmcdf1P:bofs8ej) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8aac97f6b95a4138bf21140ea85d2f49ebb8a77/crates/blockifier/src/fee/fee_utils.rs#L88)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't know what to say here, this is unsafe anyway (precision can always be lost with floats...). you mean unsafe i.e. panic? don't know how to solve this type of problem
</blockquote></details>

I mean unsafe because we can lose information. @elintul  - can we know in advance an upper bound on the actual usage?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/397)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/397#-NSfaKsy6BhJ4pPFdFGH:-NSfaKsy6BhJ4pPFdFGI:baq46dk) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8aac97f6b95a4138bf21140ea85d2f49ebb8a77/crates/blockifier/src/fee/fee_utils.rs#L90)):*
> ```XML
>             (*resource_val) * cairo_resource_usage.0.get(key).cloned().unwrap_or_default() as f64
>         })
>         .fold(f64::NAN, f64::max);
> ```

maybe `0 as f64`?



_Code quote:_
```XML
f64::NAN
```

**Review by noaov1 — COMMENTED** [review]
FYI @amosStarkware

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/397#-:-NSfay5W3UeTmGO_zOuk:b-jm92a3)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/397)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/397#-NSf3jwMADJ31Nivu9Wx:-NSplzL0EGniqUfp7i6b:b-unqz7w) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8aac97f6b95a4138bf21140ea85d2f49ebb8a77/crates/blockifier/src/fee/fee_utils.rs#L88)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I mean unsafe because we can lose information. @elintul  - can we know in advance an upper bound on the actual usage?
</blockquote></details>

I think it can be `u64` (even `u32`), which is big enough.
How difficult is it to convert to integers in Python?

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/397)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/397#-NSfaKsy6BhJ4pPFdFGH:-NSuDuzE7lP6l8hKaxOI:b-kbr766) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8aac97f6b95a4138bf21140ea85d2f49ebb8a77/crates/blockifier/src/fee/fee_utils.rs#L90)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Wouldn't that hide an error (when the `cairo_resource_fee_weights` is empty)? 0 is a valid output, no? 
</blockquote></details>

ah, right.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/397#-:-NSuIRi-5INwyws-GRpU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
