### PR TITLE
Uncomment fixed security tests.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/275)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/275)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE7178CR5tP-m4bRhL:-NOE7178CR5tP-m4bRhM:b-xrmhqr) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L235)):*
> ```XML
> 
>     run_security_test(
>         "Bad expr: {test}. (Cannot evaluate ap-based or complex references: ['test'])",
> ```

Where is this formatted in? What does it represent?



_Code quote:_
```XML
'test'
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/275)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/275)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE7178CR5tP-m4bRhL:-NOE7QiAAaBvXsFIPbS5:bga5d9) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L235)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where is this formatted in? What does it represent?
</blockquote></details>

```
@external
func test_bad_expr_eval() {
    let test = [cast(fp, TxInfo*)];
    with_attr error_message("Bad expr: {test}.") {
        assert 1 = 0;
    }
    return ();
}
```

This is the entry point that's running; the error message can format an expression into it, but not complex expressions like this one. I don't know the reason behind it, but the error matches the one in the Python VM.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/275)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE8fne0o1TUQSGEXzg:-NOE8fne0o1TUQSGEXzh:b-uxhmuq) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L168)):*
> ```XML
>         panic!("Expected error: {expected_error}.\nGot: {error}")
>     }
> }
> ```

Can you format in the values to the error messages?
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE87253Pp7HOqdBAUe:-NOE87253Pp7HOqdBAUf:bktoyih) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L175)):*
> ```XML
> 
>     run_security_test(
>         "Expected relocatable",
> ```

This is different from the error message in the Pythonic VM.
Perhaps the message should say something about attempting to write to the syscall segment outside the OS?



_Code quote:_
```XML
"Expected relocatable"
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE914NCSnxy0pL134B:-NOE914NCSnxy0pL134C:bund90c) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L221)):*
> ```XML
> 
>     run_security_test(
>         "exceeds maximum offset value",
> ```

Different than Python, is this informative enough?



_Code quote:_
```XML
"exceeds maximum offset value"
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/275)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE9hOX65YLhBXnkPQ1:-NOE9hOX65YLhBXnkPQ2:bund90c) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L321)):*
> ```XML
> 
>     run_security_test(
>         "Memory addresses must be relocatable",
> ```

Different than Python, is this informative enough?



_Code quote:_
```XML
"Memory addresses must be relocatable"
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOEA-ec3trDLG938JWE:-NOEA-ec3trDLG938JWF:bkgofbd) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L376)):*
> ```XML
>         &mut state,
>     );
> ```

Can we format in the RO segment names?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/275)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE8fne0o1TUQSGEXzg:-NOEzwMPAp6aqIxxBlbs:bkod7zw) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L168)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you format in the values to the error messages?
</blockquote></details>

I can hard code the values that aren't expected to change, or I can try using regex in Rust. What do you prefer?
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE87253Pp7HOqdBAUe:-NOF1G2t4d-IBO5KgLhd:b-xv71me) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L175)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is different from the error message in the Pythonic VM.
Perhaps the message should say something about attempting to write to the syscall segment outside the OS?
</blockquote></details>

It's different because it fails before the validation; for writing a felt into a pointer, which is good I think (I'm not sure why it doesn't fail in the python VM).
Regarding the writing into the syscall segment (or changing the syscall pointer), that's fine and should also happen outside of the OS. When someone wants to use a syscall, he writes the request into the syscall segment, and after getting the response he advances the syscall pointer by assigning a new value to it. The OS validates the values that are already written before.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE914NCSnxy0pL134B:-NOFAW-ID9yBzFYlgmaX:b4liffs) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L221)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Different than Python, is this informative enough?
</blockquote></details>

Well, I think it's more informative than the error in Python. In Python it just says the value is invalid, here it says specifically because the offset is too large.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE9hOX65YLhBXnkPQ1:-NOFEOXICc33NYfhW5Kk:b-giczxy) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L321)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Different than Python, is this informative enough?
</blockquote></details>

It is more informative in Python, there, there's `validate_runtime_request_type` which uses the `CairoStructProxy`to check the field types. We can consider adding it at some point.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOEA-ec3trDLG938JWE:-NOFPisyACcyxs-ppas8:bvbl973) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L376)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we format in the RO segment names?
</blockquote></details>

Do you want to add the names to the `ReadOnlySegment` struct for that?

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/275)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE8fne0o1TUQSGEXzg:-NOFSR2J04FELccafhLY:b-nmjt17) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L168)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I can hard code the values that aren't expected to change, or I can try using regex in Rust. What do you prefer?
</blockquote></details>

If regex isn't too complicated, it's preferable. O/w, hardcode.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOEA-ec3trDLG938JWE:-NOFSZXmDTF7553RuCIO:b-sp6gws) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L376)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do you want to add the names to the `ReadOnlySegment` struct for that?
</blockquote></details>

What's the situation in Python?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/275)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOE8fne0o1TUQSGEXzg:-NOFXTbn3aFsQ7bltvNd:b-86evoj) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L168)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

If regex isn't too complicated, it's preferable. O/w, hardcode.
</blockquote></details>

Sure, I'll work on it.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/275#-NOEA-ec3trDLG938JWE:-NOFXKwE9CeNuViv62KT:bw88ytf) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ec2436ee866009cd9d75a364db4f40ec7dc05/crates/blockifier/src/execution/entry_point_test.rs#L376)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What's the situation in Python?
</blockquote></details>

Also doesn't specify the name.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/275#-:-NOK8BbrEUBcxZQE4q2F:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
