### PR TITLE
Add out of gas test.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/593)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/593)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/593#-NXejvTZ7LJB5abU5mPe:-NXejvTZ7LJB5abU5mPf:bgg6ikw) ([raw file](https://github.com/starkware-libs/blockifier/blob/d4e5269f816623a603b876e4df280e3d443029c0/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
> ```XML
>     };
>     let error = entry_point_call.execute_directly(&mut state).unwrap_err();
>     assert_matches!(error,EntryPointExecutionError::ExecutionFailed{ error_data}
> ```

Fix your formatter?
@giladchase, how come `rustfmt` didn't catch this?



_Suggestion:_
```XML
assert_matches!(error, EntryPointExecutionError::ExecutionFailed{ error_data }
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/593)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/593#-NXejvTZ7LJB5abU5mPe:-NXenIY5B92bLrHN-I6f:b-vzvq72) ([raw file](https://github.com/starkware-libs/blockifier/blob/d4e5269f816623a603b876e4df280e3d443029c0/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Fix your formatter?
@giladchase, how come `rustfmt` didn't catch this?
</blockquote></details>

`rustfmt` [doesn't support macros](https://github.com/rust-lang/rustfmt/issues/8).

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/593)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/593#-NXejvTZ7LJB5abU5mPe:-NXeoAOm3tHji0Amox26:b-plkk6l) ([raw file](https://github.com/starkware-libs/blockifier/blob/d4e5269f816623a603b876e4df280e3d443029c0/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

`rustfmt` [doesn't support macros](https://github.com/rust-lang/rustfmt/issues/8).
</blockquote></details>

I think we had this outside macros too...

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/593)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/593#-NXejvTZ7LJB5abU5mPe:-NXeqraH9YpYdARBogux:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d4e5269f816623a603b876e4df280e3d443029c0/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we had this outside macros too...
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/593)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 498 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/593#-NXejvTZ7LJB5abU5mPe:-NXewOLv-TuGFSW82t1G:b-gz1kkr) ([raw file](https://github.com/starkware-libs/blockifier/blob/d4e5269f816623a603b876e4df280e3d443029c0/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L498)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fixed the formatter?

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/593#-:-NXez7fd9TEvdrdULvPT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
