### PR TITLE
pass state_changes_count directly to functions instead of state

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/794)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/794#-:-NaGJCHeAasH4ww5OP0r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 529 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/794#-NaGIwhe1nlp6gWGBCou:-NaGIwhe1nlp6gWGBCov:bs66dwk) ([raw file](https://github.com/starkware-libs/blockifier/blob/c57e512e215dc21e903d8ab8c764a94d5758d041/crates/blockifier/src/transaction/account_transaction.rs#L529)):*
> ```XML
>         let state_changes_count = StateChangesCount::from(&state_changes);
>         let (actual_fee, actual_resources) = self.calculate_actual_fee_and_resources(
>             state_changes_count,
> ```

this is what you did below; I like it better



_Suggestion:_
```XML
        let (actual_fee, actual_resources) = self.calculate_actual_fee_and_resources(
            StateChangesCount::from(&state_changes),
```

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/transaction/account_transaction.rs` line 529 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/794#-NaGIwhe1nlp6gWGBCou:-NaGKg5840DGiXnfs-Db:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/c57e512e215dc21e903d8ab8c764a94d5758d041/crates/blockifier/src/transaction/account_transaction.rs#L529)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is what you did below; I like it better
</blockquote></details>

Done

**Review by zuphitf — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/794)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/794)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
