### PR TITLE
refactor(execution, native_blockifier): remove Py objects from Transa…

### PR DESCRIPTION
**Pull request by barak-b-starkware**
…ctionExecutor::new

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1427)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1427)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1427#-NpoyRkG42pVIQPiQv-2:-NpoyRkH7botQ6cSFkUO:bu53w8h) (no related file):*
This collides with #1387, consider redefining Yael's util, in order to avoid conflicts.

___

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1427)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1427#-NprqdX4EPY0raLFO2JP:-NprqdX4EPY0raLFO2JQ:bta0nby) (no related file):*
Python PR?

___

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1427#-:-NpsS2nX3IGc0Z5jR6nE:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1427)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 335 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1427#-Npt8U35CRXBbsngCRrJ:-Npt8U368knWI77e_HIn:b-6jt4oh) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8abfd0b33d26da005d4ddf15635849055c16ae4/crates/native_blockifier/src/py_block_executor.rs#L335)):*
> ```XML
> }
> 
> pub fn into_block_context(
> ```

Why is this deleted?



_Code quote:_
```XML
into_block_context
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1427#-Npt8ddBByrZPXU9VRWE:-Npt8ddBByrZPXU9VRWF:b-j46orv) ([raw file](https://github.com/starkware-libs/blockifier/blob/91d63786e776b5f9cec6b37350fedb9c8de50308/crates/native_blockifier/src/py_state_diff.rs#L167)):*
> ```XML
>             block_timestamp: BlockTimestamp(py_block_info.block_timestamp),
>             sequencer_address: ContractAddress::try_from(py_block_info.sequencer_address.0)?,
>             gas_prices: GasPrices {
> ```

Any chance to make this shorter?
Consider a `for` loop and shortening each iteration.

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1427)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware)

**Pull request closed without merging**
