### PR TITLE
Add initial gas to the execution of an entry point.

### PR DESCRIPTION
**Pull request by noaov1**
Initial gas is the amount of gas allocated to the execution on initiation.
Push this value to the stack when preparing the call arguments.
Based on #515.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmKfXx-9P1q5lEegJz:-NWmKfXx-9P1q5lEegK-:b6mjnx9) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/test_utils.rs#L315)):*
> ```XML
>             AccountTransactionContext::default(),
>         );
>         self.execute(state, &mut context, &constants::INITIAL_GAS_COST.into())
> ```

Import as `abi_constants` everywhere, for consistency.



_Code quote:_
```XML
constants
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWgnDb6-lvKhgxHRFu8:-NWgnDb6-lvKhgxHRFu9:b-y1lqz3) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L375)):*
> ```XML
>         syscall_handler.state,
>         syscall_handler.context,
>         &constants::INITIAL_GAS_COST.into(),
> ```

Give this a name (although it will be very similar to the constant's name). In all places.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmNurp1UQxYs8_1PmY:-NWmNurp1UQxYs8_1PmZ:b-tvflhb) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/test_utils.rs#L315)):*
> ```XML
>             AccountTransactionContext::default(),
>         );
>         self.execute(state, &mut context, &constants::INITIAL_GAS_COST.into())
> ```

Is there a constant c-tor for `Felt252`?



_Code quote:_
```XML
&constants::INITIAL_GAS_COST.into()
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/abi/constants.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmOxmg9d1msO5REqBq:-NWmOxmg9d1msO5REqBr:b-bzp5mw) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/abi/constants.rs#L35)):*
> ```XML
> // See documentation in core/os/constants.cairo.
> pub const STEP_GAS_COST: u64 = 100;
> pub const INITIAL_GAS_COST: u64 = 10_u64.pow(8) * STEP_GAS_COST;
> ```

Please add a short comment that this is a temporary estimation, and this will become a field of the transaction in the future.



_Code quote:_
```XML
pub const INITIAL_GAS_COST: u64 = 10_u64.pow(8) * STEP_GAS_COST;
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmwJ-tDK--DcmE81Go:-NWmwJ-u1E9p14Frjeh_:b-ghqk9) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/test_utils.rs#L315)):*
> ```XML
>             AccountTransactionContext::default(),
>         );
>         self.execute(state, &mut context, &constants::INITIAL_GAS_COST.into())
> ```

I think i'm missing something, i can't find where this is called without INITIAL_GAS_COST as the third arg?



_Code quote:_
```XML
self.execute(state, &mut context, &constants::INITIAL_GAS_COST.into())
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmwJ-tDK--DcmE81Go:-NWn0j8o5Tr-DKjLeZb0:b35tuu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/test_utils.rs#L315)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think i'm missing something, i can't find where this is called without INITIAL_GAS_COST as the third arg?
</blockquote></details>

Oh i see now that it is used in the subsequent PRs without this value, unblocking...

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmKfXx-9P1q5lEegJz:-NWponK521bEIpqnfstU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/test_utils.rs#L315)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Import as `abi_constants` everywhere, for consistency.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmNurp1UQxYs8_1PmY:-NWpqqjM8caC406j6Vqz:bi1i7kc) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/test_utils.rs#L315)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there a constant c-tor for `Felt252`?
</blockquote></details>

No. I can use the crate `once_cell` and define static variables. I.e.
`pub static INITIAL_GAS_COST: Lazy<Felt252> = Lazy::new(|| Felt252::from(10_u64.pow(8) * STEP_GAS_COST));`
___
*[`crates/blockifier/src/abi/constants.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmOxmg9d1msO5REqBq:-NWpuB6x9d2fTC9oJjya:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/abi/constants.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please add a short comment that this is a temporary estimation, and this will become a field of the transaction in the future.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmNurp1UQxYs8_1PmY:-NWq8P3a0D0fe0WPgqCm:b-pra0o7) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/test_utils.rs#L315)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No. I can use the crate `once_cell` and define static variables. I.e.
`pub static INITIAL_GAS_COST: Lazy<Felt252> = Lazy::new(|| Felt252::from(10_u64.pow(8) * STEP_GAS_COST));`
</blockquote></details>

How many of these are left after the last PR in the stack? 
___
*[`crates/blockifier/src/abi/constants.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWq8nsdAZdSWr8OUbl5:-NWq8nsdAZdSWr8OUbl6:b2vuux8) ([raw file](https://github.com/starkware-libs/blockifier/blob/7618358b3e0b0b176c90c898e99e91ff5d0d7c3e/crates/blockifier/src/abi/constants.rs#L43)):*
> ```XML
> pub const ENTRY_POINT_GAS_COST: u64 = ENTRY_POINT_INITIAL_BUDGET + 500 * STEP_GAS_COST;
> // The required gas for each syscall minus the base amount that was pre-charged (by the compiler).
> pub const CALL_CONTRACT_GAS_COST: u64 = 10 * STEP_GAS_COST + ENTRY_POINT_GAS_COST;
> ```

Why do the syscall constants appear in this file? I thought those were constants that are Ethereum-related.
Let's define the purpose of this file and consider splitting it.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmNurp1UQxYs8_1PmY:-NWqBhss7tUUWgp7xwzl:b-fypkxh) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/test_utils.rs#L315)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How many of these are left after the last PR in the stack? 
</blockquote></details>

11 total: all the syscalls + INITIAL_GAS_COST + TRANSACTION_GAS_COST
___
*[`crates/blockifier/src/abi/constants.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWq8nsdAZdSWr8OUbl5:-NWqB3DJ8iSEXpBPQalS:bjrb890) ([raw file](https://github.com/starkware-libs/blockifier/blob/7618358b3e0b0b176c90c898e99e91ff5d0d7c3e/crates/blockifier/src/abi/constants.rs#L43)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why do the syscall constants appear in this file? I thought those were constants that are Ethereum-related.
Let's define the purpose of this file and consider splitting it. 
</blockquote></details>

Good point. Why Ethereum-related? Isn't that the gas in L2 (indirectly derived from L1)?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 5 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWqfJII2esqEIIVdEy6:-NWqfJII2esqEIIVdEy7:b786qkp) ([raw file](https://github.com/starkware-libs/blockifier/blob/7618358b3e0b0b176c90c898e99e91ff5d0d7c3e/crates/blockifier/src/execution/entry_point.rs#L290)):*
> ```XML
>         call_type: CallType::Call,
>     };
>     let initial_gas = abi_constants::INITIAL_GAS_COST.into();
> ```

Should `initial_gas` be a part of `CallEntryPoint`?



_Code quote:_
```XML
initial_gas
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 456 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWqfaP71JGoazwQR_Xo:-NWqfaP886JHAfjzn9bF:btb8d23) ([raw file](https://github.com/starkware-libs/blockifier/blob/7618358b3e0b0b176c90c898e99e91ff5d0d7c3e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L456)):*
> ```XML
>     vm: &mut VirtualMachine,
>     syscall_handler: &mut SyscallHintProcessor<'_>,
> ) -> SyscallResult<ReadOnlySegment> {
> ```

The inner call gas should *eventually* come from the caller current gas. So it makes sense to get it from CallEntryPoint IMO.

(Currently, it's indeed resets on each inner call, unfortunately)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWqfJII2esqEIIVdEy6:-NWqntZkBb9Ue5iB5k-z:b8vvv6k) ([raw file](https://github.com/starkware-libs/blockifier/blob/7618358b3e0b0b176c90c898e99e91ff5d0d7c3e/crates/blockifier/src/execution/entry_point.rs#L290)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Should `initial_gas` be a part of `CallEntryPoint`?
</blockquote></details>

I considered it and decided not to go that way because the `CallInfo` struct contains a field of type `CallEntryPoint` (and we don’t want `initial_gas` to be part of the call info).

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWmNurp1UQxYs8_1PmY:-NWqw5QN0lHDw4ilNcxG:b-ktj80i) ([raw file](https://github.com/starkware-libs/blockifier/blob/629e0ee39a900d75ed75dfdaf62cfb42e77a6950/crates/blockifier/src/test_utils.rs#L315)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

11 total: all the syscalls + INITIAL_GAS_COST + TRANSACTION_GAS_COST
</blockquote></details>

Of passing the _initial_ value (not remaining)?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWqfJII2esqEIIVdEy6:-NX9D9bW2ZZZBm25KIpK:bpiidbu) ([raw file](https://github.com/starkware-libs/blockifier/blob/7618358b3e0b0b176c90c898e99e91ff5d0d7c3e/crates/blockifier/src/execution/entry_point.rs#L290)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I considered it and decided not to go that way because the `CallInfo` struct contains a field of type `CallEntryPoint` (and we don’t want `initial_gas` to be part of the call info).
</blockquote></details>

I still think it makes sense, but whatever you decide.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: 5 of 21 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWqfJII2esqEIIVdEy6:-NX5nS7_0UiUCro8lr2f:b-mokwok) ([raw file](https://github.com/starkware-libs/blockifier/blob/7618358b3e0b0b176c90c898e99e91ff5d0d7c3e/crates/blockifier/src/execution/entry_point.rs#L290)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I still think it makes sense, but whatever you decide.
</blockquote></details>

Added a new struct. WDYT?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 456 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWqfaP71JGoazwQR_Xo:-NX5pr4o6Ioyyy5zZ-Mt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7618358b3e0b0b176c90c898e99e91ff5d0d7c3e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L456)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The inner call gas should *eventually* come from the caller current gas. So it makes sense to get it from CallEntryPoint IMO.

(Currently, it's indeed resets on each inner call, unfortunately)
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 10 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: 15 of 21 files reviewed, 8 unresolved discussions (waiting on @giladchase, @noaov1, and @spapinistarkware)

___
*[`crates/blockifier/src/abi/constants.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NWq8nsdAZdSWr8OUbl5:-NXAMSTL9H01Mwnjd7Gm:bkoaflh) ([raw file](https://github.com/starkware-libs/blockifier/blob/7618358b3e0b0b176c90c898e99e91ff5d0d7c3e/crates/blockifier/src/abi/constants.rs#L43)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Good point. Why Ethereum-related? Isn't that the gas in L2 (indirectly derived from L1)?
</blockquote></details>

Let's revert the "import as `abi_constants` everywhere, and only do that for files with ambiguous usage (sorry for the back and forth). We'll need to reorganize this file. 
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 188 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXAMlnFE7QKI1TfCR70:-NXAMlnFE7QKI1TfCR71:bqg5t8o) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5680e0cf0bfc9b654cb38df1fd23f55c81c598f/crates/blockifier/src/execution/cairo1_execution.rs#L188)):*
> ```XML
>     }
>     // Push gas counter.
>     args.push(CairoArg::Single((&call.initial_gas).into()));
> ```

Why are the parenthesis needed?



_Code quote:_
```XML
(&call.initial_gas)
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXAMx3b2xgnKXOUmJ94:-NXAMx3b2xgnKXOUmJ95:b-9occae) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5680e0cf0bfc9b654cb38df1fd23f55c81c598f/crates/blockifier/src/execution/cairo1_execution.rs#L267)):*
> ```XML
>         &syscall_handler.context.resources.vm_resources - &previous_vm_resources;
>     Ok(CallInfo {
>         call: syscall_handler.call.into(),
> ```

Consider using explicit `::from`.



_Code quote:_
```XML
syscall_handler.call.into()
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 176 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXAMEyj2K8aUh6_Ufar:-NXAMEyj2K8aUh6_Ufas:b-suv37y) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5680e0cf0bfc9b654cb38df1fd23f55c81c598f/crates/blockifier/src/execution/entry_point.rs#L176)):*
> ```XML
> }
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq)]
> ```

Alphabetize.



_Code quote:_
```XML
#[derive(Debug, Clone, Default, Eq, PartialEq)]
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 177 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXALx6F3VqFLPlNrovt:-NXALx6F3VqFLPlNrovu:bxpxezv) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5680e0cf0bfc9b654cb38df1fd23f55c81c598f/crates/blockifier/src/execution/entry_point.rs#L177)):*
> ```XML
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq)]
> pub struct CallEntryPointInfo {
> ```

Refer to the documentation of `CallEntryPoint` instead of repeating it.
Start the docstring with describing that the aim of this class is to be part of the execution output.



_Code quote:_
```XML
CallEntryPointInfo
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXAN8xM-3l23wXJSSfc:-NXAN8xM-3l23wXJSSfd:b-t2g0zl) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5680e0cf0bfc9b654cb38df1fd23f55c81c598f/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L111)):*
> ```XML
>         call_type: CallType::Delegate,
>         ..trivial_external_entry_point()
>     };
> ```

How about `CallInfo::new` receiving `CallEntryPoint`?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXAMx3b2xgnKXOUmJ94:-NXJ9Y2r-0eajzJR5NcZ:bu14km4) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5680e0cf0bfc9b654cb38df1fd23f55c81c598f/crates/blockifier/src/execution/cairo1_execution.rs#L267)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider using explicit `::from`.
</blockquote></details>

For the felts as well, at least in this function.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 204 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXJ9d-w0O9c_wzWrmLN:-NXJ9d-w0O9c_wzWrmLO:bzwi2z) ([raw file](https://github.com/starkware-libs/blockifier/blob/22c7787ca0598660ecde853fbe9392ad99e3cbf0/crates/blockifier/src/execution/entry_point.rs#L204)):*
> ```XML
>     }
> }
> #[derive(Debug, Default, Eq, PartialEq)]
> ```

Restore blank line above?



_Code quote:_
```XML
#[derive(Debug, Default, Eq, PartialEq)]
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXAMx3b2xgnKXOUmJ94:-NXJ9mecAgWKxd-5r_Vl:b-18vaod) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5680e0cf0bfc9b654cb38df1fd23f55c81c598f/crates/blockifier/src/execution/cairo1_execution.rs#L267)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

For the felts as well, at least in this function.
</blockquote></details>

Can be done in the next PR.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 204 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXJ9d-w0O9c_wzWrmLN:-NXJ9qbk6HUzK5W7ujYO:b-18vaod) ([raw file](https://github.com/starkware-libs/blockifier/blob/22c7787ca0598660ecde853fbe9392ad99e3cbf0/crates/blockifier/src/execution/entry_point.rs#L204)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Restore blank line above?
</blockquote></details>

Can be done in the next PR.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545#-:-NXJA5jG1gDPNxQcuvm7:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXJA0pG9a0m-wOm0XhF:-NXJA0pG9a0m-wOm0XhG:btz1m9x) (no related file):*
Please change the comment of this commit and rename the PR.

___

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: 13 of 21 files reviewed, 1 unresolved discussion (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXAMx3b2xgnKXOUmJ94:-NXJz2lH37JBnw6ZZ5EH:b-bfzpo5) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5680e0cf0bfc9b654cb38df1fd23f55c81c598f/crates/blockifier/src/execution/cairo1_execution.rs#L267)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can be done in the next PR.
</blockquote></details>

Which felts are you referring to?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 16 files at r3, 11 of 19 files at r4, 7 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545#-:-NXKEfzv6jWxJLPZ-qtr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 7 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXAMx3b2xgnKXOUmJ94:-NXKHr-900mG5gG7LtUe:baph739) ([raw file](https://github.com/starkware-libs/blockifier/blob/a5680e0cf0bfc9b654cb38df1fd23f55c81c598f/crates/blockifier/src/execution/cairo1_execution.rs#L267)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Which felts are you referring to?
</blockquote></details>

```rust
    // Push gas counter.
    args.push(CairoArg::Single((&call.initial_gas).into()));
    // Push syscall ptr.
    args.push(CairoArg::Single(initial_syscall_ptr.into()));
```

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 12 files at r2, 1 of 16 files at r3, 11 of 19 files at r4, 7 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/545)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
