### PR TITLE
Expose native blockifier error names to python

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/357)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/357)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/errors.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/357#-NRTFkhv1gwx1G-Y7jsN:-NRTFkhv1gwx1G-Y7jsO:b5l02vd) ([raw file](https://github.com/starkware-libs/blockifier/blob/8fb3ee3643562180d54ae05967798012d61b7589/crates/native_blockifier/src/errors.rs#L28)):*
> ```XML
>             vec![$(String::from(stringify!($py_error_name))),*]
>         }
> ```

generated code:
```
    pub fn py_error_names() -> Vec<String> {
        <[_]>::into_vec(
            #[rustc_box]
            ::alloc::boxed::Box::new([
                String::from("PyNativeBlockifierValidationError"),
                String::from("PyPyo3Error"),
                String::from("PySerdeError"),
                String::from("PyStarknetApiError"),
                String::from("PyTransactionExecutionError"),
                String::from("PyStorageError"),
            ]),
        )
    }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/357)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/357#-NT4Y1qZEoL_RTBYXmN1:-NT4Y1qZEoL_RTBYXmN2:byh9vau) (no related file):*
Tested [here](https://reviewable.io/reviews/starkware-industries/starkware/29443)

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/357)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/errors.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/357#-NRTFkhv1gwx1G-Y7jsN:-NT8GCtE9nRVWIpW0I4T:bp60bvw) ([raw file](https://github.com/starkware-libs/blockifier/blob/8fb3ee3643562180d54ae05967798012d61b7589/crates/native_blockifier/src/errors.rs#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

generated code:
```
    pub fn py_error_names() -> Vec<String> {
        <[_]>::into_vec(
            #[rustc_box]
            ::alloc::boxed::Box::new([
                String::from("PyNativeBlockifierValidationError"),
                String::from("PyPyo3Error"),
                String::from("PySerdeError"),
                String::from("PyStarknetApiError"),
                String::from("PyTransactionExecutionError"),
                String::from("PyStorageError"),
            ]),
        )
    }
```
</blockquote></details>

Where do we want to use this? (Python or Rust)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/357)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/357#-NRTFkhv1gwx1G-Y7jsN:-NT8KsJx-8fX84X0A6dg:bqpzdpa) ([raw file](https://github.com/starkware-libs/blockifier/blob/8fb3ee3643562180d54ae05967798012d61b7589/crates/native_blockifier/src/errors.rs#L28)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Where do we want to use this? (Python or Rust)
</blockquote></details>

we only want this for testing purposes; to make sure we never have python code that is missing a blockifier error code

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/357#-:-NT8P5se-wwELMe62k0e:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/errors.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/357#-NRTFkhv1gwx1G-Y7jsN:-NT8OlyODDbfPW953cOt:b-o03vwk) ([raw file](https://github.com/starkware-libs/blockifier/blob/8fb3ee3643562180d54ae05967798012d61b7589/crates/native_blockifier/src/errors.rs#L28)):*
>for testing purposes

Magic word right there.

**Pull request merged**
