### PR TITLE
Split L1 gas computation to function

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1040)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1040)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1040#-Nhf-DjgEEE7BfcVYaqN:-Nhf-DjgEEE7BfcVYaqO:b3ydkb) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f912d4a1f6b1fbe8afadde15e335bc3c6f04711/crates/blockifier/src/fee/fee_utils.rs#L61)):*
> ```XML
>     let (l1_gas_usage, vm_resources) = extract_l1_gas_and_vm_usage(resources);
>     let l1_gas_by_vm_usage = calculate_l1_gas_by_vm_usage(block_context, &vm_resources)?;
>     Ok(l1_gas_usage as u128 + l1_gas_by_vm_usage.ceil() as u128)
> ```

I wonder if changing the timing of the `ceil()` can lead to different results. 
The previous way was identical to the existing python code. 



_Code quote:_
```XML
Ok(l1_gas_usage as u128 + l1_gas_by_vm_usage.ceil() as u128)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1040)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1040#-Nhf-DjgEEE7BfcVYaqN:-Nhf0NdH16WEX72EAwaw:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f912d4a1f6b1fbe8afadde15e335bc3c6f04711/crates/blockifier/src/fee/fee_utils.rs#L61)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if changing the timing of the `ceil()` can lead to different results. 
The previous way was identical to the existing python code.
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1040)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1040#-Nhf11d40Fjc6yO7RyoC:-Nhf11d40Fjc6yO7RyoD:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e1406e29000f81f3ec6e7988c65d6ae4893a012/crates/blockifier/src/fee/fee_utils.rs#L61)):*
> ```XML
>     let (l1_gas_usage, vm_resources) = extract_l1_gas_and_vm_usage(resources);
>     let l1_gas_by_vm_usage = calculate_l1_gas_by_vm_usage(block_context, &vm_resources)?;
>     Ok((l1_gas_usage as f64 + l1_gas_by_vm_usage).ceil() as u128)
> ```

WDYT?



_Suggestion:_
```XML
    let l1_gas_by_vm_usage = calculate_l1_gas_by_vm_usage(block_context, &vm_resources)?;
    let total_l1_gas_usage = l1_gas_usage as f64 + l1_gas_by_vm_usage;

    Ok(total_l1_gas_usage.ceil() as u128)
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1040#-:-Nhf1iS8DgxSqetxwWae:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
