### PR TITLE
Update check_gas_and_fee

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1191)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1191)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1191#-NkUPJ3WB3X65spwSKA1:-NkUPJ3WB3X65spwSKA2:bq8vlwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/473782cbc5e1427e003c0be3fcbe1447956533a9/crates/blockifier/src/transaction/execution_flavors_test.rs#L85)):*
> ```XML
>         calculate_tx_fee(&tx_execution_info.actual_resources, block_context, fee_type).unwrap(),
>         expected_cost_of_resources
>     );
> ```

Maybe add a comment explaining this check?



_Code quote:_
```XML
    assert_eq!(
        calculate_tx_fee(&tx_execution_info.actual_resources, block_context, fee_type).unwrap(),
        expected_cost_of_resources
    );
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 554 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1191#-NkUQ2Hb1_XCjlklmqKs:-NkUQ2Hc33lpuRmZhm0f:b-398ecm) ([raw file](https://github.com/starkware-libs/blockifier/blob/473782cbc5e1427e003c0be3fcbe1447956533a9/crates/blockifier/src/transaction/execution_flavors_test.rs#L554)):*
> ```XML
>         } else {
>             unlimited_fee
>         },
> ```

Can you please remind me why `expected_actual_fee =  just_not_enough_fee_bound` and ` expected_cost_of_resources = get_fee_by_l1_gas_usage(&block_context, revert_gas_usage as u128, &fee_type)`?



_Code quote:_
```XML
        if charge_fee {
            get_fee_by_l1_gas_usage(&block_context, revert_gas_usage as u128, &fee_type)
        } else {
            unlimited_fee
        },
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 612 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1191#-NkUPfDc1GbZ5W0AmfUq:-NkUPfDc1GbZ5W0AmfUr:b-1c2o6h) ([raw file](https://github.com/starkware-libs/blockifier/blob/473782cbc5e1427e003c0be3fcbe1447956533a9/crates/blockifier/src/transaction/execution_flavors_test.rs#L612)):*
> ```XML
>         if charge_fee { fail_actual_gas } else { success_actual_gas },
>         actual_fee,
>         if charge_fee { fail_actual_cost } else { actual_fee },
> ```

Can you please remind me why in case of failure `expected_actual_fee = actual_fee` and ` expected_cost_of_resources = fail_actual_cost`?



_Code quote:_
```XML
        if charge_fee { fail_actual_cost } else { actual_fee },
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1191)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1191#-NkUPJ3WB3X65spwSKA1:-NkU_-Pe3CA455SjWMuw:b6tvwfu) ([raw file](https://github.com/starkware-libs/blockifier/blob/473782cbc5e1427e003c0be3fcbe1447956533a9/crates/blockifier/src/transaction/execution_flavors_test.rs#L85)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe add a comment explaining this check?
</blockquote></details>

Done (moved docstring down).
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 554 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1191#-NkUQ2Hb1_XCjlklmqKs:-NkUa0yZ3D51WMuRg75G:brs350k) ([raw file](https://github.com/starkware-libs/blockifier/blob/473782cbc5e1427e003c0be3fcbe1447956533a9/crates/blockifier/src/transaction/execution_flavors_test.rs#L554)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please remind me why `expected_actual_fee =  just_not_enough_fee_bound` and ` expected_cost_of_resources = get_fee_by_l1_gas_usage(&block_context, revert_gas_usage as u128, &fee_type)`?
</blockquote></details>

because after we revert
1. we take fee = sender bounds
2. we report resources = validate + revert steps (which costs slightly less than sender bounds)
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 612 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1191#-NkUPfDc1GbZ5W0AmfUq:-NkUcTLQA6wRLp_ZkxF0:bgowi9y) ([raw file](https://github.com/starkware-libs/blockifier/blob/473782cbc5e1427e003c0be3fcbe1447956533a9/crates/blockifier/src/transaction/execution_flavors_test.rs#L612)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please remind me why in case of failure `expected_actual_fee = actual_fee` and ` expected_cost_of_resources = fail_actual_cost`?
</blockquote></details>

If we fail due to insufficient balance, then we know (due to how post-execution checks work) that *pre-execute* the sender *had enough balance* to cover *the actual fee post-execute*.
So, we always charge actual fee on this revert case.
actual cost of resources depends on resources - and the cost of validate + reverted steps may be less than the actual fee, so we need the fail_actual_cost

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1191)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1191#-NkVcvWV5PZh5cNIrvl6:-NkVicZ44MAUlQvnNPjn:bsln2dd) ([raw file](https://github.com/starkware-libs/blockifier/blob/b1d9df9e34feb8a7ccaf77f848e6359fbb69e12b/crates/blockifier/src/transaction/execution_flavors_test.rs#L81)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

`calculate_tx_fee = get_fee_by_l1_gas_usage(block_context, calculate_tx_l1_gas_usage(resources, block_context)?, fee_type)`
So the main reason is that in the future we may derive the fee from resources other than `l1_gas_usage`, no?
</blockquote></details>

no; this function is not aware of the relation between fee and l1 gas reported in actual resources.
this is for cases like post-execution overdraft errors.
in these cases, `expected_actual_fee` will actually be different than `expected_cost_of_resources`.
in the future, yeah, there could be more reasons the fee isn't derived exactly from resources.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1191)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1191#-NkVcvWV5PZh5cNIrvl6:-NkihUAs0ngu31MCY90G:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b1d9df9e34feb8a7ccaf77f848e6359fbb69e12b/crates/blockifier/src/transaction/execution_flavors_test.rs#L81)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I don't refer to the `expected_actual_fee`, only to ` expected_actual_gas` and `expected_cost_of_resources`. Given the current implementation of `calculate_tx_fee`, I think it's not necessary to check the `expected_cost_of_resources` because it's derived from ` expected_actual_gas`. Hence, the future comment.
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1191#-:-NkiicXcCDm1WpJMwljG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
