### PR TITLE
Get txs from python.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/264)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/264)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNgB4qw7rgEKkiXTHIh:-NNgB4qw7rgEKkiXTHIi:bxbkskt) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f29c0a729b668d9ed1cb32a8b904209395aaaa/crates/native_blockifier/src/py_transaction.rs#L47)):*
> ```XML
>         nonce: Nonce(py_felt_attr(tx, "nonce")?),
>         sender_address: ContractAddress(
>             PatriciaKey::try_from(py_felt_attr(tx, "sender_address")?).unwrap(),
> ```

Delete `unwrap`s throughout this file.



_Code quote:_
```XML
unwrap()
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNgA_lHA1fIweVQOjIT:-NNgA_lHA1fIweVQOjIU:b-yr1vqq) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f29c0a729b668d9ed1cb32a8b904209395aaaa/crates/native_blockifier/src/py_transaction.rs#L53)):*
> ```XML
>     })
> }
> ```

Let's move declare and deploy before invoke for it to be alphabetized. Also in the `match` below.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNgArTI-0kNzaRdyUGI:-NNgArTI-0kNzaRdyUGJ:bq98lp1) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f29c0a729b668d9ed1cb32a8b904209395aaaa/crates/native_blockifier/src/py_transaction.rs#L53)):*
> ```XML
>     })
> }
> ```

Consider reusing code for building `AccountDataContext` object and taking fields from it to the transaction.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNgBD7r43nID0w9g9bj:-NNgBD7r43nID0w9g9bk:by3syq3) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f29c0a729b668d9ed1cb32a8b904209395aaaa/crates/native_blockifier/src/py_transaction.rs#L63)):*
> ```XML
>         class_hash: ClassHash(py_felt_attr(tx, "class_hash")?),
>         sender_address: ContractAddress(
>             PatriciaKey::try_from(py_felt_attr(tx, "sender_address")?).unwrap(),
> ```

No shorter way to build an address from `StarkFelt`?



_Code quote:_
```XML
        sender_address: ContractAddress(
            PatriciaKey::try_from(py_felt_attr(tx, "sender_address")?).unwrap(),
        ),
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/264)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNgB4qw7rgEKkiXTHIh:-NNkCfT-B4qR5ueDDsUc:b-ucfkn4) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f29c0a729b668d9ed1cb32a8b904209395aaaa/crates/native_blockifier/src/py_transaction.rs#L47)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Delete `unwrap`s throughout this file.
</blockquote></details>

Thanks.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNgA_lHA1fIweVQOjIT:-NNkCv7o4f8lG-UcZLih:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f29c0a729b668d9ed1cb32a8b904209395aaaa/crates/native_blockifier/src/py_transaction.rs#L53)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's move declare and deploy before invoke for it to be alphabetized. Also in the `match` below.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNgArTI-0kNzaRdyUGI:-NNkG8lB73x9j44X80Qm:b-r0wp3v) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f29c0a729b668d9ed1cb32a8b904209395aaaa/crates/native_blockifier/src/py_transaction.rs#L53)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider reusing code for building `AccountDataContext` object and taking fields from it to the transaction.
</blockquote></details>

Good idea. Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNgBD7r43nID0w9g9bj:-NNkDQ8r1ZYqW4gmLkfW:b15k75j) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f29c0a729b668d9ed1cb32a8b904209395aaaa/crates/native_blockifier/src/py_transaction.rs#L63)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No shorter way to build an address from `StarkFelt`?
</blockquote></details>

Actually, there is, thanks.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/264)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNlaQQM73L4NC0nuA7e:-NNlaQQM73L4NC0nuA7f:bbzo81d) ([raw file](https://github.com/starkware-libs/blockifier/blob/e17d7f009c91844499f0ac2539bc85fabb40a68b/crates/native_blockifier/src/py_transaction.rs#L20)):*
> ```XML
> /// Common fields used in all account transactions.
> #[derive(Debug)]
> pub struct AccountDataContext {
> ```

Can we use the existing struct?
https://github.com/starkware-libs/blockifier-old/blob/8c968410c771e5dc350200d0bc48fe859ce27835/crates/blockifier/src/transaction/objects.rs#L13



_Code quote:_
```XML
AccountDataContext
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNlag-l3tgJFtX7hFY_:-NNlag-l3tgJFtX7hFYa:b-404hmf) ([raw file](https://github.com/starkware-libs/blockifier/blob/e17d7f009c91844499f0ac2539bc85fabb40a68b/crates/native_blockifier/src/py_transaction.rs#L42)):*
> ```XML
>     raw_felts.into_iter().map(biguint_to_felt).collect()
> }
> ```

Let's go with either `py_` or `_from_python` addition to all method names (I think I prefer the first).
___
*[`crates/native_blockifier/src/py_transaction.rs` line 81 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNlb9Ff0YBZLC_8Vjng:-NNlb9Ff0YBZLC_8Vjnh:bqluv3w) ([raw file](https://github.com/starkware-libs/blockifier/blob/e17d7f009c91844499f0ac2539bc85fabb40a68b/crates/native_blockifier/src/py_transaction.rs#L81)):*
> ```XML
>         contract_address_salt: ContractAddressSalt(py_felt_attr(tx, "contract_address_salt")?),
>         constructor_calldata: Calldata(Arc::from(py_felt_sequence_attr(
>             tx,
> ```

Please reuse this code, it repeats three times (although short).



_Code quote:_
```XML
        constructor_calldata: Calldata(Arc::from(py_felt_sequence_attr(
            tx,
            "constructor_calldata",
        )?)),
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/264)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/264#-NNlaQQM73L4NC0nuA7e:-NNpIVNr07Wjkd56sa-w:bh1bfop) ([raw file](https://github.com/starkware-libs/blockifier/blob/e17d7f009c91844499f0ac2539bc85fabb40a68b/crates/native_blockifier/src/py_transaction.rs#L20)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we use the existing struct?
https://github.com/starkware-libs/blockifier-old/blob/8c968410c771e5dc350200d0bc48fe859ce27835/crates/blockifier/src/transaction/objects.rs#L13
</blockquote></details>

Oh yeah, I didn't realize there was one.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/264#-:-NNpi3TEDBqvN6IU2p0Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
