### PR TITLE
refactor(fee): removed bouncer resources field from tx execution info

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r3, 14 of 17 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: all files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtV_o_L-4PYvQG9PcUU:-NtV_o_L-4PYvQG9PcUV:b2dnrp7) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/blockifier/transaction_executor.rs#L127)):*
> ```XML
>                     additional_os_resources,
>                     state_diff_size,
>                     tx_execution_summary.n_events,
> ```

are these the same numbers we have in `tx_execution_info.actual_resources.starknet_resources`?
1. if so, use them instead of the computations above
2. if not, why not? what is different about this computation here?



_Code quote:_
```XML
                    state_diff_size,
                    tx_execution_summary.n_events,
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeWEc-f3yGeL76SON:-NtVeWEc-f3yGeL76SOO:b36c00e) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/blockifier/transaction_executor.rs#L108)):*
> ```XML
>                     &self.visited_storage_entries,
>                     &tx_execution_summary.visited_storage_entries,
>                 )?;
> ```

what is this?
is it something we don't charge for, but we still need the bouncer to know about?
these look like resource-related computations, and they should be part of the resources objects area IMO;
do we not have access to `executed_class_hashes` and `visited_storage_entries` when constructing a `StarknetResources` object?



_Code quote:_
```XML
                // Count additional OS resources.
                let mut additional_os_resources = get_casm_hash_calculation_resources(
                    &mut transactional_state,
                    &self.executed_class_hashes,
                    &tx_execution_summary.executed_class_hashes,
                )?;
                additional_os_resources += &get_particia_update_resources(
                    &self.visited_storage_entries,
                    &tx_execution_summary.visited_storage_entries,
                )?;
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 46 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVcO381LrYBrZ5D54L:-NtVcO381LrYBrZ5D54M:b-rqptci) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/fee/fee_test.rs#L46)):*
> ```XML
>     let mut vm_resource_usage = get_vm_resource_usage();
>     let n_reverted_steps = 15;
>     // Positive flow.
> ```

restore the newline



_Suggestion:_
```XML
    let n_reverted_steps = 15;
    
    // Positive flow.
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVcXNa5nUo8DbPUV1J:-NtVcXNa5nUo8DbPUV1K:bb7phvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/fee/fee_test.rs#L95)):*
> ```XML
>     // Positive flow.
>     // Verify calculation - in our case, n_steps is the heaviest resource.
>     let n_revrted_steps = 300;
> ```

typo



_Suggestion:_
```XML
n_reverted_steps
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 624 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVcnqvEGNQFyybq95a:-NtVcnqvEGNQFyybq95b:beb7sf8) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/transaction/account_transactions_test.rs#L624)):*
> ```XML
>     .unwrap();
>     let n_steps_0 =
>         result.actual_resources.vm_resources.n_steps + result.actual_resources.n_reverted_steps;
> ```

please add a `total_charged_steps(&self) -> usize` method on `TransactionResources` that returns this sum and use it here (everywhere)



_Code quote:_
```XML
result.actual_resources.vm_resources.n_steps + result.actual_resources.n_reverted_steps;
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 215 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVdENk2KC_3nQEsoCz:-NtVdENk2KC_3nQEsoD-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/transaction/objects.rs#L215)):*
> ```XML
>     pub actual_resources: TransactionResources,
>     /// Error string for reverted transactions; [None] if transaction execution was successful.
>     /// If not None, contains the resources to account for in the bouncer.
> ```


___
*[`crates/blockifier/src/transaction/objects.rs` line 465 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeBbQ6qOKPloLdtoE:-NtVeBbQ6qOKPloLdtoF:b17e5ev) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/transaction/objects.rs#L465)):*
> ```XML
>             &self.starknet_resources.message_cost_info.l2_to_l1_payload_lengths,
>             self.starknet_resources.l1_handler_payload_size,
>         );
> ```

seems to me that `calculate_message_l1_resources` should be a method of `StarknetResources`, WDYT?
also, I am not sure I understand the computation being done - is it not somehow equivalent to the logic in `set_events_and_messages_resources`? 



_Code quote:_
```XML
        let (message_segment_length, gas_usage) = calculate_message_l1_resources(
            &self.starknet_resources.message_cost_info.l2_to_l1_payload_lengths,
            self.starknet_resources.l1_handler_payload_size,
        );
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtV_o_L-4PYvQG9PcUU:-NtVlZkN8Ouzmvx-V0NG:bwylaio) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/blockifier/transaction_executor.rs#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

are these the same numbers we have in `tx_execution_info.actual_resources.starknet_resources`?
1. if so, use them instead of the computations above
2. if not, why not? what is different about this computation here?
</blockquote></details>

when we set events resources we sum event's keys length and data length. (we don't keep how many events were- the cost is not determined that way)
`state_diff_size` is different for a reason i dont know. (it holds that `tx_execution_info.actual_resources.starknet_resources !=  tx_unique_state_changes_keys`)
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeWEc-f3yGeL76SON:-NtWG35M1nPEEsxGqmRP:b6jbr7y) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/blockifier/transaction_executor.rs#L108)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what is this?
is it something we don't charge for, but we still need the bouncer to know about?
these look like resource-related computations, and they should be part of the resources objects area IMO;
do we not have access to `executed_class_hashes` and `visited_storage_entries` when constructing a `StarknetResources` object?
</blockquote></details>

If i understand correctly these resources are an estimation of additional resources to update the starknet state Patricia trees and we do charge for these resources.
(I'm not confident about that)
I think we don't have access to those objects..
___
*[`crates/blockifier/src/fee/fee_test.rs` line 46 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVcO381LrYBrZ5D54L:-NtVmuUS0qABWieNUG0T:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/fee/fee_test.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

restore the newline
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 624 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVcnqvEGNQFyybq95a:-NtW6EkM9SSZzWZVcEm_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/transaction/account_transactions_test.rs#L624)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a `total_charged_steps(&self) -> usize` method on `TransactionResources` that returns this sum and use it here (everywhere)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 215 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVdENk2KC_3nQEsoCz:-NtVnPGq2fRBHoYJSfk7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/transaction/objects.rs#L215)):*
> ```XML
>     pub actual_resources: TransactionResources,
>     /// Error string for reverted transactions; [None] if transaction execution was successful.
>     /// If not None, contains the resources to account for in the bouncer.
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtV_o_L-4PYvQG9PcUU:-NtWXQe3CESjfxUt-Moz:b-m45wdz) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/blockifier/transaction_executor.rs#L127)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

when we set events resources we sum event's keys length and data length. (we don't keep how many events were- the cost is not determined that way)
`state_diff_size` is different for a reason i dont know. (it holds that `tx_execution_info.actual_resources.starknet_resources !=  tx_unique_state_changes_keys`)
</blockquote></details>

1. if the number of events is needed for the bouncer, I think it should be added to StarknetResources
2. need to find out why there is this difference in the state diff...
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeWEc-f3yGeL76SON:-NtWSs8nCU0LBRbsg3DP:b-o24wj7) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/blockifier/transaction_executor.rs#L108)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

If i understand correctly these resources are an estimation of additional resources to update the starknet state Patricia trees and we do charge for these resources.
(I'm not confident about that)
I think we don't have access to those objects..
</blockquote></details>

if we are charged for them, then they should appear in TransactionResources::to_gas_vector... right? otherwise, how would the fee be computed?
something is fishy about this, either we don't charge for them (but we should still track this in StarknetResources), or we do, in which case there may be a bug somewhere.
In any case I see no reason why this info shouldn't be in StarknetResources, it is literally a resource consumed as part of the Starknet state update.
@noaov1 or @Yoni-Starkware ?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeWEc-f3yGeL76SON:-NtWiImY5IWF2UrFYdZU:bdbagya) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/blockifier/transaction_executor.rs#L108)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if we are charged for them, then they should appear in TransactionResources::to_gas_vector... right? otherwise, how would the fee be computed?
something is fishy about this, either we don't charge for them (but we should still track this in StarknetResources), or we do, in which case there may be a bug somewhere.
In any case I see no reason why this info shouldn't be in StarknetResources, it is literally a resource consumed as part of the Starknet state update.
@noaov1 or @Yoni-Starkware ?
</blockquote></details>

We don't charge for them.
We need a refund mechanism before we do.
Anyway it's okay

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeWEc-f3yGeL76SON:-NtjZo0529Hld2UXSe9B:b-oergsa) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/blockifier/transaction_executor.rs#L108)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We don't charge for them.
We need a refund mechanism before we do.
Anyway it's okay
</blockquote></details>

@Yoni-Starkware if we intend to charge for this one day then I still think it's an issue that this resource computation is here and not part of the resources objects.
@nimrod-starkware please add a TODO here to move this computation to some resource-tracking object (StarknetResources, TransactionResources...) and I'll unblock
___
*[`crates/blockifier/src/transaction/objects.rs` line 465 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeBbQ6qOKPloLdtoE:-NtjZbTZ24lEygCM4-UR:b-3icgnl) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/transaction/objects.rs#L465)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(The bouncer only cares about the messages gas. The full gas us not relevant for it)
</blockquote></details>

This should still be a method of StarknetResources.
Both inputs to this function come from `self.starknet_resources`, this should just be `self.starknet_resources.calculate_message_l1_resources()`

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtV_o_L-4PYvQG9PcUU:-Ntk-bjS9g2xmgzutlMc:b-yteoe5) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/blockifier/transaction_executor.rs#L127)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We charge for each storage change of the tx (relative to the previous tx), but the bouncer counts for changes relative to the previous state. I.e., the bouncer's set is a subset of the tx receipt's
</blockquote></details>

1. Done
2. So i assume it can't be part of starknet resources (it needs some extra context)
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeWEc-f3yGeL76SON:-Ntjfiz-E2Pnq2eR8dXT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/blockifier/transaction_executor.rs#L108)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware if we intend to charge for this one day then I still think it's an issue that this resource computation is here and not part of the resources objects.
@nimrod-starkware please add a TODO here to move this computation to some resource-tracking object (StarknetResources, TransactionResources...) and I'll unblock
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 465 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeBbQ6qOKPloLdtoE:-NtkOZzZ5agdK9wcZ-qO:b8q568d) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/transaction/objects.rs#L465)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This should still be a method of StarknetResources.
Both inputs to this function come from `self.starknet_resources`, this should just be `self.starknet_resources.calculate_message_l1_resources()`
</blockquote></details>

It seems it might be a duplicate of `starknet_resources.get_messages_cost`... although the logic is different. (one takes into account SHARP cost and the other doesn't)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtV_o_L-4PYvQG9PcUU:-NtkjR_rE7dOV1uBtK3H:b59vwz7) ([raw file](https://github.com/starkware-libs/blockifier/blob/324a9337280f66ac95e7fe2f9bc913b7eb919b88/crates/blockifier/src/blockifier/transaction_executor.rs#L127)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

1. Done
2. So i assume it can't be part of starknet resources (it needs some extra context)
</blockquote></details>

2. Yes, although maybe we should consider adding a `TransactionInBlockResource` struct with a `TransactionResources` field (which should maybe be renamed to `TransactionExecutionResources`) and additional field(s) for this kind of stuff. Out of scope, anyway
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 100 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtkjKD_-FORFRsZv0i6:-NtkjKD_-FORFRsZv0i7:bb7phvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/4257bca1e9034081d64a2b3350bfc2e7e9e8e56b/crates/blockifier/src/blockifier/transaction_executor.rs#L100)):*
> ```XML
> 
>                 // Count additional OS resources.
>                 // TODO(Nimrod, 1/5/2024): Move this computaion to TransactionResources.
> ```

typo



_Suggestion:_
```XML
computation
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 465 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeBbQ6qOKPloLdtoE:-NtkkT1O7W-4Lq-Nkxnp:b-566y1m) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/transaction/objects.rs#L465)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

It seems it might be a duplicate of `starknet_resources.get_messages_cost`... although the logic is different. (one takes into account SHARP cost and the other doesn't)
</blockquote></details>

IIUC, `get_messages_cost` computes the L1-message-related resources we charge the user for, and `calculate_message_l1_resources` is the L1 gas cost of the updateState operation stemming from L1-to-L2 message? @Yoni-Starkware 
Regardless, this still should be a method of SN resources, just the name is debatable (so the difference between `get_messages_cost` and `calculate_message_l1_resources` is clearer).
Either add a TODO or move to a method, either way I'll unblock
___
*[`crates/blockifier/src/transaction/objects.rs` line 484 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtkjybG3XaRdIgsmdfg:-NtkjybG3XaRdIgsmdfh:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/4257bca1e9034081d64a2b3350bfc2e7e9e8e56b/crates/blockifier/src/transaction/objects.rs#L484)):*
> ```XML
>         // );
>         // let gas_usage = usize_from_u128(self.starknet_resources.get_messages_cost().l1_gas)
>         //     .expect("This conversion should not fail as the value is a converted usize.");
> ```

delete



_Code quote:_
```XML
        // let message_segment_length = get_message_segment_length(
        //     &self.starknet_resources.message_cost_info.l2_to_l1_payload_lengths,
        //     self.starknet_resources.l1_handler_payload_size,
        // );
        // let gas_usage = usize_from_u128(self.starknet_resources.get_messages_cost().l1_gas)
        //     .expect("This conversion should not fail as the value is a converted usize.");
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 465 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtVeBbQ6qOKPloLdtoE:-Ntkr7ikDZYnvxY9w89M:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4efc0c046b4accb46012d18c1a590f73bd95c2/crates/blockifier/src/transaction/objects.rs#L465)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IIUC, `get_messages_cost` computes the L1-message-related resources we charge the user for, and `calculate_message_l1_resources` is the L1 gas cost of the updateState operation stemming from L1-to-L2 message? @Yoni-Starkware 
Regardless, this still should be a method of SN resources, just the name is debatable (so the difference between `get_messages_cost` and `calculate_message_l1_resources` is clearer).
Either add a TODO or move to a method, either way I'll unblock
</blockquote></details>

Done.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 484 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-NtkjybG3XaRdIgsmdfg:-NtkssHpAjhbOgBwTLci:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4257bca1e9034081d64a2b3350bfc2e7e9e8e56b/crates/blockifier/src/transaction/objects.rs#L484)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 402 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-Ntkvm6O06-VO9fcZWBT:-Ntkvm6O06-VO9fcZWBU:b2ykoga) ([raw file](https://github.com/starkware-libs/blockifier/blob/addaaf7c476d7850bc2426f24e5e439698e0ee60/crates/blockifier/src/transaction/objects.rs#L402)):*
> ```XML
>     }
> 
>     // TODO(Nimrod, 1/5/2024): Change function's name when it's purpose is clearer.
> ```

the purpose is clear (if I misunderstood the purpose then lol); the name is not :).
Also, when you return an unnamed data structure (like `(usize, usize)`), it's important to document what the return value is.



_Suggestion:_
```XML
/// Computes the message segment length and L1 gas usage of L1->L2 messages
/// when they are posted onchain.
// TODO(Nimrod, 1/5/2024): Find a better name for this function.
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 402 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-Ntkvm6O06-VO9fcZWBT:-Ntkxvsh69p0DwtolGVQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/addaaf7c476d7850bc2426f24e5e439698e0ee60/crates/blockifier/src/transaction/objects.rs#L402)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the purpose is clear (if I misunderstood the purpose then lol); the name is not :).
Also, when you return an unnamed data structure (like `(usize, usize)`), it's important to document what the return value is.
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1696#-:-NtlEfXHBV5nshAuDF22:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
