### PR TITLE
Add mid-execution cartesian tests

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1168)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1168)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 294 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkAy01rBRWh6JQ5i5rw:-NkAy01rBRWh6JQ5i5rx:b-gu6q7r) ([raw file](https://github.com/starkware-libs/blockifier/blob/833ab2fcc20887aff954a28e85d8f65f0b57e46c/crates/blockifier/src/transaction/execution_flavors_test.rs#L294)):*
> ```XML
>             }
>         };
>     }
> ```

next PR moves this into a function



_Code quote:_
```XML
    macro_rules! check_balance {
        () => {
            let old_balance = current_balance;
            let (current_balance, _) = state
                .get_fee_token_balance(
                    &account_address,
                    &block_context.fee_token_address(&fee_type),
                )
                .unwrap();
            if charge_fee {
                assert!(old_balance > current_balance);
            } else {
                assert_eq!(old_balance, current_balance);
            }
        };
    }
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1168)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 332 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkB9Co9EkGW3Uy8yTUG:-NkB9Co9EkGW3Uy8yTUH:b-n92fj1) ([raw file](https://github.com/starkware-libs/blockifier/blob/833ab2fcc20887aff954a28e85d8f65f0b57e46c/crates/blockifier/src/transaction/execution_flavors_test.rs#L332)):*
> ```XML
>     // If `charge_fee` is false, we don't limit the execution resources by user's resource bounds.
>     // Thus, the actual consumed resources may be greater in the `charge_fee` case (and may be
>     // greater than the upper bounds in any case).
> ```

Can you please explain this sentence?



_Code quote:_
```XML
    // Thus, the actual consumed resources may be greater in the `charge_fee` case (and may be
    // greater than the upper bounds in any case).
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkB90CE-8tLIElzvdVc:-NkB90CE-8tLIElzvdVd:b-azsyxg) ([raw file](https://github.com/starkware-libs/blockifier/blob/833ab2fcc20887aff954a28e85d8f65f0b57e46c/crates/blockifier/src/transaction/execution_flavors_test.rs#L353)):*
> ```XML
>         &tx_execution_info,
>         if charge_fee { limited_gas_used } else { unlimited_gas_used },
>         if charge_fee { fee_bound } else { unlimited_fee },
> ```

Can you please add a comment describing why it's `fee_bounds` and not `limited_fee`?



_Code quote:_
```XML
        if charge_fee { fee_bound } else { unlimited_fee },
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 387 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkBC-Nr02dLXKuSCbgT:-NkBC-Nr02dLXKuSCbgU:bwdotzj) ([raw file](https://github.com/starkware-libs/blockifier/blob/833ab2fcc20887aff954a28e85d8f65f0b57e46c/crates/blockifier/src/transaction/execution_flavors_test.rs#L387)):*
> ```XML
>     check_gas_and_fee(&block_context, &tx_execution_info, block_limit_gas, block_limit_fee);
>     // Complete resources used are reported as actual_resources; but only the charged final fee is
>     // shown in actual_fee.
> ```

WDYM in the second sentence? :)



_Code quote:_
```XML
    // Complete resources used are reported as actual_resources; but only the charged final fee is
    // shown in actual_fee.
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1168)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 332 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkB9Co9EkGW3Uy8yTUG:-NkBZUeLCR5uZgbMmw1t:b-3r1z0e) ([raw file](https://github.com/starkware-libs/blockifier/blob/833ab2fcc20887aff954a28e85d8f65f0b57e46c/crates/blockifier/src/transaction/execution_flavors_test.rs#L332)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

If charge_fee is false, we ignore resource limits, and when the tx is complete, we report actual resources consumed, which may be greater than the resource bounds
</blockquote></details>

WDYM by the `charge_fee` case? WDYM by "any case"?
Can you please rephrase? :)
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 387 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkBC-Nr02dLXKuSCbgT:-NkGMMMqByBk3AX1OGr8:b-keg8wy) ([raw file](https://github.com/starkware-libs/blockifier/blob/833ab2fcc20887aff954a28e85d8f65f0b57e46c/crates/blockifier/src/transaction/execution_flavors_test.rs#L387)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

that `actual_fee` is not necessarily equal to `calculate_fee(actual_resources)`.
Fleshed out the inline comment, better?
</blockquote></details>

When wouldn't it be the case? Only in case of post execution error?
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 356 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkFwc-X8dZnzuR-no-p:-NkFwc-X8dZnzuR-no-q:btxi76p) ([raw file](https://github.com/starkware-libs/blockifier/blob/677df8ac6125c47f9c7b4180440513dc9ffd12f9/crates/blockifier/src/transaction/execution_flavors_test.rs#L356)):*
> ```XML
>         // This is because the resource limit - enforced during execution - is an estimate.
>         // Execution is stopped when the limit is overstepped, but an estimation error means actual
>         // gas used may exceed the resource bounds.
> ```

Or something similar.



_Suggestion:_
```XML
        // In case `charge_fee = false` we completely ignore the sender bounds when executiong the transaction.
        // If `charge_fee` is true, we limit the transaction steps according to the sender boundes.
        // However, there are other resources that consumes gas (e.g. L1 data availability), hence the actual resources
        // may exceed the senders bounds after all.
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1168)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 387 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkBC-Nr02dLXKuSCbgT:-NkGW2KCAwqJrd-8p9ty:bw80pgf) ([raw file](https://github.com/starkware-libs/blockifier/blob/833ab2fcc20887aff954a28e85d8f65f0b57e46c/crates/blockifier/src/transaction/execution_flavors_test.rs#L387)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

or mid-execution error, because even after hitting mid-execution error we still may exceed the max_fee and charge less than what the resources cost. Right?
</blockquote></details>

So it's a post execution error :) (which raised after we executed part of the transaction)
I am not sure I understand this comment. 
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 331 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkGVPDh7jf_O33yEsKA:-NkGVPDh7jf_O33yEsKB:b-oz1o55) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7a744abe9bd431226d426cb87b58d942ed1999a/crates/blockifier/src/transaction/execution_flavors_test.rs#L331)):*
> ```XML
>     // is derived from sender bounds (`charge_fee` mode).
>     // If `charge_fee` is false, we don't limit the execution resources by user's resource bounds.
>     // Thus, the actual consumed resources may be greater in the `charge_fee=false` case (and may be
> ```

greater then what?



_Code quote:_
```XML
 // Thus, the actual consumed resources may be greater in the `charge_fee=false` case (and may be
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 333 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkGVbAz2LHGlyiq6LJt:-NkGVbAz2LHGlyiq6LJu:b-qke0j4) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7a744abe9bd431226d426cb87b58d942ed1999a/crates/blockifier/src/transaction/execution_flavors_test.rs#L333)):*
> ```XML
>     // Thus, the actual consumed resources may be greater in the `charge_fee=false` case (and may be
>     // greater than the upper bounds regardless of the value of `charge_fee`, as the execution step
>     // limit derived from the resource bounds is not tight).
> ```

Is it relevant here?



_Code quote:_
```XML
    // greater than the upper bounds regardless of the value of `charge_fee`, as the execution step
    // limit derived from the resource bounds is not tight).
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1168)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 387 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkBC-Nr02dLXKuSCbgT:-NkGgGRW-JX7pPrxaygS:bvpplgs) ([raw file](https://github.com/starkware-libs/blockifier/blob/833ab2fcc20887aff954a28e85d8f65f0b57e46c/crates/blockifier/src/transaction/execution_flavors_test.rs#L387)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

So it's a post execution error :) (which raised after we executed part of the transaction)
I am not sure I understand this comment.
</blockquote></details>

Yes, I only expect a difference in post-execution. Since the three flags tested can have strange and unexpected effects on fee and resource computation, I feel this check (that fee is exactly derived from resources) is worth it
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 333 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkGVbAz2LHGlyiq6LJt:-NkGg0RSESpr_xmzwR5S:b-fgb7wm) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7a744abe9bd431226d426cb87b58d942ed1999a/crates/blockifier/src/transaction/execution_flavors_test.rs#L333)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it relevant here?
</blockquote></details>

IMO yes. I remark that if charge_fee=false we would exceed resource bounds; if I don't add this remark, one would be led to believe that if charge_fee=true, the resources will be *less* than the bounds

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1168)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 333 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkGVbAz2LHGlyiq6LJt:-NkK8CNw69reG-xlp85F:b-zc37o9) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7a744abe9bd431226d426cb87b58d942ed1999a/crates/blockifier/src/transaction/execution_flavors_test.rs#L333)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IMO yes. I remark that if charge_fee=false we would exceed resource bounds; if I don't add this remark, one would be led to believe that if charge_fee=true, the resources will be *less* than the bounds
</blockquote></details>

You write it below, no?
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 335 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkKC9O551QdYOD-xQ-x:-NkKC9O551QdYOD-xQ-y:b5eupif) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb7f63cd691b58bd1848a4efd4ae33e80c4da428/crates/blockifier/src/transaction/execution_flavors_test.rs#L335)):*
> ```XML
>     // execution step limit derived from the resource bounds is not tight).
>     let (gas_bound, fee_bound) = gas_and_fee(5944, validate);
>     let (limited_gas_used, limited_fee) = gas_and_fee(8392, validate);
> ```

It is just a suggestion. Limited can be confusing (since the limit is not clear from the context).



_Suggestion:_
```XML
  let (actual_limited_gas_used, _) = gas_and_fee(8392, validate);
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1168)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 396 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkKFsd7EnsRxnlGT_aG:-NkKFsd8-zECC_3hYoqJ:b-li3eet) ([raw file](https://github.com/starkware-libs/blockifier/blob/ab2345f6fa6e662c7a5e0a431d4857bfe9408744/crates/blockifier/src/transaction/execution_flavors_test.rs#L396)):*
> ```XML
>             .unwrap(),
>         block_limit_fee
>     );
> ```

I don't think it's needed (you get it from the above check)



_Code quote:_
```XML
    assert_eq!(
        calculate_tx_fee(&tx_execution_info.actual_resources, &low_step_block_context, &fee_type)
            .unwrap(),
        block_limit_fee
    );
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1168)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 396 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1168#-NkKFsd7EnsRxnlGT_aG:-NkKGgI41eEeZMcrsumf:bezb5a5) ([raw file](https://github.com/starkware-libs/blockifier/blob/ab2345f6fa6e662c7a5e0a431d4857bfe9408744/crates/blockifier/src/transaction/execution_flavors_test.rs#L396)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I don't think it's needed (you get it from the above check)
</blockquote></details>

no; `check_gas_and_fee` checks actual_fee and gas from actual_resources.
it *does not* check fee from actual_resources. hence this comment:
```
As a sanity check, verify that the fee derived directly from the
consumed resources is also equal to the expected fee
```

**Pull request merged**
