### PR TITLE
chore!: limit pointer width in both crates

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1527)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1527)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1527#-NqlYhi8E72JCoKtz0Rr:-NqlYhi8E72JCoKtz0Rs:b-edmcp8) (no related file):*
For [this](https://reviewable.io/reviews/starkware-libs/blockifier/1522)

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1527)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1527#-Nquqz8x-sOgqM20iW0n:-Nquqz8yCSXUQtGo3mpd:b9q006m) (no related file):*
Can you explain more?
What pointer are we limiting? What does the code you added mean?

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1527)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1527#-Nquqz8x-sOgqM20iW0n:-NqvEIbQBKDsSSEQ3SbU:b505626) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain more?
What pointer are we limiting? What does the code you added mean?
</blockquote></details>

Basically I am trying to limit `usize` to at most 128 bits (although index range is not the same as pointer length, it [doesn't look like there will be a difference anytime soon](https://github.com/rust-lang/rust/issues/65473)).
The code I added means that the blockifier and native_blockifier libraries will be empty (no `lib.rs`) unless the architecture on which the code is compiled has pointer size in `{16, 32, 64,128}`.

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1527)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1527#-Nquqz8x-sOgqM20iW0n:-NqvOOAx3QyFzvznxVHT:bukaf2u) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Basically I am trying to limit `usize` to at most 128 bits (although index range is not the same as pointer length, it [doesn't look like there will be a difference anytime soon](https://github.com/rust-lang/rust/issues/65473)).
The code I added means that the blockifier and native_blockifier libraries will be empty (no `lib.rs`) unless the architecture on which the code is compiled has pointer size in `{16, 32, 64,128}`.
</blockquote></details>

Please document this for future readers.

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1527)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1527#-Nquqz8x-sOgqM20iW0n:-NqvYgmc2mmtwKa3UFxn:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please document this for future readers.
</blockquote></details>

Done.

___

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1527#-:-NqvbWwWBbDCTy9OPqe2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Pull request merged**
