### PR TITLE
Add PyBlockExecutor to Manage Block-Level Information and Access to storage and execution

### PR DESCRIPTION
**Pull request by giladchase**
This commit refactors the `PyBlockExecutor` to manage all block-level information and control access and initialization/deallocation of both Storage and `TransactionExecutor`. These components are now encapsulated within `PyBlockExecutor` and hidden from Python.

Key changes in py_block_executor.rs include:

- `PyBlockExecutor` now handles the storage and tx_executor APIs, delegating to each respective module. These modules are planned to be submodules of block_executor in future iterations.
- `Storage` is instantiated when the block executor is created and deallocated when the block executor is deallocated.
- `TransactionExecutor` is initialized via `start_block`, which should be invoked when a new block is ready for execution. Conversely, `end_block` is called to deallocate the transaction executor once execution is finalized.
- The `PyBlockInfo`, which is returned from `finalize` back to Python, is the same one that was passed through in `start_block`. This change is due to the Python blockifier instance now being a singleton, rather than being created for each block.
- Moved `PyGeneralConfig` and `PyOsConfig` from the transaction executor
  into the block executor, since it is now in charge of them.

Change in storage.rs:
- The storage is now a pure Rust struct instead of a `pyclass`, as it is encapsulated within `BlockExecutor`.
- The `validate_aligned` function was imported into Python, as Python no longer has direct access to papyrus storage.

Changes in `py_transaction_executor.rs`-> `transaction_executor.rs`:
- The transaction executor is no longer a pyclass and needs to return `PyBlockInfo` from `finalize`.
- `Py{Os,General}Config` have been moved into the block executor.
- `PyBlockInfo` is now used instead of `PyAny`.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/733)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/733)* status: 0 of 12 files reviewed, 1 unresolved discussion

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4EA81Cn9hbLvLX8UH:-N_4EA81Cn9hbLvLX8UI:b206w0e) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d9fbbb620771d4eeb7b129a7ac47c210a946224/crates/native_blockifier/src/py_state_diff.rs#L118)):*
> ```XML
> }
> 
> #[pyclass]
> ```

Possible way of making this nicer: make this into a proper Blockifier struct `BlockInfo`, and make `BlockContext` have have a `BlockInfo` instance as a member.
Pros: Not having to do this cast, more consistent with Python design.
Cons: are sequencer_address/gas_price really parts of a "block info"?

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 12 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/733)* status: 10 of 13 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4nBl_89u4giXu4AeC:-N_4nBl_89u4giXu4AeD:b-xjy52h) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b6003110a5d7dac0ed4259c1d273f06d48ad328/crates/native_blockifier/src/py_block_executor.rs#L18)):*
> ```XML
> // TODO(Gilad): Make Storage and TransactionExecutor into submodules of PyBlockExecutor.
> #[pyclass]
> pub struct PyBlockExecutor {
> ```

Inside each themed block of methods: what's the order? Let's make it Python-facing, Rust-`pub`lic, non-`pub`lic.



_Code quote:_
```XML
PyBlockExecutor
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4lmnq-1sds97VoZnP:-N_4lmnq-1sds97VoZnQ:btni2dw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b6003110a5d7dac0ed4259c1d273f06d48ad328/crates/native_blockifier/src/py_block_executor.rs#L34)):*
> ```XML
>         max_recursion_depth: usize,
>     ) -> Self {
>         // Executor is initialized separately for each block, since it needs block-level data.
> ```

Nothing more elegant?



_Code quote:_
```XML
// Executor is initialized separately for each block, since it needs block-level data.
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4mh1p6KWnImLu8rjg:-N_4mh1p6KWnImLu8rjh:b-f9iuo8) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b6003110a5d7dac0ed4259c1d273f06d48ad328/crates/native_blockifier/src/py_block_executor.rs#L49)):*
> ```XML
>             self.tx_executor.is_none(),
>             "Transaction executor should not be initialized, previous block NOT finalized"
>         );
> ```

I hate this method... :smiling_face_with_tear: 



_Suggestion:_
```XML
    pub fn start_block(&mut self, block_info: PyBlockInfo) {
        assert!(
            self.tx_executor.is_none(),
            "Transaction executor should not be initialized, previous block was not finalized."
        );
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4mnXL2QEq-GfXaWdd:-N_4mnXL2QEq-GfXaWde:b-arnvnr) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b6003110a5d7dac0ed4259c1d273f06d48ad328/crates/native_blockifier/src/py_block_executor.rs#L57)):*
> ```XML
>             self.max_recursion_depth,
>         )
>         .expect("Cannot create transaction executor");
> ```

Are we ending error messages with periods, or not?



_Suggestion:_
```XML
Cannot create transaction executor.
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4EA81Cn9hbLvLX8UH:-N_4m2MvET734zvcwL6Z:bgf618) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d9fbbb620771d4eeb7b129a7ac47c210a946224/crates/native_blockifier/src/py_state_diff.rs#L118)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Possible way of making this nicer: make this into a proper Blockifier struct `BlockInfo`, and make `BlockContext` have have a `BlockInfo` instance as a member.
Pros: Not having to do this cast, more consistent with Python design.
Cons: are sequencer_address/gas_price really parts of a "block info"?
</blockquote></details>

In Python, they are.
___
*[`crates/native_blockifier/src/storage.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4m9vHE9cRVfY-V-SZ:-N_4m9vHE9cRVfY-V-S_:braxl9b) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d044a8b0bb16867691f436451b704a474573aa4/crates/native_blockifier/src/storage.rs#L99)):*
> ```XML
>     }
> 
>     // TODO(Gilad): Refactor.
> ```

Restore, haha.



_Code quote:_
```XML
// TODO(Gilad): Refactor.
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4mOfTCrdU_OajSFfQ:-N_4mOfTCrdU_OajSFfR:b-uq2ifq) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b6003110a5d7dac0ed4259c1d273f06d48ad328/crates/native_blockifier/src/transaction_executor.rs#L160)):*
> ```XML
> }
> 
> pub fn into_block_context(
> ```

Can this be a method of `PyBlockInfo`?



_Code quote:_
```XML
into_block_context
```

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/733)* status: 10 of 13 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @Yoni-Starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/733)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @Yoni-Starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/733)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/733)* status: 9 of 13 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/733)* status: 9 of 13 files reviewed, 7 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4EA81Cn9hbLvLX8UH:-N_8pZH76IvY7iqO0R5H:bmkkrkk) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d9fbbb620771d4eeb7b129a7ac47c210a946224/crates/native_blockifier/src/py_state_diff.rs#L118)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

In Python, they are.
</blockquote></details>

Fixed.
Added `block_info` to Python's `StateScope`, and removed the `block_info`-returning logic from here.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4mOfTCrdU_OajSFfQ:-N_8-Dv5AR29minpgQaa:bvq42rf) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b6003110a5d7dac0ed4259c1d273f06d48ad328/crates/native_blockifier/src/transaction_executor.rs#L160)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can this be a method of `PyBlockInfo`?
</blockquote></details>

YES!
Thanks :)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/733)* status: 9 of 13 files reviewed, 6 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4nBl_89u4giXu4AeC:-N_DRsdU9kown-ZS1MJk:b-yega28) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b6003110a5d7dac0ed4259c1d273f06d48ad328/crates/native_blockifier/src/py_block_executor.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Inside each themed block of methods: what's the order? Let's make it Python-facing, Rust-`pub`lic, non-`pub`lic.
</blockquote></details>

They are all python-facing; everything in `pymethods` is used by Python.
The internal order I tried to use inside each themed block was by importance.

The only non-python-facing method is `fn tx_executor` which is the only function in the non-`pymethods` impl block.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4lmnq-1sds97VoZnP:-N_DQi_p78eS1VhPookg:bx7l80e) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b6003110a5d7dac0ed4259c1d273f06d48ad328/crates/native_blockifier/src/py_block_executor.rs#L34)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Nothing more elegant?
</blockquote></details>

You mean the `Option<TransactionExecutor>` thing?
Ya there are better ways, but this is the simplest and least verbose one.
Refactoring after this is merged should be easier.

For example, a more elegant solution would be to have _two_ BlockExecutors, one is `PreBlockExector` which only has the alignment API and no `tx_executor`, but when `start_block` is called it consumes the `PreBlockExecutor` and create a `ExecutingBlockExecutor`, which has a `tx_executor` and the execution API, and doesn't have the storage alignment API.
Conversly, when `end_block` is called, it consumes the `ExecutingBlockExecutor` and returns the `PreBlockExecutor`.

The example above is cleaner but will make the current PR much more complicated.
Also Pyo3 doesn't allow `pyclass`es to have consuming methods (bla bla can't track livetime in Python) so this will be challenging to implement.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4mh1p6KWnImLu8rjg:-N_DOLk23SbCDD9sj86I:b-lximb5) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b6003110a5d7dac0ed4259c1d273f06d48ad328/crates/native_blockifier/src/py_block_executor.rs#L49)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I hate this method... :smiling_face_with_tear: 
</blockquote></details>

What do you mean?
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/733#-N_4mnXL2QEq-GfXaWdd:-N_DONMC7ETQ3QCdqh1w:b-z1ds3i) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b6003110a5d7dac0ed4259c1d273f06d48ad328/crates/native_blockifier/src/py_block_executor.rs#L57)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are we ending error messages with periods, or not?
</blockquote></details>

Nope, only capitalize.
Rationale is that errors are often chained together, so a period won't fit gramatically.

For example:
```rust
let result = std::fs::read_to_string("file_that_doest_exist.txt").map_err(|err| format!("failed to read file: {}", err))?; 
println!("{}", result);

```
Will print `Error: failed to read file: No such file or directory (os error 2)`, which is good.
However, if all errors had periods you'd get `Error: failed to read file: No such file or directory (os error 2)..` (first period from `"failed to read file: {}."` and the second from `No such file or directory (os error 2).`

For deeper and more complicated chains, you'd start seeing periods in the middle of a sentence or a long "........." at the end.

**Comment by giladchase** [comment]
Looks like this is too big for review indeed, closing In favor of soon to be published smaller PRs.

**Pull request closed without merging**
