### PR TITLE
Verify the syscall call_contract in validate mode.

### PR DESCRIPTION
**Pull request by ArniStarkware**
Verify the syscall call contract is never calling other contracts in validate mode.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/940)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/940)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/940#-NfH5O3V4mcJpwO0hnuJ:-NfH5O3W7l-8uenPZbFc:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/30e91a322528e9acd14c2904b4092e11d12c2eed/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L73)):*
> ```XML
>     #[error(transparent)]
>     VirtualMachineError(#[from] VirtualMachineError),
>     #[error("Invalid syscall in execution mode error: {syscall_name} in {execution_mode}.")]
> ```





_Suggestion:_
```XML
    #[error("Unauthorized syscall {syscall_name} in execution mode {execution_mode}.")]
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/940#-NfH778k9UzlJUBsLDqa:-NfH778k9UzlJUBsLDqb:bhbe3af) ([raw file](https://github.com/starkware-libs/blockifier/blob/30e91a322528e9acd14c2904b4092e11d12c2eed/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L189)):*
> ```XML
>     syscall_handler: &mut DeprecatedSyscallHintProcessor<'_>,
> ) -> DeprecatedSyscallResult<CallContractResponse> {
>     let storage_address = request.contract_address;
> ```

You need to implement it in the non-deprecated syscall handler as well.

Add a todo to change the test of this to run Cairo 1.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/940)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/940#-NfH5O3V4mcJpwO0hnuJ:-NfK3MSkAaSdK_u8Qf5v:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/30e91a322528e9acd14c2904b4092e11d12c2eed/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L73)):*
> ```XML
>     #[error(transparent)]
>     VirtualMachineError(#[from] VirtualMachineError),
>     #[error("Invalid syscall in execution mode error: {syscall_name} in {execution_mode}.")]
> ```

Done.
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/940#-NfH778k9UzlJUBsLDqa:-NfK5IzGCcayFO-49lAZ:btvjv9f) ([raw file](https://github.com/starkware-libs/blockifier/blob/30e91a322528e9acd14c2904b4092e11d12c2eed/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L189)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You need to implement it in the non-deprecated syscall handler as well.

Add a todo to change the test of this to run Cairo 1.
</blockquote></details>

Done.
(I will soon fix the base branch as well and rebase - it will clean up some of this PR).

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/940#-NfH778k9UzlJUBsLDqa:-NfLYO1O4Ac2QwH5tnWZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/30e91a322528e9acd14c2904b4092e11d12c2eed/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L189)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
(I will soon fix the base branch as well and rebase - it will clean up some of this PR).
</blockquote></details>

Done.

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/940#-:-NfPTbwA0AVrZwcESVpU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/940)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 957 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/940#-NfuUzsp6AuU43aO2Ur1:-NfuUzsp6AuU43aO2Ur2:b-dlaf5) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdad20a05c3b6178866934938719e724767c519d/crates/blockifier/src/transaction/transactions_test.rs#L957)):*
> ```XML
>             )
> 
>         );
> ```

Don't know if it is better (it's shorter but does not check the error type)



_Suggestion:_
```XML
        let error = account_tx.execute(state, block_context, true).unwrap_err().to_string();
        assert!(error.contains("
        assert_matches!("Unauthorized syscall call_contract in execution mode Validate");
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 957 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/940#-NfuUzsp6AuU43aO2Ur1:-NfuZV5fAhDMTKAAk3kF:bpicp2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdad20a05c3b6178866934938719e724767c519d/crates/blockifier/src/transaction/transactions_test.rs#L957)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Don't know if it is better (it's shorter but does not check the error type)
</blockquote></details>

I am glad you say that! I suggested something similar in `r2` of this PR.
In #922 @giladchase was asked to give his opinion.

The upside of what you say here: It is a lot simpler.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/940)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/940)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 171 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/940#-Nfv2t5j5Sv_uzzp5zT5:-NfyTm4p4odYlruiKSSg:b-llp4ag) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdad20a05c3b6178866934938719e724767c519d/crates/blockifier/src/execution/syscalls/mod.rs#L171)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Should it "trigger" the failure flag?
</blockquote></details>

No, we want to fail the run. No need to prove failed `validate`

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/940)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions.rs` line 201 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/940#-NfyrM-U-KgtdSIHnGug:-NfyrM-U-KgtdSIHnGuh:b-aj5ctl) ([raw file](https://github.com/starkware-libs/blockifier/blob/250a313fc53917a1655125dcdb02071b8b83d51a/crates/blockifier/src/transaction/transactions.rs#L201)):*
> ```XML
>         update_remaining_gas(remaining_gas, &call_info);
>         // TODO(Arni, 01/10/2023): Remove this check once this function is only run in validate
>         // mode.
> ```

Indeed, #936.



_Code quote:_
```XML
        // TODO(Arni, 01/10/2023): Remove this check once this function is only run in validate
        // mode.
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions.rs` line 201 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/940#-NfyrM-U-KgtdSIHnGug:-NfyradJE5WsgI5xadW6:btpx3ko) ([raw file](https://github.com/starkware-libs/blockifier/blob/250a313fc53917a1655125dcdb02071b8b83d51a/crates/blockifier/src/transaction/transactions.rs#L201)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Indeed, #936.
</blockquote></details>

This TODO can be seen in R1 of this PR.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, 3 of 4 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/940#-:-NgxttjdAfNWkk1rtb1Q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r7, 3 of 4 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/940)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
