### PR TITLE
chore: refactor messages gas computation for bouncer

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware, @Yael-Starkware, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtlMe3W2Uxl3kU4tEx_:-NtlMe3W2Uxl3kU4tExa:b1odpp) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/34497)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware, @Yael-Starkware, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtlMe3W2Uxl3kU4tEx_:-NtmBxuD3_S1oE5AYEb6:b-m6tflo) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[python side](https://reviewable.io/reviews/starkware-industries/starkware/34497)
</blockquote></details>

passes

___

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoE6OO1ZW8dB44Ym7o:-NtoE6OO1ZW8dB44Ym7p:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L161)):*
> ```XML
>         state: &mut TransactionalState<'_, S>,
>         tx_execution_summary: &ExecutionSummary,
>         transaction_resources: &TransactionResources,
> ```





_Suggestion:_
```XML
tx_resources
```
___
*[`crates/blockifier/src/bouncer.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoEcxg4ybYLrqkVy-g:-NtoEcxg4ybYLrqkVy-h:b786enc) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L178)):*
> ```XML
>         )?;
> 
>         let mut tx_weights = BouncerWeights::from(additional_os_resources) + execution_info_weights;
> ```

Can you eliminate this conversion and do arithmetics with `ExecutionResources`? 
(you can get rid of `get_tx_execution_info_resources_weights`)



_Code quote:_
```XML
BouncerWeights::from(additional_os_resources)
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoY8_Q5u4qSIhpwZXv:-NtoY8_Q5u4qSIhpwZXw:b7pcpk1) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L180)):*
> ```XML
>         let mut tx_weights = BouncerWeights::from(additional_os_resources) + execution_info_weights;
>         tx_weights.state_diff_size =
>             get_onchain_data_segment_length(&self.transactional.state_changes_keys.count());
> ```

can this be taken from  transaction_resources.starknet_resources.state_changes_count?



_Code quote:_
```XML
self.transactional.state_changes_keys.count()
```
___
*[`crates/blockifier/src/bouncer.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoXP702f4CPRkZxWaX:-NtoXP702f4CPRkZxWaY:b1atf3v) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L195)):*
> ```XML
>             gas: gas_usage,
>             message_segment_length,
>             n_events: tx_execution_summary.n_events,
> ```

I see that n_event appear in both tx_execution_summary and  tx_resources.starknet_resources.
is this redundant?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoY8_Q5u4qSIhpwZXv:-Nto_28P4IDgpsPiTw0Q:b-cjuj0d) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L180)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can this be taken from  transaction_resources.starknet_resources.state_changes_count?
</blockquote></details>

Oops, no, they count different things
@dorimedini-starkware may be worth renaming this to `state_changes_for_fee`

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoE6OO1ZW8dB44Ym7o:-NtpD0CL3pKSV7L3ShbU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L161)):*
> ```XML
>         state: &mut TransactionalState<'_, S>,
>         tx_execution_summary: &ExecutionSummary,
>         transaction_resources: &TransactionResources,
> ```

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoEcxg4ybYLrqkVy-g:-NtpDlZh7tt5St_nufRI:b4sxwf1) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L178)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you eliminate this conversion and do arithmetics with `ExecutionResources`? 
(you can get rid of `get_tx_execution_info_resources_weights`)
</blockquote></details>

like this?
___
*[`crates/blockifier/src/bouncer.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoY8_Q5u4qSIhpwZXv:-NtpDzTJ0oY3NEjRtAcM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L180)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oops, no, they count different things
@dorimedini-starkware may be worth renaming this to `state_changes_for_fee`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoXP702f4CPRkZxWaX:-NtpE1JA2b0g-gcSu8VX:b-pua8lc) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L195)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I see that n_event appear in both tx_execution_summary and  tx_resources.starknet_resources.
is this redundant?
</blockquote></details>

I think it is; I'll replace it here, can you open a PR to remove the field from `ExecutionSummary` if possible?
Also, what is `ExecutionSummary` for? Can it be removed entirely in favor of `TransactionResources` or StarknetResources` or something?

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoEcxg4ybYLrqkVy-g:-NtpGLAJ2eaMsgW4czWD:b-8afcp5) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L178)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

like this?
</blockquote></details>

Yes! can you delete `BouncerWeights::from`?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoEcxg4ybYLrqkVy-g:-NtpHHux6p0jyuHESApS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L178)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yes! can you delete `BouncerWeights::from`?
</blockquote></details>

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtpGbYW7oFVFLZpk2x9:-NtpJ79eBeajutAwGT9Y:bay4lnh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4eccb0140f20fc6e1da13b6a1a21fceb9a05232f/crates/blockifier/src/bouncer.rs#L159)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware :
1. If this is the *original* (beginning of block) state, why is this a `TransactionalState`?
2. If this is the state before applying this specific transaction, then why can't this entire computation be moved to `StarknetResources`?
</blockquote></details>

Actually you're right
The only thing that should happen in the bouncer is this
```
state_changes_keys = tx_state_changes_keys.difference(&self.bouncer.state_changes_keys)
```
You can get the tx keys from the starknet resources, cool

**Review by Yoni-Starkware — COMMENTED** [review]
@Yael-Starkware why do we have two `bouncer.rs` files?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-:-NtpJO4u8eso_9-quKGx:b-6vmjel)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @Yael-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtpGbYW7oFVFLZpk2x9:-NtpTzVB0bIWwtY_NpnM:b-nz3hxn) ([raw file](https://github.com/starkware-libs/blockifier/blob/4eccb0140f20fc6e1da13b6a1a21fceb9a05232f/crates/blockifier/src/bouncer.rs#L159)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Actually you're right
The only thing that should happen in the bouncer is this
```
state_changes_keys = tx_state_changes_keys.difference(&self.bouncer.state_changes_keys)
```
You can get the tx keys from the starknet resources, cool
</blockquote></details>

How?
StarknetResources only tracks the StateChangeCount, we have no access to which keys were touched...
Not sure the set of storage keys belongs in StarknetResources, because it is not a quantity

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-:-NtpfM5n90XLr4mzwEml:bnfp4nl)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtpGbYW7oFVFLZpk2x9:-NtpenUW3lDa0DM527mf:b8mjj6a) ([raw file](https://github.com/starkware-libs/blockifier/blob/4eccb0140f20fc6e1da13b6a1a21fceb9a05232f/crates/blockifier/src/bouncer.rs#L159)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

How?
StarknetResources only tracks the StateChangeCount, we have no access to which keys were touched...
Not sure the set of storage keys belongs in StarknetResources, because it is not a quantity
</blockquote></details>

Oh, so NVM for now

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoXP702f4CPRkZxWaX:-NttpC_HCFhG8gYsic0q:bpyene3) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L195)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it is; I'll replace it here, can you open a PR to remove the field from `ExecutionSummary` if possible?
Also, what is `ExecutionSummary` for? Can it be removed entirely in favor of `TransactionResources` or StarknetResources` or something?
</blockquote></details>

Thanks, will remove it from there.

the execution summary is holding a set of executed_class_hashes and visited_storage_entries.  
Sounds good to add it to TransactionResources.
iiuc, both TransactionResources and ExecutionSummary serve the same purpose.

**Review by Yael-Starkware — COMMENTED** [review]
the old one should be deleted after the new bouncer kicks in.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-:-NttqEZ55QLF24TL-VjX:bb6xlrv)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @nimrod-starkware and @Yoni-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-:-NttqZRU8-3_Svjc_tCG:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @nimrod-starkware and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @nimrod-starkware, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1711#-NtoXP702f4CPRkZxWaX:-NttqWLo0Eb19oOiUC85:bsbw56d) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8083954566f6e754addaffb0546ed4877bb4edf/crates/blockifier/src/bouncer.rs#L195)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Thanks, will remove it from there.

the execution summary is holding a set of executed_class_hashes and visited_storage_entries.  
Sounds good to add it to TransactionResources.
iiuc, both TransactionResources and ExecutionSummary serve the same purpose.
</blockquote></details>

Not exactly:
I want (if it makes sense) to keep the `XResources` structs *quantative*, i.e. only numeric counts of resources.
e.g. a set of visited storage keys shouldn't be in `TransactionResources` or `StarknetResources`... but this may be the wrong way to go, maybe these structs really should contain these kind of things?
WDYT?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1711)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
