### PR TITLE
Alonh/blockifier for papyrus execution 0.12.2

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/912)

### CODE REVIEW

**Comment by elintul** [comment]
Is simply `cherry-pick`ing enough?
Also, I assume there were quite a lot conflicts.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/912)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/912#-Ne8BinYA1tfciIEy1FC:-Ne8BinZ4deAVy8XX5d5:bd4duoy) (no related file):*
Not for merging.

___

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/912)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dan-starkware)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/912)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/912#-Ne8BinYA1tfciIEy1FC:-Ne8Jj7cBA7xs8YXy8pv:bbrgydy) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Python side?
</blockquote></details>

Python compatibility [PR](https://reviewable.io/reviews/starkware-industries/starkware/31825).

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/912)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/912#-Ne8QQAt8MZ7KrtDB6Cu:-Ne8QQAt8MZ7KrtDB6Cv:b-jeqwci) (no related file):*
Not for merging. 

___

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/912)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dan-starkware)

**Pull request closed without merging**
