### PR TITLE
Merge main-v0.13.1 into main

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1550)

### CODE REVIEW

**Comment by Yoni-Starkware** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/828c57b054f9402a04817edc82a045864419d477..main-v0.13.1#diff-ec73f506940d2ffac36e120aa9bcfc30205cb6fd31180e10784759375d03bb26) [Dst](https://github.com/starkware-libs/blockifier/compare/828c57b054f9402a04817edc82a045864419d477..main#diff-ec73f506940d2ffac36e120aa9bcfc30205cb6fd31180e10784759375d03bb26) crates/blockifier/src/transaction/transactions_test.rs

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1550)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @dorimedini-starkware, and @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1550#-:-Nr0N2dB-Y-cZSOrPHrM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @elintul)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1550)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 9 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1550#-Nr0N62S5A--O76e4EUk:-Nr0N62S5A--O76e4EUl:b354p86) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cfdc657fc602655226b0c8d65dea18c54a58249/crates/blockifier/resources/versioned_constants.json#L9)):*
> ```JSON
>     "gateway": {
>         "max_calldata_length": 4000,
>         "max_contract_bytecode_size": 81920
> ```

what's this?



_Code quote:_
```JSON
81920
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1550)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @barak-b-starkware, and @elintul)

___
*[`crates/blockifier/resources/versioned_constants.json` line 9 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1550#-Nr0N62S5A--O76e4EUk:-Nr0P7xk317IUc_yqO2A:b-2tn1iw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cfdc657fc602655226b0c8d65dea18c54a58249/crates/blockifier/resources/versioned_constants.json#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

@ArniStarkware modified it in 0.13.1 (request from product)

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1550)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @elintul)

___
*[`-- commits` line 24 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1550#-Nr0cjfN1pBaw0ckHAw3):*
WDYT of maintaining the following convention(?):



_Suggestion:_
```
chore: merge branch main-v0.13.1 into main (resolve conflicts)
```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1550)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware and @elintul)

___
*[`-- commits` line 24 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1550#-Nr0cjfN1pBaw0ckHAw3):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT of maintaining the following convention(?):
</blockquote></details>

merges should not appear in changelogs; TAL at our workflow file and you'll see we basically skip commitlint phase for merge PRs

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1550)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware and @elintul)

**Pull request merged**
