### PR TITLE
Pass error info in #[source] variants

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1217)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
This is from the 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1217#-:-Nkxr5Lh3R2BKeexEkA1:b-qhqtys)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1217#-NkySqfB-AbuSjNikjKo:-NkySqfCAqndbU50gQQB:bbq4o3x) ([raw file](https://github.com/starkware-libs/blockifier/blob/00b9eaa2ba241ecf72a9f965c3fa415fc2f0da27/crates/blockifier/src/transaction/errors.rs#L62)):*
> ```XML
>     DeclareTransactionError { class_hash: ClassHash },
>     #[error(transparent)]
>     EntryPointExecutionError(#[from] EntryPointExecutionError),
> ```

If you're already here, it looks like this variant is only used once, [in execute_fee_transfer](https://github.com/starkware-libs/blockifier/blob/bd7633214270cf1a50fc2d1ed2be8c6669c24664/crates/blockifier/src/transaction/account_transaction.rs#L313) (if you remove this variant this is the only error you get).

Can you plz make it use TransactionFeeError? (or another error if you think it's more appropriate)



_Code quote:_
```XML
    #[error(transparent)]
    EntryPointExecutionError(#[from] EntryPointExecutionError),
```

**Review by dorimedini-starkware — COMMENTED** [review]
`this == "from the"`?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1217#-:-NkyXM8c1avd_EnqG1Hj:b-qtx6r)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/transaction/errors.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1217#-NkySqfB-AbuSjNikjKo:-NkyX9rR7RckgMpAMJi0:b-v4gc3s) ([raw file](https://github.com/starkware-libs/blockifier/blob/00b9eaa2ba241ecf72a9f965c3fa415fc2f0da27/crates/blockifier/src/transaction/errors.rs#L62)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If you're already here, it looks like this variant is only used once, [in execute_fee_transfer](https://github.com/starkware-libs/blockifier/blob/bd7633214270cf1a50fc2d1ed2be8c6669c24664/crates/blockifier/src/transaction/account_transaction.rs#L313) (if you remove this variant this is the only error you get).

Can you plz make it use TransactionFeeError? (or another error if you think it's more appropriate)
</blockquote></details>

I don't follow... `EntryPointExecutionError` is used many times, you're saying it's only converted to `TransactionExecutionError` once? How do you see that?

**Review by giladchase — CHANGES_REQUESTED** [review]
Whoops didn't mean to post that, ignore :grimacing: srry

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1217#-:-Nky_4L2CGRG8vgPltTY:bcm61vh)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1217#-NkySqfB-AbuSjNikjKo:-Nky_Cr56mKpzOVW2kP0:bp0aomm) ([raw file](https://github.com/starkware-libs/blockifier/blob/f84907e1e2a38f7842017f6ee198a337bee83197/crates/blockifier/src/transaction/errors.rs#L62)):*
>you're saying it's only converted to `TransactionExecutionError` once

Using the transparent variant, yes.
The other conversions use the other variants.

>How do you see that?

If you delete this variant you get an error in only one place, which is in the link above.
Conversely, if i remove the `transparent` and use this variant explicitly via `map_err`, there are no errors (this is all done in compilation so there are no runtime risks associated with this change).

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1217)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/transaction/errors.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1217#-NkySqfB-AbuSjNikjKo:-Nkz3y3bEO81itB00axu:bixjn1v) ([raw file](https://github.com/starkware-libs/blockifier/blob/f84907e1e2a38f7842017f6ee198a337bee83197/crates/blockifier/src/transaction/errors.rs#L62)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>you're saying it's only converted to `TransactionExecutionError` once

Using the transparent variant, yes.
The other conversions use the other variants.

>How do you see that?

If you delete this variant you get an error in only one place, which is in the link above.
Conversely, if i remove the `transparent` and use this variant explicitly via `map_err`, there are no errors (this is all done in compilation so there are no runtime risks associated with this change).
</blockquote></details>

there are a total of fourth variants with `EntryPointExecutionError` as a source.
We need to delete three of them to be able to use `from`.
What exactly are you suggesting...? Intermediate types for 3 out of the 4 variants?

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1217)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1217#-NkySqfB-AbuSjNikjKo:-Nkz4_RJDg-UcL5nwWcp:b-mx5zdu) ([raw file](https://github.com/starkware-libs/blockifier/blob/f84907e1e2a38f7842017f6ee198a337bee83197/crates/blockifier/src/transaction/errors.rs#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there are a total of fourth variants with `EntryPointExecutionError` as a source.
We need to delete three of them to be able to use `from`.
What exactly are you suggesting...? Intermediate types for 3 out of the 4 variants?
</blockquote></details>

Oh i meant that following our offline convo the {0} implementation should stay, and additionally (and independently in fact, maybe this doesn't belong in this PR i guess), we should change
this:
```rust
 #[error(transparent)]
    EntryPointExecutionError(#[from] EntryPointExecutionError),
```
to this:
```rust
 #[error("Fee transfer error: {0}")]
    FeeTransferError(#[source] EntryPointExecutionError),
```
Reasons: the variant is only used in one spot in a specific context (during fee transfer), so transparent doesn't really fit there.
(The transparent probably made sense in the past, before we added the other explicit EntrypointExecutionError variants)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1217)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/transaction/errors.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1217#-NkySqfB-AbuSjNikjKo:-NkzIQg3BgKYe5h0BMPw:b-k48oax) ([raw file](https://github.com/starkware-libs/blockifier/blob/f84907e1e2a38f7842017f6ee198a337bee83197/crates/blockifier/src/transaction/errors.rs#L62)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Oh i meant that following our offline convo the {0} implementation should stay, and additionally (and independently in fact, maybe this doesn't belong in this PR i guess), we should change
this:
```rust
 #[error(transparent)]
    EntryPointExecutionError(#[from] EntryPointExecutionError),
```
to this:
```rust
 #[error("Fee transfer error: {0}")]
    FeeTransferError(#[source] EntryPointExecutionError),
```
Reasons: the variant is only used in one spot in a specific context (during fee transfer), so transparent doesn't really fit there.
(The transparent probably made sense in the past, before we added the other explicit EntrypointExecutionError variants)
</blockquote></details>

ahhh!
Done.

**Pull request merged**
