### PR TITLE
Separate contexts to `[EntryPoint/Transaction]ExecutionContext`.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/601)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/601)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXkeqkP6QS5zQKmK3iv:-NXkeqkP6QS5zQKmK3iw:b-829p9a) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/execution/syscalls/hint_processor.rs#L94)):*
> ```XML
>     pub state: &'a mut dyn State,
>     pub context: &'a mut EntryPointExecutionContext,
>     pub tx_context: &'a mut TransactionExecutionContext,
> ```

Don't these have different lifetimes?



_Code quote:_
```XML
    pub context: &'a mut EntryPointExecutionContext,
    pub tx_context: &'a mut TransactionExecutionContext,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXkcjVe9HKYX2Jty1-k:-NXkcjVf6tIur1ouQrRj:b-cftf9p) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/transaction/account_transaction.rs#L159)):*
> ```XML
>         Ok(state.increment_nonce(address)?)
>     }
> ```

Might be over-engineering this, but i'm seeing `tx_context` passed into three separate methods/functions of this struct, which kind of hints that it should perhaps be a field in the struct (initialized empty and modified by these functions maybe?).

This would likely require surgery though, cause it doesn't seem right adding it as an extra field to the enum, so I think it entails adding another struct that holds the enum and the tx_context instance :thinking:  If that's the case it might not be worth it.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXkAd6N9aiRkND6HSM6:-NXkAd6N9aiRkND6HSM7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/transaction/transaction_execution.rs#L38)):*
> ```XML
>     }
> 
>     pub fn get_execute_context(&self) -> EntryPointExecutionContext {
> ```





_Suggestion:_
```XML
  pub fn get_execution_context(&self) -> EntryPointExecutionContext {
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXkeGFz0HL2PRVvmssy:-NXkeGFz0HL2PRVvmssz:bpaditg) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/transaction/transactions.rs#L68)):*
> ```XML
>         state: &mut S,
>         tx_context: &mut TransactionExecutionContext,
>         remaining_gas: &mut Felt252,
> ```

So, `tx_context` looks like it indeed fits here in the flow, that is, an execution function taking in external context as a variable :muscle: 

That gas though :thinking:  does it make sense if gas is included in the TransactionExecutionContext? 



_Code quote:_
```XML
    fn run_execute(
        &self,
        state: &mut S,
        tx_context: &mut TransactionExecutionContext,
        remaining_gas: &mut Felt252,
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/601)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXkcjVe9HKYX2Jty1-k:-NXo3O1WEChg_ROSi9Ly:b-3ieoet) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/transaction/account_transaction.rs#L159)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Might be over-engineering this, but i'm seeing `tx_context` passed into three separate methods/functions of this struct, which kind of hints that it should perhaps be a field in the struct (initialized empty and modified by these functions maybe?).

This would likely require surgery though, cause it doesn't seem right adding it as an extra field to the enum, so I think it entails adding another struct that holds the enum and the tx_context instance :thinking:  If that's the case it might not be worth it.
</blockquote></details>

The flow that calls those functions (validate-execute-fee), which is `execute_raw`, is the one in charge of initializing the context in the right moment. So I don't see how the transaction object itself can be responsible for that. 
___
*[`crates/blockifier/src/transaction/transactions.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXkeGFz0HL2PRVvmssy:-NXo3hJyCArcBqA6nMq1:b427efp) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/transaction/transactions.rs#L68)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

So, `tx_context` looks like it indeed fits here in the flow, that is, an execution function taking in external context as a variable :muscle: 

That gas though :thinking:  does it make sense if gas is included in the TransactionExecutionContext? 
</blockquote></details>

It can be included there, I think.
But that's a separate refactor, so let's consider after this PR?

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/601)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXqGKal-Xy9546PeamW:-NXqGKal-Xy9546PeamX:bl0s85l) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/execution/execution_utils.rs#L199)):*
> ```XML
> pub fn execute_deployment(
>     state: &mut dyn State,
>     tx_context: &mut TransactionExecutionContext,
> ```

Why add it here and not insert it directly in `constructor_call.execute(state, context)` (in the method `execute_constructor_entry_point`).



_Code quote:_
```XML
tx_context: &mut TransactionExecutionContext
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXq9z1cATRxhW3fxCGq:-NXq9z1cATRxhW3fxCGr:bqfmhbn) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/transaction/transaction_execution.rs#L35)):*
> ```XML
> 
>     pub fn get_validate_context(&self) -> EntryPointExecutionContext {
>         EntryPointExecutionContext::new(self.block_context.validate_max_n_steps as usize)
> ```

Maybe it should be of the same type as `n_steps` (or vice versa).
Same for `self.block_context.invoke_tx_max_n_steps`.



_Code quote:_
```XML
self.block_context.validate_max_n_steps
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXkeGFz0HL2PRVvmssy:-NXqDcqO7pra6i39vyQe:b-1qmw0w) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/transaction/transactions.rs#L68)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It can be included there, I think.
But that's a separate refactor, so let's consider after this PR?
</blockquote></details>

The `TransactionExecutionContext` is a field in the `SyscallHintProcessor` struct. We calculate the remaining gas differently in the execution of an entry point and in the syscalls, so I think that it might be confusing. In the syscalls we take the value from the stack. When running an EP we enter the remaining gas as the initial gas of an entry point and after the execution we update the remaining gas using the `CallInfo.execution.gas_consumed`. We can think of a way to do it in a clear manner (after this PR :)).
___
*[`crates/blockifier/src/transaction/transactions.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXqDvrw2aZBKZu7TD5E:-NXqDvrw2aZBKZu7TD5F:bwgcyo6) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/transaction/transactions.rs#L184)):*
> ```XML
>             state,
>             tx_context,
>             &mut tx_context.get_execute_context(),
> ```

As in python. I'll ask Yoni why (maybe it's because we run it before `__validate__`?)



_Suggestion:_
```XML
 &mut tx_context.get_validate_context(),
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/601)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXqGKal-Xy9546PeamW:-NXsSaNn3MJ4xlstyAbB:b-f2n409) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/execution/execution_utils.rs#L199)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why add it here and not insert it directly in `constructor_call.execute(state, context)` (in the method `execute_constructor_entry_point`).
</blockquote></details>

I see now. Please ignore the above.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/601)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXqGKal-Xy9546PeamW:-NXtO9p1BLA3Ai3z2u3h:bko1se4) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/execution/execution_utils.rs#L199)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see now. Please ignore the above.
</blockquote></details>

Because of the syscall (I guess you saw). :)
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/601#-NXq9z1cATRxhW3fxCGq:-NXtOUhV2Bbxk8MF8z_u:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/17460383c458d81e34d103690f751df798d968ae/crates/blockifier/src/transaction/transaction_execution.rs#L35)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe it should be of the same type as `n_steps` (or vice versa).
Same for `self.block_context.invoke_tx_max_n_steps`.
</blockquote></details>

WDYM?

**Pull request closed without merging**
