### PR TITLE
Refactor in prep for post-validation usage

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1140)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1140)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjI9EQi5Duwbxcd3cB2:-NjI9EQj6UJL8jullIQK:b-kgx28l) ([raw file](https://github.com/starkware-libs/blockifier/blob/1490ad94d0018c35bac939f1a13280d2cf13e486/crates/blockifier/src/fee/actual_cost.rs#L202)):*
> ```XML
>     /// Given a fee error and the current context, constructs and returns a report.
>     pub fn from_fee_check_error(
>         actual_fee: Fee,
> ```

Why is it needed? You can extract it from `FeeCheckError::InsufficientFeeTokenBalance`.



_Code quote:_
```XML
        actual_fee: Fee,
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjI7HOk3m3iEQM6uoY4:-NjI7HOl0NmfIfa-9E8p:by8lm2n) ([raw file](https://github.com/starkware-libs/blockifier/blob/1490ad94d0018c35bac939f1a13280d2cf13e486/crates/blockifier/src/fee/actual_cost.rs#L208)):*
> ```XML
>     ) -> TransactionExecutionResult<Self> {
>         let recommended_fee = match error {
>             FeeCheckError::InsufficientFeeTokenBalance { .. } => actual_fee,
> ```

Document?



_Code quote:_
```XML
            FeeCheckError::InsufficientFeeTokenBalance { .. } => actual_fee,
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjIDNZzBDv7wA2JC4WD:-NjIDNZzBDv7wA2JC4WE:bebib0c) ([raw file](https://github.com/starkware-libs/blockifier/blob/1490ad94d0018c35bac939f1a13280d2cf13e486/crates/blockifier/src/fee/actual_cost.rs#L335)):*
> ```XML
>                 )?))
>             }
>             Err(other_error) => Err(other_error),
> ```

We are not going to use the report in case of error.
WDYT?



_Suggestion:_
```XML
       FeeCheckReport::check_actual_cost_within_bounds(
            block_context,
            account_tx_context,
            actual_cost,
        )?;
        Ok(Self(FeeCheckReport::success_report(actual_cost.actual_fee)))
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 357 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjIDfmk2OOwKShjnja-:-NjIDfmk2OOwKShjnja0:btxuw80) ([raw file](https://github.com/starkware-libs/blockifier/blob/1490ad94d0018c35bac939f1a13280d2cf13e486/crates/blockifier/src/fee/actual_cost.rs#L357)):*
> ```XML
>         }
> 
>         for fee_check_result in [
> ```

Can you please define a variable for each report and then perform the for loop?



_Code quote:_
```XML
 for fee_check_result in [
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjIF9D_7zbK_b3TNlhf:-NjIF9DaEFXHjtd1qYa6:bdk7ku9) ([raw file](https://github.com/starkware-libs/blockifier/blob/1490ad94d0018c35bac939f1a13280d2cf13e486/crates/blockifier/src/fee/actual_cost.rs#L367)):*
> ```XML
>             // Next, compare resource bounds cover the actual cost, and are covered by
>             // pre-execution balance (verified in pre-validation phase).
>             // Verify against the account balance, which may have changed after execution.
> ```

Why is this needed?



_Suggestion:_
```XML
            // Next, compare resource bounds cover the actual cost.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1140)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjI9EQi5Duwbxcd3cB2:-NjIOfL69m8_rk-Ff-kp:bov0n2x) ([raw file](https://github.com/starkware-libs/blockifier/blob/1490ad94d0018c35bac939f1a13280d2cf13e486/crates/blockifier/src/fee/actual_cost.rs#L202)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed? You can extract it from `FeeCheckError::InsufficientFeeTokenBalance`.
</blockquote></details>

I prefer not to read business-logic *data* from *errors*.
I would rather rely on the variants only to see what we logically should use; better separation IMO.
This is a compromise - we will need to compromise somewhere, because of the difference in revert and non-revert flows we treat "fee check failures" as either *errors* or *different behavior*
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjI7HOk3m3iEQM6uoY4:-NjIPgB70GPXqz7XvqDS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1490ad94d0018c35bac939f1a13280d2cf13e486/crates/blockifier/src/fee/actual_cost.rs#L208)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Document?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjIDNZzBDv7wA2JC4WD:-NjIQWeI85w2vMV_gU8L:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1490ad94d0018c35bac939f1a13280d2cf13e486/crates/blockifier/src/fee/actual_cost.rs#L335)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We are not going to use the report in case of error.
WDYT?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 357 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjIDfmk2OOwKShjnja-:-NjIR3yHEsFjm3firXe3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1490ad94d0018c35bac939f1a13280d2cf13e486/crates/blockifier/src/fee/actual_cost.rs#L357)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please define a variable for each report and then perform the for loop?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjIF9D_7zbK_b3TNlhf:-NjIRQ5lCkE8JN1wXcW4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1490ad94d0018c35bac939f1a13280d2cf13e486/crates/blockifier/src/fee/actual_cost.rs#L367)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1140)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjM9vY6BxjCDymr3cMm:-NjM9vY79YOyZaAENMKj:b2nhkyh) ([raw file](https://github.com/starkware-libs/blockifier/blob/7917163c3d69f8e7fec47455c171aad007bf3eab/crates/blockifier/src/fee/actual_cost.rs#L211)):*
> ```XML
>             // This recommendation assumes (a) the pre-validation checks were applied and pass (i.e.
>             // the sender initially could cover the resource bounds), and (b) the sender's balance
>             // (pre-execution) covered the resource bounds.
> ```

No?



_Suggestion:_
```XML
            // If the error is insufficient balance, the recommended fee is the actual fee.
            // This recommendation assumes (a) the pre-validation checks were applied and pass (i.e.
            // the sender initially could cover the esource bounds), and (b) the actual resources
            // are smaller then the resources bounds set by the sender.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1140)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1140#-NjM9vY6BxjCDymr3cMm:-NjMWfY479FGV4gjZaRG:b-mjer7h) ([raw file](https://github.com/starkware-libs/blockifier/blob/7917163c3d69f8e7fec47455c171aad007bf3eab/crates/blockifier/src/fee/actual_cost.rs#L211)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No?
</blockquote></details>

right, good catch

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
