### PR TITLE
Fix actual fee for l1 handler: it equals the L2 cost.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1210)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1210)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1402 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1210#-NkoW1sd8i9v7RktUfgL:-NkoXemm96Pwms0jicsG:bmbyh4g) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d0711dee0704234a7a92663f214cdb582bc3801/crates/blockifier/src/transaction/transactions_test.rs#L1402)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Where do you see that `max_fee = 1`?
</blockquote></details>

tagged you

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1210)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1403 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1210#-Nko_oYH2Hw1JMM6iHGT:-Nko_oYH2Hw1JMM6iHGU:b-8b8zne) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d0711dee0704234a7a92663f214cdb582bc3801/crates/blockifier/src/transaction/transactions_test.rs#L1403)):*
> ```XML
>             TransactionFeeError::InsufficientL1Fee { paid_fee, actual_fee, })
>             if paid_fee == Fee(0) && actual_fee == Fee(1732700000000000)
>     );
> ```

I don't follow the logic.
If `paid_fee` is `1`, the tx is successful; but if it's zero, we get this error, which seems to indicate only a minimum of `paid_fee=1732700000000000` would allow the tx to pass.
Is this just future-preparation for when the error is more meaningful?



_Code quote:_
```XML
        TransactionExecutionError::TransactionFeeError(
            TransactionFeeError::InsufficientL1Fee { paid_fee, actual_fee, })
            if paid_fee == Fee(0) && actual_fee == Fee(1732700000000000)
    );
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1210)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1330 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1210#-NkoXZTJAyopD94wpWtY:-NkoXv5K3uO5V3Tj-3RB:bb5wxig) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d0711dee0704234a7a92663f214cdb582bc3801/crates/blockifier/src/transaction/transactions_test.rs#L1330)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@noaov1 
If max_fee=1 and actual_fee>1 I would expect an error... no?
</blockquote></details>

`Fee(1)` is the fee paid on l1. Currently, we only verify it is positive. L1 handlers do not have a `max_fee` field. We set it to 0 (in the `account_tx_context` for our own use. 
In the future: we will verify `paid_fee_on_l1 >= required_fee_on_l2`.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1403 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1210#-Nko_oYH2Hw1JMM6iHGT:-NkoauZR-tTAzHkUrdcF:b2nhswy) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d0711dee0704234a7a92663f214cdb582bc3801/crates/blockifier/src/transaction/transactions_test.rs#L1403)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't follow the logic.
If `paid_fee` is `1`, the tx is successful; but if it's zero, we get this error, which seems to indicate only a minimum of `paid_fee=1732700000000000` would allow the tx to pass.
Is this just future-preparation for when the error is more meaningful?
</blockquote></details>

Yes

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1210#-:-NkoxBVQC4fS3QtXlfv4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
