### PR TITLE
Fix keccak resources.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/681)

### CODE REVIEW

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/681)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/fee/os_resources.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/681#-NZ0TgFw0t0sJ3h5E4eQ:-NZ0TgFw0t0sJ3h5E4eR:bjunovz) ([raw file](https://github.com/starkware-libs/blockifier/blob/da8905e226a6a614f171a7a3e257d9ff9cb10410/crates/blockifier/src/fee/os_resources.rs#L101)):*
> ```XML
>                 },
>                 "n_memory_holes": 0,
>                 "n_steps": 381
> ```

Does each round use these resources?



_Code quote:_
```XML
                "builtin_instance_counter": {
                    "bitwise_builtin": 6,
                    "keccak_builtin": 1,
                    "range_check_builtin": 56
                },
                "n_memory_holes": 0,
                "n_steps": 381
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/fee/os_resources.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/681#-NZ0TgFw0t0sJ3h5E4eQ:-NZ0VHGcAHjJzHfBdeby:b2nign6) ([raw file](https://github.com/starkware-libs/blockifier/blob/da8905e226a6a614f171a7a3e257d9ff9cb10410/crates/blockifier/src/fee/os_resources.rs#L101)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Does each round use these resources?
</blockquote></details>

yes

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/681)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/fee/os_resources.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/681#-NZ0XwmBBOkqawwhCU5f:-NZ0XwmC-KkZ6H4soCPu:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c17635891229fd195ed46b47ab17367a082e6a5/crates/blockifier/src/fee/os_resources.rs#L95)):*
> ```XML
>             },
>             // The following is the cost of one Keccak round.
>             // TODO(ilya): Consider moving the resources of a keccak round to a seperate dict.
> ```

Why?



_Code quote:_
```XML
Consider moving the resources of a keccak round to a seperate dict.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/fee/os_resources.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/681#-NZ0XwmBBOkqawwhCU5f:-NZ0Y84a-Q-_EqpRbmYn:b329hz7) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c17635891229fd195ed46b47ab17367a082e6a5/crates/blockifier/src/fee/os_resources.rs#L95)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Currently, the key to this dict is a syscall selector.

I think we should split the above to

keccak
and 
keccak_round

and we there is no selector for keccak_round.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/681#-:-NZ0hqyb6SDn5hP6VJBq:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/681)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
