### PR TITLE
Implement `replace_class` syscall.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/499)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/499)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/499#-NVxBAc74Dj4sbJEwZ5-:-NVxBAc74Dj4sbJEwZ50:bgb1mtn) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef507eade2cd76d4ed023a110a53a1b47bda6a13/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L272)):*
> ```XML
>     assert!(error.contains("is not declared"));
> 
>     // Positive flow.
> ```

Separate into 2 tests

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/499#-:-NVxBMcr4RRLSAqz-8Mr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/499)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/499#-NVxBAc74Dj4sbJEwZ5-:-NVxz3n25SixIF79Pnh3:b8tszv3) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef507eade2cd76d4ed023a110a53a1b47bda6a13/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L272)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Separate into 2 tests
</blockquote></details>

I think it's rather short and they can stay in the same test.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/499)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
