### PR TITLE
Update cairo-vm revision.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/418)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/418)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/418#-NTOICK13OReW0mgUz6X:-NTOICK13OReW0mgUz6Y:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/846e87e2c90d6e94bcbeed18b2fe93140d302ceb/crates/blockifier/src/execution/contract_class.rs#L6)):*
> ```XML
> use cairo_vm::types::program::Program;
> use serde::de::Error as DeserializationError;
> use serde::{Deserialize, Deserializer, Serialize};
> ```

Why?
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/418#-NTOIPci-kQfNCMHIf6Y:-NTOIPci-kQfNCMHIf6Z:bdtoqvr) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca9b6285eff85e9bdbf448965bc231da8274ea15/crates/blockifier/src/execution/execution_utils.rs#L191)):*
> ```XML
> ) -> Result<(), VirtualMachineExecutionError> {
>     let verify_secure = true;
>     let program_segment_size = None;
> ```

Why `None`? Where is this used?



_Code quote:_
```XML
let program_segment_size = None;
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/418)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/418#-NTOJIjL-QiZA71Fs2U4:-NTOJIjM7gi9mIE1hOqj:bhfcg3h) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca9b6285eff85e9bdbf448965bc231da8274ea15/crates/blockifier/src/execution/syscalls_test.rs#L213)):*
> ```XML
> Unknown location (pc=0:605)
> ```

too many newlines... please find the `\n\n` I wrote and change it to `\n`, and make sure this is reverted

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/418)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/418#-NTOICK13OReW0mgUz6X:-NTOJigU8v2f6fwWNTF8:by79bp5) ([raw file](https://github.com/starkware-libs/blockifier/blob/846e87e2c90d6e94bcbeed18b2fe93140d302ceb/crates/blockifier/src/execution/contract_class.rs#L6)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

`Program` no longer implements `Serialize`, I'm not sure why. Do we need it?
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/418#-NTOIPci-kQfNCMHIf6Y:-NTOKLdL0_ct5eoglzuR:b-p7pve) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca9b6285eff85e9bdbf448965bc231da8274ea15/crates/blockifier/src/execution/execution_utils.rs#L191)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why `None`? Where is this used?
</blockquote></details>

If it's `None`, they use `runner.program.shared_program_data.data.len()` insead. Maybe it's some optimization, we should ask them. In practice, they pass `None` everywhere ATM.
___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/418#-NTOJIjL-QiZA71Fs2U4:-NTOLebBBrdDJuFnYS74:boyexbg) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca9b6285eff85e9bdbf448965bc231da8274ea15/crates/blockifier/src/execution/syscalls_test.rs#L213)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

too many newlines... please find the `\n\n` I wrote and change it to `\n`, and make sure this is reverted
</blockquote></details>

Done. Thanks.

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/418)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/418)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/418#-NTOICK13OReW0mgUz6X:-NTOUXeH-9ngHMFCBmED:b-fd3ilc) ([raw file](https://github.com/starkware-libs/blockifier/blob/846e87e2c90d6e94bcbeed18b2fe93140d302ceb/crates/blockifier/src/execution/contract_class.rs#L6)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

`Program` no longer implements `Serialize`, I'm not sure why. Do we need it?
</blockquote></details>

I guess not.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/418#-NTOIPci-kQfNCMHIf6Y:-NTOUOcNAwmKFphsAvhd:bu007ce) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca9b6285eff85e9bdbf448965bc231da8274ea15/crates/blockifier/src/execution/execution_utils.rs#L191)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

If it's `None`, they use `runner.program.shared_program_data.data.len()` insead. Maybe it's some optimization, we should ask them. In practice, they pass `None` everywhere ATM.
</blockquote></details>

Add an inline comment: `// Infer size from program.`.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/418)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/418#-:-NTOeua4AcjgGknHIiME:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/418)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Pull request merged**
