### PR TITLE
Add Keccak syscall support.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 21 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NXyyH-U-N-CGmk5oDKR:-NXyyH-U-N-CGmk5oDKS:b-gdxvgj) ([raw file](https://github.com/starkware-libs/blockifier/blob/d76ebe53959e0a28a83539b1575ab59946a6010f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L21)):*
> ```Cairo
> 
>     #[constructor]
>     fn constructor(ref self: ContractState, arg1: felt252, arg2: felt252) -> felt252 {
> ```

I guess this should be done in a separate PR.

Should I do a PR to 0.12? or directly to main?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 21 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NXyyH-U-N-CGmk5oDKR:-NYHqfqy7I_40AK8qv5l:b-5aqvr3) ([raw file](https://github.com/starkware-libs/blockifier/blob/d76ebe53959e0a28a83539b1575ab59946a6010f/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L21)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess this should be done in a separate PR.

Should I do a PR to 0.12? or directly to main?
</blockquote></details>

Done in 0.12.

I will rebase once this is merged.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @giladchase and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 525 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYSu5FJDHO_5zd4wFM-:-NYSu5FJDHO_5zd4wFM0:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L525)):*
> ```XML
> }
> 
> #[derive(Debug, Eq, PartialEq)]
> ```





_Suggestion:_
```XML
// Keccac syscall.

#[derive(Debug, Eq, PartialEq)]
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 587 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYSvH6m0UioBHfkvC2j:-NYSvH6m0UioBHfkvC2k:b-ga1nvn) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L587)):*
> ```XML
>     // syscall invocations. Since the infrastructure already added 1 to the counter, we add
>     // n_rounds - 1 here.
>     syscall_handler.increment_syscall_count_by(&SyscallSelector::Keccak, n_rounds - 1);
> ```

Do we want to check that `n_rounds > 1` or is it always satisfied?



_Code quote:_
```XML
syscall_handler.increment_syscall_count_by(&SyscallSelector::Keccak, n_rounds - 1);
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @giladchase and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 587 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYSvH6m0UioBHfkvC2j:-NYSwkdb3rgjuLdF5BqQ:bo6oq39) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L587)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

but I guess I sould check that 
`n_rounds` > 0
good catch.
</blockquote></details>

Yes, I meant `>=1`, sorry for the confusion. And great.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @giladchase and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYTBLwzBoheEvkeGwOV:-NYTBLwzBoheEvkeGwOW:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L25)):*
> ```XML
> use thiserror::Error;
> 
> use super::keccak;
> ```





_Suggestion:_
```XML
use crate::execution::syscalls::keccak
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYTC6HI4lsyUXK-SDJW:-NYTC6HI4lsyUXK-SDJX:bkpk30t) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L215)):*
> ```XML
>             }
> 
>             SyscallSelector::Keccak => self.execute_syscall(vm, keccak, constants::KECCAK_GAS_COST),
> ```

Do we support keccak also for cairo 0 contracts?



_Code quote:_
```XML
SyscallSelector::Keccak => self.execute_syscall(vm, keccak, constants::KECCAK_GAS_COST),
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYTBAe7D6s5tMqUJKVO:-NYTBAe7D6s5tMqUJKVP:b-gakaye) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L20)):*
> ```XML
>     SyscallHintProcessor,
> };
> use crate::abi::constants::{self, KECCAK_ROUND_COST_GAS_COST};
> ```

And then use `constants::KECCAK_ROUND_COST_GAS_COST`



_Suggestion:_
```XML
use crate::abi::constants;
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 575 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYT8Gf_6ViSCObOLxzb:-NYT8Gf_6ViSCObOLxzc:b-5ii48r) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L575)):*
> ```XML
>     }
> 
>     let gas_cost = Felt252::from_u64(n_rounds as u64 * KECCAK_ROUND_COST_GAS_COST).unwrap();
> ```

Do we know that `n_rounds < 2^64 -1`?



_Suggestion:_
```XML
let gas_cost = Felt252::from(n_rounds as u64 * KECCAK_ROUND_COST_GAS_COST);
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 587 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYSvH6m0UioBHfkvC2j:-NYT4irQEhT7XDZYV-sk:bh8wk5r) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L587)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes, I meant `>=1`, sorry for the confusion. And great.
</blockquote></details>

Actually, `1` is valid but in that case we don't need to call `increment_syscall_count_by`, right?

**Review by noaov1 — COMMENTED** [review]
Can you please add it to the `os_resources.rs` file?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620#-:-NYXn2VV2Fziw4waAfOK:b-dfl64g)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @giladchase and @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYTC6HI4lsyUXK-SDJW:-NYlhDde3Bm-sFIBOEgX:b32wsm) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L215)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we support keccak also for cairo 0 contracts?
</blockquote></details>

no

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 587 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYSvH6m0UioBHfkvC2j:-NYlhYGMBI64qF7DEkpO:b-wfxmfb) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L587)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Actually, `1` is valid but in that case we don't need to call `increment_syscall_count_by`, right?
</blockquote></details>

We still need to handle the case of 0 rounds.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYTBLwzBoheEvkeGwOV:-NYlhEgZ5O3AKn6J8eJc:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L25)):*
> ```XML
> use thiserror::Error;
> 
> use super::keccak;
> ```

done
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYTBAe7D6s5tMqUJKVO:-NYlhNnWDJtZ0cNNu48u:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L20)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And then use `constants::KECCAK_ROUND_COST_GAS_COST`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 525 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYSu5FJDHO_5zd4wFM-:-NYlhS9p70vfO-DEqQ6R:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L525)):*
> ```XML
> }
> 
> #[derive(Debug, Eq, PartialEq)]
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 575 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYT8Gf_6ViSCObOLxzb:-NYlhXQP6udmxDp-0a11:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L575)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we know that `n_rounds < 2^64 -1`?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 9 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: 10 of 11 files reviewed, 6 unresolved discussions (waiting on @giladchase and @noaov1)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
done.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620#-:-NYmC1eu4DUZQHovuFR4:b-7rl0jd)* status: 10 of 12 files reviewed, 6 unresolved discussions (waiting on @giladchase and @noaov1)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 587 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYSvH6m0UioBHfkvC2j:-NYqQO0CATCD1kOPYx0T:bosym5v) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L587)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We still need to handle the case of 0 rounds.
</blockquote></details>

You are absolutely right. It will be as the keccak builtin was never called when `n_round = 0`?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 574 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYmk7O84lN4t-qVPw2x:-NYmk7O84lN4t-qVPw2y:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8d63c50de6ccb18797a5d4f35c17eae25409748/crates/blockifier/src/execution/syscalls/mod.rs#L574)):*
> ```XML
> 
> // Keccak syscall.
> #[derive(Debug, Eq, PartialEq)]
> ```





_Suggestion:_
```XML
// Keccak syscall.

#[derive(Debug, Eq, PartialEq)]
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 642 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYqaATg857iObcIbtv1:-NYqaATg857iObcIbtv2:bvx31tg) ([raw file](https://github.com/starkware-libs/blockifier/blob/13767414d9ace988c5712eadaacf2cd9c077c882/crates/blockifier/src/execution/syscalls/mod.rs#L642)):*
> ```XML
>     for chunk in data.chunks(KECCAK_FULL_RATE_IN_WORDS) {
>         for (i, val) in chunk.iter().enumerate() {
>             state[i] ^= val.to_u64().unwrap();
> ```

Do we know that the input will contain numbers `< 2^64 -1`? Do we want to panic if that is not the case?



_Code quote:_
```XML
 state[i] ^= val.to_u64().unwrap();
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 574 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYmk7O84lN4t-qVPw2x:-NYqod0E1iakd78J9FhK:b-pgqk5u) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8d63c50de6ccb18797a5d4f35c17eae25409748/crates/blockifier/src/execution/syscalls/mod.rs#L574)):*
> ```XML
> 
> // Keccak syscall.
> #[derive(Debug, Eq, PartialEq)]
> ```

what? why do we have that convention?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 574 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYmk7O84lN4t-qVPw2x:-NYqp0aoCtXC1ORpcl_c:b-jellhs) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8d63c50de6ccb18797a5d4f35c17eae25409748/crates/blockifier/src/execution/syscalls/mod.rs#L574)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what? why do we have that convention?
</blockquote></details>

Ok, I guess its because it described the next section and not just the struct.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 587 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYSvH6m0UioBHfkvC2j:-NYqpILl6zftQPKu-Q1L:b-4m1bxg) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac884e394fcde3292cc82c2b6d0abf64bb32a25e/crates/blockifier/src/execution/syscalls/mod.rs#L587)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You are absolutely right. It will be as the keccak builtin was never called when `n_round = 0`?
</blockquote></details>

yes, the builtin is not used when `n_round = 0`.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 642 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYqaATg857iObcIbtv1:-NYqpR3vArEnf6egMnCI:bllklvi) ([raw file](https://github.com/starkware-libs/blockifier/blob/13767414d9ace988c5712eadaacf2cd9c077c882/crates/blockifier/src/execution/syscalls/mod.rs#L642)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we know that the input will contain numbers `< 2^64 -1`? Do we want to panic if that is not the case?
</blockquote></details>

Yes, it shouldn't happen. Do you think we shouldn't panic here? What should we do?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 642 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYqaATg857iObcIbtv1:-NYqw0S7592E9-x35ozK:b-mf2j5p) ([raw file](https://github.com/starkware-libs/blockifier/blob/13767414d9ace988c5712eadaacf2cd9c077c882/crates/blockifier/src/execution/syscalls/mod.rs#L642)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Yes, it shouldn't happen. Do you think we shouldn't panic here? What should we do?
</blockquote></details>

Maybe it's better to return an error? (this way only the transaction will fail and not the entire batcher)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 5 of 10 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 573 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYmJG6j-bRqmVzeBX-a:-NYmJG6j-bRqmVzeBX-b:b-svec3q) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8d63c50de6ccb18797a5d4f35c17eae25409748/crates/blockifier/src/execution/syscalls/mod.rs#L573)):*
> ```XML
> }
> 
> // Keccak syscall.
> ```

Add a blank line below.



_Code quote:_
```XML
// Keccak syscall.
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 610 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYmJhV90Dy7H6NrgEvz:-NYmJhV90Dy7H6NrgEw-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8d63c50de6ccb18797a5d4f35c17eae25409748/crates/blockifier/src/execution/syscalls/mod.rs#L610)):*
> ```XML
>     remaining_gas: &mut Felt252,
> ) -> SyscallResult<KeccakResponse> {
>     let input_len = (request.input_end - request.input_start)?;
> ```





_Suggestion:_
```XML
input_length
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 615 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYmJk4lAniUXUGtxFVZ:-NYmJk4lAniUXUGtxFV_:b-628y1g) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8d63c50de6ccb18797a5d4f35c17eae25409748/crates/blockifier/src/execution/syscalls/mod.rs#L615)):*
> ```XML
>     let (n_rounds, r) = num_integer::div_rem(input_len, KECCAK_FULL_RATE_IN_WORDS);
> 
>     if r != 0 {
> ```

What's the full name? Is it the remainder? I think it can be the variable's name.



_Code quote:_
```XML
r
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 584 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYrFSbRDfe8xVfUYpUQ:-NYrFSbRDfe8xVfUYpUR:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/314a1e9e32468e9440bc8ae10e4fcf73f732054f/crates/blockifier/src/execution/syscalls/mod.rs#L584)):*
> ```XML
>     fn read(vm: &VirtualMachine, ptr: &mut Relocatable) -> SyscallResult<KeccakRequest> {
>         let input_start = vm.get_relocatable(*ptr)?;
>         *ptr += 1;
> ```





_Suggestion:_
```XML
*ptr = (*ptr + 1)?;
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 642 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYqaATg857iObcIbtv1:-NYrHVNf5FQyxVqepp8l:bp4dky3) ([raw file](https://github.com/starkware-libs/blockifier/blob/13767414d9ace988c5712eadaacf2cd9c077c882/crates/blockifier/src/execution/syscalls/mod.rs#L642)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe it's better to return an error? (this way only the transaction will fail and not the entire batcher)
</blockquote></details>

What error should I return?

Note that the syscall does not fail in the case.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 642 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYqaATg857iObcIbtv1:-NYrSAYa6S8B89nNWUZg:bt9oz9j) ([raw file](https://github.com/starkware-libs/blockifier/blob/13767414d9ace988c5712eadaacf2cd9c077c882/crates/blockifier/src/execution/syscalls/mod.rs#L642)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What error should I return?

Note that the syscall does not fail in the case.
</blockquote></details>

I guess I could use

SyscallExecutionError::InvalidSyscallInput

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 573 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYmJG6j-bRqmVzeBX-a:-NYrHilc5FS8uW8yYsRS:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8d63c50de6ccb18797a5d4f35c17eae25409748/crates/blockifier/src/execution/syscalls/mod.rs#L573)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a blank line below.
</blockquote></details>

done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 615 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYmJk4lAniUXUGtxFVZ:-NYrIHpDErQQrSKnFRbs:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8d63c50de6ccb18797a5d4f35c17eae25409748/crates/blockifier/src/execution/syscalls/mod.rs#L615)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What's the full name? Is it the remainder? I think it can be the variable's name.
</blockquote></details>

done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 642 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYqaATg857iObcIbtv1:-NYrSiuBE3Cq1lKLFU9u:bu0itiu) ([raw file](https://github.com/starkware-libs/blockifier/blob/13767414d9ace988c5712eadaacf2cd9c077c882/crates/blockifier/src/execution/syscalls/mod.rs#L642)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess I could use

SyscallExecutionError::InvalidSyscallInput
</blockquote></details>

actually, I'm not sure what to put in input: StarkFelt.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 584 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYrFSbRDfe8xVfUYpUQ:-NYrIRqS3wcaidxqNHj_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/314a1e9e32468e9440bc8ae10e4fcf73f732054f/crates/blockifier/src/execution/syscalls/mod.rs#L584)):*
> ```XML
>     fn read(vm: &VirtualMachine, ptr: &mut Relocatable) -> SyscallResult<KeccakRequest> {
>         let input_start = vm.get_relocatable(*ptr)?;
>         *ptr += 1;
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 610 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYmJhV90Dy7H6NrgEvz:-NYrSt-J9SHNxZWrV2d0:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/a8d63c50de6ccb18797a5d4f35c17eae25409748/crates/blockifier/src/execution/syscalls/mod.rs#L610)):*
> ```XML
>     remaining_gas: &mut Felt252,
> ) -> SyscallResult<KeccakResponse> {
>     let input_len = (request.input_end - request.input_start)?;
> ```

done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 642 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYqaATg857iObcIbtv1:-NYrbY15BeVkjoR55D2X:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/13767414d9ace988c5712eadaacf2cd9c077c882/crates/blockifier/src/execution/syscalls/mod.rs#L642)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

actually, I'm not sure what to put in input: StarkFelt.
</blockquote></details>

done

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r3, 2 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/src/abi/constants.rs` line 60 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYrxQwv5tFU3sdaQNOn:-NYrxQwv5tFU3sdaQNOo:b-v53dqy) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ad378ab85830c1e8b1af20ff71106864b20c317/crates/blockifier/src/abi/constants.rs#L60)):*
> ```XML
> pub const SEND_MESSAGE_TO_L1_GAS_COST: u64 = 50 * STEP_GAS_COST;
> pub const STORAGE_READ_GAS_COST: u64 = 50 * STEP_GAS_COST;
> pub const STORAGE_WRITE_GAS_COST: u64 = 50 * STEP_GAS_COST;
> ```

Keep alphabetized?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 294 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYrxZO_4APFcSMUGOyl:-NYrxZO_4APFcSMUGOym:b5uoirp) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ad378ab85830c1e8b1af20ff71106864b20c317/crates/blockifier/src/execution/syscalls/hint_processor.rs#L294)):*
> ```XML
>     }
> 
>     pub fn read_next_syscall_selector(
> ```

Why is this`pub`lic?



_Code quote:_
```XML
read_next_syscall_selector
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/constants.rs` line 60 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYrxQwv5tFU3sdaQNOn:-NYs0B477cLEuErfxi6I:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ad378ab85830c1e8b1af20ff71106864b20c317/crates/blockifier/src/abi/constants.rs#L60)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Keep alphabetized?
</blockquote></details>

done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 294 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/620#-NYrxZO_4APFcSMUGOyl:-NYs-znv1hBoWN2XHMiT:bvth56w) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ad378ab85830c1e8b1af20ff71106864b20c317/crates/blockifier/src/execution/syscalls/hint_processor.rs#L294)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this`pub`lic?
</blockquote></details>

reverted

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/620)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
