### PR TITLE
feat(fee): check gas amount including discounted data gas

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1374)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1374)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1374#-Np-71Ix0P7pvgXvfIwo:-Np-71Ix0P7pvgXvfIwp:b-hppl4j) ([raw file](https://github.com/starkware-libs/blockifier/blob/d9dcc51ce42f8edc36d0ea23c41245a506d05a2f/crates/blockifier/src/fee/fee_test.rs#L110)):*
> ```XML
>         )
>     } else {
>         assert_matches!(report.error(), None);
> ```

better than `assert!(report.error().is_none());`, because the error is output on failure



_Code quote:_
```XML
assert_matches!(report.error(), None);
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1374#-:-Np-_IyX1NzJobf_GNVf:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1374)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1374)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1374#-Np-htejAHYakziRPJ1S:-Np-htejAHYakziRPJ1T:bcrxyxq) ([raw file](https://github.com/starkware-libs/blockifier/blob/e08ccc92a9ada29019bb645c3c72daeedae8afda/crates/blockifier/src/fee/fee_checks.rs#L125)):*
> ```XML
>                     block_context.block_info.gas_prices.get_data_gas_price_by_fee_type(&fee_type);
>                 let total_discounted_gas_used =
>                     gas_usage + (blob_gas_usage * data_gas_price) / gas_price;
> ```

Protect from 0.



_Code quote:_
```XML
) / gas_price;
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1374)* status: all files reviewed, 2 unresolved discussions

___
*[`crates/blockifier/src/fee/fee_test.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1374#-Np-jqwB0yWfJcKpmrGQ:-Np-jqwB0yWfJcKpmrGR:b-okc1mt) ([raw file](https://github.com/starkware-libs/blockifier/blob/e08ccc92a9ada29019bb645c3c72daeedae8afda/crates/blockifier/src/fee/fee_test.rs#L70)):*
> ```XML
>     #[case] data_gas_price: u128,
>     #[case] l1_gas_used: usize,
>     #[case] l1_data_gas_used: usize,
> ```

It could have been more readable without these



_Suggestion:_
```XML
fn test_discounted_gas_overdraft(
    #[case] l1_gas_used: usize,
    #[case] l1_data_gas_used: usize,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1374)* status: all files reviewed, 2 unresolved discussions

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1374#-Np-htejAHYakziRPJ1S:-Np-wTTSBnhL0zgjEa2n:b-h6exrm) ([raw file](https://github.com/starkware-libs/blockifier/blob/e08ccc92a9ada29019bb645c3c72daeedae8afda/crates/blockifier/src/fee/fee_checks.rs#L125)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Protect from 0.
</blockquote></details>

If gas price is zero here, IMO we want to panic (all txs will fail in this block...)
___
*[`crates/blockifier/src/fee/fee_test.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1374#-Np-jqwB0yWfJcKpmrGQ:-Np-wOHt06IwaeHCOz2i:b-otrfve) ([raw file](https://github.com/starkware-libs/blockifier/blob/e08ccc92a9ada29019bb645c3c72daeedae8afda/crates/blockifier/src/fee/fee_test.rs#L70)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It could have been more readable without these
</blockquote></details>

I parametrize with them (sometimes `1000,10` and sometimes `10,1000`)

**Pull request merged**
