### PR TITLE
get_execution_info: Test deprecated contract

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 349 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj1x3egCsuPcNi2mrHg:-Nj1x3egCsuPcNi2mrHh:b-iz4woo) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1c4daf8fa75424ffa527352d756903f3d0992c1/crates/blockifier/src/test_utils.rs#L349)):*
> ```XML
>             contract_address!(TEST_PAIR_SKELETON_CONTRACT_ADDRESS1),
>             class_hash!(TEST_PAIR_SKELETON_CONTRACT_CLASS_HASH),
>         ),
> ```

there is duplication here with `get_address_to_v0_class_hash`; please extract common map setup and use it twice



_Code quote:_
```XML
        (contract_address!(TEST_CONTRACT_ADDRESS), class_hash!(TEST_CLASS_HASH)),
        (contract_address!(LEGACY_TEST_CONTRACT_ADDRESS), class_hash!(LEGACY_TEST_CLASS_HASH)),
        (contract_address!(TEST_CONTRACT_ADDRESS_2), class_hash!(TEST_CLASS_HASH)),
        (
            contract_address!(TEST_PAIR_SKELETON_CONTRACT_ADDRESS1),
            class_hash!(TEST_PAIR_SKELETON_CONTRACT_CLASS_HASH),
        ),
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj1xIpn8Ii1e3zr3zwL:-Nj1xIpn8Ii1e3zr3zwM:b-fcorwk) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1c4daf8fa75424ffa527352d756903f3d0992c1/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L279)):*
> ```XML
> 
>     let tx_hash = TransactionHash(stark_felt!(1991_u16));
>     let max_fee = if is_legacy { Fee(0) } else { Fee(42) };
> ```

why zero fee in legacy test?



_Code quote:_
```XML
Fee(0)
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 281 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj1xtwf8qOmwSx3mDGg:-Nj1xtwf8qOmwSx3mDGh:b9m92i7) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1c4daf8fa75424ffa527352d756903f3d0992c1/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L281)):*
> ```XML
>     let max_fee = if is_legacy { Fee(0) } else { Fee(42) };
>     let nonce = Nonce(stark_felt!(3_u16));
>     let sender_address = ContractAddress(patricia_key!(test_contract_address));
> ```

doesn't this work?



_Suggestion:_
```XML
contract_address!(test_contract_address)
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 349 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj1x3egCsuPcNi2mrHg:-Nj2HdnuCEW9DODaob-_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1c4daf8fa75424ffa527352d756903f3d0992c1/crates/blockifier/src/test_utils.rs#L349)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there is duplication here with `get_address_to_v0_class_hash`; please extract common map setup and use it twice
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj1xIpn8Ii1e3zr3zwL:-Nj2HelLAWDtzRRac2pI:b-da8vfe) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1c4daf8fa75424ffa527352d756903f3d0992c1/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L279)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why zero fee in legacy test?
</blockquote></details>

Right, I can send Fee>0 for legacy test.
Updated!
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 281 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj1xtwf8qOmwSx3mDGg:-Nj2I03Q3F_umZYgyHEU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1c4daf8fa75424ffa527352d756903f3d0992c1/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L281)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

doesn't this work?
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo1/legacy_test_contract.cairo` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj2VfoG7iH65P1ohjYj:-Nj2VfoG7iH65P1ohjYk:bsizssw) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd2ae2cce29e2dad91f0889eba3ffac5c7fd2910/crates/blockifier/feature_contracts/cairo1/legacy_test_contract.cairo#L61)):*
> ```Cairo
> 
>     #[external(v0)]
>     fn test_get_execution_info(
> ```

Delete everything except this function

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/legacy_test_contract.cairo` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj2VfoG7iH65P1ohjYj:-Nj2_8nb9zE2hQmDRmBj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd2ae2cce29e2dad91f0889eba3ffac5c7fd2910/crates/blockifier/feature_contracts/cairo1/legacy_test_contract.cairo#L61)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Delete everything except this function
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 256 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj2dLlN5S8J_-3t5y8j:-Nj2dLlN5S8J_-3t5y8k:by0k81w) ([raw file](https://github.com/starkware-libs/blockifier/blob/9afe15333211e1f9b06989f93f1a11f6a061b673/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L256)):*
> ```XML
>     false;
>     "Legacy test contract. Execute execution mode: block info should be as usual. Tx version 3.")]
> fn test_get_execution_info(
> ```

Can you assert somewhere that the compiler version of the contract is `2.1.0`?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils.rs` line 271 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj2tFjHACPKKj6g6eWi:-Nj2tFjHACPKKj6g6eWj:bcofw9g) ([raw file](https://github.com/starkware-libs/blockifier/blob/9afe15333211e1f9b06989f93f1a11f6a061b673/crates/blockifier/src/test_utils.rs#L271)):*
> ```XML
>     );
> 
>     map
> ```

use `from`



_Suggestion:_
```XML
    HashMap::from([
        (contract_address!(TEST_CONTRACT_ADDRESS), class_hash!(TEST_CLASS_HASH)),
        (contract_address!(TEST_CONTRACT_ADDRESS_2), class_hash!(TEST_CLASS_HASH)),
        (
            contract_address!(TEST_PAIR_SKELETON_CONTRACT_ADDRESS1),
            class_hash!(TEST_PAIR_SKELETON_CONTRACT_CLASS_HASH),
        )
    ])
```
___
*[`crates/blockifier/src/test_utils.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj2tXcT0AMSVuvHUg6C:-Nj2tXcT0AMSVuvHUg6D:bf1ka70) ([raw file](https://github.com/starkware-libs/blockifier/blob/9afe15333211e1f9b06989f93f1a11f6a061b673/crates/blockifier/src/test_utils.rs#L318)):*
> ```XML
>         class_hash!(SECURITY_TEST_CLASS_HASH),
>     );
>     address_to_class_hash
> ```

why did you remove the legacy class here?



_Code quote:_
```XML
    address_to_class_hash.insert(
        contract_address!(SECURITY_TEST_CONTRACT_ADDRESS),
        class_hash!(SECURITY_TEST_CLASS_HASH),
    );
    address_to_class_hash
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 271 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj2tFjHACPKKj6g6eWi:-Nj35bSq8xRo0nJO9wpj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9afe15333211e1f9b06989f93f1a11f6a061b673/crates/blockifier/src/test_utils.rs#L271)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `from`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-Nj2tXcT0AMSVuvHUg6C:-Nj35n2qAiPFI-LPPFeh:b-et55r7) ([raw file](https://github.com/starkware-libs/blockifier/blob/9afe15333211e1f9b06989f93f1a11f6a061b673/crates/blockifier/src/test_utils.rs#L318)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why did you remove the legacy class here?
</blockquote></details>

Since it is Cairo 1 contract. It maps the Cairo 0 contracts here.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-:-Nj3N4eEAjcnh8fgwpWg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 231 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-NjCS-olENFLl7Ck6Gck:-NjCS-olENFLl7Ck6Gcl:b-3qpsm1) ([raw file](https://github.com/starkware-libs/blockifier/blob/3d2bfb3f3c5f1826936e34db1786842108ccbde6/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L231)):*
> ```XML
>     }
> }
> ```

ChatGPT's suggestion:

```rs
fn verify_compiler_version(file_path: &str, expected_version: &str) {
    // Read and parse file content.
    let mut content = String::new();
    File::open(file_path)
        .and_then(|mut file| file.read_to_string(&mut content))
        .expect("Unable to read the file");
    let raw_contract: serde_json::Value = serde_json::from_str(&content).expect("Error parsing JSON");

    // Verify version.
    if let Some(compiler_version) = raw_contract["compiler_version"].as_str() { 
        assert_eq!(compiler_version, expected_version); 
    } else { 
        panic!("'expected_version' not found or not a valid string in JSON."); }
    }
}
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 224 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-NjCXG3t4pHAMvo69gHr:-NjCXG3t4pHAMvo69gHs:bg0tm9k) ([raw file](https://github.com/starkware-libs/blockifier/blob/61602b7042ff0a89e0fd9071ba139ce68d2baceb/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L224)):*
> ```XML
>         assert_eq!(compiler_version, expected_version);
>     } else {
>         panic!("'expected_version' not found or not a valid string in JSON.");
> ```

My bad.



_Suggestion:_
```XML
compiler_version
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 224 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-NjCXG3t4pHAMvo69gHr:-NjCZFtSA6leAQljTj5v:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/61602b7042ff0a89e0fd9071ba139ce68d2baceb/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L224)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

My bad.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1113#-:-NjHPyNhBo70r78VPuZH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
