### PR TITLE
refactor(transaction): use ClassInfo in Declare transaction

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)* status: 0 of 12 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3GJbz0HZJvpQqSL3j:-Nq3GJbz0HZJvpQqSL3k:b-xu81fk) (no related file):*
Python's PR: 
https://reviewable.io/reviews/starkware-industries/starkware/33853

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)* status: all files reviewed, 12 unresolved discussions (waiting on @avi-starkware, @ayeletstarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 560 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3MjFn34P-vc18bx88:-Nq3MjFn34P-vc18bx89:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/account_transaction.rs#L560)):*
> ```XML
>             self.calldata_length(),
>             self.signature_length(),
>         );
> ```





_Suggestion:_
```XML
        let actual_cost_builder = ActualCostBuilder::new(
            tx_context,
            self.tx_type(),
            self.calldata_length(),
            self.signature_length(),
        );
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NHpOCzOnbzkZ9jw3:-Nq3NHpOCzOnbzkZ9jw4:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transaction_utils.rs#L58)):*
> ```XML
> }
> 
> // TODO(Ayelet,01/03/2024): Consider removing this function.
> ```

Why?



_Code quote:_
```XML
Consider removing this function.
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NL3lAxflPceSUk2f:-Nq3NL3lAxflPceSUk2g:bum11ae) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transaction_utils.rs#L60)):*
> ```XML
> // TODO(Ayelet,01/03/2024): Consider removing this function.
> pub fn verify_contract_class_version(
>     contract_class: &ContractClass,
> ```

I think it's better, but why was it needed?



_Code quote:_
```XML
contract_class: &ContractClass,
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NaXW8jae5ZYhbucD:-Nq3NaXW8jae5ZYhbucE:ba09g6t) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transaction_utils.rs#L72)):*
> ```XML
>                     cairo_version: 0,
>                 })
>             }
> ```

x2
Does it work?



_Suggestion:_
```XML
            if let TransactionVersion::ZERO | TransactionVersion::ONE = declare_version {
                return Ok(())
            }
            
            Err(TransactionExecutionError::ContractClassVersionMismatch {
                declare_version,
                cairo_version: 0,
            })
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NiWZA78alwCiJwPy:-Nq3NiWZA78alwCiJwPz:bhdj3v6) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transactions.rs#L190)):*
> ```XML
>             starknet_api::transaction::DeclareTransaction::V0(_)
>             | starknet_api::transaction::DeclareTransaction::V1(_) => {
>                 state.set_contract_class(class_hash, self.class_info.contract_class.clone())?;
> ```

Can we use the getter above?



_Code quote:_
```XML
self.class_info.contract_class.clone()
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NlPRB5EM_6K8sY8x:-Nq3NlPRB5EM_6K8sY8y:brhumzt) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transactions.rs#L206)):*
> ```XML
>                         state.set_contract_class(
>                             class_hash,
>                             self.class_info.contract_class.clone(),
> ```

Same here.



_Code quote:_
```XML
self.class_info.contract_class.clone(),
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1095 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3MvEKDtwpZ-ZeQCkC:-Nq3MvEKDtwpZ-ZeQCkD:b-6a6oym) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transactions_test.rs#L1095)):*
> ```XML
>         sierra_program_length,
>         abi_length: 100,
>     };
> ```

Consider a test util that does all that (with the arguments you need).



_Code quote:_
```XML
    let sierra_program_length = calculate_sierra_program_length_for_testing(tx_version);
    let class_info = ClassInfo {
        contract_class: empty_contract.get_class(),
        sierra_program_length,
        abi_length: 100,
    };
```
___
*[`crates/native_blockifier/src/py_declare.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NsOq9__9DH8RQ8Iz:-Nq3NsOq9__9DH8RQ8J-:bpvxya6) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/native_blockifier/src/py_declare.rs#L133)):*
> ```XML
>     }?;
> 
>     let class_info = ClassInfo::try_from(py_class_info)?;
> ```

Pass directly.



_Code quote:_
```XML
ClassInfo::try_from(py_class_info)?
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3O33qDZLlm0ciHkS9:-Nq3O33qDZLlm0ciHkSA:b-skcnju) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/native_blockifier/src/py_transaction.rs#L159)):*
> ```XML
>         } else {
>             ContractClassV1::try_from_json_string(&py_class_info.raw_contract_class)?.into()
>         };
> ```

Why not use the existing conversion?



_Code quote:_
```XML
        let contract_class: ContractClass = if py_class_info.sierra_program_length == 0 {
            ContractClassV0::try_from_json_string(&py_class_info.raw_contract_class)?.into()
        } else {
            ContractClassV1::try_from_json_string(&py_class_info.raw_contract_class)?.into()
        };
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3O6JS6VxB6cZiAeK2:-Nq3O6JS6VxB6cZiAeK3:b-gxo9x5) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/native_blockifier/src/py_transaction.rs#L162)):*
> ```XML
> 
>         let sierra_program_length = py_class_info.sierra_program_length;
>         let abi_length = py_class_info.abi_length;
> ```

Consider passing directly.



_Code quote:_
```XML
        let sierra_program_length = py_class_info.sierra_program_length;
        let abi_length = py_class_info.abi_length;
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3OBvS8li4aUgkkc1h:-Nq3OBvS8li4aUgkkc1i:b5s87r1) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/native_blockifier/src/py_validator.rs#L81)):*
> ```XML
>         // so they are skipped here.
>         if let AccountTransaction::DeployAccount(_deploy_account_tx) = account_tx {
>             let (_tx_execution_info, _py_bouncer_info) = self.execute(tx, None)?;
> ```

Give this a name?



_Code quote:_
```XML
None
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)* status: all files reviewed, 9 unresolved discussions (waiting on @avi-starkware, @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 560 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3MjFn34P-vc18bx88:-Nq6xYjs8pzSGLbW9gWA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/account_transaction.rs#L560)):*
> ```XML
>             self.calldata_length(),
>             self.signature_length(),
>         );
> ```

Done.
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NHpOCzOnbzkZ9jw3:-Nq7AP3XAdKXpB8ImBwu:bon3eq7) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transaction_utils.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Gilad didn't like it. I'll consult with him. Removed for now.
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NL3lAxflPceSUk2f:-Nq77j-i7XRD_VnCvi-U:b-wfzqtm) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transaction_utils.rs#L60)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it's better, but why was it needed?
</blockquote></details>

 In the `DeclareTransaction.create` function, the `verify_contract_class_version` previously requested ownership of `contract_class` and returned it without modifications. This prevents passing `class_info.contract_class` to `Self{}` at the end of the function due to a "partially moved value" issue.
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NaXW8jae5ZYhbucD:-Nq7Ajln8JPCH5nyoBTx:bb77ufg) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transaction_utils.rs#L72)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

x2
Does it work?
</blockquote></details>

Yes.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NiWZA78alwCiJwPy:-Nq710gM6dnkqiBtnwSY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transactions.rs#L190)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we use the getter above?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NlPRB5EM_6K8sY8x:-Nq7151tBhb284lDJUyN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transactions.rs#L206)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1095 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3MvEKDtwpZ-ZeQCkC:-Nq76fgsDuTjzl63hKpR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/blockifier/src/transaction/transactions_test.rs#L1095)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider a test util that does all that (with the arguments you need).
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_declare.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3NsOq9__9DH8RQ8Iz:-Nq76zDn2xgBFztwt4ZT:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/native_blockifier/src/py_declare.rs#L133)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Pass directly.
</blockquote></details>

Done
___
*[`crates/native_blockifier/src/py_transaction.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3O33qDZLlm0ciHkS9:-Nq7Ec8_D_hSypqcqogz:b-hi8t5m) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/native_blockifier/src/py_transaction.rs#L159)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not use the existing conversion?
</blockquote></details>

The existing conversion relies on `TransactionVersion`. Since `From` functions can't accept two inputs directly, this solution distinguishes between versions without explicitly receiving the transaction version as an argument.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3O6JS6VxB6cZiAeK2:-Nq77C0U5bUgZGm3pPn0:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/native_blockifier/src/py_transaction.rs#L162)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider passing directly.
</blockquote></details>

Done
___
*[`crates/native_blockifier/src/py_validator.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3OBvS8li4aUgkkc1h:-Nq7C9-p4hXRvM6JiH2H:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/native_blockifier/src/py_validator.rs#L81)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give this a name?
</blockquote></details>

Done

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @ayeletstarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3O33qDZLlm0ciHkS9:-Nq7OQ5nENwpYwecTxxp:blysek2) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/native_blockifier/src/py_transaction.rs#L159)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

The existing conversion relies on `TransactionVersion`. Since `From` functions can't accept two inputs directly, this solution distinguishes between versions without explicitly receiving the transaction version as an argument.
</blockquote></details>

A bit flaky, suggested an additional check above.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq7ODyKEGkega40rgkU:-Nq7ODyKEGkega40rgkV:b39vzm7) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4101717b7d64c763f026fadb2f8bb1a0164ed9b/crates/native_blockifier/src/py_transaction.rs#L132)):*
> ```XML
>         TransactionType::Declare => {
>             let non_optional_py_class_info: PyClassInfo = optional_py_class_info
>                 .expect("A class info must be passed in a Declare transaction.");
> ```

Please add an additional check here, that `version >= 2 == sierra_length != 0` (in case it does not hold, return an appropriate error).



_Code quote:_
```XML
            let non_optional_py_class_info: PyClassInfo = optional_py_class_info
                .expect("A class info must be passed in a Declare transaction.");
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq7Niv7-pR72hv9f-Nu:-Nq7Niv7-pR72hv9f-Nv:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4101717b7d64c763f026fadb2f8bb1a0164ed9b/crates/native_blockifier/src/py_validator.rs#L81)):*
> ```XML
>         // so they are skipped here.
>         if let AccountTransaction::DeployAccount(_deploy_account_tx) = account_tx {
>             let empty_class_info_for_deploy_account_tx = None;
> ```





_Suggestion:_
```XML
sentinel_class_info
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq3O33qDZLlm0ciHkS9:-Nq7_uxP4XCMbbMtgzaV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5a9d3fd32750d63f7512f87efe278e23cfab5f9e/crates/native_blockifier/src/py_transaction.rs#L159)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

A bit flaky, suggested an additional check above.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq7ODyKEGkega40rgkU:-Nq7_eJp0BwqJdCQx_PE:b-vehnlg) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4101717b7d64c763f026fadb2f8bb1a0164ed9b/crates/native_blockifier/src/py_transaction.rs#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please add an additional check here, that `version >= 2 == sierra_length != 0` (in case it does not hold, return an appropriate error).
</blockquote></details>

Is it okay to add it inside `py_declare`? We already have version parsing from `py_tx` there.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 147 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1456#-Nq7ekyKEux_-OeDGGNB:-Nq7ekyKEux_-OeDGGNC:b-75nmpn) ([raw file](https://github.com/starkware-libs/blockifier/blob/91ff56dc1f7e47e6f94af8154004148c3f929dc1/crates/native_blockifier/src/py_transaction.rs#L147)):*
> ```XML
> pub struct PyClassInfo {
>     pub raw_contract_class: String,
>     pub sierra_program_length: usize,
> ```

Had to include it because we use `sierra_program_length` in the version/length check in `py_declare`.

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1456)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Pull request merged**
