### PR TITLE
Add test_utils::initial_test_state

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1225)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1225)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @giladchase, @MohammadNassar1, and @zuphitf)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-Nl2ZMrg7qYYzSGzl9IZ:-Nl2ZMrg7qYYzSGzl9I_:btf7wkd) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ea3a24031a9256e9a2e663445959f168fb7715f/crates/blockifier/src/test_utils/initial_test_state.rs#L23)):*
> ```XML
> /// Also sets the two fee token address to the correct ERC20 class hash, and performs some initial
> /// setup of the token contracts.
> /// Takes the state from `full_unfunded_test_state` and sets a non-zero fee token balance for each
> ```

whoops
blocking self to update the doc



_Code quote:_
```XML
Takes the state from `full_unfunded_test_state` 
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1225)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, @MohammadNassar1, and @zuphitf)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-Nl2YBJg2quFwRPoU-2P:-Nl2YBJg2quFwRPoU-2Q:b-vxmom3) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ea3a24031a9256e9a2e663445959f168fb7715f/crates/blockifier/src/test_utils/initial_test_state.rs#L36)):*
> ```XML
>     // Declare and deploy instances of all contracts.
>     for version in CairoVersion::iter() {
>         for mut contract in FeatureContract::iter() {
> ```

This means all the states built with this function will have all the contracts declared and deployed.
This means irrelevant contracts will be a part of the state for some tests. (This is redundant - but maybe it is not a big deal?) 
WDYT about passing a list of required contracts as a parameter?



_Code quote:_
```XML
for mut contract in FeatureContract::iter() {
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-Nl2YRhCEQM_rWQwadXb:-Nl2YRhCEQM_rWQwadXc:b-rtyg4z) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ea3a24031a9256e9a2e663445959f168fb7715f/crates/blockifier/src/transaction/transactions_test.rs#L44)):*
> ```XML
> use crate::state::state_api::{State, StateReader};
> use crate::test_utils::cached_state::create_test_state;
> use crate::test_utils::contracts::FeatureContract as FC;
> ```

No need to abriviate. I think the full name is more readable.



_Code quote:_
```XML
use crate::test_utils::contracts::FeatureContract as FC;
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-Nl2cNDj44bH0MwG2Lcq:-Nl2cNDj44bH0MwG2Lcr:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ea3a24031a9256e9a2e663445959f168fb7715f/crates/blockifier/src/test_utils/initial_test_state.rs#L55)):*
> ```XML
>                 address_to_class_hash
>                     .insert(contract.get_address(instance_id), contract.get_class_hash());
>             }
> ```





_Suggestion:_
```XML
            let class_hash = contract.get_class_hash();
            class_hash_to_class.insert(class_hash, contract.get_class());
            for instance_id in 0..N_INSTANCES {
                address_to_class_hash
                    .insert(contract.get_address(instance_id), class_hash);
            }
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-Nl2b3w_6jhjv6OVtNE9:-Nl2b3w_6jhjv6OVtNEA:b-rlcnav) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ea3a24031a9256e9a2e663445959f168fb7715f/crates/blockifier/src/test_utils/initial_test_state.rs#L36)):*
> ```XML
>     // Declare and deploy instances of all contracts.
>     for version in CairoVersion::iter() {
>         for mut contract in FeatureContract::iter() {
> ```

(This suggestion is very silly). 
This tells the story more correctly. 

Or does that not match how rust works?



_Suggestion:_
```XML
    for mut contract in FeatureContract::iter() {
        for version in CairoVersion::iter() {
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-Nl2cNDj44bH0MwG2Lcq:-Nl2fcK6-U6h-NFOuOh4:bsoceq4) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ea3a24031a9256e9a2e663445959f168fb7715f/crates/blockifier/src/test_utils/initial_test_state.rs#L55)):*
> ```XML
>                 address_to_class_hash
>                     .insert(contract.get_address(instance_id), contract.get_class_hash());
>             }
> ```

@dorimedini-starkware look at slack.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1225)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @giladchase, @MohammadNassar1, and @zuphitf)

___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-Nl2b3w_6jhjv6OVtNE9:-Nl3-buVC1LECvWlv1rv:b-132xnq) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ea3a24031a9256e9a2e663445959f168fb7715f/crates/blockifier/src/test_utils/initial_test_state.rs#L36)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

(This suggestion is very silly). 
This tells the story more correctly. 

Or does that not match how rust works?
</blockquote></details>

no longer relevant
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-Nl2gD9oBrYDiVp3EAvf:-Nl3-hSL3tw5uO_4Gq41:b-132xnq) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ea3a24031a9256e9a2e663445959f168fb7715f/crates/blockifier/src/test_utils/initial_test_state.rs#L72)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

These are not all the contracts, there is also "faulty account". 
I understand why this one does not count, but maybe at some point, it will.  When this happens, it should be clear this account should be added to this list to fund it.
</blockquote></details>

no longer relevant
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-Nl2h6prADPpX3n-p4A1:-Nl3-jcF2MCT4cnA3D3w:b-132xnq) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ea3a24031a9256e9a2e663445959f168fb7715f/crates/blockifier/src/test_utils/initial_test_state.rs#L89)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Extract list of `account_types_for_minting_and_funding`.
</blockquote></details>

no longer relevant

**Review by ArniStarkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-:-Nl3GZNj9NpjSmr-f28W:bnfp4nl)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, @MohammadNassar1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1263 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1225#-Nl3F0CsBe9Fi1P3aBSr:-Nl3F0CsBe9Fi1P3aBSs:bw7ried) ([raw file](https://github.com/starkware-libs/blockifier/blob/8b1997e77bf4afdb411d9ce361b0f8a98d3e873c/crates/blockifier/src/transaction/transactions_test.rs#L1263)):*
> ```XML
>         version += query_version_base;
>     }
>     let sender_address = account.get_address(0);
> ```

About the method `get_address`. 
1. Start the docstring with: `Returns the address of the instance with the given instance ID.`
2. Maybe rename the method? At first glance, It is unclear why the method `get_address` will require a parameter. Part of the confusion is that `FeatureContract` objects don't stand for an instance of a contract - but for the class of a contract (And some info about the corresponding list of instances). 



For another PR.



_Code quote:_
```XML
 account.get_address(0);
```

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1225)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @giladchase, @MohammadNassar1, and @zuphitf)

**Pull request merged**
