### PR TITLE
refactor(native_blockifier): remove unused py objects

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1864)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1864)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/native_blockifier/src/py_objects.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1864#-NxC2g5BBrQ54eprIShC:-NxC2g5C7Owng193_dFQ:b-yk9qym) ([raw file](https://github.com/starkware-libs/blockifier/blob/850861608c514e8786a2bc150dc2dc6b5d44f874/crates/native_blockifier/src/py_objects.rs#L1)):*
> ```XML
> use std::collections::HashMap;
> ```

Sorry, this is a renaming of `py_transaction_execution_info.rs` + deletion of unused classes. Not a new file

**Review by noaov1 — APPROVED** [review]
Can you please check it in python?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1864#-:-NxCPOAk9ou0ESVXUFbM:b-vqx0fv)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by Yoni-Starkware — COMMENTED** [review]
Here: https://github.com/starkware-industries/starkware/pull/34920

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1864#-:-NxCPh6C68ZI_RRhzWYx:bsv94ky)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1864)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Pull request merged**
