### PR TITLE
chore: fix import in check_entry_point_execution_error

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1778)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1778#-:-NvCPYmbA4uUn2bo8MWy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @MohammadNassar1)

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1778)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @giladchase, and @MohammadNassar1)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1778#-NvCSx0f3CBPTCpGKfah):*




_Suggestion:_
```
refactor: move imports to macros
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1778)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @barak-b-starkware, @giladchase, and @MohammadNassar1)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1778#-NvCSx0f3CBPTCpGKfah):*
Done.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1778#-:-NvCUagHDaekhRV-XOyj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @MohammadNassar1)

**Pull request merged**
