### PR TITLE
refactor(concurrency): change initial_state of VersionedState to Arc<…

### PR DESCRIPTION
**Pull request by barak-b-starkware**
…Mutex<_>>

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1925)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1925)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-Nz74E0n7SdSPOaZXu2f:-Nz74E0o3nCS37tvi6Ek:bwzaggb) ([raw file](https://github.com/starkware-libs/blockifier/blob/aebdfae147532271574dfc1546a25e9b5dbab6d4/crates/blockifier/src/concurrency/versioned_state.rs#L29)):*
> ```XML
>     // The VersionedState is passed across threads. The generic S represents the block state and is
>     // not necessarily thread-safe. For example, if the block state is of type CachedState, it
>     // would have RefCell members. Thus, it needs to be wrapped by Arc with a Mutex.
> ```

Re "it needs": does it fail to compile? are you worried about runtime errors?



_Code quote:_
```XML
    // not necessarily thread-safe. For example, if the block state is of type CachedState, it
    // would have RefCell members. Thus, it needs to be wrapped by Arc with a Mutex.
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-Nz74yaN0ARDbr8rjNgZ:-Nz74yaN0ARDbr8rjNg_:bhbii3q) ([raw file](https://github.com/starkware-libs/blockifier/blob/aebdfae147532271574dfc1546a25e9b5dbab6d4/crates/blockifier/src/concurrency/versioned_state.rs#L45)):*
> ```XML
>     pub fn new(initial_state: Arc<Mutex<S>>) -> Self {
>         VersionedState {
>             initial_state,
> ```

Why not? (I'll retract if I see the answer in next PRs)



_Suggestion:_
```XML
    pub fn new(initial_state: S) -> Self {
        VersionedState {
            initial_state: Arc::new(Mutex::new(initial_state),
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-Nz75A_-4PS00w9hx62V:-Nz75A_-4PS00w9hx62W:b-61qn4j) ([raw file](https://github.com/starkware-libs/blockifier/blob/aebdfae147532271574dfc1546a25e9b5dbab6d4/crates/blockifier/src/concurrency/versioned_state.rs#L267)):*
> ```XML
>                     .initial_state
>                     .lock()
>                     .expect("Failed to acquire state lock.")
> ```

Implement a getter for this (`self.initial_state()`)



_Code quote:_
```XML
                let initial_value = state
                    .initial_state
                    .lock()
                    .expect("Failed to acquire state lock.")
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1925)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-Nz74E0n7SdSPOaZXu2f:-Nz7XCpeALV_bUKa27pT:b-a9fxvx) ([raw file](https://github.com/starkware-libs/blockifier/blob/aebdfae147532271574dfc1546a25e9b5dbab6d4/crates/blockifier/src/concurrency/versioned_state.rs#L29)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Re "it needs": does it fail to compile? are you worried about runtime errors?
</blockquote></details>

"It needs" because of the compiler constraints. The compiler doesn't allow the ref cells not to be wrapped up by arc<mutex<>>.
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-Nz74yaN0ARDbr8rjNgZ:-Nz7X_vG78GkU4o-XaGE:bk0u4jv) ([raw file](https://github.com/starkware-libs/blockifier/blob/aebdfae147532271574dfc1546a25e9b5dbab6d4/crates/blockifier/src/concurrency/versioned_state.rs#L45)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not? (I'll retract if I see the answer in next PRs)
</blockquote></details>

I think it's more natural to create the mutex at the block level (in our case, in the transaction executor), given how we use it.
Moreover, @noaov1 mentioned that in the future, we might get rid of the higher level mutex (the one initialized by `ThreadSafeVersionedState` so we access specific cells in the block level by a mutex, so it makes sense that the block level state would be locked from the beginning.

But it can be changed, WDYT?
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-Nz75A_-4PS00w9hx62V:-Nz7c4LMB5_32NI-a6Jy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/aebdfae147532271574dfc1546a25e9b5dbab6d4/crates/blockifier/src/concurrency/versioned_state.rs#L267)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Implement a getter for this (`self.initial_state()`)
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-:-Nz7yDPhCyyRv4A-nZ1L:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware, @meship-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1925)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, @MohammadNassar1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-Nz74yaN0ARDbr8rjNgZ:-NzDHKeUAdoanyKdMjW4:b-djvdmi) ([raw file](https://github.com/starkware-libs/blockifier/blob/aebdfae147532271574dfc1546a25e9b5dbab6d4/crates/blockifier/src/concurrency/versioned_state.rs#L45)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I think it's more natural to create the mutex at the block level (in our case, in the transaction executor), given how we use it.
Moreover, @noaov1 mentioned that in the future, we might get rid of the higher level mutex (the one initialized by `ThreadSafeVersionedState` so we access specific cells in the block level by a mutex, so it makes sense that the block level state would be locked from the beginning.

But it can be changed, WDYT?
</blockquote></details>

It is not possible (without more sophisticated code). If we do that we will move the initial state (in our case, the block state) to be owned by the versioned state.
Why is this problematic? The block state is shared between chunks, plus it needs to be updated after the chunk. We cannot move it.
(plus it is a field of the transaction executor which cannot be moved)
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-NzDIFY54MEB6ykBEhxp:-NzDIFY6AoQViWN5N9sI:b-vzzh5z) ([raw file](https://github.com/starkware-libs/blockifier/blob/ebefdd4cc72021b9ebde2efdeb2969ed5f71dcab/crates/blockifier/src/concurrency/versioned_state.rs#L29)):*
> ```XML
>     // The VersionedState is passed across threads. The generic S represents the block state and is
>     // not necessarily thread-safe. For example, if the block state is of type CachedState, it
>     // would have RefCell members. Thus, it needs to be wrapped by Arc with a Mutex.
> ```

The `Arc` is needed because the block state is shared between chunks.
The mutex is needed for thread safety. 



_Code quote:_
```XML
    // The VersionedState is passed across threads. The generic S represents the block state and is
    // not necessarily thread-safe. For example, if the block state is of type CachedState, it
    // would have RefCell members. Thus, it needs to be wrapped by Arc with a Mutex.
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-NzDHpUI-vGvbiEAqvYA:-NzDHpUI-vGvbiEAqvYB:b8du9dj) ([raw file](https://github.com/starkware-libs/blockifier/blob/ebefdd4cc72021b9ebde2efdeb2969ed5f71dcab/crates/blockifier/src/concurrency/versioned_state.rs#L55)):*
> ```XML
>     }
> 
>     fn get_initial_state(&self) -> MutexGuard<'_, S> {
> ```

Idiomatic Rust tends to favour omitting `get` for simplicity and readability when it’s clear from the context that a method is a getter.



_Suggestion:_
```XML
fn initial_state(&self) -> MutexGuard<'_, S> {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-NzDJbubCf1JVM2W958F:-NzDJbubCf1JVM2W958G:bko5o8p) ([raw file](https://github.com/starkware-libs/blockifier/blob/ebefdd4cc72021b9ebde2efdeb2969ed5f71dcab/crates/blockifier/src/concurrency/versioned_state_test.rs#L76)):*
> ```XML
>         Arc::new(Mutex::new(VersionedState::new(Arc::new(Mutex::new(cached_state)))));
> 
>     let safe_versioned_state = ThreadSafeVersionedState(Arc::clone(&versioned_state));
> ```

Consider using `safe_versioned_state_for_testing` 
(in the entire file, when possible)



_Code quote:_
```XML
    let versioned_state =
        Arc::new(Mutex::new(VersionedState::new(Arc::new(Mutex::new(cached_state)))));

    let safe_versioned_state = ThreadSafeVersionedState(Arc::clone(&versioned_state));
```

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1925#-:-NzSB9Ly7wgkZ24JNqOz:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, and @MohammadNassar1)

**Pull request closed without merging**
