### PR TITLE
fix(concurrency): stop the transaction committer when the scheduler is done

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1989)

### CODE REVIEW

**Review by Yoni-Starkware — APPROVED** [review]
Cool, how did you find this?
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1989#-:-O-ao8DBCx1953CSUtLg:bksjic8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

**Comment by avi-starkware** [comment]
@barak-b-starkware said his flow test got stuck in an infinite loop, so I tried to think of places where the scheduler might get stuck.
This is probably not the bug from Barak's flow test because his flow test does not use the method `halt_scheduler`, but it is still a bug.

**Review by Yoni-Starkware — APPROVED** [review]
Then @OriStarkware must see this bug in his env. Please make sure

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1989#-:-O-aq5ox8f5LE5Ap5-HG:bauil0f)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @OriStarkware)

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1989#-O-cDCAR8SGFJ1r9K-PL:-O-cDCAR8SGFJ1r9K-PM:b-jxkter) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1b8d0584a4daf61d0468736a4a48d9b1d82d807/crates/blockifier/src/concurrency/scheduler.rs#L31)):*
> ```XML
>             *self.commit_index_guard < self.scheduler.chunk_size,
>             "The commit index must be less than the chunk size, since the scheduler is not done."
>         );
> ```

Why do we need this assertion? It feels trivial/redundant. What do I miss here?



_Code quote:_
```XML
        assert!(
            *self.commit_index_guard < self.scheduler.chunk_size,
            "The commit index must be less than the chunk size, since the scheduler is not done."
        );
```

**Pull request merged**
