### PR TITLE
move fee and resource calculation closer to execution

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/809)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/809)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 588 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/809#-NapBcbI2UuOumDxwPr9:-NapBcbI2UuOumDxwPrA:b-xh6lcg) ([raw file](https://github.com/starkware-libs/blockifier/blob/d926fc424ea5d4c0a67cdb9475b9d13dc6f59453/crates/blockifier/src/transaction/account_transaction.rs#L588)):*
> ```XML
>         // transactions of are non-revertible iff they are of version 0.
>         self.get_account_transaction_context().is_v0()
>     }
> ```

prefer positive check (in general, + here it's much shorter)



_Suggestion:_
```XML
    fn is_revertible(&self) -> bool {
        // Reverting a Declare or Deploy transaction is not currently supported in the OS.
        // V0 transactions do not have validation; we cannot deduct fee for execution. Thus, invoke
        // transactions of are non-revertible iff they are of version 0.
        matches!(self, Self::Invoke(_)) && !self.get_account_transaction_context().is_v0()
    }
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/809)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/809#-NapCQm02YWPraAV_sum:-NapCQm02YWPraAV_sun:b-bkn6dq) ([raw file](https://github.com/starkware-libs/blockifier/blob/d926fc424ea5d4c0a67cdb9475b9d13dc6f59453/crates/blockifier/src/transaction/account_transaction.rs#L507)):*
> ```XML
>                 if actual_fee > max_fee {
>                     // Insufficient max fee. Revert the execution and charge what is available.
>                     let final_fee = max_fee;
> ```

why define this var?



_Code quote:_
```XML
let final_fee = max_fee;
```

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/transaction/account_transaction.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/809#-NapCQm02YWPraAV_sum:-Napw2bE0w53O3y4En2d:bljij4b) ([raw file](https://github.com/starkware-libs/blockifier/blob/d926fc424ea5d4c0a67cdb9475b9d13dc6f59453/crates/blockifier/src/transaction/account_transaction.rs#L507)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why define this var?
</blockquote></details>

In the next PR it's going to have a real usage in this block since two values will be possible  (`if user_final_balance < actual_fee then final_fee = ...`)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/809#-:-Naq-qvKDYt761dz9oWD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/809#-NapCQm02YWPraAV_sum:-Naq-axx1q6oj_7u7CsV:b9h7o07) ([raw file](https://github.com/starkware-libs/blockifier/blob/d926fc424ea5d4c0a67cdb9475b9d13dc6f59453/crates/blockifier/src/transaction/account_transaction.rs#L507)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

In the next PR it's going to have a real usage in this block since two values will be possible  (`if user_final_balance < actual_fee then final_fee = ...`)
</blockquote></details>

ah ok
so this is a splitting artifact
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 588 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/809#-NapBcbI2UuOumDxwPr9:-Naq-kxH9PrcAI22Pya_:b-nmxdcg) ([raw file](https://github.com/starkware-libs/blockifier/blob/d926fc424ea5d4c0a67cdb9475b9d13dc6f59453/crates/blockifier/src/transaction/account_transaction.rs#L588)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

prefer positive check (in general, + here it's much shorter)
</blockquote></details>

ok... I see the advantage of using `match`
this is no future-proof for new tx types
unblocking

**Pull request merged**
