### PR TITLE
Create common test utils, change AccountTransaction::Declare construc…

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
…tion

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/575)

### CODE REVIEW

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/575#-:-NXL2IUu2vw8J6Hqm0gh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/575)* status: all files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/575#-NXPC0a92PoFqAh_Q4O0:-NXPC0aB2O40kIvUBulU:b5v29ew) (no related file):*
required for [this](https://reviewable.io/reviews/starkware-libs/blockifier/577) (along with [this](https://reviewable.io/reviews/starkware-libs/blockifier/576))

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/575)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by alonh5 — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/575)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/575)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/575)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/575#-:-NYIzaBcC5jzsK6xgWgI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
