### PR TITLE
Add mid-validation cartesian test

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1167)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1167)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1167#-NjwbMXh8B0E-Y1SfGtl:-NjwbMXi2AkLIf1wYzh6:b-rll82e) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e0a437b6ad0da06d38d8f4ba12277c333bf7684/crates/blockifier/src/transaction/execution_flavors_test.rs#L191)):*
> ```XML
>     let max_fee = Fee(MAX_FEE);
> 
>     // Create two states, one of which contains a contract that can fail validation on demand.
> ```

Please fix.



_Code quote:_
```XML
    // Create two states, one of which contains a contract that can fail validation on demand.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1167)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1167#-:-NkAPioICrD6FVE67CO3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
