### PR TITLE
Block syscalls of type get_block_info in validate.

### PR DESCRIPTION
**Pull request by ArniStarkware**
I am adding tests in this PR or the next one.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1014)

### CODE REVIEW

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1014#-:-NhMjr3YBjXGTFku5JJa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
Just wondering: what about `get_execution_info` syscall? It returns information from the block as well.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1014#-:-NhNgJHj4xHX6D5GZAZc:b-gov0n1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
It is already covered; see #1010.
Note `get_execution_info` is a Cairo 1 syscall. The behavior this syscall now has in validate mode is that it returns a trivial "`block_info`" (all zeros).
This PR, focuses on Cairo 0 syscalls. We took a different approach here.

**Review by noaov1 — APPROVED** [review]
Missed that. Thanks.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1014#-:-NhQCijl9W7Bmx7fz7pt:b-lnb52s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
