### PR TITLE
Refactor `InvokeTransaction` creation in `native_blockifier`.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/960)

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/960)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul and @NirLevi-starkware)

___
*[`crates/native_blockifier/src/py_invoke_function.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/960#-NfiktDQ3Ziy_bImHrMT:-NfiktDQ3Ziy_bImHrMU:b-jw4g34) ([raw file](https://github.com/starkware-libs/blockifier/blob/44106a1381d0d24f989d9f9f25e6c5dd1e0c9781/crates/native_blockifier/src/py_invoke_function.rs#L106)):*
> ```XML
>             let py_declare_tx: PyInvokeTransactionV0 = py_tx.extract()?;
>             let declare_tx = InvokeTransactionV0::try_from(py_declare_tx)?;
>             Ok(starknet_api::transaction::InvokeTransaction::V0(declare_tx))
> ```

In all versions



_Suggestion:_
```XML
            let py_invoke_tx: PyInvokeTransactionV0 = py_tx.extract()?;
            let invoke_tx = InvokeTransactionV0::try_from(py_declare_tx)?;
            Ok(starknet_api::transaction::InvokeTransaction::V0(declare_tx))
```

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/960)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @NirLevi-starkware)

___
*[`crates/native_blockifier/src/py_invoke_function.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/960#-Nfilvk68ct-QSsKWYtJ:-Nfilvk68ct-QSsKWYtK:b-o16ej2) ([raw file](https://github.com/starkware-libs/blockifier/blob/44106a1381d0d24f989d9f9f25e6c5dd1e0c9781/crates/native_blockifier/src/py_invoke_function.rs#L35)):*
> ```XML
>             contract_address: ContractAddress::try_from(tx.contract_address.0)?,
>             entry_point_selector: EntryPointSelector(tx.entry_point_selector.0),
>             calldata: Calldata(from_py_felts(tx.calldata).into()),
> ```

Too long?



_Suggestion:_
```XML
calldata: Calldata(Arc::from(from_py_felts(tx.calldata))),
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/960#-NfimXVc90vygrMCmKQa:-NfimXVdDWfDp5i-MBqf:benamew) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fb3261306ef4760f41cb2fcfbd43132ed31ae28/crates/native_blockifier/src/py_transaction.rs#L242)):*
> ```XML
>         })),
>         3 => {
>             let common_tx_fields = build_common_tx_fields(tx)?;
> ```

Can be deleted now?



_Code quote:_
```XML
build_common_tx_fields
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/960)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @NirLevi-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_invoke_function.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/960#-Nfilvk68ct-QSsKWYtJ:-Nfjhh83C-zw8fU2mS9F:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/44106a1381d0d24f989d9f9f25e6c5dd1e0c9781/crates/native_blockifier/src/py_invoke_function.rs#L35)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Too long?
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_invoke_function.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/960#-NfiktDQ3Ziy_bImHrMT:-Nfjb6lR5VjP0WCHqGvY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/44106a1381d0d24f989d9f9f25e6c5dd1e0c9781/crates/native_blockifier/src/py_invoke_function.rs#L106)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In all versions
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/960#-NfimXVc90vygrMCmKQa:-Nfjb6L31_4q6d3uTMMw:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4fb3261306ef4760f41cb2fcfbd43132ed31ae28/crates/native_blockifier/src/py_transaction.rs#L242)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can be deleted now?
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/960#-:-Nfjm1UD1tLcTOv4lvlF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NirLevi-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/960)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NirLevi-starkware)

**Pull request merged**
