### PR TITLE
refactor(fee): merge TransactionExecutionInfo calculations for Bouncer

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1533)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1533)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-NqvsalG8Xqasa_H760X:-NqvsalH5XyAtTP7HRYa:b-a1zxrk) (no related file):*
Python's PR:
https://reviewable.io/reviews/starkware-industries/starkware/34034

___

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1533)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/call_info.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-Nqw-txB0DT65sAxrT1s:-Nqw-txCBkt3KMQDFxSm:b32wzj) ([raw file](https://github.com/starkware-libs/blockifier/blob/870f65394df954ab79ad982e1f680c195516f5bc/crates/blockifier/src/execution/call_info.rs#L176)):*
> ```XML
>     }
> 
>     pub fn calculate_tx_execution_summary(&self) -> TxExecutionSummary {
> ```

x2



_Suggestion:_
```XML
pub fn summarise(&self) -> ExecutionSummary {
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-Nqw19QR7Q3kQ5PudsV8:-Nqw19QR7Q3kQ5PudsV9:b-otckr8) ([raw file](https://github.com/starkware-libs/blockifier/blob/870f65394df954ab79ad982e1f680c195516f5bc/crates/blockifier/src/execution/call_info.rs#L178)):*
> ```XML
>     pub fn calculate_tx_execution_summary(&self) -> TxExecutionSummary {
>         let mut executed_class_hashes = HashSet::new();
>         let mut visited_storage_entries = HashSet::new();
> ```

Add type annotations.



_Suggestion:_
```XML
        let mut executed_class_hashes = HashSet<...>::new();
        let mut visited_storage_entries = HashSet<...>::new();
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-Nqw1oRMEyIu2-I5vSCA:-Nqw1oRN30zQGORxDzHC:b-b1lodu) ([raw file](https://github.com/starkware-libs/blockifier/blob/870f65394df954ab79ad982e1f680c195516f5bc/crates/blockifier/src/transaction/objects.rs#L180)):*
> ```XML
> }
> 
> pub struct TxExecutionSummary {
> ```

Try to use `derive_more::Add`.



_Code quote:_
```XML
TxExecutionSummary
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-Nqw2LIr96g4XAaQSNEH:-Nqw2LIr96g4XAaQSNEI:ba81rdo) ([raw file](https://github.com/starkware-libs/blockifier/blob/870f65394df954ab79ad982e1f680c195516f5bc/crates/blockifier/src/transaction/objects.rs#L238)):*
> ```XML
>         self.revert_error.is_some()
>     }
> ```

Refactor to use a more idiomatic loop.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-Nqw2SbkEK8ux945Vlrd:-Nqw2SbkEK8ux945Vlre:ba3dfmt) ([raw file](https://github.com/starkware-libs/blockifier/blob/870f65394df954ab79ad982e1f680c195516f5bc/crates/native_blockifier/src/transaction_executor.rs#L89)):*
> ```XML
>                 // state changes and execution info rather than the cumulative state attributes.
> 
>                 // TODO(Elin, 01/06/2024): consider traversing the calls to collect data once.
> ```

Remove.



_Code quote:_
```XML
// TODO(Elin, 01/06/2024): consider traversing the calls to collect data once.
```

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1533)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 181 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-NqwHMxKEqTfitUI5rJU:-NqwHMxLDyEPTK6ccDnd:bhb4kr7) ([raw file](https://github.com/starkware-libs/blockifier/blob/5807d70238a86733237295632a2ff6de8f81d6a1/crates/blockifier/src/transaction/objects.rs#L181)):*
> ```XML
> 
> #[derive(Default)]
> pub struct ExecutionSummary {
> ```

Move to `call_info.rs`.



_Code quote:_
```XML
ExecutionSummary
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-NqwHQiv3_XHoLMOozlK:-NqwHQiv3_XHoLMOozlL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5807d70238a86733237295632a2ff6de8f81d6a1/crates/blockifier/src/transaction/objects.rs#L186)):*
> ```XML
>     pub n_events: usize,
> }
> impl ExecutionSummary {
> ```





_Suggestion:_
```XML
}

impl ExecutionSummary {
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-NqwHU5e3ioaid6Sx39t:-NqwHU5e3ioaid6Sx39u:b-9r4pgc) ([raw file](https://github.com/starkware-libs/blockifier/blob/5807d70238a86733237295632a2ff6de8f81d6a1/crates/blockifier/src/transaction/objects.rs#L188)):*
> ```XML
> impl ExecutionSummary {
>     pub fn merge(&mut self, other: ExecutionSummary) {
>         self.executed_class_hashes.extend(other.executed_class_hashes.iter().cloned());
> ```

Can we remove this? Given that this function owns `other`?



_Code quote:_
```XML
.cloned()
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 253 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-NqwHvXhA6xlbXqVQ6Ai:-NqwHvXhA6xlbXqVQ6Aj:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5807d70238a86733237295632a2ff6de8f81d6a1/crates/blockifier/src/transaction/objects.rs#L253)):*
> ```XML
>         }
>         result
>     }
> ```





_Suggestion:_
```XML
pub fn summarize(&self) -> ExecutionSummary {
    self.non_optional_call_infos()
        .iter()
        .map(|call_info| call_info.summarize())
        .fold(Default::default(), |acc, summary| acc.merge(summary))
}
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1533)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 239 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-Nr4XOPY-O7NFdzoE46W:-Nr5GduP9qH4prFMDElS:b-er15o1) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6808b75dae2528cfc8522c8eb316f8191b4586b/crates/blockifier/src/transaction/objects.rs#L239)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you change your code so this will work?
</blockquote></details>

I attempted to use the default sum method, but it failed because ExecutionSummary type doesn't directly support summing. 

Implementing an iterator for ExecutionSummary also did not resolve the issue. 

I tried to create a custom sum function, but it was similar to the original approach, using fold with map.

**Review by elintul — DISMISSED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1533)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-:-NrZQo9f834uQwdrS1y8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1533)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/blockifier/src/execution/call_info.rs` line 199 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-NrZ_uU9BwMU2d0-_-To:-NrZ_uU9BwMU2d0-_-Tp:b-7dklw8) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ea5404de681f7fafc3346517eb7c58eab6d23e3/crates/blockifier/src/execution/call_info.rs#L199)):*
> ```XML
>     /// Returns the sum of events in CallInfo and its inner_calls
>     pub fn get_number_of_events(&self) -> usize {
>         self.into_iter().map(|call_info| call_info.execution.events.len()).sum()
> ```

Remove unused functions



_Code quote:_
```XML
    /// Returns the sum of events in CallInfo and its inner_calls
    pub fn get_number_of_events(&self) -> usize {
        self.into_iter().map(|call_info| call_info.execution.events.len()).sum()
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1533)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 199 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-NrZ_uU9BwMU2d0-_-To:-NrZlSM62H1vxpKwfcNh:b-ip9sn) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ea5404de681f7fafc3346517eb7c58eab6d23e3/crates/blockifier/src/execution/call_info.rs#L199)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Remove unused functions
</blockquote></details>

it's here #1562

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1533#-:-Nr_Cj9X8Zbzsjuk2TPZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
