### PR TITLE
feat(concurrency): add commit transactions phase to worker loop

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906)

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyGVcP41gIdI7WBY-qZ:-NyGVcP55jZdwf1CsTS0:b-p66127) ([raw file](https://github.com/starkware-libs/blockifier/blob/ccdecf16fbb060c2d056f92b63d17db6eecc06a6/crates/blockifier/src/concurrency/worker_logic.rs#L78)):*
> ```XML
>     }
> 
>     fn commit_transactions_while_possible(&self) -> Result<(), StateError> {
> ```

I think it might be better not to have this function and put all the logic directly in `run`.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyJMVFwBq-X9XL0Kg_o:-NyJMVFwBq-X9XL0Kg_p:b-3oxf75) ([raw file](https://github.com/starkware-libs/blockifier/blob/ccdecf16fbb060c2d056f92b63d17db6eecc06a6/crates/blockifier/src/concurrency/scheduler.rs#L141)):*
> ```XML
>     pub fn done_committing_transactions(&self) {
>         self.commit_lock.store(false, Ordering::Release);
>     }
> ```

Hmm, that's roughly the implementation of `try_lock`.
It seems like you should use it (on self.commit_index) instead of these functions. I think it's better to use the native mutex object,  which releases the lock automatically when dropped.

Let's talk today



_Code quote:_
```XML
    pub fn should_commit_transactions(&self) -> bool {
        self.commit_lock
            .compare_exchange_weak(false, true, Ordering::Acquire, Ordering::Relaxed)
            .is_ok()
    }

    pub fn done_committing_transactions(&self) {
        self.commit_lock.store(false, Ordering::Release);
    }
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyJO7PRAs88uANY2LUW:-NyJO7PRAs88uANY2LUX:b92k2cc) ([raw file](https://github.com/starkware-libs/blockifier/blob/6fc2a062572c35e8b89b1522ffcb186d53c2ccca/crates/blockifier/src/concurrency/worker_logic.rs#L81)):*
> ```XML
>     fn commit_transactions_while_possible(&self) -> Result<(), StateError> {
>         if self.scheduler.should_commit_transactions() {
>             while let Some(tx_index) = self.scheduler.try_commit() {
> ```

I think it fails when called with `tx_index = chunk_size - 1`



_Code quote:_
```XML
Some(tx_index) = self.scheduler.try_commit() {
```

**Review by Yoni-Starkware — COMMENTED** [review]
Please rebase this PR over `main` - it should not be dependent of the `halt` PR (assume no bouncer for now)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-:-NyJPjyT2tF53fQLhLrB:b-jgddcg)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

**Comment by avi-starkware** [comment]
+reviewer:@barak-b-starkware

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyJMVFwBq-X9XL0Kg_o:-NyKmHZP8yvWa3z-NDSK:b-t70n0k) ([raw file](https://github.com/starkware-libs/blockifier/blob/ccdecf16fbb060c2d056f92b63d17db6eecc06a6/crates/blockifier/src/concurrency/scheduler.rs#L141)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Hmm, that's roughly the implementation of `try_lock`.
It seems like you should use it (on self.commit_index) instead of these functions. I think it's better to use the native mutex object,  which releases the lock automatically when dropped.

Let's talk today
</blockquote></details>

I changed the implementation of the commit lock. Take a look.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyJO7PRAs88uANY2LUW:-NyKaP0-6y9EnRLtgKhG:b-sl9chs) ([raw file](https://github.com/starkware-libs/blockifier/blob/6fc2a062572c35e8b89b1522ffcb186d53c2ccca/crates/blockifier/src/concurrency/worker_logic.rs#L81)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think it fails when called with `tx_index = chunk_size - 1`
</blockquote></details>

You are right.
Fixed.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyLbtjcBHRUQj7SPxy2:-NyLqfyG3y18j_oCd7QK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/04d599b68dc825974d11316403d71a153b7eb9b8/crates/blockifier/src/concurrency/worker_logic.rs#L82)):*
> ```XML
>             while let Some(tx_index) = transaction_committer.try_commit() {
>                 let commit_failed = !self.commit_tx(tx_index)?;
>                 if commit_failed {
> ```

Done.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 38 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyL_Z697xmDh--2LKEq:-NyLqa7q-gO3y-V2xcDX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/04d599b68dc825974d11316403d71a153b7eb9b8/crates/blockifier/src/concurrency/scheduler.rs#L38)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use early return
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 78 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyLaaRn4jq8RoI8qzVc:-NyLqdAP0U9lruySv3xE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/04d599b68dc825974d11316403d71a153b7eb9b8/crates/blockifier/src/concurrency/worker_logic.rs#L78)):*
> ```XML
>     }
> 
>     fn commit_transactions_while_possible(&self) -> Result<(), StateError> {
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 78 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyLdAA92rth3l6ejCqZ:-NyLqeNLAJ5lmA8mlxlc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/04d599b68dc825974d11316403d71a153b7eb9b8/crates/blockifier/src/concurrency/worker_logic.rs#L78)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use `StateResult` x2
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 145 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyLcVHF-IlN3Ii72eA0:-NyLqiUr11NKIde6yWPb:b-3xlxmi) ([raw file](https://github.com/starkware-libs/blockifier/blob/04d599b68dc825974d11316403d71a153b7eb9b8/crates/blockifier/src/concurrency/worker_logic.rs#L145)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

That's not true, right? you should commit if the execution failed (and if the tx is too big)
</blockquote></details>

I edited the docstring to make it slightly more organized and fixed your comment.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-:-NyM3elq4Th4QHO6OrWB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @meship-starkware, and @noaov1)

**Review by noaov1 — COMMENTED** [review]
Nice!

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-:-NyPn9AY9VnK0dl_JHUQ:b-83sjoh)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @barak-b-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyPl3hD10oyZBVeSkNV:-NyPl3hD10oyZBVeSkNW:br27huo) ([raw file](https://github.com/starkware-libs/blockifier/blob/fcd35e3ae56f45051734838849470ca111f605e5/crates/blockifier/src/concurrency/worker_logic.rs#L81)):*
> ```XML
>             while let Some(tx_index) = transaction_committer.try_commit() {
>                 let commit_succeeded = self.commit_tx(tx_index)?;
>                 if !commit_succeeded {
> ```

I wonder if we want to be specific with the error (no room error).
Not sure what should be done in case of other error.
I think that the `commit_tx` should not return a `StateError`, but rather panic in case of unsuccessful access to state. 



_Code quote:_
```XML
                let commit_succeeded = self.commit_tx(tx_index)?;
                if !commit_succeeded {
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyPl3hD10oyZBVeSkNV:-NyPnld22GtE5a_C2VHE:b-5v4rn9) ([raw file](https://github.com/starkware-libs/blockifier/blob/fcd35e3ae56f45051734838849470ca111f605e5/crates/blockifier/src/concurrency/worker_logic.rs#L81)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if we want to be specific with the error (no room error).
Not sure what should be done in case of other error.
I think that the `commit_tx` should not return a `StateError`, but rather panic in case of unsuccessful access to state.
</blockquote></details>

This all depends on the implementation of `commit_tx`.
Do you want me to change it?
@meship-starkware still has a PR that depends on it...

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-NyPl3hD10oyZBVeSkNV:-NyPqdhhCK0JDSrwgKA4:b4r72ds) ([raw file](https://github.com/starkware-libs/blockifier/blob/fcd35e3ae56f45051734838849470ca111f605e5/crates/blockifier/src/concurrency/worker_logic.rs#L81)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This all depends on the implementation of `commit_tx`.
Do you want me to change it?
@meship-starkware still has a PR that depends on it...
</blockquote></details>

No need. Just a wonder. It's okay for now.

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @barak-b-starkware, @meship-starkware, and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906#-:-NyU7n7sAoMk4YaZvf-1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @meship-starkware)

**Review by avi-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1906)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @meship-starkware)

**Pull request merged**
