### PR TITLE
Separate Cairo0 execution

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a> 
    * **PR #449** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/449" target="_blank">Graphite</a> 
      * **PR #451** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/451" target="_blank">Graphite</a> 
        * **PR #450** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/450" target="_blank">Graphite</a> 
          * **PR #452** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/452" target="_blank">Graphite</a> 
            * **PR #458** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/458" target="_blank">Graphite</a> 
              * **PR #459** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/459" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/459?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV8qPgM38SqyreSIcqa:-NV8qPgN1E9CaXaPKK0M:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/77a22f29f16885ec759c9a06542babd9148d9a7e/crates/blockifier/src/execution.rs#L6)):*
> ```XML
> pub mod entry_point;
> pub mod errors;
> pub mod exec_v0;
> ```





_Suggestion:_
```XML
deprecated_execution
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV8pX7O4eeF0R7PfDD7:-NV8pX7O4eeF0R7PfDD8:bbps8xu) ([raw file](https://github.com/starkware-libs/blockifier/blob/77a22f29f16885ec759c9a06542babd9148d9a7e/crates/blockifier/src/execution/contract_class.rs#L61)):*
> ```XML
> }
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize)]
> pub struct ContractClassV0Inner {
> ```

Please add a blank line above.



_Code quote:_
```XML
#[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize)]
pub struct ContractClassV0Inner {
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV8q3Ft0tPmzU7xBUkl:-NV8q3FuBKc-jRi3q_CW:b-mimgli) ([raw file](https://github.com/starkware-libs/blockifier/blob/77a22f29f16885ec759c9a06542babd9148d9a7e/crates/blockifier/src/execution/contract_class.rs#L82)):*
> ```XML
> impl ContractClassV1 {
>     fn constructor_selector(&self) -> Option<EntryPointSelector> {
>         Some(self.0.entry_points_by_type[&EntryPointType::Constructor].first()?.selector)
> ```

How come this does not require returning `Result`?



_Code quote:_
```XML
first()?
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV8pYFYBUsrxiY8LmJJ:-NV8pYFYBUsrxiY8LmJK:bbps8xu) ([raw file](https://github.com/starkware-libs/blockifier/blob/77a22f29f16885ec759c9a06542babd9148d9a7e/crates/blockifier/src/execution/contract_class.rs#L86)):*
> ```XML
> }
> #[derive(Debug, Clone, Default, Eq, PartialEq)]
> pub struct ContractClassV1Inner {
> ```

Please add a blank line above.



_Code quote:_
```XML
#[derive(Debug, Clone, Default, Eq, PartialEq)]
pub struct ContractClassV1Inner {
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV8qMEy8SmeqTW9IS93:-NV8qMEy8SmeqTW9IS94:b-oogqxs) ([raw file](https://github.com/starkware-libs/blockifier/blob/77a22f29f16885ec759c9a06542babd9148d9a7e/crates/blockifier/src/execution/execution_utils.rs#L57)):*
> ```XML
> 
> /// Executes a specific call to a contract entry point and returns its output.
> pub fn execute_entry_point_call(
> ```

Why not move this as well?



_Code quote:_
```XML
execute_entry_point_call
```

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @giladchase and @spapinistarkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV8qPgM38SqyreSIcqa:-NV97kpnEOFmBzyi7Ex8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/77a22f29f16885ec759c9a06542babd9148d9a7e/crates/blockifier/src/execution.rs#L6)):*
> ```XML
> pub mod entry_point;
> pub mod errors;
> pub mod exec_v0;
> ```

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV8q3Ft0tPmzU7xBUkl:-NV97s656I857SB__N8g:b-5ej84k) ([raw file](https://github.com/starkware-libs/blockifier/blob/77a22f29f16885ec759c9a06542babd9148d9a7e/crates/blockifier/src/execution/contract_class.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come this does not require returning `Result`?
</blockquote></details>

Do you mean `?`? it works with Option and Result.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV8qMEy8SmeqTW9IS93:-NV9813rBEQLI1o1AEHd:b-mo0vw5) ([raw file](https://github.com/starkware-libs/blockifier/blob/77a22f29f16885ec759c9a06542babd9148d9a7e/crates/blockifier/src/execution/execution_utils.rs#L57)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not move this as well?
</blockquote></details>

It will turn into a match

**Review by elintul — APPROVED** [review]
> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV98_YI1CNxEEU46Qff:-NV98_YI1CNxEEU46Qfg:b28m6v5) (no related file):*
Please use `::from` instead of `.into`-s.

___
___
*[`crates/native_blockifier/src/py_transaction.rs` line 196 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV98d7OAAKXVHnqsAzj:-NV98d7OAAKXVHnqsAzk:b-ju5bac) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a339155eda707ac3a214247f957f9e83bf53638/crates/native_blockifier/src/py_transaction.rs#L196)):*
> ```XML
>             let raw_contract_class: &str = raw_contract_class
>                 .expect("A contract class must be passed in a Declare transaction.");
>             let contract_class =
> ```

I think this looked different last I saw it.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459)* status: 5 of 16 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV98_YI1CNxEEU46Qff:-NV9Da_TCm7QJ0bXr1Qy:brw6z2i) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please use `::from` instead of `.into`-s.
</blockquote></details>

Where exactly? It depends on where.
Are you forbidding the use of ".into()" altogether? That sounds harsh. Entire language feature for ergonomics down the drain.

___

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459#-:-NV9F0neCLtbNGXp1--v:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV98_YI1CNxEEU46Qff:-NV9EpRx8k55Lep7ICn1:b-kugurp) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Where exactly? It depends on where.
Are you forbidding the use of ".into()" altogether? That sounds harsh. Entire language feature for ergonomics down the drain.
</blockquote></details>

I just want explicit readable code. 

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/459#-NV98_YI1CNxEEU46Qff:-NV9IHcz4XEGuEOI7T17:b-9nm76o) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I just want explicit readable code. 
</blockquote></details>

Me too:)

___

**Review by elintul — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/459#-:-NV9MMHq4q6TCQP6mh-C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
