### PR TITLE
Add `calculate_tx_gas_usage`.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/379)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/379#-:-NRmXgL4CNt4QnuVD9lR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/379#-NRmXJe9CVrPutwSPWxP:-NRmXJe9CVrPutwSPWxQ:bphou2x) ([raw file](https://github.com/starkware-libs/blockifier/blob/0fa7145a79ac75509f62b7b1546150dbab1adc77/crates/blockifier/src/fee/gas_usage.rs#L25)):*
> ```XML
>     let n_l2_to_l1_messages = l2_to_l1_payloads_length.len();
>     let n_l1_to_l2_messages = match l1_handler_payload_size {
>         Some(_) => 1,
> ```

if this doesn't break lines maybe it's better than match



_Suggestion:_
```XML
    let n_l1_to_l2_messages = if l1_handler_payload_size.is_some() { 1 } else { 0 };
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/379)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/379)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/379#-NRme9Ij2ovJ0Y45XfTK:-NRme9Ij2ovJ0Y45XfTL:b-ac07u6) ([raw file](https://github.com/starkware-libs/blockifier/blob/b41fed7404bf570d29b96263dcb8aa01bf910757/crates/blockifier/src/fee/gas_usage.rs#L24)):*
> ```XML
> 
>     let n_l2_to_l1_messages = l2_to_l1_payloads_length.len();
>     let n_l1_to_l2_messages = usize::from(l1_handler_payload_size.is_some());
> ```

Clippy did not like [it](https://rust-lang.github.io/rust-clippy/master/index.html#bool_to_int_with_if). WDYT? Is it intuitive enough?



_Code quote:_
```XML
usize::from(l1_handler_payload_size.is_some());
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/379)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/379#-NRme9Ij2ovJ0Y45XfTK:-NRmkUKj3uIgc0Rghe46:b2nhtan) ([raw file](https://github.com/starkware-libs/blockifier/blob/b41fed7404bf570d29b96263dcb8aa01bf910757/crates/blockifier/src/fee/gas_usage.rs#L24)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Clippy did not like [it](https://rust-lang.github.io/rust-clippy/master/index.html#bool_to_int_with_if). WDYT? Is it intuitive enough?
</blockquote></details>

Yup



_Code quote:_
```XML
if l1_handler_payload_size.is_some() { 1 } else { 0 }
```

**Pull request merged**
