### PR TITLE
chore(state): use strict_subtract_mappings for compiled classes

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyPdZN68Py7JMdI_o_U:-NyPdZN68Py7JMdI_o_V:bc27vjl) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state.rs#L98)):*
> ```XML
>         let cache = &mut *self.cache.borrow_mut();
> 
>         // Eliminate storage writes that are identical to the initial value (no change). Assumes
> ```

?
Why did you remove the second sentence?



_Suggestion:_
```XML
// Eliminate storage writes that are identical to the initial value (no change).
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQOjAy-6m0Ncyk2yA-:-NyQOjAy-6m0Ncyk2yA0:b-sr0708) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state.rs#L201)):*
> ```XML
>                         class_hash,
>                         CompiledClassHash(StarkFelt::ZERO),
>                     );
> ```

We always override this value, right?
(unless of an uncaught error)



_Code quote:_
```XML
                    cache.set_compiled_class_hash_initial_value(
                        class_hash,
                        CompiledClassHash(StarkFelt::ZERO),
                    );
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQNlRB9rn4JOKuVuW3:-NyQNlRB9rn4JOKuVuW4:b32vly) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state_test.rs#L264)):*
> ```XML
>     let class_hash = FeatureContract::Empty(CairoVersion::Cairo0).get_class_hash();
>     let compiled_class_hash = compiled_class_hash!(1_u8);
>     // Cache the initial read value, as in regular flow.
> ```

? 



_Suggestion:_
```XML
    // Cache the initial read value, as in regular declare flow.
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQNo9nDCogvypv3hL6:-NyQNo9nDCogvypv3hL7:b-39ios0) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state_test.rs#L277)):*
> ```XML
>     let new_class_hash = class_hash!("0x11111111");
> 
>     // Cache the initial read value, as in regular flow.
> ```

Do we do it also in case of replace class?



_Suggestion:_
```XML
    // Cache the initial read value, as in regular deploy flow.
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQJjl_3CZasflog9N7:-NyQJjl_3CZasflog9N8:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state.rs#L98)):*
> ```XML
>         let cache = &mut *self.cache.borrow_mut();
> 
>         // Eliminate storage writes that are identical to the initial value (no change). Assumes
> ```





_Suggestion:_
```XML
      // Eliminate storage writes that are identical to the initial value (no change).
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 494 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQLBMoAOpea4DWNGhg:-NyQLBMoAOpea4DWNGhh:bunva6a) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bdfda2ea7235e50b6d9644a301bfa01ed74d916/crates/blockifier/src/state/cached_state.rs#L494)):*
> ```XML
>         // `get_compiled_class_hash` method. When declaring a Cairo 1 class we update the
>         // writes mapping but cannot update the reads mapping. As a result, the compiled
>         // class hash writes keys are not a subset of compiled class hash initial values keys.
> ```

Does Papyrus support the `get_compiled_class_hash` method now?



_Code quote:_
```XML
        // This is not a strict subtraction, as Papyrus does not support the
        // `get_compiled_class_hash` method. When declaring a Cairo 1 class we update the
        // writes mapping but cannot update the reads mapping. As a result, the compiled
        // class hash writes keys are not a subset of compiled class hash initial values keys.
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @dorimedini-starkware, and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyPdZN68Py7JMdI_o_U:-NyQQY7A4z19EvgdfzKz:bhcaypu) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state.rs#L98)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
Why did you remove the second sentence?
</blockquote></details>

I thought it's not relevant anymore (`set_storage_at`)
What is the intention?
___
*[`crates/blockifier/src/state/cached_state.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQJjl_3CZasflog9N7:-NyQR03s0lqZjbMiazir:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state.rs#L98)):*
> ```XML
>         let cache = &mut *self.cache.borrow_mut();
> 
>         // Eliminate storage writes that are identical to the initial value (no change). Assumes
> ```

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQOjAy-6m0Ncyk2yA-:-NyQR5UnEv02tw1cXwil:b-veu5vu) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state.rs#L201)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We always override this value, right?
(unless of an uncaught error)
</blockquote></details>

WDYM? when we declare a Cairo 1 class?
___
*[`crates/blockifier/src/state/cached_state.rs` line 494 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQLBMoAOpea4DWNGhg:-NyQQlcz2_Qj8j6QGkjg:bxzy3d8) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bdfda2ea7235e50b6d9644a301bfa01ed74d916/crates/blockifier/src/state/cached_state.rs#L494)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Does Papyrus support the `get_compiled_class_hash` method now?
</blockquote></details>

No, but it doesn't matter, I changed `get_compiled_contract_class` to update this field
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQNo9nDCogvypv3hL6:-NyQRuCs71QHQVOgFnrj:b-dis8b6) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state_test.rs#L277)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we do it also in case of replace class?
</blockquote></details>

No, but we do this before running any transaction on self contract address. I'll document.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: all files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQZbf_7d_kjGyqvKUs:-NyQZbf_7d_kjGyqvKUt:b-hly2zx) (no related file):*
python side PR?

___

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/state/cached_state_test.rs` line 310 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQf4kJ6zNwaiIdvjSR:-NyQf4kJ6zNwaiIdvjSS:bjuhjd8) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state_test.rs#L310)):*
> ```XML
> 
>     state.set_storage_at(contract_address, key, storage_val).unwrap();
>     state.increment_nonce(contract_address2).unwrap();
> ```

Why don't we add these too?



_Suggestion:_
```XML
    state.get_storage_at(contract_address, key).unwrap();
    state.set_storage_at(contract_address, key, storage_val).unwrap();
    state.get_nonce_at(contract_address2).unwrap();
    state.increment_nonce(contract_address2).unwrap();
```

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @dorimedini-starkware, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQZbf_7d_kjGyqvKUs:-NyQmCRUEM32BcNVnliP:big7q26) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

python side PR?
</blockquote></details>

Why? it's an internal change and should not affect python (i.e., any bug should be caught in blockifier's tests)

___
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 310 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQf4kJ6zNwaiIdvjSR:-NyQlqDN50h6IQle2XM8:bp2r1c6) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state_test.rs#L310)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why don't we add these too?
</blockquote></details>

Storage is an exception. Someone can write without reading before. We fetch all missing initial values at the end

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-:-NyQugJJ9teBFqiafsnc:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQZbf_7d_kjGyqvKUs:-NyRHBDf1SqC4gFOijMp:b5pe9qb) (no related file):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why? it's an internal change and should not affect python (i.e., any bug should be caught in blockifier's tests)
</blockquote></details>

1. I am not sure we have coverage for this: you change the way the state diff is computed internally, can you make sure we have coverage for some basic sanity cases (one change per diff field, one change back to original value per diff field)
2. this could potentially have an effect on the native blockifier user (python side) due to the state diff construction logic changing

I'll unblock in case you find coverage (or are convinced it's fine)

___

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQZbf_7d_kjGyqvKUs:-NyRQzyWBW3Fb_14AF1P:b6edq9k) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. I am not sure we have coverage for this: you change the way the state diff is computed internally, can you make sure we have coverage for some basic sanity cases (one change per diff field, one change back to original value per diff field)
2. this could potentially have an effect on the native blockifier user (python side) due to the state diff construction logic changing

I'll unblock in case you find coverage (or are convinced it's fine)
</blockquote></details>

That's an internal change that should not affect the native, so it's the blockifier's "responsibility" to catch issues (and there are several tests for this here, some of them I had to fix)

I think it's reasonable not to wait for python in such cases (the risk is low, we will find the bug eventually)

___

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQOjAy-6m0Ncyk2yA-:-NyUAbWB12m4rM1lxGM8:bqtt6i2) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state.rs#L201)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

WDYM? when we declare a Cairo 1 class?
</blockquote></details>

Oh, if we encounter other StateError, the tx must fail (thus no declare will follow)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyPdZN68Py7JMdI_o_U:-NyUF4HJ5fcdz4f9Q4Jx:b6g0819) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state.rs#L98)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I thought it's not relevant anymore (`set_storage_at`)
What is the intention?
</blockquote></details>

Don't remember :)
___
*[`crates/blockifier/src/state/cached_state.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyUE2VFB5_-mVgqQaRr:-NyUE2VFB5_-mVgqQaRs:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d147de24deeb0054fdc02cb54617dc541b009da1/crates/blockifier/src/state/cached_state.rs#L95)):*
> ```XML
>     ///   * Nonce: read previous before incrementing.
>     ///   * Class hash: Deploy: verify the address is not occupied; Replace class: verify the
>     ///     contract is deployed before running any code.
> ```





_Suggestion:_
```XML
    ///     contract is declared before running any code.
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQNo9nDCogvypv3hL6:-NyUEKsiDkav6KltkuDk:byfhnzs) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state_test.rs#L277)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No, but we do this before running any transaction on self contract address. I'll document.
</blockquote></details>

In case of replace class we first call `get_compiled_contract_class` and then `set_class_hash_at`. When will we set the class hash initial value? :thinking:

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyUE2VFB5_-mVgqQaRr:-NyUTE4O8IFWuEm48sJ1:br6rrro) ([raw file](https://github.com/starkware-libs/blockifier/blob/d147de24deeb0054fdc02cb54617dc541b009da1/crates/blockifier/src/state/cached_state.rs#L95)):*
> ```XML
>     ///   * Nonce: read previous before incrementing.
>     ///   * Class hash: Deploy: verify the address is not occupied; Replace class: verify the
>     ///     contract is deployed before running any code.
> ```

Nope :)
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1909#-NyQNo9nDCogvypv3hL6:-NyUTH4j83Hn6Feb4USv:bigagdu) ([raw file](https://github.com/starkware-libs/blockifier/blob/35f1ee8c66b913070de1af1d0a5d5dffb3f7728d/crates/blockifier/src/state/cached_state_test.rs#L277)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In case of replace class we first call `get_compiled_contract_class` and then `set_class_hash_at`. When will we set the class hash initial value? :thinking:
</blockquote></details>

You can only replace your self class hash. 
Before running any code, we check that the contract is deployed

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1909)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
