### PR TITLE
test(concurrency): test concurrent fee transfer when the sequencer is…

### PR DESCRIPTION
**Pull request by meship-starkware**
… the sender

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1302 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-Nzg_wiT51bkjdEveh7A:-Nzg_wiT51bkjdEveh7B:b-u4zv7u) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e4d6373f1fa2753a192aadf2fb6d4d7a0d0352c/crates/blockifier/src/transaction/account_transactions_test.rs#L1302)):*
> ```XML
>             [(sequencer_balance_key_low, sender_balance), (sequencer_balance_key_high, 0_u128)]
>         {
>             assert!(storage.contains_key(&(fee_token_address, seq_key)));
> ```

I think the first assertion is enough because it indicates that we run the sequential fee transfer, and a test already checks it. WDYT?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1269 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzhNTiX1VC8pfGb-eyb:-NzhNTiX1VC8pfGb-eyc:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e4d6373f1fa2753a192aadf2fb6d4d7a0d0352c/crates/blockifier/src/transaction/account_transactions_test.rs#L1269)):*
> ```XML
>     block_context.block_info = block_info;
> 
>     // Create the account transaction accurding to the fee type.
> ```





_Suggestion:_
```XML
    // Create the account transaction according to the fee type.
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1302 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-Nzg_wiT51bkjdEveh7A:-NzhRaYvChbofsSduXyK:bb77ufg) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e4d6373f1fa2753a192aadf2fb6d4d7a0d0352c/crates/blockifier/src/transaction/account_transactions_test.rs#L1302)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

You want to remove the second assertion?
</blockquote></details>

Yes.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1302 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-Nzg_wiT51bkjdEveh7A:-NzhXxTy8vWApQRW2jyV:b-5w5bhk) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e4d6373f1fa2753a192aadf2fb6d4d7a0d0352c/crates/blockifier/src/transaction/account_transactions_test.rs#L1302)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Actually, I think we should remove the first assertion. If we are able to compare the value at the key, then that key obviously exists.

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1269 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzhNTiX1VC8pfGb-eyb:-Nzw32G53oo3tJZTz8DI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e4d6373f1fa2753a192aadf2fb6d4d7a0d0352c/crates/blockifier/src/transaction/account_transactions_test.rs#L1269)):*
> ```XML
>     block_context.block_info = block_info;
> 
>     // Create the account transaction accurding to the fee type.
> ```

Done.

**Review by avi-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-:-NzwS_ByDXkdrWpila5P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1259 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxXJkI7riFWcV-9MOf:-NzxXJkI7riFWcV-9MOg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1259)):*
> ```XML
>     max_fee: Fee,
>     #[values(FeeType::Eth, FeeType::Strk)] fee_type: FeeType,
> ) {
> ```





_Suggestion:_
```XML
#[case::tx_version_1(TransactionVersion::ONE, FeeType::Eth)]
#[case::tx_version_3(TransactionVersion::THREE, FeeType::Strk)]
fn test_concurrent_fee_transfer_when_sender_is_sequencer(
    #[case] version: TransactionVersion,
    #[case] fee_type: FeeType,
) {
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1267 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxWwp88-kbxidLnrjy:-NzxWwp88-kbxidLnrjz:b-gl3rx9) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1267)):*
> ```XML
>     // Set the sequencer as the sender.
>     block_info.sequencer_address = account_address;
>     block_context.block_info = block_info;
> ```

Why is it needed?
Why not modifying directly the block context?



_Suggestion:_
```XML
    // Set the sequencer as the sender.
    block_context.block_info.sequencer_address = account_address;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1284 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxXUV07smGNz898UvD:-NzxXUV07smGNz898UvE:btpeqxf) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1284)):*
> ```XML
>             version: TransactionVersion::THREE
>         })
>     };
> ```

Note that it knows which resource bound to use according to the transaction version. 
You need to declare and deploy the test contract. 



_Suggestion:_
```XML
    let account_tx = account_invoke_tx(invoke_tx_args! {
            max_fee,
            sender_address: account_address,
            calldata: create_trivial_calldata(test_contract.get_instance_address(0)),
            version: TransactionVersion::ONE,
            resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
            version
        })
    };
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1288 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxYZ7QD1U0BWKjjDcV:-NzxYZ7QD1U0BWKjjDcW:brylva0) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1288)):*
> ```XML
>     let chain_info = &block_context.chain_info;
>     let fee_token_address = block_context.chain_info.fee_token_address(&fee_type);
>     let state = &mut test_state(chain_info, sender_balance, &[(account, 1)]);
> ```

Better to define it at the beginning (see other tests)



_Code quote:_
```XML
    let chain_info = &block_context.chain_info;
    let fee_token_address = block_context.chain_info.fee_token_address(&fee_type);
    let state = &mut test_state(chain_info, sender_balance, &[(account, 1)]);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1292 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxYhGY9HrcnS-APWk5:-NzxYhGY9HrcnS-APWk6:b-gfip05) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1292)):*
> ```XML
>         get_sequencer_balance_keys(&block_context);
>     let mut transactional_state = TransactionalState::create_transactional(state);
>     account_tx.execute_raw(&mut transactional_state, &block_context, true, false).unwrap();
> ```

Please define variables to the flags. 
Why `validate=false`? Does it matter?



_Suggestion:_
```XML
    account_tx.execute(&mut state, &block_context, true, false).unwrap();
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1307 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxZSAI7k6CCR4bBYIS:-NzxZSAI7k6CCR4bBYIT:bvybozt) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1307)):*
> ```XML
>             );
>         }
>     }
> ```

Will reading directly from the state be enough? :thinking: 



_Code quote:_
```XML
    for storage in [
        transactional_cache.initial_reads.storage.clone(),
        transactional_cache.writes.storage.clone(),
    ] {
        for (seq_key, seq_value) in
            [(sequencer_balance_key_low, sender_balance), (sequencer_balance_key_high, 0_u128)]
        {
            assert_eq!(
                *storage.get(&(fee_token_address, seq_key)).unwrap(),
                stark_felt!(seq_value)
            );
        }
    }
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1267 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxWwp88-kbxidLnrjy:-O-0ae2z65_jVgo5JyxW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1267)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
Why not modifying directly the block context?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1284 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxXUV07smGNz898UvD:-O-0cLTA2h9YoNpR98pi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1284)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note that it knows which resource bound to use according to the transaction version. 
You need to declare and deploy the test contract.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1292 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxYhGY9HrcnS-APWk5:-O-0d7vJDR8EvSVL9Wi8:b-i8p71m) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1292)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please define variables to the flags. 
Why `validate=false`? Does it matter?
</blockquote></details>

No, it's a mistake. Validate should be true.
Done. 
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1307 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxZSAI7k6CCR4bBYIS:-O-0dT_r2sVEq0vNjYl1:b-c1va7c) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1307)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Will reading directly from the state be enough? :thinking:
</blockquote></details>

I don't think I understand the question.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1307 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxZSAI7k6CCR4bBYIS:-O-LaMR28N-DLHm0-wvJ:bz0a93b) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1307)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I don't think I understand the question.
</blockquote></details>

I meant:



_Code snippet:_
```XML
for (seq_key, seq_value) in
            [(sequencer_balance_key_low, sender_balance), (sequencer_balance_key_high, 0_u128)]
        {
            assert_eq!(
                state.get_storage_at(fee_token_address, seq_key).unwrap(),
                stark_felt!(seq_value)
            );
        }
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1278 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-L_JB6C9fydhyidPrE:-O-L_JB75zh_Xsn9jh85:b-n6d6dn) ([raw file](https://github.com/starkware-libs/blockifier/blob/439540936c61f33eb8c0310e94fdf624db4e3c30/crates/blockifier/src/transaction/account_transactions_test.rs#L1278)):*
> ```XML
>     let (sequencer_balance_key_low, sequencer_balance_key_high) =
>         get_sequencer_balance_keys(&block_context);
>     // Create the account transaction according to the fee type.
> ```

Please remove



_Code quote:_
```XML
    // Create the account transaction according to the fee type.
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1307 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-NzxZSAI7k6CCR4bBYIS:-O-UUVKOAuPCBZZXcgUJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a0d7e8d8129d9944f75cb0bd72f69ec1feafaf34/crates/blockifier/src/transaction/account_transactions_test.rs#L1307)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I meant:
</blockquote></details>

Done.

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1171 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-VFEbDB7vnp4BvQ3UW:-O-VFEbDB7vnp4BvQ3UX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/843360d8a04d15864ca3f53030427d7361e0cf2d/crates/blockifier/src/transaction/account_transactions_test.rs#L1171)):*
> ```XML
>     // sequencer_balance_key_high.
>     const STORAGE_WRITE_LOW: u128 = 100;
>     const STORAGE_READ_LOW: u128 = 50;
> ```





_Suggestion:_
```XML
    const TRANSFER_AMOUNT: u128 = 100;
    const SEQUENCER_BALANCE_LOW_INITIAL u128 = 50;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1184 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-VCpJTCw1XjoAjUY_f:-O-VCpJUBiCrRxrEJXsg:b-6x996b) ([raw file](https://github.com/starkware-libs/blockifier/blob/843360d8a04d15864ca3f53030427d7361e0cf2d/crates/blockifier/src/transaction/account_transactions_test.rs#L1184)):*
> ```XML
>         calldata: create_trivial_calldata(test_contract.get_instance_address(0)),
>         resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
>         version: TransactionVersion::THREE
> ```

Please add the version as an input parameter (to fit the fee type) or use version only (see my comment below)



_Code quote:_
```XML
        version: TransactionVersion::THREE
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1265 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-VDyxyC1Vqs5TMDfnp:-O-VDyxyC1Vqs5TMDfnq:b71emi1) ([raw file](https://github.com/starkware-libs/blockifier/blob/843360d8a04d15864ca3f53030427d7361e0cf2d/crates/blockifier/src/transaction/account_transactions_test.rs#L1265)):*
> ```XML
> #[rstest]
> #[case::tx_version_1(TransactionVersion::ONE, FeeType::Eth)]
> #[case::tx_version_3(TransactionVersion::THREE, FeeType::Strk)]
> ```

Can you deduce the fee type from the transaction directly?



_Code quote:_
```XML
#[case::tx_version_1(TransactionVersion::ONE, FeeType::Eth)]
#[case::tx_version_3(TransactionVersion::THREE, FeeType::Strk)]
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1296 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-VEMm-1Z6qccllkw4z:-O-VEMm-1Z6qccllkw5-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/843360d8a04d15864ca3f53030427d7361e0cf2d/crates/blockifier/src/transaction/account_transactions_test.rs#L1296)):*
> ```XML
>         account_tx.execute(&mut transactional_state, &block_context, charge_fee, validate).unwrap();
>     assert!(!result.is_reverted());
>     // Check that the sequencer balance was not changed.
> ```





_Suggestion:_
```XML
    // Check that the sequencer balance was updared (in this case, was not changed).
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1184 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-VCpJTCw1XjoAjUY_f:-O-V_kYh9H4NhmS2Dxji:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/843360d8a04d15864ca3f53030427d7361e0cf2d/crates/blockifier/src/transaction/account_transactions_test.rs#L1184)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add the version as an input parameter (to fit the fee type) or use version only (see my comment below)
</blockquote></details>

Done.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1247 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-Vawxo6TAnyAm7e2VQ:-O-VawxpBD-x4zGRY2k6:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ccbd1bf6d229a2d583b14ddaf9acbfa8d1fe8b6e/crates/blockifier/src/transaction/account_transactions_test.rs#L1247)):*
> ```XML
>     assert!(!result.is_reverted());
> 
>     // Check that the sequencer balance was updared (in this case, was not changed).
> ```





_Suggestion:_
```XML
    // Check that the sequencer balance was updated (in this case, was not changed).
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1173 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-VdO689RV5gjQoKzX9:-O-VdO6964rD0-FI3imP:b-4aw3l) ([raw file](https://github.com/starkware-libs/blockifier/blob/21130460c11949d57ee8ce1ff7ceca408422f061/crates/blockifier/src/transaction/account_transactions_test.rs#L1173)):*
> ```XML
>     // sequencer_balance_key_high.
>     const STORAGE_WRITE_LOW: u128 = 100;
>     const STORAGE_READ_LOW: u128 = 50;
> ```

Are those constants needed now?



_Code quote:_
```XML
    const STORAGE_WRITE_LOW: u128 = 100;
    const STORAGE_READ_LOW: u128 = 50;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1181 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-VdZA04kJMwmoGXYvI:-O-VdZA04kJMwmoGXYvJ:brejra4) ([raw file](https://github.com/starkware-libs/blockifier/blob/21130460c11949d57ee8ce1ff7ceca408422f061/crates/blockifier/src/transaction/account_transactions_test.rs#L1181)):*
> ```XML
>     let test_contract = FeatureContract::TestContract(CairoVersion::Cairo0);
>     let chain_info = &block_context.chain_info;
>     let fee_type = if version == TransactionVersion::ONE { FeeType::Eth } else { FeeType::Strk };
> ```

Same below



_Suggestion:_
```XML
    let fee_type = &account_tx.fee_type();
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1247 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-Ve4us8l1KBZEL6pKY:-O-Ve4us8l1KBZEL6pKZ:byr4fm0) ([raw file](https://github.com/starkware-libs/blockifier/blob/21130460c11949d57ee8ce1ff7ceca408422f061/crates/blockifier/src/transaction/account_transactions_test.rs#L1247)):*
> ```XML
>     assert!(!result.is_reverted());
> 
>     // Check that the sequencer balance was updated (in this case, was not changed).
> ```

Right?



_Suggestion:_
```XML
// Check that the sequencer balance was not updated.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1305 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-Ve9tp277ECxri9ih-:-O-Ve9tq-Cl4x4TzQ7J4:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/21130460c11949d57ee8ce1ff7ceca408422f061/crates/blockifier/src/transaction/account_transactions_test.rs#L1305)):*
> ```XML
>         account_tx.execute(&mut transactional_state, &block_context, charge_fee, validate).unwrap();
>     assert!(!result.is_reverted());
>     // Check that the sequencer balance was not changed.
> ```





_Suggestion:_
```XML
// Check that the sequencer balance was updated (in this case, was not changed).
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1181 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-VdZA04kJMwmoGXYvI:-O-VniV00r8aMDEPGe1w:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/21130460c11949d57ee8ce1ff7ceca408422f061/crates/blockifier/src/transaction/account_transactions_test.rs#L1181)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same below
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1247 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1963#-O-Ve4us8l1KBZEL6pKY:-O-VnkY75k4v1yjjBdH-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/21130460c11949d57ee8ce1ff7ceca408422f061/crates/blockifier/src/transaction/account_transactions_test.rs#L1247)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Right?
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1963)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
