### PR TITLE
chore: upgrade papyrus version

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`Cargo.toml` line 40 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1460#-Nq8-JIG9NMJHntoxWfR:-Nq8-JIH-4QliIlHMfuy:b-xfkz9t) ([raw file](https://github.com/starkware-libs/blockifier/blob/69a6c5c84300a37aa1fe1050a01177c0ceaadc73/Cargo.toml#L40)):*
> ```TOML
> once_cell = "1.19.0"
> papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", branch = "yair/bump_blockifier" }
> #papyrus_storage = "0.3.0-dev.0"
> ```

Blocking until Papyrus is ready.



_Code quote:_
```TOML
papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", branch = "yair/bump_blockifier" }
#papyrus_storage = "0.3.0-dev.0"
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 37 files at r3, 5 of 11 files at r4, 34 of 34 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460#-:-NqLwT0lBJ0iDU9cz2Gm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r4, 12 of 34 files at r5, 1 of 2 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`-- commits` line 1 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1460#-NqMS06YCEDYb8zUUjzG):*
Plz add python pr 
___
*[`crates/blockifier/Cargo.toml` line 54 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1460#-NqMRH6y3rYzVV9ktUnp:-NqMRH6y3rYzVV9ktUnq:bfq4ca9) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0deeedb1e9a3ac7cb6193e843e375b035370d95/crates/blockifier/Cargo.toml#L54)):*
> ```TOML
> cairo-lang-casm = { workspace = true, features = [
>     "parity-scale-codec",
>     "schemars",
> ```

Where is this used? or is it due to dependencies?



_Code quote:_
```TOML
"schemars",
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: 36 of 38 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1460#-NqMmoUX7Gph9YcDck-9:-NqMmoUX7Gph9YcDck-A:b-3o16ok) (no related file):*
Python PR that checks this commit:
https://reviewable.io/reviews/starkware-industries/starkware/33867#-

___
___
*[`-- commits` line 1 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1460#-NqMS06YCEDYb8zUUjzG):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Plz add python pr
</blockquote></details>

Added above :)
___
*[`crates/blockifier/Cargo.toml` line 54 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1460#-NqMRH6y3rYzVV9ktUnp:-NqMVgHd-MXLjWUsmvcS:bsclc63) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0deeedb1e9a3ac7cb6193e843e375b035370d95/crates/blockifier/Cargo.toml#L54)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Where is this used? or is it due to dependencies?
</blockquote></details>

Removed from dev-dependency as it's not used in testing.
It was an attempt to resolve the udeps error.

**Review by giladchase — COMMENTED** [review]
> Reviewed 2 of 34 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: 36 of 38 files reviewed, 2 unresolved discussions (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/Cargo.toml` line 25 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1460#-NqMpQIn-zGch3ZcxTQc:-NqMpQIo3L0MyvumCFgH:bdk7ku9) ([raw file](https://github.com/starkware-libs/blockifier/blob/4163aa06b2b3c2a266b623bedb64e7722f494f51/crates/blockifier/Cargo.toml#L25)):*
> ```TOML
> cached.workspace = true
> cairo-felt.workspace = true
> cairo-lang-casm = { workspace = true, features = ["parity-scale-codec"] }
> ```

Why is this needed?



_Code quote:_
```TOML
features = ["parity-scale-codec"]
```

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`-- commits` line 2 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1460#-NqNdx_dEMl3QuYd-QvW):*
Adding a blocking commit to remind us to full-merge instead of squash (to preserve the tag)

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460#-:-NqOImVk97CqNm2EvEo1:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

**Review by giladchase — APPROVED** [review]
> Reviewed 19 of 34 files at r5, 1 of 2 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Pull request merged**
