### PR TITLE
refactor: remove f64 usage at blockifier

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1519)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1519)* status: all files reviewed, 9 unresolved discussions (waiting on @nimrod-starkware)

___
*[`Cargo.toml` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr-xdzB9Jvcq0K4KU8S:-Nr-xdzB9Jvcq0K4KU8T:b6daed5) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5faae6427de9a61992d663900f7a0938f02d79/Cargo.toml#L38)):*
> ```TOML
> num-integer = "0.1.45"
> num-traits = "0.2"
> num-rational = {version = "0.4", features = ["serde"]}
> ```

consistency (non-blocking)



_Suggestion:_
```TOML
{ version = "0.4", features = ["serde"] }
```
___
*[`crates/blockifier/resources/versioned_constants.json` line 491 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr-xns4CZr6GOrL5L9o:-Nr-xns4CZr6GOrL5L9p:b-yisu2f) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5faae6427de9a61992d663900f7a0938f02d79/crates/blockifier/resources/versioned_constants.json#L491)):*
> ```JSON
>             1,
>             25
>         ]
> ```

please use denominators that are powers of 10 (easier to review the change, and easier to read)



_Code quote:_
```JSON
        "bitwise_builtin": [
            4,
            25
        ],
        "ec_op_builtin": [
            64,
            25
        ],
        "ecdsa_builtin": [
            128,
            25
        ],
        "keccak_builtin": [
            128,
            25
        ],
        "n_steps": [
            1,
            400
        ],
        "output_builtin": [
            0,
            1
        ],
        "pedersen_builtin": [
            2,
            25
        ],
        "poseidon_builtin": [
            2,
            25
        ],
        "range_check_builtin": [
            1,
            25
        ]
```
___
*[`crates/blockifier/resources/versioned_constants.json` line 493 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr-xveV-EZOnz9uorCM:-Nr-xveV-EZOnz9uorCN:b6phgi6) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5faae6427de9a61992d663900f7a0938f02d79/crates/blockifier/resources/versioned_constants.json#L493)):*
> ```JSON
>         ]
>     }
> }
> ```

add the deleted newline (we end files with newlines)



_Code quote:_
```JSON
}
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr-y1N4CvjAAKSnyXyG:-Nr-y1N4CvjAAKSnyXyH:b-9dur9n) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5faae6427de9a61992d663900f7a0938f02d79/crates/blockifier/src/versioned_constants.rs#L4)):*
> ```XML
> use std::path::Path;
> use std::sync::Arc;
> use std::{io, u128};
> ```

revert (no need to import u128)



_Code quote:_
```XML
use std::{io, u128};
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr-yTTYEmLZVRQb6i-l:-Nr-yTTYEmLZVRQb6i-m:b-h1fgrk) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5faae6427de9a61992d663900f7a0938f02d79/crates/blockifier/src/versioned_constants.rs#L50)):*
> ```XML
>     // TODO: Consider making this a struct, this will require change the way we access these
>     // values.
>     vm_resource_fee_cost: Arc<HashMap<String, Ratio<u128>>>,
> ```

please define an explicit type (I suggest naming it `ResourceCost`) and use it everywhere you use `Ratio<u128>`
```
pub type ResourceCost = Ratio<u128>;
```



_Code quote:_
```XML
Ratio<u128>
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr-zWed6XSEPZFkC5XV:-Nr-zWed6XSEPZFkC5XW:b-942mwt) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5faae6427de9a61992d663900f7a0938f02d79/crates/blockifier/src/execution/entry_point.rs#L248)):*
> ```XML
>         // bounded above by the block's limit, which is a usize.
> 
>         let upper_bound_u128 = (u128_from_usize(tx_gas_upper_bound).unwrap()
> ```

`unwrap` is only allowed in tests - in production code we only use `expect`.
Note that once [this](https://reviewable.io/reviews/starkware-libs/blockifier/1522) is merged, it will no longer be an issue here anyway... but just for now.



_Suggestion:_
```XML
.expect("Conversion from usize to u128 should not fail.")
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr-yqVD26p0jpG-7s3H:-Nr-yqVD26p0jpG-7s3I:bmyw49v) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5faae6427de9a61992d663900f7a0938f02d79/crates/blockifier/src/execution/entry_point.rs#L250)):*
> ```XML
>         let upper_bound_u128 = (u128_from_usize(tx_gas_upper_bound).unwrap()
>             * gas_per_step.denom())
>             / gas_per_step.numer();
> ```

We can, in theory, decide that steps are free.
So, the numerator can be zero... in which case, the user's fee bound does not limit the number of allowed cairo steps.
Also, after you take care of the `0` case, you can multiply by the inverse instead of explicit field access.



_Suggestion:_
```XML
        let upper_bound_u128 = if gas_per_step.is_zero() {
            usize::MAX
        } else {
            u128_from_usize(tx_gas_upper_bound).unwrap() * gas_per_step.inv()
        };
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr-zsmbEKD_4hz7uJuW:-Nr-zsmbEKD_4hz7uJuX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5faae6427de9a61992d663900f7a0938f02d79/crates/blockifier/src/fee/fee_utils.rs#L58)):*
> ```XML
>             (*resource_val)
>                 * u128_from_usize(vm_resource_usage.0.get(key).cloned().unwrap_or_default())
>                     .unwrap()
> ```





_Suggestion:_
```XML
.expect("Conversion from usize to u128 should not fail.")
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr-zx329SQ1mzlXmRvp:-Nr-zx329SQ1mzlXmRvq:bcdwi0i) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5faae6427de9a61992d663900f7a0938f02d79/crates/blockifier/src/fee/fee_utils.rs#L61)):*
> ```XML
>         })
>         .max()
>         .unwrap();
> ```

why is `unwrap` needed here?
if this is because `max` on an empty collection can be `None`, then I suggest
1. converting to integer (`.ceil().to_integer()`) in the `map` iterations
2. using `.fold(0, u128::max)` instead of `.max().unwrap()`



_Code quote:_
```XML
        .max()
        .unwrap();
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1519)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr0kSzP2P0AeHoJKXwq:-Nr0kSzP2P0AeHoJKXwr:b-rqptci) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5faae6427de9a61992d663900f7a0938f02d79/crates/blockifier/src/versioned_constants.rs#L33)):*
> ```XML
>         .expect("Versioned constants JSON file is malformed")
> });
> ```

restore the newline
___
*[`crates/blockifier/src/versioned_constants.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr0kZdw2A6FBw1RzWEr:-Nr0kZdw2A6FBw1RzWEs:b-ay68d) ([raw file](https://github.com/starkware-libs/blockifier/blob/30df206f2004c8d6b7ae39472ef73b8766631554/crates/blockifier/src/versioned_constants.rs#L37)):*
> ```XML
> /// automatically ignored during deserialization.
> pub type ResourceCost = Ratio<u128>;
> #[derive(Clone, Debug, Default, Deserialize)]
> ```

newlines between logically separate items.
`ResourceCost` exists as an independent type (related to `VersionedConstants` but still deserves it's own line).



_Suggestion:_
```XML
});

pub type ResourceCost = Ratio<u128>;

/// Contains constants for the Blockifier that may vary between versions.
/// Additional constants in the JSON file, not used by Blockifier but included for transparency, are
/// automatically ignored during deserialization.
#[derive(Clone, Debug, Default, Deserialize)]
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr0kzUfEM4-Qq89I-zp:-Nr0kzUfEM4-Qq89I-zq:b-ozgsvi) ([raw file](https://github.com/starkware-libs/blockifier/blob/30df206f2004c8d6b7ae39472ef73b8766631554/crates/blockifier/src/versioned_constants.rs#L136)):*
> ```XML
>             (
>                 crate::abi::constants::N_STEPS_RESOURCE.to_string(),
>                 ResourceCost::from_integer(1_u128),
> ```

see if you can remove the type (everywhere)



_Suggestion:_
```XML
1
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1519)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr0tCyQ65aDs4h0vdTN:-Nr0tCyR5VvpoDbyUKEe:bvbo442) (no related file):*
Please paste a link to the python side PR

___

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr0tCyQ65aDs4h0vdTN:-Nr18ypL2vJyv9cnDmlv:b45h) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Please paste a link to the python side PR
</blockquote></details>





_Code snippet:_
```
[python PR](https://github.com/starkware-industries/starkware/pull/34041)
```

___

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1519)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-Nr5HoG_5lMT35ylqoBX:-Nr5HoG_5lMT35ylqoBY:bl3ari9) (no related file):*
[python PR](https://github.com/starkware-industries/starkware/pull/34041)

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1519#-:-NrB5d6j2MedqLrj_e-6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
