### PR TITLE
Dori/merge main v0.12.0 into main 2

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/640)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/640)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/640)* status: 17 of 21 files reviewed, all discussions resolved (waiting on @giladchase, @liorgold2, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/640#-NYN1nmg9jUyFK8_sfLV:-NYN1nmg9jUyFK8_sfLW:b-516f6z) ([raw file](https://github.com/starkware-libs/blockifier/blob/5b23f48145a3a299b81ea70b1ca7cebf806432d4/crates/blockifier/src/transaction/account_transactions_test.rs#L143)):*
> ```XML
>             None,
>             None,
>             &mut NonceManager::default(),
> ```

test was copied down; and this nonce manager was added. no other change to test



_Code quote:_
```XML
&mut NonceManager::default(),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/640)* status: 17 of 21 files reviewed, all discussions resolved (waiting on @giladchase, @liorgold2, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 702 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/640#-NYN1wT-CDJmalxp4N-O:-NYN1wT-CDJmalxp4N-P:b-twx8t) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd062ebfbf9104498dd96ec822513fc868d21036/crates/blockifier/src/transaction/transactions_test.rs#L702)):*
> ```XML
> 
> <<<<<<< HEAD
> fn create_account_tx_for_validate_test(
> ```

on 0.12.0, this function was moved to a test_utils file (for use in account_transaction_test as well as transaction_test)



_Code quote:_
```XML
fn create_account_tx_for_validate_test
```

**Review by giladchase — COMMENTED** [review]
:lgtm: 

> Reviewed 12 of 20 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/640#-:-NYN32k55SuBxY5HH1Nq:bg7igkv)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @liorgold2 and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/640)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2 and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/640)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/640#-NYNvxkh8N9lAABTpRO7:-NYNvxkh8N9lAABTpRO8:b-q569xe) ([raw file](https://github.com/starkware-libs/blockifier/blob/5b23f48145a3a299b81ea70b1ca7cebf806432d4/crates/blockifier/src/transaction/account_transactions_test.rs#L220)):*
> ```XML
>     let account_tx = AccountTransaction::Invoke(InvokeTransaction::V1(InvokeTransactionV1 {
>         nonce: Nonce(stark_felt!(1_u8)),
>         ..tx
> ```

use nonce manager



_Code quote:_
```XML
        nonce: Nonce(stark_felt!(1_u8)),
        ..tx
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
merge direction is wrong.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/640#-:-NYS167k451ZXUbFDjla:bfdffvt)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @giladchase, @liorgold2, @noaov1, and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/640)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @giladchase, @liorgold2, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/640#-NYS2LBBBXHeJ7-9wKEy:-NYS2LBBBXHeJ7-9wKEz:b120tz9) (no related file):*
closing in favor of [this](https://reviewable.io/reviews/starkware-libs/blockifier/643)

___

**Pull request closed without merging**
