### PR TITLE
test(concurrency): test the halt flow in the commit phase

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2011)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2011)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 675 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-O0cafakBZ1c2ELv15Pp:-O0cafakBZ1c2ELv15Pq:b-vi80qu) ([raw file](https://github.com/starkware-libs/blockifier/blob/24dc5498c16c52bb86b8923809c9159f9d1a981a/crates/blockifier/src/concurrency/worker_logic_test.rs#L675)):*
> ```XML
> 
>     let mut bouncer = Bouncer::new(block_context.bouncer_config.clone());
>     bouncer.set_accumulated_weights(initial_bouncer_weights);
> ```

It's a bit "hacky". Consider adding one more transaction to emit two events. 



_Code quote:_
```XML
    bouncer.set_accumulated_weights(initial_bouncer_weights);
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 700 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-O0casSQ4QmFkfME4MzQ:-O0casSQ4QmFkfME4MzR:b-swsyd8) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3bda1e3ab51b58b4b4c15f9fee6921165a975ba/crates/blockifier/src/concurrency/worker_logic_test.rs#L700)):*
> ```XML
> 
>     // Verify the commit index is now 3, the status of the last transaction is `Committed`, and the
>     // next task is `Done`.
> ```

Now we are not testing turning on the done marker when we reach the chunk size, right?



_Code quote:_
```XML
    // Verify the commit index is now 3, the status of the last transaction is `Committed`, and the
    // next task is `Done`.
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2011)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 675 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-O0cafakBZ1c2ELv15Pp:-O0cuQZN0gyM-o60lekl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/24dc5498c16c52bb86b8923809c9159f9d1a981a/crates/blockifier/src/concurrency/worker_logic_test.rs#L675)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It's a bit "hacky". Consider adding one more transaction to emit two events.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 700 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-O0casSQ4QmFkfME4MzQ:-O0ceuvD4cf_rrS7YoZy:b2aun4) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3bda1e3ab51b58b4b4c15f9fee6921165a975ba/crates/blockifier/src/concurrency/worker_logic_test.rs#L700)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Now we are not testing turning on the done marker when we reach the chunk size, right?
</blockquote></details>

You are right!
I moved the new logic to a new test.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2011)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 699 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-O0dCCTtCI86EhYC9NRs:-O0dCCTtCI86EhYC9NRt:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e5e1a26a61ce3b2e1a5dae0c6040819c0857746e/crates/blockifier/src/concurrency/worker_logic_test.rs#L699)):*
> ```XML
>     worker_executor.commit_while_possible();
> 
>     // Verify the commit index is now 3, the status of the last transaction is `Committed`, and the
> ```





_Suggestion:_
```XML
    // Verify the number of comitted transactions is 3, the status of the last transaction is `Committed`, and the
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 740 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-O0dCSeF50BJ5CfA6wr7:-O0dCSeF50BJ5CfA6wr8:b-329jai) ([raw file](https://github.com/starkware-libs/blockifier/blob/e5e1a26a61ce3b2e1a5dae0c6040819c0857746e/crates/blockifier/src/concurrency/worker_logic_test.rs#L740)):*
> ```XML
>     // and simply set max_n_events_in_block to 1, the transaction will fail with a different error,
>     // TransactionTooLarge).
>     let n_events = 2;
> ```

Avoids false search results.



_Suggestion:_
```XML
    // Create two transactions with 2 events to trigger BlockFull (if we use a single transaction
    // and simply set the maximal number of events in the block to 1, the transaction will fail with a different error,
    //(it will be too large to fit a block).
    let n_events = max_n_events_in_block - 1;
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 779 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-O0dD7H13nHcQcp-bzky:-O0dD7H242YspQ_5ei_L:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e5e1a26a61ce3b2e1a5dae0c6040819c0857746e/crates/blockifier/src/concurrency/worker_logic_test.rs#L779)):*
> ```XML
>     // Verify the status both transactions is `Committed`.
>     assert_eq!(*worker_executor.scheduler.get_tx_status(0), TransactionStatus::Committed);
>     assert_eq!(*worker_executor.scheduler.get_tx_status(1), TransactionStatus::Committed);
> ```





_Suggestion:_
```XML
    // Verify the status both transactions is `Committed`.
    assert_eq!(*worker_executor.scheduler.get_tx_status(0), TransactionStatus::Committed);
    assert_eq!(*worker_executor.scheduler.get_tx_status(1), TransactionStatus::Committed);
    
    // Verify that only one transaction was committed.
    assert_eq!(worker_executor.scheduler.get_n_committed_txs(), 1);
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2011)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 699 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-O0dCCTtCI86EhYC9NRs:-O0dFCuN7eMePH21l397:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e5e1a26a61ce3b2e1a5dae0c6040819c0857746e/crates/blockifier/src/concurrency/worker_logic_test.rs#L699)):*
> ```XML
>     worker_executor.commit_while_possible();
> 
>     // Verify the commit index is now 3, the status of the last transaction is `Committed`, and the
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 740 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-O0dCSeF50BJ5CfA6wr7:-O0dFBP66epkNWxnjmoW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e5e1a26a61ce3b2e1a5dae0c6040819c0857746e/crates/blockifier/src/concurrency/worker_logic_test.rs#L740)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Avoids false search results.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 779 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-O0dD7H13nHcQcp-bzky:-O0dFDwW4HpaYM-3Z0cY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e5e1a26a61ce3b2e1a5dae0c6040819c0857746e/crates/blockifier/src/concurrency/worker_logic_test.rs#L779)):*
> ```XML
>     // Verify the status both transactions is `Committed`.
>     assert_eq!(*worker_executor.scheduler.get_tx_status(0), TransactionStatus::Committed);
>     assert_eq!(*worker_executor.scheduler.get_tx_status(1), TransactionStatus::Committed);
> ```

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2011#-:-O0dJGm-AHaQHv_Hu0yF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @meship-starkware)

**Pull request merged**
