### PR TITLE
chore(concurrency): implement validate method in worker logic

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1903)

### CODE REVIEW

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-:-NyLLs3Q0hx3mzFVysKx:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-NyLFeZjAl7_38hMVDUs:-NyLFeZjAl7_38hMVDUt:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c9168c8804e500516206e3dfed5fba72734fff75/crates/blockifier/src/concurrency/worker_logic.rs#L123)):*
> ```XML
>         let read_set_valid = tx_versioned_state.validate_reads(read_set);
> 
>         let aborted = !read_set_valid && self.scheduler.try_validation_abort(tx_index);
> ```





_Suggestion:_
```XML
        let reads = &execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).reads;
        let reads_valid = tx_versioned_state.validate_reads(read_set);

        let aborted = !reads_valid && self.scheduler.try_validation_abort(tx_index);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-NyLFtcf4qjFLFduwfLY:-NyLFtcgCZcwd-m82iTA:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c9168c8804e500516206e3dfed5fba72734fff75/crates/blockifier/src/concurrency/worker_logic.rs#L149)):*
> ```XML
> 
>         let read_set = &execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).reads;
>         let read_set_valid = tx_versioned_state.validate_reads(read_set);
> ```





_Suggestion:_
```XML
        let reads = &execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).reads;
        let reads = tx_versioned_state.validate_reads(read_set);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-NyLG7pyEa0-aBC8bOjP:-NyLG7pyEa0-aBC8bOjQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c9168c8804e500516206e3dfed5fba72734fff75/crates/blockifier/src/concurrency/worker_logic.rs#L207)):*
> ```XML
> }
> 
> // Utils
> ```





_Suggestion:_
```XML
// Utilities.
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1903)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 232 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-NyMDh5e72297OaiHFXD:-NyMDh5fDgh83Ifwk9Es:bv9jbgk) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7b8dc3a6f131738d354d7bec4fe88e280494e06/crates/blockifier/src/concurrency/worker_logic_test.rs#L232)):*
> ```XML
>     });
> 
>     let account_tx1 = account_invoke_tx(invoke_tx_args! {
> ```

I'm not sure where to put this comment. But I think we should make it clear that there is a dependency between the two transactions because they change the same storage key.
Without noticing this detail, it's not obvious why the first validation succeeds and the second fails.



_Suggestion:_
```XML
    // Both transactions change the same storage key.
    let account_tx1 = account_invoke_tx(invoke_tx_args! {
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 257 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-NyMD3Wh3hSZiM0VcOqw:-NyMD3Wh3hSZiM0VcOqx:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7b8dc3a6f131738d354d7bec4fe88e280494e06/crates/blockifier/src/concurrency/worker_logic_test.rs#L257)):*
> ```XML
> 
>     worker_executor.execute(1);
>     worker_executor.execute(0);
> ```





_Suggestion:_
```XML
    // Execute transactions in the wrong order, making the first execution invalid.
    worker_executor.execute(1);
    worker_executor.execute(0);
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 278 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-NyMCHwt8KS9yOb6iEZ8:-NyMCHwt8KS9yOb6iEZ9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7b8dc3a6f131738d354d7bec4fe88e280494e06/crates/blockifier/src/concurrency/worker_logic_test.rs#L278)):*
> ```XML
>     assert_eq!(*worker_executor.scheduler.get_tx_status(tx_index), TransactionStatus::Executed);
> 
>     // Validate failed. Invoke 2 failed validation, only the first lead to a re-execution.
> ```





_Suggestion:_
```XML
    // Validate failed. Invoke 2 failed validations; only the first leads to a re-execution.
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1903)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 232 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-NyMDh5e72297OaiHFXD:-NyOrCezAaBfBeVyJfq5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7b8dc3a6f131738d354d7bec4fe88e280494e06/crates/blockifier/src/concurrency/worker_logic_test.rs#L232)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I'm not sure where to put this comment. But I think we should make it clear that there is a dependency between the two transactions because they change the same storage key.
Without noticing this detail, it's not obvious why the first validation succeeds and the second fails.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 257 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-NyMD3Wh3hSZiM0VcOqw:-NyOrIJEC3oo97tvTQi-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7b8dc3a6f131738d354d7bec4fe88e280494e06/crates/blockifier/src/concurrency/worker_logic_test.rs#L257)):*
> ```XML
> 
>     worker_executor.execute(1);
>     worker_executor.execute(0);
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 278 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-NyMCHwt8KS9yOb6iEZ8:-NyOrVud-wgckwO9eiCd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7b8dc3a6f131738d354d7bec4fe88e280494e06/crates/blockifier/src/concurrency/worker_logic_test.rs#L278)):*
> ```XML
>     assert_eq!(*worker_executor.scheduler.get_tx_status(tx_index), TransactionStatus::Executed);
> 
>     // Validate failed. Invoke 2 failed validation, only the first lead to a re-execution.
> ```

Done.

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-:-NyPXl1z5dWlrrURVfgv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1903#-:-NyPZHERAw8bgraagTYh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
