### PR TITLE
Merge main-v0.12.1 into main

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)

### CODE REVIEW

**Comment by alonh5** [comment]
[Src](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main-v0.12.1#diff-783357e44344438283415c291d26cd2bb0fc6a53a607037495d43459cea04f12) [Dst](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main#diff-783357e44344438283415c291d26cd2bb0fc6a53a607037495d43459cea04f12) crates/blockifier/feature_contracts/cairo1/compiled/account_contract.casm.json
[Src](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main-v0.12.1#diff-c9b60ac7ffd07ea976565a4f73ee20657f90bb003d77440d956368786801b80b) [Dst](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main#diff-c9b60ac7ffd07ea976565a4f73ee20657f90bb003d77440d956368786801b80b) crates/blockifier/src/execution/syscalls/syscalls_test.rs
[Src](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main-v0.12.1#diff-d04d552c3a81553b8faab105c9c4747436e500fd358eddf33f60c09b8cb4ed8c) [Dst](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main#diff-d04d552c3a81553b8faab105c9c4747436e500fd358eddf33f60c09b8cb4ed8c) crates/blockifier/src/transaction/account_transaction.rs
[Src](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main-v0.12.1#diff-ec73f506940d2ffac36e120aa9bcfc30205cb6fd31180e10784759375d03bb26) [Dst](https://github.com/starkware-industries/starkware/compare/4b3273ccbd5c7dec7224dca2e4618cab57c86476..main#diff-ec73f506940d2ffac36e120aa9bcfc30205cb6fd31180e10784759375d03bb26) crates/blockifier/src/transaction/transactions_test.rs

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mM5B-B8UNE8HZUOMP:-N_mM5B-B8UNE8HZUOMQ:b-4dus5r) (no related file):*
Please recompile the precompiled contacts. 

___
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 305 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mMDVW3XHGdVfAbSK9:-N_mMDVW3XHGdVfAbSKA:b64lj6m) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc49b62ad7924f140d8150e25f011a8b1605db3/crates/blockifier/src/transaction/account_transaction.rs#L305)):*
> ```XML
>         }
> 
>         Ok(())
> ```

Are we not taking the refactor to main? 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 264 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mMPLe52njIq7y2tcr:-N_mMPLe52njIq7y2tcs:benf35l) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3abe43a950c80b001e3cc3b86cf60fb57c94eb0/crates/blockifier/src/transaction/transactions_test.rs#L264)):*
> ```XML
> 
> <<<<<<< HEAD
> #[test_case(
> ```

What happened here?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 497 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mPRo5Clq1qv0evHI1:-N_mQy7n1JdagJswsdzB:btxlg72) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc49b62ad7924f140d8150e25f011a8b1605db3/crates/blockifier/src/transaction/account_transaction.rs#L497)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In case of `!charge-fee` we want `actual_fee` to be equal to the actual fee calculated before.
</blockquote></details>

Notice the flag changed it's name and purpose, it's now the opposite of `skip_fee_charge`.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 497 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mPRo5Clq1qv0evHI1:-N_mSmIJ0X6b2pXb8xR3:bw0nne) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc49b62ad7924f140d8150e25f011a8b1605db3/crates/blockifier/src/transaction/account_transaction.rs#L497)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Notice the flag changed it's name and purpose, it's now the opposite of `skip_fee_charge`.
</blockquote></details>

I agree with Noa: this flag only affects whether we actually execute the charge or not; it shouldn't affect the actual fee. 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 264 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mMPLe52njIq7y2tcr:-N_mTClHC_uzoQWB6A8U:b-4parvu) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3abe43a950c80b001e3cc3b86cf60fb57c94eb0/crates/blockifier/src/transaction/transactions_test.rs#L264)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It all looks like big changes, but it's just the `n_steps` values that changed in both, I'm not sure why it showed the whole block as a conflict (I verified this by comparing the texts).
</blockquote></details>

Do you use `[src/dst]diff` to resolve conflicts?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 497 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mPRo5Clq1qv0evHI1:-N_mVxUG2WJJtmTNpIJQ:bds0g1w) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc49b62ad7924f140d8150e25f011a8b1605db3/crates/blockifier/src/transaction/account_transaction.rs#L497)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I agree with Noa: this flag only affects whether we actually execute the charge or not; it shouldn't affect the actual fee. 
</blockquote></details>

This is part of the refactor that Zuphit did. Would you like me to revert it?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 264 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mMPLe52njIq7y2tcr:-N_mWJ8Y0jHH-m-RP-b4:brs6bn) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3abe43a950c80b001e3cc3b86cf60fb57c94eb0/crates/blockifier/src/transaction/transactions_test.rs#L264)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you use `[src/dst]diff` to resolve conflicts? 
</blockquote></details>

WDYM by `[src/dst]diff`?

In this case, I took the correct values of `n_steps`, which changed because of the compiler update (which happened on `0.12.1`).

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 497 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mPRo5Clq1qv0evHI1:-N_maLcZ5UZF0jQ8uMB7:bmb129f) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc49b62ad7924f140d8150e25f011a8b1605db3/crates/blockifier/src/transaction/account_transaction.rs#L497)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is part of the refactor that Zuphit did. Would you like me to revert it?
</blockquote></details>

@zuphitf

**Review by elintul — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 497 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mPRo5Clq1qv0evHI1:-N_maZk43u1uaI30yo9-:b-tv0g33) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc49b62ad7924f140d8150e25f011a8b1605db3/crates/blockifier/src/transaction/account_transaction.rs#L497)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@zuphitf 
</blockquote></details>

It's an additional flag, no need to revert anything. We should simply add an `if change_fee` before executing the transfer itself.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 264 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mMPLe52njIq7y2tcr:-N_m_sni1KPaq8UlFxD3:b-5go6f5) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3abe43a950c80b001e3cc3b86cf60fb57c94eb0/crates/blockifier/src/transaction/transactions_test.rs#L264)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

WDYM by `[src/dst]diff`?

In this case, I took the correct values of `n_steps`, which changed because of the compiler update (which happened on `0.12.1`).
</blockquote></details>

It's part of the script function suite, you can use it to resolve conflicts more comfortably and in a safe way. Please get acquaintant with it, even on this PR (for Qs, ask Noa/Barak).

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: 29 of 30 files reviewed, 2 unresolved discussions (waiting on @elintul and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 497 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mPRo5Clq1qv0evHI1:-N_mdG3NEodbz_89N4Nf:b32wsn) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc49b62ad7924f140d8150e25f011a8b1605db3/crates/blockifier/src/transaction/account_transaction.rs#L497)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's an additional flag, no need to revert anything. We should simply add an `if change_fee` before executing the transfer itself.
</blockquote></details>

np
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 264 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/761#-N_mMPLe52njIq7y2tcr:-N_mbTED7ec5RYvvkF5n:bkf6n13) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3abe43a950c80b001e3cc3b86cf60fb57c94eb0/crates/blockifier/src/transaction/transactions_test.rs#L264)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's part of the script function suite, you can use it to resolve conflicts more comfortably and in a safe way. Please get acquaintant with it, even on this PR (for Qs, ask Noa/Barak).
</blockquote></details>

Sure, thanks.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @zuphitf)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761#-:-N_n0xy_9HRvPtvHERRP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Review by alonh5 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/761)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
