### PR TITLE
Add rust_fmt and clippy scripts.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/669)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`.github/workflows/ci.yml` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/669#-NYvbwTMBAq-0kGvy4Op:-NYvbwTMBAq-0kGvy4Oq:bstdd9o) ([raw file](https://github.com/starkware-libs/blockifier/blob/27bdd61ea0896bc278231613fd2df4b5fb68eb32/.github/workflows/ci.yml#L30)):*
> ```YAML
>       - run: |
>           cargo +nightly-2022-11-03 fmt --all -- --check
>           cargo clippy --all-targets --all-features
> ```

it seems that it didn't work.



_Code quote:_
```YAML
cargo clippy --all-targets --all-features
```

**Comment by ilyalesokhin-starkware** [comment]
*[`.github/workflows/ci.yml` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/669#-NYvbwTMBAq-0kGvy4Op:-NZ-tqDABk30g4l4btiV:b-bx5x71) ([raw file](https://github.com/starkware-libs/blockifier/blob/27bdd61ea0896bc278231613fd2df4b5fb68eb32/.github/workflows/ci.yml#L30)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it seems that it didn't work.
</blockquote></details>

acutally, nvm

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/669#-:-NZ0NU4dEazTkl-630sq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware and @spapinistarkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/669)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/669#-NZ0NVRj2J-F1J56WKU9:-NZ0NVRj2J-F1J56WKUA:b-841hfo) (no related file):*
Rebase over `main-v0.12.0`.

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/669)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware, @elintul, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/669#-NZ0NVRj2J-F1J56WKU9:-NZ0P6PA3-Z06-1SqiTQ:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Rebase over `main-v0.12.0`.
</blockquote></details>

Done.

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/669)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware and @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/669#-:-NZ0Qe1z0et3XFQvKdFS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Pull request merged**
