### PR TITLE
Implement grindy-validate contract in cairo1

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1215)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1215)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo1/account_with_long_validate.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1215#-NktcdAo9VIWCQv4Q4p1:-NktcdAo9VIWCQv4Q4p2:b-mj5vt9) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f5d6494020f694e9cc65ee9cf67c06369fbfb7f/crates/blockifier/feature_contracts/cairo1/account_with_long_validate.cairo#L42)):*
> ```Cairo
>     #[external(v0)]
>     fn __validate_declare__(self: @ContractState, class_hash: felt252) -> felt252 {
>         starknet::VALIDATED
> ```

why not grind also here? as implemented in the cairo 0 contract?

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1215)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1215#-NktiC6yBBwOwCzO0raC:-NktiC6yBBwOwCzO0raD:bgurzfh) (no related file):*
I see that you removed 2 functions compared to the cairo 0 version:  deploy_contract and assert_only_self.
why? and should they also be deleted from the original contract?

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1215)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1215#-NktiC6yBBwOwCzO0raC:-NktlPFS93pnUh21W6xc:b-a8forl) (no related file):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I see that you removed 2 functions compared to the cairo 0 version:  deploy_contract and assert_only_self.
why? and should they also be deleted from the original contract?
</blockquote></details>

assert_only_self is only used in deploy_contract; and I think the deploy_contract function should be implemented only when (if) it will be used.
Specifically, both of these functions can be deleted from the cairo0 contract :) no one uses the grindy-validation account to deploy contracts.
Deleted functions from cairo0 contract

___
___
*[`crates/blockifier/feature_contracts/cairo1/account_with_long_validate.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1215#-NktcdAo9VIWCQv4Q4p1:-Nktl1J83iFc82sJbi1A:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f5d6494020f694e9cc65ee9cf67c06369fbfb7f/crates/blockifier/feature_contracts/cairo1/account_with_long_validate.cairo#L42)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why not grind also here? as implemented in the cairo 0 contract?
</blockquote></details>

Done.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1215)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1215#-:-NkuD8VmBCHJv0RTdYjG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
