### PR TITLE
Refactor check_transaction_execution_error macros.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1294)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1294#-:-NmfhWVX63h8oc3ezekV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1294#-NmfhQvq3cwh3LWRGSeF:-NmfhQvrAJqsYj2rEs27:by3kkdc) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c4d03c79da6d5b89cd3f1c01925e0a587794f7a/crates/blockifier/src/transaction/account_transactions_test.rs#L62)):*
> ```XML
>     check_transaction_execution_error_inner, declare_tx_args, deploy_account_tx_args,
>     invoke_tx_args,
> };
> ```

@dorimedini-starkware Can we decorate the macros so they will not be imported here?



_Code quote:_
```XML
use std::collections::{HashMap, HashSet};

use assert_matches::assert_matches;
use cairo_felt::Felt252;
use cairo_vm::vm::errors::cairo_run_errors::CairoRunError;
use cairo_vm::vm::errors::hint_errors::HintError;
use cairo_vm::vm::errors::vm_errors::VirtualMachineError;
use cairo_vm::vm::errors::vm_exception::VmException;
use cairo_vm::vm::runners::cairo_runner::ResourceTracker;
use crate::transaction::transaction_types::TransactionType;
use crate::transaction::transactions::{DeclareTransaction, ExecutableTransaction};
use crate::{
    check_entry_point_execution_error_for_custom_hint,
    check_entry_point_execution_error_for_invalid_scenario,
    check_transaction_execution_error_for_invalid_scenario,
    check_transaction_execution_error_inner, declare_tx_args, deploy_account_tx_args,
    invoke_tx_args,
};
```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1294)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1294#-NmfhQvq3cwh3LWRGSeF:-Nmfhk3-EFTw2YFGZ5Su:b-fuvz9f) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c4d03c79da6d5b89cd3f1c01925e0a587794f7a/crates/blockifier/src/transaction/account_transactions_test.rs#L62)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@dorimedini-starkware Can we decorate the macros so they will not be imported here?
</blockquote></details>

WDYM by "decorate"?

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1294#-NmfhQvq3cwh3LWRGSeF:-Nmfkj3D5rbD_hIXV9el:b4ysbpq) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c4d03c79da6d5b89cd3f1c01925e0a587794f7a/crates/blockifier/src/transaction/account_transactions_test.rs#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM by "decorate"?
</blockquote></details>

We solved the imports of the types. Can we solve the ugliness of importing: `check_transaction_execution_error_inner`?
It sounds like not... Unblocking myself.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1294)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1294)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by dorimedini-starkware — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1294)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1338 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1294#-Nmjg8hcCWslWV6zr018:-Nmjg8hcCWslWV6zr019:biu8i3) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d7cb4c710217c9a27cb933592b44d5ddf059c0/crates/blockifier/src/transaction/transactions_test.rs#L1338)):*
> ```XML
>     );
>     let error = account_tx.execute(state, block_context, true, true).unwrap_err();
>     check_transaction_execution_error_for_invalid_scenario!(cairo_version, error, false,);
> ```

drop the trailing `,`



_Suggestion:_
```XML
 false
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1435 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1294#-NmjgQOK8m7dVwjFl76t:-NmjgQOK8m7dVwjFl76u:b-ebupqc) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d7cb4c710217c9a27cb933592b44d5ddf059c0/crates/blockifier/src/transaction/transactions_test.rs#L1435)):*
> ```XML
>     );
>     let error = account_tx.execute(state, block_context, true, true).unwrap_err();
>     check_transaction_execution_error_for_invalid_scenario!(cairo_version, error, true,);
> ```

drop trailing `,`



_Suggestion:_
```XML
true
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1294)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1338 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1294#-Nmjg8hcCWslWV6zr018:-Nmjk4Cy-d5h_yS2Dm3m:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d7cb4c710217c9a27cb933592b44d5ddf059c0/crates/blockifier/src/transaction/transactions_test.rs#L1338)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

drop the trailing `,`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1435 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1294#-NmjgQOK8m7dVwjFl76t:-Nmjk4vv1wZxZV99dggM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8d7cb4c710217c9a27cb933592b44d5ddf059c0/crates/blockifier/src/transaction/transactions_test.rs#L1435)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

drop trailing `,`
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1294#-:-Nmjpd9L-pUNDg6lhpaK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

**Pull request merged**
