### PR TITLE
Implement get_balance on State

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`Cargo.toml` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxvwhJ8WF0nKNCmwJm:-NVxvwhJ8WF0nKNCmwJn:b-nojcyn) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/Cargo.toml#L32)):*
> ```TOML
> sha3 = "0.10.6"
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "24a7249" }
> starknet-crypto = "0.2.0"
> ```

If you have any other ideas how to take the result of `get_storage_var_address("ERC20_balances", &[*address.0.key()])?`, and add `1` to it, without importing this crate for `FieldElement`, PLMK
___
*[`crates/blockifier/src/state/state_api.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxwOjEB-Kh47NbqJAN:-NVxwOjEB-Kh47NbqJAO:bpecop1) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/crates/blockifier/src/state/state_api.rs#L53)):*
> ```XML
>         let base_key = get_storage_var_address("ERC20_balances", &[*address.0.key()])?;
>         let high = self.get_storage_at(block_context.fee_token_address, base_key)?;
>         let low = self.get_storage_at(
> ```

any idea how I can tell for sure that the `low` and `high` are correct?
which type do we have that can be 256 bits, and has comparison operators?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxw_RUBME3rEGPS1IY:-NVxw_RUBME3rEGPS1IZ:b57qf3j) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/crates/blockifier/src/transaction/transactions_test.rs#L82)):*
> ```XML
>     let storage_view = HashMap::from([
>         ((test_erc20_address, erc20_account_balance_key), stark_felt!(initial_account_balance)),
>         // Give the account mint permission.
> ```

Easiest way to control precise balances in tests IMO



_Code quote:_
```XML
// Give the account mint permission.
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/state/state_api.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxyMeQE9uMn56UIg9q:-NVxyMeQE9uMn56UIg9r:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/crates/blockifier/src/state/state_api.rs#L48)):*
> ```XML
>     fn get_fee_token_balance(
>         &mut self,
>         address: &ContractAddress,
> ```





_Suggestion:_
```XML
contract_address: &ContractAddress,
```
___
*[`crates/blockifier/src/state/state_api.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxyeMwCOAq5s6NE7yY:-NVxyeMwCOAq5s6NE7yZ:b-atykke) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/crates/blockifier/src/state/state_api.rs#L53)):*
> ```XML
>         let base_key = get_storage_var_address("ERC20_balances", &[*address.0.key()])?;
>         let high = self.get_storage_at(block_context.fee_token_address, base_key)?;
>         let low = self.get_storage_at(
> ```

See https://github.com/starkware-industries/starkware/blob/256c5f4526d9692d6b04b5126a476d1ee5e21028/src/starkware/cairo/common/uint256.cairo#L9



_Suggestion:_
```XML
        let low = self.get_storage_at(block_context.fee_token_address, base_key)?;
        let high = self.get_storage_at(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/state_api.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxyMeQE9uMn56UIg9q:-NVy-0XME83mtoXmqqTJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/crates/blockifier/src/state/state_api.rs#L48)):*
> ```XML
>     fn get_fee_token_balance(
>         &mut self,
>         address: &ContractAddress,
> ```

Done.
___
*[`crates/blockifier/src/state/state_api.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxyeMwCOAq5s6NE7yY:-NVy--kpErvOq1SdKOMg:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/crates/blockifier/src/state/state_api.rs#L53)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

See https://github.com/starkware-industries/starkware/blob/256c5f4526d9692d6b04b5126a476d1ee5e21028/src/starkware/cairo/common/uint256.cairo#L9
</blockquote></details>

Done.

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`Cargo.toml` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxvwhJ8WF0nKNCmwJm:-NVy-7CJ6ZUPOEN0fR0j:b-3brbc2) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/Cargo.toml#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

If you have any other ideas how to take the result of `get_storage_var_address("ERC20_balances", &[*address.0.key()])?`, and add `1` to it, without importing this crate for `FieldElement`, PLMK
</blockquote></details>

I think you can use LC's felt.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`Cargo.toml` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxvwhJ8WF0nKNCmwJm:-NVy0L-o9koWOJY1sUBJ:b-3r6rdq) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/Cargo.toml#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think you can use LC's felt.
</blockquote></details>

I thought to be consistent with starknet-api, which defines `StarkFelt` and conversions between `StarkFelt` and `FieldElement`

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`Cargo.toml` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxvwhJ8WF0nKNCmwJm:-NVy0hA58R_WU0rWjLyW:b-ddg2yq) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/Cargo.toml#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I thought to be consistent with starknet-api, which defines `StarkFelt` and conversions between `StarkFelt` and `FieldElement`
</blockquote></details>

I guess the good way to be to implement arithmetic operators on `StarkFelt`... though if that's the case maybe we should just stop using `StarkFelt` entirely, and use some agreed-upon struct...
so let's wait for DanB's meeting

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`Cargo.toml` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVxvwhJ8WF0nKNCmwJm:-NVy0vGhB_jjrObwZaNU:b4w3vdm) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/Cargo.toml#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I guess the good way to be to implement arithmetic operators on `StarkFelt`... though if that's the case maybe we should just stop using `StarkFelt` entirely, and use some agreed-upon struct...
so let's wait for DanB's meeting
</blockquote></details>

Put a TODO for now

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/state_api.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVy-hR632khbAMrwhDt:-NVy-hR632khbAMrwhDu:b-hv4b2q) ([raw file](https://github.com/starkware-libs/blockifier/blob/4ed9dfeb4eb57222e9c69ab096d569ac873c1767/crates/blockifier/src/state/state_api.rs#L49)):*
> ```XML
>         &mut self,
>         contract_address: &ContractAddress,
>         block_context: &BlockContext,
> ```

Move after `self`? It's a more generic argument than the contract address.



_Code quote:_
```XML
block_context: &BlockContext,
```
___
*[`crates/blockifier/src/state/state_api.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVy0bx88l0LHHnq2Txw:-NVy0bx88l0LHHnq2Txx:bu5f7id) ([raw file](https://github.com/starkware-libs/blockifier/blob/4ed9dfeb4eb57222e9c69ab096d569ac873c1767/crates/blockifier/src/state/state_api.rs#L59)):*
> ```XML
>             StorageKey(PatriciaKey::try_from(StarkFelt::from(
>                 FieldElement::from(*base_key.0.key()) + FieldElement::ONE,
>             ))?),
> ```

Give this a name, please. Perhaps `[low/high]_key`, `[lsb/msb]_key`, something similar.



_Code quote:_
```XML
            StorageKey(PatriciaKey::try_from(StarkFelt::from(
                FieldElement::from(*base_key.0.key()) + FieldElement::ONE,
            ))?),
```
___
*[`crates/blockifier/src/state/state_api.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVy0tnkAfYhpg155uCJ:-NVy0tnkAfYhpg155uCK:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/4ed9dfeb4eb57222e9c69ab096d569ac873c1767/crates/blockifier/src/state/state_api.rs#L61)):*
> ```XML
>             ))?),
>         )?;
>         Ok((low, high))
> ```

Add a blank line above.



_Code quote:_
```XML
Ok((low, high))
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVy12lmBMswrAFhfmTb:-NVy12lmBMswrAFhfmTc:ba32x4z) ([raw file](https://github.com/starkware-libs/blockifier/blob/4ed9dfeb4eb57222e9c69ab096d569ac873c1767/crates/blockifier/src/transaction/transactions_test.rs#L87)):*
> ```XML
>                 test_erc20_address,
>                 get_storage_var_address("permitted_minter", &[])
>                     .expect("Failed to get permitted_minter storage address."),
> ```

Consider giving this a name, a bit hard to read with all the `tuple`ing going on.



_Code quote:_
```XML
                get_storage_var_address("permitted_minter", &[])
                    .expect("Failed to get permitted_minter storage address."),
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVyJtPvB4StpfcAUMh5:-NVyJtPwDNZ4_quijSnl:b-vth7aw) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/crates/blockifier/src/transaction/transactions_test.rs#L387)):*
> ```XML
> 
>     // Get balance from state, and validate.
>     let (high, low) = state
> ```

Swap, everywhere

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVyJtPvB4StpfcAUMh5:-NVyKE5cCJatFYM1laFw:bbnggso) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/crates/blockifier/src/transaction/transactions_test.rs#L387)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Swap, everywhere 
</blockquote></details>

WDYM? It should be correct now; `low` is before `high` everywhere

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/501#-:-NVyNCd7BkL_ML93FSYz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/501#-NVyJtPvB4StpfcAUMh5:-NVyN-1yB4jshidqQ4gX:b-luknql) ([raw file](https://github.com/starkware-libs/blockifier/blob/08dc3d2447c6df62dc9f02b85bf10c76ad07ec8d/crates/blockifier/src/transaction/transactions_test.rs#L387)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM? It should be correct now; `low` is before `high` everywhere
</blockquote></details>

Oops, I looked at r1 here

**Pull request merged**
