### PR TITLE
feat(execution): implement execute_txs

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
Python side https://reviewable.io/reviews/starkware-industries/starkware/34875

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-:-NwuL-PH1jUUW1abrNBS:b-6fl4au)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @barak-b-starkware, @nimrod-starkware, and @noaov1)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7oq4jAo15f5RvrbVZ:-Nx7oq4jAo15f5RvrbV_:b10jewi) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L226)):*
> ```XML
>                 py_tx(tx, optional_py_class_info).expect(PY_TX_PARSING_ERR)
>             })
>             .collect();
> ```

use `unzip`, seems nicer (single iteration).



_Suggestion:_
```XML
        let (tx_types, txs): (Vec<String, Vec<Transaction>) = txs_with_class_infos
            .iter()
            .map(|(tx, optional_py_class_info)| {
                (
                    get_py_tx_type(tx).expect(PY_TX_PARSING_ERR).to_string(),
                    py_tx(tx, optional_py_class_info).expect(PY_TX_PARSING_ERR)
                )
            })
            .unzip()
            .collect();
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7p_JOEokGviWtc84S:-Nx7p_JOEokGviWtc84T:b-i16dp) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L232)):*
> ```XML
> 
>         // Process results.
>         // TODO(Yoni, 15/5/2024): use rayon.
> ```

prefer tokio, or talk to Ittay about it?



_Code quote:_
```XML
rayon
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7qEaU1wRCQyMuSqiB:-Nx7qEaU1wRCQyMuSqiC:b-v4iusn) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L236)):*
> ```XML
>         let serialized_results: Vec<(bool, RawTransactionExecutionResult)> = results
>             .into_iter()
>             .zip(tx_types)
> ```

the `results` vector could have less entries than the `tx_types` vector, correct?
is this safe to zip?



_Code quote:_
```XML
.zip(tx_types)
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7qRwu7ISf5vPggXy8:-Nx7qRwu7ISf5vPggXy9:b-jdpky8) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L239)):*
> ```XML
>             .map(|(result, tx_type)| match result {
>                 Ok(tx_execution_info) => (
>                     true,
> ```

this can still mean reverted, you are aware, yes?



_Code quote:_
```XML
true
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7qfpr8BfTBuA0n4d4:-Nx7qfpr8BfTBuA0n4d5:bb7phvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L256)):*
> ```XML
>             let py_serialized_results: Vec<(bool, Py<PyBytes>)> = serialized_results
>                 .into_iter()
>                 .map(|(sucess, execution_result)| {
> ```

typo



_Suggestion:_
```XML
success
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 551 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7pjt98VAB3rAz-Mzd:-Nx7pjtA-UnskmDKBIGu:bw02lz) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L551)):*
> ```XML
>     // TODO(Yoni, 1/7/2024): re-consider this serialization.
>     serde_json::to_vec(&format!("{}", error)).expect(RESULT_SERIALIZE_ERR)
> }
> ```

why not `impl Serialize for TransactionExecutorError`?



_Code quote:_
```XML
fn serialize_failure_reason(error: TransactionExecutorError) -> RawTransactionExecutionResult {
    // TODO(Yoni, 1/7/2024): re-consider this serialization.
    serde_json::to_vec(&format!("{}", error)).expect(RESULT_SERIALIZE_ERR)
}
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @dorimedini-starkware, @MohammadNassar1, and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7oq4jAo15f5RvrbVZ:-Nx80PA96dodkIYeAE4n:b-89q77x) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L226)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `unzip`, seems nicer (single iteration).
</blockquote></details>

Cool!
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7p_JOEokGviWtc84S:-Nx80aZ42Kj6-eMaMisk:b-y3wosr) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L232)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

prefer tokio, or talk to Ittay about it?
</blockquote></details>

Either, I'm talking about the serialization
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7qEaU1wRCQyMuSqiB:-Nx80iXP0309AChrpoZr:b-9uurvu) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L236)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the `results` vector could have less entries than the `tx_types` vector, correct?
is this safe to zip?
</blockquote></details>

Right, it's **not** a safe zip. Added a comment
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7qRwu7ISf5vPggXy8:-Nx81Lzc3FyEgxBt8rOi:b-m7h6sr) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L239)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this can still mean reverted, you are aware, yes?
</blockquote></details>

Right, reverted is still "accepted"
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 551 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7pjt98VAB3rAz-Mzd:-Nx81YvH5gFoF_NIUSaQ:b-6h2aj8) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L551)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not `impl Serialize for TransactionExecutorError`?
</blockquote></details>

Because I'll need to impl it manually, for all error enums (`derive` doesn't work)
I have a todo to reconsider this

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-:-Nx82fqa7-g7JaTvBGWi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @MohammadNassar1, and @noaov1)

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7qEaU1wRCQyMuSqiB:-Nx85gCj8n_JiCOFStUY:b-z0qq5a) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L236)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Right, it's **not** a safe zip. Added a comment
</blockquote></details>

What happens in this case?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7qEaU1wRCQyMuSqiB:-Nx86IadBBmCbqcUW1gL:bza6e6l) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L236)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

What happens in this case?
</blockquote></details>

The iteration is over once the shortest iterator is over

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-:-Nx8A9ItD4Pt9qXhNwJK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-Nx7qEaU1wRCQyMuSqiB:-Nx8A6dt0GSVFVONMQh0:bo5cp9s) ([raw file](https://github.com/starkware-libs/blockifier/blob/81116f13b0438d6de9c60ebd639ff0fa1d5ebcb3/crates/native_blockifier/src/py_block_executor.rs#L236)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The iteration is over once the shortest iterator is over
</blockquote></details>

Nice (:

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1859#-:-Nx8BGXLCkFmxZgr8M8Y:b-ucfknh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @noaov1)

**Pull request merged**
