### PR TITLE
Objects and methods for STRK gas price calculation

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/928)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 
FYI @zuphitf 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/928#-:-NenEDsg7DmcLCi35H53:b1q0l4g)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/928)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/fee/strk_gas_price.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-NeqXvlD1sZQwYE7ECem:-NeqXvlD1sZQwYE7ECen:b-xowb3p) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price.rs#L30)):*
> ```XML
>         let rhs = other.total_strk.clone() * self.total_wei.clone();
>         lhs.cmp(&rhs)
>     }
> ```

wei to strk ratio comparison means `(self.wei / self.strk) <= (other.wei / other.strk)`; or, `self.wei * other.strk <= self.strk * other.wei`.
what you are checking ATM is strk to wei ratio.
either make this change or rename to `compare_strk_to_wei_ratio`
(after reading ahead, I guess just renaming the function is all that's needed)



_Suggestion:_
```XML
    pub fn compare_wei_to_strk_ratio(&self, other: &Self) -> Ordering {
        //  a / b < c / d <=> a * d < c * b. The same is true for the other orders.
        let lhs = self.total_wei.clone() * other.total_strk.clone();
        let rhs = other.total_wei.clone() * self.total_strk.clone();
        lhs.cmp(&rhs)
    }
```
___
*[`crates/blockifier/src/fee/strk_gas_price.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-NeqZOA6DVlFo4Ho8KPw:-NeqZOA6DVlFo4Ho8KPx:b-6jdcyq) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price.rs#L69)):*
> ```XML
>     pub fn calc_median_values(sorted_pool_states: &[PoolState]) -> (BigUint, BigUint) {
>         let total_weight: BigUint =
>             sorted_pool_states.iter().map(|state| (state.tvl_in_wei())).sum::<BigUint>();
> ```

redundant parens?



_Suggestion:_
```XML
state.tvl_in_wei()
```
___
*[`crates/blockifier/src/fee/strk_gas_price.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-NeqZTEPBgdKNT-xQkuN:-NeqZTEPBgdKNT-xQkuO:b-9kdvfx) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price.rs#L71)):*
> ```XML
>             sorted_pool_states.iter().map(|state| (state.tvl_in_wei())).sum::<BigUint>();
> 
>         // Find idx of weighted median STRK / Wei ratio.
> ```

no need for shorthand in comments



_Suggestion:_
```XML
index
```
___
*[`crates/blockifier/src/fee/strk_gas_price.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-Neq_7R45_Sicngr8dtD:-Neq_7R45_Sicngr8dtE:bi72nlk) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price.rs#L97)):*
> ```XML
>             median_pool_wei_tvl = sorted_pool_states[median_idx].total_wei.clone();
>         }
>         (median_pool_strk_tvl, median_pool_wei_tvl)
> ```

WDYT? non-blockiing



_Suggestion:_
```XML
        if equal_weight_partition {
            ((sorted_pool_states[median_idx].total_strk.clone()
                + sorted_pool_states[median_idx + 1].total_strk.clone())
                / BigUint::from(2_u32),
            (sorted_pool_states[median_idx].total_wei.clone()
                + sorted_pool_states[median_idx + 1].total_wei.clone())
                / BigUint::from(2_u32))
        } else {
            (sorted_pool_states[median_idx].total_strk.clone(),
            sorted_pool_states[median_idx].total_wei.clone())
        }
```
___
*[`crates/blockifier/src/fee/strk_gas_price_test.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-Neq_S6A2_4WlC_Elvz4:-Neq_S6A2_4WlC_Elvz5:b-f38dmb) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price_test.rs#L16)):*
> ```XML
>     let state_2 = PoolState { total_wei: wei_2, total_strk: strk_2 };
>     let state_3 = PoolState { total_wei: wei_3, total_strk: strk_3 };
>     let state_4 = PoolState { total_wei: wei_1, total_strk: BigUint::from(150_u32) };
> ```

consider defining `strk_4`, it's weird that this is the only unnamed constant



_Code quote:_
```XML
BigUint::from(150_u32)
```
___
*[`crates/blockifier/src/fee/strk_gas_price_test.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-Neq__k2162WTefbtHab:-Neq__k2162WTefbtHac:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price_test.rs#L22)):*
> ```XML
>     assert!(matches!(PoolStateAggregator::new(&[]), Err(StrkGasPriceCalcError::NoPoolStatesError)));
> 
>     // convert Wei -> STRK with a single pool state.
> ```





_Suggestion:_
```XML
Convert
```
___
*[`crates/blockifier/src/fee/strk_gas_price_test.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-Neq_hQXCjxajj3jYIty:-Neq_hQXCjxajj3jYItz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price_test.rs#L30)):*
> ```XML
>     );
> 
>     // convert Wei -> STRK with multiple pool states, no equal weight partition.
> ```





_Suggestion:_
```XML
Convert
```
___
*[`crates/blockifier/src/fee/strk_gas_price_test.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-Neqa4DW7fFUIZ0lAb1p:-Neqa4DW7fFUIZ0lAb1q:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price_test.rs#L44)):*
> ```XML
>     );
> 
>     // convert Wei -> STRK with multiple pool states with equal weight partition.
> ```





_Suggestion:_
```XML
Convert
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/928)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/strk_gas_price.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-NeqXvlD1sZQwYE7ECem:-Ner10P_2CM1ZWeC_YCM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price.rs#L30)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wei to strk ratio comparison means `(self.wei / self.strk) <= (other.wei / other.strk)`; or, `self.wei * other.strk <= self.strk * other.wei`.
what you are checking ATM is strk to wei ratio.
either make this change or rename to `compare_strk_to_wei_ratio`
(after reading ahead, I guess just renaming the function is all that's needed)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/strk_gas_price.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-NeqZOA6DVlFo4Ho8KPw:-Ner1D9J7tEeW-Fe8Ur1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price.rs#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

redundant parens?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/strk_gas_price.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-NeqZTEPBgdKNT-xQkuN:-Ner1Lpz7O9P07RImES9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need for shorthand in comments
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/strk_gas_price.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-Neq_7R45_Sicngr8dtD:-Ner1ilq-LVzBZ-3tkPz:b-bqdg5f) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYT? non-blockiing
</blockquote></details>

hmm doesn't really improve readability IMO
___
*[`crates/blockifier/src/fee/strk_gas_price_test.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/928#-Neq_S6A2_4WlC_Elvz4:-Ner2EU7BFc_Xsq4xSb4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/713ae4641703957c660422e51463f610fdb389c6/crates/blockifier/src/fee/strk_gas_price_test.rs#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider defining `strk_4`, it's weird that this is the only unnamed constant
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/928#-:-Ner3N2SAC_s9Gk2pG58:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/928)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
