### PR TITLE
Add a query version bit.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1042)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1042)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-Nhq0Cxa9oeteRCPNeRw:-Nhq0CxbC-lC3ONrFcCw:b-naybuc) ([raw file](https://github.com/starkware-libs/blockifier/blob/0a664b3eaf4ee4a8d3a8467dee90e964cb255363/crates/blockifier/src/transaction/account_transaction.rs#L160)):*
> ```XML
>         let mut version = self.version();
>         if simulate {
>             let query_version_base = BigUint::from(2_u8).pow(QUERY_VERSION_BASE_BIT);
> ```

can this be constant?
or at least lazy_static?



_Code quote:_
```XML
BigUint::from(2_u8).pow(QUERY_VERSION_BASE_BIT);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-NhuMq__Ed-hF_CUW3NT:-NhuMq__Ed-hF_CUW3NU:b-xx0qkj) ([raw file](https://github.com/starkware-libs/blockifier/blob/83c52e5e70ca2bd11e2835673706760ae11b110c/crates/blockifier/src/transaction/account_transactions_test.rs#L103)):*
> ```XML
>     );
> 
>     let account_tx = AccountTransaction::DeployAccount(deploy_account_tx);
> ```

can you add a test where the simulate bit is `true`?
enough to parametrize an existing test... it shouldn't effect the test itself IIUC
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1121 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-NhuNouU0tlVDspUzvhi:-NhuNouU0tlVDspUzvhj:bwvuz8u) ([raw file](https://github.com/starkware-libs/blockifier/blob/83c52e5e70ca2bd11e2835673706760ae11b110c/crates/blockifier/src/transaction/transactions_test.rs#L1121)):*
> ```XML
>     let account_tx = AccountTransaction::Invoke(InvokeTransaction::V1(invoke_tx));
> 
>     account_tx.execute(state, block_context, true, true, true).unwrap();
> ```

anything to check on the resulting execution info? is the version written there somewhere?
also, please add `assert!(!tx_execution_info.is_reverted())`

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1042)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-Nhq0Cxa9oeteRCPNeRw:-NhuTQ7wAt7CQv66lGin:b-eohk1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/0a664b3eaf4ee4a8d3a8467dee90e964cb255363/crates/blockifier/src/transaction/account_transaction.rs#L160)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can this be constant?
or at least lazy_static?
</blockquote></details>

It can be lazy_static but that requires adding a dependency in the Cargo.toml (`once_cell`).
I wanted to avoid that in this PR (added a TODO above the constant) but can do it if you think it's necessary.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-NhuMq__Ed-hF_CUW3NT:-NhuaY50-CdYJbeH7Vkz:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/83c52e5e70ca2bd11e2835673706760ae11b110c/crates/blockifier/src/transaction/account_transactions_test.rs#L103)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you add a test where the simulate bit is `true`?
enough to parametrize an existing test... it shouldn't effect the test itself IIUC
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1121 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-NhuNouU0tlVDspUzvhi:-NhuaHa16s1BtjFicS62:b-fxkhkw) ([raw file](https://github.com/starkware-libs/blockifier/blob/83c52e5e70ca2bd11e2835673706760ae11b110c/crates/blockifier/src/transaction/transactions_test.rs#L1121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

anything to check on the resulting execution info? is the version written there somewhere?
also, please add `assert!(!tx_execution_info.is_reverted())`
</blockquote></details>

I tested that the output of the syscall contains the correct version (see `expected_tx_info`).
Done.
[Pre-PR](https://reviewable.io/reviews/starkware-libs/blockifier/1051).

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1042)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-Nhq0Cxa9oeteRCPNeRw:-Nhugv-R9KJtmLu6VOPe:bye9dlp) ([raw file](https://github.com/starkware-libs/blockifier/blob/0a664b3eaf4ee4a8d3a8467dee90e964cb255363/crates/blockifier/src/transaction/account_transaction.rs#L160)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can this be constant?
or at least lazy_static?
</blockquote></details>

+1
But plz use `once_cell::sync::Lazy` since `lazy_static` [is deprecated](https://github.com/rust-lang-nursery/lazy-static.rs/issues/214)
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-NhueEmt8FCf50YmUuJQ:-NhueEmt8FCf50YmUuJR:b2w09ot) ([raw file](https://github.com/starkware-libs/blockifier/blob/83c52e5e70ca2bd11e2835673706760ae11b110c/crates/blockifier/src/transaction/account_transaction.rs#L153)):*
> ```XML
>                 InvokeTransaction::V0(_) => TransactionVersion(StarkFelt::from(0_u8)),
>                 InvokeTransaction::V1(_) => TransactionVersion(StarkFelt::from(1_u8)),
>             },
> ```

Export to SN API? That is, add a`version()` method to `InvokeTransaction` that'll basically be identical to the one in `DeclareTransaction` (not sure if it's possible to do this without duplicating the version() logic)



_Code quote:_
```XML
            Self::Invoke(tx) => match tx {
                InvokeTransaction::V0(_) => TransactionVersion(StarkFelt::from(0_u8)),
                InvokeTransaction::V1(_) => TransactionVersion(StarkFelt::from(1_u8)),
            },
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 211 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-NhutXLyAT4KaqpkJaY_:-NhutXLyAT4KaqpkJaYa:b-2xylvy) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7d1a0f8235172633471ce7c9d93054903c7f62e/crates/blockifier/src/transaction/account_transaction.rs#L211)):*
> ```XML
>             }
>             false => version,
>         };
> ```

IMO one of those rare cases where if-else is better (also shorter) than `match` 



_Suggestion:_
```XML
        let version = if simulate {
            let simulate_version_base = BigUint::from(2_u8).pow(SIMULATE_VERSION_BASE_BIT);
            let adjusted_version = felt_to_biguint(version.0) - simulate_version_base;
            TransactionVersion(
                biguint_to_felt(adjusted_version).expect("The version should be a field element."),
            )
        } else {
            version
        };
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1042)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1042)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 458 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-NhuwHiA1Ut5VVQxj7dK:-NhuwHiA1Ut5VVQxj7dL:b-c2r6x2) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7d1a0f8235172633471ce7c9d93054903c7f62e/crates/blockifier/src/transaction/account_transaction.rs#L458)):*
> ```XML
>         mut execution_context: EntryPointExecutionContext,
>         validate: bool,
>         simulate: bool,
> ```

If we're already passing multiple context args everywhere, we might as well initialize `AccountTransactionExecutionContext` "at the root level" and pass it around (is it immutable?).
@noaov1  Is that possible?

This aligns well with our refactoring plans.
(I'm talking about a follow-up PR here, this shouldn't hold up the current one.)

WDYT @noaov1 @dorimedini-starkware @elintul ?



_Code quote:_
```XML
        validate: bool,
        simulate: bool,
```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1042)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 458 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-NhuwHiA1Ut5VVQxj7dK:-Nhv0N9X5sRouizKALVI:bwflen) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7d1a0f8235172633471ce7c9d93054903c7f62e/crates/blockifier/src/transaction/account_transaction.rs#L458)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If we're already passing multiple context args everywhere, we might as well initialize `AccountTransactionExecutionContext` "at the root level" and pass it around (is it immutable?).
@noaov1  Is that possible?

This aligns well with our refactoring plans.
(I'm talking about a follow-up PR here, this shouldn't hold up the current one.)

WDYT @noaov1 @dorimedini-starkware @elintul ?
</blockquote></details>

you are planning to remove `get_account_transaction_context()`?
what refactor are you talking about?
not in context to have an opinion here

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1042)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 458 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-NhuwHiA1Ut5VVQxj7dK:-Nhv53u-25zpBmFjCfXq:b9oh07f) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7d1a0f8235172633471ce7c9d93054903c7f62e/crates/blockifier/src/transaction/account_transaction.rs#L458)):*
>you are planning to remove get_account_transaction_context()?

Yep, having to initialize it at the onset of every function isn't ideal (duplication/boilerplate).

>what refactor are you talking about?

Haven't settled on anything yet, at the very least we can split it into smaller ctx objects (this is a non-trivial task since it is passed around a lot).

Anyhow, this doesn't have to be agreed upon at this PR, i just mentioned it to provide additional context.
In other words, i think passing around the instance is preferable to passing a bunch of boolean args for it initialization, even if the refactor i mentioned doesn't end up happening.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-Nhv1T7g9_InJKPB3cff:-Nhv1T7g9_InJKPB3cfg:b-r8t0fa) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7d1a0f8235172633471ce7c9d93054903c7f62e/crates/blockifier/src/transaction/test_utils.rs#L88)):*
> ```XML
>         account_balance,
>         ContractClassV0::from_file(TEST_CONTRACT_CAIRO0_PATH).into(),
>     )
> ```

Let's add a `create_cairo0_account_tx_test_state` wrapper which has a hardcoded `TEST_CONTRACT_CAIRO0_PATH`, and similarly for the CAIRO1 usage you added



_Code quote:_
```XML
    create_account_tx_test_state(
        ContractClassV0::from_file(ACCOUNT_CONTRACT_CAIRO0_PATH).into(),
        TEST_ACCOUNT_CONTRACT_CLASS_HASH,
        TEST_ACCOUNT_CONTRACT_ADDRESS,
        test_erc20_account_balance_key(),
        account_balance,
        ContractClassV0::from_file(TEST_CONTRACT_CAIRO0_PATH).into(),
    )
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-Nhv27O71iSeBOwSP9E6:-Nhv27O71iSeBOwSP9E7:bkflk50) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7d1a0f8235172633471ce7c9d93054903c7f62e/crates/blockifier/src/transaction/transaction_utils.rs#L68)):*
> ```XML
> }
> 
> // TODO: Convert to a `TryFrom` cast and put in starknet-api (In StarkFelt).
> ```

Ditto for the second comment



_Suggestion:_
```XML
// TODO: Convert to a `TryFrom` cast and put in starknet-api (In StarkFelt), gated behind `num-bigint` feature (for the sake of no-std users).
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1130 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1042#-Nhv4Ysg-9VEZ9u2g7sb:-Nhv4Ysg-9VEZ9u2g7sc:bw3yvon) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7d1a0f8235172633471ce7c9d93054903c7f62e/crates/blockifier/src/transaction/transactions_test.rs#L1130)):*
> ```XML
>             .concat()
>             .into(),
>     );
> ```

can you use `calldata!` here?



_Code quote:_
```XML
    let execute_calldata = vec![
        stark_felt!(TEST_CONTRACT_ADDRESS), // Contract address.
        entry_point_selector.0,             // EP selector.
        stark_felt!(calldata_len as u64),   // Calldata length.
    ];
    let execute_calldata = Calldata(
        [execute_calldata, expected_block_info.to_vec(), expected_tx_info, expected_call_info]
            .concat()
            .into(),
    );
```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1042)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

**Pull request closed without merging**
