### PR TITLE
Return `Arc<ContractClass>` from `get_contract_class()` API.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/277)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/277)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/papyrus_state_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/277#-NOFVagqAOGLlg8Sa6c2:-NOFVagqAOGLlg8Sa6c3:b-m83896) ([raw file](https://github.com/starkware-libs/blockifier/blob/921feb47481e89589744a35eaa298a54d2ff1fc6/crates/blockifier/src/state/papyrus_state_test.rs#L32)):*
> ```XML
>     let declared_classes = IndexMap::from([(
>         ClassHash(stark_felt!(TEST_CLASS_HASH)),
>         starknet_api::state::ContractClass::from((*get_test_contract_class()).clone()),
> ```

Would love an alternative here.



_Code quote:_
```XML
(*get_test_contract_class()).clone()
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @Yoni-Starkware)

**Comment by elintul** [comment]
Reminder to merge.

**Review by giladchase — COMMENTED** [review]
What's the motivation for this change?

> Reviewed 1 of 6 files at r1, 3 of 5 files at r3, 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/277#-:-NRYqdbw7fg9WfoJ7AtQ:b-2ily24)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 117 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/277#-NRYx0V8CjuCIU5iRfi1:-NRYx0V8CjuCIU5iRfi2:b-h14bbj) ([raw file](https://github.com/starkware-libs/blockifier/blob/df03de702d49f9eb3ab7285170fe7a062a7790d7/crates/blockifier/src/test_utils.rs#L117)):*
> ```XML
>         let contract_class = self.class_hash_to_class.get(class_hash).cloned();
>         match contract_class {
>             Some(contract_class) => Ok(Arc::from(contract_class)),
> ```

Do you prefer `Arc::from` over `Arc::new`? (they [are equivalent](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.from-10))



_Code quote:_
```XML
Arc::from(
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/277#-NRYu7iD5l5u88BZKbDd:-NRYu7iD5l5u88BZKbDe:btjatd7) ([raw file](https://github.com/starkware-libs/blockifier/blob/df03de702d49f9eb3ab7285170fe7a062a7790d7/crates/blockifier/src/state/cached_state.rs#L19)):*
> ```XML
> mod test;
> 
> pub type ContractClassMapping = HashMap<ClassHash, Arc<ContractClass>>;
> ```

I think this is a private type now, so we can remove the `pub`?



_Code quote:_
```XML
pub type ContractClassMapping = HashMap<ClassHash, Arc<ContractClass>>;
```
___
*[`crates/blockifier/src/state/papyrus_state_test.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/277#-NRYzAOE1_S2GTrinKmA:-NRYzAOE1_S2GTrinKmB:b35drit) ([raw file](https://github.com/starkware-libs/blockifier/blob/df03de702d49f9eb3ab7285170fe7a062a7790d7/crates/blockifier/src/state/papyrus_state_test.rs#L32)):*
> ```XML
>     let declared_classes = IndexMap::from([(
>         ClassHash(stark_felt!(TEST_CLASS_HASH)),
>         starknet_api::state::ContractClass::from(get_test_contract_class()),
> ```

Getting a bit long; consider `use starknet_api::state::ContractClass as ApiContractClass`, not sure though.



_Code quote:_
```XML
  starknet_api::state::ContractClass
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 462 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/277#-NRYyOV-4nzHbx5wXOFZ:-NRYyOV-4nzHbx5wXOF_:bxo5bkh) ([raw file](https://github.com/starkware-libs/blockifier/blob/df03de702d49f9eb3ab7285170fe7a062a7790d7/crates/blockifier/src/transaction/transactions_test.rs#L462)):*
> ```XML
>     // Verify class declaration.
>     let contract_class_from_state = state.get_contract_class(&class_hash).unwrap();
>     assert_eq!(contract_class_from_state, Arc::from(contract_class.clone()));
> ```

Is the clone here because `invalid_declare_tx` also wants to own it?



_Code quote:_
```XML
contract_class.clone()
```

**Review by elintul — COMMENTED** [review]
Not to copy the class?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/277#-:-NRb9e2U1trIMHdgNU3d:bprr40e)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 117 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/277#-NRYx0V8CjuCIU5iRfi1:-NRb9hg46KipLKPho1KV:b-w19qpc) ([raw file](https://github.com/starkware-libs/blockifier/blob/df03de702d49f9eb3ab7285170fe7a062a7790d7/crates/blockifier/src/test_utils.rs#L117)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do you prefer `Arc::from` over `Arc::new`? (they [are equivalent](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.from-10))
</blockquote></details>

Perhaps `new` is better, since it's the first time it's created.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/277)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 462 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/277#-NRYyOV-4nzHbx5wXOFZ:-NRb9oZQ6MKQnqHtjf4I:bwqt9q6) ([raw file](https://github.com/starkware-libs/blockifier/blob/df03de702d49f9eb3ab7285170fe7a062a7790d7/crates/blockifier/src/transaction/transactions_test.rs#L462)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is the clone here because `invalid_declare_tx` also wants to own it?
</blockquote></details>

Yeah... :(
Wanted to ask you for a better suggestion.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/277)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/277#-NRYu7iD5l5u88BZKbDd:-NRb_eU61vmmWfrFGJz4:b-fvh0wu) ([raw file](https://github.com/starkware-libs/blockifier/blob/df03de702d49f9eb3ab7285170fe7a062a7790d7/crates/blockifier/src/state/cached_state.rs#L19)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think this is a private type now, so we can remove the `pub`?
</blockquote></details>

Didn't know the test can use non-`pub`lic variables.



_Code quote:_
```XML
ContractClassMapping
```
___
*[`crates/blockifier/src/state/papyrus_state_test.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/277#-NRYzAOE1_S2GTrinKmA:-NRb_nkr-XLJC02GEyc7:b-d508pn) ([raw file](https://github.com/starkware-libs/blockifier/blob/df03de702d49f9eb3ab7285170fe7a062a7790d7/crates/blockifier/src/state/papyrus_state_test.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Getting a bit long; consider `use starknet_api::state::ContractClass as ApiContractClass`, not sure though.
</blockquote></details>

I think it's okay, on the verge of too long.

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/277#-:-NRliGwB67m3eTHC6hHF:bnfp4nl)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 462 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/277#-NRYyOV-4nzHbx5wXOFZ:-NRlhoV4Eql7AhOzBOEW:b6onq7q) ([raw file](https://github.com/starkware-libs/blockifier/blob/df03de702d49f9eb3ab7285170fe7a062a7790d7/crates/blockifier/src/transaction/transactions_test.rs#L462)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yeah... :(
Wanted to ask you for a better suggestion.
</blockquote></details>

Not really... meh, it's a test :shrug:

**Review by giladchase — APPROVED** [review]
> Reviewed 3 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
