### PR TITLE
Fix master.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/248)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/248#-:-NN0ZkaM-y7qparsTMeL:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/248#-:-NN0adPr-4QgukmyEmRT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/248#-:-NN0cr_Y1S-yDuwVXn1G:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
