### PR TITLE
Return executed compiled class sizes to Python.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/542)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/542)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/errors.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/542#-NWgnwroA4sHOCW6tKT1:-NWgnwroA4sHOCW6tKT2:b8jj3tr) ([raw file](https://github.com/starkware-libs/blockifier/blob/47d4114eb7698872b7bdb3d06afca8e1fb892827/crates/native_blockifier/src/errors.rs#L65)):*
> ```XML
>     (SerdeError, serde_json::Error, PySerdeError),
>     (StarknetApiError, StarknetApiError, PyStarknetApiError),
>     (StateError, StateError, PyStateError),
> ```

Reminder: once this is merge the Python repo must make changes in 2 places in order to accommodate this change.



_Code quote:_
```XML
    (StateError, StateError, PyStateError),
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 477 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/542#-NWgpcnbC1KIA6Tuy05F:-NWgpcnbC1KIA6Tuy05G:bmqus6x) ([raw file](https://github.com/starkware-libs/blockifier/blob/47d4114eb7698872b7bdb3d06afca8e1fb892827/crates/native_blockifier/src/py_transaction.rs#L477)):*
> ```XML
>             }
>             Err(error) => return Err(error.into()),
>         };
> ```

Since `?` implicitly does "`unwrap` or return return `Err(error.into())`" we can replace the match with `?`



_Suggestion:_
```XML
        let class = state.get_compiled_contract_class(&class_hash)?;
        let sizes = match class {
            ContractClass::V0(class) => PyContractClassSizes {
                bytecode_length: class.program.data.len(),
                n_builtins: Some(class.program.builtins.len()),
            },
            ContractClass::V1(class) => {
                PyContractClassSizes { bytecode_length: class.program.data.len(), n_builtins: None }
            }
        };
```

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/542#-:-NWgqdcz-7Pl7iGnqnnc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/542)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 477 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/542#-NWgpcnbC1KIA6Tuy05F:-NWltIMBD7xhjUJwaO4C:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/47d4114eb7698872b7bdb3d06afca8e1fb892827/crates/native_blockifier/src/py_transaction.rs#L477)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Since `?` implicitly does "`unwrap` or return return `Err(error.into())`" we can replace the match with `?`
</blockquote></details>

Done.

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/542)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/542)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
