### PR TITLE
Add max_steps to ExecutionContext

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/544)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/544)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/544#-NWgUZ5uEHVyrpz9Hk7M:-NWgUZ5vBQxYTEpAG2S_:b-xki82t) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb0b09e5abfcfdfafd65cf1a1645f22249dd3f1a/crates/blockifier/src/execution/entry_point.rs#L85)):*
> ```XML
>                 .expect(format!("{} must be in vm_resource_fee_cost.", N_STEPS_RESOURCE).as_str());
>             let max_gas = account_tx_context.max_fee.0 / block_context.gas_price;
>             let max_steps = (max_gas as f64 / gas_per_step).floor();
> ```

this conversion seems unsafe; but from [this](https://doc.rust-lang.org/reference/expressions/operator-expr.html#numeric-cast) it looks like it is safe.
I'll ask in rust practices...



_Code quote:_
```XML
max_gas as f64
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/544)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 347 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/544#-NWgpMH6CmngkUmAmhnD:-NWguMv6-3TBUHcLWpG4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f53f7ed099524b021cdc8f70bb7b48e043144cfc/crates/blockifier/src/test_utils.rs#L347)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why do you need to add it separately? Does it make sense to add it in a "non-account" test?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/544#-NWgYx26AHL3JReduZfb:-NWguNhjCnvufO0IZClW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f53f7ed099524b021cdc8f70bb7b48e043144cfc/crates/blockifier/src/execution/entry_point.rs#L79)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why `usize`?
Maybe define it as a constant?
</blockquote></details>

Done.

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/544)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/544#-NWrHckxCxmPGeM_7BPS:-NWrHckxCxmPGeM_7BPT:b5yz5xh) ([raw file](https://github.com/starkware-libs/blockifier/blob/3932dd5ad2651a3dc227e1acb64ee3aa98864fbe/crates/blockifier/src/execution/entry_point.rs#L96)):*
> ```XML
> }
> 
> impl ExecutionContext {
> ```

Combine with the above?



_Code quote:_
```XML
impl ExecutionContext {
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/544)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/544#-NWrHckxCxmPGeM_7BPS:-NX5APv8AO8WMVSNg3Dj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3932dd5ad2651a3dc227e1acb64ee3aa98864fbe/crates/blockifier/src/execution/entry_point.rs#L96)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Combine with the above?
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/544#-:-NX5Qw-Y9648iv6fPEC5:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/544)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
