### PR TITLE
Limit validate steps + test

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-NhWD4fI68E7kTz-qa93:-NhWD4fI68E7kTz-qa94:bgklrw0) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2d9340b3c7ea94759ed4d1975e552f274e93581/crates/blockifier/src/execution/entry_point.rs#L209)):*
> ```XML
>     ) -> usize {
>         let configured_max = min(
>             constants::MAX_STEPS_PER_TX,
> ```

this value (4 million) should be the same for validate and execute phases?
@Yoni-Starkware 



_Code quote:_
```XML
constants::MAX_STEPS_PER_TX,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-NhWzEPn-z-vr-sMGu8U:-NhWzEPn-z-vr-sMGu8V:bjijx) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/32297)

___

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-Nhe6xfKC9fLgwSxZgs-:-Nhe6xfKC9fLgwSxZgs0:b8u65wr) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2d9340b3c7ea94759ed4d1975e552f274e93581/crates/blockifier/src/execution/entry_point.rs#L212)):*
> ```XML
>             match mode {
>                 ExecutionMode::Validate => block_context.validate_max_n_steps as usize,
>                 ExecutionMode::Execute => block_context.invoke_tx_max_n_steps as usize,
> ```

Do you know why these are not usize to begin with? also why u32 and not higher :thinking: 



_Code quote:_
```XML
                ExecutionMode::Validate => block_context.validate_max_n_steps as usize,
                ExecutionMode::Execute => block_context.invoke_tx_max_n_steps as usize,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 396 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-Nhe7ZbsD8X2vaPCx8Ro:-Nhe7ZbsD8X2vaPCx8Rp:bism3fz) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2d9340b3c7ea94759ed4d1975e552f274e93581/crates/blockifier/src/transaction/account_transactions_test.rs#L396)):*
> ```XML
>     .unwrap_err();
> 
>     assert!(matches!(error, TransactionExecutionError::MaxFeeTooLow { max_fee: Fee(10), .. }));
> ```

For better debug info



_Suggestion:_
```XML
assert_matches!   
```

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-Nhe6xfKC9fLgwSxZgs-:-Nhe8L75DIQthVT8fjd4:blj68vm) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2d9340b3c7ea94759ed4d1975e552f274e93581/crates/blockifier/src/execution/entry_point.rs#L212)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do you know why these are not usize to begin with? also why u32 and not higher :thinking:
</blockquote></details>

Also, just out of curiousity, is there some expected ratio between these two values?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-Nhe6xfKC9fLgwSxZgs-:-Nhemhzk8RGJ049T5ts_:b-q7k253) ([raw file](https://github.com/starkware-libs/blockifier/blob/d2d9340b3c7ea94759ed4d1975e552f274e93581/crates/blockifier/src/execution/entry_point.rs#L212)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Also, just out of curiousity, is there some expected ratio between these two values?
</blockquote></details>

Don't know why they are u32; as for expected ratio, no, but we should have global maximum values.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @giladchase, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 192 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-NhfHDBi0lHZAB8j94mR:-NhfVSKE64dFVs0Oxpu-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3b434609fac9216b5636864592a352d1b569722b/crates/blockifier/src/execution/entry_point.rs#L192)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

If this is the only use, please merge these two functions and name it `new`
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @zuphitf)

___
*[`crates/blockifier/src/test_utils.rs` line 417 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-Nhf_kG4869wmOAr6nGy:-Nhf_kG4869wmOAr6nGz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ff161d7a794c431e78668619774f250f6e8abcd/crates/blockifier/src/test_utils.rs#L417)):*
> ```XML
>                 strk_l1_gas_price: DEFAULT_STRK_L1_GAS_PRICE,
>             },
>             invoke_tx_max_n_steps: MAX_VALIDATE_STEPS_PER_TX,
> ```





_Suggestion:_
```XML
MAX_STEPS_
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 206 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-NhfaSUx7aqG9x_gZXi2:-NhfaSUx7aqG9x_gZXi3:bohudh) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ff161d7a794c431e78668619774f250f6e8abcd/crates/blockifier/src/execution/entry_point.rs#L206)):*
> ```XML
>             ),
>             ExecutionMode::Execute => {
>                 min(block_context.invoke_tx_max_n_steps as usize, constants::MAX_STEPS_PER_TX)
> ```

Why the constants don't have the same type?



_Code quote:_
```XML
                constants::MAX_VALIDATE_STEPS_PER_TX as usize,
            ),
            ExecutionMode::Execute => {
                min(block_context.invoke_tx_max_n_steps as usize, constants::MAX_STEPS_PER_TX)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @giladchase, @Yoni-Starkware, and @zuphitf)

___
*[`crates/blockifier/src/test_utils.rs` line 417 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-Nhf_kG4869wmOAr6nGy:-NhfbX7y3yart9XtDFdm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ff161d7a794c431e78668619774f250f6e8abcd/crates/blockifier/src/test_utils.rs#L417)):*
> ```XML
>                 strk_l1_gas_price: DEFAULT_STRK_L1_GAS_PRICE,
>             },
>             invoke_tx_max_n_steps: MAX_VALIDATE_STEPS_PER_TX,
> ```

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 206 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-NhfaSUx7aqG9x_gZXi2:-NhfbXlgBWxOz-L-mzS0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ff161d7a794c431e78668619774f250f6e8abcd/crates/blockifier/src/execution/entry_point.rs#L206)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why the constants don't have the same type?
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026#-:-NhgJHiP17jmX_M5-EBj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1026)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Pull request merged**
