### PR TITLE
Get `OsResources` as an external arg

### PR DESCRIPTION
**Pull request by giladchase**
- Don't maintain os_resources inside the blockifier, it is passed from
outside.
- This will be tested in a subsequent commit.

---

**Stack**:
- #1181
- #1180 ⬅
- #1179
- #1178
- #1177
- #1176
- #1175

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1180)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1180)* status: 3 of 16 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 281 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-NjwZgTFBo-5ANs1-2Vz:-NjwZgTFBo-5ANs1-2W-:bfi0j61) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/execution/entry_point.rs#L281)):*
> ```XML
>         validate_call_info: &Option<CallInfo>,
>         tx_type: &TransactionType,
>         os_resources: &OsResources,
> ```

Why? It's on `self.block_context`, no?



_Code quote:_
```XML
os_resources: &OsResources,
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-NjwZnmCBzXMYRROzXHk:-NjwZnmD2siy4Vh5osub:b-k2pczf) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/fee/actual_cost.rs#L55)):*
> ```XML
>     l1_payload_size: Option<usize>,
>     n_reverted_steps: usize,
>     os_resources: Arc<OsResources>,
> ```

Here too.



_Code quote:_
```XML
os_resources: Arc<OsResources>,
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 11 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1180)* status: 14 of 16 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njw_cUmCf9K4dZJXNF4:-Njw_cUmCf9K4dZJXNF5:b-tqu9ia) (no related file):*
Can you please separate this PR into `blockifier` and `native_blockifier` changes?

___
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njw_jhR3-Qwg1bSQeQB:-Njw_jhR3-Qwg1bSQeQC:b-t9o2pe) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L36)):*
> ```XML
> pub type DeprecatedSyscallResult<T> = Result<T, DeprecatedSyscallExecutionError>;
> pub type WriteResponseResult = DeprecatedSyscallResult<()>;
> ```

Can you explain this change, please?
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njw_9bn-oB3jaW9Y1Kd:-Njw_9bn-oB3jaW9Y1Ke:ba26pz) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/transaction/transaction_utils.rs#L43)):*
> ```XML
>     l1_gas_usage: usize,
>     tx_type: TransactionType,
>     os_resources: &OsResources,
> ```

Move under `execution_resources`, they are of the same theme.



_Code quote:_
```XML
os_resources: &OsResources,
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njw_KQqEUErfpxwZyfz:-Njw_KQqEUErfpxwZyg-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/native_blockifier/src/py_block_executor.rs#L45)):*
> ```XML
>         max_recursion_depth: usize,
>         target_storage_config: StorageConfig,
>         os_resources: String,
> ```





_Suggestion:_
```XML
        general_config: PyGeneralConfig,
        target_storage_config: StorageConfig,
        max_recursion_depth: usize,
        os_resources: String,
```

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1180)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njw_tM66CZw05iLVpl4:-Njw_tM66CZw05iLVpl5:bdrcm6w) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/fee/os_usage.rs#L57)):*
> ```XML
>             .unwrap_or_else(|| panic!("should contain transaction type '{tx_type:?}'."))
>     }
> ```

Consider early `return`s, so that the errors code is less indented.
___
*[`crates/blockifier/src/fee/os_usage.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njwa1dEBYlCW140YBsW:-Njwa1dEBYlCW140YBsX:b-d73xsb) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/fee/os_usage.rs#L139)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum OsResourcesError {
> ```

Move up? What's the convention?



_Code quote:_
```XML
pub enum OsResourcesError
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1180)* status: all files reviewed, 21 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njw_JFM2cYNUmNB9Q8h:-Njw_JFM2cYNUmNB9Q8i:b-qze42k) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/fee/actual_cost.rs#L36)):*
> ```XML
>             tx_context,
>             TransactionType::L1Handler,
>             block_context.os_resources.clone(),
> ```

is this necessary? I think cloning this can be painful, no?
or is cloning an `Arc` cheap?



_Code quote:_
```XML
.clone()
```
___
*[`crates/blockifier/src/fee/os_resources.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njw_aiP-Etbci-k5Wlt:-Njw_aiP-Etbci-k5Wlu:b6ujrhm) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/fee/os_resources.rs#L13)):*
> ```XML
> // TODO(Arni, 14/6/2023): Update `GetBlockHash` values.
> pub fn os_resources() -> serde_json::Value {
>     json!({
> ```

this really should be (a) stored in a json *file* and (b) lazy-loaded once... but, out of scope



_Code quote:_
```XML
json!
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njw_phm0cDVeSY8V_3R:-Njw_phm0cDVeSY8V_3S:b-q60y6c) ([raw file](https://github.com/starkware-libs/blockifier/blob/df7ff210892cccaa57834055a6ea79ec7db62fb7/crates/blockifier/src/fee/os_usage.rs#L14)):*
> ```XML
> #[cfg(test)]
> #[path = "os_usage_test.rs"]
> pub mod test;
> ```

where did this go...?



_Code quote:_
```XML
#[cfg(test)]
#[path = "os_usage_test.rs"]
pub mod test;
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njwa04CE5DbZ12k1YzX:-Njwa04D7372ZGcLCPOc:b-rmejd1) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/fee/os_usage.rs#L37)):*
> ```XML
> 
> impl OsResources {
>     pub fn new(os_resources: String) -> Result<Self, OsResourcesError> {
> ```

confusing



_Suggestion:_
```XML
os_resources_json_str
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-NjwaRKnA88IsMZkUxYT:-NjwaRKnA88IsMZkUxYU:b9gomhe) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/fee/os_usage.rs#L37)):*
> ```XML
> 
> impl OsResources {
>     pub fn new(os_resources: String) -> Result<Self, OsResourcesError> {
> ```

this is called only once per block, right? looks like a lot is being verified each time...
wouldn't it be better to just write a test that performs all these validations (calls `new` and then all three verifications), and never verify on `new`?
The source JSON is hard-coded in the repo, if it changes the test will catch errors, no?



_Code quote:_
```XML
new
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njwat_S7uqbGx7UZA0U:-Njwat_S7uqbGx7UZA0V:bvnndtc) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/fee/os_usage.rs#L126)):*
> ```XML
>             .execute_syscalls
>             .get(syscall_selector)
>             .unwrap_or_else(|| panic!("Should contain syscall selector '{syscall_selector:?}'."));
> ```

want to add a similar method?
(also prefer `Err`/`Ok` to `panic!` but may be out of scope)



_Suggestion:_
```XML
        let syscall_resources = os_resources.resources_for_syscall(syscall_selector);
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-NjwbBZ74VnHai6UPzZo:-NjwbBZ74VnHai6UPzZp:b-bcntnn) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/blockifier/src/test_utils/struct_impls.rs#L107)):*
> ```XML
>             validate_max_n_steps: MAX_VALIDATE_STEPS_PER_TX as u32,
>             os_resources: serde_json::from_value(os_resources::os_resources())
>                 .expect("os_resources json does not exist or cannot be deserialized."),
> ```

I think the serde logic should go into the os_resources module, including the `expect`



_Suggestion:_
```XML
            os_resources: os_resources::load_os_resources(),
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-NjwbVFj5EgmwypAf6eF:-NjwbVFj5EgmwypAf6eG:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/native_blockifier/src/py_block_executor.rs#L40)):*
> ```XML
> impl PyBlockExecutor {
>     #[new]
>     #[pyo3(signature = (general_config, max_recursion_depth, target_storage_config,os_resources))]
> ```





_Suggestion:_
```XML
os_resources_json_str
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-NjwbdcO1YKUY6UuVpID:-NjwbdcO1YKUY6UuVpIE:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/native_blockifier/src/py_block_executor.rs#L219)):*
> ```XML
>             tx_executor: None,
>             global_contract_cache: GlobalContractCache::default(),
>             //  REMOVE ME! get this as a param.
> ```





_Suggestion:_
```XML
// TODO(Gilad, 1/12/2023): REMOVE ME!
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njwbj8H3H0fXfAs3nAj:-Njwbj8H3H0fXfAs3nAk:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/native_blockifier/src/py_block_executor.rs#L221)):*
> ```XML
>             //  REMOVE ME! get this as a param.
>             os_resources: serde_json::from_value(os_resources::os_resources())
>                 .expect("os_resources json does not exist or cannot be deserialized."),
> ```





_Suggestion:_
```XML
            os_resources: os_resources::load_os_resources(),
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-Njwbo6PC_z-N1m1fUWm:-Njwbo6PC_z-N1m1fUWn:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/native_blockifier/src/py_block_executor.rs#L246)):*
> ```XML
>             global_contract_cache: GlobalContractCache::default(),
>             os_resources: serde_json::from_value(os_resources::os_resources())
>                 .expect("os_resources json does not exist or cannot be deserialized."),
> ```





_Suggestion:_
```XML
            os_resources: os_resources::load_os_resources(),
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-NjwbrbE4gzr20YePFQw:-NjwbrbE4gzr20YePFQx:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/native_blockifier/src/py_validator.rs#L41)):*
> ```XML
> impl PyValidator {
>     #[new]
>     #[pyo3(signature = (general_config, max_recursion_depth, max_nonce_for_validation_skip, os_resources))]
> ```





_Suggestion:_
```XML
os_resources_json_str
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-NjwbukZ1wlbB3bjcZ9e:-NjwbukZ1wlbB3bjcZ9f:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0634147cb93bf2565bf4bcd6a0a068144eb65e7d/crates/native_blockifier/src/py_validator.rs#L182)):*
> ```XML
>             global_contract_cache: GlobalContractCache::default(),
>             os_resources: serde_json::from_value(os_resources::os_resources())
>                 .expect("os_resources json does not exist or cannot be deserialized."),
> ```





_Suggestion:_
```XML
            os_resources: os_resources::load_os_resources(),
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1180)* status: 13 of 16 files reviewed, 22 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1180#-NkFXplq9DRda2pjaZcn:-NkFXplq9DRda2pjaZco:b-ajb6ll) (no related file):*
Closing.
Spec has changed, we'll do the opposite direction, keep the os resources only in Rust and have Python require it via native_blockifier.

___

**Comment by giladchase** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
