### PR TITLE
test: append block with large declared contract

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2054)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2054)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 373 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2054#-O1He9fmCkET5dNBy_lD:-O1He9fnEMkKarK2sqyr:bad60e9) ([raw file](https://github.com/starkware-libs/blockifier/blob/e09c00e35a525db1e84affa4a62cb0083f8c093c/crates/native_blockifier/src/py_block_executor.rs#L373)):*
> ```XML
>     /// Wrapper with pub(crate) visibility for internal (in crate) testing.
>     #[cfg(test)]
>     #[pyo3(signature = (concurrency_config, general_config, path, max_state_diff_size))]
> ```

Is this necessary?



_Code quote:_
```XML
#[pyo3(signature = (concurrency_config, general_config, path, max_state_diff_size))]
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 374 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2054#-O1HeE_NCuQoxNW_Kcyc:-O1HeE_NCuQoxNW_Kcyd:bdvqq2l) ([raw file](https://github.com/starkware-libs/blockifier/blob/e09c00e35a525db1e84affa4a62cb0083f8c093c/crates/native_blockifier/src/py_block_executor.rs#L374)):*
> ```XML
>     #[cfg(test)]
>     #[pyo3(signature = (concurrency_config, general_config, path, max_state_diff_size))]
>     #[staticmethod]
> ```

Same. What does it mean?



_Code quote:_
```XML
#[staticmethod]
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2054)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 373 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2054#-O1He9fmCkET5dNBy_lD:-O1HkmuaDGunBKgkMzhq:b-e6b5qz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e09c00e35a525db1e84affa4a62cb0083f8c093c/crates/native_blockifier/src/py_block_executor.rs#L373)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

nope, fixed
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 374 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2054#-O1HeE_NCuQoxNW_Kcyc:-O1HknP6AdMbqcqYG5I3:bx65v6s) ([raw file](https://github.com/starkware-libs/blockifier/blob/e09c00e35a525db1e84affa4a62cb0083f8c093c/crates/native_blockifier/src/py_block_executor.rs#L374)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Same. What does it mean?
</blockquote></details>

yup (pyo3 expects the first arg to be of some wrapper type to `Self` without this)
```
error[E0277]: the trait bound `PyConcurrencyConfig: TryFrom<&PyCell<PyBlockExecutor>>` is not satisfied
   --> crates/native_blockifier/src/py_block_executor.rs:375:29
    |
375 |         concurrency_config: PyConcurrencyConfig,
    |                             ^^^^^^^^^^^^^^^^^^^ the trait `From<&PyCell<PyBlockExecutor>>` is not implemented for `PyConcurrencyConfig`, which is required by `PyConcurrencyConfig: TryFrom<&PyCell<PyBlockExecutor>>`
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2054)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 374 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2054#-O1HeE_NCuQoxNW_Kcyc:-O1HpIr_3stC9-tWtwpq:b-sehk2i) ([raw file](https://github.com/starkware-libs/blockifier/blob/e09c00e35a525db1e84affa4a62cb0083f8c093c/crates/native_blockifier/src/py_block_executor.rs#L374)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yup (pyo3 expects the first arg to be of some wrapper type to `Self` without this)
```
error[E0277]: the trait bound `PyConcurrencyConfig: TryFrom<&PyCell<PyBlockExecutor>>` is not satisfied
   --> crates/native_blockifier/src/py_block_executor.rs:375:29
    |
375 |         concurrency_config: PyConcurrencyConfig,
    |                             ^^^^^^^^^^^^^^^^^^^ the trait `From<&PyCell<PyBlockExecutor>>` is not implemented for `PyConcurrencyConfig`, which is required by `PyConcurrencyConfig: TryFrom<&PyCell<PyBlockExecutor>>`
```
</blockquote></details>

Move this to the second `impl PyBlockExecutor` block

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2054)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/state_readers/papyrus_state_test.rs` line 126 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2054#-O1HqtyjBjJm5UZb2ach:-O1HqtyjBjJm5UZb2aci:b-lqk406) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3cf78b8c08e396dd0fb6ad9401fb0bee994398f/crates/native_blockifier/src/state_readers/papyrus_state_test.rs#L126)):*
> ```XML
>             HashMap::from([(PyFelt::from(1_u8), serde_json::to_string(&dep_casm).unwrap())]),
>         )
>         .unwrap();
> ```

why is this done twice? @Yoni-Starkware 



_Code quote:_
```XML
    block_executor
        .append_block(
            0,
            None,
            Default::default(),
            Default::default(),
            Default::default(),
            HashMap::from([(PyFelt::from(1_u8), serde_json::to_string(&dep_casm).unwrap())]),
        )
        .unwrap();

    block_executor
        .append_block(
            1,
            Some(PyFelt(Felt::ZERO)),
            PyBlockInfo { block_number: 1, ..PyBlockInfo::default() },
            Default::default(),
            Default::default(),
            HashMap::from([(PyFelt::from(1_u8), serde_json::to_string(&dep_casm).unwrap())]),
        )
        .unwrap();
```

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2054)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/state_readers/papyrus_state_test.rs` line 126 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2054#-O1HqtyjBjJm5UZb2ach:-O1IBVCgBsofha0oq6zm:bilpfy) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3cf78b8c08e396dd0fb6ad9401fb0bee994398f/crates/native_blockifier/src/state_readers/papyrus_state_test.rs#L126)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this done twice? @Yoni-Starkware
</blockquote></details>

We read the class in the second append. 
The bug was in that read

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2054#-:-O1IBmaW12VPOj5UGY_Z:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Pull request merged**
