### PR TITLE
Refactor Recursion Depth Management with `Guard` Pattern

### PR DESCRIPTION
**Pull request by giladchase**
- Introduced `RecursionDepthGuard` to manage `current_recursion_depth` in `EntryPointExecutionContext`.
- Eliminates potential bugs arising from early exit (`?`) by ensuring each increment has a matching decrement via `Drop` impl.
- Simplifies error-prone manual increment/decrement.
- Large change around let `result =` due to obviating the need for result variable; logic remains unchanged.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1012)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1012)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1012#-NhMimr66dndFqD5W9Is:-NhMimr66dndFqD5W9It:bq9r3p) (no related file):*
We currently have no unit test that matches against `RecursionDepthExceeded`; please add one with positive + negative flows

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1012)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1012#-NhMimr66dndFqD5W9Is:-NhQvoO8-myeiTkm0xyO:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

We currently have no unit test that matches against `RecursionDepthExceeded`; please add one with positive + negative flows
</blockquote></details>

Done.

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1012)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1012#-NhQy4Om33zLgdQgdYdT:-NhQy4Om33zLgdQgdYdU:b-49cjnu) ([raw file](https://github.com/starkware-libs/blockifier/blob/5551cb0472c0275d30cf930a09b3c70b71d36cc8/crates/blockifier/src/transaction/account_transactions_test.rs#L361)):*
> ```XML
> }
> 
> #[rstest]
> ```

please parametrize (missing positive case - recursing exactly to the max)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1012#-NhQyGya52byC-LnPHU1:-NhQyGya52byC-LnPHU2:b-kavrbo) ([raw file](https://github.com/starkware-libs/blockifier/blob/5551cb0472c0275d30cf930a09b3c70b71d36cc8/crates/blockifier/src/transaction/account_transactions_test.rs#L395)):*
> ```XML
>             sender_address: account_address,
>             calldata,
>             version: TransactionVersion::ONE,
> ```

while you're at it... why not parametrize the tx version as well? to also test this for v3 txs?



_Code quote:_
```XML
version: TransactionVersion::ONE,
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1012)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1012#-NhQy4Om33zLgdQgdYdT:-NhRZCYb37BeKT0I8BbM:b-ye5r23) ([raw file](https://github.com/starkware-libs/blockifier/blob/5551cb0472c0275d30cf930a09b3c70b71d36cc8/crates/blockifier/src/transaction/account_transactions_test.rs#L361)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please parametrize (missing positive case - recursing exactly to the max)
</blockquote></details>

Done, i ended up adding it inline since the -2 depth param required some explaining, and _i think_ inlining the explanation makes it a bit more readable (at the cost of a little duplication).
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1012#-NhQyGya52byC-LnPHU1:-NhRZZhV7FMkZvcLCg_3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5551cb0472c0275d30cf930a09b3c70b71d36cc8/crates/blockifier/src/transaction/account_transactions_test.rs#L395)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

while you're at it... why not parametrize the tx version as well? to also test this for v3 txs?
</blockquote></details>

Done.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1012)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1012#-NhQy4Om33zLgdQgdYdT:-NhRZejH85zyiAhHgj5b:b-upngg6) ([raw file](https://github.com/starkware-libs/blockifier/blob/5551cb0472c0275d30cf930a09b3c70b71d36cc8/crates/blockifier/src/transaction/account_transactions_test.rs#L361)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done, i ended up adding it inline since the -2 depth param required some explaining, and _i think_ inlining the explanation makes it a bit more readable (at the cost of a little duplication).
</blockquote></details>

I forgot to mention, i found out about the -2 only now yes? previously it equaled block_context's max depth + 1, but evidently that was tight for the max depth of _inner_ calls

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1012#-:-NhRcCcZ2E-UJdgmIy9Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1012)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
