### PR TITLE
Check for sufficient L1 fee paid for L1HandlerTransaction.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/480)

### CODE REVIEW

**Review by alonh5 — COMMENTED** [review]
Need to update SN API revision for this to pass.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/480#-:-NVdUOJD8ygrdQofI8Do:bl421n6)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @elintul, @giladchase, and @noaov1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/480)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/480#-NVdpIdlDEedQSQ_OUyK:-NVdpIdmDT40msdn0sl6:bturn3l) ([raw file](https://github.com/starkware-libs/blockifier/blob/484c06fae72f323385d464613a5ce7cd5a8919a2/crates/blockifier/src/transaction/transaction_execution.rs#L75)):*
> ```XML
>             state,
>             l1_handler_payload_size,
>         )?;
> ```

Why do we need the `paid_fee` variable?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/480)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/480#-NVdpIdlDEedQSQ_OUyK:-NVdrpyOCQzWneQEmkm5:bcwym5f) ([raw file](https://github.com/starkware-libs/blockifier/blob/484c06fae72f323385d464613a5ce7cd5a8919a2/crates/blockifier/src/transaction/transaction_execution.rs#L75)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why do we need the `paid_fee` variable? 
</blockquote></details>

It isn't necessary. I just think it's nicer because we're using it twice and it allows to use the name in the error struct instead of
 `TransactionExecutionError::InsufficientL1Fee { paid_fee: self.paid_fee_on_l1, actual_fee }`.

**Review by elintul — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/480#-:-NVeAZSW8INDHcxwDcCd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/480#-NVdpIdlDEedQSQ_OUyK:-NVeARjaAEzajZypzQer:b-wuvuws) ([raw file](https://github.com/starkware-libs/blockifier/blob/484c06fae72f323385d464613a5ce7cd5a8919a2/crates/blockifier/src/transaction/transaction_execution.rs#L75)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It isn't necessary. I just think it's nicer because we're using it twice and it allows to use the name in the error struct instead of
 `TransactionExecutionError::InsufficientL1Fee { paid_fee: self.paid_fee_on_l1, actual_fee }`.
</blockquote></details>

Oh, right.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/480#-:-NVitLr5C3duqGWbtoAr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Pull request merged**
