### PR TITLE
Update SN API and Papyrus storage dependencies.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)

### CODE REVIEW

**Review by alonh5 — COMMENTED** [review]
Python [PR](https://reviewable.io/reviews/starkware-industries/starkware/30792)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763#-:-N_nayYw8CZHu409W6vl:b9yhktu)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 483 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_nb-eq0z0gSB1A2jeA:-N_nb-eq0z0gSB1A2jeB:b-4q3crm) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transactions_test.rs#L483)):*
> ```XML
>         None,
>         &mut NonceManager::default(),
>     ));
> ```

is this a rebase diff...? where is the usage of `invalid_max_fee`?



_Code quote:_
```XML
    let invalid_tx = AccountTransaction::DeployAccount(deploy_account_tx(
        TEST_ACCOUNT_CONTRACT_CLASS_HASH,
        None,
        None,
        &mut NonceManager::default(),
    ));
```
___
*[`crates/native_blockifier/src/storage.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_nbZ5o4tkLOZqPbmom:-N_nbZ5o4tkLOZqPbmon:b-fkrpkk) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/native_blockifier/src/storage.rs#L40)):*
> ```XML
>         path_prefix: PathBuf,
>         #[pyo3(from_py_with = "int_to_chain_id")] chain_id: ChainId,
>         max_size: usize,
> ```

I failed to update the python side with this diff, is the python version bump PR open?



_Code quote:_
```XML
        path_prefix: PathBuf,
        #[pyo3(from_py_with = "int_to_chain_id")] chain_id: ChainId,
        max_size: usize,
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_n_XkN-KS15sfNonhm:-N_nb3xI4LM5rE5AQ-PF:bd23uo0) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/test_utils.rs#L405)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Any idea why was change done? In the deploy account struct. 
</blockquote></details>

I think they matched the specs, where the deploy account tx doesn't have a contract address field.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_na7otBbV1RhqqkSFS:-N_nbFPFC1H7a8AZ72qI:bj4p0xi) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I don't want us to calc. the address again if not needed. 
</blockquote></details>

It can be passed as an optional arg as well and have users calculate it. We have all that's required to calculate ourselves so I thought it best to do that.
___
*[`crates/native_blockifier/src/storage.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_nbZ5o4tkLOZqPbmom:-N_nbidy68c9yytkV48b:bmdxgn7) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/native_blockifier/src/storage.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I failed to update the python side with this diff, is the python version bump PR open?
</blockquote></details>

Yes [here](https://reviewable.io/reviews/starkware-industries/starkware/30792)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 483 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_nb-eq0z0gSB1A2jeA:-N_nbzFt4LKr4snXwuQu:b-c6l21q) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transactions_test.rs#L483)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this a rebase diff...? where is the usage of `invalid_max_fee`?
</blockquote></details>

It's used in other txs in this test, but there's no balance passed to the address computed in the deploy account tx so no need to modify the max fee.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @elintul)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_n_elMDeW5tcsUEccF:-N_ncg3h4FVpXYW1fzRj:b-lq1cab) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d525066f01ee462910f57c35f613a404a375d32/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Looks bad... please consider adding getters for these. 
</blockquote></details>

These structs are from sn api so I can't implement getters for them (unless I add it as a trait impl).
We decided not to implement getters for them in sn api because v0 isn't actually an account tx and doesn't have a nonce and sender address.

BTW you already reviewed this and it was already in main but it was reverted in the merge, I just copied it back. (I didn't revert it in the merge, it was reverted the commit was reverted in 0.12.1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_n_elMDeW5tcsUEccF:-N_nkIUz3c9EgsDlG1XT:b-ylzky0) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d525066f01ee462910f57c35f613a404a375d32/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

These structs are from sn api so I can't implement getters for them (unless I add it as a trait impl).
We decided not to implement getters for them in sn api because v0 isn't actually an account tx and doesn't have a nonce and sender address.

BTW you already reviewed this and it was already in main but it was reverted in the merge, I just copied it back. (I didn't revert it in the merge, it was reverted the commit was reverted in 0.12.1)
</blockquote></details>

You can implement in SN API, we did so for some transactions, right?
Don't remember reviewing the `DeployAccount` part.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_na7otBbV1RhqqkSFS:-N_nkb5_4t22LXL_8KFd:b-s7drik) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L58)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It can be passed as an optional arg as well and have users calculate it. We have all that's required to calculate ourselves so I thought it best to do that.
</blockquote></details>

It takes time, why is it better?
Anyway, I don't think this function is in use, can we delete it?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_na7otBbV1RhqqkSFS:-N_nlW6k70V2idPKWqX2:b1uptic) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It takes time, why is it better?
Anyway, I don't think this function is in use, can we delete it?
</blockquote></details>

If we can't delete - why isn't it simply the sender's address? As in `py_transaction.rs`.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_n_elMDeW5tcsUEccF:-Na0bx670YcossR4R-4k:bywljhe) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d525066f01ee462910f57c35f613a404a375d32/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You can implement in SN API, we did so for some transactions, right?
Don't remember reviewing the `DeployAccount` part.
</blockquote></details>

You're right, the `DeployAccount` is new.
I can implement getters in SN API, but that's almost like the struct having those fields. V0 shouldn't technically have a `nonce` and `sender_address` field because it isn't an account tx, we're the ones using it that way (with the account tx context), and other users of SN API might not.
If you'd like it to be in SN API anyway I'll do it no problem.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_na7otBbV1RhqqkSFS:-Na0dQMTAVr5PfvDWrBS:brbsato) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

If we can't delete - why isn't it simply the sender's address? As in `py_transaction.rs`.
</blockquote></details>

The `sender_address` field was deleted from the SN API tx; that's the reason for this change (in `py_transaction.rs` we're getting it from Python which does have that field).
Regarding deleting it, it's an API of ours and people might be using it, specifically, I think Yair is using it for tx simulation.
I thought it's better service, because we already have all the needed arguments. It does take time but it's not part of our execution, it'll either take time and effort from the user, or just time.
I can do whichever, LMK if you want me to delete the API, get it as an arg, or compute as it is now.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_n_elMDeW5tcsUEccF:-Na164uGESpn5MYd6c7t:b-ibgfbu) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d525066f01ee462910f57c35f613a404a375d32/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You're right, the `DeployAccount` is new.
I can implement getters in SN API, but that's almost like the struct having those fields. V0 shouldn't technically have a `nonce` and `sender_address` field because it isn't an account tx, we're the ones using it that way (with the account tx context), and other users of SN API might not.
If you'd like it to be in SN API anyway I'll do it no problem.

</blockquote></details>

It's not only the account-related fields, it's also deployment-related ones. Let's add getters in SN API.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_na7otBbV1RhqqkSFS:-Na16MU3-BtLVpqmp_xE:b5k68l7) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L58)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The `sender_address` field was deleted from the SN API tx; that's the reason for this change (in `py_transaction.rs` we're getting it from Python which does have that field).
Regarding deleting it, it's an API of ours and people might be using it, specifically, I think Yair is using it for tx simulation.
I thought it's better service, because we already have all the needed arguments. It does take time but it's not part of our execution, it'll either take time and effort from the user, or just time.
I can do whichever, LMK if you want me to delete the API, get it as an arg, or compute as it is now.
</blockquote></details>

Please make sure he actually uses it.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_n_elMDeW5tcsUEccF:-Na65QnI3yiGtcfEFVSc:b-4wc6mq) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d525066f01ee462910f57c35f613a404a375d32/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's not only the account-related fields, it's also deployment-related ones. Let's add getters in SN API.
</blockquote></details>

Done in this [PR](https://reviewable.io/reviews/starkware-libs/starknet-api/105). I'll change here after it's merged.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_na7otBbV1RhqqkSFS:-Na64LPD0YUCXxSU1Zc8:b-rclax2) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please make sure he actually uses it.
</blockquote></details>

He is, I asked in the channel.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_n_elMDeW5tcsUEccF:-Na6HJ7P2XgGRXenVeSR:bi475tm) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d525066f01ee462910f57c35f613a404a375d32/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done in this [PR](https://reviewable.io/reviews/starkware-libs/starknet-api/105). I'll change here after it's merged.
</blockquote></details>

What I had in mind are small getters to prevent `tx.tx.X`; as Dori did with a macro (not obligatory, but maybe we can reuse).
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_na7otBbV1RhqqkSFS:-Na6HCwq2QbvXlQa7S5B:b-3sbao0) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L58)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

He is, I asked in the channel.
</blockquote></details>

@yair-starkware, this is currently doing heavy calc. (i.e., hashes); FYI.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @yair-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_n_elMDeW5tcsUEccF:-Na6MGGAC12d1YfSZv3B:bjlbjwc) ([raw file](https://github.com/starkware-libs/blockifier/blob/7d525066f01ee462910f57c35f613a404a375d32/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What I had in mind are small getters to prevent `tx.tx.X`; as Dori did with a macro (not obligatory, but maybe we can reuse).
</blockquote></details>

Okay, I misunderstood. Done.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_na7otBbV1RhqqkSFS:-Na6MMRk379b1f4H6s7T:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@yair-starkware, this is currently doing heavy calc. (i.e., hashes); FYI.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_na7otBbV1RhqqkSFS:-Na6Q7jQ0jYf6oRB-1yo:b5mgf7h) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L58)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please make sure he's aware.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6PwSI1XspuuSyQkxF:-Na6PwSI1XspuuSyQkxG:b-bgrnsa) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9313eb14805f90ba9a5f92c2a6fed4f99ccc94/crates/blockifier/src/transaction/transactions.rs#L31)):*
> ```XML
> #[path = "transactions_test.rs"]
> mod test;
> ```

Is there an easy way to reuse this code from SN API, instead of repeating it?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6PwSI1XspuuSyQkxF:-Na6RvKA9ubEV4DiXb4A:ba0k8w5) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9313eb14805f90ba9a5f92c2a6fed4f99ccc94/crates/blockifier/src/transaction/transactions.rs#L31)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there an easy way to reuse this code from SN API, instead of repeating it?
</blockquote></details>

In SN API, the code is different, it's implementing getters for different versions of declare and invoke. Here it's just to get to the inner tx fields, so I don't think there is.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6PwSI1XspuuSyQkxF:-Na6U7Gh8CM33A-NbMOA:b-1rbmj8) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9313eb14805f90ba9a5f92c2a6fed4f99ccc94/crates/blockifier/src/transaction/transactions.rs#L31)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In SN API, the code is different, it's implementing getters for different versions of declare and invoke. Here it's just to get to the inner tx fields, so I don't think there is.
</blockquote></details>

Okay, and do we need both cloned and not? 
I see SN API only has the cloned version, which maybe also includes the copyable types?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6PwSI1XspuuSyQkxF:-Na6UZSn2trbguLushxt:bg8k3z1) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9313eb14805f90ba9a5f92c2a6fed4f99ccc94/crates/blockifier/src/transaction/transactions.rs#L31)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Okay, and do we need both cloned and not? 
I see SN API only has the cloned version, which maybe also includes the copyable types?
</blockquote></details>

I can clone them all. You're fine with that?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6PwSI1XspuuSyQkxF:-Na6UlGl5BPl13Nu0y_B:b-q2to9h) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9313eb14805f90ba9a5f92c2a6fed4f99ccc94/crates/blockifier/src/transaction/transactions.rs#L31)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I can clone them all. You're fine with that?
</blockquote></details>

That's what's done in SN API. Does it hurt performance? That is a Q for you.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6PwSI1XspuuSyQkxF:-Na6Uz9B3obdN18pKHXP:bk2t88z) ([raw file](https://github.com/starkware-libs/blockifier/blob/6e9313eb14805f90ba9a5f92c2a6fed4f99ccc94/crates/blockifier/src/transaction/transactions.rs#L31)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

That's what's done in SN API. Does it hurt performance? That is a Q for you.
</blockquote></details>

I don't think it does, they are all small, other than the signature (which could technically be any size, but is usually 2-5 felts) which is already cloned. I did that then.

**Review by elintul — DISMISSED** [review]
:lgtm:

Please merge the Python PR adjacent to this one (using the created squash commit).

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763#-:-Na6YIGW4PqmpNBqdPqS:b-z4384v)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6eY-J-uVntVWbH0hU:-Na6eY-J-uVntVWbH0hV:bynw643) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L56)):*
> ```XML
>                 )?)))
>             }
>             StarknetApiTransaction::DeployAccount(deploy_account) => {
> ```

Why option?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6eY-J-uVntVWbH0hU:-Na6e_xm5TPIYkNetwtL:bi4ugn8) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L56)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why option? 
</blockquote></details>

Please consult with Yair on the best API for their use, considering efficiency.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6eY-J-uVntVWbH0hU:-Na6iwTQ1kNPOk364BxU:bwul2hh) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L56)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please consult with Yair on the best API for their use, considering efficiency. 
</blockquote></details>

Because it's only for deploy account. Like the other optional args, which are only for one tx type (contract class for declare, paid fee on l1 for l1 handler).
Will do.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6eY-J-uVntVWbH0hU:-Na6rqGp6_yxBpkdsWr9:b-3srlwu) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L56)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

@yair-starkware PTAL here.
</blockquote></details>

Now there are 2 cases it can be None, right?
Either it is not a deploy tx, or it is and we still want the function to calculate the address.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-N_na7otBbV1RhqqkSFS:-Na6rC64CEPCHRIFtve4:b3bmm7a) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please make sure he's aware.
</blockquote></details>

Thanks, looks fine.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/763#-Na6eY-J-uVntVWbH0hU:-Na6s_hs6n-rT0LWj2tE:byr4flj) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ae4d9e47088dfce5d33f2868e4b650bc88fc6e/crates/blockifier/src/transaction/transaction_execution.rs#L56)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Now there are 2 cases it can be None, right?
Either it is not a deploy tx, or it is and we still want the function to calculate the address.
</blockquote></details>

Right.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by alonh5 — COMMENTED** [review]
> Dismissed @elintul from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/763)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
