### PR TITLE
Allow declaring a class that was already declared (for V0V1).

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/475)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/475)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/475)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/475#-NVZ142uANA2BnWGpCUx:-NVZ1Yfy-Qqcw-fcw3YU:b-xafr3c) ([raw file](https://github.com/starkware-libs/blockifier/blob/f17474c9e5d923dec9517a6efa7378bf2ce44e98/crates/native_blockifier/src/storage.rs#L126)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give this a name, please: `class_undeclared`.
</blockquote></details>

I edited this before I saw your comment. Is that also good?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/475)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/475#-NVZ142uANA2BnWGpCUx:-NVZ2i7HEXK1dX-z9fDh:b-xl05xy) ([raw file](https://github.com/starkware-libs/blockifier/blob/f17474c9e5d923dec9517a6efa7378bf2ce44e98/crates/native_blockifier/src/storage.rs#L126)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I edited this before I saw your comment. Is that also good?
</blockquote></details>

I think it's better not to keep the class itself at any moment since it's big, let's keep the boolean instead (not sure if the compiler indeed optimized better in this case).

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/475)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/475#-NVZ142uANA2BnWGpCUx:-NVZ71u98DjefBnGfr4-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f17474c9e5d923dec9517a6efa7378bf2ce44e98/crates/native_blockifier/src/storage.rs#L126)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it's better not to keep the class itself at any moment since it's big, let's keep the boolean instead (not sure if the compiler indeed optimized better in this case). 
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/475#-:-NVZ7SCW8Y_AdzG9WWUX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
