### PR TITLE
fix: state error undeclared class hash format

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
change error format to hex

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1HZY45D0Mz0Lt0_rmr:-O1HZY45D0Mz0Lt0_rms:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/259a8aa8086911412050b0d3b9957fb6ad61776a/crates/blockifier/src/state.rs#L6)):*
> ```XML
> pub mod state_api;
> #[cfg(test)]
> pub mod errors_test;
> ```





_Suggestion:_
```XML
error_format_test
```
___
*[`crates/blockifier/src/state/errors_test.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1HZTxj-XKFKGj-D_zJ:-O1HZTxj-XKFKGj-D_zK:b1sp3ii) ([raw file](https://github.com/starkware-libs/blockifier/blob/259a8aa8086911412050b0d3b9957fb6ad61776a/crates/blockifier/src/state/errors_test.rs#L8)):*
> ```XML
> #[rstest]
> 
> fn test_error_forrmat() {
> ```

weird the formatter didn't catch this



_Suggestion:_
```XML
use crate::state::errors::StateError;

#[rstest]
fn test_error_forrmat() {
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/state/errors.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1IBx5z4puiUiDrxT0p:-O1IBx5z4puiUiDrxT0q:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/259a8aa8086911412050b0d3b9957fb6ad61776a/crates/blockifier/src/state/errors.rs#L24)):*
> ```XML
>     #[error("Requested {0:?} is unavailable for deployment.")]
>     UnavailableContractAddress(ContractAddress),
>     // TODO: (Aviv, 8/7/2024): use lowerhex print instead of debug in the next starknet-api version.
> ```





_Suggestion:_
```XML
// TODO(Aviv, 8/7/2024): 
```
___
*[`crates/blockifier/src/state/errors_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1IC3HaEmqouuZbhXOU:-O1IC3HaEmqouuZbhXOV:bvhuccf) ([raw file](https://github.com/starkware-libs/blockifier/blob/259a8aa8086911412050b0d3b9957fb6ad61776a/crates/blockifier/src/state/errors_test.rs#L10)):*
> ```XML
> fn test_error_forrmat() {
>     let error = StateError::UndeclaredClassHash(ClassHash(Felt252::from(2)));
>     assert_eq!(error.to_string(), "Class with hash ClassHash(0x2) is not declared.");
> ```

This is the goal for all error messages



_Suggestion:_
```XML
"Class with hash 0x2 is 
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053)* status: all files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/state/errors_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1IC3HaEmqouuZbhXOU:-O1QLZTG4XfSr2ey1g3L:bgmyr5n) ([raw file](https://github.com/starkware-libs/blockifier/blob/259a8aa8086911412050b0d3b9957fb6ad61776a/crates/blockifier/src/state/errors_test.rs#L10)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This is the goal for all error messages
</blockquote></details>

To achieve this without changing the starknet-api,I need to define a new wrapper struct and update it everywhere in the code.
in starknet-api all I need is to change 1 line, 
do it?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/state/errors_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1IC3HaEmqouuZbhXOU:-O1QTc_P1UL6qW1gXdY7:b929a0y) ([raw file](https://github.com/starkware-libs/blockifier/blob/259a8aa8086911412050b0d3b9957fb6ad61776a/crates/blockifier/src/state/errors_test.rs#L10)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

To achieve this without changing the starknet-api,I need to define a new wrapper struct and update it everywhere in the code.
in starknet-api all I need is to change 1 line, 
do it?
</blockquote></details>

Oh, no. Let's do it later through SN API

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1HZY45D0Mz0Lt0_rmr:-O1QXEv45uxaw7QIyXCU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/259a8aa8086911412050b0d3b9957fb6ad61776a/crates/blockifier/src/state.rs#L6)):*
> ```XML
> pub mod state_api;
> #[cfg(test)]
> pub mod errors_test;
> ```

Done.
___
*[`crates/blockifier/src/state/errors_test.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1HZTxj-XKFKGj-D_zJ:-O1QUNOk86bqpV-qK6dc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/259a8aa8086911412050b0d3b9957fb6ad61776a/crates/blockifier/src/state/errors_test.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

weird the formatter didn't catch this
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/errors_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1IC3HaEmqouuZbhXOU:-O1QTNq49V9IXg6AyOUy:b-2l52dd) ([raw file](https://github.com/starkware-libs/blockifier/blob/259a8aa8086911412050b0d3b9957fb6ad61776a/crates/blockifier/src/state/errors_test.rs#L10)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh, no. Let's do it later through SN API
</blockquote></details>

I can also use a helper function that returns the nested field. For some reason, I can't access the nested field directly with .0.0.
For now, I think that's the best option

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/error_format_test.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1RvY3lBsZTU3udXFSs:-O1RvY3lBsZTU3udXFSt:b-bshp6v) ([raw file](https://github.com/starkware-libs/blockifier/blob/08372814a894737beb73150ec9425fbe5f304d7e/crates/blockifier/src/state/error_format_test.rs#L7)):*
> ```XML
> use crate::state::errors::StateError;
> 
> #[rstest]
> ```

I think `#[test]` is enough here, no need for `rstest` (the `rstest` crate is used for the `cases`, `case` and `values` attributes, for example)



_Suggestion:_
```XML
use starknet_api::core::ClassHash;

use crate::state::errors::StateError;

#[test]
```
___
*[`crates/blockifier/src/state/error_format_test.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1RvQmE7bOaY6ccHGTX:-O1RvQmE7bOaY6ccHGTY:b-b8c6pc) ([raw file](https://github.com/starkware-libs/blockifier/blob/08372814a894737beb73150ec9425fbe5f304d7e/crates/blockifier/src/state/error_format_test.rs#L9)):*
> ```XML
> #[rstest]
> fn test_error_undeclared_class_hash_forrmat() {
>     let error = StateError::UndeclaredClassHash(ClassHash(Felt252::from(2)));
> ```

wrong felt :)



_Suggestion:_
```XML
use starknet_types_core::felt::Felt;
use rstest::rstest;
use starknet_api::core::ClassHash;

use crate::state::errors::StateError;

#[rstest]
fn test_error_undeclared_class_hash_forrmat() {
    let error = StateError::UndeclaredClassHash(ClassHash(Felt::TWO));
```
___
*[`crates/blockifier/src/state/errors.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1Rw6MI86Vc-IXqXBTd:-O1Rw6MI86Vc-IXqXBTe:bm1js25) ([raw file](https://github.com/starkware-libs/blockifier/blob/08372814a894737beb73150ec9425fbe5f304d7e/crates/blockifier/src/state/errors.rs#L24)):*
> ```XML
>     #[error("Requested {0:?} is unavailable for deployment.")]
>     UnavailableContractAddress(ContractAddress),
>     #[error("Class with hash {:#064x} is not declared.", **.0)]
> ```

@Yoni-Starkware you mentioned ([here](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1IC3HaEmqouuZbhXOU)) that you want `0x2` and not `0x000...0002`?
Is it important or are leading zeros ok?



_Code quote:_
```XML
{:#064x}
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/error_format_test.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1RvY3lBsZTU3udXFSs:-O1S3-Lc1OC3lLLD-gUM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/08372814a894737beb73150ec9425fbe5f304d7e/crates/blockifier/src/state/error_format_test.rs#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think `#[test]` is enough here, no need for `rstest` (the `rstest` crate is used for the `cases`, `case` and `values` attributes, for example)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/error_format_test.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1RvQmE7bOaY6ccHGTX:-O1S39eF2TeI3CbhGx9V:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/08372814a894737beb73150ec9425fbe5f304d7e/crates/blockifier/src/state/error_format_test.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wrong felt :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/errors.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1Rw6MI86Vc-IXqXBTd:-O1S28Tw0aYTdZTkIztL:b-om3uq7) ([raw file](https://github.com/starkware-libs/blockifier/blob/08372814a894737beb73150ec9425fbe5f304d7e/crates/blockifier/src/state/errors.rs#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware you mentioned ([here](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-O1IC3HaEmqouuZbhXOU)) that you want `0x2` and not `0x000...0002`?
Is it important or are leading zeros ok?
</blockquote></details>

I tried to be consistent with other errors



_Code snippet:_
```XML
    #[error("Entry point {:#064x} of type {typ:?} is not unique.", .selector.0)]
    DuplicatedEntryPointSelector { selector: EntryPointSelector, typ: EntryPointType },
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-:-O1S5Q426uATFWJXZmqm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2053#-:-O1VMQDh2imtmPa-E2eJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
