### PR TITLE
version() and pays_with_Strk() methods

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/883)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/883)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/883#-NdUyPDb1eyh8uVxaLYR:-NdUyPDc3c_UA4BZv4Ca:b64yvvk) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e00bb3c550cd108198e494219a5160892a4e50c/crates/blockifier/src/transaction/account_transaction.rs#L167)):*
> ```XML
> 
>     pub fn pays_with_strk(&self) -> bool {
>         self.version() >= TransactionVersion(StarkFelt::from(3_u8))
> ```

duplicated, but, calling `get_account_transaction_context` clones many fields, so I prefer to duplicate the logic

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/883)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/objects.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/883#-NdV07lt6LeFCGbva0sy:-NdV07lt6LeFCGbva0sz:bxag7qy) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e00bb3c550cd108198e494219a5160892a4e50c/crates/blockifier/src/transaction/objects.rs#L30)):*
> ```XML
>     }
> 
>     pub fn pays_with_strk(&self) -> bool {
> ```

needed for [next PR](https://reviewable.io/reviews/starkware-libs/blockifier/884)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/883)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/883#-NdV1OKL7w4oU-7XOHyr:-NdV1OKL7w4oU-7XOHys:bewrtz2) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e00bb3c550cd108198e494219a5160892a4e50c/crates/blockifier/src/transaction/account_transaction.rs#L166)):*
> ```XML
>     }
> 
>     pub fn pays_with_strk(&self) -> bool {
> ```

not actually sure if this is needed... but can be useful

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/883)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/883#-NdV8TTX9v0WBgPjLQoV:-NdV8TTX9v0WBgPjLQoW:bifvt0r) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e00bb3c550cd108198e494219a5160892a4e50c/crates/blockifier/src/transaction/account_transaction.rs#L166)):*
> ```XML
>     }
> 
>     pub fn pays_with_strk(&self) -> bool {
> ```

What about `fee_token_address` getter?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/883)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/883#-NdV8TTX9v0WBgPjLQoV:-NdV8xW1-wi00yKWXwCh:b-x26gxo) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e00bb3c550cd108198e494219a5160892a4e50c/crates/blockifier/src/transaction/account_transaction.rs#L166)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about `fee_token_address` getter?
</blockquote></details>

removed all but the necessary method

**Pull request closed without merging**
