### PR TITLE
refactor: lift the order assumption on the os constants in versioned constants json

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1559)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Plz add another reviewer

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-:-Nr9IYTV19PVruwmwhWu:bx8k9wo)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1559)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @OriStarkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9KhAu7FSK6lz5qUm1):*
The crux of this change is that the order assumption was lifted from the versioned constants json, that should be what people see in the commit log/PR title.



_Code quote:_
```
 refactor: add add_to_gas_costs function
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 421 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9LmLpCjrlT2Azfxhn:-Nr9LmLpCjrlT2Azfxho:bcpfgo3) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L421)):*
> ```XML
>     }
> 
>     fn add_to_gas_costs(
> ```

Consider adding a `recursive_` prefix to this, for readability



_Code quote:_
```XML
    fn add_to_gas_costs(
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 423 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9LYWCE9rce273y55l:-Nr9LYWD6dyxeHOq1e-i:bx20yjl) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L423)):*
> ```XML
>     fn add_to_gas_costs(
>         key: String,
>         value: Value,
> ```

Can these be &str and &Value?



_Code quote:_
```XML
        key: String,
        value: Value,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 426 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9NAo6959PpwKknpr3:-Nr9NAo6959PpwKknpr4:b-gv5cse) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L426)):*
> ```XML
>         raw_data: &IndexMap<String, Value>,
>         mut gas_costs: IndexMap<String, u64>,
>     ) -> Result<IndexMap<String, u64>, OsConstantsSerdeError> {
> ```

Can we use &mut gas_costs instead? 
Does that give borrow-checker issues due to recrusion?

The pattern of "passing ownership to an arg and then returning it from the function" is usually an indication of an unhandled ownership issue.



_Code quote:_
```XML
        mut gas_costs: IndexMap<String, u64>,
    ) -> Result<IndexMap<String, u64>, OsConstantsSerdeError> {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 426 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9Oge4E4hkOndAPBww:-Nr9Oge4E4hkOndAPBwx:b9jgwel) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L426)):*
> ```XML
>         raw_data: &IndexMap<String, Value>,
>         mut gas_costs: IndexMap<String, u64>,
>     ) -> Result<IndexMap<String, u64>, OsConstantsSerdeError> {
> ```

And move into `OsConstantsRawJson`.
Rationale: other than the usage of `raw_data`, which is from `self, this logic has more to do the RawJson struct, since it has to do with parsing, whereas the OsConstant itself is more of a dataclass.



_Suggestion:_
```XML
    fn add_to_gas_costs(
        &self,
        key: String,
        value: Value,
        mut gas_costs: IndexMap<String, u64>,
    ) -> Result<IndexMap<String, u64>, OsConstantsSerdeError> {
        let raw_json_file_as_dict = &self.raw_json_file_as_dict;
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 451 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9M60O4qc42A-rQe14:-Nr9M60O4qc42A-rQe15:b-nb36yk) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c55aa3571aa8fdcf765cb06f5ac43ea4e77c75/crates/blockifier/src/versioned_constants.rs#L451)):*
> ```XML
>                     // into:
>                     // k_1 = k_2 * factor_1 + k_3 * factor_2
>                     // Assumption: k_2 and k_3 appeared before k_1 in the JSON.
> ```

Can you re-add the docstring? or replace with something better if you have an idea for one



_Code quote:_
```XML
                    // Converts:
                    // `k_1: {k_2: factor_1, k_3: factor_2}`
                    // into:
                    // k_1 = k_2 * factor_1 + k_3 * factor_2
                    // Assumption: k_2 and k_3 appeared before k_1 in the JSON.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 467 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9KQKs-hElRVdWlvqo:-Nr9KQKs-hElRVdWlvqp:b3nmtgk) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L467)):*
> ```XML
>                 // String consts are all non-whitelisted, ignore them.
>                 return Ok(gas_costs);
>             }
> ```

This part might be confusing to readers: it's not obvious why an ignored value returns `Ok(gas_costs)` (it's clarified only after reviewing the rest of the code).
I think due to having to return gas_costs from the function 



_Code quote:_
```XML
            Value::String(_) => {
                // String consts are all non-whitelisted, ignore them.
                return Ok(gas_costs);
            }
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 485 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9J_jWA1zadwOrzSyY:-Nr9J_jWA1zadwOrzSyZ:b7hay1q) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L485)):*
> ```XML
> 
>         let OsConstantsRawJson { raw_json_file_as_dict, validate_rounding_consts } = raw_json_data;
>         for (key, value) in raw_json_file_as_dict.clone() {
> ```

I see this clone was added, as well as a few more inside the function.
Can they be avoided?



_Code quote:_
```XML
        for (key, value) in raw_json_file_as_dict.clone() {
```

**Review by giladchase — COMMENTED** [review]
Python Pr

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-:-Nr9WDEd9vri57nC7xeS:b-5xgmn3)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @OriStarkware)

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1559)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @giladchase)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9KhAu7FSK6lz5qUm1):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The crux of this change is that the order assumption was lifted from the versioned constants json, that should be what people see in the commit log/PR title.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 423 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9LYWCE9rce273y55l:-Nr9pbh87Utj3-trmgtc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L423)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can these be &str and &Value?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 426 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9NAo6959PpwKknpr3:-Nr9r9jO3LLHeoZFKErJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L426)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can we use &mut gas_costs instead? 
Does that give borrow-checker issues due to recrusion?

The pattern of "passing ownership to an arg and then returning it from the function" is usually an indication of an unhandled ownership issue.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 426 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9Oge4E4hkOndAPBww:-NrA0yli2k9SwycXdHbK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L426)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

And move into `OsConstantsRawJson`.
Rationale: other than the usage of `raw_data`, which is from `self, this logic has more to do the RawJson struct, since it has to do with parsing, whereas the OsConstant itself is more of a dataclass.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 451 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9M60O4qc42A-rQe14:-NrA1L975RcPkSQ7qEpD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c55aa3571aa8fdcf765cb06f5ac43ea4e77c75/crates/blockifier/src/versioned_constants.rs#L451)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can you re-add the docstring? or replace with something better if you have an idea for one
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 467 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9KQKs-hElRVdWlvqo:-NrA2KW87n51Yysumnbt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L467)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This part might be confusing to readers: it's not obvious why an ignored value returns `Ok(gas_costs)` (it's clarified only after reviewing the rest of the code).
I think due to having to return gas_costs from the function
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 485 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9J_jWA1zadwOrzSyY:-NrALBWk5QK6xxUBHROf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L485)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I see this clone was added, as well as a few more inside the function.
Can they be avoided?
</blockquote></details>

Done.

**Review by OriStarkware — COMMENTED** [review]
Python PR: https://reviewable.io/reviews/starkware-industries/starkware/34099

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-:-NrAONlTBYH-NIABM7EC:b616041)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @giladchase and @OriStarkware)

**Review by ayeletstarkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1559)* status: all files reviewed, 7 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

**Review by giladchase — CHANGES_REQUESTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-:-NrFAtWt-kFaVEI62h4f:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 423 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-Nr9LYWCE9rce273y55l:-NrEuz1T4txCkO0R3JQX:b-lwimy) ([raw file](https://github.com/starkware-libs/blockifier/blob/76c6102c648d81fd08e93dad3e6af3f59547f2c5/crates/blockifier/src/versioned_constants.rs#L423)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Tnx.

Note that it should be `&str` though, rather than `&String`.

In almost all cases, due to the deref-coercion &String -> &str,  having function take args as `&str` will make them stritcly more general than `&String`, making the latter a type you almost never see explicitly required.
___
*[`crates/blockifier/src/versioned_constants.rs` line 428 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-NrEpGAf2e8LMuvGAg-w:-NrEpGAf2e8LMuvGAg-x:b-qvrnll) ([raw file](https://github.com/starkware-libs/blockifier/blob/03fbe26f46abfe0f711c5bf68e0f6886855994a6/crates/blockifier/src/versioned_constants.rs#L428)):*
> ```XML
>         let gas_costs = raw_json_data.get_gas_costs()?;
>         let validate_rounding_consts = raw_json_data.validate_rounding_consts;
>         let os_constants = OSConstants { gas_costs, validate_rounding_consts };
> ```

If you want (and if it fits into one line), not critical



_Suggestion:_
```XML
    
        let os_constants = OSConstants { gas_costs, validate_rounding_consts: raw_json_data.validate_rounding_consts };
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 464 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1559#-NrEvaWM5NdISdNO4e3-:-NrEvaWM5NdISdNO4e30:b-nlubg8) ([raw file](https://github.com/starkware-libs/blockifier/blob/03fbe26f46abfe0f711c5bf68e0f6886855994a6/crates/blockifier/src/versioned_constants.rs#L464)):*
> ```XML
>     }
> 
>     fn recursive_add_to_gas_costs(
> ```

Add very short docstring (`///`), something about having some keys require other keys to defined first in order to be defined properly.
Also add a short comment beneth it:`// Invariant: there is no circular dependency between key definitions.` 



_Code quote:_
```XML
    fn recursive_add_to_gas_costs(
```

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1559)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1559)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
