### PR TITLE
Refactor L1 handler creation in `native_blockifier`.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/969)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/969)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @NirLevi-starkware)

___
*[`crates/native_blockifier/src/py_l1_handler.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/969#-NgSnFHg7cEkqSD7IOSL:-NgTN_t21qrLd3cEEL7l:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8cc50c39d237f73fa85fc2ac2627a60ff9ddddbe/crates/native_blockifier/src/py_l1_handler.rs#L25)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should we extract this logic into the constants module itself?
We can now do:
```rust
// in constants.rs
pub const L1_HANDLER_VERSION: TransactionVersion = TransactionVersion(StarkFelt::ZERO);
```
For versions larger than 0 we can use `TransactionVersion(StarFelt::from_u128(...))` once we bump SN API.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_l1_handler.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/969#-NgSoBlk1LcpcMbCCXmK:-NgTN1Ro4spe8DS3Wi17:b-4xp06p) ([raw file](https://github.com/starkware-libs/blockifier/blob/8cc50c39d237f73fa85fc2ac2627a60ff9ddddbe/crates/native_blockifier/src/py_l1_handler.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Maybe we should add `From<PyFelt> for Nonce` as well as for other commonly used types?
</blockquote></details>

Do you think it would make the code much better?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/969)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @NirLevi-starkware)

___
*[`crates/native_blockifier/src/py_l1_handler.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/969#-NgSoBlk1LcpcMbCCXmK:-NgTaSVy5axliJcVls2H:baoowrz) ([raw file](https://github.com/starkware-libs/blockifier/blob/8cc50c39d237f73fa85fc2ac2627a60ff9ddddbe/crates/native_blockifier/src/py_l1_handler.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you think it would make the code much better?
</blockquote></details>

Not sure :thinking: the only thing that _might_ make it worth is that it removes the IP addr.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/969)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @giladchase and @NirLevi-starkware)

___
*[`crates/native_blockifier/src/py_l1_handler.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/969#-NgSoBlk1LcpcMbCCXmK:-NgmmlD43Am4a4ev_t_Q:b-qcn8va) ([raw file](https://github.com/starkware-libs/blockifier/blob/8cc50c39d237f73fa85fc2ac2627a60ff9ddddbe/crates/native_blockifier/src/py_l1_handler.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not sure :thinking: the only thing that _might_ make it worth is that it removes the IP addr.
</blockquote></details>

It should be done separately, since this is in SN API.

**Review by giladchase — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/969)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NirLevi-starkware)

**Pull request merged**
