### PR TITLE
chore: publish native blockifier artifacts via CI

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O09UXdz3BACd1aoMXa_:-O09UXdz3BACd1aoMXaa:b26w9f) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/35294)

___

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @giladchase, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`BUILD` line 1 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0ESwpq46kJWwAMWfyf:-O0ESwpq46kJWwAMWfyg:b-uh7f5s) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/BUILD#L1)):*
> ```Starlark
> # Export the built artifact to allow local builds.
> ```

are you sure its needed? there is no native bazel builds of this project

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @elintul, @giladchase, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`BUILD` line 1 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0ESwpq46kJWwAMWfyf:-O0ETxJ6B4pmTUf7PsEs:befs1bn) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/BUILD#L1)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

are you sure its needed? there is no native bazel builds of this project
</blockquote></details>

the local build on python side uses `local_repository`, which expects this file to be exported via BUILD.
Tested locally now, this is required

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-:-O0Ee1ZS3a8elamg6Joc:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @elintul, @giladchase, @RoeiE-starkware, and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul, @giladchase, @RoeiE-starkware, and @Yoni-Starkware)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 85 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0ILuhl3WfjGz3Di5ZE:-O0ILuhl3WfjGz3Di5ZF:brmpne2) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/.github/workflows/ci.yml#L85)):*
> ```YAML
>       - run: cargo test --features concurrency
> 
>   native-blockifier-artifacts-push:
> ```

Do we want failure in this to block merges? if the upload fails (ran out of room on bucket? something else that can make it fail) will this workflow fail?



_Code quote:_
```YAML
  native-blockifier-artifacts-push:
```
___
*[`.github/workflows/ci.yml` line 93 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0ILDQc3Qn0tcTTmLUD:-O0ILDQc3Qn0tcTTmLUE:bjxtobe) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/.github/workflows/ci.yml#L93)):*
> ```YAML
>       - uses: actions/setup-python@v5
>         with:
>           python-version: 'pypy3.9'
> ```

Do we need caching here? 



_Code quote:_
```YAML
      - uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.9'
```
___
*[`.github/workflows/ci.yml` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0IG8eT6MMDAsCQ_eoM:-O0IG8eU7bT-qiQo13Vr:ber9o4e) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/.github/workflows/ci.yml#L110)):*
> ```YAML
>             fi | \
>             cut -c 1-7) && \
>             echo "short_hash=$SHORT_HASH" >> $GITHUB_OUTPUT
> ```

Maybe more readable



_Suggestion:_
```YAML
          FULL_HASH=$(\
            if [ "$EVENT_NAME" == 'pull_request' ]; then \
            echo "$HEAD_SHA"; \
            else echo "$AFTER_EVENT"; \
            fi)
          echo "short_hash=${FULL_HASH:0:7}" >> $GITHUB_OUTPUT
```
___
*[`.github/workflows/ci.yml` line 113 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0IKj3QEBZHAg_SiB0D:-O0IKj3QEBZHAg_SiB0E:b-3m3bti) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/.github/workflows/ci.yml#L113)):*
> ```YAML
> 
>       - name: Build native_blockifier shared object
>         if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
> ```

Where can i see the logic for when this get's invalidated?



_Code quote:_
```YAML
        if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 93 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0ILDQc3Qn0tcTTmLUD:-O0Ieg4CBHaeDY2mOA8W:b-c93304) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/.github/workflows/ci.yml#L93)):*
[by default](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#hosted-tool-cache) this should be cached; from the [README](https://github.com/actions/setup-python):
> The action will first check the local [tool cache](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#hosted-tool-cache) for a [semver](https://github.com/npm/node-semver#versions) match. If unable to find a specific version in the tool cache, the action will attempt to download a version of Python from [GitHub Releases](https://github.com/actions/python-versions/releases) and for PyPy from the official [PyPy's dist](https://downloads.python.org/pypy/).

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0IG8eT6MMDAsCQ_eoM:-O0IfiOJ8x_Lk0d9s7p6:b9of58q) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/.github/workflows/ci.yml#L110)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Maybe more readable
</blockquote></details>

[didn't work](https://github.com/starkware-libs/blockifier/actions/runs/9676294182/job/26695521387)... translates to this, for some reason:
```
echo "short_hash=$***FULL_HASH:0:7***" >> $GITHUB_OUTPUT
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 113 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0IKj3QEBZHAg_SiB0D:-O0JBtn8-OR5cMcZ4xnh:b-jiod05) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/.github/workflows/ci.yml#L113)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

caching currently doesn't seem to be working here; @alon-dotan-starkware you suspect something with pyo3 build system invalidating dependencies cache?
</blockquote></details>

[caching works](https://github.com/starkware-libs/blockifier/actions/runs/9678376316/job/26702025119), but not in current PR - subsequent PRs will have faster CI

**Review by giladchase — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-:-O0JFE0c9qay_2SwegIY:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware, @elintul, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 85 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0ILuhl3WfjGz3Di5ZE:-O0JEciSD_Ga6_wKNbHf:b-2kvz04) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/.github/workflows/ci.yml#L85)):*
> we'll need to update the github settings after this is merged

Sounds good

> when a new feature branch is checked out we'll need a new branch rule (or add an empty `native-blockifier-artifacts-push` phase to the ci of every old feature branch).

I don't think I understand this one, can you explain more the context? checking out a branch locally will trigger something?
___
*[`.github/workflows/ci.yml` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0IG8eT6MMDAsCQ_eoM:-O0JF3mGDIuuIq7HJP1T:b-amvdbd) ([raw file](https://github.com/starkware-libs/blockifier/blob/de7ae5cb5c59780df6b2ac5f77236c85825ea295/.github/workflows/ci.yml#L110)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[didn't work](https://github.com/starkware-libs/blockifier/actions/runs/9676294182/job/26695521387)... translates to this, for some reason:
```
echo "short_hash=$***FULL_HASH:0:7***" >> $GITHUB_OUTPUT
```
</blockquote></details>

oh well :( must need escaping of stuff or something github'ish, no matter

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul, @RoeiE-starkware, and @Yoni-Starkware)

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`build_native_blockifier.sh` line 11 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0NjWsI2KtdNqyT_ncJ:-O0NjWsI2KtdNqyT_ncK:bxoclc6) ([raw file](https://github.com/starkware-libs/blockifier/blob/c82b90039d0f0b2dd80e70b0d46a7b76a55c4fe6/build_native_blockifier.sh#L11)):*
> ```Shell
>     --net host \
>     -e CARGO_HOME=${HOME}/.cargo \
>     -e PYO3_PYTHON=/usr/local/bin/pypy3.9 \
> ```

we cant rust it? add env to the Cargo.toml
https://doc.rust-lang.org/nightly/cargo/reference/config.html#env



_Code quote:_
```Shell
PYO3_PYTHON=/usr/local/bin/pypy3.9
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`scripts/install_pypy.sh` line 3 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0Njsc01cUGPr4P2G2L:-O0Njsc01cUGPr4P2G2M:b-x3nqzn) ([raw file](https://github.com/starkware-libs/blockifier/blob/c82b90039d0f0b2dd80e70b0d46a7b76a55c4fe6/scripts/install_pypy.sh#L3)):*
> ```Shell
> #!/bin/env bash
> 
> set -e
> ```

not needed in non executable file



_Code quote:_
```Shell
#!/bin/env bash

set -e
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`build_native_blockifier.sh` line 17 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0NkhQ42oaMdrPVPAHi:-O0NkhQ42oaMdrPVPAHj:bb7r2f0) ([raw file](https://github.com/starkware-libs/blockifier/blob/c82b90039d0f0b2dd80e70b0d46a7b76a55c4fe6/build_native_blockifier.sh#L17)):*
> ```Shell
>     --workdir ${PWD} \
>     ${docker_image_name} \
>     cargo build --release -p native_blockifier --features=testing
> ```

why?



_Code quote:_
```Shell
cargo build --release -p native_blockifier --features=testing
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware, @elintul, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`build_native_blockifier.sh` line 11 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0NjWsI2KtdNqyT_ncJ:-O0NqXor71iUh00wqhEs:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c82b90039d0f0b2dd80e70b0d46a7b76a55c4fe6/build_native_blockifier.sh#L11)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

we cant rust it? add env to the Cargo.toml
https://doc.rust-lang.org/nightly/cargo/reference/config.html#env
</blockquote></details>

Done.
___
*[`build_native_blockifier.sh` line 17 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0NkhQ42oaMdrPVPAHi:-O0NqYPF1X3yZxg_kNJZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c82b90039d0f0b2dd80e70b0d46a7b76a55c4fe6/build_native_blockifier.sh#L17)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

Done.
___
*[`scripts/install_pypy.sh` line 3 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/2001#-O0Njsc01cUGPr4P2G2L:-O0NmnvyC6yL6o8qbfoT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c82b90039d0f0b2dd80e70b0d46a7b76a55c4fe6/scripts/install_pypy.sh#L3)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

not needed in non executable file
</blockquote></details>

Done.

**Review by alon-dotan-starkware — APPROVED** [review]
> Reviewed 3 of 6 files at r7, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul, @RoeiE-starkware, and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2001)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul, @RoeiE-starkware, and @Yoni-Starkware)

**Pull request merged**
