### PR TITLE
Minimal example for list parametrization

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/930)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/930)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/930#-Nemp6VP53243pQxC8oc:-Nemp6VP53243pQxC8od:b-2omigf) ([raw file](https://github.com/starkware-libs/blockifier/blob/29dc394a48fb6be9a90a266fba700320df2dbc37/crates/blockifier/src/transaction/test_utils.rs#L38)):*
> ```XML
> #[case::v0(TransactionVersion::ZERO)]
> #[case::v1(TransactionVersion::ONE)]
> fn all_tx_versions(#[case] tx_version: TransactionVersion) {}
> ```

Now you can remove the dummy stuff



_Suggestion:_
```XML
#[allow(clippy::unused-macros)]
#[template]
#[rstest]
#[case::v0(TransactionVersion::ZERO)]
#[case::v1(TransactionVersion::ONE)]
fn all_tx_versions(#[case] tx_version: TransactionVersion) {}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/930)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/930#-Nemp6VP53243pQxC8oc:-NempcBcBA9GlTuy9lZl:b-ss6mbo) ([raw file](https://github.com/starkware-libs/blockifier/blob/29dc394a48fb6be9a90a266fba700320df2dbc37/crates/blockifier/src/transaction/test_utils.rs#L38)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Now you can remove the dummy stuff
</blockquote></details>

Doesn't work.
Please checkout and test yourself first :P
in any case I guess we can close this in favor of rstest's `values` proc macro

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/930)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/930#-Nemp6VP53243pQxC8oc:-Nemty17Axdy_P2H93E4:b-d4w33v) ([raw file](https://github.com/starkware-libs/blockifier/blob/29dc394a48fb6be9a90a266fba700320df2dbc37/crates/blockifier/src/transaction/test_utils.rs#L38)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Doesn't work.
Please checkout and test yourself first :P
in any case I guess we can close this in favor of rstest's `values` proc macro
</blockquote></details>

I did, but only for the module-level :sweat_smile: it does work for the module level though, that is, putting `#![allow(unused_macros)]` at the top of the module (if we define the macro in a dedicated module this will be an OK move i guess).

but ya if you can use a ready-made solution that'd be better :muscle: 

In any case, both yours and the values thing are pretty cool :sunglasses:

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/930)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/930#-Nemp6VP53243pQxC8oc:-NemxjRX7abGLGRz9RZB:b7imi4m) ([raw file](https://github.com/starkware-libs/blockifier/blob/29dc394a48fb6be9a90a266fba700320df2dbc37/crates/blockifier/src/transaction/test_utils.rs#L38)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I did, but only for the module-level :sweat_smile: it does work for the module level though, that is, putting `#![allow(unused_macros)]` at the top of the module (if we define the macro in a dedicated module this will be an OK move i guess).

but ya if you can use a ready-made solution that'd be better :muscle: 

In any case, both yours and the values thing are pretty cool :sunglasses:
</blockquote></details>

still trying the values thing... not getting it to work yet.
may need to write a proc-macro

**Pull request closed without merging**
