### PR TITLE
Move payrus storage to native_blockifier

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/402)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #402** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/402" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/402?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/402)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/402#-NSt_vpqEpjcaNnuzkC3:-NSt_vpqEpjcaNnuzkC4:b-wf0r9m) (no related file):*
Why are you moving it?
You think that executor should't have Papyrus dependency embedded in it?
If someone wants to easily use it out-of-the-box _with_ Papyrus storage, how would she do that?

___
___
*[`crates/native_blockifier/src/lib.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/402#-NSt_oqj475HbCo2MItG:-NSt_oqj475HbCo2MItH:b-v53drf) ([raw file](https://github.com/starkware-libs/blockifier/blob/41630338009fbffd54bfef4cda88c2d8d8c69db3/crates/native_blockifier/src/lib.rs#L8)):*
> ```XML
> pub mod py_utils;
> pub mod storage;
> pub mod papyrus_state;
> ```

Keep alphabetized.



_Code quote:_
```XML
pub mod papyrus_state;
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/402)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/402#-NSt_vpqEpjcaNnuzkC3:-NStfJgh8_GIhPNrmEZj:b-xjcdgu) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I need papyrus to depend on blockfier. The idea is to eventually have it on papyrus, so you could import it from there.
</blockquote></details>

For example, currently we are forcing users (like Madara) to depend on papyrus, which is weird.

___

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/402#-:-NStohDQDddpdoTt6_Bz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
