### PR TITLE
Add V3 support in get_account_tx_context.

### PR DESCRIPTION
**Pull request by NirLevi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/970)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/970)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @NirLevi-starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/970#-Nfuw9b47x9PTfEJ2kun:-Nfuw9b47x9PTfEJ2kuo:bv0klhy) ([raw file](https://github.com/starkware-libs/blockifier/blob/55d75fd8f6638d74548508508917019a5a741b96/crates/blockifier/src/transaction/transactions.rs#L183)):*
> ```XML
>             sender_address: self.tx.sender_address(),
>         };
> ```

I think a big `match` is better.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/970#-NfuwDEi3hitGUmsJ19K:-NfuwDEj6HYc0tSDeJiK:bxhymww) ([raw file](https://github.com/starkware-libs/blockifier/blob/55d75fd8f6638d74548508508917019a5a741b96/crates/blockifier/src/transaction/transactions.rs#L200)):*
> ```XML
>                     fee_data_availability_mode: tx.fee_data_availability_mode,
>                     paymaster_data: tx.paymaster_data.clone(),
>                     account_deployment_data: tx.account_deployment_data.clone(),
> ```

This might be big, I'll add a Monday item to avoid this.



_Code quote:_
```XML
account_deployment_data: tx.account_deployment_data.clone()
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/970)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @NirLevi-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/970#-Nfv0LJTEEjuLv-rKccc:-Nfv0LJTEEjuLv-rKccd:bta0nby) (no related file):*
Python PR?

___

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/970)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @NirLevi-starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/970)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @giladchase and @NirLevi-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/970#-NfvKw5AD4WZHAU9IbLl:-NfvKw5AD4WZHAU9IbLm:b-1wqqgo) (no related file):*
I see all previous PRs' content; is this what you intended? 

___
___
*[`crates/blockifier/src/transaction/objects.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/970#-NfvKd0A1YfZQ_8BVotZ:-NfvKd0BBvdfQzhKmj0S:b-afmvzz) ([raw file](https://github.com/starkware-libs/blockifier/blob/8766f7956ab68adce484dcdd555f8243ca02b25f/crates/blockifier/src/transaction/objects.rs#L19)):*
> ```XML
>         $(pub fn $field(&self) -> $field_type {
>             match self{
>                 Self::Deprecated(context) => context.$field,
> ```

Change order (in all `match`es).

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/970)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/970#-Nfv0LJTEEjuLv-rKccc:-NfvOAeg4OX7mPzltyzU:b9cpy7n) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Python PR?
</blockquote></details>

What do you mean? Do i need to open a PR with an update of the commit hash? 

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/970#-NfvKw5AD4WZHAU9IbLl:-NfvNeRx37SL3fiLIixR:b-oa8lw3) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I see all previous PRs' content; is this what you intended?
</blockquote></details>

Nope, git issues, fixed it :)

___
___
*[`crates/blockifier/src/transaction/transactions.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/970#-Nfuw9b47x9PTfEJ2kun:-NfvNcle1qJijHHaYwVs:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/55d75fd8f6638d74548508508917019a5a741b96/crates/blockifier/src/transaction/transactions.rs#L183)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think a big `match` is better.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/970#-NfvKd0A1YfZQ_8BVotZ:-NfvNprD1U_hQ5cymHyz:btoyel8) ([raw file](https://github.com/starkware-libs/blockifier/blob/8766f7956ab68adce484dcdd555f8243ca02b25f/crates/blockifier/src/transaction/objects.rs#L19)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Change order (in all `match`es).
</blockquote></details>

V3 above the deprecated? I've seen many places in the code that go in numerical order

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/970)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @NirLevi-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/970#-Nfv0LJTEEjuLv-rKccc:-NfvcRcP8Pgiicl8pDJS:bn8ry9q) (no related file):*
<details><summary><i>Previously, NirLevi-starkware (Nir Levi) wrote…</i></summary><blockquote>

What do you mean? Do i need to open a PR with an update of the commit hash?
</blockquote></details>

Yup, and put here the link to it. 

___
___
*[`crates/blockifier/src/transaction/objects.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/970#-NfvKd0A1YfZQ_8BVotZ:-Nfvcl225yEdumF5N0XO:b3d5ho4) ([raw file](https://github.com/starkware-libs/blockifier/blob/8766f7956ab68adce484dcdd555f8243ca02b25f/crates/blockifier/src/transaction/objects.rs#L19)):*
<details><summary><i>Previously, NirLevi-starkware (Nir Levi) wrote…</i></summary><blockquote>

V3 above the deprecated? I've seen many places in the code that go in numerical order
</blockquote></details>

I prefer we keep the enum variants alphabetized.

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/970)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/970#-Nfv0LJTEEjuLv-rKccc:-NfvmRsj-6qortuu_3BM:bwuh6ng) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yup, and put here the link to it.
</blockquote></details>

[Here](https://github.com/starkware-industries/starkware/pull/32060)

___
___
*[`crates/blockifier/src/transaction/objects.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/970#-NfvKd0A1YfZQ_8BVotZ:-Nfvklk05uDM9vZsm_H0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8766f7956ab68adce484dcdd555f8243ca02b25f/crates/blockifier/src/transaction/objects.rs#L19)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I prefer we keep the enum variants alphabetized.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/970#-:-Nfykawc98eS1HUbuqc9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/970)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
