### PR TITLE
chore: panic if u128_from_usize fails

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1522)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1522)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1522)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1522#-Nqi0P1K-nfz03Z3_aXi:-Nqi0P1K-nfz03Z3_aXj:b-xjm5fe) (no related file):*
@giladchase should we perhaps block via `cgf(...)` attributes any architecture with over 128 bits of address space?
I see `cfg(target_arch = "<ARCHITECTURE>")` is a possible feature (see [here](https://stackoverflow.com/questions/41742046/is-there-a-list-of-all-cfg-features)) and running `rustc --print target-list` shows many architectures (but `| grep 128` shows nothing). Perhaps we should explicitly *only allow* specific (currently known) architectures...?
Or is this overkill?

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1522)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1522#-Nqi0P1K-nfz03Z3_aXi:-NqlYeuk-gzKq0UiJLf3:bd4ke1j) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@giladchase should we perhaps block via `cgf(...)` attributes any architecture with over 128 bits of address space?
I see `cfg(target_arch = "<ARCHITECTURE>")` is a possible feature (see [here](https://stackoverflow.com/questions/41742046/is-there-a-list-of-all-cfg-features)) and running `rustc --print target-list` shows many architectures (but `| grep 128` shows nothing). Perhaps we should explicitly *only allow* specific (currently known) architectures...?
Or is this overkill?
</blockquote></details>

Like [this](https://reviewable.io/reviews/starkware-libs/blockifier/1527)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1522)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1522#-Nqi0P1K-nfz03Z3_aXi:-Nqvlw0C3hlcqhCrkaKG:b-9sb4v8) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Like [this](https://reviewable.io/reviews/starkware-libs/blockifier/1527)
</blockquote></details>

(this was merged :))

___

**Review by giladchase — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1522)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1522#-Nqi0P1K-nfz03Z3_aXi:-Nr4qQ_FDOQ86XsrR2h6:bdczi4i) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

(this was merged :))
</blockquote></details>

Overkill :grimacing: 
Unwrapping a cast from usize to u128 inside the `from` cast is totally fine, cause usize \in {u32,u64} for all intended purposes now and anytime in the foreseeable future.

But as for this PR, :lgtm_strong: 

___

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1522)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1522#-Nqi0P1K-nfz03Z3_aXi:-Nr4tmtyCUQYN2dSch1b:b4bt5jq) (no related file):*
>(this was merged :))

I checked out the Rust issue and the MIPS/CHERI example you added. MIPS/CHERI seems to be more about specific security features than general computing needs.

Considering what our users typically need from our project, I'm thinking we might not need to focus on these specialized architectures for now. It could even lead to some confusion about whether our tool is intended for scenarios like MIPS/CHERI, which, as far as I know, we're not targeting.

___

**Pull request merged**
