### PR TITLE
Remove externalization of ` execute ` and ` validate ` of ` PyValidator ` .

### PR DESCRIPTION
**Pull request by noaov1**
Python PR [#32886](https://reviewable.io/reviews/starkware-industries/starkware/32886)

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1211)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1211#-:-Nkt7PUJ47CwRMUPhcwD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1211#-Nkt7EzN1b3XCA_2cbfc:-Nkt7EzN1b3XCA_2cbfd:b-w0t9s5) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2e7daf361b1b8eb928d9dec6e6c6e5e01c8e000/crates/native_blockifier/src/py_validator.rs#L153)):*
> ```XML
> 
>     /// Applicable solely to account deployment transactions: the execution of the constructor
>     // is required before they can be validated.
> ```

another slash



_Suggestion:_
```XML
/// is required before they can be validated.
```

**Review by giladchase — CHANGES_REQUESTED** [review]
Can you give me more context plz about what happened here? why are these methods no longer called from python?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1211#-:-Nkt8usd7roCwFPafkxT:b-was0a5)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1211#-Nkt8SFK-RuOGoY0_CjI:-Nkt8SFK-RuOGoY0_CjJ:bpk14d6) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2e7daf361b1b8eb928d9dec6e6c6e5e01c8e000/crates/native_blockifier/src/py_validator.rs#L154)):*
> ```XML
>     /// Applicable solely to account deployment transactions: the execution of the constructor
>     // is required before they can be validated.
>     pub fn execute(
> ```

Does this and the validate below need to remain`pub`?
If they do, plz move `validate` up so that it appears before private methods.



_Code quote:_
```XML
 pub fn execute(
```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1211)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
Sure. Previously, for deprecated transactions, we performed the gateway validations using a mix of python and blockifier code. This code called the `execute` and `validate` methods. 
We now perform the gateway validations by calling a single method in the blockifier (`perform_validations`), which in turn, calls `execute` and `validate`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1211#-:-NktHu3_BhI3VPFqbREz:bwbfaud)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/py_validator.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1211#-Nkt7EzN1b3XCA_2cbfc:-NktFOjP6BGTeVbhPUVv:b-4kkiy6) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2e7daf361b1b8eb928d9dec6e6c6e5e01c8e000/crates/native_blockifier/src/py_validator.rs#L153)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

another slash
</blockquote></details>

Nice catch :)
___
*[`crates/native_blockifier/src/py_validator.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1211#-Nkt8SFK-RuOGoY0_CjI:-NktFSGsB4jgonCdI4n0:b-nykp7x) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2e7daf361b1b8eb928d9dec6e6c6e5e01c8e000/crates/native_blockifier/src/py_validator.rs#L154)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Does this and the validate below need to remain`pub`?
If they do, plz move `validate` up so that it appears before private methods.
</blockquote></details>

No. Fixed :)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1211)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by giladchase — APPROVED** [review]
TANKS

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1211#-:-Nku6pu7D7Jf5-GjsCbI:b-817rr0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
