### PR TITLE
Fix chain ID construction

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
Did you test the conversion works?

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312#-:-NPMwjxg5PYCQzxGMna1:b-i7f59r)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMwoj8DeBzkxtiQZ1-:-NPMwoj8DeBzkxtiQZ10:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d3f258ba1abb402633637b98178feef3acd29ef/crates/native_blockifier/src/py_transaction.rs#L164)):*
> ```XML
> }
> 
> fn chain_id_int_to_chain_id(value: BigInt) -> NativeBlockifierResult<ChainId> {
> ```





_Suggestion:_
```XML
BigUint
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMwrxl1lJFEUzNzIRp:-NPMwrxl1lJFEUzNzIRq:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d3f258ba1abb402633637b98178feef3acd29ef/crates/native_blockifier/src/py_transaction.rs#L166)):*
> ```XML
> fn chain_id_int_to_chain_id(value: BigInt) -> NativeBlockifierResult<ChainId> {
>     for known_chain_name in vec!["SN_MAIN", "SN_GOERLI", "SN_GOERLI2"] {
>         if value == BigInt::from_bytes_be(Sign::Plus, known_chain_name.as_bytes()) {
> ```





_Suggestion:_
```XML
BigUint::from_bytes_be(known_chain_name.as_bytes()) {
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMxoGZ3DQC11X3wp5N:-NPMxoGZ3DQC11X3wp5O:b-bpq0yr) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L165)):*
> ```XML
> 
> fn chain_id_int_to_chain_id(value: BigInt) -> NativeBlockifierResult<ChainId> {
>     for known_chain_name in &["SN_MAIN", "SN_GOERLI", "SN_GOERLI2"] {
> ```

Make this a constant.
What about the POTC chain ID?



_Code quote:_
```XML
&["SN_MAIN", "SN_GOERLI", "SN_GOERLI2"]
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMxp8C5QHDsC0a8YRL:-NPMxp8C5QHDsC0a8YRM:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L165)):*
> ```XML
> 
> fn chain_id_int_to_chain_id(value: BigInt) -> NativeBlockifierResult<ChainId> {
>     for known_chain_name in &["SN_MAIN", "SN_GOERLI", "SN_GOERLI2"] {
> ```





_Suggestion:_
```XML
chain_name
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMyHbp6Qj_D027nYWj:-NPMyHbp6Qj_D027nYWk:b-a6ch0d) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L170)):*
> ```XML
>         }
>     }
>     Err(NativeBlockifierError::from(StarknetApiError::OutOfRange { string: value.to_string() }))
> ```

Add an unknown/invalid chain id error to `TransactionExecutionError` (this isn't a SN API error).
Are we verifying in python somewhere that the chain ID is valid? When it was an enum it wasn't possible but now that it's an int it can be anything.



_Code quote:_
```XML
StarknetApiError::OutOfRange { string: value.to_string() }
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMzcR50KVTyJWuimAM:-NPMzcR50KVTyJWuimAN:bykpj1s) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L164)):*
> ```XML
> }
> 
> fn chain_id_int_to_chain_id(value: BigInt) -> NativeBlockifierResult<ChainId> {
> ```

Maybe a `TryFrom` in SN API?



_Code quote:_
```XML
chain_id_int_to_chain_id
```

**Review by dorimedini-starkware — COMMENTED** [review]
`cargo test test_dur` is green, where
```
#[test]
fn test_dur() {
    assert_eq!(
        BigUint::from_bytes_be("SN_MAIN".as_bytes()),
        BigUint::from_str("23448594291968334").unwrap()
    );
    assert_eq!(
        BigUint::from_bytes_be("SN_GOERLI".as_bytes()),
        BigUint::from_str("1536727068981429685321").unwrap()
    );
    assert_eq!(
        BigUint::from_bytes_be("SN_GOERLI2".as_bytes()),
        BigUint::from_str("393402129659245999442226").unwrap()
    );
}
```

the numbers are from using `from_bytes(b"SN_MAIN")`, etc. (in python)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312#-:-NPMzEcv3wrn3EDr-Jyf:b1dkci6)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMwoj8DeBzkxtiQZ1-:-NPMzziJ9WLDFwEHfSdn:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d3f258ba1abb402633637b98178feef3acd29ef/crates/native_blockifier/src/py_transaction.rs#L164)):*
> ```XML
> }
> 
> fn chain_id_int_to_chain_id(value: BigInt) -> NativeBlockifierResult<ChainId> {
> ```

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMwrxl1lJFEUzNzIRp:-NPN-IXr1BoE6hJAmDFU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d3f258ba1abb402633637b98178feef3acd29ef/crates/native_blockifier/src/py_transaction.rs#L166)):*
> ```XML
> fn chain_id_int_to_chain_id(value: BigInt) -> NativeBlockifierResult<ChainId> {
>     for known_chain_name in vec!["SN_MAIN", "SN_GOERLI", "SN_GOERLI2"] {
>         if value == BigInt::from_bytes_be(Sign::Plus, known_chain_name.as_bytes()) {
> ```

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMzcR50KVTyJWuimAM:-NPN--2E8k4w8dkr416u:byp8kr) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L164)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe a `TryFrom` in SN API?
</blockquote></details>

WDYM? I should open a PR in starknet-api?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMxoGZ3DQC11X3wp5N:-NPN-2gj5DNPeYRI1CE8:b7g06mk) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L165)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Make this a constant.
What about the POTC chain ID?
</blockquote></details>

1. WDYM "make this a constant"? Tried `vec![...]` but formatter (CI) complained "this can be a reference"
2. Good point, added
___
*[`crates/native_blockifier/src/py_transaction.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMxp8C5QHDsC0a8YRL:-NPN-Hv6DbQYzfgoLSTK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L165)):*
> ```XML
> 
> fn chain_id_int_to_chain_id(value: BigInt) -> NativeBlockifierResult<ChainId> {
>     for known_chain_name in &["SN_MAIN", "SN_GOERLI", "SN_GOERLI2"] {
> ```

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMyHbp6Qj_D027nYWj:-NPN-NsZB0jjRJUVFEq7:b-22a2tc) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L170)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add an unknown/invalid chain id error to `TransactionExecutionError` (this isn't a SN API error).
Are we verifying in python somewhere that the chain ID is valid? When it was an enum it wasn't possible but now that it's an int it can be anything.
</blockquote></details>

If we allow POTC, we cannot verify in public python modules.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMzcR50KVTyJWuimAM:-NPN2h0mDefRMxFwY_jm:bb77ufg) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L164)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM? I should open a PR in starknet-api?
</blockquote></details>

Yes.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPNA1r8AxEZWF9UUgsU:-NPNA1r8AxEZWF9UUgsV:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4568618e0ea6d20763af6f6c70b04865f76134fa/crates/blockifier/src/transaction/errors.rs#L50)):*
> ```XML
>     #[error("Calling other contracts during '{entry_point_kind}' execution is forbidden.")]
>     UnauthorizedInnerCall { entry_point_kind: String },
>     #[error("Unknown chain ID {chain_id:?}.")]
> ```





_Suggestion:_
```XML
#[error("Unknown chain ID '{chain_id:?}'.")]
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMxoGZ3DQC11X3wp5N:-NPNBBtcCFTniIjg3nbh:buir4nv) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L165)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. WDYM "make this a constant"? Tried `vec![...]` but formatter (CI) complained "this can be a reference"
2. Good point, added
</blockquote></details>

At the top of the file, or a different more appropriate file.
`pub const CHAIN_NAMES: &[&str; 3] = &["SN_MAIN", "SN_GOERLI", "SN_GOERLI2"];`
___
*[`crates/native_blockifier/src/py_transaction.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMyHbp6Qj_D027nYWj:-NPNAOcEBH5QndPrZHCy:bov6xoq) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L170)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

If we allow POTC, we cannot verify in public python modules.
</blockquote></details>

So as of now users can send txs to any chain ID?
Should it even be verified here then?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/errors.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPNA1r8AxEZWF9UUgsU:-NPNUcHF2OX0CITZZrUl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4568618e0ea6d20763af6f6c70b04865f76134fa/crates/blockifier/src/transaction/errors.rs#L50)):*
> ```XML
>     #[error("Calling other contracts during '{entry_point_kind}' execution is forbidden.")]
>     UnauthorizedInnerCall { entry_point_kind: String },
>     #[error("Unknown chain ID {chain_id:?}.")]
> ```

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMzcR50KVTyJWuimAM:-NPNPq7U9HKbTSxquSBt:b-xkvkip) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L164)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

here's the issue: I don't want POTC to appear in the starknet-api repo.
I can write a `fn from_number(chain_id: BigUint, allowed_chains: Vec<String>) -> ChainId` function in starknet-api, is that the idea?
from the blockifier I can pass the POTC chain ID name as part of the `allowed_chains` vector
___
*[`crates/native_blockifier/src/py_transaction.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMxoGZ3DQC11X3wp5N:-NPNUBmi2m9keWUoxUjx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L165)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

At the top of the file, or a different more appropriate file.
`pub const CHAIN_NAMES: &[&str; 3] = &["SN_MAIN", "SN_GOERLI", "SN_GOERLI2"];`
</blockquote></details>

Done.



_Code quote:_
```XML
"PRIVATE_SN_POTC_GOERLI"
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMyHbp6Qj_D027nYWj:-NPNUGLk-jYvv-Ohzvds:bp01zzt) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L170)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

So as of now users can send txs to any chain ID?
Should it even be verified here then?
</blockquote></details>

This is meant to be a temporary hack until we separate between public and private SN code. Yes, we should assert the chain ID is one of a set of specific values; how to do this correctly is up to Elin/Yoni (probably low priority ATM)

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPMzcR50KVTyJWuimAM:-NPSMCfzASVsvdUwcDXD:b8oak6c) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fe93aea069687a022c9d01f008331e755a690a8/crates/native_blockifier/src/py_transaction.rs#L164)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

here's the issue: I don't want POTC to appear in the starknet-api repo.
I can write a `fn from_number(chain_id: BigUint, allowed_chains: Vec<String>) -> ChainId` function in starknet-api, is that the idea?
from the blockifier I can pass the POTC chain ID name as part of the `allowed_chains` vector
</blockquote></details>

Can you rename to `to_chain_id_enum`, and move to `py_utils.py`?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_utils.rs` line 57 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPSUuBF2cpaNt6rHvxG:-NPSUuBGEEEa6cc_Mxju:b5ub618) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a5b5072c43b826370a19b3352ac25ba7c259d25/crates/native_blockifier/src/py_utils.rs#L57)):*
> ```XML
> }
> 
> pub fn to_chain_id_enum(value: BigUint) -> NativeBlockifierResult<ChainId> {
> ```

Isn't it better to convert the input, instead of all the allowed IDs?



_Code quote:_
```XML
value: BigUint
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_utils.rs` line 57 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/312#-NPSUuBF2cpaNt6rHvxG:-NPSViOIB0wRhNY4EKPF:b5yb51f) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a5b5072c43b826370a19b3352ac25ba7c259d25/crates/native_blockifier/src/py_utils.rs#L57)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't it better to convert the input, instead of all the allowed IDs?
</blockquote></details>

done.
this test passes (was temporary, not part of PR):
```
#[test]
fn test_dur() {
    assert_eq!(
        BigUint::from_bytes_be("SN_MAIN".as_bytes()),
        BigUint::from_str("23448594291968334").unwrap()
    );
    assert_eq!("SN_MAIN".as_bytes(), BigUint::from_str("23448594291968334").unwrap().to_bytes_be());
    assert_eq!(
        "SN_MAIN",
        String::from_utf8_lossy(&BigUint::from_str("23448594291968334").unwrap().to_bytes_be())
            .to_string()
    );

    assert_eq!(
        BigUint::from_bytes_be("SN_GOERLI".as_bytes()),
        BigUint::from_str("1536727068981429685321").unwrap()
    );
    assert_eq!(
        "SN_GOERLI".as_bytes(),
        BigUint::from_str("1536727068981429685321").unwrap().to_bytes_be()
    );
    assert_eq!(
        "SN_GOERLI",
        String::from_utf8_lossy(
            &BigUint::from_str("1536727068981429685321").unwrap().to_bytes_be()
        )
        .to_string()
    );

    assert_eq!(
        BigUint::from_bytes_be("SN_GOERLI2".as_bytes()),
        BigUint::from_str("393402129659245999442226").unwrap()
    );
    assert_eq!(
        "SN_GOERLI2".as_bytes(),
        BigUint::from_str("393402129659245999442226").unwrap().to_bytes_be()
    );
    assert_eq!(
        "SN_GOERLI2",
        String::from_utf8_lossy(
            &BigUint::from_str("393402129659245999442226").unwrap().to_bytes_be()
        )
        .to_string()
    );

    assert_eq!(
        BigUint::from_bytes_be("PRIVATE_SN_POTC_GOERLI".as_bytes()),
        BigUint::from_str("30051815346679357534098361596796215352075404222549065").unwrap()
    );
    assert_eq!(
        "PRIVATE_SN_POTC_GOERLI".as_bytes(),
        BigUint::from_str("30051815346679357534098361596796215352075404222549065")
            .unwrap()
            .to_bytes_be()
    );
    assert_eq!(
        "PRIVATE_SN_POTC_GOERLI",
        String::from_utf8_lossy(
            &BigUint::from_str("30051815346679357534098361596796215352075404222549065")
                .unwrap()
                .to_bytes_be()
        )
        .to_string()
    );
}
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/312#-:-NPSbA_x4gacUJoZPM_D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
