### PR TITLE
Add `validate_tx` to `Transaction` API

### PR DESCRIPTION
**Pull request by giladchase**
This will be used by gateway APIs that wish to validate directly from the gateway.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: all files reviewed, 8 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQwjqF7I5692_3RZRP:-NdQwjqF7I5692_3RZRQ:b-h1p95x) ([raw file](https://github.com/starkware-libs/blockifier/blob/0959c45f18a81501726bb1e432cd8bb334620a36/crates/blockifier/src/transaction/account_transaction.rs#L121)):*
> ```XML
>     }
> 
>     pub fn validate_tx(
> ```

Only moving, since now `pub`lic?



_Code quote:_
```XML
pub fn validate_tx
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQx2wh62cFN4cjHEoL:-NdQx2wh62cFN4cjHEoM:b-ascs1f) ([raw file](https://github.com/starkware-libs/blockifier/blob/0959c45f18a81501726bb1e432cd8bb334620a36/crates/blockifier/src/transaction/transaction_execution.rs#L88)):*
> ```XML
>     }
> 
>     pub fn validate_tx(
> ```

Please add a docstring, explaining that this API is to-be-used for pre-execution (by sequencer) flow.



_Code quote:_
```XML
pub fn validate_tx
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQwxB09iKCf7NqZSd1:-NdQwxB09iKCf7NqZSd2:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0959c45f18a81501726bb1e432cd8bb334620a36/crates/blockifier/src/transaction/transaction_execution.rs#L100)):*
> ```XML
>             }
>             Self::L1HandlerTransaction(_) => {
>                 panic!("L1HandlerTransaction should not be validated here")
> ```





_Suggestion:_
```XML
L1 handlers should not be validated separately, only as part of execution
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxJRh5NIl40qC55jz:-NdQxJRh5NIl40qC55k-:b-xsyk8o) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f125cbadacb37932a46df23289bd8bd84c5c386/crates/native_blockifier/src/transaction_executor.rs#L104)):*
> ```XML
>     ) -> NativeBlockifierResult<Option<CallInfo>> {
>         let tx_type: String = py_enum_name(tx, "tx_type")?;
>         let tx: Transaction = py_tx(&tx_type, tx, raw_contract_class)?;
> ```

Why not only `AccountTransaction` here?



_Code quote:_
```XML
let tx: Transaction
```
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxQ9XCOoA28tpa0Aa:-NdQxQ9XCOoA28tpa0Ab:b-y00awo) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator.rs#L18)):*
> ```XML
> 
> #[pyclass]
> pub struct PyValidator {
> ```

Docstring (see my comment in the first PR for a behavioral phrasing).



_Code quote:_
```XML
pub struct PyValidator
```
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxbSFBs5x412OHZkH:-NdQxbSFBs5x412OHZkI:blf98gm) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator.rs#L77)):*
> ```XML
> 
>     #[pyo3(signature = (tx, raw_contract_class))]
>     pub fn execute(
> ```

Docstring, explain that for deploy account transactions (c-tor) execution is done before validation, and this is why this API is needed here. 



_Code quote:_
```XML
pub fn execute(
```
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxntt6X5IKplQ7uwr:-NdQxntt6X5IKplQ7uws:b-jzzbpj) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator.rs#L122)):*
> ```XML
> 
> // Typing edge case where python genesis block has block number -1.
> pub fn handle_negative_block_number(block_info: &PyAny) -> PyResult<PyBlockInfo> {
> ```

Do we need to repeat this?



_Code quote:_
```XML
pub fn handle_negative_block_number
```
___
*[`crates/native_blockifier/src/gateway/py_validator_test.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxqJ9-IGT-qVKI11v:-NdQxqJ9-IGT-qVKI11w:bukqi4s) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator_test.rs#L1)):*
> ```XML
> 
> ```

Add when tests are added?

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: all files reviewed, 9 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdUgFHn3ySnm3E5ckQv:-NdUgFHn3ySnm3E5ckQw:b-fnrurc) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/blockifier/src/transaction/account_transaction.rs#L121)):*
> ```XML
>     }
> 
>     pub fn validate_tx(
> ```

Consider adding ValidatableTransaction trait (similar to ExecutableTransaction), and implement it for AccountTransaction.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: all files reviewed, 9 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQwjqF7I5692_3RZRP:-Ne3-P7tDSD8RHZIObwR:bm0aqwv) ([raw file](https://github.com/starkware-libs/blockifier/blob/0959c45f18a81501726bb1e432cd8bb334620a36/crates/blockifier/src/transaction/account_transaction.rs#L121)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Only moving, since now `pub`lic?
</blockquote></details>

Exactly, no other changes.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdUgFHn3ySnm3E5ckQv:-Ne3WszU1pp6SSgaptiz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/blockifier/src/transaction/account_transaction.rs#L121)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider adding ValidatableTransaction trait (similar to ExecutableTransaction), and implement it for AccountTransaction.
</blockquote></details>

Done.

**Review by elintul — COMMENTED** [review]
> Reviewed 7 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQx2wh62cFN4cjHEoL:-Ne3YZoV6OIpP-aZD_kl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0959c45f18a81501726bb1e432cd8bb334620a36/crates/blockifier/src/transaction/transaction_execution.rs#L88)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please add a docstring, explaining that this API is to-be-used for pre-execution (by sequencer) flow.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxJRh5NIl40qC55jz:-Ne3Z6bz1WJzuukCESaf:bq6rift) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f125cbadacb37932a46df23289bd8bd84c5c386/crates/native_blockifier/src/transaction_executor.rs#L104)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not only `AccountTransaction` here?
</blockquote></details>

`py_tx` doesn't support it :( technically i can add a `py_account_tx` and use that instead of `py_tx`, but that'd extend the `py_X` API :sweat_smile:, we want that?

I added a downcast of sorts using let-else for now, and removed the trait impl from `Transaction`, so that it is only available for `AccountTransaction`.
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxQ9XCOoA28tpa0Aa:-Ne3b8NyEi4q1piO9eOo:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Docstring (see my comment in the first PR for a behavioral phrasing).
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxbSFBs5x412OHZkH:-Ne3cUo61IvR3Fc8nRxE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator.rs#L77)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Docstring, explain that for deploy account transactions (c-tor) execution is done before validation, and this is why this API is needed here.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxntt6X5IKplQ7uwr:-Ne3ckYcAUcFPQ3d12XU:b-cfv0ht) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator.rs#L122)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we need to repeat this?
</blockquote></details>

WDYM? Repeat where?
I needed this here because the genesis can be a valid input for this function (when validating the first non-genesisi block)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/native_blockifier/src/gateway/py_validator_test.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxqJ9-IGT-qVKI11v:-NeJ_j7M4QQ3avpC4dfn:b-bmm435) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator_test.rs#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add when tests are added?
</blockquote></details>

Once we decide on which reader to use and get rid of the `unimplemented!` above, is it ok to put back the PythonReader?

**Review by elintul — DISMISSED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxntt6X5IKplQ7uwr:-NeQwQx_E_ArV4-DwEn-:brfedk5) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator.rs#L122)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

WDYM? Repeat where?
I needed this here because the genesis can be a valid input for this function (when validating the first non-genesisi block)
</blockquote></details>

Consider sharing this code.
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 18 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NeQwGxC30NhX0yFHBwC:-NeQwGxC30NhX0yFHBwD:b-hcp0q2) ([raw file](https://github.com/starkware-libs/blockifier/blob/7c47290fc6233f2afe174b86c6cc136c6e247c7e/crates/native_blockifier/src/gateway/py_validator.rs#L18)):*
> ```XML
> 
> #[pyclass]
> /// Manages transaction validation for pre-execution flows, often used in gateway services.
> ```

I would refrain from mentioning other components.



_Code quote:_
```XML
, often used in gateway services.
```
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 80 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NeQvaPP2BEe9As6SkP8:-NeQvaPP2BEe9As6SkP9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7c47290fc6233f2afe174b86c6cc136c6e247c7e/crates/native_blockifier/src/gateway/py_validator.rs#L80)):*
> ```XML
>     /// Applicable solely to `deploy account` transactions. These transaction's constructor
>     /// generally requires execution of the constructor before they can be validated. For all other
>     /// transaction types, execution is not a prerequisite for validation.
> ```





_Suggestion:_
```XML
    /// Applicable solely to accounא deployment transactions: the execution of the constructor 
    // is required before they can be validated.
```
___
*[`crates/native_blockifier/src/gateway/py_validator_test.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxqJ9-IGT-qVKI11v:-NeQw-k20FHb7ae01QfW:b-u1vy19) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator_test.rs#L1)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Once we decide on which reader to use and get rid of the `unimplemented!` above, is it ok to put back the PythonReader?
</blockquote></details>

Not in this PR.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxntt6X5IKplQ7uwr:-NeaRlGY3thigS6Oe11L:b7v45sk) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator.rs#L122)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider sharing this code.
</blockquote></details>

Oh I get it now, we used to have a similar check in native_blockifier, but we ended up doing the block number bump in python instead.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxntt6X5IKplQ7uwr:-Neb27QhChlZCXpymwGR:bjm6qok) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator.rs#L122)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Oh I get it now, we used to have a similar check in native_blockifier, but we ended up doing the block number bump in python instead.
</blockquote></details>

Can we do the same for validation flow?

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NdQxntt6X5IKplQ7uwr:-NfG4Dzm1ULHyU1tlGYB:b8kjddl) ([raw file](https://github.com/starkware-libs/blockifier/blob/1dd0c4a8943011cd77b2d2fcccc266e3354a2039/crates/native_blockifier/src/gateway/py_validator.rs#L122)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we do the same for validation flow?
</blockquote></details>

Will handle in Python then.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879#-:-NfGKVkx2tRawx1yeEUl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NfKYldz4UQyTbP19zxF:-NfKYldz4UQyTbP19zxG:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/263c7e1f1c1d2c3fa905e5c0ef08e74767128468/crates/native_blockifier/src/gateway/py_validator.rs#L32)):*
> ```XML
> impl PyValidator {
>     #[new]
>     #[pyo3(signature = (general_config, max_recursion_depth ))]
> ```





_Suggestion:_
```XML
#[pyo3(signature = (general_config, max_recursion_depth))]
```
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 59 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NfKYth5DYu2QfxCkF1h:-NfKYth5DYu2QfxCkF1i:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/263c7e1f1c1d2c3fa905e5c0ef08e74767128468/crates/native_blockifier/src/gateway/py_validator.rs#L59)):*
> ```XML
>              executor with it."
>         )
>         // let reader = ToBeDecoded::new(state_reader_proxy);
> ```





_Suggestion:_
```XML
ToBeDecided
```
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 118 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NfKZes-DnN4zRqkYEtD:-NfKZes0ASC2Ooj3slKF:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/263c7e1f1c1d2c3fa905e5c0ef08e74767128468/crates/native_blockifier/src/gateway/py_validator.rs#L118)):*
> ```XML
> 
> impl PyValidator {
>     // TODO replace PapyrusReader with PyStateReader once it's in.
> ```





_Suggestion:_
```XML
TODO:
```
___
*[`crates/native_blockifier/src/gateway/py_validator_test.rs` line 1 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NfKZv_h-rRxvJiOkQEZ:-NfKZv_h-rRxvJiOkQE_:b-gjf6r7) ([raw file](https://github.com/starkware-libs/blockifier/blob/263c7e1f1c1d2c3fa905e5c0ef08e74767128468/crates/native_blockifier/src/gateway/py_validator_test.rs#L1)):*
> ```XML
> 
> ```

Empty test file?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/native_blockifier/src/gateway/py_validator_test.rs` line 1 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NfKZv_h-rRxvJiOkQEZ:-Nfii6pU7_4xJ-I5EE8R:bss4a2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/263c7e1f1c1d2c3fa905e5c0ef08e74767128468/crates/native_blockifier/src/gateway/py_validator_test.rs#L1)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Empty test file?
</blockquote></details>

Removed.
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NfKYldz4UQyTbP19zxF:-NfihyJr3TtQTth29AAT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/263c7e1f1c1d2c3fa905e5c0ef08e74767128468/crates/native_blockifier/src/gateway/py_validator.rs#L32)):*
> ```XML
> impl PyValidator {
>     #[new]
>     #[pyo3(signature = (general_config, max_recursion_depth ))]
> ```

Done.
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 59 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NfKYth5DYu2QfxCkF1h:-Nfii1XS4brVHJPsHPAY:b-ptlcs1) ([raw file](https://github.com/starkware-libs/blockifier/blob/263c7e1f1c1d2c3fa905e5c0ef08e74767128468/crates/native_blockifier/src/gateway/py_validator.rs#L59)):*
> ```XML
>              executor with it."
>         )
>         // let reader = ToBeDecoded::new(state_reader_proxy);
> ```

Removed commented out code altogether.
___
*[`crates/native_blockifier/src/gateway/py_validator.rs` line 118 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/879#-NfKZes-DnN4zRqkYEtD:-Nfii6OeBE3C89eahfFw:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/263c7e1f1c1d2c3fa905e5c0ef08e74767128468/crates/native_blockifier/src/gateway/py_validator.rs#L118)):*
> ```XML
> 
> impl PyValidator {
>     // TODO replace PapyrusReader with PyStateReader once it's in.
> ```

Done.

**Review by elintul — DISMISSED** [review]
> Reviewed 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879#-:-Nfj6fUVAmvyV_nOVTWp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/879)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
