### PR TITLE
Add Global Contract Cache to CachedState

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6J89i2J1WnBTrogQA:-Na6J89i2J1WnBTrogQB:bx0h12g) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L139)):*
> ```XML
> 
>     /// Drains contract-class cache collected during execution and updates the global cache.
>     pub fn update_global_contract_cache(&mut self) {
> ```

I'd like the name to embed the fact that it mutates one of the mappings, perhaps `move_classes_to_global_cache`?



_Code quote:_
```XML
update_global_contract_cache
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6JZfF1fUoeRyt34Gg:-Na6JZfGEmmYJcuw_L57:b-qn49vo) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L143)):*
> ```XML
>             self.global_class_hash_to_class
>                 .lock()
>                 .expect("Global contract cache is poisoned.")
> ```

Can't we use `global_class_hash_to_class` instead?



_Code quote:_
```XML
            self.global_class_hash_to_class
                .lock()
                .expect("Global contract cache is poisoned.")
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6JPzN32L1xuRsq0EJ:-Na6JPzN32L1xuRsq0EK:b58pjfj) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L148)):*
> ```XML
>     }
> 
>     // The global cache can theoretically become poisoned, if a panic occurs in the middle of a
> ```

Haha, :wat:



_Code quote:_
```XML
become poisoned
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6JRsB16Onf-5Yd9k7:-Na6JRsB16Onf-5Yd9k8:bzekso4) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L148)):*
> ```XML
>     }
> 
>     // The global cache can theoretically become poisoned, if a panic occurs in the middle of a
> ```

Start with a present simple tense sentence, describing what the method does.



_Code quote:_
```XML
// The global cache
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6Jjxk3WCOq-elW4RR:-Na6Jjxk3WCOq-elW4RS:bcax9rj) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L223)):*
> ```XML
>             .get(class_hash)
>             .cloned()
>             .or_else(|| self.global_class_hash_to_class().cache_get(class_hash).cloned())
> ```

Explain, please?



_Code quote:_
```XML
            .cloned()
            .or_else(|| self.global_class_hash_to_class().cache_get(class_hash).cloned())
```
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6Jr0h7HhO-NYPMy0F:-Na6Jr0h7HhO-NYPMy0G:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/native_blockifier/src/py_transaction_executor.rs#L135)):*
> ```XML
>         self.state.update_global_contract_cache();
> 
>         PyStateDiff::from(self.state.to_state_diff())
> ```





_Suggestion:_
```XML
        self.state.update_global_contract_cache();
        PyStateDiff::from(self.state.to_state_diff())
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/state/cached_state.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6JZfF1fUoeRyt34Gg:-Na6SgxkAxaW3wpzhNRQ:bx6yl5a) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L143)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can't we use `global_class_hash_to_class` instead?
</blockquote></details>

Done, but it required a separate variable, since otherwise, the &mut of the `drain` classes with the &mut of `global_class_hash_to_class()`. 
___
*[`crates/blockifier/src/state/cached_state.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6JPzN32L1xuRsq0EJ:-Na6Ta4XDsWfnYvN-T3b:betpw6i) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L148)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Haha, :wat:
</blockquote></details>

What rust (and other languages) calls the state of a Mutex that paniced while locked, it becomes invalid and all subsequent `lock`s of it will panic.
___
*[`crates/blockifier/src/state/cached_state.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6JRsB16Onf-5Yd9k7:-Na6V9uGCHK3ubW8wdzj:b-fdifx1) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L148)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Start with a present simple tense sentence, describing what the method does.
</blockquote></details>

Not sure i follow, it was already in PST as far as I know, I rewrote to explain what it does.
___
*[`crates/blockifier/src/state/cached_state.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6Jjxk3WCOq-elW4RR:-Na6WI-X39iHZDeOOQ3p:b-f8sf1p) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L223)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Explain, please?
</blockquote></details>

Added a comment.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6JZfF1fUoeRyt34Gg:-Na6Y85u-mpBikClQCOQ:b-m4iwxt) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L143)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done, but it required a separate variable, since otherwise, the &mut of the `drain` classes with the &mut of `global_class_hash_to_class()`. 
</blockquote></details>

Does the `collect` hurt preformance?

**Review by elintul — DISMISSED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: 8 of 13 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/blockifier/src/state/cached_state.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6JZfF1fUoeRyt34Gg:-NaKSEVL42juBxysEQWk:b-kq0j3s) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L143)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Does the `collect` hurt preformance?
</blockquote></details>

Nope, just using to free up the `drain` iterator that held a `&mut self`, which clashed with `&mut self` in `global_class_hash_to_class()`.

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6JZfF1fUoeRyt34Gg:-NaKemSA1L-_q89hsRns:blznv47) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L143)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Nope, just using to free up the `drain` iterator that held a `&mut self`, which clashed with `&mut self` in `global_class_hash_to_class()`. 
</blockquote></details>

Can you elaborate on how freeing up while iterating the collection doesn't take time?

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/780#-Na6JZfF1fUoeRyt34Gg:-NaLD61W4qKglyvqqh7R:b-oaruyj) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a0c7e70264312fb5ffd41832fc8f46281cd3c07/crates/blockifier/src/state/cached_state.rs#L143)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you elaborate on how freeing up while iterating the collection doesn't take time? 
</blockquote></details>

Oh it takes time, O(<number_of_contracts_in_class_hash_to_class>) but it should be negligible, since there will probably be only a few dozen contracts there (I presume...).
It means that instead of iterating of the entries of `class_hash_to_class` once in order to insert them into the global cache, we iterate over them twice.

The constants should probably also not be too bad, since we're not cloning anything, just moving them from inside class_hash_to_class into the temporary vector created by `collect`.

That being said, if you don't want to iterate over them twice, I can revert adding the collect and put it back to revision `r1`

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780#-:-NaL_wje5HLpsqs8MG2X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/780)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
