### PR TITLE
chore: bump sn-api version

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1908)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1908)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 370 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1908#-NyKeg2k0LO8KZokEviH:-NyKeg2l09cTJb_pYJU_:b-ruksf2) ([raw file](https://github.com/starkware-libs/blockifier/blob/5654345b888e3a8d5a4042f8d33ae921ff419fdf/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L370)):*
> ```XML
>             tx_signature_start_ptr.into(),
>             stark_felt_to_felt(tx_info.transaction_hash().0).into(),
>             Felt252::from_bytes_be(block_context.chain_info.chain_id.to_string().as_bytes()).into(),
> ```

you sure `chain_id.0` was previously equivalent to `chain_id.to_string()`?



_Code quote:_
```XML
chain_id.to_string().as_bytes()
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1908)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 370 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1908#-NyKeg2k0LO8KZokEviH:-NyKoLneBnYvWPCXL0dB:b-h0vtl3) ([raw file](https://github.com/starkware-libs/blockifier/blob/5654345b888e3a8d5a4042f8d33ae921ff419fdf/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L370)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you sure `chain_id.0` was previously equivalent to `chain_id.to_string()`?
</blockquote></details>

The previous `ChainId` was:
pub struct ChainId(pub String);

So yeah, I think it's equivalent.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1908#-:-NyPhYKBC4g8AraFsgPr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1908)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Comment by MohammadNassar1** [comment]
Closing this PR, we decided to use a feature branch instead.

**Pull request closed without merging**
