### PR TITLE
feat: test bouncer in tx executor

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1784)

### CODE REVIEW

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 266 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1784#-Nv_t4baCW1tKJ_jx-qZ:-Nv_t4baCW1tKJ_jx-q_:b-pw4ive) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e9d0127c058ba77f02f37191bf76671cabed4a8/crates/blockifier/src/blockifier/transaction_executor_test.rs#L266)):*
> ```XML
>             true,
>         )
>         .unwrap();
> ```

Now you can adjust the expected strings in the `should_panic` above



_Suggestion:_
```XML
.map_err(|error| panic!("{error:?}: {error}")).unwrap();
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 253 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1784#-Nv_gGgR9pk-Kxw-bHwm:-Nv_gGgS3_avIXoiTUBi:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e9d0127c058ba77f02f37191bf76671cabed4a8/crates/blockifier/src/blockifier/transaction_executor_test.rs#L253)):*
> ```XML
>             ..BouncerConfig::default()
>         },
>     );
> ```





_Suggestion:_
```XML
    let max_events_capacity = 10;
    let TestInitData { state, account_address, contract_address, mut nonce_manager } =
        create_test_init_data(&block_context.chain_info, CairoVersion::Cairo1);

    let mut tx_executor = TransactionExecutor::new(
        state,
        block_context,
        BouncerConfig {
            block_max_capacity: BouncerWeights { n_events: max_events_capacity, ..BouncerWeights::max(false) },
            ..BouncerConfig::default()
        },
    );
```

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1784)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 266 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1784#-Nv_t4baCW1tKJ_jx-qZ:-Nv_vMoN3mBGJGWUlGZu:by19pyi) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e9d0127c058ba77f02f37191bf76671cabed4a8/crates/blockifier/src/blockifier/transaction_executor_test.rs#L266)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Now you can adjust the expected strings in the `should_panic` above
</blockquote></details>

maybe:
`.map_err(|error| panic!("{error:?}: {error}")).ok();`
is better? WDYT? to imply that it can only be an `Ok`.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1784)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 253 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1784#-Nv_gGgR9pk-Kxw-bHwm:-Nv_u5UoAMdBL7Z3Ps3X:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e9d0127c058ba77f02f37191bf76671cabed4a8/crates/blockifier/src/blockifier/transaction_executor_test.rs#L253)):*
> ```XML
>             ..BouncerConfig::default()
>         },
>     );
> ```

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 266 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1784#-Nv_t4baCW1tKJ_jx-qZ:-Nv_u1yH1EB1-lxde57b:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e9d0127c058ba77f02f37191bf76671cabed4a8/crates/blockifier/src/blockifier/transaction_executor_test.rs#L266)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Now you can adjust the expected strings in the `should_panic` above
</blockquote></details>

Done.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1784#-:-NvafMGV7g_fE-wibQcM:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request closed without merging**
