### PR TITLE
fix: balance print in errors

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1986)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1986)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1986#-O-Wb5RG367m8N82d0Yy:-O-Wb5RG367m8N82d0Yz:bwtiot) ([raw file](https://github.com/starkware-libs/blockifier/blob/75ab89dc8e369bd67b3fff330acc8a1012304651/crates/blockifier/src/transaction/errors.rs#L36)):*
> ```XML
>     },
>     #[error("Max fee ({}) exceeds balance ({}).", max_fee.0, balance_to_big_uint(balance_low, balance_high))]
>     MaxFeeExceedsBalance { max_fee: Fee, balance_low: StarkFelt, balance_high: StarkFelt },
> ```

in both of these error variants: change the  balance from two fields to a single BigUint field and create a BigUint when the error is created, no reason to do logic here



_Suggestion:_
```XML
    #[error(
        "L1 gas bounds (max amount: {max_amount}, max price: {max_price}) exceed balance ({}).",
        balance_to_big_uint(balance_low, balance_high)
    )]
    L1GasBoundsExceedBalance {
        max_amount: u64,
        max_price: u128,
        balance: BigUint,
    },
    #[error("Max fee ({}) exceeds balance ({}).", max_fee.0, balance_to_big_uint(balance_low, balance_high))]
    MaxFeeExceedsBalance { max_fee: Fee, balance: BigUint },
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2021 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1986#-O-WYY54Av4xK9M9HNmT:-O-WYY54Av4xK9M9HNmU:btrncxs) ([raw file](https://github.com/starkware-libs/blockifier/blob/75ab89dc8e369bd67b3fff330acc8a1012304651/crates/blockifier/src/transaction/transactions_test.rs#L2021)):*
> ```XML
>     let int = balance_to_big_uint(&StarkFelt::from(16_u64), &StarkFelt::from(1_u64));
>     // 340282366920938463463374607431768211472 = 1 << 128 + 16
>     assert!(format!("{}", int) == "340282366920938463463374607431768211472");
> ```

better IMO



_Suggestion:_
```XML
    assert!(format!("{}", int) == (uint!(u128::MAX) + 17).to_string());
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1986)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1986#-O-Wb5RG367m8N82d0Yy:-O-WtG925Esbhr2p8RkW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/75ab89dc8e369bd67b3fff330acc8a1012304651/crates/blockifier/src/transaction/errors.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in both of these error variants: change the  balance from two fields to a single BigUint field and create a BigUint when the error is created, no reason to do logic here
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2021 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1986#-O-WYY54Av4xK9M9HNmT:-O-Zz9tZ7cdPpdqkbp1t:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/75ab89dc8e369bd67b3fff330acc8a1012304651/crates/blockifier/src/transaction/transactions_test.rs#L2021)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

better IMO
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1986)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2022 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1986#-O-_61_l775y0zxUi7v_:-O-_61_l775y0zxUi7va:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c8298163586e5ebf60a709ecb82ec20a158db256/crates/blockifier/src/transaction/transactions_test.rs#L2022)):*
> ```XML
>     let int = balance_to_big_uint(&StarkFelt::from(16_u64), &StarkFelt::from(1_u64));
>     assert!(
>         format!("{}", int) == format!("{}", (BigUint::from(u128::MAX) + BigUint::from(17_u128)))
> ```





_Suggestion:_
```XML
(BigUint::from(u128::MAX) + BigUint::from(17_u128)).to_string()
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1986)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2022 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1986#-O-_61_l775y0zxUi7v_:-O-_74n3B2Jvmcvok3eN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c8298163586e5ebf60a709ecb82ec20a158db256/crates/blockifier/src/transaction/transactions_test.rs#L2022)):*
> ```XML
>     let int = balance_to_big_uint(&StarkFelt::from(16_u64), &StarkFelt::from(1_u64));
>     assert!(
>         format!("{}", int) == format!("{}", (BigUint::from(u128::MAX) + BigUint::from(17_u128)))
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1986#-:-O-_9i60COXaE-cJeiTL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
