### PR TITLE
test: remove the test util deprecated_create_deploy_test_state

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1600)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1600#-NroovBNCcMbDsZUyt-P:-NroovBOAaV4dlx9qeg3:b-ywijz7) ([raw file](https://github.com/starkware-libs/blockifier/blob/0737146c204e3aededda5b625629fb7a4223268e/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L304)):*
> ```XML
>     calldata.push(stark_felt!(if deploy_from_zero_positive_flow { 0_u8 } else { 2_u8 }));
>     Calldata(calldata.into())
> }
> ```

move to test utils: https://github.com/starkware-libs/blockifier/blob/44125355d77c5eaa2d980aa45891f05b24078b8b/crates/blockifier/src/test_utils.rs#L228-L229



_Code quote:_
```XML
fn calldata_for_deploy_test(
    class_hash: ClassHash,
    constructor_calldata: &Vec<StarkFelt>,
    deploy_from_zero_positive_flow: bool,
) -> Calldata {
    let mut calldata = Vec::new();
    calldata.extend(vec![
        class_hash.0,                     // Class hash.
        ContractAddressSalt::default().0, // Contract_address_salt.
    ]);
    calldata.push(stark_felt!(u8::try_from(constructor_calldata.len()).unwrap()));
    calldata.extend(constructor_calldata);
    calldata.push(stark_felt!(if deploy_from_zero_positive_flow { 0_u8 } else { 2_u8 }));
    Calldata(calldata.into())
}
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1600#-NroovBNCcMbDsZUyt-P:-NrpEenM6-Zt_4kRB46n:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0737146c204e3aededda5b625629fb7a4223268e/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L304)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

move to test utils: https://github.com/starkware-libs/blockifier/blob/44125355d77c5eaa2d980aa45891f05b24078b8b/crates/blockifier/src/test_utils.rs#L228-L229
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1600)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 249 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1600#-NrpOs1x1ToMTnBRy9CD:-NrpOs1x1ToMTnBRy9CE:bf6xj2d) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e377c4be20e1d57fe8a074f78e451983e86f170/crates/blockifier/src/test_utils.rs#L249)):*
> ```XML
>         ContractAddressSalt::default().0, // Contract_address_salt.
>     ]);
>     calldata.push(stark_felt!(u8::try_from(constructor_calldata.len()).unwrap()));
> ```

why not in the extend?



_Suggestion:_
```XML
    calldata.extend(vec![
        class_hash.0,                     // Class hash.
        ContractAddressSalt::default().0, // Contract_address_salt.
        stark_felt!(u8::try_from(constructor_calldata.len()).unwrap()),
    ]);
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 304 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1600#-NrpPRAj1oOtTEDUVaUl:-NrpPRAj1oOtTEDUVaUm:b-5ptd22) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e377c4be20e1d57fe8a074f78e451983e86f170/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L304)):*
> ```XML
>         "Invalid input: {:}",
>         "constructor_calldata; Cannot pass calldata to a contract with no constructor.",
>     ))
> ```

why `format!`?



_Suggestion:_
```XML
    Some(
        "Invalid input: constructor_calldata; Cannot pass calldata to a contract with no constructor.",
    )
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1600)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1600)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 249 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1600#-NrpOs1x1ToMTnBRy9CD:-NrpUhhE3ybElERrNUH6:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e377c4be20e1d57fe8a074f78e451983e86f170/crates/blockifier/src/test_utils.rs#L249)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not in the extend?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 304 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1600#-NrpPRAj1oOtTEDUVaUl:-NrpTy8i1dok8IM08e7-:bjmpdf) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e377c4be20e1d57fe8a074f78e451983e86f170/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L304)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why `format!`?
</blockquote></details>

Done.
(The line is over 100 chars - even when aligned to most left).

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1600)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 249 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1600#-NrpWJLu23lOMiByQVm0:-NrpWJLu23lOMiByQVm1:bisrppi) ([raw file](https://github.com/starkware-libs/blockifier/blob/da5dfdc6eba1d772565afc2c95d12077563d3f72/crates/blockifier/src/test_utils.rs#L249)):*
> ```XML
>         ContractAddressSalt::default().0, // Contract_address_salt.
>         stark_felt!(u8::try_from(constructor_calldata.len()).unwrap()), /* Constructor calldata
>                                            * len. */
> ```

either fix the third comment better than the auto-formatter did, or remove all of them (I think it's clear from the code what each felt is)



_Suggestion:_
```XML
        class_hash.0,
        ContractAddressSalt::default().0,
        stark_felt!(u8::try_from(constructor_calldata.len()).unwrap()),
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1600#-:-NrpaNWZCb-4ylIuqXXo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1600)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 249 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1600#-NrpWJLu23lOMiByQVm0:-Nrq4T6f5Bv74JmfmYO6:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/da5dfdc6eba1d772565afc2c95d12077563d3f72/crates/blockifier/src/test_utils.rs#L249)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

either fix the third comment better than the auto-formatter did, or remove all of them (I think it's clear from the code what each felt is)
</blockquote></details>

Done.

**Pull request merged**
