### PR TITLE
test: regression test versioned constants deserialization

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1743)

### CODE REVIEW

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1743)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 329 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1743#-NuNN0b0ESYuxkQgH6kG:-NuNN0b0ESYuxkQgH6kH:b-sufrio) ([raw file](https://github.com/starkware-libs/blockifier/blob/50d32caff9a0080f311f065e710e58fc23f5a81c/crates/blockifier/resources/versioned_constants_13_0.json#L329)):*
> ```JSON
>                 },
>                 "n_memory_holes": 40,
>                 "n_steps": 594
> ```

I recommend a design review on this significant decision, potentially with Lior, if he's available. 

Modifying previously released `versioned_constants_13_0.json` files could confuse users and may not scale well with future updates. Additionally, if we proceed with this proposal, reverting [this pull request](https://github.com/starkware-libs/blockifier/pull/1523) is necessary, as it becomes redundant. 

To be clear, the proposal here might possibly be our best option, but I suggest the review to make sure our approach is both maintainable and user-friendly.
(Doing what we did in the linked PR, for example, is very user-friendly but very not scalable I think.)
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1743#-NuNLzTd37wYOFYxJs46:-NuNLzTd37wYOFYxJs47:b-h3bf) ([raw file](https://github.com/starkware-libs/blockifier/blob/50d32caff9a0080f311f065e710e58fc23f5a81c/crates/blockifier/src/versioned_constants_test.rs#L202)):*
> ```XML
>     let files = glob(format!("{}/resources/*.json", env!("CARGO_MANIFEST_DIR")).as_str()).unwrap();
>     for file in files.map(Result::unwrap) {
>         serde_json::from_str::<VersionedConstants>(&read_to_string(file.clone()).unwrap())
> ```

Saves the creating a temp string



_Suggestion:_
```XML
        serde_json::from_reader::<_, VersionedConstants>(&fs::File::open(&file).unwrap())
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1743)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 329 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1743#-NuNN0b0ESYuxkQgH6kG:-NuNV43F24znPSh-XPE-:bxzmlkh) ([raw file](https://github.com/starkware-libs/blockifier/blob/50d32caff9a0080f311f065e710e58fc23f5a81c/crates/blockifier/resources/versioned_constants_13_0.json#L329)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I recommend a design review on this significant decision, potentially with Lior, if he's available. 

Modifying previously released `versioned_constants_13_0.json` files could confuse users and may not scale well with future updates. Additionally, if we proceed with this proposal, reverting [this pull request](https://github.com/starkware-libs/blockifier/pull/1523) is necessary, as it becomes redundant. 

To be clear, the proposal here might possibly be our best option, but I suggest the review to make sure our approach is both maintainable and user-friendly.
(Doing what we did in the linked PR, for example, is very user-friendly but very not scalable I think.)
</blockquote></details>

1. Reverting the linked PR is not actually necessary... although it would be a good idea (if my way is the way we go).
2. This is not a modification, per se, of the 0.13.0 constants: the 0.13.0 are intact and unchanged *on the version branch they were released from*.
3. If a user wants to use old constants on a new blockifier release, IMO an explicit JSON that can be properly deserialized is clearer than fancy default loading code (especially after maintaining said feature for many versions...), but I'll talk to Lior.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1743#-NuNLzTd37wYOFYxJs46:-NuNkFA797Nb73jfPg7j:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/50d32caff9a0080f311f065e710e58fc23f5a81c/crates/blockifier/src/versioned_constants_test.rs#L202)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Saves the creating a temp string
</blockquote></details>

Done.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1743)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 329 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1743#-NuNN0b0ESYuxkQgH6kG:-NuNu6JV9l599_oR142z:b7c10tu) ([raw file](https://github.com/starkware-libs/blockifier/blob/50d32caff9a0080f311f065e710e58fc23f5a81c/crates/blockifier/resources/versioned_constants_13_0.json#L329)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. Reverting the linked PR is not actually necessary... although it would be a good idea (if my way is the way we go).
2. This is not a modification, per se, of the 0.13.0 constants: the 0.13.0 are intact and unchanged *on the version branch they were released from*.
3. If a user wants to use old constants on a new blockifier release, IMO an explicit JSON that can be properly deserialized is clearer than fancy default loading code (especially after maintaining said feature for many versions...), but I'll talk to Lior.
</blockquote></details>

1. After your code is merged it'll be effectively dead code.
2. Ya i meant modification of the format of the file, but of course the user can't know that unless they review it themselves.
3. I agree, i hope there's a better solution out there  :pleading_face: 

Eitherway, i hear that Lior LGTMed, so unblocking.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1743)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 334 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1743#-NuOpesa3QloptHtTjPL:-NuOpesa3QloptHtTjPM:b-2xeszs) ([raw file](https://github.com/starkware-libs/blockifier/blob/29736cfded10e93abfea245ed1672a3b1b6e21d2/crates/blockifier/resources/versioned_constants_13_0.json#L334)):*
> ```JSON
>                 "n_steps": 84,
>                 "builtin_instance_counter": {},
>                 "n_memory_holes": 0
> ```

Why not sorted?



_Code quote:_
```JSON
                "n_steps": 84,
                "builtin_instance_counter": {},
                "n_memory_holes": 0
```
___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 435 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1743#-NuOpuif4a6WfD8NlMKH:-NuOpuif4a6WfD8NlMKI:b2nhexc) ([raw file](https://github.com/starkware-libs/blockifier/blob/29736cfded10e93abfea245ed1672a3b1b6e21d2/crates/blockifier/resources/versioned_constants_13_0.json#L435)):*
> ```JSON
>                         },
>                         "n_memory_holes": 0,
>                         "n_steps": 3628
> ```

Fix



_Code quote:_
```JSON
                        "builtin_instance_counter": {
                            "pedersen_builtin": 23,
                            "range_check_builtin": 83
                        },
                        "n_memory_holes": 0,
                        "n_steps": 3628
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1743)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 334 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1743#-NuOpesa3QloptHtTjPL:-NuP5N1D-PIdC6rmuXhC:b-pcaz0p) ([raw file](https://github.com/starkware-libs/blockifier/blob/29736cfded10e93abfea245ed1672a3b1b6e21d2/crates/blockifier/resources/versioned_constants_13_0.json#L334)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not sorted?
</blockquote></details>

reordered lines while investigating deserialization error; fixed.
___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 435 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1743#-NuOpuif4a6WfD8NlMKH:-NuP5WBRELMWkhh3iK88:bgb8z0j) ([raw file](https://github.com/starkware-libs/blockifier/blob/29736cfded10e93abfea245ed1672a3b1b6e21d2/crates/blockifier/resources/versioned_constants_13_0.json#L435)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Fix
</blockquote></details>

whoops... good catch

**Pull request merged**
