### PR TITLE
Macrofiy From<InvokeVX> for Invoke

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/948)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/948#-:-NfkCv_H7Hzy1-BCMt86:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/948)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/948)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/948)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/948)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
