### PR TITLE
test: use FeatureContract in create_test_state and tests which uses it

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1556)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1556)* status: all files reviewed, 5 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 538 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5eqGa6BKURh7cWGCg:-Nr5eqGa6BKURh7cWGCh:b-qd0a7e) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L538)):*
> ```XML
>     let mut state = test_state(chain_info, BALANCE, &[(test_contract, 1)]);
>     let inner_entry_point_selector = selector_from_name("assert_eq");
>     let test_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
> ```

duplicated line
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 568 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5ev-SEtOmLYbt5Igu:-Nr5ev-T37LHD8l7ua1T:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L568)):*
> ```XML
>     let outer_entry_point_selector = selector_from_name("test_library_call");
>     let inner_entry_point_selector = selector_from_name("test_storage_read_write");
>     let test_class_hash = FeatureContract::TestContract(CairoVersion::Cairo1).get_class_hash();
> ```





_Suggestion:_
```XML
let test_class_hash = test_contract.get_class_hash();
```
___
*[`crates/blockifier/src/test_utils/cached_state.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5f8038Ze9XAN15Ssh:-Nr5f8038Ze9XAN15Ssi:bhz6sxk) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/test_utils/cached_state.rs#L42)):*
> ```XML
>     .map(|contract| (contract, 1));
>     test_state(chain_info, BALANCE, &test_contracts)
> }
> ```

Why do you change `create_test_state`? I see it's usages are deleted; I expect we will want to eventually delete this function entirely, not maintain it



_Code quote:_
```XML
pub fn create_test_state() -> CachedState<DictStateReader> {
    let chain_info = &ChainInfo::create_for_testing();
    let test_contracts = [
        FeatureContract::TestContract(CairoVersion::Cairo1),
        FeatureContract::LegacyTestContract,
        FeatureContract::Empty(CairoVersion::Cairo1),
    ]
    .map(|contract| (contract, 1));
    test_state(chain_info, BALANCE, &test_contracts)
}
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1644 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5fJbv2QSltpEndhVx:-Nr5fJbv2QSltpEndhVy:b-gd5k7z) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/transaction/transactions_test.rs#L1644)):*
> ```XML
>             version: TransactionVersion::ZERO,
>             nonce: Nonce::default(),
>             contract_address: FeatureContract::TestContract(CairoVersion::Cairo1)
> ```

no; you have a test util here that implicitly constructs a specific (versioned) contract. Either pass the cairo version or the contract itself as input



_Code quote:_
```XML
FeatureContract::TestContract(CairoVersion::Cairo1)
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1671 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5fPA9BSoTz1WAdEzq:-Nr5fPA9BSoTz1WAdEzr:b-k6k0k2) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/transaction/transactions_test.rs#L1671)):*
> ```XML
>     // Build the expected call info.
>     let accessed_storage_key = StorageKey::try_from(key).unwrap();
>     let test_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
> ```

duplicate line

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1556)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 538 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5eqGa6BKURh7cWGCg:-Nr646e04nNAYeastG0s:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L538)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

duplicated line
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 568 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5ev-SEtOmLYbt5Igu:-Nr64FhE5iaqFdX3fbzd:bele1qb) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L568)):*
> ```XML
>     let outer_entry_point_selector = selector_from_name("test_library_call");
>     let inner_entry_point_selector = selector_from_name("test_storage_read_write");
>     let test_class_hash = FeatureContract::TestContract(CairoVersion::Cairo1).get_class_hash();
> ```

Some embarrassing comments here...
___
*[`crates/blockifier/src/test_utils/cached_state.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5f8038Ze9XAN15Ssh:-Nr64SxG-Dw2YkrbEvSL:b-qzvogn) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/test_utils/cached_state.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Why do you change `create_test_state`? I see it's usages are deleted; I expect we will want to eventually delete this function entirely, not maintain it
</blockquote></details>

It is not used anywhere now, but I thought we will use it in the feature in some  way, won't we? I'll just remove it ATM
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1644 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5fJbv2QSltpEndhVx:-Nr65Fi753KrVTBQhj8j:b-3mgfol) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/transaction/transactions_test.rs#L1644)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no; you have a test util here that implicitly constructs a specific (versioned) contract. Either pass the cairo version or the contract itself as input
</blockquote></details>

OK, I get you now - but it seems this is a helper function for a single test with version 1, so I don't think it's needed here. WDYT?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1671 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5fPA9BSoTz1WAdEzq:-Nr65Vor5Pvm3pBnduiP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/transaction/transactions_test.rs#L1671)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

duplicate line
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1556)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 568 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5ev-SEtOmLYbt5Igu:-Nr68BXM2szW_mAfNbe4:b-kkwju5) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L568)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Some embarrassing comments here...
</blockquote></details>

don't worry it's just a highly visible repo
___
*[`crates/blockifier/src/test_utils/cached_state.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5f8038Ze9XAN15Ssh:-Nr68Ikx9MvaUl2oKQzj:be6husl) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/test_utils/cached_state.rs#L42)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

It is not used anywhere now, but I thought we will use it in the feature in some  way, won't we? I'll just remove it ATM
</blockquote></details>

we won't; we'll write something new if we want to, later
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1644 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5fJbv2QSltpEndhVx:-Nr68R4C25vdiyty5dcs:b-6qduoe) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/transaction/transactions_test.rs#L1644)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

OK, I get you now - but it seems this is a helper function for a single test with version 1, so I don't think it's needed here. WDYT?
</blockquote></details>

if it's only used once, I would inline the code

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1556)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1644 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5fJbv2QSltpEndhVx:-Nr6twL17d2u2Zeeqlfn:b-av3eoq) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/transaction/transactions_test.rs#L1644)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if it's only used once, I would inline the code
</blockquote></details>

Used twice in a single test

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1556)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1644 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5fJbv2QSltpEndhVx:-Nr9rg2lDw1uVS3fVm5Q:bg42fly) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/transaction/transactions_test.rs#L1644)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Used twice in a single test
</blockquote></details>

so the feature contract or cairo version needs to be input... this is a test util, nothing to prevent it's future use in other tests

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1556)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1644 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-Nr5fJbv2QSltpEndhVx:-NrB0Ihm5xDdJtTC2nPN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/20a53e167db74fe89a17d5c2e6f636007bac5e61/crates/blockifier/src/transaction/transactions_test.rs#L1644)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so the feature contract or cairo version needs to be input... this is a test util, nothing to prevent it's future use in other tests
</blockquote></details>

Done.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1556)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1667 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-NrB0TKY40UtHB3I0lr1:-NrB1t2A0PQBeJVqsEkM:bb77ucv) ([raw file](https://github.com/starkware-libs/blockifier/blob/42cc726d166ca0745c296071c80346065e058ffe/crates/blockifier/src/transaction/transactions_test.rs#L1667)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is now coupled, right?
</blockquote></details>

Yep.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1747 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1556#-NrB0YIx41bpYxyKzq_h:-NrB2-pw-yCOfB6xs-5L:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/42cc726d166ca0745c296071c80346065e058ffe/crates/blockifier/src/transaction/transactions_test.rs#L1747)):*
> ```XML
> 
>     // Negative flow: not enough fee paid on L1.
>     let tx_no_fee = l1_handler_tx(&calldata, Fee(0), CairoVersion::Cairo1);
> ```

Done.

**Pull request merged**
