### PR TITLE
Use macros, reduce boilerplate

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1203)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1203)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1203#-Nkj4k9nAocM1rlIr71U:-NkjAxMh9jNM0eDPRHRN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f0116031cf47886f387f2b0a6004cf04bbed2df/crates/blockifier/src/test_utils/declare.rs#L57)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This will save us from having to import it when using the macro.
</blockquote></details>

Done.

**Review by giladchase — DISMISSED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1203#-:-Nko_Lys1K3Oa3CuFwbp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by giladchase — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
