### PR TITLE
Execute general transactions.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/255)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/255)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/objects.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2lAgrETR1XF_PNTDa:-NN2lAgrETR1XF_PNTDb:b-uzv1yu) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee2648646dacfd1b06b9dc0c0d8244f12fc424b9/crates/blockifier/src/transaction/objects.rs#L27)):*
> ```XML
>     /// Transaction validation call info.
>     pub validate_call_info: CallInfo,
>     /// Transaction execution call info; trivial for `Declare`.
> ```

Perhaps restore and add "; trivial for `L1Hanlder`." for the validate and fee call info.?



_Code quote:_
```XML
; trivial for `Declare`.
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2kdxsALSD8gvnT_0D:-NN2kdxsALSD8gvnT_0E:b-ferw3c) ([raw file](https://github.com/starkware-libs/blockifier/blob/34e516019b6246a604a289f4be91522f776ea206/crates/blockifier/src/transaction/transaction_execution.rs#L26)):*
> ```XML
>             Self::AccountTransaction(account_tx) => account_tx.execute(state, block_context),
>             Self::L1HandlerTransaction(tx) => {
>                 let account_tx_context = AccountTransactionContext {
> ```

Weird it's called account context, since it's not an account transaction.
Perhaps the whole struct should be renamed, but not now.



_Suggestion:_
```XML
let tx_context
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2lpZK7Hk1cTQWj0tS:-NN2lpZLC8MGQSXM9k_a:b3reeiy) ([raw file](https://github.com/starkware-libs/blockifier/blob/34e516019b6246a604a289f4be91522f776ea206/crates/blockifier/src/transaction/transactions_test.rs#L229)):*
> ```XML
>     let expected_return_result_retdata = Retdata(expected_return_result_calldata);
>     let expected_execute_call_info = Some(CallInfo {
>         call: expected_execute_call,
> ```

Make the `expected_*_call_info`s functions return `Option<CallInfo>`, instead.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/255)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/objects.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2lAgrETR1XF_PNTDa:-NN5myNr2eQvEdRu0Wvx:b9532ns) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee2648646dacfd1b06b9dc0c0d8244f12fc424b9/crates/blockifier/src/transaction/objects.rs#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps restore and add "; trivial for `L1Hanlder`." for the validate and fee call info.?
</blockquote></details>

Sure. How about `None` instead of trivial?
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2kdxsALSD8gvnT_0D:-NN5kGNpEYWGATAh39TN:b-lry5ta) ([raw file](https://github.com/starkware-libs/blockifier/blob/34e516019b6246a604a289f4be91522f776ea206/crates/blockifier/src/transaction/transaction_execution.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Weird it's called account context, since it's not an account transaction.
Perhaps the whole struct should be renamed, but not now.
</blockquote></details>

I agree. Next PR?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2lpZK7Hk1cTQWj0tS:-NN5llTA-lEtwm5xyo6a:b-i21bbo) ([raw file](https://github.com/starkware-libs/blockifier/blob/34e516019b6246a604a289f4be91522f776ea206/crates/blockifier/src/transaction/transactions_test.rs#L229)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Make the `expected_*_call_info`s functions return `Option<CallInfo>`, instead.
</blockquote></details>

Thanks. Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/255)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/objects.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2lAgrETR1XF_PNTDa:-NN5zYS-A_UrUwIBbzyE:b-gtqsos) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee2648646dacfd1b06b9dc0c0d8244f12fc424b9/crates/blockifier/src/transaction/objects.rs#L27)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Sure. How about `None` instead of trivial?
</blockquote></details>

Fine too. Why `[]`?
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2kdxsALSD8gvnT_0D:-NN5zct168DOLfw6z-h7:b-lbojd7) ([raw file](https://github.com/starkware-libs/blockifier/blob/34e516019b6246a604a289f4be91522f776ea206/crates/blockifier/src/transaction/transaction_execution.rs#L26)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I agree. Next PR?
</blockquote></details>

Can you rename the variable here to `tx_context`?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN5zTtt7cFaa8jl4ASx:-NN5zTtt7cFaa8jl4ASy:bdk7ku9) ([raw file](https://github.com/starkware-libs/blockifier/blob/b15778325391260c82e233aed9dc52c4b7318149/crates/blockifier/src/transaction/transactions_test.rs#L225)):*
> ```XML
>     let expected_execute_call = CallEntryPoint {
>         entry_point_selector: selector_from_name(constants::EXECUTE_ENTRY_POINT_NAME),
>         ..expected_validate_call_info.as_ref().unwrap().call.clone()
> ```

Why is this needed?



_Code quote:_
```XML
as_ref()
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/255#-:-NN64-FD7pQPbbCok2QC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/255)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/objects.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2lAgrETR1XF_PNTDa:-NN643YjCAgqJ86v4DbI:bvtimvs) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee2648646dacfd1b06b9dc0c0d8244f12fc424b9/crates/blockifier/src/transaction/objects.rs#L27)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Using `[]` around types in doc strings marks them as a type, and you can click it as a link to it.
</blockquote></details>

Cool. Maybe for the transactions too?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/255)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/objects.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2lAgrETR1XF_PNTDa:-NN66F7o3d6OQuge36RF:b-o5h5v2) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee2648646dacfd1b06b9dc0c0d8244f12fc424b9/crates/blockifier/src/transaction/objects.rs#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Cool. Maybe for the transactions too?
</blockquote></details>

Done, needed to import this way. WDYT?

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/255)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/objects.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2lAgrETR1XF_PNTDa:-NN6DVZD4IOrPCqe1y8K:b1lud8z) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee2648646dacfd1b06b9dc0c0d8244f12fc424b9/crates/blockifier/src/transaction/objects.rs#L27)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done, needed to import this way. WDYT?
</blockquote></details>

It's too long... :(
Let's revert.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/255)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/objects.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/255#-NN2lAgrETR1XF_PNTDa:-NN6E-iF6r0iC9yEJEOO:b2nhk7b) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee2648646dacfd1b06b9dc0c0d8244f12fc424b9/crates/blockifier/src/transaction/objects.rs#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's too long... :(
Let's revert.
</blockquote></details>

NP.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
