### PR TITLE
chore: run feature tests in the ci

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1657)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1657)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`.github/workflows/ci.yml` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1657#-Nsqf_SS6TVyT8X9cWI2:-Nsqf_ST5dmohq8FiqRu:b-g8ms8v) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9743b31b03346305985e84f81e9fbceb70e83f4/.github/workflows/ci.yml#L79)):*
> ```YAML
>       - run: cargo test
> 
>   run-feature-tests:
> ```

Sounds too similar to the cairo feature test (I initially thought that was that when looking in the actions)



_Suggestion:_
```YAML
run-concurrency-tests:
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1657)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1657#-NsqjuFV7bW6K-5Ev5DF:-NsqjuFV7bW6K-5Ev5DG:b3i7kfm) (no related file):*
Base branch was updated to `main`.

___
___
*[`.github/workflows/ci.yml` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1657#-Nsqf_SS6TVyT8X9cWI2:-NsqjBKl-lJ7kz4liUBD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9743b31b03346305985e84f81e9fbceb70e83f4/.github/workflows/ci.yml#L79)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Sounds too similar to the cairo feature test (I initially thought that was that when looking in the actions)
</blockquote></details>

Done.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1657#-:-NsvTNTh3G7g3KgWvFj5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1657#-:-NswFtam-xX-EF3MSmdI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Pull request merged**
