### PR TITLE
Update post-execution tests

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1048)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1048)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1048#-Ni9j2Z2CqeqzWPld1Tj:-Ni9j2Z2CqeqzWPld1Tk:bi2s6rx) ([raw file](https://github.com/starkware-libs/blockifier/blob/0dcb4aff50122b6677c3260c9f83c7762c692f9b/crates/blockifier/src/transaction/account_transactions_test.rs#L61)):*
> ```XML
> fn max_resource_bounds() -> ResourceBoundsMapping {
>     let max_amount = u64::try_from(MAX_L1_GAS_AMOUNT)
>         .unwrap_or_else(|_| panic!("MAX_L1_GAS_AMOUNT {MAX_L1_GAS_AMOUNT:?} is too large."));
> ```

Can the const itself be defined as a u64?



_Code quote:_
```XML
    let max_amount = u64::try_from(MAX_L1_GAS_AMOUNT)
        .unwrap_or_else(|_| panic!("MAX_L1_GAS_AMOUNT {MAX_L1_GAS_AMOUNT:?} is too large."));
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1069 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1048#-Ni9fD6sChBWF0rzYsv5:-Ni9fD6sChBWF0rzYsv6:b-4tm1aa) ([raw file](https://github.com/starkware-libs/blockifier/blob/0dcb4aff50122b6677c3260c9f83c7762c692f9b/crates/blockifier/src/transaction/account_transactions_test.rs#L1069)):*
> ```XML
>         } else {
>             &FeeType::Strk
>         });
> ```

Better push setup stuff up to rstest as much as possible, to keep the tests short.
If this repeats a lot we'll wrap it up with some test struct i guess.



_Suggestion:_
```XML
#[case(TransactionVersion::ONE, Eth)]
#[case(TransactionVersion::THREE, Strk)]
fn test_revert_on_overdraft(
    max_fee: Fee,
    max_resource_bounds: ResourceBoundsMapping,
    block_context: BlockContext,
    #[from(create_state)] state: CachedState<DictStateReader>,
    #[case] version: TransactionVersion,
    #[case] fee_type: FeeType
) {
    let fee_token_address =
        block_context.fee_token_addresses.get_by_fee_type(fee_type);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1048)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1069 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1048#-Ni9fD6sChBWF0rzYsv5:-NiEAYOtA4LBofdXMm7D:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0dcb4aff50122b6677c3260c9f83c7762c692f9b/crates/blockifier/src/transaction/account_transactions_test.rs#L1069)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Better push setup stuff up to rstest as much as possible, to keep the tests short.
If this repeats a lot we'll wrap it up with some test struct i guess.
</blockquote></details>

Done.

**Review by giladchase — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware, @noaov1, and @zuphitf)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1048#-:-NiURYTW4nQguE0f93GV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware, @noaov1, and @zuphitf)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware, @noaov1, and @zuphitf)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1048#-:-NiVPqNG8nxSlikWxuDw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware, @noaov1, and @zuphitf)

**Pull request merged**
