### PR TITLE
fix(transaction): remove charge fee flag from the transaction executo…

### PR DESCRIPTION
**Pull request by meship-starkware**
…r execute

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1970)

### CODE REVIEW

**Review by OriStarkware — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1970#-:-Nzw8UpFB-WTI77ma2Ni:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1970)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1970#-Nzx_0cNCB6zJla5znfa:-Nzx_0cOCzGOPk_r0-hH:b-knvnre) ([raw file](https://github.com/starkware-libs/blockifier/blob/47586ffaa95de1713317d35f837c7cb149395d65/crates/blockifier/src/blockifier/transaction_executor.rs#L113)):*
> ```XML
>         &mut self,
>         txs: &[Transaction],
>         charge_fee: bool,
> ```

Can be removed.



_Code quote:_
```XML
        charge_fee: bool,
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1970#-Nzx_Cw7DQQTwZBZCWqw:-Nzx_Cw7DQQTwZBZCWqx:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/47586ffaa95de1713317d35f837c7cb149395d65/crates/blockifier/src/blockifier/transaction_executor.rs#L120)):*
> ```XML
>             txs.chunks(self.config.concurrency_config.chunk_size)
>                 .fold_while(Vec::new(), |mut results, chunk| {
>                     let chunk_results = self.execute_chunk(chunk, charge_fee);
> ```





_Suggestion:_
```XML
 let chunk_results = self.execute_chunk(chunk);
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1970#-Nzx_F7t4dyBIOjCINd9:-Nzx_F7t4dyBIOjCINdA:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/47586ffaa95de1713317d35f837c7cb149395d65/crates/blockifier/src/blockifier/transaction_executor.rs#L137)):*
> ```XML
>         &mut self,
>         _chunk: &[Transaction],
>         _charge_fee: bool,
> ```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1970)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1970#-Nzx_0cNCB6zJla5znfa:-O--WtBB8HREjKMuoHS_:b-8kjny0) ([raw file](https://github.com/starkware-libs/blockifier/blob/47586ffaa95de1713317d35f837c7cb149395d65/crates/blockifier/src/blockifier/transaction_executor.rs#L113)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can be removed.
</blockquote></details>

I think that this requires a python PR

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1970)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1970#-Nzx_0cNCB6zJla5znfa:-O--tBqbDLlnvw2IrVgE:byl3sqb) ([raw file](https://github.com/starkware-libs/blockifier/blob/47586ffaa95de1713317d35f837c7cb149395d65/crates/blockifier/src/blockifier/transaction_executor.rs#L113)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that this requires a python PR
</blockquote></details>

It does not, my bad.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1970)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1970#-Nzx_0cNCB6zJla5znfa:-O-00Hd_CHKgO757Fkb5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/47586ffaa95de1713317d35f837c7cb149395d65/crates/blockifier/src/blockifier/transaction_executor.rs#L113)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It does not, my bad.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1970#-Nzx_Cw7DQQTwZBZCWqw:-O-008Du0oFin9zr-BV0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/47586ffaa95de1713317d35f837c7cb149395d65/crates/blockifier/src/blockifier/transaction_executor.rs#L120)):*
> ```XML
>             txs.chunks(self.config.concurrency_config.chunk_size)
>                 .fold_while(Vec::new(), |mut results, chunk| {
>                     let chunk_results = self.execute_chunk(chunk, charge_fee);
> ```

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1970#-Nzx_F7t4dyBIOjCINd9:-O-008UE88YMvOicjKOa:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/47586ffaa95de1713317d35f837c7cb149395d65/crates/blockifier/src/blockifier/transaction_executor.rs#L137)):*
> ```XML
>         &mut self,
>         _chunk: &[Transaction],
>         _charge_fee: bool,
> ```

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1970#-:-O-06YOj9i-cRRygcTWy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1970)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
