### PR TITLE
refactor(transaction): add v3 txes to versioned_constants

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 164 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqafnF37QUZIz4449jg:-NqafnF37QUZIz4449jh:b-t65vjv) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L164)):*
> ```JSON
>                     "range_check_builtin": 20
>                 },
>                 "n_memory_holes": 0
> ```

Why is the order changed?



_Code quote:_
```JSON
                "n_steps": 760,
                "builtin_instance_counter": {
                    "range_check_builtin": 20
                },
                "n_memory_holes": 0
```
___
*[`crates/blockifier/resources/versioned_constants.json` line 390 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqaeRUh22LUJJmViMFA:-NqaeRUh22LUJJmViMFB:bo97604) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L390)):*
> ```JSON
>                     "n_steps": 2945,
>                     "builtin_instance_counter": {
>                         "pedersen_builtin": 4,
> ```

When do we use the `pedersen_builtin` in V3 transactions?



_Code quote:_
```JSON
                        "pedersen_builtin": 4,
```
___
*[`crates/blockifier/resources/versioned_constants.json` line 415 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqaevoXDeG9DFpxtQZT:-NqaevoXDeG9DFpxtQZU:b-s50752) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L415)):*
> ```JSON
>                     "builtin_instance_counter": {},
>                     "n_memory_holes": 0
>                 },
> ```

Same in the non-deprecated (for now)



_Suggestion:_
```JSON
                "deprecated_calldata_factor": {
                    "n_steps": 21,
                    "builtin_instance_counter": {
                        "pedersen_builtin": 2,
                        "range_check_builtin": 0
                    },
                    "n_memory_holes": 0
                },
```
___
*[`crates/blockifier/resources/versioned_constants.json` line 444 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqafLCQAwSYUUww3Slj:-NqafLCQAwSYUUww3Slk:b-s50752) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L444)):*
> ```JSON
>                     "builtin_instance_counter": {},
>                     "n_memory_holes": 0
>                 },
> ```

Same in the non-deprecated (for now)



_Suggestion:_
```JSON
                "deprecated_calldata_factor": {
                    "builtin_instance_counter": {
                        "pedersen_builtin": 1,
                        "range_check_builtin": 0
                    },
                    "n_memory_holes": 0,
                    "n_steps": 8
                },
```
___
*[`crates/blockifier/resources/versioned_constants.json` line 473 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqafgWY6WKaYwrtbfLN:-NqafgWY6WKaYwrtbfLO:b-s50752) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L473)):*
> ```JSON
>                     "builtin_instance_counter": {},
>                     "n_memory_holes": 0
>                 },
> ```

Same in the non-deprecated (for now)



_Suggestion:_
```JSON
                "deprecated_calldata_factor": {
                    "builtin_instance_counter": {
                        "pedersen_builtin": 1,
                        "range_check_builtin": 0
                    },
                    "n_memory_holes": 0,
                    "n_steps": 13
                },
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 390 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqaeRUh22LUJJmViMFA:-NqvSCqoCtQekGWBxZUv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L390)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When do we use the `pedersen_builtin` in V3 transactions?
</blockquote></details>

Done.
___
*[`crates/blockifier/resources/versioned_constants.json` line 415 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqaevoXDeG9DFpxtQZT:-NqvSDaqEgy-gZGeYNCb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L415)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same in the non-deprecated (for now)
</blockquote></details>

Done.
___
*[`crates/blockifier/resources/versioned_constants.json` line 444 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqafLCQAwSYUUww3Slj:-NqvSE8L8a5jj0__8ZBS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L444)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same in the non-deprecated (for now)
</blockquote></details>

Done.
___
*[`crates/blockifier/resources/versioned_constants.json` line 473 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqafgWY6WKaYwrtbfLN:-NqvSEgiA-YMnidXm5Kg:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L473)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same in the non-deprecated (for now)
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
Python PR? :)

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-:-NqbzKyyDLl9YFQAdJk8:b-uctea7)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 415 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqaevoXDeG9DFpxtQZT:-NqwhQQ_3ycH-eUjBPJH:btxoq5b) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L415)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Change the non-deprecated as well? (in all transactions types)

**Review by meship-starkware — COMMENTED** [review]
https://github.com/starkware-industries/starkware/pull/33588

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-:-Nr59Rtt35fBwK8Nl6U_:b-j5as9x)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 415 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqaevoXDeG9DFpxtQZT:-Nr4xjVv0HttYeFeE37P:b-c1q92o) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L415)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Change the non-deprecated as well? (in all transactions types)
</blockquote></details>

I think it would be better if they stayed empty until we will have the right value for them to show that it is still not finished.
I can assign the same value as the deprecated and add a todo in the Python repo.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 415 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NqaevoXDeG9DFpxtQZT:-NrUiIUm31bigFxAQwxr:b-bge26i) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a38f4258135a782c07b6bd2535b640db905f2b0/crates/blockifier/resources/versioned_constants.json#L415)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think it would be better if they stayed empty until we will have the right value for them to show that it is still not finished.
I can assign the same value as the deprecated and add a todo in the Python repo.
</blockquote></details>

I think it is better to have the same values and add a TODO.
___
*[`crates/blockifier/src/versioned_constants.rs` line 205 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NrV5MoN1L3JblZLSOkZ:-NrV5MoN1L3JblZLSOk_:by8huwl) ([raw file](https://github.com/starkware-libs/blockifier/blob/de2d550055ec6162f9bf65e6a6c7b372e6798f65/crates/blockifier/src/versioned_constants.rs#L205)):*
> ```XML
>     // For each transaction the OS uses a constant amount of VM resources, and an
>     // additional variable amount that depends on the calldata length.
>     execute_txs_inner: HashMap<TransactionType, TxExecutionResources>,
> ```

You may want to consider adding a backward-compatibility here (see `ResourceParamsRaw`).
Better to ask @giladchase :)



_Code quote:_
```XML
execute_txs_inner: HashMap<TransactionType, TxExecutionResources>,
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 205 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NrV5MoN1L3JblZLSOkZ:-Nr_iGMX3nJP02YTH3Hd:b6bk3gw) ([raw file](https://github.com/starkware-libs/blockifier/blob/de2d550055ec6162f9bf65e6a6c7b372e6798f65/crates/blockifier/src/versioned_constants.rs#L205)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You may want to consider adding a backward-compatibility here (see `ResourceParamsRaw`).
Better to ask @giladchase :)
</blockquote></details>

Backwards comp needs design review, you can not worry about this now, we'll worry about it after the design review later.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 205 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NrV5MoN1L3JblZLSOkZ:-NrjpM-u9cIL8iLjlBiR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de2d550055ec6162f9bf65e6a6c7b372e6798f65/crates/blockifier/src/versioned_constants.rs#L205)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Backwards comp needs design review, you can not worry about this now, we'll worry about it after the design review later.
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 526 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-NrkFPMJ4z8w6V-ULu6M:-NrkVjVc2ITTu5JTxVjF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/98edf09d22ea41d0753d999b2c4fcf2a5bae89ee/crates/blockifier/resources/versioned_constants.json#L526)):*
> ```JSON
>                         "builtin_instance_counter": {},
>                         "n_memory_holes": 0
>                     }
> ```

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1500#-Nrnzrmw4nDjDgKUZ547:-Nrnzrmw4nDjDgKUZ548:b-sq45zl) ([raw file](https://github.com/starkware-libs/blockifier/blob/b684db82755227528b6147b51eb8cef63361f5da/crates/blockifier/src/versioned_constants_test.rs#L64)):*
> ```XML
>                         "n_steps": 2839
>                     }
>                 }
> ```

What about `calldata_factor`?



_Code quote:_
```XML
                    "deprecated_resources":{
                        "builtin_instance_counter": {
                            "pedersen_builtin": 16,
                            "range_check_builtin": 63
                        },
                        "n_memory_holes": 0,
                        "n_steps": 2839
                    },
                    "resources": {
                        "builtin_instance_counter": {
                            "pedersen_builtin": 16,
                            "range_check_builtin": 63
                        },
                        "n_memory_holes": 0,
                        "n_steps": 2839
                    }
                }
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1500)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

**Pull request merged**
