### PR TITLE
Update security tests to new infra

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1238)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1238)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ2l6c9uwarLuuIqIm:-NlJ2l6c9uwarLuuIqIn:b-6vzdab) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90e198e42beadcec708b5fe8a68db7b8ef8b81d/crates/blockifier/src/execution/entry_point_test.rs#L205)):*
> ```XML
>         call_type: CallType::Call,
>         initial_gas: constants::INITIAL_GAS_COST,
>     };
> ```

It uses the new util and does not code dup.

Refactor `trivial_external_entry_point` in another PR.



_Suggestion:_
```XML
    let entry_point_call = CallEntryPoint {
        entry_point_selector: selector_from_name(entry_point_name),
        calldata,
        storage_address: FeatureContract::SecurityTests.get_instance_address(0),
        ..trivial_external_entry_point()
    };
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ1Eer1dr2iO_vOGGC:-NlJ1Eer1dr2iO_vOGGD:b-lc3aqh) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90e198e42beadcec708b5fe8a68db7b8ef8b81d/crates/blockifier/src/execution/entry_point_test.rs#L221)):*
> ```XML
>     let security_contract = FeatureContract::SecurityTests;
>     test_state(&block_context, BALANCE, &[(security_contract, 1)])
> }
> ```

It is odd to me that `FeatureContract::SecurityTests` is defined twice. 



_Suggestion:_
```XML
fn run_security_test(
    expected_error: &str,
    entry_point_name: &str,
    calldata: Calldata,
    state: &mut CachedState<DictStateReader>,
) {
    let entry_point_call = CallEntryPoint {
        entry_point_selector: selector_from_name(entry_point_name),
        calldata,
        storage_address: FeatureContract::SecurityTests.get_instance_address(0), // Defined here.
        class_hash: None,
        code_address: Some(
            FeatureContract::TestContract(CairoVersion::Cairo0).get_instance_address(0),
        ),
        entry_point_type: EntryPointType::External,
        caller_address: ContractAddress::default(),
        call_type: CallType::Call,
        initial_gas: constants::INITIAL_GAS_COST,
    };
    let error = match entry_point_call.execute_directly(state) {
        Err(error) => error.to_string(),
        Ok(_) => panic!(
            "Entry point '{entry_point_name}' did not fail! Expected error: {expected_error}"
        ),
    };
    if !error.contains(expected_error) {
        panic!("Expected error: {expected_error}.\nGot: {error}")
    }
}

fn security_test_state() -> CachedState<DictStateReader> {
    let block_context = BlockContext::create_for_testing();
    let security_contract = FeatureContract::SecurityTests; // Defined Here.
    test_state(&block_context, BALANCE, &[(security_contract, 1)])
}
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1238)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1238)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ2l6c9uwarLuuIqIm:-NlJ3cWc3KKJwUVYeFH1:b-sr9f3a) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90e198e42beadcec708b5fe8a68db7b8ef8b81d/crates/blockifier/src/execution/entry_point_test.rs#L205)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It uses the new util and does not code dup.

Refactor `trivial_external_entry_point` in another PR.
</blockquote></details>

it wants to kill this test util!!!
trivial_external_entry_point with *hard coded addresses and class hash* is not good practice IMO. Caller should be explicit about the cairo version at least.
use `Default`, better?
Or do you think the feature contract defs should go into the util?
If so, that means we will need to update all tests that use it, in one go
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ1Eer1dr2iO_vOGGC:-NlJ5QWb8kiRj8w8ERrF:bphcmqr) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90e198e42beadcec708b5fe8a68db7b8ef8b81d/crates/blockifier/src/execution/entry_point_test.rs#L221)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It is odd to me that `FeatureContract::SecurityTests` is defined twice.
</blockquote></details>

Done. Slight refactor to make stuff better

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1238)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ2l6c9uwarLuuIqIm:-NlJ7isc5ZdLMHPSslAs:bp8l7es) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90e198e42beadcec708b5fe8a68db7b8ef8b81d/crates/blockifier/src/execution/entry_point_test.rs#L205)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it wants to kill this test util!!!
trivial_external_entry_point with *hard coded addresses and class hash* is not good practice IMO. Caller should be explicit about the cairo version at least.
use `Default`, better?
Or do you think the feature contract defs should go into the util?
If so, that means we will need to update all tests that use it, in one go
</blockquote></details>

A lot better!

We can consider adding the feature contract defs to the util, but I can see how it is a bad practice.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ1Eer1dr2iO_vOGGC:-NlJ8yMZ5P_oyMFnU_HH:brnkkyc) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90e198e42beadcec708b5fe8a68db7b8ef8b81d/crates/blockifier/src/execution/entry_point_test.rs#L221)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done. Slight refactor to make stuff better
</blockquote></details>

Humm - it is nicer and more self-contained this way.
Too bad we create many instances of state.


How about a test util similar to `security_test_state` (from the first revision of this PR: `r1`) that returns a state and the used `FeatureContract`?
Or maybe it is just the correct way to have it similar to `r1` - where a few instances of `FeatureContract::SecurityTests` are created.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ7JBi-sNLgp5ttqZY:-NlJ7JBi-sNLgp5ttqZZ:bmbsd75) ([raw file](https://github.com/starkware-libs/blockifier/blob/50f231f58d811e5482109123ff70bbd9c88e2a6c/crates/blockifier/src/execution/entry_point_test.rs#L196)):*
> ```XML
>         code_address: Some(
>             FeatureContract::TestContract(CairoVersion::Cairo0).get_instance_address(0),
>         ),
> ```

Comment that this address is irrelevant for this test (it is - right?)

the `code_address` be None?



_Suggestion:_
```XML
        code_address: None,
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1238)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/entry_point_test.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ7JBi-sNLgp5ttqZY:-NlJOTBs2j9zD25PsQuS:bpqlbdo) ([raw file](https://github.com/starkware-libs/blockifier/blob/50f231f58d811e5482109123ff70bbd9c88e2a6c/crates/blockifier/src/execution/entry_point_test.rs#L196)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Comment that this address is irrelevant for this test (it is - right?)

the `code_address` be None?
</blockquote></details>

What I meant to write:
Can the `code_address` be None?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1238)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ1Eer1dr2iO_vOGGC:-NlNu_li6Ek10WXjDEOV:b-77u488) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90e198e42beadcec708b5fe8a68db7b8ef8b81d/crates/blockifier/src/execution/entry_point_test.rs#L221)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Humm - it is nicer and more self-contained this way.
Too bad we create many instances of state.


How about a test util similar to `security_test_state` (from the first revision of this PR: `r1`) that returns a state and the used `FeatureContract`?
Or maybe it is just the correct way to have it similar to `r1` - where a few instances of `FeatureContract::SecurityTests` are created.
</blockquote></details>

hmmm.. I also don't like the multiple state creation.
Now take the state and contract as inputs (worth it IMO)
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ7JBi-sNLgp5ttqZY:-NlNuZxY2MWgQ6_-GTYN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/50f231f58d811e5482109123ff70bbd9c88e2a6c/crates/blockifier/src/execution/entry_point_test.rs#L196)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

What I meant to write:
Can the `code_address` be None?
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-:-NlNwqtO3A5Ujh6xaxKp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1238#-NlJ1Eer1dr2iO_vOGGC:-NlNwktzC1qPOrLtNpVx:b-83sjoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90e198e42beadcec708b5fe8a68db7b8ef8b81d/crates/blockifier/src/execution/entry_point_test.rs#L221)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm.. I also don't like the multiple state creation.
Now take the state and contract as inputs (worth it IMO)
</blockquote></details>

Nice!

**Pull request merged**
