### PR TITLE
fix: contract class version mismatch format

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
**Stack**:
- #2078
- #2073
- #2072
- #2069
- #2068 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2068)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2068)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2068#-O1VRICdDLN9n2_GsKKc:-O1VRICe-hrvnyct6dOn:b9zr2rv) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b10c29f16ae23b0abdc98e4e59b1be903dbd417/crates/blockifier/src/transaction/errors.rs#L56)):*
> ```XML
>          version {cairo_version:?}.", **declare_version
>     )]
>     ContractClassVersionMismatch { declare_version: TransactionVersion, cairo_version: u64 },
> ```

why is this a `u64` and not a `CairoVersion` enum instance?



_Code quote:_
```XML
cairo_version: u64
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2068)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2068#-O1VRICdDLN9n2_GsKKc:-O1VUD2D4hVZ1ZDhSQsa:bg1f8f0) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b10c29f16ae23b0abdc98e4e59b1be903dbd417/crates/blockifier/src/transaction/errors.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this a `u64` and not a `CairoVersion` enum instance?
</blockquote></details>

good question it was u64 before

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2068)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2068#-O1VRICdDLN9n2_GsKKc:-O1jyr9q7JRJCrBbkfCz:bfsanql) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b10c29f16ae23b0abdc98e4e59b1be903dbd417/crates/blockifier/src/transaction/errors.rs#L56)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

good question it was u64 before
</blockquote></details>

Okay, it's because this enum in a test utils and cannot be compile in a non-test module. Should I move the enum to a diff module or keep it u64?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2068)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2068#-O1VRICdDLN9n2_GsKKc:-O1kNoDl5fvjnxT-xEko:bqg7l70) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b10c29f16ae23b0abdc98e4e59b1be903dbd417/crates/blockifier/src/transaction/errors.rs#L56)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Okay, it's because this enum in a test utils and cannot be compile in a non-test module. Should I move the enum to a diff module or keep it u64?
</blockquote></details>

hmm... keep it u64 but please add a TODO to move the def to a non-test area

**Comment by AvivYossef-starkware** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
