### PR TITLE
DA cost calc: reduce cost for the nonce felt encoding and fee balance…

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
… change.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1236)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1236)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlIrDE2Ci0tghaEk4AI:-NlIrDE2Ci0tghaEk4AJ:bepolil) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage.rs#L85)):*
> ```XML
> 
>     // 1 bytes for class hash flag; 2 for number of storage updates (up to 64K);
>     // 3 for nonce update (up to 16M).
> ```

Or something similar



_Suggestion:_
```XML
    // For each modified contract, the expected non-zeros bits in the second word are:
    // 1 bytes for class hash flag; 2 for number of storage updates (up to 64K);
    // 3 for nonce update (up to 16M).
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlItxLg66dO3URZl_WC:-NlItxLh3s6aBHF1Bq4K:b-vartl7) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage.rs#L90)):*
> ```XML
>     naive_cost -= state_changes_count.n_modified_contracts * nonce_felt_discount;
> 
>     // Up to balance of 8**10 ETH.
> ```

How did you get this number?



_Code quote:_
```XML
    // Up to balance of 8**10 ETH.
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlIxMdn464M3MLB3b3S:-NlIxMdo30Z8kPI4NS0p:bpq9hma) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage.rs#L95)):*
> ```XML
>         eth_gas_constants::GAS_PER_MEMORY_WORD - fee_balance_value_cost;
> 
>     if naive_cost < fee_balance_value_discount {
> ```

Is it only a discount for the sender address balance, right?



_Code quote:_
```XML
    if naive_cost < fee_balance_value_discount {
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1020 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlIub37AQNEQEFgVjz3:-NlIub37AQNEQEFgVjz4:b-p7led3) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/transaction/account_transactions_test.rs#L1020)):*
> ```XML
>     } = create_test_init_data(Fee(MAX_FEE), block_context, state);
>     let actual_gas_used = 6043;
>     let actual_fee = actual_gas_used as u128 * 100000000000;
> ```

You may need to derive the fee type from the transaction version or by using the account transaction.



_Suggestion:_
```XML
    let actual_fee = actual_gas_used as u128 * block_context.gas_prices.get_by_fee_type(fee_type);
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1236)* status: all files reviewed, 6 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlIze8J50P-dUh-dzdr:-NlIze8J50P-dUh-dzds:b-a7sza4) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage.rs#L88)):*
> ```XML
>     let nonce_felt_cost = eth_gas_constants::get_calldata_word_cost(1 + 2 + 3);
>     let nonce_felt_discount = eth_gas_constants::GAS_PER_MEMORY_WORD - nonce_felt_cost;
>     naive_cost -= state_changes_count.n_modified_contracts * nonce_felt_discount;
> ```

Can this be negative?
If not, why it differs from `naive_cost - fee_balance_value_discount`?



_Code quote:_
```XML
   naive_cost -= state_changes_count.n_modified_contracts * nonce_felt_discount;
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlJ-TuX-9ngPoOFk2gd:-NlJ-TuX-9ngPoOFk2ge:b-n0cqdi) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage_test.rs#L42)):*
> ```XML
>         n_class_hash_updates: 0,
>         n_compiled_class_hash_updates: 0,
>         n_modified_contracts: 1,
> ```

Which contract is modified? 



_Code quote:_
```XML
        n_modified_contracts: 1,
```

**Review by noaov1 — COMMENTED** [review]
Can you test the discount calculation?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-:-NlJ3sUp-TThqipLdOVX:b-d81l76)* status: all files reviewed, 6 unresolved discussions (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
Sure, good idea

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-:-NlKYQTIAZfliX06m1Zl:btfgm18)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlIrDE2Ci0tghaEk4AI:-NlKWYe04xoVU4GMbxCz:b-zcjvte) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage.rs#L85)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Or something similar
</blockquote></details>

Thanks
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlIze8J50P-dUh-dzdr:-NlKWapO9I59v_tJJJ4B:b-ojkdpp) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage.rs#L88)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can this be negative?
If not, why it differs from `naive_cost - fee_balance_value_discount`?
</blockquote></details>

No, it can't since it depends on `state_changes_count.n_modified_contracts` being greater than 0
But better safe than sorry, you're right (we may add more discounts) 
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlItxLg66dO3URZl_WC:-NlKWo1p9L1lwj97zPPP:b-npdw84) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage.rs#L90)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

How did you get this number?
</blockquote></details>

Oops, thanks
```
2**(12*8) = 2**96 ~= 8*10**28 = 8 * (10**10) * (10**18)
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlIxMdn464M3MLB3b3S:-NlKXl9LBqFDaahLaX2K:b-tuik1l) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage.rs#L95)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it only a discount for the sender address balance, right?
</blockquote></details>

Exactly
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlJ-TuX-9ngPoOFk2gd:-NlKXyMt83yg75-C1RH3:b-fkffix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage_test.rs#L42)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Which contract is modified?
</blockquote></details>

Just for the test. I didn't wanted to go into the flow that the discount is higher than the DA cost
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1020 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlIub37AQNEQEFgVjz3:-NlKY9km2nvT87818CIf:b3rqerl) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/transaction/account_transactions_test.rs#L1020)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You may need to derive the fee type from the transaction version or by using the account transaction.
</blockquote></details>

I prefer leaving these improvements to Dori and don't do it in this PR

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1236)* status: all files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlIze8J50P-dUh-dzdr:-NlMm0Pp7oagO6NFxbls:b-l5srun) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage.rs#L88)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No, it can't since it depends on `state_changes_count.n_modified_contracts` being greater than 0
But better safe than sorry, you're right (we may add more discounts)
</blockquote></details>

Oh, I see. In the fee discount, we may refund a transaction with no fee charge?
So the sender gets the entire discount or no discount at all?
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlMsFPy7ug_7s3fJl3e:-NlMsFPy7ug_7s3fJl3f:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/984fc41d0fd6ded3912de28869f2188eb85da688/crates/blockifier/src/fee/gas_usage.rs#L88)):*
> ```XML
>     // 3 for nonce update (up to 16M).
>     let nonce_felt_cost = eth_gas_constants::get_calldata_word_cost(1 + 2 + 3);
>     let nonce_felt_discount = eth_gas_constants::GAS_PER_MEMORY_WORD - nonce_felt_cost;
> ```

WDYT?



_Suggestion:_
```XML
    let modified_contract_felt_cost = eth_gas_constants::get_calldata_word_cost(1 + 2 + 3);
    let modified_contract_felt_discount = eth_gas_constants::GAS_PER_MEMORY_WORD - nonce_felt_cost;
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlMrYDp5hEv9U0EL32r:-NlMrYDp5hEv9U0EL32s:b6nwr5b) ([raw file](https://github.com/starkware-libs/blockifier/blob/984fc41d0fd6ded3912de28869f2188eb85da688/crates/blockifier/src/fee/gas_usage_test.rs#L135)):*
> ```XML
>         // Fee balance update.
>         n_storage_updates: 1,
>         n_modified_contracts: 7,
> ```

Is it possible to have only one storage update and 7 modified contracts? Does it matter?
Can the number of storage updates be greater than 1?



_Code quote:_
```XML
        n_modified_contracts: 7,
```

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1236)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1236)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlJ-TuX-9ngPoOFk2gd:-NlN6WOyAKAt46XZW61w:ba9894m) ([raw file](https://github.com/starkware-libs/blockifier/blob/e250b9942392abdabbc50c5f1daa939b2fd027f1/crates/blockifier/src/fee/gas_usage_test.rs#L42)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Just for the test. I didn't wanted to go into the flow that the discount is higher than the DA cost
</blockquote></details>

Can you please explain? Why is the discount higher than the DA cost?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1236)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1236#-NlMrYDp5hEv9U0EL32r:-NlN8H7A-OMyCJyXN5Cv:bb77ueg) ([raw file](https://github.com/starkware-libs/blockifier/blob/984fc41d0fd6ded3912de28869f2188eb85da688/crates/blockifier/src/fee/gas_usage_test.rs#L135)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it possible to have only one storage update and 7 modified contracts? Does it matter?
Can the number of storage updates be greater than 1?
</blockquote></details>

Yes

**Pull request merged**
