### PR TITLE
fix(transaction): set l1 hanlder payload size to None for non-l1 hanlder txs (bouncer count)

### PR DESCRIPTION
**Pull request by noaov1**
Python PR [#33905](https://reviewable.io/reviews/starkware-industries/starkware/33905).

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1470#-NqLqzaO-WXJrMg3sdTG:-NqLqzaO-WXJrMg3sdTH:bmhpgjx) ([raw file](https://github.com/starkware-libs/blockifier/blob/54b493e513389995247d0dc36c7549f78bcff05a/crates/native_blockifier/src/transaction_executor.rs#L75)):*
> ```XML
>         let l1_handler_payload_size: usize =
>             if let Transaction::L1HandlerTransaction(l1_handler_tx) = &tx {
>                 l1_handler_tx.payload_size()
> ```

Add a type annotation of `Option<usize>`?
Also, can this method be removed?

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1470#-NqLqzaO-WXJrMg3sdTG:-NqMbHzL6ASPbBGikKHa:b-gglf9m) ([raw file](https://github.com/starkware-libs/blockifier/blob/54b493e513389995247d0dc36c7549f78bcff05a/crates/native_blockifier/src/transaction_executor.rs#L75)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a type annotation of `Option<usize>`?
Also, can this method be removed?
</blockquote></details>

Which method?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1470#-NqLqzaO-WXJrMg3sdTG:-NqMpCi9-trbiylm6zCG:bu7wj8g) ([raw file](https://github.com/starkware-libs/blockifier/blob/54b493e513389995247d0dc36c7549f78bcff05a/crates/native_blockifier/src/transaction_executor.rs#L75)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Which method?
</blockquote></details>

`payload_size` of `L1Handler`?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1470#-NqLqzaO-WXJrMg3sdTG:-NqMpMCH7f246xBbv2lR:b-oshm4l) ([raw file](https://github.com/starkware-libs/blockifier/blob/54b493e513389995247d0dc36c7549f78bcff05a/crates/native_blockifier/src/transaction_executor.rs#L75)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`payload_size` of `L1Handler`?
</blockquote></details>

We use it [here](https://github.com/starkware-libs/blockifier/blob/7db8f7675478f2a618d45e3ea6803e950780951b/crates/blockifier/src/transaction/transaction_execution.rs#L116) as well.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470#-:-NqMwjCo0NqufSQClYmX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1470#-NqLqzaO-WXJrMg3sdTG:-NqMwgWR9F8TlItf5h6n:b-kufkxf) ([raw file](https://github.com/starkware-libs/blockifier/blob/54b493e513389995247d0dc36c7549f78bcff05a/crates/native_blockifier/src/transaction_executor.rs#L75)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We use it [here](https://github.com/starkware-libs/blockifier/blob/7db8f7675478f2a618d45e3ea6803e950780951b/crates/blockifier/src/transaction/transaction_execution.rs#L116) as well.
</blockquote></details>

I see, thanks!

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1470#-NqMwkKN4fceM_1kuhrH:-NqMwkKN4fceM_1kuhrI:bta0nby) (no related file):*
Python PR?

___

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1470#-NqMwkKN4fceM_1kuhrH:-NqMyDAC1DYwdXgEbBuH:b-b5wgdc) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Python PR?
</blockquote></details>

Python PR [#33905](https://reviewable.io/reviews/starkware-industries/starkware/33905).

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1470#-NqMwkKN4fceM_1kuhrH:-NqMyFuxCYAunRYyrr3X:b-6y0f66) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Python PR [#33905](https://reviewable.io/reviews/starkware-industries/starkware/33905).
</blockquote></details>

No need to wait for it since we need to merge everything today. Sorry for the back and forth. :)

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1470)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
