### PR TITLE
Return `StateDiff` and `TransactionExecutionInfo` from `PyExecutor.execute()`.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPqUuC16NWcRLh7ACs:-NOPqUuC16NWcRLh7ACt:bjopmbi) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction.rs#L201)):*
> ```XML
>         tx: &PyAny,
>         contract_class: Option<&str>,
>     ) -> PyResult<(PyStateDiff, PyTransactionExecutionInfo)> {
> ```

Let's not return the state diff. here, but instead from `finalize()` in this class (which Python will call once it decides a block should be closed).



_Code quote:_
```XML
PyStateDiff
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPql0CEqJCyAy0m2V4:-NOPql0CEqJCyAy0m2V5:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction.rs#L207)):*
> ```XML
>             .execute(&mut self.state, &self.block_context)
>             .map_err(NativeBlockifierError::from)?;
>         Ok((PyStateDiff::from(state_diff), PyTransactionExecutionInfo::from(tx_execution_info)))
> ```

Add a blank line above.



_Code quote:_
```XML
Ok((PyStateDiff::from(state_diff), PyTransactionExecutionInfo::from(tx_execution_info)))
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPqzIo0NGnWHXhtBDB:-NOPqzIo0NGnWHXhtBDC:buqety9) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L38)):*
> ```XML
>     pub contract_address: PyFelt,
>     pub class_hash: Option<PyFelt>,
>     pub entry_point_selector: PyFelt,
> ```

`Option<...>` not needed?



_Code quote:_
```XML
PyFelt,
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284)* status: all files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPuQ_T7VUj06uLT9Qc:-NOPuQ_T7VUj06uLT9Qd:b-h364ja) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L16)):*
> ```XML
>     pub execute_call_info: Option<PyCallInfo>,
>     pub fee_transfer_call_info: Option<PyCallInfo>,
>     #[pyo3(get)]
> ```

What are those? Why only for two fields?



_Code quote:_
```XML
#[pyo3(get)]
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPv1qh-WJLKbRqD6ya:-NOPv1qh-WJLKbRqD6yb:b-v7d7az) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L23)):*
> ```XML
> 
> impl From<TransactionExecutionInfo> for PyTransactionExecutionInfo {
>     fn from(tx_execution_info: TransactionExecutionInfo) -> Self {
> ```

So it's easier to read. :)



_Suggestion:_
```XML
info: TransactionExecutionInfo
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPuDyv2Kh_wQ_k8-Yw:-NOPuDyv2Kh_wQ_k8-Yx:b-su0wpt) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L49)):*
> ```XML
>     fn from(call_info: CallInfo) -> Self {
>         let call = call_info.call;
>         let class_hash = call.class_hash.map(|class_hash| PyFelt(class_hash.0));
> ```

I don't think this variable is needed.



_Code quote:_
```XML
let class_hash = call.class_hash.map(|class_hash| PyFelt(class_hash.0));
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPvIPFA8IKhMLblPSa:-NOPvIPFA8IKhMLblPSb:b-x5r81y) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L58)):*
> ```XML
>             calldata: starkfelt_to_pyfelt_vec(call.calldata.0.to_vec()),
>             retdata: starkfelt_to_pyfelt_vec(call_info.execution.retdata.0),
>             events: call_info.execution.events.into_iter().map(PyEvent::from).collect(),
> ```

Can you have an `let execution = call_info.execution` variable, so the last line is easier to read?



_Code quote:_
```XML
 call_info.execution
```
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPtwH987JDtJKUBDt7:-NOPtwH987JDtJKUBDt8:b-1cf39u) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L94)):*
> ```XML
> }
> 
> fn starkfelt_to_pyfelt_vec(vec: Vec<StarkFelt>) -> Vec<PyFelt> {
> ```

Move to `py_utils.rs`?



_Suggestion:_
```XML
fn starkfelt_to_pyfelt_vec(stark_felts: Vec<StarkFelt>) -> Vec<PyFelt> {
    stark_felts.into_iter().map(PyFelt).collect()
}
```
___
*[`crates/native_blockifier/src/py_utils.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPrdd50E4ADTOPUBaK:-NOPrdd64niCynFX6L5y:bl20q9f) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_utils.rs#L30)):*
> ```XML
> impl From<EthAddress> for PyFelt {
>     fn from(address: EthAddress) -> Self {
>         let felt = StarkFelt::try_from(
> ```

WDYT? It should indeed be `from` (not `try_from`), but no `.expect` is needed, IMO.



_Suggestion:_
```XML
        let address_as_bytes: [u8; 20] = address.0.to_fixed_bytes();
        let address_as_bytes: [u8; 32] = // Pad with 12 zeros.
        StarkFelt(address_as_hex_str)
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPqUuC16NWcRLh7ACs:-NOPycBq6aNKoC0z7XhB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction.rs#L201)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's not return the state diff. here, but instead from `finalize()` in this class (which Python will call once it decides a block should be closed).
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPql0CEqJCyAy0m2V4:-NOcV1AwCq6z9crtlKrY:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction.rs#L207)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a blank line above.
</blockquote></details>

Done
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPuQ_T7VUj06uLT9Qc:-NOPym9K1jjbgs9GrW1g:bj4ztcu) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L16)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What are those? Why only for two fields?
</blockquote></details>

These macros are used in case you want to be able to get the struct fields in Python. In the background it clones the object. Since the `CallInfo` struct is "heavy" I did not want to add it above the `_call_info` fields. But on the other hand I assume we would like to access those fields so I added it there as well.
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPv1qh-WJLKbRqD6ya:-NOcfsVB3NoGYW4GCV7X:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L23)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So it's easier to read. :)
</blockquote></details>

Done
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPqzIo0NGnWHXhtBDB:-NOcfvwQDmky_T2i_d5-:b-evd1m3) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`Option<...>` not needed?
</blockquote></details>

Why? Because of `InvokeTransaction`? In the struct `CallEntryPoint` it is not optional.
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPvIPFA8IKhMLblPSa:-NOchCJp4YUV1NqPuG-p:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you have an `let execution = call_info.execution` variable, so the last line is easier to read?
</blockquote></details>

Done
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPtwH987JDtJKUBDt7:-NOchf-O-CIoctApiiJW:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L94)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move to `py_utils.rs`?
</blockquote></details>

Done
___
*[`crates/native_blockifier/src/py_utils.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPrdd50E4ADTOPUBaK:-NOcj7CO7FO5v8L2Vpax:b-wsw79a) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_utils.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT? It should indeed be `from` (not `try_from`), but no `.expect` is needed, IMO.
</blockquote></details>

I'm not sure how do we avoid the `expect`. The `new` method returns `Result` as well. Do you think this is better:



_Code snippet:_
```XML
        let address_as_bytes: [u8; 20] = address.0.to_fixed_bytes();
        // Pad with 12 zeros.
        let mut bytes = [0; 32];
        bytes[..24].copy_from_slice(&address_as_bytes);
        PyFelt(StarkFelt::new(bytes).expect("Convert Ethereum address to StarkFelt"))
```

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPuQ_T7VUj06uLT9Qc:-NOcp6xB0LOAyg5IMm1C:b-gjhutl) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L16)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

These macros are used in case you want to be able to get the struct fields in Python. In the background it clones the object. Since the `CallInfo` struct is "heavy" I did not want to add it above the `_call_info` fields. But on the other hand I assume we would like to access those fields so I added it there as well.
</blockquote></details>

WDYM by "get the struct fields in Python"? Doing `X.field_name`?
Does it add an additional clone, that otherwise wouldn't have happened?
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPqzIo0NGnWHXhtBDB:-NOcpv7m7PkTpbSk0pPc:bsneu61) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L38)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why? Because of `InvokeTransaction`? In the struct `CallEntryPoint` it is not optional.
</blockquote></details>

I don't remember why is it optional in Python.
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPvIPFA8IKhMLblPSa:-NOcpT-00Mav_6wy9-Sm:b-r9lv7s) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L58)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Can the `l2_to_l1_messages: ...` lines now be squashed?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_utils.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPrdd50E4ADTOPUBaK:-NOd-2YB7SB9RM2MjcJo:bcntq0) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_utils.rs#L30)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm not sure how do we avoid the `expect`. The `new` method returns `Result` as well. Do you think this is better:
</blockquote></details>

You're right, we can't avoid the `.expect()` because of that. :(
I think the second version is better, since if `StarkFelt::new()` changes in the future to return `StarkFelt` rather than `Result<...>` we'd be able to delete the `.expect()`. WDYT?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPuQ_T7VUj06uLT9Qc:-NOcsEvj-qb-ODbXkkaY:bcqla2u) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L16)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM by "get the struct fields in Python"? Doing `X.field_name`?
Does it add an additional clone, that otherwise wouldn't have happened?
</blockquote></details>

Yes. As far as I understand it adds an additional clone: For get the field type must implement both `IntoPy<PyObject>` and `Clone` (maybe to avoid dealing with lifetimes?)
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPqzIo0NGnWHXhtBDB:-NOd3WT734ocVjtUdXp6:bnac8g7) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I don't remember why is it optional in Python.
</blockquote></details>

In `convert_contract_calls_to_call_info` we use an `ContractCall` object in order to fill the `CallInfo` fields. The `ContractCall` class has an optional `entry_point_selector` field. Maybe it is because of that?
___
*[`crates/native_blockifier/src/py_utils.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPrdd50E4ADTOPUBaK:-NOd43de6s3S3QEnayLQ:b-c13ux9) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_utils.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You're right, we can't avoid the `.expect()` because of that. :(
I think the second version is better, since if `StarkFelt::new()` changes in the future to return `StarkFelt` rather than `Result<...>` we'd be able to delete the `.expect()`. WDYT?
</blockquote></details>

Agree. Changed.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284#-:-NOd63qEB0UehdahzRCM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPuQ_T7VUj06uLT9Qc:-NOd5B_OEiuuO669zQlN:b-c8pnfy) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L16)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes. As far as I understand it adds an additional clone: For get the field type must implement both `IntoPy<PyObject>` and `Clone` (maybe to avoid dealing with lifetimes?)
</blockquote></details>

Do you think we'll have to access those fields? We only need to write them into the storage.
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPqzIo0NGnWHXhtBDB:-NOd5t6I4WgeBxH1__hO:biki6x1) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L38)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In `convert_contract_calls_to_call_info` we use an `ContractCall` object in order to fill the `CallInfo` fields. The `ContractCall` class has an optional `entry_point_selector` field. Maybe it is because of that?
</blockquote></details>

Probably, but I don't recall why was the selector optional to begin with; I think we had a selector from day one.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPuQ_T7VUj06uLT9Qc:-NOd7z9S5m3pETCpdAB7:bxplwyj) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L16)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you think we'll have to access those fields? We only need to write them into the storage.
</blockquote></details>

Good question. I though we need to read this object directly in python. The same applies to `PyStateDiff`? 
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPvIPFA8IKhMLblPSa:-NOd7fF09xUhKv9hj1Jx:b-3cjs6d) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can the `l2_to_l1_messages: ...` lines now be squashed?
</blockquote></details>

WDYM? To be in one line? The auto formatter change it every time I save the file

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPuQ_T7VUj06uLT9Qc:-NOdLMgZ4g20g5hwxcFf:bx6vj23) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L16)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Good question. I though we need to read this object directly in python. The same applies to `PyStateDiff`? 
</blockquote></details>

No. 
And for now, while the logic for whether to close the block or not is Pythonic, we _will_ need to access them in Python. 
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/284#-NOPvIPFA8IKhMLblPSa:-NOdKyl1BlJxoOcJxx38:b-ytc96n) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b6c64055e0bcd1682941449817fc2da9fbd445f/crates/native_blockifier/src/py_transaction_execution_info.rs#L58)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM? To be in one line? The auto formatter change it every time I save the file
</blockquote></details>

Nevermind, I thought the line fits into 100 characters.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/284)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
