### PR TITLE
feat(execution): calculate the syscall resources for every entry point

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1437)

### CODE REVIEW

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1437)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 343 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-NpxSWdVAH-uMF9jbwaw:-NpxSWdVAH-uMF9jbwax:bapl7ls) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd9f19149f2a250a8982d64fe5b041cd3220dc36/crates/blockifier/src/execution/entry_point_execution.rs#L343)):*
> ```XML
>     let versioned_constants = VersionedConstants::latest_constants();
>     syscall_handler.resources.vm_resources +=
>         &versioned_constants.get_additional_os_syscall_resources(&syscall_handler.syscall_counter)?;
> ```

The caller of this function, `execute_entry_point_call`, has `context: EntryPointExecutionContext`, from which you can get `versioned_constants` via `context.versioned_constants()`.

Ditto for the second one.

The idea is that `VersionedConstants` (which holds all of the blockifier's constants) is now initialized by the user _before_ calling execute/validate, and is then passed on via context variable, which have been consolidated in a matrushka-style:

`BlockContext`: holds `VersionedContext`, chain info, and block info
==> `TransactionContext`: holds `BlockContext` and transaction info
==> `EntryPointExecutionContext`: holds `TransactionContext` and entry point info  // Your code is at this "depth" of the call stack, hence you have the entry point context to work on.



_Suggestion:_
```XML
pub fn finalize_execution(
    versioned_constants: &VersionedConstants,
    mut vm: VirtualMachine,
    runner: CairoRunner,
    syscall_handler: SyscallHintProcessor<'_>,
    previous_vm_resources: VmExecutionResources,
    n_total_args: usize,
    program_extra_data_length: usize,
) -> Result<CallInfo, PostExecutionError> {
    // Close memory holes in segments (OS code touches those memory cells, we simulate it).
    let program_start_ptr = runner
        .program_base
        .expect("The `program_base` field should be initialized after running the entry point.");
    let program_end_ptr = (program_start_ptr + runner.get_program().data_len())?;
    vm.mark_address_range_as_accessed(program_end_ptr, program_extra_data_length)?;

    let initial_fp = runner
        .get_initial_fp()
        .expect("The `initial_fp` field should be initialized after running the entry point.");
    // When execution starts the stack holds the EP arguments + [ret_fp, ret_pc].
    let args_ptr = (initial_fp - (n_total_args + 2))?;
    vm.mark_address_range_as_accessed(args_ptr, n_total_args)?;
    syscall_handler.read_only_segments.mark_as_accessed(&mut vm)?;

    let call_result = get_call_result(&vm, &syscall_handler)?;

    // Take into account the VM execution resources of the current call, without inner calls.
    // Has to happen after marking holes in segments as accessed.
    let vm_resources_without_inner_calls = runner
        .get_execution_resources(&vm)
        .map_err(VirtualMachineError::RunnerError)?
        .filter_unused_builtins();
    // TODO(Ori, 14/2/2024): Rename `vm_resources`.
    syscall_handler.resources.vm_resources += &vm_resources_without_inner_calls;
    syscall_handler.resources.vm_resources +=
        &versioned_constants.get_additional_os_syscall_resources(&syscall_handler.syscall_counter)?;
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1437)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 343 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-NpxSWdVAH-uMF9jbwaw:-NpxgMwVDqSnlGkdDFDH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd9f19149f2a250a8982d64fe5b041cd3220dc36/crates/blockifier/src/execution/entry_point_execution.rs#L343)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The caller of this function, `execute_entry_point_call`, has `context: EntryPointExecutionContext`, from which you can get `versioned_constants` via `context.versioned_constants()`.

Ditto for the second one.

The idea is that `VersionedConstants` (which holds all of the blockifier's constants) is now initialized by the user _before_ calling execute/validate, and is then passed on via context variable, which have been consolidated in a matrushka-style:

`BlockContext`: holds `VersionedContext`, chain info, and block info
==> `TransactionContext`: holds `BlockContext` and transaction info
==> `EntryPointExecutionContext`: holds `TransactionContext` and entry point info  // Your code is at this "depth" of the call stack, hence you have the entry point context to work on.
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1437)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-Npy9-Zq0cx9o6YpEXQd:-Npy9-Zq0cx9o6YpEXQe:b23i27q) ([raw file](https://github.com/starkware-libs/blockifier/blob/4160542085c767722758da6b8bbdd751b9c4c7ac/crates/blockifier/src/versioned_constants.rs#L104)):*
> ```XML
>     // i.e., the resources of the Starknet OS function `execute_transactions_inner`.
>     // Also adds the resources needed for the fee transfer execution, performed in the end·
>     // of every transaction.
> ```

I wonder if this duplication is needed (you documented the inner method. Same for below.



_Code quote:_
```XML
    // Calculates the additional resources needed for the OS to run the given transaction;
    // i.e., the resources of the Starknet OS function `execute_transactions_inner`.
    // Also adds the resources needed for the fee transfer execution, performed in the end·
    // of every transaction.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 168 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-Npy8wD8BtYQmsyQJCrl:-Npy8wD8BtYQmsyQJCrm:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4160542085c767722758da6b8bbdd751b9c4c7ac/crates/blockifier/src/versioned_constants.rs#L168)):*
> ```XML
>     // i.e., the resources of the Starknet OS function `execute_transactions_inner`.
>     // Also adds the resources needed for the fee transfer execution, performed in the end·
>     // of every transaction.
> ```





_Suggestion:_
```XML
    /// Calculates the additional resources needed for the OS to run the given transaction;
    /// i.e., the resources of the Starknet OS function `execute_transactions_inner`.
    /// Also adds the resources needed for the fee transfer execution, performed in the end·
    /// of every transaction.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 169 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-Npy82MP-9vU2W-q8daZ:-Npy82MQE0GR8cQWOYwT:bl63f5l) ([raw file](https://github.com/starkware-libs/blockifier/blob/4160542085c767722758da6b8bbdd751b9c4c7ac/crates/blockifier/src/versioned_constants.rs#L169)):*
> ```XML
>     // Also adds the resources needed for the fee transfer execution, performed in the end·
>     // of every transaction.
>     pub fn get_additional_os_tx_resources(
> ```

Why `pub`?



_Code quote:_
```XML
    pub fn get_additional_os_tx_resources(
```
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 248 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-Npy9UPK49nzBPVvbp0u:-Npy9UPK49nzBPVvbp0v:bjh9w1y) ([raw file](https://github.com/starkware-libs/blockifier/blob/4160542085c767722758da6b8bbdd751b9c4c7ac/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L248)):*
> ```XML
>     let versioned_constants = syscall_handler.context.versioned_constants();
>     syscall_handler.resources.vm_resources += &versioned_constants
>         .get_additional_os_syscall_resources(&syscall_handler.syscall_counter)?;
> ```

Same in the non-deprecated file. 



_Suggestion:_
```XML
    // Take into account the syscall resources of the current call.
    syscall_handler.resources.vm_resources += &versioned_constants
        .get_additional_os_syscall_resources(&syscall_handler.syscall_counter)?;
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1437)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-Npy9-Zq0cx9o6YpEXQd:-NpyB4e-1Aw7L0WqmW9B:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4160542085c767722758da6b8bbdd751b9c4c7ac/crates/blockifier/src/versioned_constants.rs#L104)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if this duplication is needed (you documented the inner method. Same for below.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 168 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-Npy8wD8BtYQmsyQJCrl:-NpyB5LW5Sr4zhlCipHR:b-bbb34d) ([raw file](https://github.com/starkware-libs/blockifier/blob/4160542085c767722758da6b8bbdd751b9c4c7ac/crates/blockifier/src/versioned_constants.rs#L168)):*
> ```XML
>     // i.e., the resources of the Starknet OS function `execute_transactions_inner`.
>     // Also adds the resources needed for the fee transfer execution, performed in the end·
>     // of every transaction.
> ```

Is this to mark the repetition or is there another comment?
___
*[`crates/blockifier/src/versioned_constants.rs` line 169 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-Npy82MP-9vU2W-q8daZ:-NpyBBYz8nyB0lBHlvp4:b-qzdxsz) ([raw file](https://github.com/starkware-libs/blockifier/blob/4160542085c767722758da6b8bbdd751b9c4c7ac/crates/blockifier/src/versioned_constants.rs#L169)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why `pub`?
</blockquote></details>

It is used in crates/blockifier/src/transaction/transaction_utils.rs

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1437)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 168 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-Npy8wD8BtYQmsyQJCrl:-NpyCDPk9wCONJ27UQ-t:b-pgx1xj) ([raw file](https://github.com/starkware-libs/blockifier/blob/4160542085c767722758da6b8bbdd751b9c4c7ac/crates/blockifier/src/versioned_constants.rs#L168)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Is this to mark the repetition or is there another comment?
</blockquote></details>

You should add one more `/` to indicate that it is a documentation and not a comment. 
___
*[`crates/blockifier/src/versioned_constants.rs` line 169 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-Npy82MP-9vU2W-q8daZ:-NpyCV_v-VovgWVa8vFg:b-7gm0rn) ([raw file](https://github.com/starkware-libs/blockifier/blob/4160542085c767722758da6b8bbdd751b9c4c7ac/crates/blockifier/src/versioned_constants.rs#L169)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

It is used in crates/blockifier/src/transaction/transaction_utils.rs
</blockquote></details>

Isn't it the method of `VersionedConstants`?

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1437)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 169 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-Npy82MP-9vU2W-q8daZ:-NpyE1no9u2GXqgXBnBD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4160542085c767722758da6b8bbdd751b9c4c7ac/crates/blockifier/src/versioned_constants.rs#L169)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Isn't it the method of `VersionedConstants`?
</blockquote></details>

Done.

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1437)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-NpyEb1oAKYjn2jTkQ4S:-NpyEb1oAKYjn2jTkQ4T:b-lx8y8n) (no related file):*
Wait for python PR

___

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1437#-:-Npy_E4r5flaFTf-_gSA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by OriStarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1437)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
