### PR TITLE
feat(execution): compute state_diff_size and add it to bouncer info

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1395)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
Python side: https://github.com/starkware-industries/starkware/pull/33662

**Comment by ArniStarkware** [comment]
*[`crates/native_blockifier/src/transaction_executor.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-NpLDRqK0aTfmhnLHjjk:-NpLDRqL237a7OwDwwS6:b-itwuiv) ([raw file](https://github.com/starkware-libs/blockifier/blob/12618ee6c4e61dbfa75e2bf8b5812f653fd5e553/crates/native_blockifier/src/transaction_executor.rs#L141)):*
> ```XML
>                     sender_address,
>                     &mut transactional_state,
>                 )?;
> ```

Seems like there is something wrong with my code. I never use the block-level state changes.
Would we like to have the "difference"(whatever that means) between `self.new_state_changes` and `self.block_level_state_changes`?

I think I know what I get by running the command: `get_new_state_changes`. I am not sure what I want to send to the bouncer.



_Code quote:_
```XML
                self.new_state_changes = get_new_state_changes(
                    &fee_type,
                    self.block_context.clone(),
                    sender_address,
                    &mut transactional_state,
                )?;
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
I think there's a bug in `try_add_state_changes`, let's talk tomorrow

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-:-NpLY_TQEv4cjLwRE5Mi:b-i7nd7v)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-NpLUypW0CtnEOjJEM_W:-NpLUypX7Cc7neZRWWfU:b-owftil) ([raw file](https://github.com/starkware-libs/blockifier/blob/12618ee6c4e61dbfa75e2bf8b5812f653fd5e553/crates/native_blockifier/src/transaction_executor.rs#L42)):*
> ```XML
>     // State-related fields.
>     pub state: CachedState<S>,
>     pub block_level_state_changes: StateChanges,
> ```

Add a TODO to handle redundant writes (0 -> 1 -> 0)
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-NpLSt_EC0ISF3WdrlHp:-NpLSt_EC0ISF3WdrlHq:b-s1xml9) ([raw file](https://github.com/starkware-libs/blockifier/blob/12618ee6c4e61dbfa75e2bf8b5812f653fd5e553/crates/native_blockifier/src/transaction_executor.rs#L43)):*
> ```XML
>     pub state: CachedState<S>,
>     pub block_level_state_changes: StateChanges,
>     pub new_state_changes: StateChanges,
> ```

Rename `new_state_changes` -> `tx_state_changes` and move to `StagedTransactionalState`.

Add a TODO to compute it - and messages_segment_length - once (make it part of the output)



_Suggestion:_
```XML
    pub state_changes: StateChanges,
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-NpLDRqK0aTfmhnLHjjk:-NpLUAaODjw1SJzKdaIq:b-2ntz5a) ([raw file](https://github.com/starkware-libs/blockifier/blob/12618ee6c4e61dbfa75e2bf8b5812f653fd5e553/crates/native_blockifier/src/transaction_executor.rs#L141)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Seems like there is something wrong with my code. I never use the block-level state changes.
Would we like to have the "difference"(whatever that means) between `self.new_state_changes` and `self.block_level_state_changes`?

I think I know what I get by running the command: `get_new_state_changes`. I am not sure what I want to send to the bouncer.
</blockquote></details>

The bouncer should get the residual amount. You can either keep here the prev length, and pass the diff, 
or do the same in python (read the prev value from the weight dict).

Option 1 is consistent with other code here. 
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-NpLRu624arWaf5t8uVF:-NpLRu624arWaf5t8uVG:blayzuw) ([raw file](https://github.com/starkware-libs/blockifier/blob/12618ee6c4e61dbfa75e2bf8b5812f653fd5e553/crates/native_blockifier/src/transaction_executor.rs#L239)):*
> ```XML
>             StateChanges::merge(vec![
>                 self.block_level_state_changes.clone(),
>                 self.new_state_changes.clone(),
> ```

Can you avoid cloning here?



_Code quote:_
```XML
            StateChanges::merge(vec![
                self.block_level_state_changes.clone(),
                self.new_state_changes.clone(),
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
Blocking: this function removes several fields such as fee token contract and sequencer balance. Need to think about it

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-:-NpLb8M86fwwLcac3UbU:b-ohdd3j)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1395)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-NpLUypW0CtnEOjJEM_W:-NpO1rgZ9woxxRBDWo7A:b215q00) ([raw file](https://github.com/starkware-libs/blockifier/blob/12618ee6c4e61dbfa75e2bf8b5812f653fd5e553/crates/native_blockifier/src/transaction_executor.rs#L42)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add a TODO to handle redundant writes (0 -> 1 -> 0)
</blockquote></details>

Don't we currently handle this?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1395)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-NpLUypW0CtnEOjJEM_W:-NpOOrziDQBBW7GS9393:b-vn5dp3) ([raw file](https://github.com/starkware-libs/blockifier/blob/12618ee6c4e61dbfa75e2bf8b5812f653fd5e553/crates/native_blockifier/src/transaction_executor.rs#L42)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Don't we currently handle this?
</blockquote></details>

In the context of the tx-executor we do handle it (with the `merge` operation during the `commit` method).
Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-NpLSt_EC0ISF3WdrlHp:-NpOVDHr4nMBMlVW3azy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/12618ee6c4e61dbfa75e2bf8b5812f653fd5e553/crates/native_blockifier/src/transaction_executor.rs#L43)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Rename `new_state_changes` -> `tx_state_changes` and move to `StagedTransactionalState`.

Add a TODO to compute it - and messages_segment_length - once (make it part of the output)
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-NpLDRqK0aTfmhnLHjjk:-NpOVBYg1ObN8E_FEa7A:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/12618ee6c4e61dbfa75e2bf8b5812f653fd5e553/crates/native_blockifier/src/transaction_executor.rs#L141)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The bouncer should get the residual amount. You can either keep here the prev length, and pass the diff, 
or do the same in python (read the prev value from the weight dict).

Option 1 is consistent with other code here.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1395#-NpLRu624arWaf5t8uVF:-NpOUepK9F5CbHC2aWjI:b-uhb6pg) ([raw file](https://github.com/starkware-libs/blockifier/blob/12618ee6c4e61dbfa75e2bf8b5812f653fd5e553/crates/native_blockifier/src/transaction_executor.rs#L239)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you avoid cloning here?
</blockquote></details>

(For the current version of the code: (r2))
Without a clone, we get:
```
error[E0507]: cannot move out of `self.state_changes` which is behind a mutable reference
   --> crates/native_blockifier/src/transaction_executor.rs:245:13
    |
245 |             self.state_changes,
    |             ^^^^^^^^^^^^^^^^^^ move occurs because `self.state_changes` has type `blockifier::state::cached_state::StateChanges`, which does not implement the `Copy` trait
```

**Comment by ArniStarkware** [comment]
Redesign in #1413.

**Comment by ArniStarkware** [comment]
replaced with #1438.

**Pull request closed without merging**
