### PR TITLE
Set execution mode as validate for deploy-account transaction.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/937)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/account_transaction.rs` line 624 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/937#-NfGdHMb2YKj9SurQjN7:-NfGdHMb2YKj9SurQjN8:b-3b9di4) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b7f205cd439a771f72db78b625f51cd87847883/crates/blockifier/src/transaction/account_transaction.rs#L624)):*
> ```XML
>                 &account_tx_context,
>             )
>         } else {
> ```

This is one more middle-ground solution. 



_Suggestion:_
```XML
        let execution_context = if matches!(self, Self::DeployAccount(_)) {
            let execution_context = EntryPointExecutionContext::new_invoke(
                block_context,
                &account_tx_context,
            );
            execution_context.execution_mode = ExecutionMode::Validate;
            execution_context
        } else {
```

**Review by Yoni-Starkware — APPROVED** [review]
Wait for @elintul 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/937#-:-NfH4ekOBB_tdxhnJmfd:b95z89w)* status: all files reviewed, 1 unresolved discussion

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/937)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 618 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/937#-NfLSPKR-hvUTDXZwI8R:-NfLSPKR-hvUTDXZwI8S:b-y3jpd4) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc246c28eadfd531877023d4f3fda8f86bc1b0f3/crates/blockifier/src/transaction/account_transaction.rs#L618)):*
> ```XML
>         block_context: &BlockContext,
>     ) -> TransactionExecutionResult<ValidateExecuteCallInfo> {
>         let account_tx_context = self.get_account_transaction_context();
> ```

Are we okay with the `n_max_steps`?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 620 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/937#-NfLSV2xCH0n0onDO4-k:-NfLSV2yCvmiVy2pEpCi:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc246c28eadfd531877023d4f3fda8f86bc1b0f3/crates/blockifier/src/transaction/account_transaction.rs#L620)):*
> ```XML
>         let account_tx_context = self.get_account_transaction_context();
>         let execution_context = if matches!(self, Self::DeployAccount(_)) {
>             EntryPointExecutionContext::new_validate(block_context, &account_tx_context)
> ```





_Suggestion:_
```XML
// Run constructor in validate mode, since it is executed first.
EntryPointExecutionContext::new_validate(block_context, &account_tx_context)
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/937)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 618 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/937#-NfLSPKR-hvUTDXZwI8R:-NfLTtyFB_9wA_dCsTKl:bp1n6sc) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc246c28eadfd531877023d4f3fda8f86bc1b0f3/crates/blockifier/src/transaction/account_transaction.rs#L618)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are we okay with the `n_max_steps`?
</blockquote></details>

Yes :) This is intended.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 620 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/937#-NfLSV2xCH0n0onDO4-k:-NfLXKEn9OpsTj_eZea2:b-sxsq2y) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc246c28eadfd531877023d4f3fda8f86bc1b0f3/crates/blockifier/src/transaction/account_transaction.rs#L620)):*
> ```XML
>         let account_tx_context = self.get_account_transaction_context();
>         let execution_context = if matches!(self, Self::DeployAccount(_)) {
>             EntryPointExecutionContext::new_validate(block_context, &account_tx_context)
> ```

Slight rephrase. Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/937#-:-NfL_94p0n3ZhXTZOyDX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/937)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
