### PR TITLE
chore: move code size logic to ClassInfo

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1685)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1685)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 280 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1685#-NtMTMlb-cqmpOfdi1Dd:-NtMTMlb-cqmpOfdi1De:bs1gybp) ([raw file](https://github.com/starkware-libs/blockifier/blob/2fc99d1bf149fe3fe5d29bb3be8afcb25d9b88d1/crates/blockifier/src/transaction/objects.rs#L280)):*
> ```XML
>         calldata_length: usize,
>         signature_length: usize,
>         code_size: usize,
> ```

there may be a smarter way to solve this but in [this](https://reviewable.io/reviews/starkware-libs/blockifier/1686) PR I hit lifetime issues if I try to pass an `Option<&ClassInfo>` into a lifetimed struct with a `&'a StarknetResources` field



_Code quote:_
```XML
code_size: usize
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1685#-:-NtQ0LJL9_cyBEhKMZav:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @nimrod-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 280 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1685#-NtMTMlb-cqmpOfdi1Dd:-NtQ-rf9AMhJ_2CQSMi6:bbowh8n) ([raw file](https://github.com/starkware-libs/blockifier/blob/2fc99d1bf149fe3fe5d29bb3be8afcb25d9b88d1/crates/blockifier/src/transaction/objects.rs#L280)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there may be a smarter way to solve this but in [this](https://reviewable.io/reviews/starkware-libs/blockifier/1686) PR I hit lifetime issues if I try to pass an `Option<&ClassInfo>` into a lifetimed struct with a `&'a StarknetResources` field
</blockquote></details>

This solution is better IMO

**Review by noaov1 — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1685#-:-NtQ57ESCl8rQaZPecmD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1685#-:-NtVG0EGCTgRZxzfz1Wu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware and @Yoni-Starkware)

**Pull request merged**
