### PR TITLE
Elin/merge main v0.13.0 into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1304)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1304)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1304)* status: 5 of 9 files reviewed, all discussions resolved

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1304)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1304#-Nn3ged7DW7t6izf6B2J:-Nn3ged8-pwMpdXkS83x:b-3a799i) (no related file):*
[Python side](https://reviewable.io/reviews/starkware-industries/starkware/33192).

___

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1304#-:-Nn3wO-r8qOLFXXOdiP0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1304)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
