### PR TITLE
chore(state): implement diff for StateMaps

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1910)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1910)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1910#-NyQZsNU6syBlYx7U9My:-NyQZsNV6M0dXlSAiD5W:b-96zvz7) ([raw file](https://github.com/starkware-libs/blockifier/blob/21b712cc0d2f83250fa3b500b99588d60e2a6ee1/crates/blockifier/src/state/cached_state.rs#L60)):*
> ```XML
>         self.update_initial_values_of_write_only_access()?;
>         let cache = self.cache.borrow();
>         Ok(StateChanges(cache.writes.diff(&cache.initial_reads)))
> ```

add a method on the cache object for this? seems natural



_Suggestion:_
```XML
cache.diff()
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 350 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1910#-NyQ_3yRC_URzfdop1dk:-NyQ_3yRC_URzfdop1dl:baf6zlm) ([raw file](https://github.com/starkware-libs/blockifier/blob/21b712cc0d2f83250fa3b500b99588d60e2a6ee1/crates/blockifier/src/state/cached_state.rs#L350)):*
> ```XML
>     /// Assumes (and enforces) other's keys contains self's.
>     pub fn diff(&self, other: &Self) -> Self {
>         StateMaps {
> ```

non-blocking



_Suggestion:_
```XML
Self
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1910)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1910#-NyQ_ZtI66iXCekFlZCO:-NyQ_ZtI66iXCekFlZCP:b-hly2zx) (no related file):*
python side PR?

___

**Review by avi-starkware — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1910)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1910)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @dorimedini-starkware, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1910#-NyQ_ZtI66iXCekFlZCO:-NyT_VAoEZ0EURNfYj1P:b-2blbt1) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

python side PR?
</blockquote></details>

Again, I don't think we should delay these kind of PRs

___
___
*[`crates/blockifier/src/state/cached_state.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1910#-NyQZsNU6syBlYx7U9My:-NyT_Phs9Sy_lrdsnmHo:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/21b712cc0d2f83250fa3b500b99588d60e2a6ee1/crates/blockifier/src/state/cached_state.rs#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a method on the cache object for this? seems natural
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1910#-:-NyUF3Dh3zBZSwfZg2x-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 385 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1910#-NyUEwQGCInevnXikD3x:-NyUEwQGCInevnXikD3y:bxp78hp) ([raw file](https://github.com/starkware-libs/blockifier/blob/19c78582eae087f2747435edeee261d8030ae8c8/crates/blockifier/src/state/cached_state.rs#L385)):*
> ```XML
>         self.writes.diff(&self.initial_reads)
>     }
>     fn declare_contract(&mut self, class_hash: ClassHash) {
> ```

newline (non-blocking)



_Suggestion:_
```XML
    }
    
    fn declare_contract(&mut self, class_hash: ClassHash) {
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1910)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1910#-NyQR0bi-yci2Sc7j26K:-NyQR0bi-yci2Sc7j26L:b-ethvb7) ([raw file](https://github.com/starkware-libs/blockifier/blob/088b449e08f02097e02a10154bb01a8cac35ef11/crates/blockifier/src/state/cached_state.rs#L324)):*
> ```XML
> }
> 
> #[derive(Clone, Debug, Default, PartialEq, Eq)]
> ```

Are we okay with the clone? Same question for `StateChanges` struct. 
I see that the clone is used only in testing. Maybe it's better to write: `#[cfg_attr(any(feature = "testing", test), derive(Clone))]`



_Code quote:_
```XML
#[derive(Clone, Debug, Default, PartialEq, Eq)]
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1910)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1910#-NyQR0bi-yci2Sc7j26K:-NyUUhjP5yp_LondKhUu:bpgzdyq) ([raw file](https://github.com/starkware-libs/blockifier/blob/088b449e08f02097e02a10154bb01a8cac35ef11/crates/blockifier/src/state/cached_state.rs#L324)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Are we okay with the clone? Same question for `StateChanges` struct. 
I see that the clone is used only in testing. Maybe it's better to write: `#[cfg_attr(any(feature = "testing", test), derive(Clone))]`
</blockquote></details>

You're right, done
___
*[`crates/blockifier/src/state/cached_state.rs` line 385 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1910#-NyUEwQGCInevnXikD3x:-NyUU_0gBqU4j5-X9TM8:b-af8rk2) ([raw file](https://github.com/starkware-libs/blockifier/blob/19c78582eae087f2747435edeee261d8030ae8c8/crates/blockifier/src/state/cached_state.rs#L385)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline (non-blocking)
</blockquote></details>

Oops, done

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1910)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1910)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Pull request merged**
