### PR TITLE
Change ` gas_consumed ` to be of type ` u64 ` .

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/676)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/676)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/676#-NZ0nKMt4OLR-qMV3O9Y:-NZ0nKMt4OLR-qMV3O9Z:bbwp5nb) ([raw file](https://github.com/starkware-libs/blockifier/blob/15348f682c35ed0bf87687862c13380109f0f53e/crates/blockifier/src/execution/cairo1_execution.rs#L324)):*
> ```XML
>             error_message: "Error extracting return data.".to_string()});
>     };
>     if gas < &Felt252::from(0) || gas > &Felt252::from(syscall_handler.call.initial_gas) {
> ```

This check is useless due to the new type limits



_Code quote:_
```XML
if gas < &Felt252::from(0)
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/676#-:-NZ0tNb8DGXFRWSt05FG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/676)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/676#-:-NZ1Rp3h8uCzIYZ-MTzu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Pull request merged**
