### PR TITLE
chore: release v0.5.0-rc.4

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1602)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
[Python side](https://reviewable.io/reviews/starkware-industries/starkware/34195)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1602#-:-NrpeKgi33zXzc_SJpQo:bi8mxiq)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1602)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`Cargo.toml` line 49 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1602#-Ns2hYGuDu2aVuKvwHzi:-Ns2hYGv9ePOl047YmIm:b-vre3hw) ([raw file](https://github.com/starkware-libs/blockifier/blob/365fb2ef2e83bde3ebaed7146064e4d53d4d765b/Cargo.toml#L49)):*
> ```TOML
> sha3 = "0.10.6"
> starknet-crypto = "0.5.1"
> starknet_api = "0.10.0-dev.2"
> ```

What were the changes between 0.8.0 to this?



_Code quote:_
```TOML
starknet_api = "0.10.0-dev.2"
```

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1602)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1602)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`Cargo.toml` line 49 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1602#-Ns2hYGuDu2aVuKvwHzi:-Ns3rcjgD1fiFheh022d:b-3ns6jg) ([raw file](https://github.com/starkware-libs/blockifier/blob/365fb2ef2e83bde3ebaed7146064e4d53d4d765b/Cargo.toml#L49)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What were the changes between 0.8.0 to this?
</blockquote></details>

I don't know actually

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1602)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
