### PR TITLE
Elin/merge main v0.12.3 into main

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1075)

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
> Reviewed 8 of 13 files at r1, 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1075)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1075)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/feature_contracts/cairo0/compiled/test_pair_skeleton_compiled.json` line 1433 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1075#-NiFDxl_2_0bxvm9t8dc:-NiFDxl_2_0bxvm9t8dd:b-vxorml) ([raw file](https://github.com/starkware-libs/blockifier/blob/32cea96e42c5bdf3792d0b49d468121915e6e7c4/crates/blockifier/feature_contracts/cairo0/compiled/test_pair_skeleton_compiled.json#L1433)):*
> ```JSON
>             },
>             "starkware.cairo.common.uint256.split_felt": {
>                 "destination": "starkware.cairo.common.math.split_felt",
> ```

It's an added functionality?



_Code quote:_
```JSON
            "starkware.cairo.common.uint256.split_felt": {
                "destination": "starkware.cairo.common.math.split_felt",
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1075)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo0/compiled/test_pair_skeleton_compiled.json` line 1433 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1075#-NiFDxl_2_0bxvm9t8dc:-NiFLVAnBa_xlqtdiz80:b-ylb0r0) ([raw file](https://github.com/starkware-libs/blockifier/blob/32cea96e42c5bdf3792d0b49d468121915e6e7c4/crates/blockifier/feature_contracts/cairo0/compiled/test_pair_skeleton_compiled.json#L1433)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It's an added functionality?
</blockquote></details>

No idea, what's this contract?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1075)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/feature_contracts/cairo0/compiled/test_pair_skeleton_compiled.json` line 1433 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1075#-NiFDxl_2_0bxvm9t8dc:-NiFMX_R7aOjrdwSGuZz:b-2hf78h) ([raw file](https://github.com/starkware-libs/blockifier/blob/32cea96e42c5bdf3792d0b49d468121915e6e7c4/crates/blockifier/feature_contracts/cairo0/compiled/test_pair_skeleton_compiled.json#L1433)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No idea, what's this contract?
</blockquote></details>

No idea. It is used in [this](https://github.com/starkware-libs/blockifier/blob/4db71ea89357e6496704fd0ae4fb0370ea449c30/crates/blockifier/src/fee/strk_gas_price/gas_price_test.rs#L72) test.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1075)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo0/compiled/test_pair_skeleton_compiled.json` line 1433 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1075#-NiFDxl_2_0bxvm9t8dc:-NiFZdGqCqNA9oh44kHS:b-o8wcpq) ([raw file](https://github.com/starkware-libs/blockifier/blob/32cea96e42c5bdf3792d0b49d468121915e6e7c4/crates/blockifier/feature_contracts/cairo0/compiled/test_pair_skeleton_compiled.json#L1433)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No idea. It is used in [this](https://github.com/starkware-libs/blockifier/blob/4db71ea89357e6496704fd0ae4fb0370ea449c30/crates/blockifier/src/fee/strk_gas_price/gas_price_test.rs#L72) test.
</blockquote></details>

Not sure when during compilation these scopes are added and why, but I guess it's okay.

**Review by noaov1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1075)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
