### PR TITLE
fix(concurrency): add the sequencer key when checking if the tx is

### PR DESCRIPTION
**Pull request by meship-starkware**
too big in concurrency mode

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 578 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-GHPkr3mJmYeOWBzON:-O-GHPks5dl9sXNJIFA1:bw736fm) ([raw file](https://github.com/starkware-libs/blockifier/blob/c26ebfb06a2a634f82bc0a52e2c319a4cc761b39/crates/blockifier/src/state/cached_state.rs#L578)):*
> ```XML
> pub struct StateChangesKeys {
>     nonce_keys: HashSet<ContractAddress>,
>     class_hash_keys: HashSet<ContractAddress>,
> ```

Im not sure changing this filed to pub(crate) is the right solution to add the sequencer balance key to the storage keys.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-GmAF8DeCLipyRMwba:-O-GmAF8DeCLipyRMwbb:bp1wjp0) ([raw file](https://github.com/starkware-libs/blockifier/blob/c26ebfb06a2a634f82bc0a52e2c319a4cc761b39/crates/blockifier/src/concurrency/worker_logic.rs#L225)):*
> ```XML
>         let mut execution_output = lock_mutex_in_array(&self.execution_outputs, tx_index);
>         let writes = &execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).writes;
>         let reads = &execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).reads;
> ```

It might be better to fix the sequencer balance before checking if it has a place in the bouncer. We just need to ensure that if the transaction fails because it has no space, we won't need to revert this change.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 578 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-GHPkr3mJmYeOWBzON:-O-H8zjS2nQ0fcnrzQw0:b-lt70u7) ([raw file](https://github.com/starkware-libs/blockifier/blob/c26ebfb06a2a634f82bc0a52e2c319a4cc761b39/crates/blockifier/src/state/cached_state.rs#L578)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Im not sure changing this filed to pub(crate) is the right solution to add the sequencer balance key to the storage keys.
</blockquote></details>

Instead, create a StateChangesKeys object and use `extend`
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 192 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-H9QMhEYF7S4xGh19D:-O-H9QMhEYF7S4xGh19E:bgj5aie) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a62cbc76661fbb11fe211e0e2ecaa071e3d1d68/crates/blockifier/src/transaction/transaction_execution.rs#L192)):*
> ```XML
>                 .storage_keys
>                 .insert((tx_context.fee_token_address(), sequencer_balance_low));
>         }
> ```

Share code with the worker logic.



_Code quote:_
```XML
        if block_context.concurrency_mode
            && block_context.block_info.sequencer_address != tx_context.tx_info.sender_address()
        {
            // Add the deleted sequencer balance key to the storage keys.
            let sequencer_balance_low =
                get_fee_token_var_address(block_context.block_info.sequencer_address);
            tx_state_changes_keys
                .storage_keys
                .insert((tx_context.fee_token_address(), sequencer_balance_low));
        }
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 578 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-GHPkr3mJmYeOWBzON:-O-V4DeEBP8n8IuPc0SM:b-qy5ydv) ([raw file](https://github.com/starkware-libs/blockifier/blob/c26ebfb06a2a634f82bc0a52e2c319a4cc761b39/crates/blockifier/src/state/cached_state.rs#L578)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Instead, create a StateChangesKeys object and use `extend`
</blockquote></details>

I tried using Extend by creating a new StateChangesKeys and using StateChangesKeys::default(), but it told me that I couldn't use the default because the fields are private.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 192 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-H9QMhEYF7S4xGh19D:-O-V8VQG09LUgmPACPMw:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8a62cbc76661fbb11fe211e0e2ecaa071e3d1d68/crates/blockifier/src/transaction/transaction_execution.rs#L192)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Share code with the worker logic.
</blockquote></details>

Done.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/state/cached_state.rs` line 623 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-VeiXI1w-oF54BAz-n:-O-VeiXI1w-oF54BAz-o:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f1fc430ce4528d7d863e7af9f89827e455b77a1/crates/blockifier/src/state/cached_state.rs#L623)):*
> ```XML
>     pub fn update_sequencer_key_in_storage(&mut self, tx_context: &TransactionContext) {
>         let seqencer_address = tx_context.block_context.block_info.sequencer_address;
>         let seqencer_is_sender = seqencer_address == tx_context.tx_info.sender_address();
> ```





_Suggestion:_
```XML
        let sequencer_address = tx_context.block_context.block_info.sequencer_address;
        let sequencer_is_sender = sequencer_address == tx_context.tx_info.sender_address();
```

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 623 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-VeiXI1w-oF54BAz-n:-O-VgyNF1N9vKNkYMivl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f1fc430ce4528d7d863e7af9f89827e455b77a1/crates/blockifier/src/state/cached_state.rs#L623)):*
> ```XML
>     pub fn update_sequencer_key_in_storage(&mut self, tx_context: &TransactionContext) {
>         let seqencer_address = tx_context.block_context.block_info.sequencer_address;
>         let seqencer_is_sender = seqencer_address == tx_context.tx_info.sender_address();
> ```

Done.

**Review by avi-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-:-O-Vhe8j5xDxADjvMc7x:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 621 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-WUhQ6238F5v2CV_T6:-O-WUhQ6238F5v2CV_T7:b-7ruu90) ([raw file](https://github.com/starkware-libs/blockifier/blob/641654857509f5705eaa2e07fec9bc26f4e46983/crates/blockifier/src/state/cached_state.rs#L621)):*
> ```XML
>     }
> 
>     pub fn update_sequencer_key_in_storage(&mut self, tx_context: &TransactionContext) {
> ```

Pass the fee, and add the key only if the fee is greater than zero



_Code quote:_
```XML
 pub fn update_sequencer_key_in_storage(&mut self, tx_context: &TransactionContext) 
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 623 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-WIyte7M2ph6rKPnB8:-O-WIyte7M2ph6rKPnB9:b-gtfan3) ([raw file](https://github.com/starkware-libs/blockifier/blob/641654857509f5705eaa2e07fec9bc26f4e46983/crates/blockifier/src/state/cached_state.rs#L623)):*
> ```XML
>     pub fn update_sequencer_key_in_storage(&mut self, tx_context: &TransactionContext) {
>         let sequencer_address = tx_context.block_context.block_info.sequencer_address;
>         let sequencer_is_sender = sequencer_address == tx_context.tx_info.sender_address();
> ```

Move this check to be a function of tx_context, and use it [here](https://github.com/starkware-libs/blockifier/blob/99527a30202264556d100fd41589a1f22f4abdb4/crates/blockifier/src/transaction/account_transaction.rs#L322) and in other places if there are



_Code quote:_
```XML
sequencer_address == tx_context.tx_info.sender_address()
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 625 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-WJkINBffWwTT65xYp:-O-WJkINBffWwTT65xYq:bdl4wlv) ([raw file](https://github.com/starkware-libs/blockifier/blob/641654857509f5705eaa2e07fec9bc26f4e46983/crates/blockifier/src/state/cached_state.rs#L625)):*
> ```XML
>         let sequencer_is_sender = sequencer_address == tx_context.tx_info.sender_address();
>         // Checks if we run in concurrency mode.
>         if tx_context.block_context.concurrency_mode && !sequencer_is_sender {
> ```

Comments are written in ציווי. Anyway, the comment does not help here.



_Suggestion:_
```XML
        if tx_context.block_context.concurrency_mode && !sequencer_is_sender {
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 180 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-WNx3Y2RD8qHjhqU20:-O-WNx3Z5L0gwNYYuBYW:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/641654857509f5705eaa2e07fec9bc26f4e46983/crates/blockifier/src/transaction/transaction_execution.rs#L180)):*
> ```XML
>         let tx_execution_summary = tx_execution_info.summarize();
>         let mut tx_state_changes_keys = state.get_actual_state_changes()?.into_keys();
>         tx_state_changes_keys.update_sequencer_key_in_storage(&tx_context);
> ```





_Suggestion:_
```XML
        // types, since now running Transaction::execute_raw is not identical to
        // AccountTransaction::execute_raw.
        let tx_execution_info = match self {
            Self::AccountTransaction(account_tx) => {
                account_tx.execute_raw(state, block_context, charge_fee, validate)?
            }
            Self::L1HandlerTransaction(tx) => {
                tx.execute_raw(state, block_context, charge_fee, validate)?
            }
        };

        // Check if the transaction is too large to fit any block.
        // TODO(Yoni, 1/8/2024): consider caching these two.
        let tx_execution_summary = tx_execution_info.summarize();
        let mut tx_state_changes_keys = state.get_actual_state_changes()?.into_keys();
        tx_state_changes_keys.update_sequencer_key_in_storage(&block_context.to_tx_context(self));
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 621 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-WUhQ6238F5v2CV_T6:-O-WV1D6AgSccLtbS7I4:bghzuia) ([raw file](https://github.com/starkware-libs/blockifier/blob/641654857509f5705eaa2e07fec9bc26f4e46983/crates/blockifier/src/state/cached_state.rs#L621)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Pass the fee, and add the key only if the fee is greater than zero
</blockquote></details>

Or the execution result, whatever is more convenient

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-:-O-_slAbBOmXI-HqbJlF:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/context.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-_sTEQ6hjKaDlXcsLB:-O-_sTER9uKq6JRnxB4c:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f5f75cf3d0e8d45986f328c4d202743a93709d42/crates/blockifier/src/context.rs#L21)):*
> ```XML
>         self.block_context.chain_info.fee_token_address(&self.tx_info.fee_type())
>     }
>     pub fn sequencer_is_the_sender(&self) -> bool {
> ```





_Suggestion:_
```XML
is_sequencer_the_sender
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 621 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-WUhQ6238F5v2CV_T6:-O-_lmPuAUFHylEZlJTF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/641654857509f5705eaa2e07fec9bc26f4e46983/crates/blockifier/src/state/cached_state.rs#L621)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Or the execution result, whatever is more convenient
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 623 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-WIyte7M2ph6rKPnB8:-O-_pLpZ42xuTvSdparm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/641654857509f5705eaa2e07fec9bc26f4e46983/crates/blockifier/src/state/cached_state.rs#L623)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Move this check to be a function of tx_context, and use it [here](https://github.com/starkware-libs/blockifier/blob/99527a30202264556d100fd41589a1f22f4abdb4/crates/blockifier/src/transaction/account_transaction.rs#L322) and in other places if there are
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 625 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-WJkINBffWwTT65xYp:-O-_fmHfDvnUrPOx42td:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/641654857509f5705eaa2e07fec9bc26f4e46983/crates/blockifier/src/state/cached_state.rs#L625)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Comments are written in ציווי. Anyway, the comment does not help here.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 180 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-WNx3Y2RD8qHjhqU20:-O-_fdjO3LKH9TOO_tZj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/641654857509f5705eaa2e07fec9bc26f4e46983/crates/blockifier/src/transaction/transaction_execution.rs#L180)):*
> ```XML
>         let tx_execution_summary = tx_execution_info.summarize();
>         let mut tx_state_changes_keys = state.get_actual_state_changes()?.into_keys();
>         tx_state_changes_keys.update_sequencer_key_in_storage(&tx_context);
> ```

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-:-O-a31ZbEhVacp6duBNv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 252 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-aTgqu0NAdxz2LQG_z:-O-aTgqu0NAdxz2LQGa-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f0bc0bae150696edbc3c581ea5ea21f1e7b998a/crates/blockifier/src/concurrency/worker_logic.rs#L252)):*
> ```XML
>             // Update the sequencer balance (in state + call info).
>             if tx_context.tx_info.sender_address()
>                 == self.block_context.block_info.sequencer_address
> ```





_Suggestion:_
```XML
            if tx_context.is_sequencer_the_sender()
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 252 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-aTgqu0NAdxz2LQG_z:-O-aXYt774K6DiXtGNH5:b-abem5c) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f0bc0bae150696edbc3c581ea5ea21f1e7b998a/crates/blockifier/src/concurrency/worker_logic.rs#L252)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we want to add `fee == 0` here as well?
</blockquote></details>

Better not to. You assume that fee==0 -> no fee transfer

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 252 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-aTgqu0NAdxz2LQG_z:-O-aYNZn5HfofkDbyLV2:b-ua467a) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f0bc0bae150696edbc3c581ea5ea21f1e7b998a/crates/blockifier/src/concurrency/worker_logic.rs#L252)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Better not to. You assume that fee==0 -> no fee transfer
</blockquote></details>

Which is true now but we gain nothing from this extra assumption here

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 252 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-O-aTgqu0NAdxz2LQG_z:-O-a_X14D0KPwdVfoAtz:b7ljyct) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f0bc0bae150696edbc3c581ea5ea21f1e7b998a/crates/blockifier/src/concurrency/worker_logic.rs#L252)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Which is true now but we gain nothing from this extra assumption here
</blockquote></details>

We will add the sequencer balance keys to the call info storage read values

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1980#-:-O-aafDD8jBGcJIsAos4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
