### PR TITLE
add invoke_tx test with storage operation

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1255)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1255)* status: all files reviewed, 11 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 339 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYo7J41muvS28jPVzT:-NlYo7J41muvS28jPVzU:b-8w7qf0) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L339)):*
> ```Cairo
> @external
> func advance_counter{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
>     index: felt, diffs_len: felt, diffs: felt*
> ```

why `felt*` and not explicit felts...? genuine question



_Suggestion:_
```Cairo
diff_0: felt, diff_1: felt
```
___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 345 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYnuPJ-JgAcD0DZDus:-NlYnuPJ-JgAcD0DZDut:b-7ev9qo) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L345)):*
> ```Cairo
>     two_counters.write(index, (val[0] + diffs[0], val[1] + diffs[1]));
>     return ();
> }
> ```

add newline



_Suggestion:_
```Cairo
}
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 452 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYoLxABVpOwB3GBXQP:-NlYoLxABVpOwB3GBXQQ:bb8sx7m) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L452)):*
> ```XML
> }
> 
> // Verifies the storage after each invoke execution in test_invoke_tx_advanced_operations
> ```

end with `.`



_Suggestion:_
```XML
test_invoke_tx_advanced_operations.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 459 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYoiQQ5AmcaR40nVcJ:-NlYoiQQ5AmcaR40nVcK:bnjst20) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L459)):*
> ```XML
>     index: StarkFelt,
>     expected_counters: [StarkFelt; 2],
>     expected_ec_point: [StarkFelt; 2],
> ```

no need in this PR, delete



_Code quote:_
```XML
expected_ec_point: [StarkFelt; 2],
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 460 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYoltE9B44qihF-HKQ:-NlYoltE9B44qihF-HKR:bmtz33p) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L460)):*
> ```XML
>     expected_counters: [StarkFelt; 2],
>     expected_ec_point: [StarkFelt; 2],
>     last_used_nonce: Nonce,
> ```

no need to verify nonce; we have separate tests for this (right?)



_Code quote:_
```XML
last_used_nonce: Nonce,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 475 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYp-313N_jZHlQoDmO:-NlYp-313N_jZHlQoDmP:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L475)):*
> ```XML
>     let key = next_storage_key(&key).unwrap();
>     let value = state.get_storage_at(contract_address, key).unwrap();
>     assert_eq!(value, expected_ec_point[1]);
> ```

delete



_Code quote:_
```XML
    // Verify the ec_point values in storage.
    let key = get_storage_var_address("ec_point", &[]);
    let value = state.get_storage_at(contract_address, key).unwrap();
    assert_eq!(value, expected_ec_point[0]);
    let key = next_storage_key(&key).unwrap();
    let value = state.get_storage_at(contract_address, key).unwrap();
    assert_eq!(value, expected_ec_point[1]);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 478 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYorU_0iV7flY3lefN:-NlYorU_0iV7flY3lefO:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L478)):*
> ```XML
>     // Verify the nonce value in storage.
>     let nonce_from_state = state.get_nonce_at(account_address).unwrap();
>     assert_eq!(nonce_from_state, last_used_nonce.try_increment().unwrap());
> ```

delete



_Code quote:_
```XML
    // Verify the nonce value in storage.
    let nonce_from_state = state.get_nonce_at(account_address).unwrap();
    assert_eq!(nonce_from_state, last_used_nonce.try_increment().unwrap());
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 493 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYpA4h79nD8H0_QEbv:-NlYpA4h79nD8H0_QEbw:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L493)):*
> ```XML
> 
>     // Invoke advance_counter function.
>     let nonce = Nonce::default();
> ```





_Suggestion:_
```XML
let mut nonce_manager = NonceManager::default();
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 497 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYpEgS3vRwS_idauWx:-NlYpEgS3vRwS_idauWy:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L497)):*
> ```XML
>     let counter_diffs = [101_u32, 102_u32];
>     let initial_counters = [stark_felt!(counter_diffs[0]), stark_felt!(counter_diffs[1])];
>     let initial_ec_point = [StarkFelt::ZERO, StarkFelt::ZERO];
> ```

delete



_Code quote:_
```XML
let initial_ec_point = [StarkFelt::ZERO, StarkFelt::ZERO];
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 502 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYpJXK81sQfmYZVEcG:-NlYpJXK81sQfmYZVEcH:b-q569xe) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L502)):*
> ```XML
>     let invoke_tx_args = invoke_tx_args!(
>         max_fee: Fee(MAX_FEE),
>         nonce,
> ```

use nonce manager



_Suggestion:_
```XML
nonce: nonce_manager.next(sender_address),
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 508 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYpTAz5meWc3Qow60Y:-NlYpTAz5meWc3Qow60Z:b-kaozf) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L508)):*
> ```XML
>     );
>     let tx = AccountTransaction::Invoke(invoke_tx(invoke_tx_args.clone()));
>     tx.execute(state, block_context, true, true).unwrap();
> ```

1. use `account_invoke_tx` function
2. by convention we use `invoke_tx_args! {}` with curly braces (like initializing a struct)



_Suggestion:_
```XML
    let account_tx = account_invoke_tx(invoke_tx_args! {
        max_fee: Fee(MAX_FEE),
        nonce,
        sender_address,
        calldata:
            create_calldata(contract_address, "advance_counter", &calldata_args),
    });
    account_tx.execute(state, block_context, true, true).unwrap();
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1255)* status: 0 of 3 files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 460 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYoltE9B44qihF-HKQ:-Nlb7u8nByXCeaGH9xzB:b6j21j0) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L460)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need to verify nonce; we have separate tests for this (right?)
</blockquote></details>

I see it is checked in test_invoke_tx, test_deploy_account_tx, test_declare_tx, test_revert_invoke. But in all of them the nonce is only increased by 1. is that good enough?  I get to 4 in my test :)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 475 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYp-313N_jZHlQoDmO:-Nlb8olB9gxjoIH0aAMR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L475)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 478 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYorU_0iV7flY3lefN:-Nlb9K_b-j4i06BepciY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L478)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 493 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYpA4h79nD8H0_QEbv:-Nlb9evE2mlc4PqIKvSd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L493)):*
> ```XML
> 
>     // Invoke advance_counter function.
>     let nonce = Nonce::default();
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 497 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYpEgS3vRwS_idauWx:-Nlb9MU_9Y3fZxRvoeN8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L497)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 502 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYpJXK81sQfmYZVEcG:-Nlb9fM11nY4xCqJ0RCf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L502)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use nonce manager
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 508 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYpTAz5meWc3Qow60Y:-NlbA8fj0WZiYT50uzCM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L508)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. use `account_invoke_tx` function
2. by convention we use `invoke_tx_args! {}` with curly braces (like initializing a struct)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1255)* status: all files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 339 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlbK2QR64wCAY3GxAu-:-NlbK2QR64wCAY3GxAu0:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1c60de0ca9eb6f06099e96cab5b9613e6fba2fa/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L339)):*
> ```Cairo
> @external
> func advance_counter{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
>     index: felt, diffs_len: felt, diff_0: felt, diff_1: felt
> ```

delete



_Code quote:_
```Cairo
diffs_len: felt
```
___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 341 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlbK3b34iEuZ0q0kbyr:-NlbK3b34iEuZ0q0kbys:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1c60de0ca9eb6f06099e96cab5b9613e6fba2fa/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L341)):*
> ```Cairo
>     index: felt, diffs_len: felt, diff_0: felt, diff_1: felt
> ) {
>     assert diffs_len = 2;
> ```

delete



_Code quote:_
```Cairo
assert diffs_len = 2;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 460 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYoltE9B44qihF-HKQ:-NlbKJ8P1NP6YzljPCrp:bo38gy9) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L460)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I see it is checked in test_invoke_tx, test_deploy_account_tx, test_declare_tx, test_revert_invoke. But in all of them the nonce is only increased by 1. is that good enough?  I get to 4 in my test :)
</blockquote></details>

ah... sorry
then please pass `expected_nonce` explicitly, without `try_increment`
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 478 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYorU_0iV7flY3lefN:-NlbKT-o9RcdWg6Sq1dD:b9vkd4z) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L478)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

revert change (see above)... sorry
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 481 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlbK_dx06ByTLfoQOEC:-NlbK_dx06ByTLfoQOED:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1c60de0ca9eb6f06099e96cab5b9613e6fba2fa/crates/blockifier/src/transaction/transactions_test.rs#L481)):*
> ```XML
>     // Invoke advance_counter function.
>     let mut nonce_manager = NonceManager::default();
>     let len = stark_felt!(2_u8);
> ```

delete



_Code quote:_
```XML
let len = stark_felt!(2_u8);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 484 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlbKZMjCLXvB8rqSBHO:-NlbKZMjCLXvB8rqSBHP:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1c60de0ca9eb6f06099e96cab5b9613e6fba2fa/crates/blockifier/src/transaction/transactions_test.rs#L484)):*
> ```XML
>     let counter_diffs = [101_u32, 102_u32];
>     let initial_counters = [stark_felt!(counter_diffs[0]), stark_felt!(counter_diffs[1])];
>     let calldata_args = vec![index, len, initial_counters[0], initial_counters[1]];
> ```

delete



_Code quote:_
```XML
len, 
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1255)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 339 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYo7J41muvS28jPVzT:-NlbL8YG69m3hlcM96IK:barc1tv) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L339)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why `felt*` and not explicit felts...? genuine question
</blockquote></details>

hmmm, copied from the python version, I agree that this is better
___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 339 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlbK2QR64wCAY3GxAu-:-NlbLSHu7IzdC9-YzzNW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1c60de0ca9eb6f06099e96cab5b9613e6fba2fa/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L339)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 341 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlbK3b34iEuZ0q0kbyr:-NlbLTfGDmsTbGxN4iLY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1c60de0ca9eb6f06099e96cab5b9613e6fba2fa/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L341)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 460 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYoltE9B44qihF-HKQ:-NlbNLySAY0K9wAybiAK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L460)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah... sorry
then please pass `expected_nonce` explicitly, without `try_increment`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 478 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlYorU_0iV7flY3lefN:-NlbNKz39px11CSYzTje:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a859ee1fd23e758f5a2aca4570310f02fe1a4485/crates/blockifier/src/transaction/transactions_test.rs#L478)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

revert change (see above)... sorry
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 481 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlbK_dx06ByTLfoQOEC:-NlbLvTe9w0Lak63sOuG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1c60de0ca9eb6f06099e96cab5b9613e6fba2fa/crates/blockifier/src/transaction/transactions_test.rs#L481)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 484 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlbKZMjCLXvB8rqSBHO:-NlbLvIU-2Xsrlji6s3J:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1c60de0ca9eb6f06099e96cab5b9613e6fba2fa/crates/blockifier/src/transaction/transactions_test.rs#L484)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1255)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlbhzOg9pqZChiZP87Z:-NlbhzOg9pqZChiZP87_:b9h396b) ([raw file](https://github.com/starkware-libs/blockifier/blob/b2dc433411788b113bf23d967084961ec99d5a7e/crates/blockifier/src/test_utils.rs#L155)):*
> ```XML
>         let next_felt252 = self.next_nonce.get(&account_address).unwrap_or(&zero);
>         Nonce(felt_to_stark_felt(next_felt252))
>     }
> ```

please define a `top` (private) utillity method for this... already have the same `let zero = ` logic in two places, now three :)



_Suggestion:_
```XML
    fn top(&self, account_address: &ContractAddress) -> Felt252 {
        let zero = Felt252::zero();
        self.next_nonce.get(account_address).unwrap_or(&zero)
    }

    pub fn next(&mut self, account_address: ContractAddress) -> Nonce {
        let next_felt252 = self.top(account_address);
        let next = Nonce(felt_to_stark_felt(next_felt252));
        self.next_nonce.insert(account_address, Felt252::one() + next_felt252);
        next
    }

    /// Decrements the nonce of the account, unless it is zero.
    pub fn rollback(&mut self, account_address: ContractAddress) {
        let current = self.top(&account_address);
        if !current.is_zero() {
            self.next_nonce.insert(account_address, current - 1);
        }
    }

    pub fn query_next(&self, account_address: ContractAddress) -> Nonce {
        Nonce(felt_to_stark_felt(self.top(&account_address)))
    }
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 505 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-Nlbii05D65ThgJiwqs4:-Nlbii05D65ThgJiwqs5:b63sc5j) ([raw file](https://github.com/starkware-libs/blockifier/blob/b2dc433411788b113bf23d967084961ec99d5a7e/crates/blockifier/src/transaction/transactions_test.rs#L505)):*
> ```XML
>         index,
>         initial_counters,
>         nonce_manager.query_next(account_address),
> ```

can you get the nonce from the `account_tx` (before calling `execute`)?
that way you won't need to implement `query_next`



_Code quote:_
```XML
nonce_manager.query_next(account_address)
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1255)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 505 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-Nlbii05D65ThgJiwqs4:-NlblXId9qZR4dRZPOhM:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/b2dc433411788b113bf23d967084961ec99d5a7e/crates/blockifier/src/transaction/transactions_test.rs#L505)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you get the nonce from the `account_tx` (before calling `execute`)?
that way you won't need to implement `query_next`
</blockquote></details>

done
___
*[`crates/blockifier/src/test_utils.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-NlbhzOg9pqZChiZP87Z:-NlblZJ8BWcsm_dKSUcG:bh37z1y) ([raw file](https://github.com/starkware-libs/blockifier/blob/b2dc433411788b113bf23d967084961ec99d5a7e/crates/blockifier/src/test_utils.rs#L155)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please define a `top` (private) utillity method for this... already have the same `let zero = ` logic in two places, now three :)
</blockquote></details>

deleted query_next

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1255#-:-Nlc4jkG4puIs_gFB7Jd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1255)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
