### PR TITLE
Test deprecated syscalls of type get_block_info in validate mode.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1016)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1016)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1016#-NhN76rO4ZMmRcKn9zbS:-NhN76rO4ZMmRcKn9zbT:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/040653ea25619f1bbcc491e8bb58f71c67abdeaa/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L347)):*
> ```XML
>     ExecutionMode::Validate, "sequencer_address" ;
>     "Test the syscall get_sequencer_address in execution mode Validate")]
> fn test_syscall_get_type_of_block_info(
> ```





_Suggestion:_
```XML
fn test_block_info_syscalls(
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1016#-NhN7KHZ6VBZrLPBwX06:-NhN7KHZ6VBZrLPBwX07:b55nr5m) ([raw file](https://github.com/starkware-libs/blockifier/blob/040653ea25619f1bbcc491e8bb58f71c67abdeaa/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L369)):*
> ```XML
>         }
>         _ => panic!("Unexpected block info member name: {}", block_info_member_name),
>     };
> ```

Let's make it a bit shorter (using those default values is the same as creating the default block info)



_Suggestion:_
```XML
#[test_case(
    ExecutionMode::Execute, "block_number", stark_felt!(CURRENT_BLOCK_NUMBER);
    "Test the syscall get_block_number in execution mode Execute")]
#[test_case(
    ExecutionMode::Validate, "block_number", stark_felt!(0_u16);
    "Test the syscall get_block_number in execution mode Validate")]
#[test_case(
    ExecutionMode::Execute, "block_timestamp", stark_felt!(CURRENT_BLOCK_TIMESTAMP);
    "Test the syscall get_block_timestamp in execution mode Execute")]
#[test_case(
    ExecutionMode::Validate, "block_timestamp", stark_felt!(0_u16);
    "Test the syscall get_block_timestamp in execution mode Validate")]
#[test_case(
    ExecutionMode::Execute, "sequencer_address", stark_felt!(TEST_SEQUENCER_ADDRESS);
    "Test the syscall get_sequencer_address in execution mode Execute")]
#[test_case(
    ExecutionMode::Validate, stark_felt!(0_u16);
    "Test the syscall get_sequencer_address in execution mode Validate")]
fn test_syscall_get_type_of_block_info(
    execution_mode: ExecutionMode, 
    block_info_member_name: &str, 
    block_info_memmber: StarkFelt,
) {
    let mut state = deprecated_create_test_state();
    // Create a block context with known parameters. These parameters match the block context used
    // in the method execute_directly.
    let block_context = BlockContext::create_for_testing();
    let calldata = calldata![block_info_memeber]
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 383 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1016#-NhN6Sxn3ZTkU3oLUEch:-NhN6SxoBQwMN83owZwa:b-e3y4fh) ([raw file](https://github.com/starkware-libs/blockifier/blob/040653ea25619f1bbcc491e8bb58f71c67abdeaa/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L383)):*
> ```XML
>     } else {
>         // Test that the syscall is not available in validation mode.
>         let error = entry_point_call.execute_directly_in_validate_mode(&mut state).unwrap_err();
> ```

Start with `Validate`, which is the only mode with meaning in this context
(maybe we will have other modes, such as `Fee`)



_Code quote:_
```XML
    if execution_mode == ExecutionMode::Execute {
        // Test that the syscall is available in execution mode.
        assert_eq!(
            entry_point_call.execute_directly(&mut state).unwrap().execution,
            CallExecution::from_retdata(retdata![])
        );
    } else {
        // Test that the syscall is not available in validation mode.
        let error = entry_point_call.execute_directly_in_validate_mode(&mut state).unwrap_err();
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1016)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1016#-NhN76rO4ZMmRcKn9zbS:-NhOFxqf5RF_NySKkprM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/040653ea25619f1bbcc491e8bb58f71c67abdeaa/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L347)):*
> ```XML
>     ExecutionMode::Validate, "sequencer_address" ;
>     "Test the syscall get_sequencer_address in execution mode Validate")]
> fn test_syscall_get_type_of_block_info(
> ```

Done.
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1016#-NhN7KHZ6VBZrLPBwX06:-NhOKBxADjJR3-m2SOij:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/040653ea25619f1bbcc491e8bb58f71c67abdeaa/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L369)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Let's make it a bit shorter (using those default values is the same as creating the default block info)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 383 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1016#-NhN6Sxn3ZTkU3oLUEch:-NhOJqTnB1q8V0NbmvKi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/040653ea25619f1bbcc491e8bb58f71c67abdeaa/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L383)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Start with `Validate`, which is the only mode with meaning in this context
(maybe we will have other modes, such as `Fee`)
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1016#-:-NhPkiWm7vp13xpAjbkU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1016#-:-NhQI9Mc5bXf7YoU2t0z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1016)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
