### PR TITLE
Added strk_l1_gas_price to PyBlockInfo & BlockContext.

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/868)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
@giladchase 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/868#-:-Nd9wnR-8o1j9vPGe2pn:b-m113j0)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@giladchase 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/868#-:-NdAu-8ADEXTp24VS_LK:b-uvtt1u)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/868)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/blockifier/src/block_context.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/868#-NdOb0GTCw2pOEwWCWup:-NdOb0GTCw2pOEwWCWuq:bgqcj8o) ([raw file](https://github.com/starkware-libs/blockifier/blob/792caf2b95cad0e47c5da3aee18ab7aedd327137/crates/blockifier/src/block_context.rs#L19)):*
> ```XML
>     pub vm_resource_fee_cost: Arc<HashMap<String, f64>>,
>     pub gas_price: u128, // In wei.
>     // TODO(Amos, 01/09/2023): NEW_TOKEN_SUPPORT use this for V3 txs.
> ```

For future reference, can you plz explain what you mean by this TODO?



_Code quote:_
```XML
    // TODO(Amos, 01/09/2023): NEW_TOKEN_SUPPORT use this for V3 txs.
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/868#-NdOdmpFExmuMB6eC32e:-NdOdmpFExmuMB6eC32f:bbgauhv) ([raw file](https://github.com/starkware-libs/blockifier/blob/792caf2b95cad0e47c5da3aee18ab7aedd327137/crates/native_blockifier/src/py_state_diff.rs#L122)):*
> ```XML
>     pub block_timestamp: u64,
>     pub gas_price: u128,
>     pub strk_l1_gas_price: u128,
> ```

Looks like this field will be not well-defined for non-v3 txs, which is somewhat problematic in rust (it's similar to "no undefined fields").

There are alternatives to this though, the simplest one is to make it an `Option`, which is clear but will require "unwrap"ing the value everywhere.

Here are two other options that are somewhat more elegant, but could be overkill (though that depends on how these will be used).

1) use enums and structs:
```rust
// v2v1v0 is kind of long, maybe instead of V3/V2V1V0 use Current/Legacy?
enum Fees {
    V2V1V0(V2V1V0Fees) 
    V3(V3Fees), 

// Aגג `impl Deref` here to make this easier to handle.
struct V2V1V0Fees {`
    gas_price: i32,
}

struct V3Fees {
    gas_price: i32,
    strk_gas_price: i32,
}

PyBlockInfo {
  pub fees: Fees // this will require a custom `FromPyObject` to create if the Python side doesn't mirror this structure.
  ...
}
```
Biggest problem with this one is that it'll most likely require `match`ing everywhere.

2) use Traits:
```rust
trait FeeProvider {
    fn gas_price(&self) -> i32;
}

struct LegacyFees {
    gas_price: i32,
}

impl FeeProvider for LegacyFees {
    fn gas_price(&self) -> i32 { self.gas_price }
}

struct Fees {
    gas_price: i32,
    strk_gas_price: i32,
}

impl Fees {
  ...<strk_gas_price related stuff>
}

impl FeeProvider for Fees {
    fn gas_price(&self) -> i32 { self.gas_price }
}

// Might require a custom `FromPyObject`.
// Maybe define as `struct PyBlockInfo<F: FeeProvider = Fees>` if it makes the code nicer.
struct PyBlockInfo<F: FeeProvider> {
    fees: F,
    ...
}
```
Only problem here (other than possible over-engineering) is the duplication in the gas_price impl.

Also adding @elintul here in case she has a preference.



_Code quote:_
```XML
    pub strk_l1_gas_price: u128,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/868)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @elintul)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/868#-NdOdmpFExmuMB6eC32e:-NdP_hcA1A_rVxp4PfAZ:b9cqic4) ([raw file](https://github.com/starkware-libs/blockifier/blob/792caf2b95cad0e47c5da3aee18ab7aedd327137/crates/native_blockifier/src/py_state_diff.rs#L122)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Looks like this field will be not well-defined for non-v3 txs, which is somewhat problematic in rust (it's similar to "no undefined fields").

There are alternatives to this though, the simplest one is to make it an `Option`, which is clear but will require "unwrap"ing the value everywhere.

Here are two other options that are somewhat more elegant, but could be overkill (though that depends on how these will be used).

1) use enums and structs:
```rust
// v2v1v0 is kind of long, maybe instead of V3/V2V1V0 use Current/Legacy?
enum Fees {
    V2V1V0(V2V1V0Fees) 
    V3(V3Fees), 

// Aגג `impl Deref` here to make this easier to handle.
struct V2V1V0Fees {`
    gas_price: i32,
}

struct V3Fees {
    gas_price: i32,
    strk_gas_price: i32,
}

PyBlockInfo {
  pub fees: Fees // this will require a custom `FromPyObject` to create if the Python side doesn't mirror this structure.
  ...
}
```
Biggest problem with this one is that it'll most likely require `match`ing everywhere.

2) use Traits:
```rust
trait FeeProvider {
    fn gas_price(&self) -> i32;
}

struct LegacyFees {
    gas_price: i32,
}

impl FeeProvider for LegacyFees {
    fn gas_price(&self) -> i32 { self.gas_price }
}

struct Fees {
    gas_price: i32,
    strk_gas_price: i32,
}

impl Fees {
  ...<strk_gas_price related stuff>
}

impl FeeProvider for Fees {
    fn gas_price(&self) -> i32 { self.gas_price }
}

// Might require a custom `FromPyObject`.
// Maybe define as `struct PyBlockInfo<F: FeeProvider = Fees>` if it makes the code nicer.
struct PyBlockInfo<F: FeeProvider> {
    fees: F,
    ...
}
```
Only problem here (other than possible over-engineering) is the duplication in the gas_price impl.

Also adding @elintul here in case she has a preference.
</blockquote></details>

Not sure what the problem is...
This is the BlockInfo from python side.
Maybe [this](https://reviewable.io/reviews/starkware-libs/blockifier/847) is what you mean?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/868)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/868#-NdOdmpFExmuMB6eC32e:-NdPvoch0eiGWjzGI8kB:b-yu03oz) ([raw file](https://github.com/starkware-libs/blockifier/blob/792caf2b95cad0e47c5da3aee18ab7aedd327137/crates/native_blockifier/src/py_state_diff.rs#L122)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Not sure what the problem is...
This is the BlockInfo from python side.
Maybe [this](https://reviewable.io/reviews/starkware-libs/blockifier/847) is what you mean?
</blockquote></details>

I was mistaken, unblocking.
I though `strk_l1_gas_price` was undefined sometimes, but that isn't the case, just unused (which is also a problem'ish but much less serious).

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/868)* status: 0 of 4 files reviewed, all discussions resolved

___
*[`crates/blockifier/src/block_context.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/868#-NdOb0GTCw2pOEwWCWup:-NdQWMAy0G-utDJUe_cz:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/792caf2b95cad0e47c5da3aee18ab7aedd327137/crates/blockifier/src/block_context.rs#L19)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

For future reference, can you plz explain what you mean by this TODO?
</blockquote></details>

Done

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/868#-:-NdU2IawC0hZRGvkMIHV:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
