### PR TITLE
Refactor: add `StateContext`

### PR DESCRIPTION
**Pull request by giladchase**
Bundle 3 commonly used variables into a context instance.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/333)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/333)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NPzuhgW1C40mPo6Dc-9:-NPzuhgW1C40mPo6Dc-A:b6nyydn) ([raw file](https://github.com/starkware-libs/blockifier/blob/684561012e9f1613b7c075a84bc5d8e08e8e6b14/crates/blockifier/src/execution/entry_point.rs#L69)):*
> ```XML
> }
> 
> pub struct StateContext<'a> {
> ```

Let's rename the other `ExecutionContext` to... `VmExecutionContext`?.
Add a short docstring, move above `EntryPoint`.
Also, note `ExecutionResourcesManager` is not yet defined. Not fond of this name, I'd like `ExecutionResources`, but it's taken by `cairo-rs`. Maybe we can import theirs `as VmExecutionResources`? 



_Suggestion:_
```XML
pub struct ExecutionContext<'a>
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/333)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NPzuhgW1C40mPo6Dc-9:-NQ-19y8D1xtQP06TV0d:b-8vgk0g) ([raw file](https://github.com/starkware-libs/blockifier/blob/684561012e9f1613b7c075a84bc5d8e08e8e6b14/crates/blockifier/src/execution/entry_point.rs#L69)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's rename the other `ExecutionContext` to... `VmExecutionContext`?.
Add a short docstring, move above `EntryPoint`.
Also, note `ExecutionResourcesManager` is not yet defined. Not fond of this name, I'd like `ExecutionResources`, but it's taken by `cairo-rs`. Maybe we can import theirs `as VmExecutionResources`? 
</blockquote></details>


Renaming already merged into your branch in a separate PR (rebased it here).

Done on the rest.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/333)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NQ-XnUkElKV4mbWqjpJ:-NQ-XnUkElKV4mbWqjpK:bq1dn4f) ([raw file](https://github.com/starkware-libs/blockifier/blob/522b7b339cc34f11471bb43d4a53ae83a41670d1/crates/blockifier/src/transaction/transactions.rs#L58)):*
> ```XML
> }
> 
> pub trait Executable {
> ```

no longer generic? is this intentional?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/333)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NQ-btkRBZ7sUC3HdU2d:-NQ-btkRBZ7sUC3HdU2e:bu66167) ([raw file](https://github.com/starkware-libs/blockifier/blob/522b7b339cc34f11471bb43d4a53ae83a41670d1/crates/blockifier/src/execution/entry_point.rs#L24)):*
> ```XML
> 
> // Contains common information used throughout the execution of a block.
> pub struct ExecutionContext<'a> {
> ```

Shouldn't this be generic of `S: State`?



_Code quote:_
```XML
ExecutionContext<'a> 
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NQ-bg2a5pt1X7Isp6ZW:-NQ-bg2a5pt1X7Isp6ZX:b-wuu0vj) ([raw file](https://github.com/starkware-libs/blockifier/blob/522b7b339cc34f11471bb43d4a53ae83a41670d1/crates/blockifier/src/execution/entry_point.rs#L50)):*
> ```XML
> 
> impl CallEntryPoint {
>     pub fn execute(self, ctx: &mut ExecutionContext<'_>) -> EntryPointExecutionResult<CallInfo> {
> ```

Don't like abbreviations... :(



_Suggestion:_
```XML
context
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/333)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NQ-btkRBZ7sUC3HdU2d:-NQ-vZA66ZxiLrZXDal9:bo1zr9z) ([raw file](https://github.com/starkware-libs/blockifier/blob/522b7b339cc34f11471bb43d4a53ae83a41670d1/crates/blockifier/src/execution/entry_point.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Shouldn't this be generic of `S: State`?
</blockquote></details>

Since we're using `dyn State` (that was the type of the `state` param that we passed everywhere), it isn't necessary.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NQ-bg2a5pt1X7Isp6ZW:-NQ-w8ER8IwlSRj7XJS5:bo0u3g7) ([raw file](https://github.com/starkware-libs/blockifier/blob/522b7b339cc34f11471bb43d4a53ae83a41670d1/crates/blockifier/src/execution/entry_point.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Don't like abbreviations... :(
</blockquote></details>

ya ya i was wondering if `ctx` could squeeze by :sweat_smile: 
___
*[`crates/blockifier/src/transaction/transactions.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NQ-XnUkElKV4mbWqjpJ:-NQ-wTAm3aCQ5SQF1DQk:bsltpft) ([raw file](https://github.com/starkware-libs/blockifier/blob/522b7b339cc34f11471bb43d4a53ae83a41670d1/crates/blockifier/src/transaction/transactions.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no longer generic? is this intentional?
</blockquote></details>

Yep, because the `State` type is not inside `ExecutionContext`, which holds it as a `dyn State` (therefore no longer needing a generic).

I'm not sure why the `state` arg was passed as a `dyn State` in other places, but I kept it that way to keep things consistent.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/333)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/333)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NQ-btkRBZ7sUC3HdU2d:-NQK08HU712fbReHnRV-:b-spro0f) ([raw file](https://github.com/starkware-libs/blockifier/blob/522b7b339cc34f11471bb43d4a53ae83a41670d1/crates/blockifier/src/execution/entry_point.rs#L24)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Since we're using `dyn State` (that was the type of the `state` param that we passed everywhere), it isn't necessary.
</blockquote></details>

Can we make it generic of `S: State` and lose the `dyn`?
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NQK-80QDCwrHBU9ApXG:-NQK-80R0CTuxj0JYJnw:b-2nskeg) ([raw file](https://github.com/starkware-libs/blockifier/blob/c0d6038c15d4e5a6a1831fb094ed054b50284e8a/crates/blockifier/src/execution/execution_utils.rs#L37)):*
> ```XML
> pub mod test;
> 
> pub struct VmExecutionContext<'a, 'b> {
> ```

Why two lifetime parameters? It's supposed to be the same one.



_Code quote:_
```XML
<'a, 'b>
```

**Review by giladchase — COMMENTED** [review]
@elin I rebased over main, not taking ExecutionResources for now, as discussed offline.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/333#-:-NQKwzvK3oiy2VcFYbhV:bccwed0)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NQK-80QDCwrHBU9ApXG:-NQKy1aT6KeTah3UeZlP:b-tn97ec) ([raw file](https://github.com/starkware-libs/blockifier/blob/c0d6038c15d4e5a6a1831fb094ed054b50284e8a/crates/blockifier/src/execution/execution_utils.rs#L37)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why two lifetime parameters? It's supposed to be the same one.
</blockquote></details>

As discussed offline, we'll refactor this later.

The reason we need this at the moment is due to places like `execute_raw` in `account_transaction.rs`, which have multiple mutable refs that have lifetime issues.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/333)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/333#-NQ-btkRBZ7sUC3HdU2d:-NQL-AhtEkVBDjiw0d3o:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/522b7b339cc34f11471bb43d4a53ae83a41670d1/crates/blockifier/src/execution/entry_point.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we make it generic of `S: State` and lose the `dyn`?
</blockquote></details>

Done.

**Pull request closed without merging**
