### PR TITLE
Implemented finalize()

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@starkware.co>

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/278)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/278)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/278#-NOIpNOMBe4dIG32GKaI:-NOIpNOMBe4dIG32GKaJ:b-xe8248) ([raw file](https://github.com/starkware-libs/blockifier/blob/819fee6f51184db91a827f2f020395c9bb7aa825/crates/native_blockifier/src/py_transaction.rs#L194)):*
> ```XML
>     }
> 
>     /// Return the current state as a diff from the empty state.
> ```

I think this docstring should move to `CachedState`'s `to_state_diff()` instead.
Here you can say: `// Returns the state diff resulting in executing transactions.`. 

It should return `PyStateDiff` (not sure Gilad implemented this direction).



_Suggestion:_
```XML
    /// Returns the current state writes as a diff from the reader.
    pub fn finalize(&mut self) -> PyStateDiff {...}
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/278)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/278#-NOIpNOMBe4dIG32GKaI:-NOIs39FCvVdpY7GGcml:b-e7f4v9) ([raw file](https://github.com/starkware-libs/blockifier/blob/819fee6f51184db91a827f2f020395c9bb7aa825/crates/native_blockifier/src/py_transaction.rs#L194)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think this docstring should move to `CachedState`'s `to_state_diff()` instead.
Here you can say: `// Returns the state diff resulting in executing transactions.`. 

It should return `PyStateDiff` (not sure Gilad implemented this direction).
</blockquote></details>

@giladchase, is this direction easy? Perhaps Dori can take it if you haven't started.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/278)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/278#-NOIpNOMBe4dIG32GKaI:-NOJgFxr8ZIZK-Qd3xLp:bv0oupj) ([raw file](https://github.com/starkware-libs/blockifier/blob/819fee6f51184db91a827f2f020395c9bb7aa825/crates/native_blockifier/src/py_transaction.rs#L194)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@giladchase, is this direction easy? Perhaps Dori can take it if you haven't started.
</blockquote></details>

1. Gilad started
2. I think it should return `StateDiff`, and implement `IntoPy<PyStateDiff> for StateDiff` separately; that way the signature remains rusty. WDYT?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/278)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/278#-NOIpNOMBe4dIG32GKaI:-NOJmi-QEVzVHBXv37Ss:b-5pdixz) ([raw file](https://github.com/starkware-libs/blockifier/blob/819fee6f51184db91a827f2f020395c9bb7aa825/crates/native_blockifier/src/py_transaction.rs#L194)):*
> /// Returns the current state writes as a diff from the reader.
Can you add this as docstring to `CachedState.to_state_diff()`?

Re the types: `PyStateDiff` is Rusty.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/278)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/278#-NOIpNOMBe4dIG32GKaI:-NOK0Fj2-hlyKAr2m0y5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/819fee6f51184db91a827f2f020395c9bb7aa825/crates/native_blockifier/src/py_transaction.rs#L194)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

> /// Returns the current state writes as a diff from the reader.
Can you add this as docstring to `CachedState.to_state_diff()`?

Re the types: `PyStateDiff` is Rusty.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/278#-:-NOKLSLm1gDB6nRfYqxO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
