### PR TITLE
chore: explicit filenames for versioned constants, and a softlink to …

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
…the current

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1749)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/resources/versioned_constants.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1749#-NuSejI2EC5zYpqSrhgX:-NuSejI2EC5zYpqSrhgY:b-6ssa39) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a6adfa79e88a4e3fc7164231b3f8535182d1ee1/crates/blockifier/resources/versioned_constants.json#L1)):*
> ```JSON
> versioned_constants_13_2.json
> ```

Add a new line - for the reviewable not to be annoying?
Or does this not work for symbolic link?



_Suggestion:_
```JSON
versioned_constants_13_2.json
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1749)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1749#-NuSejI2EC5zYpqSrhgX:-NuSmikW1DUGBCYpzQ_q:b3bcgou) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a6adfa79e88a4e3fc7164231b3f8535182d1ee1/crates/blockifier/resources/versioned_constants.json#L1)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add a new line - for the reviewable not to be annoying?
Or does this not work for symbolic link?
</blockquote></details>

this is the result of `ln -s versioned_constants_13_2.json versioned_constants.json`, I wouldn't edit it

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/resources/versioned_constants_13_2.json` line 0 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1749#-NuSmS0d2mBdgzDhdzZB:-NuSmS0d2mBdgzDhdzZC:bsfzb31) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a6adfa79e88a4e3fc7164231b3f8535182d1ee1/crates/blockifier/resources/versioned_constants_13_2.json#L0)):*
A more optimistic name for the file is `0_13_2.json` (In six months, versions will be called 1_*_* - because we will be decentralized,  didn't you know)?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1749)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants_13_2.json` line  at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1749#-NuSmS0d2mBdgzDhdzZB:-NuSmsVR6eQLb9FjTxnH:bevit4d) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a6adfa79e88a4e3fc7164231b3f8535182d1ee1/crates/blockifier/resources/versioned_constants_13_2.json#L)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

A more optimistic name for the file is `0_13_2.json` (In six months, versions will be called 1_*_* - because we will be decentralized,  didn't you know)?
</blockquote></details>

Good point - will do in a separate PR

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1749#-:-NuTGE5jBJRRXCNfZKp1:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1749)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
