### PR TITLE
Remove code address from external entry points.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/419)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/419)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/419#-NTTCnQN-kEFI-XW-l5D:-NTTCnQN-kEFI-XW-l5E:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/473add408ba070589ab422528ff794dfa103e12c/crates/blockifier/src/execution/entry_point.rs#L39)):*
> ```XML
>     // The class hash is not given if it can be deduced from the storage address.
>     pub class_hash: Option<ClassHash>,
>     // Optional, since there is no address to the code implementation in a library call.
> ```





_Suggestion:_
```XML
    // Optional, since there is no address to the code implementation in a library call 
    // and for outermost calls (triggered by the transaction itself).
    // TODO: BACKWARD-COMPATIBILITY.
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 429 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/419#-NTTD5x0EsLX2fWLz59D:-NTTD5x0EsLX2fWLz59E:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/473add408ba070589ab422528ff794dfa103e12c/crates/blockifier/src/execution/execution_utils.rs#L429)):*
> ```XML
>     // visible from it.
>     state.set_class_hash_at(deployed_contract_address, class_hash)?;
>     let code_address = match is_deploy_account_tx {
> ```





_Suggestion:_
```XML
    let code_address = if is_deploy_account_tx { None } else { Some(deployed_contract_address) };
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/419#-NTTCe91APtQv0OdH9G1:-NTTCe922LRz6RclpFAH:b17bpk1) ([raw file](https://github.com/starkware-libs/blockifier/blob/473add408ba070589ab422528ff794dfa103e12c/crates/blockifier/src/transaction/transactions.rs#L137)):*
> ```XML
>             ContractAddress::default(),
>             self.constructor_calldata.clone(),
>             true,
> ```

Give this a name, also in other location. Let's refrain from passing contracts without names.



_Code quote:_
```XML
true,
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/419)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/419#-NTTCnQN-kEFI-XW-l5D:-NTTFUWq4PieprTvpCrz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/473add408ba070589ab422528ff794dfa103e12c/crates/blockifier/src/execution/entry_point.rs#L39)):*
> ```XML
>     // The class hash is not given if it can be deduced from the storage address.
>     pub class_hash: Option<ClassHash>,
>     // Optional, since there is no address to the code implementation in a library call.
> ```

Done.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 429 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/419#-NTTD5x0EsLX2fWLz59D:-NTTFeQ3Dwl5guxakUgP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/473add408ba070589ab422528ff794dfa103e12c/crates/blockifier/src/execution/execution_utils.rs#L429)):*
> ```XML
>     // visible from it.
>     state.set_class_hash_at(deployed_contract_address, class_hash)?;
>     let code_address = match is_deploy_account_tx {
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/419#-NTTCe91APtQv0OdH9G1:-NTTFfagBVds-0rSgs4-:bbw24fn) ([raw file](https://github.com/starkware-libs/blockifier/blob/473add408ba070589ab422528ff794dfa103e12c/crates/blockifier/src/transaction/transactions.rs#L137)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give this a name, also in other location. Let's refrain from passing contracts without names.
</blockquote></details>

NP. Done.

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/419)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/blockifier/src/execution/syscalls.rs` line 424 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/419#-NTTGucf4d64H-7pLOZW:-NTTGucf4d64H-7pLOZX:bfajkuo) ([raw file](https://github.com/starkware-libs/blockifier/blob/af74618d35258e44fd1718f0edc4a4aa113bfb63/crates/blockifier/src/execution/syscalls.rs#L424)):*
> ```XML
>         &request.constructor_calldata,
>         deployer_address_for_calculation,
>     )?;
> ```

Restore empty line.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/419#-:-NTTHrpeDQPiDDIBUvz8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
