### PR TITLE
Implemented faulty account in cairo1

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1219)

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1219)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1219)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1219#-Nkz0rxNEdifVhI0TyV1:-Nkz0rxO0gx7Irez_cgZ:bmqm367) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc803126a11f14587d5ae5bc4f6a8dd57c20e767/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L28)):*
> ```Cairo
>     const FOO_ENTRY_POINT_SELECTOR: felt252 = (
>         0x1b1a0649752af1b28b3dc29a1556eee781e4a4c3a1f7f53f90fa834de098c4d
>     );
> ```

Have you checked this selector number, how it is calculated?
I remember I copied it from Cairo 0 :), so I'm not sure about it.



_Code quote:_
```Cairo
    // get_selector_from_name('foo').
    const FOO_ENTRY_POINT_SELECTOR: felt252 = (
        0x1b1a0649752af1b28b3dc29a1556eee781e4a4c3a1f7f53f90fa834de098c4d
    );
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1219#-Nkz0rxNEdifVhI0TyV1:-NkzFg815EQFRg5JZfjB:bmbzb0n) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc803126a11f14587d5ae5bc4f6a8dd57c20e767/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L28)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Have you checked this selector number, how it is calculated?
I remember I copied it from Cairo 0 :), so I'm not sure about it.
</blockquote></details>

I run Cairo 1 contracts using this number as the entry point selector (A modified copy of this file) This is fine.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1219#-NkzGd9n6Bx8-r8uSLIB:-NkzGd9o0Lc96FHbrfEA:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc803126a11f14587d5ae5bc4f6a8dd57c20e767/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L53)):*
> ```Cairo
>             }
> 
>             assert (scenario == CALL_CONTRACT, 'Wrong call contract');
> ```





_Suggestion:_
```Cairo
'INVALID_SCENARIO'/ 'Invalid scenario'
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1219#-NkzH4-48XNIwMXhEKEu:-NkzH4-48XNIwMXhEKEv:bti6kng) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc803126a11f14587d5ae5bc4f6a8dd57c20e767/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L42)):*
> ```Cairo
>             let tx_info = starknet::get_tx_info().unbox();
>             let signature = tx_info.signature;
>             assert(signature.len() == 2_u32, 'INVALID_SIGNATURE_LENGTH');
> ```

Must we assert this?
It is fine for the signature to be of length 1 for the `VALID`, `INVALID`, and future scenarios.



_Code quote:_
```Cairo
assert(signature.len() == 2_u32, 'INVALID_SIGNATURE_LENGTH');
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1219)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1219#-Nkz0rxNEdifVhI0TyV1:-NkzIasD5pYWtkZL-NV1:b4855pb) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc803126a11f14587d5ae5bc4f6a8dd57c20e767/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L28)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I run Cairo 1 contracts using this number as the entry point selector (A modified copy of this file) This is fine.
</blockquote></details>

Thanks! Done.
___
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1219#-NkzH4-48XNIwMXhEKEu:-NkzJxAy0x5aZy6B0AWC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc803126a11f14587d5ae5bc4f6a8dd57c20e767/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L42)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Must we assert this?
It is fine for the signature to be of length 1 for the `VALID`, `INVALID`, and future scenarios.
</blockquote></details>

Done.
___
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1219#-NkzGd9n6Bx8-r8uSLIB:-NkzJwz63AnkmEnukqwq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc803126a11f14587d5ae5bc4f6a8dd57c20e767/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L53)):*
> ```Cairo
>             }
> 
>             assert (scenario == CALL_CONTRACT, 'Wrong call contract');
> ```

Done.

**Review by MohammadNassar1 — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1219)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 36 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1219#-NkzLdTpA_Kl7g_D2bz0:-NkzLdTpA_Kl7g_D2bz1:b-ost510) ([raw file](https://github.com/starkware-libs/blockifier/blob/6be7eaf2e4f2cc278561e2794aeb47811ec9ec51/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L36)):*
> ```Cairo
>     trait StorageTrait {
>         fn faulty_validate(self: @ContractState) -> felt252;
>     }
> ```

Why is `faulty_validate` a storage trait?



_Code quote:_
```Cairo
    trait StorageTrait {
        fn faulty_validate(self: @ContractState) -> felt252;
    }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1219)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 36 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1219#-NkzLdTpA_Kl7g_D2bz0:-Nl28cRI9zRLAQ3l3X7c:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6be7eaf2e4f2cc278561e2794aeb47811ec9ec51/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L36)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why is `faulty_validate` a storage trait?
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1219#-:-Nl2DeE-9Z5gjmPhnrO_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
