### PR TITLE
fix(concurrency): fix add fee to sequencer balance so it will check u128

### PR DESCRIPTION
**Pull request by meship-starkware**
overflow

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1915)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1915)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1915#-Ny_P8pvCmY3qWzPGTds:-Ny_cBzt2gZFxthXZOF2:bukpuyk) ([raw file](https://github.com/starkware-libs/blockifier/blob/74901d4cba20e70c2e0daab5ecce8cb1728e133a/crates/blockifier/src/concurrency/worker_logic.rs#L251)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Don't we want to check it after we add the carry?
Do we want to panic in this case?
</blockquote></details>

Yes, it should be after we add the carry. Carry is a boolean so we will add only one or zero.  What would you like to do if the sequencer balance high is not u128? I think we should panic in this case

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1915)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1915#-Ny_P8pvCmY3qWzPGTds:-Ny_esLX18zGPTXMFq9y:bpsparx) ([raw file](https://github.com/starkware-libs/blockifier/blob/74901d4cba20e70c2e0daab5ecce8cb1728e133a/crates/blockifier/src/concurrency/worker_logic.rs#L251)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Yes, it should be after we add the carry. Carry is a boolean so we will add only one or zero.  What would you like to do if the sequencer balance high is not u128? I think we should panic in this case
</blockquote></details>

What will happen in case this is run in cairo?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1915#-Ny_P8pvCmY3qWzPGTds:-Ny_t7tKARc3G809lHzc:bz4z6ok) ([raw file](https://github.com/starkware-libs/blockifier/blob/74901d4cba20e70c2e0daab5ecce8cb1728e133a/crates/blockifier/src/concurrency/worker_logic.rs#L251)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What will happen in case this is run in cairo?
</blockquote></details>

By the way,
I don't think we check for overflows anywhere else in the blockifier code.

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1915)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1915)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1915)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1915#-Ny_P8pvCmY3qWzPGTds:-Nyek1QsAEKsfIFijrke:bnwoaea) ([raw file](https://github.com/starkware-libs/blockifier/blob/74901d4cba20e70c2e0daab5ecce8cb1728e133a/crates/blockifier/src/concurrency/worker_logic.rs#L251)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

By the way,
I don't think we check for overflows anywhere else in the blockifier code.
</blockquote></details>

Which other places?
We usually run the cairo code in such scenarios, so it's worth understanding what happens there

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1915#-Ny_P8pvCmY3qWzPGTds:-NyndMcc1P1rdkN55Dm9:b-17qaxt) ([raw file](https://github.com/starkware-libs/blockifier/blob/74901d4cba20e70c2e0daab5ecce8cb1728e133a/crates/blockifier/src/concurrency/worker_logic.rs#L251)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Which other places?
We usually run the cairo code in such scenarios, so it's worth understanding what happens there
</blockquote></details>

I don't know... Shouldn't it happen in areas related to fee computation?
I tried to find another example in the code an couldn't.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1915)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1915#-Ny_P8pvCmY3qWzPGTds:-Nyu8XK34nwCBXVbDbOd:b-be3bbk) ([raw file](https://github.com/starkware-libs/blockifier/blob/74901d4cba20e70c2e0daab5ecce8cb1728e133a/crates/blockifier/src/concurrency/worker_logic.rs#L251)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I don't know... Shouldn't it happen in areas related to fee computation?
I tried to find another example in the code an couldn't.
</blockquote></details>

We are ignoring this case. I added TODO to check what we are doing in Cairo.

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1915)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1915)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Pull request merged**
