### PR TITLE
Return an error for unsupported versions.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/886)

### CODE REVIEW

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/886)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/886#-NdVn0CP-Eu49QDpxdV5:-NdVn0CP-Eu49QDpxdV6:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/862adad2c6514d8983c057eafdcdfba27225f878/crates/native_blockifier/src/py_transaction.rs#L138)):*
> ```XML
>     })
> 
> }
> ```





_Suggestion:_
```XML
    }?;
    
    Ok(DeployAccountTransaction {
        tx: sn_api_tx,
        tx_hash: account_data_context.transaction_hash,
        contract_address: account_data_context.sender_address,
    })
}
```

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/886#-:-NdZ7txU-CmPj28KNfIP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 126 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/886#-NdZ7yvg2zvPmjM_wfUF:-NdZ7yvg2zvPmjM_wfUG:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bcd118a28506202b0b958aead22a89dd02bf0b13/crates/native_blockifier/src/py_transaction.rs#L126)):*
> ```XML
>         }),
>         _ => Err(NativeBlockifierInputError::UnsupportedTransactionVersion {
>             tx_type: TransactionType::Declare,
> ```





_Suggestion:_
```XML
TransactionType::DeployAccount
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/886)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 126 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/886#-NdZ7yvg2zvPmjM_wfUF:-NdZ8Gm31xXXl9USzVIG:b-vttr73) ([raw file](https://github.com/starkware-libs/blockifier/blob/bcd118a28506202b0b958aead22a89dd02bf0b13/crates/native_blockifier/src/py_transaction.rs#L126)):*
> ```XML
>         }),
>         _ => Err(NativeBlockifierInputError::UnsupportedTransactionVersion {
>             tx_type: TransactionType::Declare,
> ```

Oh, right. Done :)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/886)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/886#-:-NdZGjv24ySzd9KC66Wa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
