### PR TITLE
Update cairo compiler version and fix related TODOs.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1332)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1332)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1332#-No7CUUyD8_MrhvJGy1t:-No7CUUyD8_MrhvJGy1u:by15o7l) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae8aca204aa42a4bac77c09807dcdd3bec5c1760/Cargo.toml#L23)):*
> ```TOML
> cached = "0.44.0"
> cairo-felt = "0.9.1"
> cairo-lang-casm = "2.5.0-dev.1"
> ```

What does this version include?
___
*[`crates/blockifier/src/execution/contract_class.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1332#-No7Ct9U4_ZdgAenyaeX:-No7Ct9U4_ZdgAenyaeY:b-jlkinp) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae8aca204aa42a4bac77c09807dcdd3bec5c1760/crates/blockifier/src/execution/contract_class.rs#L189)):*
> ```XML
>     fn get_byte_code_segment_lengths(&self) -> NestedIntList {
>         self.bytecode_segment_lengths
>             .clone()
> ```

Any way to avoid cloning?



_Code quote:_
```XML
.clone()
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1332)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1332#-No7CUUyD8_MrhvJGy1t:-No7FE1H16CvOpOLsOoi:b-ad8f65) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae8aca204aa42a4bac77c09807dcdd3bec5c1760/Cargo.toml#L23)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does this version include?
</blockquote></details>

The contract segmentation feature on the compiler side among other things.
In particular, the definition of `NestedIntList` and the `bytecode_segment_lengths` field in the Casm class.

**Review by elintul — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1332)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1332)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1332#-No7Ct9U4_ZdgAenyaeX:-No7FTwZ1QwUhlWpevuS:bykb8b2) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae8aca204aa42a4bac77c09807dcdd3bec5c1760/crates/blockifier/src/execution/contract_class.rs#L189)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Any way to avoid cloning?
</blockquote></details>

I'll move this logic to the construction of the struct.

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1332#-:-No7Hn8y8yVIz56vVSP2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1332#-No7Ct9U4_ZdgAenyaeX:-No7HjqiE-YBzPTm1msb:b-ucfknh) ([raw file](https://github.com/starkware-libs/blockifier/blob/ae8aca204aa42a4bac77c09807dcdd3bec5c1760/crates/blockifier/src/execution/contract_class.rs#L189)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I'll move this logic to the construction of the struct.
</blockquote></details>

Thanks!

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1332)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 189 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1332#-No7JVTRCXlMR7-ZYsqU:-No7JVTRCXlMR7-ZYsqV:b-aftmwp) ([raw file](https://github.com/starkware-libs/blockifier/blob/b34b9c7de37d1a5e256e48bcfa156f2290b24f6a/crates/blockifier/src/execution/contract_class.rs#L189)):*
> ```XML
>     /// Returns an empty contract class for testing purposes.
>     #[cfg(any(feature = "testing", test))]
>     pub fn empty_for_testing() -> Self {
> ```

This is instead of supporting `Default` (which doesn't make sense to a contract class IMO).

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1332)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
