### PR TITLE
Nest library call test

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/472)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #464** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/464" target="_blank">Graphite</a> 
    * **PR #465** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/465" target="_blank">Graphite</a> 
      * **PR #466** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/466" target="_blank">Graphite</a> 
        * **PR #469** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/469" target="_blank">Graphite</a> 
          * **PR #470** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/470" target="_blank">Graphite</a> 
            * **PR #472** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/472" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/472?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/472)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 34 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/472#-NVXrfFx29S-4bx2VLtv:-NVXrfFx29S-4bx2VLtw:b-4wsd2r) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b94c5aaa5eb72c52d6c1ffe457a46e1a0e125e2/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L34)):*
> ```Cairo
>     #[external]
>     fn test_nested_library_call(
>         class_hash: ClassHash, lib_selector: felt252, nested_selector: felt252, a:felt252, b:felt252
> ```

Is there an auto-formatter?



_Suggestion:_
```Cairo
a: felt252, b: felt252
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/472#-NVXujAu3I5QvJqAYV-q:-NVXujAu3I5QvJqAYV-r:bobk9go) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b94c5aaa5eb72c52d6c1ffe457a46e1a0e125e2/crates/blockifier/src/execution/cairo1_execution.rs#L238)):*
> ```XML
> 
>     // Get retdata.
>     // TODO(spapini): Do something with `success`.
> ```

We should pass to `CallInfo`, see [here](https://github.com/starkware-industries/starkware/blob/21cf5877347d53f9089159125b3366acf98caf21/src/starkware/starknet/business_logic/execution/execute_entry_point.py#L470-L472).
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/472#-NVXtQY4A26VE-4Qs5gg:-NVXtQY4A26VE-4Qs5gh:by48fvu) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b94c5aaa5eb72c52d6c1ffe457a46e1a0e125e2/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L110)):*
> ```XML
>         ..nested_storage_entry_point
>     };
>     let storage_entry_point_vm_resources = VmExecutionResources {
> ```

Can you explain the diff. from the old one?
```rs
    let storage_entry_point_vm_resources =
        VmExecutionResources { n_steps: 41, ..Default::default() };
```

I understand it's a whole different language, but I'd like to try to get some idea.



_Code quote:_
```XML
storage_entry_point_vm_resources
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/472#-NVXteCR7vCPV1mxfjU0:-NVXteCR7vCPV1mxfjU1:b7vv6dy) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b94c5aaa5eb72c52d6c1ffe457a46e1a0e125e2/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L123)):*
> ```XML
>         ..Default::default()
>     };
>     let mut library_call_vm_resources = VmExecutionResources {
> ```

Here too:
```rs
    let mut library_call_vm_resources = VmExecutionResources {
        n_steps: 38,
        builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 1)]),
        ..Default::default()
    };
```



_Code quote:_
```XML
library_call_vm_resources
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/472#-NVXu4xwBOqL2u6UFGyd:-NVXu4xwBOqL2u6UFGye:bsfqgn2) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b94c5aaa5eb72c52d6c1ffe457a46e1a0e125e2/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L150)):*
> ```XML
>         builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 10)]),
>     };
>     main_call_vm_resources += &library_call_vm_resources;
> ```

Before we did:
```rs
    // Nested library call cost: library_call(inner) + library_call(library_call(inner)).
    let mut main_call_vm_resources = VmExecutionResources { n_steps: 45, ..Default::default() };
    main_call_vm_resources += &(&library_call_vm_resources * 2);
```



_Code quote:_
```XML
main_call_vm_resources
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/472)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 34 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/472#-NVXrfFx29S-4bx2VLtv:-NVcDQEw7XjP9JaKvDpc:bqpu7tb) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b94c5aaa5eb72c52d6c1ffe457a46e1a0e125e2/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L34)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there an auto-formatter?
</blockquote></details>

Yes, I forgot to run it :) Thanks
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/472#-NVXujAu3I5QvJqAYV-q:-NVcEH5_1In-1_KKYeQE:bna6mpi) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b94c5aaa5eb72c52d6c1ffe457a46e1a0e125e2/crates/blockifier/src/execution/cairo1_execution.rs#L238)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We should pass to `CallInfo`, see [here](https://github.com/starkware-industries/starkware/blob/21cf5877347d53f9089159125b3366acf98caf21/src/starkware/starknet/business_logic/execution/execute_entry_point.py#L470-L472).
</blockquote></details>

Thanks. Will do in another PR that will also check failures.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/472#-NVXtQY4A26VE-4Qs5gg:-NVcECOTB7WzoRbKpNN-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b94c5aaa5eb72c52d6c1ffe457a46e1a0e125e2/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain the diff. from the old one?
```rs
    let storage_entry_point_vm_resources =
        VmExecutionResources { n_steps: 41, ..Default::default() };
```

I understand it's a whole different language, but I'd like to try to get some idea.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/472#-NVXteCR7vCPV1mxfjU0:-NVcEDB33KlcXGySLcA7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b94c5aaa5eb72c52d6c1ffe457a46e1a0e125e2/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L123)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Here too:
```rs
    let mut library_call_vm_resources = VmExecutionResources {
        n_steps: 38,
        builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 1)]),
        ..Default::default()
    };
```
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/472#-:-NVcpBpb1xFcvp5NRvxk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/472).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/472) couldn't merge this pull request because a downstack PR #466 failed to merge.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/472#-:-NVd1TtJ1aHkQq0KuQII:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/472#-:-NVhDmxG8qPpEVWzi7Xf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
