### PR TITLE
fix(concurrency): fix test_concurrent_fee_transfer_when_sender_is_seq…

### PR DESCRIPTION
**Pull request by meship-starkware**
…uencer to run in concurrency mode

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2051)

### CODE REVIEW

**Comment by avi-starkware** [comment]
Commit lint fails due to the commit message being too long (it is 102 chars and max is 100)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1338 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2051#-O1HUnBq4yYhxuAyxyUa:-O1HUnBq4yYhxuAyxyUb:b-84birv) ([raw file](https://github.com/starkware-libs/blockifier/blob/2b806cc9e441a9b8a55981ae56f65949a964761d/crates/blockifier/src/transaction/account_transactions_test.rs#L1338)):*
> ```XML
>         ExecutionFlags { charge_fee: true, validate: true, concurrency_mode: true };
>     let result =
>         account_tx.execute_raw(&mut transactional_state, &block_context, execution_flags).unwrap();
> ```

There are many other places where we use `execute` and not `execute_raw` (including in this file). Do we only change it in places that relate to the concurrency module?



_Code quote:_
```XML
        account_tx.execute_raw(&mut transactional_state, &block_context, execution_flags).unwrap();
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2051)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1338 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2051#-O1HUnBq4yYhxuAyxyUa:-O1HXIsK3shs6MTSiJE4:bkj1h0c) ([raw file](https://github.com/starkware-libs/blockifier/blob/2b806cc9e441a9b8a55981ae56f65949a964761d/crates/blockifier/src/transaction/account_transactions_test.rs#L1338)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

There are many other places where we use `execute` and not `execute_raw` (including in this file). Do we only change it in places that relate to the concurrency module?
</blockquote></details>

We prefer using execute because it's closer to the real flow. But using `execute_raw` lets us run the transaction in concurrency mode without changing the configurations.

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2051#-:-O1HYQgN2RivduGpdO5t:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2051)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
