### PR TITLE
Add github nightly job that checks that dependencies are not broken

### PR DESCRIPTION
**Pull request by giladchase**
Based on [this](https://doc.rust-lang.org/nightly/cargo/guide/continuous-integration.html#verifying-latest-dependencies)
recommendation from The Cargo Book.

This will give us a heads-up against a future `genco` problem from one of our deps.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1093)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1093#-:-NiclNS788O6FiPZpuJk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1093#-NiclPK4AT9R8_Ou2Wq8:-NiclPK4AT9R8_Ou2Wq9:b-d306gm) (no related file):*
Where will we see results? Will we get push-notified?

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1093)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1093#-NiclPK4AT9R8_Ou2Wq8:-NicrHab2dttzhizTvHV:bfyfweo) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Where will we see results? Will we get push-notified?
</blockquote></details>

Not sure yet, I couldn't get it to run on the branch, maybe it only works on main? :thinking: 

Currently, i'm just trying to follow the cargo book as closely as possible, if it doesn't work i'll start hacking it.

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1093)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1093#-NiclPK4AT9R8_Ou2Wq8:-NictFMb6MQT3oo-NRFE:b-t1g6ap) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not sure yet, I couldn't get it to run on the branch, maybe it only works on main? :thinking: 

Currently, i'm just trying to follow the cargo book as closely as possible, if it doesn't work i'll start hacking it.
</blockquote></details>

Yuck, looks like i might have to add some `secrets` in order to do this according to this: https://github.com/orgs/community/discussions/25351

Bah, let's get it to work first and worry about notifications later? :grimacing: 

___

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1093)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1093#-NiclPK4AT9R8_Ou2Wq8:-NiczxbwAjV_VbRsgrzv:b-7gab64) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yuck, looks like i might have to add some `secrets` in order to do this according to this: https://github.com/orgs/community/discussions/25351

Bah, let's get it to work first and worry about notifications later? :grimacing:
</blockquote></details>

yalla

___

**Pull request merged**
