### PR TITLE
Copy v0 execution code

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/460)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a> 
    * **PR #449** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/449" target="_blank">Graphite</a> 
      * **PR #451** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/451" target="_blank">Graphite</a> 
        * **PR #450** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/450" target="_blank">Graphite</a> 
          * **PR #452** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/452" target="_blank">Graphite</a> 
            * **PR #458** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/458" target="_blank">Graphite</a> 
              * **PR #459** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/459" target="_blank">Graphite</a> 
                * **PR #460** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/460" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/460?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/460)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/460#-NV8qi87Cbdhlxl4k6IV:-NV8qi87Cbdhlxl4k6IW:b-nkg9v7) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c931c8b3631b1dc2f4b8ccdc728ee2a0b78874f/crates/blockifier/src/execution.rs#L7)):*
> ```XML
> pub mod errors;
> pub mod exec_v0;
> pub mod exec_v1;
> ```

WDYT of `[starknet_]runner.rs`?
I was thinking of defining a `StarknetRunner` struct holding the VM, `CallEntryPoint`, and anything else needed for execution.
It will have the following API: `initialize/create`, `prepare_execution_arguments`, `execute`, `validate_execution`, `finalize_execution`. 



_Code quote:_
```XML
exec_v1
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/460)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/460)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/460#-NV8qi87Cbdhlxl4k6IV:-NV98KePAsoN-yvIL0Qt:bc56yci) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c931c8b3631b1dc2f4b8ccdc728ee2a0b78874f/crates/blockifier/src/execution.rs#L7)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT of `[starknet_]runner.rs`?
I was thinking of defining a `StarknetRunner` struct holding the VM, `CallEntryPoint`, and anything else needed for execution.
It will have the following API: `initialize/create`, `prepare_execution_arguments`, `execute`, `validate_execution`, `finalize_execution`. 
</blockquote></details>

Sounds reasonable. Added a TODO.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/460)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/460#-NV9FA5d4nn-ufaeu2Gs:-NV9FA5d4nn-ufaeu2Gt:b-vhoh2z) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6b797bac9f8685cb2dc89b1121b52047933b67a/crates/blockifier/src/execution.rs#L1)):*
> ```XML
> pub mod cairo1_execution;
> ```

Why not simply `execution`? That's the only execution we'll have down the line.



_Code quote:_
```XML
cairo1_execution;
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/460)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/460#-NV9Gx1zAUCrYEIsuffA:-NV9Gx1zAUCrYEIsuffB:bswspws) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6b797bac9f8685cb2dc89b1121b52047933b67a/crates/blockifier/src/execution/cairo1_execution.rs#L1)):*
> ```XML
> use cairo_vm::types::relocatable::{MaybeRelocatable, Relocatable};
> ```

Where are Cairo1-related changes supposed to appear? 
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/460#-NV9GnC0BTvsT4GuUjSG:-NV9GnC0BTvsT4GuUjSH:b8rqs93) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6b797bac9f8685cb2dc89b1121b52047933b67a/crates/blockifier/src/execution/cairo1_execution.rs#L96)):*
> ```XML
> }
> 
> pub fn resolve_entry_point_pc(
> ```

Is it the same impl.? Can we leave as a method of `CallEntryPoint`?



_Code quote:_
```XML
resolve_entry_point_pc
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/460)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/460#-NV9FA5d4nn-ufaeu2Gs:-NV9JaNs65IbXpLyeSUT:bc2t9jn) ([raw file](https://github.com/starkware-libs/blockifier/blob/e117616f049df00c5175a0230af7147fa1a7b7c2/crates/blockifier/src/execution.rs#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not simply `execution`? That's the only execution we'll have down the line.
</blockquote></details>

execution::execution is weird, and will make it hard doing search and replace later. Have another suggestion?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/460)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/460#-NV9Gx1zAUCrYEIsuffA:-NV9Jir7A27WlJ6XGMA6:b-qaddxv) ([raw file](https://github.com/starkware-libs/blockifier/blob/e117616f049df00c5175a0230af7147fa1a7b7c2/crates/blockifier/src/execution/cairo1_execution.rs#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where are Cairo1-related changes supposed to appear? 
</blockquote></details>

This is just a copy PR. No cairo1 related things here yet.
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/460#-NV9GnC0BTvsT4GuUjSG:-NV9Jpa3EYQiKre6r06P:b4dgxsu) ([raw file](https://github.com/starkware-libs/blockifier/blob/e117616f049df00c5175a0230af7147fa1a7b7c2/crates/blockifier/src/execution/cairo1_execution.rs#L96)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is it the same impl.? Can we leave as a method of `CallEntryPoint`?
</blockquote></details>

1. No, it's the same text, but different types
2. It'll change to axclude the default, since we have no default in Cairo1. this is just a copy PR

**Review by elintul — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/460#-:-NV9M7CO4872cCqBkTjN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/460#-NV9FA5d4nn-ufaeu2Gs:-NV9M3E-6fbpy116LEkz:b-stsiy6) ([raw file](https://github.com/starkware-libs/blockifier/blob/e117616f049df00c5175a0230af7147fa1a7b7c2/crates/blockifier/src/execution.rs#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

execution::execution is weird, and will make it hard doing search and replace later. Have another suggestion?
</blockquote></details>

I'll think of something.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/460)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
