### PR TITLE
Delete write_and_transfer for flexibility

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047)

### CODE REVIEW

**Review by amosStarkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1019 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1047#-Ni-o6J5D8ECxeqUvKhh:-Ni-o6J5D8ECxeqUvKhi:bjhgw4t) ([raw file](https://github.com/starkware-libs/blockifier/blob/e12eb737efc053434639ed992fbcc3e11b5686ca/crates/blockifier/src/transaction/account_transactions_test.rs#L1019)):*
> ```XML
> #[allow(clippy::too_many_arguments)]
> /// Calls `test_write_and_transfer` with the given parameters.
> fn write_and_transfer(
> ```

can you explain why you're deleting the function?
if you want it to receive `fee_token_address` you can just add it as a param, no?



_Code quote:_
```XML
fn write_and_transfer(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1019 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1047#-Ni-o6J5D8ECxeqUvKhh:-Ni0pOTdCB-MwPsQ76uB:b-ctcsi4) ([raw file](https://github.com/starkware-libs/blockifier/blob/e12eb737efc053434639ed992fbcc3e11b5686ca/crates/blockifier/src/transaction/account_transactions_test.rs#L1019)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

can you explain why you're deleting the function?
if you want it to receive `fee_token_address` you can just add it as a param, no?
</blockquote></details>

1. I want to receive `version` and `resource_bounds` explicitly later
2. I think we should stick to manually creating InvokeTxArgs now. This struct was created after these utilities were written; they no longer save much boilerplate (params are written to the function instead of the struct, currently). Main reason is: now I need version and resource bounds, next versions will need other v3 tx features; using InvokeTxArgs covers that.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1032 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1047#-NiB9bVC37-5z5FrL_Qr:-NiB9bVC37-5z5FrL_Qs:bi6q6ui) ([raw file](https://github.com/starkware-libs/blockifier/blob/bea0b03a8200f0724d3d66dca55a83a9570048c1/crates/blockifier/src/transaction/account_transactions_test.rs#L1032)):*
> ```XML
>             &FeeType::Strk
>         },
>     );
> ```

Is it currently used with version::Three somewhere? in other PRs?



_Code quote:_
```XML
    let fee_token_address = block_context.fee_token_addresses.get_by_fee_type(
        if transaction_version < TransactionVersion::THREE {
            &FeeType::Eth
        } else {
            &FeeType::Strk
        },
    );
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1032 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1047#-NiB9bVC37-5z5FrL_Qr:-NiE8xfj6L6_MGTpll5m:b5479ya) ([raw file](https://github.com/starkware-libs/blockifier/blob/bea0b03a8200f0724d3d66dca55a83a9570048c1/crates/blockifier/src/transaction/account_transactions_test.rs#L1032)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is it currently used with version::Three somewhere? in other PRs?
</blockquote></details>

Don't understand the question

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1032 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1047#-NiB9bVC37-5z5FrL_Qr:-NiEK7Ai0YxyODJcvtG8:b19v5ju) ([raw file](https://github.com/starkware-libs/blockifier/blob/bea0b03a8200f0724d3d66dca55a83a9570048c1/crates/blockifier/src/transaction/account_transactions_test.rs#L1032)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Don't understand the question
</blockquote></details>

I looked up usage of this function, and it seemed like it was only called with version = 1.

If that's the case, then i think we should either hard-code version 1, or add a TODO that explains that the version-3 part is currently unused.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1032 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1047#-NiB9bVC37-5z5FrL_Qr:-NiEV-UOD0W8ovjOmvkE:bf6r8ku) ([raw file](https://github.com/starkware-libs/blockifier/blob/bea0b03a8200f0724d3d66dca55a83a9570048c1/crates/blockifier/src/transaction/account_transactions_test.rs#L1032)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I looked up usage of this function, and it seemed like it was only called with version = 1.

If that's the case, then i think we should either hard-code version 1, or add a TODO that explains that the version-3 part is currently unused.
</blockquote></details>

it's a preparation for the [next PR](https://reviewable.io/reviews/starkware-libs/blockifier/1048), which uses v3

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1012 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1047#-NiUQnnJ83woc7f05n8V:-NiUQnnJ83woc7f05n8W:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/06ba9e5cd0605286149851c548e900a097740658/crates/blockifier/src/transaction/account_transactions_test.rs#L1012)):*
> ```XML
> }
> 
> fn write_and_transfer_calldata(
> ```





_Suggestion:_
```XML
calldata_for_write_and_transfer[_entry_point]
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1019 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1047#-NiUR4ba89Uw6YLL3DWQ:-NiUR4bb6bnIPdo0u56F:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/06ba9e5cd0605286149851c548e900a097740658/crates/blockifier/src/transaction/account_transactions_test.rs#L1019)):*
> ```XML
>     recipient: StarkFelt,
>     transfer_amount: StarkFelt,
>     transaction_version: TransactionVersion,
> ```





_Suggestion:_
```XML
tx_version: TransactionVersion,
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047#-:-NiVCllt2UC2vLMjpgTI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @zuphitf)

**Review by dorimedini-starkware — COMMENTED** [review]
> Dismissed @giladchase from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1047#-:-NiVKBTV8Rd3HJJ4CiO1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
