### PR TITLE
refactor: add stateful validator error

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1731)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1731?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1731** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1731?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1730** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1730?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1731)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`crates/native_blockifier/src/errors.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1731#-Nu3T1C98FsK02zbIL59:-Nu3T1C98FsK02zbIL5A:b-tjx6ci) ([raw file](https://github.com/starkware-libs/blockifier/blob/0f6038393ac54b587f891e2b6f3904c902298ae7/crates/native_blockifier/src/errors.rs#L17)):*
> ```XML
> pub type NativeBlockifierResult<T> = Result<T, NativeBlockifierError>;
> 
> // TODO(Arni, 28/3/2024): Move to stateful validator dedicated file.
> ```

Addresses in #1732.



_Code quote:_
```XML
// TODO(Arni, 28/3/2024): Move to stateful validator dedicated file.
```
___
*[`crates/native_blockifier/src/errors.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1731#-Nu3T6CC3uBaiM-wBr9f:-Nu3T6CC3uBaiM-wBr9g:b-9ypy1e) ([raw file](https://github.com/starkware-libs/blockifier/blob/0f6038393ac54b587f891e2b6f3904c902298ae7/crates/native_blockifier/src/errors.rs#L93)):*
> ```XML
> 
> // TODO(Arni, 21/3/2024): Add ValidatorError to the enum NativeBlockifierError and remove this
> // implementation.
> ```

Addressed in #1733.



_Code quote:_
```XML
// TODO(Arni, 21/3/2024): Add ValidatorError to the enum NativeBlockifierError and remove this
// implementation.
```

**Review by giladchase — APPROVED** [review]
Thanks for the PR comments and refs :pray: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1731#-:-NuOFoPE9JQ1gHfPETyw:b-1bnz4n)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1731)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Apr 8, 3:03 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/1731).

**Pull request merged**
