### PR TITLE
Add an `initial_gas` field to `CallEntryPoint` and as a result- create a new similar struct to be used inside `CallInfo`.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/571)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/571)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @elintul and @spapinistarkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/571#-NXAn3y9A9Z5v5mHZtAq:-NXAn3y9A9Z5v5mHZtAr:bssn775) ([raw file](https://github.com/starkware-libs/blockifier/blob/d578ab38c0936353d231358b0a559ed8e196cef4/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L121)):*
> ```XML
>         VmExecutionResources { n_steps: 41, ..Default::default() };
>     let nested_storage_call_info = CallInfo {
>         call: CallEntryPointInfo::from(nested_storage_entry_point),
> ```

RE [this](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXAN8xM-3l23wXJSSfc:~:text=How%20about%20CallInfo%3A%3Anew%20receiving%20CallEntryPoint%3F): Do you think it's more readable? The problem with `new()` is that rust has no named arguments plus we can't use the `..Default::default()`.



_Code quote:_
```XML
 call: CallEntryPointInfo::from(nested_storage_entry_point),
```

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/571)* status: 2 of 15 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/571#-NXGfyKg1ibCPqwtOrsn:-NXGfyKg1ibCPqwtOrso:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d578ab38c0936353d231358b0a559ed8e196cef4/crates/blockifier/src/execution/entry_point.rs#L177)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> /// This class contains the call related information that should be a part of the execution
> ```





_Suggestion:_
```XML
/// Contains the call-related
```

**Review by elintul — APPROVED** [review]
> Reviewed 14 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/571)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/571#-NXAn3y9A9Z5v5mHZtAq:-NXJ98I9559JtzjyBNDU:b2ftdbu) ([raw file](https://github.com/starkware-libs/blockifier/blob/d578ab38c0936353d231358b0a559ed8e196cef4/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L121)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

RE [this](https://reviewable.io/reviews/starkware-libs/blockifier/545#-NXAN8xM-3l23wXJSSfc:~:text=How%20about%20CallInfo%3A%3Anew%20receiving%20CallEntryPoint%3F): Do you think it's more readable? The problem with `new()` is that rust has no named arguments plus we can't use the `..Default::default()`.
</blockquote></details>

You're right, let's leave it as it is.
___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/571#-NXJ8rGG3xVDmoAly2pA:-NXJ8rGG3xVDmoAly2pB:bbrjmev) ([raw file](https://github.com/starkware-libs/blockifier/blob/d578ab38c0936353d231358b0a559ed8e196cef4/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L395)):*
> ```XML
>     let initial_gas = constants::INITIAL_GAS_COST.into();
> 
>     let entry_point = CallEntryPoint {
> ```

Remove blank line above (can be done in the next PR).



_Code quote:_
```XML
let entry_point = CallEntryPoint {
```

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/571#-:-NXJ9FKE4rIi-U1zRMg8:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/571#-:-NXJ9wZ42cRq2snj3APn:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

**Pull request closed without merging**
