### PR TITLE
refactor(execution): rename execute_chunk to execute_txs

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1874)

### CODE REVIEW

**Review by barak-b-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1874)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1874#-NxG_W6u9QHTYAXfrPVu:-NxG_W6u9QHTYAXfrPVv:b-cx5oum) ([raw file](https://github.com/starkware-libs/blockifier/blob/89c8c4af411918a66c4509d5af199202ae7933ad/crates/blockifier/src/blockifier/transaction_executor.rs#L117)):*
> ```XML
>                     break;
>                 }
>             }
> ```

I think `fold_while` can be more fit here (: but it's a matter of style



_Code quote:_
```XML
            for chunk in txs.chunks(self.config.concurrency_config.chunk_size) {
                let chunk_results = self.execute_chunk(chunk, charge_fee);
                let chunk_results_len = chunk_results.len();
                results.extend(chunk_results);

                if chunk_results_len < chunk.len() {
                    // Block is full.
                    break;
                }
            }
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1874#-NxG_W6u9QHTYAXfrPVu:-NxGec6O4XuQSr1EatD0:b-p28t8q) ([raw file](https://github.com/starkware-libs/blockifier/blob/89c8c4af411918a66c4509d5af199202ae7933ad/crates/blockifier/src/blockifier/transaction_executor.rs#L117)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I think `fold_while` can be more fit here (: but it's a matter of style
</blockquote></details>

Something like:
```
use itertools::FoldWhile::{Continue, Done};
let results = txs.chunks(self.config.concurrency_config.chunk_size).fold_while(Vec::new(), |mut acc, chunk| {
    let chunk_results = self.execute_chunk(chunk, charge_fee);
    if chunk_results.len() < acc.len() { acc.extend(chunk_results); Done(acc) } else { acc.extend(chunk_results); Continue(acc) }
}).into_inner();
results
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1874)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1874#-NxG_W6u9QHTYAXfrPVu:-NxGoyCY6OtwV2AFHtwv:bmfxgaw) ([raw file](https://github.com/starkware-libs/blockifier/blob/89c8c4af411918a66c4509d5af199202ae7933ad/crates/blockifier/src/blockifier/transaction_executor.rs#L117)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Something like:
```
use itertools::FoldWhile::{Continue, Done};
let results = txs.chunks(self.config.concurrency_config.chunk_size).fold_while(Vec::new(), |mut acc, chunk| {
    let chunk_results = self.execute_chunk(chunk, charge_fee);
    if chunk_results.len() < acc.len() { acc.extend(chunk_results); Done(acc) } else { acc.extend(chunk_results); Continue(acc) }
}).into_inner();
results
```
</blockquote></details>

Done :)

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1874#-:-NxGv5Xd4O0lY2KQN1KX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
