### PR TITLE
Simple benchmark

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/native_blockifier/Cargo.toml` line 44 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCW1zZ3CzDIMc1VbKv:-NYCW1zZ3CzDIMc1VbKw:b8arbnj) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/Cargo.toml#L44)):*
> ```TOML
> name = "blockifier_bench"
> harness = false
> # cargo criterion --bench criterion_benchmark
> ```

Should this be  `cargo criterion --bench blockifier_bench`? (running with criterion_benchmark gave me "error: no bench target named `criterion_benchmark`.")
Also, how does this differ from `cargo bench --bench blockifier_bench`



_Code quote:_
```TOML
# cargo criterion --bench criterion_benchmark
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCf3Ng80WatCw-6C1k:-NYCf3Ng80WatCw-6C1l:bp574qw) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L24)):*
> ```XML
> use starknet_api::{calldata, stark_felt};
> 
> const N_ACCOUNTS: usize = 10;
> ```

Is this large enough to ensure the compiler/OS doesn’t cache things we don't want it to?
In other words, this will generate a bunch of txs between the same contracts that only differ in nonce (IIUC the transfer amount is fixed?), will parts of these get cached?



_Code quote:_
```XML
const N_ACCOUNTS: usize = 10;
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCcRal5tdolJwXerN1:-NYCcRal5tdolJwXerN2:b6j48un) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L62)):*
> ```XML
> 
> fn do_transfer(
>     account0: usize,
> ```

also for address and nonce



_Suggestion:_
```XML
sender_account
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYC_C4T5GUBoho6cMda:-NYC_C4T5GUBoho6cMdb:bjsaj3p) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L63)):*
> ```XML
> fn do_transfer(
>     account0: usize,
>     accounts: &[starknet_api::core::ContractAddress],
> ```

Why fullpath here and in `prepare_accounts` return value?
We tend not to do this for SN API types when it is unambiguous (for example `ClassHash` in this module).



_Code quote:_
```XML
starknet_api::core::ContractAddress
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCcTF-7XnHr5Pc8snh:-NYCcTF-7XnHr5Pc8sni:b-amoji9) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L69)):*
> ```XML
> ) {
>     let n_accounts = accounts.len();
>     let account1 = (account0 + 1) % n_accounts;
> ```

also for address and nonce.



_Suggestion:_
```XML
recipient_account
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCb37-DQATpXjAyzE9:-NYCb37-DQATpXjAyzEA:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L75)):*
> ```XML
>     nonces[account0] += 1;
> 
>     let entry_point_selector = selector_from_name("transfer");
> ```





_Suggestion:_
```XML
blockifier::transaction::constants::TRANSFER_ENTRY_POINT_NAME
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCbYPV5TymZa8gm6-r:-NYCbYPV5TymZa8gm6-s:b-epq3yw) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L82)):*
> ```XML
>         *addr1.0.key(),
>         stark_felt!(1_u8),
>         stark_felt!(0_u8)
> ```

Wrap in variables or add comments plz?
Alternatively, is there anywhere in the `blockifier` codebase that explains these? (I couldn't find it myself)



_Code quote:_
```XML
        *block_context.fee_token_address.0.key(),
        entry_point_selector.0,
        stark_felt!(3_u8),
        *addr1.0.key(),
        stark_felt!(1_u8),
        stark_felt!(0_u8)
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCdnYR8QsiNF6UEPV_:-NYCdnYR8QsiNF6UEPVa:bp7megt) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L88)):*
> ```XML
>         nonce: Nonce(stark_felt!(nonce)),
>         ..tx
>     }));
> ```

Not sure if this helps readability or not, also the suggestion adds a function call in the middle of a benchmark, so probably worse on that aspect...
WDYT?



_Suggestion:_
```XML
    let account_tx = AccountTransaction::Invoke(
        InvokeTransactionV1 { nonce: Nonce(stark_felt!(nonce)), ..tx }.into(),
    );
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCYR2V6tuhZyVl46fj:-NYCYR2V6tuhZyVl46fk:b-xlv88k) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L114)):*
> ```XML
>         nonces.push(1_u64);
>         let deployed_account_balance_key =
>             get_storage_var_address("ERC20_balances", &[*deployed_account_address.0.key()])
> ```

Not sure if the suggestion is better, [saves a `Copy` though](https://doc.rust-lang.org/stable/std/slice/fn.from_ref.html) (not sure if optimizing `Copy`s is worth it :sweat_smile:); your call.



_Suggestion:_
```XML
std::slice::from_ref(deployed_account_address.0.key())
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/native_blockifier/Cargo.toml` line 44 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCW1zZ3CzDIMc1VbKv:-Na805lG910lLMkUZCOf:bss4a2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/Cargo.toml#L44)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should this be  `cargo criterion --bench blockifier_bench`? (running with criterion_benchmark gave me "error: no bench target named `criterion_benchmark`.")
Also, how does this differ from `cargo bench --bench blockifier_bench`
</blockquote></details>

Removed.
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCf3Ng80WatCw-6C1k:-Na8D095E-9yii6X0RDD:b-9q6i0q) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L24)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is this large enough to ensure the compiler/OS doesn’t cache things we don't want it to?
In other words, this will generate a bunch of txs between the same contracts that only differ in nonce (IIUC the transfer amount is fixed?), will parts of these get cached?
</blockquote></details>

Increased to 10K, not sure if this is enough though, locally I'm getting erratic benchmark results.
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCcRal5tdolJwXerN1:-Na7xaJ3-YcISJnJc2RR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L62)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

also for address and nonce
</blockquote></details>

Done.
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYC_C4T5GUBoho6cMda:-Na8-Eki-QZXR9sZ-srl:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L63)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Why fullpath here and in `prepare_accounts` return value?
We tend not to do this for SN API types when it is unambiguous (for example `ClassHash` in this module).
</blockquote></details>

Done
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCcTF-7XnHr5Pc8snh:-Na7xeOa2GJQKH9QAcbW:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L69)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

also for address and nonce.
</blockquote></details>

Done
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCb37-DQATpXjAyzE9:-Na7y1e69iFpqRMamMNB:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L75)):*
> ```XML
>     nonces[account0] += 1;
> 
>     let entry_point_selector = selector_from_name("transfer");
> ```

Done
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCbYPV5TymZa8gm6-r:-Na8-2xm9LQ0tx7hBFfG:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L82)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Wrap in variables or add comments plz?
Alternatively, is there anywhere in the `blockifier` codebase that explains these? (I couldn't find it myself)
</blockquote></details>

Done

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @giladchase and @spapinistarkware)

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 4 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @giladchase and @spapinistarkware)

___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCdnYR8QsiNF6UEPV_:-NbsnEid-vgVM-MXVtRE:b-yerjjv) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L88)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not sure if this helps readability or not, also the suggestion adds a function call in the middle of a benchmark, so probably worse on that aspect...
WDYT?
</blockquote></details>

Let's not add additional runtime.
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 38 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NbsmpxPCGHqum449YRY:-NbsmpxQ51EtNrichkDV:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c793d1fe4158cdec92c2a2b69a1658e736279513/crates/native_blockifier/bench/blockifier_bench.rs#L38)):*
> ```XML
>         (test_erc20_class_hash, ContractClassV0::from_file(ERC20_CONTRACT_PATH).into()),
>     ]);
>     // Deploy the erc20 contract.
> ```





_Suggestion:_
```XML
ERC20
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/618#-Nbsmv1N4U3jAihpg6z6:-Nbsmv1N4U3jAihpg6z7:ba3wb2o) ([raw file](https://github.com/starkware-libs/blockifier/blob/c793d1fe4158cdec92c2a2b69a1658e736279513/crates/native_blockifier/bench/blockifier_bench.rs#L49)):*
> ```XML
> }
> 
> pub fn transfers_benchmark(c: &mut Criterion) {
> ```

Is this the convention in their docs.? :(



_Code quote:_
```XML
c
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 55 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/618#-Nbsn-ba8Iq4cRaT4wWq:-Nbsn-ba8Iq4cRaT4wWr:b3facjo) ([raw file](https://github.com/starkware-libs/blockifier/blob/c793d1fe4158cdec92c2a2b69a1658e736279513/crates/native_blockifier/bench/blockifier_bench.rs#L55)):*
> ```XML
> 
>     let mut sender_account = 0;
>     c.bench_function("transfers", |b| {
> ```

Give this an informative name.



_Code quote:_
```XML
|b|
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 109 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NbsnRHCDhz0fKVxL2O7:-NbsnRHCDhz0fKVxL2O8:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/c793d1fe4158cdec92c2a2b69a1658e736279513/crates/native_blockifier/bench/blockifier_bench.rs#L109)):*
> ```XML
>     let mut addresses = vec![];
>     let mut nonces = vec![];
>     for i in 0..N_ACCOUNTS {
> ```





_Suggestion:_
```XML
`account_salt`
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 114 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NbsnUfmB-e-1uz4Zgx-:-NbsnUfmB-e-1uz4Zgx0:b-3jpeo0) ([raw file](https://github.com/starkware-libs/blockifier/blob/c793d1fe4158cdec92c2a2b69a1658e736279513/crates/native_blockifier/bench/blockifier_bench.rs#L114)):*
> ```XML
>             TEST_ACCOUNT_CONTRACT_CLASS_HASH,
>             Fee(MAX_FEE),
>             None,
> ```

Informative names?



_Code quote:_
```XML
None,
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)* status: all files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 1 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NbsnphSCHEmaDY-py48:-NbsnphSCHEmaDY-py49:b-soy9ij) ([raw file](https://github.com/starkware-libs/blockifier/blob/c793d1fe4158cdec92c2a2b69a1658e736279513/crates/native_blockifier/bench/blockifier_bench.rs#L1)):*
> ```XML
> //! Benchmark for the blockifier crate. Run using `cargo bench --bench blockifier_bench`.
> ```

Consider documenting this module a bit more, especially re the framework.
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 138 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/618#-Nbsnk0W11aPk1D_aNou:-Nbsnk0X-3hlvV1PoMJe:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c793d1fe4158cdec92c2a2b69a1658e736279513/crates/native_blockifier/bench/blockifier_bench.rs#L138)):*
> ```XML
>         account_tx.execute(state, block_context, charge_fee, validate).unwrap();
>     }
>     (addresses, nonces)
> ```





_Suggestion:_
```XML
    }
    
    (addresses, nonces)
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)* status: all files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/618#-NYCYR2V6tuhZyVl46fj:-NbsoteQ1EpuptgK3BtD:b35klbz) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea12507ee4039d0d7746d06262cfd8f9f660c481/crates/native_blockifier/bench/blockifier_bench.rs#L114)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not sure if the suggestion is better, [saves a `Copy` though](https://doc.rust-lang.org/stable/std/slice/fn.from_ref.html) (not sure if optimizing `Copy`s is worth it :sweat_smile:); your call.
</blockquote></details>

Nah, let's skip it.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @elintul and @spapinistarkware)

___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/618#-Nbsmv1N4U3jAihpg6z6:-Nc2dxwk79I6UAsUNLqe:by5risa) ([raw file](https://github.com/starkware-libs/blockifier/blob/c793d1fe4158cdec92c2a2b69a1658e736279513/crates/native_blockifier/bench/blockifier_bench.rs#L49)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the convention in their docs.? :(
</blockquote></details>

[Looks like it:](https://github.com/bheisler/criterion.rs#quickstart)
They use it in their source code as well.

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618#-:-Nc2h_KW7VVbwCafqD1_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/618)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
