### PR TITLE
Remove gas price bounds from general config

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1329)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1329)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1329#-NnxF5Po1nmdkAIMqDWu:-NnxF5Po1nmdkAIMqDWv:b-bpxmu7) (no related file):*
These values are not needed in the blockifier - the final prices are given in the BlockInfo when a block is started.

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1329)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1329#-NnxFgAB3I56qSix7OQa:-NnxFgAB3I56qSix7OQb:b13xao) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/33383)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1329)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1329#-NnxFgAB3I56qSix7OQa:-No3bauc6XO6Ow7FWmn3:b-yemhz0) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[python side](https://reviewable.io/reviews/starkware-industries/starkware/33383)
</blockquote></details>

passes hodor

___

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1329#-:-No61Xrt9NZgsPSqidAj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Pull request merged**
