### PR TITLE
chore(execution): enforce nonzero gas prices

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391)* status: 0 of 11 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpFy3SyCZDYqsf_fQ9o:-NpFy3SyCZDYqsf_fQ9p:b15res) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/33648)

___

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ2hDe6zoWucL-U0mL:-NpJ2hDe6zoWucL-U0mM:b92gy9t) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/blockifier/src/fee/fee_checks.rs#L125)):*
> ```XML
>                     block_context.block_info.gas_prices.get_data_gas_price_by_fee_type(&fee_type);
>                 let total_discounted_gas_used =
>                     gas_usage + (u128::from(data_gas_price) * blob_gas_usage) / gas_price;
> ```

:chefkiss:



_Code quote:_
```XML
                let total_discounted_gas_used =
                    gas_usage + (u128::from(data_gas_price) * blob_gas_usage) / gas_price;
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ3lR-3unJVaBqaDO9:-NpJ3lR-3unJVaBqaDOA:b-wj7io2) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/blockifier/src/fee/fee_utils.rs#L85)):*
> ```XML
>     // TODO(Aner, 25/01/24) compute via linear combination and rename function accordingly.
>     Fee(l1_gas_usages.gas_usage
>         * u128::from(block_info.gas_prices.get_gas_price_by_fee_type(fee_type)))
> ```

What happens on overflow?

If we want to saturate then we should be explicit: we can use [saturdating_mul](https://doc.rust-lang.org/std/num/struct.NonZeroU128.html#method.saturating_mul), which guarantees MAX value on overflow.

Alternatively, there's also [checked_mul](https://doc.rust-lang.org/std/num/struct.NonZeroU128.html#method.checked_mul) which returns None on overflow, which also ensures non-zero after the mul, but adding an option will probably be an annoyance here.



_Code quote:_
```XML
    Fee(l1_gas_usages.gas_usage
        * u128::from(block_info.gas_prices.get_gas_price_by_fee_type(fee_type)))
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ4g22CItY2X7YyEee:-NpJ4g22CItY2X7YyEef:b9brknm) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/blockifier/src/test_utils/struct_impls.rs#L108)):*
> ```XML
>             vm_resource_fee_cost: Default::default(),
>             gas_prices: GasPrices {
>                 eth_l1_gas_price: NonZeroU128::new(DEFAULT_ETH_L1_GAS_PRICE).unwrap(),
> ```

Consider hiding `NonZeroU128`, it's an implementation detail which we might decide to get rid off if we find a quirk in it, hiding it will make the fix easier.



_Suggestion:_
```XML
DEFAULT_ETH_L1_GAS_PRICE.try_into().unwrap(),
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ57sd8iQAs5gL-sK5:-NpJ57sd8iQAs5gL-sK6:bf39688) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/blockifier/src/transaction/execution_flavors_test.rs#L278)):*
> ```XML
>     if !is_deprecated {
>         let result = account_invoke_tx(invoke_tx_args! {
>             resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, u128::from(gas_price) - 1),
> ```

nit picking here: could gas_price - 1 be 0 here? :sweat_smile: 



_Code quote:_
```XML
            resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, u128::from(gas_price) - 1),
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 318 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ5MpE38K-8v7558sK:-NpJ5MpE38K-8v7558sL:b3zx2xw) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/native_blockifier/src/py_block_executor.rs#L318)):*
> ```XML
>                 strk_l1_data_gas_price: NonZeroU128::new(block_info.l1_data_gas_price.price_in_fri)
>                     .unwrap_or_else(|| panic!("Fri data gas price is zero.")),
>             },
> ```

let's return NativeBlockifierInputError here?
(panic == blockifier is brokenz and needs fix, which isn't the case here, it's python that sent bad stuff)



_Code quote:_
```XML
            gas_prices: GasPrices {
                eth_l1_gas_price: NonZeroU128::new(block_info.l1_gas_price.price_in_wei)
                    .unwrap_or_else(|| panic!("Wei gas price is zero.")),
                strk_l1_gas_price: NonZeroU128::new(block_info.l1_gas_price.price_in_fri)
                    .unwrap_or_else(|| panic!("Fri gas price is zero.")),
                eth_l1_data_gas_price: NonZeroU128::new(block_info.l1_data_gas_price.price_in_wei)
                    .unwrap_or_else(|| panic!("Wei data gas price is zero.")),
                strk_l1_data_gas_price: NonZeroU128::new(block_info.l1_data_gas_price.price_in_fri)
                    .unwrap_or_else(|| panic!("Fri data gas price is zero.")),
            },
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ6B3cDkk1AixJJEws:-NpJ6B3cDkk1AixJJEwt:b-bqqiqo) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/native_blockifier/src/py_state_diff.rs#L155)):*
> ```XML
>         }
>     }
> }
> ```

Hmm i think `Default` is generally much expected to be trivial, at least as far as i can find.

Looks like there is only one usage for this, in a test, so for now I think it can just be a rstest fixture and side-step the issue.



_Code quote:_
```XML
/// Block info cannot have gas prices set to zero; implement `Default` explicitly.
impl Default for PyBlockInfo {
    fn default() -> Self {
        Self {
            block_number: u64::default(),
            block_timestamp: u64::default(),
            l1_gas_price: PyResourcePrice {
                price_in_wei: DEFAULT_ETH_L1_GAS_PRICE,
                price_in_fri: DEFAULT_STRK_L1_GAS_PRICE,
            },
            l1_data_gas_price: PyResourcePrice {
                price_in_wei: DEFAULT_ETH_L1_DATA_GAS_PRICE,
                price_in_fri: DEFAULT_STRK_L1_DATA_GAS_PRICE,
            },
            sequencer_address: PyFelt::default(),
            use_kzg_da: bool::default(),
        }
    }
}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ3lR-3unJVaBqaDO9:-NpJRYLX9RhXVyMmHWAi:booirdq) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/blockifier/src/fee/fee_utils.rs#L85)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What happens on overflow?

If we want to saturate then we should be explicit: we can use [saturdating_mul](https://doc.rust-lang.org/std/num/struct.NonZeroU128.html#method.saturating_mul), which guarantees MAX value on overflow.

Alternatively, there's also [checked_mul](https://doc.rust-lang.org/std/num/struct.NonZeroU128.html#method.checked_mul) which returns None on overflow, which also ensures non-zero after the mul, but adding an option will probably be an annoyance here.
</blockquote></details>

gas_usage can be zero (or at least, it should be allowed to be zero).
however, perhaps we want to panic on overflow here...? WDYT?
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ57sd8iQAs5gL-sK5:-NpJSOJF09Oc_VIwtq0k:b-4ugzc3) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/blockifier/src/transaction/execution_flavors_test.rs#L278)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

nit picking here: could gas_price - 1 be 0 here? :sweat_smile:
</blockquote></details>

yes.
gas price cannot be zero, but gas price *bound* must be allowed to be zero. this is fine
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 318 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ5MpE38K-8v7558sK:-NpJUO4w6iyQJs3bac80:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/native_blockifier/src/py_block_executor.rs#L318)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

let's return NativeBlockifierInputError here?
(panic == blockifier is brokenz and needs fix, which isn't the case here, it's python that sent bad stuff)
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ6B3cDkk1AixJJEws:-NpJUWgED6k6Bl763nd2:bg280ly) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/native_blockifier/src/py_state_diff.rs#L155)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Hmm i think `Default` is generally much expected to be trivial, at least as far as i can find.

Looks like there is only one usage for this, in a test, so for now I think it can just be a rstest fixture and side-step the issue.
</blockquote></details>

Since we divide by prices in business logic, I would argue `PyResourcePrice` cannot have zero values, even for testing.
"trivial" default is fine but it must be "valid", no?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpFy3SyCZDYqsf_fQ9o:-NpJd9fT0h6NvzLjcE9x:b-yemhz0) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[python side](https://reviewable.io/reviews/starkware-industries/starkware/33648)
</blockquote></details>

passes hodor

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391)* status: 4 of 13 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ3lR-3unJVaBqaDO9:-NpQvy9cCXMBiXCGH0Gi:b-t0qrxu) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/blockifier/src/fee/fee_utils.rs#L85)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not sure :thinking: 
Returning an error might not be correct, because the user input has no control over this calc, it's purely circumstantial (is that correct?).
If that's the case, we need product input on this, perhaps they prefer overflow...
</blockquote></details>

asking
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ6B3cDkk1AixJJEws:-NpQv1ot8pw9O0y6esFZ:b-bgpj5z) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/native_blockifier/src/py_state_diff.rs#L155)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

yes yes i agree, therefore i think PyBLockInfo shouldn't have a Default impl, and this construction should be handled through a constructor / inline construction.
</blockquote></details>

why...? we have default gas prices for a reason, why not use them?

**Review by giladchase — APPROVED** [review]
> Reviewed 8 of 9 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ3lR-3unJVaBqaDO9:-NpZzVgk279myGneUyZ6:bksm7ji) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/blockifier/src/fee/fee_utils.rs#L85)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

saturating it is
</blockquote></details>

Cool! 
Did they say if saturation should be a notable event?
That is, should we log::warn/info when saturation happens? or is it a non-issue
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpJ6B3cDkk1AixJJEws:-NpZzlHH702An0r0PuU4:b4abprx) ([raw file](https://github.com/starkware-libs/blockifier/blob/07e7786dfc38c676ba829b3274328793627bbc13/crates/native_blockifier/src/py_state_diff.rs#L155)):*
>Hmm i think `Default` is generally much expected to be trivial, at least as far as i can find.

Found a good [counter argument](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md#constructors), retracting.

**Review by giladchase — DISMISSED** [review]
:lgtm:

> Reviewed 11 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-:-NpnO0di4W2qfM9ii-m0:bnfp4nl)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpnLzDu5oLshLiqGKBO:-NpnLzDu5oLshLiqGKBP:brxmo56) ([raw file](https://github.com/starkware-libs/blockifier/blob/95cd6bb5df4571d365287087f3be6179cbed34a7/crates/blockifier/src/transaction/objects.rs#L152)):*
> ```XML
>                 u128::MAX
>             }
>         };
> ```

If you feel like it (in the other ones as well), not critical though.



_Suggestion:_
```XML
        let l1_gas_cost = self.l1_gas.checked_mul(gas_price).unwrap_or_else(|| {
            log::warn!(
                "L1 gas cost overflowed: multiplication of {} by {} resulted in overflow.",
                self.l1_gas,
                gas_price
            );
            u128::MAX
    });
```

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 12 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/block_context.rs` line 2 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1391#-NpoQZAj5uQi1t33W8tB:-NpoQZAj5uQi1t33W8tC:by89f6w) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0c1e2bcd1b9f979df72c6682e278e8e92d901ee/crates/blockifier/src/block_context.rs#L2)):*
> ```XML
> use std::collections::HashMap;
> use std::num::NonZeroU128;
> ```

this file was deleted (srry again), real code is in `block.rs`

**Review by giladchase — APPROVED** [review]
> Reviewed 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Pull request merged**
