### PR TITLE
Fix py_account_data_context

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemO58T8c_PvSIbwqme:-NemO58T8c_PvSIbwqmf:b-sbhdbl) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d48719ec82ac514198dc420a46fdd661d3f5ce/crates/native_blockifier/src/py_transaction.rs#L106)):*
> ```XML
>             0 => Ok(PyDataAvailabilityMode::L1),
>             1 => Ok(PyDataAvailabilityMode::L2),
>             _ => panic!("Invalid data availability mode"),
> ```

Why is it a `panic` here and not in `PyResource`?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemD9_j3MVcUS2TVBAX:-NemD9_j3MVcUS2TVBAY:b-uzxt1r) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d48719ec82ac514198dc420a46fdd661d3f5ce/crates/native_blockifier/src/py_transaction.rs#L141)):*
> ```XML
>     let py_signature: Vec<PyFelt> = py_attr(tx, "signature")?;
>     let signature: Vec<StarkFelt> = py_signature.into_iter().map(|felt| felt.0).collect();
>     let max_fee: Fee = if TransactionVersion(py_attr::<PyFelt>(tx, "version")?.0)
> ```

Extract to variable.



_Code quote:_
```XML
TransactionVersion(py_attr::<PyFelt>(tx, "version")?.0
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemDEYS2G4o_3djqZbh:-NemDEYS2G4o_3djqZbi:b-vyizhn) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d48719ec82ac514198dc420a46fdd661d3f5ce/crates/native_blockifier/src/py_transaction.rs#L153)):*
> ```XML
>             resource_bounds.0.get(&Resource::L1Gas).copied().unwrap_or_default();
>         // Calculate max_fee when version is >= 3
>         Fee(l1_resource_bounds.max_amount as u128 * l1_resource_bounds.max_price_per_unit)
> ```

Extract to function.



_Code quote:_
```XML
        let py_resource_bounds: PyResourceBoundsMapping = py_attr(tx, "resource_bounds")?;
        let resource_bounds: ResourceBoundsMapping =
            ResourceBoundsMapping::from(py_resource_bounds);
        let l1_resource_bounds =
            resource_bounds.0.get(&Resource::L1Gas).copied().unwrap_or_default();
        // Calculate max_fee when version is >= 3
        Fee(l1_resource_bounds.max_amount as u128 * l1_resource_bounds.max_price_per_unit)
```

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemWxMYETcw31zYB-WI:-NemWxMZ8_m7opMTVXV8:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d48719ec82ac514198dc420a46fdd661d3f5ce/crates/native_blockifier/src/py_transaction.rs#L57)):*
> ```XML
>             "L1Gas" => Ok(PyResource::L1Gas),
>             _ => Ok(PyResource::L2Gas),
>         }
> ```





_Suggestion:_
```XML
        let resource_name: String = py_attr(resource, "name")?;
        match resource_name {
            "L1Gas" => Ok(PyResource::L1Gas),
            "L2Gas"=> Ok(PyResource::L2Gas),
            _ => <return_an_error>
        }
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/929#-Nem8GrQ67ep6k5_Oxj6:-Nem8GrQ67ep6k5_Oxj7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d48719ec82ac514198dc420a46fdd661d3f5ce/crates/native_blockifier/src/py_transaction.rs#L107)):*
> ```XML
>             1 => Ok(PyDataAvailabilityMode::L2),
>             _ => panic!("Invalid data availability mode"),
>         }
> ```





_Suggestion:_
```XML
        let data_availability_mode: i32 = data_availability_mode.extract()?;
        match data_availability_mode {
            0 => Ok(PyDataAvailabilityMode::L1),
            1 => Ok(PyDataAvailabilityMode::L2),
            _ => panic!("Invalid data availability mode"),
        }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemO58T8c_PvSIbwqme:-NemVTqhEky-dck0KQH4:bilehdl) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d48719ec82ac514198dc420a46fdd661d3f5ce/crates/native_blockifier/src/py_transaction.rs#L106)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why is it a `panic` here and not in `PyResource`?
</blockquote></details>

Replaced with `PyErr`.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemDEYS2G4o_3djqZbh:-NemXoCl60YjaR-YBIwJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d48719ec82ac514198dc420a46fdd661d3f5ce/crates/native_blockifier/src/py_transaction.rs#L153)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Extract to function.
</blockquote></details>

Done.

**Review by alonh5 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 167 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemYji4-GIPa1m_kIih:-NemYji4-GIPa1m_kIii:b-yxxppm) ([raw file](https://github.com/starkware-libs/blockifier/blob/88f4653c4535c56fa1e47cd3c90554a62e8c3912/crates/native_blockifier/src/py_transaction.rs#L167)):*
> ```XML
>     } else {
>         let py_resource_bounds: PyResourceBoundsMapping = py_attr(tx, "resource_bounds")?;
>         calculate_max_fee(py_resource_bounds.clone())
> ```

Why must it be cloned?



_Code quote:_
```XML
py_resource_bounds.clone()
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NembElYDJFcnpjFbv4k:-NembElYDJFcnpjFbv4l:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/88f4653c4535c56fa1e47cd3c90554a62e8c3912/crates/native_blockifier/src/py_transaction.rs#L174)):*
> ```XML
>         max_fee,
>         signature: TransactionSignature(signature),
>         version: TransactionVersion(py_attr::<PyFelt>(tx, "version")?.0),
> ```





_Suggestion:_
```XML
    let version = TransactionVersion(py_attr::<PyFelt>(tx, "version")?.0);
    let max_fee: Fee = if version < TransactionVersion::THREE
    {
        // Use max_fee from tx when version is < 3
        Fee(py_attr(tx, "max_fee")?) // Assuming max_fee is of type Fee
    } else {
        let py_resource_bounds: PyResourceBoundsMapping = py_attr(tx, "resource_bounds")?;
        calculate_max_fee(py_resource_bounds.clone())
    };

    Ok(AccountTransactionContext {
        transaction_hash: TransactionHash(py_attr::<PyFelt>(tx, "hash_value")?.0),
        max_fee,
        signature: TransactionSignature(signature),
        version,
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemtPQTCtYNQ0M79nCm:-NemtPQTCtYNQ0M79nCn:b-frwmda) (no related file):*
Python PR? 

___
___
*[`crates/native_blockifier/src/py_transaction.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemWxMYETcw31zYB-WI:-NemspDJ-E9xxxOto5in:bnz2530) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d48719ec82ac514198dc420a46fdd661d3f5ce/crates/native_blockifier/src/py_transaction.rs#L57)):*
> ```XML
>             "L1Gas" => Ok(PyResource::L1Gas),
>             _ => Ok(PyResource::L2Gas),
>         }
> ```

No need for the comments. 
___
*[`crates/native_blockifier/src/py_transaction.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/929#-Nem8GrQ67ep6k5_Oxj6:-NemsrBS7ne3EP_FtKt8:bnz2530) ([raw file](https://github.com/starkware-libs/blockifier/blob/41d48719ec82ac514198dc420a46fdd661d3f5ce/crates/native_blockifier/src/py_transaction.rs#L107)):*
> ```XML
>             1 => Ok(PyDataAvailabilityMode::L2),
>             _ => panic!("Invalid data availability mode"),
>         }
> ```

No need for the comments. 
___
*[`crates/native_blockifier/src/py_transaction.rs` line 140 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemtEdq1bebRvSByLpl:-NemtEdq1bebRvSByLpm:b-ppcwzz) ([raw file](https://github.com/starkware-libs/blockifier/blob/33f20e8928b02949f44d258bd67e7941ca2bcf4c/crates/native_blockifier/src/py_transaction.rs#L140)):*
> ```XML
> }
> 
> fn calculate_max_fee(py_resource_bounds: PyResourceBoundsMapping) -> Fee {
> ```

Can this be a method? 
___
*[`crates/native_blockifier/src/py_transaction.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemtJaP1XrFeTrguWdc:-NemtJaP1XrFeTrguWdd:b-rnfbc2) ([raw file](https://github.com/starkware-libs/blockifier/blob/33f20e8928b02949f44d258bd67e7941ca2bcf4c/crates/native_blockifier/src/py_transaction.rs#L157)):*
> ```XML
>     } else {
>         let py_resource_bounds: PyResourceBoundsMapping = py_attr(tx, "resource_bounds")?;
>         assert_eq!(1, 0);
> ```

Remove assert?

**Review by giladchase — COMMENTED** [review]
Taking Over :smiling_imp: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929#-:-NfFFkLQBbpLTOBIEvJL:b-ik9qfh)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemtJaP1XrFeTrguWdc:-NfFIah85YRUuvxr6hkl:bwum426) ([raw file](https://github.com/starkware-libs/blockifier/blob/33f20e8928b02949f44d258bd67e7941ca2bcf4c/crates/native_blockifier/src/py_transaction.rs#L157)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove assert?
</blockquote></details>

Done (by @MohammadNassar1).
___
*[`crates/native_blockifier/src/py_transaction.rs` line 79 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NenBLCi3CYk_dPum86P:-NfFJFf8-EB0BJF_Zwz5:b-qp32au) ([raw file](https://github.com/starkware-libs/blockifier/blob/97a73f74dee730c2e528b08f3337f84c2fde1eb2/crates/native_blockifier/src/py_transaction.rs#L79)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use this method in the transactions' `max_fee` getter?
Need to move to the non-`Py` struct instead.
</blockquote></details>

Looks like the method (calculate_max_fee) was removed from here in a separate PR?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 80 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NenBHYV41i8PckJ19A4:-NfFI4Fl5w-zWEIjU3K1:b7xm0bk) ([raw file](https://github.com/starkware-libs/blockifier/blob/97a73f74dee730c2e528b08f3337f84c2fde1eb2/crates/native_blockifier/src/py_transaction.rs#L80)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove blank line above.
</blockquote></details>

Done (by @MohammadNassar1)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemtPQTCtYNQ0M79nCm:-NfFOTeMCqUG3s7X8n_X:bsg4387) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Python PR?
</blockquote></details>

Python: https://reviewable.io/reviews/starkware-industries/starkware/31960

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemtJaP1XrFeTrguWdc:-NfFfr7q15lSBqYPyf3i:byfxkpr) ([raw file](https://github.com/starkware-libs/blockifier/blob/33f20e8928b02949f44d258bd67e7941ca2bcf4c/crates/native_blockifier/src/py_transaction.rs#L157)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done (by @MohammadNassar1).
</blockquote></details>

It shouldn't be zero in V3, but the product of `l1_gas_max_amount` and `l1_gas_max_price`.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NfFfRpA9lU97XhGy9Bp:-NfFfRpA9lU97XhGy9Bq:b-73bhnf) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4e570e3d832487019aa3ae3962505fd0a4651ea/crates/native_blockifier/src/py_transaction.rs#L51)):*
> ```XML
> impl FromPyObject<'_> for PyResource {
>     fn extract(resource: &PyAny) -> PyResult<Self> {
>         let resource_name: &str = resource.getattr("name")?.extract()?;
> ```

Can you please explain the difference from the previous attribute extraction?



_Code quote:_
```XML
let resource_name: &str = resource.getattr("name")?.extract()?;
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemtJaP1XrFeTrguWdc:-NfGPm5UE0aagVo0QiSy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/33f20e8928b02949f44d258bd67e7941ca2bcf4c/crates/native_blockifier/src/py_transaction.rs#L157)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It shouldn't be zero in V3, but the product of `l1_gas_max_amount` and `l1_gas_max_price`.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NfFfRpA9lU97XhGy9Bp:-NfGCcAsDtuhSCEd4xF-:brl6wig) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4e570e3d832487019aa3ae3962505fd0a4651ea/crates/native_blockifier/src/py_transaction.rs#L51)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you please explain the difference from the previous attribute extraction?
</blockquote></details>

Wanted to cast directly into &str since we're matching on &str anyway.
Had to manually extract rather than `py_attir`ng cause (it looks like)`py_attr` doesn't support extracting into &str (probably lifetime issues).
No critical, can revert.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemtJaP1XrFeTrguWdc:-NfLAA8U4SzUkYlTvZPF:b-smz22o) ([raw file](https://github.com/starkware-libs/blockifier/blob/33f20e8928b02949f44d258bd67e7941ca2bcf4c/crates/native_blockifier/src/py_transaction.rs#L157)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done.
</blockquote></details>

WDYT about a small method of `ResourceBoundsMapping`: `get_l1_gas_max_fee`?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5, @elintul, and @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NemtJaP1XrFeTrguWdc:-NfLGzgh1EBFt0XqUSvU:b-o6mhp4) ([raw file](https://github.com/starkware-libs/blockifier/blob/33f20e8928b02949f44d258bd67e7941ca2bcf4c/crates/native_blockifier/src/py_transaction.rs#L157)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT about a small method of `ResourceBoundsMapping`: `get_l1_gas_max_fee`?
</blockquote></details>

Added as utils, since it's part of SN API

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 63 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NfLQx3A8IsuJ5gBfFea:-NfLQx3A8IsuJ5gBfFeb:bcpxj3n) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ff9ecc876b145876051507d449b8dc2a7866f40/crates/blockifier/src/fee/fee_utils.rs#L63)):*
> ```XML
> 
> // TODO(gilad) add to SN API as a method.
> pub fn l1_gas_max_fee(resource_bounds_mapping: ResourceBoundsMapping) -> Fee {
> ```

Can you use in transactions' `max_fee` getter as well?



_Suggestion:_
```XML
get_l1_gas_max_fee
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 63 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/929#-NfLQx3A8IsuJ5gBfFea:-NfLyoWcBRfpXLtVCKS1:bidms98) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ff9ecc876b145876051507d449b8dc2a7866f40/crates/blockifier/src/fee/fee_utils.rs#L63)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you use in transactions' `max_fee` getter as well?
</blockquote></details>

Handled at https://reviewable.io/reviews/starkware-libs/blockifier/944

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/929#-:-NfPwY6F7-DbpheUImCA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
