### PR TITLE
Update contract syntax.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/623)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
Did you compile the contract using `2.0.0-rc1`commit?
Does the new compiler version affect `empty_contract.cairo`? If so, can you please recompile it as well?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/623#-:-NYC_1fZ4dxaEu5baUuD:b-qu575v)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/623#-NYCXb2eASZqnj5I8U3S:-NYCXb2eASZqnj5I8U3T:b-bdte0y) ([raw file](https://github.com/starkware-libs/blockifier/blob/316fcc5765e20014e5d7949180587cf69a61a92a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L267)):*
> ```XML
>     };
>     let storage_entry_point_vm_resources = VmExecutionResources {
>         n_steps: 147,
> ```

Do we need to update the `os_resources` file? 



_Code quote:_
```XML
 n_steps: 147,
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 288 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/623#-NYCXf8N23P7xC_rFKCV:-NYCXf8N23P7xC_rFKCW:b-1do3us) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc9a73aef38853ace0ae3ec95546ec504e158567/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L288)):*
> ```XML
>         builtin_instance_counter: HashMap::from([(RANGE_CHECK_BUILTIN_NAME.to_string(), 8)]),
>     };
>     library_call_vm_resources += &storage_entry_point_vm_resources;
> ```

Why did you remove it? Do you think it's better to simply write the expected values?



_Code quote:_
```XML
    library_call_vm_resources += &storage_entry_point_vm_resources;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 288 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/623#-NYCXf8N23P7xC_rFKCV:-NYCwJyBChzsrzqX15RO:b-r4jfab) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc9a73aef38853ace0ae3ec95546ec504e158567/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L288)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you remove it? Do you think it's better to simply write the expected values?
</blockquote></details>

it was much easier to fix the test this way.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/623#-NYCXb2eASZqnj5I8U3S:-NYCwcII2jkvXY09-_4I:b-87j9c5) ([raw file](https://github.com/starkware-libs/blockifier/blob/316fcc5765e20014e5d7949180587cf69a61a92a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L267)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we need to update the `os_resources` file? 
</blockquote></details>

should the `os_resources` file include only the OS costs?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
I compiled it with `2.0.0-rc2'

do you know why the test contract has a sierra.json file but the empty_contract doesn’t?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/623#-:-NYD-lxy4FlPUxJO5VqC:bm3lq79)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
No. We do not need the sierra.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/623#-:-NYHQUVC9bKOirP_Naxx:bqqljpn)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/623#-NYCXb2eASZqnj5I8U3S:-NYHRjiFBhRXubqYquK4:b-jgczju) ([raw file](https://github.com/starkware-libs/blockifier/blob/316fcc5765e20014e5d7949180587cf69a61a92a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L267)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

should the `os_resources` file include only the OS costs?
</blockquote></details>

It contains the syscalls cost (and I saw that the `n_steps` was changed)
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 288 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/623#-NYCXf8N23P7xC_rFKCV:-NYHUhKv8wH_CBUaCErz:bkoh86x) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc9a73aef38853ace0ae3ec95546ec504e158567/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L288)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it was much easier to fix the test this way.
</blockquote></details>

I see. And do you find it as readable as the previous one?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/623)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/623#-NYCXb2eASZqnj5I8U3S:-NYHdIPS4IaHXq4zRyPg:b-qwgd4n) ([raw file](https://github.com/starkware-libs/blockifier/blob/316fcc5765e20014e5d7949180587cf69a61a92a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L267)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It contains the syscalls cost (and I saw that the `n_steps` was changed)
</blockquote></details>

I didn't change the OS.

Only the code that triggers the system call changed.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 288 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/623#-NYCXf8N23P7xC_rFKCV:-NYHdNgu2O7j4u5ojN3o:bb7sa0c) ([raw file](https://github.com/starkware-libs/blockifier/blob/cc9a73aef38853ace0ae3ec95546ec504e158567/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L288)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see. And do you find it as readable as the previous one?
</blockquote></details>

yes.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
should I delete the sierra of the test_contract as well?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/623#-:-NYHdS5PAZzV4Mgdun9L:b-yjk1gt)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/623)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/623#-NYCXb2eASZqnj5I8U3S:-NYHi3AsEaFxUUy_nqHw:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/316fcc5765e20014e5d7949180587cf69a61a92a/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L267)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it. Thanks.
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/623)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
