### PR TITLE
Add `tx_signature_start_ptr` to syscall handler.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/221)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/221)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/syscalls.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMTQT7x4qJ0IwtYXPXB:-NMTQT7x4qJ0IwtYXPXC:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/df092b7fdaaf392cd079bfa02ef532db9034d91c/crates/blockifier/src/execution/syscalls.rs#L81)):*
> ```XML
>     fn write(self, vm: &mut VirtualMachine, ptr: &Relocatable) -> WriteResponseResult {
>         vm.insert_value(ptr, self.start_ptr)?;
>         Ok(vm.insert_value(&(ptr + 1), self.length)?)
> ```

.



_Suggestion:_
```XML
        vm.insert_value(ptr, self.length)?;
        Ok(vm.insert_value(&(ptr + 1), self.start_ptr)?)
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/221)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMSr6fRBbeZBoxik_OO:-NMU3B543h8szE_YBJfG:b-5jo9kh) ([raw file](https://github.com/starkware-libs/blockifier/blob/df092b7fdaaf392cd079bfa02ef532db9034d91c/crates/blockifier/src/execution/syscall_handling.rs#L134)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Implementation detail?
</blockquote></details>

I like that the name let's you know the side effect, and it doesn't feel like a simple getter.
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMSqG8GB7WCjHH_XTIT:-NMU3Zhh5wzgkRgFjlkJ:bpfugy5) ([raw file](https://github.com/starkware-libs/blockifier/blob/df092b7fdaaf392cd079bfa02ef532db9034d91c/crates/blockifier/src/execution/syscall_handling.rs#L142)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You're doing this assignment both here and in `allocate_tx_signature_segment()`.
</blockquote></details>

Right, thanks!



_Code quote:_
```XML
self.tx_signature_start_ptr
```
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMSrb79AUXDo_OmWQJP:-NMU3b0sDEtYckIiDWPy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/df092b7fdaaf392cd079bfa02ef532db9034d91c/crates/blockifier/src/execution/syscall_handling.rs#L184)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This isn't necessary in this case.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMSrzQ90NlW0i3eHsPS:-NMU4L5Z9TCxJTAF50nM:b-vskzwp) ([raw file](https://github.com/starkware-libs/blockifier/blob/df092b7fdaaf392cd079bfa02ef532db9034d91c/crates/blockifier/src/execution/syscalls.rs#L79)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Now that `Relocatable` is `Copyable` we don't need to reference it (same as we wouldn't reference an `integer`). Doesn't have to be in this PR but I think we should remove the references everywhere, WDYT?
</blockquote></details>

I'll open a PR. WDYT of suggesting it to LC as well?
___
*[`crates/blockifier/src/execution/syscalls.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMTQT7x4qJ0IwtYXPXB:-NMU4QKH748wHlZ_QQvO:brsh7ji) ([raw file](https://github.com/starkware-libs/blockifier/blob/df092b7fdaaf392cd079bfa02ef532db9034d91c/crates/blockifier/src/execution/syscalls.rs#L81)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

.
</blockquote></details>

Damn, thanks.
___
*[`crates/blockifier/src/execution/syscalls.rs` line 481 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMSsmNa7XWs2_LVTTW5:-NMU8YMU1HN2bbDwYSl_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/df092b7fdaaf392cd079bfa02ef532db9034d91c/crates/blockifier/src/execution/syscalls.rs#L481)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Create `GetTxSignatureResponse` alias?
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/221)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMSqG8GB7WCjHH_XTIT:-NMXk0Hl1Bz_5OG8HI3Q:bqmuidm) ([raw file](https://github.com/starkware-libs/blockifier/blob/df092b7fdaaf392cd079bfa02ef532db9034d91c/crates/blockifier/src/execution/syscall_handling.rs#L142)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Right, thanks!
</blockquote></details>

I don't see any of them removed. 
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMXjOw29ZHw6EIqcD-n:-NMXjOw29ZHw6EIqcD-o:b-k8l2qh) ([raw file](https://github.com/starkware-libs/blockifier/blob/b482bf74a20005d20f25dc4bea35703a66083d00/crates/blockifier/src/execution/syscall_handling.rs#L244)):*
> ```XML
>     let segment_start_ptr = vm.add_memory_segment();
>     vm.insert_value(&(ptr + 1), segment_start_ptr)?;
>     let data = data.iter().map(|&x| MaybeRelocatable::from(stark_felt_to_felt(x))).collect();
> ```

What changed that this was needed?



_Code quote:_
```XML
&
```
___
*[`crates/blockifier/src/execution/syscalls.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMSrzQ90NlW0i3eHsPS:-NMXjXXW20jZ_DLCQSB8:bi89xty) ([raw file](https://github.com/starkware-libs/blockifier/blob/df092b7fdaaf392cd079bfa02ef532db9034d91c/crates/blockifier/src/execution/syscalls.rs#L79)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'll open a PR. WDYT of suggesting it to LC as well?
</blockquote></details>

Sure, I'll do that.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/221)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMSqG8GB7WCjHH_XTIT:-NMYObz50ijd4SRbr0uc:b-ljo57k) ([raw file](https://github.com/starkware-libs/blockifier/blob/df092b7fdaaf392cd079bfa02ef532db9034d91c/crates/blockifier/src/execution/syscall_handling.rs#L142)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I don't see any of them removed. 
</blockquote></details>

Sorry, done.



_Code quote:_
```XML
self.tx_signature_start_ptr =
```
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/221#-NMXjOw29ZHw6EIqcD-n:-NMYOj177T-LCdE0q6q2:bppj29x) ([raw file](https://github.com/starkware-libs/blockifier/blob/b482bf74a20005d20f25dc4bea35703a66083d00/crates/blockifier/src/execution/syscall_handling.rs#L244)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What changed that this was needed?
</blockquote></details>

Not sure what you mean.

**Pull request merged**
