### PR TITLE
test(execution): get_sequencer_address in test_validate_accounts_tx

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1496)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 29 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1496#-NqXmu5oCyuBnIabpMzq:-NqXmu5oCyuBnIabpMzr:b-u2holk) ([raw file](https://github.com/starkware-libs/blockifier/blob/64ce1d26d2b01336a075a1bf6176043fe0f3572f/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L29)):*
> ```Cairo
> // const GET_BLOCK_TIMESTAMP = 6;
> // Use get_sequencer_address syscall.
> const GET_SEQUENCER_ADDRESS = 7;
> ```

Please delete these unused lines.



_Suggestion:_
```Cairo
// Use get_sequencer_address syscall.
const GET_SEQUENCER_ADDRESS = 7;
```

**Comment by aner-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 29 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1496#-NqXmu5oCyuBnIabpMzq:-NqXyML15B9BSSMtENGa:b28ngik) ([raw file](https://github.com/starkware-libs/blockifier/blob/64ce1d26d2b01336a075a1bf6176043fe0f3572f/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L29)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please delete these unused lines.
</blockquote></details>

Should I add a TODO?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1496)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @MohammadNassar1, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/feature_contracts/cairo0/account_faulty.cairo` line 29 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1496#-NqXmu5oCyuBnIabpMzq:-NqYExY427v8ajp1MQZM:b-g4oszg) ([raw file](https://github.com/starkware-libs/blockifier/blob/64ce1d26d2b01336a075a1bf6176043fe0f3572f/crates/blockifier/feature_contracts/cairo0/account_faulty.cairo#L29)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Should I add a TODO?
</blockquote></details>

Yes please, but not here. See the comment below.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1485 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1496#-NqYFNWF1IA4p9JXu3DQ:-NqYFNWF1IA4p9JXu3DR:b-or06eu) ([raw file](https://github.com/starkware-libs/blockifier/blob/d6b4ad9aeabafd6ad883ae1652366afd5d814cdf/crates/blockifier/src/transaction/transactions_test.rs#L1485)):*
> ```XML
>         account_tx.execute(state, block_context, true, true).unwrap();
>     }
> ```

Please add a TODO:
// TODO(): Cover positive flows of Cairo 0 syscalls: get_block_number and get_block_timestamp.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1496)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware, @noaov1, and @TzahiTaub)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1440 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1496#-NqcPcsJ6S7_butU5Zt8:-NqcPcsJ6S7_butU5Zt9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ed14fbdda1de4f9a5f224a4c1b9bda3c9c01a2d/crates/blockifier/src/transaction/transactions_test.rs#L1440)):*
> ```XML
>     }
>     if let CairoVersion::Cairo0 = cairo_version {
>         // Trying to use the syscall get_sequencer_address (forbidden).
> ```





_Suggestion:_
```XML
       // Try to use the syscall get_sequencer_address (forbidden).
```

**Review by aner-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1496#-:-NqcPnMS6Bqd_3KXY1qL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @TzahiTaub)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1496)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @TzahiTaub)

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1496)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @TzahiTaub)

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1440 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1496#-NqcPcsJ6S7_butU5Zt8:-NqcSeS90hYGFCnhTyJp:btbtdxn) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ed14fbdda1de4f9a5f224a4c1b9bda3c9c01a2d/crates/blockifier/src/transaction/transactions_test.rs#L1440)):*
> ```XML
>     }
>     if let CairoVersion::Cairo0 = cairo_version {
>         // Trying to use the syscall get_sequencer_address (forbidden).
> ```

OK, will fix next PR

**Pull request merged**
