### PR TITLE
More informative entry point errors

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/359)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/359)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/359#-NRUHKwO7R8qkv7I0KRf:-NRUHKwO7R8qkv7I0KRg:b-dpg3e8) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e8d68ed6e1c5f6ad7afda58fba56c2fc9da79c4/crates/blockifier/src/execution/entry_point.rs#L128)):*
> ```XML
>             return Err(PreExecutionError::DuplicateSelector {
>                 selector: self.entry_point_selector,
>                 n_matches: filtered_entry_points.len(),
> ```

I would just pass the EntryPointType but you are not allowed two errors with the same `from` type in thiserror I think

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/359)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/359#-NRUqqLb50liAooKRZxr:-NRUqqLb50liAooKRZxs:b-v0mjdy) (no related file):*
[PR](https://reviewable.io/reviews/starkware-libs/blockifier/360) for if and when LC add `Deserialize` to `ExecutionResources`

___
___
*[`crates/blockifier/src/execution/entry_point.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/359#-NRX-SwI9Y6Av0OZqIbi:-NRXnUhe8o9klC5wypAM:b-pgnscd) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e8d68ed6e1c5f6ad7afda58fba56c2fc9da79c4/crates/blockifier/src/execution/entry_point.rs#L119)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why does it have to be cloned at this point?
</blockquote></details>

because `EntryPointType` (defined in starknet-api) doesn't implement `Copy`
___
*[`crates/blockifier/src/execution/entry_point.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/359#-NRUHKwO7R8qkv7I0KRf:-NRXnaXP0s40BIl3elgC:b-2s21oq) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e8d68ed6e1c5f6ad7afda58fba56c2fc9da79c4/crates/blockifier/src/execution/entry_point.rs#L128)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Didn't follow...
I think passing the type here would be more informative; the user will know which subset of EPs to look into.
</blockquote></details>

This is not allowed:
```
#[derive(Error)]
enum Errors {
    #[error("Inner: {:?}")]
    Variant0(#[from] EntryPointType),
    #[error("Inner: {:?}")]
    Variant1(#[from] EntryPointType),
}
```
... don't understand why.
since we already have an error that is `#[from] EntryPointType` I'll add the selector as well

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/359)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/359#-NRX-SwI9Y6Av0OZqIbi:-NRY8f7m0qhMZddEDrbC:b-7m451a) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e8d68ed6e1c5f6ad7afda58fba56c2fc9da79c4/crates/blockifier/src/execution/entry_point.rs#L119)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because `EntryPointType` (defined in starknet-api) doesn't implement `Copy`
</blockquote></details>

Add it, it's small. :)
___
*[`crates/blockifier/src/execution/entry_point.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/359#-NRUHKwO7R8qkv7I0KRf:-NRqGY0UE2Q0Fw75tSfE:b73o00b) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e8d68ed6e1c5f6ad7afda58fba56c2fc9da79c4/crates/blockifier/src/execution/entry_point.rs#L128)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This is not allowed:
```
#[derive(Error)]
enum Errors {
    #[error("Inner: {:?}")]
    Variant0(#[from] EntryPointType),
    #[error("Inner: {:?}")]
    Variant1(#[from] EntryPointType),
}
```
... don't understand why.
since we already have an error that is `#[from] EntryPointType` I'll add the selector as well
</blockquote></details>

Confused... what are you trying to achieve?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/359)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/359#-NRX-SwI9Y6Av0OZqIbi:-NRqvnB80gke8TREDQMg:b-cxnuoc) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e8d68ed6e1c5f6ad7afda58fba56c2fc9da79c4/crates/blockifier/src/execution/entry_point.rs#L119)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add it, it's small. :)
</blockquote></details>

[PTAL](https://reviewable.io/reviews/starkware-libs/starknet-api/43)
will `cargo update` here after it's merged
___
*[`crates/blockifier/src/execution/entry_point.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/359#-NRUHKwO7R8qkv7I0KRf:-NRqw0H2EPJhn_d0RrXF:bx119lg) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e8d68ed6e1c5f6ad7afda58fba56c2fc9da79c4/crates/blockifier/src/execution/entry_point.rs#L128)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Confused... what are you trying to achieve?
</blockquote></details>

informative errors

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/359)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/359#-NRwpWvTBjxa3oTqA1o3:-NRwpWvTBjxa3oTqA1o4:bhz99z1) (no related file):*
Updating to the new starknet-api commit is painful (`state` subdir moved to `deprecated_`, declare txs have versions...).
I'm reverting to `clone`ing for now, [opened a new PR](https://reviewable.io/reviews/starkware-libs/starknet-api/44) which helps with one issue (put it on Yair, it isn't urgent IMO)

___

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/359#-:-NSpsPHnAeiBjWYzNOs-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Pull request merged**
