### PR TITLE
refactor(execution): add a function for calc_message_segment_length

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1584)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1584)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-NrUtFevDdX3YuM-D8g8):*
This commit should be tested with hodor before merged since it changes to the real execute function

**Review by Yael-Starkware — COMMENTED** [review]
small refactor to extract logic that will move to the bouncer

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-:-NrUtUz48X7QCc6GP0_5:boy92lm)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1584)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-Ns3sbW_4REpgsmKRKcH:-Ns3sbW_4REpgsmKRKcI:b-jlnogh) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc4cbaf1f4ac0cc4358ce684ade4f860c2232fa2/crates/blockifier/src/bouncer.rs#L190)):*
> ```XML
> }
> 
> pub fn calc_message_segment_length(
> ```

why not `calculate`?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1584)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/bouncer.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-Ns3sbW_4REpgsmKRKcH:-NsMojvo31NcU4t6V9NN:b-oua9qg) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc4cbaf1f4ac0cc4358ce684ade4f860c2232fa2/crates/blockifier/src/bouncer.rs#L190)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why not `calculate`?
</blockquote></details>

I think calc is clear enough

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1584)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-Ns3sbW_4REpgsmKRKcH:-Nsc6c737OVnaaparC2Q:b-ndp53j) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc4cbaf1f4ac0cc4358ce684ade4f860c2232fa2/crates/blockifier/src/bouncer.rs#L190)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think calc is clear enough
</blockquote></details>

Agreed but we use full words by convention, except several known ones (e.g., info, tx)
___
*[`crates/blockifier/src/bouncer.rs` line 145 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-Nsg9ueMCK--Ko1b7GOH:-Nsg9ueMCK--Ko1b7GOI:b-tcxk2t) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e35bfb9e488b472bb2500f7cfa91ae16a6520be/crates/blockifier/src/bouncer.rs#L145)):*
> ```XML
>     tx_execution_info: &TransactionExecutionInfo,
>     l1_handler_payload_size: Option<usize>,
> ) -> TransactionExecutorResult<(usize, GasVector)> {
> ```

Document the return type



_Code quote:_
```XML
<(usize, GasVector)>
```
___
*[`crates/blockifier/src/bouncer.rs` line 157 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-NsgA-Uv6rqP4-gvW0ma:-NsgA-Uv6rqP4-gvW0mb:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e35bfb9e488b472bb2500f7cfa91ae16a6520be/crates/blockifier/src/bouncer.rs#L157)):*
> ```XML
>     let starknet_gas_usage = get_messages_gas_usage(&message_cost_info, l1_handler_payload_size);
> 
>     Ok((message_cost_info.message_segment_length, starknet_gas_usage))
> ```





_Suggestion:_
```XML
    let message_cost_info = MessageL1CostInfo::calculate(call_infos, l1_handler_payload_size)?;
    let starknet_gas_usage = get_messages_gas_usage(&message_cost_info, l1_handler_payload_size);

    Ok((message_cost_info.message_segment_length, starknet_gas_usage))
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1584)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-Ns3sbW_4REpgsmKRKcH:-NshDJTS6v2bzwymMOdQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc4cbaf1f4ac0cc4358ce684ade4f860c2232fa2/crates/blockifier/src/bouncer.rs#L190)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Agreed but we use full words by convention, except several known ones (e.g., info, tx)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 145 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-Nsg9ueMCK--Ko1b7GOH:-NshE1K835bUHcWMMm_v:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e35bfb9e488b472bb2500f7cfa91ae16a6520be/crates/blockifier/src/bouncer.rs#L145)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Document the return type
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 157 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-NsgA-Uv6rqP4-gvW0ma:-NshEEmO-CLmlRaDZfk4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e35bfb9e488b472bb2500f7cfa91ae16a6520be/crates/blockifier/src/bouncer.rs#L157)):*
> ```XML
>     let starknet_gas_usage = get_messages_gas_usage(&message_cost_info, l1_handler_payload_size);
> 
>     Ok((message_cost_info.message_segment_length, starknet_gas_usage))
> ```

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-:-NsmebOo2jlpxZ7oqgUs:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 143 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1584#-NsmeVr_13jNeVGN6LBN:-NsmeVr_13jNeVGN6LBO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e7d70f036db616b6af9cee51e67cb81a52b060ed/crates/blockifier/src/bouncer.rs#L143)):*
> ```XML
> 
> /// Calculates the l1 resources used by l1 and l2 messages.
> /// Returns the total message segment length and the l1 gas usage.
> ```





_Suggestion:_
```XML
/// Calculates the L1 resources used by L1<>L2 messages.
/// Returns the total message segment length and the L1 gas usage.
```

**Pull request closed without merging**
