### PR TITLE
Start supporting Cairo1 execution

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a> 
    * **PR #449** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/449" target="_blank">Graphite</a> 
      * **PR #451** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/451" target="_blank">Graphite</a> 
        * **PR #450** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/450" target="_blank">Graphite</a> 
          * **PR #452** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/452" target="_blank">Graphite</a> 
            * **PR #458** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/458" target="_blank">Graphite</a> 
              * **PR #459** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/459" target="_blank">Graphite</a> 
                * **PR #460** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/460" target="_blank">Graphite</a> 
                  * **PR #461** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/461" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/461?utm_source=stack-comment).

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a> 
    * **PR #449** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/449" target="_blank">Graphite</a> 
      * **PR #451** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/451" target="_blank">Graphite</a> 
        * **PR #450** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/450" target="_blank">Graphite</a> 
          * **PR #452** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/452" target="_blank">Graphite</a> 
            * **PR #458** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/458" target="_blank">Graphite</a> 
              * **PR #459** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/459" target="_blank">Graphite</a> 
                * **PR #460** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/460" target="_blank">Graphite</a> 
                  * **PR #461** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/461" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/461?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV95EHN34ImZEstelMl:-NV95EHN34ImZEstelMm:bpq5p9u) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f797b09f7f15f9e7c200004314b4ee43420ed0c/crates/blockifier/src/execution/contract_class.rs#L135)):*
> ```XML
>             .map(|x| MaybeRelocatable::from(Felt252::from(x.value)))
>             .collect();
>         let hints: HashMap<_, _> = class
> ```

Why is this annotation needed? Can you change to an informative one?
Can you add a short comment on what's done here?



_Code quote:_
```XML
: HashMap<_, _>
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 500 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV95lJQ6A8gV1vEmomP:-NV95lJQ6A8gV1vEmomQ:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f797b09f7f15f9e7c200004314b4ee43420ed0c/crates/blockifier/src/execution/entry_point_test.rs#L500)):*
> ```XML
> 
>     let res = entry_point_call.execute_directly(&mut state);
>     println!("{:?}", res);
> ```

Remove?



_Code quote:_
```XML
println!("{:?}", res);
```
___
*[`crates/blockifier/src/execution/exec_v1.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV95r-l7PWXSmKFkkpX:-NV95r-l7PWXSmKFkkpY:b-rw9olg) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f797b09f7f15f9e7c200004314b4ee43420ed0c/crates/blockifier/src/execution/exec_v1.rs#L8)):*
> ```XML
> use cairo_vm::vm::vm_core::VirtualMachine;
> use starknet_api::core::EntryPointSelector;
> use starknet_api::hash::StarkHash;
> ```

Change `super -> crate`.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV96FP-3laG6sdjGZTM:-NV96FP-3laG6sdjGZTN:b-wz6nce) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f797b09f7f15f9e7c200004314b4ee43420ed0c/crates/blockifier/src/execution/syscalls/hint_processor.rs#L100)):*
> ```XML
> 
>     // Additional fields.
>     hints: &'a HashMap<String, Hint>,
> ```

Can you please explain this change?
Why do we need the raw hints now?
It's disturbing we're building them for every contract, in V0 they were global.



_Code quote:_
```XML
hints: &'a HashMap<String, Hint>,
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV96FP-3laG6sdjGZTM:-NV9ADKUEze4CKRsEuef:b-7f7w0i) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f797b09f7f15f9e7c200004314b4ee43420ed0c/crates/blockifier/src/execution/syscalls/hint_processor.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you please explain this change?
Why do we need the raw hints now?
It's disturbing we're building them for every contract, in V0 they were global.
</blockquote></details>

We are not building them. They are deserialized from the CasmContractClass.
Old hints were matched by string in the cairo-rs. In Cairo1, we don't look at the python code, we serialize them in the contract json.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV9G0R7DsEuEM--uyaT:-NV9G0R7DsEuEM--uyaU:b-ybknon) ([raw file](https://github.com/starkware-libs/blockifier/blob/0727628b17b3093bc491f23d3fec355428f23b79/crates/blockifier/src/execution/contract_class.rs#L56)):*
> ```XML
> #[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq)]
> pub struct ContractClassV0(pub Arc<ContractClassV0Inner>);
> impl Deref for ContractClassV0 {
> ```

Apparently [this is an anti-pattern](https://rust-unofficial.github.io/patterns/anti_patterns/deref.html).
Can you justify it?



_Code quote:_
```XML
impl Deref
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV9HOvv0Y50NPOV5UY8:-NV9HOvv0Y50NPOV5UY9:b3can6r) ([raw file](https://github.com/starkware-libs/blockifier/blob/0727628b17b3093bc491f23d3fec355428f23b79/crates/blockifier/src/execution/cairo1_execution.rs#L76)):*
> ```XML
> pub fn initialize_execution_context<'a>(
>     call: &CallEntryPoint,
>     contract_class: &'a ContractClassV1,
> ```

Why not consume the class? I believe this is what's done in the V0 flow.



_Code quote:_
```XML
contract_class: &'a ContractClassV1,
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV96FP-3laG6sdjGZTM:-NV9H_SHD857cIYJSzkN:b-2hhc60) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f797b09f7f15f9e7c200004314b4ee43420ed0c/crates/blockifier/src/execution/syscalls/hint_processor.rs#L100)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We are not building them. They are deserialized from the CasmContractClass.
Old hints were matched by string in the cairo-rs. In Cairo1, we don't look at the python code, we serialize them in the contract json.
</blockquote></details>

Are you planning to have the Cairo1 hint processor as a member soon?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV9HOvv0Y50NPOV5UY8:-NV9KrpQ-b_Mk8TXTzV-:bb593zh) ([raw file](https://github.com/starkware-libs/blockifier/blob/96251c7046a8039f55a6aee323c86a093a6bf798/crates/blockifier/src/execution/cairo1_execution.rs#L76)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not consume the class? I believe this is what's done in the V0 flow.
</blockquote></details>

It's because I need to keep the hints mapping, and I dont want to copy it since it might be big.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV9G0R7DsEuEM--uyaT:-NV9Kyel30FIB8rOUWsc:b-cfp20c) ([raw file](https://github.com/starkware-libs/blockifier/blob/96251c7046a8039f55a6aee323c86a093a6bf798/crates/blockifier/src/execution/contract_class.rs#L56)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Apparently [this is an anti-pattern](https://rust-unofficial.github.io/patterns/anti_patterns/deref.html).
Can you justify it?
</blockquote></details>

It's not an anti pattern. Some uses of it are. Specifically, in the link you sent, using it as "inheritence" is an anti pattern.
Another anti pattern involving this is using it instead of `Borrow`, as this also introduces the `*` syntax. However, I think it is appropriate in this case.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV96FP-3laG6sdjGZTM:-NV9LQjJC-2aVPhpHMrp:b-2obidj) ([raw file](https://github.com/starkware-libs/blockifier/blob/8f797b09f7f15f9e7c200004314b4ee43420ed0c/crates/blockifier/src/execution/syscalls/hint_processor.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are you planning to have the Cairo1 hint processor as a member soon?
</blockquote></details>

I'm not planning on having another hint processor. I want to use the execute_core_hint() function from cairo-lang repo

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV9SyoL804i1-IqKcH_:-NV9UXqa3ND9-m5rFJBb:b2nhswy) ([raw file](https://github.com/starkware-libs/blockifier/blob/96251c7046a8039f55a6aee323c86a093a6bf798/crates/blockifier/src/execution/cairo1_execution.rs#L142)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is embedded in the `[entry_point]` case, right?
</blockquote></details>

Yes

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/461#-NV9SoBO05czUS07qfSv:-NV9UZIJ0jEhs3fxlzfM:bjimtsw) ([raw file](https://github.com/starkware-libs/blockifier/blob/5b72c7ef632467508d2a7bf0fc808fa3d27137cc/crates/blockifier/src/execution/cairo1_execution.rs#L114)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Gorgeous! Can you also change the V0 code? :heart_eyes: 
</blockquote></details>

Maybe later :)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461#-:-NV9VsUV1eLlPzebve6L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461#-:-NV9bHv_9koNZRFtxH4r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/461#-:-NV9bv71DAWyDst1XIRm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
