### PR TITLE
feat(concurrency): use the bouncer in concurrent execution

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz7aKVjCWlQJoPL-X3l:-Nz7aKVjCWlQJoPL-X3m:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f30a53cf2b1aa13eb07c18c3bab287a6224772fa/crates/blockifier/src/concurrency/worker_logic.rs#L210)):*
> ```XML
> 
>         let tx_context = Arc::new(self.block_context.to_tx_context(tx));
>         if let Ok(tx_info) = result_tx_info.as_mut() {
> ```





_Suggestion:_
```XML
        let tx_result =
            &mut execution_output.as_mut().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).result;

        let tx_context = Arc::new(self.block_context.to_tx_context(tx));
        if let Ok(tx_execution_info) = tx_result.as_mut() {
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz7a96IE_GMz3zU5plt:-Nz7a96IE_GMz3zU5plu:b-elb2sg) ([raw file](https://github.com/starkware-libs/blockifier/blob/f30a53cf2b1aa13eb07c18c3bab287a6224772fa/crates/blockifier/src/concurrency/worker_logic.rs#L212)):*
> ```XML
>         if let Ok(tx_info) = result_tx_info.as_mut() {
>             // Ask the bouncer if there is room for the transaction in the block.
>             let bouncer_result = self.bouncer.lock().unwrap().try_update(
> ```

Add a short message



_Code quote:_
```XML
.unwrap()
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz7MRXg0jGZUkf7IPFM:-Nz7MRXg0jGZUkf7IPFN:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f30a53cf2b1aa13eb07c18c3bab287a6224772fa/crates/blockifier/src/concurrency/worker_logic.rs#L217)):*
> ```XML
>                 &tx_info.summarize(),
>                 &tx_info.actual_resources,
>             );
> ```





_Suggestion:_
```XML
        let mut execution_output = lock_mutex_in_array(&self.execution_outputs, tx_index);
        let result_tx_info =
            &mut execution_output.as_mut().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).result;

        let tx_context = Arc::new(self.block_context.to_tx_context(tx));
        if let Ok(tx_info) = result_tx_info.as_mut() {
            // Ask the bouncer if there is room for the transaction in the block.
            let writes = &execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).writes;
            let reads = &execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).reads;
            // Assumption: the reads contain the write keys.
            let tx_state_changes_keys = StateChanges::from(writes.diff(reads)).into_keys();

            let bouncer_result = self.bouncer.lock().unwrap().try_update(
                &tx_versioned_state,
                &tx_state_changes_keys,
                &tx_info.summarize(),
                &tx_info.actual_resources,
            );
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz7jY8m9Hgh6b17zlSZ:-Nz7jY8m9Hgh6b17zlS_:b-fsxdft) ([raw file](https://github.com/starkware-libs/blockifier/blob/f30a53cf2b1aa13eb07c18c3bab287a6224772fa/crates/blockifier/src/concurrency/worker_logic.rs#L225)):*
> ```XML
>                         // TransactionTooLarge error - revise the execution result and commit.
>                         *result_tx_info = Err(e);
>                         return Ok(true);
> ```

You need to delete the writes in this case (and other things) see `execute_tx` and `validate`



_Code quote:_
```XML
                    TransactionExecutorError::TransactionExecutionError(e) => {
                        // TransactionTooLarge error - revise the execution result and commit.
                        *result_tx_info = Err(e);
                        return Ok(true);
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz7MRXg0jGZUkf7IPFM:-Nz8_58c4p29JSneBR_7:bssvk7a) ([raw file](https://github.com/starkware-libs/blockifier/blob/f30a53cf2b1aa13eb07c18c3bab287a6224772fa/crates/blockifier/src/concurrency/worker_logic.rs#L217)):*
> ```XML
>                 &tx_info.summarize(),
>                 &tx_info.actual_resources,
>             );
> ```

I can't do that. `result_tx_info` takes a mutable reference to `execution_output`, so I can't take any other references to `execution_output` after creating `result_tx_info`.
```
error[E0502]: cannot borrow `execution_output` as immutable because it is also borrowed as mutable
   --> crates/blockifier/src/concurrency/worker_logic.rs:212:27
    |
207 |             &mut execution_output.as_mut().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).result;
    |                  ---------------- mutable borrow occurs here
...
212 |             let writes = &execution_output.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).writes;
    |                           ^^^^^^^^^^^^^^^^ immutable borrow occurs here
...
229 |                         *result_tx_info = Err(e);
    |                         --------------- mutable borrow later used here


```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gwMD6DAIlNk24Mls:-Nz8gwMD6DAIlNk24Mlt:b-fqknua) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L225)):*
> ```XML
>                         // TransactionTooLarge error - revise the execution result, delete writes
>                         // and commit.
>                         *tx_result = Err(e);
> ```

Do we need to do something with the validation/execution indexes in this case?

Anyway, please add a TODO to move the `TransactionTooLarge` inside `execute_raw`



_Code quote:_
```XML
                        // TransactionTooLarge error - revise the execution result, delete writes
                        // and commit.
                        *tx_result = Err(e);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gin043jHuSfs7kUH:-Nz8gin043jHuSfs7kUI:b4ekve4) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L233)):*
> ```XML
>                             .as_ref()
>                             .expect(EXECUTION_OUTPUTS_UNWRAP_ERROR)
>                             .contract_classes;
> ```

Empty these maps



_Code quote:_
```XML
                        let writes = &execution_output
                            .as_ref()
                            .expect(EXECUTION_OUTPUTS_UNWRAP_ERROR)
                            .writes;
                        let contract_classes = &execution_output
                            .as_ref()
                            .expect(EXECUTION_OUTPUTS_UNWRAP_ERROR)
                            .contract_classes;
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gin043jHuSfs7kUH:-Nz8i2w37eK_IOTi7yWG:b-lbut5x) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L233)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Empty these maps
</blockquote></details>

What do you mean?

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gwMD6DAIlNk24Mls:-Nz8i85dBAHkfz8AYBCo:b-4fxo35) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L225)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Do we need to do something with the validation/execution indexes in this case?

Anyway, please add a TODO to move the `TransactionTooLarge` inside `execute_raw`
</blockquote></details>

We don't. The scheduler doesn't care. As far as it can tell the transaction is already committed, so it will no longer assign any validation/execution tasks for it.

Added a TODO.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-:-Nz8mVGaCx6xiO06mvFR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gwMD6DAIlNk24Mls:-Nz8luf66qEBkRQG_65h:burjvyo) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L225)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

We don't. The scheduler doesn't care. As far as it can tell the transaction is already committed, so it will no longer assign any validation/execution tasks for it.

Added a TODO.
</blockquote></details>

But all other txs should be re-validated, since the state has changed, right?
Don't do that anyway, I want to get rid of this flow here 
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gin043jHuSfs7kUH:-Nz8mEylAlqiNDrj2wOS:b-tk1lo) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L233)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

`*writes = HashMap::default();`
For consistency with regular failure

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gwMD6DAIlNk24Mls:-Nz8tt9F1NrDYmaDtjVc:b86qczs) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L225)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

But all other txs should be re-validated, since the state has changed, right?
Don't do that anyway, I want to get rid of this flow here
</blockquote></details>

Yes this happens when we run the method `finish_execution_during_commit` (we don't do this after deleting the writes here... shouldn't we?)
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gin043jHuSfs7kUH:-Nz90vYk5-Ntuy-uppYs:blh7plx) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L233)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`*writes = HashMap::default();`
For consistency with regular failure
</blockquote></details>

`writes` and `contract_classes` are not mutable references.

Take a look at what I did. Does it make sense?

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 222 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzJAu-N5XMYGIs8z_XS:-NzJAu-N5XMYGIs8z_XT:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be1d6cbcf4e370bb38a5acfac0191c75edb7aba/crates/blockifier/src/concurrency/worker_logic.rs#L222)):*
> ```XML
>                     TransactionExecutorError::BlockFull => return Ok(false),
>                     TransactionExecutorError::StateError(e) => return Err(e),
>                     TransactionExecutorError::TransactionExecutionError(e) => {
> ```





_Suggestion:_
```XML
                      _ => panic!("Meaningful error message"),
                    TransactionExecutorError::TransactionExecutionError(
                        TransactionExecutionError::TransactionTooLarge,
                    ) => {
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 229 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzJ9VJREE_2X6_nc7S9:-NzJ9VJREE_2X6_nc7SA:bxtub52) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be1d6cbcf4e370bb38a5acfac0191c75edb7aba/crates/blockifier/src/concurrency/worker_logic.rs#L229)):*
> ```XML
>                             .as_ref()
>                             .expect(EXECUTION_OUTPUTS_UNWRAP_ERROR)
>                             .writes;
> ```

Is it needed?



_Code quote:_
```XML
                        let writes = &execution_output
                            .as_ref()
                            .expect(EXECUTION_OUTPUTS_UNWRAP_ERROR)
                            .writes;
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gwMD6DAIlNk24Mls:-NzNlPTs7b3rYPcf312K:bojuvss) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L225)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Yes this happens when we run the method `finish_execution_during_commit` (we don't do this after deleting the writes here... shouldn't we?)
</blockquote></details>

I added `finish_execution_during_commit` at the end of this match arm as we agreed offline.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gin043jHuSfs7kUH:-NzNl_k25JNbQME-h5BJ:b-7fy6fs) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L233)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

`writes` and `contract_classes` are not mutable references.

Take a look at what I did. Does it make sense?
</blockquote></details>

I changed it to keep the reads without change in the execution_output struct.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 222 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzJAu-N5XMYGIs8z_XS:-NzNlClW9eZC0qT_0PMY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be1d6cbcf4e370bb38a5acfac0191c75edb7aba/crates/blockifier/src/concurrency/worker_logic.rs#L222)):*
> ```XML
>                     TransactionExecutorError::BlockFull => return Ok(false),
>                     TransactionExecutorError::StateError(e) => return Err(e),
>                     TransactionExecutorError::TransactionExecutionError(e) => {
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 229 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzJ9VJREE_2X6_nc7S9:-NzNlE0zCZkfPjGi5LPw:bn9hk9n) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be1d6cbcf4e370bb38a5acfac0191c75edb7aba/crates/blockifier/src/concurrency/worker_logic.rs#L229)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

I need the writes to run the method `delete_writes`.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gin043jHuSfs7kUH:-NzNnWry30OkTrxYM3ho:b2kokp3) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L233)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I changed it to keep the reads without change in the execution_output struct.
</blockquote></details>

Instead of cloning the reads, use `take()`

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 233 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-Nz8gin043jHuSfs7kUH:-NzNrez204nYZu1rYTCH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/975b2e07eb2698587cc2eab0f5ed1c91546ddd14/crates/blockifier/src/concurrency/worker_logic.rs#L233)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Instead of cloning the reads, use `take()`
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 229 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzJ9VJREE_2X6_nc7S9:-NzOds1R9zJXoNEAzlGW:bhox445) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be1d6cbcf4e370bb38a5acfac0191c75edb7aba/crates/blockifier/src/concurrency/worker_logic.rs#L229)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I need the writes to run the method `delete_writes`.
</blockquote></details>

Don't you already defined this variable below the ` // Execution is final.` comment? :thinking:

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 229 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzJ9VJREE_2X6_nc7S9:-NzOmq297pWqZGTr3eC_:b-cmfn31) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be1d6cbcf4e370bb38a5acfac0191c75edb7aba/crates/blockifier/src/concurrency/worker_logic.rs#L229)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Don't you already defined this variable below the ` // Execution is final.` comment? :thinking:
</blockquote></details>

These immutable refs get dropped once we define a mutable ref, so they can no longer be used.
Anyway, I do it differently now. Take a look.

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by noaov1 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-:-NzTSXQEB702XTjadW7t:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 52 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzX4DKr4ygtkB51uMGO:-NzX4DKs54b78UXV5Usp:bp24gzg) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ab1eadb07eeadb3f4402763e62d971de67b617b/crates/blockifier/src/concurrency/worker_logic.rs#L52)):*
> ```XML
>     pub execution_outputs: Box<[Mutex<Option<ExecutionTaskOutput>>]>,
>     pub block_context: BlockContext,
>     pub bouncer: Arc<Mutex<&'a mut Bouncer>>,
> ```

Is the Arc needed?



_Code quote:_
```XML
pub bouncer: Arc<Mutex<&'a mut Bouncer>>,
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 52 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzX4DKr4ygtkB51uMGO:-NzXHtVq6DM-q3K4lMVF:b-6lndrj) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ab1eadb07eeadb3f4402763e62d971de67b617b/crates/blockifier/src/concurrency/worker_logic.rs#L52)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is the Arc needed?
</blockquote></details>

I removed the `Arc`.
I think it is not needed since we pass a reference to the bouncer anyway.

**Review by noaov1 — DISMISSED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 253 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzXPzAZ9-zxV3dtL6Fy:-NzXPzAZ9-zxV3dtL6Fz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/09a05f2590dbf4f099ac31b6ceb118e13758121b/crates/blockifier/src/concurrency/worker_logic.rs#L253)):*
> ```XML
>                     TransactionExecutorError::TransactionExecutionError(e) => {
>                         panic!("Unexpected TransactionExecutionError. {e:?}: {e}")
>                     }
> ```





_Suggestion:_
```XML
                    TransactionExecutorError::TransactionExecutionError(
                        TransactionExecutionError::TransactionTooLarge,
                    ) => {
                        // TransactionTooLarge error - revise the execution result, delete writes
                        // and commit.
                        // TODO(Avi, 20/6/2024): Move TransactionTooLarge inside execute_raw.
                        let old_execution_output =
                            execution_output.take().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR);
                        tx_versioned_state.delete_writes(
                            &old_execution_output.writes,
                            &old_execution_output.contract_classes,
                        );

                        *execution_output = Some(ExecutionTaskOutput {
                            reads: old_execution_output.reads,
                            writes: StateMaps::default(),
                            contract_classes: HashMap::default(),
                            visited_pcs: HashMap::default(),
                            result: Err(TransactionExecutionError::TransactionTooLarge),
                        });

                        // Signal to the scheduler that the execution output has been revised, so
                        // higher transactions should be re-validated.
                        self.scheduler.finish_execution_during_commit(tx_index);

                        return true;
                    }
                    _ => {
                        // TODO(Avi, 01/07/2024): Consider propagating the error.
                        panic!("Unexpected TransactionExecutionError. {error:?}: {erorr}")
                    }
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 253 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzXPzAZ9-zxV3dtL6Fy:-NzXRdoMEw6Xf7ev49cx:bb2x91l) ([raw file](https://github.com/starkware-libs/blockifier/blob/09a05f2590dbf4f099ac31b6ceb118e13758121b/crates/blockifier/src/concurrency/worker_logic.rs#L253)):*
> ```XML
>                     TransactionExecutorError::TransactionExecutionError(e) => {
>                         panic!("Unexpected TransactionExecutionError. {e:?}: {e}")
>                     }
> ```

If I do this, I won't have the `error` variable to use inside the panic, right?

Also, I thought the two cases are different. The state error could be due to valid reasons, while TransactionExecutionError should only be TransactionTooLarge, and if it is not then something unexpected happened.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 253 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1930#-NzXPzAZ9-zxV3dtL6Fy:-NzXTY8o3SEh1QH5cG4L:bwj5ayx) ([raw file](https://github.com/starkware-libs/blockifier/blob/09a05f2590dbf4f099ac31b6ceb118e13758121b/crates/blockifier/src/concurrency/worker_logic.rs#L253)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

If I do this, I won't have the `error` variable to use inside the panic, right?

Also, I thought the two cases are different. The state error could be due to valid reasons, while TransactionExecutionError should only be TransactionTooLarge, and if it is not then something unexpected happened.
</blockquote></details>

Never mind, I got it now.

Done.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1930)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
