### PR TITLE
Return executed compiled class hashes to Python.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/447)

### CODE REVIEW

**Review by giladchase — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/447)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/447#-NV-cn2M8UxGD2XMrfvA:-NV-cn2M8UxGD2XMrfvB:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/1eb118a832c3f6848439d00f1e82cd1740aae3cc/crates/native_blockifier/src/py_transaction.rs#L290)):*
> ```XML
>     }
> 
>     /// Executes the given transaction on the state maintained by the executer.
> ```





_Suggestion:_
```XML
executor
```
___
*[`crates/native_blockifier/src/py_utils.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/447#-NV-cBC01jyqYIHwKCmN:-NV-cBC01jyqYIHwKCmO:b-gh0kf2) ([raw file](https://github.com/starkware-libs/blockifier/blob/1eb118a832c3f6848439d00f1e82cd1740aae3cc/crates/native_blockifier/src/py_utils.rs#L27)):*
> ```XML
> impl From<ClassHash> for PyFelt {
>     fn from(class_hash: ClassHash) -> Self {
>         Self(class_hash.0)
> ```

Thank you :tears_of_joy:



_Code quote:_
```XML
impl From<ClassHash> for PyFelt {
    fn from(class_hash: ClassHash) -> Self {
        Self(class_hash.0)
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/447)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/447#-NVPNZoB01nsuYpIM-oZ:-NVPNZoB01nsuYpIM-o_:bcvcjcd) ([raw file](https://github.com/starkware-libs/blockifier/blob/0768c8ffaa5f5265124c9bdc291849ecca487bb0/crates/blockifier/src/transaction/objects.rs#L40)):*
> ```XML
> 
> impl TransactionExecutionInfo {
>     pub fn non_optional_call_infos(&self) -> Vec<&CallInfo> {
> ```

The second function below converts it into a HashSet, is it ok that here we allow duplicates?



_Code quote:_
```XML
Vec<&CallInfo>
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/447)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/447#-NVPNZoB01nsuYpIM-oZ:-NVXrE4v3HsQ6McJVet1:b-ab259m) ([raw file](https://github.com/starkware-libs/blockifier/blob/0768c8ffaa5f5265124c9bdc291849ecca487bb0/crates/blockifier/src/transaction/objects.rs#L40)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The second function below converts it into a HashSet, is it ok that here we allow duplicates?
</blockquote></details>

Of class hashes? We will always have duplicates: for example, `validate` and `execute` both operate on the account contract (same hash, and instance).

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/447)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/447#-NVPNZoB01nsuYpIM-oZ:-NVcEzUM7LRo9iNFr34x:b-hy7761) ([raw file](https://github.com/starkware-libs/blockifier/blob/0768c8ffaa5f5265124c9bdc291849ecca487bb0/crates/blockifier/src/transaction/objects.rs#L40)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Of class hashes? We will always have duplicates: for example, `validate` and `execute` both operate on the account contract (same hash, and instance).
</blockquote></details>

Ya i mean, shouldn't this be made a hashet as well? Currently its only use is in a function that converts it into a Hashset anyway

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/447)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/447#-NVPNZoB01nsuYpIM-oZ:-NVcrFhp7QY-jxGWUV5R:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0768c8ffaa5f5265124c9bdc291849ecca487bb0/crates/blockifier/src/transaction/objects.rs#L40)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ya i mean, shouldn't this be made a hashet as well? Currently its only use is in a function that converts it into a Hashset anyway
</blockquote></details>

Done.

**Pull request merged**
