### PR TITLE
Add SecpHintProcessor.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/864)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/864)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/864#-NdAXnQjEzGwW-zSP_1m:-NdAgIOL05wqelQo-SIf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/492789217105f8918be74a063f0e2391db573751/crates/blockifier/src/execution/syscalls/secp.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move down? We put `pub`lic API first.
</blockquote></details>

Done.

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/864#-:-NdAgW7AAoCUjCrqqjX5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/864)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/864#-NdAhlig6ieX91WLDSid:-NdAhlih-zers93IxipS:bcv5v0) ([raw file](https://github.com/starkware-libs/blockifier/blob/28b30e3d5bfaf526b057353d651d76dfd9c7dd87/crates/blockifier/src/execution/syscalls/secp.rs#L28)):*
> ```XML
> }
> 
> impl<Curve: SWCurveConfig> SecpHintProcessor<Curve>
> ```

I discovered that 
SWCurveConfig : CurveConfig
:)

Should I call the generic arg Curve or CurveConfig?



_Code quote:_
```XML
Curve: SWCurveConfig
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/864)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/864#-NdAhlig6ieX91WLDSid:-NdAiQGo93Vop2UdN-g5:bk6gzql) ([raw file](https://github.com/starkware-libs/blockifier/blob/28b30e3d5bfaf526b057353d651d76dfd9c7dd87/crates/blockifier/src/execution/syscalls/secp.rs#L28)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I discovered that 
SWCurveConfig : CurveConfig
:)

Should I call the generic arg Curve or CurveConfig?
</blockquote></details>

I like `Curve` better. :)

**Pull request merged**
