### PR TITLE
Create StateChangesCount struct and use it

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/762)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/762)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul and @zuphitf)

___
*[`crates/blockifier/src/state/cached_state.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/762#-N_n0eoD7LkixQRJkmaY:-N_n0eoD7LkixQRJkmaZ:b-kbcxo6) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce72c7edd6c7de5940929a7276a5b4e17864507b/crates/blockifier/src/state/cached_state.rs#L91)):*
> ```XML
>             class_hash_updates: class_hash_updates.clone(),
>             compiled_class_hash_updates: compiled_class_hash_updates.clone(),
>         })
> ```

Clone is necessary for the use case IMO; unless the `count_actual_state_changes_for_fee_charge` function can take ownership of these dicts.
This struct will be consumed to combine StateChanges



_Code quote:_
```XML
        Ok(StateChanges {
            storage_updates: storage_updates.clone(),
            modified_contracts,
            class_hash_updates: class_hash_updates.clone(),
            compiled_class_hash_updates: compiled_class_hash_updates.clone(),
        })
```

**Review by zuphitf — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/762)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/state/cached_state.rs` line 570 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/762#-N_njAww2SXxu_6CdoI9:-N_njAww2SXxu_6CdoIA:bzha95n) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce72c7edd6c7de5940929a7276a5b4e17864507b/crates/blockifier/src/state/cached_state.rs#L570)):*
> ```XML
> 
> impl From<StateChanges> for StateChangesCount {
>     fn from(value: StateChanges) -> Self {
> ```

consider a better var name. `changes`, `state_changes` etc.



_Code quote:_
```XML
value: StateChanges
```

**Review by zuphitf — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/762)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/state/cached_state.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/762#-N_n0eoD7LkixQRJkmaY:-Na0tX-60rk2odI7FRTq:b2vs1ri) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce72c7edd6c7de5940929a7276a5b4e17864507b/crates/blockifier/src/state/cached_state.rs#L91)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Clone is necessary for the use case IMO; unless the `count_actual_state_changes_for_fee_charge` function can take ownership of these dicts.
This struct will be consumed to combine StateChanges
</blockquote></details>

Is it possible to do some of the clones earlier (i.e.  `let storage_updates = &mut self.cache.get_storage_updates().clone();`) and then maybe `self` wouldn't have to be mutable, since all the changes that this function performs to do the counting will be on the cloned objects?

**Review by zuphitf — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/762)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/state/cached_state.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/762#-N_n0eoD7LkixQRJkmaY:-Na0v7WQDiA2QfSNLv2d:b-zbl06d) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce72c7edd6c7de5940929a7276a5b4e17864507b/crates/blockifier/src/state/cached_state.rs#L91)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Is it possible to do some of the clones earlier (i.e.  `let storage_updates = &mut self.cache.get_storage_updates().clone();`) and then maybe `self` wouldn't have to be mutable, since all the changes that this function performs to do the counting will be on the cloned objects?
</blockquote></details>

hmm actually it wouldn't help making `self` non-mutable because of the `self.update_initial_values_of_write_only_access()?;` call.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/762)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/blockifier/src/state/cached_state.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/762#-N_n0eoD7LkixQRJkmaY:-Na1AMQH2k5dkUAgqM4P:b-62ahks) ([raw file](https://github.com/starkware-libs/blockifier/blob/ce72c7edd6c7de5940929a7276a5b4e17864507b/crates/blockifier/src/state/cached_state.rs#L91)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

hmm actually it wouldn't help making `self` non-mutable because of the `self.update_initial_values_of_write_only_access()?;` call.
</blockquote></details>

Since this is an implementation of a cached state, even read operations require a mutable instance

**Pull request merged**
