### PR TITLE
add enforce_file_exists to check on mdbx.dat file

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1204)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1204)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1204#-Nkigw9I86jTagVSr0Qa:-Nkigw9I86jTagVSr0Qb:bo4eydd) (no related file):*
Link to python-side PR?

___
___
*[`Cargo.toml` line 64 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1204#-Nkighp6Ci_TgcePBoH9:-Nkighp6Ci_TgcePBoHA:b-s4fe2c) ([raw file](https://github.com/starkware-libs/blockifier/blob/824289a54e422da070c629920d353a3ec3990af3/Cargo.toml#L64)):*
> ```TOML
> # Temporarily here until a tag is published.
> [patch.crates-io]
> papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", rev = "94c6dfeb" }
> ```

why patch instead of explicit dependency on revision above?
we cannot release a version like this anyway



_Code quote:_
```TOML
# Temporarily here until a tag is published.
[patch.crates-io]
papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", rev = "94c6dfeb" }
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1204)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @zuphitf)

___
*[`Cargo.toml` line 64 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1204#-Nkighp6Ci_TgcePBoH9:-NkpLJWj565emVmz1mD0:bn33g9a) ([raw file](https://github.com/starkware-libs/blockifier/blob/824289a54e422da070c629920d353a3ec3990af3/Cargo.toml#L64)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

FYI Dan said that they're gonna publish soon so maybe we should just wait a bit until it's up?
</blockquote></details>

Should be [0.2.0-rc4](https://crates.io/crates/papyrus_storage/0.2.0-rc4)

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1204)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1204#-Nkigw9I86jTagVSr0Qa:-NkpNSFI3IyKJUelFks_:b-adubzq) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Link to python-side PR?
</blockquote></details>

Added you to it

___
___
*[`Cargo.toml` line 64 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1204#-Nkighp6Ci_TgcePBoH9:-NkpNJwZ5AACG1kSdMnz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/824289a54e422da070c629920d353a3ec3990af3/Cargo.toml#L64)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Should be [0.2.0-rc4](https://crates.io/crates/papyrus_storage/0.2.0-rc4)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1204#-:-NkpQQMEEOHhlSHRrkbX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
