### PR TITLE
add signature operation to invoke_tx tests

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1266)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1266)* status: all files reviewed, 7 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 453 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrFI_DA-_kp2KNlLVH:-NlrFI_DA-_kp2KNlLVI:b-c9m791) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L453)):*
> ```XML
> 
> // Verifies the storage after each invoke execution in test_invoke_tx_advanced_operations.
> fn verify_storage_after_invoke(
> ```

please rename, it's too general and checks very specific things



_Suggestion:_
```XML
verify_storage_after_invoke_advance_operation
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 506 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrEilJD0vdhujo9weB:-NlrEilJD0vdhujo9weC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L506)):*
> ```XML
>         calldata:
>             create_calldata(contract_address, "advance_counter", &calldata_args),
>     });
> ```





_Suggestion:_
```XML
    let calldata_args = vec![index, initial_counters[0], initial_counters[1]];
    let base_tx_args = invoke_tx_args! {
        max_fee: Fee(MAX_FEE),
        sender_address: account_address,
    };

    let account_tx = account_invoke_tx(invoke_tx_args! {
        nonce: nonce_manager.next(account_address),
        calldata:
            create_calldata(contract_address, "advance_counter", &calldata_args),
        ..base_tx_args.clone()
    });
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 536 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrEsCa9mLV1ImNBQeY:-NlrEsCa9mLV1ImNBQeZ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L536)):*
> ```XML
>         calldata:
>             create_calldata(contract_address, "call_xor_counters", &calldata_args),
>     });
> ```





_Suggestion:_
```XML
    let account_tx = account_invoke_tx(invoke_tx_args! {
        nonce: next_nonce,
        calldata:
            create_calldata(contract_address, "call_xor_counters", &calldata_args),
        ..base_tx_args.clone()
    });
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 561 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrEvP4-fc9dFm3fqNG:-NlrEvP4-fc9dFm3fqNH:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L561)):*
> ```XML
>         calldata:
>             create_calldata(contract_address, "test_ec_op", &[]),
>     });
> ```





_Suggestion:_
```XML
    let account_tx = account_invoke_tx(invoke_tx_args! {
        nonce: next_nonce,
        calldata:
            create_calldata(contract_address, "test_ec_op", &[]),
        ..base_tx_args.clone()
    });
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 594 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrFbgf4ewuZcwCCGkV:-NlrFbgf4ewuZcwCCGkW:b7pgujp) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L594)):*
> ```XML
>         stark_felt!(signature_values[0]),
>         stark_felt!(signature_values[1]),
>     ]);
> ```

I suggest you work with Felt252, to get arithmetic (see below).
Non-blocking (not sure it works)



_Suggestion:_
```XML
    let signature_values = [Felt252::from(200_u64), Felt252::from(300_u64)];
    let signature =
        TransactionSignature(signature_values.iter().map(felt_to_stark_felt).collect());
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 603 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrEydeBPiyD3sioERS:-NlrEydeBPiyD3sioERT:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L603)):*
> ```XML
>             calldata:
>                 create_calldata(contract_address, "add_signature_to_counters", &[index]),
>     });
> ```





_Suggestion:_
```XML
            signature,
            nonce: next_nonce,
            calldata:
                create_calldata(contract_address, "add_signature_to_counters", &[index]),
            ..base_tx_args
    });
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 609 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrG-5t1uxl2agnFxWM:-NlrG-5t1uxl2agnFxWN:bjln265) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L609)):*
> ```XML
>         stark_felt!(u64::try_from(expected_counters[0]).unwrap() + signature_values[0]),
>         stark_felt!(u64::try_from(expected_counters[1]).unwrap() + signature_values[1]),
>     ];
> ```

If the comment above about Felt252 works, try this:



_Suggestion:_
```XML
    let expected_counters = [
        felt_to_stark_felt(stark_felt_to_felt(expected_counters[0]) + signature_values[0]),
        felt_to_stark_felt(stark_felt_to_felt(expected_counters[1]) + signature_values[1]),
    ];
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1266)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 453 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrFI_DA-_kp2KNlLVH:-NlrIKEq9dafs60IoIDl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L453)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please rename, it's too general and checks very specific things
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 506 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrEilJD0vdhujo9weB:-NlrIBN2DhpATUKNZfnq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L506)):*
> ```XML
>         calldata:
>             create_calldata(contract_address, "advance_counter", &calldata_args),
>     });
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 536 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrEsCa9mLV1ImNBQeY:-NlrICfQ6Kp7QhSuJdRp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L536)):*
> ```XML
>         calldata:
>             create_calldata(contract_address, "call_xor_counters", &calldata_args),
>     });
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 561 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrEvP4-fc9dFm3fqNG:-NlrID3gDnGvY9VzO657:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L561)):*
> ```XML
>         calldata:
>             create_calldata(contract_address, "test_ec_op", &[]),
>     });
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 594 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrFbgf4ewuZcwCCGkV:-NlrMnLADysmE8h_HbEk:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L594)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I suggest you work with Felt252, to get arithmetic (see below).
Non-blocking (not sure it works)
</blockquote></details>

done
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 603 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrEydeBPiyD3sioERS:-NlrIDvqB30tZIJfdkWq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L603)):*
> ```XML
>             calldata:
>                 create_calldata(contract_address, "add_signature_to_counters", &[index]),
>     });
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 609 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrG-5t1uxl2agnFxWM:-NlrMmd8C3xoMsOTyGiy:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L609)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

If the comment above about Felt252 works, try this:
</blockquote></details>

done

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 603 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-NlrEydeBPiyD3sioERS:-NlrNsDJ3QPMh3_utSJJ:b-wz24dh) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d5530e07f02acaeb193dd34b0dca78daab6b012/crates/blockifier/src/transaction/transactions_test.rs#L603)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

don't think you need this `clone()` here, wonder why `clippy` likes it...? non-blocking

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1266#-:-NlrO2WJ9aGhIfiBVHWH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
