### PR TITLE
Execution context refactor

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/457)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #457** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/457" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/457?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/457)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/block_context.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8Ys429Bcd0UGqu6z3:-NV8Ys429Bcd0UGqu6z4:b-j1g5tu) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/block_context.rs#L6)):*
> ```XML
> use starknet_api::core::{ChainId, ContractAddress};
> 
> #[derive(Debug, Clone)]
> ```

Please alphabetize.



_Code quote:_
```XML
Debug, Clone
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8a3lfEal9yE3H0aFn:-NV8a3lfEal9yE3H0aFo:bm4el56) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/execution/entry_point.rs#L58)):*
> ```XML
> 
> #[derive(Debug, Clone)]
> pub struct ExecutionContext {
> ```

Perhaps `block_context` and `account_tx_context` should be held as refs., so no clones are needed?



_Code quote:_
```XML
ExecutionContext
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8Z-h96dw0u3q23PB9:-NV8Z-h96dw0u3q23PBA:bkc1yd6) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/execution/entry_point.rs#L67)):*
> ```XML
>     pub block_context: BlockContext,
>     pub execution_resources: ExecutionResources,
>     pub account_tx_context: AccountTransactionContext,
> ```

Please move to be first, those are more important fields in this struct.
Also `execution_resources` can simply be `resources`.



_Suggestion:_
```XML
    pub block_context: BlockContext,
    pub resources: ExecutionResources,
    pub account_tx_context: AccountTransactionContext,
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8ZNjW07BbfO-KkSVZ:-NV8ZNjW07BbfO-KkSV_:b-pthxqh) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/execution/entry_point.rs#L102)):*
> ```XML
>         mut self,
>         state: &mut dyn State,
>         ctx: &mut ExecutionContext,
> ```

In all locations, please. Same for variable name.



_Suggestion:_
```XML
context: &mut ExecutionContext,
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8ZjBE-ymBAhVAIfN7:-NV8ZjBE-ymBAhVAIfN8:bblti3q) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L109)):*
> ```XML
> 
> impl<'a> DeprecatedSyscallHintProcessor<'a> {
>     #[allow(clippy::too_many_arguments)]
> ```

Can all those be deleted now?



_Code quote:_
```XML
#[allow(clippy::too_many_arguments)]
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8ZqC_3XC0qj5XW3uG:-NV8ZqC_3XC0qj5XW3uH:bd7olbs) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L278)):*
> ```XML
>     ) -> DeprecatedSyscallResult<Relocatable> {
>         let tx_signature_start_ptr = self.get_or_allocate_tx_signature_segment(vm)?;
>         let tx_signature_length = self.ctx.account_tx_context.signature.0.len();
> ```

Consider defining a variable (also in the new hint processor).



_Suggestion:_
```XML
let account_data = self.ctx.account_tx_context
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8_87s38DrH1N8dU02:-NV8_87s38DrH1N8dU03:bkaef1c) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/state/cached_state.rs#L348)):*
> ```XML
> /// Wraps a mutable reference to a `State` object, exposing its API.
> /// Used to pass ownership to a `CachedState`.
> pub struct MutRefState<'a, S: State + ?Sized>(&'a mut S);
> ```

Can you please explain what it means, and why is it now needed?



_Code quote:_
```XML
?Sized
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8_ZJZ3bZPulyqGzeK:-NV8_ZJZ3bZPulyqGzeL:b-ekcsim) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/transaction/account_transaction.rs#L181)):*
> ```XML
>     }
> 
>     fn charge_fee(
> ```

Why not make this method receive the whole context object, like the others?



_Code quote:_
```XML
charge_fee
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/457)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8a3lfEal9yE3H0aFn:-NV8bGdu-KvFP6K2oOHZ:b-r1zd8l) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/execution/entry_point.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps `block_context` and `account_tx_context` should be held as refs., so no clones are needed?
</blockquote></details>

That's definitely an option, but I think it's insignificant. They are small, and having refs would prevent Clone and require lifetime. I think it can be a followup work.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8ZNjW07BbfO-KkSVZ:-NV8c-DB7RssoFbqrQ08:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/execution/entry_point.rs#L102)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

In all locations, please. Same for variable name.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8_87s38DrH1N8dU02:-NV8cjNS6sjqOFLJPIZY:b-fly45y) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/state/cached_state.rs#L348)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you please explain what it means, and why is it now needed?
</blockquote></details>

It is not needed now, but it's correct in general. It lets you use MutRefState<dyn State> (which I thought I needed, but I didn't).
By default, every generic type param has a hidden `:Sized`, which means rust knows the size at compile time. Doing `?Sized` is turning it off, not requiring it.
Since we only have a pointer to S here, we don't need to know its size.
`dyn Trait` doesnt have a known size at compile time
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8_ZJZ3bZPulyqGzeK:-NV8duF6DWeQXyeuubsf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/transaction/account_transaction.rs#L181)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not make this method receive the whole context object, like the others?
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/457)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 276 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8fD_811vtlVtmUWIe:-NV8fD_811vtlVtmUWIf:bph684w) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ffe899c7fc6b8ef4efb1e5c658672a3ad0564cc/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L276)):*
> ```XML
>     ) -> DeprecatedSyscallResult<Relocatable> {
>         let tx_signature_start_ptr = self.get_or_allocate_tx_signature_segment(vm)?;
>         let account_transaction_context = &self.context.account_tx_context;
> ```

I don't use the full word, only in camelcase. x2



_Suggestion:_
```XML
account_tx_context
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/457#-NV8_87s38DrH1N8dU02:-NV8fZ6c3ECCfvd9Jned:b-ucfknh) ([raw file](https://github.com/starkware-libs/blockifier/blob/667189f80a209712b1ac98c38b85524132316cce/crates/blockifier/src/state/cached_state.rs#L348)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It is not needed now, but it's correct in general. It lets you use MutRefState<dyn State> (which I thought I needed, but I didn't).
By default, every generic type param has a hidden `:Sized`, which means rust knows the size at compile time. Doing `?Sized` is turning it off, not requiring it.
Since we only have a pointer to S here, we don't need to know its size.
`dyn Trait` doesnt have a known size at compile time
</blockquote></details>

Thanks!

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/457#-:-NV8lBTl8kIcn3NU5KVl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
