### PR TITLE
feat: added private versioned constants

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1992)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-:-O-kkArq1uzZTaA-2tlO:b-hz3kb8)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1992)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pcSxIB-nSZGZ8qPcP:-O-pcSxIB-nSZGZ8qPcQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/blockifier/src/versioned_constants.rs#L207)):*
> ```XML
> 
>     /// Private versioned constants are used if they are provided, otherwise the latest versioned
>     /// constants are used. `validate_max_n_steps` & `max_recursion_depth` override both.
> ```





_Suggestion:_
```XML
    /// Private versioned constants are used if they are provided, otherwise the latest versioned
    /// constants are used. `validate_max_n_steps` & `max_recursion_depth` override both.
    // TODO(Amos, 1/8/2024): remove the explicit max_n_steps, they should be part of the general override.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pce4a1EE2XOEpOjjr:-O-pce4a1EE2XOEpOjjs:b-8tjgdf) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/blockifier/src/versioned_constants.rs#L209)):*
> ```XML
>     /// constants are used. `validate_max_n_steps` & `max_recursion_depth` override both.
>     pub fn get_versioned_constants(
>         private_versioned_constants: Option<String>,
> ```

please move all deserialization logic  to the native blockifier side (you can add a utility function for this)



_Suggestion:_
```XML
versioned_constants_override: Option<VersionedConstants>,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pcsrk5ZiG9D2rQY0Q:-O-pcsrk5ZiG9D2rQY0R:b-y774fd) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/blockifier/src/versioned_constants.rs#L231)):*
> ```XML
>                 }
>             }
>         }
> ```

reduce some duplication



_Suggestion:_
```XML
        let base_versioned_constants = match private_versioned_constants {
            Some(private_versioned_constants) => {
                log::debug!(
                    "Using provided private versioned constants (with additional overrides)."
                );
                serde_json::from_str(&private_versioned_constants)
                    .expect("Versioned constants JSON file is malformed.")
            }
            None => {
                log::debug!("Using latest versioned constants (with additional overrides).");
                Self::latest_constants().clone()
            };
            Self {
                validate_max_n_steps,
                max_recursion_depth,
                ..base_versioned_constants
            }
        }
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pbZ-I6mMqku-sNfg8:-O-pbZ-I6mMqku-sNfg9:brzimnw) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/native_blockifier/src/py_block_executor.rs#L115)):*
> ```XML
>             validate_max_n_steps,
>             max_recursion_depth,
>         );
> ```

1. Define a `VersionedConstantsOverrides` (without the `Py`) struct
2. implement `From<PyVersionedConstantsOverrides> for VersionedConstantsOverrides`
3. use it instead of the three params in `get_versioned_constants`



_Suggestion:_
```XML
        let versioned_constants = VersionedConstants::get_versioned_constants(
            versioned_constants_overrides.into
        );
```
___
*[`crates/native_blockifier/src/py_objects.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pcDjk1DdtXyIhOZop:-O-pcDjk1DdtXyIhOZoq:b-2y8xr5) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/native_blockifier/src/py_objects.rs#L65)):*
> ```XML
>             Err(PyValueError::new_err("Failed to parse private_versioned_constants."))
>         }
>     }
> ```

is this ever used in business logic...? I don't see any usage here



_Code quote:_
```XML
    #[staticmethod]
    pub fn validate_private_versioned_constants_str(
        private_versioned_constants: &str,
    ) -> PyResult<()> {
        if serde_json::from_str::<VersionedConstants>(private_versioned_constants).is_ok() {
            Ok(())
        } else {
            Err(PyValueError::new_err("Failed to parse private_versioned_constants."))
        }
    }
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pc7WuBLnoCwg3OrBk:-O-pc7WuBLnoCwg3OrBl:byr4ffv) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/native_blockifier/src/py_validator.rs#L48)):*
> ```XML
>             validate_max_n_steps,
>             max_recursion_depth,
>         );
> ```

see above



_Code quote:_
```XML
        let PyVersionedConstantsOverrides {
            validate_max_n_steps,
            max_recursion_depth,
            private_versioned_constants,
        } = versioned_constants_overrides;
        let versioned_constants = VersionedConstants::get_versioned_constants(
            private_versioned_constants,
            validate_max_n_steps,
            max_recursion_depth,
        );
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1992)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pcSxIB-nSZGZ8qPcP:-O-u_QAB7dg2bNrF8nNQ:bom4l0p) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/blockifier/src/versioned_constants.rs#L207)):*
> ```XML
> 
>     /// Private versioned constants are used if they are provided, otherwise the latest versioned
>     /// constants are used. `validate_max_n_steps` & `max_recursion_depth` override both.
> ```

how would you implement this?
i.e., how would an override of only `validate_max_n_steps` look like?
___
*[`crates/blockifier/src/versioned_constants.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pce4a1EE2XOEpOjjr:-O-ur3iO-4tr2fHHaBiJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/blockifier/src/versioned_constants.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please move all deserialization logic  to the native blockifier side (you can add a utility function for this)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pcsrk5ZiG9D2rQY0Q:-O-utoFi0e5n_vAVfpvb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/blockifier/src/versioned_constants.rs#L231)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reduce some duplication
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pbZ-I6mMqku-sNfg8:-O-utr2DCVzL5tXdQexm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/native_blockifier/src/py_block_executor.rs#L115)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. Define a `VersionedConstantsOverrides` (without the `Py`) struct
2. implement `From<PyVersionedConstantsOverrides> for VersionedConstantsOverrides`
3. use it instead of the three params in `get_versioned_constants`
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_objects.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pcDjk1DdtXyIhOZop:-O-utt5k0wD8efYmK5ba:bfyq2at) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/native_blockifier/src/py_objects.rs#L65)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this ever used in business logic...? I don't see any usage here
</blockquote></details>

This is used in the Python test `private_versioned_constants_test.py`
___
*[`crates/native_blockifier/src/py_validator.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pc7WuBLnoCwg3OrBk:-O-uu-T88rlsmVJ4WQOt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/native_blockifier/src/py_validator.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1992)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pcSxIB-nSZGZ8qPcP:-O-zc0k04w-nt4GMfgwT:byggve9) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/blockifier/src/versioned_constants.rs#L207)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

how would you implement this?
i.e., how would an override of only `validate_max_n_steps` look like?
</blockquote></details>

good question.
I can think of a solution using a macro; macro should accept the fields defining the versioned constants, and automatically defines VersionedConstants and VersionedConstantsOverrides: the latter equal to the former except every field is wrapped with Option<>.
the macro can also generate an `apply_overrides(&mut self, overrides: &VersionedConstantsOverrides)` method on VersionedConstants to update every non-None field.
needs thought, out of scope of this PR though; a TODO is enough
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-zcq1K3t3EbqltS_4V:-O-zcq1K3t3EbqltS_4W:b-jax5ks) ([raw file](https://github.com/starkware-libs/blockifier/blob/984beba372be8675fcaabed5660206d41696cd77/crates/native_blockifier/src/py_block_executor.rs#L109)):*
> ```XML
>             VersionedConstantsOverrides::from(py_versioned_constants_overrides);
>         let versioned_constants =
>             VersionedConstants::get_versioned_constants(versioned_constants_overrides);
> ```

more concice



_Suggestion:_
```XML
        let versioned_constants =
            VersionedConstants::get_versioned_constants(
                py_versioned_constants_overrides.into()
            );
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-zdBFK4fKCpx7EvYcH:-O-zdBFK4fKCpx7EvYcI:byr4ffv) ([raw file](https://github.com/starkware-libs/blockifier/blob/984beba372be8675fcaabed5660206d41696cd77/crates/native_blockifier/src/py_validator.rs#L42)):*
> ```XML
>             VersionedConstantsOverrides::from(py_versioned_constants_overrides);
>         let versioned_constants =
>             VersionedConstants::get_versioned_constants(versioned_constants_overrides);
> ```

see above



_Suggestion:_
```XML
        let versioned_constants =
            VersionedConstants::get_versioned_constants(
                py_versioned_constants_overrides.into()
            );
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1992)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-pcSxIB-nSZGZ8qPcP:-O02vq13EO4ejYj4yYZ4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc2bf7581d75b81c7042cfb0cd8ff986dad4340c/crates/blockifier/src/versioned_constants.rs#L207)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

good question.
I can think of a solution using a macro; macro should accept the fields defining the versioned constants, and automatically defines VersionedConstants and VersionedConstantsOverrides: the latter equal to the former except every field is wrapped with Option<>.
the macro can also generate an `apply_overrides(&mut self, overrides: &VersionedConstantsOverrides)` method on VersionedConstants to update every non-None field.
needs thought, out of scope of this PR though; a TODO is enough
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-zcq1K3t3EbqltS_4V:-O02wJ7t5Vq5jW884YXj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/984beba372be8675fcaabed5660206d41696cd77/crates/native_blockifier/src/py_block_executor.rs#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

more concice
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-O-zdBFK4fKCpx7EvYcH:-O02wKVk8UHu8UhSW1Wz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/984beba372be8675fcaabed5660206d41696cd77/crates/native_blockifier/src/py_validator.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@Yoni-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-:-O02zkz25CvQ2zqrpAKm:b-gza3mz)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1992#-:-O03GrV_4kJjGayE6deU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
