### PR TITLE
Add PyGeneralConfig to avoid using `get_attr`.

### PR DESCRIPTION
**Pull request by NirLevi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/569)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/569)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @NirLevi-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/569#-NXC-Cr14AGZtiSczqjf:-NXC-Cr22b8VNu_-hE5w:b-ijydlr) ([raw file](https://github.com/starkware-libs/blockifier/blob/10e27d47bd057e08b03d550099e022fa7becf0fc/crates/native_blockifier/src/py_transaction.rs#L123)):*
> ```XML
>     cairo_resource_fee_weights: &HashMap<String, f64>,
> ) -> Result<HashMap<String, f64>, NativeBlockifierError> {
>     // let cairo_resource_fee_weights = &general_config.cairo_resource_fee_weights;
> ```

Delete plz :)



_Code quote:_
```XML
    // let cairo_resource_fee_weights = &general_config.cairo_resource_fee_weights;
```

**Review by NirLevi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/569)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/569#-NXC-Cr14AGZtiSczqjf:-NXExOkJBSB2Vd6ylg_5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/10e27d47bd057e08b03d550099e022fa7becf0fc/crates/native_blockifier/src/py_transaction.rs#L123)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Delete plz :)
</blockquote></details>

Done.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/569#-:-NXjaUY3AiPJa9ziZ5ty:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
