### PR TITLE
Make `Storage` trait, for testability

### PR DESCRIPTION
**Pull request by giladchase**
This will soon be used to create a `StorageMock`, which we'll need in
order to test native_blockifier.

commit-id:10e79abc

---

**Stack**:
- #1155
- #1153 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1153)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

**Review by dorimedini-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1153)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1153)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`Cargo.toml` line 39 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1153#-NjgOYNc2Kv-IG4j1FU0:-NjgOYNc2Kv-IG4j1FU1:b-iiukuf) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca8091cecb6f9cc7f7b1743d094cb3a1eafa6ec4/Cargo.toml#L39)):*
> ```TOML
> num-traits = "0.2"
> rstest = "0.17.0"
> papyrus_storage = "0.2.0-rc2"
> ```

ooooohhhh do we really want a root level dependency on papyrus...? won't this make publishing harder?



_Code quote:_
```TOML
papyrus_storage = "0.2.0-rc2"
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1153)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`Cargo.toml` line 39 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1153#-NjgOYNc2Kv-IG4j1FU0:-NjgOn3q-OI9IePlHIgM:b7pjayj) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca8091cecb6f9cc7f7b1743d094cb3a1eafa6ec4/Cargo.toml#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ooooohhhh do we really want a root level dependency on papyrus...? won't this make publishing harder?
</blockquote></details>

Nope what matters is the crate-level toml (we hit this fact directly in one of the publications last week).

If `blockifier/Cargo.toml` doesn't include `papyrus_storage` then `papyrus_storage` doesn't exist as far as blockifier crate is concerned.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1153#-:-NjgQf7q2BKceSAb-lcG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
