### PR TITLE
refactor(execution, native_blockifier): move pre_process_block to PyB…

### PR DESCRIPTION
**Pull request by barak-b-starkware**
…lockExecutor

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1422)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1422)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1422#-Npp_bDA-KNrHT6oP2iy:-Npp_bDA-KNrHT6oP2iz:bfcsmwe) (no related file):*
This might also collide with #1387, please make sure you minimize conflicts. 

___

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1422)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1422#-NprqVKMBYRTZ-qmweCH:-NprqVKMBYRTZ-qmweCI:bta0nby) (no related file):*
Python PR?

___

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1422#-:-NpsPRWI0G8DJZi78rqI:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1422)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Pull request closed without merging**
