### PR TITLE
fix(concurrency): add assert message to the declared_contracts assertion in validate_reads

### PR DESCRIPTION
**Pull request by OriStarkware**
…reads

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1981)

### CODE REVIEW

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1981)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1981#-O-H4FHx9UHWKAZOElqW:-O-H4FHx9UHWKAZOElqX:b2lwe5v) ([raw file](https://github.com/starkware-libs/blockifier/blob/04b37a1ab9034f70b0d6c5e96207714586c64572/crates/blockifier/src/concurrency/versioned_state.rs#L125)):*
> ```XML
>                 is_declared,
>                 self.compiled_contract_classes.read(tx_index + 1, class_hash).is_some(),
>                 "The declared_contracts mapping should match the compiled_contract_classes mapping"
> ```

(Point at the end)



_Suggestion:_
```XML
"The declared_contracts mapping should match the compiled_contract_classes mapping."
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 340 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1981#-O-H50wD8QZqBG5W5FdT:-O-H50wD8QZqBG5W5FdU:b-w831ar) ([raw file](https://github.com/starkware-libs/blockifier/blob/04b37a1ab9034f70b0d6c5e96207714586c64572/crates/blockifier/src/concurrency/versioned_state_test.rs#L340)):*
> ```XML
>     let version_state_proxy = safe_versioned_state.pin_version(0);
>     version_state_proxy.state().declared_contracts.write(0, class_hash!(1_u8), true);
>     assert!(!safe_versioned_state.pin_version(1).validate_reads(&state_maps_to_validate));
> ```

Add another flow in which the assertion fails in the opposite way (`.is_some() == true` and `is_declared == false`)



_Code quote:_
```XML
    let state_maps_to_validate = StateMaps {
        declared_contracts: HashMap::from([(class_hash!(1_u8), false)]),
        ..Default::default()
    };
    let version_state_proxy = safe_versioned_state.pin_version(0);
    version_state_proxy.state().declared_contracts.write(0, class_hash!(1_u8), true);
    assert!(!safe_versioned_state.pin_version(1).validate_reads(&state_maps_to_validate));
```

**Review by noaov1 — COMMENTED** [review]
Can you please explain the motivation for this test?

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1981#-:-O-LRnklBuI9GY1bEyvX:b-1n768c)* status: all files reviewed, 3 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1981#-O-LRVnL915kYqOL5iYV:-O-LRVnL915kYqOL5iYW:bewvy9n) ([raw file](https://github.com/starkware-libs/blockifier/blob/04b37a1ab9034f70b0d6c5e96207714586c64572/crates/blockifier/src/concurrency/versioned_state.rs#L125)):*
> ```XML
>                 is_declared,
>                 self.compiled_contract_classes.read(tx_index + 1, class_hash).is_some(),
>                 "The declared_contracts mapping should match the compiled_contract_classes mapping"
> ```

So it won't contaminate the search



_Suggestion:_
```XML
                "The declared contracts mapping should match the compiled contract classes mapping"
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1981)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1981#-O-H4FHx9UHWKAZOElqW:-O-VZ8Su5i4FpP1_Yk6B:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/04b37a1ab9034f70b0d6c5e96207714586c64572/crates/blockifier/src/concurrency/versioned_state.rs#L125)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

(Point at the end)
</blockquote></details>

Done.

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1981)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 340 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1981#-O-H50wD8QZqBG5W5FdT:-O-VZB937JQR-rJsKaP0:b-sunoey) ([raw file](https://github.com/starkware-libs/blockifier/blob/04b37a1ab9034f70b0d6c5e96207714586c64572/crates/blockifier/src/concurrency/versioned_state_test.rs#L340)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Add another flow in which the assertion fails in the opposite way (`.is_some() == true` and `is_declared == false`)
</blockquote></details>

After discussion, we decided that this is an unnecessary test and we should not add it.

**Review by OriStarkware — COMMENTED** [review]
I am adding a new assert message. The PR initially added a test for the assert, but after discussion we decided that it is an unnecessary test, so I deleted it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1981#-:-O-VZbt7AQbJE9F7L11f:bbgy5b5)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1981)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

**Review by barak-b-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1981)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
