### PR TITLE
Supporting declare version 2 in py transaction.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/473)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/473)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/473#-NVZ4t1fAGG20E17eZDU:-NVZ4t1g50Dsk3J7mSlm:b-yzmfsi) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ed451cb468bb2e27ccab5d1f9efd70fc2b41eb5/crates/native_blockifier/src/py_transaction.rs#L117)):*
> ```XML
> 
>     match version {
>         0 => {
> ```

Same Q as in the other PR: can we consolidate `V0V1`? Having as variants `V0V1 + V0Class` and `V2 + V1Class`?



_Code quote:_
```XML
0 => {
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/473#-NVZ5QikB_O_Ww6o0HB7:-NVZ5FGZ90paIyGe9u8l:btfc2wp) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ed451cb468bb2e27ccab5d1f9efd70fc2b41eb5/crates/native_blockifier/src/py_transaction.rs#L216)):*
> ```XML
>     })
> }
> ```

I think we have those as test utils, perhaps they can be moved to a `utils.rs` file and used here as well?
If too complicated, let's make them not `pub`lic here.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/473#-NVZ5hP1-mIJndHRgVLh:-NVZ5hP1-mIJndHRgVLi:b-3laahq) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ed451cb468bb2e27ccab5d1f9efd70fc2b41eb5/crates/native_blockifier/src/py_transaction.rs#L226)):*
> ```XML
>     let contract_class: ContractClassV1 = casm_contract_class.try_into()?;
> 
>     Ok(contract_class)
> ```

How come this isn't symmetrical to the utility above?



_Code quote:_
```XML
    let contract_class: ContractClassV1 = casm_contract_class.try_into()?;

    Ok(contract_class)
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/473)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/473#-NVZ4t1fAGG20E17eZDU:-NVdzs3N0RnDRB0UOqnO:bhctveo) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ed451cb468bb2e27ccab5d1f9efd70fc2b41eb5/crates/native_blockifier/src/py_transaction.rs#L117)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Same Q as in the other PR: can we consolidate `V0V1`? Having as variants `V0V1 + V0Class` and `V2 + V1Class`?
</blockquote></details>

The main problem is that the `Declare` transaction enum distinguishes between the two.  I can define the transaction itself before the match and use it in 0 and 1 cases. WDYT?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/473#-NVZ5QikB_O_Ww6o0HB7:-NVe0Qkn7xVqyMFe4SlG:b2ody5s) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ed451cb468bb2e27ccab5d1f9efd70fc2b41eb5/crates/native_blockifier/src/py_transaction.rs#L216)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we have those as test utils, perhaps they can be moved to a `utils.rs` file and used here as well?
If too complicated, let's make them not `pub`lic here.
</blockquote></details>

Good point.  Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/473#-NVZ5hP1-mIJndHRgVLh:-NVha9K_8mqAzxBFTpDC:b-xcgy9o) ([raw file](https://github.com/starkware-libs/blockifier/blob/0ed451cb468bb2e27ccab5d1f9efd70fc2b41eb5/crates/native_blockifier/src/py_transaction.rs#L226)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come this isn't symmetrical to the utility above?
</blockquote></details>

Because we cannot deserialize directly to the `Class 1 Inner contract` (and have to "go through" `try_from`).

**Review by elintul — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/473)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/473#-NVtVkwK7Xdnw0u4zCie:-NVtVkwK7Xdnw0u4zCif:b-30vrph) ([raw file](https://github.com/starkware-libs/blockifier/blob/c39e6ee764fdbb10787efae5904957b168c564cf/crates/blockifier/src/test_utils.rs#L152)):*
> ```XML
> pub fn get_contract_class_v1(contract_path: &str) -> ContractClassV1 {
>     let raw_contract_class = get_raw_contract_class(contract_path);
>     crate::utils::get_contract_class_v1(&raw_contract_class).unwrap()
> ```

Why fully-quilified?



_Code quote:_
```XML
crate::utils::get_contract_class_v1
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/473)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/473#-NVtVkwK7Xdnw0u4zCie:-NVulaNrEIY-_w7gvGRh:bjxx4j7) ([raw file](https://github.com/starkware-libs/blockifier/blob/c39e6ee764fdbb10787efae5904957b168c564cf/crates/blockifier/src/test_utils.rs#L152)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why fully-quilified?
</blockquote></details>

Because it has the same name as the function itself. Do you think it would be better to give these functions different names?

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/473)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/473#-NVtVkwK7Xdnw0u4zCie:-NVxgSHZ0Kuzacubswfn:b-5mg9si) ([raw file](https://github.com/starkware-libs/blockifier/blob/c39e6ee764fdbb10787efae5904957b168c564cf/crates/blockifier/src/test_utils.rs#L152)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Because it has the same name as the function itself. Do you think it would be better to give these functions different names?
</blockquote></details>

Perhaps we can have a `from_json_string` method on the contract structs.
The test util can also be a method on another `impl` in `test_utils.rs` (can be done i another PR).

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/473)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/473#-NVtVkwK7Xdnw0u4zCie:-NVy7-Ns0ZFCz5UHlq2U:bfe3fcr) ([raw file](https://github.com/starkware-libs/blockifier/blob/c39e6ee764fdbb10787efae5904957b168c564cf/crates/blockifier/src/test_utils.rs#L152)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps we can have a `from_json_string` method on the contract structs.
The test util can also be a method on another `impl` in `test_utils.rs` (can be done i another PR).
</blockquote></details>

Sound good.

**Pull request merged**
