### PR TITLE
Break up test_utils.rs: extract struct extensions

### PR DESCRIPTION
**Pull request by giladchase**
commit-id:d621942f

---

**Stack**:
- #1179
- #1178
- #1177
- #1176 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1176#-:-NjwYezn5XLmEUfylzkG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1176)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1176#-NjwYjat9KlSx2Tw9VAk:-NjwYjat9KlSx2Tw9VAl:bnutdi5) (no related file):*
Not sure I like the file name, any other ideas?
Also, this PR doesn't really depend on the previous one.

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1176)* status: 0 of 33 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1176#-NjwYjat9KlSx2Tw9VAk:-NkFWGGhE5kbTj2vgF4C:bvwn02u) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure I like the file name, any other ideas?
Also, this PR doesn't really depend on the previous one.
</blockquote></details>

Offline, we decided on keeping as is cause we couldn't find a better one :)

___

**Review by dorimedini-starkware — DISMISSED** [review]
> Reviewed 2 of 16 files at r6, 31 of 31 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1176)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1176#-:-NkL8NqICs79yWCZ2mYi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> Reviewed 2 of 16 files at r6, 31 of 31 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1176)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
