### PR TITLE
feat(concurrency): add halt() to scheduler

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1891)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1891)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1891)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-NxhDBO_1Eg_4IoshHpJ:-NxhDBO_1Eg_4IoshHpK:bz83sd0) ([raw file](https://github.com/starkware-libs/blockifier/blob/3ce3d32b0c0ebc529e6b649c009e7f88aa90634c/crates/blockifier/src/concurrency/scheduler.rs#L229)):*
> ```XML
>     }
> 
>     /// Returns the done marker.
> ```

Maybe the name should be is_done? Because as it is now, it implies that it changes the done flag, and it's a bit confusing.
___
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-Nxh9lKK4wqXN25aY6_E:-Nxh9lKK4wqXN25aY6_F:b-rl2bnu) ([raw file](https://github.com/starkware-libs/blockifier/blob/3ce3d32b0c0ebc529e6b649c009e7f88aa90634c/crates/blockifier/src/concurrency/scheduler_test.rs#L218)):*
> ```XML
> #[case::aborting(0, TransactionStatus::Aborting, false)]
> #[case::index_out_of_bounds(DEFAULT_CHUNK_SIZE, TransactionStatus::ReadyToExecute, false)]
> fn test_try_incarnate(
> ```

Why incarnate? Shouldn't it be something closer to execute or run?

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1891)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1891)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @barak-b-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-NxusDQc-khdVY-Ody8Y:-NxusDQc-khdVY-Ody8Z:bcs1os8) ([raw file](https://github.com/starkware-libs/blockifier/blob/3ce3d32b0c0ebc529e6b649c009e7f88aa90634c/crates/blockifier/src/concurrency/scheduler.rs#L30)):*
> ```XML
>     done_marker: AtomicBool,
>     // Updated by the `halt` procedure. Used to signal to the first thread that halts that it
>     // should perform the halt logic on the executor end.
> ```

Can you please elaborate?



_Code quote:_
```XML
    // should perform the halt logic on the executor end.
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-NxusDQc-khdVY-Ody8Y:-Nxv1MHPCBmA_r7TGaUc:b-79pdge) ([raw file](https://github.com/starkware-libs/blockifier/blob/3ce3d32b0c0ebc529e6b649c009e7f88aa90634c/crates/blockifier/src/concurrency/scheduler.rs#L30)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please elaborate?
</blockquote></details>

I just mean that if there is some logic that the executor runs after the final transaction of the block, and it should only run once, then this marker is used to check whether the thread that called the `halt()` method is actually the thread that halted the scheduler (i.e., no other thread called `halt()` earlier).

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler_test.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-Nxh9lKK4wqXN25aY6_E:-Nxv2oVU9BpXg6alE1JY:b-ro4g29) ([raw file](https://github.com/starkware-libs/blockifier/blob/3ce3d32b0c0ebc529e6b649c009e7f88aa90634c/crates/blockifier/src/concurrency/scheduler_test.rs#L218)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why incarnate? Shouldn't it be something closer to execute or run?
</blockquote></details>

Most of the names come from the BlockSTM paper, and we avoided changing them to make it easier to compare our code to the algorithm in the paper. The word incarnate comes from the fact that any given execution of the same tx is called an "incarnation" in the paper.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1891)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-NxhDBO_1Eg_4IoshHpJ:-Nxv2YXx0eMjk2u7qNII:bqhk485) ([raw file](https://github.com/starkware-libs/blockifier/blob/3ce3d32b0c0ebc529e6b649c009e7f88aa90634c/crates/blockifier/src/concurrency/scheduler.rs#L229)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Maybe the name should be is_done? Because as it is now, it implies that it changes the done flag, and it's a bit confusing.
</blockquote></details>

Most of the names come from the BlockSTM paper, and we avoided changing them to make it easier to compare our code to the algorithm in the paper.

**Review by noaov1 — CHANGES_REQUESTED** [review]
Can you please explain the logic of the halt marker?
How are you planning to stop the threads?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-:-Ny4KdOH694Kg5clAE8G:b4bm67y)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-NxusDQc-khdVY-Ody8Y:-Ny4KLM7AFE2q4CFVr_J:b-iz3nnr) ([raw file](https://github.com/starkware-libs/blockifier/blob/3ce3d32b0c0ebc529e6b649c009e7f88aa90634c/crates/blockifier/src/concurrency/scheduler.rs#L30)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I just mean that if there is some logic that the executor runs after the final transaction of the block, and it should only run once, then this marker is used to check whether the thread that called the `halt()` method is actually the thread that halted the scheduler (i.e., no other thread called `halt()` earlier).
</blockquote></details>

Do you have some logic in mind?
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 234 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-Ny4KrMG9ZJlEfAQjBhd:-Ny4KrMG9ZJlEfAQjBhe:b-k9gvrz) ([raw file](https://github.com/starkware-libs/blockifier/blob/7df2b9f0bb8f769cb11e18b37f4a3edc13cf021d/crates/blockifier/src/concurrency/scheduler.rs#L234)):*
> ```XML
>         let index_to_validate = self.validation_index.load(Ordering::Acquire);
>         if index_to_validate >= self.chunk_size {
>             self.check_done();
> ```

Why did you remove it?
Same question for the `next_version_to_execute` method?



_Code quote:_
```XML
            self.check_done();
```

**Comment by avi-starkware** [comment]
+reviewer:@Yoni-Starkware

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1891)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 46 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-NyVnwJa-Lj1GWIE2GqI:-NyVnwJa-Lj1GWIE2GqJ:b-humjfy) ([raw file](https://github.com/starkware-libs/blockifier/blob/04957842727a8a577417540c19f6956aa061c303/crates/blockifier/src/concurrency/scheduler.rs#L46)):*
> ```XML
>         self.scheduler.done_marker.store(true, Ordering::Release);
>         assert!(*self.commit_index_guard > 0, "Commit index underflow.");
>         *self.commit_index_guard -= 1;
> ```

`done` should be the last operation on the scheduler (no bug right now but better to be safe)



_Suggestion:_
```XML
        assert!(*self.commit_index_guard > 0, "Commit index underflow.");
        *self.commit_index_guard -= 1;
        
        self.scheduler.done_marker.store(true, Ordering::Release);
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/scheduler.rs` line 46 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-NyVnwJa-Lj1GWIE2GqI:-NyW9hCW-4vpK1_W3_Ev:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/04957842727a8a577417540c19f6956aa061c303/crates/blockifier/src/concurrency/scheduler.rs#L46)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`done` should be the last operation on the scheduler (no bug right now but better to be safe)
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1891#-:-NyWxQuA-urboDjKGGl_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
