### PR TITLE
TMP - DO NOT MERGE

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/551)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> Reviewed 8 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/551)* status: 8 of 13 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4LND0BSDfItYp9kcr:-NX4LND0BSDfItYp9kcs:b-7dmj6t) ([raw file](https://github.com/starkware-libs/blockifier/blob/19f3c6d0d70831c655e657aaee52f5dff5c0b2ab/crates/blockifier/src/test_utils.rs#L337)):*
> ```XML
> 
>     pub fn create_for_account_testing() -> BlockContext {
>         let vm_resource_fee_cost = HashMap::from([
> ```

Should this be `ResourcesMapping`? 



_Code quote:_
```XML
HashMap::from(
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4IR2W4uO8WYvGLwE8:-NX4IR2XExiquhB3mw1c:b-hyoy0j) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4f6cb3b9ba9129ee4c3d43d367f39367f7966ed/crates/blockifier/src/execution/contract_class.rs#L204)):*
> ```XML
>         let program = Program::new(
>             builtins,
>             Felt252::prime().to_str_radix(16),
> ```

Why was this removed?



_Code quote:_
```XML
      Felt252::prime().to_str_radix(16),
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4Qj1x2eQhN7aMaEfz:-NX4Qj1x2eQhN7aMaEg-:b-xp53u2) ([raw file](https://github.com/starkware-libs/blockifier/blob/19f3c6d0d70831c655e657aaee52f5dff5c0b2ab/crates/blockifier/src/fee/fee_test.rs#L22)):*
> ```XML
>         (String::from(BITWISE_BUILTIN_NAME), 1),
>         (String::from(POSEIDON_BUILTIN_NAME), 1),
>     ]))
> ```

Perhaps add an impl for `ResourcesMapping::from_iter([("n_steps",1800),..)`, something like
```rust
impl<'a> FromIterator<(&'a str, usize)> for ResourcesMapping {
    fn from_iter<I: IntoIterator<Item = (&'a str, usize)>>(iter: I) -> Self {
        Self(iter.into_iter().map(|(key, value)| (key.to_string(), value)).collect())
    }
}
```



_Code quote:_
```XML
    ResourcesMapping(HashMap::from([
        (String::from("n_steps"), 1800),
        (String::from(HASH_BUILTIN_NAME), 10),
        (String::from(RANGE_CHECK_BUILTIN_NAME), 24),
        (String::from(SIGNATURE_BUILTIN_NAME), 1),
        (String::from(BITWISE_BUILTIN_NAME), 1),
        (String::from(POSEIDON_BUILTIN_NAME), 1),
    ]))
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4Jhs-Cya1cMxAE8Zh:-NX4Jhs-Cya1cMxAE8Zi:bllp32i) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4f6cb3b9ba9129ee4c3d43d367f39367f7966ed/crates/native_blockifier/src/py_transaction.rs#L123)):*
> ```XML
>         .collect();
> 
>     Ok(cairo_resource_fee_weights)
> ```

THANK U




_Code quote:_
```XML
}

fn process_cairo_resource_fee_weights(
    general_config: &PyAny,
) -> Result<HashMap<String, f64>, NativeBlockifierError> {
    let cairo_resource_fee_weights: HashMap<String, f64> =
        py_attr(general_config, "cairo_resource_fee_weights")?;

    // Remove the suffix "_builtin" from the keys, if exists.
    // FIXME: This should be fixed in python though...
    let cairo_resource_fee_weights = cairo_resource_fee_weights
        .into_iter()
        .map(|(k, v)| (k.trim_end_matches("_builtin").to_string(), v))
        .collect();

    Ok(cairo_resource_fee_weights)
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/551)* status: 8 of 13 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4S_zrBkPUqWC9f0R5:-NX4S_zrBkPUqWC9f0R6:b-nm5hn2) ([raw file](https://github.com/starkware-libs/blockifier/blob/19f3c6d0d70831c655e657aaee52f5dff5c0b2ab/crates/blockifier/src/test_utils.rs#L7)):*
> ```XML
> use cairo_vm::vm::runners::builtin_runner::{
>     BITWISE_BUILTIN_NAME, EC_OP_BUILTIN_NAME, HASH_BUILTIN_NAME, OUTPUT_BUILTIN_NAME,
>     POSEIDON_BUILTIN_NAME, RANGE_CHECK_BUILTIN_NAME, SIGNATURE_BUILTIN_NAME,
> ```

Should these be in constants.rs? (I'm not sure...)



_Code quote:_
```XML
    BITWISE_BUILTIN_NAME, EC_OP_BUILTIN_NAME, HASH_BUILTIN_NAME, OUTPUT_BUILTIN_NAME,
    POSEIDON_BUILTIN_NAME, RANGE_CHECK_BUILTIN_NAME, SIGNATURE_BUILTIN_NAME,
```
___
*[`crates/blockifier/src/test_utils.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4SRPA-zR_tAY6ZqvP:-NX4SRPA-zR_tAY6ZqvQ:becxggy) ([raw file](https://github.com/starkware-libs/blockifier/blob/19f3c6d0d70831c655e657aaee52f5dff5c0b2ab/crates/blockifier/src/test_utils.rs#L338)):*
> ```XML
>     pub fn create_for_account_testing() -> BlockContext {
>         let vm_resource_fee_cost = HashMap::from([
>             (String::from("n_steps"), 1_f64),
> ```

I think we have  N_STEPS_RESOURCE in constants.rs



_Code quote:_
```XML
"n_steps"
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/551)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4S_zrBkPUqWC9f0R5:-NX531K307vHYVlNrMIR:b-mz7gfa) ([raw file](https://github.com/starkware-libs/blockifier/blob/19f3c6d0d70831c655e657aaee52f5dff5c0b2ab/crates/blockifier/src/test_utils.rs#L7)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should these be in constants.rs? (I'm not sure...)
</blockquote></details>

These are imported from LC. I can ask them to move these but not in the blockifier repo...
___
*[`crates/blockifier/src/test_utils.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4LND0BSDfItYp9kcr:-NX53DWOBLgRJ8Cg_J3Q:b-bhtqmp) ([raw file](https://github.com/starkware-libs/blockifier/blob/19f3c6d0d70831c655e657aaee52f5dff5c0b2ab/crates/blockifier/src/test_utils.rs#L337)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should this be `ResourcesMapping`? 
</blockquote></details>

No; `ResourcesMapping` is a `HashMap<String, usize>`, not a `HashMap<String, f64>`
___
*[`crates/blockifier/src/test_utils.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4SRPA-zR_tAY6ZqvP:-NX54Sez2yNjiF6ZUC96:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/19f3c6d0d70831c655e657aaee52f5dff5c0b2ab/crates/blockifier/src/test_utils.rs#L338)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think we have  N_STEPS_RESOURCE in constants.rs
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4IR2W4uO8WYvGLwE8:-NX55ZGqBDBY8OJz-cTB:b-5hciz4) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4f6cb3b9ba9129ee4c3d43d367f39367f7966ed/crates/blockifier/src/execution/contract_class.rs#L204)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Why was this removed?
</blockquote></details>

from [here](https://github.com/lambdaclass/cairo-rs/pull/999), don't know why; maybe only default prime is used.
Should I escalate question to LC?
___
*[`crates/blockifier/src/fee/fee_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4Qj1x2eQhN7aMaEfz:-NX55mDk1A40awkJiLtU:bof2xg4) ([raw file](https://github.com/starkware-libs/blockifier/blob/19f3c6d0d70831c655e657aaee52f5dff5c0b2ab/crates/blockifier/src/fee/fee_test.rs#L22)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Perhaps add an impl for `ResourcesMapping::from_iter([("n_steps",1800),..)`, something like
```rust
impl<'a> FromIterator<(&'a str, usize)> for ResourcesMapping {
    fn from_iter<I: IntoIterator<Item = (&'a str, usize)>>(iter: I) -> Self {
        Self(iter.into_iter().map(|(key, value)| (key.to_string(), value)).collect())
    }
}
```
</blockquote></details>

1. I think it's a bit excessive to add this just to drop `HashMap::from`
2. No guarantee that `ResourcesMapping` will always be a tuple struct with a single mapping

WDYT?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4Jhs-Cya1cMxAE8Zh:-NX5692X-IQS9z1C7De5:b-dtvis7) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4f6cb3b9ba9129ee4c3d43d367f39367f7966ed/crates/native_blockifier/src/py_transaction.rs#L123)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

THANK U


</blockquote></details>

**Review by giladchase — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/551)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4IR2W4uO8WYvGLwE8:-NX9Rh_G-Dgxz-wm0HyC:bmuyuh2) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4f6cb3b9ba9129ee4c3d43d367f39367f7966ed/crates/blockifier/src/execution/contract_class.rs#L204)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

from [here](https://github.com/lambdaclass/cairo-rs/pull/999), don't know why; maybe only default prime is used.
Should I escalate question to LC?
</blockquote></details>

Mmm looks like boilerplate, if it is indeed the case then not worth it I think
___
*[`crates/blockifier/src/fee/fee_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4Qj1x2eQhN7aMaEfz:-NX9Rt0kBFYE6RNnL5gY:b-hem3lk) ([raw file](https://github.com/starkware-libs/blockifier/blob/19f3c6d0d70831c655e657aaee52f5dff5c0b2ab/crates/blockifier/src/fee/fee_test.rs#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. I think it's a bit excessive to add this just to drop `HashMap::from`
2. No guarantee that `ResourcesMapping` will always be a tuple struct with a single mapping

WDYT?
</blockquote></details>

Fair enough :)
___
*[`crates/native_blockifier/src/py_transaction.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX4Jhs-Cya1cMxAE8Zh:-NX9RyMD8Que2xOjimgq:bc52tdo) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4f6cb3b9ba9129ee4c3d43d367f39367f7966ed/crates/native_blockifier/src/py_transaction.rs#L123)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>


</blockquote></details>

:laughing:

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/551)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/551#-NX9YotQ0rSbbCUBEnBM:-NX9YotQ0rSbbCUBEnBN:b-kvpxf9) (no related file):*


___

**Pull request closed without merging**
