### PR TITLE
Replace *py_felt_sequence_attr method.*

### PR DESCRIPTION
**Pull request by NirLevi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/832)

### CODE REVIEW

**Review by giladchase — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/832#-:-NbtVEEi4P0dQCUfiX0q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @NirLevi-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/832#-NbtUrXCCFPlU867AzlC:-NbtUrXD8i48VnIIUxR4:biyol5d) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f181a4d5b453dc1034d8be64c4e353c9511e98/crates/native_blockifier/src/py_transaction.rs#L33)):*
> ```XML
> 
> fn py_calldata(tx: &PyAny, attr: &str) -> NativeBlockifierResult<Calldata> {
>     let py_call: Vec<PyFelt> = tx.getattr(attr)?.extract()?;
> ```

Also in the other one, just to keep things a bit cleaner in the meantime, even though in subsequent PRs you'll be refactoring this code again.



_Suggestion:_
```XML
let py_call: Vec<PyFelt> = py_attr(tx, attr)?
```

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/832#-:-NbtY1JR2L-UZJsIQGvL:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @NirLevi-starkware)

**Comment by NirLevi-starkware** [comment]
*[`crates/native_blockifier/src/py_transaction.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/832#-NbtUrXCCFPlU867AzlC:-NbtXy2Q5T7_gCJLzzsk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f181a4d5b453dc1034d8be64c4e353c9511e98/crates/native_blockifier/src/py_transaction.rs#L33)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Also in the other one, just to keep things a bit cleaner in the meantime, even though in subsequent PRs you'll be refactoring this code again.
</blockquote></details>

Done.

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/832)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NirLevi-starkware)

**Pull request merged**
