### PR TITLE
Refactor calculate_tx_gas_usage

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1320)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
I want to share code from the "calculate_tx_gas_usage" function for the next PR (I will use "calculate_l2_to_l1_payloads_length_and_message_segment_length"). While doing that, I realized "calculate_l1_gas_usage" is no longer needed. This change has affected many tests.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-:-NnnpxVt-w_btr9eXkP0:b-357azb)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-Nnn97W09S6n96jP7KPF:-NnnotKV3mBCDCK5HOly:b-hq9rye) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f4a1d48ad9c81618b37f224fdbf2339b1dfabe6/crates/blockifier/src/fee/gas_usage.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Shouldn't this be "length of the addition"? or something of that nature
</blockquote></details>

 not sure this comment is still relevant. was moved from "calculate_tx_gas_usage" func. 
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-NnnBGWl8AD7bXdQrqoH:-NnnsskHBZZ3AL4bQ1Dq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f4a1d48ad9c81618b37f224fdbf2339b1dfabe6/crates/blockifier/src/fee/gas_usage_test.rs#L210)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

you can unwrap freely in tests, no need for `and_then` (which is rarely used, since it isn't too intuitive), unless you want to explicitly assert something being OK as part of the test logic.
</blockquote></details>

Done.

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-Nnqq2hJD96iAABS2ktB:-Nnqq2hK6XucoRiXryKd:b-hhxv84) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd1a7665b27d586546c6858c751cf5cdb40af56f/crates/blockifier/src/fee/gas_usage.rs#L23)):*
> ```XML
> // TODO(Ayelet, 10/1/2024): Use to calculate message segment length in transaction_executer's
> // execute
> pub fn calculate_l2_to_l1_payloads_length_and_message_segment_length<'a>(
> ```

Plz make private until it is actually used outside of this module.
Also, once it is reused, consider bundling the payload length and segment  length into some struct (for 1-2 usages returning the 2-tuple is fine).



_Code quote:_
```XML
// TODO(Ayelet, 10/1/2024): Use to calculate message segment length in transaction_executer's
// execute
pub fn calculate_l2_to_l1_payloads_length_and_message_segment_length<'a>(
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-Nnqq2hJD96iAABS2ktB:-NnrT2JD-0fcsNtCaTmv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd1a7665b27d586546c6858c751cf5cdb40af56f/crates/blockifier/src/fee/gas_usage.rs#L23)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Plz make private until it is actually used outside of this module.
Also, once it is reused, consider bundling the payload length and segment  length into some struct (for 1-2 usages returning the 2-tuple is fine).
</blockquote></details>

Done.

**Review by giladchase — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1320)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1320)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-No7QuY63Evau8w9Hw3Q:-No7QuY63Evau8w9Hw3R:b-qlvp8m) ([raw file](https://github.com/starkware-libs/blockifier/blob/b405d20a958afcf22557f06234c682676eb68870/crates/blockifier/src/fee/gas_usage.rs#L33)):*
> ```XML
> 
>     let residual_message_segment_length =
>         get_message_segment_length(&l2_to_l1_payloads_length, l1_handler_payload_size);
> ```

What is the meaning of residual in this context?



_Code quote:_
```XML
    let residual_message_segment_length =
        get_message_segment_length(&l2_to_l1_payloads_length, l1_handler_payload_size);
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-No7SzQZ69_-3L6zOBH2:-No7SzQZ69_-3L6zOBH3:btk84kh) ([raw file](https://github.com/starkware-libs/blockifier/blob/b405d20a958afcf22557f06234c682676eb68870/crates/blockifier/src/fee/gas_usage_test.rs#L123)):*
> ```XML
>             ..Default::default()
>         },
>     ];
> ```

Consider using a loop



_Code quote:_
```XML
        CallInfo {
            execution: CallExecution {
                l2_to_l1_messages: vec![OrderedL2ToL1Message {
                    message: Default::default(),
                    ..Default::default()
                }],
                ..Default::default()
            },
            ..Default::default()
        },
        CallInfo {
            execution: CallExecution {
                l2_to_l1_messages: vec![OrderedL2ToL1Message {
                    message: MessageToL1 {
                        payload: L2ToL1Payload(vec![stark_felt!(0_u16)]),
                        ..Default::default()
                    },
                    ..Default::default()
                }],
                ..Default::default()
            },
            ..Default::default()
        },
        CallInfo {
            execution: CallExecution {
                l2_to_l1_messages: vec![OrderedL2ToL1Message {
                    message: MessageToL1 {
                        payload: L2ToL1Payload(vec![stark_felt!(0_u16), stark_felt!(0_u16)]),
                        ..Default::default()
                    },
                    ..Default::default()
                }],
                ..Default::default()
            },
            ..Default::default()
        },
        CallInfo {
            execution: CallExecution {
                l2_to_l1_messages: vec![OrderedL2ToL1Message {
                    message: MessageToL1 {
                        payload: L2ToL1Payload(vec![
                            stark_felt!(0_u16),
                            stark_felt!(0_u16),
                            stark_felt!(0_u16),
                        ]),
                        ..Default::default()
                    },
                    ..Default::default()
                }],
                ..Default::default()
            },
            ..Default::default()
        },
    ];
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1450 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-No7GHi9086aXHpsWm4L:-No7GHi9086aXHpsWm4M:b6ki81q) ([raw file](https://github.com/starkware-libs/blockifier/blob/b405d20a958afcf22557f06234c682676eb68870/crates/blockifier/src/transaction/transactions_test.rs#L1450)):*
> ```XML
>     let l1_gas_usage = calculate_tx_gas_usage(std::iter::empty(), state_changes_count, None);
>     assert!(l1_gas_usage.is_ok());
>     assert_eq!(tx_execution_info.actual_resources.gas_usage(), l1_gas_usage.unwrap());
> ```

Can you please change it in all the calls to `calculate_tx_gas_usage` in test files?



_Suggestion:_
```XML
    let l1_gas_usage = calculate_tx_gas_usage(std::iter::empty(), state_changes_count, None).unwrap();
    assert_eq!(tx_execution_info.actual_resources.gas_usage(), l1_gas_usage);
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1320)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 98 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-NoDn-EzBsUGGjNHylrY:-NoDn-EzBsUGGjNHylrZ:b-3ud3v5) ([raw file](https://github.com/starkware-libs/blockifier/blob/37b67069d6cd1c41d0179b7bba77968eb6455d4b/crates/blockifier/src/fee/gas_usage_test.rs#L98)):*
> ```XML
>     };
>     let l2_to_l1_messages_gas_usage =
>         calculate_tx_gas_usage(call_infos.iter(), l2_to_l1_state_changes_count, None).unwrap();
> ```

Consider defining `let call_infos_iter = call_infos.iter()` (you can also use it when calculating `l2_to_l1_payloads_length`).



_Code quote:_
```XML
call_infos.iter()
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-NoDme2yB20eIz5eDZ1c:-NoDme2yB20eIz5eDZ1d:b-z2dejy) ([raw file](https://github.com/starkware-libs/blockifier/blob/37b67069d6cd1c41d0179b7bba77968eb6455d4b/crates/blockifier/src/fee/gas_usage_test.rs#L152)):*
> ```XML
> 
>     // l2_to_l1_messages_gas_usage and storage_writings_gas_usage got a discount each, while
>     // the combined calculation got it once.
> ```

Why did you move this comment?



_Code quote:_
```XML
    // l2_to_l1_messages_gas_usage and storage_writings_gas_usage got a discount each, while
    // the combined calculation got it once.
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 98 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-NoDn-EzBsUGGjNHylrY:-NoGWgf-A5nYjljgTd52:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/37b67069d6cd1c41d0179b7bba77968eb6455d4b/crates/blockifier/src/fee/gas_usage_test.rs#L98)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining `let call_infos_iter = call_infos.iter()` (you can also use it when calculating `l2_to_l1_payloads_length`).
</blockquote></details>

Done
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-NoDme2yB20eIz5eDZ1c:-NoGWei709Op92Eaxd6E:b-886gsx) ([raw file](https://github.com/starkware-libs/blockifier/blob/37b67069d6cd1c41d0179b7bba77968eb6455d4b/crates/blockifier/src/fee/gas_usage_test.rs#L152)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you move this comment?
</blockquote></details>

Fixed

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-:-NoGuCL5EprHLOB-KZIe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 98 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1320#-NoDn-EzBsUGGjNHylrY:-NoGtyRo1y9VVK91rJbQ:bz0nhvv) ([raw file](https://github.com/starkware-libs/blockifier/blob/37b67069d6cd1c41d0179b7bba77968eb6455d4b/crates/blockifier/src/fee/gas_usage_test.rs#L98)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Previously it looked better, right? Anyway, next PR.

**Pull request merged**
