### PR TITLE
Add secp256k1_new.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 5 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 660 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NYsCECSEb5G0rQaGeeQ:-NYsCECSEb5G0rQaGeeR:b-n6dpf5) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d05b95f79fba74a42baeae463111c4e54aa0419/crates/blockifier/src/execution/syscalls/mod.rs#L660)):*
> ```XML
> }
> 
> // Secp256k1 new syscall.
> ```

Add a blank line below.
Keep alphabetized (also Keccak should be moved).



_Code quote:_
```XML
// Secp256k1 new syscall.
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: 5 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NYsCxs4BJ0Q_lHbk9x7:-NYsCxs4BJ0Q_lHbk9x8:b-k2pczf) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d05b95f79fba74a42baeae463111c4e54aa0419/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L176)):*
> ```XML
> 
> #[test]
> fn test_secp256k1() {
> ```

Here too.



_Code quote:_
```XML
fn test_secp256k1
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NYsCxs4BJ0Q_lHbk9x7:-NYvYS21C0B6_YGz1huY:bzbbkjf) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d05b95f79fba74a42baeae463111c4e54aa0419/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L176)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Here too.
</blockquote></details>

nothing is alphabetized here.

the first test is
test_storage_read_write
and the second is 
test_call_contract

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NYsCxs4BJ0Q_lHbk9x7:-NYvcXcc8djXRY-raPaT:b-xxeql1) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d05b95f79fba74a42baeae463111c4e54aa0419/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L176)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

nothing is alphabetized here.

the first test is
test_storage_read_write
and the second is 
test_call_contract
</blockquote></details>

I think it is done now.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 660 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NYsCECSEb5G0rQaGeeQ:-NYvcVBK-mssy_6LMR7_:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d05b95f79fba74a42baeae463111c4e54aa0419/crates/blockifier/src/execution/syscalls/mod.rs#L660)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a blank line below.
Keep alphabetized (also Keccak should be moved).
</blockquote></details>

done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 497 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ055wY9A2PtA1HHWRC:-NZ055wY9A2PtA1HHWRD:b-6l60rq) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f198513427e52003da769e224e2f935e474e9cd/crates/blockifier/src/execution/syscalls/mod.rs#L497)):*
> ```XML
> }
> 
> pub fn secp256k1_new(
> ```

based on
https://github.com/starkware-libs/cairo/blob/cce494fd766d5c57478db067d4c98d77597810b8/crates/cairo-lang-runner/src/casm_run/mod.rs#L1061

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 467 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ09itPCUMc6ko-Q7Sx:-NZ09itPCUMc6ko-Q7Sy:b-f688y5) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f198513427e52003da769e224e2f935e474e9cd/crates/blockifier/src/execution/syscalls/mod.rs#L467)):*
> ```XML
> }
> 
> // Secp256k1 new syscall.
> ```

split into:
https://reviewable.io/reviews/starkware-libs/blockifier/678



_Code quote:_
```XML
// Secp256k1 new syscall.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 467 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ09itPCUMc6ko-Q7Sx:-NZ0zhHKDlKXbNDnG3HX:b-jpzpr7) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f198513427e52003da769e224e2f935e474e9cd/crates/blockifier/src/execution/syscalls/mod.rs#L467)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

split into:
https://reviewable.io/reviews/starkware-libs/blockifier/678
</blockquote></details>

merged.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 4 of 13 files at r1, 1 of 2 files at r2, 1 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @elintul and @ilyalesokhin-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 198 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ1FjJ55RKIG-g-ORHV:-NZ1FjJ55RKIG-g-ORHW:bjh3jr7) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L198)):*
> ```Cairo
>         // Test a point not on the curve.
>         assert (starknet::secp256k1::secp256k1_new_syscall(
>             x: 0, y: 1).unwrap_syscall().is_none(), 'Should be none');
> ```

Can you please explain why it should be none?



_Code quote:_
```Cairo
        assert (starknet::secp256k1::secp256k1_new_syscall(
            x: 0, y: 1).unwrap_syscall().is_none(), 'Should be none');
```
___
*[`crates/blockifier/src/abi/constants.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ122jf6yK-CgRuKa1C:-NZ122jf6yK-CgRuKa1D:bsf1syu) ([raw file](https://github.com/starkware-libs/blockifier/blob/90253d2d0d512cbed9046ede5ced09fd41bedaaf/crates/blockifier/src/abi/constants.rs#L40)):*
> ```XML
> // See documentation in core/os/constants.cairo.
> pub const STEP_GAS_COST: u64 = 100;
> pub const RANGE_CHECK_GAS_COST: u64 = 70;
> ```

Can you please explain what this is?



_Code quote:_
```XML
pub const RANGE_CHECK_GAS_COST: u64 = 70;
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ13Odi4vBmBuzyYlYJ:-NZ13Odi4vBmBuzyYlYK:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/90253d2d0d512cbed9046ede5ced09fd41bedaaf/crates/blockifier/src/execution/syscalls/hint_processor.rs#L93)):*
> ```XML
> 
> pub const INVALID_ARGUMENT: &str =
>     "0x00000000000000000000000000000000496e76616c696420617267756d656e74"; // "Invalid argument";
> ```





_Suggestion:_
```XML
pub const OUT_OF_GAS_ERROR: &str =
    "0x000000000000000000000000000000000000000000004f7574206f6620676173"; // "Out of gas";
pub const INVALID_INPUT_LENGTH_ERROR: &str =
    "0x000000000000000000000000496e76616c696420696e707574206c656e677468"; // "Invalid input length";
pub const INVALID_ARGUMENT: &str =
    "0x00000000000000000000000000000000496e76616c696420617267756d656e74"; // "Invalid argument";
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 413 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ1Ak8241VZcHWAPkBd:-NZ1Ak8241VZcHWAPkBe:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/90253d2d0d512cbed9046ede5ced09fd41bedaaf/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L413)):*
> ```XML
>             gas_consumed: stark_felt!(174970_u64),
>             ..CallExecution::from_retdata(retdata![])
>         }
> ```





_Suggestion:_
```XML
    assert_eq!(
        entry_point_call.execute_directly(&mut state).unwrap().execution,
        CallExecution {
            gas_consumed: stark_felt!(174970_u64),
            ..Default:default()
        }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 198 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ1FjJ55RKIG-g-ORHV:-NZ1JBhP-mDd0h2MXZ83:bvdffst) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L198)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain why it should be none?
</blockquote></details>

0, 1 is not on the curve and
 

(0, don't care) is interpreted as None.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/constants.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ122jf6yK-CgRuKa1C:-NZ1JJq531iX0TYXznUR:b-nhq5tw) ([raw file](https://github.com/starkware-libs/blockifier/blob/90253d2d0d512cbed9046ede5ced09fd41bedaaf/crates/blockifier/src/abi/constants.rs#L40)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain what this is?
</blockquote></details>

thats the value we've decided on.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ13Odi4vBmBuzyYlYJ:-NZ1JcSeBAmSXZPJ478p:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/90253d2d0d512cbed9046ede5ced09fd41bedaaf/crates/blockifier/src/execution/syscalls/hint_processor.rs#L93)):*
> ```XML
> 
> pub const INVALID_ARGUMENT: &str =
>     "0x00000000000000000000000000000000496e76616c696420617267756d656e74"; // "Invalid argument";
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 413 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ1Ak8241VZcHWAPkBd:-NZ1JXkT8ZLMkY9mAB8w:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/90253d2d0d512cbed9046ede5ced09fd41bedaaf/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L413)):*
> ```XML
>             gas_consumed: stark_felt!(174970_u64),
>             ..CallExecution::from_retdata(retdata![])
>         }
> ```

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 13 files at r1, 1 of 2 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1)

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: all files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ55mY8ErR6OTQzJD51:-NZ55mY9B3qlYnZE7Bau:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/src/execution/syscalls/hint_processor.rs#L118)):*
> ```XML
>     pub accessed_keys: HashSet<StorageKey>,
> 
>     // secp256k1 points.
> ```





_Suggestion:_
```XML
// Secp256k1 points.
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 237 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ55ugu5bLbi_tIjAB_:-NZ55ugu5bLbi_tIjABa:b-ohk3y9) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/src/execution/syscalls/hint_processor.rs#L237)):*
> ```XML
>             SyscallSelector::Secp256k1New => {
>                 self.execute_syscall(vm, secp256k1_new, constants::SECP256K1_NEW_GAS_COST)
>             }
> ```

Keep alphabetized, remove blank line.



_Suggestion:_
```XML
            SyscallSelector::Keccak => self.execute_syscall(vm, keccak, constants::KECCAK_GAS_COST),
            SyscallSelector::Secp256k1New => {
                self.execute_syscall(vm, secp256k1_new, constants::SECP256K1_NEW_GAS_COST)
            }
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ568ggBbFhOUjg9e6F:-NZ568ggBbFhOUjg9e6G:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/src/execution/syscalls/secp.rs#L73)):*
> ```XML
>     } else {
>         secp256k1::Affine::new_unchecked(x.into(), y.into())
>     };
> ```





_Suggestion:_
```XML
    
    let p = if x.is_zero() && y.is_zero() {
        secp256k1::Affine::identity()
    } else {
        secp256k1::Affine::new_unchecked(x.into(), y.into())
    };
    
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ56kYl0o7ZxCIxfp2q:-NZ56kYm-rwUoU5lEf_V:ba8t4ly) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/src/execution/syscalls/secp.rs#L82)):*
> ```XML
>         } else {
>             None
>         },
> ```

Move outside struct initialization, this line is hard to read.



_Code quote:_
```XML
        optional_ec_point_id: if p.is_on_curve() && p.is_in_correct_subgroup_assuming_on_curve() {
            let points = &mut syscall_handler.secp256k1_points;
            let id = points.len();
            points.push(p);
            Some(id)
        } else {
            None
        },
```

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 198 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ1FjJ55RKIG-g-ORHV:-NZ1KhJ28iv_O7emmckD:b4mbii0) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L198)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

0, 1 is not on the curve and
 

(0, don't care) is interpreted as None.
</blockquote></details>

Can you please add a short documentation regarding this in `Secp256k1NewResponse`?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/constants.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ122jf6yK-CgRuKa1C:-NZ5XoSc1lntqzcFfn23:b1ger1h) ([raw file](https://github.com/starkware-libs/blockifier/blob/90253d2d0d512cbed9046ede5ced09fd41bedaaf/crates/blockifier/src/abi/constants.rs#L40)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

thats the value we've decided on.
</blockquote></details>

for the cost os a using a single range check unit.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 198 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ1FjJ55RKIG-g-ORHV:-NZ5YHhpAHm69RKi-n5v:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L198)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please add a short documentation regarding this in `Secp256k1NewResponse`?
</blockquote></details>

done
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 237 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ55ugu5bLbi_tIjAB_:-NZ5XVh49srhFjkLmlNZ:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/src/execution/syscalls/hint_processor.rs#L237)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Keep alphabetized, remove blank line.
</blockquote></details>

done
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ568ggBbFhOUjg9e6F:-NZ5Xdfj0yrNETnbLd9j:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/src/execution/syscalls/secp.rs#L73)):*
> ```XML
>     } else {
>         secp256k1::Affine::new_unchecked(x.into(), y.into())
>     };
> ```

done
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ56kYl0o7ZxCIxfp2q:-NZ5Xgg-52ha0pjht26b:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/src/execution/syscalls/secp.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move outside struct initialization, this line is hard to read.
</blockquote></details>

done.

**Review by elintul — DISMISSED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 237 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ55ugu5bLbi_tIjAB_:-NZ5ZQFS5r9bX7lPTCGu:b-qzus3x) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0dce00e5f110c518149f44eb67571ee382f902/crates/blockifier/src/execution/syscalls/hint_processor.rs#L237)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

done
</blockquote></details>

Keccak too, please.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 35 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ5ZW2l9qSTZrj9HgvL:-NZ5ZW2l9qSTZrj9HgvM:b-aegs8z) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad75c299a78ed48175b27bc952e48e739ee91f35/crates/blockifier/src/execution/syscalls/secp.rs#L35)):*
> ```XML
>     // The syscall returns `Option<Secp256k1Point>` which is represented as two felts in Cairo0.
>     // The first felt is a indicates if it is `Some` (0) or `None` (1).
>     // The second felt is only valid if the first felt is `Some` and contains the id of the point.
> ```

WDYM by ID, BTW? Simply its creation order? Perhaps elaborate shortly.



_Suggestion:_
```XML
the ID of
```

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 244 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ5_i348n6OJCY5fuza:-NZ5_i35B5AJgVg3tBMk:b-x70ep2) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7e51b5a4ee0f9c88b9eb93f9c98440adad93031/crates/blockifier/src/execution/syscalls/hint_processor.rs#L244)):*
> ```XML
>             }
> 
>             _ => Err(HintError::UnknownHint(
> ```

Remove blank line above.



_Code quote:_
```XML
 _ => Err(HintError::UnknownHint(
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 35 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ5ZW2l9qSTZrj9HgvL:-NZ5a665-7wYrsE4samA:bdm7gq0) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad75c299a78ed48175b27bc952e48e739ee91f35/crates/blockifier/src/execution/syscalls/secp.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM by ID, BTW? Simply its creation order? Perhaps elaborate shortly.
</blockquote></details>

I'll just say the co-pilot figured it out on its own.

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666#-:-NZ5b5p7830PqCWhWCqK:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/abi/constants.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ122jf6yK-CgRuKa1C:-NZ5axWU5TMi00IbFeWC:bos8k14) ([raw file](https://github.com/starkware-libs/blockifier/blob/90253d2d0d512cbed9046ede5ced09fd41bedaaf/crates/blockifier/src/abi/constants.rs#L40)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

for the cost os a using a single range check unit.
</blockquote></details>

WDYM? I wonder if it fits better under `// OS gas costs.`

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/constants.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/666#-NZ122jf6yK-CgRuKa1C:-NZ5bkZy5p6KOkxs7vcN:b-i5uhpr) ([raw file](https://github.com/starkware-libs/blockifier/blob/90253d2d0d512cbed9046ede5ced09fd41bedaaf/crates/blockifier/src/abi/constants.rs#L40)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM? I wonder if it fits better under `// OS gas costs.`
</blockquote></details>

I has to do with cairo costs, not os costs.

I think it makes sense to put it next to STEP_GAS_COST or maybe next to other builtin costs.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/666)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
