### PR TITLE
Missing L1 gas bounds should return Err, not panic

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1105)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1105)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1105#-NijemmTE-FGSPWyhBBH:-NijemmTE-FGSPWyhBBI:b8zse9s) (no related file):*
Perhaps we should make it more structured, not a mapping of _any_ key to resource?

___
___
*[`crates/blockifier/src/execution/entry_point.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1105#-NijcJnz0E8p8OVwY-G-:-NijcJo--9uKTm3a7DHg:b9ep3yq) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5bdd28f609538f431a1f8a5eb0d643e9b83319c/crates/blockifier/src/execution/entry_point.rs#L170)):*
> ```XML
>                 &mode,
>                 limit_steps_by_resources,
>             )?),
> ```

Please define `max_steps` variable.



_Code quote:_
```XML
            vm_run_resources: RunResources::new(Self::max_steps(
                block_context,
                account_tx_context,
                &mode,
                limit_steps_by_resources,
            )?),
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1105#-NijcPjQ3eilTqi62zN_:-NijcPjQ3eilTqi62zNa:bq9gxkw) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5bdd28f609538f431a1f8a5eb0d643e9b83319c/crates/blockifier/src/execution/entry_point.rs#L181)):*
> ```XML
>         })
>     }
> ```

Why `Result` for non-error-raising methods?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1105)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1105#-NijemmTE-FGSPWyhBBH:-Nijn9UA2QbMVje4uAlL:b-kmtaa1) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps we should make it more structured, not a mapping of _any_ key to resource?
</blockquote></details>

I was under the impression that this is for "forward compatability", i.e. no need to change objects when new resources are added.
Out of scope anyway

___
___
*[`crates/blockifier/src/execution/entry_point.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1105#-NijcPjQ3eilTqi62zN_:-NijnXVwD29v0XiwYUyP:bk49y4v) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5bdd28f609538f431a1f8a5eb0d643e9b83319c/crates/blockifier/src/execution/entry_point.rs#L181)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why `Result` for non-error-raising methods?
</blockquote></details>

`Self::new`'s return type is a Result

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1105)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1105#-NijcPjQ3eilTqi62zN_:-NinPhNW9LONRkWhrSjv:bkujhn4) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5bdd28f609538f431a1f8a5eb0d643e9b83319c/crates/blockifier/src/execution/entry_point.rs#L181)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`Self::new`'s return type is a Result
</blockquote></details>

Is it a trait, a convention?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1105)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1105#-NijcPjQ3eilTqi62zN_:-Nio4JfmDIADpsiM-3i5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5bdd28f609538f431a1f8a5eb0d643e9b83319c/crates/blockifier/src/execution/entry_point.rs#L181)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is it a trait, a convention?
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1105#-:-NioDEED24el5ipwCt3r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
