### PR TITLE
Pass account_tx_context to run_or_revert.

### PR DESCRIPTION
**Pull request by ArniStarkware**
Pass account_tx_context to run_or_revert to prevent duplication of account_tx_context.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/931)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/931)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/931#-NeqmwmT9ly-9xk85pDr:-NeqmwmT9ly-9xk85pDs:b4rgbdd) (no related file):*
What's the motivation? 

___

**Comment by ArniStarkware** [comment]
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What's the motivation?
</blockquote></details>

The motivation is to clean up the code.
It seems like `account_tx_context` is being created twice, which is unnecessary. 

@Yoni-Starkware and I noticed this issue while browsing the code toward the validate-execution_mode-block_syscalls vector.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/931)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/931#-NeqmwmT9ly-9xk85pDr:-Nerp2KI0ZnA0jwJw2hB:br8j18o) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The motivation is to clean up the code.
It seems like `account_tx_context` is being created twice, which is unnecessary. 

@Yoni-Starkware and I noticed this issue while browsing the code toward the validate-execution_mode-block_syscalls vector.
</blockquote></details>

It's created more than twice, unfortunately. 

___

**Comment by ArniStarkware** [comment]
Not up to date.

**Pull request closed without merging**
