### PR TITLE
refactor: changed call_infos input type to avoid clone usage

### PR DESCRIPTION
**Pull request by nimrod-starkware**
clone was [here](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/fee/actual_cost.rs#L217C45-L217C50)

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1637)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1637)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsDffgP2qynLv1ckfJx:-NsDffgP2qynLv1ckfJy:baqwwwh) ([raw file](https://github.com/starkware-libs/blockifier/blob/596c5b6cfa23c8c0bfff37d602042980e8f1b1e6/crates/blockifier/src/fee/actual_cost_test.rs#L159)):*
> ```XML
>     let call_info_1 = create_callinfo(1);
>     let call_info_2 = create_callinfo(2);
>     let call_info_3 = create_callinfo(3);
> ```

i know it's very ugly... i couldnt find another way to do that

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1637)* status: all files reviewed, 9 unresolved discussions (waiting on @giladchase and @nimrod-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsDo7JJ-bMKlQvPjkA1:-NsDo7JJ-bMKlQvPjkA2:b-yk6k9z) ([raw file](https://github.com/starkware-libs/blockifier/blob/596c5b6cfa23c8c0bfff37d602042980e8f1b1e6/crates/blockifier/src/blockifier/transaction_executor.rs#L105)):*
> ```XML
>                     &tx_execution_info.validate_call_info.as_ref(),
>                     &tx_execution_info.execute_call_info.as_ref(),
>                 ];
> ```

[`filter_map` filters `None` values](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter_map), after this change the `call_infos` variable can contain `None`s. Is this intended? What is the type of `call_infos` here?



_Code quote:_
```XML
                let call_infos = &[
                    &tx_execution_info.validate_call_info.as_ref(),
                    &tx_execution_info.execute_call_info.as_ref(),
                ];
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsDoFKz1tEOQeAqZWh3:-NsDoFKz1tEOQeAqZWh4:bacp4o7) ([raw file](https://github.com/starkware-libs/blockifier/blob/596c5b6cfa23c8c0bfff37d602042980e8f1b1e6/crates/blockifier/src/execution/call_info.rs#L52)):*
> ```XML
>             .filter_map(|call_info| {
>                 call_info.map(|info| info.get_sorted_l2_to_l1_payload_lengths())
>             })
> ```

isn't this equivalent....?



_Suggestion:_
```XML
            .filter_map(|call_info| call_info.get_sorted_l2_to_l1_payload_lengths())
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsDoJkY4Ohk3V5cZFLo:-NsDoJkY4Ohk3V5cZFLp:bkiuaq8) ([raw file](https://github.com/starkware-libs/blockifier/blob/596c5b6cfa23c8c0bfff37d602042980e8f1b1e6/crates/blockifier/src/execution/call_info.rs#L56)):*
> ```XML
>         .into_iter()
>         .flatten()
>         .collect();
> ```

are the "outer" parens necessary?



_Suggestion:_
```XML
        let l2_to_l1_payload_lengths: Vec<usize> = call_infos
            .iter()
            .filter_map(|call_info| {
                call_info.map(|info| info.get_sorted_l2_to_l1_payload_lengths())
            })
            .try_collect::<Vec<usize>, Vec<Vec<usize>>, TransactionExecutionError>()?
        .into_iter()
        .flatten()
        .collect();
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsDoTLy6kCiYP3Z9lS5:-NsDoTLy6kCiYP3Z9lS6:by7keen) ([raw file](https://github.com/starkware-libs/blockifier/blob/596c5b6cfa23c8c0bfff37d602042980e8f1b1e6/crates/blockifier/src/fee/actual_cost.rs#L164)):*
> ```XML
>         // TODO(Dafna, 1/6/2024): Compute the DA size and pass it instead of state_changes_count.
>         let da_gas = self.starknet_resources.get_state_changes_cost(use_kzg_da);
>         let non_optional_call_infos = &[&self.validate_call_info, &self.execute_call_info];
> ```

it seems like `for info in non_optional_call_infos` will no longer include inner calls.  
previously the `into_iter` method created a custom iterator over call infos (including nested call infos) by [inspecting inner calls](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/execution/call_info.rs#L244).

Consider simply _collecting_ here and passing the constructed vector to two places



_Code quote:_
```XML
let non_optional_call_infos = &[&self.validate_call_info, &self.execute_call_info];
```
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsDffgP2qynLv1ckfJx:-NsDpYyH1xY08xWHO1gV:b-y91wf1) ([raw file](https://github.com/starkware-libs/blockifier/blob/596c5b6cfa23c8c0bfff37d602042980e8f1b1e6/crates/blockifier/src/fee/actual_cost_test.rs#L159)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

i know it's very ugly... i couldnt find another way to do that
</blockquote></details>

see below... it's possible you'll need to play with where 
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsDp2WJ-zoQs2H7jVTz:-NsDp2WJ-zoQs2H7jVU-:bd73ywn) ([raw file](https://github.com/starkware-libs/blockifier/blob/596c5b6cfa23c8c0bfff37d602042980e8f1b1e6/crates/blockifier/src/fee/actual_cost_test.rs#L161)):*
> ```XML
>     let call_info_3 = create_callinfo(3);
>     let call_infos =
>         &[&Some(&call_info_0), &Some(&call_info_1), &Some(&call_info_2), &Some(&call_info_3)];
> ```

does this work?
why do you need everything as references in `call_infos`?



_Suggestion:_
```XML
    let call_infos = &[0, 1, 2, 3].iter().map(|payload_size| Some(create_callinfo(payload_size))).collect();
```
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsDofzX2ToiLxF-gloc:-NsDofzX2ToiLxF-glod:b-71j928) ([raw file](https://github.com/starkware-libs/blockifier/blob/596c5b6cfa23c8c0bfff37d602042980e8f1b1e6/crates/blockifier/src/fee/actual_cost_test.rs#L396)):*
> ```XML
>         ..Default::default()
>     }
> }
> ```

1. move this function up above the tests
2. drop the `pub`
3. rename parameter



_Suggestion:_
```XML
fn create_callinfo(l2_to_l1_payload_size: usize) -> CallInfo {
    let payload_vec = vec![stark_felt!(0_u16); l2_to_l1_payload_size];
    CallInfo {
        execution: CallExecution {
            l2_to_l1_messages: vec![OrderedL2ToL1Message {
                message: MessageToL1 { payload: L2ToL1Payload(payload_vec), ..Default::default() },
                ..Default::default()
            }],
            ..Default::default()
        },
        ..Default::default()
    }
}
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsDpSaN59RSmAxPK3CX:-NsDpSaN59RSmAxPK3CY:b-yb4qmo) ([raw file](https://github.com/starkware-libs/blockifier/blob/596c5b6cfa23c8c0bfff37d602042980e8f1b1e6/crates/blockifier/src/fee/gas_usage.rs#L29)):*
> ```XML
>         .filter_map(|call_info| {
>             call_info.map(|info| get_events_gas_cost(&info.execution.events, versioned_constants))
>         })
> ```

why `map` twice?



_Suggestion:_
```XML
        .filter_map(|call_info| get_events_gas_cost(&call_info.execution.events, versioned_constants))
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsDpXga9iYNs2WVx6ui:-NsDpXga9iYNs2WVx6uj:b-7ep5ag) ([raw file](https://github.com/starkware-libs/blockifier/blob/596c5b6cfa23c8c0bfff37d602042980e8f1b1e6/crates/blockifier/src/fee/gas_usage_test.rs#L60)):*
> ```XML
>         ..Default::default()
>     };
>     let call_infos = &[&Some(call_info_1), &Some(call_info_2), &Some(call_info_3)];
> ```

not equivalent... `into_iter` iterates over internal call infos as well



_Code quote:_
```XML
let call_infos = &[&Some(call_info_1), &Some(call_info_2), &Some(call_info_3)];
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1637)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @nimrod-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsERs6S75n8Z5y1lpB9:-NsERs6S75n8Z5y1lpBA:baeu226) ([raw file](https://github.com/starkware-libs/blockifier/blob/882780267d201d19646b37f0875b2005b29bd470/crates/blockifier/src/fee/gas_usage.rs#L27)):*
> ```XML
>     let l1_gas: u128 = call_infos
>         .iter()
>         .map(|call_info| (get_events_gas_cost(&call_info.execution.events, versioned_constants)))
> ```

redundant parents?



_Suggestion:_
```XML
get_events_gas_cost(&call_info.execution.events, versioned_constants))
```

**Review by giladchase — CHANGES_REQUESTED** [review]
What's the motivation for this change?
The clone in the existing code you referenced to is a clone of an iterator over the collection which is cheap, and not of the collection itself, unless I'm missing anything here.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-:-NsHdKj8Ae8iUE5mGod2:bkbcqso)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1637#-NsHdFCA45AX_YOwGD4F:-NsHdFCA45AX_YOwGD4G:byabzvu) ([raw file](https://github.com/starkware-libs/blockifier/blob/882780267d201d19646b37f0875b2005b29bd470/crates/blockifier/src/blockifier/transaction_executor.rs#L102)):*
> ```XML
> 
>                 // Count message to L1 resources.
>                 let call_infos: Vec<&CallInfo> =
> ```

Can we keep it an iterator



_Code quote:_
```XML
                let call_infos: Vec<&CallInfo> =
```

**Pull request closed without merging**
