### PR TITLE
refactor: add BouncerConfig to BlockContext

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1956)

### CODE REVIEW

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1956)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbNee23MfoK5nhA3gD:-NzbNee23MfoK5nhA3gE:b-8k9the) ([raw file](https://github.com/starkware-libs/blockifier/blob/529bf3daa4e3fb926ad53724456300ab86f72849/crates/blockifier/src/blockifier/transaction_executor.rs#L58)):*
> ```XML
>     ) -> Self {
>         log::debug!("Initializing Transaction Executor...");
>         let bouncer_config = block_context.bouncer_config.clone();
> ```

I think we should implement `Copy` for `BouncerConfig` if we intend to move it around like this.



_Suggestion:_
```XML
        let bouncer_config = block_context.bouncer_config;
```

**Review by noaov1 — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1956)* status: all files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 292 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbOK0uBFTQ3zD_ymcF:-NzbOK0uBFTQ3zD_ymcG:b-6ol45g) ([raw file](https://github.com/starkware-libs/blockifier/blob/529bf3daa4e3fb926ad53724456300ab86f72849/crates/blockifier/src/blockifier/transaction_executor_test.rs#L292)):*
> ```XML
>         },
>         ..BouncerConfig::default()
>     };
> ```

Consider defining `create_for_bouncer_testing` method in the `BlockContext` impl and use it here and above.



_Code quote:_
```XML
    let bouncer_config = BouncerConfig {
        block_max_capacity: BouncerWeights {
            n_events: max_n_events_in_block,
            ..BouncerWeights::max(false)
        },
        ..BouncerConfig::default()
    };
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbGw-x21Vb4afARihH:-NzbGw-y4vxZQPUBRzwJ:b-bfsj21) ([raw file](https://github.com/starkware-libs/blockifier/blob/529bf3daa4e3fb926ad53724456300ab86f72849/crates/blockifier/src/test_utils/struct_impls.rs#L145)):*
> ```XML
>             chain_info: ChainInfo::create_for_testing(),
>             versioned_constants: VersionedConstants::create_for_testing(),
>             bouncer_config: BouncerConfig::max(),
> ```

?
Same below.



_Suggestion:_
```XML
bouncer_config: BouncerConfig::create_for_testing(),
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1956)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbNee23MfoK5nhA3gD:-NzbPWDHDiP2lGwm2gHE:bwe6chi) ([raw file](https://github.com/starkware-libs/blockifier/blob/529bf3daa4e3fb926ad53724456300ab86f72849/crates/blockifier/src/blockifier/transaction_executor.rs#L58)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think we should implement `Copy` for `BouncerConfig` if we intend to move it around like this.
</blockquote></details>

We don't move it that much, there are two clones for each block. 
I don't like the implicit copy (a struct might get big in the future).
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbGw-x21Vb4afARihH:-NzbQ1uq3jM8O7UFrFrl:b-ktlcc8) ([raw file](https://github.com/starkware-libs/blockifier/blob/529bf3daa4e3fb926ad53724456300ab86f72849/crates/blockifier/src/test_utils/struct_impls.rs#L145)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
Same below.
</blockquote></details>

Maybe I should remove `create_for_testing`. I prefer `max` since I don't want this config to fail unrelated tests.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbNee23MfoK5nhA3gD:-NzbULod2gRxeJZigqDP:bnykrfm) ([raw file](https://github.com/starkware-libs/blockifier/blob/529bf3daa4e3fb926ad53724456300ab86f72849/crates/blockifier/src/blockifier/transaction_executor.rs#L58)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We don't move it that much, there are two clones for each block. 
I don't like the implicit copy (a struct might get big in the future).
</blockquote></details>

Note that `BouncerWeights` does implement `Copy`. It is derived, but we can implement it explicitly to control what gets copied in case the struct gets big. If we use `clone()`, everything gets duplicated in an uncontrolled manner.

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1956)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1956)* status: all files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbGw-x21Vb4afARihH:-NzbXl6T8K23NzKUMETw:bz1ns9y) ([raw file](https://github.com/starkware-libs/blockifier/blob/529bf3daa4e3fb926ad53724456300ab86f72849/crates/blockifier/src/test_utils/struct_impls.rs#L145)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Maybe I should remove `create_for_testing`. I prefer `max` since I don't want this config to fail unrelated tests.
</blockquote></details>

Sounds good. Foe what purpose was it created?
You can change it to have the values you are using in the bouncer testing and use it below.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 173 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbXWni0OZoYqgV9vd6:-NzbXWnj9m_bIhJcJkLh:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/daef3734a7aa2e9935509035a177e30369ec7350/crates/blockifier/src/test_utils/struct_impls.rs#L173)):*
> ```XML
>             },
>             concurrency_mode: false,
>         }
> ```





_Suggestion:_
```XML
        Self {
            bouncer_config: BouncerConfig {
                block_max_capacity: BouncerWeights {
                    n_events: max_n_events_in_block,
                    ..BouncerWeights::max(false)
                },
                ..BouncerConfig::default()
            },
            ..create_for_account_testing(),
        }
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1956)* status: all files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbGw-x21Vb4afARihH:-NzbYjPQC16w7lfhVc__:bubwn54) ([raw file](https://github.com/starkware-libs/blockifier/blob/529bf3daa4e3fb926ad53724456300ab86f72849/crates/blockifier/src/test_utils/struct_impls.rs#L145)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Sounds good. Foe what purpose was it created?
You can change it to have the values you are using in the bouncer testing and use it below.
</blockquote></details>

Or not. It may be confusing.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1956)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbNee23MfoK5nhA3gD:-NzbdSOQ7NiqfyVrjFdG:b-sxz44u) ([raw file](https://github.com/starkware-libs/blockifier/blob/529bf3daa4e3fb926ad53724456300ab86f72849/crates/blockifier/src/blockifier/transaction_executor.rs#L58)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Note that `BouncerWeights` does implement `Copy`. It is derived, but we can implement it explicitly to control what gets copied in case the struct gets big. If we use `clone()`, everything gets duplicated in an uncontrolled manner.
</blockquote></details>

I see. We do arithmetics with the weights (+, -) so it's more convenient. 
I prefer cloning the Config twice and keep it without the Copy.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbGw-x21Vb4afARihH:-NzbdwPD7ii1RO8GLfVo:bcxbxvx) ([raw file](https://github.com/starkware-libs/blockifier/blob/529bf3daa4e3fb926ad53724456300ab86f72849/crates/blockifier/src/test_utils/struct_impls.rs#L145)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Or not. It may be confusing.
</blockquote></details>

Yeah, `max` is good enough
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 173 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1956#-NzbXWni0OZoYqgV9vd6:-NzbdzN41-wGCfumkjSK:bvtk9y9) ([raw file](https://github.com/starkware-libs/blockifier/blob/daef3734a7aa2e9935509035a177e30369ec7350/crates/blockifier/src/test_utils/struct_impls.rs#L173)):*
> ```XML
>             },
>             concurrency_mode: false,
>         }
> ```

Thanks :)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1956)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
