### PR TITLE
fix(native_blockifier): use PyCallType and PyEntryPointType instead o…

### PR DESCRIPTION
**Pull request by OriStarkware**
…f as

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1383)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1383)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1383#-NpAUdbQE3A0tPqhGCMU:-NpAUdbQE3A0tPqhGCMV:b-d77yn) (no related file):*
Looks much better, WDYT?

___
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1383#-NpAUbbfAhD-7YC3HbSZ:-NpAUbbfAhD-7YC3HbS_:bdk7ku9) ([raw file](https://github.com/starkware-libs/blockifier/blob/822ca8bc505a3055d0245a29f1ea506f691969cc/crates/native_blockifier/src/py_transaction_execution_info.rs#L92)):*
> ```XML
> 
> #[pyclass]
> #[derive(Clone)]
> ```

Why is this needed?



_Code quote:_
```XML
#[derive(Clone)]
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1383)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1383#-NpAUdbQE3A0tPqhGCMU:-NpDsMKvAYsxb_ZQOXOk:b-cstnkg) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Looks much better, WDYT?
</blockquote></details>

I agree

___
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1383#-NpAUbbfAhD-7YC3HbSZ:-NpDsbFFB7zWHs8qRZ_o:bt82ize) ([raw file](https://github.com/starkware-libs/blockifier/blob/822ca8bc505a3055d0245a29f1ea506f691969cc/crates/native_blockifier/src/py_transaction_execution_info.rs#L92)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Because PyCallInfo has #[derive(Clone)]

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1383)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1383#-NpAUdbQE3A0tPqhGCMU:-NpE2Pjm0VR5dE2YCjJ_:b615hem) (no related file):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

I agree
</blockquote></details>

Python PR: https://reviewable.io/reviews/starkware-industries/starkware/33628

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1383)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @OriStarkware)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1383#-NpAUbbfAhD-7YC3HbSZ:-NpE2tRpAcRSTJET-MZq:b-h30cx3) ([raw file](https://github.com/starkware-libs/blockifier/blob/822ca8bc505a3055d0245a29f1ea506f691969cc/crates/native_blockifier/src/py_transaction_execution_info.rs#L92)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Because PyCallInfo has #[derive(Clone)]
</blockquote></details>

Your answer is what I asked. Why is cloning needed?

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1383)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1383#-NpAUbbfAhD-7YC3HbSZ:-NpE3Lu-AkgaK0imHcnz:b-ez52lh) ([raw file](https://github.com/starkware-libs/blockifier/blob/822ca8bc505a3055d0245a29f1ea506f691969cc/crates/native_blockifier/src/py_transaction_execution_info.rs#L92)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Your answer is what I asked. Why is cloning needed?
</blockquote></details>

PyCallInfo is the struct the contains both PyCallType and PyEntryPointType.
I assume that PyCallInfo has colne because it is part of PyTransactionExecutionInfo that also requires clone.
I can keep tracking that if it is important, but due to the fact that both PyCallInfo and PyTransactionExecutionInfo are already in the code as is, I am not sure it is necessary.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1383#-:-NpE4UnQ96gpU_8ZvLmr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @OriStarkware)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1383#-NpAUbbfAhD-7YC3HbSZ:-NpE4RvsCw2RBxwrQ1T6:b-5k8020) ([raw file](https://github.com/starkware-libs/blockifier/blob/822ca8bc505a3055d0245a29f1ea506f691969cc/crates/native_blockifier/src/py_transaction_execution_info.rs#L92)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

PyCallInfo is the struct the contains both PyCallType and PyEntryPointType.
I assume that PyCallInfo has colne because it is part of PyTransactionExecutionInfo that also requires clone.
I can keep tracking that if it is important, but due to the fact that both PyCallInfo and PyTransactionExecutionInfo are already in the code as is, I am not sure it is necessary.
</blockquote></details>

Sorry, I misread. :(
Thanks!

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1383)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
