### PR TITLE
Cairo1 read and write syscalls

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/466)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #464** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/464" target="_blank">Graphite</a> 
    * **PR #465** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/465" target="_blank">Graphite</a> 
      * **PR #466** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/466" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/466?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/466)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/466#-NVXy-fS8KrhbHTNvNU6:-NVXy-fTAOdxdZQO0X45:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ae783181d037c7a6a167ff057e6021cee894f8c/crates/blockifier/src/execution/syscalls/hint_processor.rs#L153)):*
> ```XML
>         hint: &StarknetHint,
>     ) -> HintExecutionResult {
>         let StarknetHint::SystemCall{ system } = hint else {
> ```





_Suggestion:_
```XML
syscall
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 312 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/466#-NVXy8d84rwzSo71R3Yc:-NVXy8d84rwzSo71R3Yd:b9lhjcf) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ae783181d037c7a6a167ff057e6021cee894f8c/crates/blockifier/src/execution/syscalls/hint_processor.rs#L312)):*
> ```XML
> }
> 
> fn get_ptr_from_res_operand_unchecked(vm: &mut VirtualMachine, res: &ResOperand) -> Relocatable {
> ```

Seems like code that should appear in `cairo-rs`...
Can you add documentation? Why wasn't this needed until now?



_Code quote:_
```XML
get_ptr_from_res_operand_unchecked
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 591 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/466#-NVXyV7QEkIja5LOWDoX:-NVXyV7QEkIja5LOWDoY:b-a2vtid) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ae783181d037c7a6a167ff057e6021cee894f8c/crates/blockifier/src/execution/syscalls/mod.rs#L591)):*
> ```XML
> // TODO(spapini): Do something with address domain in read and write.
> // StorageRead syscall.
> ```

Let's make sure `address_domain` is `0` in `storage_[read/write]`, as we do [in Python](https://github.com/starkware-industries/starkware/blob/d89aac80ae578d2f2b7d426a94afc5ff49159bad/src/starkware/starknet/core/os/syscall_handler.py#L293).

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/466)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 312 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/466#-NVXy8d84rwzSo71R3Yc:-NVcBQPBE9FN6RKmkenk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ae783181d037c7a6a167ff057e6021cee894f8c/crates/blockifier/src/execution/syscalls/hint_processor.rs#L312)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Seems like code that should appear in `cairo-rs`...
Can you add documentation? Why wasn't this needed until now?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 591 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/466#-NVXyV7QEkIja5LOWDoX:-NVcBxKb6a4maKTbjVp8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ae783181d037c7a6a167ff057e6021cee894f8c/crates/blockifier/src/execution/syscalls/mod.rs#L591)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's make sure `address_domain` is `0` in `storage_[read/write]`, as we do [in Python](https://github.com/starkware-industries/starkware/blob/d89aac80ae578d2f2b7d426a94afc5ff49159bad/src/starkware/starknet/core/os/syscall_handler.py#L293).
</blockquote></details>

Done.

**Review by elintul — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/466#-:-NVcpm-pE6DNhhozT505:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/466).

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/466)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by spapinistarkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/466#-:-NVcvZc1A7wYtYkhbl74:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/466) couldn't merge this PR because it was not satisfying all requirements.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/466#-:-NVd19CM-06gO0K6ztMc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
