### PR TITLE
refactor(native_blockifier): rename l1_gas_amount to gas_weight in bo…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…uncerInfo

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1524)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1524)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1524#-NqhKLwiDRS0p8M2cInY:-NqhKLwiDRS0p8M2cInZ:b-a1zxsi) (no related file):*
Python's PR:
https://reviewable.io/reviews/starkware-industries/starkware/34021

___

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1524)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1524#-NqhTZswEm2QerI92Bwv:-NqhTZswEm2QerI92Bww:bti4rvf) ([raw file](https://github.com/starkware-libs/blockifier/blob/ec45a316e0ae9fe817017e143b035038ffb90af7/crates/native_blockifier/src/py_transaction_execution_info.rs#L233)):*
> ```XML
>     pub n_events: usize,
> }
> ```

Maybe we can only change here, if this is a fast fix and we eventually want to keep `l1_gas_amount`?

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1524)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1524#-:-Nqw-1Qd7L9LTWOoLwHC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Pull request merged**
