### PR TITLE
refactor: added conversion functions f64_into_u128, usize_into_f64, usize_as_u128

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-I5duDV-wSO-O3Joj:-Np-I5duDV-wSO-O3Jok:bdt4hz4) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L19)):*
> ```XML
> 
> /// Returns the max value of two constants, at compile time.
> pub const fn const_max(a: u128, b: u128) -> u128 {
> ```

`assert_eq!` would panic. Return error on failure (change return types to Result)
___
*[`crates/blockifier/src/utils.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-IK5tD5uZWFI8EN_8:-Np-IK5tD5uZWFI8EN_9:b-8t2k28) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L26)):*
> ```XML
> pub fn f64_into_u128(value: f64) -> u128 {
>     let value_u128 = value as u128;
>     assert_eq!(value, value_u128 as f64);
> ```

this will fail if
1. the input value is not an integer
2. floating-point comparison errors
I think we can assume that if the input value is within range `[0, u128::MAX]` then the `as` conversion will succeed.
@giladchase WDYT?
If so, just do:
```
if 0 <= value <= u128::MAX {
    return value as u128
}
Err(F64ToU128Error { from: value })
```



_Code quote:_
```XML
    let value_u128 = value as u128;
    assert_eq!(value, value_u128 as f64);
```
___
*[`crates/blockifier/src/utils.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-J-B70vKtTf0NmQWm:-Np-J-B70vKtTf0NmQWn:b9tb94k) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L33)):*
> ```XML
> pub fn usize_into_f64(value: usize) -> f64 {
>     let value_f64 = value as f64;
>     assert_eq!(value, value_f64 as usize);
> ```

problem (2) above (floating point comparison) still applies here.
@giladchase do you know if and when `usize as f64` can (silently) fail?



_Code quote:_
```XML
    let value_f64 = value as f64;
    assert_eq!(value, value_f64 as usize);
```
___
*[`crates/blockifier/src/utils.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-JeFt47jEjbsVS91k:-Np-JeFt47jEjbsVS91l:b-3d6rtg) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L39)):*
> ```XML
> /// usize as u128
> pub fn usize_as_u128(value: usize) -> u128 {
>     value as u128
> ```

not sure if this third function is needed; `u128` has `TryFrom<usize>`. consider deleting it (or changing the implementation)



_Suggestion:_
```XML
u128::try_from(usize)
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-I5duDV-wSO-O3Joj:-Np-ONloB2-7laTYU0E_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`assert_eq!` would panic. Return error on failure (change return types to Result)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/utils.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-IK5tD5uZWFI8EN_8:-Np-STZL5JYO4dXgEXZa:b-55oh7q) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L26)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

How and where do I define this new error type?
</blockquote></details>

Maybe change the function to do the rounding inside? Which value do you want to compare to 128::MAX? If it's the u128 value, there might have been an error already; in case we compare the f64 value - is there definitely not an issue with u128::MAX as f64?
___
*[`crates/blockifier/src/utils.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-JeFt47jEjbsVS91k:-Np-LgGX-kKg-Qoj2lLN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not sure if this third function is needed; `u128` has `TryFrom<usize>`. consider deleting it (or changing the implementation)
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-IK5tD5uZWFI8EN_8:-Np-XjRJC85Fq_v63zWM:b-lvu1z2) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L26)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Maybe change the function to do the rounding inside? Which value do you want to compare to 128::MAX? If it's the u128 value, there might have been an error already; in case we compare the f64 value - is there definitely not an issue with u128::MAX as f64?
</blockquote></details>

I do not know of anything that can fail in u128->f64 conversion other than precision loss (if f64 has 53 bits mantissa, and your u128 is `x=2^54+1`, then `((x as f64) as u128)` would most likely be `2^54`).
@giladchase ?
___
*[`crates/blockifier/src/utils.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-J-B70vKtTf0NmQWm:-Np-YRnE96zwtZrYMxRq:b3kje4v) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L33)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

problem (2) above (floating point comparison) still applies here.
@giladchase do you know if and when `usize as f64` can (silently) fail?
</blockquote></details>

ah... problem (2) does not apply, integer comparison should be fine.
still question on (if and) when `usize as f64` can fail
___
*[`crates/blockifier/src/utils.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-XbUZD-oVYr5scAll:-Np-XbU_Eg88g3kz1muR:b-ckg55x) ([raw file](https://github.com/starkware-libs/blockifier/blob/efaf0153956e7bda23513e4add55962a6c0c16c8/crates/blockifier/src/utils.rs#L28)):*
> ```XML
> pub fn f64_into_u128(value: f64) -> Result<u128, F64ToU128Error> {
>     let value_u128 = value as u128;
>     if value == value_u128 as f64 {
> ```

still dangerous (item (2)).
Compare in range



_Code quote:_
```XML
value == value_u128 as f64
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-Yf8mBqqy4Ts4gDko:-Np-Yf8mBqqy4Ts4gDkp:b-7jkff5) ([raw file](https://github.com/starkware-libs/blockifier/blob/efaf0153956e7bda23513e4add55962a6c0c16c8/crates/blockifier/src/fee/fee_utils.rs#L54)):*
> ```XML
>         .iter()
>         .map(|(key, resource_val)| {
>             (*resource_val) * vm_resource_usage.0.get(key).cloned().unwrap_or_default() as f64
> ```

why did you make this change? why not use `usize_into_f64`?



_Code quote:_
```XML
(*resource_val) * vm_resource_usage.0.get(key).cloned().unwrap_or_default() as f64
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-YwZ1ASWLk7NIhpM4:-Np-YwZ238A7xLrQefSm:b1ivy0x) ([raw file](https://github.com/starkware-libs/blockifier/blob/efaf0153956e7bda23513e4add55962a6c0c16c8/crates/blockifier/src/transaction/errors.rs#L132)):*
> ```XML
>     #[error("Conversion from {0} to f64 unsuccessful")]
>     ConversionError(usize),
> }
> ```

single enum for numeric errors



_Suggestion:_
```XML
#[derive(Debug, Error)]
pub enum NumericConversionError {
    #[error("Conversion from {0} to u128 unsuccessful")]
    F64ToU128(f64),
    #[error("Conversion from {0} to f64 unsuccessful")]
    UsizeToF64(usize),
}
```

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/fee/fee_utils.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-Yf8mBqqy4Ts4gDko:-Np-cI7wCsfgvi21tdww:b-b2y8y9) ([raw file](https://github.com/starkware-libs/blockifier/blob/efaf0153956e7bda23513e4add55962a6c0c16c8/crates/blockifier/src/fee/fee_utils.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why did you make this change? why not use `usize_into_f64`?
</blockquote></details>

In this specific case, it's inside a closure, so there's a question of what to do in case an error is returned (there's an unwrap_or_default before, should I use unwrap_or_default as well?)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-e7Sy5Eh2PZkUtb9k:-Np-e7Sy5Eh2PZkUtb9l:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/40877c8adf69e21f8148ea8077150f88e057615a/crates/blockifier/src/utils.rs#L29)):*
> ```XML
>     let value_u128 = value as u128;
>     if value >= 0.0 && value < u128::MAX as f64 {
>         Ok(value_u128)
> ```





_Suggestion:_
```XML
    if value >= 0.0 && value < u128::MAX as f64 {
        Ok(value as u128)
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-Yf8mBqqy4Ts4gDko:-Np-eGbG5caCQb-WP-N-:b-jkhe8q) ([raw file](https://github.com/starkware-libs/blockifier/blob/efaf0153956e7bda23513e4add55962a6c0c16c8/crates/blockifier/src/fee/fee_utils.rs#L54)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

In this specific case, it's inside a closure, so there's a question of what to do in case an error is returned (there's an unwrap_or_default before, should I use unwrap_or_default as well?)
</blockquote></details>

if you encounter an error at any point in this iterator, you should stop and return the error. do not unwrap or panic

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @giladchase, and @OriStarkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-J-B70vKtTf0NmQWm:-Np-kZHV9--4ZtcQ5a33:b-z0x16s) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L33)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Would apparently fail in the example you gave above.
</blockquote></details>

ah, right

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-o9At6U5fr8_PZrA-:-Np-o9At6U5fr8_PZrA0:b-2yi50m) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7be1aba7905871963d5e2f3250771bc4096a75d/crates/blockifier/src/transaction/errors.rs#L53)):*
> ```XML
>     TryFromIntError(#[from] std::num::TryFromIntError),
>     #[error(transparent)]
>     NumericConversionError(#[from] NumericConversionError),
> ```

sort variants alphabetically



_Code quote:_
```XML
    #[error(transparent)]
    TryFromIntError(#[from] std::num::TryFromIntError),
    #[error(transparent)]
    NumericConversionError(#[from] NumericConversionError),
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 98 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-oBFS5rj7RUPvjTUM:-Np-oBFS5rj7RUPvjTUN:b-2yi50m) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7be1aba7905871963d5e2f3250771bc4096a75d/crates/blockifier/src/transaction/errors.rs#L98)):*
> ```XML
>     ValidateTransactionError(#[source] EntryPointExecutionError),
>     #[error(transparent)]
>     NumericConversionError(#[from] NumericConversionError),
> ```

sort variants alphabetically



_Code quote:_
```XML
    #[error(transparent)]
    NumericConversionError(#[from] NumericConversionError),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @OriStarkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @OriStarkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 272 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np0-wU3-YfVOTr3RnPm:-Np0-wU3-YfVOTr3RnPn:b8jc2m2) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3768fd6f71025337b67e491c9e4e6c463aa16b5/crates/blockifier/src/execution/entry_point.rs#L272)):*
> ```XML
>         };
> 
>         let tx_upper_bound = (usize_into_f64(tx_gas_upper_bound)? / gas_per_step).floor() as usize;
> ```

add this conversion too while you're at it



_Suggestion:_
```XML
u128_into_usize(usize_into_f64(tx_gas_upper_bound)? / gas_per_step).floor())?;
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np01Ip8Ct414171EiuI:-NpB4i_R3O0QHF1uNtKG:b9hevji) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3768fd6f71025337b67e491c9e4e6c463aa16b5/crates/blockifier/src/utils.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add tests for these (bot hpositive and negative) in `utils_test.rs`
</blockquote></details>

Done. Though perhaps the test for the 2^54+1 example you gave above test could fail in the future? (In case 2^54+1 would be representable by f64 in future Rust versions)
___
*[`crates/blockifier/src/execution/entry_point.rs` line 272 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np0-wU3-YfVOTr3RnPm:-NpAI-ccDJXdcP3W5-3W:b48gqot) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3768fd6f71025337b67e491c9e4e6c463aa16b5/crates/blockifier/src/execution/entry_point.rs#L272)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add this conversion too while you're at it
</blockquote></details>

Done. What about the `expect` and `as` above it? (Changed them, should I change back?)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np01Ip8Ct414171EiuI:-NpBXe9ADzgBPidSwbPm:b-2tspzd) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3768fd6f71025337b67e491c9e4e6c463aa16b5/crates/blockifier/src/utils.rs#L42)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. Though perhaps the test for the 2^54+1 example you gave above test could fail in the future? (In case 2^54+1 would be representable by f64 in future Rust versions)
</blockquote></details>

I think `f64` spec shouldn't change; 64 bits is 64 bits and I doubt mantissa size will change
___
*[`crates/blockifier/src/utils_test.rs` line 36 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-NpBX18n1uUKu7oZOfSu:-NpBX18n1uUKu7oZOfSv:b713mnj) ([raw file](https://github.com/starkware-libs/blockifier/blob/dac0c0a5de252f4b6e02ebe53ba039b8fa5a505e/crates/blockifier/src/utils_test.rs#L36)):*
> ```XML
>     assert!(f64_into_u128(too_big_val).is_err());
>     let loss_conversion_val: usize = (2 << 54) + 1;
>     assert!(usize_into_f64(loss_conversion_val).is_err());
> ```

no need for the variables, pretty clear what is being tested IMO.



_Suggestion:_
```XML
    assert!(f64_into_u128(-10.0).is_err());
    assert!(f64_into_u128(2.0_f64.powi(129)).is_err());
    assert!(usize_into_f64((2_usize << 54) + 1).is_err());
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 272 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np0-wU3-YfVOTr3RnPm:-NpBXSnr9Yfoa0iGbJSQ:b-32o3e2) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3768fd6f71025337b67e491c9e4e6c463aa16b5/crates/blockifier/src/execution/entry_point.rs#L272)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. What about the `expect` and `as` above it? (Changed them, should I change back?)
</blockquote></details>

the `as` you should change (previously, it failed silently).
I think you should leave the `expect` as-is for now, as it previously did *not* fail silently

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np01Ip8Ct414171EiuI:-NpDhhwyDEpZexCWU5n0:by7ibjg) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3768fd6f71025337b67e491c9e4e6c463aa16b5/crates/blockifier/src/utils.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think `f64` spec shouldn't change; 64 bits is 64 bits and I doubt mantissa size will change
</blockquote></details>

I mean, this test will definitely pass (err) for most 54-bit integers, but maybe not necessarily for 2^54+1. Is there a reason this specific value should throw an error?
___
*[`crates/blockifier/src/utils_test.rs` line 36 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-NpBX18n1uUKu7oZOfSu:-NpDhdxr-eXQIwKHPrlq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dac0c0a5de252f4b6e02ebe53ba039b8fa5a505e/crates/blockifier/src/utils_test.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need for the variables, pretty clear what is being tested IMO.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 272 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np0-wU3-YfVOTr3RnPm:-NpDgl--4jWMvP10Ml-i:b-9sj5wv) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3768fd6f71025337b67e491c9e4e6c463aa16b5/crates/blockifier/src/execution/entry_point.rs#L272)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the `as` you should change (previously, it failed silently).
I think you should leave the `expect` as-is for now, as it previously did *not* fail silently
</blockquote></details>

Apparently, it should never fail, but if it ever does, it will panic.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np01Ip8Ct414171EiuI:-NpE6NTPCwx7VR5kykuZ:bnixtx8) ([raw file](https://github.com/starkware-libs/blockifier/blob/f3768fd6f71025337b67e491c9e4e6c463aa16b5/crates/blockifier/src/utils.rs#L42)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I mean, this test will definitely pass (err) for most 54-bit integers, but maybe not necessarily for 2^54+1. Is there a reason this specific value should throw an error?
</blockquote></details>

Yes, f64 has 53 mantissa bits. The 53 most significant bits of the 55-bit integer 2^54+1 are the top 53 bits, so `((2^54 + 1) as f64) as u64)` is 2^54

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @OriStarkware)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1376)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @dorimedini-starkware, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-IK5tD5uZWFI8EN_8:-NpTfeny55LM6uy7m6G_:b-ajc393) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L26)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I do not know of anything that can fail in u128->f64 conversion other than precision loss (if f64 has 53 bits mantissa, and your u128 is `x=2^54+1`, then `((x as f64) as u128)` would most likely be `2^54`).
@giladchase ?
</blockquote></details>

Can of worms.

Without knowing what the exact requirement is for how these numbers should behave when > 2**53 (the max int accureately represented by f64) we might be over-engineering things.

Without any specific accuracy requirements, i think what Aner did is fine
___
*[`crates/blockifier/src/utils.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-Np-J-B70vKtTf0NmQWm:-NpToD6n1jz9HNIiIRTY:b-kv9vgs) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa7505ff1b369fb77fe3c81c3cbe772514e6b17f/crates/blockifier/src/utils.rs#L33)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, right
</blockquote></details>

Not sure i follow, you are comparing usize to f64, would this pass compilation?
And i think up to 2**53 equality is OK? not sure though, really depends on the requirement.
___
*[`crates/blockifier/src/utils.rs` line 26 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1376#-NpThMN02sADMLed_kEl:-NpThMN02sADMLed_kEm:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0dd7fd15758252f1045f6960713cfa6f89838b24/crates/blockifier/src/utils.rs#L26)):*
> ```XML
> 
> /// converts from f64 to u128, checks that the value is in range.
> pub fn f64_into_u128(value: f64) -> Result<u128, NumericConversionError> {
> ```





_Suggestion:_
```XML
try_f64_into_u128
```

**Pull request closed without merging**
