### PR TITLE
refactor(concurrency): use visited_pcs in execute_chunk

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1988)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1988)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-O-a5EXD1Xc7bOj2OTay:-O-a5EXD1Xc7bOj2OTaz:b4wew6j) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcfd47443a6150ef6ff4e92b7bc43a07acd67867/crates/blockifier/src/blockifier/transaction_executor.rs#L219)):*
> ```XML
>         chunk: &[Transaction],
>     ) -> Vec<TransactionExecutorResult<TransactionExecutionInfo>> {
>         use std::collections::HashMap;
> ```

Move up (use `#[cfg(feature = "concurrency")]`)



_Code quote:_
```XML
    use std::collections::HashMap;
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-O-a6qsS6xka8zX5PdBI:-O-a6qsT19AGk6B_fPax:b-jtkxfq) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcfd47443a6150ef6ff4e92b7bc43a07acd67867/crates/blockifier/src/blockifier/transaction_executor.rs#L258)):*
> ```XML
>             tx_execution_results
>                 .push(locked_execution_output.result.map_err(TransactionExecutorError::from));
>             visited_pcs.extend(locked_execution_output.visited_pcs);
> ```

You might be overriding existing keys. You should extend values like this function: 
https://github.com/starkware-libs/blockifier/blob/952373db454baa8d038609b5fbf00273635f1ca1/crates/blockifier/src/state/cached_state.rs#L76

Please share this code - extract it out of the CachedState and call the function `merge_visited_pcs`



_Code quote:_
```XML
visited_pcs.extend(locked_execution_output.visited_pcs);
```

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1988)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-O-a5EXD1Xc7bOj2OTay:-O-eTRn33OmMRx9s16vR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcfd47443a6150ef6ff4e92b7bc43a07acd67867/crates/blockifier/src/blockifier/transaction_executor.rs#L219)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Move up (use `#[cfg(feature = "concurrency")]`)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-O-a6qsS6xka8zX5PdBI:-O-eUxxuEV5KnD3vZ0ht:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcfd47443a6150ef6ff4e92b7bc43a07acd67867/crates/blockifier/src/blockifier/transaction_executor.rs#L258)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You might be overriding existing keys. You should extend values like this function: 
https://github.com/starkware-libs/blockifier/blob/952373db454baa8d038609b5fbf00273635f1ca1/crates/blockifier/src/state/cached_state.rs#L76

Please share this code - extract it out of the CachedState and call the function `merge_visited_pcs`
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1988)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-O-a6qsS6xka8zX5PdBI:-O-gbqae0FpM7ULtN6wP:b5lsiat) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcfd47443a6150ef6ff4e92b7bc43a07acd67867/crates/blockifier/src/blockifier/transaction_executor.rs#L258)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM but please share this piece of code
```
for (class_hash, class_visited_pcs) in locked_execution_output.visited_pcs {
                visited_pcs.entry(class_hash).or_default().extend(class_visited_pcs);
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 261 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-O-jbxd5B6plg1hPn4Ii:-O-jbxd5B6plg1hPn4Ij:b-js59mz) ([raw file](https://github.com/starkware-libs/blockifier/blob/c23e4092845e29442f8dd91ab4e4d26cee301ee2/crates/blockifier/src/blockifier/transaction_executor.rs#L261)):*
> ```XML
>                 visited_pcs.entry(class_hash).or_default().extend(class_visited_pcs);
>             }
>         }
> ```

I like the `fold_while` style better. This use case fits it 100%, but it's a matter of style.
Then, instead of `visited_pcs` use `results_visited_pcs.1` and instead of `tx_execution_results` use `results_visited_pcs.0`.
Non-blocking



_Suggestion:_
```XML
        let results_visited_pcs = worker_executor
            .execution_outputs
            .iter()
            .fold_while((Vec::new(), HashMap::<ClassHash, HashSet<usize>>::new()), |mut results_visited_pcs, execution_output| {
                if results_visited_pcs.0.len() >= n_committed_txs {
                    Done(results_visited_pcs)
                } else {
                    let locked_execution_output = execution_output
                        .lock()
                        .expect("Failed to lock execution output.")
                        .take()
                        .expect("Output must be ready.");
                    results_visited_pcs.0.push(
                        locked_execution_output.result.map_err(TransactionExecutorError::from),
                    );
                    for (class_hash, class_visited_pcs) in locked_execution_output.visited_pcs {
                        results_visited_pcs.1.entry(class_hash).or_default().extend(class_visited_pcs);
                    }        
                    Continue(results_visited_pcs)
                }
            })
            .into_inner();
```

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
AFAIU we use the `visited_pcs` in the `finalize` method of the `TransactionExecutor`.
I think we need tests for that, maybe some flow that involves `execute_chunk` and `finalize`. Maybe more unit tests?
BTW I think we don't have any test for `finalize` of the `TransactionExecutor`.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-:-O-jdTB-43bc35aonoGp:b-n5asjg)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @OriStarkware)

**Review by Yoni-Starkware — COMMENTED** [review]
Correct. The tx executor test is also relatively new. We should add unit tests, not necessarily in this PR.
Currently, it is tested by python's flow tests

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-:-O-k7S2T5jc7PNtXp7az:b-t6eink)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @OriStarkware)

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 261 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-O-jbxd5B6plg1hPn4Ii:-O-k7__41q8DDMeClP2S:bewngfs) ([raw file](https://github.com/starkware-libs/blockifier/blob/c23e4092845e29442f8dd91ab4e4d26cee301ee2/crates/blockifier/src/blockifier/transaction_executor.rs#L261)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I like the `fold_while` style better. This use case fits it 100%, but it's a matter of style.
Then, instead of `visited_pcs` use `results_visited_pcs.1` and instead of `tx_execution_results` use `results_visited_pcs.0`.
Non-blocking
</blockquote></details>

Even better, `let (tx_execution_results, visited_pcs)` instead of `let results_visited_pcs` and then no need to use the `results_visited_pcs.0/1`

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1988)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-O-a6qsS6xka8zX5PdBI:-O-oPaN27SOoW8Xx_yBT:b-8hxrxt) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcfd47443a6150ef6ff4e92b7bc43a07acd67867/crates/blockifier/src/blockifier/transaction_executor.rs#L258)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

LGTM but please share this piece of code
```
for (class_hash, class_visited_pcs) in locked_execution_output.visited_pcs {
                visited_pcs.entry(class_hash).or_default().extend(class_visited_pcs);
```
</blockquote></details>

add_visited_pcs is part of the state trait, so code sharing will not be elegant.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 261 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1988#-O-jbxd5B6plg1hPn4Ii:-O-oPoOB-DGhAKrUFjH3:b-l2nsav) ([raw file](https://github.com/starkware-libs/blockifier/blob/c23e4092845e29442f8dd91ab4e4d26cee301ee2/crates/blockifier/src/blockifier/transaction_executor.rs#L261)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Even better, `let (tx_execution_results, visited_pcs)` instead of `let results_visited_pcs` and then no need to use the `results_visited_pcs.0/1`
</blockquote></details>

I think that it is more readable with the for.

**Review by noaov1 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1988)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
