### PR TITLE
Get gas_consumed from the return values of the execution.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/555)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/555)* status: all files reviewed, 9 unresolved discussions (waiting on @giladchase, @noaov1, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJDWA62iCa4GlMDw0T:-NXJDWA62iCa4GlMDw0U:b6xltf0) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/cairo1_execution.rs#L228)):*
> ```XML
> }
> 
> pub fn finalize_execution(
> ```

It became quite long, let's see if we can break it.



_Code quote:_
```XML
finalize_execution
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJDOYW4H3qfwUTU7_b:-NXJDOYW4H3qfwUTU7_c:b-ko5g4h) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ee12b26bc78c793b3f42ecda776ffd8f64a1dbf/crates/blockifier/src/execution/cairo1_execution.rs#L246)):*
> ```XML
>     // Get retdata.
>     let [failure_flag, retdata_start, retdata_end]: [MaybeRelocatable; 3] =
>         vm.get_return_values(3)?.try_into().expect("Return values must be of size 2.");
> ```

Why not use this method?



_Code quote:_
```XML
get_return_values
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJDBIaBxvcfGYzjS5S:-NXJDBIaBxvcfGYzjS5T:b-trehru) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/cairo1_execution.rs#L247)):*
> ```XML
>     let return_result = vm.get_return_values(5)?;
>     // Corresponds to the Cairo 1.0 enum:
>     // enum PanicResult<Array::<felt>> { Ok: Array::<felt>, Err: Array::<felt>, }.
> ```

Quote the Cairo repo. here; is this how this enum is defined there?



_Code quote:_
```XML
enum PanicResult<Array::<felt>> { Ok: Array::<felt>, Err: Array::<felt>, }.
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJDJ3c0f00oslJkg8-:-NXJDJ3c0f00oslJkg80:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/cairo1_execution.rs#L249)):*
> ```XML
>     // enum PanicResult<Array::<felt>> { Ok: Array::<felt>, Err: Array::<felt>, }.
>     let [failure_flag, retdata_start, retdata_end]: &[MaybeRelocatable; 3] =
>         (&return_result[2..]).try_into().expect("Return values must be of size 2.");
> ```





_Suggestion:_
```XML
size 3
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJDepu2aiSRIB2boXx:-NXJDepu2aiSRIB2boXy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/cairo1_execution.rs#L257)):*
> ```XML
>     } else {
>         return Err(PostExecutionError::MalformedReturnData(
>             "Failure_flag field expected to be either 0 or 1.".to_string(),
> ```





_Suggestion:_
```XML
Failure flag
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJDh6EDJlDc4coo2-S:-NXJDh6EDJlDc4coo2-T:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/cairo1_execution.rs#L271)):*
> ```XML
>     if gas < &0.into() || gas > &syscall_handler.call.initial_gas {
>         return Err(PostExecutionError::MalformedReturnData(format!(
>             "Unexpected remaining gas: {gas}"
> ```





_Suggestion:_
```XML
{gas}."
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJDovGA2nKAkE0gYtH:-NXJDovGA2nKAkE0gYtI:bmml0oq) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/cairo1_execution.rs#L274)):*
> ```XML
>         )));
>     }
>     let gas_consumed = &syscall_handler.call.initial_gas - gas;
> ```

Move down, just before usage.



_Code quote:_
```XML
let gas_consumed = &syscall_handler.call.initial_gas - gas;
```
___
*[`crates/blockifier/src/execution/errors.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJCtoeCGHvdcxnChUM:-NXJCtoeCGHvdcxnChUN:bbqgdai) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/errors.rs#L59)):*
> ```XML
>     #[error(transparent)]
>     VirtualMachineError(#[from] VirtualMachineError),
>     #[error("Malformed return data : {0}.")]
> ```

Give it a name?



_Code quote:_
```XML
{0}
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJCzNC5s814QkCnrm4:-NXJCzNC5s814QkCnrm5:b5oit66) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ee12b26bc78c793b3f42ecda776ffd8f64a1dbf/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L44)):*
> ```XML
>     assert_eq!(
>         entry_point_call.execute_directly(&mut state).unwrap().execution,
>         CallExecution::from_retdata(retdata![stark_felt!(value)])
> ```

Is this c-tor still needed?



_Code quote:_
```XML
from_retdata
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/555)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJDOYW4H3qfwUTU7_b:-NXOjkDN68oxYtIr_JES:b-go8cbo) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ee12b26bc78c793b3f42ecda776ffd8f64a1dbf/crates/blockifier/src/execution/cairo1_execution.rs#L246)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not use this method?
</blockquote></details>

I use it to get all the 5 values. 
___
*[`crates/blockifier/src/execution/errors.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJCtoeCGHvdcxnChUM:-NXLUTpBBKf3laOZNIzp:b6ib1w2) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/errors.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give it a name?
</blockquote></details>

WDYM? 
` MalformedReturnData{msg: String}`
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJCzNC5s814QkCnrm4:-NXLUjzq2_Y-L7l6n_vX:bm43xg6) ([raw file](https://github.com/starkware-libs/blockifier/blob/1ee12b26bc78c793b3f42ecda776ffd8f64a1dbf/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L44)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this c-tor still needed?
</blockquote></details>

Yes. In all the cairo 0 tests.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/555)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @giladchase, @noaov1, and @spapinistarkware)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/555)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJDBIaBxvcfGYzjS5S:-NXP4kQ0EDWAcLWd9Knp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/cairo1_execution.rs#L247)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Quote the Cairo repo. here; is this how this enum is defined there?
</blockquote></details>

Done.

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/555)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @giladchase, @noaov1, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJDBIaBxvcfGYzjS5S:-NXPieavEdkKv4g726f7:b-tlmd56) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/cairo1_execution.rs#L247)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I mislead you. Linking to the repo. is fragile. What I meant is to make sure this is how the enum is defined in Cairo. So revert. :grimacing: 
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 312 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXPiuqa1ZK-lyFBlfFg:-NXPiuqbA1ojiLR3yGwg:b74v1wg) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dc8f9fc30c50538d32037c80c07c644ad5d0c76/crates/blockifier/src/execution/cairo1_execution.rs#L312)):*
> ```XML
>     let gas_consumed = &syscall_handler.call.initial_gas - gas;
> 
>     let call_result = CallResult {
> ```

You can lose this variable, right?



_Code quote:_
```XML
let call_result
```
___
*[`crates/blockifier/src/execution/errors.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXJCtoeCGHvdcxnChUM:-NXPizlfA5M-BOTTOlxs:b-vifvf) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd8b5a3033e86a712517456fd80e234f63a3796d/crates/blockifier/src/execution/errors.rs#L59)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM? 
` MalformedReturnData{msg: String}`
</blockquote></details>

Yes, `error_message` would be good.

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 4 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/555)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase, @noaov1, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 286 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXPkGgS1FxOveIHgLZ6:-NXPxk8Q9JOqxI6E4GHq:b-8am1lp) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dc8f9fc30c50538d32037c80c07c644ad5d0c76/crates/blockifier/src/execution/cairo1_execution.rs#L286)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Better! :)
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 10 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXPxWyV0wUYEzi6mQbw:-NXPxWyWCZtq81hK9j6h:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1cf4e6c362d34dc16313d063aca8f6f2d4ed196/crates/blockifier/src/execution/cairo1_execution.rs#L10)):*
> ```XML
> use starknet_api::stark_felt;
> 
> use super::entry_point::Retdata;
> ```





_Suggestion:_
```XML
crate
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 300 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXPxzmFDbzQEOPoDWh8:-NXPxzmFDbzQEOPoDWh9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1cf4e6c362d34dc16313d063aca8f6f2d4ed196/crates/blockifier/src/execution/cairo1_execution.rs#L300)):*
> ```XML
> 
>     let gas = &return_result[0];
>     let MaybeRelocatable::Int(gas) =  gas
> ```





_Suggestion:_
```XML
= gas
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 304 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXPy47NBecSycz_MHfx:-NXPy47NBecSycz_MHfy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1cf4e6c362d34dc16313d063aca8f6f2d4ed196/crates/blockifier/src/execution/cairo1_execution.rs#L304)):*
> ```XML
>         return
>         Err(PostExecutionError::MalformedReturnData
>             {error_message:"Error extracting return data.".to_string()});
> ```





_Suggestion:_
```XML
        Err(PostExecutionError::MalformedReturnData {
            error_message: "Error extracting return data.".to_string()});
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 306 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXPxuZO1rgNM_lHL-db:-NXPxuZO1rgNM_lHL-dc:bbdlirc) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1cf4e6c362d34dc16313d063aca8f6f2d4ed196/crates/blockifier/src/execution/cairo1_execution.rs#L306)):*
> ```XML
>             {error_message:"Error extracting return data.".to_string()});
>     };
>     if gas < &0.into() || gas > &syscall_handler.call.initial_gas {
> ```

Here too? And throughout this function.



_Code quote:_
```XML
&0.into()
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 313 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXPyB83CBXmmpb3KJz2:-NXPyB83CBXmmpb3KJz3:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c1cf4e6c362d34dc16313d063aca8f6f2d4ed196/crates/blockifier/src/execution/cairo1_execution.rs#L313)):*
> ```XML
>     let gas_consumed = &syscall_handler.call.initial_gas - gas;
> 
>     Ok(CallResult {
> ```





_Suggestion:_
```XML
    
    let gas_consumed = &syscall_handler.call.initial_gas - gas;
    Ok(CallResult {
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/555)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 286 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/555#-NXPkGgS1FxOveIHgLZ6:-NXPype64sIkebrq2CMS:b32vhw) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dc8f9fc30c50538d32037c80c07c644ad5d0c76/crates/blockifier/src/execution/cairo1_execution.rs#L286)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Better! :)
</blockquote></details>

:)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/555#-:-NXQGcfW2vY98bvwh5wP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @spapinistarkware)

**Pull request merged**
