### PR TITLE
chore(fee): update os resources and fix expected

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1440)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1440)* status: 0 of 4 files reviewed, 1 unresolved discussion

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1440#-NpxsAzF1EuLOzG1M2-r):*
Blocking until we get blockifier tests to pass, then add a Python PR and run hodor.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1440)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by giladchase — COMMENTED** [review]
Python: https://reviewable.io/reviews/starkware-industries/starkware/33823

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1440#-:-NpyKGoMCejAxKM7nC0y:bsg5cd7)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1440)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1440)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1440#-:-Npyhb8h3NMIy36NVrCP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1440)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
