### PR TITLE
add bazel support to build blockifier

### PR DESCRIPTION
**Pull request by alon-dotan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @elintul)

___
*[`crates/native_blockifier/native_blockifier/BUILD` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQUFffT53G21bKKMwao:-NQUFffT53G21bKKMwap:bmq4ulz) ([raw file](https://github.com/starkware-libs/blockifier/blob/d415aa3c3eeace55b72eeaa968af3cd59050ff4d/crates/native_blockifier/native_blockifier/BUILD#L10)):*
> ```Starlark
>     name = "copy_libnative_blockifier_so",
>     srcs = ["//:libnative_blockifier.so"],
>     outs = ["libnative_blockifier.so"],
> ```

i think the OUT should be `native_blockifier.so` (without the `lib` prefix)? But maybe you're renaming it on the Python end?



_Code quote:_
```Starlark
libnative_blockifier.so
```
___
*[`crates/native_blockifier/native_blockifier/BUILD` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQUEwSP8bDk-BMxWsSk:-NQUEwSP8bDk-BMxWsSl:bqc5icb) ([raw file](https://github.com/starkware-libs/blockifier/blob/d415aa3c3eeace55b72eeaa968af3cd59050ff4d/crates/native_blockifier/native_blockifier/BUILD#L11)):*
> ```Starlark
>     srcs = ["//:libnative_blockifier.so"],
>     outs = ["libnative_blockifier.so"],
>     cmd = "cp $< $@" # Copy SRC to DST.
> ```

IIUC this differs from `cp $SRCS $OUTS` by enforcing that only on file is passed?
If so, I'm not sure it is worth the readability hit



_Code quote:_
```Starlark
    cmd = "cp $< $@" # Copy SRC to DST.
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @elintul)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQUH80v7E_VcZRN-vAf):*
Blocking until this goes through a review by someone from the bazel team

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware, @elintul, and @giladchase)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQUH80v7E_VcZRN-vAf):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Blocking until this goes through a review by someone from the bazel team
</blockquote></details>

Hello
___
*[`BUILD` line 4 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQVPsDe7Pb4RwiJ8eOQ:-NQVPsDe7Pb4RwiJ8eOR:bexbh2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/26fdf68ff2fe77cc120f459ce6617ab0741a5959/BUILD#L4)):*
> ```Starlark
> exports_files(glob(["**"]))
> 
> genrule(
> ```

Add TODO to use rust rules
___
*[`WORKSPACE` line 28 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQVQza21poo_HQ3Jc5P:-NQVQza31j7KAF6ARDld:bicfh9l) ([raw file](https://github.com/starkware-libs/blockifier/blob/26fdf68ff2fe77cc120f459ce6617ab0741a5959/WORKSPACE#L28)):*
> ```Starlark
> rules_rust_dependencies()
> 
> rust_register_toolchains(
> ```

Is there a way to specify here the rust version we want?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 4 unresolved discussions (waiting on @alon-dotan-starkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQVRcf-3MxEufQvYKai:-NQVRcf0ASvZ1TrWhqcN:b9en539) (no related file):*
Add `bazel build //...` to the CI of this repo (Can be done in a later PR)

___

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @ShahakShama)

___
*[`WORKSPACE` line 28 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQVQza21poo_HQ3Jc5P:-NQaiq6yE09FhmzSGqQv:b-bp29qf) ([raw file](https://github.com/starkware-libs/blockifier/blob/26fdf68ff2fe77cc120f459ce6617ab0741a5959/WORKSPACE#L28)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Is there a way to specify here the rust version we want?
</blockquote></details>

The edition is the version, in that .bazelrc file you can choose stable or nightly

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQVRcf-3MxEufQvYKai:-NQaj-_d6oYYR31wHAf5:b-4y3ryu) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add `bazel build //...` to the CI of this repo (Can be done in a later PR)
</blockquote></details>

next pr

___

**Review by ShahakShama — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339#-:-NQe5tbNALc-d7832jTu:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @elintul, and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @elintul)

___
*[`BUILD` line 4 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQVPsDe7Pb4RwiJ8eOQ:-NQeOhyvBBAtKR1yJhgd:b-x1m4qu) ([raw file](https://github.com/starkware-libs/blockifier/blob/26fdf68ff2fe77cc120f459ce6617ab0741a5959/BUILD#L4)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to use rust rules
</blockquote></details>

@alon-dotan-starkware If i recall you told me that rust rules is not sufficient for this?
We need raze or that other thing, and they were cumbersome?

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @elintul)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @elintul)

___
*[`BUILD` line 4 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQVPsDe7Pb4RwiJ8eOQ:-NQf0IpgAUmk0m-Xju2P:bj4s6c0) ([raw file](https://github.com/starkware-libs/blockifier/blob/26fdf68ff2fe77cc120f459ce6617ab0741a5959/BUILD#L4)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

@alon-dotan-starkware If i recall you told me that rust rules is not sufficient for this?
We need raze or that other thing, and they were cumbersome?
</blockquote></details>

Why is rust rules insufficient?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @elintul)

___
*[`BUILD` line 4 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/339#-NQVPsDe7Pb4RwiJ8eOQ:-NQsLCBmB4zD94IaVtf5:bj90t93) ([raw file](https://github.com/starkware-libs/blockifier/blob/26fdf68ff2fe77cc120f459ce6617ab0741a5959/BUILD#L4)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why is rust rules insufficient?
</blockquote></details>

Nevermind :grimacing:  I thought crate-universe (which is necessary, or raze) was not part of rust_rules

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by alon-dotan-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339#-:-NQtrbkcCbhEoKlI9xk-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by ShahakShama — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339#-:-NQu08wZ8RX_h9Ui-LeG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by alon-dotan-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339#-:-NQuEW4t7BTBP-wz_u18:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by ShahakShama — APPROVED** [review]

**Review by ShahakShama — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339#-:-NQuHrEB9MFGsBP_jveh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/339#-:-NQubZp221_rL0H7zdUR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Pull request merged**
