### PR TITLE
Make `execute_fee_transfer` depend on transaction version.

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/891)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/891)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/891#-Nd_gZJWCtEXMnipPRDc:-Nd_gZJWCtEXMnipPRDd:bydpb56) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad866a6e79dc839e1f39bea74fa6694efc7b90a0/crates/blockifier/src/transaction/account_transaction.rs#L361)):*
> ```XML
> 
>         // TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT address depends on tx version.
>         let storage_address = block_context.fee_token_address(&account_tx_context);
> ```

unit test please (two invokes - of different tx versions - and check the balances of both fee tokens after each invoke)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/891)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/891#-Nd_gZJWCtEXMnipPRDc:-Ndd_FoR4YQxEYOJ6HqN:b-z03vxw) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad866a6e79dc839e1f39bea74fa6694efc7b90a0/crates/blockifier/src/transaction/account_transaction.rs#L361)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

unit test please (two invokes - of different tx versions - and check the balances of both fee tokens after each invoke)
</blockquote></details>

Maybe add a TODO for unit tests, so you can merge this

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/891)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/891#-Nd_gZJWCtEXMnipPRDc:-NegfB5iEdVC-L_dMgqC:b-apz4iv) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad866a6e79dc839e1f39bea74fa6694efc7b90a0/crates/blockifier/src/transaction/account_transaction.rs#L361)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Maybe add a TODO for unit tests, so you can merge this
</blockquote></details>

Added a TODO, in order to test this we'll need a proper InvokeV3 test support, which i'll setup separately rather than here.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/891#-:-NegffYo3INR-NAN7s3_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
