### PR TITLE
Split post-execution test

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1234)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1234)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @zuphitf)

___
*[`crates/blockifier/src/test_utils/fixtures.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1234#-NlO1Fn-11jl22fb71VB:-NlOe3uL1IrfckR4U7_M:b-aldb9z) ([raw file](https://github.com/starkware-libs/blockifier/blob/419d27825b1278224ba6b522d1ad7ba8945c9378/crates/blockifier/src/test_utils/fixtures.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

You just worked hard on splitting test utils... let's keep thing compartmentalized, no?
We may want more fixtures in the future (ahem ahem price abstraction ahem)
</blockquote></details>

Ya but that was the main test_utils which was already bloated, `transaction/test_utils.rs` is in good shape so far.

In general i'm hesitant about adding support for possible future optimizations, unless it is in a subsequent commit.
I'm more worried about a "oh there's a fixtures module lets put all fixtures there" situation, which will make it bloat real quick.

Eitherway, unblocking and removing myself from review.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1234)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @TzahiTaub, and @zuphitf)

___
*[`crates/blockifier/Cargo.toml` line 37 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1234#-NlSIlA048-urZKOwrkq:-NlSIlA048-urZKOwrkr:bg7igkv) ([raw file](https://github.com/starkware-libs/blockifier/blob/419d27825b1278224ba6b522d1ad7ba8945c9378/crates/blockifier/Cargo.toml#L37)):*
> ```TOML
> num-integer.workspace = true
> num-traits.workspace = true
> rstest = { workspace = true, optional = true }
> ```

:lgtm: 



_Code quote:_
```TOML
[features]
testing = ["rstest"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

num-bigint.workspace = true
num-integer.workspace = true
num-traits.workspace = true
rstest = { workspace = true, optional = true }
```

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @zuphitf)

**Review by dorimedini-starkware — COMMENTED** [review]
> Dismissed @giladchase from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1234)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub and @zuphitf)

**Pull request merged**
