### PR TITLE
test: add version related scenarios to tests using faulty account

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1797)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1797?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1797** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1797?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1796** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1796?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1794** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1794?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ArniStarkware** [comment]
+reviewer:@MohammadNassar1

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1797)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 1007 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1797#-NvklTRcE3_rzAoe5cYq:-NvklTRdEKTifCofxjAl:b-6b41d3) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0f4a07c996add75546344d486445d699b7ef779/crates/blockifier/src/execution/entry_point_test.rs#L1007)):*
> ```XML
> }
> 
> // TODO(Arni, 1/5/2024): Cover version 0 declare transaction.
> ```

What about invoke  version 0?



_Code quote:_
```XML
Cover version 0 declare transaction.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1797)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 1007 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1797#-NvklTRcE3_rzAoe5cYq:-Nvl1tbe5SWQSW-wzYjV:b-vxdyjm) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0f4a07c996add75546344d486445d699b7ef779/crates/blockifier/src/execution/entry_point_test.rs#L1007)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What about invoke  version 0?
</blockquote></details>

Added a TODO.

It is somewhat more complicated. Let us cover it in another PR (if at all).
The issue is - the `execute` does not return an error where it does for version 1 txs.

**Review by MohammadNassar1 — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1797#-:-Nvl8EJXBGKGylA3GIIz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1797#-:-NvliV0M0RdNTdNVTFkV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
