### PR TITLE
Add structs for secp256k1 ec operations.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/694)

### CODE REVIEW

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/694)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5vmPKA3Am6a_p8GDk:-NZ5vmPKA3Am6a_p8GDl:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L24)):*
> ```XML
> }
> 
> // secp256k1Add
> ```





_Suggestion:_
```XML
// Secp256k1Add syscall.
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5wFFd0hEBSwPUk6V0:-NZ5wFFd0hEBSwPUk6V1:bs17stn) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L29)):*
> ```XML
> pub struct Secp256k1AddRequest {
>     pub ec_point_id0: Felt252,
>     pub ec_point_id1: Felt252,
> ```

Consider `rhs_id`, `lhs_id`, if compatible here.



_Code quote:_
```XML
    pub ec_point_id0: Felt252,
    pub ec_point_id1: Felt252,
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5vjVTAhP90v7rQ8fs:-NZ5vjVUDYEeQavn7SNd:b-ltu7df) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L32)):*
> ```XML
> }
> 
> // Secp256k1GetXy syscall.
> ```

Move above `Secp256k1AddReques`.



_Code quote:_
```XML
// Secp256k1GetXy syscall.
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5wM0t4PwIDG4-x_r1:-NZ5wM0t4PwIDG4-x_r2:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L135)):*
> ```XML
> 
> // secp256k1Mul syscall.
> #[derive(Debug, Eq, PartialEq)]
> ```





_Suggestion:_
```XML
// Secp256k1Mul syscall.

#[derive(Debug, Eq, PartialEq)]
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5wn8S7SplDEhv6kMK:-NZ5wn8S7SplDEhv6kML:b26t5sa) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L138)):*
> ```XML
> pub struct Secp256k1MulRequest {
>     pub ec_point_id: Felt252,
>     m: BigUint,
> ```

Why isn't this `pub`lic? If no need, then please fix other structs too.



_Suggestion:_
```XML
multiplier: BigUint,
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5wXoc17ZoNr_Tc5tW:-NZ5wXoc17ZoNr_Tc5tX:bns9obi) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L149)):*
> ```XML
> }
> 
> // The response for Secp256k1 add and mul operations.
> ```

No need.



_Code quote:_
```XML
// The response for Secp256k1 add and mul operations.
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5w_9tCSLUiH15IrbL:-NZ5w_9tCSLUiH15IrbM:b53n12g) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L151)):*
> ```XML
> // The response for Secp256k1 add and mul operations.
> #[derive(Debug, Eq, PartialEq)]
> pub struct Secp256k1OpRespone {
> ```

Move under `EcPointCoordinates`, since those are both common structs.



_Code quote:_
```XML
pub struct Secp256k1OpRespone
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5vjVTAhP90v7rQ8fs:-NZ5xz819kHd6UAr5pp_:bej2ju8) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move above `Secp256k1AddReques`.
</blockquote></details>

didn't you want the syscall to be alphabetized?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/694)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5wFFd0hEBSwPUk6V0:-NZ5yJO3-O6R8CYpqe_U:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L29)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider `rhs_id`, `lhs_id`, if compatible here.
</blockquote></details>

done.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5wM0t4PwIDG4-x_r1:-NZ5xx8P-47ZoqrzjVvm:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L135)):*
> ```XML
> 
> // secp256k1Mul syscall.
> #[derive(Debug, Eq, PartialEq)]
> ```

done.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5wn8S7SplDEhv6kMK:-NZ5xvqf6hGrdC9jxh0L:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L138)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why isn't this `pub`lic? If no need, then please fix other structs too.
</blockquote></details>

done.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5wXoc17ZoNr_Tc5tW:-NZ5xpwFC3FihbUyRu3V:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L149)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No need.
</blockquote></details>

done
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5w_9tCSLUiH15IrbL:-NZ5xn_CE-ERX9GuoueX:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L151)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move under `EcPointCoordinates`, since those are both common structs.
</blockquote></details>

done

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/694)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5vjVTAhP90v7rQ8fs:-NZ6--rZ32pSJnZUzgV-:b-74lm67) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L32)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

didn't you want the syscall to be alphabetized?
</blockquote></details>

Yes, sorry, got confused. :(
Revert?
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ6-7U44kc4luy0Y_2X:-NZ6-7U44kc4luy0Y_2Y:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/37858062f110a4ef2742c325211c7bc5ea58374a/crates/blockifier/src/execution/syscalls/secp.rs#L74)):*
> ```XML
> 
> // Secp256k1Mul syscall.
> #[derive(Debug, Eq, PartialEq)]
> ```

Add a blank line above.



_Code quote:_
```XML
#[derive(Debug, Eq, PartialEq)]
```
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ6-ByaBZGjFN64rGY0:-NZ6-ByaBZGjFN64rGY1:by6kf5v) ([raw file](https://github.com/starkware-libs/blockifier/blob/37858062f110a4ef2742c325211c7bc5ea58374a/crates/blockifier/src/execution/syscalls/secp.rs#L87)):*
> ```XML
>     }
> }
> ```

Do you want to add `pub type Secp256k1MulResponse = Secp256k1OpRespone;` and for `Secp256k1AddResponse` too?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/694)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ5vjVTAhP90v7rQ8fs:-NZ5yROq9fDKzIpRtzhz:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/4864960d2fde99668eb7059f4eb937db531cfcaf/crates/blockifier/src/execution/syscalls/secp.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yes, sorry, got confused. :(
Revert?
</blockquote></details>

done.
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ6-7U44kc4luy0Y_2X:-NZ60Su35iqBEnQOENDt:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/37858062f110a4ef2742c325211c7bc5ea58374a/crates/blockifier/src/execution/syscalls/secp.rs#L74)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a blank line above.
</blockquote></details>

done
___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ6-ByaBZGjFN64rGY0:-NZ60QEeATMmQ5tiGteM:b-49ib6c) ([raw file](https://github.com/starkware-libs/blockifier/blob/37858062f110a4ef2742c325211c7bc5ea58374a/crates/blockifier/src/execution/syscalls/secp.rs#L87)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you want to add `pub type Secp256k1MulResponse = Secp256k1OpRespone;` and for `Secp256k1AddResponse` too?
</blockquote></details>

The compiler complains that they are unused but I can add them in future PRs

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/694#-:-NZ61dSUEVoUjjk4fuOw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/secp.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/694#-NZ6-ByaBZGjFN64rGY0:-NZ61cCz8C5CoBiGJrbM:br1vbjs) ([raw file](https://github.com/starkware-libs/blockifier/blob/37858062f110a4ef2742c325211c7bc5ea58374a/crates/blockifier/src/execution/syscalls/secp.rs#L87)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The compiler complains that they are unused but I can add them in future PRs
</blockquote></details>

Okay, cool.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/694)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
