### PR TITLE
Add cairo1 deploy syscall.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/502)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/502#-:-NVyf3uw9fcFASL7oF4A:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/502)* status: all files reviewed, 6 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 157 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/502#-NVyr7DIBS7AKqvIHwDg:-NVyr7DIBS7AKqvIHwDh:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a98674c0aaba247f419421729e1bc15d70f816/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L157)):*
> ```Cairo
>         ).unwrap_syscall();
> 
>     }
> ```





_Suggestion:_
```Cairo
        ).unwrap_syscall();
    }
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 433 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/502#-NVypzBi00RZtW_Evfix:-NVypzBi00RZtW_Evfiy:b-ayknxq) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a98674c0aaba247f419421729e1bc15d70f816/crates/blockifier/src/execution/syscalls/hint_processor.rs#L433)):*
> ```XML
> 
> pub fn create_retdata_segment(
>     raw_retdata: &[StarkFelt],
> ```

Move to be last, less chance `mut`able arguments to the function will change going forward.



_Code quote:_
```XML
raw_retdata: &[StarkFelt],
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 486 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/502#-NVyqeat80LIN9Ae83x4:-NVyqeat80LIN9Ae83x5:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a98674c0aaba247f419421729e1bc15d70f816/crates/blockifier/src/execution/syscalls/hint_processor.rs#L486)):*
> ```XML
> }
> 
> pub fn write_retdata_segment(
> ```





_Suggestion:_
```XML
write_segment
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 194 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/502#-NVyrLo37nYEHCIYYJwl:-NVyrLo37nYEHCIYYJwm:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a98674c0aaba247f419421729e1bc15d70f816/crates/blockifier/src/execution/syscalls/mod.rs#L194)):*
> ```XML
> pub struct DeployResponse {
>     pub contract_address: ContractAddress,
>     pub segment: ReadOnlySegment,
> ```





_Suggestion:_
```XML
constructor_retdata
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 232 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/502#-NVyrQeq4MSkBh2epq20:-NVyrQeq4MSkBh2epq21:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a98674c0aaba247f419421729e1bc15d70f816/crates/blockifier/src/execution/syscalls/mod.rs#L232)):*
> ```XML
>     )?;
> 
>     let retdata_segment =
> ```





_Suggestion:_
```XML
constructor_retdata
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 366 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/502#-NVyqphP0-gMxLYPKN7I:-NVyqphP0-gMxLYPKN7J:bhc65i7) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a98674c0aaba247f419421729e1bc15d70f816/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L366)):*
> ```XML
>         stark_felt!(3_u8), // Calldata: arg1.
>         stark_felt!(3_u8), // Calldata: arg2.
>         stark_felt!(0_u8) // deploy_from_zero.
> ```

Fix indentation of comments? For all such comments?



_Code quote:_
```XML
        stark_felt!(TEST_CLASS_HASH), // Class hash.
        ContractAddressSalt::default().0, // Contract_address_salt.
        stark_felt!(2_u8), // Calldata length.
        stark_felt!(3_u8), // Calldata: arg1.
        stark_felt!(3_u8), // Calldata: arg2.
        stark_felt!(0_u8) // deploy_from_zero.
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/502)* status: all files reviewed, 7 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 492 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/502#-NVyroF19VxaYLNhRfRA:-NVyroF19VxaYLNhRfRB:b-gzy5kc) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a98674c0aaba247f419421729e1bc15d70f816/crates/blockifier/src/execution/syscalls/hint_processor.rs#L492)):*
> ```XML
> ) -> SyscallResult<()> {
>     write_maybe_relocatable(vm, ptr, segment.start_ptr)?;
>     write_maybe_relocatable(vm, ptr, (segment.start_ptr + segment.length)?)?;
> ```

Give this a name: `segment_end_ptr`.



_Code quote:_
```XML
(segment.start_ptr + segment.length)
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/502)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 486 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/502#-NVyqeat80LIN9Ae83x4:-NVzwi9t8U4kGOG0q4CF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d3a98674c0aaba247f419421729e1bc15d70f816/crates/blockifier/src/execution/syscalls/hint_processor.rs#L486)):*
> ```XML
> }
> 
> pub fn write_retdata_segment(
> ```

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/502#-:-NW14NXI1dvIvG7jKecg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
