### PR TITLE
feat(concurrency): move versioned_state_for_testing to test_utils

### PR DESCRIPTION
**Pull request by meship-starkware**
…st utils

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1835)

### CODE REVIEW

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1835)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-NwjH7BU4NkgzOjEYQY4:-NwjH7BVCneCchgzdUDB:b-b1psck) ([raw file](https://github.com/starkware-libs/blockifier/blob/cde5d2b2077eed6a32db3687b6efe847bfe3b0c0/crates/blockifier/src/concurrency/test_utils.rs#L48)):*
> ```XML
>         CachedState::from(DictStateReader { address_to_class_hash, ..Default::default() });
>     Arc::new(Mutex::new(VersionedState::new(cached_state)))
> }
> ```

copying my comments from @MohammadNassar1 PR:

The point is that the `DictStateReader` has 5 fields (and not only the `address_to_class_hash`) so this generalization will not end here. I suggest creating a macro as a test util to allow the creation of `VersionedState` with different state readers or a macro as a test util for the `DictStateReader`.  
WDYT? (It can be added as a TODO here) I feel that the current form of this util lacks some indirections.

To save code duplication in this file, you can add a fixture that does what the comment below suggests:

```
    let address_to_class_hash = HashMap::from(contract_address!("0x1"), ClassHash(stark_felt!(27_u8)));
    let initial_state = CachedState::from(....);
    let versioned_state = versioned_state_for_testing(initial_state);
```

If you need you can use a fixture in your case too.



_Suggestion:_
```XML
pub fn versioned_state_for_testing(
    initial_state: impl StateReader,
) -> Arc<Mutex<VersionedState<CachedState<DictStateReader>>>> {
    let mut address_to_class_hash = HashMap::new();
    address_to_class_hash.insert(contract_address, class_hash);

    Arc::new(Mutex::new(VersionedState::new(initial_state)))
}
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/concurrency/test_utils.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-Nwn7VOB42YdhF1hMA7w:-Nwn7VOB42YdhF1hMA7x:bjy51u4) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c5b3529bb988888e989bcca993f2c2a84138753/crates/blockifier/src/concurrency/test_utils.rs#L51)):*
> ```XML
>         ..DictStateReader::default()
>     }
> }
> ```

This should be placed (if necessary) in the test file itself.



_Code quote:_
```XML
#[fixture]
pub fn initial_state_for_testing() -> DictStateReader {
    DictStateReader {
        address_to_class_hash: HashMap::from([(
            contract_address!("0x1"),
            ClassHash(stark_felt!(27_u8)),
        )]),
        ..DictStateReader::default()
    }
}
```

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1835)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1835)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-Nwn7VOB42YdhF1hMA7w:-NwnKFfQ9KyySP3j5nio:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c5b3529bb988888e989bcca993f2c2a84138753/crates/blockifier/src/concurrency/test_utils.rs#L51)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

This should be placed (if necessary) in the test file itself.
</blockquote></details>

Done.

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1835)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-NwnSMwTCPX9j6ph_yRv:-NwnSMwTCPX9j6ph_yRw:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2ad70dbc9956947bf4b8745f494a4119c9d2c31/crates/blockifier/src/concurrency/test_utils.rs#L35)):*
> ```XML
> }
> 
> // TODO: consider making this a macro.
> ```





_Suggestion:_
```XML
// TODO(meshi, 01/06/2024): Consider making this a macro.
```
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-NwnSCM-7H2EHYXZaGj7:-NwnSCM-7H2EHYXZaGj8:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2ad70dbc9956947bf4b8745f494a4119c9d2c31/crates/blockifier/src/concurrency/test_utils.rs#L37)):*
> ```XML
> // TODO: consider making this a macro.
> pub fn versioned_state_for_testing(
>     initial_state: impl StateReader,
> ```





_Suggestion:_
```XML
block_state: impl StateReader,
```
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-NwnSEi12ga-ArDIQGLx:-NwnSEi12ga-ArDIQGLy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2ad70dbc9956947bf4b8745f494a4119c9d2c31/crates/blockifier/src/concurrency/test_utils.rs#L39)):*
> ```XML
>     initial_state: impl StateReader,
> ) -> Arc<Mutex<VersionedState<CachedState<impl StateReader>>>> {
>     Arc::new(Mutex::new(VersionedState::new(CachedState::new(initial_state))))
> ```





_Suggestion:_
```XML
Arc::new(Mutex::new(VersionedState::new(block_state)))
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1835)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-NwnSMwTCPX9j6ph_yRv:-NwnTtX72aCxGhbqQ9OY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2ad70dbc9956947bf4b8745f494a4119c9d2c31/crates/blockifier/src/concurrency/test_utils.rs#L35)):*
> ```XML
> }
> 
> // TODO: consider making this a macro.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-NwnSCM-7H2EHYXZaGj7:-NwnTuAV1Y2nIgNfAXEk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2ad70dbc9956947bf4b8745f494a4119c9d2c31/crates/blockifier/src/concurrency/test_utils.rs#L37)):*
> ```XML
> // TODO: consider making this a macro.
> pub fn versioned_state_for_testing(
>     initial_state: impl StateReader,
> ```

Done.
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-NwnSEi12ga-ArDIQGLx:-NwnTuN83_rq2hOYz_1R:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2ad70dbc9956947bf4b8745f494a4119c9d2c31/crates/blockifier/src/concurrency/test_utils.rs#L39)):*
> ```XML
>     initial_state: impl StateReader,
> ) -> Arc<Mutex<VersionedState<CachedState<impl StateReader>>>> {
>     Arc::new(Mutex::new(VersionedState::new(CachedState::new(initial_state))))
> ```

Done.

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1835)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by barak-b-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-:-Nwnqdx1BQ3n1KdL3RBz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1835#-:-NwnsF2n3XXZ_nnRiku1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
