### PR TITLE
feat(execution): pass correct bouncer info

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1577)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1577)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1577#-NrG3m8n-8ThOvyKC64V:-NrG3m8n-8ThOvyKC64W:b1masp) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/34116)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1577)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1577#-NrG3m8n-8ThOvyKC64V:-NrH2v8bBSGtikwM3eJ3:b-hf5zo5) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[python side](https://reviewable.io/reviews/starkware-industries/starkware/34116)
</blockquote></details>

... no, actually the above is the python side of [the PR beneath this one](https://reviewable.io/reviews/starkware-libs/blockifier/1576)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1577)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1577#-NrG3m8n-8ThOvyKC64V:-NrH3taeA4C-duxWHs8b:b-fmb5zc) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... no, actually the above is the python side of [the PR beneath this one](https://reviewable.io/reviews/starkware-libs/blockifier/1576)
</blockquote></details>

[this](https://reviewable.io/reviews/starkware-industries/starkware/34122) is the python side for the current PR

___

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1577#-:-NrpJusnDzy8HuTdiyxg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Pull request merged**
