### PR TITLE
Verify the executors storage is aligned with the main storage.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-mC96kGXsgfaaWlL:-NPr-mC96kGXsgfaaWlM:b-8epqjg) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L52)):*
> ```XML
>     (
>         NativeBlockifierValidationError,
>         NativeBlockifierValidationError,
> ```

What does the second argument mean?



_Code quote:_
```XML
NativeBlockifierValidationError,
```
___
*[`crates/native_blockifier/src/errors.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-uj95Ylp_wsoxd-D:-NPr-uj95Ylp_wsoxd-E:b-716tig) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L63)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum NativeBlockifierValidationError {
> ```

Do you think a new enum is needed? Why not add to `NativeBlockifierError` in a flat way?



_Code quote:_
```XML
pub enum NativeBlockifierValidationError
```
___
*[`crates/native_blockifier/src/errors.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-ORT1aaMAQ6HNv10:-NPr-ORT1aaMAQ6HNv11:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L66)):*
> ```XML
>     #[error(
>         "Blockifier storage is not aligned with the main storage; latest block in blockifier: \
>          {blockifier_latest_block}, latest block in main storage: {actual_latest_block}."
> ```





_Suggestion:_
```XML
    #[error(
        "Blockifier storage is not aligned with the main storage; \
        latest block ID in blockifier: {blockifier_latest_block_id}, \
        latest block in main storage: {actual_latest_block_id}."
    )]
    StorageUnaligned { 
        blockifier_latest_block_id: BigInt, actual_latest_block_id: BigInt 
    },
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPqxUPA6GoXZkUwLVOS:-NPqxUPA6GoXZkUwLVOT:b-73pum5) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/py_transaction.rs#L189)):*
> ```XML
>         storage_path: String,
>         latest_block_id: BigInt,
>     ) -> NativeBlockifierResult<Self> {
> ```

This function became too long.
Please refactor it: `validate_storage_aligned`, `impl TryFrom<PyBlockInfo> for BlockInfo` (for now `build_block_context`, since it requires defining `PyBlockInfo`), `build_tx_executor`.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPqzwrgEIv10lZ7ObMn:-NPqzwrgEIv10lZ7ObMo:ba9tea5) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/py_transaction.rs#L194)):*
> ```XML
>         // Verify storage is aligned.
>         let block_number = storage.get_state_marker()? - 1;
>         let block_hash = storage.get_block_hash(block_number)?;
> ```

Refrain from using "hash", since it's a unique ID and not a hash.



_Suggestion:_
```XML
let block_id
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @giladchase)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-mC96kGXsgfaaWlL:-NPr2CqmCBb5YKKmx5DP:b-y1fxr9) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L52)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does the second argument mean?
</blockquote></details>

The first is the name of the variant, and the second is the name of the error from which it converts. Many times it's the same name. e.g:
```
#[error(transparent)]
    EntryPointExecutionError(#[from] EntryPointExecutionError)
```
___
*[`crates/native_blockifier/src/errors.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-uj95Ylp_wsoxd-D:-NPr0H2Z3WviIBHtz39g:b-wfcm6f) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L63)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you think a new enum is needed? Why not add to `NativeBlockifierError` in a flat way?
</blockquote></details>

I don't think it's needed, I did it only so it works with the macro that created the pyerrors.
___
*[`crates/native_blockifier/src/errors.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-ORT1aaMAQ6HNv10:-NPr10xc6EWIO38HDM7z:b-caihdc) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L66)):*
> ```XML
>     #[error(
>         "Blockifier storage is not aligned with the main storage; latest block in blockifier: \
>          {blockifier_latest_block}, latest block in main storage: {actual_latest_block}."
> ```

Done. Can't split into 3 lines if it fits in 2 (because of the formatter).
___
*[`crates/native_blockifier/src/py_transaction.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPqxUPA6GoXZkUwLVOS:-NPr8zRDBAvdxGsuLgw3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/py_transaction.rs#L189)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This function became too long.
Please refactor it: `validate_storage_aligned`, `impl TryFrom<PyBlockInfo> for BlockInfo` (for now `build_block_context`, since it requires defining `PyBlockInfo`), `build_tx_executor`.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPqzwrgEIv10lZ7ObMn:-NPr1Jvd6v9jqjrVPGxU:b-ybx963) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/py_transaction.rs#L194)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Refrain from using "hash", since it's a unique ID and not a hash.
</blockquote></details>

Done. Should I change the method name too?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPqxUPA6GoXZkUwLVOS:-NPrB7aGDA1pNK3iO5FU:b-hffk5t) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/py_transaction.rs#L189)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Re `build_tx_executor`, 
___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPqzwrgEIv10lZ7ObMn:-NPrBxMU5xG4cXJXcjUA:b-yrockj) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/py_transaction.rs#L194)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done. Should I change the method name too?
</blockquote></details>

Yes, and a short docstring explaining we use a different unique identifier, instead of the hash.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 206 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPrBPZa4U4ylVz38Flc:-NPrBPZa4U4ylVz38Fld:bttxgmy) ([raw file](https://github.com/starkware-libs/blockifier/blob/32fc4cd47b7e0affb82c4081f5240bf5df3a651f/crates/native_blockifier/src/py_transaction.rs#L206)):*
> ```XML
> pub fn build_tx_executor(
>     block_context: BlockContext,
>     storage: Storage,
> ```

Pass only the reader, so we can't use the writer here.



_Code quote:_
```XML
storage: Storage,
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 224 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPrBF-q8gTx0uEcQnFO:-NPrBF-q8gTx0uEcQnFP:bpvxyan) ([raw file](https://github.com/starkware-libs/blockifier/blob/32fc4cd47b7e0affb82c4081f5240bf5df3a651f/crates/native_blockifier/src/py_transaction.rs#L224)):*
> ```XML
>     }
> 
>     let block_number = block_context.block_number;
> ```

Pass directly?



_Code quote:_
```XML
let block_number = block_context.block_number;
```
___
*[`crates/native_blockifier/src/py_utils.rs` line 81 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPrBcs241i6Kg6QrYaP:-NPrBcs241i6Kg6QrYaQ:bsooqr3) ([raw file](https://github.com/starkware-libs/blockifier/blob/32fc4cd47b7e0affb82c4081f5240bf5df3a651f/crates/native_blockifier/src/py_utils.rs#L81)):*
> ```XML
> }
> 
> pub fn validate_storage_aligned(
> ```

Perhaps a method of `Storage`?



_Code quote:_
```XML
validate_storage_aligned
```
___
*[`crates/native_blockifier/src/py_utils.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPrBfvYCB3utHUeBtiZ:-NPrBfvYCB3utHUeBti_:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/32fc4cd47b7e0affb82c4081f5240bf5df3a651f/crates/native_blockifier/src/py_utils.rs#L91)):*
> ```XML
>         None => BigInt::from(-1),
>     };
>     if block_id != latest_block_id {
> ```

Add a blank line above.



_Code quote:_
```XML
if block_id != latest_block_id {
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPqxUPA6GoXZkUwLVOS:-NPrFEJj0525-kKDQ1oJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/py_transaction.rs#L189)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Re `build_tx_executor`, 
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPqzwrgEIv10lZ7ObMn:-NPrCUY73wrRzJhFBDMS:b-pw2kx3) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/py_transaction.rs#L194)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yes, and a short docstring explaining we use a different unique identifier, instead of the hash.
</blockquote></details>

NP. We'll have to bump a version and fix it in python, also.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 206 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPrBPZa4U4ylVz38Flc:-NPrDht_7bNKauoFbg2f:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/32fc4cd47b7e0affb82c4081f5240bf5df3a651f/crates/native_blockifier/src/py_transaction.rs#L206)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Pass only the reader, so we can't use the writer here.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 224 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPrBF-q8gTx0uEcQnFO:-NPrDpk61deoKpUNk9Se:bz97cpr) ([raw file](https://github.com/starkware-libs/blockifier/blob/32fc4cd47b7e0affb82c4081f5240bf5df3a651f/crates/native_blockifier/src/py_transaction.rs#L224)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Pass directly?
</blockquote></details>

That's a problem because `block_context` is used (=moved) before. BlockNumber is copyable, so this line copies it beforehand.
___
*[`crates/native_blockifier/src/py_utils.rs` line 81 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPrBcs241i6Kg6QrYaP:-NPrEvS016TPUILsvGwz:b-ovwaw7) ([raw file](https://github.com/starkware-libs/blockifier/blob/32fc4cd47b7e0affb82c4081f5240bf5df3a651f/crates/native_blockifier/src/py_utils.rs#L81)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps a method of `Storage`?
</blockquote></details>

Good idea.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, and @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-uj95Ylp_wsoxd-D:-NPrHdWR7ZW7oUwl-rxc:bbin80o) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L63)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I don't think it's needed, I did it only so it works with the macro that created the pyerrors.
</blockquote></details>

@dorimedini-starkware, is this indeed the only way?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPqzwrgEIv10lZ7ObMn:-NPrHlN-9T5aMw8qsM4v:b-r6ew6q) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/py_transaction.rs#L194)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

NP. We'll have to bump a version and fix it in python, also.
</blockquote></details>

So let's wait with this, we'll do it over `cairo-0.11.0-blockifier`.
___
*[`crates/native_blockifier/src/storage.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPrHue-EYQisBfF6A-i:-NPrHue-EYQisBfF6A-j:b-7r34fw) ([raw file](https://github.com/starkware-libs/blockifier/blob/63549a040b141b73c12b7e2e6c1043034783b3de/crates/native_blockifier/src/storage.rs#L49)):*
> ```XML
>     #[args(block_number)]
>     /// Returns the unique identifier of the given block number in bytes.
>     pub fn get_block_id(&self, block_number: u64) -> NativeBlockifierResult<Option<Vec<u8>>> {
> ```

Let's restore the name, but leave the comment.



_Code quote:_
```XML
get_block_id
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-uj95Ylp_wsoxd-D:-NPrIaB74XijwCGEMhce:bazawev) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L63)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@dorimedini-starkware, is this indeed the only way?
</blockquote></details>

Every `NativeBlockifierError` needs a source error. You cannot directly define a struct-type variant in the `NativeBlockifierError` enum

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, and @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-uj95Ylp_wsoxd-D:-NPrLWgQDiDxWTldpu7m:bdt9xk5) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Every `NativeBlockifierError` needs a source error. You cannot directly define a struct-type variant in the `NativeBlockifierError` enum
</blockquote></details>

Can't we do `enum NewErrEnum {  X, Y }` and call `native_blockifier_errors!((NewErrEnum.X, NewErrEnum.X, PyNewErrEnum))`?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-uj95Ylp_wsoxd-D:-NPrPmq-ETvIc6cXDP0S:b-gfurv2) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L63)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can't we do `enum NewErrEnum {  X, Y }` and call `native_blockifier_errors!((NewErrEnum.X, NewErrEnum.X, PyNewErrEnum))`?
</blockquote></details>

(a) not sure what you're trying to accomplish, (b) the `(A, B, C)` tuple input to the macro is:
`A`: Enum variant name (cannot be `NewErrEnum::X`, must be a valid variant name)
`B`: Source error type (a struct decorated with `#[derive(Error)]`)
`C`: Some new identifier for the python type

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPr-uj95Ylp_wsoxd-D:-NPrQQiJDvusqSqxUIQr:b16k4ah) ([raw file](https://github.com/starkware-libs/blockifier/blob/49158e7d28820d4966b59643c23b5708bf35748a/crates/native_blockifier/src/errors.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

(a) not sure what you're trying to accomplish, (b) the `(A, B, C)` tuple input to the macro is:
`A`: Enum variant name (cannot be `NewErrEnum::X`, must be a valid variant name)
`B`: Source error type (a struct decorated with `#[derive(Error)]`)
`C`: Some new identifier for the python type
</blockquote></details>

I think of it this way: the `NativeBlockifierError` also has the property that it has a 1:1 mapping to python errors.
This need not be the case for all errors in the blockifier crate, so it makes sense to define another enum IMO

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPrHue-EYQisBfF6A-i:-NPrIh9C8A0KZCMPQiMm:b9ykrq2) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb34f7a0c8a4a200a4408b1388832e948157a389/crates/native_blockifier/src/storage.rs#L49)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's restore the name, but leave the comment.
</blockquote></details>

Kept the new name, as we are going to need to update the python repo anyway.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330#-:-NPsGwqT4k5D5bkLfrJl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 243 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPsLdZh1yy4FJ_duFQa:-NPsLdZh1yy4FJ_duFQb:b-ckgbr3) ([raw file](https://github.com/starkware-libs/blockifier/blob/380e9d9f5a20ff7798993d8c2a2a91492b1bbdbb/crates/native_blockifier/src/py_transaction.rs#L243)):*
> ```XML
>         block_info: &PyAny,
>         storage_path: String,
>         latest_block_id: BigInt,
> ```

this will also break dev... right?



_Code quote:_
```XML
latest_block_id: BigInt
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 243 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPsLdZh1yy4FJ_duFQa:-NPsLtHvEQmEjBR7hfTp:bdwoq2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/380e9d9f5a20ff7798993d8c2a2a91492b1bbdbb/crates/native_blockifier/src/py_transaction.rs#L243)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this will also break dev... right?
</blockquote></details>

@elintul if this is critical I'll unblock but we'll need to start cherry-picking version 0.14.0 of the native blockifier and bump later to include this... or wait for another dev PR to go through

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 243 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPsLdZh1yy4FJ_duFQa:-NPsMewSED3-tbmc_Zia:b-ma1878) ([raw file](https://github.com/starkware-libs/blockifier/blob/380e9d9f5a20ff7798993d8c2a2a91492b1bbdbb/crates/native_blockifier/src/py_transaction.rs#L243)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@elintul if this is critical I'll unblock but we'll need to start cherry-picking version 0.14.0 of the native blockifier and bump later to include this... or wait for another dev PR to go through
</blockquote></details>

I want this check to be merge, we're still blocked on infra. (bug + PVC PR).

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 243 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/330#-NPsLdZh1yy4FJ_duFQa:-NPsN52z1qGV4i8IDClh:b-6bbioj) ([raw file](https://github.com/starkware-libs/blockifier/blob/380e9d9f5a20ff7798993d8c2a2a91492b1bbdbb/crates/native_blockifier/src/py_transaction.rs#L243)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I want this check to be merge, we're still blocked on infra. (bug + PVC PR). 
</blockquote></details>

Sorry, irrelevant. I answered regarding deployment, not cherry-picking.
Still want this in, Alon has the Pythonic PR up already.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
