### PR TITLE
Don't make loop depend on open transaction results.

### PR DESCRIPTION
**Pull request by giladchase**
Even if this worked, it's not intuitive.
Now using read transactions for reading and creating the write tx later.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/596)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/596)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/596#-NXfE60a7q4svz_qE6Cf:-NXfE60a7q4svz_qE6Cg:b-ehx71o) ([raw file](https://github.com/starkware-libs/blockifier/blob/220ae2fb661dac51cd8cfcc71e34719274d3b1bf/crates/native_blockifier/src/storage.rs#L146)):*
> ```XML
>         let mut declared_classes: IndexMap<ClassHash, (CompiledClassHash, ContractClass)> =
>             IndexMap::new();
>         let mut undeclared_casm_contracts: Vec<(ClassHash, CasmContractClass)> = Vec::new();
> ```

Is this possible? I think it's more readable.



_Suggestion:_
```XML
let mut undeclared_casm_contracts = Vec<(ClassHash, CasmContractClass)>::new();
```
___
*[`crates/native_blockifier/src/storage.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/596#-NXfEboG9D0zEAQElyF_:-NXfEboH3DE2fLh8Wei7:bt1riwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/220ae2fb661dac51cd8cfcc71e34719274d3b1bf/crates/native_blockifier/src/storage.rs#L168)):*
> ```XML
>         let mut append_txn = self.writer().begin_rw_txn()?;
>         for (class_hash, contract_class) in undeclared_casm_contracts {
>             append_txn = append_txn.append_casm(&class_hash, &contract_class)?;
> ```

Is there a block `append_casm`? Would it even improve runtime?



_Code quote:_
```XML
append_txn = append_txn.append_casm(&class_hash, &contract_class)?;
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/596)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/596#-NXfEf9GAY5AXAlmssxH:-NXfEf9GAY5AXAlmssxI:bqpft1v) ([raw file](https://github.com/starkware-libs/blockifier/blob/23811938fd150dc551d873286dece9bcf2e983d0/crates/native_blockifier/src/storage.rs#L172)):*
> ```XML
>         let deployed_contract_class_definitions =
>             IndexMap::<ClassHash, DeprecatedContractClass>::new();
>         let append_txn = append_txn.append_state_diff(
> ```

I forgot to mention, i also removed the unnecessary `let`'s everywhere.
Making variable `mut` makes this unnecesary.



_Code quote:_
```XML
let append_txn = append_txn.append_state_diff(
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/596)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/596)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/596#-NXfE60a7q4svz_qE6Cf:-NXfEozD4wOHXK_rXQrH:b-vwvp9m) ([raw file](https://github.com/starkware-libs/blockifier/blob/220ae2fb661dac51cd8cfcc71e34719274d3b1bf/crates/native_blockifier/src/storage.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this possible? I think it's more readable.
</blockquote></details>

Only turbofish
```rust
        let mut deprecated_declared_classes = IndexMap::<ClassHash, DeprecatedContractClass>::new();
```
still more readable? :thinking:  (not sure myself)
___
*[`crates/native_blockifier/src/storage.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/596#-NXfEboG9D0zEAQElyF_:-NXfFCelBctehlFyf44m:b3wnvvi) ([raw file](https://github.com/starkware-libs/blockifier/blob/220ae2fb661dac51cd8cfcc71e34719274d3b1bf/crates/native_blockifier/src/storage.rs#L168)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there a block `append_casm`? Would it even improve runtime?
</blockquote></details>

No block op.
But it won't improve runtime anyway, since we are only committing the txn at the end of this function, making all write operations concatenated on `append_txn` happen in bulk anyway.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/596)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/596#-NXfEboG9D0zEAQElyF_:-NXfFjnADdQFHxsyuf5N:b-ucfknh) ([raw file](https://github.com/starkware-libs/blockifier/blob/220ae2fb661dac51cd8cfcc71e34719274d3b1bf/crates/native_blockifier/src/storage.rs#L168)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

No block op.
But it won't improve runtime anyway, since we are only committing the txn at the end of this function, making all write operations concatenated on `append_txn` happen in bulk anyway.
</blockquote></details>

Thanks!

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/596)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/596#-NXfE60a7q4svz_qE6Cf:-NXfFz96-xfFIcAFp6vT:b-x2tlnn) ([raw file](https://github.com/starkware-libs/blockifier/blob/220ae2fb661dac51cd8cfcc71e34719274d3b1bf/crates/native_blockifier/src/storage.rs#L146)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Only turbofish
```rust
        let mut deprecated_declared_classes = IndexMap::<ClassHash, DeprecatedContractClass>::new();
```
still more readable? :thinking:  (not sure myself)
</blockquote></details>

It can be a regular map, not an `IndexMap`; or keep it a `Vec`. Simply wanted to prevent the extra annotaion.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/596)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/596#-NXfE60a7q4svz_qE6Cf:-NXfJhcS4Y6s6IpqQVti:b-3poyw4) ([raw file](https://github.com/starkware-libs/blockifier/blob/220ae2fb661dac51cd8cfcc71e34719274d3b1bf/crates/native_blockifier/src/storage.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It can be a regular map, not an `IndexMap`; or keep it a `Vec`. Simply wanted to prevent the extra annotaion.
</blockquote></details>

Oh poop copied the wrong code, i meant
```rust
        let mut undeclared_casm_contracts = Vec::<(ClassHash, CasmContractClass)>::new();
```
Did it also in another couple places in the function, for consistency.
___
*[`crates/native_blockifier/src/storage.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/596#-NXfEboG9D0zEAQElyF_:-NXfInCaAsVnIwaoWV3z:bxyk19k) ([raw file](https://github.com/starkware-libs/blockifier/blob/220ae2fb661dac51cd8cfcc71e34719274d3b1bf/crates/native_blockifier/src/storage.rs#L168)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Instead of the vanilla loop we can use this, but I'm not sure if it's more readable, WDYT
```rust
        let mut append_txn = self.writer().begin_rw_txn()?;
        append_txn = undeclared_casm_contracts.into_iter().try_fold(
            append_txn,
            |append_txn, (class_hash, contract_class)| {
                append_txn.append_casm(&class_hash, &contract_class)
            },
        )?;
```
or shorter
```rust
        let mut append_txn = self.writer().begin_rw_txn()?;
        append_txn = undeclared_casm_contracts.into_iter().try_fold(
            append_txn,
            |append_txn, (class_hash, contract_class)| {
                append_txn.append_casm(&class_hash, &contract_class)
            },
        )?;
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/596)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
