### PR TITLE
Add ExecutionMode enum to EntryPointExecutionContext.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/926)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/926#-NehNakAC0Lrvdw16182:-NehNakAC0Lrvdw16183:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b3362696d9c0db2ba8b69e50a01da707577e71d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L177)):*
> ```XML
>             secp256r1_hint_processor: SecpHintProcessor::default(),
>             execution_mode,
>         }
> ```





_Suggestion:_
```XML
        SyscallHintProcessor {
            state,
            resources,
            context,
            call,
            inner_calls: vec![],
            events: vec![],
            l2_to_l1_messages: vec![],
            read_only_segments,
            syscall_ptr: initial_syscall_ptr,
            read_values: vec![],
            accessed_keys: HashSet::new(),
            hints,
            execution_info_ptr: None,
            secp256k1_hint_processor: SecpHintProcessor::default(),
            secp256r1_hint_processor: SecpHintProcessor::default(),
            context.execution_mode,
        }
```

**Comment by ArniStarkware** [comment]
*[`crates/native_blockifier/src/papyrus_state_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/926#-NehQS4aACZLW-vUcsG5:-NehQS4b2bxRPH2r-Gwj:b-olrhar) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b3362696d9c0db2ba8b69e50a01da707577e71d/crates/native_blockifier/src/papyrus_state_test.rs#L0)):*
Can we make changes to this file like this?

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/926#-NehRXVC3-FjlXy8yklO:-NehRXVD9JyIBrVdYmcP:b-2rrwmi) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b3362696d9c0db2ba8b69e50a01da707577e71d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L177)):*
> ```XML
>             secp256r1_hint_processor: SecpHintProcessor::default(),
>             execution_mode,
>         }
> ```

Is this better?
Otherwise, it complaints about context being borrowed.



_Suggestion:_
```XML
        SyscallHintProcessor {
            state,
            resources,
            execution_mode: context.execution_mode,
            context,
            call,
            inner_calls: vec![],
            events: vec![],
            l2_to_l1_messages: vec![],
            read_only_segments,
            syscall_ptr: initial_syscall_ptr,
            read_values: vec![],
            accessed_keys: HashSet::new(),
            hints,
            execution_info_ptr: None,
            secp256k1_hint_processor: SecpHintProcessor::default(),
            secp256r1_hint_processor: SecpHintProcessor::default(),
        }
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/926)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/common_hints.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/926#-NemfuMiB72xNH0t9MM2:-Nemj-th3YbmUoRrA1Fk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/942d5a0e791a34f625c2cd103e3b20240b9f1e44/crates/blockifier/src/execution/common_hints.rs#L31)):*
> ```XML
>     /// Normal execution mode.
>     #[default]
>     Default,
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/926#-Nemg1z5Brg59dLiQZZC:-Nemj0xTEF3_o6631fPU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/942d5a0e791a34f625c2cd103e3b20240b9f1e44/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L154)):*
> ```XML
>     );
> 
>     // Negative flow. Block number out of range.
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/926#-NehjRao9HDx9giK8km-:-NemUIH80g1hWbttK9qX:bss4a2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/fff80680112677d85256efe276188298a197dd09/crates/blockifier/src/execution/syscalls/hint_processor.rs#L136)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

There is no need. This value can be accessed just the same by `context.execution_mode`.
</blockquote></details>

Removed.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/926#-:-NemruzS-l_u7m9RABLr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 6 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
