### PR TITLE
Convert `dyn State` to parametrized.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/300)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/300)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/300#-NOyvNRe7v7kjiT0bgE2:-NOyvNRe7v7kjiT0bgE3:b34qp6y) ([raw file](https://github.com/starkware-libs/blockifier/blob/0aebb1a0e14607ade0d5ef29aa2ba0855355898f/crates/blockifier/src/transaction/transaction_execution.rs#L47)):*
> ```XML
>         };
> 
>         Ok((state.to_state_diff(), tx_execution_info))
> ```

Remove as we said.



_Code quote:_
```XML
state.to_state_diff()
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/300)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/300#-NOyvNRe7v7kjiT0bgE2:-NOz-2taCV9yAmwXj6Eq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0aebb1a0e14607ade0d5ef29aa2ba0855355898f/crates/blockifier/src/transaction/transaction_execution.rs#L47)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Remove as we said.
</blockquote></details>

Done.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/300)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/state/cached_state.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/300#-NOz-68u4RrSxbR3mYOz:-NOz-68v8pSPUMCJdCQ5:be686p4) ([raw file](https://github.com/starkware-libs/blockifier/blob/0aebb1a0e14607ade0d5ef29aa2ba0855355898f/crates/blockifier/src/state/cached_state.rs#L25)):*
> ```XML
> /// initialization.
> #[derive(Debug, Default)]
> pub struct CachedState<SR: StateReader> {
> ```

Are you also planning to rename this?



_Code quote:_
```XML
SR: StateReader
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/300)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/state/cached_state.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/300#-NOz-68u4RrSxbR3mYOz:-NOz-Pgs3xo2SZOY4tiG:b-g8bnid) ([raw file](https://github.com/starkware-libs/blockifier/blob/0aebb1a0e14607ade0d5ef29aa2ba0855355898f/crates/blockifier/src/state/cached_state.rs#L25)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Are you also planning to rename this?
</blockquote></details>

To what?

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/300)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/blockifier/src/state/cached_state.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/300#-NOz-68u4RrSxbR3mYOz:-NOz-RaB9_ehVBAfL8Ah:b-7uadv1) ([raw file](https://github.com/starkware-libs/blockifier/blob/0aebb1a0e14607ade0d5ef29aa2ba0855355898f/crates/blockifier/src/state/cached_state.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

To what?
</blockquote></details>

`S`?

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
