### PR TITLE
Add storage related members to the syscall handler.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 2 of 10 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSFbZu75WOKjMeDEbA:-NPSFbZu75WOKjMeDEbB:b-nkhaea) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/entry_point.rs#L95)):*
> ```XML
>     pub l2_to_l1_messages: Vec<OrderedL2ToL1Message>,
>     pub storage_read_values: Vec<StarkFelt>,
>     pub accessed_storage_keys: HashSet<StorageKey>,
> ```

WDYT of moving those to `CallInfo` instead? It will cleanup the tests.



_Code quote:_
```XML
    pub storage_read_values: Vec<StarkFelt>,
    pub accessed_storage_keys: HashSet<StorageKey>,
```
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPS6-YgDqFDM5bdcbDU:-NPS6-YhDztHwl1_yi1h:boc4pnu) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/syscall_handling.rs#L65)):*
> ```XML
>     // Used for tracking L2-to-L1 messages order during the current execution.
>     pub n_sent_messages_to_l1: usize,
> ```

Perhaps start another category under `Execution results`, of: `// Additional information gathered during execution.`.
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSBfTV0DS3Ok2bw7Ym:-NPSBfTV0DS3Ok2bw7Yn:bht9qce) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/syscall_handling.rs#L324)):*
> ```XML
>     Ok(ReadOnlySegment { start_ptr: retdata_segment_start_ptr, length: retdata.len() })
> }
> ```

Implement a symmetric `set_contract_storage_at` and add the key to `accessed_keys` (if we delete the read before the write, we will still have the full functionality).
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPS6ueI8yPTRdMawHDY:-NPS6ueI8yPTRdMawHDZ:bkgz5jt) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/syscall_handling.rs#L327)):*
> ```XML
> pub fn read(
>     address: StorageKey,
>     syscall_handler: &mut SyscallHintProcessor<'_>,
> ```

Make this a method.



_Suggestion:_
```XML
pub fn get_contract_storage_at(
    &mut self, key: StorageKey,
) -> SyscallResult<StorageReadResponse> {
```
___
*[`crates/blockifier/src/execution/syscalls.rs` line 198 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSEP7s6Fur1PDg4fqW:-NPSEP7s6Fur1PDg4fqX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/syscalls.rs#L198)):*
> ```XML
>     syscall_handler: &mut SyscallHintProcessor<'_>,
> ) -> SyscallResult<StorageWriteResponse> {
>     // Read the value before the write operation in order to log it in the read_values list.
> ```





_Suggestion:_
```XML
    // Read the value before the write operation in order to log it in the list of read 
    // values. This is needed to correctly build the `DictAccess` entry corresponding to 
    // `storage_write` syscall in the OS.
```
___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSErVU7VmUFUbVqLHy:-NPSErVU7VmUFUbVqLHz:b2gy667) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/syscalls_test.rs#L35)):*
> ```XML
>     let expected_call_execution = CallExecution {
>         storage_read_values: vec![stark_felt!(0), value],
>         accessed_storage_keys: HashSet::from([StorageKey(patricia_key!(key))]),
> ```

Move after `retdata`, for all.



_Code quote:_
```XML
        storage_read_values: vec![stark_felt!(0), value],
        accessed_storage_keys: HashSet::from([StorageKey(patricia_key!(key))]),
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSFbZu75WOKjMeDEbA:-NPSgsQm6N7CDgw6r61s:b-e2vx2g) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/entry_point.rs#L95)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT of moving those to `CallInfo` instead? It will cleanup the tests.
</blockquote></details>

We can. I though it is execution related information. In this case, should I add a test to validate these specific fields? Or is it enough to leave some of the changes I made?
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSBfTV0DS3Ok2bw7Ym:-NPSfmEMCOnFnCCnm_iu:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/syscall_handling.rs#L324)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Implement a symmetric `set_contract_storage_at` and add the key to `accessed_keys` (if we delete the read before the write, we will still have the full functionality).
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSFbZu75WOKjMeDEbA:-NPSjspnAd8u2nNVZqo4:b-bu4ox6) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/entry_point.rs#L95)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We can. I though it is execution related information. In this case, should I add a test to validate these specific fields? Or is it enough to leave some of the changes I made?
</blockquote></details>

It is execution-related, but shouldn't pollute the tests (if we decide otherwise, we can move it inside).
So yes, dedicated tests are required.
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 269 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSkJTQ3PZv5DNpo53K:-NPSkJTQ3PZv5DNpo53L:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/abde6e97770e809eaafdeb321710e70ca64df7f5/crates/blockifier/src/execution/syscall_handling.rs#L269)):*
> ```XML
>         self.state.set_storage_at(self.storage_address, key, value);
> 
>         Ok(StorageReadResponse { value })
> ```





_Suggestion:_
```XML
Ok(StorageWriteResponse {})
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSFbZu75WOKjMeDEbA:-NPWAWyK9SpjZHCfqyqG:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/entry_point.rs#L95)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It is execution-related, but shouldn't pollute the tests (if we decide otherwise, we can move it inside).
So yes, dedicated tests are required.
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 269 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSkJTQ3PZv5DNpo53K:-NPSlVJq9tGptOc39MLp:b-5s1q13) ([raw file](https://github.com/starkware-libs/blockifier/blob/abde6e97770e809eaafdeb321710e70ca64df7f5/crates/blockifier/src/execution/syscall_handling.rs#L269)):*
> ```XML
>         self.state.set_storage_at(self.storage_address, key, value);
> 
>         Ok(StorageReadResponse { value })
> ```

Ops. Fixed.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPSFbZu75WOKjMeDEbA:-NPWRmqD5DsGQ6QBZQOK:bin7vn9) ([raw file](https://github.com/starkware-libs/blockifier/blob/ac1576219ed05cbe93b5a0ddabfb2018b7532921/crates/blockifier/src/execution/entry_point.rs#L95)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Let's add the comment from the syscall handler here as well: `// Additional information gathered during execution.`.
___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 249 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPWToGJ-hWTu91lem7h:-NPWToGJ-hWTu91lem7i:b-doh3pz) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd18acdb0f319645bddf59ab78336674309b39fa/crates/blockifier/src/execution/syscall_handling.rs#L249)):*
> ```XML
>         Ok(tx_info_start_ptr)
>     }
> ```

WDYT of passing the `Storage*Request`? Keep it symmetrical with the return value.
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPWUKRL7oLUOUqlt_Wm:-NPWUKRL7oLUOUqlt_Wn:b-4hmag0) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd18acdb0f319645bddf59ab78336674309b39fa/crates/native_blockifier/src/py_transaction_execution_info.rs#L109)):*
> ```XML
>             internal_calls: call_info.inner_calls.into_iter().map(PyCallInfo::from).collect(),
>             storage_read_values: starkfelt_to_pyfelt_vec(call_info.storage_read_values),
>             accessed_storage_keys: call_info
> ```

WDYT of a small more generic util than `starkfelt_to_pyfelt_vec`? We repeat this line a lot.

Use some types `T, PyT` and do:
```rust
pub fn to_py_vec<T, PyT>(values: Vec<T>, converter: F) -> Vec<PyT> 
where
    F: FnOnce(T) -> PyT
{
    values.into_iter().map(F).collect()
}
```



_Code quote:_
```XML
            accessed_storage_keys: call_info
                .accessed_storage_keys
                .into_iter()
                .map(|storage_key| PyFelt(*storage_key.0.key()))
                .collect(),
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 249 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPWToGJ-hWTu91lem7h:-NPWWgQd-Fs8yggkV-8Q:b-txid3o) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd18acdb0f319645bddf59ab78336674309b39fa/crates/blockifier/src/execution/syscall_handling.rs#L249)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT of passing the `Storage*Request`? Keep it symmetrical with the return value.
</blockquote></details>

NP. Is it okay that in`get_contract_storage_at` it is not symmetrical? (and can't be done symmetrical)
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPWUKRL7oLUOUqlt_Wm:-NPWlRAZ51xVa2YSkPpx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd18acdb0f319645bddf59ab78336674309b39fa/crates/native_blockifier/src/py_transaction_execution_info.rs#L109)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT of a small more generic util than `starkfelt_to_pyfelt_vec`? We repeat this line a lot.

Use some types `T, PyT` and do:
```rust
pub fn to_py_vec<T, PyT>(values: Vec<T>, converter: F) -> Vec<PyT> 
where
    F: FnOnce(T) -> PyT
{
    values.into_iter().map(F).collect()
}
```
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPWUKRL7oLUOUqlt_Wm:-NPWlnSz1s5TXWVtv5KR:bf83zmg) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd18acdb0f319645bddf59ab78336674309b39fa/crates/native_blockifier/src/py_transaction_execution_info.rs#L109)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Forgot to push?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 249 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPWToGJ-hWTu91lem7h:-NPWvRTY6I6CIDnEibB8:bd8omcw) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd18acdb0f319645bddf59ab78336674309b39fa/crates/blockifier/src/execution/syscall_handling.rs#L249)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

NP. Is it okay that in`get_contract_storage_at` it is not symmetrical? (and can't be done symmetrical)
</blockquote></details>

Oh, I see. Then let's revert so write looks like read (sorry).
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPWUKRL7oLUOUqlt_Wm:-NPWvEJ8DEr27KZquxJk:b-xdpn2y) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd18acdb0f319645bddf59ab78336674309b39fa/crates/native_blockifier/src/py_transaction_execution_info.rs#L109)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Forgot to push?
</blockquote></details>

You can also use [here](https://github.com/starkware-libs/blockifier-old/blob/778eef42269fd151f46e3a2b8811c6e3ad8cf070/crates/native_blockifier/src/py_transaction.rs#L52).

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPWUKRL7oLUOUqlt_Wm:-NPWwuou8AscT_evg_4x:bk0frf9) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd18acdb0f319645bddf59ab78336674309b39fa/crates/native_blockifier/src/py_transaction_execution_info.rs#L109)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You can also use [here](https://github.com/starkware-libs/blockifier-old/blob/778eef42269fd151f46e3a2b8811c6e3ad8cf070/crates/native_blockifier/src/py_transaction.rs#L52).
</blockquote></details>

The main problem is that `biguint_to_felt` returns a `Result` so using it here returns `Vec<Result<StarkFelt, NativeBlockifierError>>` (as opposed to `Result<Vec<StarkFelt>, NativeBlockifierError>`.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 6 of 13 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/execution/syscall_handling.rs` line 249 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPWToGJ-hWTu91lem7h:-NPXDb9z5lLJ0WIssghk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd18acdb0f319645bddf59ab78336674309b39fa/crates/blockifier/src/execution/syscall_handling.rs#L249)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Oh, I see. Then let's revert so write looks like read (sorry).
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r3, 1 of 5 files at r4, 3 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPkttTLEe4v6AuVenrm:-NPkttTLEe4v6AuVenrn:b-obqcni) ([raw file](https://github.com/starkware-libs/blockifier/blob/1106239f1be1595967b19fa807dde939e7d714c4/crates/blockifier/src/execution/syscalls_test.rs#L132)):*
> ```XML
>     };
> 
>     compare_call_info_fields(
> ```

Let's compare the fields you added here; it's a good use case (nested calls).
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 244 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPkuMJ56UfFgHWMSTJl:-NPkuMJ56UfFgHWMSTJm:bdy6fe6) ([raw file](https://github.com/starkware-libs/blockifier/blob/1106239f1be1595967b19fa807dde939e7d714c4/crates/blockifier/src/transaction/transactions_test.rs#L244)):*
> ```XML
>         actual_resources: ResourcesMapping::default(),
>     };
> ```

How difficult will it be to compare the storage values here as well?
A bit worried about forgetting fields we add in the test util.
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPWUKRL7oLUOUqlt_Wm:-NPktHGcDydE746zwi_w:b-4hvi0m) ([raw file](https://github.com/starkware-libs/blockifier/blob/fd18acdb0f319645bddf59ab78336674309b39fa/crates/native_blockifier/src/py_transaction_execution_info.rs#L109)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The main problem is that `biguint_to_felt` returns a `Result` so using it here returns `Vec<Result<StarkFelt, NativeBlockifierError>>` (as opposed to `Result<Vec<StarkFelt>, NativeBlockifierError>`.
</blockquote></details>

Got it.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPkttTLEe4v6AuVenrm:-NPl-iHa3sYG6pNeap1z:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1106239f1be1595967b19fa807dde939e7d714c4/crates/blockifier/src/execution/syscalls_test.rs#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's compare the fields you added here; it's a good use case (nested calls).
</blockquote></details>

Done.



_Code quote:_
```XML
 assert_eq!(main_entry_point.execute_directly(&mut state).unwrap(), expected_call_info);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 244 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPkuMJ56UfFgHWMSTJl:-NPlB-hQ8TSkMfMrrhg_:b-4nyroy) ([raw file](https://github.com/starkware-libs/blockifier/blob/1106239f1be1595967b19fa807dde939e7d714c4/crates/blockifier/src/transaction/transactions_test.rs#L244)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How difficult will it be to compare the storage values here as well?
A bit worried about forgetting fields we add in the test util.
</blockquote></details>

Can I do it in a separate PR?

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 12 files at r3, 2 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 427 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPmg5vIBtuiV8wae-6S:-NPmg5vIBtuiV8wae-6T:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3af46c66f3e566b7179a3b40a1eca34b478c4a4d/crates/blockifier/src/execution/entry_point_test.rs#L427)):*
> ```XML
> }
> 
> // Test correct update of the fields: `storage_read_values` and `accessed_storage_keys`.
> ```





_Suggestion:_
```XML
// Tests correct update of the fields: `storage_read_values` and `accessed_storage_keys`.
// Note read values also contain the reads performed right before a write operation.
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 432 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPmfwvE3utSbVE3WOCf:-NPmfwvE3utSbVE3WOCg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3af46c66f3e566b7179a3b40a1eca34b478c4a4d/crates/blockifier/src/execution/entry_point_test.rs#L432)):*
> ```XML
>     let mut state = create_test_state();
> 
>     // Storage var.
> ```





_Suggestion:_
```XML
// Test storage variable.
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 441 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPmfiYT5QY3k_Ub46Sy:-NPmfiYT5QY3k_Ub46Sz:b-68ylr6) ([raw file](https://github.com/starkware-libs/blockifier/blob/3af46c66f3e566b7179a3b40a1eca34b478c4a4d/crates/blockifier/src/execution/entry_point_test.rs#L441)):*
> ```XML
>     assert_eq!(
>         actual_call_info.accessed_storage_keys,
>         HashSet::from([get_storage_var_address("number_map", &[stark_felt!(1)],).unwrap()])
> ```

Remove tailing comma.



_Suggestion:_
```XML
get_storage_var_address("number_map", &[stark_felt!(1)])
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 444 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPmfn7xE23jhx2mqgbe:-NPmfn7xE23jhx2mqgbf:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3af46c66f3e566b7179a3b40a1eca34b478c4a4d/crates/blockifier/src/execution/entry_point_test.rs#L444)):*
> ```XML
>     );
> 
>     // Storage read and write.
> ```





_Suggestion:_
```XML
// Test raw storage read and write.
```
___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 116 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/314#-NPmZL4fDNbQcDKASXOM:-NPmZL4fDNbQcDKASXON:b-x70ep2) ([raw file](https://github.com/starkware-libs/blockifier/blob/3af46c66f3e566b7179a3b40a1eca34b478c4a4d/crates/blockifier/src/execution/syscalls_test.rs#L116)):*
> ```XML
>         accessed_storage_keys: HashSet::from([StorageKey(patricia_key!(key + 1))]),
> 
>         ..Default::default()
> ```

Remove blank line above.



_Code quote:_
```XML
..Default::default()
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/314#-:-NPpmiGy4lz-Je9QWmoN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
