### PR TITLE
Add `calculate_tx_resources`.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/386)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/386)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBIcpi3h2tc-I371vY:-NSBIcpi3h2tc-I371vZ:b-250ayg) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L13)):*
> ```XML
> const FEE_TRANSFER_N_STORAGE_CHANGES: u32 = 2; // Sender and sequencer balance update.
> // Exclude the sequencer balance update, since it's charged once throughout the batch.
> const FEE_TRANSFER_N_STORAGE_CHANGES_TO_CHARGE: u32 = FEE_TRANSFER_N_STORAGE_CHANGES - 1;
> ```

maybe we should have only two integer types... `usize` or `u128`.
I suggest that for any integer variable `X`:
1. If there exists some data structure with `~X` elements (`Vec`, `HashMap` etc), then `X` should be of type `usize`.
2. Otherwise, `X` should be `u128`.
WDYT?
Specifically, these two seem like they should be `usize`, because we *will* have some form of list/map of all storage changes, right?



_Code quote:_
```XML
const FEE_TRANSFER_N_STORAGE_CHANGES: u32 = 2; // Sender and sequencer balance update.
// Exclude the sequencer balance update, since it's charged once throughout the batch.
const FEE_TRANSFER_N_STORAGE_CHANGES_TO_CHARGE: u32 = FEE_TRANSFER_N_STORAGE_CHANGES - 1;
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBIKY0-Nx1aZ_PlmGc:-NSBIKY0-Nx1aZ_PlmGd:bf56h37) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L29)):*
> ```XML
>         state.count_actual_state_changes();
> 
>     let non_optional_call_infos: Vec<&CallInfo> = call_infos.iter().flatten().collect();
> ```

what's this? on python side it seems you should be filtering `None`s, not flattening



_Code quote:_
```XML
call_infos.iter().flatten().collect()
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBJVKJCUZhOBjcQZPK:-NSBJVKJCUZhOBjcQZPL:b2l7ffp) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L49)):*
> ```XML
>     let mut tx_resources = HashMap::from([
>         ("l1_gas_usage".to_string(), l1_gas_usage),
>         ("n_steps".to_string(), cairo_usage.n_steps + cairo_usage.n_memory_holes),
> ```

Perhaps these constant strings should be named constants...? WDYT?
`"l1_gas_usage"` is used in this file already, and `"n_steps"` is used to define the JSON in `os_resources.rs`



_Code quote:_
```XML
        ("l1_gas_usage".to_string(), l1_gas_usage),
        ("n_steps".to_string(), cairo_usage.n_steps + cairo_usage.n_memory_holes),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/386)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBLIif4t_KFbwkcRLA:-NSBLIif4t_KFbwkcRLB:b-nuu8ss) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L49)):*
> ```XML
>     let mut tx_resources = HashMap::from([
>         ("l1_gas_usage".to_string(), l1_gas_usage),
>         ("n_steps".to_string(), cairo_usage.n_steps + cairo_usage.n_memory_holes),
> ```

this is part of `to_dict` on python, maybe add a comment here why memory holes are added as `n_steps` here?



_Code quote:_
```XML
cairo_usage.n_steps + cairo_usage.n_memory_holes
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/386)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBIcpi3h2tc-I371vY:-NSWGGZGAJeJ_cmHxAn-:bnzjs6t) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe we should have only two integer types... `usize` or `u128`.
I suggest that for any integer variable `X`:
1. If there exists some data structure with `~X` elements (`Vec`, `HashMap` etc), then `X` should be of type `usize`.
2. Otherwise, `X` should be `u128`.
WDYT?
Specifically, these two seem like they should be `usize`, because we *will* have some form of list/map of all storage changes, right?
</blockquote></details>

I see what you mean. Though I read [this] (https://www.reddit.com/r/rust/comments/4lql5l/beginner_question_should_i_use_usize_and_isize/) and it seems that we should use a concrete type and maybe convert the `usize` using `try_from()`. WDYT? 
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBIKY0-Nx1aZ_PlmGc:-NSWGnqo1F_ztWmuy9mV:bu7ivke) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this? on python side it seems you should be filtering `None`s, not flattening
</blockquote></details>

Flattening also filters `None`s. Since `Option` implements `IntoIterator`, we can convert our `Vec` into an iterator (which will be an iterator of iterators) and then flatten it.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBJVKJCUZhOBjcQZPK:-NSWKcKm3vJiVP_9zD9K:bqlnojg) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Perhaps these constant strings should be named constants...? WDYT?
`"l1_gas_usage"` is used in this file already, and `"n_steps"` is used to define the JSON in `os_resources.rs`
</blockquote></details>

Do you think it is necessary? Wouldn't that be more confusing?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/386)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBIcpi3h2tc-I371vY:-NSeIhqH5ZmXhNWWSUMY:b-rscwvd) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L13)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see what you mean. Though I read [this] (https://www.reddit.com/r/rust/comments/4lql5l/beginner_question_should_i_use_usize_and_isize/) and it seems that we should use a concrete type and maybe convert the `usize` using `try_from()`. WDYT? 
</blockquote></details>

in the blockifier we hit an error on block 256 due to papyrus not working on a different architecture, so maybe you're right.
but why are you so sure there are at most 256 storage changes for fee transfer?
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBJVKJCUZhOBjcQZPK:-NSeFosi-UJsFtdntM0H:b4os34y) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L49)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do you think it is necessary? Wouldn't that be more confusing?
</blockquote></details>

shouldn't be, if the constant has a good name (N_STEPS_KEY_STRING or something).
makes it less error-prone.
non-blocking anyway, your call

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/386)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBIcpi3h2tc-I371vY:-NSeObhT7S4a8CwrfQd_:b-yo0msu) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in the blockifier we hit an error on block 256 due to papyrus not working on a different architecture, so maybe you're right.
but why are you so sure there are at most 256 storage changes for fee transfer?
</blockquote></details>

I decided to change every numeric value to `u64` (after consulting with Elin that the numbers should not exceed `2^64` bits) (except for the gas usage that is `u128`). I chose here (as a temporary solution) `u8` because the size of a `usize` is always guaranteed to be 8 bits or greater and a `u8` to `usize` From conversion will always exist. 
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBJVKJCUZhOBjcQZPK:-NSeQILL720_b_CVIoyJ:b-bsljaj) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shouldn't be, if the constant has a good name (N_STEPS_KEY_STRING or something).
makes it less error-prone.
non-blocking anyway, your call
</blockquote></details>

Got it. I agree. Will do it in my next PR.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/386#-NSBLIif4t_KFbwkcRLA:-NSeQOzF52vu5iFU1zro:b-f0h5ug) ([raw file](https://github.com/starkware-libs/blockifier/blob/999210ab84a841be4068142dac94870f3e0b6e76/crates/blockifier/src/fee/fee_utils.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is part of `to_dict` on python, maybe add a comment here why memory holes are added as `n_steps` here?
</blockquote></details>

Will do. Still waiting for an answer as to why this is.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/386)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

**Pull request merged**
