### PR TITLE
feat(concurrency): write thin re-validate

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nvk7GMR64CiDkkY0QRp:-Nvk7GMS8zPOYvc7MQF_:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8efa14041989e1bcebd99251ce03ed476a552df/crates/blockifier/src/concurrency/worker_logic.rs#L16)):*
> ```XML
>     tx_index: TxIndex,
>     block_context: &BlockContext,
>     state_cache: &mut StateCache,
> ```





_Suggestion:_
```XML
    read_set: &mut StateCache,
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nvk50ZI2n50zXtKkIqh:-Nvk50ZI2n50zXtKkIqi:b-9wbt3d) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8efa14041989e1bcebd99251ce03ed476a552df/crates/blockifier/src/concurrency/worker_logic.rs#L18)):*
> ```XML
>     state_cache: &mut StateCache,
> ) -> bool {
>     let fee_token_address = block_context.chain_info.fee_token_address(&FeeType::Strk);
> ```

Consider adding `tx_context` as an input parameter.



_Suggestion:_
```XML
    let fee_token_address = tx_context.fee_token_address();
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nvk8DuC0O_nwi-Z2Thk:-Nvk8DuC0O_nwi-Z2Thl:b-l59s0a) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea0d625e064de66a88cf6fcc4c27d8455c030c35/crates/blockifier/src/concurrency/worker_logic.rs#L28)):*
> ```XML
>                 .storage_initial_values
>                 .get(&(fee_token_address, sequencer_balance_key_low))
>                 .unwrap(),
> ```

Note- it can be `None`, and that's okay. We want to insert only in case of `Some`.



_Code quote:_
```XML
            *state_cache
                .storage_initial_values
                .get(&(fee_token_address, sequencer_balance_key_low))
                .unwrap(),
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nvk7GMR64CiDkkY0QRp:-NvkMfYY9IK8ih2h9Xkd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8efa14041989e1bcebd99251ce03ed476a552df/crates/blockifier/src/concurrency/worker_logic.rs#L16)):*
> ```XML
>     tx_index: TxIndex,
>     block_context: &BlockContext,
>     state_cache: &mut StateCache,
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nvk50ZI2n50zXtKkIqh:-NvkMhyw8_NMDRWp13Ud:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8efa14041989e1bcebd99251ce03ed476a552df/crates/blockifier/src/concurrency/worker_logic.rs#L18)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider adding `tx_context` as an input parameter.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nvk8DuC0O_nwi-Z2Thk:-NvkMjKRDPe8NFDdKCsV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea0d625e064de66a88cf6fcc4c27d8455c030c35/crates/blockifier/src/concurrency/worker_logic.rs#L28)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note- it can be `None`, and that's okay. We want to insert only in case of `Some`.
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NvkY6ED7pfgIqeLsYPK:-NvkY6ED7pfgIqeLsYPL:bvjr6ya) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdc8f01a1add01aab301ae2b057ca1a320cc80fd/crates/blockifier/src/concurrency/worker_logic.rs#L15)):*
> ```XML
>     state: &mut VersionedState<S>,
>     tx_index: TxIndex,
>     tx_context: Arc<TransactionContext>,
> ```

Do you need an actual copy?



_Suggestion:_
```XML
    tx_context:&TransactionContext,
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NvkYtks2tZLyJaFIYAm:-NvkYtkt1pKRjHB2lkTA:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdc8f01a1add01aab301ae2b057ca1a320cc80fd/crates/blockifier/src/concurrency/worker_logic.rs#L22)):*
> ```XML
>     let sequencer_balance_key_low = get_fee_token_var_address(sequencer_address);
>     let sequencer_balance_key_high = next_storage_key(&sequencer_balance_key_low).unwrap();
>     let mut storage_initial_values = HashMap::new();
> ```





_Suggestion:_
```XML
    let mut sequencer_balance_storage_reads = HashMap::new();
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NvkYHsAEX6k6ZIyJdEK:-NvkYHsAEX6k6ZIyJdEL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdc8f01a1add01aab301ae2b057ca1a320cc80fd/crates/blockifier/src/concurrency/worker_logic.rs#L27)):*
> ```XML
>             Some(value) => storage_initial_values.insert((fee_token_address, seq_key), *value),
>             None => None,
>         };
> ```





_Suggestion:_
```XML
        if let Some(value) = read_set.storage_initial_values.get(&(fee_token_address, seq_key)) {
            storage_initial_values.insert((fee_token_address, seq_key), *value),
        };
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NvkYXogAC4OnjRv2KM4:-NvkYXogAC4OnjRv2KM5:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdc8f01a1add01aab301ae2b057ca1a320cc80fd/crates/blockifier/src/concurrency/worker_logic.rs#L31)):*
> ```XML
> 
>     let new_state_cache = &mut StateCache { storage_initial_values, ..StateCache::default() };
>     state.validate_read_set(tx_index, new_state_cache)
> ```





_Suggestion:_
```XML
    if storage_initial_values.len() == 0 {
        return true;
    }
    let new_state_cache = &mut StateCache { storage_initial_values, ..StateCache::default() };
    state.validate_read_set(tx_index, new_state_cache)
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NvkuS-H2NiEkeACmndA:-NvkuS-H2NiEkeACmndB:b-oy5i54) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdc8f01a1add01aab301ae2b057ca1a320cc80fd/crates/blockifier/src/concurrency/worker_logic.rs#L12)):*
> ```XML
> use crate::state::state_api::StateReader;
> 
> pub fn thin_revalidate<S: StateReader>(
> ```

Please invest in good and informative naming. Consider `revalidate_sequencer_balance_reads` (unless you're planning to add more things to this function)

Also, worth documenting the use-case as it is not trivial.



_Code quote:_
```XML
thin_revalidate
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NvktPFn66IuJD4I6PSl:-NvktPFn66IuJD4I6PSm:b-6hjwvr) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdc8f01a1add01aab301ae2b057ca1a320cc80fd/crates/blockifier/src/concurrency/worker_logic.rs#L21)):*
> ```XML
>     let sequencer_address = tx_context.block_context.block_info.sequencer_address;
>     let sequencer_balance_key_low = get_fee_token_var_address(sequencer_address);
>     let sequencer_balance_key_high = next_storage_key(&sequencer_balance_key_low).unwrap();
> ```

`except("...")`, or wait for the PR with the refactor of these three lines



_Code quote:_
```XML
.unwrap();
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NvkuS-H2NiEkeACmndA:-Nvl9j8h6PpiFauKcCzW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdc8f01a1add01aab301ae2b057ca1a320cc80fd/crates/blockifier/src/concurrency/worker_logic.rs#L12)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please invest in good and informative naming. Consider `revalidate_sequencer_balance_reads` (unless you're planning to add more things to this function)

Also, worth documenting the use-case as it is not trivial.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NvkYXogAC4OnjRv2KM4:-Nvl0PjIC1lJVcQYnQ_8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdc8f01a1add01aab301ae2b057ca1a320cc80fd/crates/blockifier/src/concurrency/worker_logic.rs#L31)):*
> ```XML
> 
>     let new_state_cache = &mut StateCache { storage_initial_values, ..StateCache::default() };
>     state.validate_read_set(tx_index, new_state_cache)
> ```

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
@meship-starkware can you please rebase this PR?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-:-NwJRk16CTAnBhgjxHow:b-goaayu)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by meship-starkware — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-:-Nwj3SBM4cvdJdD82O-v:b-896fix)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NvkuS-H2NiEkeACmndA:-NwjYTiDEWR-kiO0h92K:b-hd29tu) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdc8f01a1add01aab301ae2b057ca1a320cc80fd/crates/blockifier/src/concurrency/worker_logic.rs#L12)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I.e., that it is relevant for transactions that read the sequencer balance before the fee transfer

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NwkOH1A-5jkPi5KRwdB:-NwkOH1A-5jkPi5KRwdC:b-tiub40) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cddd76a431f81579c0f85fb6a8c35f0945c576/crates/blockifier/src/concurrency/worker_logic.rs#L15)):*
> ```XML
> // before the previous transaction was commited.
> pub fn revalidate_sequencer_balance_reads<S: StateReader>(
>     versioned_state: &mut VersionedStateProxy<S>,
> ```

Maybe you don't need the reference



_Suggestion:_
```XML
    state: &ThreadSafeVersionedState<S>,
    tx_index: TxIndex,
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NwkNjjq9N_F_pmkxtPg:-NwkNjjr81VU0DG2ahcX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cddd76a431f81579c0f85fb6a8c35f0945c576/crates/blockifier/src/concurrency/worker_logic.rs#L17)):*
> ```XML
>     versioned_state: &mut VersionedStateProxy<S>,
>     tx_context: &TransactionContext,
>     read_set: &StateCache,
> ```





_Suggestion:_
```XML
    read_set: &StateMaps,
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 33 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NwkQ4cL6cFHLwWMouPc:-NwkQ4cM-Dkd1DoohVic:b-itb1nc) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cddd76a431f81579c0f85fb6a8c35f0945c576/crates/blockifier/src/concurrency/worker_logic.rs#L33)):*
> ```XML
>     }
> 
>     let new_state_cache = &mut StateCache {
> ```

Please use `StateMaps` directly



_Code quote:_
```XML
    let new_state_cache = &mut StateCache {
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NwkOS5JDMTUeT3nuZfl:-NwkOS5K9YmLIR87vVbn:b-5lx4fe) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cddd76a431f81579c0f85fb6a8c35f0945c576/crates/blockifier/src/concurrency/worker_logic.rs#L44)):*
> ```XML
>         .lock()
>         .unwrap()
>         .validate_read_set(versioned_state.tx_index, &new_state_cache.initial_reads)
> ```

You may need to change the inner field to public. Consider making it a method. Or, use
'state.pin_version(tx_index).state().validate_read_set(tx_index, &new_state_cache.initial_reads)`
I'm wondering if the `validate_read_set` should be a method of `VersionedStateProxy`.



_Suggestion:_
```XML
    state.0.lock.expect("some error message").validate_read_set(tx_index, &new_state_cache.initial_reads)
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 33 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NwkQ4cL6cFHLwWMouPc:-NwnLaHoD4oTbgwB5180:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cddd76a431f81579c0f85fb6a8c35f0945c576/crates/blockifier/src/concurrency/worker_logic.rs#L33)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please use `StateMaps` directly
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-NvkuS-H2NiEkeACmndA:-Nws8hWl0HMarCbjuzhf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bdc8f01a1add01aab301ae2b057ca1a320cc80fd/crates/blockifier/src/concurrency/worker_logic.rs#L12)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I.e., that it is relevant for transactions that read the sequencer balance before the fee transfer
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 22 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nx6_xrd1ryEhicohHiW:-Nx6_xrd1ryEhicohHiX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/10065f10d748e9e3d7440795d4ec0e273943caef/crates/blockifier/src/concurrency/fee_utils.rs#L22)):*
> ```XML
> pub fn fix_concurrency_fee_transfer_call_info(
>     call_info: &mut CallInfo,
>     sequencer_balance: StarkFelt,
> ```





_Suggestion:_
```XML
pub fn pub fn fill_sequencer_balance_reads(
    fee_transfer_call_info: &mut CallInfo,
    sequencer_balance: StarkFelt,
```
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 40 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nx6_blrAbVE9zhjWRGS:-Nx6_bls1u6K1zeQX2QR:b-afs2tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/10065f10d748e9e3d7440795d4ec0e273943caef/crates/blockifier/src/concurrency/fee_utils.rs#L40)):*
> ```XML
>         "Sequencer balance should be zero"
>     );
>     call_info.storage_read_values[STORAGE_READ_SEQUENCER_BALANCE_INDICES.1] = sequencer_balance;
> ```

Use for loop



_Code quote:_
```XML
    assert_eq!(
        call_info.storage_read_values[STORAGE_READ_SEQUENCER_BALANCE_INDICES.0],
        StarkFelt::ZERO,
        "Sequencer balance should be the zero"
    );
    call_info.storage_read_values[STORAGE_READ_SEQUENCER_BALANCE_INDICES.0] = sequencer_balance;
    assert_eq!(
        call_info.storage_read_values[STORAGE_READ_SEQUENCER_BALANCE_INDICES.1],
        StarkFelt::ZERO,
        "Sequencer balance should be zero"
    );
    call_info.storage_read_values[STORAGE_READ_SEQUENCER_BALANCE_INDICES.1] = sequencer_balance;
```
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 43 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nx6ZBQzBbq2-3f_BHMn:-Nx6ZBQzBbq2-3f_BHMo:brz3ac9) ([raw file](https://github.com/starkware-libs/blockifier/blob/10065f10d748e9e3d7440795d4ec0e273943caef/crates/blockifier/src/concurrency/fee_utils.rs#L43)):*
> ```XML
> }
> 
> pub fn create_fee_transfer_call_data<S: StateReader>(
> ```

Why here and not in some test util file?

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 35 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nx6agGREghatGkNXw9G:-Nx6agGREghatGkNXw9H:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/10065f10d748e9e3d7440795d4ec0e273943caef/crates/blockifier/src/concurrency/worker_logic.rs#L35)):*
> ```XML
> 
>     let new_state_cache =
>         &mut StateMaps { storage: sequencer_balance_storage_reads, ..StateMaps::default() };
> ```





_Suggestion:_
```XML
    let state_reads =
        &mut StateMaps { storage: sequencer_balance_storage_reads, ..StateMaps::default() };
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 42 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nx6aZmI6tHhgiqbPL7x:-Nx6aZmI6tHhgiqbPL7y:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/10065f10d748e9e3d7440795d4ec0e273943caef/crates/blockifier/src/concurrency/worker_logic.rs#L42)):*
> ```XML
>         .expect("failed to lock state in revalidate_sequencer_balance_reads")
>         .validate_read_set(tx_index, new_state_cache)
> }
> ```





_Suggestion:_
```XML
        .pin_version(tx_index)
        .state()
        .validate_read_set(tx_index, new_state_cache)
}
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: 1 of 7 files reviewed, 7 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 22 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nx6_xrd1ryEhicohHiW:-Nx76fgYBzMO2tKeRNxQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/10065f10d748e9e3d7440795d4ec0e273943caef/crates/blockifier/src/concurrency/fee_utils.rs#L22)):*
> ```XML
> pub fn fix_concurrency_fee_transfer_call_info(
>     call_info: &mut CallInfo,
>     sequencer_balance: StarkFelt,
> ```

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 40 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nx6_blrAbVE9zhjWRGS:-Nx76hDF9tNn_yWKElbp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/10065f10d748e9e3d7440795d4ec0e273943caef/crates/blockifier/src/concurrency/fee_utils.rs#L40)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use for loop
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 43 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nx6ZBQzBbq2-3f_BHMn:-Nx6wXbZE2OGwL7MmX_T:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/10065f10d748e9e3d7440795d4ec0e273943caef/crates/blockifier/src/concurrency/fee_utils.rs#L43)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why here and not in some test util file?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 148 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nx6bXK02CR-lxdX3pj2:-Nx6wZmh7zQ9uzBkmFei:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/10065f10d748e9e3d7440795d4ec0e273943caef/crates/blockifier/src/fee/fee_utils.rs#L148)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1802)* status: all files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 13 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1802#-Nx7SLGu0dYHVH19CA9O:-Nx7SLGu0dYHVH19CA9P:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/37dc426610c6eb42fad35cf18b224c26d644769b/crates/blockifier/src/concurrency/worker_logic.rs#L13)):*
> ```XML
> // All transactions update the sequencer balance only when they are committed.
> // These changes are not visible to other transactions during execution and validation.
> // Therefore, revalidation of these reads is needed before committing a transaction.
> ```





_Suggestion:_
```XML
/// Checks that the sequencer balance reads made by a given transaction are still valid.
/// All transactions update the sequencer balance (with the required fee) only when they are committed.
/// These changes are not visible to other transactions during execution and validation.
/// Therefore, revalidation of these reads is needed before committing a transaction.
```

**Pull request closed without merging**
