### PR TITLE
test(fee): transaction execution info summarize info for bouncer test

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr5anD0BwO_G-HZhRm-:-Nr5anD0BwO_G-HZhRm0:bdss0af) (no related file):*
Summarize function's PR:
https://reviewable.io/reviews/starkware-libs/blockifier/1533

___

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9OHOnCT3E9vVXixg6:-Nr9OHOnCT3E9vVXixg7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L53)):*
> ```XML
> }
> 
> fn create_classhash_hashset(
> ```





_Suggestion:_
```XML
fn create_class_hash_set(
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9Qf6xDbnQU_a12GYE:-Nr9Qf6xDbnQU_a12GYF:b-yrku4o) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L56)):*
> ```XML
>     class_hash1: ClassHash,
>     class_hash2: ClassHash,
>     class_hash3: ClassHash,
> ```

Consider using a vector as an argument.
It would simplify the implementation.



_Code quote:_
```XML
    class_hash1: ClassHash,
    class_hash2: ClassHash,
    class_hash3: ClassHash,
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9PtaHBBQbTPV4w98A:-Nr9PtaHBBQbTPV4w98B:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L65)):*
> ```XML
> }
> 
> fn create_storage_key_hashset(
> ```





_Suggestion:_
```XML
fn create_storage_key_set(
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9S6D81-863_prub3u:-Nr9S6D81-863_prub3v:bfhldg1) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L68)):*
> ```XML
>     storage_key1: StorageKey,
>     storage_key2: Option<StorageKey>,
>     storage_key3: Option<StorageKey>,
> ```

Why can this one be optional?



_Code quote:_
```XML
    storage_key2: Option<StorageKey>,
    storage_key3: Option<StorageKey>,
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9Pw1I5LV69A7BvmtK:-Nr9Pw1I5LV69A7BvmtL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L81)):*
> ```XML
> }
> 
> fn create_contract_address_storage_key_hashset(
> ```





_Suggestion:_
```XML
fn create_contract_address_storage_key_set(
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9SCEN27mU8xGgfQ79:-Nr9SCEN27mU8xGgfQ7A:b-396dwh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L98)):*
> ```XML
> 
> #[derive(Debug, Default)]
> struct CallInfoParameters {
> ```

Can you think of a different name?
Maybe something related to the summarize method?



_Code quote:_
```XML
struct CallInfoParameters {
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9SWcX79xCTZSoSYQB:-Nr9SWcX79xCTZSoSYQC:bgki893) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L121)):*
> ```XML
> }
> 
> fn create_call_info(params: &CallInfoParameters) -> CallInfo {
> ```

What do you think about moving it under `impl`?
It would receive `self` as an argument.



_Code quote:_
```XML
fn create_call_info(params: &CallInfoParameters) -> CallInfo {
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9OHOnCT3E9vVXixg6:-Nr9xRTe-01-Yzog-Bwb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L53)):*
> ```XML
> }
> 
> fn create_classhash_hashset(
> ```

Done.
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9Qf6xDbnQU_a12GYE:-NrA3m-d2je2Hx4qM1UL:bdlv6fp) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L56)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Consider using a vector as an argument.
It would simplify the implementation.
</blockquote></details>

Removed this function
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9PtaHBBQbTPV4w98A:-Nr9xWyD0suctSBFsiHS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L65)):*
> ```XML
> }
> 
> fn create_storage_key_hashset(
> ```

Done.
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9S6D81-863_prub3u:-NrA3inG9rZS7KBkmTar:b-rj0gu6) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L68)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why can this one be optional?
</blockquote></details>

Changes to something else
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9Pw1I5LV69A7BvmtK:-Nr9xbYH2wXNlAoDoZGY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L81)):*
> ```XML
> }
> 
> fn create_contract_address_storage_key_hashset(
> ```

Done.
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9SWcX79xCTZSoSYQB:-NrA3heuB1Lm2Ub_9lW5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L121)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What do you think about moving it under `impl`?
It would receive `self` as an argument.
</blockquote></details>

Done.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-NrAMMfoCJYDght8n7VM:-NrAMMfoCJYDght8n7VN:b-6g8yny) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c88e23cc893b366bbfd656c83498f25a1a3e91e/crates/blockifier/src/execution/call_info.rs#L238)):*
> ```XML
>     }
> 
>     pub fn create_call_info_for_testing(params: &ExecutionSummaryParameters) -> Self {
> ```

What do you think about moving it under the `impl` of `EXecutionSummaryParameter`?
Something like this:
pub fn create_call_info_for_testing(&self) -> CallInfo



_Code quote:_
```XML
    pub fn create_call_info_for_testing(params: &ExecutionSummaryParameters) -> Self {
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-NrAMMfoCJYDght8n7VM:-NrB-N-M7IokrDy03k8i:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c88e23cc893b366bbfd656c83498f25a1a3e91e/crates/blockifier/src/execution/call_info.rs#L238)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What do you think about moving it under the `impl` of `EXecutionSummaryParameter`?
Something like this:
pub fn create_call_info_for_testing(&self) -> CallInfo
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-Nr9SWcX79xCTZSoSYQB:-NrB-MT24-mip-78ciot:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f1952ad3e276dd431508c1fff55ff420577d818/crates/blockifier/src/transaction/objects_test.rs#L121)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please see my comment above.
</blockquote></details>

Done.

**Review by OriStarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-NrBC9E25uLLUEGKysxn:-NrBC9E25uLLUEGKysxo:b-8lc0qc) ([raw file](https://github.com/starkware-libs/blockifier/blob/2f5de2a19c60b6aa8a520c7d4f60c6a10c30ca88/crates/blockifier/src/execution/call_info.rs#L107)):*
> ```XML
> 
> #[derive(Debug, Default)]
> pub struct ExecutionSummaryParameters {
> ```

Consider renaming to TestExecutionSummary.



_Code quote:_
```XML
ExecutionSummaryParameters
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 129 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-NrB1cOl9unevHgG5rMD:-NrBCE4bAGr2TpY4Ey7i:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2f5de2a19c60b6aa8a520c7d4f60c6a10c30ca88/crates/blockifier/src/execution/call_info.rs#L129)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please use self instead.
</blockquote></details>

Done.

**Review by OriStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-:-NrBGjN5A_KawB24cAFL:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

**Review by OriStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-:-NrGUqpoEd38fNf2C3Bh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by OriStarkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1560#-:-Nrj3VLW2ZOE8CmarMBm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Pull request merged**
