### PR TITLE
test: add stack trace regressions tests in Cairo1 for various call chains

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1367)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1367)* status: all files reviewed, 4 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 400 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-NoqBO_y1IXcPCFOG4uj:-NoqBO_y1IXcPCFOG4uk:b-wg8ku4) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa760064db69c353ff1f5bcae762b4fcd21b4a5e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L400)):*
> ```Cairo
>                 fail(ref self);
>             }
>         }
> ```

assert inputs are as expected? not sure what the cairo1 syntax should be



_Suggestion:_
```Cairo
        } else {
            assert call_type == 2;
            let invoke_call_chain_selector: felt252 =
                0x0062c83572d28cb834a3de3c1e94977a4191469a4a8c26d1d7bc55305e640ed5;
            let fail_selector: felt252 =
                0x032564d7e0fe091d49b4c20f4632191e4ed6986bf993849879abfef9465def25;
            if function_selector == invoke_call_chain_selector {
                return invoke_call_chain(ref self, call_chain);
            }
            else {
                assert function_selector == fail_selector;
                fail(ref self);
            }
        }
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 705 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-NoqEI8YEuZmvddKeEOs:-NoqEI8YEuZmvddKeEOt:b-hccr1l) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa760064db69c353ff1f5bcae762b4fcd21b4a5e/crates/blockifier/src/execution/entry_point_test.rs#L705)):*
> ```XML
> Got an exception while executing a hint: Hint Error: Execution failed. Failure reason: {}.
> Cairo traceback (most recent call last):
> Unknown location (pc=0:2561)
> ```

what do these PC locations refer to?
can you compute them via relative offset to some named PC value taken from the compiled artifact?



_Code quote:_
```XML
Error at pc=0:7981:
Got an exception while executing a hint: Hint Error: Execution failed. Failure reason: {}.
Cairo traceback (most recent call last):
Unknown location (pc=0:2561)
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 721 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-NoqEPF7BWA9AzvZsc9R:-NoqEPF7BWA9AzvZsc9S:bs6wkmu) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa760064db69c353ff1f5bcae762b4fcd21b4a5e/crates/blockifier/src/execution/entry_point_test.rs#L721)):*
> ```XML
> #[case("fail", "0x6661696c ('fail')", 0_u8)]
> fn test_trace_call_chain_with_syscalls(
>     #[values((0_u8, 7981_u16), (1_u8, 8070_u16))] call_type_expected_pc: (u8, u16),
> ```

see above comment about PC locations: if you take offsets from named PC values from the compiled contract artifact; you may be able to infer the correct PC just by call type,
and then you'll only need `#[values(0_u8, 1_u8)] call_type: u8` (plus you'll have a more robust test).



_Code quote:_
```XML
#[values((0_u8, 7981_u16), (1_u8, 8070_u16))] call_type_expected_pc: (u8, u16),
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 753 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-NoqDcUj5xLVqpayDLVi:-NoqDcUj5xLVqpayDLVj:b-qxpjdk) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa760064db69c353ff1f5bcae762b4fcd21b4a5e/crates/blockifier/src/execution/entry_point_test.rs#L753)):*
> ```XML
>     if last_func_name == "invoke_call_chain" {
>         calldata.push(stark_felt!(0_u8));
>     }
> ```

TAL at `create_calldata`; it could save you some boilerplate (and you won't need the `calldata_extra_length` parameter).
Non-blocking, I'm not sure this is the correct calldata format for direct entry point execution.



_Suggestion:_
```XML
    let mut parameters = vec![
        invoke_call_chain_selector.0,              // Function selector.
        stark_felt!(0_u8),                         // Call type: call_contract_syscall.
        stark_felt!(3_u8 + calldata_extra_length), // Calldata length
        contract_id,                               // Contract address / class hash.
        selector_from_name(last_func_name).0,      // Function selector.
        stark_felt!(call_type),                    // Syscall type: library_call or call_contract.
    ];

    // Need to send an empty array for the last call in `invoke_call_chain` variant.
    if last_func_name == "invoke_call_chain" {
        calldata.push(stark_felt!(0_u8));
    }

    let calldata = create_calldata(address, "invoke_call_chain", parameters);
```

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1367)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 400 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-NoqBO_y1IXcPCFOG4uj:-NoqQ3CxCXSoAr0g19YM:bew9nis) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa760064db69c353ff1f5bcae762b4fcd21b4a5e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L400)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

assert inputs are as expected? not sure what the cairo1 syntax should be
</blockquote></details>

I think returning zero is fine in this case. I don't see an added value in asserting here.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 705 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-NoqEI8YEuZmvddKeEOs:-NoquQHY8pLGZ1wD1Nhf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa760064db69c353ff1f5bcae762b4fcd21b4a5e/crates/blockifier/src/execution/entry_point_test.rs#L705)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what do these PC locations refer to?
can you compute them via relative offset to some named PC value taken from the compiled artifact?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 721 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-NoqEPF7BWA9AzvZsc9R:-NoqttmzCKvtuolPp3f7:b9pd1dr) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa760064db69c353ff1f5bcae762b4fcd21b4a5e/crates/blockifier/src/execution/entry_point_test.rs#L721)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above comment about PC locations: if you take offsets from named PC values from the compiled contract artifact; you may be able to infer the correct PC just by call type,
and then you'll only need `#[values(0_u8, 1_u8)] call_type: u8` (plus you'll have a more robust test).
</blockquote></details>

actually managed to get anything but this (for now)
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 753 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-NoqDcUj5xLVqpayDLVi:-NoqQUGF4k-liseYS2_M:b-m6btvk) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa760064db69c353ff1f5bcae762b4fcd21b4a5e/crates/blockifier/src/execution/entry_point_test.rs#L753)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

TAL at `create_calldata`; it could save you some boilerplate (and you won't need the `calldata_extra_length` parameter).
Non-blocking, I'm not sure this is the correct calldata format for direct entry point execution.
</blockquote></details>

It didn't work for this case. I tried it initially.
It'd still need the extra length param, it's needed both in the beginning (which works, if all items are known in advance) and in the middle (which `create_calldata` definitely can't manage conditionally)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1367)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 400 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-NoqBO_y1IXcPCFOG4uj:-Nor1GLE5innA1GqrdbW:bq0dplk) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa760064db69c353ff1f5bcae762b4fcd21b4a5e/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L400)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

I think returning zero is fine in this case. I don't see an added value in asserting here.
</blockquote></details>

currently if I send `call_type=7` I will get behavior equivalent to `call_type=2`; this is confusing (not terrible but confusing).
and if (when sending `call_type=7` the function just returns zero, this is also confusing; no?
(about the function selectors - yeah you're right, it's pretty self-documenting as it is now)
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 721 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-NoqEPF7BWA9AzvZsc9R:-Nor0GZvBYzH5Zrmt6Fm:bbsmstn) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa760064db69c353ff1f5bcae762b4fcd21b4a5e/crates/blockifier/src/execution/entry_point_test.rs#L721)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

actually managed to get anything but this (for now)
</blockquote></details>

hmm...
maybe a solution would be to (not now) create an account transaction and run it. not sure we want to unravel how `execute_directly` works just to understand this value.
unblocking
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 553 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-Nor-RgfCsulIBXSdP0b:-Nor-RgfCsulIBXSdP0c:b-qyzwzu) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dd343c315f0989e2750e6c0331a4ee32a62066f/crates/blockifier/src/execution/entry_point_test.rs#L553)):*
> ```XML
>     // Fetch PC locations from the compiled contract to compute the expected PC locations in the
>     // traceback. Computation is not robust, but as long as the cairo function itself is not edited,
>     // this computation should be stable.
> ```

rust-style docstring



_Suggestion:_
```XML
/// Fetch PC locations from the compiled contract to compute the expected PC locations in the
/// traceback. Computation is not robust, but as long as the cairo function itself is not edited,
/// this computation should be stable.
fn get_entry_point_offset(
    contract_class: &ContractClass,
    entry_point_selector: EntryPointSelector,
) -> EntryPointOffset {
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 714 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-Nor0qHyDXMyfHkWkVg1:-Nor0qHyDXMyfHkWkVg2:bcd0cpw) ([raw file](https://github.com/starkware-libs/blockifier/blob/5dd343c315f0989e2750e6c0331a4ee32a62066f/crates/blockifier/src/execution/entry_point_test.rs#L714)):*
> ```XML
>     let entry_point_offset =
>         get_entry_point_offset(&test_contract.get_class(), entry_point_call.entry_point_selector);
>     let pc_location = entry_point_offset.0 + 65;
> ```

this `65` appears twice.
low hanging fruit - give this a named constant? maybe `INNER_CALL_CONTRACT_IN_CALL_CHAIN_OFFSET` or something...
(these magic number tend to multiply if not aggressively fought in advance..)



_Code quote:_
```XML
let pc_location = entry_point_offset.0 + 65;
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1367#-:-Nor5JED05fJqO4INRib:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
