### PR TITLE
refactor(execution, native_blockifier): decouple BouncerInfo from Python

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1428#-NpoxYeu3ydTmKAGy59H:-NpoxYeu3ydTmKAGy59I:b-8uixar) ([raw file](https://github.com/starkware-libs/blockifier/blob/719591434bfc1205bd8a05eccc3bc03b159c5ed6/crates/native_blockifier/src/py_transaction_execution_info.rs#L221)):*
> ```XML
> // TODO(Barak, 24/01/2024): Move to blockifier crate.
> // TODO(Ayelet, 24/01/2024): Consider remove message_segment_length, state_diff_size.
> pub struct BouncerInfo {
> ```

Move to `blockifier` crate?



_Code quote:_
```XML
pub struct BouncerInfo
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1428#-NprqfUh67h_aHCRWx5V:-NprqfUh67h_aHCRWx5W:bta0nby) (no related file):*
Python PR?

___

**Review by Yoni-Starkware — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428#-:-NpsST0s-n6PWFMRiMCk:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1428#-NpoxYeu3ydTmKAGy59H:-NptgiANAqWz35dZlyHZ:b-1lx7gs) ([raw file](https://github.com/starkware-libs/blockifier/blob/719591434bfc1205bd8a05eccc3bc03b159c5ed6/crates/native_blockifier/src/py_transaction_execution_info.rs#L221)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move to `blockifier` crate?
</blockquote></details>

Can we move code later?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1428#-NpoxYeu3ydTmKAGy59H:-Nptu_uW2vbY79lBii9o:bm9rk78) ([raw file](https://github.com/starkware-libs/blockifier/blob/719591434bfc1205bd8a05eccc3bc03b159c5ed6/crates/native_blockifier/src/py_transaction_execution_info.rs#L221)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can we move code later?
</blockquote></details>

It's not moving, it's a new struct.

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1428)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
