### PR TITLE
fix(concurrency): assert no concurrency mode in sequential run

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1987)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1987)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1987#-O-a3NtvDFn1pS38Ty3J:-O-a3NtvDFn1pS38Ty3K:bdog02i) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e576843d9d2d08f6d7cdc9cba7aeb62e29e3ea6/crates/blockifier/src/blockifier/transaction_executor.rs#L62)):*
> ```XML
>         block_state: CachedState<S>,
>         block_context: BlockContext,
>         config: TransactionExecutorConfig,
> ```

Assert consistency between these two



_Code quote:_
```XML
        block_context: BlockContext,
        config: TransactionExecutorConfig,
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1987)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1987#-O-a48lE2ImgD09Skx5e:-O-a48lE2ImgD09Skx5f:b-kpsxql) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e576843d9d2d08f6d7cdc9cba7aeb62e29e3ea6/crates/blockifier/src/test_utils/transfers_generator.rs#L119)):*
> ```XML
> }
> 
> impl Default for TransfersGenerator {
> ```

Are you using this?



_Code quote:_
```XML
impl Default for TransfersGenerator {
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1987#-:-O-a8PIpBU9tzpqLsjzE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1987)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 269 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1987#-O-oxEqY1lNsfu0NJ0BY:-O-oxEqZ5UQ1AP-l1vf3:b6wbt0t) ([raw file](https://github.com/starkware-libs/blockifier/blob/790222bf925a2f1bc4d25792b81d8b57a6af6160/crates/blockifier/src/blockifier/transaction_executor_test.rs#L269)):*
> ```XML
> fn test_execute_txs_bouncing() {
>     let config = TransactionExecutorConfig::create_for_testing();
>     dbg!(&config);
> ```

Intentional?



_Code quote:_
```XML
dbg!(&config);
```
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1987#-O-a48lE2ImgD09Skx5e:-O-oxnwJ0Guz8gU6BLYy:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e576843d9d2d08f6d7cdc9cba7aeb62e29e3ea6/crates/blockifier/src/test_utils/transfers_generator.rs#L119)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Are you using this?
</blockquote></details>

?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1987)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 269 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1987#-O-oxEqY1lNsfu0NJ0BY:-O-peaou4KxpHztv-Ka3:b-knkl1c) ([raw file](https://github.com/starkware-libs/blockifier/blob/790222bf925a2f1bc4d25792b81d8b57a6af6160/crates/blockifier/src/blockifier/transaction_executor_test.rs#L269)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Intentional?
</blockquote></details>

No. Thanks!
___
*[`crates/blockifier/src/test_utils/transfers_generator.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1987#-O-a48lE2ImgD09Skx5e:-O-peUzv4XCykJzVCTW0:btg71y9) ([raw file](https://github.com/starkware-libs/blockifier/blob/8e576843d9d2d08f6d7cdc9cba7aeb62e29e3ea6/crates/blockifier/src/test_utils/transfers_generator.rs#L119)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

?
</blockquote></details>

I'm not, but clippy is asking for this (for structs with a`new()` method with no arguments)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1987#-:-O02NfWFDrDdJKNn9j-L:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
