### PR TITLE
Added test_calculate_tx_gas_usage_basic.

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/413)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware +reviewer:@noaov1 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/413#-:-NT8QjVN6bfHTUFVzPTE:bd7uazw)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/413)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/413#-NT8S1T_DWa132k3ENwc:-NT8S1T_DWa132k3ENwd:bgwvtsh) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c7b2010fde43a2705ccd35472ba78d970790f97/crates/blockifier/src/fee/gas_usage_test.rs#L10)):*
> ```XML
> /// This test goes over five cases. In each case, we calculate the gas usage given the parameters.
> /// We then perform the same calculation manually, each time using only the relevant parameters.
> ```

drop the newline (I have a feeling any autodocing for functions would rely on a continuous `///`-led block of text)
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/413#-NT8SvXX-PaS3XFWpine:-NT8SvXY2LiSPr23qwHs:bjoo5qj) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c7b2010fde43a2705ccd35472ba78d970790f97/crates/blockifier/src/fee/gas_usage_test.rs#L18)):*
> ```XML
> ///     5. A combination of cases 2. 3. and 4.
> #[test]
> fn test_calculate_tx_gas_usage_basic() {
> ```

for all hard-coded, non-zero values; could you either name them and / or comment about them?
i.e. the `2` in `deploy_gas_usage` could use a name (or comment), `n_modified_contracts = 7` could use a comment, etc.



_Code quote:_
```XML
test_calculate_tx_gas_usage_basic
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/413)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/413#-NT8S1T_DWa132k3ENwc:-NT8YzH54R3wnZqYUI9P:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c7b2010fde43a2705ccd35472ba78d970790f97/crates/blockifier/src/fee/gas_usage_test.rs#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

drop the newline (I have a feeling any autodocing for functions would rely on a continuous `///`-led block of text)
</blockquote></details>

Done
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/413#-NT8SvXX-PaS3XFWpine:-NT8Z3YV5odrc8S6YQfN:b-pv4lk1) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c7b2010fde43a2705ccd35472ba78d970790f97/crates/blockifier/src/fee/gas_usage_test.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

for all hard-coded, non-zero values; could you either name them and / or comment about them?
i.e. the `2` in `deploy_gas_usage` could use a name (or comment), `n_modified_contracts = 7` could use a comment, etc.
</blockquote></details>

I named non-zero values (found 2).
Are you sure `n_modified_contracts` needs a comment? I think it's just an arbitrary value used to test the gas calculation (it's a bit surprising that it's used in more than one case, but I think this is because the second case is a combination of previous cases).

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/413#-:-NT8dMr8BlVrJw9eyra5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/413#-NT8SvXX-PaS3XFWpine:-NT8dJ7h-xWqERRXsLrX:b-xooybw) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c7b2010fde43a2705ccd35472ba78d970790f97/crates/blockifier/src/fee/gas_usage_test.rs#L18)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I named non-zero values (found 2).
Are you sure `n_modified_contracts` needs a comment? I think it's just an arbitrary value used to test the gas calculation (it's a bit surprising that it's used in more than one case, but I think this is because the second case is a combination of previous cases).
</blockquote></details>

ah... didn't realize it's arbitrary, ok then

**Pull request merged**
