### PR TITLE
Prepare segment arena Segment

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/465)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/465)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVAOTCr99C8WrlSEi_G:-NVAOTCr99C8WrlSEi_H:b-eijurk) ([raw file](https://github.com/starkware-libs/blockifier/blob/e38b3b2d498c20cd6ecc4940cd54a4c9a3869209/crates/blockifier/src/execution/cairo1_execution.rs#L154)):*
> ```XML
>             args.extend(builtin.initial_stack().into_iter().map(CairoArg::Single));
>             continue;
>         }
> ```

Remove `unwrap`s?
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVAOx0d44nm-1Lr6jML:-NVAOx0d44nm-1Lr6jMM:budx9nd) ([raw file](https://github.com/starkware-libs/blockifier/blob/e38b3b2d498c20cd6ecc4940cd54a4c9a3869209/crates/blockifier/src/execution/cairo1_execution.rs#L164)):*
> ```XML
>             write_felt(vm, &mut ptr, StarkFelt::default()).unwrap();
>             write_felt(vm, &mut ptr, StarkFelt::default()).unwrap();
>             args.push(CairoArg::Single(segment_arena.into()));
> ```

WDYT? Names instead of comments.
Same Q as in the other PR: why only start ptr and no length? How do you know how to parse?



_Suggestion:_
```XML
            
            let segment_arena = vm.add_memory_segment();
            
            // Write into segment arena.
            let mut ptr = segment_arena;
            let info_segment_start_ptr = vm.add_memory_segment();
            let n_constructed = StarkFelt::default();
            let n_destructed = StarkFelt::default();
            write_maybe_relocatable(vm, &mut ptr, info_segment_start_ptr)?;
            write_felt(vm, &mut ptr, n_constructed)?;
            write_felt(vm, &mut ptr, n_destructed)?;
            args.push(CairoArg::Single(segment_arena.into()));
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVAOGU915-UIq3AOXFH:-NVAOGU915-UIq3AOXFI:b-9ibt2t) ([raw file](https://github.com/starkware-libs/blockifier/blob/e38b3b2d498c20cd6ecc4940cd54a4c9a3869209/crates/blockifier/src/execution/cairo1_execution.rs#L195)):*
> ```XML
> ) -> Result<(), VirtualMachineExecutionError> {
>     // We write at the end of the program segment, which fails secure verification.
>     let verify_secure = false;
> ```

What checks won't be done?
Isn't it dangerous for other segments?



_Code quote:_
```XML
let verify_secure = false;
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 495 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVAO2rsCq9H1fkUpooD:-NVAO2rsCq9H1fkUpooE:bzhrwc6) ([raw file](https://github.com/starkware-libs/blockifier/blob/e38b3b2d498c20cd6ecc4940cd54a4c9a3869209/crates/blockifier/src/execution/entry_point_test.rs#L495)):*
> ```XML
> 
>     let res = entry_point_call.execute_directly(&mut state);
>     assert!(res.is_ok());
> ```

:heart_eyes: 



_Code quote:_
```XML
assert!(res.is_ok());
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/465)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVAOGU915-UIq3AOXFH:-NVAXPkM8O2dAAc4Enra:bitvqr3) ([raw file](https://github.com/starkware-libs/blockifier/blob/e38b3b2d498c20cd6ecc4940cd54a4c9a3869209/crates/blockifier/src/execution/cairo1_execution.rs#L195)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What checks won't be done?
Isn't it dangerous for other segments?
</blockquote></details>

Maybe, but right now I don't have any other option. We can ask LC to do something about this.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/465)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVAOGU915-UIq3AOXFH:-NVSwV7h09yQpo68HoRT:bt2vr1b) ([raw file](https://github.com/starkware-libs/blockifier/blob/e38b3b2d498c20cd6ecc4940cd54a4c9a3869209/crates/blockifier/src/execution/cairo1_execution.rs#L195)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Maybe, but right now I don't have any other option. We can ask LC to do something about this.
</blockquote></details>

Fixed.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/465)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @spapinistarkware)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVXxZQg3dTKxedv-C4B:-NVXxZQg3dTKxedv-C4C:b9a04g2) ([raw file](https://github.com/starkware-libs/blockifier/blob/165aa9180fe3c081964ad7ac7967dc841efedcce/crates/blockifier/src/execution/cairo1_execution.rs#L94)):*
> ```XML
>     runner.initialize_builtins(&mut vm)?;
>     runner.initialize_segments(&mut vm, None);
>     let mut read_only_segments = ReadOnlySegments::default();
> ```

Can we also allocate the failure data segment through it?



_Code quote:_
```XML
read_only_segments
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVXx-wZ-skQN8nYGZjz:-NVXx-w_7gHyKX_0-E1w:b-2hlke9) ([raw file](https://github.com/starkware-libs/blockifier/blob/165aa9180fe3c081964ad7ac7967dc841efedcce/crates/blockifier/src/execution/cairo1_execution.rs#L95)):*
> ```XML
>     runner.initialize_segments(&mut vm, None);
>     let mut read_only_segments = ReadOnlySegments::default();
>     let program_segment_size =
> ```

Isn't this the builtin costs segment? Or do you plan to perhaps add to it more things in the future?



_Code quote:_
```XML
program_segment_size
```
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 132 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVXxg0XDPwJAlfON65l:-NVXxg0XDPwJAlfON65m:b27miyr) ([raw file](https://github.com/starkware-libs/blockifier/blob/165aa9180fe3c081964ad7ac7967dc841efedcce/crates/blockifier/src/execution/cairo1_execution.rs#L132)):*
> ```XML
>         data.push(0.into());
>     }
>     let builtin_cost_segment_start = read_only_segments.allocate(vm, &data)?;
> ```

Segment allocation is different in Cairo 1; can you add a method for writing `[start, end]`?



_Code quote:_
```XML
read_only_segments.allocate(vm, &data)?;
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/465)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVXxZQg3dTKxedv-C4B:-NVc6P4t5F48AbtMyP9B:b-byv0oy) ([raw file](https://github.com/starkware-libs/blockifier/blob/165aa9180fe3c081964ad7ac7967dc841efedcce/crates/blockifier/src/execution/cairo1_execution.rs#L94)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we also allocate the failure data segment through it?
</blockquote></details>

The failure segment data is actually supposed to be changable by the user, so it's not RO.
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVXx-wZ-skQN8nYGZjz:-NVc6b5mBeY2pprWzFBP:b-q2ushr) ([raw file](https://github.com/starkware-libs/blockifier/blob/165aa9180fe3c081964ad7ac7967dc841efedcce/crates/blockifier/src/execution/cairo1_execution.rs#L95)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't this the builtin costs segment? Or do you plan to perhaps add to it more things in the future?
</blockquote></details>

This is the program size after adding 2 felts at the end for the builtin costs ptr. It could change in the future.
___
*[`crates/blockifier/src/execution/cairo1_execution.rs` line 132 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/465#-NVXxg0XDPwJAlfON65l:-NVc77Tc24Tlwn5lcyPS:bzbzz1m) ([raw file](https://github.com/starkware-libs/blockifier/blob/165aa9180fe3c081964ad7ac7967dc841efedcce/crates/blockifier/src/execution/cairo1_execution.rs#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Segment allocation is different in Cairo 1; can you add a method for writing `[start, end]`?
</blockquote></details>

Sounds a bit too early.
I don't see any 2 places that use the same logic, let alone 3.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/465#-:-NVctLdmBZXyEQ38EQCC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/465).

**Comment by spapinistarkware** [comment]
@spapinistarkware merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/465).

**Pull request merged**
