### PR TITLE
feat: implement and test deploy syscall ctor stack trace

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1849)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1849)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @avi-starkware, @barak-b-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 482 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhJ1F83jgFpS9vFQyq:-NxhJ1F83jgFpS9vFQyr:br7w80x) ([raw file](https://github.com/starkware-libs/blockifier/blob/56eec34915c257952c18fa11c2747bae0275503e/crates/blockifier/src/transaction/account_transactions_test.rs#L482)):*
> ```XML
> /// Tests that hitting an execution error in an account contract constructor outputs the correct
> /// traceback (including correct class hash, contract address and constructor entry point selector).
> fn test_account_ctor_frame_stack_trace(
> ```

@avi-starkware FYI: this is the test for the same stack trace in the `DeployAccount` case (non-syscall deployment)



_Code quote:_
```XML
#[rstest]
/// Tests that hitting an execution error in an account contract constructor outputs the correct
/// traceback (including correct class hash, contract address and constructor entry point selector).
fn test_account_ctor_frame_stack_trace(
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/execution/errors.rs` line 399 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhKZBC-SpHI7L8hTPP:-NxhKZBC-SpHI7L8hTPQ:buhjru9) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/execution/errors.rs#L399)):*
> ```XML
>             extract_entry_point_execution_error_into_stack_trace(
>                 error_stack,
>                 depth,
> ```

Why is it not `depth+1` here, as in the cases above?



_Code quote:_
```XML
                depth,
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/execution/errors.rs` line 464 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhLgXO73WJj2CllzrX:-NxhLgXP1aJEKJlIvE62:buhjru9) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/execution/errors.rs#L464)):*
> ```XML
>             extract_entry_point_execution_error_into_stack_trace(
>                 error_stack,
>                 depth,
> ```

Why is it not `depth+1` here, as in the cases above?



_Code quote:_
```XML
                depth,
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1849)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 559 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhQ16X1ze-QTIiRR--:-NxhQ16X1ze-QTIiRR-0:bewowfj) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/transaction/account_transactions_test.rs#L559)):*
> ```XML
> 
>     let salt = stark_felt!(7_u8);
>     let ctor_arg = stark_felt!(1_u8); // validate_constructor arg: set to true to fail deployment.
> ```

It makes the comment clearer.



_Suggestion:_
```XML
   let validate_constructor = FELT_TRUE; // validate_constructor arg: set to true to fail deployment.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 570 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhQxWZ75lbn-RkCbYO:-NxhQxWZ75lbn-RkCbYP:blgtdco) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/transaction/account_transactions_test.rs#L570)):*
> ```XML
> 
>     // Invoke the deploy_contract function on the dummy account to deploy the faulty contract.
>     let invoke_deploy_tx = account_invoke_tx(invoke_tx_args! {
> ```

Why did you set `max_fee: Fee(BALANCE)` in the `DeployAccount` test, but here you keep it at default?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 575 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhUG1c4OGx7gUdc6q6:-NxhUG1c4OGx7gUdc6q7:bqo82ju) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/transaction/account_transactions_test.rs#L575)):*
> ```XML
>         calldata: create_calldata(
>             account_address,
>             "deploy_contract",
> ```

Add `DEPLOY_CONTRACT_ENTRY_POINT_NAME` to `constants`.



_Suggestion:_
```XML
            DEPLOY_CONTRACT_ENTRY_POINT_NAME,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 589 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhU3B-1GUlE0pNEGXN:-NxhU3B-1GUlE0pNEGXO:bqo82ju) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/transaction/account_transactions_test.rs#L589)):*
> ```XML
>     // Construct expected output.
>     let execute_selector = selector_from_name(EXECUTE_ENTRY_POINT_NAME);
>     let deploy_contract_selector = selector_from_name("deploy_contract");
> ```

Add `DEPLOY_CONTRACT_ENTRY_POINT_NAME` to `constants`.



_Suggestion:_
```XML
    let deploy_contract_selector = selector_from_name(DEPLOY_CONTRACT_ENTRY_POINT_NAME);
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 482 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhJ1F83jgFpS9vFQyq:-NxhUqIM8mL_bYOQ0xc_:b-ucfknh) ([raw file](https://github.com/starkware-libs/blockifier/blob/56eec34915c257952c18fa11c2747bae0275503e/crates/blockifier/src/transaction/account_transactions_test.rs#L482)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@avi-starkware FYI: this is the test for the same stack trace in the `DeployAccount` case (non-syscall deployment)
</blockquote></details>

Thanks!

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1849)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @dorimedini-starkware, and @TzahiTaub)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1849)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/errors.rs` line 399 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhKZBC-SpHI7L8hTPP:-Nxhd3XE-g2cRwVHNw8h:b-sph9a0) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/execution/errors.rs#L399)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why is it not `depth+1` here, as in the cases above?
</blockquote></details>

the above recursive calls are to `extract_syscall_execution_error_into_stack_trace`, which is indeed a new depth.
`extract_entry_point_execution_error_into_stack_trace` extracts the VM portion of the same frame.
Not a perfect setup ATM (why the different behavior on this syscall?), but IMO we shouldn't really redesign until we have a way to test regression against a *reconstructed traceback* (i.e. the output text should include source code quotes).
___
*[`crates/blockifier/src/execution/errors.rs` line 464 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhLgXO73WJj2CllzrX:-Nxhdl9p1I6CGDcKgWDn:byr4ffv) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/execution/errors.rs#L464)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why is it not `depth+1` here, as in the cases above?
</blockquote></details>

see above
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 559 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhQ16X1ze-QTIiRR--:-Nxhc-WvDFOxiztiRfva:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/transaction/account_transactions_test.rs#L559)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

It makes the comment clearer.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 570 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhQxWZ75lbn-RkCbYO:-NxhcUi44pGdY_IP8pid:b-6q78f) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/transaction/account_transactions_test.rs#L570)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why did you set `max_fee: Fee(BALANCE)` in the `DeployAccount` test, but here you keep it at default?
</blockquote></details>

good catch. up until now the test was run in "don't charge" mode (skipping validations)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 575 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhUG1c4OGx7gUdc6q6:-Nxhd0sfEURAhpM9NXox:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/transaction/account_transactions_test.rs#L575)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Add `DEPLOY_CONTRACT_ENTRY_POINT_NAME` to `constants`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 589 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhU3B-1GUlE0pNEGXN:-Nxhd1eo4rB3ueJoKDY7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/transaction/account_transactions_test.rs#L589)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Add `DEPLOY_CONTRACT_ENTRY_POINT_NAME` to `constants`.
</blockquote></details>

Done.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/execution/errors.rs` line 399 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhKZBC-SpHI7L8hTPP:-Nxhq1BfEnY7TL1T918X:bjn43iw) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/execution/errors.rs#L399)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the above recursive calls are to `extract_syscall_execution_error_into_stack_trace`, which is indeed a new depth.
`extract_entry_point_execution_error_into_stack_trace` extracts the VM portion of the same frame.
Not a perfect setup ATM (why the different behavior on this syscall?), but IMO we shouldn't really redesign until we have a way to test regression against a *reconstructed traceback* (i.e. the output text should include source code quotes).
</blockquote></details>

Okay. I didn't even see it's a different function.

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1849)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 570 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhQxWZ75lbn-RkCbYO:-NxhqwdpClxn-U_zsKNz:b-5avls5) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/transaction/account_transactions_test.rs#L570)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

good catch. up until now the test was run in "don't charge" mode (skipping validations)
</blockquote></details>

Should we change it to not skip validations? If not, why change the max fee?

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1849)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dorimedini-starkware, and @TzahiTaub)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1849)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @barak-b-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/errors.rs` line 399 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhKZBC-SpHI7L8hTPP:-NxiGAXEDB88noNVujf7:b-6zbwyu) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/execution/errors.rs#L399)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Okay. I didn't even see it's a different function.
</blockquote></details>

will be slightly better by the end of the stack I hope
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 570 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-NxhQxWZ75lbn-RkCbYO:-NxiFmoh4SUpB1GUH5z0:b-r09mgy) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2f609690bc369796abb817fa3a347b457664e12/crates/blockifier/src/transaction/account_transactions_test.rs#L570)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Should we change it to not skip validations? If not, why change the max fee?
</blockquote></details>

if the blockifier gets a tx with zero max bounds, fee is not enforced.
the fee bound (max fee / max amount for v txs) must be positive for fee to be charged (and validated).
chaning the max fee to positive enforced bounds.
it's not critical (as we get the expected error) but good practice

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1849#-:-NxiLe_71sAl8LeNaudo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @TzahiTaub)

**Pull request merged**
