### PR TITLE
fix: state trait does not require &mut self

### PR DESCRIPTION
**Pull request by tdelabro**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1325)

### CODE REVIEW

**Comment by tdelabro** [comment]
@giladchase can you review this one? And re-run the codecov CI that seems to fail in a way unrelated to my code?

**Comment by tdelabro** [comment]
@giladchase could you review this one?

**Review by giladchase — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1325#-:-NqfFmlh-T7zb8anb4OH:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

___
*[`crates/blockifier/src/state/cached_state.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1325#-Nqf8FCH41pGzYgG9CB0:-Nqf8FCH41pGzYgG9CB1:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f8cbe822574b5656193ce7ca0205d21f91354762/crates/blockifier/src/state/cached_state.rs#L32)):*
> ```XML
>     pub state: S,
>     // Invariant: read/write access is managed by CachedState.
>     cache: RefCell<StateCache>,
> ```





_Suggestion:_
```XML
    // Invariant: read/write access is managed by CachedState.
    // Using interior mutability to update caches during `State`'s immutable getters. 
    cache: RefCell<StateCache>,
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1325#-NqfF6bG9mPaYu_OnW37:-NqfF6bG9mPaYu_OnW38:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f8cbe822574b5656193ce7ca0205d21f91354762/crates/blockifier/src/state/cached_state.rs#L249)):*
> ```XML
>         let class_hash_to_class = &mut *self.class_hash_to_class.borrow_mut();
> 
>         if let std::collections::hash_map::Entry::Vacant(e) = class_hash_to_class.entry(class_hash)
> ```





_Suggestion:_
```XML
        if let std::collections::hash_map::Entry::Vacant(entry) = class_hash_to_class.entry(class_hash)
```

**Review by giladchase — COMMENTED** [review]
Plz rename commits using this format:
```
fix: state trait does not require &mut self // note the first letter after `:` is not capitalized.
chore: remove clippy allow
fix: small review fix
```
Also change the PR title to match the msg of the first commit.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1325#-:-NqgwueKBmWZXkoqpT6R:be26hew)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @tdelabro)

**Review by giladchase — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1325)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1325#-:-NqgzvX71_mYXf1FaFhQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Pull request merged**
