### PR TITLE
Receive a contract class from python in execute.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/280)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/280)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/280#-NOKEVbq4vTc_gp5pdpL:-NOKEVbrDDnAe8DY2DiH:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d8f4c83c2cf2b04dc191252bd3bd0ab04757e2/crates/native_blockifier/src/py_transaction.rs#L130)):*
> ```XML
> pub fn py_tx(
>     tx: &PyAny,
>     tx_type: &str,
> ```





_Suggestion:_
```XML
    tx_type: &str,
    tx: &PyAny,
    contract_class: Option<&str>,
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/280#-NOKEbGyEI12bpQMAlHi:-NOKEbGyEI12bpQMAlHj:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d8f4c83c2cf2b04dc191252bd3bd0ab04757e2/crates/native_blockifier/src/py_transaction.rs#L136)):*
> ```XML
>         "DECLARE" => {
>             let contract_class: ContractClass = serde_json::from_str(&contract_class)
>                 .expect("Deserialize contract class from python.");
> ```





_Suggestion:_
```XML
"Illegal class schema from Python."
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/280#-NOKEJLL5CRgrWUFA6VR:-NOKEJLL5CRgrWUFA6VS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d8f4c83c2cf2b04dc191252bd3bd0ab04757e2/crates/native_blockifier/src/py_transaction.rs#L194)):*
> ```XML
>     pub fn execute(&mut self, tx: &PyAny, contract_class: String) -> PyResult<()> {
>         let tx_type: String = py_enum_name(tx, "tx_type")?;
>         let tx = py_tx(tx, &tx_type, contract_class)?;
> ```





_Suggestion:_
```XML
let tx: Transaction = py_tx(tx, &tx_type, contract_class)?;
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/280)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/280)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/280#-NOKEJLL5CRgrWUFA6VR:-NOKUVfw7muifkzueOEc:betmvt4) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d8f4c83c2cf2b04dc191252bd3bd0ab04757e2/crates/native_blockifier/src/py_transaction.rs#L194)):*
> ```XML
>     pub fn execute(&mut self, tx: &PyAny, contract_class: String) -> PyResult<()> {
>         let tx_type: String = py_enum_name(tx, "tx_type")?;
>         let tx = py_tx(tx, &tx_type, contract_class)?;
> ```

Why do you think it's needed?

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/280)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/280#-NOKEVbq4vTc_gp5pdpL:-NOKjxYr67m-0U9tHPo0:bq8bgvv) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d8f4c83c2cf2b04dc191252bd3bd0ab04757e2/crates/native_blockifier/src/py_transaction.rs#L130)):*
> ```XML
> pub fn py_tx(
>     tx: &PyAny,
>     tx_type: &str,
> ```

Can you pass `tx_type` to be first? I tend to allocate selectors before the actual arguments.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/280#-NOKEJLL5CRgrWUFA6VR:-NOKjnUr-6HGqBL9xf5G:bu6g4z8) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d8f4c83c2cf2b04dc191252bd3bd0ab04757e2/crates/native_blockifier/src/py_transaction.rs#L194)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why do you think it's needed?
</blockquote></details>

I found it less readable without the annotation.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/280#-NOKjXZf4oBGhh59tULg:-NOKjXZf4oBGhh59tULh:b8edils) ([raw file](https://github.com/starkware-libs/blockifier/blob/22847c90d0ffc67449de228d89380aaeeeae1070/crates/native_blockifier/src/py_transaction.rs#L137)):*
> ```XML
>     match tx_type {
>         "DECLARE" => {
>             let non_opt_contract_class =
> ```

I prefer reusing variable names when possible.



_Suggestion:_
```XML
            let contract_class: &str =
                contract_class.expect("A contract class must be passed in a Declare transaction.");
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/280)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/280#-NOKEVbq4vTc_gp5pdpL:-NOODO8XEgO2Xpo-XueN:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d8f4c83c2cf2b04dc191252bd3bd0ab04757e2/crates/native_blockifier/src/py_transaction.rs#L130)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you pass `tx_type` to be first? I tend to allocate selectors before the actual arguments.
</blockquote></details>

Done
___
*[`crates/native_blockifier/src/py_transaction.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/280#-NOKjXZf4oBGhh59tULg:-NOOCwHy6__Bh03Pwwzi:bjrm1z6) ([raw file](https://github.com/starkware-libs/blockifier/blob/22847c90d0ffc67449de228d89380aaeeeae1070/crates/native_blockifier/src/py_transaction.rs#L137)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I prefer reusing variable names when possible.
</blockquote></details>

Done. It can be confusing though because we have another variable named `contract_class` of type `ContractClass`.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/280#-:-NOOHKva0g6htyxykSay:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/280#-NOKjXZf4oBGhh59tULg:-NOOHAcWAlJDOiqfxAmV:bnzrmt1) ([raw file](https://github.com/starkware-libs/blockifier/blob/22847c90d0ffc67449de228d89380aaeeeae1070/crates/native_blockifier/src/py_transaction.rs#L137)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done. It can be confusing though because we have another variable named `contract_class` of type `ContractClass`.
</blockquote></details>

If it's an intermediate towards a final type and represents the same object, I think it can be reused.

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/280)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
