### PR TITLE
refactor: use versioned_constants function when possible

### PR DESCRIPTION
**Pull request by OriStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1508)

### CODE REVIEW

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1508)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1508#-:-NqbMw_w4z3BFjYYurRu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1508)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @OriStarkware and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1508#-NqdRAeK-ZPfBsZyywMo:-NqdRAeK-ZPfBsZyywMp:bqy10gr) (no related file):*
Python check: https://reviewable.io/reviews/starkware-industries/starkware/33991

___

**Review by OriStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1508)* status: all files reviewed, 1 unresolved discussion (waiting on @OriStarkware)

**Pull request merged**
