### PR TITLE
Adjust Invoke transaction to V3 changes in starknet-api.

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`Cargo.toml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Nd9tPKK00prBQgT7EYz:-Nd9tPKK00prBQgT7EZ-:b-eaidc2) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d5fe9ebd93d9d89df566db8a3b1428d0b383190/Cargo.toml#L50)):*
> ```TOML
> 
> [patch.crates-io]
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "572042c" }
> ```

Is this enough to compile? I think Papyrus also needs to be patched.



_Code quote:_
```TOML
[patch.crates-io]
starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "572042c" }
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Nd9tSS_-Cay2gl_V0y6:-Nd9tSS_-Cay2gl_V0y7:b-oz0mcg) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d5fe9ebd93d9d89df566db8a3b1428d0b383190/crates/blockifier/src/transaction/transactions.rs#L308)):*
> ```XML
>     implement_inner_tx_getter_calls!((calldata, Calldata), (signature, TransactionSignature));
> 
>     pub fn max_fee(&self) -> Fee {
> ```

Use above?



_Code quote:_
```XML
pub fn max_fee(&self) -> Fee {
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ndn5Uwi30P4aetp2NMh:-Ndn5Uwi30P4aetp2NMi:b-4eiy72) ([raw file](https://github.com/starkware-libs/blockifier/blob/5596485dd414e9139e06c27c80538a21a66d0c16/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
> ```XML
>                         starknet_api::transaction::InvokeTransaction::V3(tx_v3) => tx_v3.nonce,
>                     },
>                     sender_address: match sn_api_tx {
> ```

Why not use the getter?



_Code quote:_
```XML
sender_address: match sn_api_tx {
```

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @MohammadNassar1)

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ndn5Uwi30P4aetp2NMh:-Ndw-PpjEMkOyU8dO_Md:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5596485dd414e9139e06c27c80538a21a66d0c16/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not use the getter?
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 186 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ne13jyF05bvEyay9Yeq:-Ne13jyF05bvEyay9Yer:bhl771u) ([raw file](https://github.com/starkware-libs/blockifier/blob/6cac0e82f68e50738174f674edad2fc15bc9b521/crates/blockifier/src/transaction/account_transaction.rs#L186)):*
> ```XML
>                     TransactionVersion(StarkFelt::from(0_u8)),
>                     TransactionVersion(StarkFelt::from(1_u8)),
>                     TransactionVersion(StarkFelt::from(3_u8)),
> ```

Use constants? 
___
*[`crates/blockifier/src/transaction/transactions.rs` line 326 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ne13m7r-x8SvqJ5pmxc:-Ne13m7r-x8SvqJ5pmxd:b-wbyamm) ([raw file](https://github.com/starkware-libs/blockifier/blob/6cac0e82f68e50738174f674edad2fc15bc9b521/crates/blockifier/src/transaction/transactions.rs#L326)):*
> ```XML
>             starknet_api::transaction::InvokeTransaction::V3(tx) => {
>                 // TODO(barak, 01/10/2023): Change to max_price_per_unit * block_context.gas_price.
>                 Fee(tx
> ```

Get the resource once, instead of repeating code.
Why is `map_or` needed?
Also, can this code be shared (we can do it after the upgrade).

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 326 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ne13m7r-x8SvqJ5pmxc:-Ne13rP-06adKWohbirt:bv2exuo) ([raw file](https://github.com/starkware-libs/blockifier/blob/6cac0e82f68e50738174f674edad2fc15bc9b521/crates/blockifier/src/transaction/transactions.rs#L326)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Get the resource once, instead of repeating code.
Why is `map_or` needed?
Also, can this code be shared (we can do it after the upgrade).
</blockquote></details>

You can also pass 0 for now, we'll implement after the upgrade.

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 186 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ne13jyF05bvEyay9Yeq:-Ne8K-j_5cYnAIclWqaz:b-1pwxv) ([raw file](https://github.com/starkware-libs/blockifier/blob/6cac0e82f68e50738174f674edad2fc15bc9b521/crates/blockifier/src/transaction/account_transaction.rs#L186)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use constants?
</blockquote></details>

Yes (: I do it once for all txs types in another PR:  
[https://reviewable.io/reviews/starkware-libs/blockifier/904](https://reviewable.io/reviews/starkware-libs/blockifier/904)
___
*[`crates/blockifier/src/transaction/transactions.rs` line 326 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ne13m7r-x8SvqJ5pmxc:-Ne8L_Md3tH3rWIi6ebU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6cac0e82f68e50738174f674edad2fc15bc9b521/crates/blockifier/src/transaction/transactions.rs#L326)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You can also pass 0 for now, we'll implement after the upgrade.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 336 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ne8ScszCrZT-xxjvFmZ:-Ne8Sct-4OseVT2JEXyx:b2zap3j) ([raw file](https://github.com/starkware-libs/blockifier/blob/d37ef192d539f4d63f1fe688a430093ab29a6665/crates/blockifier/src/transaction/transactions.rs#L336)):*
> ```XML
>     pub fn max_fee(&self) -> Fee {
>         match &self.tx {
>             starknet_api::transaction::InvokeTransaction::V0(tx) => tx.max_fee,
> ```

Add a TODO to reuse this getter's code, or even considering moving up to `AccountTransaction`.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 311 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ne8T7_QEDoW4kDavbSG:-Ne8T7_QEDoW4kDavbSH:b19wcwz) ([raw file](https://github.com/starkware-libs/blockifier/blob/d37ef192d539f4d63f1fe688a430093ab29a6665/crates/native_blockifier/src/py_transaction.rs#L311)):*
> ```XML
>                 fee_data_availability_mode: common_tx_fields.fee_data_availability_mode,
>                 paymaster_address: common_tx_fields.paymaster_address,
>                 account_deployment_data: AccountDeploymentData(
> ```

I think we might already have a converter for a collection of felts, check out the adjacent utils file.

**Comment by barak-b-starkware** [comment]
*[`crates/native_blockifier/src/py_transaction.rs` line 311 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ne8T7_QEDoW4kDavbSG:-NeCQCTj-n5rXc-DlkiD:b3gogq7) ([raw file](https://github.com/starkware-libs/blockifier/blob/d37ef192d539f4d63f1fe688a430093ab29a6665/crates/native_blockifier/src/py_transaction.rs#L311)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we might already have a converter for a collection of felts, check out the adjacent utils file.
</blockquote></details>

@NirLevi-starkware removed this util as @giladchase mentioned in previous PR:
https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne90mW6-LheGTacmDm4

It does repeat five times in this file.

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase, @MohammadNassar1, and @NirLevi-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 311 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/867#-Ne8T7_QEDoW4kDavbSG:-NeCUIT1Egzb-jWG7vpI:b-h8awyr) ([raw file](https://github.com/starkware-libs/blockifier/blob/d37ef192d539f4d63f1fe688a430093ab29a6665/crates/native_blockifier/src/py_transaction.rs#L311)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

@NirLevi-starkware removed this util as @giladchase mentioned in previous PR:
https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne90mW6-LheGTacmDm4

It does repeat five times in this file.
</blockquote></details>

Add a TODO to reintroduce this util?

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/867)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase, @MohammadNassar1, and @NirLevi-starkware)

**Comment by barak-b-starkware** [comment]
Merged in the following PRs: [1](https://github.com/starkware-libs/blockifier/pull/918), [2](https://github.com/starkware-libs/blockifier/pull/919), [3](https://github.com/starkware-libs/blockifier/pull/920).

**Pull request closed without merging**
