### PR TITLE
add test for deploy_account with constructor

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-NkpEiH76jfzPgenLJQi:-NkpEiH8CGD7lo-Fyyo8:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e57195005ed89195f969660156ddc743c85a0502/crates/blockifier/src/transaction/account_transactions_test.rs#L309)):*
> ```XML
>     // Expect this to fail without bumping nonce, so pass a temporary nonce manager.
>     let mut ctor_grind_arg = stark_felt!(1_u8); // Grind in deploy phase. 
>     let ctor_storage_arg = stark_felt!(1_u8); // not relevant for this test.
> ```





_Suggestion:_
```XML
Not
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 318 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-NkpERoE1kznMaJvXi0I:-NkpERoE1kznMaJvXi0J:b-s51u94) ([raw file](https://github.com/starkware-libs/blockifier/blob/e57195005ed89195f969660156ddc743c85a0502/crates/blockifier/src/transaction/account_transactions_test.rs#L318)):*
> ```XML
>             max_fee,
>             constructor_calldata: calldata![ctor_grind_arg, ctor_storage_arg],
>             ..Default::default()
> ```

not needed with the macro; the macro adds the `Default::default()`



_Code quote:_
```XML
..Default::default()
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-NkpE_MwD8LeovOKCG16:-NkpE_MwD8LeovOKCG17:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/e57195005ed89195f969660156ddc743c85a0502/crates/blockifier/src/transaction/account_transactions_test.rs#L340)):*
> ```XML
>             max_fee,
>             constructor_calldata: calldata![ctor_grind_arg, ctor_storage_arg],
>             ..Default::default()
> ```

delete



_Code quote:_
```XML
..Default::default()
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1297 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-NkpEm8E2quYRZ5bXRbx:-NkpEm8E2quYRZ5bXRby:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e57195005ed89195f969660156ddc743c85a0502/crates/blockifier/src/transaction/account_transactions_test.rs#L1297)):*
> ```XML
>     let class_hash = class_hash!(TEST_GRINDY_ACCOUNT_CONTRACT_CLASS_HASH);
>     let ctor_storage_arg = stark_felt!(1_u8);
>     let ctor_grind_arg = stark_felt!(0_u8); /* not relevant for this test */
> ```





_Suggestion:_
```XML
// Do not grind in deploy phase.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1312 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-NkpErvd-avcyemFCkDR:-NkpErvd-avcyemFCkDS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e57195005ed89195f969660156ddc743c85a0502/crates/blockifier/src/transaction/account_transactions_test.rs#L1312)):*
> ```XML
>     deploy_account_tx.execute(&mut state, &block_context, true, true).unwrap();
> 
>     // Check that the constructor wrote ctor_arg to the storage
> ```





_Suggestion:_
```XML
// Check that the constructor wrote ctor_arg to the storage.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213)* status: all files reviewed, 7 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/blockifier/feature_contracts/cairo0/account_with_long_validate.cairo` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-Nkt17AS18l-Q8ed_BsV:-Nkt17AS18l-Q8ed_BsW:br9o5pe) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de52648442c47bab2fa7c5ea0f81fc7529a7767/crates/blockifier/feature_contracts/cairo0/account_with_long_validate.cairo#L25)):*
> ```Cairo
> func constructor{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
>     grind_on_deploy: felt,
>     arg: felt,
> ```

Are those two inputs needed? Can you write `grind_on_deploy`?



_Code quote:_
```Cairo
    grind_on_deploy: felt,
    arg: felt,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 308 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-Nkt2HMmDIvh7YNl1ZPo:-Nkt2HMmDIvh7YNl1ZPp:b-gt2rcx) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de52648442c47bab2fa7c5ea0f81fc7529a7767/crates/blockifier/src/transaction/account_transactions_test.rs#L308)):*
> ```XML
>     // Deploy grindy account with a lot of grind in the constructor.
>     // Expect this to fail without bumping nonce, so pass a temporary nonce manager.
>     let mut ctor_grind_arg = stark_felt!(1_u8); // Grind in deploy phase.
> ```

It technically affect `__validate_deploy__`, no?



_Suggestion:_
```XML
let mut validate_grind_arg = stark_felt!(1_u8); // Grind in deploy phase.
```

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-:-Nkt8_8r9vM3eVKALugf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 308 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-Nkt2HMmDIvh7YNl1ZPo:-Nkt8GwMEhb6If_hcU2R:b-6hhfn4) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de52648442c47bab2fa7c5ea0f81fc7529a7767/crates/blockifier/src/transaction/account_transactions_test.rs#L308)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It technically affect `__validate_deploy__`, no?
</blockquote></details>

ctor args are also args to validate_deploy, I think `ctor_grind_arg` is a better name

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo0/account_with_long_validate.cairo` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-Nkt17AS18l-Q8ed_BsV:-NktBpQs01vLcBMfFn8D:belywav) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de52648442c47bab2fa7c5ea0f81fc7529a7767/crates/blockifier/feature_contracts/cairo0/account_with_long_validate.cairo#L25)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Are those two inputs needed? Can you write `grind_on_deploy`?
</blockquote></details>

I actually had a version like this at the beginning.
I think it won't work because I need to set grind_on_deploy=0 in order for the deploy to succeed. And then when reading it back to verify that the value was written to storage I'll get 0 and have no way to verify.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 308 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-Nkt2HMmDIvh7YNl1ZPo:-NktCWP29FgIcMw6ELUa:borgfi0) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de52648442c47bab2fa7c5ea0f81fc7529a7767/crates/blockifier/src/transaction/account_transactions_test.rs#L308)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ctor args are also args to validate_deploy, I think `ctor_grind_arg` is a better name
</blockquote></details>

you mean validate_grind_arg is a better arg? right?
done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/blockifier/feature_contracts/cairo0/account_with_long_validate.cairo` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-Nkt17AS18l-Q8ed_BsV:-NktEA70C8bw1HZE1tRp:batsk3j) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de52648442c47bab2fa7c5ea0f81fc7529a7767/crates/blockifier/feature_contracts/cairo0/account_with_long_validate.cairo#L25)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I actually had a version like this at the beginning.
I think it won't work because I need to set grind_on_deploy=0 in order for the deploy to succeed. And then when reading it back to verify that the value was written to storage I'll get 0 and have no way to verify.
</blockquote></details>

Got it. Thanks
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 308 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-Nkt2HMmDIvh7YNl1ZPo:-NktEPTHE-NmrxBIdrvH:b-dc6hyb) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de52648442c47bab2fa7c5ea0f81fc7529a7767/crates/blockifier/src/transaction/account_transactions_test.rs#L308)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

you mean validate_grind_arg is a better arg? right?
done.
</blockquote></details>

I actually meant for `ctor_grind_arg`. I just find it confusing that it does not affect the constructor. You can leave it as before as well, whatever you prefer.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 308 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-Nkt2HMmDIvh7YNl1ZPo:-NktEqvF3e9z4UkQRLq5:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de52648442c47bab2fa7c5ea0f81fc7529a7767/crates/blockifier/src/transaction/account_transactions_test.rs#L308)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I actually meant for `ctor_grind_arg`. I just find it confusing that it does not affect the constructor. You can leave it as before as well, whatever you prefer.
</blockquote></details>

.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 308 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1213#-Nkt2HMmDIvh7YNl1ZPo:-NktFjHP30A8H8Fi0OY2:b1qv6p1) ([raw file](https://github.com/starkware-libs/blockifier/blob/7de52648442c47bab2fa7c5ea0f81fc7529a7767/crates/blockifier/src/transaction/account_transactions_test.rs#L308)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

.
</blockquote></details>

oh oops, I change the wrong name.
anyway reverted this change.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1213)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
