### PR TITLE
New syscalls

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/449)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a> 
    * **PR #449** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/449" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/449?utm_source=stack-comment).

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/449)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/449#-NUoyClrAX_zAqPv02Ub:-NUoyClrAX_zAqPv02Uc:b-u34ccp) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6084da557d9ba49142f2777896335efd64b2b55/crates/blockifier/src/execution/syscalls/hint_processor.rs#L50)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum SyscallExecutionError {
> ```

We define error enums in `erros.rs` files. WDYT?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/449#-NUoycle1myZj-4syoNt:-NUoycle1myZj-4syoNu:bpe181a) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6084da557d9ba49142f2777896335efd64b2b55/crates/blockifier/src/execution/syscalls/mod.rs#L1)):*
> ```XML
> use cairo_vm::felt::Felt252;
> ```

Why in `mod.rs`?
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/449#-NUoyiTMDiYtMqN_Sija:-NUoyiTMDiYtMqN_Sijb:b-zic40m) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6084da557d9ba49142f2777896335efd64b2b55/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L1)):*
> ```XML
> use std::collections::{HashMap, HashSet};
> ```

Don't you think we should add test-by-test when we write the new syscalls? 
Or perhaps they are not supposed to change much (only the underlying test contract changes).

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/449)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/449#-NUoyClrAX_zAqPv02Ub:-NUp2_LK6oTmXmt0iNO0:bzc004z) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6084da557d9ba49142f2777896335efd64b2b55/crates/blockifier/src/execution/syscalls/hint_processor.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We define error enums in `erros.rs` files. WDYT?
</blockquote></details>

This error is related to this file though. It's the errors of the syscalls defiend here. Why put it somewhere else?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/449#-NUoycle1myZj-4syoNt:-NUp2gyJ09rx9RWPHvpL:b1179x1) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6084da557d9ba49142f2777896335efd64b2b55/crates/blockifier/src/execution/syscalls/mod.rs#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why in `mod.rs`?
</blockquote></details>

Just kept the old module hierarchy. I can move it if you want.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/449#-NUoyiTMDiYtMqN_Sija:-NUp2l95BRaE9tLbR1Ab:b-zed4xj) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6084da557d9ba49142f2777896335efd64b2b55/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Don't you think we should add test-by-test when we write the new syscalls? 
Or perhaps they are not supposed to change much (only the underlying test contract changes).
</blockquote></details>

I'm not sure. All I did in this Pr was to copy the directory, I thought it would be a smaller step. I can remove the tests though, if you want.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/449)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/449#-NUoyiTMDiYtMqN_Sija:-NUp4Xyx8aOLQ-u7fLnA:ba3dfob) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6084da557d9ba49142f2777896335efd64b2b55/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'm not sure. All I did in this Pr was to copy the directory, I thought it would be a smaller step. I can remove the tests though, if you want.
</blockquote></details>

Removed

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/449#-:-NUpc2zP-ti-w3TXPkio:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/449#-NUoyClrAX_zAqPv02Ub:-NUpbq3s5SpfAccmoRwm:blzfg33) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6084da557d9ba49142f2777896335efd64b2b55/crates/blockifier/src/execution/syscalls/hint_processor.rs#L50)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This error is related to this file though. It's the errors of the syscalls defiend here. Why put it somewhere else?
</blockquote></details>

The convention we used so far is having all errors defined in one file, in each directory. I'm willing to change it if you think we should.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/449)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/449#-NUoyClrAX_zAqPv02Ub:-NUppy8i6ag3cUkxxYZg:bbm8fhb) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6084da557d9ba49142f2777896335efd64b2b55/crates/blockifier/src/execution/syscalls/hint_processor.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The convention we used so far is having all errors defined in one file, in each directory. I'm willing to change it if you think we should.
</blockquote></details>

I think it makes sense like this.

**Pull request merged**
