### PR TITLE
feat(concurrency): add consumers to the versioned state

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYAxoRBUPylFbwmF5d:-NzYAxoRBUPylFbwmF5e:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L224)):*
> ```XML
>                     "In order to consume VersionedState you must to have only one strong refernce \
>                      to the ThreadSafeVersionedState. Consider dropping objects that hold a \
>                      refernce to the VersionedState."
> ```





_Suggestion:_
```XML
                    "In order to consume VersionedState you must to have only one strong reference \
                     to the ThreadSafeVersionedState. Consider dropping objects that hold a \
                     reference to the VersionedState."
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYEFJP4WHBncZD-k_C:-NzYEFJP4WHBncZD-k_D:b-lsbumo) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L53)):*
> ```XML
>     }
> 
>     pub fn consume_block_state(self) -> S {
> ```

@Yoni-Starkware suggested and I think it's good



_Suggestion:_
```XML
    pub fn into_initial_state(self) -> S {
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYEM2r43ePAYl25_zG:-NzYEM2r43ePAYl25_zH:b-z8avqq) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L218)):*
> ```XML
>     }
> 
>     pub fn consume_versioned_state(self) -> VersionedState<S> {
> ```

or `into_versioned_state`



_Suggestion:_
```XML
    pub fn into_inner_state(self) -> VersionedState<S> {
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYEr0uATbnSpD1iRgg:-NzYEr0v2PtTeLNQuR6t:b-cpskoa) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L224)):*
> ```XML
>                     "In order to consume VersionedState you must to have only one strong refernce \
>                      to the ThreadSafeVersionedState. Consider dropping objects that hold a \
>                      refernce to the VersionedState."
> ```

@Avi's suggestion and



_Suggestion:_
```XML
                    "To consume the versioned state you must have only one strong refernce \
                     to self. Consider dropping objects that hold a \
                     refernce to it."
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYFV_e9AWTC0lNDSNm:-NzYFV_e9AWTC0lNDSNn:b7iqk6l) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L228)):*
> ```XML
>             })
>             .into_inner()
>             .expect("No other Mutex should hold the VersionedState while calling this method.")
> ```

Will we get an error if another thread is holding the mutex or only if another user of this mutex panicked while holding the mutex?



_Suggestion:_
```XML
            .expect("No other mutex should hold the versioned state while calling this method.")
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYEr0uATbnSpD1iRgg:-NzYFxl1Bd6Htpp0CbiJ:b-a6xj6h) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L224)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@Avi's suggestion and
</blockquote></details>

@avi-starkware, my bad

**Comment by avi** [comment]
I can (it’s ok happens all the time)Sent from my iPhoneOn Jun 4, 2024, at 13:45, avi-starkware ***@***.***> wrote:﻿
crates/blockifier/src/concurrency/versioned_state.rs line 224 at r1 (raw file):
Previously, noaov1 (Noa Oved) wrote…
@avi-starkware, my bad

lol I wonder if he can see this mention...

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYEFJP4WHBncZD-k_C:-NzYVIk46tvREz9t2BdF:b-w4c2db) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L53)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@Yoni-Starkware suggested and I think it's good
</blockquote></details>

Done.
I think the "consume" terminology is better since it tells the story of using it, but I'm OK with the other option.
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYEM2r43ePAYl25_zG:-NzYVW9kDvDRAwnV0Eho:b-w4c2db) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L218)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

or `into_versioned_state`
</blockquote></details>

Done.
I think the "consume" terminology is better since it tells the story of using it, but I'm OK with the other option.
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYAxoRBUPylFbwmF5d:-NzYVd0BDM2FeEX_oogW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L224)):*
> ```XML
>                     "In order to consume VersionedState you must to have only one strong refernce \
>                      to the ThreadSafeVersionedState. Consider dropping objects that hold a \
>                      refernce to the VersionedState."
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYEr0uATbnSpD1iRgg:-NzYVtjj3JeHAS2h8OyA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L224)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

lol I wonder if he can see this mention...
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYFV_e9AWTC0lNDSNm:-NzYVwuq66c2z7olwJtt:bwc9hn9) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L228)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Will we get an error if another thread is holding the mutex or only if another user of this mutex panicked while holding the mutex?
</blockquote></details>

AFAIU is the second option.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 223 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYYgun-pozi54V3DG1:-NzYYgun-pozi54V3DG2:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/502f196ddeed286fa4c95d4aa57941670d06f0b5/crates/blockifier/src/concurrency/versioned_state.rs#L223)):*
> ```XML
>                 panic!(
>                     "To consume the versioned state you must to have only one strong reference to \
>                      self. Consider dropping objects that hold a reference to it."
> ```





_Suggestion:_
```XML
                    "To consume the versioned state, you must have only one strong reference to \
                     self. Consider dropping objects that hold a reference to it."
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYFV_e9AWTC0lNDSNm:-NzYbgfq4q8V-5Nl1Cws:b-hsypwr) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L228)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

AFAIU is the second option.
</blockquote></details>

I looked at [the source code](https://doc.rust-lang.org/src/std/sync/mutex.rs.html#452), and it seems that `into_inner` doesn't care if the lock is held by another thread. It only checks whether the mutex is poisoned and, if not, returns the data.

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 223 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYYgun-pozi54V3DG1:-NzYiH2T-aK8cWFhSIdf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/502f196ddeed286fa4c95d4aa57941670d06f0b5/crates/blockifier/src/concurrency/versioned_state.rs#L223)):*
> ```XML
>                 panic!(
>                     "To consume the versioned state you must to have only one strong reference to \
>                      self. Consider dropping objects that hold a reference to it."
> ```

Done.

**Review by avi-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-:-NzYk4pkBl7j3ty5R9QY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYEFJP4WHBncZD-k_C:-NzYtR6w5xCAkyAQSacB:b5z9gpz) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L53)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
I think the "consume" terminology is better since it tells the story of using it, but I'm OK with the other option.
</blockquote></details>

Oh I don't think we should add this to the API. The consumption of the VersionedState should only be allowed through `commit`

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 28 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYtosb16poIPuSWOMO:-NzYtosc84ImuRKmeF50:b-c4ld1b) ([raw file](https://github.com/starkware-libs/blockifier/blob/529c06cf8378804282eff51bad5117cb4a27ddf1/crates/blockifier/src/concurrency/versioned_state.rs#L28)):*
> ```XML
> pub struct VersionedState<S: StateReader> {
>     // TODO(barak, 01/08/2024): Change initial_state to block_state.
>     initial_state: S,
> ```

Just `state` is okay, no need to mention `block`



_Code quote:_
```XML
    // TODO(barak, 01/08/2024): Change initial_state to block_state.
    initial_state: S,
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYEFJP4WHBncZD-k_C:-NzcEPYHDFM2p_pGeQgW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ff11d3280c9dfaedb60838b1586369a9f58aef9/crates/blockifier/src/concurrency/versioned_state.rs#L53)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh I don't think we should add this to the API. The consumption of the VersionedState should only be allowed through `commit`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 28 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-NzYtosb16poIPuSWOMO:-NzcEGtwCcHDNACGeR6s:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/529c06cf8378804282eff51bad5117cb4a27ddf1/crates/blockifier/src/concurrency/versioned_state.rs#L28)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Just `state` is okay, no need to mention `block`
</blockquote></details>

Done.

**Review by Yoni-Starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @OriStarkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1949#-:-NzhPqbd8YGKj4JptUkR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @OriStarkware)

**Pull request merged**
