### PR TITLE
Count actual state changes.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 3 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/feature_contracts/test_contract.cairo` line 99 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NQumP7R5bJb_Jj4ODIW:-NQumP7R5bJb_Jj4ODIX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/21d650d321ab26af2bd30fde8b2bc2d424e02510/crates/blockifier/feature_contracts/test_contract.cairo#L99)):*
> ```Cairo
>     alloc_locals;
>     assert calldata_len = 2;
>     local nested_library_calldata: felt* = new (
> ```





_Suggestion:_
```Cairo
new(
```
___
*[`crates/blockifier/src/test_utils.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSpZ3mAsjd3AlpQz3H:-NRSpZ3mAsjd3AlpQz3I:bscl7og) ([raw file](https://github.com/starkware-libs/blockifier/blob/a44608734c23ef78ed31b530dd10258fc90ad3f0/crates/blockifier/src/test_utils.rs#L56)):*
> ```XML
>     "./ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls_compiled.json";
> 
> // Selectors.
> ```

Not in use anymore?



_Code quote:_
```XML
// Selectors.
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSoq9G6AU-dCf8bLVZ:-NRSoq9G6AU-dCf8bLV_:bu3bbj3) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/transaction/objects.rs#L36)):*
> ```XML
>     /// including L1 gas and additional OS resources estimation.
>     pub actual_resources: ResourcesMapping,
>     pub n_storage_updates: usize,
> ```

Let's revert this change for now; if we decide that we're not going to invoke Python logic to calc. the actual fee, no need to pass it to the execution info (and therefore to Python). Also, in general, it's healthier to separate function + tests from its usage (especially, if it's wide). 

You can remember the commit, if we _do_ decide to use it.

Re the tests, validate the changes by calling the new method of state you added.



_Code quote:_
```XML
    pub n_storage_updates: usize,
    pub n_modified_contracts: usize,
    pub n_class_updates: usize,
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 364 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSqsodCpBcvux6BmuE:-NRSqsoe-rcTRr673SuV:b-3zlnxs) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L364)):*
> ```XML
>     /// has changed and the number of deployed contracts.
>     pub fn count_actual_state_changes(&self) -> (usize, usize, usize) {
>         let state_cache = &self.cache;
> ```

Is this variable needed? It's used twice and `&self.cache` is pretty short.



_Code quote:_
```XML
let state_cache = &self.cache;
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 368 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSrMKR7AKRqcJ_NbXZ:-NRSrMKR7AKRqcJ_NbX_:bsszcoy) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L368)):*
> ```XML
>         let storage_diffs = state_cache.get_stoarge_diffs();
>         let modified_contracts: HashSet<ContractAddress> =
>             storage_diffs.keys().map(|key| key.0).collect();
> ```

So that it's clear that we're taking the unique addresses, without a comment. :)



_Suggestion:_
```XML
|address_key_pair| address_key_pair.0
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSrcS92g1bdHBJGP3Z:-NRSrcS92g1bdHBJGP3_:b-a7a4r2) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L372)):*
> ```XML
> 
>         // Exclude the sequencer balance update, since it's charged once throughout the batch.
>         // Exclude the ERC20 contract, since it's changed one time in a batch.
> ```

No "batch" in our repo. :)



_Suggestion:_
```XML
        // Exclude the sequencer's balance update (from storage diffs) and fee token
        // (from modified contracts), since they are charged once throughout the block.
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 373 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSsgpHENQwLr4b94jb:-NRSsgpHENQwLr4b94jc:b-903hcr) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L373)):*
> ```XML
>         // Exclude the sequencer balance update, since it's charged once throughout the batch.
>         // Exclude the ERC20 contract, since it's changed one time in a batch.
>         (storage_diffs.len() - 1, modified_contracts.len() - 1, deployed_contracts.len())
> ```

These two can intersect; I think you need to `or` with `deployed_contracts`, since for every modified one (either for storage change of class hash change; i.e., - deploy) we [charge an L1 cost](https://github.com/starkware-industries/starkware/blob/80ab20b5359bd3ce095000340f7bb6d3d70ee0fd/src/starkware/starknet/business_logic/execution/gas_usage.py#L102).



_Code quote:_
```XML
modified_contracts.len() - 1, deployed_contracts.len()
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: all files reviewed, 7 unresolved discussions (waiting on @alonh5 and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/feature_contracts/test_contract.cairo` line 99 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NQumP7R5bJb_Jj4ODIW:-NRXKtaH50PE85AQrZ-_:b-72s99k) ([raw file](https://github.com/starkware-libs/blockifier/blob/21d650d321ab26af2bd30fde8b2bc2d424e02510/crates/blockifier/feature_contracts/test_contract.cairo#L99)):*
> ```Cairo
>     alloc_locals;
>     assert calldata_len = 2;
>     local nested_library_calldata: felt* = new (
> ```

It changes every time I save the file. Do you want me to change it anyway?
___
*[`crates/blockifier/src/test_utils.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSpZ3mAsjd3AlpQz3H:-NRXG7zPEzA2tHkhlXht:b-7qnes4) ([raw file](https://github.com/starkware-libs/blockifier/blob/a44608734c23ef78ed31b530dd10258fc90ad3f0/crates/blockifier/src/test_utils.rs#L56)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not in use anymore?
</blockquote></details>

So it seems :)
___
*[`crates/blockifier/src/state/cached_state.rs` line 364 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSqsodCpBcvux6BmuE:-NRY3ZZI04sDWqZa_vlS:b-gpk3xp) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L364)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this variable needed? It's used twice and `&self.cache` is pretty short.
</blockquote></details>

No. I deleted it. 
___
*[`crates/blockifier/src/state/cached_state.rs` line 368 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSrMKR7AKRqcJ_NbXZ:-NRY47293sxVbKkmjoVb:b-896fjb) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L368)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So that it's clear that we're taking the unique addresses, without a comment. :)
</blockquote></details>

Done 
___
*[`crates/blockifier/src/state/cached_state.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSrcS92g1bdHBJGP3Z:-NRY4OIz5Anz8ui3thlz:b-o4wjw0) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L372)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No "batch" in our repo. :)
</blockquote></details>

I think it is not needed anymore since we will run it before the fee charge (as in python) , no?
___
*[`crates/blockifier/src/state/cached_state.rs` line 373 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSsgpHENQwLr4b94jb:-NRYBjmg0M7rbD4a1C6i:bctnto3) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L373)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

These two can intersect; I think you need to `or` with `deployed_contracts`, since for every modified one (either for storage change of class hash change; i.e., - deploy) we [charge an L1 cost](https://github.com/starkware-industries/starkware/blob/80ab20b5359bd3ce095000340f7bb6d3d70ee0fd/src/starkware/starknet/business_logic/execution/gas_usage.py#L102).
</blockquote></details>

Can you please elaborate? Why a deployed contract is counted also in `modified_contracts`?
___
*[`crates/blockifier/src/transaction/objects.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSoq9G6AU-dCf8bLVZ:-NRYDaHj9l9R53lIYYYb:bv9j642) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/transaction/objects.rs#L36)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's revert this change for now; if we decide that we're not going to invoke Python logic to calc. the actual fee, no need to pass it to the execution info (and therefore to Python). Also, in general, it's healthier to separate function + tests from its usage (especially, if it's wide). 

You can remember the commit, if we _do_ decide to use it.

Re the tests, validate the changes by calling the new method of state you added.
</blockquote></details>

Done. 
Can you please explain WDYM by: "separate function + tests from its usage"?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5, @giladchase, and @noaov1)

___
*[`crates/blockifier/feature_contracts/test_contract.cairo` line 99 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NQumP7R5bJb_Jj4ODIW:-NRb751gEBE5QS8Z8-k2:bbagj8p) ([raw file](https://github.com/starkware-libs/blockifier/blob/21d650d321ab26af2bd30fde8b2bc2d424e02510/crates/blockifier/feature_contracts/test_contract.cairo#L99)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It changes every time I save the file. Do you want me to change it anyway?
</blockquote></details>

What's the format in the Python repo.? Perhaps it should be configured in our repo.; @giladchase, any idea?
___
*[`crates/blockifier/src/state/cached_state.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSrcS92g1bdHBJGP3Z:-NRb8734-u0zMVzkiYwW:byzl1hu) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L372)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it is not needed anymore since we will run it before the fee charge (as in python) , no?
</blockquote></details>

Okay, cool. Where do we add those then?
___
*[`crates/blockifier/src/state/cached_state.rs` line 373 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSsgpHENQwLr4b94jb:-NRb7TNMClI4ilCV1pEF:bgbrdj7) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L373)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please elaborate? Why a deployed contract is counted also in `modified_contracts`?
</blockquote></details>

Since we output felts to L1 for [every modified contract](https://github.com/starkware-industries/starkware/blob/80ab20b5359bd3ce095000340f7bb6d3d70ee0fd/src/starkware/starknet/business_logic/execution/gas_usage.py#L102); deployed contract [as well](https://github.com/starkware-industries/starkware/blob/80ab20b5359bd3ce095000340f7bb6d3d70ee0fd/src/starkware/starknet/business_logic/state/state.py#L573) (their state root, which consists of `(class_hash, storage_root, nonce)` changed.
___
*[`crates/blockifier/src/state/cached_state.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRb8czd-_zFJZOpUEUe:-NRb8czd-_zFJZOpUEUf:b-5xml8u) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4311f361c0a5184b99a80f86a9c4c6eb587037/crates/blockifier/src/state/cached_state.rs#L39)):*
> ```XML
> 
>     /// Returns the number of storage changes done through this state, the number of modified
>     /// contracts, where a contract is considered as modified if one or more of its storage cells
> ```

Try to describe behavior in the docstring, rather than concrete implementation, which might change and leave the documentation unmaintained.
We'll implement the nonce count in `0.11.0` support.



_Suggestion:_
```XML
    /// Returns the number of storage changes done through this state.
    /// Any change to the contract's state (storage, nonce, class hash) is considered.
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 276 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRb9Q53BZRncLTjBM6g:-NRb9Q53BZRncLTjBM6h:bcbyewk) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4311f361c0a5184b99a80f86a9c4c6eb587037/crates/blockifier/src/state/cached_state_test.rs#L276)):*
> ```XML
>     state.set_storage_at(contract_address, key, storage_val);
> 
>     assert_eq!(state.count_actual_state_changes(), (1, 1, 1));
> ```

Unpack, give them names, so the assert is clear.



_Code quote:_
```XML
(1, 1, 1)
```
___
*[`crates/blockifier/tests/requirements.txt` line 2 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRb8Hz3AJsYPD_mDLTj:-NRb8Hz3AJsYPD_mDLTk:b-hm9nfx) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4311f361c0a5184b99a80f86a9c4c6eb587037/crates/blockifier/tests/requirements.txt#L2)):*
> ```help
> cairo-lang
> typeguard<3.0.0
> ```

No need anymore, this was fixed in `0.11.0`.



_Code quote:_
```help
typeguard<3.0.0
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSoq9G6AU-dCf8bLVZ:-NRb8RFA21reZ_UGBwOw:b70jm1l) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/transaction/objects.rs#L36)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done. 
Can you please explain WDYM by: "separate function + tests from its usage"?
</blockquote></details>

Yes, a PR for the function you added + a test for it (maybe with additional cases to existing tests as well). Then, after that another PR for this function's usage.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: all files reviewed, 7 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSrcS92g1bdHBJGP3Z:-NRbAgy01MBoo3Vk93vd:b-uq7ku0) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L372)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Okay, cool. Where do we add those then?
</blockquote></details>

[Here](https://github.com/starkware-industries/starkware/blob/f946e2dd1523a538f4458f7ffdaf059aae5c7f28/src/starkware/starknet/business_logic/utils.py#L241)
___
*[`crates/blockifier/src/state/cached_state.rs` line 373 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSsgpHENQwLr4b94jb:-NRbICyy9vG3pBrXlFmn:bci1nc6) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L373)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Since we output felts to L1 for [every modified contract](https://github.com/starkware-industries/starkware/blob/80ab20b5359bd3ce095000340f7bb6d3d70ee0fd/src/starkware/starknet/business_logic/execution/gas_usage.py#L102); deployed contract [as well](https://github.com/starkware-industries/starkware/blob/80ab20b5359bd3ce095000340f7bb6d3d70ee0fd/src/starkware/starknet/business_logic/state/state.py#L573) (their state root, which consists of `(class_hash, storage_root, nonce)` changed.
</blockquote></details>

Oh I see. Changed.
___
*[`crates/blockifier/src/state/cached_state.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRb8czd-_zFJZOpUEUe:-NRbAfl5EyiIJecccy78:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4311f361c0a5184b99a80f86a9c4c6eb587037/crates/blockifier/src/state/cached_state.rs#L39)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Try to describe behavior in the docstring, rather than concrete implementation, which might change and leave the documentation unmaintained.
We'll implement the nonce count in `0.11.0` support.

</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 276 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRb9Q53BZRncLTjBM6g:-NRbNJIpDbtAgvBvOPz8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4311f361c0a5184b99a80f86a9c4c6eb587037/crates/blockifier/src/state/cached_state_test.rs#L276)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Unpack, give them names, so the assert is clear.
</blockquote></details>

Done.
___
*[`crates/blockifier/tests/requirements.txt` line 2 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRYU_Hp2W-crpcL0MeR:-NRYSsDWCl_RFXyJxJ6N:bn6tls2) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4311f361c0a5184b99a80f86a9c4c6eb587037/crates/blockifier/tests/requirements.txt#L2)):*
> ```help
> cairo-lang
> typeguard<3.0.0
> ```

I thought it should help with `verify_cairo_file_dependencies` but apparently it did not. I'll check for a different solution and revert this file.



_Code quote:_
```help
typeguard<3.0.0
```
___
*[`crates/blockifier/tests/requirements.txt` line 2 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRb8Hz3AJsYPD_mDLTj:-NRbMvHe1e44LVMLElV3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4311f361c0a5184b99a80f86a9c4c6eb587037/crates/blockifier/tests/requirements.txt#L2)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No need anymore, this was fixed in `0.11.0`.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSrcS92g1bdHBJGP3Z:-NRbWv1X892zE_qiFuyr:b-o7h0gh) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L372)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

[Here](https://github.com/starkware-industries/starkware/blob/f946e2dd1523a538f4458f7ffdaf059aae5c7f28/src/starkware/starknet/business_logic/utils.py#L241)
</blockquote></details>

Wait, so do we need to exclude them here (for every transaction) or not, if they're added later?
Let's still add a small comment on this in the end of the docstring of  `count_actual_state_changes`: `Exclude fee-related contracts (sequencer account, fee token), since they are charged once throughout the block.`.
___
*[`crates/blockifier/tests/requirements.txt` line 2 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRYU_Hp2W-crpcL0MeR:-NRbWY5D7Ei6TVwlXXZ0:b-5bq3o0) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4311f361c0a5184b99a80f86a9c4c6eb587037/crates/blockifier/tests/requirements.txt#L2)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I thought it should help with `verify_cairo_file_dependencies` but apparently it did not. I'll check for a different solution and revert this file.
</blockquote></details>

It should work now, since `cairo-lang` is installed in version `0.11.0`; does it still fail on `typeguard`?

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @giladchase, and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSrcS92g1bdHBJGP3Z:-NRbZu4E3sfiYPFqMhuU:b3v4fn4) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L372)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Wait, so do we need to exclude them here (for every transaction) or not, if they're added later?
Let's still add a small comment on this in the end of the docstring of  `count_actual_state_changes`: `Exclude fee-related contracts (sequencer account, fee token), since they are charged once throughout the block.`.
</blockquote></details>

No since we will calculate the actual resources before the fee charge (as done in python).
Done.
___
*[`crates/blockifier/tests/requirements.txt` line 2 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRYU_Hp2W-crpcL0MeR:-NRbdSEs7STzzoaWrSwJ:blrjr2a) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c4311f361c0a5184b99a80f86a9c4c6eb587037/crates/blockifier/tests/requirements.txt#L2)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It should work now, since `cairo-lang` is installed in version `0.11.0`; does it still fail on `typeguard`?
</blockquote></details>

Don't know, I reverted the changes

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSrcS92g1bdHBJGP3Z:-NRbeN2AAcnvqrOFIwnD:b-czfmy8) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L372)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No since we will calculate the actual resources before the fee charge (as done in python).
Done.
</blockquote></details>

Okay, got it. So because this is out of scope for this `CachedState` method (can either be called on the transaction _or block_ level. Let's add this sentence when we actually add these contracts.

Copy it so you'd have it later on (I'll try to remember too). Sorry for the back and forth.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335#-:-NRby5AQ7MnwBBSyyLYN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/335)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/blockifier/src/state/cached_state.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/335#-NRSrcS92g1bdHBJGP3Z:-NRbuGV32juAEbUbsI4L:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb4495d0c9e2cf82da8e0ee43f995a427df3b485/crates/blockifier/src/state/cached_state.rs#L372)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Okay, got it. So because this is out of scope for this `CachedState` method (can either be called on the transaction _or block_ level. Let's add this sentence when we actually add these contracts.

Copy it so you'd have it later on (I'll try to remember too). Sorry for the back and forth.
</blockquote></details>

Done.

**Pull request merged**
