### PR TITLE
Use SN API and papyrus storage published crates.

### PR DESCRIPTION
**Pull request by alonh5**
Will update to papyrus_storage crate when published (In this PR).

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`Cargo.toml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNMCE99I_SwnoNjSo:-NZeNMCE99I_SwnoNjSp:b-xpwm81) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L25)):*
> ```TOML
> ouroboros = "0.15.6"
> rstest = "0.17.0"
> papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", rev = "d371b17" }
> ```

blocking until PR update



_Code quote:_
```TOML
papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", rev = "d371b17" }
```
___
*[`Cargo.toml` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNXbK6LCCwLzdYPlB:-NZeNXbK6LCCwLzdYPlC:b-4issw5) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L31)):*
> ```TOML
> serde_json = "1.0.81"
> sha3 = "0.10.6"
> starknet_api = "0.1.0"
> ```

not 0.1.1?



_Code quote:_
```TOML
starknet_api = "0.1.0"
```
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNed92PSJsHPNMTwh:-NZeNed92PSJsHPNMTwi:b-4uv1lb) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/crates/native_blockifier/src/py_transaction_executor.rs#L36)):*
> ```XML
> impl PyTransactionExecutor {
>     #[new]
>     #[args(papyrus_storage, general_config, block_info, max_recursion_depth)]
> ```

where did this change come from?
or is it unrelated (just reordering args correctly)?



_Code quote:_
```XML
#[args(papyrus_storage, general_config, block_info, max_recursion_depth)
```
___
*[`crates/native_blockifier/src/storage.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNtMY-5b1oZ11aWFn:-NZeNtMY-5b1oZ11aWFo:b-8hnvch) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/crates/native_blockifier/src/storage.rs#L46)):*
> ```XML
>         let db_config = papyrus_storage::db::DbConfig {
>             path_prefix,
>             chain_id: to_chain_id_enum(chain_id)?,
> ```

open a PR with a version bump in SW side please? this change is sensitive (storage API change + chain ID addition)



_Code quote:_
```XML
    pub fn new(
        path_prefix: PathBuf,
        chain_id: BigUint,
        max_size: usize,
    ) -> NativeBlockifierResult<Storage> {
        log::debug!("Initializing Blockifier storage...");
        let db_config = papyrus_storage::db::DbConfig {
            path_prefix,
            chain_id: to_chain_id_enum(chain_id)?,
```

**Review by elintul — CHANGES_REQUESTED** [review]
Why not merge the SN API change separately? 

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715#-:-NZeVIZ2EYmLNtdSLA6k:bvj75g7)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, and @giladchase)

___
*[`Cargo.toml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNMCE99I_SwnoNjSo:-NZeVFbb8oRcc5A_GpgS:bydxlwn) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

blocking until PR update
</blockquote></details>

Why not `v0.1.2-alpha`?
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeVQGXEaMEp5LkiLw8:-NZeVQGXEaMEp5LkiLw9:bxy5su6) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/crates/native_blockifier/src/py_transaction_executor.rs#L36)):*
> ```XML
> impl PyTransactionExecutor {
>     #[new]
>     #[args(papyrus_storage, general_config, block_info, max_recursion_depth)]
> ```

How come Python isn't broken?



_Code quote:_
```XML
#[args(papyrus_storage, general_config, block_info, max_recursion_depth)]
```

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, and @giladchase)

**Review by alonh5 — COMMENTED** [review]
Papyrus also depends on it, we can't have different SN API versions.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715#-:-NZeXgKM6gsR-FnA6UW6:b-iiikq9)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`Cargo.toml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNMCE99I_SwnoNjSo:-NZeXpuT6xj5m_zgkBqp:bhqkfja) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not `v0.1.2-alpha`?
</blockquote></details>

I answered above, the SN API version must match.
___
*[`Cargo.toml` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNXbK6LCCwLzdYPlB:-NZeVCl12vcR7UE628rR:b-493hgh) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L31)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not 0.1.1?
</blockquote></details>

Yep, thanks.
Papyrus hasn't updated to this yet so clippy fails, but we're waiting for the crate release anyway so it's all good. 
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNed92PSJsHPNMTwh:-NZeVTxH353i9vYzYuDK:bnzy5yk) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/crates/native_blockifier/src/py_transaction_executor.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where did this change come from?
or is it unrelated (just reordering args correctly)?
</blockquote></details>

I reordered and added the missing arg.
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeVQGXEaMEp5LkiLw8:-NZeVa10ACyp0mQQkzOQ:b4bvdom) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/crates/native_blockifier/src/py_transaction_executor.rs#L36)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come Python isn't broken?
</blockquote></details>

From what I see, this is used for defining default arguments and also allows the function to receive `*args` and `**kwargs`.
So we're not using it correctly and it's adding nothing. Should I remove everywhere that doesn't have the above use?
___
*[`crates/native_blockifier/src/storage.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNtMY-5b1oZ11aWFn:-NZeWpoKChoes5Xq7183:bny2xov) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/crates/native_blockifier/src/storage.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

open a PR with a version bump in SW side please? this change is sensitive (storage API change + chain ID addition)
</blockquote></details>

Of course.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, and @giladchase)

___
*[`Cargo.toml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNMCE99I_SwnoNjSo:-NZeZKYBBpFUfGSTC8mt:b-42scns) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L25)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I answered above, the SN API version must match.
</blockquote></details>

I thought `v0.1.2-alpha` depended on `0.1.1` SN API.
___
*[`Cargo.toml` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNXbK6LCCwLzdYPlB:-NZeZTSY01mz3wyLcXnf:b-g3ht5z) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L31)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yep, thanks.
Papyrus hasn't updated to this yet so clippy fails, but we're waiting for the crate release anyway so it's all good. 
</blockquote></details>

I prefer not to wait with open PRs... let's go with `0.1.0` and change both when Papyrus publishes.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeZbh_269xfrXszAAc:-NZeZbha5xndK6Cbmp7S:b-qonwux) ([raw file](https://github.com/starkware-libs/blockifier/blob/b97e10866ea6aadd1109b857c348ddc6989ec5a4/crates/blockifier/src/transaction/account_transaction.rs#L109)):*
> ```XML
>                 signature: tx.signature(),
>                 nonce: match tx {
>                     InvokeTransaction::V0(_) => Nonce::default(),
> ```

Isn't this embedded in SN API in the end?
Seems weird all users would have to repeat this code.



_Code quote:_
```XML
InvokeTransaction::V0(_) => Nonce::default(),
```
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeVQGXEaMEp5LkiLw8:-NZeZuFT2yRmlqBGKe8o:b7gnl2j) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/crates/native_blockifier/src/py_transaction_executor.rs#L36)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

From what I see, this is used for defining default arguments and also allows the function to receive `*args` and `**kwargs`.
So we're not using it correctly and it's adding nothing. Should I remove everywhere that doesn't have the above use?
</blockquote></details>

I think we use it to pass named arguments from Python.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`Cargo.toml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNMCE99I_SwnoNjSo:-NZecDSlB835oYgKQQm5:b-83og3x) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I thought `v0.1.2-alpha` depended on `0.1.1` SN API.
</blockquote></details>

Nope.
___
*[`Cargo.toml` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNXbK6LCCwLzdYPlB:-NZecG6wEBe2jLfYuPnc:b-immaub) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L31)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I prefer not to wait with open PRs... let's go with `0.1.0` and change both when Papyrus publishes.
</blockquote></details>

We need to wait for the papyrus release anyway. Unless you're fine with using a commit instead of a tag for now.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeZbh_269xfrXszAAc:-NZecah6BADscD7mYud3:b-haob9b) ([raw file](https://github.com/starkware-libs/blockifier/blob/b97e10866ea6aadd1109b857c348ddc6989ec5a4/crates/blockifier/src/transaction/account_transaction.rs#L109)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't this embedded in SN API in the end?
Seems weird all users would have to repeat this code.
</blockquote></details>

Not all users necessarily use it like this. If we refactor our code to not go through an account transaction for V0 - we won't either.
We thought SN API shouldn't assume this use. WDYT?
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeVQGXEaMEp5LkiLw8:-NZedipsBOQG2SLRQ8Hx:bnpdsoa) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/crates/native_blockifier/src/py_transaction_executor.rs#L36)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we use it to pass named arguments from Python.
</blockquote></details>

Yeah, I guess that's what we thought it did. But they can be passed as named args anyways, as you can see.
From poy3 docs:
```
Deprecated way to define a method’s default arguments and allows the function to receive `*args` and `**kwargs`. Use `#[pyo3(signature = (...))]` instead.
```
(`#[pyo3(signature = (...))]` has the same use.)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, and @giladchase)

___
*[`Cargo.toml` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNXbK6LCCwLzdYPlB:-NZepk5U0FVhvRWo1hLw:b6tlet4) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L31)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

We need to wait for the papyrus release anyway. Unless you're fine with using a commit instead of a tag for now.
</blockquote></details>

Let's use a commit hash for Papyrus and once they publish - change their dependency alone.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeZbh_269xfrXszAAc:-NZepz9c2kVIvjMS-Cf4:brxp9sq) ([raw file](https://github.com/starkware-libs/blockifier/blob/b97e10866ea6aadd1109b857c348ddc6989ec5a4/crates/blockifier/src/transaction/account_transaction.rs#L109)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Not all users necessarily use it like this. If we refactor our code to not go through an account transaction for V0 - we won't either.
We thought SN API shouldn't assume this use. WDYT?
</blockquote></details>

Sounds good.
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeVQGXEaMEp5LkiLw8:-NZeq4E23x0PFcxLQ1ki:beuve12) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/crates/native_blockifier/src/py_transaction_executor.rs#L36)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yeah, I guess that's what we thought it did. But they can be passed as named args anyways, as you can see.
From poy3 docs:
```
Deprecated way to define a method’s default arguments and allows the function to receive `*args` and `**kwargs`. Use `#[pyo3(signature = (...))]` instead.
```
(`#[pyo3(signature = (...))]` has the same use.)
</blockquote></details>

Make sure Python isn't broken, please? :grimacing:

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`Cargo.toml` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeNXbK6LCCwLzdYPlB:-NZexH9c712qmY-AB8ev:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/Cargo.toml#L31)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's use a commit hash for Papyrus and once they publish - change their dependency alone.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/715#-NZeVQGXEaMEp5LkiLw8:-NZevNQR3VsCqt6M5vM4:bciln42) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b346fb904cc6e22bdd24253e6b058d3815b978/crates/native_blockifier/src/py_transaction_executor.rs#L36)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Make sure Python isn't broken, please? :grimacing: 
</blockquote></details>

I made sure by looking that the blockifier commit used also doesn't have that arg, and ran the blockifier test just in case.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715#-:-NZf72kRDlhaYZOAW4zU:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/715)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
