### PR TITLE
chore: add merge_status.py script

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1543)

### CODE REVIEW

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1543)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`scripts/merge_status.py` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-NqwzBCU6ZgURXWP1PtF:-NqwzBCU6ZgURXWP1PtG:b-j97wwv) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f72c995c2fbeab52e5dbea0b5b9969f33ef6a4c/scripts/merge_status.py#L9)):*
> ```Python
> 
> DIR = os.path.dirname(__file__)
> MERGE_PATHS_FILE = os.path.join(DIR, "merge_paths.json")
> ```

I suggest being consistent with the other Pythonic scripts. In `merge_branches.py` we use:
```
MERGE_PATHS_FILE = "scripts/merge_paths.json"
```
So either use the same pattern or change it in `merge_branches.py`.



_Code quote:_
```Python
DIR = os.path.dirname(__file__)
MERGE_PATHS_FILE = os.path.join(DIR, "merge_paths.json")
```
___
*[`scripts/merge_status.py` line 20 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-NqwzsUvC3bxQ80Ctjt-:-NqwzsUvC3bxQ80Ctjt0:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f72c995c2fbeab52e5dbea0b5b9969f33ef6a4c/scripts/merge_status.py#L20)):*
> ```Python
> 
> 
> def color_txt(color, txt: str, bold: bool = True):
> ```





_Suggestion:_
```Python
def color_txt(color: str, txt: str, bold: bool = True):
```
___
*[`scripts/merge_status.py` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-Nqwzv7Y7shHIUQnEQ-T:-Nqwzv7Y7shHIUQnEQ-U:b-ii42b0) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f72c995c2fbeab52e5dbea0b5b9969f33ef6a4c/scripts/merge_status.py#L22)):*
> ```Python
> def color_txt(color, txt: str, bold: bool = True):
>     bold_str = "1;" if bold else ""
>     color_code = BASH_COLORS[color.lower()]
> ```

Why does someone call it w/o lowercase? If such an option exists, might it allow others to be inconsistent here?



_Suggestion:_
```Python
color_code = BASH_COLORS[color]
```
___
*[`scripts/merge_status.py` line 27 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-Nqx-IXU97uLGiGsEWdA:-Nqx-IXU97uLGiGsEWdB:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f72c995c2fbeab52e5dbea0b5b9969f33ef6a4c/scripts/merge_status.py#L27)):*
> ```Python
> 
> 
> def main():
> ```





_Suggestion:_
```Python
def print_merge_status():
```

**Comment by barak-b-starkware** [comment]
*[`scripts/merge_status.py` line 61 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-Nqx0ACE0ss1G3lt3HWN:-Nqx0ACF5lnoa9A11EcJ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f72c995c2fbeab52e5dbea0b5b9969f33ef6a4c/scripts/merge_status.py#L61)):*
> ```Python
> 
> if __name__ == "__main__":
>     main()
> ```





_Suggestion:_
```Python
print_merge_status()
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1543)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @barak-b-starkware and @elintul)

___
*[`scripts/merge_status.py` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-Nqwzv7Y7shHIUQnEQ-T:-Nr-uoET8asVSt2T_fTt:b6c3h6) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f72c995c2fbeab52e5dbea0b5b9969f33ef6a4c/scripts/merge_status.py#L22)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Why does someone call it w/o lowercase? If such an option exists, might it allow others to be inconsistent here?
</blockquote></details>

Converted to enum because why wasn't it

**Comment by barak-b-starkware** [comment]
*[`scripts/merge_status.py` line 11 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-Nr09_Dz0opnCnwR1O4u:-Nr09_Dz0opnCnwR1O4v:b-jmepyd) ([raw file](https://github.com/starkware-libs/blockifier/blob/c201f06acdb576a76a5245d9e4657df73c5a85c9/scripts/merge_status.py#L11)):*
> ```Python
> from merge_branches import MERGE_PATHS_FILE
> 
> DIR = os.path.dirname(__file__)
> ```

unused

**Comment by barak-b-starkware** [comment]
*[`scripts/merge_branches.py` line 113 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-Nr0A7N56zh9f-wPRLm1:-Nr0A7N56zh9f-wPRLm2:b-376n0d) ([raw file](https://github.com/starkware-libs/blockifier/blob/c201f06acdb576a76a5245d9e4657df73c5a85c9/scripts/merge_branches.py#L113)):*
> ```Python
>         run_command(
>             f'git commit -m "chore: merge branch {src_branch} into {dst_branch} (with conflicts)"'
>         )
> ```

Why it's part of this PR?

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1543)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1543)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @elintul)

___
*[`scripts/merge_branches.py` line 113 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-Nr0A7N56zh9f-wPRLm1:-Nr0C5md3o9kP02am6ft:b-qesrx1) ([raw file](https://github.com/starkware-libs/blockifier/blob/c201f06acdb576a76a5245d9e4657df73c5a85c9/scripts/merge_branches.py#L113)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Why it's part of this PR?
</blockquote></details>

VSCode did it. Want to open a separate PR for it?
___
*[`scripts/merge_status.py` line 11 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-Nr09_Dz0opnCnwR1O4u:-Nr0CGyh7gQsw--5kGhA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c201f06acdb576a76a5245d9e4657df73c5a85c9/scripts/merge_status.py#L11)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1543#-:-Nr0bZtH3GQAh4Mq6GrM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
