### PR TITLE
add l1_handler test in the spirit of the python test

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1201)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1201)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 151 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-NkQ94oT8bHh7U23xRy0:-NkQEiCl38_dlzxc2rcH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c403999e4b998b538ebe449ac4216284b1e62d96/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L151)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this called `deposit`? you are calling `storage_write`; are you actually depositing something?
why do you use `to` and `from` and `amount` terminology, and you ignore the `from_address`, instead of using key-value terminology and calling this function `l1_handler_set_value` or something more descriptive?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1308 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-NkQ2NLI9vPw8V69pU8Y:-NkQEjSu22x9O1XOA9UQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c403999e4b998b538ebe449ac4216284b1e62d96/crates/blockifier/src/transaction/transactions_test.rs#L1308)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why does this function name start with `test_`? what is being tested?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1335 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-NkQ84t12sUJGEtSrugE:-NkQFOmLAVX594p2dQFV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c403999e4b998b538ebe449ac4216284b1e62d96/crates/blockifier/src/transaction/transactions_test.rs#L1335)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please give `0x876` a name and use it when constructing the calldata and here
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1346 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-NkQ8K4x36PBY7pGwMOb:-NkQFNzlAybe-glR0i3N:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c403999e4b998b538ebe449ac4216284b1e62d96/crates/blockifier/src/transaction/transactions_test.rs#L1346)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1385 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-NkQ8fXI-5sfdmk9WWjP:-NkQFhkWD9zed7PJGC2s:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c403999e4b998b538ebe449ac4216284b1e62d96/crates/blockifier/src/transaction/transactions_test.rs#L1385)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a `paid_fee_on_l1` parameter to your utility function and use it; no need for mutable object
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1391 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-NkQ8txU83CXoUWZ8WuE:-NkQFiV09kPgPgqcMlrX:blim289) ([raw file](https://github.com/starkware-libs/blockifier/blob/c403999e4b998b538ebe449ac4216284b1e62d96/crates/blockifier/src/transaction/transactions_test.rs#L1391)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is the fee insufficient if the actual fee equals the paid fee?
</blockquote></details>

Today we return an error only if the Fee is 0 , and no matter what the actual fee was.  I added a comment there.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1201)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 151 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-NkQLH2dAsoiK-OSaidd:-NkQLH2dAsoiK-OSaide:b-d75pqm) ([raw file](https://github.com/starkware-libs/blockifier/blob/7597103771d8f3d705591ee0379535270b7827ca/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L151)):*
> ```Cairo
> 
>     #[l1_handler]
>     fn l1_handler_set_value(self: @ContractState, from_address: felt252, key: StorageAddress, value: felt252) -> felt252{
> ```

no need for this param



_Code quote:_
```Cairo
from_address: felt252
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1201)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 151 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-NkQLH2dAsoiK-OSaidd:-NkTs4Cg2PzSjOyAbKL7:b7i16w7) ([raw file](https://github.com/starkware-libs/blockifier/blob/7597103771d8f3d705591ee0379535270b7827ca/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L151)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need for this param
</blockquote></details>

it is a mandatory field for l1_handler, the compiler doesn't let me remove it.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1329 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-NkQ7qafBwHDtk6AQ31e:-NkTre0c80DPNsYwJb6u:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/c403999e4b998b538ebe449ac4216284b1e62d96/crates/blockifier/src/transaction/transactions_test.rs#L1329)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `calldata!` macro
</blockquote></details>

done
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1383 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-NkQ8aH68w9F2BqEWK3C:-NkTrfEHBOS06sMy5bvF:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/c403999e4b998b538ebe449ac4216284b1e62d96/crates/blockifier/src/transaction/transactions_test.rs#L1383)):*
> ```XML
>     assert_eq!(actual_execution_info, expected_execution_info);
> 
>     // Negative flow: not enough fee paid on L1
> ```

done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1201#-:-NkUKykcD1DLCkoE1Cy0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
