### PR TITLE
Skip charge_fee in case max_fee is 0 (for testing).

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/298)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/298)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/298#-NOxZq7G8vlxJEbb9V_f:-NOxZq7G8vlxJEbb9V_g:bide44z) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16b2c007a0e6382e42bd8833d8a50d190ce3e94/crates/blockifier/src/transaction/account_transaction.rs#L225)):*
> ```XML
>         account_tx_context: &AccountTransactionContext,
>     ) -> TransactionExecutionResult<(Fee, Option<CallInfo>)> {
>         if account_tx_context.max_fee == Fee(0) {
> ```

Perhaps create one variable? 
WDYT of using `Fee::default()`?



_Code quote:_
```XML
Fee(0)
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/298)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/298#-NOxZq7G8vlxJEbb9V_f:-NOxcjBE60TiNkFrXp1h:b-1eh3wi) ([raw file](https://github.com/starkware-libs/blockifier/blob/d16b2c007a0e6382e42bd8833d8a50d190ce3e94/crates/blockifier/src/transaction/account_transaction.rs#L225)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps create one variable? 
WDYT of using `Fee::default()`?
</blockquote></details>

Sure, done.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/298)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/298#-NOxsOS57Rmk65kILWdE:-NOxsOS57Rmk65kILWdF:bxoffpb) ([raw file](https://github.com/starkware-libs/blockifier/blob/80160d4ecf7ce7f6d8622565b5cea7c26dd899f2/crates/blockifier/src/transaction/account_transaction.rs#L228)):*
> ```XML
>         if account_tx_context.max_fee == no_fee {
>             // Fee charging is not enforced in some tests.
>             return Ok((no_fee, None));
> ```

Shouldn't we add protection...? Or, since this is for decentraland, if a sequencer doesn't charge fee that's it's own responsibility?
What if we forget this here and people just use `max_fee=0` to bypass paying fees?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/298)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/298#-NOxsOS57Rmk65kILWdE:-NOxzeUe6GdlpVUc_GaD:b-cep4pa) ([raw file](https://github.com/starkware-libs/blockifier/blob/80160d4ecf7ce7f6d8622565b5cea7c26dd899f2/crates/blockifier/src/transaction/account_transaction.rs#L228)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Shouldn't we add protection...? Or, since this is for decentraland, if a sequencer doesn't charge fee that's it's own responsibility?
What if we forget this here and people just use `max_fee=0` to bypass paying fees?
</blockquote></details>

Txs can only be sent through the gateway, where there is a validation that the max fee is greater than 0. This validation is configurable and is disabled in tests only.

**Pull request merged**
