### PR TITLE
Define get_strk_gas_price on executor

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/887)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/887)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/887#-NdVa9Rd-3pUs6ThjdLj:-NdVaxXICFw1t3LpC1LV:b4i5x65) ([raw file](https://github.com/starkware-libs/blockifier/blob/446710ff475cb0ef557a7c3ffa0c88283c428498/crates/native_blockifier/src/py_block_executor.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Talked to @elintul, she noted a possibe issue here.
StateReader might not be enough, in case the API requires us to `execute` some `CallEntryPoint`  that'll call `get_tvl/get_ratio`.
In that case, we'll need the `TransactionExecutor itself, not just the reader.
</blockquote></details>

*I stand corrected (thanks Elin again...), `TransactionExecutor` itself isn't applicable, because it can only execute transactions, not just entry points.

But we do need to initialize a `State` instance (cachedState will do, then again, we're not really Caching...) in order to call `CallEntryPoint#execute`.

That might be enough, but very likely that we'll have to encpasulate this logic with some new abstraction.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/887)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/887#-NdVa9Rd-3pUs6ThjdLj:-NdVdDvY1qVdJl9Xdurx:bedy5jl) ([raw file](https://github.com/starkware-libs/blockifier/blob/446710ff475cb0ef557a7c3ffa0c88283c428498/crates/native_blockifier/src/py_block_executor.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

*I stand corrected (thanks Elin again...), `TransactionExecutor` itself isn't applicable, because it can only execute transactions, not just entry points.

But we do need to initialize a `State` instance (cachedState will do, then again, we're not really Caching...) in order to call `CallEntryPoint#execute`.

That might be enough, but very likely that we'll have to encpasulate this logic with some new abstraction.
</blockquote></details>

Would rather not use an executor, so we don't have the issue of a partially initialized BlockInfo

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/887)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/887#-NdVa9Rd-3pUs6ThjdLj:-NdVdUAW2YehFa-7Bi6i:beyonh7) ([raw file](https://github.com/starkware-libs/blockifier/blob/446710ff475cb0ef557a7c3ffa0c88283c428498/crates/native_blockifier/src/py_block_executor.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Would rather not use an executor, so we don't have the issue of a partially initialized BlockInfo
</blockquote></details>

yes yes the executor won't fit anyway, it works on `Transaction`s, which we don't have at this point.
We just need to call a specific CallEntryPoint#execute, which it can't do.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/887)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/887#-NdVa9Rd-3pUs6ThjdLj:-NdZDB_90279Vxgqhg0t:b-lb4g3h) ([raw file](https://github.com/starkware-libs/blockifier/blob/446710ff475cb0ef557a7c3ffa0c88283c428498/crates/native_blockifier/src/py_block_executor.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

yes yes the executor won't fit anyway, it works on `Transaction`s, which we don't have at this point.
We just need to call a specific CallEntryPoint#execute, which it can't do.
</blockquote></details>

soooo... y blocking?

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/887)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/887#-NdVa9Rd-3pUs6ThjdLj:-Ndcb3xw0WyyaKgieavi:b-bicj1c) ([raw file](https://github.com/starkware-libs/blockifier/blob/446710ff475cb0ef557a7c3ffa0c88283c428498/crates/native_blockifier/src/py_block_executor.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

soooo... y blocking?
</blockquote></details>

unblocked, but just note that there is probably a bit more design work left here, cause we need to call EntryPoints without an executor, which is something we haven't done thus far.

**Pull request merged**
