### PR TITLE
Make gas costs more similar to os_resources.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1173)

### CODE REVIEW

**Review by noaov1 — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1173)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/abi/constants.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1173#-Nkk5Z0V4IbzByVMrGYm:-Nkk5Z0V4IbzByVMrGYn:bidpvhr) ([raw file](https://github.com/starkware-libs/blockifier/blob/c763399bd33518f9d87725568bba52d83e954c59/crates/blockifier/src/abi/constants.rs#L53)):*
> ```XML
> pub const ENTRY_POINT_INITIAL_BUDGET: u64 = 100 * STEP_GAS_COST;
> // The initial gas budget for a system call (this value is hard-coded by the compiler).
> // This needs to be high enough to cover OS costs in the case of failure due to out of gas.
> ```

Can you please elaborate? In case we of out of gas failure we will charge according to the gas consumed until the failure? 



_Code quote:_
```XML
// This needs to be high enough to cover OS costs in the case of failure due to out of gas.
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1173#-Nkk2WlqExDgz07FzLnz:-Nkk2WlqExDgz07FzLo-:bok54it) ([raw file](https://github.com/starkware-libs/blockifier/blob/c763399bd33518f9d87725568bba52d83e954c59/crates/blockifier/src/execution/syscalls/hint_processor.rs#L27)):*
> ```XML
> use thiserror::Error;
> 
> use crate::abi::constants::{self, SYSCALL_BASE_GAS_COST};
> ```

And use `constants::SYSCALL_BASE_GAS_COST`.



_Suggestion:_
```XML
use crate::abi::constants;
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 351 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1173#-Nkk3yRS9GiXIRMpym6J:-Nkk3yRS9GiXIRMpym6K:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/c763399bd33518f9d87725568bba52d83e954c59/crates/blockifier/src/execution/syscalls/hint_processor.rs#L351)):*
> ```XML
>         vm: &mut VirtualMachine,
>         execute_callback: ExecuteCallback,
>         base_gas_cost: u64,
> ```

WDYT?



_Suggestion:_
```XML
      required_gas: u64,
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 363 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1173#-Nkk4GcA7CEg4W9U78Im:-Nkk4GcA7CEg4W9U78In:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c763399bd33518f9d87725568bba52d83e954c59/crates/blockifier/src/execution/syscalls/hint_processor.rs#L363)):*
> ```XML
>         ) -> SyscallResult<Response>,
>     {
>         // Substract precharged cost from `base_gas_cost`.
> ```





_Suggestion:_
```XML
// Refund the base amount that was pre-charged.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/abi/constants.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1173#-Nkk5Z0V4IbzByVMrGYm:-NknkBItAKLlW8I2DMUw:bae9l6x) ([raw file](https://github.com/starkware-libs/blockifier/blob/c763399bd33518f9d87725568bba52d83e954c59/crates/blockifier/src/abi/constants.rs#L53)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please elaborate? In case we of out of gas failure we will charge according to the gas consumed until the failure?
</blockquote></details>

currently, only call_contract (and library_call)  charge different amounts of failure, all the other syscalls charge the `SYSCALL_BASE_GAS_COST` in case of failure, be that might change in the future.

**Comment by ilyalesokhin-starkware** [comment]
This change does not change any costs, only split the cost of each system call into ` SYSCALL_BASE_GAS_COST` and the rest of the cost like in the main repo.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1173)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1173#-Nkk2WlqExDgz07FzLnz:-Nknpl5T-zqMohFNffek:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/c763399bd33518f9d87725568bba52d83e954c59/crates/blockifier/src/execution/syscalls/hint_processor.rs#L27)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And use `constants::SYSCALL_BASE_GAS_COST`.
</blockquote></details>

done
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 351 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1173#-Nkk3yRS9GiXIRMpym6J:-NknnjS_0MAmB4z2C3aN:b-o3dn9t) ([raw file](https://github.com/starkware-libs/blockifier/blob/c763399bd33518f9d87725568bba52d83e954c59/crates/blockifier/src/execution/syscalls/hint_processor.rs#L351)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

in the main repo `required_gas` is the amount after the subtraction.
https://github.com/starkware-industries/starkware/blob/de88501fb7f7ada8be40d0df64ec08523a79adfb/src/starkware/starknet/core/os/syscall_handler.py#L697
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 363 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1173#-Nkk4GcA7CEg4W9U78Im:-NknpefA8Nk5PAIDri5P:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/c763399bd33518f9d87725568bba52d83e954c59/crates/blockifier/src/execution/syscalls/hint_processor.rs#L363)):*
> ```XML
>         ) -> SyscallResult<Response>,
>     {
>         // Substract precharged cost from `base_gas_cost`.
> ```

done

**Pull request merged**
