### PR TITLE
Complete VM resources logic.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/348)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/348)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/348#-NR-3pFN4pLcBlGmlHq7:-NR-3pFN4pLcBlGmlHq8:b-j4d4hy) ([raw file](https://github.com/starkware-libs/blockifier/blob/dc452f035c9e1adef147500184996130f2d0ab10/crates/blockifier/src/execution/execution_utils.rs#L227)):*
> ```XML
>         .map_err(VirtualMachineError::TracerError)?
>         .filter_unused_builtins();
>     syscall_handler.execution_resources.vm_resources =
> ```

Asked LC to implement `+=`.



_Code quote:_
```XML
    syscall_handler.execution_resources.vm_resources =
        (syscall_handler.execution_resources.vm_resources).clone() + external_call_vm_resources;
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/348)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/348#-NR-5cwI3A5L4ikaD8Sc:-NR-5cwI3A5L4ikaD8Sd:blbj27j) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3e7558683a4f46ccf5e07999bb98fcc4e92ec99/crates/blockifier/src/execution/execution_utils.rs#L187)):*
> ```XML
> 
> /// Runs the runner from the given PC.
> /// Returns the VM execution resources used, including inner calls.
> ```

... where?



_Code quote:_
```XML
Returns the VM execution resources used, including inner calls.
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 237 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/348#-NR-6S1I4uf6TsUE73iH:-NR-6S1I4uf6TsUE73iI:bpl5h24) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3e7558683a4f46ccf5e07999bb98fcc4e92ec99/crates/blockifier/src/execution/execution_utils.rs#L237)):*
> ```XML
> 
>     let vm_resources =
>         (syscall_handler.execution_resources.vm_resources).clone() - previous_vm_resources;
> ```

I don't understand what's going on...
isn't `external_call_vm_resources` equal to this difference?
I.e. the `previous_vm_resources` are the resources in `syscall_handler.execution_resources.vm_resources` before the current execution resources were added?
Or is `external_call_vm_resources` *not* the current context's resources...?



_Code quote:_
```XML
    let vm_resources =
        (syscall_handler.execution_resources.vm_resources).clone() - previous_vm_resources;
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 419 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/348#-NR-6e41DAg86TAoQpBk:-NR-6e41DAg86TAoQpBl:b-tevlzr) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3e7558683a4f46ccf5e07999bb98fcc4e92ec99/crates/blockifier/src/execution/execution_utils.rs#L419)):*
> ```XML
>     }
> 
>     pub fn mark_as_accessed(&self, vm: &mut VirtualMachine) -> Result<(), PostExecutionError> {
> ```

makes the call faster? (by reference better than by value on `self`?)



_Code quote:_
```XML
&
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/348)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/348#-NR-5cwI3A5L4ikaD8Sc:-NR-LH2g43MDqjvZNOkP:bay750v) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3e7558683a4f46ccf5e07999bb98fcc4e92ec99/crates/blockifier/src/execution/execution_utils.rs#L187)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... where?
</blockquote></details>

Sorry, a previous iteration.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 237 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/348#-NR-6S1I4uf6TsUE73iH:-NR-LZ9Y7aCXeQvAToNi:b26xzxx) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3e7558683a4f46ccf5e07999bb98fcc4e92ec99/crates/blockifier/src/execution/execution_utils.rs#L237)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't understand what's going on...
isn't `external_call_vm_resources` equal to this difference?
I.e. the `previous_vm_resources` are the resources in `syscall_handler.execution_resources.vm_resources` before the current execution resources were added?
Or is `external_call_vm_resources` *not* the current context's resources...?
</blockquote></details>

No, it's only the external usage (not inner calls). Was a mind-f*ck for me too. 
Adding the external resources is the recursion step; this is how the resources are accumulated.

How would you call it? Maybe `vm_resources_with_inner_calls` and `vm_resources_without_inner_calls` is the clearest? 
Also, can you suggest a good additional documentation that'll help future readers? I thought what I added (comments and variable names was enough, but apparently not).
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 419 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/348#-NR-6e41DAg86TAoQpBk:-NR-LLyA2ifMhC26bsA1:b-x2swg7) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3e7558683a4f46ccf5e07999bb98fcc4e92ec99/crates/blockifier/src/execution/execution_utils.rs#L419)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

makes the call faster? (by reference better than by value on `self`?)
</blockquote></details>

It enforced this call to be the last one made on the syscall handler (it consumes it), and I don't want it to be the last. I want to first mark memory holes as accessed and close them, then validate (which also mutates the VM), only then get the VM resources.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/348)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Pull request merged**
