### PR TITLE
Add nonce count and consider it in the modified contracts.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/651)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/651)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYlP0Pl75oXhl9GUyU2:-NYlP0Pl75oXhl9GUyU3:b-bmdtf6) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e50dd22e6de10178b8c9a40fe19cef9863a272/crates/blockifier/src/transaction/transactions_test.rs#L335)):*
> ```XML
>         actual_fee: expected_actual_fee,
>         actual_resources: ResourcesMapping(HashMap::from([
>             (abi_constants::GAS_USAGE.to_string(), 2448),
> ```

Any good way of verifying that this new gas number makes sense?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/651)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYlP0Pl75oXhl9GUyU2:-NYlpzEX67_CTJUIUjm6:bzbv19k) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e50dd22e6de10178b8c9a40fe19cef9863a272/crates/blockifier/src/transaction/transactions_test.rs#L335)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Any good way of verifying that this new gas number makes sense?
</blockquote></details>

Great question. Adding the `nonce_counter` to the modified contracts added one more contract that was modified (the account contract).
This results in:



_Code snippet:_
```XML
n_modified_contracts +=1
-> onchain_data_segment_length +=2 (for each modified contract we write: contract address, number of modified storage cells)
-> sharp_gas_usage +=2 *612 (SHARP_GAS_PER_MEMORY_WORD)
-> l1_gas_usage += 1224 (as desired)
```

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/651)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYm9ibyCUCX-rIWwK7H:-NYm9ibyCUCX-rIWwK7I:b2ru7fl) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e50dd22e6de10178b8c9a40fe19cef9863a272/crates/blockifier/src/state/cached_state.rs#L52)):*
> ```XML
>     /// Returns the number of storage changes done through this state.
>     /// Any change to the contract's state (storage, nonce, class hash) is considered.
>     pub fn count_actual_state_changes(&self) -> (usize, usize, usize, usize) {
> ```

Perhaps it's time for a struct?
Only if it's more readable.



_Code quote:_
```XML
(usize, usize, usize, usize)
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYm9t4d3ghGtU-xicrb:-NYm9t4d3ghGtU-xicrc:bft6dw8) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e50dd22e6de10178b8c9a40fe19cef9863a272/crates/blockifier/src/state/cached_state.rs#L55)):*
> ```XML
>         // Storage Update.
>         let storage_updates = &self.cache.get_storage_updates();
>         let mut modified_contracts: HashSet<ContractAddress> =
> ```

Add a short comment (maybe in the docstring) that for each contract instance (address) we have three attributes: `(class hash, nonce, storage root)`; the state updates correspond to them.



_Code quote:_
```XML
modified_contracts
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYmAL7fAu7TkPqu3huY:-NYmAL7fAu7TkPqu3huZ:bdlr9kv) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e50dd22e6de10178b8c9a40fe19cef9863a272/crates/blockifier/src/transaction/transaction_utils.rs#L46)):*
> ```XML
>     l1_handler_payload_size: Option<usize>,
> ) -> TransactionExecutionResult<ResourcesMapping> {
>     let (n_storage_changes, n_modified_contracts, n_class_updates, _n_nonce_updates) =
> ```

Will be used next PR?



_Code quote:_
```XML
_n_nonce_updates
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/651)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYm9ibyCUCX-rIWwK7H:-NYmXB7oAVlNws5YkjFL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e50dd22e6de10178b8c9a40fe19cef9863a272/crates/blockifier/src/state/cached_state.rs#L52)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps it's time for a struct?
Only if it's more readable.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYmAL7fAu7TkPqu3huY:-NYmQ8095WmREgc-z3mX:bc0mldu) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e50dd22e6de10178b8c9a40fe19cef9863a272/crates/blockifier/src/transaction/transaction_utils.rs#L46)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Will be used next PR?
</blockquote></details>

Actually no. Currently, we don't plan to use it as it is meaningless in DA. Yoni said to include it in the return value for symmetry.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/651)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYmn8Iz0hhi7vWqygfY:-NYmn8Iz0hhi7vWqygfZ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d147ee0fd659d4c3699814de0863916f1e7ae883/crates/blockifier/src/state/cached_state.rs#L46)):*
> ```XML
>     /// Returns the number of storage changes done through this state.
>     /// For each contract instance (address) we have three attributes: `(class hash, nonce, storage
>     /// root)`; the state updates correspond to them.
> ```





_Suggestion:_
```XML
    /// For each contract instance (address) we have three attributes: (class hash, nonce, storage
    /// root); the state updates correspond to them.
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYmnF3TC8lWICNvBX0S:-NYmnF3TC8lWICNvBX0T:b-x70ep2) ([raw file](https://github.com/starkware-libs/blockifier/blob/d147ee0fd659d4c3699814de0863916f1e7ae883/crates/blockifier/src/state/cached_state.rs#L53)):*
> ```XML
>         let storage_updates = &self.cache.get_storage_updates();
> 
>         let mut modified_contracts: HashSet<ContractAddress> =
> ```

Remove blank line above.



_Code quote:_
```XML
let mut modified_contracts: HashSet<ContractAddress> =
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYmnIgu1Vts8tjlIyh0:-NYmnIgu1Vts8tjlIyh1:b-4zsvm) ([raw file](https://github.com/starkware-libs/blockifier/blob/d147ee0fd659d4c3699814de0863916f1e7ae883/crates/blockifier/src/state/cached_state.rs#L77)):*
> ```XML
>     /// Same for class hash and nonce writes.
>     // TODO(Noa, 30/07/23): Consider adding DB getters in bulk (via a DB read transaction).
>     fn update_initial_values_of_write_only_access(&mut self) -> StateResult<()> {
> ```

Can you please move this to another PR?



_Code quote:_
```XML
update_initial_values_of_write_only_access
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYmAL7fAu7TkPqu3huY:-NYmn11FAfr9H01qKV52:bch9lbg) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e50dd22e6de10178b8c9a40fe19cef9863a272/crates/blockifier/src/transaction/transaction_utils.rs#L46)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Actually no. Currently, we don't plan to use it as it is meaningless in DA. Yoni said to include it in the return value for symmetry.
</blockquote></details>

Return value of what?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/651)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYmnIgu1Vts8tjlIyh0:-NYmqtHo9SkjugnrSnVG:b-yooau7) ([raw file](https://github.com/starkware-libs/blockifier/blob/d147ee0fd659d4c3699814de0863916f1e7ae883/crates/blockifier/src/state/cached_state.rs#L77)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you please move this to another PR?
</blockquote></details>

It was already merged :) (maybe you see it because I had conflicts)
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYmAL7fAu7TkPqu3huY:-NYmr3jeD4WoDNouI_ZM:b-h2590i) ([raw file](https://github.com/starkware-libs/blockifier/blob/50e50dd22e6de10178b8c9a40fe19cef9863a272/crates/blockifier/src/transaction/transaction_utils.rs#L46)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Return value of what?
</blockquote></details>

Of `count_actual_state_changes`.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/651#-:-NYmrmNs8UE4JQ2bP_jW:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYmnIgu1Vts8tjlIyh0:-NYmreQG6u4Bh86Y3mvQ:b-gp6tgg) ([raw file](https://github.com/starkware-libs/blockifier/blob/d147ee0fd659d4c3699814de0863916f1e7ae883/crates/blockifier/src/state/cached_state.rs#L77)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It was already merged :) (maybe you see it because I had conflicts)
</blockquote></details>

Okay, got it. Can you briefly explain this change then? Is it the `0 -> 5 -> 0` fix?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/651)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/651#-NYmnIgu1Vts8tjlIyh0:-NYms3zk1fQw5CKSBL9S:b-k9qt1b) ([raw file](https://github.com/starkware-libs/blockifier/blob/d147ee0fd659d4c3699814de0863916f1e7ae883/crates/blockifier/src/state/cached_state.rs#L77)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Okay, got it. Can you briefly explain this change then? Is it the `0 -> 5 -> 0` fix?
</blockquote></details>

First, we deal with cases where we set a value before reading it (hence, we do not update the `initial_value` mapping). Second, the relevant cases are setting a value that has already been written before. See #648 .

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/651)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Pull request merged**
