### PR TITLE
Add pre-validation cartesian tests

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1166)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1166)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwS_JS8qoDScQ-Hra5:-NjwS_JS8qoDScQ-Hra6:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/test_utils.rs#L213)):*
> ```XML
>     pub fn rollback(&mut self, account_address: ContractAddress) {
>         let zero = Felt252::zero();
>         let current = self.next_nonce.get(&account_address).unwrap_or(&zero);
> ```





_Suggestion:_
```XML
        let current = self.next_nonce.get(&account_address).unwrap_or_default();
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwSk1k2jXxmvMS_F3M:-NjwSk1k2jXxmvMS_F3N:b-h0710o) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/account_transaction.rs#L45)):*
> ```XML
> #[cfg(test)]
> #[path = "execution_flavors_test.rs"]
> mod flavors_test;
> ```

Nice. What is the meaning of the module name?



_Code quote:_
```XML
mod flavors_test;
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwXBjJDofoy4P7NLAI:-NjwXBjJDofoy4P7NLAJ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L45)):*
> ```XML
> #[case(TransactionVersion::THREE, FeeType::Strk, false)]
> fn test_simulate_validate_charge_fee_pre_validate(
>     #[values(true, false)] simulate: bool,
> ```





_Suggestion:_
```XML
    #[values(true, false)] only_query: bool,
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-Njw_Z377I4MbRNgwQjn:-Njw_Z383Gepkwr2bG9x:b-6gnw5v) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L56)):*
> ```XML
>     let gas_price = block_context.gas_prices.get_by_fee_type(&fee_type);
> 
>     // Create two states, one of which contains a contract that can fail validation on demand.
> ```

Not yet, right?



_Code quote:_
```XML
    // Create two states, one of which contains a contract that can fail validation on demand.
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwW7FX3vbmzwl_Q1UF:-NjwW7FX3vbmzwl_Q1UG:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L68)):*
> ```XML
>     // In each scenario, need to verify the reported fee - even if charge_fee is false, we need to
>     // report the fee.
>     // Also, unwrap_err and if unwrap, verify revert state.
> ```

?



_Code quote:_
```XML
    // Also, unwrap_err and if unwrap, verify revert state.
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwWDk_2LXhJfyhL4u1:-NjwWDk_2LXhJfyhL4u2:blcy7eg) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L73)):*
> ```XML
>     // 1. Invalid nonce.
>     // 2. Not enough resource bounds for minimal fee.
>     // 3. Not enough balance for resource bounds.
> ```

4. `max_l1_gas_price < actual_l1_gas_price`?
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwXVpC80bu0odLzx5H:-NjwXVpD-fTbqIP99A4T:bed4070) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L91)):*
> ```XML
>     // First scenario: invalid nonce. Regardless of flags, should fail.
>     let invalid_nonce = Nonce(stark_felt!(7_u8));
>     let account_nonce = nonce_manager.next(account_address);
> ```

Wouldn't it be easier to read it from the state? (avoid the rollback)



_Code quote:_
```XML
    let account_nonce = nonce_manager.next(account_address);
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwZedU6MFmQB6QQoNJ:-NjwZedU6MFmQB6QQoNK:b280drh) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L123)):*
> ```XML
>             actual_gas_used as u128
>         );
>         assert_eq!(tx_execution_info.actual_fee, actual_fee);
> ```

Why both of them needed?



_Code quote:_
```XML
        assert_eq!(
            calculate_tx_l1_gas_usage(&tx_execution_info.actual_resources, &block_context).unwrap(),
            actual_gas_used as u128
        );
        assert_eq!(tx_execution_info.actual_fee, actual_fee);
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-Njw_mGh9mbaexifAJGG:-Njw_mGh9mbaexifAJGH:bsdgx9e) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L125)):*
> ```XML
>         assert_eq!(tx_execution_info.actual_fee, actual_fee);
>     } else {
>         nonce_manager.rollback(account_address);
> ```

If you will `abort` the transactional state, can you avoid the nonce roolback?



_Code quote:_
```XML
nonce_manager.rollback(account_address);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1166)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwS_JS8qoDScQ-Hra5:-NjwdCne5HPFM6yqNaBZ:b-ugpazo) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/test_utils.rs#L213)):*
> ```XML
>     pub fn rollback(&mut self, account_address: ContractAddress) {
>         let zero = Felt252::zero();
>         let current = self.next_nonce.get(&account_address).unwrap_or(&zero);
> ```

`&Felt252` doesn't implement `Default` apparently. Need a default reference here
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwSk1k2jXxmvMS_F3M:-NjwdJn-3jr-EfF45-3L:b-u6aj8o) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/account_transaction.rs#L45)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Nice. What is the meaning of the module name?
</blockquote></details>

validate, simulate, charge_fee... are execution flavors. WDYT?
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwXBjJDofoy4P7NLAI:-NjwdV9e3pli-moQolyl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L45)):*
> ```XML
> #[case(TransactionVersion::THREE, FeeType::Strk, false)]
> fn test_simulate_validate_charge_fee_pre_validate(
>     #[values(true, false)] simulate: bool,
> ```

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-Njw_Z377I4MbRNgwQjn:-Njwdo1RDlByuikjU-lq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L56)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not yet, right?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwW7FX3vbmzwl_Q1UF:-NjwdpKm1ZqhYbUEV1bG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L68)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwWDk_2LXhJfyhL4u1:-NjweYeEBTTC0wab6Qlq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L73)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

4. `max_l1_gas_price < actual_l1_gas_price`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwXVpC80bu0odLzx5H:-NjwexOH73oMK7Fcdg4N:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L91)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Wouldn't it be easier to read it from the state? (avoid the rollback)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwZedU6MFmQB6QQoNJ:-Njwf02N1EO4TFWSen8v:bs4614y) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L123)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why both of them needed?
</blockquote></details>

actual resources and actual fee may not be directly related; in pre-validate this is probably redundant (in post-execute it's not), but no harm and better to keep it IMO
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-Njw_mGh9mbaexifAJGG:-NjwfC4J9RYtqHlTkWP4:bj0gmtz) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L125)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

If you will `abort` the transactional state, can you avoid the nonce roolback?
</blockquote></details>

I no longer work with a transactional state; too much boilerplate (extra two lines every time)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 3 of 5 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1166)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwSk1k2jXxmvMS_F3M:-Nk9g7J-6bpBJAr9_Cg5:b2h3dfa) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/account_transaction.rs#L45)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

validate, simulate, charge_fee... are execution flavors. WDYT?
</blockquote></details>

Okay. Out of curiosity- Is the name must include test?
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwZedU6MFmQB6QQoNJ:-Nk9gbn_CeqNXm_O8p9w:bq5hrk4) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L123)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

actual resources and actual fee may not be directly related; in pre-validate this is probably redundant (in post-execute it's not), but no harm and better to keep it IMO
</blockquote></details>

I see. I wonder if it can be confusing.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-Njw_mGh9mbaexifAJGG:-Nk9ggo_C1JlnEyBKmdH:b-32kst9) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L125)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I no longer work with a transactional state; too much boilerplate (extra two lines every time)
</blockquote></details>

Why? Isn't it just writing `abort()` at the end of each test?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1166)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwSk1k2jXxmvMS_F3M:-Nk9qxhx8Fe6z0v8ZhU0:b1kofhx) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/account_transaction.rs#L45)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Okay. Out of curiosity- Is the name must include test?
</blockquote></details>

IDK, but IMO it should
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-NjwZedU6MFmQB6QQoNJ:-Nk9rHZk5Zr6RzcIBpDm:boc7y49) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L123)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see. I wonder if it can be confusing.
</blockquote></details>

Added a utility function for this + docstring
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-Njw_mGh9mbaexifAJGG:-Nk9rBQ75r90mtRaFkYC:b-5yykm6) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L125)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why? Isn't it just writing `abort()` at the end of each test?
</blockquote></details>

no, because I also need to re-open a transactional state after aborting the last one (`abort()` is consuming)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-Njw_mGh9mbaexifAJGG:-Nk9ygAAEyzOb_0IWihY:bpnv1kj) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L125)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, because I also need to re-open a transactional state after aborting the last one (`abort()` is consuming)
</blockquote></details>

Oh, I see. So we simply revert the nonce incrementation as the state should not change?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1166#-Njw_mGh9mbaexifAJGG:-NkAEwnP5UO-mDnG-Haz:b2nign6) ([raw file](https://github.com/starkware-libs/blockifier/blob/91c737a506977532f5c618dfc3cde6e6115ee4e9/crates/blockifier/src/transaction/execution_flavors_test.rs#L125)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh, I see. So we simply revert the nonce incrementation as the state should not change?
</blockquote></details>

yes

**Pull request merged**
