### PR TITLE
Remove redundant code

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1028)

### CODE REVIEW

**Review by zuphitf — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1028)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 736 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1028#-Nh_pmbd6WfveSsmzTXC:-Nh_pmbeCUOFrQrpMXuF:b-ndgrn3) ([raw file](https://github.com/starkware-libs/blockifier/blob/be64c5ebcd142119d97776370374618fc65296c5/crates/blockifier/src/transaction/account_transactions_test.rs#L736)):*
> ```XML
>     // Make sure the resources in block of invocation 0 and 1 are the same, except for the number
>     // of cairo steps.
>     actual_resources_1.0.insert("n_steps".to_string(), *n_steps_0);
> ```

That is kinda an ugly way to do that. Can you pop that field out of both (or add the delta to one of them)?



_Code quote:_
```XML
    // Make sure the resources in block of invocation 0 and 1 are the same, except for the number
    // of cairo steps.
    actual_resources_1.0.insert("n_steps".to_string(), *n_steps_0);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1028)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 736 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1028#-Nh_pmbd6WfveSsmzTXC:-Nh_xd6P3ig-XT3hLCgO:b7hwxk9) ([raw file](https://github.com/starkware-libs/blockifier/blob/be64c5ebcd142119d97776370374618fc65296c5/crates/blockifier/src/transaction/account_transactions_test.rs#L736)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

That is kinda an ugly way to do that. Can you pop that field out of both (or add the delta to one of them)?
</blockquote></details>

adding the delta means replacing `*n_steps_1` with `*n_steps_1 + (*n_steps_0 - *n_steps_1)`, it's equivalent; right?
Popping the field from both means both need to be mutable (currently only the second resources object is mutable)

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 736 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1028#-Nh_pmbd6WfveSsmzTXC:-Nha1hT4BGzeHl7WzD3B:b-2ibb41) ([raw file](https://github.com/starkware-libs/blockifier/blob/be64c5ebcd142119d97776370374618fc65296c5/crates/blockifier/src/transaction/account_transactions_test.rs#L736)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

adding the delta means replacing `*n_steps_1` with `*n_steps_1 + (*n_steps_0 - *n_steps_1)`, it's equivalent; right?
Popping the field from both means both need to be mutable (currently only the second resources object is mutable)
</blockquote></details>

You have `let single_call_steps_delta = n_steps_1 - n_steps_0;` right below though, it is used in other assertions too.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1028)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 736 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1028#-Nh_pmbd6WfveSsmzTXC:-Nha69v6DJnihgvXhuC0:bcyxokj) ([raw file](https://github.com/starkware-libs/blockifier/blob/be64c5ebcd142119d97776370374618fc65296c5/crates/blockifier/src/transaction/account_transactions_test.rs#L736)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

You have `let single_call_steps_delta = n_steps_1 - n_steps_0;` right below though, it is used in other assertions too.
</blockquote></details>

Nice! done

**Review by zuphitf — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1028)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
