### PR TITLE
add StateChanges::merge(..) and some small fixes (renames etc)

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/790)

### CODE REVIEW

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/state/cached_state.rs` line 583 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCF-np4eaoszb2UDy5:-NaCF-np4eaoszb2UDy6:b-6re4s0) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state.rs#L583)):*
> ```XML
> 
> impl From<&StateChanges> for StateChangesCount {
>     fn from(state_changes: &StateChanges) -> Self {
> ```

better make this a borrow rather than having to consume/clone this just to get lengths



_Code quote:_
```XML
state_changes: &StateChanges
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/790)* status: all files reviewed, 3 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/state/cached_state.rs` line 571 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCFTgr7GRGQQgSb7Td:-NaCFTgr7GRGQQgSb7Te:b-xik2f3) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state.rs#L571)):*
> ```XML
>         merged_state_changes
>     }
> }
> ```

If I want to merge `x` state changes, we will have `x+1` state changes in memory.
IIUC, the only use case is merging two state changes, and even then, we will no longer need either.
No problem IMO passing the inputs as reference, but I prefer something like
```
pub fn merge(&mut self, state_changes: &[&Self]) -> Self {
    for ... {
        self.storage_updates.extend(...)
        ...
    }
    self
}
```
that mutates in-place. WDYT?

Also, if you change the signature to
```
pub fn update(&mut self, other: &Self) -> Self
```
it would be much simpler to test, no? And this is the only use case ATM



_Code quote:_
```XML
impl StateChanges {
    /// Merges the given state changes into a single one. Note that the order of the state changes
    /// is important. The state changes are merged in the order they appear in the given vector.
    pub fn merge(state_changes: &[&Self]) -> Self {
        let mut merged_state_changes = Self::default();
        for state_change in state_changes {
            merged_state_changes.storage_updates.extend(state_change.storage_updates.clone());
            merged_state_changes.class_hash_updates.extend(state_change.class_hash_updates.clone());
            merged_state_changes
                .compiled_class_hash_updates
                .extend(state_change.compiled_class_hash_updates.clone());
            merged_state_changes.modified_contracts.extend(state_change.modified_contracts.clone());
        }

        merged_state_changes
    }
}
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCGT0JBp1NPKYKHxOb:-NaCGT0K3PiEGJ0fF8_K:b-xwyrhw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state_test.rs#L313)):*
> ```XML
> 
>     // Make sure that null state changes are attained from a transactional state by
>     // `get_actual_state_changes_for_fee_charge` after a commit and before any additional changes.
> ```

you recreate `transactional_state` before you call `get_actual_state_changes_for_fee_charge`; there was no commit. Maybe delete the recreation?



_Code quote:_
```XML
after a commit
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 327 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCGiVF5U2BassmW8qQ:-NaCGiVF5U2BassmW8qR:b7pm2cz) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state_test.rs#L327)):*
> ```XML
> 
>     // Get the storage updates' addresses and keys from the state_changes1, to overwrite.
>     let mut storeage_updates_keys = state_changes1.storage_updates.keys();
> ```

typo + only one plural `s`



_Suggestion:_
```XML
storage_update_keys
```

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/790)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 571 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCFTgr7GRGQQgSb7Td:-NaCI9A39WxqQwi3NMHF:b8hx55z) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state.rs#L571)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

If I want to merge `x` state changes, we will have `x+1` state changes in memory.
IIUC, the only use case is merging two state changes, and even then, we will no longer need either.
No problem IMO passing the inputs as reference, but I prefer something like
```
pub fn merge(&mut self, state_changes: &[&Self]) -> Self {
    for ... {
        self.storage_updates.extend(...)
        ...
    }
    self
}
```
that mutates in-place. WDYT?

Also, if you change the signature to
```
pub fn update(&mut self, other: &Self) -> Self
```
it would be much simpler to test, no? And this is the only use case ATM
</blockquote></details>

Hmm, I actually use the fact that this doesn't affect any of the original states in the test. I merge and re-merge in all sorts of orders.
Passing `self` will only save one line (`let mut merged_state_changes = Self::default();`) and will take this capability away.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCGT0JBp1NPKYKHxOb:-NaCHgl3ERZ1FovhFDfe:b-yfapvh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state_test.rs#L313)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you recreate `transactional_state` before you call `get_actual_state_changes_for_fee_charge`; there was no commit. Maybe delete the recreation?
</blockquote></details>

wdym? Committed 3 lines above, right after creating state_changes1

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/790)* status: all files reviewed, 3 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/state/cached_state.rs` line 571 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCFTgr7GRGQQgSb7Td:-NaCJfli54WVOHaFrdsJ:bsxy13m) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state.rs#L571)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Hmm, I actually use the fact that this doesn't affect any of the original states in the test. I merge and re-merge in all sorts of orders.
Passing `self` will only save one line (`let mut merged_state_changes = Self::default();`) and will take this capability away.
</blockquote></details>

1. It will save memory allocation (I think, not sure how smart rust compiler is to know by use case that the original object can be reused)
2. No reason to implement something very general if it won't be used
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCGT0JBp1NPKYKHxOb:-NaCIwVK4u5NaL9nVcfD:b-19mps0) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state_test.rs#L313)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

wdym? Committed 3 lines above, right after creating state_changes1
</blockquote></details>

because this
```
    let mut transactional_state = CachedState::create_transactional(&mut state);
    let state_changes1 = create_state_changes_for_test(&mut transactional_state);
    transactional_state.commit();

    // Make sure that null state changes are attained from a transactional state by
    // `get_actual_state_changes_for_fee_charge` after a commit and before any additional changes.
    let block_context = BlockContext::create_for_testing();
    let mut transactional_state = CachedState::create_transactional(&mut state);
```
first and last lines create `transactional_state`.
last line shadows first variable.

You are basically testing that this:
```
    let mut transactional_state = CachedState::create_transactional(&mut state);
    transactional_state.get_actual_state_changes_for_fee_charge(...)
```
... is an empty state change. Unrelated to the `commit`.

Maybe I'm misunderstanding what it is you're trying to test?

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/state/cached_state_test.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCGT0JBp1NPKYKHxOb:-NaCK23d0SDZEV4XF-D2:b-vfxfk1) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state_test.rs#L313)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because this
```
    let mut transactional_state = CachedState::create_transactional(&mut state);
    let state_changes1 = create_state_changes_for_test(&mut transactional_state);
    transactional_state.commit();

    // Make sure that null state changes are attained from a transactional state by
    // `get_actual_state_changes_for_fee_charge` after a commit and before any additional changes.
    let block_context = BlockContext::create_for_testing();
    let mut transactional_state = CachedState::create_transactional(&mut state);
```
first and last lines create `transactional_state`.
last line shadows first variable.

You are basically testing that this:
```
    let mut transactional_state = CachedState::create_transactional(&mut state);
    transactional_state.get_actual_state_changes_for_fee_charge(...)
```
... is an empty state change. Unrelated to the `commit`.

Maybe I'm misunderstanding what it is you're trying to test?
</blockquote></details>

ah, ok so: `transactional_state` is dead after the commit. can no longer use it.

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/790)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 571 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCFTgr7GRGQQgSb7Td:-NaCS7Kt5shh12gcYMri:b-xh4bp5) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state.rs#L571)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. It will save memory allocation (I think, not sure how smart rust compiler is to know by use case that the original object can be reused)
2. No reason to implement something very general if it won't be used
</blockquote></details>

How about now? Values will be moved instead of cloned
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCGT0JBp1NPKYKHxOb:-NaCSDPZDrsZy55eqiiU:b-9f7vmd) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state_test.rs#L313)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

ah, ok so: `transactional_state` is dead after the commit. can no longer use it.
</blockquote></details>

Tried to rephrase this part
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 327 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCGiVF5U2BassmW8qQ:-NaCSjyi3oGODI6Egmqj:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state_test.rs#L327)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

typo + only one plural `s`
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/790#-:-NaCV_UjBr2FG9GUmqBn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 327 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCGiVF5U2BassmW8qQ:-NaCVWlm8O06NPV-cfc4:by6hks) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state_test.rs#L327)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Done
</blockquote></details>

well, half :P

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/790)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 327 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/790#-NaCGiVF5U2BassmW8qQ:-NaCVftJ2WNlWCIy3lcq:b-s00g0a) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c236868c69ad75fb8b4b30c7523f04fc64ca6b6/crates/blockifier/src/state/cached_state_test.rs#L327)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

well, half :P
</blockquote></details>

oh, but that's actually the field's name though
`state_changes.storage_updates.keys()`

**Pull request merged**
