### PR TITLE
chore: add py-stateful-validator-error

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1732)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1732?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1732** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1732?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1731** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1731?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1730** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/1730?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1732)* status: all files reviewed, 1 unresolved discussion

**Review by dafnamatsry — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1732)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Apr 8, 3:03 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/1732).

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1732)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
