### PR TITLE
test: add invoke test to tx_executor

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1629)

### CODE REVIEW

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1629)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1629#-NshtuSP8onUXWferbnY:-NshtuSP8onUXWferbnZ:b-2d3iwz) ([raw file](https://github.com/starkware-libs/blockifier/blob/03321bf6ef5b5bd8794585a74362d7f5493fe09f/crates/blockifier/src/blockifier/transaction_executor_test.rs#L96)):*
> ```XML
>         ..Default::default()
>     }
> )]
> ```

Why did you choose those two entry points?



_Code quote:_
```XML
#[case::invoke_function(
    "assert_eq",
    vec![
        stark_felt!(3_u32), // x.
        stark_felt!(3_u32)  // y.
    ],
    BouncerInfo {
        state_diff_size: 2,
        message_segment_length: 0,
        n_events: 0,
        ..Default::default()
    }
)]
#[case::invoke_emit_event(
    "test_emit_events",
    vec![
        stark_felt!(1_u32), // events_number.
        stark_felt!(0_u32), // keys length.
        stark_felt!(0_u32)  // data length.
    ],
    BouncerInfo {
        state_diff_size: 2,
        message_segment_length: 0,
        n_events: 1,
        ..Default::default()
    }
)]
```
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1629#-Nshu-YfAkbLgA1l6htK:-Nshu-YfAkbLgA1l6htL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/03321bf6ef5b5bd8794585a74362d7f5493fe09f/crates/blockifier/src/blockifier/transaction_executor_test.rs#L103)):*
> ```XML
>     #[values(CairoVersion::Cairo0, CairoVersion::Cairo1)] cairo_version: CairoVersion,
>     #[case] selector_name: &str,
>     #[case] calldata: Vec<StarkFelt>,
> ```





_Suggestion:_
```XML
    #[case] entry_point_name: &str,
    #[case] entry_point_args: Vec<StarkFelt>,
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1629#-NshtuSP8onUXWferbnY:-NshvFYF9hRCpPXUlbxo:brevu1f) ([raw file](https://github.com/starkware-libs/blockifier/blob/03321bf6ef5b5bd8794585a74362d7f5493fe09f/crates/blockifier/src/blockifier/transaction_executor_test.rs#L96)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Why did you choose those two entry points?
</blockquote></details>

`assert_eq` - arbitrarily, I wanted something very simple.
`test_emit_events` - I chose the most straightforward entry point that has a code that uses `emit_event`.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1629)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1629#-Nshu-YfAkbLgA1l6htK:-NshvfTr8d73PYe4eaw5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/03321bf6ef5b5bd8794585a74362d7f5493fe09f/crates/blockifier/src/blockifier/transaction_executor_test.rs#L103)):*
> ```XML
>     #[values(CairoVersion::Cairo0, CairoVersion::Cairo1)] cairo_version: CairoVersion,
>     #[case] selector_name: &str,
>     #[case] calldata: Vec<StarkFelt>,
> ```

Done.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1629#-NshtuSP8onUXWferbnY:-NshwLGC8FA8I0z_s-um:b-xhzynk) ([raw file](https://github.com/starkware-libs/blockifier/blob/03321bf6ef5b5bd8794585a74362d7f5493fe09f/crates/blockifier/src/blockifier/transaction_executor_test.rs#L96)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

`assert_eq` - arbitrarily, I wanted something very simple.
`test_emit_events` - I chose the most straightforward entry point that has a code that uses `emit_event`.
</blockquote></details>

`test_emit_event` - the only* entry point that uses the `emit_event`.

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1629)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1629#-NshtuSP8onUXWferbnY:-NshyPPQ29jyAzb8ZIN3:bv33nzw) ([raw file](https://github.com/starkware-libs/blockifier/blob/03321bf6ef5b5bd8794585a74362d7f5493fe09f/crates/blockifier/src/blockifier/transaction_executor_test.rs#L96)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

`test_emit_event` - the only* entry point that uses the `emit_event`.
</blockquote></details>

Why specifically `emit_event` and not other syscalls?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1629)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1629#-NshtuSP8onUXWferbnY:-Nsi2PjmDZ_ZDVW2rhwG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/03321bf6ef5b5bd8794585a74362d7f5493fe09f/crates/blockifier/src/blockifier/transaction_executor_test.rs#L96)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Why specifically `emit_event` and not other syscalls?
</blockquote></details>

Done.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1629#-:-Nsi3JTODSu-GWAScV7q:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
