### PR TITLE
Support V3 DeployAccount in tests

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1195)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1195#-:-NkLghe7Dkaew8x6tOPx:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1195)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1195#-NkLfuxh1tyx4y9fr7k2:-NkLpUdd5O9PxqxWoZ_-:bc02ceg) ([raw file](https://github.com/starkware-libs/blockifier/blob/dcfd14ab17901667190732c210fdff001162ef56/crates/blockifier/src/transaction/account_transactions_test.rs#L73)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

:pinched_fingers: :kiss:
</blockquote></details>

![](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBYWFRgWFhYYGRgaHB4eHBwcHCEaIR0hISMcHCQcGiEjIS4lHiErIRweJzgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QHhISHjQsJCs2NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NP/AABEIAJABXQMBIgACEQEDEQH/xAAcAAACAwEBAQEAAAAAAAAAAAAEBQIDBgcBAAj/xABAEAACAQIEBAMECAQFAwUAAAABAhEAAwQSITEFBkFRImFxE4GRoQcyM0JScrHwFCPB0RUkYuHxRFOCFhc0krL/xAAaAQADAQEBAQAAAAAAAAAAAAAAAQIDBAUG/8QAJhEAAwACAgICAQQDAAAAAAAAAAECAxEhMQQSE0FRImFxgTIzof/aAAwDAQACEQMRAD8A6Exquam9UsdDFchsfNUWOk1NRrXty3mECf7UNgVW0ZgI61+eeZFy4q+pA0dh3r9K27eUkT1Gnl5/OsHx/wCjazdvPeV2BdsxQABfPXcTvNR8+PE/1MPRvo5vwtMowrqZJcz8K2nKWFDXGeA/s3Z/h38ppW/LN3DDDPdKqousI375SdeoFNuS7nhxH5yD6Eya3m4yNNPgIj9STNfjcC5bOEAUgGBttrHnVC2Tp4T8Ku4ZfNx1BbwgEjSKfLiVIJMaEhTG2mtbViSezTLh9WI0Sr0GtRbVie9WItYnMTWqsaPA4/0mrlFVY37N/wAppiHPB/sLf5RVmLGgqHCfsU/KKuvitPoAa0NaYBKDtDUeoplNGx6A71uleINMMbf3ApRdcmk2SwW+9AOaYutBOvaoYIxnMfMV23eW1bVdRJJnTz9KzeK50xK3PCyeHTaV07DSfU/KnHO2NS2zqyeO4sK0AwBEjy9xrJYXhpuW3dVZmB6QFUSBLn4xTWktsuZb6Nra59unDozojEmGyr4RroMpMkwCSQf93PDebcGyN7QoCACQEKss6R9YyQfeK59w7gWMjMltip+7vPnE17jeWsTZAuXk9mr+HNvE9SAZ670tz9Mt46XaN6OJNfIOGe2/dWlWy9Co2aBufjFZzi/Nt6w+QopPUEZSPmZB6HrS3hmKOHyPaYOJysjgEK+4Kk6r5EU3a/8AxNzJftK6FlV4MMhf6ro0lshI1Oo7xFC1shyxb/7g3f8Atp8a6Fy9xE37KXCIkdK5LzVwYYa+UXNkOq5txvKkjRu8jcEV1HkZP8rb9KvS+iXwaFDRVo61Uq1O2KozGNoTR9q3QGHfXWnFjamNHwt0P7FpProfeaMr6kVoXOj6Hz/f96EuI+m/7HX305utApbcczVImgF1f9x5f1mrbSEz6j9KtmaKsJ4WNBInv23PQ/Lt/ehmstOk06ZapCVDkpMFwmHI36Ab06wq6UOiQKKw21Up0GxRcNCu2h/fWp4l4maEV5+FcrOgJLxJA6TFWYDiSGROsDSh7ZBQGsfisQ+EutlIZCJyt29e9YZnU8o6cGObTX2dBfEhhIn0jWvJ0rI4LiRYpeOIREdgoUiR5ya1u0QZ8+9fP+ZFy3VPs2cqeEV3LGeFIUidQyhpHYTt60I3LeGjKLYQEhmKHLmjoSKPBPSo3rkAmCYGw3NZ+P5NRKS3vf54/ghzyB4bgKpn9k2UmILeKOmlVtp4Rsuk9SepNC8L5yw7ubZDqWOWcugO24210mjHwjqJglRsxOpGuvevqPFy28aV9/j8GOW60yCCr1FVIKsU1uchdFUYweB/yn9KvqnF/Uf8poAb8J+xT8ooi5Q/CvsU/KKvuVougILuPUUa21BKdR6ijH2NJlIVY00tZqKxpYbilpepbJZ670Mxq1zS7ieK9nbd4nIpMTE++pbEc85rvNicTbsBVzBo77nXzGgnWtTy7wa6jKqqotyJnWQB6a9K55hsWy3WuwCVAEgzqZ1nvXTOS+PXbji09shsmcSIlY0PoawzquF9HoeNqZb+zf4CwqbKBQXNuEW7h3UiYBIjeRtFZrD/AEjWluBLiFNQCZnL6iK0v+K2rqn2bq+kwDNTtKNB6177ZwHi1rI6uJGozjswP7NGWOMBFzffGUDuV2IPxnWivpCwOS/nA8LGSPOslevZo0AA9/xPWunF+qUznzL1po0/GMe+NsXHIBawwMgalGlQW7kaTXQuTB/lLX5a49g8Y9shlMA+Fh+IHQg+oNdj5RUDDIBsBArVI576NBNTtCq+lWWaZmMLQpthUgGlWG8htTqzMCaC0Tr6vq+oGD4gUI4onEtQxqkTXZDLRtgeA++hKNs/U+NDEgKvQtfAVYBQI8iiLY0qk1daGlAzJ8QuRJ8qCwt6a94nd0NLuHXdYrhb5OpDvB3MoMmRJ17Ht6VmvpCsD2dtgY8Rn09ac/4naTMjNEDMRG/p51guYuM37lxrbCbBXMiiJI7z3pcUtbNomoaegnA4nhy4YNee4zgzkUxB7Ada3nBOasJiQEsMSyqJXLEdOv8ASuAXspYiSB0nv51rOQOO2MG7e3WQ4EOBJUjdSO2u9Y+V4ieGmk29cITzOrW+jtwI0IkHrWW5gxmLtK7WbTsikszkgiN9BMmtHZvK6K6nwkBgfIjf51nuc+MXcPbQIyBbkq+zMBB1UeleF4Cqsymp4/4jTJpSY/lO0zPmJMli5PvJj510Vb7EQxYjtWR5StH2eciJOnmBWoQ96+mmVvZxumXirVqlHBMVeq1qQTWqsZ9R/wApq1arxf1G9DQwGvCvsU/KKvumqOFfYp+UVZiDWi6GRDVXh+Jzee0TqoVh75/tXxaslw/HZuIYiNgqD3iTHzpMNmxxsEUkupvR929pQLvUsQG9KOYdbLjYEAE9gTqfhTm4ay3OeMKYW4Ru0J/9jBPwqQS5FXK/BVOHUwM7EvJ10JhflW+5ewa20a5IZzoDuY/fSub/APqRLNpVXxMUiB0060s4XxJ1YAXnUhhlM6DzjqBrXJ626dM9T2n0UJm15m5TRrqXchyMfEU0MzPi8jtPlV+C5avo4ZGASZEyGUdtta1HDMT4AM63VInMugJ66etW3ceRtUU1rTZUut8JfyYb6RcBOGZiRKkGe9citiSBBM9Bv7q6r9I3Eh7MW1PiYyw8ta5aVKtGoPnp6GuvxeI0cnlb9tltu0QWBBEawfUxXZuUnnDWj3BPxM1yH2kWiGWZnxE/Kuv8pA/wtn8g/rXSuzivofKNKKw1mTVFrajcMaozQ3wVkAVPHYxbahm6sFHqTFUWb0VmOfOIZUtawPapJ7QwM0mXLNvVF/EBSgP3jHymo2cWhUEMDp3pPxrHL7ayikE5sx66QRr8aNDdD25BFBMoqYuEiolqZL5IZdaIV/BVE1InSmIitTFQBqQNAHtX2zoKHY0VbOgpDRzTH3ZJk6ULgbkNFV8TuZQx3PQVRhjAk9p9a87Z2aGfGsEHtl1jOqmPPyNcpx/FXZhBjIuQR8/fW25q497HDhE0uXNJ3heprmFb4saf6hVmrSnfQx/hi6SokySY1MUXwLly7iXQCEV2yq7bSNf70FwnFG2+dWykA+cg9Io/Bcz3bauo2eZHY/iHY+lav2XCM3SfJ03iXtnKcPR4QIFe8uxCqPgdIoQ/Rzkbw4licpBLa79p2pfy1zmmSLlogrBDA6vqAfnrXRHuNdw5uIIYkHX8P/Fedqse5la+ynXsLLHDfZIAg20j06+lXWV11ptw3CkjxN4tjWd4xzLhrF/2LsVcRmkaCdjPmK2w1TS2Q0NVohKrtJmAYGQdQe4qwArvXSSTQ1Xi/qN+U/pVoFV4r6jehpMY04X9kn5RVmI6VXwv7JPyirMR099aLoAdqSWcOiO7BQCx1PWnZoVuHncMNaGiQR7lDl6Ytw0n7wqo8Ib8a1OmAqd6xH0k3SMOi9GcfIE10ZuDt+Jay3PnLbvhHeQTb8YgamNx8CaSTTGmcm4W6Z/5gzD1ge+tJgsNhrqmEdG6FW0HuNY5WgzVqYt1+qY6aUXjb5TOnFmUrTRqOXuY3wzspJKayJ7dfKnuK59BBAHTSuam4ZnrUZqK8aae2UvKaWkOMdxc3Lgduhn5z+/WhOJ4r211nJ+sdyI09OkVQLRC5jtMCr8Dg2YqYkFsvfy271rMqejG7qv8v5CeJjKqoSDAkFGlT6jodK63yr/8W1+QUtwf0fW3tiTmUiRBIn56VrcBwVraKijRRA1qpMKZZbbSi8O9Qt8OeelX2eHuO3xrQyLg5pfxTBJdUBwCAdKZDCP5fGvGwT/s0+A5Ei8GTu3pmNEYXhyI+dRr3OtMxgn7fOpDBt2+dHA+S1Hqc1BMOw6fOpi03akM8zV8TXwst2r51I3oA8r2aga9FAEyaKs/VFB0WmwoBHHsR4rjg9E0+dQsKQigbwPOiMcwV3/Karwmqp6CvMR2ow3GeF4h77gK76+E7iPLtQj8u4kKXNl8o1J/rXaMAkCjlGkGumcjSM3J+dAa+rt+J5PwzM7C2Azfr5VybmLhDYa+9sg5QSVPcfvStZtUS0H8rYnDjMuIcqQISRK67z2rT8r813bTHDWh7RWOjTOUT0npXM62XA+G2zhTdLG26ySxnWDsKzywtN/kEdcPGYKFAAxBzK+hBEVj+beL4IsblxVe8ylcwAMR0rOcX5hNxLaWXzXGBDEjbyBpfguSsVdXOSB2zTJrHFiae29fsDZ0jkjmZbii0ykMuixJEbiT00rWX11NYrlfh97CoEyK5JksdOu3zitgLhbU7mt11okmKqxP1W9DVgNVYn6jehoAacLP8lPyip4k7e/+lVcKP8lPyirMT0q10Ng7tSK9iGk+I796duaz1/c1NMlHhxD/AIj8aqbFP0ZviaIw+Bd/qrp3OgplY4Cv32zeQ0FTpjM+2IuN4VLljsBNZu9w7E2s74rFOqFvs1bNp/rJ0GnQV0+5aCKQgCjy0+e9c85ltl1ZTO/vpvaRUrdLZyviSoLjeznIScoO4HuoWKbY/AwxIqizhS2kVSyLRr8NN8AOU0bw/hzXGAA0mnGD4A79Ce0VsuEcECLGUk/pXNl8pJans6sPhNvddGW43wrLaRVEayPPvTXlLlJ7trPh7yLeRpKusjeAVO6mjuYGlgvRREem/wA//wA1o/oywzA3H2XRR86nx8tNqWV5WCVLsxfHsdxjA/bHKvRlhkM6xI60mXn/ABwGl35V+jXthlKsAVO4IkH1Fc+5g+ibD3mZ8O5sMfuxmSf1Gtdx5fAJydxzEXbAd3LMetaJcfc/GaUcJ5ZvYK0EeGAMZk1B16/ho5OlNGddjFMc/wCI1emMc/eNAJuKvRvhFUiQsYp/xGprin/EaFBqxTTFsK/i3716MU/ehqnNAbCP4l/xVNbhIkmaDzVfaOlJjTLpr0VGakKRR6aLTYUGxoxBoKaGcg4oP5jT2P619YIzIBtFW8x28j6dRvS7AXPGgrz9HSmbTCDQUYtA4Y6CjUbSmB6a4/8ASFjle/kAM2yQT3mK667Vx/n61/mmIGygmO3etMf+RNdGXSJ1rqfJ2IS9YNvKIUEEEd65daSTPbeuh/R0IF0eYPx/2rWyTV4LgGHSMtpARsYnendoRpQ6USlZoRaoq1KrFSQ1QFqVXivqN6GrFaq8UfA3oaAGPCvsk/KKljGgAxt0qHCfsU/KKsxew9atdDYEXB0g0LgcKC5Zu+g7+dGsdKHvvCMRoQpI9RrQxIPIiBXoaoZwyqw2Kg/HWvgaCkiN2TSXH8PVtY1/WnjVQ9uhoZirvA7LkkrEHtrU7XLlkHRZ9a0WIspmEkAtovSesDvoK9GGYfhPyrnvCqOjF5DgT4HAZSIWAKY4xwiSIzHQev8Atv7qMt2G6wPnSrjHibKNQogfKf0j41heGcUt/Z0RnrNSX0ZPFYcsxA6n4mui8LtjDYZJUwIzZRJEnePfSDg3DWdxrAGpMTFbhRprV+JDS9mT52XeoX0e2LocAjb0I+IO1Wg15XhruPNLC/el3EOFpclkhX79D6/3qN6wA+fM/pmMaTuOv+1ffxEUbE1szouMrtbdSrr0OxHdT1HpRFtqfuEurlca9G6j0NJsVg2tnXVejDb39qpMip0fKf8AerQ1DBoqaPVbJLg1SzVQXFe56ALs1FWNqX+0o7DHSkwRep/fxqVRqQpFHp2NHJsKBajhsPSgaOXc029j5VnuGv419f6VqOYhKj0rH4a7lcetcdLk2Rt7bRRmHu71m7vE0SczCKXtzXDeAT60aZWzcNXK+akZr2JZQSEVFY7xJMU3fmi9+JR7qzWG4pfuYp0TKf4l1RlOitrCz6TVwnsTYktiFc+UR6mtv9G9yWu+i0q5m5du4YXXfLGcIQPjI8qo5O4x/Dl/DOaOsVpXK2SdettRFs1lsJzShAlSKb4bjlltM0etZoB0pr0CqLOIRvqsD6GrHdVGZiFA3J0A9aYi8Gq8SfAfSh/8Rtf9xPiKjfx1oo0XEMCTqNBtPxMUAPeE/Yp6VZiulD8Dvo9lCjBgBBgzB7GvXxtt9EdGI1hSD79OlaLooCvv447CT+lDY64MhPu+Ph/rULuKRGcsyrOgkxPU0s43xJUtK+650zRrpO47jUVLYaNVYPgUdlA+AqYNZ7/GEcBUYGACdauHFkUhWdQTEAmPfVbGOLlyB3PQTE+QnyqLXgEzsMoiSGgR5HoKQ3eMYZL7JcIV8wEtqp00IOy7x0Olecex4S2Sl4OXbQEqQFggyNyvr1ijYmzMcZuXLznMWU5swT8DRlkdp/qa2fAsSxRFuuheAABvoswehbQmsKt8CPMDLBzE6b+dHYTGuJCQjdXZsjKNJADem4BoJ2bzHXwiFuuw9azZO/n1PeDXvFeJkogdkMABiPqltNj57D0NCBwQArgAnUg7AET6E6D3mvOz5Pav2R6uDH6z+7NnwTC5EB6tqfTsf31piTWNu8cJGT22QjsRI7AnWvrPGso1vz5lhW0+TMpJJmFeNVPbaNdZxObMArAqYMj36d9KsJrM2+YgpyswYjfuPhTizxK06F1dcqiWMjw/m7V0Y8qvo5suFx2e4+5EDvS57kmq8fxFHIyOrQNYM0sucTRTBdZ2gnvtVtmWh9Yc0zs3ZEESO1ZFeKgGC0e+iU4ih+tegdgYoVaByaVuH2zsoHlQ5w9oEgjWhsNj10ykwBvXj41HHijyPb1pVmmdbY5w1SblBItWu1fC1a/ZrNYnjhRyjJ4h+waEucdE7RV+6M/Rmw9la/ZqRVQPDtWHfi5OoECtZwu4Wtqe4mmqTE50GipLUFNWCmI+NHUD0o6mCOS8wcURF8TDbaua4rizMxyaa71bxC8G1ZiT60pQifhWEyuzYYi47kljJ7mi7KxQ1p1Eaj40QMQn4h8aTGWvMVdwRcMpN5rk30MojaAMNVaesECgrmKT8Y/WkjN4p85pyhM2OB5lcvc/jGW8jyGU/dMaFYpHdW0r/wAhmZT0PTypbfvZiY6mf9qjZu5elXrgDRWLh/ZohbsaVnzxNohQB86qbHufvEemlR6sDY4fii2yCGYN0APXtHWulYRDesJnJVmCnYSCIYb6HUVyb6PcMbmMVmXOFBYkiQD69DXaV/4pNaYH1nG3VXE5nDm3YLoWRBlbx/hUAjQaGgcZadgjvcLkNbUeBFADXLZP1VE/VG9Tv4hEGKDsqlsMQoZgCT49BO51Fe45wLakkAB7RJOgAzpqT0FVsQ4Ae3cvAWHYO+ZWQLBGRR1YdQaXNhyjYZGXKww7Bh5gpoYom3Zs3nxFw5XAeAwaRARdAQY3pRiOIoEw7K6sy4cg+IGGLW1GYzpr3pjJW8W1pWxCqru9z2dtW18CHNcYeZykDzApJzlhVVLyDVMovWz/AKD4mA8gZ07RWgxty3CIltLqWFCh/aMsswBaMgIPSTO5pZxrFW7mERlVEewxt+zzySjgKMuaCw1U+40MAjBpYbAYCyxyvcT+Tdj6rACA3kwMe/vFB8ODJh+Ii6oD20QMOxGc6HsRrPnS3iGJQYLhtvMrMqOrKGEqQq7jddqdYbjNu9gcSrsq4gIEZiQGuKJyNr9Y6kHzFHGwJcGL4rDYkois7XbJXYAgZDm18gTQHMePFlXw1tlZ/wDqLjQjOQPqII0QSNt9upNe2L62cDikt3hnz2ckOubdB4YI89BUuJAYm17R8lvGWRKs5RVxCAb6NBbU9dCOxoEe8nBmwt8YbKuMzCM0ZsgiAmYQNM3SJpXj3xN66lrFs4KyYdFUxpMMoAbYDQ/eoHA8LvYxBdS9bDq0APcNq5AA8QMajsa0vGL5XC2LF28l7ErczZlbOVQTozd4IHn7qjI9S3+xphn2tLX2fWoN2wI/6i0PdnX9/wDNU8VugYzErG9zvA0RN9PP50Lg70XcOxIA9taLEmAq5lk/ER6A03xCq+IxBUq6tc3EMD4U69dvlXn1/p/s9SeM/wDQPhMddsiEfwlwSpVGEsVB1KzEedNeP4q6b160LgS3CrlCp95QTqVJkyetJsRbABYaKjKDIyxDLrrpH9qZcXxSG/iGDqyEoAQQyzkURpIn+tVFX8T5+yckR8y47WydrEXLWCDWswY4h1Yqoc5Zbup7DWKt8T4dHxCgXGuhFJUI1y2xhg6wNMuY7fdBoC1xEjBqlu6UuNiHBCsA4XxHVTrGg6VLimJRls4q+0XrBy3beYLnXo6KT10OnQsOldMPWuedLg48i3vjjb5L8TZe7bHs0D4jDwhWcpuI2ivPcHUnurd6U8fxGHTJgWvZPZQ7uBo91pkMegWdvMdqv5d44tzHK7MltMjrBIUEaMAxOhM1g3KXc+cMZZyWneWPinzrV1xs50uQnihuWBmYi5aOzqZj1jUCqeFcZDPoMx6QCflFCcN5XxLsyozhDPUiR2jauicA5cTDpEDNpJ7mubLnmOuWdWPA65rhF2BdmWbltxbOjPnCvuPEF/CO29M+M8JWxaLBiVEb7npQeLuaEaj39a0HMOOtWsKDfDFWCrC7kkfvWohrNDb7RpW8FLXT+jO4G7buoC4EroCdyN4q44bDdcvxrIYu8TqiuLUyAx8UdietK+JPJ0tuo99aYaanTOfyFLtuToAt4b8SfGnuEvIyAIQQNNK4WvD3utoWUepiup8h2cmHyydCdTud+9dMM5qk1K1MVWDUhWpBYKNoE/1o2mNH5Fiva+r6kaHlfV7X1AH1fUx5fw6PiLaOMyltR38qK5uwiWsSyIoVYBgUt86ASV6EMExoNz2ryjcKf5N4fk/U0MAKt7yhyZav2lvXWY5phRoNNNTWCrsvIA/yVv8A8v1pU9IDQcNwFuyuS2iovl19aPWqVq1TWQj1rYO4B9QDVWIWUbtVwNQv/VNAy3DlUwoYkIiAs52AA3OlC2L1srnTJcRvvKAQR/Wg+J4jNh7dhTrc1ePwDp7z8gaWW8MLf1CyH/TpPTxDZvfWN+TM166OvF4lXPtschlIZV0B1GXTy271m+Im2qsuIORDsxYBgRqGU7g19isUwkss6/WQ5THpP6H3Vj+M4m3dYhmLR+IARHQVtFzS2jC8dQ9NC/HYdxdDozXSzEhiILLEgQOsZj7qdcPX2hXMIBP/ADQONxqezC29HR0cHqI7e6nyXEvW0vp4XVv5ijQZoM+7rNNvZGhhibFhPYqrouTQIFDN2lj0B211nahcFi8O5IuYZjO7qxJBBiVBPh36Hp1pZwvBG42cSzfeYmFjaT+IiB33ERvW04XhVV5iQsFswBnMND+p00070xAPH7iezRQ7FFQAIySXjTxufugdB1NIsOfKATJgDQbzV3NXEQ94qplEMCDInqR++lS4LhWc5lOULDEmI0Mqs98wk+QHeuPKnkv1PUwOcWF0+zX8M4cUSHXxNqw3joE/8Rp8aOt4cAaADy2oLAcUDmHaGUToNHHpqcwPQb9Kc+zmBrHlpH9RR8PJn8+0CNaOwQtI7iPTWo2rOhCpB/CQB+x50zW3UH3ypv1bt5DzrT4kkQ8rYpxLrbfwWle+RHQ5Z/G0aD5mqP8ABswe5eYO7IQXK/VH+gdANfWm9qwq+FQD1Yndj1k9Z719xJ8lvvmKg+h2HypNeqdCVez9fyY/C8tKXnOrL1GQ/wB/3FPMPy9bGpXMRsT/AEq62zBZRVB86sfHZV8REjeNK5HkquzoWGZ6RJ3VF2GlI8dxmCYMx2qHEL73T4Edh3jT47V7gOVLl3VyEHaJb+1TOKretGvyRC23yL8HcfE4hLaEmWBbXRVBBJPu/WtT9Id0RatHVdXI9PCP1p3wLl21hhKrLkQztEkbxPasv9KLFPY3ehlD82H6GvQx4fSGvyednzfJaa+hTYxS3AFkADpMUTicUMypoQdKw1vC55YMwnsavwHD3ZtbzgAfi2+Io9THZp8Wtq1Ok9d603K+KS5azIIEn9TXI+LFUJVrjs3SDNdD+i5pwczPjbX/AMjWsLkmujaCpCoipVqZk0O3rRtBJuPWiyaYH//Z)

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1195)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1195#-NkOo47_8MwJT7aQ87ml:-NkOo47a3FUuraLrTlAy:bh32ml0) ([raw file](https://github.com/starkware-libs/blockifier/blob/a4da116d46b3c43eed079f6f85dbb3c20ed02841/crates/blockifier/src/transaction/account_transactions_test.rs#L71)):*
> ```XML
>             class_hash: class_hash!(TEST_ACCOUNT_CONTRACT_CLASS_HASH),
>             max_fee: Fee(u128::from(!zero_bounds)),
>             resource_bounds: l1_resource_bounds(u64::from(!zero_bounds), DEFAULT_STRK_L1_GAS_PRICE),
> ```

Q - don't we check  (in execution) that `max_amount >= MIN_AMOUNT`? 
As we did in python.



_Code quote:_
```XML
u64::from(!zero_bounds)
```

**Review by MohammadNassar1 — DISMISSED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1195)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1195#-NkPKqhnDTpOggW1tLFd:-NkPKqhnDTpOggW1tLFe:b-f48jrg) ([raw file](https://github.com/starkware-libs/blockifier/blob/8dce6940966cd80c0fa5bfdae7736d162e0a7cf9/crates/blockifier/src/test_utils/deploy_account.rs#L85)):*
> ```XML
>                 fee_data_availability_mode: deploy_tx_args.fee_data_availability_mode,
>                 paymaster_data: deploy_tx_args.paymaster_data,
>             })
> ```

(Non-blocking)
Please arrange the arguments like in the DeployAccountArg struct.



_Code quote:_
```XML
            starknet_api::transaction::DeployAccountTransaction::V3(DeployAccountTransactionV3 {
                resource_bounds: deploy_tx_args.resource_bounds,
                signature: deploy_tx_args.signature,
                class_hash: deploy_tx_args.class_hash,
                contract_address_salt: deploy_tx_args.contract_address_salt,
                constructor_calldata: deploy_tx_args.constructor_calldata,
                nonce: nonce_manager.next(contract_address),
                tip: deploy_tx_args.tip,
                nonce_data_availability_mode: deploy_tx_args.nonce_data_availability_mode,
                fee_data_availability_mode: deploy_tx_args.fee_data_availability_mode,
                paymaster_data: deploy_tx_args.paymaster_data,
            })
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1195)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
