### PR TITLE
Make get_fee_token_balance consider transaction version

### PR DESCRIPTION
**Pull request by giladchase**
- Store fee token addresses in a dedicated struct `FeeTokenAddresses`.
- Add `HasTransactionVersion` to represent objects that store
  `TransactionVersion` (or store fields that store `TransactionVersion`,
  and so on). Ideally, we should have a `Versioned` trait in SN API for
  this kind of thing, which will be more generic, rather than
  specifically a TransactionVersion.
- Changes in tests currently just preserve the current state, once we
  add support for the new transactions we'll update the tests to not
  hard-code deprecated transactions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/889)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/889)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @giladchase)

___
*[`crates/blockifier/src/block_context.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_9MMX5uEC4H249okK:-Nd_9MMX5uEC4H249okL:b-xv26el) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/blockifier/src/block_context.rs#L40)):*
> ```XML
> pub struct FeeTokenAddresses {
>     pub fee_token_address: ContractAddress,
>     pub deprecated_fee_token_address: ContractAddress,
> ```

no need to perpetuate wrong names IMO (working on renaming...)
call these `[strk|eth]_fee_token_address`.
I'm planning on renaming anyway, if you want to add it to your plate of tasks be my guest ([WIP](https://reviewable.io/reviews/starkware-libs/blockifier/888))



_Code quote:_
```XML
    pub fee_token_address: ContractAddress,
    pub deprecated_fee_token_address: ContractAddress,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 372 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_A2kcCUenhrH8UKGk:-Nd_A2kcCUenhrH8UKGl:b-kopdoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/blockifier/src/transaction/account_transactions_test.rs#L372)):*
> ```XML
>     let deployed_account_address =
>         ContractAddress::try_from(stark_felt!(TEST_FAULTY_ACCOUNT_CONTRACT_ADDRESS)).unwrap();
>     let tx_version = TransactionVersion(stark_felt!(1_u8));
> ```

should this be hard-coded...? non blocking
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 410 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_A7yz2waju38BJe_1:-Nd_A7z-5BL5DsSkHFGb:by86o53) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/blockifier/src/transaction/account_transactions_test.rs#L410)):*
> ```XML
>         init_data;
>     let class_hash = class_hash!(0xdeadeadeaf72_u128);
>     let tx_version = TransactionVersion(stark_felt!(1_u8));
> ```

ditto on the hard-coding
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 439 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_AKm_3BKzdus30CHc:-Nd_AKm_3BKzdus30CHd:blsagh2) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/blockifier/src/transaction/transactions_test.rs#L439)):*
> ```XML
>         .get_fee_token_balance(
>             &contract_address!(recipient),
>             &block_context.fee_token_address(&TransactionVersion(stark_felt!(1_u8))),
> ```

ditto on hard-coding
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_AaUJ9kubVe7gHuW9:-Nd_AaUJ9kubVe7gHuWA:b-lwl3zy) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/native_blockifier/bench/blockifier_bench.rs#L98)):*
> ```XML
>     ];
> 
>     let tx = invoke_tx(execute_calldata, sender_account_address, Fee(MAX_FEE), None);
> ```

I don't really like this... tx version is hard coded in `invoke_tx` function, the correct fee token address should be computed within that context.
Maybe add a TODO above the line with `let contract_address = ...` to fix this double-point-of-truth?



_Code quote:_
```XML
    let contract_address = *block_context.fee_token_addresses.deprecated_fee_token_address.0.key();
    let execute_calldata = calldata![
        contract_address,                   // Contract address.
        entry_point_selector.0,             // EP selector.
        stark_felt!(3_u8),                  // Calldata length.
        *recipient_account_address.0.key(), // Calldata: recipient.
        stark_felt!(1_u8),                  // Calldata: lsb amount.
        stark_felt!(0_u8)                   // Calldata: msb amount.
    ];

    let tx = invoke_tx(execute_calldata, sender_account_address, Fee(MAX_FEE), None);
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/889)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/block_context.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_9MMX5uEC4H249okK:-Nd_D0sp70e8-lphCJVF:bysstbe) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/blockifier/src/block_context.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need to perpetuate wrong names IMO (working on renaming...)
call these `[strk|eth]_fee_token_address`.
I'm planning on renaming anyway, if you want to add it to your plate of tasks be my guest ([WIP](https://reviewable.io/reviews/starkware-libs/blockifier/888))
</blockquote></details>

:laughing: 
I'm cool with renaming them here if you're really OK with it :)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/889)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @giladchase)

___
*[`crates/blockifier/src/block_context.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_9MMX5uEC4H249okK:-Nd_FsN-3qOI650LHXYk:bb6w73c) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/blockifier/src/block_context.rs#L40)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

:laughing: 
I'm cool with renaming them here if you're really OK with it :)
</blockquote></details>

I am

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/889)* status: 2 of 12 files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/block_context.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_9MMX5uEC4H249okK:-Nd_H4Fr4IXBscJNJT2k:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/blockifier/src/block_context.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I am
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 372 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_A2kcCUenhrH8UKGk:-Nd_DoUw8fS5vLUqexil:b-e36bcn) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/blockifier/src/transaction/account_transactions_test.rs#L372)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should this be hard-coded...? non blocking
</blockquote></details>

Ya hated writing that, i did it because the test is already hard-coding this version when creating `deploy_account_tx` (the constructor has V1 hard-coded), and fixing it felt off-scope for this task.

Therefore, if I'm not going to make the entire test support V3, I might as well keep consistency with the rest of it, until we get to fixing it end-to-end.

That being said, if you don't want to add more hard-coding I'll fix it here in an additional commit.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 410 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_A7yz2waju38BJe_1:-Nd_FPKw9EHsaTo2Sdc3:b-h0o8bh) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/blockifier/src/transaction/account_transactions_test.rs#L410)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto on the hard-coding
</blockquote></details>

Same answer as above (i fixed the hard-code in the meantime, it didn't match the tx version).
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/889#-Nd_AaUJ9kubVe7gHuW9:-Nd_Fic97mNNGi5f_MCv:byi5hih) ([raw file](https://github.com/starkware-libs/blockifier/blob/eed41806f585826e374fd1630178f5f8841c66a2/crates/native_blockifier/bench/blockifier_bench.rs#L98)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't really like this... tx version is hard coded in `invoke_tx` function, the correct fee token address should be computed within that context.
Maybe add a TODO above the line with `let contract_address = ...` to fix this double-point-of-truth?
</blockquote></details>

Yep i agree like before, added the TODO.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/889#-:-Nd_ZU8R7vCWe5zryZ9l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
