### PR TITLE
chore: move max_capacity selection to BouncerConfig

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1941)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1941)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1941#-NzSb2BE2gfggtcu6Cl4:-NzSb2BF5yWJYJakmQZN:b-r2tedk) ([raw file](https://github.com/starkware-libs/blockifier/blob/88838be95ac3640fcd50bf254c42f5762c6729ba/crates/blockifier/src/bouncer.rs#L54)):*
> ```XML
> 
>     pub fn has_room(&self, weights: BouncerWeights) -> bool {
>         let max_capacity = if weights.builtin_count.keccak > 0 {
> ```

why did you change the condition 
self.accumulated_weights.builtin_count.keccak > 0 || tx_weights.builtin_count.keccak > 0 ?

what if there was already keccak usage in previous transactions in the block?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1941)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1941#-NzSb2BE2gfggtcu6Cl4:-NzSqWKt3_QBylmip1up:b4a6sc1) ([raw file](https://github.com/starkware-libs/blockifier/blob/88838be95ac3640fcd50bf254c42f5762c6729ba/crates/blockifier/src/bouncer.rs#L54)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why did you change the condition 
self.accumulated_weights.builtin_count.keccak > 0 || tx_weights.builtin_count.keccak > 0 ?

what if there was already keccak usage in previous transactions in the block?
</blockquote></details>

That's okay - if the tx does not contain keccak, we can close the block without it and add it to the next block

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1941)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @noaov1)

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1941#-:-NzT73hk2zO6eiuLNFWR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
