### PR TITLE
refactor: modified estimate_minimal_gas_vector for 4844

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1401)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1401)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @ArniStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1401#-NpPRtprByJfmbTmxjNd:-NpPRtprByJfmbTmxjNe:b-53w1bh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b9b7774620629f89a495cbffa7ac1420c0ccad4/crates/blockifier/src/fee/gas_usage.rs#L245)):*
> ```XML
>         true => (0, calculate_tx_blob_gas_usage(state_changes_by_account_transaction, use_kzg_da)),
>         false => (get_onchain_data_cost(state_changes_by_account_transaction), 0),
>     };
> ```

I don't like how we have two separate function `calculate_tx_blob_gas_usage` and `get_onchain_data_cost`.
We should have one unified function `get_da_gas_cost(state_changes_count, use_kzg_da) -> GasVector`, which consturcts a GasVector that has one field zero, and the other non-zero (or zero if state changes are zero).
Please add a TODO to implement such a function, and delete `calculate_tx_blob_gas_usage` and `get_onchain_data_cost` functions



_Code quote:_
```XML
    let use_kzg_da = block_context.block_info.use_kzg_da;
    let (gas_cost, blob_gas_cost): (usize, usize) = match use_kzg_da {
        true => (0, calculate_tx_blob_gas_usage(state_changes_by_account_transaction, use_kzg_da)),
        false => (get_onchain_data_cost(state_changes_by_account_transaction), 0),
    };
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1401#-NpPSKkZ4JvDrBVyVHh8:-NpPSKkZ4JvDrBVyVHh9:btatbw5) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b9b7774620629f89a495cbffa7ac1420c0ccad4/crates/blockifier/src/transaction/account_transaction.rs#L182)):*
> ```XML
>         // TODO(Aner, 21/01/24) modify for 4844 (blob_gas).
>         let minimal_l1_gas_amount_vector = estimate_minimal_gas_vector(block_context, self)?;
>         let minimal_l1_gas_amount = minimal_l1_gas_amount_vector.l1_gas;
> ```

blocking here at this time until the gas-flattening logic is added



_Code quote:_
```XML
let minimal_l1_gas_amount = minimal_l1_gas_amount_vector.l1_gas;
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1401)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1401#-NpPRtprByJfmbTmxjNd:-NpPcjg75so62oH1Z6Qb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b9b7774620629f89a495cbffa7ac1420c0ccad4/crates/blockifier/src/fee/gas_usage.rs#L245)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't like how we have two separate function `calculate_tx_blob_gas_usage` and `get_onchain_data_cost`.
We should have one unified function `get_da_gas_cost(state_changes_count, use_kzg_da) -> GasVector`, which consturcts a GasVector that has one field zero, and the other non-zero (or zero if state changes are zero).
Please add a TODO to implement such a function, and delete `calculate_tx_blob_gas_usage` and `get_onchain_data_cost` functions
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1401#-NpPSKkZ4JvDrBVyVHh8:-NpP_XKK8vcMplRSDnfn:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b9b7774620629f89a495cbffa7ac1420c0ccad4/crates/blockifier/src/transaction/account_transaction.rs#L182)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

blocking here at this time until the gas-flattening logic is added
</blockquote></details>

Done.

**Review by dorimedini-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1401#-:-NpPfxBb90bSH0ZU5Ejm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware and @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1401#-:-NpPpUDR2Wp5Qnz5YdaW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware and @Yoni-Starkware)

**Pull request merged**
