### PR TITLE
Use BlockNumber in GetBlockHashRequest.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/604)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 304 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/604#-NYYUEMbEbZRbWbc0gLD:-NYYUEMbEbZRbWbc0gLE:b-5u2ypj) ([raw file](https://github.com/starkware-libs/blockifier/blob/8238804c86d46b2d58748c94d00b4a3d40897368/crates/blockifier/src/execution/syscalls/mod.rs#L304)):*
> ```XML
>         let block_number_as_felt = stark_felt_from_ptr(vm, ptr)?;
>         let block_number =
>             BlockNumber(u64::try_from(usize::try_from(block_number_as_felt)?).map_err(|_| {
> ```

There is a correctness issue here.
Can be solved if the following PR is merged into `starknet-api`: https://reviewable.io/reviews/starkware-libs/starknet-api/87



_Code quote:_
```XML
u64::try_from(usize::try_from(block_number_as_felt)?
```

**Review by dafnamatsry — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/604#-:-NYqxq9TCy3r2Wcu4OvT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 304 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/604#-NYYUEMbEbZRbWbc0gLD:-NYrdWsWBa6rp9mLc-K6:bcbceva) ([raw file](https://github.com/starkware-libs/blockifier/blob/8238804c86d46b2d58748c94d00b4a3d40897368/crates/blockifier/src/execution/syscalls/mod.rs#L304)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

There is a correctness issue here.
Can be solved if the following PR is merged into `starknet-api`: https://reviewable.io/reviews/starkware-libs/starknet-api/87
</blockquote></details>

Talked with @Yoni-Starkware . Let us merge this PR for now. 
The only harm that this correctness issue would do is:
1. Some valid requests will not be processed.
2. The requests that will not be processed are for `block_number >= 2^32`. This will not be an issue in the following week.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 306 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/604#-NYsJe8jDDMtJO46RyMT:-NYsMpf3AwjcAYnWwo7X:b167yg5) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f96a6887efc1253c458e8e964ff2ea827cb0842/crates/blockifier/src/execution/syscalls/mod.rs#L306)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Looks great!
See the solution in the following PR:

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/604)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/604#-:-NYvSobI7Vik9EocHkRB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 306 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/604#-NYsJe8jDDMtJO46RyMT:-NYv_0zG7a2IASRA2QHp:b-43s6yh) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f96a6887efc1253c458e8e964ff2ea827cb0842/crates/blockifier/src/execution/syscalls/mod.rs#L306)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Looks great!
See the solution in the following PR:
</blockquote></details>

See #668.

**Pull request merged**
