### PR TITLE
Create a Python tx executor class with a saved state and block context.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlj7jd7iSxLBo5-eSc:-NNlj7jd7iSxLBo5-eSd:bdhls29) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L148)):*
> ```XML
> #[pyclass]
> pub struct PyTransactionExecutor {
>     pub state: CachedState<DictStateReader>,
> ```

Planning to change that? Perhaps it should be templated by `S: State`?



_Code quote:_
```XML
CachedState<DictStateReader>
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlmdqj9z8_n_lkUGCc:-NNlmdqj9z8_n_lkUGCd:b-tutb1q) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L162)):*
> ```XML
>         let starknet_os_config = general_config.getattr("starknet_os_config")?;
>         let chain_id =
>             starknet_os_config.getattr("starknet_os_config")?.getattr("name")?.extract()?;
> ```

Also, I don't think `chain_id` variable is needed; it's pretty clear.



_Suggestion:_
```XML
"chain_id"
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNllAnFAJ_27VePHx0j:-NNllAnFAJ_27VePHx0k:bfhxbph) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L165)):*
> ```XML
>         let block_context = BlockContext {
>             chain_id: ChainId(chain_id),
>             block_number: BlockNumber(block_info.getattr("block_number")?.extract()?),
> ```

I think this should also be a small utility; it's very short, but repeats a lot.
Reading an address as well.



_Code quote:_
```XML
block_info.getattr("block_number")?.extract()?
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlmrrM5vqw8s5GNzR4:-NNlmrrM5vqw8s5GNzR5:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L181)):*
> ```XML
>             validate_max_n_steps: general_config.getattr("validate_max_n_steps")?.extract()?,
>         };
>         Ok(Self { state, block_context })
> ```

Add a blank line above.



_Code quote:_
```XML
Ok(Self { state, block_context })
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlmztYA4DCfVKfgTl-:-NNlmztYA4DCfVKfgTl0:bez3bek) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L184)):*
> ```XML
>     }
> 
>     pub fn execute(&mut self, tx: &PyAny) -> PyResult<()> {
> ```

Are you planning to return the execution results?



_Code quote:_
```XML
PyResult<()
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlvmQJChE4iLeJGn88:-NNlvmQJChE4iLeJGn89:bj2756) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L152)):*
> ```XML
> }
> 
> #[allow(clippy::new_without_default)]
> ```

I think this one's only necessary if `new` takes no args.



_Code quote:_
```XML
#[allow(clippy::new_without_default)
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlw4J09Suy_jqrWXBV:-NNlw4J09Suy_jqrWXBW:bfb5crg) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L185)):*
> ```XML
> 
>     pub fn execute(&mut self, tx: &PyAny) -> PyResult<()> {
>         let tx_type: &str = tx.getattr("tx_type")?.getattr("name")?.extract()?;
> ```

This pattern also appeared in a previous PR, we should extract the logic into one place.

IMO this logic should be`tx.tx_type`, where `tx` is some Rust struct cast from the PyAny `tx`.



_Code quote:_
```XML
 tx.getattr("tx_type")?.getattr("name")?.extract()?;
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlj7jd7iSxLBo5-eSc:-NNpLzZg4q_93dfBJ_EK:b-fgojf) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L148)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Planning to change that? Perhaps it should be templated by `S: State`?
</blockquote></details>

Yes, I added a TODO to change to Papyrus storage (at the least). Making it a `dyn State` is probably the right thing to do, but it was giving me problems; I'd rather deal with it in a later PR.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlvmQJChE4iLeJGn88:-NNpM6YA2PuUtAcRd-Kf:bpfugyi) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L152)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think this one's only necessary if `new` takes no args.
</blockquote></details>

Right, thanks.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlmdqj9z8_n_lkUGCc:-NNpN3EW49182ZyX056x:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L162)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Also, I don't think `chain_id` variable is needed; it's pretty clear.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNllAnFAJ_27VePHx0j:-NNpSuTe53la4LYHDnBb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L165)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think this should also be a small utility; it's very short, but repeats a lot.
Reading an address as well.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlmztYA4DCfVKfgTl-:-NNpUkqm8w11NePKsupn:b-pcwwgf) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L184)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are you planning to return the execution results?
</blockquote></details>

Yes, it will have to be some sort of union between `TransactionExecutionInfo` and `TransactionFailureReason`. I didn't do it yet because the return type of `#[pymethods]` has to implement some trait, better to do it in a separate PR.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNlw4J09Suy_jqrWXBV:-NNpVSks1R_M2I1ntwJM:bi4kwzu) ([raw file](https://github.com/starkware-libs/blockifier/blob/17e32910e407a143bd0a3e40d3a126024bd47a92/crates/native_blockifier/src/py_transaction.rs#L185)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This pattern also appeared in a previous PR, we should extract the logic into one place.

IMO this logic should be`tx.tx_type`, where `tx` is some Rust struct cast from the PyAny `tx`.
</blockquote></details>

It was actually the same line, I just moved it to this file in this PR. But I did create a util similar to the others because the `"name"` extraction appeared twice. WDYT?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNpjItXEcMuZUSyMYN8:-NNpjItXEcMuZUSyMYN9:b-3eziv3) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad7af037b5079751df6c2badd29b09af70ca4a60/crates/native_blockifier/src/py_transaction.rs#L30)):*
> ```XML
> fn py_attr<T>(obj: &PyAny, attr: &str) -> NativeBlockifierResult<T>
> where
>     T: for<'a> FromPyObject<'a>,
> ```

Why are both of them needed? Also, how do I read the first one and what does lifetime have to do here?



_Code quote:_
```XML
    T: for<'a> FromPyObject<'a>,
    T: Clone,
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNpz-hLB_dmsl-Qct2w:-NNpz-hM7RVBKPGgTU8w:br1e3hd) (no related file):*
WDYT about using `#[derive(FromPyObject)]` on Rust-analogues to the Python transactions, so that the parsing to Rust logic doesn't have to be explicitly written?

___

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNpz-hLB_dmsl-Qct2w:-NNq2R4Q3yfoIVC853gw:b-12ik23) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT about using `#[derive(FromPyObject)]` on Rust-analogues to the Python transactions, so that the parsing to Rust logic doesn't have to be explicitly written?
</blockquote></details>

I considered that, but realized those structs' fields will have to be of types that also derive that, so we'll still need to explicitly parse those fields into the actual tx fields. For example, the type of `sender_address` will have to be `BigUint` and then converted into `StarkFelt` and then into `ContractAddress` as is done now. Do you think that has a benefit that's worth the work?

___
___
*[`crates/native_blockifier/src/py_transaction.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNpjItXEcMuZUSyMYN8:-NNpksdo3dXDXkP0FotG:bmyx93w) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad7af037b5079751df6c2badd29b09af70ca4a60/crates/native_blockifier/src/py_transaction.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why are both of them needed? Also, how do I read the first one and what does lifetime have to do here?
</blockquote></details>

In order to `extract::<T>`, `T` has to implement both according to the compiler. There is probably a clone happening behind the scenes.
The lifetimes are needed because `FromPyObject` is a trait that has a lifetime. IIUC it means the trait is implemented for all lifetimes. You can read about it more here: https://doc.rust-lang.org/reference/trait-bounds.html#higher-ranked-trait-bounds.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNpz-hLB_dmsl-Qct2w:-NO3Ity8AtxyWLJ03ELS:b-bunfw5) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I considered that, but realized those structs' fields will have to be of types that also derive that, so we'll still need to explicitly parse those fields into the actual tx fields. For example, the type of `sender_address` will have to be `BigUint` and then converted into `StarkFelt` and then into `ContractAddress` as is done now. Do you think that has a benefit that's worth the work?
</blockquote></details>

How is it longer than what we're doing now?
The goal should be to optimize the use of existing solutions and try not to repeat code already implemented in the third-party package.
Let's merge though, we can consider refactoring later.

___
___
*[`crates/native_blockifier/src/py_transaction.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNpjItXEcMuZUSyMYN8:-NO3JDpq7TSYEMPcf4Om:brwxmp1) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad7af037b5079751df6c2badd29b09af70ca4a60/crates/native_blockifier/src/py_transaction.rs#L30)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In order to `extract::<T>`, `T` has to implement both according to the compiler. There is probably a clone happening behind the scenes.
The lifetimes are needed because `FromPyObject` is a trait that has a lifetime. IIUC it means the trait is implemented for all lifetimes. You can read about it more here: https://doc.rust-lang.org/reference/trait-bounds.html#higher-ranked-trait-bounds.
</blockquote></details>

What exactly does `extract` do? Is there a way to avoid all `getattr` and `extract`s?

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NO3Qo34D3kxpkd3iM9_:-NO3Qo34D3kxpkd3iM9a:b4j4r2i) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad7af037b5079751df6c2badd29b09af70ca4a60/crates/native_blockifier/src/py_transaction.rs#L162)):*
> ```XML
> impl PyTransactionExecutor {
>     #[new]
>     pub fn new(general_config: &PyAny, block_info: &PyAny) -> NativeBlockifierResult<Self> {
> ```

Add the names of the arguments, so that they can be passed by name in Python: `#[args(general_config, block_info)]`.



_Code quote:_
```XML
new
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NO3Qo34D3kxpkd3iM9_:-NO3Rg3W1gBfT7wdFMXr:b-llrb2r) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad7af037b5079751df6c2badd29b09af70ca4a60/crates/native_blockifier/src/py_transaction.rs#L162)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add the names of the arguments, so that they can be passed by name in Python: `#[args(general_config, block_info)]`.
</blockquote></details>

Also in `execute`:
```rust
#[args(tx)]
pub fn execute(&mut self, tx: &PyAny) -> PyResult<()> {...}
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNpz-hLB_dmsl-Qct2w:-NO4MLvv9r1FuhjOjySY:b2nhk7b) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How is it longer than what we're doing now?
The goal should be to optimize the use of existing solutions and try not to repeat code already implemented in the third-party package.
Let's merge though, we can consider refactoring later.
</blockquote></details>

NP.

___
___
*[`crates/native_blockifier/src/py_transaction.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NNpjItXEcMuZUSyMYN8:-NO4MJdQ4bvrd2bO3vv9:b-j6y6c) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad7af037b5079751df6c2badd29b09af70ca4a60/crates/native_blockifier/src/py_transaction.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What exactly does `extract` do? Is there a way to avoid all `getattr` and `extract`s?
</blockquote></details>

`getattr` gets the attribute as a `PyAny` and `extract` turns a `PyAny` into a Rust type that implements `FromPyObject` (like u64, BigUint, etc.). How do you mean avoid them? We can avoid the `getattr` by creating structs and deriving `FromPyObject` for them, which we said we'll discuss after merging. The `extract` is necessary IIUC.  
___
*[`crates/native_blockifier/src/py_transaction.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/268#-NO3Qo34D3kxpkd3iM9_:-NO4NXBN39IfjF8_qZYj:b-g70hwh) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad7af037b5079751df6c2badd29b09af70ca4a60/crates/native_blockifier/src/py_transaction.rs#L162)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Also in `execute`:
```rust
#[args(tx)]
pub fn execute(&mut self, tx: &PyAny) -> PyResult<()> {...}
```
</blockquote></details>

Cool! Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/268#-:-NO4Rp8q4kK1zjXLfG10:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
