### PR TITLE
Refactor Syscall reads and writes

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/451)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #448** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/448" target="_blank">Graphite</a> 
    * **PR #449** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/449" target="_blank">Graphite</a> 
      * **PR #451** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/451" target="_blank">Graphite</a>  👈
        * **PR #450** <a href="https://app.graphite.dev/github/pr/starkware-libs/blockifier/450" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/blockifier/451?utm_source=stack-comment).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/451)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/451#-NUpdBWy0qtmAjZObrIw:-NUpdBWy0qtmAjZObrIx:b-imf1np) ([raw file](https://github.com/starkware-libs/blockifier/blob/45b9ba20e9b22ab8590a380e00ce99c70671c1f8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L236)):*
> ```XML
>             &mut SyscallHintProcessor<'_>,
>         ) -> SyscallResult<Response>,
>     {
> ```

Do you think it's better now? What's the motivation?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/451)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/451#-NUpdBWy0qtmAjZObrIw:-NUpuwyMBqI2FwF7ycc1:b-x4qles) ([raw file](https://github.com/starkware-libs/blockifier/blob/45b9ba20e9b22ab8590a380e00ce99c70671c1f8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L236)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you think it's better now? What's the motivation?
</blockquote></details>

Yes. Currently, we demand constant size for these, even though that interface we actually need is just write/read.
Also, the size is decoupled from reading and the caller needs to remember to do it himself.

Specifically, I will need to thave the SyscallResponse which is of nonconstant size.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/451)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/451#-NUpdBWy0qtmAjZObrIw:-NUpzCa05rcjMEJsaZs2:bvvdtei) ([raw file](https://github.com/starkware-libs/blockifier/blob/45b9ba20e9b22ab8590a380e00ce99c70671c1f8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L236)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Yes. Currently, we demand constant size for these, even though that interface we actually need is just write/read.
Also, the size is decoupled from reading and the caller needs to remember to do it himself.

Specifically, I will need to thave the SyscallResponse which is of nonconstant size.
</blockquote></details>

I understand. But what I like in the current code is that the user doesn't have to advance tut syscall ptr himself. Doesn't it bother you it can be forgotten?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/451)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/451#-NUpdBWy0qtmAjZObrIw:-NUqDOIH9-gcS5BVfsKT:b-7v199l) ([raw file](https://github.com/starkware-libs/blockifier/blob/d781044b87757fa1da05a431b265babb5cb8046a/crates/blockifier/src/execution/syscalls/hint_processor.rs#L236)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I understand. But what I like in the current code is that the user doesn't have to advance tut syscall ptr himself. Doesn't it bother you it can be forgotten? 
</blockquote></details>

What? You are not making sense. That is exaclt the problem I fixed, that the user had to advacne it himself.
Now, it't inside the read() and write()

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/451)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
