### PR TITLE
feat(fee): charge for signatures per byte

### PR DESCRIPTION
**Pull request by avi-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1474)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1474)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 7 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqMjj9A2T7ZjW3gC8Mp:-NqMjj9B8R6DQlY69oFg:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8b8e87585b791334c8fb73a851a80a753ad868f/crates/blockifier/resources/versioned_constants.json#L7)):*
> ```JSON
>     },
>     "l2_resource_gas_costs": {
>         "milligas_per_data_word": 1280,
> ```

?



_Suggestion:_
```JSON
 "milligas_per_data_felt": 1280,
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqMhoXP0-ljZ3LJyEk6:-NqMhoXP0-ljZ3LJyEk7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8b8e87585b791334c8fb73a851a80a753ad868f/crates/blockifier/src/fee/gas_usage.rs#L95)):*
> ```XML
>     let l2_resource_gas_costs = versioned_constants.get_l2_resource_gas_costs();
>     let calldata_gas_cost =
>         (calldata_length + signature_length) * l2_resource_gas_costs.milligas_per_data_word / 1000;
> ```





_Suggestion:_
```XML
    let l2_gas_cost =
        (calldata_length + signature_length) * l2_resource_gas_costs.milligas_per_data_word / 1000;
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqMiRcL8NBCtm_PfWZV:-NqMiRcL8NBCtm_PfWZW:b-qk9xmr) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8b8e87585b791334c8fb73a851a80a753ad868f/crates/blockifier/src/fee/gas_usage_test.rs#L103)):*
> ```XML
>     let manual_starknet_gas_usage = 0;
>     let calldata_length = 0;
>     let signature_length = 0;
> ```

Try a non-zero value?



_Code quote:_
```XML
    let signature_length = 0;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqMi_4_8Dx1CeTjKGyy:-NqMi_4a56S6oRzsHNYx:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8b8e87585b791334c8fb73a851a80a753ad868f/crates/blockifier/src/transaction/transactions_test.rs#L435)):*
> ```XML
>     let da_gas = get_da_gas_cost(state_changes_count, use_kzg_da);
>     let calldata_gas =
>         get_calldata_and_signature_gas_cost(calldata_length, signature_length, versioned_constants);
> ```





_Suggestion:_
```XML
    let l2_gas_cost =
        get_calldata_and_signature_gas_cost(calldata_length, signature_length, versioned_constants);
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1474)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 7 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqMjj9A2T7ZjW3gC8Mp:-NqN13Ps6nqHY8_bNAQj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8b8e87585b791334c8fb73a851a80a753ad868f/crates/blockifier/resources/versioned_constants.json#L7)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqMhoXP0-ljZ3LJyEk6:-NqN1aF121xJL4x2Lih3:bynhe01) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8b8e87585b791334c8fb73a851a80a753ad868f/crates/blockifier/src/fee/gas_usage.rs#L95)):*
> ```XML
>     let l2_resource_gas_costs = versioned_constants.get_l2_resource_gas_costs();
>     let calldata_gas_cost =
>         (calldata_length + signature_length) * l2_resource_gas_costs.milligas_per_data_word / 1000;
> ```

I made it `calldata_and_signature_gas_cost` to be consistent with the name of the function.
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqMiRcL8NBCtm_PfWZV:-NqN20O2DKXHNt9voiSM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8b8e87585b791334c8fb73a851a80a753ad868f/crates/blockifier/src/fee/gas_usage_test.rs#L103)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Try a non-zero value?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqMi_4_8Dx1CeTjKGyy:-NqN16G4EXwRTSnLA3zj:b9v2to7) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8b8e87585b791334c8fb73a851a80a753ad868f/crates/blockifier/src/transaction/transactions_test.rs#L435)):*
> ```XML
>     let da_gas = get_da_gas_cost(state_changes_count, use_kzg_da);
>     let calldata_gas =
>         get_calldata_and_signature_gas_cost(calldata_length, signature_length, versioned_constants);
> ```

I made it `calldata_and_signature_gas` to be consistent with the name of the function and with the name of the variable above.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1474)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqN7Dc_5EAMZF6ko1LC:-NqN7Dc_5EAMZF6ko1LD:b-d4j3r3) ([raw file](https://github.com/starkware-libs/blockifier/blob/81de2b56432a83d986f2449ee30de0736f9d5c4e/crates/blockifier/src/versioned_constants.rs#L55)):*
> ```XML
>     os_constants: Arc<OSConstants>,
> 
>     l2_resource_gas_costs: Arc<L2ResourceGasCosts>,
> ```

Why `Arc`? It is a light struct.
Why not pub? Don't we want those field to be easily changeable? 



_Code quote:_
```XML
l2_resource_gas_costs: Arc<L2ResourceGasCosts>,
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqN6cmF1s4M9Cc9PmTL:-NqN6cmF1s4M9Cc9PmTM:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/81de2b56432a83d986f2449ee30de0736f9d5c4e/crates/blockifier/src/fee/gas_usage.rs#L94)):*
> ```XML
>     // TODO(Avi, 20/2/2024): Calculate the number of bytes instead of the number of felts.
>     let l2_resource_gas_costs = versioned_constants.get_l2_resource_gas_costs();
>     let n_data_words = u128_from_usize(calldata_length + signature_length)
> ```





_Suggestion:_
```XML
let n_data_felts = u128_from_usize(calldata_length + signature_length)
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqMi_4_8Dx1CeTjKGyy:-NqN7nAf6yR8n0tY-biE:b-cmf3jz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8b8e87585b791334c8fb73a851a80a753ad868f/crates/blockifier/src/transaction/transactions_test.rs#L435)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I made it `calldata_and_signature_gas` to be consistent with the name of the function and with the name of the variable above.
</blockquote></details>

Add suffix `cost`?

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1474)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1474)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqN7Dc_5EAMZF6ko1LC:-NqNBBTK11D1yA1sjyQb:b4mz8l6) ([raw file](https://github.com/starkware-libs/blockifier/blob/81de2b56432a83d986f2449ee30de0736f9d5c4e/crates/blockifier/src/versioned_constants.rs#L55)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why `Arc`? It is a light struct.
Why not pub? Don't we want those field to be easily changeable?
</blockquote></details>

Done.
(No need for `Arc` here, so I got rid of it)
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqN6cmF1s4M9Cc9PmTL:-NqNBK6dCz0fMfrtOVDa:b-iuu84x) ([raw file](https://github.com/starkware-libs/blockifier/blob/81de2b56432a83d986f2449ee30de0736f9d5c4e/crates/blockifier/src/fee/gas_usage.rs#L94)):*
> ```XML
>     // TODO(Avi, 20/2/2024): Calculate the number of bytes instead of the number of felts.
>     let l2_resource_gas_costs = versioned_constants.get_l2_resource_gas_costs();
>     let n_data_words = u128_from_usize(calldata_length + signature_length)
> ```

changed to `total_data_size` to be in line with yoni's comments on barak's PR
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-NqMi_4_8Dx1CeTjKGyy:-NqNBaqa7GmPcrj-4nP3:boqy24l) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8b8e87585b791334c8fb73a851a80a753ad868f/crates/blockifier/src/transaction/transactions_test.rs#L435)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Add suffix `cost`?
</blockquote></details>

I made it consistent with the variable above: `da_gas`.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-:-NqNES_2Avyutwv4ck4_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 3 of 5 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-:-NqNGMj-6mBV1adR3oJG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1474)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1474#-:-NqNJImN46KZb6h4pR1M:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request merged**
