### PR TITLE
test: create test for tx_executor

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)

### CODE REVIEW

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsCvkRb0PQWZW6xQFfQ:-NsCvkRc9Qa_fVkc7TtA:b5l57pf) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L46)):*
> ```XML
> }
> 
> fn l1_handler_for_test(
> ```

WDYT about moving it to `crates/blockifier/src/transaction/transactions.rs` or to add an `impl` block for `L1HandlerTransaction` with `fn create_for_testing`?



_Code quote:_
```XML
fn l1_handler_for_test(
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsCyTe3BjAPpNK7eptP:-NsCyTe3BjAPpNK7eptQ:b-gwyfd0) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L84)):*
Is it some kind of a convention? not sure I understand how it helps to read the test (:

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsCz8NZ8qOE5kNuWauL:-NsCz8N_0wn0DM_vQa4_:b-cayo9d) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L87)):*
Can you explain why you used ZERO above and you suggest to  consider ONE?



_Code quote:_
```XML
// TODO: consider TransactionVersion::ONE.
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsCzUoEEeJDeXm5Sbuz:-NsCzUoEEeJDeXm5Sbv-:b-4fohj6) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L91)):*
I'm not familiar with that, what does it do? and why it's an argument?



_Code quote:_
```XML
#[values(true)]
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD-1JgEQoEI8ORo4Jf:-NsD-1JgEQoEI8ORo4Jg:bb3kxp2) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L100)):*
WDYT about something like that:



_Suggestion:_
```XML
    let mut tx_executor = TransactionExecutor::create_for_testing(...);
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD-VlB15tpOlljMx4U:-NsD-VlB15tpOlljMx4V:b-o7cfrg) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L110)):*
Possible to remove `tx_type` and `version` from the test args and to put `tx: Transaction` instead? So we can remove this `match` expression:

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 112 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD0DEZ74fm2kqzRLrE:-NsD0DEZ74fm2kqzRLrF:b-6wfhh8) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L112)):*
Don't we want to test it too?



_Code quote:_
```XML
_tx_execution_info
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/bouncer.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD0QJk855t3V5I38sH:-NsD0QJk855t3V5I38sI:b-e4qahm) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/bouncer.rs#L11)):*
> ```XML
> 
> #[derive(Clone, Default)]
> #[cfg_attr(test, derive(Eq, PartialEq, Debug))]
> ```

I'm not familiar with that, can you explain what the `cfg_attr` and the `test` do? and why the derives split between lines 10 and 11?



_Code quote:_
```XML
#[cfg_attr(test, derive(Eq, PartialEq, Debug))]
```

**Review by barak-b-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)* status: all files reviewed, 8 unresolved discussions (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/blockifier/bouncer.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD0QJk855t3V5I38sH:-NsD5o6S-5mC2nD7SUa5:bn9wkyt) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/bouncer.rs#L11)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I'm not familiar with that, can you explain what the `cfg_attr` and the `test` do? and why the derives split between lines 10 and 11?
</blockquote></details>

`cfg_attr` is a conditional attribute that allows you to conditionally apply other attributes based on a configuration flag. In this case, `cfg_attr` is used in conjunction with the `test` configuration flag.
This allows us to derive these attributes only in the context of tests. It will not allow the attributes (`Eq` etc) to be derived in any context other than for testing. 


About the line split - it is just cleaner in my opinion. 
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsCvkRb0PQWZW6xQFfQ:-NsDCA8UA76LeKlbR1yd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L46)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT about moving it to `crates/blockifier/src/transaction/transactions.rs` or to add an `impl` block for `L1HandlerTransaction` with `fn create_for_testing`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsCyTe3BjAPpNK7eptP:-NsDCNui2QeN0Gyzsuq-:b-ogfjdf) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L84)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Is it some kind of a convention? not sure I understand how it helps to read the test (:
</blockquote></details>

I think I wanted to point out that this test is specifically for the `execute` method, but yeah - it is clear.

Removed. 
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsCz8NZ8qOE5kNuWauL:-NsD-L5S547kTVBy58ZJ:bu60wti) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L87)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Can you explain why you used ZERO above and you suggest to  consider ONE?
</blockquote></details>

About the TODO: Sorry - this is an irrelevant TODO. It might have been relevant for DeployAccount.
Removed.

About why use version Zero in this case: This is the only supported version for L1Handlers. See: https://github.com/starkware-libs/blockifier/blob/eb36a4486f8beb303d2ff5c09fcb00516a015f5d/crates/blockifier/src/abi/constants.rs#L9
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsCzUoEEeJDeXm5Sbuz:-NsD39-F2zslrcn3FtuG:bk8rtw6) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L91)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I'm not familiar with that, what does it do? and why it's an argument?
</blockquote></details>

`#[values]` allows the writer of the test to parameterize the test. It multiplies each `case` by running it for each `value`.

The flag `charge_fee` is a parameter of the method: `execute`, which is the subject of this test.  I want to make sure I test both cases. The issue is that right now - the test returns the same result with both `true` and `false` values. Maybe it will be different if we test the execution info.

I added the value `false`.
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD-VlB15tpOlljMx4U:-NsDE3iu0DUfGYYcnHzp:b-jd2zc7) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L110)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Possible to remove `tx_type` and `version` from the test args and to put `tx: Transaction` instead? So we can remove this `match` expression:
</blockquote></details>

test_contract is a parameter of the transaction - so it can't be a part of the parametrization (this is a downside of the FeaturedContract util).
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 112 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD0DEZ74fm2kqzRLrE:-NsD5LFm3KYdqQCo2nMh:b-5x0vla) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L112)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Don't we want to test it too?
</blockquote></details>

We might.
1. Let's do it in another session of PRs.
2. We are testing the execution on many other tests. This test might be redundant.

Do you agree?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD-1JgEQoEI8ORo4Jf:-NsDFiMM3yN-W6k2ppns:blyj4km) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L100)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT about something like that:
</blockquote></details>

I am against it.

We use `test_contract` later in this flow. The same will be true for other featured contracts soon.
This implies that this `create_for_testing` function should get a list of all the featured contracts (and their multiplicities, maybe). This is getting complicated - and I don't think it improves readability or modularity by this much.

See the implementation of your idea anyway: #1634 .

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/blockifier/bouncer.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD0QJk855t3V5I38sH:-NsDpuak-TjMdo6-aYKt:b-9nvdhl) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/bouncer.rs#L11)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

`cfg_attr` is a conditional attribute that allows you to conditionally apply other attributes based on a configuration flag. In this case, `cfg_attr` is used in conjunction with the `test` configuration flag.
This allows us to derive these attributes only in the context of tests. It will not allow the attributes (`Eq` etc) to be derived in any context other than for testing. 


About the line split - it is just cleaner in my opinion.
</blockquote></details>

Has to be split, since you cant conditionally compile _inside_ a derive block.

Note: if this needs to be available inside anything in `test_utils/` it might be better to write `any(feature="testing", test)` instead of just `test`, so it'll also work for external users of our test utils.
(Just `test` makes it work in `cargo test`. which is only available for the blockifier and not external users; but compiling with `features "testing"` extends our regular API with "testing functions/methods" that external users of blockifier may use. )

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/blockifier/bouncer.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD0QJk855t3V5I38sH:-NsDqiyU5lILDpjWDzNG:b5thdnr) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/bouncer.rs#L11)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Has to be split, since you cant conditionally compile _inside_ a derive block.

Note: if this needs to be available inside anything in `test_utils/` it might be better to write `any(feature="testing", test)` instead of just `test`, so it'll also work for external users of our test utils.
(Just `test` makes it work in `cargo test`. which is only available for the blockifier and not external users; but compiling with `features "testing"` extends our regular API with "testing functions/methods" that external users of blockifier may use. )
</blockquote></details>

That being said, i think `Debug` can easily be part of the regular derive, it's almost always Good to have. 
Also partialEq and Eq are generally OK, is there a correctness issue in exposing them to users?

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/bouncer.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD0QJk855t3V5I38sH:-NsDtjXB2sbjNwRHuLLh:b4yfybr) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/bouncer.rs#L11)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

That being said, i think `Debug` can easily be part of the regular derive, it's almost always Good to have. 
Also partialEq and Eq are generally OK, is there a correctness issue in exposing them to users?
</blockquote></details>

Since `BouncerInfo` holds `usize`s and a `VmExecutionResources`, which all have those derivations:



_Suggestion:_
```XML
#[derive(Clone, Debug, Default, Eq, PartialEq)]
```

**Comment by barak-b-starkware** [comment]
*[`crates/blockifier/src/blockifier/bouncer.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD0QJk855t3V5I38sH:-NsDuA2l2Fha-kjsutKG:bf2hbzl) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/bouncer.rs#L11)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Since `BouncerInfo` holds `usize`s and a `VmExecutionResources`, which all have those derivations:
</blockquote></details>

Thanks for the explanation (:

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/bouncer.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD0QJk855t3V5I38sH:-NsDwcVb5JCbxj3p4cnb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/bouncer.rs#L11)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Thanks for the explanation (:
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD-VlB15tpOlljMx4U:-NsE5AaVCm2klliCt2c-:b-7o21hw) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L110)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

test_contract is a parameter of the transaction - so it can't be a part of the parametrization (this is a downside of the FeaturedContract util).
</blockquote></details>

Removed `version` for now.
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 112 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsD0DEZ74fm2kqzRLrE:-NsE5OHF5NsPMWj2tpoa:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbea3bc92df9fcd353b1f9157691b4f48443a0aa/crates/blockifier/src/blockifier/transaction_executor_test.rs#L112)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Agree (: so, if we don't want to test it here (too), then change the test name to something with `bouncer_info` since, practically, we use the transaction executor to check the bouncer aggregation. Otherwise, add a TODO to check and test the execution info.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsDwU8v7Ie8Ub95Roaj:-NsE9eilA7stq8gz-BdZ:bx8kwwn) ([raw file](https://github.com/starkware-libs/blockifier/blob/39b928cb07ec08c86f2e9d47b4f9b40277ef3a13/crates/blockifier/src/blockifier/transaction_executor_test.rs#L93)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

which of the arguments here has a meaning to test (and not some random value)?
As long as there is no need I suggest to keep the `create_for_testing` method "as default as possible".
</blockquote></details>

These values are apparently as basic as you can get. 
___
*[`crates/blockifier/src/transaction/transactions.rs` line 470 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsDww2DAWB80uj_iKKY:-NsE8WAsC-p2JvBJ953f:b-yd6p7o) ([raw file](https://github.com/starkware-libs/blockifier/blob/39b928cb07ec08c86f2e9d47b4f9b40277ef3a13/crates/blockifier/src/transaction/transactions.rs#L470)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Are there any arguments that can be removed so we could use defaults? related to the [discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsDwU8v7Ie8Ub95Roaj) above
</blockquote></details>

contract_address - can not be shared.
l1_fee  - evidently, cannot be shared. In `transactions_test.rs` it gets some default extreme values I do not wish to change, and in our test - it is the minimal required fee for the tx_executor to execute the tx.

calldata  - In `transactions_test.rs`, this value is also used later in the test - to check the call info. In our case, it is actually a part of the `_tx_execution_info` (which will not be covered in this PR). 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1707 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsDxVbnC0ScCc1ic1LE:-NsE6HtU4KaXaxqQXPAh:b7u3j2s) ([raw file](https://github.com/starkware-libs/blockifier/blob/f89d16e9e49a834bde7f0f11fe136df673544f65/crates/blockifier/src/transaction/transactions_test.rs#L1707)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I see that those values are precisely the same as you picked (: so it's another reason to move it to `create_for_testing`?
</blockquote></details>

The issue is that this calldata is used later in this test, so I do want to present it as a parameter (at least in this context).

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 75 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsIcsvn7fl4YHCmpd0Z:-NsJ-KyD2oo1RZ7Z00_i:bofgqn9) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3f2b1780c2f9bcc07bf36333b57daf236bb5765/crates/blockifier/src/blockifier/transaction_executor_test.rs#L75)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please refrain from hard-coding unstable numbers (gas_weight, n_steps, builtins)
`state_diff_size`,  `message_segment_length`,  `n_events` are okay.

You can use the execution_info (which is not tested here) to bound/calculate the unstable fields
</blockquote></details>

Done.
The fields from `BouncerInfo` which are not checked here are: `gas_weight` and `execution_resources`.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 75 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsIcsvn7fl4YHCmpd0Z:-NsJ07h96vokhErVFH3z:b-673da4) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3f2b1780c2f9bcc07bf36333b57daf236bb5765/crates/blockifier/src/blockifier/transaction_executor_test.rs#L75)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
The fields from `BouncerInfo` which are not checked here are: `gas_weight` and `execution_resources`.
</blockquote></details>

Do we want to add a todo?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 75 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsIcsvn7fl4YHCmpd0Z:-NsJKrn75SxnTqJIeG60:b-x0paxf) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3f2b1780c2f9bcc07bf36333b57daf236bb5765/crates/blockifier/src/blockifier/transaction_executor_test.rs#L75)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Do we want to add a todo?
</blockquote></details>

Yes :)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 75 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsIcsvn7fl4YHCmpd0Z:-NsNF9pr0JW-Du18BJFc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e3f2b1780c2f9bcc07bf36333b57daf236bb5765/crates/blockifier/src/blockifier/transaction_executor_test.rs#L75)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yes :)
</blockquote></details>

Done.

**Review by barak-b-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 67 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NscK64P4tf8uOYi-xLZ:-NscK64QCIsRPVxGWtFo:b-ogv627) ([raw file](https://github.com/starkware-libs/blockifier/blob/6bf2fe05982795a5b531f316f928d7b98d12ef91/crates/blockifier/src/blockifier/transaction_executor_test.rs#L67)):*
> ```XML
>     // TODO(Arni, 30/03/2024): Consider adding a test for the transaction execution info. If A test
>     // should not be added, rename the test to `test_bouncer_info`.
>     // TODO(Arni, 30/03/2024): Test all fields of bouncer info.
> ```

Why it's not the case now?



_Code quote:_
```XML
// TODO(Arni, 30/03/2024): Test all fields of bouncer info.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsDwU8v7Ie8Ub95Roaj:-NscM41u2YPeY22Wvv2r:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/39b928cb07ec08c86f2e9d47b4f9b40277ef3a13/crates/blockifier/src/blockifier/transaction_executor_test.rs#L93)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

These values are apparently as basic as you can get.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 67 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NscK64P4tf8uOYi-xLZ:-NscLYx48Px0xHc8NTCs:b-320khf) ([raw file](https://github.com/starkware-libs/blockifier/blob/6bf2fe05982795a5b531f316f928d7b98d12ef91/crates/blockifier/src/blockifier/transaction_executor_test.rs#L67)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Why it's not the case now?
</blockquote></details>

No.
See this discussion with @Yoni-Starkware.
We do not test the `gas_weight` for example.

**Review by barak-b-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-:-NscNBjWDuNl8lNe1P7P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NsDwU8v7Ie8Ub95Roaj:-NscMZVx5nYwX4Q_gWJk:b6c2lzw) ([raw file](https://github.com/starkware-libs/blockifier/blob/39b928cb07ec08c86f2e9d47b4f9b40277ef3a13/crates/blockifier/src/blockifier/transaction_executor_test.rs#L93)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Got it, I suggest extending this TODO so it will be more informative, something like "Test unstable number: gas_weight and.." or something

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-:-NscSAqm9Mj0BsM7WBLN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 67 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1625#-NscK64P4tf8uOYi-xLZ:-NscU-lr2nD2Wj36cTkI:bgll6mz) ([raw file](https://github.com/starkware-libs/blockifier/blob/6bf2fe05982795a5b531f316f928d7b98d12ef91/crates/blockifier/src/blockifier/transaction_executor_test.rs#L67)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@barak-b-starkware I don't want the test to fail upon every compiler/code/os change
We should test things like steps in a more robust way
</blockquote></details>

for the record, @barak-b-starkware wanted to say this here:
Got it, I suggest extending this TODO so it will be more informative, something like "Test unstable number: gas\_weight and.." or something

**Pull request merged**
