### PR TITLE
Setting the compiled hash under the class hash in declare version 2.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/437)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/437)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/437#-NUWZXeV73U3VFGNIrja:-NUWZXeV73U3VFGNIrjb:buom88k) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3beaa9656acea412c4cb31f61cbc96bb4e2756/crates/blockifier/src/state/cached_state.rs#L112)):*
> ```XML
>     }
> 
>     fn get_compiled_class_hash(&mut self, class_hash: ClassHash) -> StateResult<CompiledClassHash> {
> ```

Currently, it is not in use. I'll leave it here for now.



_Code quote:_
```XML
fn get_compiled_class_hash(&mut self, class_hash: ClassHash) -> StateResult<CompiledClassHash> {
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/437)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/437#-NU_GUZu1xVCaOfa4Ku7:-NU_GUZu1xVCaOfa4Ku8:bjzhwww) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3beaa9656acea412c4cb31f61cbc96bb4e2756/crates/blockifier/src/state/cached_state.rs#L231)):*
> ```XML
> #[derive(Debug, Default, PartialEq)]
> struct StateCache {
>     // Committed changes:
> ```

Move new comment to the class' docstring; explain those are changes needed for block state commitment.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/437#-NU_HIe85I3CGSv1fipa:-NU_HIe85I3CGSv1fipb:bv96rva) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3beaa9656acea412c4cb31f61cbc96bb4e2756/crates/blockifier/src/transaction/transactions.rs#L92)):*
> ```XML
>         match self {
>             // No class commitment, so no need to check if the class is already declared.
>             DeclareTransaction::V0(_) => {
> ```

Use [this](https://github.com/starkware-libs/blockifier-old/blob/185473cd803d6a5dbbdf8fb679411d775ea97d97/crates/blockifier/src/transaction/account_transaction.rs#L122) syntax to capture both V0 and V1.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/437#-NU_ICYt5JOQJeA0fXdu:-NU_ICYt5JOQJeA0fXdv:bu47dj7) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3beaa9656acea412c4cb31f61cbc96bb4e2756/crates/blockifier/src/transaction/transactions.rs#L112)):*
> ```XML
>                         // Class is already declared.
>                         // From V2 up, cannot redeclare (i.e., make sure the leaf is
>                         // uninitialized). Changing class leaf in
> ```

```
Class is already declared, cannot redeclare 
(i.e., make sure the leaf is uninitialized). 
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/437)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/437#-NU_ICYt5JOQJeA0fXdu:-NUaTzdx4eDkE8qrwgov:bs4eto8) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3beaa9656acea412c4cb31f61cbc96bb4e2756/crates/blockifier/src/transaction/transactions.rs#L112)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

```
Class is already declared, cannot redeclare 
(i.e., make sure the leaf is uninitialized). 
```
</blockquote></details>

Remove the syscall sentence, it's wrong.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/437)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/437)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/437#-NU_ICYt5JOQJeA0fXdu:-NUov5FuDYH31gi1AjBs:bs7wumx) ([raw file](https://github.com/starkware-libs/blockifier/blob/1e3beaa9656acea412c4cb31f61cbc96bb4e2756/crates/blockifier/src/transaction/transactions.rs#L112)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove the syscall sentence, it's wrong.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/437#-:-NUovneJ5dJqflJQE4MW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Pull request merged**
