### PR TITLE
feat(concurrency): implement execute_chunk

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1929)

### CODE REVIEW

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1929)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz2C5H8EZQfwXOuybOB:-Nz2C5H8EZQfwXOuybOC:bbsbukj) ([raw file](https://github.com/starkware-libs/blockifier/blob/777083b1f20b92f61991a79db64457cba83ca348/crates/blockifier/src/blockifier/transaction_executor.rs#L55)):*
> ```XML
> }
> 
> impl<S: StateReader + std::marker::Send + std::marker::Sync> TransactionExecutor<S> {
> ```

Why do you need the traits `Send` and `Sync`?

I think the prefix `std::marker::` is not needed. There are examples in the repo that use `Send` without the prefix.



_Suggestion:_
```XML
impl<S: StateReader + Send + Sync> TransactionExecutor<S> {
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz29RPr1zRbbCvpDSkx:-Nz29RPr1zRbbCvpDSky:b-qa17tr) ([raw file](https://github.com/starkware-libs/blockifier/blob/777083b1f20b92f61991a79db64457cba83ca348/crates/blockifier/src/blockifier/transaction_executor.rs#L179)):*
> ```XML
>         chunk_state_to_commit_changes
>             .commit_chunk(committed_chunk_size, Arc::clone(&self.block_state));
>         tx_execution_infos
> ```

We need to ask the scheduler how many transactions have been committed.
It is possible that some of the `execution_outputs` represent transactions that have been executed but not committed.

*Note:* the method `get_n_committed_txs` has been added to the scheduler in #1918, which hasn't been merged yet. It just returns the commit index. You can add this method yourself to avoid waiting for the other PR.
 



_Suggestion:_
```XML
        let committed_chunk_size = worker_executor.scheduler.get_n_committed_txs();
        chunk_state_to_commit_changes
            .commit_chunk(committed_chunk_size, Arc::clone(&self.block_state));
        tx_execution_infos[..committed_chunk_size].to_vec()
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1929)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz7Kb2hDLD8Xxx_Af96:-Nz7Kb2hDLD8Xxx_Af97:bx2qb) ([raw file](https://github.com/starkware-libs/blockifier/blob/777083b1f20b92f61991a79db64457cba83ca348/crates/blockifier/src/blockifier/transaction_executor.rs#L169)):*
> ```XML
>                     results.push(Ok(execution_task_output
>                         .result
>                         .expect("Failed to extract execution info from result.")));
> ```

Result can be failure

Also, @avi-starkware is right



_Suggestion:_
```XML
        let tx_execution_results = worker_executor
            .execution_outputs
            .iter()
            .fold_while(Vec::new(), |mut results, execution_output| {
                if let Some(locked_execution_output) =
                    execution_output.lock().expect("Failed to lock execution output.").take()
                {
                    results.push(Ok(locked_execution_output.result
                ));
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz7IolI1QHWf3ZpdFSy:-Nz7IolJBX68_vz7G733:b-468bfi) ([raw file](https://github.com/starkware-libs/blockifier/blob/777083b1f20b92f61991a79db64457cba83ca348/crates/blockifier/src/blockifier/transaction_executor.rs#L178)):*
> ```XML
>         let committed_chunk_size = tx_execution_infos.len();
>         chunk_state_to_commit_changes
>             .commit_chunk(committed_chunk_size, Arc::clone(&self.block_state));
> ```

Why not?

Oh, it is moved to the threadsafe thing. Can you "unwrap" it once the concurrent execution is over?



_Suggestion:_
```XML
        versioned_state
            .commit_chunk(committed_chunk_size, Arc::clone(&self.block_state));
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1929)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz2C5H8EZQfwXOuybOB:-Nz7iOi72BPmejqYu6Yy:b9c9zo) ([raw file](https://github.com/starkware-libs/blockifier/blob/777083b1f20b92f61991a79db64457cba83ca348/crates/blockifier/src/blockifier/transaction_executor.rs#L55)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why do you need the traits `Send` and `Sync`?

I think the prefix `std::marker::` is not needed. There are examples in the repo that use `Send` without the prefix.
</blockquote></details>

Done.
I need the traits to pass the block state between threads.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz7Kb2hDLD8Xxx_Af96:-Nz7ky6J--8iT-6U1-Ag:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/777083b1f20b92f61991a79db64457cba83ca348/crates/blockifier/src/blockifier/transaction_executor.rs#L169)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Result can be failure

Also, @avi-starkware is right
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz7IolI1QHWf3ZpdFSy:-Nz7oJVq90WCXQFBLdor:b-jt2st) ([raw file](https://github.com/starkware-libs/blockifier/blob/777083b1f20b92f61991a79db64457cba83ca348/crates/blockifier/src/blockifier/transaction_executor.rs#L178)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not?

Oh, it is moved to the threadsafe thing. Can you "unwrap" it once the concurrent execution is over?
</blockquote></details>

I can do something like `*chunk_state.0.lock().unwrap()` but the `.0` complains that "field `0` is private".
We can add a method to the `ThreadSafeVersionedState` that returns the `VersionedState`. WDYT?
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz29RPr1zRbbCvpDSkx:-Nz7uyl05Y6fp-7wGRLY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/777083b1f20b92f61991a79db64457cba83ca348/crates/blockifier/src/blockifier/transaction_executor.rs#L179)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

We need to ask the scheduler how many transactions have been committed.
It is possible that some of the `execution_outputs` represent transactions that have been executed but not committed.

*Note:* the method `get_n_committed_txs` has been added to the scheduler in #1918, which hasn't been merged yet. It just returns the commit index. You can add this method yourself to avoid waiting for the other PR.
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1929)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz7IolI1QHWf3ZpdFSy:-Nz89mpDAUjMXrUtKVib:b-q4i6xt) ([raw file](https://github.com/starkware-libs/blockifier/blob/777083b1f20b92f61991a79db64457cba83ca348/crates/blockifier/src/blockifier/transaction_executor.rs#L178)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I can do something like `*chunk_state.0.lock().unwrap()` but the `.0` complains that "field `0` is private".
We can add a method to the `ThreadSafeVersionedState` that returns the `VersionedState`. WDYT?
</blockquote></details>

Yeah, I like that. This method should consume  `self`
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz87tA25WkGaorvTo8n:-Nz87tA25WkGaorvTo8o:b4th09m) ([raw file](https://github.com/starkware-libs/blockifier/blob/072fbd3bb09fde17db3362b0b9f97d42eaaaa5a0/crates/blockifier/src/blockifier/transaction_executor.rs#L160)):*
> ```XML
>             }
>         });
>         let committed_chunk_size = worker_executor.scheduler.get_n_committed_txs();
> ```

@avi-starkware consider renaming to `get_last_committed_index`



_Code quote:_
```XML
get_n_committed_txs
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz88BfY-TF52G3g9Ejf:-Nz88BfY-TF52G3g9Ejg:bxew10y) ([raw file](https://github.com/starkware-libs/blockifier/blob/072fbd3bb09fde17db3362b0b9f97d42eaaaa5a0/crates/blockifier/src/blockifier/transaction_executor.rs#L179)):*
> ```XML
>                     Done(results)
>                 }
>             })
> ```


```rust
        .fold_while(Vec::new(), |mut results, execution_output| {
                if results.len() > committed_chunk_size {
                    Done(results)
                }
                let locked_execution_output.except("Output must be ready").lock().expect("Failed to lock execution output.").take()
                results.push(locked_execution_output.result.map_err(TransactionExecutorError::from));
                Continue(results)
            })
```



_Suggestion:_
```XML
        .fold_while(Vec::new(), |mut results, execution_output| {
                if results.len() > committed_chunk_size {
                    Done(results)
                }
                let locked_execution_output.except("Output must be ready").lock().expect("Failed to lock execution output.").take()
                results.push(locked_execution_output.result.map_err(TransactionExecutorError::from));
                Continue(results)
            })
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1929)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz7IolI1QHWf3ZpdFSy:-Nz8p6IjBN8uM3ndTp9o:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/777083b1f20b92f61991a79db64457cba83ca348/crates/blockifier/src/blockifier/transaction_executor.rs#L178)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yeah, I like that. This method should consume  `self`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz87tA25WkGaorvTo8n:-Nz8pGGn44PUxJBM1UgJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/072fbd3bb09fde17db3362b0b9f97d42eaaaa5a0/crates/blockifier/src/blockifier/transaction_executor.rs#L160)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@avi-starkware consider renaming to `get_last_committed_index`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz88BfY-TF52G3g9Ejf:-Nz8W07OChdQ49JTnae8:bi0setz) ([raw file](https://github.com/starkware-libs/blockifier/blob/072fbd3bb09fde17db3362b0b9f97d42eaaaa5a0/crates/blockifier/src/blockifier/transaction_executor.rs#L179)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

```rust
        .fold_while(Vec::new(), |mut results, execution_output| {
                if results.len() > committed_chunk_size {
                    Done(results)
                }
                let locked_execution_output.except("Output must be ready").lock().expect("Failed to lock execution output.").take()
                results.push(locked_execution_output.result.map_err(TransactionExecutorError::from));
                Continue(results)
            })
```
</blockquote></details>

Done.
Nice!
You must use the `else` in the `fold_while`, but it is still pretty much the same as you suggested.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1929#-Nz87tA25WkGaorvTo8n:-Nz8zQ7W4E-K5OnH8Nip:bi2eux8) ([raw file](https://github.com/starkware-libs/blockifier/blob/072fbd3bb09fde17db3362b0b9f97d42eaaaa5a0/crates/blockifier/src/blockifier/transaction_executor.rs#L160)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not the last committed index. It is the first uncommitted index (last_committed_index+1). That is why it is the number of committed transactions (the first index is 0).

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1929)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @meship-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

**Pull request closed without merging**
