### PR TITLE
Split function

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1083)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1083#-:-NiYnNF3-rjT6VRUxFWD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1083)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1083#-NiYnOKl3DMtUTWnp6sV:-NiYnOKl3DMtUTWnp6sW:bx3yzx2) ([raw file](https://github.com/starkware-libs/blockifier/blob/133eea8ca8203fce9c5522579098cbd2cc6dbeba/crates/blockifier/src/fee/fee_utils.rs#L82)):*
> ```XML
>     let l1_gas_usage = calculate_tx_l1_gas_usage(resources, block_context)?;
>     Ok(get_fee_by_l1_gas_usage(block_context, l1_gas_usage, fee_type))
> }
> ```

Is this the single usage?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1083)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1083#-NiYnOKl3DMtUTWnp6sV:-NiZ1RnQ56sJ-xzCz9ro:b-xolgew) ([raw file](https://github.com/starkware-libs/blockifier/blob/133eea8ca8203fce9c5522579098cbd2cc6dbeba/crates/blockifier/src/fee/fee_utils.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the single usage?
</blockquote></details>

A PR up the PR stack uses it.
For v3 txs that exceed max gas amount on *successful* `__execute__`, we need to charge for max gas amount, so we need the gas->fee conversion.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1083)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
