### PR TITLE
feat(fee): add n_events field to BouncerInfo

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1489)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1489)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1489#-NqSRr025MWZKIy_eDjJ:-NqSRr025MWZKIy_eDjK:b-a20e15) (no related file):*
Python's PR:
https://reviewable.io/reviews/starkware-industries/starkware/33953

___

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1489)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/execution/bouncer.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1489#-NqScQCnCxAJgA6ipraM:-NqScQCnCxAJgA6ipraN:b-cm6ugb) ([raw file](https://github.com/starkware-libs/blockifier/blob/06ceabe93f587f1085fc5e5887f2b4e748de017a/crates/blockifier/src/execution/bouncer.rs#L10)):*
> ```XML
> 
> #[derive(Clone, Default)]
> // TODO(Ayelet, 24/01/2024): Consider remove message_segment_length, state_diff_size.
> ```

Why you removed this TODO?



_Code quote:_
```XML
// TODO(Ayelet, 24/01/2024): Consider remove message_segment_length, state_diff_size.
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1489#-:-NqSmTRO7-1c8NAmdiCn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1489)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/bouncer.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1489#-NqScQCnCxAJgA6ipraM:-NqWRkXM9yPi32AlVbMn:b-vghkwv) ([raw file](https://github.com/starkware-libs/blockifier/blob/06ceabe93f587f1085fc5e5887f2b4e748de017a/crates/blockifier/src/execution/bouncer.rs#L10)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why you removed this TODO?
</blockquote></details>

Not relevant anymore. should have been deleted before.

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1489)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Pull request merged**
