### PR TITLE
Add secp256r1.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/869)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/869)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @giladchase and @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdAmBWxC6JA9_GzdbGl:-NdAmBWy-CZSKARAD_us:b-ce30n8) (no related file):*
I think we don't have `.sierra.json` files in the repo. anymore.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdAmStz9bzgf5byqhN9:-NdAmStz9bzgf5byqhNA:bc6i385) (no related file):*
Why does the new curve not use the parity of Y? Can this be documented?

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/869)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 428 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdAmrCV1U7G0aHL7naU:-NdAmrCV1U7G0aHL7naV:b-x70ep2) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f1c8f3f8d613f577aadad3f8a117067fe90d78/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L428)):*
> ```XML
> #[test]
> 
> fn test_secp256r1() {
> ```

Remove blank line above.



_Code quote:_
```XML
fn test_secp256r1() {
```
___
*[`crates/blockifier/src/fee/os_resources.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdAmv9Q3C4tg0KlOACp:-NdAmv9Q3C4tg0KlOACq:b-igijpt) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f1c8f3f8d613f577aadad3f8a117067fe90d78/crates/blockifier/src/fee/os_resources.rs#L158)):*
> ```XML
>                     "range_check_builtin": 36
>                 },
>                 "n_memory_holes": 0,
> ```

Please update the OS resources in the main repo. as well (`cairo-v0.12.3`).

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why does the new curve not use the parity of Y? Can this be documented?
</blockquote></details>

I'm testing only 
 y_parity = true;
for both curves.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/fee/os_resources.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdAmv9Q3C4tg0KlOACp:-NdAqpRk4itHr8gQRoxQ:b-pctz2z) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f1c8f3f8d613f577aadad3f8a117067fe90d78/crates/blockifier/src/fee/os_resources.rs#L158)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please update the OS resources in the main repo. as well (`cairo-v0.12.3`).
</blockquote></details>

There is a PR:
https://reviewable.io/reviews/starkware-industries/starkware/31679#-

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/869)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdAmBWxC6JA9_GzdbGl:-NdAqdUH0M_3q4M7LeMB:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we don't have `.sierra.json` files in the repo. anymore.
</blockquote></details>

Done.

___
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 428 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdAmrCV1U7G0aHL7naU:-NdAqnfU86P2KQvVFmfV:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f1c8f3f8d613f577aadad3f8a117067fe90d78/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L428)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove blank line above.
</blockquote></details>

done

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/869)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdAmStz9bzgf5byqhN9:-NdAry3583aW_Cj7Vvwi:b-cvftdo) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm testing only 
 y_parity = true;
for both curves.
</blockquote></details>

I see a difference in their (testing) Cairo code.

___

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/869)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I see a difference in their (testing) Cairo code.
</blockquote></details>

is it better now?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/869)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 222 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdAxZc90YkzjD-p8E2l:-NdB5BQb9Pcxr9FI8b45:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f2b10f83f3ec6b3c3a1bb65636703ba39771d43/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L222)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you please make the two test functions have minimum changes?
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/869)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @ilyalesokhin-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 281 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdB9i7J1aDQULvN_D4m:-NdB9i7K3Z4-ypv5P0X0:b-nvjvi4) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aa461aaa62ba48fac0843891456d67466c74127/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L281)):*
> ```Cairo
>         // msg = ""
>         // public key: (0x04aaec73635726f213fb8a9e64da3b8632e41495a944d0045b522eba7240fad5,
>         //              0x0087d9315798aaa3a5ba01775787ced05eaaf7b4e09fc81d6d1aa546e8365d525d).
> ```

Can you add a similar comment to `get_message_and_secp256k1_signature`?



_Code quote:_
```Cairo
        // msg = ""
        // public key: (0x04aaec73635726f213fb8a9e64da3b8632e41495a944d0045b522eba7240fad5,
        //              0x0087d9315798aaa3a5ba01775787ced05eaaf7b4e09fc81d6d1aa546e8365d525d).
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 281 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/869#-NdB9i7J1aDQULvN_D4m:-NdBETrS7hWKdeWyEij0:b4duz44) ([raw file](https://github.com/starkware-libs/blockifier/blob/3aa461aaa62ba48fac0843891456d67466c74127/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L281)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you add a similar comment to `get_message_and_secp256k1_signature`?
</blockquote></details>

I removed the comment here, I don't know the preimage of the other msg_hash, and the public key is redundant.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/869#-:-NdBFGOtEeBw0v3oVi6s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
