### PR TITLE
Get invoke tx in from python.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)* status: all files reviewed, 8 unresolved discussions (waiting on @alon-dotan-starkware, @alonh5, and @giladchase)

___
*[`Cargo.lock` line 217 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHbAArEapdLt8-AGq6:-NNHbAArEapdLt8-AGq7:bovbdmy) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/Cargo.lock#L217)):*
> ```TOML
>  "thiserror",
> ]
> ```

Why did this `.lock` change as well? 
___
*[`crates/native_blockifier/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHb5n7A8rJFXU74BnQ:-NNHb5n7A8rJFXU74BnR:bdk7ku9) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/Cargo.toml#L16)):*
> ```TOML
> 
> [dependencies]
> blockifier = { git = "https://github.com/starkware-libs/blockifier", branch = "main" }
> ```

Why is this needed?



_Code quote:_
```TOML
branch = "main"
```
___
*[`crates/native_blockifier/Cargo.toml` line 18 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHb2UvE56jgSRt2YIi:-NNHb2UvE56jgSRt2YIj:bts8x0u) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/Cargo.toml#L18)):*
> ```TOML
> blockifier = { git = "https://github.com/starkware-libs/blockifier", branch = "main" }
> num-bigint = { version = "0.4" }
> pyo3 = { version = "0.17.3", features = ["extension-module", "num-bigint"] }
> ```

Why not latest?
___
*[`crates/native_blockifier/Cargo.toml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHb2F_1UKNzrnjm4bZ:-NNHb2F_1UKNzrnjm4b_:b3ksj) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/Cargo.toml#L19)):*
> ```TOML
> num-bigint = { version = "0.4" }
> pyo3 = { version = "0.17.3", features = ["extension-module", "num-bigint"] }
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "0a11ad3", features = [
> ```

h



_Code quote:_
```TOML
rev = "0a11ad3"
```
___
*[`crates/native_blockifier/src/lib.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHcZHO4yODuXWg6cfG:-NNHcZHO4yODuXWg6cfH:b-7wfq46) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/src/lib.rs#L13)):*
> ```XML
>     Calldata, Fee, InvokeTransaction, TransactionHash, TransactionSignature, TransactionVersion,
> };
> ```

This is going to be a big file; let's move this code to `py_transaction.rs`.
___
*[`crates/native_blockifier/src/lib.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHbWIp9hsW5anQpU1f:-NNHbWIq6ea2zB5yIGWh:b-f5s6z4) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/src/lib.rs#L16)):*
> ```XML
> fn biguint_to_felt(biguint: BigUint) -> StarkFelt {
>     let biguint_hex = format!("{biguint:#x}");
>     StarkFelt::try_from(biguint_hex.as_str()).unwrap()
> ```

`Result`?
Also, perhaps a `try_from` for `StarkFelt`?



_Code quote:_
```XML
.unwrap()
```
___
*[`crates/native_blockifier/src/lib.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHcDdx0jLb48D2jo2g:-NNHcDdx0jLb48D2jo2h:bq2pove) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/src/lib.rs#L35)):*
> ```XML
>     ));
>     let entry_point_selector: Option<&PyAny> = tx.getattr("entry_point_selector")?.extract()?;
>     let entry_point_selector = if let Some(selector) = entry_point_selector {
> ```

This is always `None` in invoke transactions (the selector is a hardcoded `__execute__`); let's return an error if it isn't the case. 



_Code quote:_
```XML
entry_point_selector
```
___
*[`crates/native_blockifier/src/lib.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHcAVGAod-Lafl5d2T:-NNHcAVGAod-Lafl5d2U:beeavfv) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/src/lib.rs#L39)):*
> ```XML
>     } else {
>         None
>     };
> ```

Define two small utilities: receiving a name of an attribute and returning a single `StarkFelt`, or a `Vec<StarkFelt>`.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @alon-dotan-starkware, @elintul, and @giladchase)

___
*[`Cargo.lock` line 217 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHbAArEapdLt8-AGq6:-NNHctvE2GaO0Y8gdExt:b41itfr) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/Cargo.lock#L217)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why did this `.lock` change as well? 
</blockquote></details>

In `native_blockifier` I'm getting the `blockifier`dependancy from git, I think that's why.
___
*[`crates/native_blockifier/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHb5n7A8rJFXU74BnQ:-NNHecqtEf_yruBxI5dl:b-6hfd4j) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/Cargo.toml#L16)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

It wasn't getting the latest version without it, but now it's fine. There might be a small delay, I don't know where it gets it from. I removed it for now.
___
*[`crates/native_blockifier/Cargo.toml` line 18 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHb2UvE56jgSRt2YIi:-NNHdXH0CiB7K5RMx6DO:bmfc9wz) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/Cargo.toml#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not latest?
</blockquote></details>

I didn't add this. I'll ask Gilad.
___
*[`crates/native_blockifier/Cargo.toml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHb2F_1UKNzrnjm4bZ:-NNHdasb1WgvQLzokoQ7:bbowwkw) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/Cargo.toml#L19)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

h
</blockquote></details>

This was copied from `blockifier`, if that's the question. I'm guessing it's so it doesn't break on changes.
___
*[`crates/native_blockifier/src/lib.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHbWIp9hsW5anQpU1f:-NNHgc4v807wWdrIO-JM:byfwaxw) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/src/lib.rs#L16)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`Result`?
Also, perhaps a `try_from` for `StarkFelt`?
</blockquote></details>

Should a bigint to stark felt conversion be part of SN API?
___
*[`crates/native_blockifier/src/lib.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHcDdx0jLb48D2jo2g:-NNHg9kN2DFz8NErU_uj:bndnib4) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/src/lib.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is always `None` in invoke transactions (the selector is a hardcoded `__execute__`); let's return an error if it isn't the case. 
</blockquote></details>

This already happens in the account tx execution. Do you also want it here?
___
*[`crates/native_blockifier/src/lib.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHcAVGAod-Lafl5d2T:-NNHjC6h7W_KfX7mOlu-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/src/lib.rs#L39)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Define two small utilities: receiving a name of an attribute and returning a single `StarkFelt`, or a `Vec<StarkFelt>`.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)* status: all files reviewed, 13 unresolved discussions (waiting on @alon-dotan-starkware, @alonh5, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHw0y25zepm_XeT9R7:-NNHw0y25zepm_XeT9R8:b9fm7za) (no related file):*
Do we want to add a unit test?

___
___
*[`Cargo.lock` line 217 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHbAArEapdLt8-AGq6:-NNHwCDj6mugqDHf6q5l:bho8pf0) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/Cargo.lock#L217)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In `native_blockifier` I'm getting the `blockifier`dependancy from git, I think that's why.
</blockquote></details>

Weird; how is it different from the "blockifier" above?
___
*[`crates/native_blockifier/Cargo.toml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHb2F_1UKNzrnjm4bZ:-NNHwJ9F9gs61XBmljq8:b-ojj31t) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/Cargo.toml#L19)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This was copied from `blockifier`, if that's the question. I'm guessing it's so it doesn't break on changes.
</blockquote></details>

Let's try to move to latest.
___
*[`crates/native_blockifier/src/lib.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHbWIp9hsW5anQpU1f:-NNHqpqu2ZRdmbovAJfm:b-8ahzn9) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/src/lib.rs#L16)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Should a bigint to stark felt conversion be part of SN API?
</blockquote></details>

Let's leave it here, and if we see it stays for a long time we can consider moving it.
___
*[`crates/native_blockifier/src/lib.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHcDdx0jLb48D2jo2g:-NNHxJqE6ByyXDOth9FQ:b-a2zsqf) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/src/lib.rs#L35)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This already happens in the account tx execution. Do you also want it here?
</blockquote></details>

We can consider moving the check here, not now though.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHqhQNApvbDH33m6EE:-NNHqhQNApvbDH33m6EF:b5qlkvi) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L13)):*
> ```XML
>     Calldata, Fee, InvokeTransaction, TransactionHash, TransactionSignature, TransactionVersion,
> };
> ```

The utilities can be private.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHsBWRAqRClioJcg4p:-NNHsBWRAqRClioJcg4q:br3a43c) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L16)):*
> ```XML
> pub fn biguint_to_felt(biguint: BigUint) -> StarkFelt {
>     let biguint_hex = format!("{biguint:#x}");
>     StarkFelt::try_from(biguint_hex.as_str()).unwrap()
> ```

Let's use `Result`s. 
Gilad defined a `NativeBlockiferError` enum which is not yet merged; you can define it in `lib.rs`, and he'll add variants to it.



_Code quote:_
```XML
.unwrap()
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHsK6z48-Ue64zunka:-NNHsK6z48-Ue64zunkb:b27v14n) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L19)):*
> ```XML
> }
> 
> pub fn get_py_felt_attr(obj: &PyAny, attr: &str) -> PyResult<StarkFelt> {
> ```

Remove, x2.



_Code quote:_
```XML
get_
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHsZOjB-QMV8jZ9F_C:-NNHsZOjB-QMV8jZ9F_D:bfw5nlh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L24)):*
> ```XML
> 
> pub fn get_py_felt_sequence_attr(obj: &PyAny, attr: &str) -> PyResult<Vec<StarkFelt>> {
>     Ok(obj.getattr(attr)?.extract::<Vec<BigUint>>()?.into_iter().map(biguint_to_felt).collect())
> ```

Give this a name: `raw_felts`, so this line is easier to read.



_Code quote:_
```XML
obj.getattr(attr)?.extract::<Vec<BigUint>>()?
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHsvRbDzC39M2x3djP:-NNHsvRbDzC39M2x3djQ:ba3dfmt) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L27)):*
> ```XML
> }
> 
> pub fn create_invoke_function_from_python(tx: &PyAny) -> PyResult<InvokeTransaction> {
> ```

Remove.



_Suggestion:_
```XML
create_
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHx95m89BWBYAmY3KQ:-NNHx95m89BWBYAmY3KR:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L34)):*
> ```XML
>         None
>     };
>     Ok(InvokeTransaction {
> ```

Add a blank line above.



_Code quote:_
```XML
Ok(InvokeTransaction {
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHwiqiBFsOgO7h8wL_:-NNHwiqiBFsOgO7h8wLa:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L48)):*
> ```XML
> }
> 
> pub fn create_transaction_from_python(tx: &PyAny, tx_type: &str) -> PyResult<Transaction> {
> ```





_Suggestion:_
```XML
tx_from_python
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHwnDkDgbsvXntQoCU:-NNHwnDkDgbsvXntQoCV:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L51)):*
> ```XML
>     match tx_type {
>         "INVOKE_FUNCTION" => Ok(Transaction::AccountTransaction(AccountTransaction::Invoke(
>             create_invoke_function_from_python(tx)?,
> ```





_Suggestion:_
```XML
        "INVOKE_FUNCTION" => {
            let invoke_tx = AccountTransaction::Invoke(invoke_function_from_python(tx)?);
            Ok(Transaction::AccountTransaction(invoke_tx)
        }
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @alon-dotan-starkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHw0y25zepm_XeT9R7:-NNfXZnf1VpASa8YRqrc:byymhx) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we want to add a unit test?
</blockquote></details>

Tested manually for now. I'll add a test to python once we use this there.

___
___
*[`Cargo.lock` line 217 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHbAArEapdLt8-AGq6:-NNewhRI5jhicZlZlMJG:bt4ed9x) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/Cargo.lock#L217)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Weird; how is it different from the "blockifier" above?
</blockquote></details>

Just the source is different. For example, if I make changes locally to `blockifier` the above dependency will be different than this one.
___
*[`crates/native_blockifier/Cargo.toml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHb2F_1UKNzrnjm4bZ:-NNeype99yg5x3qqPHpC:bajymlc) ([raw file](https://github.com/starkware-libs/blockifier/blob/7bc7e15007340b6deef3b0bf29faebc6a7f24d88/crates/native_blockifier/Cargo.toml#L19)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's try to move to latest.
</blockquote></details>

I'm getting build errors. I'll do this in a new PR.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHsBWRAqRClioJcg4p:-NNfXiZS-lFTkLaZVaX3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L16)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's use `Result`s. 
Gilad defined a `NativeBlockiferError` enum which is not yet merged; you can define it in `lib.rs`, and he'll add variants to it.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHsK6z48-Ue64zunka:-NNezCTn4sdgREtlWIoL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L19)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove, x2.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNHsZOjB-QMV8jZ9F_C:-NNezcRE7LfS2Y93ch-r:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4a96da6ccf7f17efe193277c682b7e872c75f97f/crates/native_blockifier/src/py_transaction.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give this a name: `raw_felts`, so this line is easier to read.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @alonh5, and @giladchase)

___
*[`crates/native_blockifier/src/lib.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNgA6B74KfW5ivfzgEw:-NNgA6B74KfW5ivfzgEx:b6rhwbk) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf5a5292d8a4614c87ca294f72c2288261c72207/crates/native_blockifier/src/lib.rs#L43)):*
> ```XML
> }
> 
> impl From<NativeBlockifierError> for PyErr {
> ```

Why is this direction needed?



_Code quote:_
```XML
impl From<NativeBlockifierError> for PyErr
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNg9f8S4ZQ4qo4wmJpl:-NNg9f8S4ZQ4qo4wmJpm:b-4jfjsc) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf5a5292d8a4614c87ca294f72c2288261c72207/crates/native_blockifier/src/py_transaction.rs#L18)):*
> ```XML
> fn biguint_to_felt(biguint: BigUint) -> NativeBlockifierResult<StarkFelt> {
>     let biguint_hex = format!("{biguint:#x}");
>     Ok(StarkFelt::try_from(biguint_hex.as_str())?)
> ```

Can you move this to the line above? So that the return statement won't deal with conversions.



_Code quote:_
```XML
.as_str()
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @elintul, and @giladchase)

___
*[`crates/native_blockifier/src/lib.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNgA6B74KfW5ivfzgEw:-NNk7hknEhPjuqKd8ISs:b-6gksh5) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf5a5292d8a4614c87ca294f72c2288261c72207/crates/native_blockifier/src/lib.rs#L43)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this direction needed?
</blockquote></details>

The `#[pyfunction]` eventually needs to return a `PyResult`, so the internal `NativeBlockifierError` that may occur must be converted to a `PyErr`.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNg9f8S4ZQ4qo4wmJpl:-NNk1QgM3PctjT9V1plr:b-f9wu1k) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf5a5292d8a4614c87ca294f72c2288261c72207/crates/native_blockifier/src/py_transaction.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you move this to the line above? So that the return statement won't deal with conversions.
</blockquote></details>

I had to do it in a separate line because the output of `format!` needs to be bound to a variable, or else it's dropped.

**Review by giladchase — COMMENTED** [review]
> Reviewed 3 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @alon-dotan-starkware, @alonh5, and @elintul)

___
*[`crates/native_blockifier/src/lib.rs` line 1 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNkLQpI7GRTLXV9KCK2:-NNkLQpI7GRTLXV9KCK3:b-a88krx) ([raw file](https://github.com/starkware-libs/blockifier/blob/b16daa0f986ffc16bb65738bf26f3e6e29ab9973/crates/native_blockifier/src/lib.rs#L1)):*
> ```XML
> mod py_transaction;
> ```

Add a blank line after this line plz



_Code quote:_
```XML
mod py_transaction;
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNg9f8S4ZQ4qo4wmJpl:-NNkzIoX5l2qTRbaxOIX:b-kun3y) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf5a5292d8a4614c87ca294f72c2288261c72207/crates/native_blockifier/src/py_transaction.rs#L18)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I had to do it in a separate line because the output of `format!` needs to be bound to a variable, or else it's dropped.
</blockquote></details>

This is also possible but somewhat unpleasant. 
(BTW: for some reason we haven't been able to figure out, deref-coercion doesn't work for `From/TryFrom` conversions, so that `*` is necessary)



_Suggestion:_
```XML
    let biguint_hex = format!("{biguint:#x}");
    Ok(StarkFelt::try_from(&*biguint_hex)?)
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 16 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNl-5M24nS-gL-N6y8W:-NNl-5M24nS-gL-N6y8X:bhp98nv) ([raw file](https://github.com/starkware-libs/blockifier/blob/b16daa0f986ffc16bb65738bf26f3e6e29ab9973/crates/native_blockifier/src/py_transaction.rs#L16)):*
> ```XML
> use crate::NativeBlockifierResult;
> 
> fn biguint_to_felt(biguint: BigUint) -> NativeBlockifierResult<StarkFelt> {
> ```

do we want to add this to starknet-api as a `TryFrom`?



_Code quote:_
```XML
fn biguint_to_felt(biguint: BigUint) -> NativeBlockifierResult<StarkFelt> {
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware, @elintul, and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNg9f8S4ZQ4qo4wmJpl:-NNlLv_cERf1ETQ4xTpi:b525gju) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf5a5292d8a4614c87ca294f72c2288261c72207/crates/native_blockifier/src/py_transaction.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This is also possible but somewhat unpleasant. 
(BTW: for some reason we haven't been able to figure out, deref-coercion doesn't work for `From/TryFrom` conversions, so that `*` is necessary)
</blockquote></details>

I think it's still better, thanks.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 16 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNl-5M24nS-gL-N6y8W:-NNlM6ld7s9rw_eoAu9j:b-m61axg) ([raw file](https://github.com/starkware-libs/blockifier/blob/b16daa0f986ffc16bb65738bf26f3e6e29ab9973/crates/native_blockifier/src/py_transaction.rs#L16)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

do we want to add this to starknet-api as a `TryFrom`?
</blockquote></details>

We discussed it, and for now, we'll leave it here, and if it stays for too long, we'll move it (it should be temporary).

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @alonh5)

___
*[`crates/native_blockifier/src/lib.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNgA6B74KfW5ivfzgEw:-NNliWpSD3TrX7a8PsGc:bpfugy5) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf5a5292d8a4614c87ca294f72c2288261c72207/crates/native_blockifier/src/lib.rs#L43)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The `#[pyfunction]` eventually needs to return a `PyResult`, so the internal `NativeBlockifierError` that may occur must be converted to a `PyErr`.
</blockquote></details>

Right, thanks!
___
*[`crates/native_blockifier/src/py_transaction.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNg9f8S4ZQ4qo4wmJpl:-NNlijKeCikBsEN9TcRd:b-32mbcy) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf5a5292d8a4614c87ca294f72c2288261c72207/crates/native_blockifier/src/py_transaction.rs#L18)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think it's still better, thanks.
</blockquote></details>

You think that `&*` is better than `as_str()`? Not really sure.
Why can't `format!(...).as_str()` work?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/261)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/261#-NNg9f8S4ZQ4qo4wmJpl:-NNpHMlb67AnA1lTbBTk:b-5jrono) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf5a5292d8a4614c87ca294f72c2288261c72207/crates/native_blockifier/src/py_transaction.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You think that `&*` is better than `as_str()`? Not really sure.
Why can't `format!(...).as_str()` work? 
</blockquote></details>

It's because of the binding I explained above. Either is fine IMO; as long as it's readable and does what you expect it to do.

**Pull request merged**
