### PR TITLE
refactor(fee): moving calculate_tx_gas_usage_vector to ActualCo…

### PR DESCRIPTION
**Pull request by barak-b-starkware**
…stBuilder

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1478)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
No need to push this now into 13.1, no rush.
If you have better things to do move on to them.
Sorry if i wasn't clear on that :pray: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1478#-:-NqNphJL1WDWJhhhb0ya:bvod1g1)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Review by giladchase — COMMENTED** [review]
These are all moves right? no logic changes?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1478#-:-NqS9zYd7SSqi15pjVsG:b-nvqyd1)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Comment by barak-b-starkware** [comment]
Except for removing a TODO and changing `calculate_tx_gas_usage_vector` to `ActualCostBuilder::calculate_tx_gas_usage_vector`. (and maybe some `use` changes to match the new location but I don't remember).

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1478#-:-NqSB-Rw22k19rQ27WXV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Pull request merged**
