### PR TITLE
limit execution steps based on provided fee

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 6 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/test_utils.rs` line 342 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9MZCB7FYUXZX1XL9B:-N_9MZCB7FYUXZX1XL9C:b3lno0i) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/test_utils.rs#L342)):*
> ```XML
>         let account_tx_context = AccountTransactionContext::default();
>         let mut context =
>             EntryPointExecutionContext::new_invoke(&block_context, &account_tx_context);
> ```

redundant variable
(or does rust complain if you do it my way?)



_Suggestion:_
```XML
        let mut context =
            EntryPointExecutionContext::new_invoke(&block_context, &AccountTransactionContext::default());
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9MPaHAF5_rENCNNcr:-N_9MPaHAF5_rENCNNcs:b-gvlanb) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/execution/entry_point.rs#L155)):*
> ```XML
>     // Subtracts the given number of steps from the currently available run resources.
>     // Used for limiting the number of steps available during the execution stage, to leave enough
>     // steps available for the fee transfer stage.
> ```

function docstrings are triple-slash in rust, for some reason



_Suggestion:_
```XML
    /// Subtracts the given number of steps from the currently available run resources.
    /// Used for limiting the number of steps available during the execution stage, to leave enough
    /// steps available for the fee transfer stage.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9NB5B4plkd8KS-hOy:-N_9NB5CBZ2va2edVf83:b-ma6ybh) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L297)):*
> ```XML
>         block_context: &BlockContext,
>         resources: &ResourcesMapping,
>         is_reverted: bool,
> ```

maybe rename this to something that indicates we charge max fee in case actual fee exceeds it?
how about `cap_to_max_fee`?



_Code quote:_
```XML
is_reverted: bool,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 414 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9OAwO0ms98qb19VvA:-N_9OAwO0ms98qb19VvB:bs7hbed) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L414)):*
> ```XML
>         let validate_steps = validate_call_info.as_ref().unwrap().vm_resources.n_steps;
>         // TODO(zuphit): replace fee_steps estimation by a more concrete const/calc.
>         let fee_steps: usize = 5500;
> ```

@noaov1 WDYT?
Is there some better way to estimate this?



_Code quote:_
```XML
        // TODO(zuphit): replace fee_steps estimation by a more concrete const/calc.
        let fee_steps: usize = 5500;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 489 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9OVDaBtiZfn2mehHe:-N_9OVDaBtiZfn2mehHf:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L489)):*
> ```XML
>         let is_reverted = revert_error.is_some();
>         let (actual_fee, fee_transfer_call_info) =
>             self.charge_fee(state, block_context, &actual_resources, is_reverted)?;
> ```





_Suggestion:_
```XML
        let (actual_fee, fee_transfer_call_info) =
            self.charge_fee(state, block_context, &actual_resources, revert_error.is_some())?;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 673 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9_8Zh6qR-rTgIvxV4:-N_9_8Zh6qR-rTgIvxV5:b-op48ua) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transactions_test.rs#L673)):*
> ```XML
>     } = create_test_init_data(Fee(MAX_FEE), block_context, state);
> 
>     // Invoke the `recurse` function with depth 1 and MAX_FEE. This call should succeed.
> ```

why not use `run_recursive_function` here? twice?

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 342 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9MZCB7FYUXZX1XL9B:-N_9doQEDpLkVsdQEcOb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/test_utils.rs#L342)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

redundant variable
(or does rust complain if you do it my way?)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9MPaHAF5_rENCNNcr:-N_9e5Rz5zEvpZ0q_15N:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/execution/entry_point.rs#L155)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

function docstrings are triple-slash in rust, for some reason
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9NB5B4plkd8KS-hOy:-N_9eFj4BGX_7mXexAtw:bokwima) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L297)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe rename this to something that indicates we charge max fee in case actual fee exceeds it?
how about `cap_to_max_fee`?
</blockquote></details>

I don't think it's a good idea. 
1. You're always capped by max fee, so renaming this to `cap_to_max_fee` is somewhere between meaningless and confusing.
2. You'll lose the logical flow documented in this function that demonstrates when the actual fee can actually surpass `max_fee` and how we handle this.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 489 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9OVDaBtiZfn2mehHe:-N_9feFNCqNVSWzjTaPr:bllcg57) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L489)):*
> ```XML
>         let is_reverted = revert_error.is_some();
>         let (actual_fee, fee_transfer_call_info) =
>             self.charge_fee(state, block_context, &actual_resources, is_reverted)?;
> ```

Way less readable to save a short-lived boolean variable, I'm against.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 673 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9_8Zh6qR-rTgIvxV4:-N_9fw6R8E3VhIE4yYxf:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transactions_test.rs#L673)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not use `run_recursive_function` here? twice?
</blockquote></details>

Done

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9NB5B4plkd8KS-hOy:-N_9tccIBSG-5gHBMijV:bwuh7lw) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L297)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

I don't think it's a good idea. 
1. You're always capped by max fee, so renaming this to `cap_to_max_fee` is somewhere between meaningless and confusing.
2. You'll lose the logical flow documented in this function that demonstrates when the actual fee can actually surpass `max_fee` and how we handle this.
</blockquote></details>

1. Then `pay_max_if_needed` or `allow_lower_to_max_fee` or something. Something that indicates the logical change between what `charge_fee` does by default (enforces we don't pay too much) and the new logic (pay min(actual, max)).
2. ATM we can get actual > max without failing the execution phase, right? Misestimate the step limit? So there is a logical difference between is_reverted and pay_max_if_needed
3. charge_fee should not be aware of the *reasoning* behind taking the min(actual, max); this should be decided by calling context.

Due to (3)... maybe it would be better to call `calculate_tx_fee` in the calling context (outside of `charge_fee`, keep `charge_fee` as it was, and decide whether or not to take the minimum in the upper context? 
WDYT?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 489 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9OVDaBtiZfn2mehHe:-N_9tBheB9TclBlR52JN:b-il3l27) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L489)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Way less readable to save a short-lived boolean variable, I'm against.
</blockquote></details>

and if you rename the charge_fee input to cap_to_max or something, it will be worse. alrighty

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9NB5B4plkd8KS-hOy:-N_9w0ehAcQN_dFve7mr:be7kgok) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L297)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. Then `pay_max_if_needed` or `allow_lower_to_max_fee` or something. Something that indicates the logical change between what `charge_fee` does by default (enforces we don't pay too much) and the new logic (pay min(actual, max)).
2. ATM we can get actual > max without failing the execution phase, right? Misestimate the step limit? So there is a logical difference between is_reverted and pay_max_if_needed
3. charge_fee should not be aware of the *reasoning* behind taking the min(actual, max); this should be decided by calling context.

Due to (3)... maybe it would be better to call `calculate_tx_fee` in the calling context (outside of `charge_fee`, keep `charge_fee` as it was, and decide whether or not to take the minimum in the upper context? 
WDYT?
</blockquote></details>

ah... this is the entire logic
no point in extracting the fee calculation.
maybe `calculate_tx_fee` should accept `max_fee` as input?
in any case, due to (2) above, `is_reverted` is misleading IMO

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/transaction/account_transaction.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9NB5B4plkd8KS-hOy:-N_AaR5A9KNscKAD0j7I:b-2xhd1n) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L297)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah... this is the entire logic
no point in extracting the fee calculation.
maybe `calculate_tx_fee` should accept `max_fee` as input?
in any case, due to (2) above, `is_reverted` is misleading IMO
</blockquote></details>

Basically, we should never reach `charge_fee` with `actual > max` in non-reverted transactions (the only exception being a `deploy` situation where we want it to fail, so it's not really reverted)

If we overestimate the execution phase, then the fee-transfer phase will fail the entire tx and not charge max fee (here too it'd be failed, not reverted), which is a known behaviour until the next PR where we move the commit/abort (or alternatively, if we have an exact bound on the fee-transfer phase that'd work too).

In any case - take the actual fee (given by `calculate_tx_fee`) unless the tx is reverted, in which case then take what you can seems straightforward enough, at least for now. We could move the revert logic into `calculate_tx_fee` but maybe additional refactoring is best in a separate PR?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9NB5B4plkd8KS-hOy:-N_D8Ob3DjLOROqe4aDc:bb73djm) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L297)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Basically, we should never reach `charge_fee` with `actual > max` in non-reverted transactions (the only exception being a `deploy` situation where we want it to fail, so it's not really reverted)

If we overestimate the execution phase, then the fee-transfer phase will fail the entire tx and not charge max fee (here too it'd be failed, not reverted), which is a known behaviour until the next PR where we move the commit/abort (or alternatively, if we have an exact bound on the fee-transfer phase that'd work too).

In any case - take the actual fee (given by `calculate_tx_fee`) unless the tx is reverted, in which case then take what you can seems straightforward enough, at least for now. We could move the revert logic into `calculate_tx_fee` but maybe additional refactoring is best in a separate PR?

</blockquote></details>

SGTM

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 414 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9OAwO0ms98qb19VvA:-N_Dh-132oJhn3X_qQnh:b1rqckr) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L414)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@noaov1 WDYT?
Is there some better way to estimate this?
</blockquote></details>

This is overkill, I think. There are many resources that you don't count (DA, syscall costs, etc), so why this?

If you want, you can use those constants: https://github.com/starkware-libs/blockifier/blob/709e81aadc840e1b2e8eb5431b62fd0557b3c566/crates/blockifier/src/fee/os_resources.rs#L129

They count the overall overhead of a tx (including fee transfer and other OS things)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 378 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_DhrjO6cx4pu-HvlD2:-N_DhrjO6cx4pu-HvlD3:b-inlv2a) ([raw file](https://github.com/starkware-libs/blockifier/blob/a4649289ae2cd9cbb692b419b1b743f4553c687a/crates/blockifier/src/transaction/account_transaction.rs#L378)):*
> ```XML
>     /// Runs validation and execution.
>     // TODO(Zuphit, 15/7/2023): Move commit/abort to after fee transfer s.t. we can charge fee and
>     // revert if running out of steps during fee transfer too.
> ```

Note that the `actual_fee` includes the fee-transfer cost,
So consider checking the account balance after execute, and revert & empty the account if it has less than the actual fee.

No need to limit the fee transfer run



_Code quote:_
```XML
    // TODO(Zuphit, 15/7/2023): Move commit/abort to after fee transfer s.t. we can charge fee and
    // revert if running out of steps during fee transfer too.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 489 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_DhhTt-zC9UCo43DrM:-N_DhhTt-zC9UCo43DrN:bdvtnli) ([raw file](https://github.com/starkware-libs/blockifier/blob/a4649289ae2cd9cbb692b419b1b743f4553c687a/crates/blockifier/src/transaction/account_transaction.rs#L489)):*
> ```XML
>         )?;
>         let actual_resources =
>             calculate_tx_resources(resources, l1_gas_usage, self.tx_type(), n_reverted_steps)?;
> ```

@zuphitf not in this PR?



_Code quote:_
```XML
n_reverted_steps)?
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 414 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9OAwO0ms98qb19VvA:-N_Du2QTDFGzwpS8AOk2:b-rg5dob) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L414)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This is overkill, I think. There are many resources that you don't count (DA, syscall costs, etc), so why this?

If you want, you can use those constants: https://github.com/starkware-libs/blockifier/blob/709e81aadc840e1b2e8eb5431b62fd0557b3c566/crates/blockifier/src/fee/os_resources.rs#L129

They count the overall overhead of a tx (including fee transfer and other OS things)
</blockquote></details>

Does it not include some of the `__validate__` steps? Because if these costs do not include validate, this should be better.
If it includes `__validate__` then it's not such a good source of amount anymore; we already ran `__validate__` by the time we get here, what do we subtract?

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 414 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9OAwO0ms98qb19VvA:-N_DwA6PCyPZcVRqMnbp:b7gjie9) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L414)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Does it not include some of the `__validate__` steps? Because if these costs do not include validate, this should be better.
If it includes `__validate__` then it's not such a good source of amount anymore; we already ran `__validate__` by the time we get here, what do we subtract?
</blockquote></details>

These costs do not include `validate` and `execute` content (I don't know the code in advance)
It includes OS overhead around them (preps for the run) **and** the entire fee transfer cost (since it is known in advance)

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 414 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9OAwO0ms98qb19VvA:-N_Dk1p4BJKoahJi0NRm:bive0yu) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L414)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This is overkill, I think. There are many resources that you don't count (DA, syscall costs, etc), so why this?

If you want, you can use those constants: https://github.com/starkware-libs/blockifier/blob/709e81aadc840e1b2e8eb5431b62fd0557b3c566/crates/blockifier/src/fee/os_resources.rs#L129

They count the overall overhead of a tx (including fee transfer and other OS things)
</blockquote></details>

We only have n_steps in RunResources, so working with what we have while over-estimating it upwards to cover everything else in terms of fee/gas (this number seems to be roughly right from local debugging I did). We can go with under-estimating (~3400, like in os_resources.rs) and killing it in the fee transfer process, or if you have a better formula that converts between the cost of everything else and the cost of steps that'd be good too.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 378 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_DhrjO6cx4pu-HvlD2:-N_DlHr8-MhSNpqa03FI:bvdbrq1) ([raw file](https://github.com/starkware-libs/blockifier/blob/a4649289ae2cd9cbb692b419b1b743f4553c687a/crates/blockifier/src/transaction/account_transaction.rs#L378)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Note that the `actual_fee` includes the fee-transfer cost,
So consider checking the account balance after execute, and revert & empty the account if it has less than the actual fee.

No need to limit the fee transfer run
</blockquote></details>

Noted, but not in this PR, it's getting too big
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 489 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_DhhTt-zC9UCo43DrM:-N_Dl5Ph4IfXCbJi0sph:bqizrx5) ([raw file](https://github.com/starkware-libs/blockifier/blob/a4649289ae2cd9cbb692b419b1b743f4553c687a/crates/blockifier/src/transaction/account_transaction.rs#L489)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@zuphitf not in this PR?
</blockquote></details>

Better not mix issues. Here's a PR for it:
https://reviewable.io/reviews/starkware-libs/blockifier/744

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738#-:-N_E4k216BqZc_FDaCY1:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Comment by zuphitf** [comment]
*[`crates/blockifier/src/transaction/account_transaction.rs` line 414 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_9OAwO0ms98qb19VvA:-N_ELV-RAoG1BkjTD_FQ:begw0lt) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ca6a421365641e18497bca630906d8ab07a2ba3/crates/blockifier/src/transaction/account_transaction.rs#L414)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

We only have n_steps in RunResources, so working with what we have while over-estimating it upwards to cover everything else in terms of fee/gas (this number seems to be roughly right from local debugging I did). We can go with under-estimating (~3400, like in os_resources.rs) and killing it in the fee transfer process, or if you have a better formula that converts between the cost of everything else and the cost of steps that'd be good too.
</blockquote></details>

How about now?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738#-:-N_EV8BQEGf1kuOMvYRj:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 436 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/738#-N_EbqsmCFxbv2xjIWCz:-N_EglJV4hVoDTR3aPgM:b-gxvjb6) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed4ff870654659cca8d716795910e20f3a2770d5/crates/blockifier/src/transaction/account_transaction.rs#L436)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I know that in python, the `vm_resources` is updated by the runner. Are you sure this is needed here?
</blockquote></details>

`vm_resources` is updated here too, we want to take `validate` into consideration, so yeah

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/738#-:-N_Eoc5zBZtAy41Kq5Kk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
