### PR TITLE
fix(native_blockifier): use call_type_to_u8 and enrty_point_type_to_u…

### PR DESCRIPTION
**Pull request by OriStarkware**
…8 instead of as

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1380)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1380)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @OriStarkware)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1380#-Np-hG9n-pLqEOVFeMkY:-Np-hG9n-pLqEOVFeMkZ:bert3zx) ([raw file](https://github.com/starkware-libs/blockifier/blob/81f481923fe32c1d3dfb72aaaf91120f23bde29f/crates/native_blockifier/src/py_transaction_execution_info.rs#L90)):*
> ```XML
>     pub code_address: Option<PyFelt>,
> }
> ```

Can they appear inside an `impl`?
Please add a short docstring explaining that this replaces `FromPyObject` (the right direction) which isn't possible to use on `enum`s.

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1380)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1380#-Np-hG9n-pLqEOVFeMkY:-Np02jQy3Q7WOTJIdh1I:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/81f481923fe32c1d3dfb72aaaf91120f23bde29f/crates/native_blockifier/src/py_transaction_execution_info.rs#L90)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can they appear inside an `impl`?
Please add a short docstring explaining that this replaces `FromPyObject` (the right direction) which isn't possible to use on `enum`s.
</blockquote></details>

Done

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1380)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @OriStarkware)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1380#-Np-hG9n-pLqEOVFeMkY:-Np02npZEn0fWu9Y5cXI:bn255i9) ([raw file](https://github.com/starkware-libs/blockifier/blob/81f481923fe32c1d3dfb72aaaf91120f23bde29f/crates/native_blockifier/src/py_transaction_execution_info.rs#L90)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

I meant on the `enum`s, maybe even `Into`; is it possible?

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1380)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1380#-Np-hG9n-pLqEOVFeMkY:-Np03BUw5H1Ga3T4ijBP:b2ly8z3) ([raw file](https://github.com/starkware-libs/blockifier/blob/81f481923fe32c1d3dfb72aaaf91120f23bde29f/crates/native_blockifier/src/py_transaction_execution_info.rs#L90)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I meant on the `enum`s, maybe even `Into`; is it possible?
</blockquote></details>

The enums are defined outside of the native_blockifier and we wanted to implement those functions inside the native_blockifier

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1380)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1380)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1380#-NpDZ_CU7jZr_-ZG5QeL:-NpDZ_CU7jZr_-ZG5QeM:bugcdog) (no related file):*
I think we should merge the other PR.

___

**Review by OriStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1380)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1380#-NpDZ_CU7jZr_-ZG5QeL:-NpDu_yu8coWEWqcXSMV:b-cstnkg) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we should merge the other PR.
</blockquote></details>

I agree

___

**Pull request closed without merging**
