### PR TITLE
Use Papyrus storage in PyTransactionExecutor's state.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dorimedini-starkware, @giladchase, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPDegMz1UXAgXu13JVM:-NPDegMz1UXAgXu13JVN:b-f1v9zk) (no related file):*
I'd love some context here.

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @giladchase, and @spapinistarkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPDdlLI5fnBGMqK_D5A:-NPDdlLI5fnBGMqK_D5B:b1zqfzq) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L167)):*
> ```XML
>     pub storage_tx: papyrus_storage::StorageTxn<'this, RO>,
>     #[borrows(storage_tx)]
>     #[covariant]
> ```

so many questions...
what's self_referencing? borrows/covariant?



_Code quote:_
```XML
#[self_referencing]
pub struct PyTransactionExecutor {

    pub block_context: BlockContext,
    pub storage_reader: papyrus_storage::StorageReader,
    #[borrows(storage_reader)]
    #[covariant]
    pub storage_tx: papyrus_storage::StorageTxn<'this, RO>,
    #[borrows(storage_tx)]
    #[covariant]
    pub state: CachedState<PapyrusStateReader<'this, RO>>,
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPDe_yP8MhwAkEQa9le:-NPDe_yP8MhwAkEQa9lf:b-kc9g4l) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L213)):*
> ```XML
>         }
> 
>         Ok(PyTransactionExecutorBuilder {
> ```

what's this? where is it imported from?



_Code quote:_
```XML
PyTransactionExecutorBuilder
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPDegMz1UXAgXu13JVM:-NPDewjP4idW4O9pwtOy:b5kc26m) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'd love some context here.
</blockquote></details>

Of course. Let's talk about it after the sync tomorrow, I added it to the schedule. @dorimedini-starkware @giladchase 

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 11 unresolved discussions (waiting on @alonh5, @giladchase, and @spapinistarkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLNzPJD5RKhjSAv7x-:-NPLNzPJD5RKhjSAv7x0:b-4886e9) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L13)):*
> ```XML
> use blockifier::transaction::transaction_execution::Transaction;
> use num_bigint::BigUint;
> use ouroboros::self_referencing;
> ```

I'd like to use the whole module if it's not too long.



_Code quote:_
```XML
use ouroboros::self_referencing;
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOBBMEwxMKvnggyu2:-NPLOBBMEwxMKvnggyu3:b-zh7rks) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L15)):*
> ```XML
> use ouroboros::self_referencing;
> use papyrus_storage::db::RO;
> use papyrus_storage::state::StateStorageReader;
> ```

Where is this used? Or is it a trait?



_Code quote:_
```XML
use papyrus_storage::state::StateStorageReader;
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLMcMn6MaF-ShpNmWk:-NPLMcMn6MaF-ShpNmWl:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L162)):*
> ```XML
> pub struct PyTransactionExecutor {
>     pub block_context: BlockContext,
>     pub storage_reader: papyrus_storage::StorageReader,
> ```





_Suggestion:_
```XML
    pub block_context: BlockContext,
    
    // State-related fields.
    // Reader and storage transaction are kept merely for lifetime parameter referencing.  
    pub storage_reader: papyrus_storage::StorageReader,
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLN9PP0pWFwOtrsX_4:-NPLN9PP0pWFwOtrsX_5:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L176)):*
> ```XML
>     #[args(general_config, block_info)]
>     pub fn create(general_config: &PyAny, block_info: &PyAny) -> NativeBlockifierResult<Self> {
>         let starknet_os_config = general_config.getattr("starknet_os_config")?;
> ```





_Suggestion:_
```XML
// Build block context.
let starknet_os_config = general_config.getattr("starknet_os_config")?;
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLNJ4R9GB_RUgc03w2:-NPLNJ4R9GB_RUgc03w3:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L195)):*
> ```XML
> 
>         // TODO: Use actual (not test) Papyrus storage as state reader.
>         let (storage_reader, mut _storage_writer) = papyrus_storage::test_utils::get_test_storage();
> ```





_Suggestion:_
```XML
        // build Papyrus reader-based state.
        // TODO: Use actual (not test) Papyrus storage as state reader.
        let (storage_reader, mut _storage_writer) = papyrus_storage::test_utils::get_test_storage();
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOFxH7q4zKGl5ZG3R:-NPLOFxH7q4zKGl5ZG3S:b-ikrp30) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L196)):*
> ```XML
>         // TODO: Use actual (not test) Papyrus storage as state reader.
>         let (storage_reader, mut _storage_writer) = papyrus_storage::test_utils::get_test_storage();
> ```

Is there an alternative to the `unwrap`s?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLNSRb5RLglg8_Qnmc:-NPLNSRb5RLglg8_Qnmd:bjmok8i) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L197)):*
> ```XML
>         let (storage_reader, mut _storage_writer) = papyrus_storage::test_utils::get_test_storage();
> 
>         fn storage_tx_builder(
> ```

Can you explicitly add lifetime to `storage_tx_builder`'s definition? I think it'll be clearer.



_Suggestion:_
```XML
        // The following callbacks are required to capture the local lifetime parameter.
        fn storage_tx_builder(
            storage_reader: &papyrus_storage::StorageReader,
        ) -> papyrus_storage::StorageTxn<'_, RO> {
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOSOTEUslwfb_RKY4:-NPLOSOTEUslwfb_RKY5:b-ak36ec) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L208)):*
> ```XML
>             let state_reader = storage_tx.get_state_reader().unwrap();
> 
>             let block_number = BlockNumber::default();
> ```

Remove blank line above.
Take the block number from block context.



_Code quote:_
```XML
let block_number = BlockNumber::default();
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOYHtDdmx-QdYhJvc:-NPLOYHtDdmx-QdYhJvd:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L215)):*
> ```XML
>         Ok(PyTransactionExecutorBuilder {
>             block_context,
>             storage_reader,
> ```





_Suggestion:_
```XML
        // The builder struct below is implicitly created by `ouroboros`.
        py_tx_executor_builder = PyTransactionExecutorBuilder {
            block_context,
            storage_reader,
            storage_tx_builder,
            state_builder,
        }
        Ok(py_tx_executor_builder.build())
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOwSB3dikHU8bhlv5:-NPLOwSB3dikHU8bhlv6:b-l1empu) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L221)):*
> ```XML
>         .build())
>     }
> ```

Can you explain the following changes?
If accessing fields is done differently, please shortly mention that above `#[self_referencing] PyTransactionExecutor`.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @giladchase, and @spapinistarkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOBBMEwxMKvnggyu2:-NPMsy7_5w9QE82FLMj3:bfjs0vb) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L15)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where is this used? Or is it a trait?
</blockquote></details>

It's a trait which has `get_state_reader` used by `storage_tx`, so it has to be in the scope.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLMcMn6MaF-ShpNmWk:-NPMtSrE5lNnebsbNJ-N:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L162)):*
> ```XML
> pub struct PyTransactionExecutor {
>     pub block_context: BlockContext,
>     pub storage_reader: papyrus_storage::StorageReader,
> ```

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOFxH7q4zKGl5ZG3R:-NPN8HC4Br2gsbcFJQUi:bxyygyb) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L196)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there an alternative to the `unwrap`s?
</blockquote></details>

The builders can't return a `Result`. I added a message with expect.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLNSRb5RLglg8_Qnmc:-NPMtssU2O-_n4P4ZoAt:byo8wnu) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L197)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explicitly add lifetime to `storage_tx_builder`'s definition? I think it'll be clearer.
</blockquote></details>

Added the comment.

An explicit lifetime cannot be added here, because we don't want there to be an external lifetime in the struct. The reason the second callback has one is that it's using the lifetime of the first one which is in the struct.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOSOTEUslwfb_RKY4:-NPN1-I_DKjkFGVbMTKh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L208)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove blank line above.
Take the block number from block context.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOwSB3dikHU8bhlv5:-NPN2vGz1d5rHMO_eiEt:b-7trd1s) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L221)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain the following changes?
If accessing fields is done differently, please shortly mention that above `#[self_referencing] PyTransactionExecutor`.
</blockquote></details>

Sure. To access fields you need to call `borrow_{field_name}()`. To borrow the fields as mutable you have to use `self.with_mut` to get the fields as mut. It expects a closure or function that gets the mutable object as input.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, @giladchase, and @spapinistarkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOFxH7q4zKGl5ZG3R:-NPNGIsJ-c1q7gUl0Jkm:bsjk7e7) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L196)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The builders can't return a `Result`. I added a message with expect.
</blockquote></details>

What will happen in Python if this initialization fails?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @giladchase, and @spapinistarkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOFxH7q4zKGl5ZG3R:-NPNHdw_Dcp7VGxNVw1k:b1f5rvh) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L196)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What will happen in Python if this initialization fails?
</blockquote></details>

I'm not sure, let me check.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 8 unresolved discussions (waiting on @alonh5, @elintul, @giladchase, and @spapinistarkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPNMUim2FcMBs3fplS7:-NPNMUinCYslrHbbccMt:bda25h1) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4bcaee5e7b1ea4e1e335141a828f75d09b5ea97/crates/native_blockifier/src/py_transaction.rs#L183)):*
> ```XML
>         // Build block context.
>         let starknet_os_config = general_config.getattr("starknet_os_config")?;
>         let block_number = BlockNumber(py_attr(block_info, "block_number")?);
> ```

why not keep this inline?



_Code quote:_
```XML
let block_number = BlockNumber(py_attr(block_info, "block_number")?);
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPNMkKd06q_TkONQutn:-NPNMkKd06q_TkONQuto:b-9x4sl9) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4bcaee5e7b1ea4e1e335141a828f75d09b5ea97/crates/native_blockifier/src/py_transaction.rs#L229)):*
> ```XML
>             storage_reader,
>             storage_tx_builder,
>             state_builder: |storage_tx| state_builder(storage_tx, block_number),
> ```

is this legal?
the value of `block_number` is cloned/copied/something the moment this lambda function is constructed?



_Code quote:_
```XML
state_builder: |storage_tx| state_builder(storage_tx, block_number)
```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @spapinistarkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPNMkKd06q_TkONQutn:-NPNUsvZ7urwljx311oa:bn2lgyl) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4bcaee5e7b1ea4e1e335141a828f75d09b5ea97/crates/native_blockifier/src/py_transaction.rs#L229)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What do you mean by legal? I'm not sure exactly how it works, but the compiler seems to be happy.
</blockquote></details>

I'm afraid of something like
```
x = 7
tmp_func = lambda: print(x)
x = 8
tmp_func()  # Prints 8 instead of 7
```
but lifetimes are managed well in rust so if the compiler likes then I like

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @spapinistarkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPNMkKd06q_TkONQutn:-NPNWB7J2jmjfZkjMhUt:b-intfa) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4bcaee5e7b1ea4e1e335141a828f75d09b5ea97/crates/native_blockifier/src/py_transaction.rs#L229)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I'm afraid of something like
```
x = 7
tmp_func = lambda: print(x)
x = 8
tmp_func()  # Prints 8 instead of 7
```
but lifetimes are managed well in rust so if the compiler likes then I like
</blockquote></details>

Oh, I see. Anyway, this won't happen because the block number shouldn't change during the `PyTransactionExectuter`'s lifetime (it is recreated for every block).

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOFxH7q4zKGl5ZG3R:-NPNbJvT-Ah7FdGji4Zi:b37nlse) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L196)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I'm not sure, let me check.
</blockquote></details>

I dont like unwraps either. There is an alternative: The member itself becomes Result.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOFxH7q4zKGl5ZG3R:-NPNcSUJ9xBh9_0wYKPd:b-fxaaub) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L196)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>


Even better
</blockquote></details>

https://docs.rs/ouroboros/latest/ouroboros/attr.self_referencing.html#mystructtry_newefields---resultmystruct-e

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLNSRb5RLglg8_Qnmc:-NPNo6Q55Y-fEvMrhRHA:b-ucfknh) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L197)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Added the comment.

An explicit lifetime cannot be added here, because we don't want there to be an external lifetime in the struct. The reason the second callback has one is that it's using the lifetime of the first one which is in the struct.
</blockquote></details>

Thanks!
___
*[`crates/native_blockifier/src/py_transaction.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPNnboA7E4WIUIJWPpx:-NPNnboA7E4WIUIJWPpy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4bcaee5e7b1ea4e1e335141a828f75d09b5ea97/crates/native_blockifier/src/py_transaction.rs#L159)):*
> ```XML
> 
> #[pyclass]
> // To access a field you must use `self.borrow_{field_name}()`. Alternately, you can borrow the
> ```





_Suggestion:_
```XML
// To access a field you must use `self.borrow_{field_name}()`. 
// Alternately, you can borrow the whole object using `self.with[_mut]()`.
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPNoUdr4js4viySlzFe:-NPNoUdr4js4viySlzFf:b-dcfutx) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4bcaee5e7b1ea4e1e335141a828f75d09b5ea97/crates/native_blockifier/src/py_transaction.rs#L243)):*
> ```XML
>         let tx: Transaction = py_tx(&tx_type, tx, raw_contract_class)?;
>         let tx_execution_info = self.with_mut(|fields| {
>             tx.execute(fields.state, fields.block_context).map_err(NativeBlockifierError::from)
> ```

This shouldn't be `mut`able, perhaps extract them separately?



_Code quote:_
```XML
fields.block_context
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @giladchase)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOFxH7q4zKGl5ZG3R:-NPRSX9t8aacee9eeYOj:b9lgu0w) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L196)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

https://docs.rs/ouroboros/latest/ouroboros/attr.self_referencing.html#mystructtry_newefields---resultmystruct-e
</blockquote></details>

Very nice! Reading the docs all the way pays off, I'll do it next time.
Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPNoUdr4js4viySlzFe:-NPRORot087oDURvCrUl:bwldmvr) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4bcaee5e7b1ea4e1e335141a828f75d09b5ea97/crates/native_blockifier/src/py_transaction.rs#L243)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This shouldn't be `mut`able, perhaps extract them separately?
</blockquote></details>

I tried but couldn't borrow a field immutably while also borrowing the struct mutably. And it's not possible to borrow only one field mutably (From docs: There is no borrow_FIELD_mut, unfortunately, as Rust’s borrow checker is currently not capable of ensuring that such a method would be used safely.)
Anyhow, because `execute` doesn't declare `block_context` as mutable, it can't be changed in the function.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @giladchase, and @spapinistarkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOFxH7q4zKGl5ZG3R:-NPRwAPH6ZwhA3t-krNc:b-6hgtal) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L196)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Very nice! Reading the docs all the way pays off, I'll do it next time.
Done.

</blockquote></details>

Do we need to add variants to `NativeBlockifierError`?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPNnboA7E4WIUIJWPpx:-NPRvfK1EeCMy0AGS5wf:b-tn3llh) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4bcaee5e7b1ea4e1e335141a828f75d09b5ea97/crates/native_blockifier/src/py_transaction.rs#L159)):*
> ```XML
> 
> #[pyclass]
> // To access a field you must use `self.borrow_{field_name}()`. Alternately, you can borrow the
> ```

Remove weird character in the end of the two doc. lines (it was added by Reviewable somehow).
___
*[`crates/native_blockifier/src/py_transaction.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPNoUdr4js4viySlzFe:-NPRw4Bs--nbo7x1bKyp:b-ucfkn4) ([raw file](https://github.com/starkware-libs/blockifier/blob/c4bcaee5e7b1ea4e1e335141a828f75d09b5ea97/crates/native_blockifier/src/py_transaction.rs#L243)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I tried but couldn't borrow a field immutably while also borrowing the struct mutably. And it's not possible to borrow only one field mutably (From docs: There is no borrow_FIELD_mut, unfortunately, as Rust’s borrow checker is currently not capable of ensuring that such a method would be used safely.)
Anyhow, because `execute` doesn't declare `block_context` as mutable, it can't be changed in the function.
</blockquote></details>

Thanks.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/305#-NPLOFxH7q4zKGl5ZG3R:-NPRzPWBDPmmOJHS6TcE:b9vxskd) ([raw file](https://github.com/starkware-libs/blockifier/blob/de4619c6a0f62c3277c2a66307de333de317b6d6/crates/native_blockifier/src/py_transaction.rs#L196)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we need to add variants to `NativeBlockifierError`?
</blockquote></details>

Nope, `StorageError(#[from] papyrus_storage::StorageError)` has already been added by Gilad.

**Review by elintul — APPROVED** [review]
:lgtm:

Next PR: pass path and max size, to initialize real reader?

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305#-:-NPS5f_m7dNaHAGbUavY:bklvz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by alonh5 — COMMENTED** [review]
Yes :)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/305#-:-NPS8gkT14GvruvdqwFY:b-x0paxf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
